### ISSUE TITLE
Make it really semantic

### ISSUE THREAD

**Issue by jensgro** [Semantic-Org/Semantic-UI#1]
Please rework the whole codebase, especially the examples, to make the project semantic, as it states itself to be.

Where is the semantic in styling a DIV as a button? Use the BUTTON-element instead. It has a special purpose and meaning. And purpose and meaning are what drives semantics. Not the naming of a class.

**Comment by jjdd12** [comment]
+1

**Comment by w96k** [comment]
This issue was moved to w96k/Semantic-UI-Plus#3
