### ISSUE TITLE
Changing duration setting issue

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#1004]
In my code, I was trying to change the setting of the sidebar.

$('ui right wide sidebar').sidebar('setting','duration',1000);

When I console log it out, it states that the duration is what I set it to but nothing changes and the animation is the exact same.

Forgive me if this is not a bug and I'm doing it wrong.

**Comment by cspeer** [comment]
Hi,

do you mind taking a look?
http://jsfiddle.net/wwhrups5

Thanks,
Chris

**Comment by TylerPflueger** [comment]
Sorry, I completely forgot to check my emails on this one. Thanks to @cspeer for displaying an example.

**Comment by jlukic** [comment]
> Duration of sidebar animation when using legacy javascript animation 
settings.duration only affects legacy sidebar animations (Which use javascript). That feature was never added for standard css animations.  

You can however do it simply enough in css

```css
.my.sidebar {
  transition-duration: 5s;
}
```

**Comment by cspeer** [comment]
Oops, looks like I missed that part.
Thanks a lot @jlukic
