### ISSUE TITLE
[Form Validation] Add separate property for passing validation parameters

### ISSUE THREAD

**Issue by coreyfarrell** [Semantic-Org/Semantic-UI#1006]
The current method of declaring validation parameters as text within [] is very limiting.  It works good enough for the built-in validators, but that is due to them being simple.  Example:

`rules: [{ type: 'contains[somevalue]', prompt: 'Field must contain somevalue.' }]`

I believe it would be better if this rule could be written as:
`rules: [{ type: 'contains', parameter: 'somevalue', prompt: 'Field must contain somevalue.' }]`

I have no idea how you would check for contains: "[somevalue]" where you actually expect the brackets to be part of the value.  This becomes more useful when you consider that custom validators could use any JS object for the parameter.

`rules: [{ type: 'regex', parameter: /\d{10}/, prompt: 'Field must be a 10 digit phone number' }]`
The 'regex' validator would expect parameter to be a precompiled regular expression.  I have a regex validator on my own app, unfortunately this requires escaping (ex type: 'regex[\d+]'), and regular expressions are cryptic enough without additional escaping.

`rules: [{ type: 'ifradio', parameter: { radiofield: 'radioname', radiovalue: 'pin', pattern: /.+/ }, 'PIN must be non-blank' }]`
This custom validator 'ifradio' would be attached to an input text field that must be non-blank if `$('[name=radioname]').val() == 'pin'`.  Most likely radioname would be declared as a field that must not be empty.  Allowing structured validation parameters such as this is the primary motivation for this request.

I realiize this may require some API breakage, but I think it's well worth it.  If '[' were never allowed to be part of the validator name, current rule definitions (like `type: 'contains[somevalue]'`) could be supported.  On the other hand since Semantic-UI is currently 0.x, it might be better to just make this a breaking change, require use of a separate parameter field starting with 1.0.

**Comment by leomar-developer** [comment]
Hi guys,

Does anyone know if any work has been done in this matter as of today? I would like to know if there are any means to pass parameters to a custom validation function, I declared a custom validation function using `$.fn.form.settings.rules` but I would like to pass in a parameter that is a value from another JS object available on the application.

Thanks in advance

**Comment by jlukic** [comment]
You can pass in simple strings using bracket notation.

**Comment by leomar-developer** [comment]
Thanks jlukic, that works just fine for a limited set of use cases but in my use case I can't just pass a simple string, I need to pass a reference to another JavaScript object, in the meantime I solved it using jQuery data method to store the reference and retrieve it later from the validation rule code.

Thanks anyway buddy
