### ISSUE TITLE
Dropdown's value not being submitted on 'form' submission

### ISSUE THREAD

**Issue by dekhaus** [Semantic-Org/Semantic-UI#1008]
Hi

I'm using Semantic-UI with an Ember (ember-cli) application and am having trouble getting a dropdown-select's value to 'post' when a form is submitted.

I've wrapped the dropdown widget in an Ember component and from a visual/functional perspective the dropdown works.  I know that architecturally everything is setup correctly because other inputs (aka text) which also use semantic-ui are functioning properly - i.e. their values are properly being 'posted' on form submission.

Just in case its requested - here's the Ember component code.  First the source (coffeescript) for the component ...

``` coffeescript
`import Ember from 'ember'`
SemanticDropdownSelectComponent = Ember.Component.extend(
  items: (->
    @get("menuItems").split ","
  ).property("menuItems")
  didInsertElement: -> @$().find('.ui.selection.dropdown').dropdown()
)
`export default SemanticDropdownSelectComponent`
```

next the components template ...

``` coffeescript
<label>{{label}}</label>
<div class="ui fluid selection dropdown">
  <div class="text">{{prompt}}</div>
  <i class="dropdown icon"></i>
  {{input type='hidden' name='state' value=fields.state}}
  <div class="menu">
    {{#each items}}
      <div class="item" data-value="{{downcase this}}">{{this}}</div>
    {{/each}}
  </div>
</div>
```

Finally - how the component is 'called'/'used' ...

``` coffeescript
<div class="ui error form segment">
  <div class="field">
    {{#semantic-dropdown-select label='State:' name='state' prompt='Select a state' menuItems='draft,active,inactive,archived'}}
    {{/semantic-dropdown-select}}
  </div>    
  <div class="field">
    <label>Comment:</label>
    <div class="ui labeled input">
      {{input type='text' value=fields.comment placeholder='Comment'}}
    </div>
  </div>
  ...
  <div class="ui right attached blue submit button" {{action 'create'}}>Create</div>
</div>
```

The specific problem I'm having and the reason for this post is to try and figure out how I need to structure the semantic-dropdown-select html so that when the form is submitted the dropdown-select's value is properly submitted. When the form is submitted - I can see via console.log debug statements that a value for the 'comment' (fields.comment) is present. However - no value for 'state' (fields.state) is present.

In this initial implementation - I 'hard-coded' the 'value' of the select's input to be fields.state. Eventually - this setting would be generic just like all the other information passed into the components template.

So - in summary, I need some help figuring out why my dropdown-select components value is not being posted when I submit my form.

Thanks

**Comment by slawkens** [comment]
Got the same problem. Dropdown is not being submitted. php $_REQUEST variable is empty.

Here my code (save it as post.php):
```
<head>
	<!-- jQuery -->
	<script
			src="https://code.jquery.com/jquery-3.3.1.min.js"
			integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			crossorigin="anonymous"></script>

	<!-- Semantic UI -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css"  />
</head>
<body>
<?php echo var_dump($_REQUEST); ?>
<form class="ui large form" action="post.php" method="post">
	<div class="one field">
		<label for="profession">Profession</label>
		<select name="profession" class="ui search dropdown" id="profession"></select>
	</div>
	<button type="submit" class="ui fluid large teal submit button">Submit</button>
</form>

<script>
    $(function() {
        var professions = [{"name":"Altenpflegehelfer","value":"3"},{"name":"Altenpfleger","value":"4"},{"name":"Änderungsschneider","value":"2"},{"name":"Anlagenmechaniker","value":"5"},{"name":"Anlagenmechaniker für Sanitär-, Heizungs- und Klimatechnik (früher: Zentralheizungs- und Lüftungsbauer)","value":"6"},{"name":"Asphaltbauer","value":"7"}];

        $('#profession').dropdown({
            values: professions,
            fullTextSearch: true,
        });

    });
</script>
</body>
```
