### ISSUE TITLE
[Menu] Add Tabular Variations For All Directions

### ISSUE THREAD

**Issue by mohamedzw** [Semantic-Org/Semantic-UI#1032]
Hi,

Would it be possible to have stacked/vertical tabs?

Any help would be appreciated.

**Comment by jlukic** [comment]
I've added top and left, in my books these are the only sensible positions w/r/t user experience.

**Comment by jlukic** [comment]
I've added `right

**Comment by jlukic** [comment]
I've added `right tabular` and  `bottom tabular` menus in next release.
