### ISSUE TITLE
[accordion] does not work with meteor blaze and/or dynamic content

### ISSUE THREAD

**Issue by Sivli-Embir** [Semantic-Org/Semantic-UI#1041]
I am using Meteor JS to dynamically add title/content (pairs) based on a search filter. Basically it starts as a full accordion with a large number of pairs. Then I remove the inner content of the accordion and refill it with a smaller, or larger, number of pairs. I believe it does not actually remove all the elements from the DOM but rather move them around. 

By doing this I end up with randomly non responsive pairs that do not switch to active. I say random but I believe its when I end up with pairs that were in the middle at the top. Possibly an issue with indexing?

Regardless is there an easy fix or a way to tell the accordion to recompute?

**Comment by Vrakfall** [comment]
I love you man!

I was looking for at least one hour and a half why it didn't work and this post saved me probably many more hours!

Why isn't this more obvious in the docs? D:
