### ISSUE TITLE
Attaching button to Sidebar

### ISSUE THREAD

**Issue by dipamchang** [Semantic-Org/Semantic-UI#1043]
Hello,
I am new to developing UI, was using semantic-ui for my current project.
For the same i want to use the sidebar, like that on the http://semantic-ui.com with a button attached.

As of now I have created two separate things, a button and a side bar and sidebar toggle on button click. But i want to stick this button on the sidebar as the semantic-ui website.
Below is my code.
**HTML :**

``` html
<div id="btn" class="ui black huge launch right attached button" style="display:absolute;left:0px;width:70px;">
            <i class="icon list layout"></i>
        <span class="text" style="display:none;">Feedback</span>
</div>

<div id="feed" class="ui styled sidebar ">
  <h3 class="ui header">Your Suggestions</h3>
  <div class="ui form">
    <div class="field">
      <label>Name</label>
      <div class="ui icon input">
        <i class="user icon"></i>
        <input data-placeholder="Name" type="text">
      </div>
    </div>
    <div class="field">
      <label>Message</label>
      <textarea></textarea>
    </div>
    <div class="ui black fluid button">Submit</div>
  </div>
</div>
```

**Javascript :**

``` javascript
$(".launch.button").mouseenter(function(){
        $(this).stop().animate({width: '215px'}, 300, 
             function(){$(this).find('.text').show();});
    }).mouseleave(function (event){
        $(this).find('.text').hide();
        $(this).stop().animate({width: '70px'}, 300);
    });
$("#feed").sidebar({overlay: true})
                .sidebar('attach events','.ui.launch.button');
```

**Comment by chaconnewu** [comment]
@jlukic The example no longer works. Could you please check? Thanks!

**Comment by jlukic** [comment]
Here's an updated fiddle @chaconnewu 
http://jsfiddle.net/hwc9sLb9/

**Comment by chaconnewu** [comment]
Thank you, Jack! It looks really nice.

**Comment by dstroyrofworlds** [comment]
How can I get this to work on a sidebar on the right ?
The button must attach to the right and move with the sidebar.

**Comment by msalman86** [comment]
@dstroyrofworlds updated fiddle http://jsfiddle.net/hwc9sLb9/

**Comment by chethan1095** [comment]
@msalman86 inside this  http://jsfiddle.net/hwc9sLb9/ if i click on home one more sidebar should open can u help me with this
