### ISSUE TITLE
Modal responsive issue (not scrolling down)

### ISSUE THREAD

**Issue by AmirolAhmad** [Semantic-Org/Semantic-UI#105]
When run the code of your modal (http://semantic-ui.com/modules/modal.html) and resize the browser screen (checking on responsive), the modal are not scrolling down as wanted.
![screen shot 2013-09-29 at 4 39 57 am](https://f.cloud.github.com/assets/1130863/1231964/750c20b4-287e-11e3-8fd3-0f739cd7bb73.png)

**Comment by anil1712** [comment]
Yes, getting the same issue. Is anyone got solution for the same?
