### ISSUE TITLE
[UI] Tour / Guide

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#1053]
It could be very nice to have an onboarding module.
Or perhaps just a theme this one or another ?
https://github.com/usablica/intro.js /  http://usablica.github.io/intro.js/

or this one : http://github.hubspot.com/shepherd/docs/welcome/

**Comment by yuriolive** [comment]
+1

**Comment by mariusWeceipt** [comment]
I tweaked Intro.js plugin to work with Semantic UI. Have a look at : https://github.com/mariusWeceipt/intro.js

Initialization, step and hint definition works the same as "classic" intro.js : https://github.com/usablica/intro.js

Added an option to change elements color. Just use `introJs().setOption({ 'customColor' : 'teal' })`. Default color is Semantic UI's teal, but you can use any color class name (teal, pink, positive, primary, etc...).
