### ISSUE TITLE
[BETA] Unwanted/Incorrect list bullets appearing in .ui.list with icons.

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#1070]
Consider a UI List as follows:

``` html
<ul class="ui list">
     <li class="item">
         <i class="icon fa-cog"></i>
         Test
     </li>
</ul>
```

This should just display a UI List without the bullets. But no, doesn't work. There are unwanted bullets being displayed as shown below:

![screen shot 2014-09-08 at 4 00 31 pm](https://cloud.githubusercontent.com/assets/5097028/4184198/a5345752-3746-11e4-9365-cec823febb8f.png)
### Solution:

Looking at the source code, seems like there is a pseudo element being inserted into the li element. For now, I just set it to `display:none`.
###### SCSS:

``` scss
ul.ui.list{
  li.item:before{
     display: none !important;
  }
}
```

**Please note:** This issue affects only Unordered lists - When using an UL list tag which has LI as its children.

**Comment by dmitriid** [comment]
I'm sorry to comment on a very old closed topic, but I feel that I disagree with the following statement:

> No machine or person will gain special knowledge of your content if you use a ul. 

This is actually not true for components that have defined meaning esp. for screen readers

- lists
- dividers
- headers
- dropdowns (not just screen readers, but also mobile devices)

etc.


From HTML5 spec

[Semantics](https://html.spec.whatwg.org/#semantics-2)

> Authors must not use elements, attributes, or attribute values for purposes other than their appropriate intended semantic purpose, as doing so prevents software from correctly processing the page.

[The div element](https://html.spec.whatwg.org/#semantics-2)

> Authors are strongly encouraged to view the div element as an element of last resort, for when no other element is suitable. Use of more appropriate elements instead of the div element leads to better accessibility for readers and easier maintainability for authors.

Unfortunately, even for the elements with clear semantics SemanticUI pushes divs as the primary/only way of doing things.

I wonder if this discussion could be re-opened?

**Comment by corelaio** [comment]
Partially off topic here but in case someone lands on this page by searching for a solution to the problem of strange special characters appearing instead of list bullet points:
- When combining html5 ul and li tags together with corresponding semantic-ui classes, make sure to force utf8 for your requests. This solved the problem for me.
