### ISSUE TITLE
Gulp - Add Official NuGet Package

### ISSUE THREAD

**Issue by vjacheslavravdin** [Semantic-Org/Semantic-UI#11]
It would be great if you'll make your project available in Nuget.

Thanks in advance!

**Comment by laimonas** [comment]
Can you pls update this:
http://www.nuget.org/packages/SemanticUI/
to latest. Tnx.

**Comment by jlukic** [comment]
There could be a way to automate it. That's an unnoficial package, so community member manages the NuGet package. I'm not sure his e-mail or who he is. 

There could be a way to automate it with our release, but theres __a lot__ that needs fixing there too.
https://www.npmjs.com/package/gulp-nuget

I'll see if I can work it in..

**Comment by kawazoe** [comment]
+1 I would love seeing an official nuget package for this project
