### ISSUE TITLE
Re-init dropdown after adding new menu item

### ISSUE THREAD

**Issue by peterfyj** [Semantic-Org/Semantic-UI#1117]
I have a `.dropdown` that contains a `.menu`, and a handler is assigned to its `onChange` callback.

Now I use javascript to add a new `.menu .item` to the dropdown list, and I noticed that I have to reinitialize the dropdown with `$('.ui.dropdown').dropdown()` to get it back to work.

The problem is that once the dropdown is reinitialized, any previous settings such as callbacks are lost. Am I doing it wrong, or it is by design that I have to reassign the callback?

**Comment by TimMcCauley** [comment]
Doesn't work for me either, I can't refresh my dropdown menu after adding additional options to it.

**Comment by jlukic** [comment]
Everything seems fine to me. Check this example
http://jsfiddle.net/9j3uxczv/

You can see the debug from mutation observers when the button adds new content to a subtree.

**Comment by TimMcCauley** [comment]
Oh crap, thanks Jack. I was adding

<option>...</option>, I wasn't aware that I have to add the <div class="item">..

Thanks a bunch for clarifying, great help.

**Comment by gottlike** [comment]
@jlukic , could you please reopen this issue? I am populating a dropdown menu after the page has loaded, using the HTML structure that Tim described above. Everything works fine in Chrome and FF, but in IE10 it's broken. Also, when opening the JSFiddle you linked to in IE10, the dropdown will not open at all.

**Comment by jlukic** [comment]
This works with MutationObservers which are not supported in IE10
http://caniuse.com/#feat=mutationobserver

**Comment by gottlike** [comment]
I see.. thanks!
