### ISSUE TITLE
Perfect round icons please :)

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#1141]
I love the simplicity and ease of use with the current implementation of icons. But, if there's one thing that bothers me, it's the distorted semi-oval semi-round shapes when using `circular` icons. I'm not a perfectionist by any means, but I just like to fix something if I know for sure there's a fix. And so, I had a couple of extra hours today, to work on Semantic, so I got this annoying little (possible) bug fixed (hopefully) :)

Consider an array of round icons as below:

**HTML:**

``` html
<div class="ui center aligned segment">
              <div class="ui header medium">Share on Social Media</div>
              <div class="ui circular inverted facebook icon button">
                <i class="icon fa-facebook"></i>
              </div>
              <div class="ui circular inverted twitter icon button">
                <i class="icon fa-twitter"></i>
              </div>
              <div class="ui circular inverted linkedin icon button">
                <i class="icon fa-linkedin"></i>
              </div>
              <div class="ui circular inverted google plus icon button">
                <i class="icon fa-google-plus"></i>
              </div>
</div>
```

**Demo fiddle:**
http://jsfiddle.net/dsgnr/yddfwnsp/2/

![screen shot 2014-10-03 at 15 56 54](https://cloud.githubusercontent.com/assets/5097028/4504570/d9c0d87e-4ae7-11e4-9509-457d3b513a7a.png)

But, all of us (secretly :P) want something like this:

![screen shot 2014-10-03 at 15 57 02](https://cloud.githubusercontent.com/assets/5097028/4504595/4fdfd7bc-4ae8-11e4-945a-5f227653fe87.png)

After struggling for almost an hour, I was able to determine a (somewhat) proper fix:

For the parent container, which is the `.ui.button` in this case:

1) Add `border-radius: 50%;` (It doesn't matter actually, since it currently it inherits `10em`)
2) Turn off the padding `padding: 0em;` (This is needed to center the child element: `<i>`)
3) Assign a max-height and max-width. (In my example, I've used `2.6rem`, but any value should be fine. Vary max-height/width according to the size classes like `tiny`, `small`, `large`, etc.)

For the child container, which is the `<i>` element in this case:

``` css
    height: auto; /* Needed for centering */
    width: auto;  /* Needed for centering */
    padding: 50%  /* Needed for positioning */
    margin: -3em -50%;  /* Needed for positioning */
    position: relative;  /* Needed for positioning */
    top: 1.5em;  /* Needed for positioning */
    border: 1em solid transparent;   /* Needed for positioning */
    white-space: nowrap;   /* Needed for avoiding ovular distortion */
```

**Demo fiddle:**
http://jsfiddle.net/dsgnr/yddfwnsp/11/

**Reference:**
http://stackoverflow.com/a/9983580/381150

**Note:** Please ignore the `fa-` prefix, it's just how I use the font-awesome Icons in the demo (and also internally).

Hope this helps. Cheers~

**Comment by xiechao06** [comment]
I would also like to add "ui circular label", it is not perfectly round when there're more one characters.
http://plnkr.co/edit/uv24zAYjZ36OzJbSi1Db?p=preview
Thanks!
