### ISSUE TITLE
[Dropdown] Add "drop up" variation

### ISSUE THREAD

**Issue by KabluBR** [Semantic-Org/Semantic-UI#1146]
Hi, just tried to put a dropdown with 10 items inside modal, near the bottom, and if the window is short ( but before scrolling get activated in the modal ) the dropdown does not appear. 

The window cuts the last 5 options of the dropdown.

If I reduce more the window height and scrolling class is set to the modal, then the correct height is calculated and the dropdown appears correctly.

Is there some way to fix this behavior? I tried many things but no success.

Thanks

**Comment by rickghome** [comment]
I second this request. I have a set of controls on the bottom (footer) of a UI, and need the dropdown to open "upwards" rather than downwards.

**Comment by rickghome** [comment]
To do this, it appears that the top value in the ui.menu class needs to be move upwards by the height of the menu container, and the animation needs to expand upwards from the bottom. Looks pretty easy.

**Comment by jlukic** [comment]
Adding to `1.7`

**Comment by jlukic** [comment]
Added
