### ISSUE TITLE
[Rating] Add Colored Variations, Disabled Metadata

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#1176]
what about a colored version of the basic rating component?

something like

``` html
<div class="ui red rating" data-rating="5"></div>
```

should produce red instead of black rating stars.

And a metadata parameter to disable the rating functionality would be great!

**Comment by lubber-de** [comment]
Possible since Fomantic-UI 2.7.0
https://fomantic-ui.com/modules/rating.html#color
