### ISSUE TITLE
Feature request: Parallax image backgrounds 

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#1179]
I strongly feel that plugin should be included for adding parallax backgrounds in web pages like the one here: http://davidwalsh.name/demo/parallax.php
Parallax scrolling backgrounds are very in and no other framework has them yet (I guess).

**Comment by ZeGregg** [comment]
@jlukic do you change your mind about including a parallax option in SUI like UIK http://getuikit.com/docs/parallax.html It would be useful! If not could you please take a minute to explain why. It is time missing or technical issue?

**Comment by Mauop** [comment]
Guys ur framework is awesome but it is really a big blot on the landscape (((
