### ISSUE TITLE
DropDown does not work in a standard Android 4.2.2 browser 

### ISSUE THREAD

**Issue by ilyavaiser** [Semantic-Org/Semantic-UI#1199]
On tap menu opens and immediately closes.

**Comment by inergy** [comment]
Android 4.4.2 and when I tap the menu dropdown, it animates and as soon as animation is over it begins the hide/close event.  However, when I long-press on the menu dropdown, it will stay open but I must long press to close otherwise it will close then re-open again.

Android Browser is the only problem, works in latest chrome and ff fine on the same device.

**Comment by inergy** [comment]
This is still happening, any chance for a fix?

**Comment by jlukic** [comment]
Are you experiencing this in the beta docs? http://beta.semantic-ui.com

**Comment by inergy** [comment]
Yes, unfortunately the behavior is the same.

It may be worth noting that I am using a Samsung Galaxy Note 2, recently factory reset and only some basic apps installed.  I tested this on my wife's Samsung Galaxy S5 and I did not have any issues with the dropdown.  Additionally, I am unable to reproduce the issue on the android emulator.

Side Note: This may belong in another thread, but on beta i wasn't able to navigate easily using the sidebar:
![image](https://cloud.githubusercontent.com/assets/8495416/7981236/6bf29ce8-0a62-11e5-8492-533de1310e13.png)

**Comment by carrot93** [comment]
Same problem at android 4.4.1, it closed the dropdown menu/select rapidly. And if you use drag to open the dropdown ui, still can't select the item to select input.

**Comment by jlukic** [comment]
@inergy Beta is not being used now. I should probably take down that repo to avoid confusion.

**Comment by inergy** [comment]
@jlukic yeah, that screenshot was taken before beta launched.

The problem still exists, and i'm getting all kinds of other odd issues now (with 2.0 release), but I think I've given up for now.  Unless we start to see a ton of users using the samsung galaxy note 2 default browser, I'm going to ignore the issue.  It seems the default android browser on most other phones works without these symptoms, hard to tell if it's a samsung issue or something.

**Comment by jlukic** [comment]
I see, it seems like some android issues are a bit difficult to pin down using emulation tools only. Wish I had more of a solution

**Comment by davyvanlaere** [comment]
Any news on this? The dropdown on the semantic ui demo pages is not working on android browser in marshmallow.

**Comment by deneuxa** [comment]
I have some problems with dropdown not displaying on android too (when there is no default value selected and just a "prompt")

**Comment by Elephant-Vessel** [comment]
Come on now guys, this should be a critical bug.That SU is broken in one of the bigger mobile browsers makes it hard to motivate a dependency on this at all.

**Comment by deneuxa** [comment]
+1

**Comment by Elephant-Vessel** [comment]
I'm not able to dive into this and offer a patch myself, but is there anything else one can do to help this move forward?

**Comment by jlukic** [comment]
If anyone can send me an old android phone that I can use to test this, email me at jack@semantic-ui.com

**Comment by rlora** [comment]
I'm not sure if it is the same issue, but we experienced something similar with iOS devices. Dropdowns show and hide immediately. I think it might be related to fastclick (causing two clicks in a row).

It is possible to reproduce using an emulator. For instance semantic examples show that issue in the "Restoring Defaults" example. Maybe someone could verify using an iPad 3 and that example?

I attached a video showing the problem.

[ScreenFlow.mp4.zip](https://github.com/Semantic-Org/Semantic-UI/files/211071/ScreenFlow.mp4.zip)

**Comment by nickpolet** [comment]
Has there been any update on this?

**Comment by Elephant-Vessel** [comment]
@jlukic Could you please open some pay-pal or gofundme or whatever it's called so that we can send you money to go buy some old android phone?

**Comment by sconstantinides** [comment]
Potential temporary fix: https://github.com/Semantic-Org/Semantic-UI/issues/3304#issuecomment-241954237

**Comment by peterjunsworth** [comment]
I ended up disabling the show and hide functionality, implementing my own whilst still retaining onChange event:

`$('.dropdown').click(function(){
        $('.dropdown').toggleClass('active visible');
        $('.dropdown .menu').toggleClass('hidden visible').toggle();
});
$('.dropdown').dropdown({
        onChange: function(value, text, $selectedItem) {
                // custom code
        },
        onShow: function() {
                return false;
        },
        onHide: function() {
                return false;
        }
});`

**Comment by phillbaker** [comment]
Ongoing issues may be related to https://github.com/Semantic-Org/Semantic-UI/issues/2718?

**Comment by ryanbarsatan** [comment]
Has this issue ever been resolved?
