### ISSUE TITLE
AngularJs and Checkbox problem

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#1202]
Checkbox for some reason disables ng-submit and doesn't track changes. I created a plunkr to demonstrate this issue. (sorry jsfiddle doesn't work very well). 
http://plnkr.co/edit/Ns9eZp?p=preview

I really want to use the modern looking checkbox instead of ugly default one. Any ideas?

**Comment by geemang2000** [comment]
I got it to work inside a ng-repeat by using the non-javascript setup. 

                    <div class="positive ui checkbox">
                        <input type="checkbox" id="{{$index}}-cb" ng-model="header.active">
                        <label for="{{$index}}-cb"></label>
                    </div>

**Comment by ozeebee** [comment]
@geemang2000 Thanks ! I confirm this works without any semantic javascript as described here http://semantic-ui.com/modules/checkbox.html#basic-checkbox
but this requires that the *id* of the input element matches the *for* attribute of the label element.

**Comment by geemang2000** [comment]
@ozeebee I mistakenly left some angularjs {{ }} stuff in there.

**Comment by vinaydate** [comment]
@ozeebee , @geemang2000 thanks. This helped me as well. No more any semantic js.

**Comment by sobakinet** [comment]
I'm doing it the way described above (with matching id and for) but it fires a function only after second click. What can i miss?

**Comment by hungryzi** [comment]
@sobakinet I had the same problem and it turned out I was still running `$(".ui.checkbox").checkbox()`.  Commenting that out helped.

**Comment by jeblister** [comment]
I had the sam problem. this is my solution :
I create a directive named ckeck
## In my js
``` javascript
(function() {
    'use strict';

    angular
        .module('exampleApp')
        .directive('check', check);
 function check ( ) {
        
        var directive = {          
            link: link,
            restrict: 'AE',
            scope:true
        };
        return directive;
   function link(scope, element, attrs) {
element.on("click", function () {scope.$apply(attrs["check"]);
});
        }
    }
   
})();
```

## In my html document
``` html
<div class="ui toggle checkbox" check="ctrl.datavalue=!ctrl.datavalue">
<input type="radio" name="privacy" ng-checked="ctrl.datavalue">
<label>Toggle</label>
</div>
```

**Comment by dsnoeck** [comment]
Thanks @jeblister, this is working great.

**Comment by benlooi** [comment]
I had the same problem, but I worked out a non-directive based solution.
Semantic UI renders the radio or checkbox in CSS as a :before element to the label, and hides the original html input radio and checkbox. Hence, if you click on it in a ng-repeat generated list of radio or checkbox choices, you ain't gonna get anywhere.

What I did was to use the <label for="someUniqueID">{{option.description}}</label> method.

so, in the <input> field, add an id="someUniqueID" that corresponds to the label, and it should work.

Here's my sample code:
   `<form name="myForm" class="ui form">`
`<div class="grouped fields">`
`<div ng-repeat="item in survey" >`
`<h2>`
`{{item.statement}}`
`</h2>`
	`<div  class="field" ng-repeat="choice in item.choices track by $index">`
	`<div ng-class="{'ui radio checkbox':choice.type=='radio','ui checkbox':choice.type=='checkbox'}">`
	`<input  type="radio" ng-model="item.result" ng-value="{{choice.score}}" id="{{'qn'+item.qn_no+'s'+choice.score}}" ng-if="choice.type=='radio' "/>`
		
	`<input type="checkbox" ng-model="item.result[$index]" ng-value="{{choice.score}}" id="{{'qn'+item.qn_no+'s'+choice.score}}" ng-if="choice.type=='checkbox' " />`
	
		`<textarea ng-if="choice.type=='textarea'" ng-model="item.result[$index]"></textarea>`
		`<label for="{{'qn'+item.qn_no +'s'+ choice.score}}">{{choice.choice}}</label>`
	`</div>`

	`</div>`
`</div>`
`</div>`
`</form>`

I have a nested ng-repeat array. I also have a conditional ng-class for the items in my nested array. So, based on the type of input [radio, checkbox or textarea], the semantic styling is applied accordingly with ng-if. Hope this is helpful for anyone doing dynamically loaded forms from an array.

**Comment by sensugaz** [comment]
**it work!!**
```javascript
div(class='inline field')
            div(class='ui checkbox', ng-click='vm.input.agree =! vm.input.agree')
                input(type='checkbox', name='agree', ng-model='vm.input.agree', ng-required='true')
                label
                    | I agree to the terms and conditions

**Comment by benlooi** [comment]
Just curious @sensugaz what framework or language are you using ?
