### ISSUE TITLE
[SUI] Atom / Coda Plug-in

### ISSUE THREAD

**Issue by mikefats** [Semantic-Org/Semantic-UI#1220]
If someone had the time and desire to roll up a plugin (autocomplete, clips, hints) for the Coda 2.5 editor, that would be fantastic.

About the Coda Plug-in Kit [https://github.com/panicinc/CodaPluginKit]:

> There are three ways to write a plug-in. The first way is to write a script in any common scripting language, then use the separate Coda Plug-In Creator application to bundle your script into a Coda plug-in. The second (more complex) way is to write directly to the Cocoa Plug-In API. You may create sidebar, text, and validation plugins using Cocoa. Lastly sidebar plugins can be written using the new HTML/Scripting interface in 2.5.
> 
> Coda also allows further customization through the additional add-ons: Syntax Modes, Mode Completion Additions, and Themes. Sytax Modes allow Coda to understand and highlight languages that aren't included in the default application installation. Mode Completions extend the auto-complete system to include custom lanaguage additions for libraries and frameworks. Color Themes provide customized colors to be used for sytax higlighting source code.

**Comment by Einkoro** [comment]
An atom plugin would be nice: https://atom.io/docs

And a textmate bundle. ;)
