### ISSUE TITLE
select search dropdown focus issue

### ISSUE THREAD

**Issue by wurin7i** [Semantic-Org/Semantic-UI#1253]
Select.ui.search.dropdown loses focus after choosing an option. it's forcing user click the next element to get focus

i am using chromium 38 on ubuntu

**Comment by lubianm** [comment]
If user's choice is made through keyboard (user writes some keys to search and then uses the up/down arrows to select a value), then yes, the focus remains on the form element.
Instead, if a user chooses an item from the list with the mouse click (even if the search started from a keyboard event), the form item definitively loses focus. I've tried with version 2.1.6, you can see the same behavior on both dropdown search (http://semantic-ui.com/modules/dropdown.html) and search (http://semantic-ui.com/modules/search.html). Jack, I understand your previous sentence "having the input blurred after you select a choice from the dropdown is the intended behavior", but it would be nice to have an option to decide if, after selection, the focus should remain on form element or not. Thanks.

**Comment by dreamair** [comment]
What is the use case for having the element blurred after a selection? It seems more natural for an element to hold the focus as long the user works with it. It should only lose the focus when it's set to another element (or the document or another window).
Why do you put a tabindex -1 to the menu div inside the tabindex 0 of the dropdown?
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2203
I think this is why after a mouse click on a choice the element loses focus.

**Comment by sahilfullstack** [comment]
Facing this issue again in react semantic ui drop-down, anyone please help me
