### ISSUE TITLE
Odd semantic.js error , module.cache.height > Cannot read property height of undefined.

### ISSUE THREAD

**Issue by melbourne2991** [Semantic-Org/Semantic-UI#1259]
Hi guys,

This one's a bit of a mind bender for me right now, It must have something to do with how the cache is operating, i'm sure someone here has a better idea as to SemanticJS internals than me so I thought i'd put this up.

I am getting:

`"Uncaught TypeError: Cannot read property 'height' of undefined", source: file://***/dist/semantic.js (6243)`

Now here's the weird part, the error is occurring when I modify the text of the modal with the below, and it is only occurring on one of my machines (same OS - mac) despite being the same repo.

```

                primaryModal.find('.header').text(modalTitle);
                primaryModal.find('.content').text(modalBody);
                primaryModal.find('.approve').text(modalConfirmText);
                primaryModal.find('.deny').text(modalCancelText);

                primaryModal.modal({
                    onApprove: function(e) {
                        if(typeof scope.confirmFn === 'function') {
                            var confirmed = scope.confirmFn();
                            if(confirmed && typeof confirmed.then === 'function') {
                                confirmed.then(function() {
                                    primaryModal.modal('hide');
                                });
                            } else {
                                primaryModal.modal('hide');
                            }
                        } else {
                            primaryModal.modal('hide'); 
                        }
                    },
                    onDeny: function(e) {
                        if(typeof scope.cancelFn === 'function') {
                            var cancelled = scope.cancelFn();
                            if(cancelled && typeof cancelled.then === 'function') {
                                confirmed.then(function() {
                                    primaryModal.modal('hide');
                                });
                            } else {
                                primaryModal.modal('hide');
                            }
                        } else {
                            primaryModal.modal('hide');
                        }
                    }
                });
```

It occurs both when modifying the text before or after the settings part.

Some potentially confounding variables: I am using nodewebkit & angularjs - however this is the first major issue I have run into so I'm betting it's a problem with semantic and not my environment.

Thanks

**Comment by mariorodriguespt** [comment]
I've this issue when I set the `onApprove` callback with the modal opened.

**Comment by kashishgupta1990** [comment]
We also has the same issue on modal popup opening.

Error:
Uncaught TypeError: Cannot read property 'height' of undefined

**Comment by jlukic** [comment]
I've redone modals with `flexbox` in a branch. It removes the need to check for height in javascript. Thinking about deploying this with `1.8.0`, will work under our supported browsers listed in readme.
