### ISSUE TITLE
[Table] ui celled table missing border with rowspan

### ISSUE THREAD

**Issue by voqum** [Semantic-Org/Semantic-UI#1293]
If rowspan is used on cells in a ui celled table, some cells adjacent to the rowspan'ed cell are missing the adjacent border.

``` html
<div class="ui form">
    <table class="ui celled table">
        <thead>
            <tr>
                <th rowspan="2">One</th>
                <th>Two</th>
            </tr>
            <tr>
                <th>Three (missing left border)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan="3"></td>
                <td></td>
            </tr>
            <tr>
                <td>(missing left border)</td>
            </tr>
            <tr>
                <td>(missing left border)</td>
            </tr>
        </tbody>
    </table>
</div>
```

jsfiddle: http://jsfiddle.net/gk2zzzo4/2/

**Comment by AkramChauhan** [comment]
Solved with 
Following Code . 
`<table class="ui celled structured table">
  <thead>
    <tr>
      <th rowspan="2">Name</th>
      <th rowspan="2">Type</th>
      <th rowspan="2">Files</th>
      <th colspan="3">Languages</th>
    </tr>
    <tr>
      <th>Ruby</th>
      <th>JavaScript</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Alpha Team</td>
      <td>Project 1</td>
      <td class="right aligned">2</td>
      <td class="center aligned">
        <i class="large green checkmark icon"></i>
      </td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">Beta Team</td>
      <td>Project 1</td>
      <td class="right aligned">52</td>
      <td class="center aligned">
        <i class="large green checkmark icon"></i>
      </td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Project 2</td>
      <td class="right aligned">12</td>
      <td></td>
      <td class="center aligned">
        <i class="large green checkmark icon"></i>
      </td>
      <td></td>
    </tr>
    <tr>
      <td>Project 3</td>
      <td class="right aligned">21</td>
      <td class="center aligned">
        <i class="large green checkmark icon"></i>
      </td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>`
