### ISSUE TITLE
Google font issue during build

### ISSUE THREAD

**Issue by marcus30** [Semantic-Org/Semantic-UI#1299]
I am getting the following error when running `gulp build` -

`[14:14:18] Plumber found unhandled error:
 Error in plugin 'gulp-concat-css'
Message:
    Could not find a valid import path in string: @import 'http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic'`

Any ideas?

**Comment by Soularix** [comment]
I think you have slow connection. I used to have the same problem when I was downloading a torrent.
