### ISSUE TITLE
Break gulpfile.js into parts for readability/maintainability

### ISSUE THREAD

**Issue by designnotdrum** [Semantic-Org/Semantic-UI#1300]
The gulpfile for this project currently stands at 1119 lines. This should be broken up into logical functional chunks so that it is easier to maintain and understand.

As a reference, the yeoman generator [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) does an excellent job of this, with a structure of individual files tied to a main set of gulp tasks.

**Comment by designnotdrum** [comment]
Looks like this work was done in Jan 2015

**Comment by jlukic** [comment]
Thanks for closing

**Comment by designnotdrum** [comment]
sure, np
