### ISSUE TITLE
Google Fonts Causes Timeout in China

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#1305]
The same problem as in #1296 with [1.0.0]
BTW, I used the file in "dist" folder directly, without compiling.
In IE11, when offline,  it is slow, but the font is always nice than in google chrome in which the font is always not nice.

**Comment by atian25** [comment]
+1 @mutil

plz support local css/font.

also,  `@import` will be slow

**Comment by minzhang** [comment]
A quick work-around without customization and building:
modify the semantic.sss in dist folder, change the first line from

@import ‘http://fonts.useso.com/css?family=Lato:400,700,400italic,700italic&subset=latin';

to

@import ‘http://fonts.useso.com/css?family=Lato:400,700,400italic,700italic&subset=latin';

See: http://blog.minzhang.com/2015/02/change-google-font-cdn-url-to-speed-up-semantic-ui-page-loading/

**Comment by atian25** [comment]
@minzhang  it seem `from` and `to` is same string.

**Comment by minzhang** [comment]
@atian25 made a mistake doing copy&paste, should be:

modify the semantic.sss in 'dist' folder, change the first line from


@import ‘https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin';

to


@import ‘http://fonts.useso.com/css?family=Lato:400,700,400italic,700italic&subset=latin';

**Comment by jlukic** [comment]
Closing as this appears to be solved with `useso` replacement

**Comment by Centaur** [comment]
This is still a critical issue if using semantic-ui from a cdn service.

**Comment by uniquejava** [comment]
The site `useso.com` closed long long time ago, and the solution above (and among other related issues) all not work, please reopen.
