### ISSUE TITLE
[Progress] Text / Bar should accomodate rapid updates

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#1309]
![image](https://cloud.githubusercontent.com/assets/3665590/5226945/f562a61a-772f-11e4-9eba-6fb096413be5.png)

Mainly because of the latency of the graph, because when the text reaches 100%, the bar is fast filled to the end.

**Comment by jlukic** [comment]
@playgithub Hi, its been a few years. But I have updated progress to now use a polling interval that supports rapid updates.

This will be included in `2.1.9`
