### ISSUE TITLE
[Build] Bower Overwrites Files [!]

### ISSUE THREAD

**Issue by vikeri** [Semantic-Org/Semantic-UI#1310]
I use semantic as a bower component in my frontend source folder, thus locating it in `bower_components`

After upgrading to 1.0 I decided to modify a few things with the help of the site.variables file located in src/site/globals. I did this and successfully built my own semantic.css with `gulp build`.

Then when updating semantic to 1.0.1 with `bower update` it deleted my semantic.json, theme.less files along with the site folder. Not too happy with this. I can restore the files through git but for future updates of semantic I would like to know how my customization should be done so that it will not be overwritten.

**Comment by vikeri** [comment]
So if this is closed, what is the proposed solution? I read the other thread but it only seemed to be a general discussion of best practices, not anyone offering a concrete way of solving this problem. I can change to npm instead of bower if the workflow would work there.

**Comment by jlukic** [comment]
@vikeri The solution will launch early next week along with other changes to build tools, like importable watch and build tasks, and first party meteor integration. 

NPM will be the preferred install path. It will crawl for a `semantic.json` and either run update or install scripts.

You can take a peek at it the underlying code here if you're interested
https://github.com/Semantic-Org/Semantic-UI/tree/meteor/tasks

I still need to do some testing to make sure the changes don't introduce any other issues. So this will probably launch next week.

**Comment by vikeri** [comment]
Great news! So are those task folders included in the newest npm package or how would I go about exactly to install and configure it?

**Comment by jlukic** [comment]
I'm still debugging some edge cases. My big fear is releasing new build tools that prevent people from working with SUI immediately. Beyond this testing, and rewriting some admin tasks `meteor` branch is just about done. 

See readme here: https://github.com/Semantic-Org/Semantic-UI/tree/meteor/src#setup

**Comment by jlukic** [comment]
Moved everything into `next`, i want to review a few more things before pushing

**Comment by vikeri** [comment]
Ok! Thanks for keeping us posted :)

**Comment by jlukic** [comment]
`1.9.0` is now published. I encourage you to check it out.

**Comment by vikeri** [comment]
Good stuff! Downloaded with npm and did the install. But I'm still not 100% sure of how the supposed install config should be, my hypothesis the following:
1. I put the install in eg. lib-semantic 
2. I exclude that folder from my git-repo so that it can be updated without showing up in git.
3. I specify that my site folder should be outside of lib-semantic, eg. ../src/semantic since those are files that I do want to monitor with git
4. I add the semantic.json to git

My question is hence if this accomplishes these two objectives:
1. I can update the semantic core files with `npm update` without it showing up in git
2. When I update semantic my own edits to the theme are not overwritten

**Comment by vikeri** [comment]
I now tried this setup with a fresh install and even though the installer finds my semantic.json it says it can't find the files in the lib-semantic folder (correct since that folder does not exist in the repo). Thereafter it ignores the values in semantic.json it and runs the standard installation prompts with the standard defaults.

**Comment by jlukic** [comment]
@vikeri Make sure the `base` in `semantic.json` points to wherever you plopped in the files relative to `semantic.json`. 

It should be able to detect the files and update them instead of triggering install.

**Comment by vikeri** [comment]
The base points to the correct folder, the issue is that the folder does not exists since I do not want it to be tracked by git. This since I got the impression that those files will be overwritten when I update Semantic UI.  I do not want git to notice the upgrade of a package.

I had the impression that the only files I had to change to make my own theme were those in `site`, hence I would like to only version that specific folder. Ideally the other folders would update and install themselves when i do `npm install`.

```javascript
{
  "base": "lib-semantic/", // In my .gitignore and thus would like the install to create it
  "paths": {
    "source": {
      "config": "src/theme.config", 
      "definitions": "src/definitions/",
      "site": "../src/site/", // In git since that is where I customize my own theme
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "rtl": false,
  "version": "1.9.1"
}
```

**Comment by jlukic** [comment]
The new build tools no longer have issues with overwrites, there's a manual upgrade script baked in for npm.

This will only update if the installed version is different than the version in `semantic.json`
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/install.js#L84
