### ISSUE TITLE
[1.0.1] How to make a button togglable?

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#1326]
as in: http://semantic-ui.com/elements/button.html#inverted
If click once the button appearance changed, twice back to the former appearance.

**Comment by tomgallagher** [comment]
Hi 

Thanks for Semantic UI - I'm using this is in my project now and it's great.

Any chance you could drop in a couple of lines of code?

I'm listening to a toggle button click - just need to get the state of the button after click - is it active or inactive.

Tom

**Comment by gadlopes** [comment]
I could not get your examples to work, so I made this example:

http://jsfiddle.net/how84rzj/14/
