### ISSUE TITLE
Filterable Table Columns

### ISSUE THREAD

**Issue by Tsuroo** [Semantic-Org/Semantic-UI#1358]
I often have many rows of data to present to the user - more than will fit on the screen.  The user often wants to filter the data to look at it in different ways; they do this by providing some text to filter a column to.  I've usually handled this by forcing a row of text boxes underneath the column headers and the user can use those text boxes to filter the table based on all the inputs of those text boxes.

I wish there were an easy way to have this functionality in Semantic-UI; maybe the table could have a class like "filterable" which would then provide this, or similar, functionality.

**Comment by Jielde** [comment]
+1

**Comment by jjrockstar14** [comment]
+1

**Comment by rhoizey** [comment]
+1

**Comment by jlukic** [comment]
Merging into #1357, this is one component in my book

**Comment by benjosantony** [comment]
+1

**Comment by Mingwang1986** [comment]
+1

**Comment by VipSaran** [comment]
+1

Something like this would be perfect:
https://datatables.net/examples/styling/semanticui.html

_(I'm not affiliated with linked page/author.)_

**Comment by PsyTae** [comment]
+1

**Comment by markengelstad** [comment]
+1

**Comment by egozde** [comment]
+1

**Comment by parikshitsharma70** [comment]
+1
