### ISSUE TITLE
Grouped table headers with colspan break border expectations when celled

### ISSUE THREAD

**Issue by changemewtf** [Semantic-Org/Semantic-UI#1359]
Given the following HTML:

``` html
<table class="resources ui striped celled table">
    <colgroup class="basics">
        <col /><col /><col /><col />
    </colgroup>
    <colgroup class="languages">
        <col /><col /><col />
    </colgroup>
    <thead>
        <tr>
            <th class="name" rowspan=2>Name</th>
            <th class="type" rowspan=2>Type</th>
            <th class="file-count" rowspan=2>Files</th>
            <th class="languages" colspan=3>Languages</th>
        </tr>
        <tr>
            <th class="language">Ruby</th>
            <th class="language">JavaScript</th>
            <th class="language">Python</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Ongoing Sum</td>
            <td>Small Exercise</td>
            <td>2</td>
            <td><i class="large green checkmark icon"></i></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
```

We see the following rendered:

![screen shot 2014-12-02 at 2 24 52 pm](https://cloud.githubusercontent.com/assets/14329/5269250/0a856846-7a2f-11e4-8d32-fcd449881e85.png)

What's happening here seems to be that the definition for `.ui.celled.table th:first-child` assumes that any `th` which is a `first-child` will be the first `th` of the entire table, meaning its bordering will be taken care of by the table itself.

Not sure what the resolution for this would be, but it should be supported, as grouped header columns are fully supported by all browsers.

**Comment by Maxhodges** [comment]
shouldn't colspan value be in quotes?
`<th class="languages" colspan=3>Languages</th>`
