### ISSUE TITLE
[Input] IE 10 ui icon input - text overflows icon on blur when border-radius is set

### ISSUE THREAD

**Issue by dustbort** [Semantic-Org/Semantic-UI#1361]
In Internet Explorer 10.  If I need to override the border-radius on the input element inside a ui icon input container, the text looks fine while focus is on the input, but when focus is lost, the text spills over the icon.

http://jsfiddle.net/npfLd4zu/2/

```html
<div class="ui form">
    <div class="field">
        <div class="ui icon input" style="width: 8em;">
            <input type="text" style="border-radius: 0;" value="1234567890123" />
            <i class="euro icon"></i>
        </div>
    </div>
</div>
```

**Comment by Einkoro** [comment]
Are you still seeing this behaviour under IE10 with 1.12.0 or next branch?
