### ISSUE TITLE
Retooling Build Tools

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#1385]
I spent some extra time in the park this morning pondering things in #1350 

I've come up with some thoughts of how I think we should move this forward to improve workflow for ``npm`` and ``bower``. 

For reference "pm folder" in this discussion is referring to the local *package managed folder*  i.e. ``node_modules/semantic-ui`` or ``bower_components/semantic-ui``.

##### Nothing that should be permanent should exist in a PM Folder

Maintainers of both package managers have made it explicit that these folders may be wiped during updates, and generally no one wants to ``cd`` into their components folder. 

This means that an install should generally not change files inside of its own directory, because it can't expect them to exist on update. If it does has to modify a file in its own directory, than it must make sure that it is trivial to regenerate this file on update.

##### LESS ``import`` must be hard-coded inside definitions

Currently LESS theming and path variables are set in a ``theme.config`` file which is expected to exist in PM folder ``src/``. This is because any ``import`` paths in a definitions must be hard-coded to something because definition files can't be modified after install or will risk losing changes (see issue above).

If LESS theming variables were added as run-time variables pulled in from ``semantic.json``, then only our build tools would work with our `less` files. Which is a functional solution, but would not allow the ``less`` source to be compiled without our build tools. This might alienate developers.

### Proposal Summary

* Gulp install will check if installed with ``npm`` or ``bower``. 
* If using PM it will suggest user paths in project root. 
* Install will also create a gulpfile at project root or add tasks to an existing one. 
* Install will create paths if not currently available
* Install will modify PM folder file ``src/theme.config`` to a single line file that imports a user's real ``theme.config`` located outside of pm folder.
* This file will be considered a temporary file (that could be lost on update/upgrade) and should be automatically regenerated if not found by a backup value stored in ``semantic.json``

##### 1) Install tools should recursively search for a ``semantic.json`` across parent directories. 

This would mean having to modify the project's gulpfile to walk recursively through each parent directory until it hit a ``semantic.json``.

Having a ``semantic.json`` at project root would be similar to having a ``gulpfile`` ``gruntfile`` or ``package.json`` or ``karma.json`` which is a familiar idea for developers, and reduce the barrier for entry for new developers.

##### 2) Theme folder should include two paths. One for default theme inside PM folder, and another for user themes in project root.

This is to deal with package managed folders being wiped on update or machine change. We will need to modify ``theme.less`` to use separate paths for default theme and user themes.

##### 3) User folders should be created on install

Currently the install tool expects you to set paths that already exist. We will need to modify the install task to check the specified path then offer to create the directory if unavailable

##### 4) Install should suggest sensible default paths based on install location

The install tools should check whether it is in a PM folder then suggest a default paths that exists at project root escaping the PM folder.

My suggested setup would be
````
./node_modules/semantic-ui/
./semantic.json
./semantic/
./semantic/theme.config
./semantic/themes/
./semantic/dist/
```

##### 5) If a Gulpfile is found at project root during install. We should ask the user if we can modify it to import our own tasks. If no gulpfile exists we should offer to make it.

Developers do not want to ``cd`` into a PM folder to run gulp tasks. They want to run it from their project root. 

If a gulpfile exists already this would have to be some *magic*, which imported our tasks as ``build ui``, ``watch ui`` by modifying the existing gulp file. 

If a gulpfile did not exist, this would just a copy and paste of our gulp file to project root, with ``build``, ``watch`` also aliased as ``build ui`` ``watch ui``

##### 6) Remove theme config from PM managed ``src/theme.config``, replace with single line @import of user specified ``theme.config`` path. 

This would be the *only pm managed file that would be modified*, it would only include a single line which would specify user path from install

```less
@import '../../semantic/theme.config'
```

Because this file exists in the pm folder, it *may be lost on update upgrade or machine change*, so I propose including a backup of this path in ``semantic.json``. 

Now here's where the magic comes: when a gulp task is run, it checks to see if the PMed ``src/theme.config`` exists, if it does not exist, it automatically regenerates it from the backed up path outside of the PM folder in  ``semantic.json``.

### Thoughts /  Involvement

If you would like to contribute with this feature, or have suggestions feel free to comment here. I'll be organizing a feature branch for this where we can begin work on retooling after we can come to some form of consensus.

**Comment by jlukic** [comment]
The `next` release will allow for less files to be compiled together. There is now a single include `semantic.less` that can be used, or you can just roll your own. 

```less
/* import component */
@import 'src/definitions/elements/button'; 
/* import everything */
@import 'src/semantic';
```
[See merge commit](https://github.com/Semantic-Org/Semantic-UI/commit/67061dc73084f6d845231d001089f915362cd233)

Hopefully this will make everyone's life easier. 

Once `meteor` branch merges the project will also have much simpler gulp tasks, each defined in their own file, which can be imported into external gulp files.

```javascript
var
  watch = require('path/to/semantic/tasks/watch')
;
gulp.task('watch ui', 'Watch Semantic UI', watch));
```

[Explore meteor branch](https://github.com/Semantic-Org/Semantic-UI/tree/meteor/tasks)

#1385 #1147 #675 #1780 #1498 #1350 #1441

**Comment by jlukic** [comment]
`1.9.0` is now published I encourage anyone who had issues before with build tools to check it out.

**Comment by andela-idurotola** [comment]
Hey y'all what's up with this project and whats the 411 on it? Can I bower install now?

**Comment by JakeFalcor** [comment]
Project has since moved to 2.1 version and there are installation instructions here:  
http://semantic-ui.com/introduction/getting-started.html
and if you only need package, then here:  
http://learnsemantic.com/guide/download.html

**Comment by DaSchTour** [comment]
I don't know why, but this is totally not working. I tried to work with bower and the semantic.json but it seams like the paths from semantic.json aren't really used because it only works if my theme.config is inside my root although I have specified that it should be in my conf/semantic-ui/
I also added my site overrides to conf/semantic-ui/site but it doesn't use it. I than have seen that there are also paths in the theme.config so I changed them. but it also doesn't work. The build process isn't done. It really frustrating that the build process work with a broken configuration but simply doesn't do anything.

**Comment by cmnstmntmn** [comment]
one year, and still the process of using semantic-ui with webpack is a pain in the ass

**Comment by DaSchTour** [comment]
It's really bad. I love Semantic UI because of the style, the components and so on. But the build process and because of the fact, that there is no SASS version, I need to consider to use other frameworks for my feature projects :(

**Comment by saeidscorp** [comment]
The components still rely on the hard-coded `src/theme.config` file. (and we're now on the 2.2.0 release!)

> `1.9.0` is now published I encourage anyone who had issues before with build tools to check it out. It should solve for the issues discussed specifically in this thread.
>
> @jlukic 

It solves issues with importing Semantic's LESS file directly, but with bower... no luck. I changed `semantic.json` residing outside `bower_modules` to point to the correct paths, but Semantic still relies on hard-coded paths.

It's a pity that such an awesome web framework has this *build tool* issues.

**Comment by Pithikos** [comment]
Why is this closed? Two years and still the same issues.

The framework is awesome but without easy customization it's a pain in the ass. I have spent countless hours just to change a single color and still I haven't managed to do so without hard-coding everything.

**Comment by cmnstmntmn** [comment]
@Pithikos anyway, i find these kind of frameworks bad by design; you can't customize anything without broke some other thing; you should consider tachyons.io that uses composition. this way you could to create unlimited components.

**Comment by atrauzzi** [comment]
SASS or Stylus.  This project needs to migrate over to something more modern and sane and in particular, in such a way that doesn't require gulp as a dependency.  I wish I could use all of this, but the whole thing is stuck in 2010.
