### ISSUE TITLE
How to align login box aligned centre of the page? 

### ISSUE THREAD

**Issue by Reegan01** [Semantic-Org/Semantic-UI#1394]
Dear Developers,I con't able to understand how to place the login box centre using semantic-ui. http://stackoverflow.com/questions/27343992/semantic-ui-centre-aligned-login-box

**Comment by bkkoo** [comment]
Thank you too.

**Comment by henri-hulski** [comment]
Just have exactly the same problem.
I just have a log-in box based on your login example.

You use the css `body > .grid { height: 100%;}` for stretching the height to the whole window and then you vertical align it with `center align grid`.
This works all fine.

But I want to do that with react. As reacts inserts some divs between the body and the grid `body > .grid` doesn't work anymore.
The login box sticks at the top as height of the grid element is only it's context.

Somebody has a solution for that?

**Comment by damon-rand** [comment]
@henri-hulski I had the same issue and to solve it in my react component I bundled another stylesheet using `import` and based on the IDs of the DOM elements I just added the following to ensure that everything was 100% height. In my case there were two elements between the `body` tag and the `.grid` class.

`#[whateverID] {
	height: 100%;
	.grid {
		height: 100%;
	}
}`

**Comment by puneetverma05** [comment]
Issue Unresolved. @jlukic

**Comment by bisade** [comment]
You can add inline style to the Grid component
<Grid verticalAlign='middle' centered style={{height: '100vh'}}>
