### ISSUE TITLE
Form Validation - optional fields, validate only if value is not empty. Feature?

### ISSUE THREAD

**Issue by kurbar** [Semantic-Org/Semantic-UI#1396]
Is it possible to use the form validation to validate certain fields only if their value is not empty or would a seperate validation would need to be written? If there isn't something like that in the Form Validation behavior yet, I think it would be a really cool feature to have.

**Comment by shoaibnawaz** [comment]
I have no idea how `allowEmpty` would work here as a new rule. Each module callback just work as logic processing chamber comparing field's entered value and required one.  `allowEmpty` should intercept the other validation rules to stop when value is empty or becomes empty after invalid value is cleared altogether.

All this can work one step above where these rules are triggered. So I like the @DHNCarlos way just by adding one more line.

```
if(field.optional && $.trim($field.val()) == ""){
  module.debug("Field is optional and empty. Skipping", field.identifier);
  module.remove.prompt(field, fieldErrors);
  return true;
}
```

**Comment by shoaibnawaz** [comment]
I am sorry for touching the very old thread. I am still using the old sementic ui in my project and this thread helped me to resolve my problem.

**Comment by seanryano** [comment]
I don't see anything in link:
http://semantic-ui.com/behaviors/form.html#optional-validation-fields

About allowing empty field and only validating when the field contains text.

Anyone got this working?

`                        username: {
                            identifier : 'email',
                            rules: [
                                {
                                    type   : 'email',
                                    prompt : 'Please enter valid email'
                                }
                            ]
                        }`

I want to allow empty fields for email field and only validate when something is added there.

**Comment by kurbar** [comment]
@seanryano The link has changed http://semantic-ui.com/behaviors/form.html#optional-fields

**Comment by envision** [comment]
This doesn't seem to work with inline configurations without defining validation rules specifically:

    <input type="text" name="billing_address" [(ngModel)]="account.billing_address" minlength="2" maxlength="50" #billing_address="ngModel" optional/>

**Comment by envision** [comment]
Ah, the problem is actually in that email field can't seem to be optional...!

This doesn't work:

    <input type="email" name="billing_email" [(ngModel)]="account.billing_email" email minlength="2" maxlength="50" #billing_email="ngModel" autocomplete="off" optional/>

**Comment by HirparaNirali** [comment]
phone: {
            identifier: 'phone',
              optional: true,                                 //try this line 
            rules: [
                {
                    type: 'length[12]',
                    prompt: 'Your mobile must be at least 12 number'
                }
]}
