### ISSUE TITLE
Center aligning images?

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#1400]
Consider an element `ui medium image`.  Inside a parent with class `column`, images don't center even when assigned with something like `ui center aligned medium image`. I fixed it by using `margin:0 auto`, but I'm pretty sure there's got to be a better way to center images? Sorry, I was away for a while and a lot of things have seemed to change within SUI (and congrats on the 1.0 delivery!). 

Cheers.

**Comment by SwiTool** [comment]
Just a question, is it normal that in the fiddle previously mentionned, none of the tests work ?
