### ISSUE TITLE
Checkboxes and Radios Don't display without a <label>

### ISSUE THREAD

**Issue by waxim** [Semantic-Org/Semantic-UI#1404]
See: http://jsfiddle.net/kv6qu1bt/1/

When  displaying a checkbox or radio as part of a table (where the 'label' is in the title header) there may not be a need to use an actual <label> tag to id the element, but when using radios or checkboxes without a label they dont show.
## Tested on

Windows 7 Chrome/39.0.2171.71
Windows 7 Firefox/31.0

**Comment by ivantcholakov** [comment]
A dirty workaround is possible:

```html
...
        <td>
            <div class="ui radio checkbox">
                <input type="radio" id="default_bg" name="default" value="bg" checked="checked">
                <label>&nbsp;</label>
            </div>
        </td>
...
```
