### ISSUE TITLE
Dropdown inside a Sidebar not overlaying correctly

### ISSUE THREAD

**Issue by Trouche** [Semantic-Org/Semantic-UI#1410]
A dropdown in a sidebar menu doesn't appear correctly outside of the sidebar.  Instead the dropdown menu adds a scrollbar to the sidebar.  

http://jsfiddle.net/d0798fgd/

**Comment by xtrepo** [comment]
right but when you multiple item in the sidebar you cannot scroll .

**Comment by phuong3030** [comment]
@Trouche You can use Popup inside Menu.Item instead.

**Comment by gringolalia** [comment]
Setting the following solved the problem.
```
		.ui.vertical.sidebar.menu {
			overflow: visible !important;
		}
``` 
Thank you.
