### ISSUE TITLE
[Search] Using Different API Responses

### ISSUE THREAD

**Issue by illuminos** [Semantic-Org/Semantic-UI#1414]
I have a question. The documentation is not clear about searching a server json response without the title attribute?

Your suggested server response was 
{
{"title":"apple"},
{"title":"banana"}
}.

My existing code gives this
{"Apple","Banana"}..without title or any key.

How do I make your search module work in this scenario?

Big fan of your framework. Thank you for your time.

**Comment by SunDi3yansyah** [comment]
bagaimana untuk penulisan berkas JSON external?
is just like this
```json
[
	{
		"title" : "Lorem ipsum dolor sit amet."
	},
	{
		"title" : "Lorem ipsum dolor sit amet."
	},
	{
		"title" : "Lorem ipsum dolor sit amet."
	}
	// ect
]
```

**Comment by martoo6** [comment]
if anyone comes around the same issue the problem is that response[fields.results] fails the following validations made on the search module.
```
isProperObject = ($.isPlainObject(response[fields.results]) && !$.isEmptyObject(response[fields.results])),
isProperArray  = ($.isArray(response[fields.results]) && response[fields.results].length > 0),
```
In order to fix it fields.results must be set correctly on the search configuration and must be a non empty array.
