### ISSUE TITLE
Eliminating the 300ms touch delay on mobile devices

### ISSUE THREAD

**Issue by Trouche** [Semantic-Org/Semantic-UI#1418]
I have attempted to implement the FastClick library to eliminate the 300ms delay on many UI elements when browsing from a mobile device.  It works extremely well in most cases, making the UI seem extremely fast and responsive in a mobile browser.

https://github.com/ftlabs/fastclick

Unfortunately, there are few cases where it fails (dropdowns, menu select) because these elements already have the correct events being fired for mobile.  The FastClick documentation suggests using class='needsclick' on the element in question.  This workaround doesn't appear to be compatible with Semantic UI.

Would you consider looking into this as an enhancement?  The speed with which the UI performed on the iPad I tested it was truly amazing with the FastClick library enabled.  With a few tweaks this could be a great addition.

**Comment by SantzDesign** [comment]
+1

**Comment by flt123** [comment]
+ 1 needsclick has issues when you have more than one dropdown on a page

**Comment by aesmon** [comment]
Changed the event name to 'touchstart' in dropdown.js which worked really well with fastclick
line 23
hasTouch       = ('ontouchstart' in document.documentElement),

to

hasTouch       = ('touchstart' in document.documentElement),

**Comment by jlukic** [comment]
I'd imagine that would disable touch event handlers.

**Comment by aesmon** [comment]
Sorry, I forgot about my use case that I am using HammerJS library for touch events thus why 'touchstart' even handler is used by me. Otherwise, the dropdown would open and close on mobile on single tap.
