### ISSUE TITLE
Responsive table problems

### ISSUE THREAD

**Issue by mchaput** [Semantic-Org/Semantic-UI#1428]
1. The `display:block` in `.ui.table tr > td` is not made `!important` (semantic.css line 25019), so the rows get `display:block` but cells still have `display:table-cell`, so the display of the table gets screwed up. Not sure why it works on the demo site.
2. Tables transition when the viewport is still quite wide (768px). I feel like this should be very much a narrow, phone-only effect.
3. There should be a way to turn this effect off. Ideally per-table using a table class, and also globally in the source files.

Is there a way to turn off/comment out the code implementing this in the source now? Thanks!

**Comment by moxet** [comment]
changing ```<!DOCTYPE html>``` works for me
