### ISSUE TITLE
Documentation: Ability to map css rule to corresponding component/module

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1435]
Very often when I look at an example in the documentation I run across some CSS rule I am not familiar with. I'd like to suggest adding some sort of index or mapping between CSS rule names and their corresponding UI component/module.

For example, for `two fields` I think `two` should to the grid system documentation, and `fields` ... well... to be honest I don't know. I know that `field` probably maps to the Form documentation but I've never seen a concrete description for `fields` (nor how `field` and `fields` differ).

**Comment by jlukic** [comment]
I will close this for now, will continue adding more enhancements to code view as I can.

**Comment by stygiansabyss** [comment]
Thank you sir.
