### ISSUE TITLE
Themes using plain CSS and improving adoption

### ISSUE THREAD

**Issue by nathanpalmer** [Semantic-Org/Semantic-UI#1441]
We have been happily using Semantic UI in both Rails and Ember environments using SCSS for quite some time. That’s because all we are using are the compiled css and js files. Going back a year ago when I was working with .NET in a Microsoft environment I’m sure I could have pulled in and used pre-1.0 Semantic UI there as well. With the release of 1.0 we’ve added several dependencies that now make the upgrade from hard to impossible and I fear that will __decrease adoption__. Yes, we can still use the compiled versions but we are unable to use themes. 

Following along with some of the issues these all seem related to either the build or the lack of support of a library (such as SASS, which is necessary now if anybody wants to keep it as their pre-processor)

  * Documentation for upgrade to Semantic UI 1.X.X - #1426 
  * why installation is required - #1437 (they should add more more context to this)
  * Retooling Build Tools - #1385 
  * Restructuring Default Install - #1350
  * @themesFolder is undefined on build - #1344 
  * SASS Support - #1147 

## Semantic UI Philosophy 

What initially impressed me about semantic, and why I sold my team on it, was that the philosophy of using language as a way to communicate intent made sense. Using nouns and adjectives was also inline with how I felt CSS should be used. The idea that we weren't dealing with a ui-facebook-button but instead a “ui facebook button” meant that we are building out an interface using discrete parts to form the whole. Not only that but we could, from plain css, redefine what facebook looked like and not affect any other .ui.buttons or introduce our own variation of a button. That is the power CSS was made for which is forgotten in other frameworks.

## Semantic UI 1.0, Theming and Adoption

When I first saw theming on the main site I was excited! The dropdown with different UI styles and seeing them change was great and a really wonderful way to show the power of the framework. The more I looked into how to theme things I started to get disappointed. The design of themes seems very well thought out, however it doesn't fit in any of our environments. The road from a heavily used SCSS site using the Rails assets pipeline to a Less site using a Gulp pipeline is too high to climb. It would be less work for us to fork pre-1.0 and bring over some pieces manually.

## The Future

This got me to thinking. Why can't we achieve the same amazing theming capabilities and still maintain the ability to consume the compiled css. At that point it won't really matter what CSS Preprocessor or Build Tool the developer is using. Instead rely on carefully thought out naming, which I felt was at the core of Semantic UI’s philosophy. Take the .ui.facebook.button example.

### Defines global semantic styles, base font size, colors, etc
```
.ui
```

### Defines global theme button style
```
.button
```

### Defines the “facebook” variation for a button
```
.facebook
```

### Defining an "Amazon" theme
If we want to implement the "Amazon" theme then redefining the .button should do the trick. This also should allow for themes to be pulled in as single css files or imported easily from package managers and imported directly after semantic to fill out all the overrides. 

Taking that a step further we can introduce the .theme variation that can be applied to html/body

```
<html class="ui theme amazon">
</html>
```

Redefine .ui.theme.amazon with all the extra bits we need and users can easily change their entire site (or on a page-by-page basis if necessary.) This keeps us all nicely within pure CSS rules and stays compatible with more environments that I'd like to see Semantic UI used in.

**Comment by mikocot** [comment]
I agree with mnquintana,
we choose Semantic UI for our project, as it was simple and minimalistic, still, powerful. Fast to learn. Now it seems much more professional, but for a cost of steeper learning curve, etc.

On the other side, you can still use /dist files. And after you invest time to learn its easier to customize it, avoiding direct changes in the code, which makes it easier to maintain and keep up to date. However, an update engine would be useful. Preserving current changes and adding new stuff.

After all, themes dont need to be used at all. You can stick to one and update it according to the needs. You can choose some, build and let user choose, while replacing used css/js on the fly if needed. Otherwise you'd need load css/js for all the themes + fonts/icons which is not a good idea or manage themes resources dynamically.

**Comment by Panoplos** [comment]
I think using an additional CSS class for theming would introduce a lot of excess CSS code into the site's compiled stylesheet. This would not be the desired approach for apps that need to load on mobile over slower networks, IMO. This being said, it would be nice if I could just specify `theme: 'github'` in the config file and have that propagate throughout the build.

**Comment by aaronbhansen** [comment]
Stylesheets cascade, thats the nice advantage of CSS. If the base stylesheets were setup right, you could have the main semantic css import and then a themed imported to override each of the ui elements. Also, if you didn't mind the extra size, you could have all themes available and have the option to override specific elements the semantic way with what is mentioned above. 
You wouldn't need a custom build or webtools, just import the base + themes you want.

**Comment by Panoplos** [comment]
This is true, but I like the idea of being able to write once and reuse across disparate apps with different theme options. ;^)

**Comment by MattiSG** [comment]
@jlukic Why was this closed?

**Comment by jlukic** [comment]
This is a discussion not a bug or a proposal and has been inactive for a while.
