### ISSUE TITLE
Passing the context as an argument to $.proxy

### ISSUE THREAD

**Issue by chikamichi** [Semantic-Org/Semantic-UI#1445]
Hi,

When building "complex" UI interactions where multiple modules are involved, I've been struggling with a limitation in the way $.proxy is used in the project.

Let's say I have an icon giving access to an Export feature, through which the user may export in different formats. Those are presented as a list of export options in a dropdown. The icon has a popup, so that a description appears when hovering with the mouse. Then, upon clicking the icon, I want to close this popup and display the dropdown.

Examples below are in the context of a Backbone View, written in coffeescript, but it obviously applies whatever the coding context/syntax is:

``` coffeescript
# Let's say that .exportIcon has already been attached a popup module at this point.

bindDropdown: ->
  @$('.exportDropdown').dropdown
    onShow: =>
      @$('.exportIcon').popup('hide')
```

Note the [use of a fat arrow `=>`](http://coffeescript.org/#fat-arrow) to create a custom context (the view).

Now, let's say I want to tweak the dropdown element for some reason. I can benefit from the lib using $.proxy:

``` coffeescript
bindDropdown: ->
  @$('.exportDropdown').dropdown
    onShow: ->
      # Makes no sense, but it's just for the sake of the example ^^
      $(@).css('background', 'red')
```
Here, a simple arrow is in use (no extra binding), so the context is the element of the dropdown module.

But I can't do both, because I can only have one context at a time. The trivial workaround is to keep a reference to the custom context (here, the view) and use it in the callback, like this:

``` coffeescript
bindDropdown:  ->
  view = @
  @$('.exportDropdown').dropdown
    onShow: ->
      view.$('.exportIcon').popup('hide')
      $(@).css('background', 'red')
```

But it sucks :cactus: 

A simple, commonly used solution to this problem is to pass the context (here, the dropdown element) as an argument when proxying:

``` javascript
// Extracted from the dropdown module.

// from…
$.proxy(settings.onShow, element)();
// to:
$.proxy(settings.onShow, element, element)();
```

which allows to write this nice-looking piece of code:

``` coffeescript
bindDropdown:  ->
  @$('.exportDropdown').dropdown
    onShow: (dropdown) =>
      @$('.exportIcon').popup('hide')
      $(dropdown).css('background', 'red')
```

Those who need it, can now change the context of the callback while still having access to the original context (`element`); those who don't need the extra-feature, have nothing to worry about nor change, so it's a win-win.

What do you think?

Also, I am wondering whether the whole $.proxy thing may lack consistency. For instance, this is how a call looks like in the popup module (compare to the dropdown module, as shown above):

``` javascript
$.proxy(settings.onShow, $popup)(element);
```

**Comment by jlukic** [comment]
I am going to go against passing context as a parameter. I just find the changes too demanding for consistency, and the format slightly unconventional.

**Comment by chikamichi** [comment]
Ok, fair enough :) Thank you.
