### ISSUE TITLE
[Button] Keyboard navigation

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1449]
Reopening https://github.com/Semantic-Org/Semantic-UI/issues/890

Buttons need to support keyboard navigation for reasons mentioned at http://webaim.org/techniques/keyboard/

This was supposed to be added in version 1.0 but never was. As far as I can tell, we need to implement at least two things:
1. Mark buttons as focusable so users can use `TAB` to shift focus to a button.
2. Add some sort of border-based highlight to indicate that a button has the focus.

See the buttons on Github's issue tracker for an example of how I expect this to work.

**Comment by marcysutton** [comment]
Adding tabIndex isn't enough if you allow `<div class="button"></div>`. It also needs a keypress event and `role="button"` if it isn't a native button element.
