### ISSUE TITLE
[UI Suggestion] Text Input Validator

### ISSUE THREAD

**Issue by rogrdat** [Semantic-Org/Semantic-UI#1456]
Need a currency input type that takes a format value something like 
-- type of separator (comma or dot)
-- # of characters including decimals
-- Currency prefix

Validation code would trim/round the values based on the format -- Round the decimal value but trim or error if # of digits before decimal exceeds those specified

Ex:  format:USD###.##  that would format to $34.47

**Comment by jlukic** [comment]
#2794
