### ISSUE TITLE
[UI] Captcha 

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#146]
A simple implementation of captcha services.  More can be added at a later time; but the first release will be for "solve".

I can make the control, but I want to know if it'll be accepted and get some feedback on the API.  
### Assumptions:
- a captcha is shown when a form is shown
- it's at the bottom of a form
- a short delay between calling this function and the captcha appearing is okay (but should be possible to avoid)
### Make the Captcha

At some point you call the function to initialize the captcha, like when the page loads, or the form loads.

``` javascript
$("#my_captcha_container").captcha({
    service: "solve",
    key: "091230cksjd092138129klad"
});
```
### `$.captcha("load", which)`

This is either called explicitly, or when we try to create one.  Each captcha service has a JavaScript file, which we can load into a script element, and attach an onload callback.  This improves page load time, and avoids loading the captcha stuff, which not every visitor may need (e.g. if the captcha exists in a modal).

Examples:

``` javascript
$.captcha("load", "solve");
$.captcha("load", "recaptcha"); // when implemented
$.captcha("load", "someunknownservice"); // Throws a Not Implemented error, and lists possible options
```
### `$.captcha("input")`

Get the current text input element for the captcha.  Useful for doing an AJAX request, or binding to a MVC model.  For example, using a `change` or `keyup` event handler, and the following.
### `$.captcha("data")`

Returns an object with these keys:

``` javascript
{
    value: "what the user typed",
    challenge: "the key the server needs to authenticate the value",
}
```
## Other Notes

We will always use the "custom" theme option, which allows the usage of consistent UI, styling, and icons with the rest of SUI.  It'll also permit us to create specific styles for these in the with a class such as `.ui.captcha`, and sub items.
## 

If this would be a welcomed addition, I can start working on it.  What in the above needs to be changed?  I'm sure there are problems, at least semantic ones.

**Comment by xiwc** [comment]
+1
