### ISSUE TITLE
Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag

### ISSUE THREAD

**Issue by bolen** [Semantic-Org/Semantic-UI#1474]
Is this a bug or what?
Semantic-UI-Docs Also the case.

**Comment by bradparks** [comment]
An example of using a semantic-ui "sidebar" in only part of your page (in a "context") can be found here:

http://stackoverflow.com/q/35664906/26510

**Comment by Gloveny** [comment]
After I get this message, I loose all link functionality.    I'm using JavaScript (React) functions to navigate on the side menu.   If I make my browser window small like a phone and open and close the side menu the links stop working.  Help anyone?
