### ISSUE TITLE
Watch doesn't seem to work

### ISSUE THREAD

**Issue by ciaoben** [Semantic-Org/Semantic-UI#1476]
Hi, I've just downloaded the last release of semantic, everything seems to work fine, but when I launch 

`gulp watch`

and try to change a file, here what happen:

```
[gulp] Modified: src/site/globals/site.variables
```

And nothing happen ( no rebuild ). What could the problem be?

**Comment by r0b-** [comment]
Same here :-(

This is the output:

    SRC Path Does Not Exist path-to\my-site\site.less
    [gulp] Modified: path-to\my-site\site.variables

My custom site folder holds .variables & .overrides files only ...

PS: I'm on Win7, gulp install / theme customization runs fine

**Comment by jlukic** [comment]
@r0b- Are you still having this error? I'm moving on to build tools this week and want to help clarify and lingering bugs.

**Comment by ciaoben** [comment]
Sorry but I am not in my country from the time I've opened my issue. I 
am traveling for work so I didn't have time and my machine to test it! 
I'll let you know in the future, but with the debug I guess it's a 
problem caused by docker. Maybe can't read correctly the path or something..

Il 26/01/15 19:41, Jack Lukic ha scritto:

**Comment by r0b-** [comment]
Hi Jack, I'm on vacation and unfortunately will work with the build tools not before March...

**Comment by jlukic** [comment]
I'll close this thread for now, @ me if there's any more evidence.

**Comment by vohof** [comment]
```
Watching source files for changes
Change detected in theme config
[09:44:36] Starting 'build'...
Building Semantic
SRC Path Does Not Exist undefined
[gulp] Modified: src/theme.config
```

**Comment by agborkowski** [comment]
same here
`````
[13:53:48] Starting 'build'...
Building Semantic
SRC Path Does Not Exist undefined
[gulp] Modified: src/theme.config
`````

**Comment by r0b-** [comment]
Working for me now... using 1.9.0

**Comment by jlukic** [comment]
The error message
```
SRC Path Does Not Exist undefined
```

Should no longer occur when modifying `theme.config` in latest version.
