### ISSUE TITLE
Issue with Grid's row first column

### ISSUE THREAD

**Issue by tecoad** [Semantic-Org/Semantic-UI#1478]
I have a grid with two columns inside a row, somehow and empty space is added to the bottom of the first column. Even with a different number of columns, that space occurs only on the first column. 

![image](https://cloud.githubusercontent.com/assets/2627749/5489413/250b19e4-86b0-11e4-81f8-4514749c9f37.png)

Wonder it may be something related to font-size in collections/grid, is there a way to correct it?

**Comment by gabormeszoly** [comment]
I think, everything is fine
tested in osx: latest chrome, firefox, safari, opera
jsfiddle here: http://jsfiddle.net/gabormeszoly/kgL252tx/1/

**Comment by jlukic** [comment]
Glad to hear!
