### ISSUE TITLE
Excluding components from semantic.css and avoid building individual component css

### ISSUE THREAD

**Issue by montecruiseto** [Semantic-Org/Semantic-UI#1501]
Hi, I'm starting on SemUI and it looks amazing. A real Bootstrap killer for me. Congrats on a heroic effort so far @jlukic. 

2 questions though:
During gulp install I switched off several components in the wizard, but all the components still end up in my `semantic.css` builds for some reason. I've read everything on the Learn Semantic site a couple of times now, and dug into the gulpfile. I cannot find the answer to:
1. what is the best practice to throw out components to make the `semantic.css` really small? The only solution I found so far is to delete components from the `semantic.json.` 
2. what is the best practice to avoid building all the individual component css files all the time? They make builds quite long and I don't see any reason to ever use anything else than a concatenated `semantic.css` file (which I have customized to my liking by throwing out everything I don't need).

**Comment by jlukic** [comment]
@montecruiseto For discussion of issues with Bower and NPM see #1385. Bower and NPM both want you to treat the package folder as the same as a ``temp/`` folder which means themes get razed. 

We need to retool build tools to resolve
