### ISSUE TITLE
[Form] Highlight background color is indistinguishable for Chrome auto-completed fields

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1508]
Version 1.2.0
Chrome 39

https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L44505 uses a yellowish highlight for selected form fields.

Unfortunately, Chrome defines a rule `input:-webkit-autofill` which sets `background-color: rgb(250, 255, 189)`. This means that when one tries to select input fields inside an auto-completed form, it is impossible to see the highlight.

See the bottom of http://www.computerhope.com/issues/ch001377.htm for a form which triggers auto-fill / auto-complete. If you examine the matching CSS rule, you will find the aforementioned color.

**Comment by jlukic** [comment]
![Autocomplete Color](https://dl.dropboxusercontent.com/u/2657007/autocomplete.png)

To my eyes autocomplete fields appear to look good in SUI forms. The focused border is changing correctly.

**Comment by cowwoc** [comment]
Hi Jack,

I am referring to the fact that the fact that the selected text (ctrl-a)
inside such fields cannot be distinguished from chrome's highlighting.

**Comment by jlukic** [comment]
Ahhhh! That can be remedied..

**Comment by jlukic** [comment]
Fixed in next, neutral grey for form highlights. Page highlight moved from highlighter yellow to neutral blue (toned down browser default highlight color)

**Comment by cowwoc** [comment]
@jlukic Cool, I'll check it out.
