### ISSUE TITLE
Semantic UI broke down scrollTop()

### ISSUE THREAD

**Issue by riophae** [Semantic-Org/Semantic-UI#1509]
I tried getting scroll position but it always returns 0.

``` javascript
$(document).scrollTop(); // => 0
```

I found that it's because Semantic UI had set `height: 100%;` on `html` and `body`.
http://stackoverflow.com/a/12789956/2228929

Why? What does this code do?
Or is there any workarounds without removing the `height: 100%;`?

**Comment by tamoyal** [comment]
I'm a bit confused by this issue because I'm still seeing the `overflow-x: hidden;` in the `html.ios` class which was said to be older buggier code.  I have verified that the existence of that completely breaks `window.scrollTo`.  Should this issue really be closed?
