### ISSUE TITLE
How could I use semantic-ui offline?

### ISSUE THREAD

**Issue by zhaozhiming** [Semantic-Org/Semantic-UI#1521]
Hi all,
I found semantci-ui since 1.0 version will to find the font on google web site, but for some reasons I can't visit google web site, so I get the error below. 
My question is: how could I use semantic-ui offline, and don't need to get some other thing on web, just use the semancti.css and semantic.js?

Thanks.

``` css
@import 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin';

```

![screen shot 2014-12-28 at 1 04 10 pm](https://cloud.githubusercontent.com/assets/1436694/5563098/1f169dc6-8e92-11e4-92eb-9162ec6c2496.png)

**Comment by mikocot** [comment]
I cannot really find any information about clean customization of web font used by semantic. i can easily change the font imported from google, but there seem to be no override for @font-face. I could only locate the @headerFont  and @pageFont, but they seem to refer to the font family. I could specify the src for my fonts manually in the site.override, but as far as it should appear at the top of the .css file, and not at the end. Any suggestions here?

**Comment by sevaivanov** [comment]
Thanks @jlukic! You can locate the *src/site/* folder by looking in *semantic.json* generated during installation and don't forget to rebuild semantic after with ```gulp build``` command in the *semantic/* folder.
```
$ cat semantic.json 
{
  "base": "semantic/",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
...
$ cat semantic/src/site/globals/site.*
/*******************************
         Site Overrides
*******************************/
@font-face
{
}
/*******************************
     User Global Variables
*******************************/
@importGoogleFonts: false;
```

**Comment by 120dev** [comment]
An easy way to get google fonts locally, is with this package : 
```
https://www.npmjs.com/package/google-fonts-offline
```

**Comment by kentoj** [comment]
Does anyone have any examples of pointing Semantic to a local copy of fonts? I have the font downloaded and I see [here](https://css-tricks.com/snippets/css/using-font-face/) how to define a `@font-face` yet I do not know how to link that up with Semantic.

Will someone post an example here just so I can fill this hole in my knowledge?

**Comment by huseyinkozan** [comment]
Please fix this issue. We are using SemanticUI at a embedded device which works as stand alone AP. Due to this dependency, I we cannot simplify our release production.

**Comment by skleeschulte** [comment]
@huseyinkozan This is what I did:

- [Downloaded Lato ttf files from fonts.google.com](https://fonts.google.com/selection?selection.family=Lato:400,400i,700,700i)
- Uploaded Lato-Regular.ttf, Lato-Italic.ttf, Lato-Bold.ttf and Lato-BoldItalic.ttf to [Font Squirrel Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator)
- Used the following configuration for the generator (most importantly **select CSS: Style Link**)

    {
      "mode": "expert",
      "formats": [
        "ttf",
        "woff",
        "woff2",
        "eotz",
        "svg"
      ],
      "tt_instructor": "keep",
      "fix_vertical_metrics": "N",
      "metrics_ascent": "",
      "metrics_descent": "",
      "metrics_linegap": "",
      "fallback": "none",
      "fallback_custom": "100",
      "options_subset": "none",
      "subset_custom": "",
      "subset_custom_range": "",
      "subset_ot_features_list": "",
      "style_link": "Y",
      "css_stylesheet": "stylesheet.css",
      "filename_suffix": "-webfont",
      "spacing_adjustment": "0",
      "rememberme": "Y"
    }

- Saved the font-files (.eot, .svg, .ttf, .woff, .woff2) alongside the stylesheet.css file (all contained in the zip-file from the Webfont Generator) to a folder in my project
- Added `@importGoogleFonts: false;` to `site/global/site.variables`
- Added an import statement to `site/global/site.overrides` to import the `stylesheet.css` file generated by the Webfont Generator (it contains the `@font-face` definitions): `@import 'path/to/stylesheet.css';`

Of course you have to make sure that the browser can find the files that are referenced in `stylesheet.css`. I use all of this in a Webpack 2 setup with [file-loader](https://github.com/webpack-contrib/file-loader)s for the font files and [semantic-ui-less-module-loader](https://github.com/gadyonysh/semantic-ui-less-module-loader) for the less files from [semantic-ui-less](https://github.com/Semantic-Org/Semantic-UI-LESS).

**Comment by arthurlacoste** [comment]
I have made a fork for this issue : https://github.com/arthurlacoste/semantic-ui-offline

You cant use this for the css with fonts includes : 
```js
npm i semantic-ui-offline
```

**Comment by huseyinkozan** [comment]
@arthurlacoste Thanks. Will you continue to support newer versions ?

**Comment by arthurlacoste** [comment]
@huseyinkozan yes, [I've made a script to handle any change](https://github.com/arthurlacoste/semantic-ui-offline/blob/master/bin/recreate.js). 🍸

**Comment by Tony427** [comment]
Hi, I am using emantic-ui with dotnet core by nuget. I can't modify `ite/global/site.variables` change to offline. Anyone have idea?

**Comment by lubber-de** [comment]
Lato 2.0 fonts bundled and googlefont import removed in the official community fork https://fomantic-ui.com by
https://github.com/fomantic/Fomantic-UI/pull/2359
