### ISSUE TITLE
Animated buttons do not vertically align to inline siblings buttons

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#1536]
Noticed this when I was trying to put a series of buttons inline with each other. 

Buttons that have animation will appear higher than any other button type. I'm guessing this has something to do with ```overflow:hidden``` on the animated buttons.

Doing a little digging, I came across this: http://colinaarts.com/articles/the-magic-of-overflow-hidden/
It appears as if it causes collapsing margins.

I found a hotfix for it; setting ```display:inline-flex``` or ```display:inline-table```, however this still makes them 1px off and [browser support](http://caniuse.com/#feat=flexbox) for flexbox is spotty at best.

JSFiddle: http://jsfiddle.net/bfy0yx8f/1/

Browsers Used: Chromium 39 & Firefox 34
Operating System: Linux Mint 17 LTS

**Comment by jlukic** [comment]
Here's a simpler fix. 
http://jsfiddle.net/7nuLr4nu/

Surprising about the odd alignment with ``vertical-align: baseline``, the inherited value.

**Comment by jlukic** [comment]
Adding in patch
