### ISSUE TITLE
Question: why 16 columns not 12 columns as default ?

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1537]
16 columns: 1-2-4-8-16
12 columns: 1-2-3-4-6-12

16 columns: "sixteen wide mobile eight wide tablet four wide computer column" 
12 columns: "twelve wide mobile six wide tablet four wide computer three wide large monitor two wide widescreen column" 

as Doubling is too rough, I prefer to use Responsive Width, 12 columns will have a better transition

**Comment by jlukic** [comment]
12 and 16 are both fine column counts. I understand Bootstrap and Foundation use 12 so this might be a more familiar number. Mathematicians seem to like both 12 and 16 for their abundance of divisors 
http://en.wikipedia.org/wiki/Table_of_divisors#Key_to_the_tables

SUI went with sixteen columns as part of its default theme, but like all other arbitrary decisions in the library this can be changed by adjusted by modifying the frameworks variables. 

The global variable [``@columnCount``](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L147) affects all [calculated column widths](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L397) in all modules. So setting ``@columCount`` to 12 for example, would adjust 12 wide to be 100% 

```less
@twelveWide     : (12 / @columnCount * 100%);
@twelveWide: 12/12 * 100%;
@twelveWide: 100%;
```

**Comment by faller** [comment]
thanks a lot
