### ISSUE TITLE
Search with local source returns all data (within maxResults limit) in ver.1.5.0 

### ISSUE THREAD

**Issue by loredanacirstea** [Semantic-Org/Semantic-UI#1542]
(Happy New Year! and thanks for the .dropdown's `allowCategorySelection`)

Ver.1.5.0 behavior for .ui .search with local content : http://jsfiddle.net/loredana_cirstea/56h8kenL/1/

* if I search for 'pp' I get the undiscriminated source options within the maxResults limit

Ver.1.4.1 : http://jsfiddle.net/loredana_cirstea/4Lefzoof/3/

* if I search for 'pp' I get "No results" (correct output)

**Comment by jlukic** [comment]
Thanks and fixed
