### ISSUE TITLE
Github blocked.

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#1543]
Hi Jack, Github is blocked from my country, it's only a matter of time till my ISP enforces the rule, so if you notice very less contributions from people from my country (India), now you know why. 

Luckily I'll be gone to Singapore for a while, and I'll be able to contribute from there. But, thought I'd let you know anyway!

Cheers. (Happy new year to you, btw :) )

**Reference:**

https://www.techdirt.com/articles/20141231/02075529554/indian-government-orders-32-web-sites-blocked-including-github-archiveorg-pastebin-dailymotion-vimeo.shtml

**Comment by vinz243** [comment]
Perhaps it will be blocked only in DNS so using OpenDNS might bypass the issue, no? Or there is still the VPN solution.

**Comment by jlukic** [comment]
I read about GitHub being blocked, its really unfortunate. Let's hope the government resolves things reasonably.

**Comment by ph7vc** [comment]
You could buy a cheap DigitalOcean server in America and use it as a proxy. Just a thought

**Comment by dsignr** [comment]
Nevermind, I'm now back to SG, so shouldn't be an issue anymore. Thanks everyone :+1:
