### ISSUE TITLE
Document configuration needed to prevent sidebar from dismissing on clickaway

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1544]
In the past, clicking outside a sidebar did not dismiss it. As of 1.2 it seems the sidebar is getting dismissed by default.

How can one configure the sidebar to stay open when clicking outside it?

**Comment by cowwoc** [comment]
I figured it out. One needs to set the following settings:

```
closable: false,
dimPage: false
```

Please document these two settings.

**Comment by jlukic** [comment]
See #1528 was waiting for PR

**Comment by jlukic** [comment]
Fixed in ``1.5.1``
