### ISSUE TITLE
HTML5 Custom Elements

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#1545]
Since HTML5 allows us to define custom tags, has any thought been given to using custom tags to make simpler markup for Semantic?

I could see it being useful in defining custom form input elements like a calendar, spinner, slider, etc. 

Or would this be better suited as a third party add-on that users could choose to use?

**Comment by peterrobertz** [comment]
my first thought was angular directives, they are great for such a job.

**Comment by jlukic** [comment]
This is W3C's web components spec. If you havent looked at "Shadow DOM" spec I encourage you to check it out. 

I have doubts about W3C web component adoption given the obtuseness of the spec. I've addressed my thoughts on the nature of standards bodies in other threads, so I'll avoid sounding like a broken record or ideologue.

I'll be in the audience at the W3C TAG Q&A in NYC on Wednesday if anyone is around.
