### ISSUE TITLE
Tab 1px issue

### ISSUE THREAD

**Issue by hakeem86** [Semantic-Org/Semantic-UI#1546]
When using the tab module and have multiple tabs. The first tab is always around 1px greater then rest of the tabs in height ..
Check demo in kitchen sink

**Comment by fpayer** [comment]
The first tab is not 1px greater than the rest of the tabs. It is the active tab that is 1px great (which happens to be the first tab by default). I am under this impression that this is probably due to the fact that the active tab has a border that is 1px wide.

**Comment by hakeem86** [comment]
when I select tab 2 or 3 they will be the active tab, so they would also be 1px greater. So it should not jump 1px when switching.. Is doesn't happen when you switch between tab 2,3 and 4 etc

Try switching between tab "first" and "second" then try between "second" and "third" 
http://semantic-ui.com/modules/tab.html#/examples

**Comment by jlukic** [comment]
Caused by adjacent attached rule not being applied on first tab
```less
.ui.segment.attached + .ui.segment.attached:not(.top) {
    border-top: medium none;
}
```
