### ISSUE TITLE
Visible error messages are not shown at forms

### ISSUE THREAD

**Issue by anestv** [Semantic-Org/Semantic-UI#1548]
The same happens with success, warning and info messages.
[jsfiddle](http://jsfiddle.net/rp1h6hhr/1/)

The `.ui.form .error.message { display: none }` css rule has more importance than `.ui.message.visible { display: block }`

I don't know if this is intended or not, but I think .visible messages should always be visible

**Comment by jlukic** [comment]
Yeah. I think the counterpoint is using ``!important;`` confuses people who try to hide with ``$('.message').hide();`` and find that it doesn't work. 

Most likely the "best" solution is something like what's done with button loading. Maxing out the specificity without using ``important``, ala ``.ui.visible.visible.visible.visible.visible.message``. If only there was a way to specify css selector specificty ala ``z-index``...

**Comment by jlukic** [comment]
Fixed in `next`

**Comment by faller** [comment]
someting interesting

**Comment by jlukic** [comment]
Release a couple hours ago
