### ISSUE TITLE
Getting started guide for non developer

### ISSUE THREAD

**Issue by raitucarp** [Semantic-Org/Semantic-UI#155]
Hmm, I think It's very confusing for non-developer that just starting use semantic-ui (I am developer, though). Consider these:
- User download build kit (build/semantic.zip)
- User want to use semantic-ui without installing node / docpad things.
- After user extract semantic.zip, user wants to create html ui from scratch, user includes semantic.min.css and semantic.min.js from packaged folder, then creating simple html, starts with copy menu html code from http://semantic-ui.com/collections/menu.html:

``` html
<div class="ui menu">
  <a class="active item">
    <i class="home icon"></i> Home
  </a>
  <a class="item">
    <i class="mail icon"></i> Messages
  </a>
  <a class="item">
    <i class="user icon"></i> Friends
  </a>
  <div class="right menu">
    <div class="borderless vertically fitted item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <div class="ui dropdown item">
      Language <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item">English</a>
        <a class="item">Russian</a>
        <a class="item">Spanish</a>
      </div>
    </div>
  </div>
</div>
```

And...  not as expected, ugly menu.. confusing about where is reset stylesheet? Why this ui ugly? etc..

I think you guys, consider for non developer to use semantic ui from scratch rather than forcing them to use node / docpad.

Look at bootstrap http://getbootstrap.com/getting-started/, they just includes the stylesheet link on header, and viola ready to use.

What about semantic ui? Getting started page or this http://semantic-ui.com/project/development.html is not friendly format for non-developer (or maybe noobs out there)

**Comment by samayo** [comment]
:+1:

**Comment by meepou** [comment]
Totally agree

**Comment by dheeruChd** [comment]
Hi @jlukic ,
Is there any update for using Semantic UI like twitter bootstrap ie:- simply including in html and using it.

Thank you,
Dheeraj Kumar Singh

**Comment by hammy2899** [comment]
@dheeruChd You can include SUI from a CDN like [cdnjs](https://cdnjs.com/libraries/semantic-ui) and start using instantly.
