### ISSUE TITLE
Sidebar with static / unmoved header

### ISSUE THREAD

**Issue by pavankumarlpersonal** [Semantic-Org/Semantic-UI#1556]
When the context of the sidebar is other than 'body' sidebar should be absolutely positioned to context rather than fixed positioning.

**Comment by jlukic** [comment]
I'm pretty sure it needs to stay ``position: fixed`` but context needs ``transform: translate3d(0, 0, 0);`` to make a new ``fixed`` context.

**Comment by pavankumarlpersonal** [comment]
will provide fiddle soon

**Comment by jlukic** [comment]
See my comment here https://github.com/Semantic-Org/Semantic-UI/issues/1567#issuecomment-68802389
