### ISSUE TITLE
[Accordion] Improve Performance

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#1558]
Hi all,
My web app has performance issue when inserting mass data in accordion branches- it can take 5-6s on a laptop browser up to 10-15s on mobile device (see attached screenshot). According to the accordion JS code and docs, there are some event listener for every dom mutation, which I suspect is the cause of the performance degradation. What is the recommended approach for mass data inserts into an accordion? Can we create some JS API to temporarily suspend the current behavior and resume it after the mass insert is done.

![selection_033](https://cloud.githubusercontent.com/assets/5327044/5602800/81f933ae-931a-11e4-8a7f-0181cdb0ad32.png)

**Comment by jlukic** [comment]
I'd be curious if you comment out lines [``100-103``](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/accordion.js#L100) whether your performance.improves. Accordion also has two other possible flaws. 

* It uses JS animations (animating ``height:auto`` is not currently possible with css) 
* it animates child element opacity, which may perform poorly if there are *lots* of child elements.

**Comment by hrstoyanov** [comment]
Jack,
commenting out thee 3 lines did not help much:
//observer.observe(element, {
//              childList : true,
//              subtree   : true
//            });

I will look into this a bit more ...

**Comment by jlukic** [comment]
Those were the lines that attached the DOM Mutation Observers. I don't think they should be slow when only "watching" changes on one element, the ``ui accordion``

**Comment by mikocot** [comment]
Just after moving to 1.x I was surprised with the performance of accordions as well. Was there any significant change to its logic?

Even with powerful development machine (2x xenon + 24GB mem) you can see animation steps and lags while opening. I get impression it was better with 0.x versions. Especially visible if accordion is big or cause resizing of the page

**Comment by hrstoyanov** [comment]
I still have not done detailed analysis,  but if I switch to tables,  my data renders real fast (1s).  I was originally thinking of adding two APIs to the accordion js module:
beforeMassChange() 
afterMassChange() 
Between these calls, all fancy accordion stuff will be suspended,  and resumed later... Not sure it is possible though...

**Comment by jlukic** [comment]
It would help if you can create a JSFiddle example that reproduces the poor performance which I can use to debug.

**Comment by hrstoyanov** [comment]
Jack,
I see you have done some fixes. Let me try 1.6.x when you release it first. If it does not work, I will get you a good way to test it.

**Comment by jlukic** [comment]
There's some adjustments but I'm unclear if anything is 'fixed' per-se since perceived performance issues are a bit subjective.

**Comment by kvetoslavnovak** [comment]
I can confirm that on iPad 2 there is visible accordion lagging as well. Pre 1.0 versions seened faster.

**Comment by megamaiku** [comment]
This issue is still present. I have a retina MacBook, which I believe shuts off 3D acceleration. Wondering if there's anything I can do to improve this issue. Thanks.
