### ISSUE TITLE
Initialization of variable @theme in file theme.less

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI#1559]
I'm pretty new to Semantic UI (1 week), and I'm trying to understand what happens.

The (partial) folder hierarchy in ```/src/``` is:
 ```less
site/@type/@element
themes/@site/@type/@element
```
For example: 
```less
site/views/statistic.variables
site/views/statistic.overrides
//and
themes/default/views/statistic.variables
themes/default/views/statistic.overrides
```

So ```@site``` is the highest level.
And all the ```@element.variables``` and ```@element.overrides``` files are the lowest level.

But that doesn't fit with what I'm seeing in the main theme-imports file, ```theme.less```.

You first initialize ```@site``` with ```@element``` (highest with lowest) on ```line 5``` in ```src/theme.less```:
```@theme : @@element;```
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/theme.less#L5

And then you use ```@theme``` (```=== @element```) at the highest level, and ```@element``` at the lowest level, on these 2 lines further down:
```@import "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";```
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/theme.less#L19

```@import "@{themesFolder}/@{theme}/@{type}s/@{element}.overrides";```
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/theme.less#L46

Why are you initializing ```@theme``` with ```@element``` on ```line 5``` in ```src/theme.less```?
Shouldn't line 5 be ```@theme : @@site;```?

P.S. Apologies for the length of this post.

**Comment by jlukic** [comment]
``@@element`` is the same as the value of the variable set as `@element``. 

So if `@element` is `button` then ``@@element`` is the same as  `@button` which is set in ``theme.config`` as `default`

Each less file is compiled separately, each running ``theme.less`` in the context of the `@element` which is set in each definition.

**Comment by Lisa-Williams** [comment]
I know about the double @@ in Less.

You used the value ```button``` as an example for ```@element```.
I used as an example ```statistic```.
But, referring to line 19 and 46 again (see above), I still do not see a ```statistic```, nor ```button``` folder in the ```themes``` folder.

If:
```@theme``` === ```@element``` === ```button```.
```@theme``` === ```@element``` === ```statistic```.
and so on.
```Less
//Then
@import "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";
//becomes
@import "themes/button/elements/button.variables"
@import "themes/statistic/views/statistic.variables"
//and
@import "@{themesFolder}/@{theme}/@{type}s/@{element}.overrides";
//becomes
@import "themes/button/elements/button.overrides"
@import "themes/statistic/views/statistic.overrides"
```
I'm probably wrong, but I can't see those import paths.
If ```@theme``` would be initialized with ```@site```, or ```@site``` would be used directly instead of ```@theme``` the import paths would be all there.
```@site``` === ```'default'```|```'classic'```|```'chubby'```|```'bootstrap3'``` etc.

**Comment by jlukic** [comment]
You are mistaking the parsed values.

```Less
//Then
@import "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";
//becomes
@import "src/themes/default/elements/button.variables"
@import "src/themes/default/views/statistic.variables"
//and
@import "@{themesFolder}/@{theme}/@{type}s/@{element}.overrides";
//becomes
@import "src/themes/default/elements/button.overrides"
@import "src/themes/default/views/statistic.overrides"
```

because
@theme = (@element => @statistic => 'default').

**Comment by Lisa-Williams** [comment]
Aaaaargh.
I did again. Forgot to prepend the second @-sign to the value so it becomes a variable.
Apologies for this.

**Comment by jlukic** [comment]
No worries, nice to have this archived on GitHub in case this comes up again. 

Perhaps will include in upcoming FAQ

**Comment by Lisa-Williams** [comment]
OK then I'm safe.
Thanks for pointing out that @site is connected to the definitions and not to the generated site folder.
Didn't know that.
