### ISSUE TITLE
popup click event not working

### ISSUE THREAD

**Issue by septem123** [Semantic-Org/Semantic-UI#1560]
error code
https://github.com/Semantic-Org/Semantic-UI/commit/096f44a1c78645e8e6457b4e097ddf52fbd5fb8c

![picture_1420337739605](https://cloud.githubusercontent.com/assets/6112395/5604500/a9b5543c-93fa-11e4-9ea9-969de1517d12.jpeg)

$offsetParent is undefined

JSFiddle link
http://jsfiddle.net/fx2y9t3w/4/

**Comment by jlukic** [comment]
Can you provide a test case? There's a JSFiddle link to fork in readme.

**Comment by septem123** [comment]
JSFiddle link
http://jsfiddle.net/fx2y9t3w/4/

**Comment by jlukic** [comment]
Fixed in ``next``
