### ISSUE TITLE
Incorrect layout for <button>

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1563]
Testcase: http://jsfiddle.net/efp8z6Ln/107/

The first line demonstrates that `div.ui.button` gets laid out correctly (all three elements on the same line). The second line demonstrates that `button.ui.button` gets laid out incorrectly (gets pushed into the subsequent line).

Expected behavior: both cases should get laid out the same.

**Comment by jlukic** [comment]
``<button>`` does not support `table-cell``. This is an issue with the implementation of the tag by browsers. Not sure the issue id #, but I'm sure a quick search will show you.

**Comment by cowwoc** [comment]
@jlukic Does the specification prevent it from supporting `table-cell`? Or is this an implementation detail that will get fixed in the future?

Either way, please reopen this issue and document this limitation in the `Button` documentation page. Thanks!

**Comment by jlukic** [comment]
It's not mentioned in [the button spec](http://www.w3.org/TR/2011/WD-html5-20110405/the-button-element.html#the-button-element) its just [not implemented by browsers](http://stackoverflow.com/questions/19541639/setting-a-buttons-display-as-table-cell) for reasons unknown.

**Comment by cowwoc** [comment]
@jlukic Super. So all that's left is for you to document this limitation in the `Button` page. Thanks!

**Comment by jlukic** [comment]
Added http://www.semantic-ui.com/elements/input.html#action

**Comment by cowwoc** [comment]
@jlukic Very nice. Thank you!

**Comment by MohammadYounes** [comment]
How about this workaround! http://jsfiddle.net/u2xdzb4q/

**Comment by cowwoc** [comment]
@MohammadYounes Not bad.

@jlukic Is there any way to fold this workaround into Semantic-UI so users get a similar effect automatically?

**Comment by larsbo** [comment]
Another working solution found in the mentioned stackoverflow thread: http://stackoverflow.com/a/19624550

It needs just an additional display:none rule and also works without javascript.
Here is a working semantic ui example: http://jsfiddle.net/yog2n9zL/1/

**Comment by MohammadYounes** [comment]
@larsbo What I was trying to accomplish was accessibility! I'll try to explain:

1. In your fiddle, focus the textbox then press tab and you'll notice the focus goes to the address bar as the textbox is the last tab accessible element in the page. In chrome adding a `tabindex="0"` to the label has no effect, try changing the `label` into a `div` after adding `tabindex="0"` and the element will be accessible via `tab` key ..

2. Browser buttons are also clickable by pressing the `spacebar` key, even if the `div` has the focus, pressing `spacebar` will not fire the click event. Try it after adding this script:
  ```javascript
 $('.ui.button').click(function(){alert('clicked');});
  ```

 Thanks for sharing.

**Comment by cowwoc** [comment]
I agree with @MohammadYounes. This issue is all about accessibility.

**Comment by larsbo** [comment]
Ok, that's right, I didn't thought about the `tabindex` problem. My first goal was a simple solution that should also work without Javascript. Because in my opinion any solution with a `div` element listening for click events has bad accessibility, too.

I updated my fiddle to support `tabindex` as well. This version uses an invisible but accessible submit button:
http://jsfiddle.net/yog2n9zL/2/
(The button shows an outline on focus for visible feedback only.)
Looks fine on latest Firefox, Chrome & IE.
