### ISSUE TITLE
Multiple site styles (CSS files only) in the same dist folder.

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI#1565]
I created a design in the ```src/site/``` folder.  It's the light version of the theme.
Now I want to restyle/change the look. Only the look. No layout or size changes, etc.

I want to change the colors, gradients, etc through a second set of variables and overrides. (And a few light colored interface images with dark colored ones.)
This would be the dark version of the theme.
And I would want this dark version to be a second css stylesheet in the ```dist/``` folder`.
Next to the light version.
Everything else would be re-used (js, fonts, icon fonts, etc).

Light version: ```semantic.css``` and ```semantic.min.css```
Dark version: ```semantic-dark.css``` and ```semantic-dark.min.css```

1) Is it possible to let SUI create multiple stylesheets in the ```dist/``` folder?
2) Is it possible to have unlimited of these CSS only style variations?
3) Is it possible to have more than one ```src/site``` folder?
For example ```src/site```, ```src/site2```, ```src/site3```, .....
Or ```src/site```, ```src/dark/site```, ```src/gray/site```, .....

**Comment by jlukic** [comment]
SUI isn't designed to allow outputting multiple themes for one element. 

I plan to keep the build tools accommodating a "one to one" workflow between source and distribution versions. If you need to output multiple versions, I recommend creating your own process or manually copying `dist` output after saving theme changes.

**Comment by Lisa-Williams** [comment]
I wasn't asking to fix or change anything.
I was asking if it was possible. Meaning with the current folder structure and gulp.js processing.
My 3rd question was to find out if the Gulp processing would only watch and process files in a folder named ```site```. (Meanwhile I already tested that this is true)
If so, I only need to backup the original ```site``` folder as ```site-default```.
And then copy it to ```site-light``` and ```sight-dark```.
When working on the light version of the theme I just rename ```site-light``` to ```site```.
Similar for the dark version. Or any other version.
