### ISSUE TITLE
Collapsing disabled makes cell useless

### ISSUE THREAD

**Issue by mikemix** [Semantic-Org/Semantic-UI#1566]
I have action icons inside table cell. Marking that cell as "collapsing disabled" makes these action icons non clickable and useless in effect

```
<td class="collapsing disabled">
<a href="#"><i class="ui hide icon"></i> Hide</a> 
<a href="#"><i class="ui unhide icon"></i> Unhide</a> 
</td>
```

**Comment by jlukic** [comment]
There is no variation called ``collapsing disabled``. 

There is only disabled [which removes mouse events](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/table.less#L411)

**Comment by mikemix** [comment]
Ok I took that from the Table documentation at http://semantic-ui.com/collections/table.html

**Comment by jlukic** [comment]
I'll remove the confusing line. It was just formatting the line to appear disabled as well.
