### ISSUE TITLE
Popups stopped working after UPDATING

### ISSUE THREAD

**Issue by tecoad** [Semantic-Org/Semantic-UI#1569]
Hi there,

just updated some of my repo and my Popups stopped working, specially the HTML ones.

Just checked http://semantic-ui.com/modules/popup.html#/definition and saw it's not working there either (ie. flowing popup).

May someone provide any help?

Regards,

**Comment by jlukic** [comment]
There was a bug introduced in `1.5.0` where popup offset parent would be undefined is using a defined popup with same offset parent as activating element. 

Fixed in patch later today.
