### ISSUE TITLE
Vertical Divider breaks out of container using demo code

### ISSUE THREAD

**Issue by christianmagill** [Semantic-Org/Semantic-UI#1570]
I'm having an issue getting a vertical divider to stay within the grid, even using the demo code directly.

http://jsfiddle.net/dp502gyd/

**Comment by christianmagill** [comment]
Adding relative positioning to the grid container fixes the issue. Not sure if there is a better way to fix this within the framework itself.

**Comment by jlukic** [comment]
Yeah there should be a note about that in docs. I think for a while ``position: relative`` was built into grid. 

But it causes people to be trapped into the position system of the closest grid, which is not always intended.

**Comment by jlukic** [comment]
Added to docs
