### ISSUE TITLE
[Divider] Chrome Issues on Resize of Vertical / IE Safari Display Issues

### ISSUE THREAD

**Issue by christianmagill** [Semantic-Org/Semantic-UI#1576]
http://jsfiddle.net/dp502gyd/

After resizing down to force horizontal divider, the right column does not return upon resizing back up.

**Comment by jlukic** [comment]
Appears to be a webkit only bug due to some sort of miserly reflow on media query display changes.

**Comment by jlukic** [comment]
This was fixed in Chrome 41. At least in my testing.

**Comment by sszdh** [comment]
Same problem in chrome 43!

**Comment by jlukic** [comment]
Here's fiddle against `2.0` branch where everything is fine.
http://jsfiddle.net/rc98x3rv/

**Comment by sszdh** [comment]
@jlukic Thanks. So should I upgrade to 2.0?
