### ISSUE TITLE
Search field validation does not work and makes search field disappear on submit.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI#1578]
When a search field is used in the form and validation is added on it, it does not show the validation message and the field disappears when form is submitted.

I have localised the error, being  'prompt' class on the search input responsible for the problem.

**Comment by jlukic** [comment]
I can understand what you're describing, but would you be so kind as to provide a test-case with JSFiddle (link to fork in readme) to facilitate debugging?

**Comment by jlukic** [comment]
Thats pretty bizarre. I'll take a look at it.

**Comment by tomitrescak** [comment]
The reason is the use of "prompt" class to specify the prompt for the search field and which is being hidden by the validation script.

**Comment by jlukic** [comment]
Fixed in `next`
