### ISSUE TITLE
Adding UI Effects to anchor or button

### ISSUE THREAD

**Issue by oknoorap** [Semantic-Org/Semantic-UI#158]
Hi, I wish semantic ui adding effects, i've found inspiring good resource 

http://tympanus.net/Development/CreativeLinkEffects/
http://tympanus.net/Development/CreativeButtons/

proposal class sample

```
<a class="ui button fx transform-3d">...</a>
<a class="ui button fx slide-up">...</a>
```

The technology will never moving backwards, so the browser too, I think css3 is our era, and we must applying css3 into semantic ui, I'm bootstrap and foundation user for years, if semanticui adding more values and options for frontend developers, semanticui will become more popular.

Thanks.

**Comment by sgarbesi** [comment]
Does this work on anchor hover fx?
