### ISSUE TITLE
MultipleModal  problem, the second modal behind the first modal

### ISSUE THREAD

**Issue by suziwen** [Semantic-Org/Semantic-UI#1584]
when the second modal content is too long to need window scrollbar , the second modal position become behind to the first modal.

**Comment by jlukic** [comment]
Can you please provide a test-case, you can fork the JSFiddle in the readme. This will help in debugging.

**Comment by suziwen** [comment]
http://jsfiddle.net/suziwen/vpg04zj0/4/

**Comment by faouzzz** [comment]
i have a same problem. but not behind, it appear below the first so i need to scroll down to view it.
