### ISSUE TITLE
Horizontal divider broken on IE11

### ISSUE THREAD

**Issue by riophae** [Semantic-Org/Semantic-UI#1585]
The left part of divider was missing.
http://semantic-ui.com/elements/divider.html#horizontal-divider
![default](https://cloud.githubusercontent.com/assets/1289884/5647067/6ecc4fcc-96bd-11e4-87c0-7fc639966630.PNG)

**Comment by jlukic** [comment]
:( IE

**Comment by riophae** [comment]
It's the same on Safari 6 for OS X.. Another bad news.

**Comment by jlukic** [comment]
Moving into #1576
