### ISSUE TITLE
JavaScript: The $.size() method is deprecated as of jQuery 1.8.

### ISSUE THREAD

**Issue by vsn4ik** [Semantic-Org/Semantic-UI#1586]
The `.size()` method is deprecated as of jQuery 1.8. Use the `.length` property instead.

See: http://api.jquery.com/size/.

**Comment by jlukic** [comment]
Thanks. "Length" is such a funny term for the size of an array. Nonetheless, nice to avoid the overhead and use of deprecated function calls.
