### ISSUE TITLE
Vertical Divider does not come back from 'mobile' layout

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#1588]
I've been playing with vertical divider, when I run out into this:

![semantic-divder](https://cloud.githubusercontent.com/assets/9884950/5648904/503cc80a-9692-11e4-8ff7-79cdb516b3ee.PNG)

Using the example in divider section of semantic-ui main page. Just resize the page so the vertical divider becomes horizontal. Then slowly resize back. At one point horizontal divider becomes vertical once again, but the right content stays below.

If you resize back to the original size it should come back. However in my case it does not at all. Maybe I can prepare jsfiddle later. Anyway, seems to be a bug, as this middle stage looks weird.

Cheers!

**Comment by jlukic** [comment]
See #1576 

Thanks for the additional information.
