### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by LeonardoCiaccio** [Semantic-Org/Semantic-UI#1589]
Hi bro, i love semantic-ui but some documentation are incomplete.

How i fire "onShow" callback of sidebar ? online no documentation found ;)

**Comment by jlukic** [comment]
See #1571, more docs are on the way

```javascript
$('.ui.sidebar')
  .sidebar({
    onShow: function() {
      // do something
    }
});
```

**Comment by LeonardoCiaccio** [comment]
@jlukic not work i tested it before my request, please check this example and edit if you right

http://jsfiddle.net/leonardo_ciaccio/b6v2e9wf/

**Comment by Lisa-Williams** [comment]
I fixed your [fiddle](http://jsfiddle.net/2w03oy1t/3/)
You didn't specify your main content wrapped in an element with class ```pusher```.

SUI tried to add it for you, but failed with this error:
```Text
Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element     semantic.min.js:15
C.error     semantic.min.js:15
```

**Comment by LeonardoCiaccio** [comment]
@Lisa-Williams thanks !

**Comment by Lisa-Williams** [comment]
BTW, the same error happens in the [repeated issue](https://github.com/Semantic-Org/Semantic-UI/issues/1600) you opened.
```Text
Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element     semantic.min.js:15
C.error     semantic.min.js:15
Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag <div class=​"ui left vertical inverted labeled icon sidebar menu pointing thin uncover animating visible">​…​</div>​     semantic.min.js:14
C.setup.layout     semantic.min.js:14
```

**Comment by Lisa-Williams** [comment]
Oh, you already responded while I was adding my second comment.
Happy sidebarring.

**Comment by scienceasdf** [comment]
+1. I encountered the same problem.
