### ISSUE TITLE
Popup: responsive width?

### ISSUE THREAD

**Issue by mxth** [Semantic-Org/Semantic-UI#1590]
With wide popup on small screen (popup max-width > screen width), there's the error "No visible position could be found for the popup". Can we make popup responsive so it will take full width when popup max-width > screen width?

**Comment by mxth** [comment]
Isn't it will make a portion of the popup out of the view?

**Comment by jlukic** [comment]
I'm not understanding. I thought the question was how to make a popup show if it is larger than the screen size. Can you provide a test case?

**Comment by mxth** [comment]
It's more about how to make a popup show nicely without losing the content (as with lastResort).

I made an attempt to demonstrate this
See: http://jsfiddle.net/6murnr7n/22/

**Comment by jlukic** [comment]
Sorry to be as dull as a block of wood, but I still don't understand. I'm seeing both examples appear as expected. Are you looking for a way to make the content fit the full page width?

You can use ``ui fluid popup`` to fit the page exactly
http://jsfiddle.net/jvt38wqL/

Wide popup has a specified max-width which in the default theme is `350px`

**Comment by mxth** [comment]
This table would summarize what I were talking about.

wide popup setting  | popup's width on small screen (<350px) | large screen
------------- | -------------
none  | not displayed | 350px
lastResort  | 350px | 350px
fluid | screen width | screen width
I want | screen width | 350px

And can you check on your example with fluid popup? In small screen, it's only displayed once and its width is a little bit larger than the page width. Anyway, it's another problem.

**Comment by jlukic** [comment]
I understand now, its specifically at widths < 350px where it is not appearing

Fixed in ``next`` 
http://jsfiddle.net/y7zz7can/

**Comment by ciciandjojo** [comment]
now have a deal with lastResort
