### ISSUE TITLE
Old buttons

### ISSUE THREAD

**Issue by ThisNameWasFree** [Semantic-Org/Semantic-UI#1592]
Hello guys. I'm using 0.19.0 and I like it's elements (like in http://ehkoo.github.io/semantic-ui-examples/theme, "Buttons" section). New buttons... they don't have any soul at all. I really can't understand new design. Is there any way to download new semantic UI with an old button design?

**Comment by jlukic** [comment]
You can use the legacy version
https://github.com/Semantic-Org/Semantic-UI/archive/pre-release.zip
http://legacy.semantic-ui.com

You can also try the "classic" theme of button or create your own theme by customizing variables

Button has 168 variables available for customization which is enough for doing just about anything.
