### ISSUE TITLE
Input blurred when closing popup

### ISSUE THREAD

**Issue by aramk** [Semantic-Org/Semantic-UI#1594]
Since v1.0, when a popup is added to an input and that popup is hidden, the input is blurred. If you were typing something in a form and you cause the popup to hide by scrolling or moving your mouse, you lose focus on the input. I've fixed this behaviour below:

```
$(popupInputs).each ->
  $popupInput = $(@)
  # Manual control over popup to prevent losing focus when closing it in Semantic-UI 1.0.
  $popupInput.popup({delay: 500, on: 'manual', content: $popupInput.data('desc')})
  $popupInput.on 'mouseenter', ->
    $popupInput.popup('show')
  $popupInput.on 'mouseleave', ->
    isFocused = $popupInput.is(':focus')
    $popupInput.popup('hide')
    $popupInput.focus() if isFocused
```

I couldn't find anything in docs, but I'm guessing it's calling .blur() on the target or something when hiding.

**Comment by jlukic** [comment]
Looks like this was added with `hideOnScroll` 73b60bcc3b8f9ea77019364d0a3d669a337fa41c

I am not sure the reasoning at the time. But I'll remove it.

**Comment by aramk** [comment]
Awesome, thanks for that!
