### ISSUE TITLE
Attached Segment top border detection

### ISSUE THREAD

**Issue by gabormeszoly** [Semantic-Org/Semantic-UI#1596]
Hi Jack,
Missing top border at the second Segment Group. I dont know what version is the correct,first or second ... elements/segment.less (line 559)

thanks, Gabor
JSFiddle here: http://jsfiddle.net/gabormeszoly/koj05k6f/1/

**Comment by jlukic** [comment]
It looks like you are doing `attached` -> `bottom attached` -> `attached` -> 'bottom attached'

To have all 4 connected you could do `top attached` -> `attached` -> `attached` -> 'bottom attached'

To have 2 groups you could to  `top attached` -> 'bottom attached' -> `top attached` -> 'bottom attached'

**Comment by gabormeszoly** [comment]
soooooo simple :)
Thanks Jack!
