### ISSUE TITLE
[Form] Add Easier Handling of Error State

### ISSUE THREAD

**Issue by changemewtf** [Semantic-Org/Semantic-UI#1597]
Use case:

I am submitting a form within a modal via AJAX and leaving it on the screen until the AJAX request returns. It's possible for there to be server-side errors when there were no client-side errors.

When the AJAX request returns with errors, I call `$.form('add errors', errors)` where `errors` is an array of the messages returned by the server.

I was surprised to find that the errors were correctly appended to the error message list but still did not appear on the screen.

Apparently the enclosing form must be "in an error state", which appears to be determined entirely by the presence of the `error` class. There does not appear to be any other programmatic way to set the error state of the form.

Perhaps this is more of a partially-completed feature than a bug; if there was no way to programmatically add errors, then I would have been inclined to do all of is manually in the first place. I'm not sure what to expect if I allow the user to re-submit: will the error list be cleared?

**Comment by jlukic** [comment]
There are some other posts about this #959  #907 #779), but basically form is one of the older modules and in need of rewrite. Error handling is admittedly a bit backwards.

I'll take a look at this time permitting. My goal is to rewrite form before refactoring. We have an RTL and meteor integration launch this week so I have my hands full a bit right now.

**Comment by mcantor** [comment]
Yeah, this is deceptively tough, especially when you think about revalidation after manual error adding: should the added errors be cleared? Left on the top? On the bottom? Not sure I have any good suggestions; I ended up just managing a separate error list myself. Thanks for the quick triage.

**Comment by avsm** [comment]
I just ran into this as well -- the form API works great at client side validation, and an Ajax JSON error is parsed and added to the form errorlist -- but there's no way to switch the form into an error state to flash up the server side error.  Is there a workaround to show the message from the server side before the refactoring (or I guess I could just switch to doing it all manually with jQuery if not)

**Comment by avalanche1** [comment]
+1

**Comment by specimen151** [comment]
+1

**Comment by alexbet** [comment]
+1

**Comment by soliveri** [comment]
+1
