### ISSUE TITLE
Some icons do not work.

### ISSUE THREAD

**Issue by fe3dback** [Semantic-Org/Semantic-UI#16]
for example: http://screenshot.su/show.php?img=020e2ad16a6ff85c2a957355f1dee106.jpg

google chrome
ver 29.0.1547.66 m (last)

**Comment by frapid** [comment]
The problem is still there for firefox browser. :(

**Comment by the0ne25** [comment]
And also in Google Chrome ... can't see any of the icons :/

**Comment by Fubinator** [comment]
Same problem here :/ it seems there are missing some classes. For example the "shop" icon class is not there. message and sidebar are also not working

**Comment by AhmadMWaddah** [comment]
with me Firefox Icons not working but same file work with chromium Ubuntu
