### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by LeonardoCiaccio** [Semantic-Org/Semantic-UI#1600]
Hi all, 'onShow' event in sidebar not work
http://jsfiddle.net/leonardo_ciaccio/b6v2e9wf/

**Comment by jlukic** [comment]
If you do not include a `<div class="pusher"></div>` element on page load it is automatically added on initialization with `requestAnimationFrame` to avoid blocking layout.

This means however any calls to sidebar that happen sequentially afterwards will occur **before the `requestAnimationFrame` call** and **before the page is setup**. 

I'll remove the use of `requestAnimationFrame` which will make the layout changes block rendering, but will also make it immediately available.

**Comment by jlukic** [comment]
Fixed in `next` version

**Comment by LeonardoCiaccio** [comment]
Special thanks
