### ISSUE TITLE
[Dropdown] Search Selection Produces Error with Numerical Values

### ISSUE THREAD

**Issue by zelenin** [Semantic-Org/Semantic-UI#1601]
```
<select>
<option value="1">Name A</option>
<option value="2">Name B</option>
</select>
```
if value is numerical (common case) search not works with error:

```
TypeError: value.match is not a function	

if( text.match(exactRegExp) || value.match(exactRegExp) ) {
	
semantic.js (line 3395, col 45)
```
I think it should cast value to string in search.
version 1.6.2

**Comment by jlukic** [comment]
I'm unable to reproduce any issues with the regexp with your code example. 
http://jsfiddle.net/sg482x91/

**Comment by zelenin** [comment]
@jlukic http://jsfiddle.net/sg482x91/1/ enter A to search
http://i.imgur.com/fVERfaM.png 
Firefox 34

**Comment by jlukic** [comment]
Ah, with search selection. Thanks

**Comment by jlukic** [comment]
While I was in there, I noticed regExp were also not escaping special characters. Fixed both bugs in `next`
