### ISSUE TITLE
Dimmer problem in Segment

### ISSUE THREAD

**Issue by gabormeszoly** [Semantic-Org/Semantic-UI#1603]
Hi,
Here is a dimmer example: http://jsfiddle.net/sedusch9/
The problem:
- Inverted dimmer not inverted (white)
- Dimmer content is missing

Thanks, Gabor

**Comment by jlukic** [comment]
You added the dimmer in ``ui image`` but then initialized the parent element.

Check this fiddle
http://jsfiddle.net/u3mftxrz/

**Comment by gabormeszoly** [comment]
Thank you Jack!
