### ISSUE TITLE
[Modal/Popup] Popup Positioning Issues Inside Modal

### ISSUE THREAD

**Issue by qhapaqorg** [Semantic-Org/Semantic-UI#1605]
when I add a popup inside a modal, this is positioned in an inappropriate place.

![sin titulo-1](https://cloud.githubusercontent.com/assets/6379532/5696030/8f39162a-998b-11e4-9412-eece13694f95.jpg)

**Comment by jlukic** [comment]
Can you please provide a JSFiddle example? I'm unable to confirm

There is a link to fork in the readme.

**Comment by qhapaqorg** [comment]
Here's an example.
http://jsfiddle.net/dxkernel/op8yv334/

apparently the popup is distorted when the "modal" is very long

**Comment by jlukic** [comment]
Thanks

**Comment by qhapaqorg** [comment]
I was able to fix my problem.
1. Remove inline: true;
2. add css .ui.popup {z-index: 1001; }

Do not quite understand how it works "inline: true," but according to documentation when "inline" is set to false the "popup" is attached to the body and removed after being hidden.
unfortunately when reviewing the HTML code, I saw that always generates a new html for the popup, and when the popup is hidden, it will not get deleted. This creates a lot of unnecessary code.

sorry for my writing, I am using google translate

![image](https://cloud.githubusercontent.com/assets/6379532/5731023/39499442-9b4d-11e4-8d66-11f2c8bac5fe.png)

**Comment by jlukic** [comment]
I've begun to recode popup to use its own calculation for `offsetParent`. There are issues with `offsetParent` in jQuery when an element is inside a 3D context. See https://github.com/jquery/jquery/issues/1765

Popups are by default generated on init and preserved in page. Popup preservation can be disabled by  adding `preserve: false`.  

I am considering setting this to `false` by default in `next` to avoid the clutter that might bother developers.

**Comment by jlukic** [comment]
Fixed in `next`
