### ISSUE TITLE
[Menu] Mixed Accordion + Menu cursor problem

### ISSUE THREAD

**Issue by gabormeszoly** [Semantic-Org/Semantic-UI#1606]
Hi,
Missing pointer cursor when Accordion and Menu is mixed.
JSFiddle here: http://jsfiddle.net/7sne24yp/

around line 85 in accordion.less
solution example:
.ui.accordion.menu a,
.ui.accordion .menu a {
    cursor: pointer;
}

thanks, Gabor

**Comment by jlukic** [comment]
I'm not seeing this issue currently.
