### ISSUE TITLE
npm install fails on safefs@3.0.6

### ISSUE THREAD

**Issue by ajanssens** [Semantic-Org/Semantic-UI#1608]
Hello, 

Downloaded the last version, i did update npm (npm install -g npm). But install fails.

 C:\web\Semantic-UI-1.6.2>npm install
> safefs@3.0.6 preinstall C:\web\Semantic-UI-1.6.2\node_modules\gulp-replace\nod
e_modules\istextorbinary\node_modules\safefs
> node ./cyclic.js
> v8flags@1.0.8 install C:\web\Semantic-UI-1.6.2\node_modules\gulp\node_modules\
v8flags
> node fetch.js
npm ERR! safefs@3.0.6 preinstall: `node ./cyclic.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the safefs@3.0.6 preinstall script.
npm ERR! This is most likely a problem with the safefs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls safefs
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\web\Semantic-UI-1.6.2
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

**Comment by mikocot** [comment]
works well for me, just updated from 1.6.0 to 1.6.2, try to make a fresh install in a new folder (without -g)

**Comment by anestv** [comment]
I had this issue too, but on 2 of my 3 setups.

At Windows 7 (npm 1.4.3) and Ubuntu 14.04 VM: npm install fails for this or a similar reason. At Ubuntu 14.04 remote (npm version 1.4.28, cloud9) I am also shown that an optonal dependency failed, but instead of halting, it procceeds and finises the installation successfully.

I don't know what's going on...

**Comment by jlukic** [comment]
In cases of npm failure delete ``node_modules/` then update. I've gotten `ENOENT` errors before, can be pretty erratic with npm sometimes.

**Comment by ajanssens** [comment]
Its fixed for me. Somehow my system path have been overwritten, so i was missing system32 and other "default windows" things. I can't explain why it caused so much problem with NPM but it's now fixed for me :) 

Thanks !
