### ISSUE TITLE
provide build-in support for angular

### ISSUE THREAD

**Issue by atian25** [Semantic-Org/Semantic-UI#1610]

**Comment by hrstoyanov** [comment]
Please do not contaminate SUI core with any specific framework (even the current use of jQuery is questionable). Many users are using SUI with other frameworks.

**Comment by pkorotkov** [comment]
@hrstoyanov +1

**Comment by jlukic** [comment]
There's a team for SUI-Angular integration. https://github.com/Semantic-Org/Semantic-UI-Angular

Core SUI will remain jQuery/pure only.

Additional development would only come with more community involvement. Frankly we're understaffed with our integrations.
