### ISSUE TITLE
[Progress] Issues with Ratio Label Display

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1611]
http://jsfiddle.net/efp8z6Ln/114/

$( '#usage' ).progress({
    value: 800,
    total: 1024,
    showActivity: false,
    label: 'ratio',
    text: {
        ratio: '{value} MB left'
    }
});

I use progress as "XX MB left", could it  be larger than 100 ? thank you.

**Comment by mikocot** [comment]
why dont you operate on percentage? It's not too hard to recalculate and I'd say its much more readable to keep it within 0-100 range :)

**Comment by faller** [comment]
@mikocot Thank you for answering. In the storage scene, the remaining capacity is very important. And I think the progress itself is already readable enough. So I want the label to show the value :)

**Comment by jlukic** [comment]
One of those fun single word fixes.

**Comment by jlukic** [comment]
Added new template value `{left}` for displaying the leftover percentage, or distance to total.

http://jsfiddle.net/su8a5nqt/
