### ISSUE TITLE
[Tab] Add onVisible Callback

### ISSUE THREAD

**Issue by numaanashraf** [Semantic-Org/Semantic-UI#1612]
Is there an event or callback after a tab has been toggled and shown?
Need this for using certain modules like sticky that need to be init/refreshed after they are visible.

**Comment by jlukic** [comment]
There are two callbacks for tabs that use remote endpoints `onTabInit` and `onTabLoad`. 

There are currently no callbacks for normal tabs. I'll take a look at adding this.

**Comment by jlukic** [comment]
@numaanashraf Thanks for your patience, I apologize for how long it took to address this. 

I've added two new callbacks, `onVisible` and `onRequest`. I've also renamed previous callbacks to conform to styles of other modules. 

Starting in `2.0`, `onTabLoad` is now `onLoad`, and  `onTabInit` is now `onFirstLoad`
