### ISSUE TITLE
Video Module load over https

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#1613]
I tried using the video module on my website only to discover that the video could not load because semantic uses http to retrieve Youtube videos on my https website. Chrome then blocked this request because it was an insecure connection. Is there any way to force the video module to use https or is this a limitation?

**Comment by jlukic** [comment]
That's a bug. Fixed in `next`

**Comment by jlukic** [comment]
Sorry tagged wrong commit..
