### ISSUE TITLE
[Tab] $.tab doesn't send the query arguments to $.fn.tab

### ISSUE THREAD

**Issue by Wexcode** [Semantic-Org/Semantic-UI#1614]
Kept getting an error when trying to call `$.tab('change tab', 'tab-name')`. Looks like the problem is here:

    // shortcut for tabbed content with no defined navigation
    $.tab = function(settings) {
      $(window).tab(settings);
    };

Should probably be:

    $.tab = function() {
      $(window).tab.apply(window, arguments);
    };

**Comment by Wexcode** [comment]
May or may not be worth saving `$(window)` outside of the function:

    var $window = $(window);
    $.tab = function() {
      $window.tab.apply(window, arguments);
    }

**Comment by Wexcode** [comment]
The obvious workaround for now was for me to simply call:

    $(window).tab('change tab', 'tab-name')

**Comment by jlukic** [comment]
I just did a quick test and $.tab seems to be functioning fine.
http://jsfiddle.net/kbyzycav/

Can you provide a test case.

**Comment by Wexcode** [comment]
I see. I was referencing the https://github.com/Semantic-Org/UI-Tab repo

https://github.com/Semantic-Org/UI-Tab/blob/master/tab.js#L727

**Comment by jlukic** [comment]
Ah yes.. Sorry this is my fault. Those repos are out of date and need tagged releases like main. I just havent hooked up the github API for creating tagged releases through gulp.
