### ISSUE TITLE
Dropdown in Tab Environment not updating Select

### ISSUE THREAD

**Issue by TimMcCauley** [Semantic-Org/Semantic-UI#1616]
Hi there,

I have a minor issue with the Tab Environment. If I add a dropdown menu to it and select an option, it will not visualize the selected element in the field, it will stay white with a blinking cursor in the input field (although it was updated). The clicked option will only show up if I click somewhere else and remove the focus from the input field. Is this a bug or am I missing something here? Using jQuery 1.10.2 with the newest semantic build.

      <div class="ui top attached tabular menu">
      <a class="active item" data-tab="first">Routefinder</a>
      <a class="item" data-tab="second">Travelling Salesman</a>
      </div>
      <div class="ui bottom attached active tab segment" data-tab="first">
        <div class="ui form start">
          <div class="field">
            <label>Home Address</label>
            <select class="ui search dropdown start">
              <option value="">start address</option>
              <option value="AF">Afghanistan</option>
              <option value="AX">Åland Islands</option>
              <option value="AL">Albania</option>
              <option value="DZ">Algeria</option>
              <option value="AS">American Samoa</option>
              <option value="AD">Andorra</option>
            </select>
          </div>
        </div>
      </div>
      <div class="ui bottom attached tab segment" data-tab="second">
        Second
      </div>
    <script>
      $('.menu .item')
        .tab();
      $('select.dropdown.start')
      .dropdown();
    </script>

**Comment by jlukic** [comment]
Your code appears to be working fine with SUI. Please create a test case to demonstrate, and verify your bug in the future. There is a link to fork in the readme.

http://jsfiddle.net/xmbxgftg/

**Comment by TimMcCauley** [comment]
Hi Jack,

I updated to the newest build and it works now. Thanks once again,

// Tim
