### ISSUE TITLE
Required option for Dropdown element

### ISSUE THREAD

**Issue by aprog** [Semantic-Org/Semantic-UI#1617]
Hi,

I'm using Dropdown module and got a need to show somehow that the field is required. I found an issue https://github.com/Semantic-Org/Semantic-UI/issues/516 that says about using labeled style and tried to use it. In the result I got next combination of Dropdown element and required asterisk:
![required-dropdown-2015-1-13--12-53-41](https://cloud.githubusercontent.com/assets/725146/5719679/47238fca-9b23-11e4-8acc-90e9730b6ba9.png)
As you can see the corner overlaps the dropdown arrow. I'm just curios is it correct way to mark Dropdown element as required or are there any alternatives?

Thanks in advance

**Comment by jlukic** [comment]
You can use `required field` which adds a red asterisks. The corner labels can get a bit kludgy when trying to attach itself to every possible ui.
