### ISSUE TITLE
"equal height row" breaks column width fluidity

### ISSUE THREAD

**Issue by mcantor** [Semantic-Org/Semantic-UI#1619]
Here is a [JSFiddle of the bug in action](http://jsfiddle.net/mcantor/ozk615p6/).

`table-cell`s definitely handle percent-based widths differently, but I'm not sure how. Couldn't figure out how the effective maximum is determined.

Setting `table-row` on the row might not be an effective solution since it seems to disable the use of padding.

**Comment by jlukic** [comment]
I think perhaps its time to transition to a mixture of flexbox and display:table-cell for fallback.

**Comment by jlukic** [comment]
Btw `table-layout: fixed` should prevent the table resizing, but it seems like in some circumstances with `table-cell` it doesnt appear to do anything.

**Comment by jlukic** [comment]
Added with flex in `next`

**Comment by mcantor** [comment]
Dude, you are a wizard. Thank you!
