### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by oknoorap** [Semantic-Org/Semantic-UI#162]
We need to add new element called testimonials, it will simplify our development progress, if we have a client who want to create layout such as landing page, this tag will help frontend developer a lot.

Example:
http://bashooka.com/inspiration/15-awesome-client-testimonial-designs/
http://dribbble.com/shots/1218760-Testimonials-Layout
http://dribbble.com/shots/1075307-Testimonial-Layout
http://dribbble.com/shots/304040-SB-Testimonials-Section

Example Tag:
```
<q class="ui testimonial fancy" data-name="Customer Name" data-avatar="http://img.com/src.jpg">
Testimonial Message here
</q>
```

If developer set ```data-dropcap="true"``` to the element, it will use ```:first-letter``` pseudo class.

Thanks.

**Comment by jlukic** [comment]
Merging into #1024
