### ISSUE TITLE
Having a Sidebar disables all autocomplete fields

### ISSUE THREAD

**Issue by kkerley** [Semantic-Org/Semantic-UI#1622]
I realized today that, after adding the sidebar to the site I'm building with Semantic, all the fields I have autocomplete enabled on no longer work. I'm using just plain jQuery autocomplete on a couple and then the third is with the tokenInput (from the Railscasts episode).

As soon as I remove the sidebar from the site (not even the JS that initializes it, just the code OF the sidebar), everything works again as expected. Is there some trick or some additional setting that must be enabled to allow autocomplete to work when a Sidebar is being used?

And it's not some unclosed tag or something else inside the sidebar. I removed everything apart from:

`<div class="ui vertical sidebar menu left">`
`</div>`
And the issue persists. But as soon as I've removed the code entirely, autocomplete is back to functioning perfectly.

**Comment by kkerley** [comment]
It is literally tied to the .sidebar class. I have all the content in my sidebar.
<div class="ui vertical sidebar menu left">
...
</div>

Removing "sidebar" so it's just:
<div class="ui vertical menu left">

Makes autocomplete work again. And it's not throwing errors. Everything is working fine on the backend and all that. It's just not showing the autocomplete dropdown on the fields in question for all (any) matching terms.

**Comment by jlukic** [comment]
I don't believe sidebar can affect autocomplete functionality.
http://jsfiddle.net/m2qrnovp/

Here's a thread on all the ways to trigger autocomplete:
http://stackoverflow.com/questions/7223168/how-to-trigger-autofill-in-google-chrome

The `validate` param in this gist also shows regular expressions used to match autocomplete fields in Chromium (taken from browser source)
https://gist.github.com/jlukic/6749676#file-gistfile1-js-L9

**Comment by kkerley** [comment]
This has nothing to do with the built-in autofill of Chrome that remembers values for fields of a given name/ID. This has to do with creating a field via Rails and enabling that to use the jQuery autocomplete functionality, nor does it allow the jQuery tokenInput functionality to work (functionality covered in this video: http://railscasts.com/episodes/258-token-fields-revised). 

Using the built-in Rails development server on my machine for this music site that has autocomplete for band names, label names and a token Input for genres. Here are screenshots with the sidebar I mentioned above NOT containing .sidebar on the sidebar div (the numbers in the upper-left are the response times from the server to serve up the filtered autocomplete list matching the string in the input):

Artist:
https://www.dropbox.com/s/dxcfvn7yfhbospv/Screenshot%202015-01-22%2010.15.06.png?dl=0

Label:
https://www.dropbox.com/s/z7cqa6zvdt4jf8y/Screenshot%202015-01-22%2010.15.23.png?dl=0

Genres:
https://www.dropbox.com/s/tp81eg6o42af2j1/Screenshot%202015-01-22%2010.16.03.png?dl=0

And now those same inputs when .sidebar is back in:

Artist:
https://www.dropbox.com/s/budire3uty9xcv7/Screenshot%202015-01-22%2010.12.08.png?dl=0

Label:
https://www.dropbox.com/s/rurfa6zwj24a47o/Screenshot%202015-01-22%2010.13.10.png?dl=0

Genres:
https://www.dropbox.com/s/ilgzjrwzbfms1la/Screenshot%202015-01-22%2010.13.45.png?dl=0

So, as you can see, the server is still responding with the JSON for those fields, but because the .sidebar class is in play, those fields don't display their autocomplete dropdowns to choose from a filtered list of autocomplete options. It has NOTHING to do with the bulit-in autofill in Chrome.

**Comment by jlukic** [comment]
So this has to do with using jQuery Chosen's autocomplete. Its probably related to the `z-index` of the autocomplete in chosen. You probably need to tinker with the layering of the autocomplete
```css
.chosen-container .chosen-drop {
  // some custom thing to fix it 
}
```

I can't say what exactly needs to be done. I can only speak to the effects of Semantic UI on its own.

**Comment by kkerley** [comment]
Ahhh great call. I never thought of that. And I was able to get the Artist and Label dropdowns to work by targeting the .ui-autocomplete class and setting the z-index super-high. Trying to figure out how to do the same for tokenInput now (none of the classes I've targeted have worked).

Thanks for the help and for the awesome work on Semantic.
