### ISSUE TITLE
sidebar/pusher question

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#1624]
Many templating frameworks allows you to define a "HTML page template", where the parts of the template (for example): sidebar, content, footer - are all contained within the page template. 

In SUI one would  try to define such an HTML template page as:
```
...
<body class="index pushable"> 
<div id="template">
     <div class="ui left vertical inverted sidebar menu" id="sidebar">
      ... 
     </div>
     <div class="pusher" id="pusher">
        <div class="ui page grid" id="content">
         ....
        </div>
        <div class="ui footer segment" id="footer">
         ....
        </div>
     </div>
     
</div>
<body>
```
This pattern would not work with SUI and you will get JS errors like:
1) Sidebar: Had to add pusher element. For optimal performance make sure the body content is inside a pusher element.
2) Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag

This is a strange design ...
I am not sure how a single DIV tag between the BODY and the SIDEBAR can have such a performance impact to warrant a whole JS error, but SUI is also trying to generate additional PUSHER tag, making a complete mess. An why the sidebar is found, but the pusher were missed and had to be added?

I wonder if there is any better way to implement "page templates/skeletons" - a single root element containing the parts of the page template.

.. Or if the SUI design can be changed to be less restrictive/more robust  (as it was in the earlier versions?).

Thanks!

**Comment by calmdev** [comment]
I was working with the new sidebars last night and had a similar experience. Though, it *does* work. I was also wanting to attach the sidebar to a different root element rather than the body:

```html
<div class="application">
    <div class="left visible thin sidebar menu"></div>
    <div class="right visible thin sidebar menu"></div>
    <div class="pusher"></div>
</div>
```

However, it doesn't appear possible to have both open without overlaying them. I believe in `pre-1.x` it was possible to do this with `pushed left right`:

```html
<div class="application pushed left right">
    <div class="left visible thin sidebar menu"></div>
    <div class="right visible thin sidebar menu"></div>
    <div class="pusher"></div>
</div>
```

Does anyone know? My goal is a menu on left and activity feed on right, but to make them useful, they need to remain open, without overlaying the content...

**Comment by Lisa-Williams** [comment]
You can change this actually.
In the ```sidebar.settings``` there is a ```context``` variable which is set to ```body```.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sidebar.js#L987

The sidebar's JS picks this up, and adds class ```pushable``` to whatever element selector is in ```context```.
The sidebar's CSS only matches ```children``` of the element with that class ```pushable```.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sidebar.less#L113-L125

So if you change line ```987``` in ```sidebar.js``` from ```body``` into whatever element you want, e.g. ```#template``` for the OP, it should work.

But that would change it for all pages where you use SUI sidebars.

**Comment by hrstoyanov** [comment]
Thank you all! I think I found a way to comply with the SUI sidebar quirks!

**Comment by calmdev** [comment]
The `context` option resolves the issue for me too. Not sure how I overlooked it in the docs. 

Thanks @Lisa-Williams

**Comment by jlukic** [comment]
I'm adding better examples with `context` and `visible` with `1.7.0` today. Will be up before 6pm EST.

**Comment by calmdev** [comment]
@jlukic 

I'm using the `visible` class on my sidebars so they show on page load, but saw this in the source:

![screen shot 2015-01-14 at 4 34 40 pm](https://cloud.githubusercontent.com/assets/461249/5748191/208fd51e-9c0c-11e4-8418-0daaf894d941.png)

I'm achieving what I need using my own `.pushed.left` and `.pushed.right` classes right now, but didn't this use to be built in? Should I continue to use my own classes, or is there a better way?

Goal is a to keep the content are visible and usable while both sidebars are open.

Here is a screen shot:

![screen shot 2015-01-14 at 4 40 12 pm](https://cloud.githubusercontent.com/assets/461249/5748231/595373d8-9c0c-11e4-8a20-05513883f535.png)

**Comment by Lisa-Williams** [comment]
You're out of luck.
The first example (```Run code``` button) on this page confirms the forced override to overlay: http://semantic-ui.com/modules/sidebar.html#/examples

**Comment by calmdev** [comment]
Alright, it makes sense if you're showing four. As it is now though, I feel like we're missing out on the possibility of building layouts that function like http://www.twitch.tv/ (great example) out of the box. Is this a technical limitation of SUI, an unwanted behavior, or would a pull-request be accepted for this?

**Comment by Lisa-Williams** [comment]
I'm with you. The Twitch example makes a strong case.
Wish the reflow was animated though.

P.S.
Apparently, in the old days, a sidebar with push animation used to squeeze the page, and cause a reflow : https://github.com/Semantic-Org/Semantic-UI/issues/613
(This is way before my time with SUI though. I just happened to bump into that issue the other day.)

**Comment by jlukic** [comment]
It's not too hard to do something like twitch. If I was making a site with (my own project) I would.

1) Customize the variables for the preset sidebar sizes to the widths I wanted
2) Use a visible sidebar on page load
3) *To swap to tiny icon sidebar* Use some custom javascript to swap class to thin and hide text content
4) *To hide sidebar entirely* Just use `$('.sidebar').sidebar('hide');`

**Comment by jlukic** [comment]
@Lisa-Williams 

I moved all animations to 3d transforms in `1.0` which makes things fast with decent GPUs, but means content isn't actually "pushed" per se, they are just two side by side elements animating at the same time. The page contents, and the sidebar.

**Comment by calmdev** [comment]
@Lisa-Williams page squeeze and content reflow are better words for explaining it, thanks for the issue reference. @jlukic — yep, that's the approach that I've implemented for now.

**Comment by Lisa-Williams** [comment]
@jlukic Referring to your 3).
The CSS rules with the general sibling combinator would be matched (screenshot by @calmdev) and still **prevent** squeezing and reflow of the main content in the middle.
For which @calmdev hinted at a pull request.
Behaviour which was already in SUI way back. (Just twisting your arm here.)

**Comment by startswithaj** [comment]
Did anyone get this to work? Does anyone have an example?

I've spent about 8 hours now trying to chase down why the context option doesnt work

I get the error:

Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element

no matter where i put the bar, no matter what i set as context.

**Comment by startswithaj** [comment]
@hrstoyanov could you share how you got this to work?

**Comment by hrstoyanov** [comment]
I did get it to work, yes. Do you have a jsfiddle so we can look into?

/Hristo Stoyanov

**Comment by fluidlog** [comment]
Hi, I found the answer here : http://semantic-ui.com/modules/sidebar.html#/usage

**Comment by gVolop** [comment]
@hrstoyanov is this layout success ? -http://www.twitch.tv/directory
can you share it with JSFiddle or some else ?

**Comment by swapsword** [comment]
I also getting the same error:- 
 " Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element"
"Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag"
Is anyone is able to solve this issue? check my jsfiddle https://jsfiddle.net/swapsword/ew2xfjbr/

**Comment by OguzhanE** [comment]
i have been working with react and semantic.
if i attach the sidebar to body(default), i am getting error from react, 
so i attach the sidebar to a different root element rather than the body with ```.sidebar({ context: $('#app-container') })```,
but still errors.
Finally, i solve this issue as like below:
```javascript
// fix semantic's dom manipulation, TODO:find better way
$.fn.sidebar.settings.defaultTransition.computer.left = 'overlay'
$.fn.sidebar.settings.defaultTransition.computer.right = 'overlay';
// change sidebar's context
$('.ui.sidebar').sidebar({ context: $('#app-container') });
```
it works for me

**Comment by vko-online** [comment]
@OguzhanE 

    //rtfm
    $('.ui.sidebar').sidebar('setting', 'transition', 'overlay').sidebar({ context: $('#app-container') });

**Comment by OguzhanE** [comment]
@vko-online 
if i use ```.sidebar('setting', 'transition', 'overlay')```, i still getting error ```"Sidebar: Had to add pusher element. For optimal performance ..."```, also react gives an error because dom hierarchy was changed.

**Comment by hverlin** [comment]
It works juste fine if you change the context first : 
`$('.ui.sidebar').sidebar({ context: $('#app') }).sidebar('setting', 'transition', 'overlay')`

Otherwise, it will move the sidebar and show a warning and then change the `context`.

**Comment by bradparks** [comment]
An example of using a semantic-ui "sidebar" in only part of your page (in a "context") can be found here:

http://stackoverflow.com/q/35664906/26510

**Comment by mattfink77** [comment]
is there any example of how to use the context setting to change it from something other than body, assuming this can be set to parent without needing JQuery. If not could this feature be added parent / grandparent seems to be a common setting here
