### ISSUE TITLE
Disabled dropdown still show pointer cursor on `:hover`.

### ISSUE THREAD

**Issue by musically-ut** [Semantic-Org/Semantic-UI#1626]
Demonstrated here: http://jsfiddle.net/e359vgcv/1/ as well as on the last example (at the time of writing) here: http://semantic-ui.com/modules/dropdown.html

The cursor should be reset to `auto` if the dropdown is disabled.

**Comment by jlukic** [comment]
Dupe of #1615 already fixed in `next`
http://jsfiddle.net/pczqf8xj/
