### ISSUE TITLE
extra spacing between menu items inside .ui.page.grid

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1631]
http://jsfiddle.net/qpu792k1/1/

.ui.menu { 
    font-size: 0px;
}

is overwrited by

.ui.grid > .column:not(.row), .ui.grid > .row > .column {
    font-size: 1rem;
}

which making an extra spacing

**Comment by septem123** [comment]
+66365

**Comment by jlukic** [comment]
Fixed in `next`, sorry @faller slipped through the cracks.
