### ISSUE TITLE
[Search] Access search component selected item

### ISSUE THREAD

**Issue by siannone** [Semantic-Org/Semantic-UI#1634]
I'm having a problem using the search component.

What I want to do is being able to access the selected element data but it looks there are some timing issues and/or I'm doing things in the wrong way.

This is my code:

    $('.ui.search.popup-project-changeCustomer').search(
    {
        type : 'standard',
        source : $scope.customers,
        searchFields : [
            'title',
            'description'
        ],
        onSelect : function(event) {
            $scope.project.customer = event.target.value;
            $scope.changeCustomer(token);
            return 'default';
        }
    });

The problem resides in the onSelect event and basically I can access the `target.value` but what I get is what the user typed in and not what the search component puts into the input.

What's the best practice to actually get the data (like title, description etc..) of the user selected element? I guess I'm doing something wrong here.

**Comment by tuxgasy** [comment]
I also try to do the same. I am also interested how to do.

**Comment by rodsnjr** [comment]
Same here, I'm currently getting what element was clicked on the event, 
like: 
<div class="title">title</div> (...)

If you search the whole event object, you'll only see data related to the HTML event, and none to the search.

Is there any way to get the JSON object?

**Comment by WheelsAmerica** [comment]
I also would like to access the selected JSON object, something sillilar to the dropdown module's OnChange callback.

**Comment by jlukic** [comment]
I'll take a look at this tomorrow

**Comment by jlukic** [comment]
@siannone Kudos on discovering the `default` hook with the callbacks, I completely forgot to document that.

I think I need to simplify the `onSelect` callback to not be so obtuse. I think it should cancel default actions only if the callback returns `false`, instead of it having to explictly return `default`.

I will also add the relevant response to `onSelect`, perhaps `onSelect(query, result, response)`

**Comment by jlukic** [comment]
Available in `next`, see release notes for details on implementation
