### ISSUE TITLE
Different type nested grids leave a spacing on the right of the browser

### ISSUE THREAD

**Issue by chrisvel** [Semantic-Org/Semantic-UI#1635]
In 1.7.0 , If you have 
```
<div class="ui celled grid">
    <div class="four wide column">
        <div class="ui grid">
.....
```
then a small padding space appears on the right of the whole window. If the grids are of the same type, then all is working good.

**Comment by jlukic** [comment]
Can you give a full example?

**Comment by chrisvel** [comment]
I am afraid that this is a big project and I can't share all my code, but I can share what is needed to show the problem.

**Comment by jlukic** [comment]
There is a JSFiddle you can fork in the readme.

**Comment by jlukic** [comment]
Any luck?

**Comment by chrisvel** [comment]
I was unable to replicate the problem and I upgraded to 1.7.3.
