### ISSUE TITLE
How to display the Documentation in original translation?

### ISSUE THREAD

**Issue by mikemix** [Semantic-Org/Semantic-UI#1636]
Question included in the title. The "English" language is not available from the dropdown at http://semantic-ui.com/

**Comment by anestv** [comment]
To me it seems that English is availiable, but it may be translated to the language you are currently using. It is the first item.

![image](https://cloud.githubusercontent.com/assets/4691918/5760400/f8041b38-9cdc-11e4-8392-1c321a290939.png)

**Comment by jlukic** [comment]
First dropdown option?

**Comment by mikemix** [comment]
I don't have such option! Why you close the topic so fast? As soon as the question about participating in the translations pops out, I don't have any ability to change the language back to english.

![bez tytulu](https://cloud.githubusercontent.com/assets/2399452/5761270/aa04508a-9cda-11e4-8f35-80e72c471e5f.jpg)

**Comment by mikemix** [comment]
Ahh, I have to click on "polish" to return back to the english translation. Clever.

**Comment by anestv** [comment]
I chose Polski and indeed there was no English visible. However, clicking the first item, incorrectly labeled as Polski will change the language to English.

The translators for the docs of that language cao solve this problem by translating 'English' to the actual word for English instead of the word 'Polski'

**Comment by jlukic** [comment]
I just checked transifex and one of the translators mistranslated the worst english to Polish. 

They are all volunteers and I dont know every language so I have to just *trust* they are doing a good job 

![Polish Translation](https://dl.dropboxusercontent.com/u/2657007/polski.jpg)

**Comment by mikemix** [comment]
Looks like it :) I corrected the phrase "English" in Transifex.
