### ISSUE TITLE
Gulp build does not seem to include theme overrides for modules

### ISSUE THREAD

**Issue by oostmeijer** [Semantic-Org/Semantic-UI#1637]
I ran into this problem when trying to override sidebar module functions.

Then I tried the following:
1) clean install of semantic-ui 1.7.0
2) performed the install with 'npm install' and 'gulp' with the default settings (but skipping the src deletion)
3) then I changed in theme.config: 
```
@progress   : 'striped';
```
4) ran 'gulp build'
5) however the change does not appear in the css file

What am I doing wrong? Or is gulp indeed not including the overrides for modules?

Thank you in advance,

Jelle

**Comment by jlukic** [comment]
The striped theme is all defined in `override`. It looks like progress was missing the call to include this like the other definitions preventing themes `override` files from being parsed.

**Comment by jlukic** [comment]
Released `1.7.1`
