### ISSUE TITLE
[Dropdown] Menu with submenus don't work links

### ISSUE THREAD

**Issue by Basgrani** [Semantic-Org/Semantic-UI#1638]
The root menu, work, next sublevels not work link:

![menu](https://cloud.githubusercontent.com/assets/3121125/5764158/3a24b848-9cf0-11e4-9696-82c25639dec0.png)

View in:

http://jsfiddle.net/basgrani/do5kda6a/

Thanks in advance

**Comment by jlukic** [comment]
This is a bug

**Comment by jlukic** [comment]
It appears keyboard navigation does not correctly follow links as well.

**Comment by jlukic** [comment]
Fixed both these issues
