### ISSUE TITLE
Missing Font Awesome 4.3 icons

### ISSUE THREAD

**Issue by iNety** [Semantic-Org/Semantic-UI#1642]
Semantic UI 1.7 is missing the new icons from Font Awesome 4.2 (now 4.3 which was released on Jan 22).

http://semantic-ui.com/elements/icon.html
http://fontawesome.io/whats-new/
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css

**Comment by jlukic** [comment]
I would take any Pull Requests on the matter.

**Comment by jlukic** [comment]
Was added in `1.9.0`
