### ISSUE TITLE
[Dropdown] Add Clear/Reset Behavior

### ISSUE THREAD

**Issue by tirdadc** [Semantic-Org/Semantic-UI#1643]
```
<select class="ui dropdown">
  <option value="">Gender</option>
  <option value="1">Male</option>
  <option value="0">Female</option>
</select>
```

Using a regular select dropdown enhanced with Semantic UI, is there currently no way to reset the value to nil? Right now that option gets parsed for the placeholder.

I tried the restore button approach shown in the example, but that only works if you're dealing with a new record that doesn't already have the default set to something else.

Thanks!

**Comment by jlukic** [comment]
Can you create a test case to show the bug or missing behavior?

I'm not sure how `$('.dropdown).dropdown('restore defaults');` is failing for you.
http://semantic-ui.com/modules/dropdown.html#restoring-defaults

This JSFiddle shows it working with `<select>`
http://jsfiddle.net/e2xzj36L/

**Comment by tirdadc** [comment]
Sure, here's an example that shows what I meant:

http://jsfiddle.net/6w9xqhfs/1/

I want the ability to reset the select to blank.

**Comment by jlukic** [comment]
I've added `.dropdown('clear')` and clarified the documentation around `.dropdown('restore defaults')`

Defaults are values on page load, placeholder is the value that matches (empty string), or set on page load in class `default text`

**Comment by awaistechverx** [comment]
Whenever i run `$('.dropdown).dropdown('restore defaults');` or `$('.dropdown).dropdown('clear');`
i get error **Error: [$rootScope:inprog] $apply already in progress**
Why this is happning? any idea?

**Comment by matsura** [comment]
Try to wrap it in setTimeout(() => {
    $('.dropdown').dropdown('clear');
}, 0); or in AngularJS $timeout(() =>{
    $('.dropdown').dropdown('clear');
}, 0)

**Comment by pallakartheekreddy** [comment]
@awaistechverx i am also facing same issue. did find any solution?

**Comment by awaistechverx** [comment]
@pallakartheekreddy i resolved this issue with trick,
function clearDropdown(){
    setTimeout(function () {
        $('.ui.fluid.dropdown').dropdown('clear')
    },0)
}
