### ISSUE TITLE
[Dropdown/Label] Required corner overlaps Dropdown list

### ISSUE THREAD

**Issue by aprog** [Semantic-Org/Semantic-UI#1646]
Hi,

while using Dropdown module I noticed that corner for required element overlaps Dropdown list:
![dev iscale localhost 2015-1-16 13 27 39](https://cloud.githubusercontent.com/assets/725146/5775515/7a2a3b8c-9d83-11e4-8af4-84f13e924631.png)

Two corners relate to the elements that are *behind* the dropdown list.

**Comment by jlukic** [comment]
Thanks for your submission. I'll fix this in `next`.

**Comment by jlukic** [comment]
Fixed in `next` 98d55d0b9340c17f7a90ed5819ad9af2121b06ba
