### ISSUE TITLE
Possible to deactivate Autosearch in Dropdown?

### ISSUE THREAD

**Issue by TimMcCauley** [Semantic-Org/Semantic-UI#1648]
Hi there,

is it anyhow possible to deactivate the automatic search when using an Search Dropdown? I need to be able to input text but when typing the dropdown should not "look" for a corresponding entry.

Thanks

**Comment by jlukic** [comment]
There's no native functionality for having a search that doesnt search. But you can easily enough remove events from the input 
```javascript
$('.search.dropdown > input.search').off('.dropdown');
```

**Comment by TimMcCauley** [comment]
Thanks Jack!

**Comment by TimMcCauley** [comment]
Sorry again, I tried this and it doesn't work. Let me elaborate why I need this. What I'm doing is sending the input text to a server to fetch a list.

   $('.ui.form.start input.search').keyup('input', function() { ... }

I fill my response from the server into the dropdown menu as such

    <div class="item" data-value=".."></div>

When the list is filled I refresh the dropdown menu:

    $('.ui.search.dropdown.start').dropdown('refresh');

And then I show the options fetched from the server:
    
    $('.ui.search.dropdown.start').dropdown('show');

Now, when the user inputs new text to the input.search I fire a new request to my server and fetch new results the dropdown menu. What the dropdown now tries is to find this new text in the dropdown menu select options which shouldn't happen, that is why I want to deactive it. It just opens and closes several times and eventually stops. I can't reproduce this on jsfiddle as the code is too complex.. 

Are you sure this should work? 

   $('.search.dropdown > input.search').off('.dropdown');

**Comment by jlukic** [comment]
"UI search" does what you are describing without so much custom code

**Comment by TimMcCauley** [comment]
Yes, I get that but why is the dropdown popping up several times?

http://youtu.be/WqTOaWB3zEw

**Comment by TimMcCauley** [comment]
Jack, I fixed it, it was a problem with my JS structure. CLOSED! :+1:
