### ISSUE TITLE
[Popup] $(document).popup('hide all') throws error

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#1649]
```
Uncaught TypeError: Cannot read property 'defaultView' of null
```

$('body') works, but I feel like $(document) should work as well.

**Comment by jlukic** [comment]
Popup functions should only be called on elements that you want to be initialized as a popup. Initializing it on `document` or `body` will most likely cause unexpected behaviors.

**Comment by ShimShamSam** [comment]
On a single-page app, routing to another page is a good instance where you would want to ensure all popups are hidden. How would one accomplish this other than making sure all popups have a common class?

**Comment by jlukic** [comment]
There's a distinction between activating element (which methods are called on) and the popup. All popups share class `ui popup`, calling `hide all` on an **activating element* will call internally 

```javascript
$(selector.popup)
  .filter(':visible')
    .transition(settings.transition)
;
```

which will hide all popup on page.
