### ISSUE TITLE
[UI] Add PSD graphics to Website

### ISSUE THREAD

**Issue by macagoraga** [Semantic-Org/Semantic-UI#1650]
Hi

Where I can find the PSD graphics files of semantic-ui?

thanks

**Comment by anestv** [comment]
I don't think there are any, at least officially.

**Comment by macagoraga** [comment]
@anestv thanks for your reply.
In this case, we can start work on some part.
anyone interested to contribute?

**Comment by jlukic** [comment]
Just wanted to confirm, as far as I know no one has done anything like this before.

**Comment by macagoraga** [comment]
@jlukic I will start with http://semantic-ui.com/kitchen-sink.html then I hope someone else can help because there are a lot of things.

**Comment by Anachron** [comment]
@jlukic @macagoraga well look what I just found:

http://www.pagelayers.com

Maybe thats good enough for the beginning?

**Comment by jlukic** [comment]
Hey this is great! Yeah if someone had time they could probably create PSDs quite easily

**Comment by FoxxMD** [comment]
+1

**Comment by aqqadk** [comment]
Yes please, if someone could create a PSD for this that'd be great! 
+1

**Comment by Sanjo** [comment]
I've exported the Semantic UI kitchen sink with the Pagelayers tool. You can download the four PSDs here: https://drive.google.com/file/d/0B4i8Z3KNCWnlYkdscU5OeTFSTW8/view?usp=sharing. I license this files under the [MIT license](https://github.com/Semantic-Org/Semantic-UI/blob/master/LICENSE.md).

__How I have done it:__

Do the following for each tab in the kitchen sink:

1. Open the page in the Pagelayers tool.
2. Export the PSD
3. Open the PSD and remove the unnecessary layers for the left sidebar and top section. This will decrease the file size drastically (~ 800MB -> 20MB).

**Comment by krristap** [comment]
Great, thank you so much Sanjo, this saved me hours! Also, have added the Mac Layer Tool onto ToBuy list.

**Comment by jlukic** [comment]
@Sanjo Any chance to get these re-exported with 2.0 styles? Wanted to include this in our guide.

**Comment by Sanjo** [comment]
@jlukic Yeah sure. I can export and upload it tomorrow.

**Comment by thesalarali** [comment]
Hey @Sanjo . Any update on this?

**Comment by Sanjo** [comment]
### Semantic UI 2 PSDs

I've exported the Semantic UI kitchen sink with the Pagelayers tool. You can download the four PSDs here: https://drive.google.com/file/d/0B4i8Z3KNCWnlZDVaTW1YWFNKaUk/view?usp=sharing. I license this files under the [MIT license](https://github.com/Semantic-Org/Semantic-UI/blob/master/LICENSE.md).

__How I have done it:__

Do the following for each tab in the kitchen sink:

1. Open the page in the Pagelayers tool.
2. Set the screen size setting to 1920 x infinite.
3. Set the scale to "x 2 (Retina)". This option is in the screen size dropdown.
4. Export the PSD via the menu "Screenshot" -> "Save as..". Make sure to tick "Generate text layers". Choose the format "Photoshop (CS5 or newer)".
5. Open the PSD and remove the unnecessary layers for the left sidebar and top section. This will decrease the file size drastically (~ 800MB -> 20MB).

**Comment by jlukic** [comment]
Will get these up in the docs shortly..

**Comment by listepo** [comment]
+1

**Comment by s-devaney** [comment]
+1
