### ISSUE TITLE
[Form] using 'magic numbers' instead of breakpoint variables

### ISSUE THREAD

**Issue by r0b-** [Semantic-Org/Semantic-UI#1651]
To enable customization the rules for mobile should use a site variable like @tabletBreakpoint.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/form.less#L671
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/form.less#L769

Thanks in advance!

**Comment by jlukic** [comment]
You are correct those should be variables, unsure why they aren't.

**Comment by jlukic** [comment]
Fixed in `next`
