### ISSUE TITLE
[Menu] Vertical pointing menu style bug

### ISSUE THREAD

**Issue by wmulligan** [Semantic-Org/Semantic-UI#1653]
http://semantic-ui.com/collections/menu.html

In version 1.7.3, the pointer for the vertical menu is the wrong color.  You can see that the color is white, instead of the intended grey.

Thanks!  Love the library despite this bug. :)

**Comment by jlukic** [comment]
Thanks

**Comment by jlukic** [comment]
Fixed in `next`. Positioning should be slightly better as well.
