### ISSUE TITLE
[Header] Sub header does not scale

### ISSUE THREAD

**Issue by wmulligan** [Semantic-Org/Semantic-UI#1654]
Bug/Feature Request in 1.7.3

Changing the size of the header using either h1-h5, or using huge-tiny, does not seem to affect the sub header.  I would expect the sub header should maintain a relative smaller size.  

http://semantic-ui.com/elements/header.html

**Comment by faller** [comment]
+1

**Comment by jlukic** [comment]
I agree it should scale, but probably not linearly.

**Comment by jlukic** [comment]
Added in `next`
