### ISSUE TITLE
[Transition] Prevent multiple transitions at the same time

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#1656]
I was messing around with transitions when I stumbled upon some confusion with the settings.

I am not quite sure what the difference between queue and allowRepeats is. Is queue globally for all transitions and allowRepeats specifically for an individual transition? Neither of these options seems to prevent a new transition from occurring if another is underway (queue waits for the first transition to finish, but does not prevent a new transition). 

I think there needs to be a noDuplicate option which prevents the transition from occurring multiple times. I have a button where a transition is started when clicked and it has bad results when the user continuously clicks the button. 

See this JSFiddle: http://jsfiddle.net/gch6mfm6/1/

Repeatedly clicking the button triggers the animation event. The animation is restarted every time the button is pressed, and may flash several times before resting which seems to indicate that the transitions are all occurring at the same time.

**Comment by jlukic** [comment]
This is fairly simple using [transition behaviors](http://semantic-ui.com/modules/transition.html#behavior):
http://jsfiddle.net/rgtr7ztg/

**Comment by fpayer** [comment]
I suppose so, but this scenario seems like it would be fairly common. Adding this functionality directly into Transitions would make development cleaner. 

I have a page with three different buttons corresponding to three different transitions. In each one, I need to add an extra if statement to handle this case.

**Comment by jlukic** [comment]
Alright I'll look into this.

**Comment by jlukic** [comment]
Turns out you were right there was something broken under the hood. `is occurring` was not returning correct value. Check commit for details.

Allow repeats will also now affect animations whether or not queue is used.

Fixed in `next`
