### ISSUE TITLE
Help needed - fixed menu and page grid issue 

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#1657]
Hi,
Can someone help me understand why my top fixed menu is overlapping with the top of my page content, and how to fix it? Thanks in advance.

http://jsfiddle.net/5hbakztu/

**Comment by fpayer** [comment]
I think this is because the sidebar uses absolute positioning, so the "pusher" element does not take into consideration the space that the sidebar is using.

See this updated JSFiddle where I added padding to the sidebar to resolve the problem:

http://jsfiddle.net/5hbakztu/1/

**Comment by hrstoyanov** [comment]
Fpayer, thank you!
Not sure if this is an issue that can be fixed in SUI, or not...

**Comment by jlukic** [comment]
This isn't a bug, but just a shortcoming of framework html. There's no easy way to displace content out of flow (like absolute or fixed) without manual positioning.
