### ISSUE TITLE
[Button] Colored buttons missing box-shadow on focus

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1658]
Testcase: http://jsfiddle.net/efp8z6Ln/115/

Expected behavior: Box-shadow should display on button focus, regardless of whether it is colored or gray.

**Comment by jlukic** [comment]
Since colored elements have their own boxShadow settings, its probably overriding the default focus. 

I'll take a look.

**Comment by jlukic** [comment]
Fixed in `next`
