### ISSUE TITLE
Popup fails for non-adjacent elements

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#1659]
Testcase: http://jsfiddle.net/efp8z6Ln/116/

Activating a popup manually fails unless the two DOM elements are siblings.

Repro steps:
1. Run the testcase, notice that popup displays on hover.
2. Comment out line 2. Uncomment line 1.
3. Retry testcase. Notice that popup does not display on hover.

The elements cannot be adjacent because `<label>` may not contain `<div>` tags.

**Comment by jlukic** [comment]
If you are unable to include element as next sibling you can specify the popup using `settings.popup`. This is what I do in most cases with a predefined popup in my own projects.

See this JSFiddle:
http://jsfiddle.net/k17phdLe/

**Comment by jlukic** [comment]
```javas

**Comment by cowwoc** [comment]
@jlukic Sounds like a documentation bug to me. http://semantic-ui.com/modules/popup.html#/examples mentions the `popup` parameter but http://semantic-ui.com/modules/popup.html#/settings does not.

Can you please fix the latter?
