### ISSUE TITLE
Radio buttons do not work

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#166]
Radio buttons do not work - http://semantic-ui.com/modules/checkbox.html

Events seem to be being fired as they are logging info to the console, but the radio never selects.

Tested on Mac OSX 10.8.5 - Chrome, Canary, FF, Opera, Safari

**Comment by enjoyiacm** [comment]
I have a problem in Safari (on OS X 10.10.2). Radio buttons are worked through. That is, when I click on it does not change the situation, but only changes the background (from blue to gray and back again). How can I fix it?

**Comment by jain0nikhil** [comment]
Is this still an issue?
