### ISSUE TITLE
Modal Examples Issue

### ISSUE THREAD

**Issue by MatthewVita** [Semantic-Org/Semantic-UI#1661]
Perhaps I wasn't looking hard enough, but I can't locate the repo for semantic-ui.com (otherwise, I'd put in a PR).

http://semantic-ui.com/modules/modal.html has incorrect example code for the first two examples. For instance, the first code sample is:
```javascript
$('.standard.test.modal')
  .modal('show')
;
```

...but the respective HTML is ```<div class="ui modal">```.

**Comment by jlukic** [comment]
The additional classes are just used to distinugish between modals in the example code. Having `$('.ui.modal').show()` would trigger all modals. 

I'll see if I can find a better way to 'fake' the javascript for the examples so that it isnt confusing.

**Comment by MatthewVita** [comment]
how about something like `ui.modal.example-name-here`?

btw, thank you so much for your hard work on Semantic. I'm a huge fan.

**Comment by jlukic** [comment]
I'm adding a new parameter so code demos can run different code than the examples say they are. Should allow for simpler modal examples.
