### ISSUE TITLE
Issues with add link attribute to icons

### ISSUE THREAD

**Issue by Enelar** [Semantic-Org/Semantic-UI#1662]
Sometimes when i trying to make icon interact with user mouse, i getting `link` icon instead.
For example try this code
`<i class='icon remove'></i>`
become this
`<i class='icon remove link'></i>` or `<i class='link icon remove'></i>` or whatever.

v1.0.0

**Comment by Enelar** [comment]
I am so sorry, its just exception with `remove` icon.
We should use `close` instead. I am so sorry.

**Comment by czechnology** [comment]
Before I open another ticket, I've noticed a similar issue - the icons `external link` and `external link square` cause the icon to be "linkable" (`link` class) which might not always be the desire of the designer.
