### ISSUE TITLE
Allow images next to headers (additionally to icons)

### ISSUE THREAD

**Issue by rosetree** [Semantic-Org/Semantic-UI#1663]
I love the way Semantic UI can display icons next to headers. But, it would be great if Semantic UI could also display normal images next to headers and maybe all other elements where icons are possible.

Did someone take this into consideration, yet?

**Comment by jlukic** [comment]
This should exist, I'll need to estimate whether I can fit this into `1.8` or should push back till next week.

**Comment by jlukic** [comment]
Added in `next` along with new docs

**Comment by rosetree** [comment]
Hi, thank you very much for resolving this request!
