### ISSUE TITLE
[Docs] error on `successTest` fn.

### ISSUE THREAD

**Issue by ssbunny** [Semantic-Org/Semantic-UI#1665]
An Error on this page  -->  http://semantic-ui.com/behaviors/api.html#/usage .
To specify a global `successTest ` function , `$.fn.api.settings.successTest` should be used instead of `$.fn.api.successTest`.

**Comment by jlukic** [comment]
Thanks, typo

**Comment by jlukic** [comment]
Fixed https://github.com/Semantic-Org/Semantic-UI-Docs/commit/5594819bdf252f800fea607d6fd641c18679abe0
