### ISSUE TITLE
[Popup] Issues with Nested Content w/o Inline

### ISSUE THREAD

**Issue by CakalSG** [Semantic-Org/Semantic-UI#1668]
Hi,

See example: http://jsfiddle.net/cakal/ubvL1w4d/3/

1. Input popup not problem but table first "th" title element problem. 
$('[title]').popup({inline: true,});

2. If change (not inline option)
$('[title]').popup();

Cant see popup in Modal.

I change in semantic.css "Popup" z-index over "Modal" z-index. Ok no problem.

Sorry my bad english :(

**Comment by jlukic** [comment]
I would usually recommend `inline: true` but it appears this will not work in cases where inline element breaks styles like inside a `<table>`.

I'll take a look at what I can do.

**Comment by jlukic** [comment]
I was looking for a tricky solve for this, but really popup `z-index` can just be increased. It will now go on-top of everything.

Fixed in `next`
