### ISSUE TITLE
[Dropdown] Menu does not update with changes to <select>

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI#1669]
Check this fiddle:

http://jsfiddle.net/tomitrescak/zjpf5chr/2/

It's impossible to select value from the dropdown.

**Comment by jlukic** [comment]
Refresh doesn't update automatically in current versions with changes to the `<select>` only with changes to the dropdown menu.

**Comment by jlukic** [comment]
I'll add this as an enhancement since this is one of several issues that has requested, see #1117

**Comment by tomitrescak** [comment]
Great, also please not that calling `dropdown` on select ALWAYS creates a new menu which seems to be the problem. In my meteor app this happens quite often, whenever there is a change in the datasource and reactive change then produces a new menu instead of refreshing the old one. In one case I ended up with 100+ menus on the same dropdown ;)

**Comment by jlukic** [comment]
Building menus from `<select>` was a convenience method dropped into `1.0`. Typically it expects methods to be called on a dropdown with HTML like `ui dropdown`. Once you initialize `select` the target of future calls should be the `ui dropdown` and not the original `<select>` element, inside the dropdown. 

If you're familiar with [Select2](https://select2.github.io/), it has (at least the last time I used it) the same issue where the `<select>` becomes a nested descendent of the initialized dropdown and will fail if you repeatedly initialize it.

**Comment by jlukic** [comment]
Fixed in `next`
