### ISSUE TITLE
Form tag inside a menu 

### ISSUE THREAD

**Issue by yordis** [Semantic-Org/Semantic-UI#1670]
I am creating a menu with the basic search input. I tried to wrap the input inside  form tag and then the menu is broken. Notice the Home button have a little space in the bottom.

[JSFiddle](http://jsfiddle.net/yordisprieto/g9h7js6x/)

**Comment by jlukic** [comment]
Menu resizes `input` and `button` to fit in a single line, but only does so on `input` and `button` that are children of `item`.  Removing this child selector would make the rule too vague, and would match inside dropdown items, or other nested content. 

I recommend just making the `item` a form tag. 
http://jsfiddle.net/711wm130/

**Comment by yordis** [comment]
@jlukic Thank you very much!
