### ISSUE TITLE
[Dropdown] doesn't work without items

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#1672]
After updating to the latest version of semantic ui (at the moment `1.7.3`) the dropdown module doesn't work any more in my current project.

The last working tagged version seems to be `1.2.0`. The changelog of `1.3.0` shows some changes for the dropdown modul here https://github.com/Semantic-Org/Semantic-UI/releases/tag/1.3.0.
After analyzing the difflog https://github.com/Semantic-Org/Semantic-UI/compare/1.2.0...1.3.0#diff-13 I found out that the reason for my non working dropdown is the new method `allFiltered`.

The problem is that my dropdown menu doesn't contain any `item` classes but some other content. In this case the `allFiltered`method returns true and prevent the dropdown action:http://jsfiddle.net/dvw1vebo/1/

Although it makes sense that a menu without items must not be shown I think there are situations you want to display other content inside a dropdown.

Maybe the dropdown module is too specific by only allowing `item`childs or there should be an unstyled `item`class to allow arbitrary content inside a single `item`class?

**Comment by jlukic** [comment]
Thanks larsbo I wasn't familiar with this bug.

**Comment by jlukic** [comment]
Might be related to #1632

**Comment by jlukic** [comment]
I can confirm it is fixed with #1632, thanks to @PSyton
