### ISSUE TITLE
how to remove padding on divs right/left

### ISSUE THREAD

**Issue by rSafari** [Semantic-Org/Semantic-UI#1673]
Hello,

i have a problem with padding around my div .

![padd](https://cloud.githubusercontent.com/assets/1060150/5823172/cce49182-a0ef-11e4-87f7-e099ae28339a.jpg)

i want to remove the padding in the left and right . and this is my code

```
       <div class="ui grid">
            <div class="row">
                <div class="three wide column">
                    <nav class="main-nav-rightside">
                        qweqweqwe
                    </nav>
                </div>
                <div class="ten wide column main">
                    @RenderBody()
                </div>
                <div class="three wide column">
                    <nav class="main-nav-leftside">
                        zxczxczxc
                    </nav>
                </div>
            </div>
        </div>
```

**Comment by jlukic** [comment]
Can you create a JSFiddle that reproduces your issues?

I've tried with your example, and it looks fine:
http://jsfiddle.net/7k6kjm9h/

**Comment by rSafari** [comment]
thanks for your response 

check this out : http://jsfiddle.net/ed9ugb5f/

**Comment by rSafari** [comment]
any idea here !?
im stocking on this one !

**Comment by jlukic** [comment]
Grids have gutters between columns. Your bottom row has three columns, so there are gutters in between the first, second, and third columns. 

If you want things to "butt up" against each other, you need to specify background colors on all columns.

**Comment by rSafari** [comment]
i dont get it !
background-color  ? gutter ? whats the relation !
i just need the div with ten column having no padding in the left and right . 
the backgrounds is different and cant be the same .

if im wrong , can you please edit my fiddle ? 

thank you

**Comment by rSafari** [comment]
so how can i make this happen ?

i tried everything but i couldn't do the same thing like the picture . 

the main column ( ten wide column ) is getting filled from the partials. 

i really appreciated if you help me with this .

thank you .

**Comment by rSafari** [comment]
i get it now .

i should set the background on the <div class="three wide column"> and not the inside div . 

thank you .
