### ISSUE TITLE
publish webjars of latest version

### ISSUE THREAD

**Issue by antonkulaga** [Semantic-Org/Semantic-UI#1675]
Please, publish a webjar of the last version

**Comment by jlukic** [comment]
I'd love to publish webjars if it can be introduced as part of our release process. 

Can you provide some documentation on webjars, perhaps an explanation of how other OSS front end development projects build them?

**Comment by hrstoyanov** [comment]
+1
Jack,
It is actually very easy. Take a look at www.webjars.org/contributing

Releasing WebJars

**Comment by antonkulaga** [comment]
Actually semantic-ui is being published there very regularly by @jamesward . I opened an issue at semantic-ui webjar github repo https://github.com/webjars/Semantic-UI/issues/14

**Comment by jamesward** [comment]
WebJars are published to Maven Central.  I can setup others to have access to push new versions.  But since this takes me so little effort I don't mind doing it.  I just need an issue on the WebJar repo indicating that a new version is available (like @antonkulaga just did).

**Comment by jamesward** [comment]
Not yet. But we are looking into an auto-Bower sync to WebJars.

**Comment by jlukic** [comment]
@jamesward `1.9.0` is out :package:

**Comment by jamesward** [comment]
@jlukic Can you file an issue on the WebJar?

**Comment by jlukic** [comment]
I'm unable to maintain consistently updated webjars unless there's some automatic way for me to publish.

**Comment by jamesward** [comment]
We are working on an auto-Bower sync for WebJars which should be the best way to handle this.  Until then WebJar versions are "on-demand".

**Comment by jlukic** [comment]
@jamesward Any update on auto bower sync?

**Comment by jamesward** [comment]
It isn't fully automated but anyone can deploy a Bower WebJar.  More details: http://www.jamesward.com/2015/03/23/scaling-the-webjars-project-with-on-demand-bower-packages

Deploy a Bower WebJar: http://www.webjars.org/bower

**Comment by jlukic** [comment]
Closing for now, everything looks up to date.
