### ISSUE TITLE
Dropdown - Angular.JS

### ISSUE THREAD

**Issue by rodsnjr** [Semantic-Org/Semantic-UI#1676]
Is there anyway I can use(bind) the dropdowns with an angular.js model?

I've been trying for a couple days, and since then I haven't found any question/tips on how to do it ...

My code

http://jsfiddle.net/80vLhw4r/1/

**Comment by jlukic** [comment]
Check #1035

**Comment by rodsnjr** [comment]
My problem is that the way my selection works. 

The dropdown selection may also come from an API not from the interaction with it. I'm using that same solution to populate and bind the model. 

But when I try to change the selection, only by changing the model, the dropdown won't change its selection. 

Is there any way I could do that?

**Comment by mxth** [comment]
Try this: http://jsfiddle.net/6murnr7n/25/
