### ISSUE TITLE
Page Grid Widths

### ISSUE THREAD

**Issue by danielmatz** [Semantic-Org/Semantic-UI#1679]
I'm definitely a beginner when it comes to HTML/CSS, so please forgive me if this is a silly question...

I have some content in a page grid, but I'd like the margin/padding to be larger.  I can of course tweak the padding with CSS, but I wanted to know if there is a more "semantic" way of doing this?

I experimented a little with a doubling grid.  For a single column of content, a "centered three column doubling grid" kind of helps, but you don't really have much control on the margin/padding.  Also, for my cases with more than a single column of content, doubling will more than likely cause columns to wrap around to another row, which I don't want.

Would it be a good idea to add a "narrow page grid" and even a "very narrow page grid"?

**Comment by jlukic** [comment]
If you want to adjust the default gutter width, you can modify this variable.

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/collections/grid.variables#L19

Semantic is built around theming, which makes it easy to make these adjustments if you become comfortable compiling your own CSS using our build tools. See our [getting started guide](http://learnsemantic.com/guide/expert.html)
