### ISSUE TITLE
large ribbon label alignment

### ISSUE THREAD

**Issue by napple** [Semantic-Org/Semantic-UI#1680]
I noticed that large (or any non-default sized) ribbon labels will have their folded detail misaligned with their container. I believe this is caused by an improper use of em instead of rem when defining the border-width.

Thanks!

**Comment by jlukic** [comment]
Fixed in `next`.

**Comment by jlukic** [comment]
The math is more complicated than I originally thought

**Comment by jlukic** [comment]
Well that was fun 4a6d444f08553180e06ddc6d533baef6d1678446
