### ISSUE TITLE
Form validation onSuccess/onFailure fired twice when submitting via Enter key

### ISSUE THREAD

**Issue by DennisNygren** [Semantic-Org/Semantic-UI#1681]
If submitting a form with validation by pressing Enter key, the events onSuccess/onFailure gets fired twice.
However, this ONLY happens if the form is of an actual form-tag. If changing to a div-tag it works.

Is there a reason a lot of the examples in the documentation are using "incorrect" tags (for example div-tag instead of form-tag in this case)?

Check out this jsFiddle for demo (output printed to console log):
http://jsfiddle.net/rduvhn8u/4/

**Comment by jlukic** [comment]
Form automatically adds additional shortcuts to forms that are not always browse defaults. These can be disabled by passing the setting, `keyboardShortcuts: false`

* Enter will submit form when an input is focused
* Escape will blur input when input is focused

In addition form submit events are automatically attached:
* Any `ui button` with class name `submit` will get form submit on click, even if it is not a `<input type="button">`

Can you elaborate on the conditions which cause debug to output "twice" 2 times. I'm only seeing it once. Your link didn't have the validation hooked up to a field. Here's one with a matching field:
http://jsfiddle.net/17cwoqch/

With regards to the docs not using `<form>`, this was just me being lazy to prevent the form examples from POSTing results in the form docs. I'll modify them to be `<form>` tags and prevent the form submission in js for the docs.

**Comment by DennisNygren** [comment]
Thank you for your quick reply. Regarding the jsFiddle and how to reproduce, if you change your "alert" to "console.log" you'll see it will fire twice.

**Comment by jlukic** [comment]
I'm not seeing it appear twice, testing in Chrome, using the last JSFiddle.

What browser / environment are you reproducing this? What key or mouse movement are you using to submit the form?

**Comment by DennisNygren** [comment]
I'm on a MacBook Pro with OSX Yosemite, and I'm able to reproduce this in latest versions of both Chrome and Firefox.

How I reproduce it:
1. Go to your jsFiddle http://jsfiddle.net/17cwoqch/
2. Change alert('failure'); to console.log('failure'); and hit "Run" to update
3. Open up the developer console
4. Focus the text input field
5. Hit Enter/Return key -> Outputs "failure" twice to the console every time I hit it)

**Comment by jlukic** [comment]
Ah i see, it's specifically when you hit return on input. Fix incoming.

**Comment by DennisNygren** [comment]
Thank you for your quick help and great library!

**Comment by jlukic** [comment]
This seems not to be a bug with SUI, but just a default browser behavior. 

If you hold down the enter key when you are on a field it will submit repeatedly (this example is without semantic js included)
http://jsfiddle.net/g07t4pvy/

**Comment by DennisNygren** [comment]
But if you hit it only once it will only trigger once. I can agree with you this is weird browser behavior but what in that do you mean has to do with SUI triggering onSuccess/onFailure twice (since reproducing the bug doesn't involve holding down the key but just pressing it once)?

**Comment by jlukic** [comment]
The behavior is resolved in 90992d9. Form will prevent default behavior, and fire once on `keydown`

**Comment by DennisNygren** [comment]
Thank you Jack, keep up the good work!

**Comment by jlukic** [comment]
JSfiddle from next
http://jsfiddle.net/2auyqp0q/

**Comment by noradaiko** [comment]
Still firing submit event twice with return key on Chrome, using the last JSFiddle.

**Comment by thebadh** [comment]
I'm having the same issue on Chrome, _every time_ I submit - not just when using the return key, but also when I _click_ the submit button.

I've double-checked that the `submit` class is removed from my submit button, and that the calls to the `onSuccess` function are coming from the same physical "click" event.  Swapping the `form` tag for a `div` tag didn't help either - instead it fired _four_ times!

Ultimately, after some more cross-browser issues, I found it was more reliable to handle the event external to the form initialization, with a [`$('.foo').form('is valid')`](http://semantic-ui.com/behaviors/form.html#/settings) and  [`$('.foo').form('get values')`](http://semantic-ui.com/behaviors/form.html#/settings) call within a `submit` event.
