### ISSUE TITLE
ui grid responsive design for more then just mobile

### ISSUE THREAD

**Issue by ranbuch** [Semantic-Org/Semantic-UI#1684]
semantic-ui grid is responsive for mobile and tablet devices. 
tablet:
@media only screen and (max-width: 991px) and (min-width: 768px)
mobile:
@media only screen and (max-width: 767px)
however there's no solution for difference between laptop and desktop resolution - something like:
@media only screen and (max-width: 1200px) and (min-width: 991px)

Thank you for a beautiful framework!

**Comment by jlukic** [comment]
We offer several larger breakpoints `computer`, `large monitor` and `widescreen monitor`.

You can specify column widths for them like `eight wide computer six wide large monitor`

Details on breakpoints
http://semantic-ui.com/collections/grid.html#page-grid-breakpoints

**Comment by rickmed** [comment]
@jlukic mobile, tablet and computer are the only ones working for me

**Comment by maxwellhibbert** [comment]
I agree. A list of the actual class names in the docs would be handy.

**Comment by nbkhope** [comment]
Could someone clarify whether "large monitor" actually exist? As opposed to "large screen."

Also, please clarify for "widescreen monitor."

In the docs @ https://semantic-ui.com/collections/grid.html#device-visibility
the "Large Screen" vs "Widescreen" have the same class `two column large screen only row`, so what's the point? Was that a mistake?

**Comment by Bandlou** [comment]
@nbkhope @maxwellhibbert @rickmed 
The doc for version 1.12.2 actually offers valuable info about grid breakpoints: [1.semantic-ui.com/collections/grid.html#page-grid-breakpoints](1.semantic-ui.com/collections/grid.html#page-grid-breakpoints)
I tested these info and they still work for version 2.2
