### ISSUE TITLE
[API] meta data action is replaced with absolute url of the action

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#1685]
I'm not very familiar with the API at the moment (but it's awesome by the way! :+1: )
But I got a strange behaviour I cannot explain and even worse I cannot reproduce with a jsfiddle.

I created a config object
```js
$.fn.api.settings.api = {
    'foo': '/bar'
};
```
, an api event
```js
$('.trigger')
    .api()
;
```
and some html
```html
<a class="trigger" data-action="foo">Click me</a>
```

Now the funny part:
During the initialization of the page the `data-action` inside the html code will be replaced by an absolute url of the coresponding url: `http://www.my-domain.com/bar`.

When I click the link the console outputs:
```
API: API action used but no url was defined     false     Object { foo="/bar"}
API: No URL specified for api event     false

"Looking up url for action"    ["http://www.my-domain.com/bar", Object { foo="/bar"}]
"Added URL Data to url"    [undefined]
```
When I replace the `anchor` element with a `button` element the meta action remains `foo` during page load and everything is working fine.

I tried to make a jsfiddle with this behaviour but suprisingly it also works for `anchor` elements at that page. The semantic ui version is `1.7.3`in both cases.
Very confusing...

**Comment by larsbo** [comment]
Small update: 
When I remove the meta action and add it to the api event declaration directly it works, too :
```js
$('.trigger')
    .api({
        action: 'foo'
    })
;

**Comment by jlukic** [comment]
Seems to be working fine on JSFiddle using your example code. If you check the network traffic it goes to `/bar`
http://jsfiddle.net/4p3myfxu/

**Comment by larsbo** [comment]
Thank you for the fast answer, Jack. As mentioned in my first post, I can confirm the example works on its own on jsfiddle. That's why I didn't add a fiddle to my post ;-)

I will continue testing. Maybe there is another script that causes some conflicts in this special case.

**Comment by jlukic** [comment]
Let me know if anything changes and I'll re-open this issue.

**Comment by fpoppinga** [comment]
Hi Guys,

I can reproduce this behaviour in my current application (Semantic 2.1):

As soon as you have an element, say

    <div class=ui button" data-action="save">Save</div>

things like 

    $('.button[data-action="save"]').api({
      action: 'save something',
       ...
    });

won't work any longer and produce the error message as given above.

**Comment by iappa1** [comment]
Hi @larsbo and everyone, I am facing the same issue with  a div element.
`<div class="dashboard-top cards-row js-list-fetch loading" data-action="get all items">`

and defined global settings like 
```
$.fn.api.settings.api = {
	"get all items": "/items"
}
```
and initialising like below don't work
```
$(".js-list-fetch").api({
		on: "now"
                 .....
});
```

but the following works
```
$(".js-list-fetch").api({
		on: "now"
                action: 'get all items'
                 .....
});
```

and when it don't work, it produces message like
**API : No URL specified for api event**  
Please help me resolve this.
