### ISSUE TITLE
Different videos in single 'Video' component

### ISSUE THREAD

**Issue by dbronecki** [Semantic-Org/Semantic-UI#1688]
Hi,
I try to display different videos in single video component. Videos are changed by clicking buttons.
I can't make this work, I tried different functions, like:
http://jsfiddle.net/knhLp82n/

Is it a bug or am I doing something wrong?

**Comment by jlukic** [comment]
`ui video` has not officially been released yet. The code is a bit stale. I'll see what I can do, but I have to take a look through the code again to see where my head was at.
