### ISSUE TITLE
Input with Icon on left and right?

### ISSUE THREAD

**Issue by phillip-haydon** [Semantic-Org/Semantic-UI#169]
It seems its not possible to put an icon on the left and right of an input. 

You can use the icon on the left, with a 'corner' icon on the right. But no way to have the icon not cornered, and rather just on the right.

**Comment by theronic** [comment]
I can't find the reference in the #396 discussion. I want to do something like this, where the left icon is an action and the right icon is a state like loading / error:

![image](https://user-images.githubusercontent.com/1011676/32542318-df5ffe4e-c47a-11e7-93cb-4b67d9628be6.png)

Is this still possible?

**Comment by tkrebs2** [comment]
Was a solution ever reached here?

**Comment by pranavcool4** [comment]
I figured this out with a little bit of changes in css. Glad to write the code if anyone needs it for reference.

**Comment by HarryH-Tech** [comment]
That would be great haha :)

**Comment by kostaslamo** [comment]
Had the same problem, seems that you have to write some css code. Its quite simple.

`<div class="ui left icon huge input">
  <input type="text" placeholder="Search..." value=""  />
  <i class="search icon"></i>
  <i class="close icon" style="left: auto; right: 1px"></i>
</div>`

In the example above the search icon will be positioned left as left icon class is given in its parent element and the close icon will be positioned right.

**Comment by MendelBak** [comment]
Thanks for the code @kostaslamo ! It was exactly what I was looking for! Simple and quick solution.

I sent you a small BAT tip [via Brave Browser,](https://brave.com/tips/) although you'll need to sign up for an account to receive.
