### ISSUE TITLE
[Dropdown] Cannot use inline dropdown in a <p> element

### ISSUE THREAD

**Issue by mxth** [Semantic-Org/Semantic-UI#1690]
See: http://jsfiddle.net/6murnr7n/26/

**Comment by rSafari** [comment]
its not about the dropdown . the space is for the p tag not dropdown .
you should style the p tag with display: inline or inline-block to get them together .

good luck .

**Comment by mxth** [comment]
What space are you talking about? 

And from my expectation, a <p> and a <div> should behave the same in this case (block display). My temporary fix is using a <div> with <p>'s style.
See: http://jsfiddle.net/6murnr7n/32/

**Comment by rSafari** [comment]
of course the p tag should behave like that . but in your case you can just style the p tag.
or wrap your box with div instead of p . its much easier and more elegant
check this out : http://jsfiddle.net/kfbsgsmy/5/

good luck .

**Comment by jlukic** [comment]
`<p`> tags don't support block level elements

> The P element represents a paragraph. It cannot contain block-level elements (including P itself).
http://www.w3.org/TR/html401/struct/text.html#h-9.3.1

**Comment by jlukic** [comment]
If you really wanted to use `<p>` just convert everything to span 

http://jsfiddle.net/gk1od8w5/
```html
<p>
  Show me posts trending
  <span class="ui inline dropdown">
    <span class="text">today</span>
    <i class="dropdown icon"></i>
    <span class="menu">
      <span class="item" data-text="today">Today</span>
      <span class="item" data-text="this week">This Week</span>
      <span class="item" data-text="this month">This Month</span>
    </span>
  </span>
    
    and do something

</p>
```

**Comment by mxth** [comment]
> <p> tags don't support block level elements.

Thanks, it's the answer I wanted.
