### ISSUE TITLE
[Build] Make Permission Changes Optional

### ISSUE THREAD

**Issue by Wexcode** [Semantic-Org/Semantic-UI#1691]
Most of the changes are changing the file permissions from `755` to `644` as defined in [`defaults.js`](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/defaults.js#L10)

It also seems like some of the `dist` files are just out of date (weren't committed when the `src` files were changed).

**Comment by jlukic** [comment]
Perhaps permissions should default to not being modified, instead of setting 644.

I'm unsure of what you're referring to specifically about `dist/` files being out of date.

**Comment by Wexcode** [comment]
The Semantic-UI repo has pre-compiled assets in the `dist` folder. When I recompile those assets using gulp install, some of them change.

**Comment by jlukic** [comment]
Added in `meteor` branch.
