### ISSUE TITLE
[Docs] Countries in the local search example incorrect

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#1695]
On this page: http://semantic-ui.com/modules/search.html#/definition

The countries in the local search are mostly incorrect. It seems like all the countries all end with an 's' whether or not there should be an 's'. Example:

    { title: 'Ethiopis' },
    { title: 'European Unios' },
    { title: 'Finlans' },

**Comment by jlukic** [comment]
Haha, at least thats a little funny. Probably a poor copy and paste job. Fixing.

**Comment by jlukic** [comment]
Fixed in `next` release https://github.com/Semantic-Org/Semantic-UI-Docs/tree/f197567b3cb2edd8028297e0a96fea33b4fefb78
