### ISSUE TITLE
[Search] Getting the item selected

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#1696]
According to the docs, you can use the 'onSelect' callback to return the item selected from the search dropdown, but this causes two problems. 

1. It overrides the default action, so you can get the html element selected, but the dropdown will not close by itself. Not a big issue on its own, but
2. You receive the html element and not the result object selected. 

Use case: I have a search for components on the page. The user can search for a name and when they click on it, I take the id stored in the result object and focus the page to the html element with that id. 

Is this possible with the current search functionality or would this need to be an enhancement?

**Comment by jlukic** [comment]
`onSelect` is getting changed in the release later today. 

Previously you had to return 'default' from the callback to have default actions occur as well. This was a bit...short-sighted (and undocumented). 

The new onSelect will return the filtered json response with just the selected value, as well as only prevent default events when adding `return false;`

*From the new docs*
onSelect(result, response)
> Callback on element selection by user. The first parameter includes the filtered response results for that element. The function should return false to prevent default action (closing search results and selecting value)

If you can't wait for me to finish up with this release, you can download from branch `next`
