### ISSUE TITLE
[Search] Search on category and individual results

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#1697]
I cannot seem to find a way to have searches match category names AND the names of individual results.

If I make the searchFields select the name of the category, you can search for the categories, but not their individual elements. 

See this jsFiddle:
http://jsfiddle.net/o4capvxj/

On the docs, there is an example that uses API calls and allows you to search for the individual elements, but not by the name of the categories. I cannot seem to replicate this with local searches. I guess that the search component does then when you use API calls to generate the data. 

http://semantic-ui.com/modules/search.html#/definition

**Comment by jlukic** [comment]
Local search only works with standard formatted JSON, not category formatted.

To use category formatted search you will have to use API.
