### ISSUE TITLE
Design Issue: Modals and templates isolation

### ISSUE THREAD

**Issue by mariorodriguespt** [Semantic-Org/Semantic-UI#1699]
I'm working with the Meteor framework and it's uses Blaze. In a nutshell: Blaze allows you separated the UI in templates while providing reactive updates.

The problem I have with the Modals and Blaze is simple: I can't remove the hooks in `class="action"` of a modal. Example: You've a list of customers and when you click in a row, you're presented with a modal to handle some editing. In order to save the changes, I'm forced to use `onApprove` callback. I want to have 2 templates: 1 for displaying a list of the customer and another to handle the Modal, saves to the database and close the modal once the operation is complete.

I tried to hack around semantic-ui modals and I ended up placing code related to saving the data inside the template that handles listing the customers. I wasn't able to separate the logic. With bootstrap modals this is really easy to handle.

You can take a look at: https://github.com/mariorodriguespt/joshua-test

There is an elegant way of solving this: Render the modal template and handles everything inside of it. With this approach you simple waste more time and it's fair to say that it's overengineering.

The most common solution (according to some meteor github repo) is:
1.  Render the template
2.  Use jQuery to toggle the modal
3.  Control the cancel, reject and approve buttons with your custom code.

Semantic UI fails in the 3rd step. If I simply could choose if I want to use the default hooks or not, it would make my life a lot easier.

Am I missing something in the docs?

**Comment by jlukic** [comment]
You can disable any custom hooks by setting `settings.selector.approve` and `settings.selector.deny`. This will prevent any events from being bound automatically.

**Comment by jlukic** [comment]
>  I want to have 2 templates: 1 for displaying a list of the customer and another to handle the Modal, saves to the database and close the modal once the operation is complete.

You can have two separate templates. The only requirement for SUI is that the modal is in the DOM before invocation. How you get it there is you (and your frameworks) prerogative.
