### ISSUE TITLE
[Bug] No equal height for segment inside a column of an equal height grid

### ISSUE THREAD

**Issue by Fefas** [Semantic-Org/Semantic-UI#1700]
I don't know if it is a bug, because I'm trying to use the `equal height` grid feature for a segment inside a grid column.

You can see in this link (http://ceres.inovata.com.br/access/login) the height problem.

I would like that the block with *Últimas Notícias* title on right had the same `height` of the login form on left, but the `segment` inside the right grid column doesn't fill the height.

I didn't find how to fix it and I tried to make something like `#id.segment { height: 100%; }`, but it doesn't works.

Could you please fix it or show me a better way to do it?

Thankyou very much

**Comment by jlukic** [comment]
This is not a bug but a css limitation. The columns themselves are equal height, but any child content, for example a `ui segment` is not. 

There's no easy way around this besides using javascript. I have no plans on adding this directly into SUI, but there are alternatives in the wild.
http://brm.io/jquery-match-height/

**Comment by faheel** [comment]
Setting the height of the segments to 100% did the job for me.
