### ISSUE TITLE
Dropdown select appears to kill keydown event

### ISSUE THREAD

**Issue by joedwy** [Semantic-Org/Semantic-UI#1702]
Adding a Semantic dropdown to a page appears to kill the keydown event. Looking through the code, it appears Semantic might be hijacking `keydown` events for items that include any sort of `settings.keyboardShortcuts` values. Of course, the code is extensive and I haven't tracked all the way through it so I could easily be wrong. 

Try this on the same page as a dropdown: 

```javascript
$(function() {
    $(document).keydown(function(e) {
        console.log(e.keyCode);
    });
});
```
And it seems to block any keydown event. Or... I'm an idiot, which is quite possible, and perhaps likely.

**Comment by jlukic** [comment]
Appears to be working fine for me

http://jsfiddle.net/w2vqwtds/
