### ISSUE TITLE
[UI Suggestion] Extended Inputs

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#1703]
I'd love to see some of the non-traditional inputs as part of Semantic. Some of these have been mentioned before but some not. These are just some thing's I've seen around the web and in other frameworks.

## Masked Input:
Developers can supply a regex or some kind of special pattern to JS, and it can be applied to a textbox. The mask would enforce a set of characters; I.E. phone numbers can't have letters in them and would visually give context. I.E. when people see (___) ___ - ____ they assume it's a phone number. 

**Examples**
http://demos.telerik.com/kendo-ui/maskedtextbox/index

---

## File upload:
A place that visually indicates that you can upload a file using the form element. One should be able to filter what file ext it accepts, allow for multiple files to be selected and perhaps limit file size?

**Examples**
Dashed border: http://getuikit.com/docs/addons_upload.html
Right attached button: http://www.creattor.com/files/77/3981/image-upload-form-screenshots-1.png

---

## Spinbox:
Similar to masked input in that it can only contain numbers and have 2 buttons for increment / decrement. Definable min and max values of course; ability to define a step value (could increment a time value by 15 minutes).

My favorite thing about most spinbox's ive seen is that it allows you to use your mouse wheel to scroll the value. Not a necessity but it's a pretty neat usability feature.

**Examples**
http://getfuelux.com/javascript.html#spinbox
http://jqueryui.com/spinner/#time

---

## Calendar / Datepicker:
This is pretty ubiquitous in the modern web. Useful features could be the ability to specify the format for a date. It would be nice if Semantic ran with it's own; or at least had a calendar that had consistent styling with the rest of the framework.

The ability to jump between months and years quickly I think is essential (see first example). JQuery's date picker doesnt include this feature. Also; a min and max feature would be good as well.

**Examples**
http://getuikit.com/docs/addons_datepicker.html
http://jqueryui.com/datepicker/

---

## Range input:
HTML5 has this input; but of course it looks very ugly and browser support for it is spotty at best. It would be nice to be able to mimic the behavior of the HTML5 version; define a step interval, single or double handle range. A foreseeable issue is being able to use on a touch screen device

**Examples**
http://foundation.zurb.com/docs/components/range_slider.html
http://www.jqueryrain.com/?0qRLJKK8
https://simeydotme.github.io/jQuery-ui-Slider-Pips/

---

## Pillbox / Tagbox:
Most of the stuff needed for this already exists in Semantic, just need the JS behavior for it. The ability to enter a series of (cancelable) tags that are appended into the text box as you type them. This custom form element could send these tags as JSON or a comma separated list

**Examples**
https://designmodo.github.io/Flat-UI/ (scroll down)
http://getfuelux.com/javascript.html#pillbox

**Comment by Anachron** [comment]
:+1:

@jlukic you need help here?

**Comment by geemang2000** [comment]
:+1:   @ph7vc   These would be awesome additions. I need that spinner today :) 
As a requirement for these, simple AngularJS integration should be kept in mind. E.g. non-hidden inputs under the covers.

**Comment by ph7vc** [comment]
@geemang2000: Im not very familiar with Angular, but it doesnt like input type hidden?

**Comment by geemang2000** [comment]
Correct, All the of the angularjs magic doesn't work (out of the box) with hidden inputs. 2 way binding requires non-hidden inputs.

**Comment by kvetoslavnovak** [comment]
All of them would be great for 2.0. Mostly appreciated is date picker and probably range slider. 

For datepicker there has been nice design posted already - 
![b63aa0dc-0538-11e4-9b57-f9a1c792032c](https://cloud.githubusercontent.com/assets/5719547/6347617/a3361d5c-bc19-11e4-9c22-98fe70ced8cb.png)
 https://github.com/Semantic-Org/Semantic-UI/issues/191

For range slider design we could use  Checkbox Slider design (class="ui slider checkbox") and connect it to JQuery default range slider.

**Comment by filipstachura** [comment]
:+1: for range slider (but in the end all of them)

**Comment by AronWatson** [comment]
[?]for all of them


On Mon, Mar 16, 2015 at 11:53 AM, Filip Stachura <notifications@github.com>
wrote:

> [image: :+1:] for range slider (but in the end all of them)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/1703#issuecomment-81277294>
> .
>



-- 
Regards
Aron Watson

Phone: (03) 4349242
Address: 39 Upper Ure Street, Oamaru

**Comment by kvetoslavnovak** [comment]
Anything new regarding calendar/date-picker?

**Comment by marcoT89** [comment]
I would really appreciate if i could use select2 multiselect plugin (input tags) for semantic-ui, and also calendar and datepicker with that! Awesome front framework! Congratilations anyway!

**Comment by jlukic** [comment]
Mutiselect is in next release, see [example here](https://github.com/Semantic-Org/Semantic-UI/issues/847#issuecomment-84169359)

**Comment by jlukic** [comment]
I've broken up these suggestions into separate issues
