### ISSUE TITLE
Unable to make search loading to work.

### ISSUE THREAD

**Issue by KeinTrong** [Semantic-Org/Semantic-UI#1704]
Had searched issue list but got no luck.

http://jsfiddle.net/Lk31m3xv/

I'm unable to make search loading to work when typing like your demo, please help.

**Comment by jlukic** [comment]
Your demo is working correctly for me.

**Comment by KeinTrong** [comment]
When you typing ( keyup jQuery event ) there is no "loading" class being add to the field, when typing it must replace search icon by loading icon.

Thanks.

**Comment by jlukic** [comment]
There is no load time it's searching locally. Load indication is for server requests.
