### ISSUE TITLE
Corner labeled input field with a pointing label does not format well

### ISSUE THREAD

**Issue by MGHollander** [Semantic-Org/Semantic-UI#1705]
The following code does not work like it should.

```html
<div class="ui corner labeled input field">
    <input type="text" placeholder="First name">
    <div class="ui corner label">
        <i class="asterisk icon"></i>
    </div>
    <div class="ui pointing label">
      Please enter a value
    </div>
</div>
```

![corner-pointing-label-input](https://cloud.githubusercontent.com/assets/1532664/5887692/06a95ffe-a3e0-11e4-9279-931ebecaed71.png)

**Comment by jlukic** [comment]
`input` needs to be a child of `field`. In general its unsafe to combine UI elements on the same element unless it is used in the documentation.
