### ISSUE TITLE
cant generate the docs

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1706]
Hi,
with the new separated docs, i dont know how to generate it, because it is not well explained, i asked here

http://stackoverflow.com/questions/28069067/how-to-generate-semantic-ui-offline-doc

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs#generating-sui-for-docs

**Comment by abdelouahabb** [comment]
yes. that is why i opened the issue, it is not well explained, in the past when everything was in the same folder it was easy. a graphical explaination would be welcome!

**Comment by Lisa-Williams** [comment]
Just pick what you're missing to get it complete.
(It probably has some typos.)

A terminal is required.

## Assumed folder structure:
```Text
path/to/your/bull polished/project
 |
 `_ docs
 |
 `_ learn
 |
 `_ ui
```

```Text
cd path/to/your/bull polished/project
```

## Clone the repos:

**docs**:
```git clone --recursive --progress -v "git@github.com:Semantic-Org/Semantic-UI-Docs.git" "docs"```
Cloned https://github.com/Semantic-Org/Semantic-UI-Docs (http://semantic-ui.com/)

**learn**:
```git clone --recursive --progress -v "git@github.com:Semantic-Org/Learn-Semantic.git" "learn"```
Cloned https://github.com/Semantic-Org/Learn-Semantic (http://learnsemantic.com/)

**ui**:
```git clone --recursive --progress -v "git@github.com:Semantic-Org/Semantic-UI.git" "ui"```
Cloned https://github.com/Semantic-Org/Semantic-UI (The Semantic UI framework)

**N.B.**
All 3 subfolders ```docs```, ```learn```, ```ui``` may be given different names.
Subfolders ```docs``` and ```ui``` **must** be adjacent folders.
At the moment ```learnsemantic.com``` (```learn```) is independent of the other 2 repos. So it could be placed anywhere you like.

## Install Gulp globally AND locally.
```Text
npm install -g gulp
cd "path/to/your/bull polished/project/ui"
npm install gulp
```
## Install the Semantic UI framework.
(Still in : "path/to/your/bull polished/project/ui")
```Text
npm install
gulp
```
  OR:
```Text
gulp install
```

## Install Docpad globally AND locally. Install Docpad plugins locally.

**Install globally**:
```Text
npm install -g docpad
```
Note: To update globally ```docpad upgrade```

Then install locally into ```docs```:
```Text
cd "path/to/your/bull polished/project/docs"
npm install docpad
docpad install eco
```

Then install locally into ```learn```:
```Text
cd "path/to/your/bull polished/project/learn"
npm install docpad
docpad install eco
```
Note: To update locally (docpad and plugins) run: ```docpad update``` inside the ```docs``` and ```learn``` folders.

**NB**
```docpad update``` purges/obliterates the ```docs/out``` folder (which was filled with ```dist``` and ```src``` folders by ```gulp build-docs```, ```gulp-serve-docs```, and ```docpad run```)
So when the time comes, run ```docpad update``` before building the Docs from the ```ui``` folder.
Run ```npm install docpad``` as root/Administrator (to avoid permission issues).
Definitely on Windows.
Sometimes also on Linux/OS X, if Node was installed "incorrectly".
But at least on Linux/OS X you can reinstall Node to correct this.
See: https://github.com/node-forward/help/issues/4

## Build the Semantic UI framework:
```Text
cd "path/to/your/bull polished/project/ui"
```
Only if required:
```Text
gulp clean
```
Followed by:
```Text
gulp build OR gulp watch
```

## Build the Semantic UI framework for the Documentation in the docs folder:
```Text
cd "path/to/your/bull polished/project/ui"
gulp build-docs OR gulp serve-docs
```
```gulp build-docs``` : Creates and fills ```docs/out/dist``` and ```docs/out/src```
```gulp serve-docs``` : Watches for source file changes in the ```ui``` folder and updates folders ```docs/out/dist``` and ```docs/out/src```.

## Generate the Semantic UI Documentation pages and start the local server:
```Text
cd "path/to/your/bull polished/project/docs"
docpad run
```
```docpad run``` : Creates all documentation files and folders (other than ```docs/out/dist``` and ```docs/out/src```) in the ```docs/out``` folder.


## Generate the learnsemantic.com  pages and start the local server:
```Text
cd "path/to/your/bull polished/project/learn"
docpad run
```
```docpad run``` : Creates all documentation files and folders in the ```learn/out``` folder.

## When your changes SUI framework variables, etc

1) Make your changes to the framework.
2) Rebuild the framework:
```Text
gulp clean
gulp build OR gulp watch
```
3) Update the docs:
```Text
gulp build-docs OR gulp serve-docs
```
4) Generate the documentation pages.
```Text
docpad run
```
Go back to 1)
If you used ```gulp watch``` and ```gulp serve-docs``` you should be fully automatic.

**Comment by abdelouahabb** [comment]
@Lisa-Williams wonderful! thank you!

Update: i got this
![sans titre](https://cloud.githubusercontent.com/assets/2527234/5889558/eaf4458c-a42d-11e4-922d-88cf59752f3d.jpg)

**Comment by Lisa-Williams** [comment]
// Once set-up you can use these commands to maintain your project:
```Text
gulp
OR
gulp default
OR
gulp check install // Run the installer when required (will ask questions).
                   // Otherwise default to gulp watch.

gulp clean      // Clean the dist folder

gulp build      // Build all files from source

gulp watch      // Watch for site/theme changes (Default Task)

gulp build-docs // Build files for the local Docs. Creates docs/out/dist and docs/out/src
gulp serve-docs // Watch the ui/src folder, and serve changes to the docs/out folder

gulp version    // Displays current version of Semantic
gulp help       // List all commands

gulp install    // Re-runs the installer. As if the first time (asks questions)
                // Possibly run gulp clean first.

// **No** need to call the following 2 directly.
// Just informational, to explain what selecting "RTL=yes" at installation does.
gulp build rtl  // RTL version of "gulp build". Run automatically instead of "gulp build", if you answered "yes" to RTL at installation.
gulp watch rtl  // RTL version of "gulp watch". Run automatically instead of "gulp watch", if you answered "yes" to RTL at installation.
```

**Comment by Lisa-Williams** [comment]
@abdelouahabb Doesn't look too good. Yet!
Looks like you don't have a completely filled ```cd "path/to/your/bull polished/project/docs/out``` folder.
Try this:
```Text
cd "path/to/your/bull polished/project/ui"
gulp clean
gulp build
gulp build-docs
cd "path/to/your/bull polished/project/docs"
docpad run
```

**Comment by abdelouahabb** [comment]
@Lisa-Williams i tried another trick, is to move the `dist` folder inside the folder being served, because it was giving a `404`, and now it works :+1: thank you again!
![sans titre](https://cloud.githubusercontent.com/assets/2527234/5889586/8251bb2a-a42f-11e4-94c0-bc22c9d23f49.jpg)

**Comment by Lisa-Williams** [comment]
Good!

But, I see that you have some other folders than Semantic-UI in ```Semantic/docs/out```.
Just be careful with ```docpad update```. Read my warning.
Only run it when really necessary because it causes what you have in your first screenshot.

Enjoy the framework. :)

**Comment by abdelouahabb** [comment]
ah,  i am sorry because i come from a world of static docs (python sphinx :D )

**Comment by Lisa-Williams** [comment]
No problem, all is working now.

That's a coincidence that you mention Sphinx,
I installed it yesterday to build the docs for this WP backend framework: https://github.com/ThemeFuse/Unyson

**Comment by abdelouahabb** [comment]
hehehehee the best command you can do (even there is not the `build` file), you just run `sphinx-build . ./out ` and you got your docs to the `out` folder ;)

**Comment by Lisa-Williams** [comment]
Yeah it was a lot simpler to build those Docs.
Maybe the SUI guys avoided Sphinx because it requires Python to be installed.
I'm just guessing of course.

**Comment by abdelouahabb** [comment]
I wanted those offline docs, so i can show some people how the web can be beautiful with other alternatives than bootstrap, and i know that they will find a reason to switch to SUI ;)

**Comment by Lisa-Williams** [comment]
Yes, BS is a bit popular. Even the NuGet package manager in VS has it.
But there are so many other excellent frameworks though.
Semantic UI being the most awesome. Although it misses a couple of components I would like to see but can easily integrate from Github anyway. So that's a non issue actually.
What I like about SUI is that it looks extremely good and eye catching with the default theme. (A must to attract new FE devs,)
But the tons of variables and overrides to customize it are the best part.
And you have an almost instant Style Guide because your customizations show up in your local Docs instance. Courtesy of ```gulp build-docs``` and ```gulp serve-docs```.
Right now I have 3 versions of the Docs default, light, and dark. Which I can compare and reference  side by side.

**Comment by abdelouahabb** [comment]
A new world to discover :dancer:
can you please put the answer here so i will validate it as answered? http://stackoverflow.com/questions/28069067/how-to-generate-semantic-ui-offline-doc

**Comment by abdelouahabb** [comment]
here is the link of the generated docs (learn and docs):
https://drive.google.com/file/d/0B-Iu7VFIRkh4d0RTTkp3TEJtdmM/view?usp=sharing

**Comment by RobertinoValue** [comment]
@abdelouahabb I would have to register at SO for that. And I don't like SO.
Sorry about that.

**Comment by Lisa-Williams** [comment]
@abdelouahabb OK, I'm at my own notebook again.
Like I commented before. I would have to register at SO for that. And I don't like SO.
Sorry about that.

**Comment by abdelouahabb** [comment]
@Lisa-Williams no problem ^_^
Then, can i copy your answer and put it there?

**Comment by Lisa-Williams** [comment]
It's licensed under [WTFPL](http://www.wtfpl.net/). :)
I don't care about getting attribution.
Just get on with it.

**Comment by abdelouahabb** [comment]
ah thank you :P
