### ISSUE TITLE
[Search] Allow query terms to match each word

### ISSUE THREAD

**Issue by rSafari** [Semantic-Org/Semantic-UI#1707]
Hello ,

i have almost 4000 record and i want to use the ui.search functionality to have a full text search on them .
there is no problem , search is working perfectly and fast . ( i export them as json data and use the json data to search ).

take this as an example :
```
var Records = [

    {id: '1', title: 'Hello There how are you', description: 'ask me'},
    {id: '2', title: 'lorem ipsum is fine but not always', description: 'ask me'},
    {id: '3', title: 'my name is reza and im 24 year old', description: 'ask me'},
    {id: '4', title: 'that guy name is michele', description: 'ask me'},
    {id: '5', title: 'oh i see some snow out there', description: 'ask me'},

]
```

and have this for calling this :

```
$('.ui.search')
  .search({
      source: content,
      cache: true,
      searchFields: [
        'title', 'id'
      ],
      searchFullText: true
  })
;
```

so , as you see here i do the search in title and id . now take this queries as an example 

1. Hello There
    result : Hello There how are you

2. Name is 
    result : my name is reza and im 24 year old,
                that guy name is michele

3. name reza
    result : none

4. name michele 
    result : none

5. name + reza + 24
    result : none

look at those last three queries . how can i make this happen ?
like the google , we use + to attach words together .

**Comment by rSafari** [comment]
is it going to be around soon ?

**Comment by jlukic** [comment]
I have to evaluate the complexity. Currently everything occurs in one regexp match per field which is pretty quick. Increasing the time per record will have implications on large datasets.

**Comment by agborkowski** [comment]
#tip full text js engine
@source http://lunrjs.com/

**Comment by jlukic** [comment]
Thanks @agborkowski useful for me, i was unfamiliar with *steming* and *stop words*

**Comment by jlukic** [comment]
Pushing this back to `1.10` not enough time this release

**Comment by rSafari** [comment]
i think you should consider adding this as a plugin and not in the core .
the core function is good for public , try to release this enhancement as plugin .

**Comment by jlukic** [comment]
As a consolation i've added an implementation of [fuzzy search](https://github.com/bevacqua/fuzzysearch) as the new full text search algorithm. 

The use of meta characters like "+" to separate words will probably not come for a bit.
