### ISSUE TITLE
Custom form validation rules

### ISSUE THREAD

**Issue by rodsnjr** [Semantic-Org/Semantic-UI#1708]
Is there any way to call a direct function to make validation rules?

E.g.

username: {
      identifier : 'username',
      rules: [
        {
          type: function(text){
                            (algorithm ... )
           },
          prompt : 'Please enter a username'
        }
      ]
    }

I don't see anywhere on docs, and something like that would be great!

**Comment by jlukic** [comment]
You can specify custom form validation rules by adding rules to $.fn.form.settings.rules

```javascript
$.fn.form.settings.rules.myrule = function(value) {

}
```

**Comment by jlukic** [comment]
I'll add this to docs.

**Comment by rodsnjr** [comment]
Great, thanks, the docs specify

"Validation rules are found in $.fn.form.settings.rules, to add new global validation rules, modify $.fn.form.settings.rules to include your function."

But an example like you gave would be helpful!

**Comment by talha-asad** [comment]
There are use cases where you wouldn't want to put a rule in ```$.fn.form.settings.rules``` for one special field, don't you think it would make sense if type is a function and it is run similarly to how a global rule runs? Would make it much more easy to create one-off rules.

**Comment by eyalw** [comment]
Maybe not "type", because you are no longer specifying a type of validation, but a "validate" param or "fn" param that is given a function.

@jlukic will you consider adding such api? it does sound a bit too messy to put specific form validation rules in the "global scope" of $.fn.form.settings.rules.

**Comment by noobiwan** [comment]
+1 for inline function option

**Comment by hbaccara** [comment]
+1 for inline function option

**Comment by pedrorodrigues** [comment]
+1 for inline function option

**Comment by achimkoellner** [comment]
+1 for inline function option

**Comment by Buntix** [comment]
+ditto
handy for pre-filtering before passing to existing validators, e.g. 

```javascript
function (cardNumber, cardTypes) {
  return $.fn.form.settings.rules.creditCard(cardNumber.replace(/ +/g, ''), cardTypes);
}
```

to allow people to enter credit card numbers with spaces so they can scan/correct them more easily.

also for prototyping and testing hypotheses before formalising them as part of $.fn.form.settings.rules

**Comment by VSG24** [comment]
+10000 for inline rules
