### ISSUE TITLE
Dropdown changes position when attached to input

### ISSUE THREAD

**Issue by kenlimmj** [Semantic-Org/Semantic-UI#1709]
### Problem 
I was trying to create a form field which consists of a text/number input with a dropdown by the side, but encountered an issue wherein clicking on the dropdown (or switching it to an active state) moved it to the next line below the text/number input.

### Reproduction
http://jsfiddle.net/709hr0dy/1/

Environment: Chrome 40 OS X

### Expected Behavior
The dropdown should remain on the same line as the input with position unchanged.

### Further Details
Activating the dropdown causes ``display: inline-block !important;`` to be set on ``.ui.label.visible``, but ``display: table-cell`` is required to keep the dropdown in the correct position. As my own fix, I overwrote this specific case using an inline style, but that's hacky at best.

I'd appreciate any help, or if I'm doing this totally wrong, do let me know!

**Comment by jlukic** [comment]
I think your JSfiddle link is incorrect. Check it

**Comment by kenlimmj** [comment]
Whoops, fixed it!

**Comment by jlukic** [comment]
Simple inheritance issue i'll patch on monday.
