### ISSUE TITLE
Moving the `src` directory

### ISSUE THREAD

**Issue by czechnology** [Semantic-Org/Semantic-UI#1710]
I'd like to move (some of) `src` directory to separate it from the rest of the library. I expected a simple change to the `semantic.json` file to update the paths would be enough but that doesn't seem to help - when running `gulp build`, I get the error

```
$ gulp build
Using gulpfile /path_to_lib/gulpfile.js
Starting 'build'...
Building Semantic
Cant build LESS. Run "gulp install" to create a theme config file
```

Is this even possible?

(changing the output directories works as expected)

**Comment by jlukic** [comment]
Many gulp paths rely on files expected in `src/`
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/defaults.js#L117

You can override these in `semantic.json` with a custom path, however moving `src/` has not been tested thoroughly.

**Comment by czechnology** [comment]
Thanks for your reply.

I've tried modifying those paths in `semantic.json` but is seems like they have little or no effect, unfortunately.

**Comment by raae** [comment]
If anyone else is looking at this. I successfully changed the source path of site to my project folder, it needed to be relative to the semantic folder. This allowing me to .gitignore the whole semantic folder.

```
{
  "base": "semantic/",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "../app/styles/site/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "rtl": false,
  "version": "2.1.8"
}
```
