### ISSUE TITLE
text-align on columns shouldn't be there

### ISSUE THREAD

**Issue by romuloctba** [Semantic-Org/Semantic-UI#1711]
Hi, i see that `.ui.grid > .column:not(.row), .ui.grid > .row > .column {` (line 73, grid.less) recieves a `text-align: left` property.

but `ui.grid` itself already is `text-align: left` ( line 28 grid.less)

So i'd sudgest that `.ui.grid > .column:not(.row), .ui.grid > .row > .column {` recieves *no text-align or `text-align: inrheit`*. 

Because this way one can set `text-align: center` or whatever to the column without having to win by css specificity or `!important`

I'd pull request this but i'm not sure if i'm right

**Comment by jlukic** [comment]
I don't think there's any reason for that rule to be there. I believe it's a mistake.

`ui centered grid` uses `text-align: center` to center `inline-block` columns. But this is already cancelled out for `centered grid` in the accompanying definition.

**Comment by jlukic** [comment]
Fixed in next patch.

**Comment by romuloctba** [comment]
Thank you :) I love semantic-ui

**Comment by jlukic** [comment]
Released
