### ISSUE TITLE
Typo in Behaviors session of ui rating in semantic-ui website

### ISSUE THREAD

**Issue by williamkhshea** [Semantic-Org/Semantic-UI#1712]
It should be:

```$('.ui.rating') .rating('behavior name', argumentOne, argumentTwo);```

instead of 
```$('.ui.rating') .modal('behavior name', argumentOne, argumentTwo);```

![2015-01-25 15_02_34-rating _ semantic ui](https://cloud.githubusercontent.com/assets/4775489/5890703/83ef1bde-a4a3-11e4-8ad1-c90375a0d888.png)

**Comment by jlukic** [comment]
Thanks! https://github.com/Semantic-Org/Semantic-UI-Docs/commit/53e72d38c17cbede3341c2b095cbb0cfc5913c9e
