### ISSUE TITLE
CSS file size & Bless

### ISSUE THREAD

**Issue by montecruiseto** [Semantic-Org/Semantic-UI#1713]
Hey,
the filesize of my packaged .css (400kb) and min.css (290kb) is now going over the IE<10 max selector limit. Is this a common issue or am I going against best practices?

These are my used components

```

  "components": [
    "reset",
    "site",
    "button",
    "divider",
    "flag",
    "form",
    "header",
    "icon",
    "image",
    "input",
    "label",
    "list",
    "segment",
    "grid",
    "menu",
    "message",
    "card",
    "comment",
    "statistic",
    "accordion",
    "sidebar"
  ]
```

Such a pity, because I wanted to use even more of semantic, but now I'm starting to feel a bit gluttonous :-)

I see no way out at this point than to add a supplementary production step using https://www.npmjs.com/package/gulp-bless
Ever considered incorporating Bless into the Semantic build tooling?

**Comment by jlukic** [comment]
I understand the need for Bless for IE9, but I don't believe we should add it to the gulp pipeline for users.

SUI supports IE9 only with the applicable css prefixes. In actuality, things probably look/work pretty terribly on that browser (unfortunately).
