### ISSUE TITLE
Change trigger on select

### ISSUE THREAD

**Issue by zelenin** [Semantic-Org/Semantic-UI#1714]
When you select an option in dropdown, it triggers change event on hidden select - that's right.
But if hidden select already has selected item, dropdown trigger change event on its initialization.

Issue in this commit https://github.com/Semantic-Org/Semantic-UI/commit/a3932fcbdbec684cdd20e6b0fc7eacdad78377bf
Before it no bad behavior.

there is https://github.com/Semantic-Org/Semantic-UI/blob/b86b5ced8651b29060be941451ae93d3c4261a7b/src/definitions/modules/dropdown.js#L1158

Demo http://yii2-semantic-ui.zelenin.pw/yii2-widgets/grid-view.html 
Change event on dropdown submitting of form. After page refresh option is already selected and change event refresh of page infinitely.
http://yii2-semantic-ui.zelenin.pw/yii2-widgets/grid-view.html?ModelSearch%5Bid%5D=&ModelSearch%5Bname%5D=Title+2&ModelSearch%5Btotal%5D=

**Comment by jlukic** [comment]
Thanks, I'll take a look

**Comment by jlukic** [comment]
I can't find the corresponding javascript code that is causing the refresh issues to occur. 

Can you create a JSFiddle, or at least, copy and paste in this thread the specific code that is causing the issue?

**Comment by zelenin** [comment]
oh, I created jsfiddle and understood that it's yii.gridView issue.
If dropdown initialised later than yii.gridView
```

**Comment by jlukic** [comment]
Ah i see. Thanks for clarifying. I was a bit worried there for a second.
