### ISSUE TITLE
When to release the layout ?

### ISSUE THREAD

**Issue by raymondZhong** [Semantic-Org/Semantic-UI#1715]
When to release the layout ?

**Comment by jlukic** [comment]
It probably will be a while unfortunately.

**Comment by Anachron** [comment]
@raymondZhong @jlukic which layout are you guys talking about?

**Comment by raymondZhong** [comment]
Semantic-UI   layout   coming  soon!    
Now ,  s-ui  don't have    layout  component !

**Comment by ShawnOceanHu** [comment]
Omg,  can't wait for this : )
Css gives you millions of things, yet no simple stuff like layouts.
Is there a place that I can get a preview?

**Comment by ShawnOceanHu** [comment]
Actually using famo.us for layout might be a better idea, I used that for apps with Semantic-UI, both frameworks are amazing, and combining the two you get the native-like layout system/performance yet the simplicity and beauty.
