### ISSUE TITLE
Dropdown menu  

### ISSUE THREAD

**Issue by mayhem-ahmad** [Semantic-Org/Semantic-UI#1718]
Anchor tag inside dropdown menu is not working, it doesn't link to the href when clicked on .
it's only add  two classes like this ("active selected") to the anchor .

please advise .
Thanks for your help.

**Comment by jlukic** [comment]
I just tested links are working fine in dropdowns. There was a bug where they did not work in sub-menus before `1.8` #1638 

Please remember when posting bugs to add a test case, be as descriptive as possible, and to always search for issues before reporting.

**Comment by mayhem-ahmad** [comment]
Sorry for not being descriptive as possible .
here is a test case https://facebookstore2.shopgo.io/myapp/test.dev.shopgo.io/en 

please advise .
Thanks for your help.

**Comment by jlukic** [comment]
Your page isn't loading for me. 

Please publish a *reduced* test case, that only shows the aspects of your page that are broken. 

You can fork a link to create a JSFiddle from our readme.
