### ISSUE TITLE
Search Dropdown - Doesn't exist behaviour

### ISSUE THREAD

**Issue by waxim** [Semantic-Org/Semantic-UI#1719]
It would be very useful to be able to set behaviour for dropdown searches where a searched value does not exist. such as ``ui dropdown search addable`` then the searched value would appear as an option that can be clicked and this would add the clicked value as a select option and select it.

**Comment by jlukic** [comment]
I don't believe this use case is general enough to be added. You can modify noResults message by updating `$.fn.search.settings.templates.message`.

I do however think though there should be a `onNoResults` callback that fires only when no results are returned.

**Comment by jlukic** [comment]
Oops misread this to be about `ui search`

`ui search dropdown` already has `onNoResults` callback. This can be used to attach behavior like you are describing.
