### ISSUE TITLE
Add support for styling input type of time

### ISSUE THREAD

**Issue by Trouche** [Semantic-Org/Semantic-UI#1721]
I have the luxury in our application of supporting a limited subset of browsers.  In our case the html5 time input works quite well.  I have noticed that you support most of the other input formats in the CSS files.  Would you consider adding support for time as well?  I would really prefer to avoid branching the codebase for something simple like input[type='time'] in the CSS. 

John

**Comment by rosetree** [comment]
That’s a really good enhancement. Would you also add `type=date`? (See [w3 reference][].)

[w3 reference]: http://www.w3.org/TR/html-markup/input.date.html

**Comment by Trouche** [comment]
I believe type=date is already defined correctly.

**Comment by rosetree** [comment]
Ok, I think I misunderstood you. I thought you meant something similar to #191. As far as I know that’s not done yet. You’re right, there are some styles on `type=date`.

**Comment by Trouche** [comment]
Ah yes.  I am familiar with that discussion.

**Comment by jlukic** [comment]
Added in `next`
