### ISSUE TITLE
Tab selecting

### ISSUE THREAD

**Issue by jmasejo** [Semantic-Org/Semantic-UI#1722]
Hello how to get the name of active tab?

**Comment by ph7vc** [comment]
Easy enough: http://jsfiddle.net/u3uyyocp/1/

JS will add the class `active` to the active tab, so grabbing said text is very simple: `$("#tabs>.item.active").text()`

Just remember to craft your selector to point to the correct container for the tabs, since pages may have several tab groups

**Comment by jmasejo** [comment]
thank you!
