### ISSUE TITLE
[Popup] offset bug when target is hidden

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#1723]
When you define a hidden element (e.g. the `select` element of a `dropdown`) as popup target the popup is not placed correctly.
See an example here: http://jsfiddle.net/o0mwfwo6/1/

I guess the source of this problem is jQuery's `offset` computation which cannot handle hidden elements. But perhaps we can do better? :smile:

**Comment by ph7vc** [comment]
http://jsfiddle.net/o0mwfwo6/2/

Here is a fix

**Comment by larsbo** [comment]
Looks good to me. Thank you, @ph7vc !
But should be tested in other situations. `visibility: hidden` often produces some unexpected things.

**Comment by ph7vc** [comment]
I don't think this is a permanent solution by any means. If it was me, I'd opt for using an ID on the element instead of trying to use the generic selector. It's cleaner imo than trying to do: `$('select')[0]` or `'select'`

**Comment by larsbo** [comment]
I will test both versions tomorrow together with other elemens and actions.

The generic `select` was just for the fiddle, of course.

**Comment by jlukic** [comment]
What's the use-case for pointing to an element hidden with display: none? 

Getting offset position on a hidden element requires a bit of tomfoolery that would degrade performance + add complexity to popup show code. I think the safest path is if you need to use a popup on a hidden element to just set its width/height to 0, or use a different method for hiding it like `visibility: hidden;`

**Comment by larsbo** [comment]
My use-case is a collection of dynamically generated select elements converted to `dropdown` modules which should get a popover triggered by another element (like in the fiddle).
The select elements have ids for easy querying.
That's why I tried to use the selects but It would also possible to use `next()` or `nearest()` to get the generated `.dropdown` I think.

**Comment by ph7vc** [comment]
You could also use the `.parent(".ui.dropdown")` method to get the same JQuery object

**Comment by larsbo** [comment]
Sorry, I meant `parent()` instead of `next()`. 
I'm absolutely satisfied with the mentioned possibilities.
If there is no other known use-case with hidden elements the issue can be closed.

**Comment by jlukic** [comment]
Closing discussion. Hopefully this should help others with similar issues in the future.
