### ISSUE TITLE
[Dropdown] Auto change direction if too close to top or bottom

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#1724]
For longer form or form within a popup where the selection is either at top or bottom, the dropdown menu gets hidden and user have to scroll to see the option.   

Is it possible to auto change the direction of the dropdown list menu base on how close it is to the top ro bottom edge.

If at bottom, if the dropdown list does not have room, it will automatically open from top, etc - similar to how the default selection works.

Thanks

**Comment by nicbarker** [comment]
I'm looking for this feature, and I'm willing to implement a PR if needed. Any word on if this is already in development by someone?

**Comment by jlukic** [comment]
I'm going to implement this today

**Comment by jlukic** [comment]
Animation framerate is a bit choppy from recording a GIF but you can get idea 

![foo](https://dl.dropboxusercontent.com/u/2657007/dropdown.gif)

**Comment by faisalkhanchat** [comment]
Have any body solution for this question ?
