### ISSUE TITLE
Dropdown - Category Selection active object is overflow.

### ISSUE THREAD

**Issue by grass0916** [Semantic-Org/Semantic-UI#1725]
![2015-01-28 12 41 13](https://cloud.githubusercontent.com/assets/6274807/5922470/d21aa6ae-a686-11e4-9c39-1ddc870833f9.png)

---

[Click here to code of official site](http://semantic-ui.com/modules/dropdown.html#/examples)

Category 1
Category 2
  --- item A
  --- item B
  --- item C
Category 3
  --- item D
  --- item E
  --- item F

If 'Category 3' is active, when I browse the others categories (like 'Category 2') and show the their sub-items (like item A~C).

Will see the gray cover of active object ('Category 3') upper than layer of sub-items.

---

Sorry, I will make my English better :")

**Comment by jlukic** [comment]
What browser are you using? I'm not seeing this in FF and chrome with same conditions.

**Comment by ph7vc** [comment]
Mine does the same in both Chrome and Firefox. I'm colorblind and would never have noticed that without very close examination (zoom in 400%), it is very subtle

Item's with `active` class and the items in the submenu both have `z-index: 12`. 

I'm using Chromium Build 39 and Firefox 35 for Ubuntu 14.04

Screenshot:
![semanticuierror](https://cloud.githubusercontent.com/assets/5940454/5925132/2758d7ae-a627-11e4-83da-b2c5cb213d9f.png)

**Comment by jlukic** [comment]
![Foo](https://dl.dropboxusercontent.com/u/2657007/drop.jpg)

This is what I'm seeing on Win/Chrome30

**Comment by ph7vc** [comment]
It's when category 3 has class of `active` since that has a slight highlight to it

**Comment by grass0916** [comment]
@jlukic I'm Mac OSX, FF 35.0.1.

ph7vc is right, have to choose any category to active.

**Comment by grass0916** [comment]
@jlukic :)

**Comment by jlukic** [comment]
Still unable to reproduce on windows or linux. Not sure what to do.
