### ISSUE TITLE
Dropdown - Upward direction arrow is pointing down?

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#1726]
Is there a setting options that auto change that down arrow icon?  

I currently just manually set the html markp to have the class "upward" 

I am only using the stand alone dropdown.css and js NOT the whole semantic package.  if other elements are needed what are they

Thanks

**Comment by jlukic** [comment]
Sorry this is fixed in `next` but forgot to comment
https://github.com/Semantic-Org/Semantic-UI/commit/b3dd117747bf8a05843212cc33ce81964adeb454
