### ISSUE TITLE
[Cards] Add Colored Variations

### ISSUE THREAD

**Issue by romuloctba** [Semantic-Org/Semantic-UI#1731]
Hey.
I noticed that `segment` can be colored, like `ui red segment`, but not cards. BUt hey, did you notice that cards are simply PERFECT for coloring? Let me show ya:
![image](https://cloud.githubusercontent.com/assets/2955932/5940562/e3f955fc-a6f2-11e4-8b06-bcbcce570641.png)

Do you think a PR with this could be accepted? Yeah it is kindda weird using box-shadow to color it.

I don't really like the `ui segment` and I think `ui card` is way more elegant, that is why i'm thinking in colors. What do you think?

**Comment by Anachron** [comment]
:+1:

**Comment by romuloctba** [comment]
Just pulled, please check at 075efb506bbec2ef7dd5d387537e01170f0f3407

**Comment by jlukic** [comment]
Released earlier
