### ISSUE TITLE
Top sidebar in context issue

### ISSUE THREAD

**Issue by tecoad** [Semantic-Org/Semantic-UI#1732]
I have a top sidebar placed in context in a div.
However, the context div sets a height automatically the size of the viewport. The behavior I wish was to have the context expands vertically as the sidebar appears.

It seems the context use was designed for left/right sidebars only. 
Ive not seen in context uses of top/bottom sidebar in docs. Is this actually possible?

Check fiddle:
http://jsfiddle.net/ryf0m2f5/2/

**Comment by jlukic** [comment]
Just follow the example html..

http://jsfiddle.net/z32jna9w/
