### ISSUE TITLE
Floated column on responsive?

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#1734]
I thought I could use `right floated` columns to have better source order, i.e. displaying the asides in the right hand side of the page *before* other stuff in single column mobile layout.

However, it would appear that even if I put the floated and normal columns inside a `stackable grid`, the float is not cleared on mobile and things mess up. If the floated column is not very wide, it will even sit next to the main column, with both being very thin.

This problem seems like an obvious one, so I wonder whether I'm missing something? Are there other tricks for showing something to the right on desktop and then showing it at the top on mobile?

Also, what are those floated columns actually good for?

**Comment by jlukic** [comment]
Can you provide a JSFiddle where a `floated` column appears broken in `stackable grid`.

**Comment by dalgard** [comment]
Yes. Thanks.

http://codepen.io/dalgard/pen/zxEQLw?editors=110

**Comment by jlukic** [comment]
Thanks for the test-case.

Fixed in `next`.

**Comment by Pym** [comment]
I used the same trick as @dalgard to show one column on the right on desktop and at the top on mobile but it seems to be broken in 2.1.

Is there any way to reorder column in stacked mode right now?

**Comment by jlukic** [comment]
Yes, there is a `reverse mobile` setting.
http://semantic-ui.com/collections/grid.html#reversed
