### ISSUE TITLE
link in header not colorable

### ISSUE THREAD

**Issue by dalu** [Semantic-Org/Semantic-UI#1735]
```html
<header class="ui page grid">
    <div class="column">
        <div class="ui inverted blue segment">
            <h1 class="ui inverted header">
                <a class="ui white link" href="/">Header</a>
                <div class="sub header">Sub Header</div>
            </h1>
        </div>
    </div>
</header>
```
Header color is blue, because it's a link.
I can't give it a color, except with style="color: white"
Also the inverted header is missing "white".

**Comment by ph7vc** [comment]
http://jsfiddle.net/6s4cs6z6/2/

Looks like anchor tags don't inherit color from the header class. Not sure if bug or intentional

**Comment by jlukic** [comment]
Link are unique in that they don't inherit colors in css. SUI doesn't specify any rules for links inside header.

**Comment by dalu** [comment]
Ok so a top of the page logo link text would always be blue (or link color) colored.
Except if overridden with a custom, additional stylesheet.

**Comment by jlukic** [comment]
Link colors are inherited from `@linkColor` which is set in `site.variables`

**Comment by Fefas** [comment]
Hello!

I believe it would be great to change the colors of links by adding a class like the oders elements:

```html
<div class="ui blue button">Button</a>
<a class="ui black" href="http://blablabla.com">Link to blablabla</a>
```

I use semantic-ui just importing it on the `head` tag and I had already this *link color problem* 3 times. I find terrible to fix in my `css` file.

So in my opnion: color classes to the `a` tag would be very nice :)

Thank you

**Comment by swalladge** [comment]
What was the outcome of this issue? I'm having the same issue where links in headers (as well as links in general) can't be set to the right colour unless I manually add my own color styles. This makes it annoying when I want links in headers in an inverted segment or menu.

**Comment by Bandlou** [comment]
To put it manually in the SUI style you can add this code to your semantic/src/site/globals/site.overrides file:
``
/*-------------------
        Links
--------------------*/

/* - - - - - - - - -
  Color variations
- - - - - - - - - */

/*--- Brown ---*/
.ui.brown.links .link,
.ui.brown.link {
  color: @brown;
}
.ui.brown.links .link:hover,
.ui.brown.link:hover {
  color: @brownHover;
}

/*--- Orange ---*/
.ui.orange.links .link,
.ui.orange.link {
  color: @orange;
}
.ui.orange.links .link:hover,
.ui.orange.link:hover {
  color: @orangeHover;
}

/*--- Yellow ---*/
.ui.yellow.links .link,
.ui.yellow.link {
  color: @yellow;
}
.ui.yellow.links .link:hover,
.ui.yellow.link:hover {
  color: @yellowHover;
}

/*--- Olive ---*/
.ui.olive.links .link,
.ui.olive.link {
  color: @olive;
}
.ui.olive.links .link:hover,
.ui.olive.link:hover {
  color: @oliveHover;
}

/*--- Green ---*/
.ui.green.links .link,
.ui.green.link {
  color: @green;
}
.ui.green.links .link:hover,
.ui.green.link:hover {
  color: @greenHover;
}

/*--- Teal ---*/
.ui.teal.links .link,
.ui.teal.link {
  color: @teal;
}
.ui.teal.links .link:hover,
.ui.teal.link:hover {
  color: @tealHover;
}

/*--- Blue ---*/
.ui.blue.links .link,
.ui.blue.link {
  color: @blue;
}
.ui.blue.links .link:hover,
.ui.blue.link:hover {
  color: @blueHover;
}
``

**Comment by mbeche** [comment]
I agree - was the resolution to this simply "use custom css"? It would be nice to have semantic-ui solutions to this problem

**Comment by dalu** [comment]
Yeah I've abandoned semantic-ui because of this.

**Comment by coder8keyboard** [comment]
any solution for this? I don't want to use inline styling on top of class 'header' a tag.

**Comment by chintansheth** [comment]
I have the same issue how to change colour to a specific header

**Comment by erpx** [comment]
Anything yet?
