### ISSUE TITLE
[Dropdown] Search dropdown displays grid items incorrectly

### ISSUE THREAD

**Issue by NeArh** [Semantic-Org/Semantic-UI#1737]
Hello,

Please follow the link:
http://jsfiddle.net/kv67x3tm/

As you can see:
1) After selection, the selected item is displayed wrong
2) Search is working only for the 1st column

Regards,
Alex.

**Comment by jlukic** [comment]
Combining two elements on a single div will sometimes produce unexpected results. 

Try grid as a child element
http://jsfiddle.net/7oydh33k/

**Comment by ph7vc** [comment]
@jlukic: If selected, text container that holds the value will make the grid really squished.

I found that setting `display:block` to the `text` div will be able to render the grid child properly.

http://jsfiddle.net/wb0bbL06/1/

This seems to have no effect on other items, perhaps this could be an enhancement?

**Comment by jlukic** [comment]
I've experimented with `display: block;` with dropdown text. 

I've run into too many issues even just using it with `fluid dropdown` when mixed with other variations, or dropdown types other than `selection`.  I will keep it as `inline-block`
