### ISSUE TITLE
Semantic UI Firefox, input overflow

### ISSUE THREAD

**Issue by mhashem** [Semantic-Org/Semantic-UI#1738]
This code associated with the resulting image look in firefox,

	<div class="ui one column stackable center aligned page grid">
		<div class="column six wide">
			<div class="ui segment">
				<h4 class="ui dividing header">Account Info</h4>
				<form class="ui form error">
					<div class="field">
						<div class="ui icon input">
							<input type="text" placeholder="Login" name="login"
								id="login" />
							<i class="user icon"></i>
						</div>
					</div>
					<div class="field">
						<div class="ui icon input">
							<input type="password" placeholder="Password"
								name="password" id="password" />
							<i class="lock icon"></i>
						</div>
					</div>
					<input type="submit" name="submit" value="Submit" class="ui blue button" />
				</form>
			</div>
		</div>
	</div>

![screen shot 2015-01-30 at 10 45 45 pm](https://cloud.githubusercontent.com/assets/8841913/5983005/c7f4be06-a8d1-11e4-8b56-4cd287785051.png)

**Comment by ph7vc** [comment]
http://jsfiddle.net/p3Lpyuxk/

Looks fine to me. Tested in Chromium 39 and Firefox 35 for Ubuntu 14.04

@mhashem: What version of Firefox are you using and on what operating system?

**Comment by mhashem** [comment]
@ph7vc I am using Firefox 27.0.1 on a Mac OS X 10.10

**Comment by Anachron** [comment]
Looks fine on Firefox 35 on Win7 / 64Bit.

**Comment by jlukic** [comment]
Closing for now, unless further reports.

**Comment by mhashem** [comment]
I know it looks fine on firefox 35 but I am reporting that from a ( Firefox 27.0.1 on a Mac OS X 10.10 )
unless Semantic-UI wont support this version, I am upgrading too to Firefox 35 but maybe for future considerations .

**Comment by ewuletstalk** [comment]
Semantic doesn't work on what I think, all under Firefox 30 versions.

**Comment by jlukic** [comment]
http://caniuse.com/#feat=flexbox

Exactly, all under 31.

**Comment by ewuletstalk** [comment]
Also, maybe related but Semantic is virtually unusable in Firefox 29-down because box-sizing is completely broken. But it can easily be fixed by making this update in reset.css:

*,:after,:before{
-webkit-box-sizing:inherit;
-moz-box-sizing:inherit;
box-sizing:inherit
}

html{
-webkit-box-sizing:border-box;
-moz-box-sizing:border-box;
box-sizing:border-box;
}

I noticed it wasn't in the newest Semantic-UI-1.12.3, which it probably should be.

**Comment by yash02** [comment]
Thanks to ghost. It worked perfectly fine for me.
