### ISSUE TITLE
Duplicate Styles in RTL Build

### ISSUE THREAD

**Issue by mese79** [Semantic-Org/Semantic-UI#1740]
Hi
First of all thanks for the great job!
But i wonder why the css file has such a huge size(~650k uncompressed). i checked the css and i've found there is some duplicates like in table:

```
line: 18313 > .ui.table {...}
line: 27285 > .ui.table {...}
```

Which they are exactly the same. So am i missing something? is there any gulp command to omit the duplicates?
Thanks.

**Comment by ph7vc** [comment]
Using this command: `grep -n -B2 -A3 '^.ui.table {' semantic.css`, I see that it does repeat itself once.

```
18328-/* Prototype */
18329-
18330:.ui.table {
18331-  width: 100%;
18332-  background: #ffffff;
18333-  margin: 1em 0em;
--
19433-/* Standard */
19434-
19435:.ui.table {
19436-  font-size: 1em;
19437-}
19438-
--
27355-/* Prototype */
27356-
27357:.ui.table {
27358-  width: 100%;
27359-  background: #ffffff;
27360-  margin: 1em 0em;
--
28460-/* Standard */
28461-
28462:.ui.table {
28463-  font-size: 1em;
28464-}
28465-

```

My first thought was that it had to do with theme overrides, but I'm thinking this may be a glitch with the build tools, this doesn't appear to be the case in `table.css` that is generated using `gulp build`.

**Comment by mese79** [comment]
I ran your command on **semantic.rtl.css** and this is my result:
    
      4 .ui.table {
      4 .ui.table td.warning {
      4 .ui.table td.positive {
      4 .ui.table td.negative {
      4 .ui.table td.error {
      4 .ui.table td.active {
      4 .ui.table td {
      4 .ui.sortable.table thead th.sorted:hover {
      4 .ui.rating .icon {
      4 .ui.form {
      4 .ui.form .required.field > .checkbox:after {
      4 .ui.form .inline.field > .ui.input {
      4 .ui.form .grouped.fields > label {
      3 .ui.styled.accordion .accordion .active.title {
      3 .ui.popup {
      3 .ui.menu .item {
      3 .ui.items > .item {
      3 .ui.dropdown > .dropdown.icon {
      3 .ui.dropdown .menu > .item > img {
      3 .ui.animated.button .hidden.content {

**Comment by Einkoro** [comment]
Is this still an issue with the new build tools?

**Comment by mese79** [comment]
I don't know about the new build tools, but after i updated my git repo, `gulp build` with `rtl: true` in semantic.json file gives me the same duplication parts as above.

**Comment by vinayakkulkarni** [comment]
is this issue solved?

**Comment by mese79** [comment]
It seems solved.
