### ISSUE TITLE
Not understanding responsive columns

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#1743]
http://semantic-ui.com/collections/grid.html#responsive-width

In this example, an element is written like this: `<div class="four wide two wide large screen one wide widescreen column">` – but Chrome filters out the repeated class `wide` so the selector doesn't work.

What gives?

**Comment by jlukic** [comment]
Chrome does not filter out the additional class names.

See https://github.com/AmpersandJS/amp/issues/52 #396.

You may have trouble when using code that returns class lists, or front end libraries that remove repeated class names.

**Comment by dalgard** [comment]
I see. Meteor is out for responsive columns, then. Thanks for saving me time figuring this out :+1:

**Comment by mjmasn** [comment]
@jlukic what's the status on this? I too am trying to use Semantic UI with Meteor and it's breaking every time I need to repeat a class name. For example ```right labeled right floated``` or the responsive grid example above. I don't think it's reasonable to expect a large number of front end libraries to start supporting repeated classes. Is there any temporary solution or, failing that, anything in the pipeline to resolve these issues?

The HTML5 spec itself says 'Duplicates are ignored' http://www.w3.org/TR/html5/dom.html#classes

**Comment by dalgard** [comment]
My personal workaround simply consists in wrapping the few elements that need duplicate classes in a custom block helper, which only has one purpose, namely replacing the mangled `className` property of the element with the original value provided as a keyword argument.

If this seems a bit blurry, here are a few more notes:

- The template body of the custom block helper that serves to encapsulate this technique strictly doesn't need anything other than the `{{> Template.contentBlock}}` directive, but adding a container element could be useful in some cases.

- In the ´rendered` hook of the block helper we first obtain the correct class string (with duplicates intact), which is bound to the current context – and then we overwrite the `className` property on the view's outermost element with it.

- In order to bind each class string more tightly to the element it applies to, each string is defined directly on its block helper as a keyword argument, automatically adding them to the data context. Consequently, with the finished block helper looking more or less like below, the correct string can always be referenced by writing `this.data.class`.

```handlebars
{{#appApplyClass class='right labeled right floated'}}
  <div>
{{/appApplyClass}}
```

.
Incidentally, the details here could vary endlessly. Instead of using a keyword argument, the class string could be saved in a `data-` attribute. Likewise, if overwriting the value of `className` completely seems harsh, it is trivial to concatenate the old and the new value instead.

**Comment by mjmasn** [comment]
Thanks @dalgard, that all makes sense and has got me thinking. I don't know your exact use case but I think this can be simplified a bit by creating a global helper something like:
```coffeescript
# CoffeeScript
Template.registerHelper 'class', (string) ->
    string
```
```javascript
// Javascript
Template.registerHelper('class', function (string) {
    return string;
});
```
Then in the template:
```html
<button class="{{class 'ui right floated right labeled icon button'}}">My Button<i class="user icon"></i></button>
```

The benefit being if this is fixed at some point, it'll be pretty easy to remove the unnecessary code. Thoughts?

**Comment by mjmasn** [comment]
Hmm, not sure the method above is actually working. I have ended up (with iron router / jquery) doing:

```html
<button data-class="ui right floated right labeled icon button">My Button<i class="user icon"></i></button>
```
```coffeescript
Router.onAfterAction ->
    setTimeout ->
        $('[data-class]').each ->
            propClasses = $(this).prop('class')
            dataClasses = $(this).data('class')

            if propClasses.indexOf(dataClasses) is -1
                classes = $.trim(propClasses + ' ' + dataClasses)
                $(this).prop('class', classes)
    , 0
```

Bit of a hack but still preferable to wrapping things in additional template helpers. Luckily there's not too many places where this will be necessary in my own code, and again it's simple to remove (delete the ```onAfterAction``` function and remove ```data-``` from ```data-class```).

**Comment by dalgard** [comment]
As you've discovered, using a helper is not enough, Spacebars is pretty crafty that way – or robust, rather.

In larger projects, I prefer not to add code that runs globally. It's better to solve this kind of problem where it exists.

**Comment by myrtleTree33** [comment]
@mjmasn +1 for solution

**Comment by Type1J** [comment]
Any progress here?
