### ISSUE TITLE
Loading button should be disabled

### ISSUE THREAD

**Issue by mderazon** [Semantic-Org/Semantic-UI#1744]
I think that a `loading` button should also be disabled (without additional styling). I find it a much more common use case than a loading button that can be interacted with.
Moreover, achieving both is not possible by simply setting `disabled loading` since `disabled` changes the color of the button. So if I have a colored loading button, setting `disabled` makes it grey.

If making this breaking change is impossible, then perhaps introduce a new attribute `muted` (`disabled` and `active` were taken :) ) that when added will achieve the same...

What do you think ?

**Comment by ph7vc** [comment]
+1

**Comment by jlukic** [comment]
When you say disabled do you mean specifically [`point-events: none;`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/button.less#L211)?

**Comment by mderazon** [comment]
Yes, precisely.

**Comment by ph7vc** [comment]
@jlukic: I think he means when it has class `loading`, the button should not have hover or active states as to not give the user the impression that they can still interact with the button.

**Comment by mderazon** [comment]
Yes, like @ph7vc said but perhapes also not fire any mouse / click events

**Comment by jlukic** [comment]
I understand. I'll take a look at loading buttons again. 

Perhaps there's some middle ground for loading thats an opacity a notch above disabled. At the very least it should be a variable.

**Comment by jlukic** [comment]
Loading will no longer receive events in default theme. 

Added variables for loading opacity and pointer-events.

Available in `next`

**Comment by mderazon** [comment]
Awesome, thanks :+1:
