### ISSUE TITLE
How to put input and buttons in alignment (same line)

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1746]
Apologizes if this seems like a basic question. No finding a good example to copy. Is there a way to place an input and button(s) in the same field?  In this example the buttons wrap to the next line.  Is there a class I'm not finding? I'm aware of the action class. But this isn't what I need. 

                    <div class="required field">
                        <label>Resource</label>
                        <div class="ui input">
                            <input type="text">
                            <div class="ui button">
                                Btn1
                            </div>
                            <div class="ui button">
                                Btn2
                            </div>
                        </div>
                    </div>
![screen shot 2015-02-02 at 8 12 58 pm](https://cloud.githubusercontent.com/assets/392233/6013264/edea0862-ab17-11e4-91b9-68c0c4968655.png)

When I put this in a grid things don't line up. As the buttons top align with the label. 
![screen shot 2015-02-02 at 8 12 05 pm](https://cloud.githubusercontent.com/assets/392233/6013256/d7022ddc-ab17-11e4-9e2e-7dba08bcbf25.png)

**Comment by ph7vc** [comment]
You could do something like this: http://jsfiddle.net/6Lpj5udz/1/

First is sort of a hack but it works.

The second is just using the fact that you can attach a button to an input, only it will skew the width of the button the larger the form gets, but both are acceptable ways to accomplish what you need.

Good luck!

**Comment by geemang2000** [comment]
Thanks @ph7vc !   This is something that I'd think is  very common. 

This sort of works too. Wonder it this is a supposed to align properly?

                <div class="inline fields">
                    <div class="field">
                        <label>Last name</label>
                        <input type="text" placeholder="Full Name">
                    </div>
                    <div class="field">
                        <div class="ui blue button">Test</div>
                    </div>
                </div>

![screen shot 2015-02-03 at 8 13 54 am](https://cloud.githubusercontent.com/assets/392233/6021685/29f0351a-ab7d-11e4-84af-cdf413bb82a9.png)

**Comment by ph7vc** [comment]
That looks like a similar issue to #1536. For some reason I remember seeing this issue already reported somewhere else, but I can't seem to find it 

In any case, it does the same in my browsers. It hardly noticeable imo and probably not a high priority fix. It looks like it is off by a single pixel

Fiddle: http://jsfiddle.net/6Lpj5udz/3/

Browser: Chromium 39 & Firefox 35 on Ubuntu 14.04

**Comment by Fanna1119** [comment]
Also ran into this problem, not sure if it is still useful to someone :)

`<div class="ui container">
      <div class="ui centered grid">
          <div class="twelve wide column">
              <div class="ui fluid icon input subscribe">
                  <input type="text" placeholder="Full Name">
                  <div class="ui animated fade inverted button name" tabindex="0">
                      <div class="visible content">Test Button</div>
                      <div class="hidden content">
                          <i class="student icon"></i>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>`

css

`.ui.animated.fade.inverted.button.name {
    margin-left: 1em;
}`

**Comment by Fanna1119** [comment]
Not sure if someone will see this but I found another solution by mistake :+1: 

http://jsfiddle.net/fanna1119/hht1z6m6/1/

**Comment by jsotteccanic** [comment]
Puedes hacer algo como esto: 
```
<div class="fields">
                <div class="field">
                    <label> &lt; 65 </label>
                    <input type="number" name="edad_1" id="edad_1" min="0">
                </div>
                <div class="field">
                    <label> 66 a 84 </label>
                    <input type="number" name="edad_2" id="edad_2" min="0">
                </div>
            </div>
            <div class="field">
                <label for="">&nbsp;</label>
                <button class="ui button blue fluid">Cotizar</button>
            </div>
```

**Comment by abulka** [comment]
The use of a non breaking space as a label
```html
<label for="">&nbsp;</label>
```
 is a neat, simple solution to the OP.

**Comment by DurandSacha** [comment]
Simple solution for align input and label in CSS :

`label
{
	width: 40%;
  display: block;
	float: left;
}`
