### ISSUE TITLE
Drupal integration released

### ISSUE THREAD

**Issue by culfin** [Semantic-Org/Semantic-UI#1748]
Hi Jack,

I just wanted to inform you that we released the Drupal 7 integration of your framework. It's almost finished and we tried to directly inject the Semantic UI classes into the markup by using preprocess functions, hooks and template overrides.

It would be nice if you could add it to the readme or somewhere where it fits:
https://www.drupal.org/project/semanticui

Best, Andreas

**Comment by jlukic** [comment]
Thanks culfin I've updated our link in the integration wiki, and made a specific callout to drupal in our readme.
https://github.com/Semantic-Org/Semantic-UI/wiki/Integration
