### ISSUE TITLE
Dropdown with icon only for selection

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1749]
I've created the following plnker:  http://plnkr.co/edit/Hnue2YspqW0buctt8SE3?p=preview

My goal is to have the selected value show only the icon selected from the dropdown.

**Comment by ph7vc** [comment]
I dont think this can be done with the default stuff in Semantic. You need to override the change function and strip off the icon with Jquery, and get the text display to show it. 

http://plnkr.co/edit/4SwxqhrUZo2L6GVzAC2J?p=preview

```
 $('.ui.dropdown').dropdown({
          onChange: function(value, text, $choice){
            var icon = value.substring( 0, value.indexOf('</i>') + 4 );
            var selection = $($(this).children('.text')[0])
            selection.empty();
            selection.append(icon);
          }
        
      });
```

**Comment by geemang2000** [comment]
Thanks @ph7vc !
