### ISSUE TITLE
more examples would be helpful

### ISSUE THREAD

**Issue by programming-kid** [Semantic-Org/Semantic-UI#175]
I am new to semantics and I am not really able to figure out exactly how it works .bootstrap has a format like 

``` css
<body>
  <div class='container'>
    <div class="row">
      <div class="col-md-6">
            Blah blah
        </div>
        <div class="col-md-6">
            Blah blah
            </div>
     </div>
  </div>
</body>
```

In semantic I am not able to find equivalent to .container I guess it is .ui.page but it doesn't exactly behave as one 

What I am suggesting is please create some example pages so that newcomers like me who are used to bootstrap can quickly get started with semantics .Best part would be to convert these [bootstrap examples](http://getbootstrap.com/getting-started/#examples) to their semantic equivalents to help new developers to get started quickly.

**Comment by codynguyen** [comment]
I'm new to semantic-ui & I'm experiencing the negative `margin-top` too when trying to use `.ui.page.grid` to mimic bootstrap's `.container` as suggested here: http://stackoverflow.com/a/28676816

My html is as followed:

```jade
  body.menu.pushable
    .ui.fixed.inverted.menu
      .ui.page.grid
        .left.menu
          a.item(href='#') Brand
          a.item(href='/dashboard') Dashboard

        .right.menu
          a.borderless.item(href='/logout') Logout

    .pusher
      .full.height
        .main.container
          block content
      .ui.footer.vertical.segment
```
Can anyone explain why it is happening & the semantic-ui way to resolve this? Also is there any update on the progress of adding `.container` support?

**Comment by jlukic** [comment]
Container is in `2.0` which will be available june 1st. You are probably experiencing [collapsing margins](https://developer.mozilla.org/en-US/docs/Web/CSS/margin_collapsing).
