### ISSUE TITLE
Modal module's destroy() method removes all event handlers from window object.

### ISSUE THREAD

**Issue by cueedee** [Semantic-Org/Semantic-UI#1750]
Please see this [jsfiddle](http://jsfiddle.net/1xybzyqc/2/) for a demo.
 
The [`modal` module](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/modal.js)'s [`destroy`](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/modal.js#L129) method wants to remove only *element*-namespaced event handlers from the `window` object, but instead removes all because [`elementNamespace`](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/modal.js#L135) is undefined when `destroy` is [called internally](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/modal.js#L790)

```javascript
destroy: function() {
    module.verbose('Destroying previous modal');
    $module
        .removeData(moduleNamespace)
        .off(eventNamespace)
    ;
    $window.off(elementNamespace);
    $close.off(eventNamespace);
    $context.dimmer('destroy');
},
```

The [`dropdown` module](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/dropdown.js) has [the same issue](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/dropdown.js#L1620).

**Comment by jlukic** [comment]
Thanks, I'll take a look at this.

**Comment by jlukic** [comment]
Thanks for the catch, and very useful test case. 

Fixed in `next`

JSfiddle of fixed
http://jsfiddle.net/qvv8sfj7/

**Comment by cueedee** [comment]
Thank *you* for the quick fix. The issue was breaking our backbone router by removing its `hashchange` event handler.
