### ISSUE TITLE
Dropdown should allow arbitrary data input and possibly a alternate operation mode

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1753]
I feel dropdown should have another mode where users can add other choices that are not part of the select list and it will be recorded when they interact with the dropdown input.

By definition this would be a combobox which supports arbitrary text input, type ahead and selection from the list. 

NOTE: the current dropdown does allow text input, but does not behave great. Once text is entered the dropdown caret does not function. Also it does not expose the arbitrary text easily to the form. 

The dropdown should also select set the search input to the currently selected dropdown menu choice, when the user finishes interacting with the dropdown and when rendered on page load. 

#1752  is related

**Comment by jlukic** [comment]
I think adding the ability to add other values will probably have to wait for a while. In the meanwhile I've fixed the dropdown icon to close a `search selection` in `next`.
