### ISSUE TITLE
[Transition] does not respect `namespace` setting.

### ISSUE THREAD

**Issue by cueedee** [Semantic-Org/Semantic-UI#1754]
Please see this excerpt from the [`transition.js`](https://github.com/Semantic-Org/Semantic-UI/blob/1.8.1/src/definitions/modules/transition.js#L65) module:

```javascript
module = {

    initialize: function () {

        // get full settings
        moduleNamespace = 'module-' + namespace;
        settings = module.get.settings.apply( element, moduleArguments );
        className = settings.className;
        metadata = settings.metadata;

        animationStart = module.get.animationStartEvent();
        animationEnd = module.get.animationEndEvent();
        animationName = module.get.animationName();
        error = settings.error;
        namespace = settings.namespace;
...
```

As you can see `namespace` is used before it is initialized:

```javascript
        moduleNamespace = 'module-' + namespace;
...
        namespace = settings.namespace;
```

The result of this is `moduleNamespace` always receiving the value `'module-undefined'`, regardless of `namespace` default or custom setting. 

I found this while debugging the issue that led to #1750, encountering `'moduleUndefined'` and `'module-undefined'` keys on a `$('.ui.modal').data()` object.

**Comment by jlukic** [comment]
Fixed in `next`. 

Thanks for the vigilance. Definitely need more watchful eyes like yours poking through code.

**Comment by cueedee** [comment]
Yw
