### ISSUE TITLE
two problems of divider

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1757]
http://jsfiddle.net/cve2f118/1/

1) divider's font color is black inside an inverted segment, should it not define ?
2) drag the viewport to mobile and drag back to computer, column has problems like that:

![2015-02-05_155951](https://cloud.githubusercontent.com/assets/3031252/6056742/5fa95144-ad50-11e4-963a-935f1b3c005d.gif)

**Comment by jlukic** [comment]
For inverted divider, you still have to specify `ui inverted divider` even if its inside an `inverted segment`.

The other issue is documented in #1576, I'm unsure of a fix it seems to be browser specific bug.

**Comment by faller** [comment]
thank's so much!
