### ISSUE TITLE
Elements getting hidden if the style is applied on span which has the input type as its child

### ISSUE THREAD

**Issue by vikramjb** [Semantic-Org/Semantic-UI#1759]
I am using Semantic UI as my stylesheet for a ASP.net web application. For some reason the elements are getting hidden if they are within a span element. For instance

        <span id="testcheckbox" class="ui checkbox">
            <input type="checkbox" id="checkboxTest" />
        </span>

The above html code is for a simple check box, however the element will not be shown unless the css tag is moved to the element itself. The reason why I am styling it this way is because, ASP.NET be default generates a server control within a span tag and applies the style to the span element. 

I am wading through the sematic css but have been unable to find any presence of span tags. I'd appreciate any help on this.

**Comment by jlukic** [comment]
Hi, this issue isnt with using a `span`, you are missing the `<label>` which is used for box stylings.

http://jsfiddle.net/fcvvt6d9/

**Comment by ph7vc** [comment]
The way that Semantic does checkboxes asks that you have a label present. While its not entirely nessessary, almost every case you would want it. 

However, you simply need to call the `checkbox()` module on your target to get it to be interactive. Without a label it wont appear without javascript.

http://jsfiddle.net/jsz8hofd/2/

**Comment by vikramjb** [comment]
Thank you @ph7vc . Putting the label did the trick.
