### ISSUE TITLE
Incorrect handle display:none for cards

### ISSUE THREAD

**Issue by elyzov** [Semantic-Org/Semantic-UI#1760]
When I set number of cards in row, then display:none handled incorrect.

example:
![Example](http://i.imgur.com/2jzGaF2.png)

**Comment by elyzov** [comment]
But without specifying number of columns (e.g. use only class="ui card") it works well.

**Comment by Anachron** [comment]
Why you dont make a picture to see which properties are computed, if the inspector is already open? I dont understand. It would be very useful to know where he inherits the visibility/display from.

**Comment by romuloctba** [comment]
@elyzov  Please provide example code

**Comment by elyzov** [comment]
@romuloctba You may try this right now. Go to http://semantic-ui.com/views/card.html#column-count, inspect html code one of the cards, and append style="display:none;" to card's div tag.

I'm not good at css, but I think it is due to the following style:
```
.ui.four.cards>.card:nth-child(4n+1) {
    clear: left;
}
```

**Comment by jlukic** [comment]
Eylzov. Cards are manually clearing floats every (x) cards to prevent them stacking incorrectly when different heights. 

I'm not convinced this is the best way still to be doing things. I will be looking into a simpler solution, or perhaps one including flexbox for row spacing.

**Comment by elyzov** [comment]
@jlukic, thanks! It's important for me, couse I use cards in my project and now filtering looks not so pretty...

**Comment by Anachron** [comment]
@jlukic @elyzov why not use `.ui.four.cards>.card:not(.hidden):nth-child(4n+1)` and add hidden to hide the card? Shouldn't that work?

Relevant is all stuff with `:first-child` or `:last-child` or `:nth-child` as rule.

**Comment by jlukic** [comment]
I think i will just implement flexbox. This is actually a case where it solves a problem *quite* well. 

[Scroll to "EXAMPLE 1: CARD LAYOUT WITH LIST"](http://chriswrightdesign.com/experiments/using-flexbox-today/)

**Comment by romuloctba** [comment]
This is awesome, flexbox is awesome and has a good fallback also
