### ISSUE TITLE
Units on zero values in compiled CSS (and Less)

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI#1762]
**EDITED**

I'm trying to reduce the file size of compiled CSS further.

When I go to to http://csslint.net/ and only check for "Disallow units for 0 values", I'm getting 2389 warnings which should shave off roughly 4KB of the compiled CSS file size.

So, is there a setting to rid off the unit from e.g. ```0px```, ```0em```, ```0%```?

P.S.
Probably not, because I noticed that you set ```zero-units``` in the [```.lintrc``` file to false](
https://github.com/Semantic-Org/Semantic-UI/blob/e9a4b6673e93ddd2911162bfc18af629585219b7/.csslintrc#L17).

**Comment by jlukic** [comment]
Units are removed automatically during minification.
https://raw.githubusercontent.com/Semantic-Org/Semantic-UI/master/dist/semantic.min.css

**Comment by Lisa-Williams** [comment]
I uploaded the ```dist/semantic.css``` file to ccslint.net for convenience.
But I'm adding some of the separate css files from dist/components/*.css to existing web sites.
I'm minifying and concatenating them through a custom gulp script.

What node_module are you using to remove the units during minification?
