### ISSUE TITLE
[Card] Images inside cards' .content

### ISSUE THREAD

**Issue by romuloctba** [Semantic-Org/Semantic-UI#1763]
A `.ui.image` inside a card, but outside it's `.content` is beautifully 100% width.

But if you put the `.image` it inside `.content` it goes 2em width. ( `card.less arround line 205` ) 

One should be able to use images inside `.card .content` even that it needs to add the .image class to it, so it displays nicely

Currently the 100% width is overwritten by a 2em width ( card.less arround line 205 )

**Comment by romuloctba** [comment]
So i did this. Sorry, i tried PR instead of just talking here :p 

Also, the colored cards improovement i'll try to make in this branch.

Please check and comment: 0060fa800f16cfc99f8223e592c3e456a0a2f5be

**Comment by romuloctba** [comment]
couldn't resist. PR'd it.

**Comment by jlukic** [comment]
Closed discussion in PR
