### ISSUE TITLE
Icons 'external link' and 'external link square' imply 'link' class

### ISSUE THREAD

**Issue by czechnology** [Semantic-Org/Semantic-UI#1766]
I've noticed the following - the icons `external link` and `external link square` cause the icon to be "linkable" (`link` class) which might not always be the desire of the designer. Or is this on purpose?

Thanks

**Comment by jlukic** [comment]
My original thought was that anything with an external link icon would always be clickable. Perhaps there are cases where this is not true. 

I'll rename to ``external icon` and `external square` which is backwards compatible for those using the old name, but still allow it not to link.
