### ISSUE TITLE
Documentation needs more code for the examples

### ISSUE THREAD

**Issue by Jakobud** [Semantic-Org/Semantic-UI#1767]
I've just recently discovered Semantic UI. I am impressed so far. This is kind of a suggestion but the documentation really needs more code with it. Each example you show in the doc's is great, but along with each example, you should have the accompanying code that you use to make that example. Otherwise, users (especially new ones) are stuck trying to figure out how to recreate what you did.

Keep up the good work on this project. It's very nice so far.

**Comment by Anachron** [comment]
Well you can toggle code visible and invisible. What else do you want?

**Comment by Jakobud** [comment]
Oh I totally didn't see the little code `< >` links. That is exactly what I was looking for. They were just kind of hidden since they were faded out. Thank you!
