### ISSUE TITLE
Chinese mirror site info box appears on every page of semantic-ui.com when choosing Chinese as the language.

### ISSUE THREAD

**Issue by betaver** [Semantic-Org/Semantic-UI#1769]
After choosing Chinese as the site language of semantic-ui.com, every time I browse to a page of the site, the info box appears,

> Would you like to visit the mirror site?

> Semantic is available at semantic-ui.cn a mirror site hosted inside China. This should make browsing much faster for those visiting from mainland China.

> No, Thank you / Yes, take me there

If I click No, this box appears once visiting another page.

**Comment by jlukic** [comment]
I'll fix this today. Thanks

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-Docs/commit/af585b4e58002876cdd5fc93ca3adb7d4205dc3f , deploying now

**Comment by jlukic** [comment]
Deployed
