### ISSUE TITLE
Sidebar Bug on IE 9-11

### ISSUE THREAD

**Issue by mbeckenbach** [Semantic-Org/Semantic-UI#1771]
When using a custom context, sidebar does not show.
Look like it's missing a kind of a margin or offset.

Example: 
http://semantic-ui.com/modules/sidebar.html#/examples -> Using a custom context

**Comment by jlukic** [comment]
Thanks that was a disaster in IE. IE doesnt create new contexts with `transform` for `position: fixed`, so everything has to be swapped with `absolute` when used inside a context.
