### ISSUE TITLE
Burma Flag Is Old

### ISSUE THREAD

**Issue by magixsource** [Semantic-Org/Semantic-UI#1773]
Hey,I find falg icon on http://semantic-ui.com/elements/flag.html is incorrect.
for example,Myanmar(Burma),this flag is http://ts1.mm.bing.net/th?&id=HN.608001416334475740&w=300&h=300&c=0&pid=1.9&rs=0&p=0.

**Comment by QWp6t** [comment]
Also its ISO 3166-1 Code is MM

Also SUI's table header on `flag.html` is wrong. Those are ISO 3166-1 alpha-2 codes, not ISO 3166-2 codes. The former are two-letter (*cf.* "alpha-2") country codes while the latter are subdivision codes (e.g. states and provinces) within countries.

**Comment by jlukic** [comment]
Hi, the flag for Burma is just out of date, it is the previous Burmese flag. The source must have been previous to 2010.

http://en.wikipedia.org/wiki/Flag_of_Burma#mediaviewer/File:Flag_of_Myanmar_(1974-2010).svg

**Comment by jlukic** [comment]
Added in `next` release, you can see changes here https://github.com/Semantic-Org/Semantic-UI/commit/5eb9aff51f7b10ee0bc3bc88a42caa75422aa0a6
