### ISSUE TITLE
change asset path in build

### ISSUE THREAD

**Issue by mbeckenbach** [Semantic-Org/Semantic-UI#1774]
When building I would like to use a custom absolute paths for fonts and images.

The build process uses relatives paths, but on my scenario the relative path is not the same as it is when the app is deployed. 

At the moment I use a custom grunt task to replace the task, but having a build variable in the semantic gulp build script would be cool to avoid this.

**Comment by jlukic** [comment]
Asset paths are in `site.variables`

Gulp tools automatically change the paths to match `dist/` paths, you can also add your own changes when compiling less in your grunt pipeline.

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L200

**Comment by kbajpai** [comment]
I wanted the paths for the *dist* to be as follows without breaking the paths. How do I achieve this?

dist
├── fonts
├── icons
├── images
├── javascripts
└── stylesheets
