### ISSUE TITLE
simplify theme build

### ISSUE THREAD

**Issue by mbeckenbach** [Semantic-Org/Semantic-UI#1775]
Would it be possible to have a separate build process to quickly create only theme CSS?

The idea is that I have two resulting CSS files. One with all the classes needed for the framework to work. Another one with just colors, fonts, etc.

The theme build process would have single variables file to quickly adjust everything in a single place and start the build. 

The scenario where I would like this is a multi tenant app, where all tenants can have their own ci reflected in colors. So I would need a way to create color themes as easy as possible without really knowing the framework. 

This could also be used to create something similar to the jQuery UI theme roller.

**Comment by jlukic** [comment]
The place to adjust global variables is `src/site/globals/site.variables`. 

You can see our [customization guide](http://learnsemantic.com/developing/customizing.html) on learnsemantic

And browse values here:
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables

**Comment by mbeckenbach** [comment]
Ok. Thank you! I will have a Look at it. 

Are you planning something like the theme roller tool? I'm asking because what I'm looking for is a way to let non-developers customize color schemes.

**Comment by jlukic** [comment]
There's nothing planned. Perhaps a more in-depth offering if I ever get the resources. But for now you'll have to adjust inside code.

**Comment by mbeckenbach** [comment]
Let me see if i can get some ressources in the next weeks and try to create some prototype. 

I'm not a nodejs dev yet. But as far as i understand it gulp is a node plugin, correct?

So it should be possible to create a small nodejs web app which shows a visual editor for that variables file. This node app should be able to run the gulp build task and deliver a compiles CSS file as download. 

Do you think this could work?

**Comment by jlukic** [comment]
That idea could definitely work. I never though of having design tools run offline with node. My original plan was to have a hosted version that would export files.

**Comment by mbeckenbach** [comment]
Sorry it has been a while since i had time to think about it. 

As you said: You need to have a hosted version. What i'm thinking about is a way to host this theme builder on my own web. 

What i found out so far is, that when you create a nodejs web application using soething like express you can run things like grunt as long as it's not installed as a dev dependency. You can make your nodejs website depend on any nodejs module you like and then excecute.

Let me dig into that some more. If i'm right i should be able to start your build process as it is from a website. Until now i'm not sure how i can set the output folder at runtime which would be needed to have run it with multiple users concurrent.
