### ISSUE TITLE
background problem in "primary vertical segment"

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1776]
http://jsfiddle.net/jvntaadp/1/

Should vertical segment remove "background-color: transparent;" 
or primary segment add "background-color: white" ?

:)

**Comment by Anachron** [comment]
As I believe, neither. Segment is meant to act as a container, but the styling (background & border) should be up to the developer. I don't think there is a good way to put a background color for all situations.

**Comment by faller** [comment]
I think Grid is a container, and Segment is a styling container

**Comment by jlukic** [comment]
Yes, grid provides structure, while segment provides a rounded box with padding.

**Comment by faller** [comment]
@jlukic there's something wrong with the background-color

http://jsfiddle.net/jvntaadp/3/

**Comment by jlukic** [comment]
`ui segment` do not currently have a `primary` variation. Only `secondary` `tertiary`
