### ISSUE TITLE
Breadcrumbs misalign on phone

### ISSUE THREAD

**Issue by Anachron** [Semantic-Org/Semantic-UI#1779]
Take a look how the breadcrumbs misalign on phone, it looks like its not properly aligned, at least in my eyes. Also the icons (Arrows) are too low.

![image](https://cloud.githubusercontent.com/assets/589800/6132012/34dd1f28-b150-11e4-9429-bd3c0a0e180e.jpg)

**Comment by jlukic** [comment]
Breadcrumb icon now uses exact pixel em value which should help vertical align.
