### ISSUE TITLE
[tab]  Dynamic content tab was not worked after I update from 1.7.3 to 1.8

### ISSUE THREAD

**Issue by xiemeilong** [Semantic-Org/Semantic-UI#1783]
http://jsfiddle.net/xiemeilong/apuv0g02/2/    1.8.1 not work

http://jsfiddle.net/xiemeilong/apuv0g02/3/   1.7.3 work

@jlukic

**Comment by jlukic** [comment]
Can you provide a test-case that shows the bug?

**Comment by xiemeilong** [comment]
Why is this issue closed?
