### ISSUE TITLE
incorrect right-menu height-position

### ISSUE THREAD

**Issue by JohnnyCrazy** [Semantic-Org/Semantic-UI#1788]
When using an input-box inside a menu, the right-menu will be not in the correct height-position

[JSFiddle with the search](http://jsfiddle.net/trxmzaj3/):
![alt](http://i.imgur.com/1Aghu97.png)

[JSFiddle without the search](http://jsfiddle.net/9xaetmck/):
![alt](http://i.imgur.com/NtzWKE9.png)

Did I miss something or is this a bug?

**Comment by ph7vc** [comment]
I've noticed this myself, and I thought I reported it but I guess not.

**Comment by jlukic** [comment]
Horizontal menu items don't resize to be equal height. It's as simple as that. The only way to make it work with current-gen tech is `table-cell` which makes floats impossible. 

Using `flexbox` may be viable, but it's very difficult to port the entire definition to flexbox. It may also alienate developers that need to support older browsers.

**Comment by CakalSG** [comment]
Change <div class="right menu"> to <div class="ui right item">
your right menu middle aligned right?
sorry my bad english :(

**Comment by JohnnyCrazy** [comment]
Well, kind of:
![](http://i.imgur.com/EtY2bx3.png)

Guess we have to live with it :smiley:

**Comment by jlukic** [comment]
You can manually set the height on the items to the size of the largest one. 

`.menu .item { height: 60px; }`
