### ISSUE TITLE
Forms in android browser

### ISSUE THREAD

**Issue by sarbona** [Semantic-Org/Semantic-UI#1790]
I am developing a webapp with semantic, and form scrolling in Android browser (Android 4.1.x - 4.3.x) is moving elements at different speeds, icons move outside buttons and inputs, and input and buttons overlap other elements, but when scrolling ends, the elements end in the right place.
I have tried to simplify the code to the most simple thing, and I have found that the problem is caused when the form is inside a div with overflow-y "scroll" or "auto".

&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
	&lt;meta charset="utf-8" /&gt;
	&lt;meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" /&gt;
	&lt;script src="jquery/jquery-2.1.1.min.js" type="text/javascript"&gt;&lt;/script&gt;
	&lt;link href="semantic18/semantic.min.css" rel="stylesheet"&gt;
	&lt;script src="semantic18/semantic.min.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;div style="overflow-y:auto; height:400px; width:100%; overflow-x:hidden; text-align:center; padding:2rem;"&gt;
		&lt;p&gt;Lorem ipsum dolor ....&lt;/p&gt;
		&lt;hr /&gt;
		&lt;div class="ui form"&gt;
			&lt;div&gt;User authentication&lt;/div&gt;
			&lt;div class="field"&gt;
				&lt;div class=" ui icon input"&gt;
					&lt;input id="login" type="text" placeholder="User name" value="" /&gt;
					&lt;i class="lock icon"&gt;&lt;/i&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="field"&gt;
				&lt;div class=" ui icon input"&gt;
					&lt;input id="password" type="password" placeholder="Password" value="" /&gt;
					&lt;i class="lock icon"&gt;&lt;/i&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="ui icon button labeled submit"&gt;&lt;i class="sign in icon"&gt;&lt;/i&gt;Login&lt;/div&gt;
			&lt;hr /&gt;
			&lt;div class="ui icon button labeled" onclick=""&gt;
				&lt;i class=" browser icon"&gt;&lt;/i&gt;
				Register
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;p&gt;Lorem ipsum dolor...&lt;/p&gt;
	&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

I can not change this layout because webapp structure and I need the form to go inside a scrolleable div.

If I change the semantic 1.8.1 for an older one ¿0.19.3? (not sure about this versión but in JavaScript there is this versión number) then the form scrolls correctly.

Any idea about how to fix this?

Thank you for your time and efforts.

**Comment by jlukic** [comment]
http://jsfiddle.net/24f8a5xo/

**Comment by jlukic** [comment]
I'm unable to reproduce your described behavior when using Chrome's phone emulator with Android OS in the above  jsfiddle.

If you visit the above url in your browser is the issue for you occurring there?

**Comment by ph7vc** [comment]
I opened it in my phone's (Android) browser, can I cannot see any icons at all.

Doesn't look like anything is wrong with the layout however.

I can upload a screenshot if needed @jlukic

**Comment by sarbona** [comment]
Try this:

http://www.haiku-media.com/Resources/Tests/Semantic/test.html

I can reproduce the problem with a Samsung Galaxy S2 and even with the Android Emulator using the Nexus 4 device profile and target Android 4.3.1 (Level 18) using the standard android browser (not Chrome). My webapp will be packaged with Apache cordova and it uses webviews with the standard Android browser not chrome.

I have duplicated the previous file and changed the semantic for an older one and it doesn't reproduce the problem. You can try here:

http://www.haiku-media.com/Resources/Tests/Semantic/test2.html

Can you reproduce the problem now?

Thank you for your help.

**Comment by Anachron** [comment]
It also happens on iOS 7.11 Safari if you scroll too fast or too much. I attached an example.
![image](https://cloud.githubusercontent.com/assets/589800/6172978/ac6c20da-b2e4-11e4-94af-5ab147d02155.jpg)

**Comment by jlukic** [comment]
If anyone has any ideas. I'd love to help. Its simple `position: absolute;` I'm unsure of why its causing so many issues.

**Comment by arkmuay** [comment]
Arf...
