### ISSUE TITLE
[Vertical Menu] Collapsing Sections?

### ISSUE THREAD

**Issue by FoxxMD** [Semantic-Org/Semantic-UI#1793]
First let me say I am LOVING semantic ui, it's a nice change from bootstrap for me and the amount of variations and customization is absolutely refreshing!

Is it possible to make [sections in the vertical menu](http://semantic-ui.com/collections/menu.html#vertical-menu-w-sub-menus) collapse? 

I looked into the transitions module but it doesn't seem to be the right use case for that and google isn't turning up with any way to do this. I have a vertical menu with many sub items in each section and I'd like to be able to only have the section that is active expanded with the rest collapsed. I could use dropdown items but it makes more sense for the user to be able to see which sub section they are in without having to open the dropdown...Am I missing something obvious?

Thanks!

**Comment by ph7vc** [comment]
Try: http://semantic-ui.com/modules/accordion.html

**Comment by FoxxMD** [comment]
It's even got an [example of a menu](http://semantic-ui.com/modules/accordion.html#menu) :) thanks!
