### ISSUE TITLE
Dropdown not validating on blur or change events

### ISSUE THREAD

**Issue by KlustoR** [Semantic-Org/Semantic-UI#1794]
I dont know if this is for a particular reason, but i cant seem to get a dropdown box to validate on blur or change events. It does validate correctly upon form submit.
All semantic-ui demo code for form validation also has this, so no demo code needed i suppose.

**Comment by KlustoR** [comment]
Any update on the issue ? 
Here is a jsfiddle that duplicates the error : http://jsfiddle.net/8wm6uoth/18/
All elements validate trough blur, only dropdown doesn't, still validates on submit tho.

**Comment by jlukic** [comment]
I'll try to sneak this in `1.9`

**Comment by KlustoR** [comment]
awesome, thanks :+1:

**Comment by KlustoR** [comment]
everything seems fine now, thanks for the fix :+1:

**Comment by utsavig** [comment]
I am still having this issue with Semantic-ui  2.1.5. only dropdown doesn't validate onBlur.  
I am using semantic ui with React framework.  
Demo site seems to have same issue too.
http://semantic-ui.com/behaviors/form.html#/examples

**Comment by oliviertr** [comment]
Echoing @utsavig, dropdown doesn't validate on blur.

**Comment by kungfuyou** [comment]
I'm using semantic-ui-dropdown npm package. To fix @utsavig problem, I added :

` $input.trigger('blur');`

to the blur method on line 927

```
blur: function(event) {
            $input.trigger('blur');
            pageLostFocus = (document.activeElement === this);
            if(!activated && !pageLostFocus) {
              module.remove.activeLabel();
              module.hide();
            }
          }
```

**Comment by mckinley** [comment]
Still seeing the 'blur' problem in `2.3.1` and on the examples page.

Im using this for now:
```
  $('.ui.dropdown').on('blur', function () {
    setTimeout(function ($e) { $e.find('input,select').trigger('blur') }, 1, $(this))
  })
```

The `setTimeout` is there to avoid a flash of the error prompt when selecting a value. Hope someone else finds it useful.
