### ISSUE TITLE
Vertical divider does not work with explicit column width

### ISSUE THREAD

**Issue by DHNCarlos** [Semantic-Org/Semantic-UI#1795]
https://jsfiddle.net/1tqqj43x/1/

It seems that the vertical divider ignores any explicit width set to columns and appears in the dead center of a row. This is even if the columns are direct descendants of a grid.

Not sure if bug or feature. Is it supposed to only work on evenly divided columns instead of explicitly set ones?

**Comment by jlukic** [comment]
See the note in divider about use with grids
http://semantic-ui.com/elements/divider.html#divider

You can just use a `ui divided grid`, `vertical divider` is expected to behave that way.
https://jsfiddle.net/hdrt7wpn/
