### ISSUE TITLE
please use gitter.im chat room

### ISSUE THREAD

**Issue by Centaur** [Semantic-Org/Semantic-UI#1796]
Or at lease choose a chat service that don't need registration.

**Comment by jlukic** [comment]
What does everyone else think?

**Comment by kwando** [comment]
+1 for gitter

**Comment by Einkoro** [comment]
I preferred slack after evaluating gitter and hipchat.

**Comment by jhliberty** [comment]
Slack has been deprecated - please join us in [gitter](https://gitter.im/Semantic-Org/Semantic-UI)!

commit: 0e4e687a
