### ISSUE TITLE
Linkify icon misswords.

### ISSUE THREAD

**Issue by Ethaan** [Semantic-Org/Semantic-UI#1798]
Hi first of all awesome library.

Well after testing this library on my  project i noticed that you guys have on the [icon.html](http://semantic-ui.com/elements/icon.html) page  this `html` markup to use the **link icon**
```javascript
<i class="link link icon"></i>
```
and it dosnt works, it works like this.

```javascript
<i class="linkify link icon"></i>
```

Its just a little typo but it will be nice to fix it to don't confuse newcomers like me =p

**Comment by jlukic** [comment]
Thanks, it's definitely incorrect

**Comment by jlukic** [comment]
Fixed in docs
