### ISSUE TITLE
Sidebar option exclusive closes the sidebar when opening another

### ISSUE THREAD

**Issue by gYonder** [Semantic-Org/Semantic-UI#1800]
When you have two sidebars, and want to switch from one to another without closing the sidebar you can use the option exclusive = true when setting up sidebar. At least on 1.8.1 it is working poorly compared to 0.19.3. What happens is that the sidebar closes, and unexpected things happen when you try to open it again. It should just show the other sidebar.

Steps to reproduce:
1) Add two sidebars
2) Add a button in one of the sidebars to open the other
3) Initialize sidebar using exclusive = true
4) Open the first sidebar and press the button to open the second

Please use these testcases to compare how it was working in 0.19.3
http://jsfiddle.net/r1sjq103/1/

And on the current 1.8.1.
http://jsfiddle.net/ccap8bf3/7/

Tested with Chrome 40.0

**Comment by jlukic** [comment]
Can you please provide a test case (there's a jsfiddle to fork in the readme) which reproduces the bug you are describing.

**Comment by gYonder** [comment]
Alright I've updated the original post with test cases

**Comment by jlukic** [comment]
Thanks, sorry for the delay

**Comment by jlukic** [comment]
Fixed in `next` release

With uncover it will queue:
http://jsfiddle.net/v2runL3s/

With overlay it will occur simultaneously
http://jsfiddle.net/n2jvx76j/
