### ISSUE TITLE
inverted flat tcheme + input, text are invisible

### ISSUE THREAD

**Issue by agborkowski** [Semantic-Org/Semantic-UI#1802]
![screen shot 2015-02-13 at 11 53 35](https://cloud.githubusercontent.com/assets/170557/6186227/16368f86-b377-11e4-9b13-2ce5cab292a3.png)

#source http://semantic-ui.com/collections/form.html

**Comment by Anachron** [comment]
Not on my iPhone, which OS/browser do you use?

**Comment by jlukic** [comment]
Themes other than the `default` theme are not supported. If you are interested in improving or hacking upon them PR will be accepted.

**Comment by agborkowski** [comment]
disappears on focus and text is written in black so is invisible, Chrome Version 40.0.2214.115 (64-bit), ill try fix it.
