### ISSUE TITLE
table hover effect

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1803]
It'd be great if the table supported a subtle row mouseover effect. This is a pretty standard user feedback mechanism to allow better eye tracking.

**Comment by Anachron** [comment]
:+1: totally. Just something subtle like 20% black mask on background.

**Comment by jlukic** [comment]
There used to be something like this, not sure why I changed it. I'll look into this.

**Comment by hrstoyanov** [comment]
jlukich,
I see you dropped this fix from 1.12.0. Can you please put this one back on the schedule releases. I need this one badly. Thanks

**Comment by hrstoyanov** [comment]
Jlukich,
I see some commits reverencing this issue? Is it closed now, and If so - in which version.

**Comment by guo-chen** [comment]
It is also good to make pop ups available when hovering on table cells, which will allow tooltips for the fields.

**Comment by jlukic** [comment]
Added `selectable table` variation @hrstoyanov 
http://beta.semantic-ui.com/collections/table.html#selectable
