### ISSUE TITLE
Close icon is not visible when same height as pageHeight

### ISSUE THREAD

**Issue by huan** [Semantic-Org/Semantic-UI#1804]
see http://jsfiddle.net/m1h98ams/2/ and screenshot
![screen shot 2015-02-13 at 11 58 07 am](https://cloud.githubusercontent.com/assets/1144344/6194306/0cddd920-b378-11e4-81d5-e23a047aea42.png)

There a threshold on which the position of the modal becomes absolute from the top, this threshold needs to account for the close icon.

**Comment by ericz** [comment]
This is due to the modal javascript not counting the icon in the height of the modal. the can.fit() function in modal should include the icon in the modal height.

**Comment by jlukic** [comment]
You're correct. There is a `settings.padding` but it was not being used in the conditional for height.

**Comment by jlukic** [comment]
Fixed in `next`
