### ISSUE TITLE
full width containers with page grid child and no padding ?

### ISSUE THREAD

**Issue by quasiperfect** [Semantic-Org/Semantic-UI#1805]
hi

how can you get full width containers with page grid and no padding ?

i want to create a full page width div with  menu inside

![m1](https://cloud.githubusercontent.com/assets/287513/6199612/bbc56ea0-b457-11e4-9d9a-8937d7d8b611.jpg)

and i tried this 
```
<div class="main-menu">
  <div class="ui page grid">
    <div class="column">
      <div class="ui menu">
        <a class="active item"> <i class="home icon"></i> Home </a> <a class="item"> <i class="mail icon"></i> Messages
      </a>
        <div class="right menu">
          <div class="item">
            <div class="ui transparent icon input">
              <input type="text" placeholder="Search..."> <i class="search link icon"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```
with the css
```
.main-menu {
  position: relative;
  border: 1px solid #e9e9e9;
}

.main-menu .ui.menu {
  border-radius: 0;
  box-shadow: none;
}
```

**Comment by jlukic** [comment]
Do you have padding on `body { }`? I'm not seeing this

http://jsfiddle.net/pxqx13zw/

**Comment by jlukic** [comment]
Here's a much simpler way
http://jsfiddle.net/5xkhj9f9/

**Comment by quasiperfect** [comment]
ty @jlukic 

no padding just wrong html (my page and column divs where outside of menu) i will wait for the finished examples and documentation
