### ISSUE TITLE
hooking up progress bar and ribbon label with card

### ISSUE THREAD

**Issue by citysheep** [Semantic-Org/Semantic-UI#1807]
Hi,

I tried to put a ribbon label onto a card as well as attach a progress bar to the bottom of it. However, it looks like this (the card is a fluid card inside a grid column):

![screen shot 2015-02-15 at 5 59 24 pm](https://cloud.githubusercontent.com/assets/526876/6202869/4c3db722-b53d-11e4-85eb-c244d39616b6.png)

1. If i put the label inside "content", it will be fine.
2. If i put the label inside "image", it is attached to the column which contains the card, instead of the card itself.
3. The progress bar is not attached properly to the card.

Would really appreciate your help. Thanks.

Regards,
Darren

**Comment by citysheep** [comment]
Also, is there a way to put other elements at the same line with the ribbon?

Regards,
Darren

**Comment by jlukic** [comment]
Added in aea9abd6187564265e9c1a64a1930aa93c719b36 and af7c709 

Available in `next`, with new examples in docs.

Cards and segments should not include `ui attached progress` as a child element, not outside. This makes coupling easier.

Ribbon labels now support `ui image` and `ui card`

**Comment by flyboarder** [comment]
This issue seems to still happen in 2.1, unable to put a ribbon label anywhere in card. It always seems to attach to column containing card.

**Comment by ionlights** [comment]
@jlukic concur with @flyboarder, experiencing the issue right now, actually.
is the ribbon only meant to be used with segments?

**Comment by codenoid** [comment]
hi, please can give me the code, i have same bug :(
