### ISSUE TITLE
[Dropdown] Trigger native actions on mobile

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#181]
In addition to what already exists...

``` html
<div class="ui selection dropdown">
    <select name="gender" data-default="Gender">
        <option value="male">Male</option>
        <option value="female">Female</option>
    </select>
</div>
```

``` javascript
$('.ui.selection.dropdown').dropdown();
```

So, what happens if the first child is a select element?
- hide the select element
- insert the dropdown icon
- insert the default text if defined
- insert the items based on the text and value of each option
- watch for change events on the select element
- allow the dev to rebuild it at any time (e.g. if options change)

Benifits:
- great fallback for if a dev doesn't load jQuery and/or semantic.js
- works well with MVC, MVVM, server forms (Django, Rails, ASP, etc.)
- less code
- devs can decide criteria for making it turn into a SUI dropdown
  - if A: `$('.ui.dropdown').dropdown();`
  - if not A: cool, it'll just be a select element

**Comment by NilsJPWerner** [comment]
Could this possibly be opened again? I think that the dropdowns work on mobile, but the default ones would just be easier.

**Comment by David-Tsui** [comment]
Agree above, most of my friends consider the default ones on mobile is easier and better.

**Comment by Staphwar** [comment]
Horrible on bigger inputs. Used an semantic dropdown 18 times. I guess I got to switch back to native in order to make it work.
