### ISSUE TITLE
Missing :hover highlight on dropdown in inverted menu

### ISSUE THREAD

**Issue by slb235** [Semantic-Org/Semantic-UI#1810]
Example (from docs, just added inverted): http://jsfiddle.net/md62o9vc/

Expected result: Hovering over items on open dropdown highlights the item.
Actual result: Hovering over items on open dropdown changes nothing visible.
Browser: Chrome 40.0.2214.111 (64-bit)

**Comment by jlukic** [comment]
Duplicate #1281
