### ISSUE TITLE
Bite-sized contribution

### ISSUE THREAD

**Issue by wordempire** [Semantic-Org/Semantic-UI#1813]
On behalf of [team semantic ui](https://github.com/delftswa2014/Semantic-UI) for a master course at TU-Delft, we are looking into contributing to and analyzing the code base of Semantic-UI. As we would like our contributions to actually be helpful and eventually see them merged, could someone please give us some pointers on some low barrier of entry issues that would could tackle. 

Kudos on the documentation site! How should contributions for the documentation be presented?

**Comment by jlukic** [comment]
Hey I'll delve back into this tonight after I get some coding out of the way. Trying to get out this massive `1.9.0`, 

#1571 is a great place to start for an explanation of how to contribute to docs. Markdown is great. Topic ideas are available in the thread, although some of the 'getting started' will change with build tool updates that are about to be released.

**Comment by evanderschrier** [comment]
I am another member of the semantic ui team :smile:. Thank you for the info!

**Comment by HDking** [comment]
+1!

**Comment by phuckien** [comment]
Here also a member of the semantic ui team.
