### ISSUE TITLE
Middle align with equal height grid row display:flex issue

### ISSUE THREAD

**Issue by taywhited** [Semantic-Org/Semantic-UI#1814]
Fiddle here: http://jsfiddle.net/2nsmvmxd/ (Chrome Version 40.0.2214.111 m)

The only way I could get back to the middle alignment functionality was reverting back to the table displays. Is middle alignment just going to be deprecated for equal height and the display:table workaround should be used instead, or is there a potential fix for this with display:flex?

**Comment by jlukic** [comment]
I can see that alignment is an issue inside `equal height` now due to `align-items: stretch;` being mutually exclusive with with `align-items: center;`. 

If you have a solve i'll look into a PR. Moving to next milestone.

**Comment by jlukic** [comment]
@taywhited Sorry for the delay. 

I've given this issue some more thought, and it seems i was capable of accomplishing this with flexbox.


`top aligned`, `bottom aligned`, and `center aligned` now work with `equal height` correctly. There is an additional alignment variation called `stretched` which can be used as well to stretch internal content (like a ui segment) to be the full column height.
