### ISSUE TITLE
Build failed 'cause of '/tasks/config/admin/github.js'

### ISSUE THREAD

**Issue by esbanarango** [Semantic-Org/Semantic-UI#1817]
Hi.

Thank you for this project.

I'm having an issue running my tests on Travis CI. This is the output Im getting:

>
Build failed.
File: bower_components/semantic-ui/tasks/config/admin/github
'return' outside of function (21:2)

I checked that file and seems like there is an extra `return` [there](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/admin/github.js#L21).

**Comment by jlukic** [comment]
Weird this would kill travisCI test, this file should only be included [for admins](https://github.com/Semantic-Org/Semantic-UI/blob/master/gulpfile.js#L71)

Nevertheless I'll remove the return
