### ISSUE TITLE
Horizontal menu doesn't vertically center items if they exceed a certain height.

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#1818]
Hi Jack, hope you're doing good. Sorry for my recent negligent contributions as I am still settling down. 

I found an issue today while working with SUI - When I tried to include an image that is taller than the menu itself, the contents of the menu don't vertically center themselves. Is this the expected behaviour? I was expecting them to behave as if they've been assigned with `vertical-align: middle;`

Demo:

http://jsfiddle.net/dsgnr/c4q7ma4c/1/

Cheers.

**Comment by jlukic** [comment]
Check #1598

**Comment by dsignr** [comment]
Thanks! :+1:
