### ISSUE TITLE
Semantic update js not work for modal

### ISSUE THREAD

**Issue by KhadeerMojostreet** [Semantic-Org/Semantic-UI#1819]
Hi,

I am added semantic old version semantic.min.js now that updated new version 1.7.3 this is not work on my website especially modals. Modals not closed properly.

**Comment by jlukic** [comment]
Please check this [guide on writing a bug report](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/). Be sure to include a test case that reproduces your error. You can fork the JSFiddle in the readme for a adding your test-case.

**Comment by KhadeerMojostreet** [comment]
Hi @jlukic ,
I am normally using this framework for my site(www.wlingo.com) only semantic.min.js and semantic.min.css version is 0.93, then developing another site i have used semantic.min.css and js also that version is 1.0.1 this is work properly. Now i am download new version of css and js that not work properly, especially for modals but same modals work properly your site, if maintain any custom javascript. Please tell me how to fix this issue.
