### ISSUE TITLE
[Dropdown] - Add ability to clear selected value with (x)

### ISSUE THREAD

**Issue by zelenin** [Semantic-Org/Semantic-UI#1820]
Empty options are removed. I cannot reset filter selecting empty option.
http://jsfiddle.net/zelenin/0kxLxxe5/1/
http://yii2-semantic-ui.zelenin.pw/yii2-widgets/grid-view.html real example, see 'Name' filter.

**Comment by jlukic** [comment]
Empty values were designed around being placeholder values not actual selectable values. 

I would recommend passing a value other than a blank string, for example no value. 
http://jsfiddle.net/zvt8n01a/

It would also make sense to have `clearable` as an option. But this might take a while.

**Comment by zelenin** [comment]
Oh, I understand it but I think that it's very-very-very big hack using empty value for placeholder generation. You must understand it.
There is no case for clear selected value. There is case about not-full support of native selects.
I think its behavior should be changed.

**Comment by jlukic** [comment]
This is the same setup select2 uses. I think its alright

**Comment by zelenin** [comment]
no, select2 not use it.

example:
http://jsfiddle.net/0kxLxxe5/3/

It changes standard behaviour of select. It's cannot alright.
