### ISSUE TITLE
semantic ui modal not closing on login after logout

### ISSUE THREAD

**Issue by alaksandarjesus** [Semantic-Org/Semantic-UI#1821]
I am using a signup modal form of semantic-ui css framework. On first login the modal is disappearing.On logout, if i login again, the modal is not disappearing.

If i refresh the page the modal is works fine for only one time.

I am using angularjs and here is a short 1 min video that explains the problem.

https://www.youtube.com/watch?v=gQpt-oQI7QE&feature=youtu.be

You can download the whole code to test drive from your localhost from Here.

https://github.com/alaksandarjesus/mockuponline

Alternatively you can visit

http://plnkr.co/edit/auurNcTpEk5izurQI6os?p=preview

Thanks in advance.

**Comment by stanzakh** [comment]
I'm having a similar issue since upgrading to 1.9. The difference is that in my case, the modal actually closes but the dimmer stays up. Unfortunately I haven't been able to reproduce the issue, but it happens to me intermittently.

**Comment by jlukic** [comment]
If anyone can create a test case on JSFiddle without other libraries that reproduces the issue i'd love to help.
