### ISSUE TITLE
Labeled input broken when changing site fontsize

### ISSUE THREAD

**Issue by kwando** [Semantic-Org/Semantic-UI#1822]
```
/*******************************
         Site Overrides
*******************************/
@pageFont          : 'Helvetica Neue', Arial,Helvetica, sans-serif;
@headerFont        : 'Helvetica Neue', Arial,Helvetica, sans-serif;
@headerFontWeight  : 400;
@emSize   : 16px;
@fontSize : 16px;
```

From the kitchen sink example:

![skarmavbild 2015-02-18 kl 20 21 56](https://cloud.githubusercontent.com/assets/891566/6254854/ee73bada-b7ab-11e4-862d-2d98e8697598.png)

**Comment by kvetoslavnovak** [comment]
Same bud here at main Semantic UI webpage or Kitchen Sink here with Chrome or IE on Windows and Safari on iPad/iPhone.

**Comment by jlukic** [comment]
I'm not seeing this when changing `html, body { font-size: 16px; }` everything appears scaled correctly to me?

**Comment by kalgon** [comment]
Got the same problem with chrome/firefox under windows 7 and with chrome under android 4.4.x.
![screenshot_2015-02-21-00-38-37](https://cloud.githubusercontent.com/assets/145925/6311409/914b8ed8-b962-11e4-979c-dd3831dc24ea.png)

**Comment by kalgon** [comment]
Strangely, this bug only occurs on the kitchen sink page, not on the [input page](http://semantic-ui.com/elements/input.html).

**Comment by kvetoslavnovak** [comment]
I see this bug everywhere on Semantic-UI.com website with default labeled inputs. Windows with Chrome or IE, iOS with Safari (iPad, iPhone, iPod).

**Comment by jlukic** [comment]
Are you saying this bug occurs only when changing the font size in developer tools? Or that it looks off just when opening the page?

**Comment by vaidhyanathan93** [comment]
It looks different when opening the page itself . In the http://semantic-ui.com/ site itself.
![bug](https://cloud.githubusercontent.com/assets/3818495/6314902/5c94b2a0-ba16-11e4-923c-be324db9a276.PNG)

**Comment by jlukic** [comment]
Ah I see, this is on the kitchen sink only. It appears to be an improper css selector in docs css, should not affect inputs outside of docs. 

Will fix.

**Comment by vaidhyanathan93** [comment]
The css in the #label  inherits the margin-botton property in the docs.css

**Comment by jlukic** [comment]
It's updated now in docs. Have a look

**Comment by jlukic** [comment]
Oh wow just noticed this was still broken on homepage. Fixed

**Comment by kvetoslavnovak** [comment]
Everything everywhere seems OK now. Great!
