### ISSUE TITLE
npm install requires installation steps. How to use it with CI?

### ISSUE THREAD

**Issue by m0t0r** [Semantic-Org/Semantic-UI#1824]
Hi,

There are two scenarios:

1) when I use `bower install semantic-ui` I am getting all packages as expected. No installation process is involved.
2) when I use `npm install semantic-ui` I am getting installation steps questions. So that I have a problem how to use such a way with CI. Is there a way to pre-configure semantic installation so that it would install everything automatically ? Or any other possible solution ?

Thank you very much

**Comment by jlukic** [comment]
See #1816, fix is coming

**Comment by m0t0r** [comment]
OK. Thank you
