### ISSUE TITLE
List 'content' class mixed up with accordion 'content' class

### ISSUE THREAD

**Issue by ardamose123** [Semantic-Org/Semantic-UI#1827]
In the following fiddle, there's a Semantic UI List inside an accordion: http://jsfiddle.net/ardamose123/vjdah0h9/2/

Both elements use a "content" class. However, when placing a list inside an accordion, the accordion's "content" class rules apply, and not the list's.

Result: an unwanted bottom padding in the list items appear.

**Comment by jlukic** [comment]
Thanks, fixed in `next`.
