### ISSUE TITLE
[MENU] Bug with dropdown header in a menu 

### ISSUE THREAD

**Issue by h4mzt3r** [Semantic-Org/Semantic-UI#1828]
Hi, 

I've just found a bug this morning in the new 1.9.1 release: 
when you put a header in a dropdown menu, he is invisible.

**code example :**
`<div class="ui menu">
    <div class="ui dropdown item">
         TEST <i class="dropdown icon"></i>
        <div class="menu">
            <div class="header">HEADER</div>
        </div>
    </div>
</div>`

![2015-02-19_15h23_47](https://cloud.githubusercontent.com/assets/1710716/6265770/564ccf8a-b84b-11e4-9119-5ff63c8354c9.png)

**Comment by h4mzt3r** [comment]
Inherited from `div.menu.transition.visible` :
`.ui.menu:not(.vertical) .menu {
/* font-size: 0; */
}`

If you remove `font-size: 0` from div.menu.transition.visible, header is now visible.

![image](https://cloud.githubusercontent.com/assets/1710716/6265962/250fffee-b84d-11e4-9f89-f2b3841050d2.png)

![image](https://cloud.githubusercontent.com/assets/1710716/6265928/c07bb802-b84c-11e4-8c6f-0da3c21b1b39.png)

**Comment by jlukic** [comment]
You need to use `header item`  if you want to include a `header` as a child of a menu

**Comment by h4mzt3r** [comment]
Hi Jack, 

So, with `header item` it's ok but the style is really... argh... ugly :/

**code example :**
`<div class="ui dropdown item"> 
                TEST <i class="dropdown icon"></i> 
                <div class="menu"> 
                    <div class="item header">HEADER</div> 
                    <div class="divider"></div>
                    <div class="item">foo</div>
                    <div class="item">bar</div>
                </div> 
            </div>`

![image](https://cloud.githubusercontent.com/assets/1710716/6281969/b529a696-b8e5-11e4-8164-747792567e15.png)

Here is an example a render with 1.8.1 version and without the `item` class, look better

![image](https://cloud.githubusercontent.com/assets/1710716/6281994/84c0558a-b8e6-11e4-8951-fd8fdf553992.png)

**Comment by jlukic** [comment]
Sorry I misunderstood the original question. You are correct `header` does not need `item` inside `ui dropdown`. 

This bug will be fixed with `flex-menu` branch

**Comment by jlukic** [comment]
Dropdown styles on `header` inside `ui menu` are fixed in `next`

**Comment by h4mzt3r** [comment]
Hi Jack,

Great news! Thanks for the support and your awesome framework ;)
