### ISSUE TITLE
Very high CPU load on gulp watch and kitchensink.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#1830]
![screenshot_2015-02-19_01-21-52_pm](https://cloud.githubusercontent.com/assets/907195/6266495/b3f829d8-b83a-11e4-904a-00a55f2bfc28.jpg)

![screenshot_2015-02-19_01-37-28_pm](https://cloud.githubusercontent.com/assets/907195/6266649/776f5232-b83c-11e4-979d-29ffd3d73048.jpg)

Gulp immediately causes the CPU on the VM to go to 140% (3 CPU), without gulp watch it's at 1-2%.
Same goes for kitchensink on chromium and safari. (Using compiles semantic-ui files).

I don't have this issue on gulp watch on bootstrap.

Core i5 3,7Ghz, 32GB RAM, GTX 670.

**Comment by jlukic** [comment]
Gulp watch and Chrome behaviors are independent. Watch doesnt trigger anything like an auto-reloader.

It does seem your VM is going a bit nuts however. The watch script is fairly simple, https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/watch.js

It's just watching a single directory for changes to assets, javascript or css. Any more info would be helpful.

**Comment by tmikaeld** [comment]
I know they are, but it would feel odd creating two issues..

It IS simple and there are not many files, i regularly watch a php project with more than 300 files. 
But gulp only consume 10% CPU on one core there...

I'll try and re-install the whole VM and see if that helps.

I guess the kitchensink have too many moving parts right? 
Having so many semantic-ui objects on one page would probably never happen, so let's just ignore the chromium issue.

**Comment by jlukic** [comment]
Testing on my crappy VM getting 3% CPU usage with negligible memory usage.

**Comment by tmikaeld** [comment]
That's kind of what i expected.

Can this have anything to do with it?

````
[12:36:31] Warning: gulp version mismatch:
[12:36:31] Global gulp is 3.8.11
[12:36:31] Local gulp is 3.8.10
[12:36:40] Using gulpfile /var/www/semantic/gulpfile.js
[12:36:40] Starting 'watch'...
````

**Comment by jlukic** [comment]
Shouldnt be an issue

**Comment by tmikaeld** [comment]
I don't get it...

Now i used the Laravel Homestead vagrant box and:
- added the latest virtualbox guestadditions to it
- use the semantic ui included gulp only

But the CPU is still 100% when using gulp watch.

So i though, maybe it's my desktop computer that is the issue!

But after installing the same Laravel homestead setup and installing semantic-ui via npm install semantic-ui and choosing all defaults then running gulp watch.... 

...It still uses 100% CPU.

**Comment by jlukic** [comment]
The gulp task and output are appearing correctly (although you are at high cpu usage)? Or is the task also not working correctly?

**Comment by tmikaeld** [comment]
The gulp task and output are working correctly, but the high CPU usage on both Gulp & Chromium on the kitchensink makes the computer go to a crawl, reloading kitchensink to see changes takes more than 10 seconds on each reload.

**Comment by jlukic** [comment]
Since I'm unable to reproduce your issues, you will have to take debugging into your own hands somewhat. 

I'd recommend opening up `watch.js` and removing portions of code incrementally until your CPU usage returns normal results, then reporting back results.

**Comment by tmikaeld** [comment]
@jlukic I'm already on it. You can close this issue and I'll open a new one if i find what is wrong.

**Comment by jlukic** [comment]
You might also want to check out [this function](https://github.com/jlukic/require-dot-file/blob/master/index.js#L22) in `node_modules/require-dot-file/` which uses recursion to walk up your directory tree. I'm going to add forced exit conditions to it now.

**Comment by tmikaeld** [comment]
@jlukic Ok, then leave this thread open. I guess it would be good if someone else want to fiddle.

**Comment by jlukic** [comment]
Published new version of module with maxDepth to prevent recursion. I don't think that should be the issue though since it wouldn't make it to the watch scripts if `requireDotFiles` was failing

**Comment by tmikaeld** [comment]
I found the issue.

Apple have disabled TRIM for all 3rd party SSD hard drives on OS X Yosemite, so my random read speed was at 0.5MB/s and many times even lower. Patching TRIM and then reconditioning the SSD sent the speeds up to the normal values. Now compiling takes less than 2 seconds even on the Virtualbox.

**Comment by powerbuoy** [comment]
@tmikaeld I'm having the same issue, running gulp inside the vagrant guest sends CPU usage from 1% to 125%. What is that about TRIM? I have no idea what that is :P Any chance you have a link to some sort of guide on how to fix it?

**Comment by tmikaeld** [comment]
@powerbuoy Do you run a real Mac or a Hackintosh?

**Comment by powerbuoy** [comment]
@tmikaeld real

**Comment by tmikaeld** [comment]
@powerbuoy And you're using an external SSD for the Virtualbox?

**Comment by powerbuoy** [comment]
@tmikaeld no the built in one

**Comment by powerbuoy** [comment]
Oh that sounds a bit scary :P Any way to check whether it's enabled already? Running the same gulp task on the host is super fast and doesn't burden the CPU at all. Running it on the guest sends VBoxHeadless to >100%.

**Comment by tmikaeld** [comment]
Yes, open up System Report, then you'll find it here:

![image 2018-11-21 at 9 44 37 am](https://user-images.githubusercontent.com/907195/48829283-3c635e80-ed72-11e8-977f-4df4438e9bc0.png)

**Comment by powerbuoy** [comment]
Hmm i couldn't find that app in Mojave but I switched to NFS and now things are much better. Thanks for helping out!
