### ISSUE TITLE
Package.json dependencies into devDependencies

### ISSUE THREAD

**Issue by embedthis** [Semantic-Org/Semantic-UI#1833]
The current package.json file lists gulp tasks and others as dependencies. However, to use semantic-ui in a browser, these items are not required .... only at build time.

Should they not be in devDependencies?

The package.json is used by NPM and other package manages who use the "dependencies" as the list of what is required to run the product, not develop with the product.

**Comment by jlukic** [comment]
I'm in the process of creating LESS/CSS only repositories. The main repo will always include install scripts which require Gulp to run.

**Comment by jlukic** [comment]
It's live now check out the revamped readme for details

**Comment by embedthis** [comment]
Very cool. That fact that it is automatically synced is key.

Thank you.

**Comment by embedthis** [comment]
Extra request, could this dist have source maps?

**Comment by jlukic** [comment]
I'd take a pull request, but ran into issues when trying to add  `gulp-sourcemaps` before that ended up being a headache so i omitted that feature.
