### ISSUE TITLE
[Build] Cannot get component selection to work

### ISSUE THREAD

**Issue by kwando** [Semantic-Org/Semantic-UI#1836]
I've tried to shrink the output of the build by removing stuff that I do not use. But I cannot get it to work properly.

```/dist/semantic.css``` contains CSS for all components even though I specifically chose only the ```reset``` and ```site``` component.

Is there something wrong with the build setup or have I missed  some piece of the puzzle?

My semantic.json
```json
{
  "base": "",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "rtl": "No",
  "components": [
    "reset",
    "site"
  ],
  "version": "1.9.1"
}
```

**Comment by jlukic** [comment]
Odd, i just tried running with your semantic.json and the build output only shows site/reset. 

Did you generate it with the installer? Whats your folder structure exactly? Are you using `gulp build`?

**Comment by jlukic** [comment]
Closing pending updates
