### ISSUE TITLE
Incorrect position of close button in model dialogs

### ISSUE THREAD

**Issue by maxd** [Semantic-Org/Semantic-UI#1838]
Hi,

Latest version of Semantic UI is show close button for modal dialog in incorrect positions (see attachment). You can reproduce it [here](http://semantic-ui.com/modules/modal.html).

Firefox 35.0.1 (OS X 10.10)

![screen shot 2015-02-20 at 1 25 57 pm](https://cloud.githubusercontent.com/assets/27208/6284744/a45bb66e-b904-11e4-8f4c-c764d9328be1.png)

**Comment by jlukic** [comment]
That is correct position, it jumps inside modal at larger resolution.
