### ISSUE TITLE
Closing a modal causes removing from the DOM

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#1839]
Hi there,

I experienced an issue today while trying to open modals, when closing a modal I'm not able to open up again anymore.
It seems that the modal completely disappear from the DOM...

Here is the example : http://jsfiddle.net/cazsan/25vkhpq6/

SUI issue?

Regards

**Comment by jlukic** [comment]
Modals are moved after activation to a new location so they are no longer sibling elements here
```javascript
$(this).next('.standard.eventResults.modal')
```

You can resolve this by using `detachable: false`
http://jsfiddle.net/5rnnj18k/

**Comment by cazzoo** [comment]
Ok, thanks for the feedback and the solution.
Keep going on, you're doing great job so far
