### ISSUE TITLE
[tab] loading event executes before previously active tabs have been hidden

### ISSUE THREAD

**Issue by Greenype** [Semantic-Org/Semantic-UI#1840]
When switching tabs, previously active tabs stay visible until the content of the selected tab has finished loading.

Tabs: A, B y C.
1. User clicks on tab A
2. Content of tab A is dynamically loaded (ajax)
3. User clicks on tab B
4. Content of tab B starts loading (ajax)
5. Content of tab A stays visible until step 4 is finished

Expected:
5. Tab A should be hidden right after step 3

![tabs](https://cloud.githubusercontent.com/assets/11091676/6287835/ea9dc17a-b914-11e4-8865-b58090de7f9b.jpg)

**Comment by jlukic** [comment]
I'll take a look

**Comment by jlukic** [comment]
Thanks for the nice bug report. This will be fixed in `next`.
