### ISSUE TITLE
[Form Validation] How to change identifier?

### ISSUE THREAD

**Issue by FoxxMD** [Semantic-Org/Semantic-UI#1841]
[On the usage page](http://semantic-ui.com/behaviors/form.html#/usage) for form validation it says 

> A validation object includes a list of form elements, and rules to validate each against. Fields are matched by either the id tag, name tag, or the data-validate metadata matching the identifier provided in the settings object.

It's unclear to me what settings exactly I need to change in order to change the identifier. Is it the `metadata` property under DOM Settings?

**Comment by jlukic** [comment]
either specify a form fields name, id or data-validate="' property.

Here's an example of all three (although you only need one to match)

```html
<input type="text" name="username" id="username" data-validate="username">
```

**Comment by FoxxMD** [comment]
Ah so it checks all the fields. Thanks!
