### ISSUE TITLE
Module Idea: Checklist, Scroll Pane

### ISSUE THREAD

**Issue by mktm** [Semantic-Org/Semantic-UI#1843]
So, I wanted to do this to a project I am currently working on, and I thought maybe this could become a good feature into Semantic among all current ones.

It is very simple...
Often, if you do crud or any other form, you might come into need to make a checklist.
So this could be a simple module (check all / uncheck all) and also this CSS "scroll pane" which basically sets a max-height to a div and overflows it to auto.

Demo: http://jsfiddle.net/mktm/xwp1L695/

**Comment by kvetoslavnovak** [comment]
This is looking really nice.

**Comment by jlukic** [comment]
Have you seen the [attaching checkbox events](http://semantic-ui.com/modules/checkbox.html#attaching-events-to-other-elements) example, this can be done relatively simply using build in checkbox behaviors.

**Comment by mktm** [comment]
That is great!
I didn't saw that before, have to replace my code.

What about the scroll pane?
You think could be implemented into Semantic?

**Comment by kvetoslavnovak** [comment]
Scroll pane is really usefull for tables. UX is much friendly than paggination, mainly when you need to see the result of search or filter. 
I would definitelly welcome to add this possibility.

**Comment by jlukic** [comment]
I think this makes more sense to handle with `check all` etc.
