### ISSUE TITLE
wrong card margin first-last child ver.1.9.3

### ISSUE THREAD

**Issue by lightstore** [Semantic-Org/Semantic-UI#1844]
I fix this:
.ui.card:first-child {
margin-top: 0.75em;
}
.ui.card:last-child {
margin-bottom: 0.75em;
}

![croppercapture 5](https://cloud.githubusercontent.com/assets/11103511/6312068/37713944-b976-11e4-8699-3a6ac7f24848.png)

**Comment by lightstore** [comment]
olso,  "pointing dropdown" dont work under "ui menu"

<div class="ui icon menu">
                <div class="left menu">
                    <div class="ui top right floating pointing dropdown item" id="select">

**Comment by jlukic** [comment]
Groups of cards should be `ui cards card` no?

**Comment by morteza** [comment]
Thank you @jlukic for the solution. I had the same margin issue of `.ui.cards` margins, and it's been resolved by changing `.ui.cards > .ui.cards` to `.ui.cards > .cards`. It might be helpful pointing it out somewhere.

**Comment by jlukic** [comment]
Can anyone make a JSFiddle of the code thats producing issues? I'd like to debug more.

**Comment by morteza** [comment]
Here it is: http://jsfiddle.net/hbasc2w1/2/

Check first child and last child margins. The reason why someone do this could be that they start with `.ui.card`, and then expand  it to `.ui.cards > .ui.card`. The inner `.ui.card`s should be `.card`s.

**Comment by jlukic** [comment]
I understand now, I'll fix `ui card` inside `ui cards` to have same formatting as `ui card card`

**Comment by gabormeszoly** [comment]
yes, without `ui card` looks good: http://jsfiddle.net/ukboporu/

**Comment by jlukic** [comment]
Fixed in `next`
