### ISSUE TITLE
Equal Height Row Changes Flex Value

### ISSUE THREAD

**Issue by c0m3nk** [Semantic-Org/Semantic-UI#1846]
Before
![screen shot 2015-02-21 at 7 42 37 pm](https://cloud.githubusercontent.com/assets/982692/6314108/d6ed3f3c-ba01-11e4-8c09-b59de982ef3b.png)

<code>
.ui[class*="equal height"].grid > .column,
.ui[class*="equal height"].grid > .row > .column,
.ui.grid > [class*="equal height"].row > .column {
  flex: 1 0 auto;
}
</code>

After
![screen shot 2015-02-21 at 7 41 59 pm](https://cloud.githubusercontent.com/assets/982692/6314104/c383c0a6-ba01-11e4-8da7-c22795a0d5bf.png)

<code>
.ui[class*="equal height"].grid > .column,
.ui[class*="equal height"].grid > .row > .column,
.ui.grid > [class*="equal height"].row > .column {
  flex: 0 0 auto;
}
</code>

**Comment by jlukic** [comment]
Can you provide a JSfiddle? I just need to get a sense for the exact html structure thats causing content to collapse.

**Comment by c0m3nk** [comment]
http://jsfiddle.net/01L4jk7o/

**Comment by jlukic** [comment]
Fixed in `next`, also column child content (like segment) will now stretch to fit column height.
