### ISSUE TITLE
More than one transition on several cards fail

### ISSUE THREAD

**Issue by cm45t3r** [Semantic-Org/Semantic-UI#1848]
Hi,

I think I found a bug when assigning more than one transitions to cards that have a picture, content and extra. E.g. `$('.card').transition('fade').transition('fade');`. When running several times, some of them don't re-appear. Here is a [jsfiddle](http://jsfiddle.net/8xqwz135/) to see live.

**Comment by jlukic** [comment]
This appears to be an issue with webkit not firing `animationend`

As a temporary solution until I look further, you can solve this by using `useFailSafe: true`
http://jsfiddle.net/8016bhah/

**Comment by jlukic** [comment]
This appears to be a webkit only bug related to [Chromium Issue #437860](https://code.google.com/p/chromium/issues/detail?id=437860)

It looks like queued animations need to also use a `failSafe` for `onanimationend` in Chrome.

**Comment by jlukic** [comment]
Fixed in `next`.

**Comment by cm45t3r** [comment]
Cool!
