### ISSUE TITLE
Visibility is made as hidden by default?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1849]
Trying to make a side menu, but  it is hidden by default even adding `active`
![untitled-1](https://cloud.githubusercontent.com/assets/2527234/6315897/5afb2ece-ba11-11e4-931d-7dc745344f28.jpg)

Is that because it is only made to hide/show using javascript, that by default it is hidden?

**Comment by ph7vc** [comment]
The sidebar intended for use with javascript. Take out the `sidebar` class and it will work that way you want it to: http://jsfiddle.net/efp8z6Ln/

You will probably want to put that menu inside a grid column so to align content to the right of it

**Comment by abdelouahabb** [comment]
Because the tutorial I saw, when he made it, it was not hidden, maybe the version was old?

**Comment by ph7vc** [comment]
What tutorial?

**Comment by abdelouahabb** [comment]
http://webdesign.tutsplus.com/courses/getting-started-with-semantic-ui

**Comment by ph7vc** [comment]
Ah, I've come across that one before. They used a pre-1.0 version in that one since 1.0 didn't release til December 2014. The doc's site has most of the info and code snippets you need to get going pretty quickly.

 I'd definitely recommend skimming through it, there are new features added all the time! http://semantic-ui.com/

**Comment by abdelouahabb** [comment]
ah, yes, that is what I am doing finally :dancer: 

Semantic UI has grew so fast! that even this tutorial as new, there are so much stuff new in the framework!

**Comment by ph7vc** [comment]
I made a mistake, you can actually have it visible with the `visible` class if you like: `<div class="ui visible sidebar"></div>`

http://semantic-ui.com/modules/sidebar.html

Shows how much I read the docs haha. This is still the Javascript controlled sidebar, so it'd probably still be best to create a vertical menu without the sidebar-ness.

**Comment by abdelouahabb** [comment]
looool it seems that even me I've read well the doc :P ^_^
