### ISSUE TITLE
Search: Selection of remote search results no longer working

### ISSUE THREAD

**Issue by r0b-** [Semantic-Org/Semantic-UI#1850]
After upgrading to 1.9 selection of remote search results is no longer working :-(

I get an "Uncaught TypeError: Cannot read property 'length' of undefined" in https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L313

Debugging shows that result is actually an object that obviously has now length property...

**Comment by r0b-** [comment]
I changed the related if statement in
```
$.each(results, function (index, category) {
	if (category.results !== undefined) {
		result = module.search.object(value, category.results)[0];
		if (result.length > 0) {
			return true;
		}
	}
});
```
to
```
if(!$.isEmptyObject(result)){
     return false; // Returning false exits the $.each() loop.
}
```
With that the code is running (hopefully as intended), but now I'm having the problem that if there are results with the same value (= displayed title) but in different categories always the value in the first category is picked.

:confused:

Thanks in advance

**Comment by jlukic** [comment]
Can you give me an example of the server response you are returning that is producing an error? I'm not able to reproduce with standard examples in docs.

**Comment by brianlawasdf123** [comment]
I'm seeing the same error. Here's a sample JSON response:
```
{
        'results': {
            '123': {
                'name': 'Cats',
                'results': [
                    {
                        'title': 'meow',
                        'url': '/optional/url/on/click',
                        'image': 'optional-image.jpg',
                        'price': 'Optional Price',
                        'description': 'Optional Description'
                    },
                    {
                        'title': 'Result Title',
                        'url': '/optional/url/on/click',
                        'image': 'optional-image.jpg',
                        'price': 'Optional Price',
                        'description': 'Optional Description'
                    }
                ]
            },
            '456': {
                'name': 'Dogs',
                'results': [
                    {
                        'title': 'bark',
                        'url': '/optional/url/on/click',
                        'image': 'optional-image.jpg',
                        'price': 'Optional Price',
                        'description': 'Optional Description'
                    }
                ]
            }
        },
            // optional action below results
            'action': {
            'url': '/path/to/results',
            'text': 'View all 202 results'
        }

    }
```

**Comment by aaroncox** [comment]
Experiencing the same issue. 

I also see it happening on the [category example](http://semantic-ui.com/modules/search.html#category) page. To reproduce, enter the search query of ***c***, and every result it returns will cause an error:

`Uncaught TypeError: Cannot read property 'length' of undefined`

Except for if you click on the 'Casey' result, which for some reason, actually populates the box and performs the action.

**Comment by jlukic** [comment]
I'll fix this tomorrow, I can reproduce finally
