### ISSUE TITLE
ui segment bug?

### ISSUE THREAD

**Issue by doortts** [Semantic-Org/Semantic-UI#1851]
```
<div class="ui page grid">
    <div class="ui segment four wide column">a</div>
    <div class="ui segment four wide column">b</div>
    <div class="ui segment four wide column">c</div>
    <div class="ui segment four wide column">d</div>
    <div class="ui segment four wide column">e</div>
    <div class="ui segment four wide column">f</div>
    <div class="ui segment four wide column">g</div>
    <div class="ui segment four wide column">h</div>
</div>
```
then it looks like following..

![home 2015-02-22 17-34-08](https://cloud.githubusercontent.com/assets/520523/6317963/122ff096-bab9-11e4-9779-552810adc0b4.png)

**Comment by jlukic** [comment]
You generally can't mix two elements on the exact same element unless specifically noted in docs, like drop down and button for example. Some may work, but others cant. Segment and column both rely on their margin and padding for different things. 

Try nesting segments inside each column.
