### ISSUE TITLE
Switching popups doesn't trigger hide/hidden

### ISSUE THREAD

**Issue by erasaur** [Semantic-Org/Semantic-UI#1852]
Not sure if this is intended behavior or not. When clicking on button A and subsequently on button B, the first popup is closed (as expected) but the hide event isn't triggered. 

See this [fiddle](http://jsfiddle.net/7kzuv0yz/1/) for an example.

**Comment by jlukic** [comment]
This is a bug related to this bit of code in [hide all](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/popup.js#L297)

The gist is that components are stored in metadata in activating elements, but those activating elements aren't easily discoverable, so the workaround is to hide all `ui popup` with `transition`, but that means it doesn't go through `popup('hide')` which triggers the correct callback. 

I'm sure this can be solved but I believe this would require a bit of a rework to store a reference to activating elements from each `ui popup`

**Comment by jlukic** [comment]
Thanks for your patience, the bug is now corrected. I've also added an `exclusive` setting to popup to specify whether it should close other popups when opening.

**Comment by erasaur** [comment]
Awesome, thanks!
