### ISSUE TITLE
Website Bug with Multiple Modals Example

### ISSUE THREAD

**Issue by Aproducktion** [Semantic-Org/Semantic-UI#1855]
The second Multiple Modals example on the [website](http://semantic-ui.com/modules/modal.html#/examples) is reproducing the same issue that I am having when opening a modal and then triggering a second modal with the first modal's button. One the second modal is open the dimmer is stuck and there is not a way to close

**Comment by jlukic** [comment]
I'm not experiencing these issues with the second example.

 Can you describe the exact process you are using to reproduce the issue with that example, and what your browser version/OS is?

**Comment by Aproducktion** [comment]
Yeah, Im on OSX 10.10.1 (14B25) and in both Chrome (41.0.2272.64) and Safari(8.0.2 ) when I navigate to the Modals examples and click run code on the second example for Multiple Modals the first popup shows. I click "Proceed" and then  "All Done" its closes the modal and leaves the dimmer up (see attached).

It seems to be a timing thing, when I first went back and spent more time clicking through it seemed to work, but if I click through quickly the problem arises. I am having the same problem on my project whereas I use one modal to open another and the dimmer stays put.

![screen shot 2015-02-23 at 2 15 23 pm](https://cloud.githubusercontent.com/assets/1811675/6338868/db8e8cb0-bb66-11e4-9deb-88950febf1e1.png)
![screen shot 2015-02-23 at 2 15 30 pm](https://cloud.githubusercontent.com/assets/1811675/6338867/db8e7e00-bb66-11e4-869f-bc37e56bb9b5.png)

**Comment by Aproducktion** [comment]
@jlukic 

It looks like your latest updates fixed the bug, thank you for all your hard work! I am really digging Semantic-UI :)

**Comment by jlukic** [comment]
Most likely this was related to `webkit` not using `failSafe` when animations are queued.
