### ISSUE TITLE
Why there is no main container rule?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1857]
As a new comer for CSS frameworks, I thought that I can find the base, which is the main container, but it was not there, so what I used is an old way:

`.main.container{width: 1200px;margin: 0 auto;background-color: rgb(23, 94, 94);border-radius: 5px;}`

The color differs, but I wished there would exist such a ruler to simplify the job, since every skeleton needs a base!

**Comment by jlukic** [comment]
`container` is the same as `ui page grid` with `one column`.  There may be a simpler `ui container` element that mimics `page grid` margins in the future, but this would only be useful as a convenience.

**Comment by abdelouahabb** [comment]
I was searching for the ruler in the `semantic.css`

![sans titre](https://cloud.githubusercontent.com/assets/2527234/6333341/870109c2-bb8c-11e4-86e9-bcab41a0d360.jpg)

But dident found it, so i guessed that it was added manually?

**Comment by abdelouahabb** [comment]
`ui page grid one column` breaks the divided `ui two column middle aligned relaxed fitted stackable grid`

**Comment by jlukic** [comment]
If you want to include arbitrary sized containers in your site's code, its definitely not incompatible with SUI. Just include your own CSS.

**Comment by abdelouahabb** [comment]
I hope this will be included in the docs?! something like: container ?
