### ISSUE TITLE
Creating Custom Validation: case-sensitivity in fluffy dogs example in Docs

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI#1858]
Ref: [Fluffy dogs example at the bottom of this docs page](http://semantic-ui.com/behaviors/form.html#/examples)

The rule ```'contains[fluffy]'``` does a case-sensitive match on the word ```fluffy```. Entering ```Fluffy```, or ```fluffY```, or ```Fluffy dog``` shows the error prompt.
The same is true for the ```'not[mean]'``` rule.

Is there an undocumented way to do a case-insensitive check?

P.S.
The word ```mean``` in the rule ```'not[mean]'``` is only matched when it's the only word in the input box.
Which is one-on-one with the validation description of the ```not``` parameter, but makes the example awkward. A ```contains``` rule would be a better fit.

**Comment by Lisa-Williams** [comment]
I already checked [the ``` contains[]``` match](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/form.js#L974)
The RegEx contains no ``` i``` flag.

And also [the ```not``` match](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/form.js#L1068)
Both expressions/variables of the ```!=``` operator, are not wrapped in ```toLowerCase()``` or ```toUpperCase()```.

So a case-insensitive check/match is not possible at all.

**Comment by jlukic** [comment]
Added `isExactly`, `notExactly`, `containsExactly`, changed previous rules to case insensitive versions.

Available in `next`.
