### ISSUE TITLE
[Searchable form dropdown] Pressing 'esc' or blurring doesn't restore old value

### ISSUE THREAD

**Issue by mroach** [Semantic-Org/Semantic-UI#1859]
Typical searchable dropdowns restore the original value when you press `esc` or manually blur without selecting anything. Semantic searchable dropdowns 1) don't close b) don't restore the old value, or leave the search text there if you have `forceSelection` disabled.

To demonstrate desired behaviour, I created this workaround using the Mousetrap javascript library which solves the `esc` key issue anyway.

```coffee
Mousetrap.bindGlobal 'esc', (e) ->
    $('input.search:focus').val('')
      .parent('.dropdown').dropdown('restore defaults').dropdown('hide')
```

**Comment by jlukic** [comment]
Let me know if I'm misunderstanding, but what you are describing sounds like the behavior of `forceSelection: true`?
