### ISSUE TITLE
<i class="woman icon"></i> would not show

### ISSUE THREAD

**Issue by ShawnOceanHu** [Semantic-Org/Semantic-UI#1863]
Hi, while playing around with SU, I ran into a really weird thing, when setting icon class to "man" or "woman", the icon would not show. But it's ok for other icons like "male/female" .etc. I'm using the latest commit, 219fedaaa3a12761a13d5f98a4b962848d63cc2d.

Do you guys have any clues ? Would really appreciate your help :)

**Comment by wordempire** [comment]
I can't seem to reproduce your problem on commit 219feda; all of the mentioned icons show up for me in `Chromium 40.0.2214.111 Ubuntu 14.04`. As jsfiddle + externally hosted webfonts don't seem to be on the best of terms, could you maybe upload files that show this bug happening?

**Comment by Anachron** [comment]
Women rarely show up when you really need them. Did this help? :)

**Comment by jlukic** [comment]
Can't reproduce your issue. Can you create a test case?
