### ISSUE TITLE
Compact dropdown problem in table cell

### ISSUE THREAD

**Issue by gabormeszoly** [Semantic-Org/Semantic-UI#1864]
Wrong dropdown icon position, only when compact.
Fiddle here: http://jsfiddle.net/epqa3dop/

**Comment by geemang2000** [comment]
Maybe haven't have enough coffee yet.  I tried your example with the following . It works as expected. 

                <div class="ui compact selection dropdown">
                    <input type="hidden" name="CHAR" value="A">
                    <i class="dropdown icon"></i>
                    <div class="text">-</div>
                    <div class="menu">
                      <div class="item" data-value="A">A</div>
                      <div class="item" data-value="B">B</div>
                      <div class="item" data-value="C">C</div>
                    </div>
              </div>

**Comment by geemang2000** [comment]
<div class="ui compact selection dropdown" >
                    <input type="hidden" name="???">
                    <i class="dropdown icon"></i>                    
                       <div class="default text">-</div> 
                   
                    <div class="menu">
                        <div class="item" data-value="1">1</div>
                        <div class="item" data-value="0">2</div>
                    </div>
                </div>

**Comment by gabormeszoly** [comment]
@geemang2000 only in table cell

**Comment by geemang2000** [comment]
ahh

**Comment by jlukic** [comment]
I can see what you mean. I'm not sure if its a bug per-se, just `table-collapse: collapse` doing its job and breaking to new lines on icons.

**Comment by gabormeszoly** [comment]
Next time I should be more attentive before opening an issue.
Thanks Jack!
