### ISSUE TITLE
Meteor: semantic:ui package missing

### ISSUE THREAD

**Issue by Helmi** [Semantic-Org/Semantic-UI#1865]
Hi,

looks like there is no semantic:ui package for Meteor like the Readme says. I also tried finding the package on Atmosphere.

Release/Build problem? Forgotten? :)

Thanks,
Frank

**Comment by splendido** [comment]
Hi @Helmi,
so far only css versions were successfully (auto) published.
The LESS version `semantic:ui` is still under discussion and at the moment `meteor publish` crashes on it: see [#1](https://github.com/Semantic-Org/Semantic-UI-LESS/issues/1)

@jlukic , perhaps we should temporarily remove references to it?

**Comment by Helmi** [comment]
ah i see. I think a small note would be good - i wouldn't remove references completely. With a small not at different points people would recognize there's work to do and probably help if they could. I would but i guess i currently couldn't.

**Comment by jlukic** [comment]
@Helmi Feel free to suggest an edit https://github.com/Semantic-Org/Semantic-UI-LESS/issues/1#issuecomment-76435378
