### ISSUE TITLE
[Build] JS Missing Version Number

### ISSUE THREAD

**Issue by blq** [Semantic-Org/Semantic-UI#1866]
All CSS files seem to have the version number burnt into the header, but none of the JS files have that. Might be nice for diffing, if not for consistency/symmetry.

**Comment by jlukic** [comment]
Consolidating license banner and adding version numbers to component releases.

**Comment by jlukic** [comment]
Slightly more work than expected but i got to add this gem `/(^\/\*[\s\S]+)(# Semantic UI )([\s\S]+?\*\/)/` so it was all worth it.
