### ISSUE TITLE
Kitchen sink flags dropdown becomes unusable

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1867]
http://semantic-ui.com/kitchen-sink.html#dropdown

The flags dropdown. 
1) type asdf in the dropdown (after you do this the caret does not work)
2) click the body of page
3) click back into the dropdown, delete the asdf
4) type asdf, select the body and the dropdown should select Andorra
5) After # the dropdown is unresponsive

**Comment by jlukic** [comment]
I've tried reproducing the steps you outline. At #4 it is leaving asdf in the dialog and not selecting Andorra. It continues to work correctly afterward.

Is there a step you're missing? What platform?

**Comment by geemang2000** [comment]
MacOS Chrome (latest)

Ok try this instead.
1) Select Andorra, type asdf
2) click body (should revert to Andorra)
Dropdown is unresponsive

**Comment by jlukic** [comment]
Thanks I see it now

**Comment by jlukic** [comment]
Fixed in `next`
