### ISSUE TITLE
[UI-Suggestion] Typography options

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#1868]
It would be cool if there was a global feature that allows one to define typography styles. Things like bold, italicized, colors, sizes, etc.

So we could have something like this: `<span class="ui bold blue text">I'm bold and blue!</span>` or `<h2 class="ui italic header">Italics!</h2>`

Of course this would only apply to certain tags, or things that are not already well-defined / theme-able parts of the framework.

The colors could be the spectrum ( roy g biv ) but also something like fadded, so it has lower opacity or is greyed a bit to show that it is not as important as the other text on the page.

I've found myself in a lot of cases wanting to be able to finely customize certain elements on the page without writing my own CSS.

**Comment by jlukic** [comment]
Semantic is meant to be abstractions for higher order UI concepts, this is much too granular. 

In general if something can be done in one or two css properties, it won't be included in SUI.
