### ISSUE TITLE
Help wanted/question - align SVG item in a menu

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#1869]
Hi everyone,
I have been fighting with the alignment of an embedded SVG image in a SUI menu. I can not get a sidebar icon, a SVG item, a link and a button to bottom-align in a SUI menu without too much padding. Can anyone show me how to control alignment and padding around menu items, please? Thanks in advance!

Here is a fiddle:
https://jsfiddle.net/11g32wr6/

**Comment by SoGooDFR** [comment]
Hi,
Replace SGV code with:  
<svg style="margin-bottom:-10px;" viewBox="0 0 100 100"  
                     preserveAspectRatio="xMinYMin meet" width="2em" height="2em">
                    <circle cx="50" cy="50" r="40" 
                         stroke="red" stroke-width="4" fill="yellow" />
                </svg>

**Comment by jlukic** [comment]
There is a `flexbox` version of `menu` in branch `flex-menu` that you might want to try, which matches item height in horizontal menus.
