### ISSUE TITLE
read-only input in form should not have focus style

### ISSUE THREAD

**Issue by SummerWish** [Semantic-Org/Semantic-UI#1870]
```css
<div class="ui form">
  <div class="ui input">
    <input type="text" value="read only here" readonly>
  </div>
</div>
```

currently it will have the focus style when user clicked it.

**Comment by jlukic** [comment]
I think its alright for read only fields to have focus stylings.

**Comment by SummerWish** [comment]
then there are no difference between a read-only field and an editable field? users may get confused

**Comment by SummerWish** [comment]
In raw HTML, read only fields has a lighter border and user cannot give focus to it.. I think it is a good example :-)

**Comment by jlukic** [comment]
Alright im convinced
