### ISSUE TITLE
How's it going about polymer with semantic-ui?

### ISSUE THREAD

**Issue by Colstuwjx** [Semantic-Org/Semantic-UI#1872]
I'm new to semantic-ui, and I think it's definitely cool.But how to use it in polymer?
I tried it in my custom element, and it didn't work, and I noticed that it's a problem of JQuery.

How to use semantic-ui in polymer with JQuery? 
As JQuery still cannot visit shadowdom right now, and it made some semantic-ui effect didn't work.

**Comment by jlukic** [comment]
I'm not familiar with jQuery's issues with shadow dom selectors, but most likely our components working rely on jQuery selectors working correctly. You'll have to check in on their issues board to see how thats going.

Semantic UI elements are a different implementation than web components (Polymer). Things are organized a little looser, there is no exposed DOM and shadow dom just class name conventions.  

I'm still a little unsure of the viability of the particular implementation details that the W3C chose to implement with the web component's standard. However the library will shift that direction if adoption proves me wrong. Semantic UI is suppose to be a library that codifies conventions in usage, which requires sometimes waiting to see where adoption leads us.

**Comment by Colstuwjx** [comment]
Hi, @jlukic, Thanks a lot for your reply. I will try to wrapper the semantic-ui element, such as toggle checkbox, try [using JQuery in Polymer element!](http://www.baasic.com/posts/Using-jQuery-with-Web-components/). I will keep it post whether it works well.

**Comment by jlukic** [comment]
If you are successful at writing polymer wrappers please let me know, i can link to individual components from our integration wiki.
