### ISSUE TITLE
how to easily stop transition

### ISSUE THREAD

**Issue by SummerWish** [Semantic-Org/Semantic-UI#1873]
`.stop()` is available for jQuery transitions. However I didn't found documentations about how to abort the current transition in semantic-ui.

**Comment by jlukic** [comment]
Technically you can do this by calling `$('.foo').transition('complete')`  but this is a bit confusing. 

I'll add `stop` (stop current animation) and `stop all`, clear current animation and queue.

**Comment by jlukic** [comment]
Added in next with examples.

**Comment by SummerWish** [comment]
thank you :-)

**Comment by batata004** [comment]
Did you add this feature of "stop"? Cause I cant find it nowhere in the documentation and it would be very handy in my situation!

**Comment by caba8685** [comment]
Also looking for this feature, is this still valid?
