### ISSUE TITLE
Typo in Page Grid Definition section

### ISSUE THREAD

**Issue by jdwallace12** [Semantic-Org/Semantic-UI#1876]
in the blue alert the word gutters has an extra s

"A page grid has gutters to the left and right of its columns to center content on a page. These gutterss adjust as the width of the browser changes, ensuring your grid uses a sensible amount of the browser."  

Loving Semantic UI btws

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/4f37e174f4186e9a39ef8af2e09f99006f351cf0
