### ISSUE TITLE
semantic-ui documentation site down for some time on 26th feb 

### ISSUE THREAD

**Issue by Prashanth-Nelli** [Semantic-Org/Semantic-UI#1877]
![site image](https://cloud.githubusercontent.com/assets/7310975/6395460/459c247a-bdfe-11e4-9bf7-96654b4fb744.jpg)

**Comment by jlukic** [comment]
We're hosted on GitHub, Perhaps this is related to government blocking of GitHub? Otherwise you can always check [GitHub Status](https://status.github.com/) to see if they are having any outages.

[Slightly old news article](http://readwrite.com/2015/01/02/india-lifts-internet-block-github)
>Update Jan. 4, 2015: A GitHub spokesperson said some users in India are still having difficulty accessing the site, and it is GitHub's top priority is to restore access to the developer community in India. "We have tried to reach out to the Indian government through several different channels, but so far it is still not clear to us what content caused them to put us on the list," a spokesperson said. " we would like to work with the Indian government to establish a transparent process for identifying unlawful content, restore access, and ensure that GitHub continues to remain available in the future without interruption."

**Comment by Prashanth-Nelli** [comment]
thanks jlukic for quick reply.
