### ISSUE TITLE
Which is the proper way to work with npm modules and browserify?

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#1878]
Hi. I'm trying to use some of the SUI modules inside an application in which I'm already using Browserify and npm modules.

I found some problems while trying to get the modules to work.
So far I've tried four modules: semantic-ui-checkbox, semantic-ui-dropdown, semantic-ui-tab and semantic-ui-modal.

With semantic-ui-checkbox everything worked properly with the following code:

```
var $ = require('jquery');
var Checkbox = require('semantic-ui-checkbox');
$.fn.checkbox = Checkbox;

....

//In my Marionette.View onShow method
this.$el.find('.ui.checkbox').checkbox();
```

However, with the other three modules I've encountered problems:

* semantic-ui-dropdown: just requiring it produced an error with browserify that goes away if I remove the underscore in this [line](https://github.com/Semantic-Org/UI-Dropdown/blob/8047fbfa25888e57a7cba87714b5fe1f6169e3dc/index.js#L1741), probably a bug. After fixing that, another error occurs because internally it is using the transition module. I've tried including the module before (without the need of manually doing `$.fn.transition = require('semantic-ui-transition')` because this time the module does it automatically -I think either all modules should do that or none, otherwise it could be misleading-). After trying that, the error is different and  `Uncaught ReferenceError: _module is not defined` pops up in this [line](https://github.com/Semantic-Org/UI-Transition/blob/aaf0fa2517d0ee777c94224fae7ea58f12425556/index.js#L508) after I click the menu.
* semantic-ui-tab: similar problems as semantic-ui-dropdown. In this case `Uncaught TypeError: Cannot read property 'exports' of undefined` pops up in [line](https://github.com/Semantic-Org/UI-Tab/blob/52024be09ab913de5d01c727bf93f3810b30d7fe/index.js#L28) when I invoke `.tab() on the DOM elements.
* semantic-ui-modal: apparently this module depends on dimmer and dimmer on transition, so I've tried requiring them before (in the same fashion as before `$.fn.dimmer = require('semantic-ui-dimmer')`. After doing that, `Uncaught ReferenceError: _module is not defined` pops up in [line](https://github.com/Semantic-Org/UI-Transition/blob/aaf0fa2517d0ee777c94224fae7ea58f12425556/index.js#L508) when I invoke the modal. It looks as the same error as with the dropdown module.

Am I doing something wrong? Are there any examples of using that modules in a browserify environment?

Thanks in advance.

**Comment by jlukic** [comment]
The NPM releases are created dynamically from source using a build script. The `_module` change came from #1156.

You can check out what the [script is doing here](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/components/create.js#L150) with [these regex](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/components/create.js#L114).

I haven't had much time testing single component releases with npm. It would be really helpful if you can provide any feedback that will help me update the regexp to patch issues you are encountering, or perhaps even PR the build script. 

You can run the build script locally using `admin: true` in your `semantic.json` and `gulp "create components"` or `gulp release`

**Comment by trigoesrodrigo** [comment]
I'll try to make them work and provide feedback, although it's my first app with browserify and I'm not confident of finding a good solution.

Until everything with the modules is sorted out, another way to make everything work easily is to use browserify-shim to expose jquery to semantic-ui in your package.json. 

```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "sui": "./semantic/dist/semantic.js"
  },
  "browserify-shim": {
    "sui": {
      "depends": [
        "jquery:jQuery"
      ]
    }
  }

```
Then, in any view in the app you could just `require('sui')` and use the modules without problems. It's not as clean as just requiring the exact modules used but it gets the job done.

Thanks for your wonderful library and the amount of effort you're putting in it.

**Comment by sdimit** [comment]
Is there any progress with fixing this bug? I'm experiencing the same issues with semantic-ui-popup. 
What worked was renaming '_module' to 'module' inside 'popup:' (index.js). Also the default easing function does not exist and causes another undefined error. Setting module.exports.settings.easing  = 'easeOutQuad' instead of 'easeOutQuadInt' fixes this as well.

**Comment by jlukic** [comment]
I'll take a look at this today

**Comment by jlukic** [comment]
Will release with patch today.

**Comment by jlukic** [comment]
Closing, will re-open if anyone sees any continuing issues

**Comment by chessels** [comment]
This patch causes a syntax error in [https://github.com/Semantic-Org/UI-Site/blob/master/index.js](https://github.com/Semantic-Org/UI-Site/blob/master/index.js) (line 13).

```javascript
/*!
 * # Semantic UI 2.0.7 - Site
 * http://github.com/semantic-org/semantic-ui/
 *
 *
 * Copyright 2015 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
;(function ( $, window, document, undefined ) {

$.site = var _module = module;
module.exports = function(parameters) {
```

**Comment by jlukic** [comment]
I'm pretty sure automatically creating modules via regExp is a terrible monkeypatch. Sorry about these kinds of bugs.

**Comment by chessels** [comment]
I agree, the RegExp approach is not very solid. No need to appologise though.

I guess refactoring each component to have built-in support for UMD/CommonJS would be the proper  solution.

**Comment by davide** [comment]
Pull request 2816 (attached above) should take care of the issues described by @trigoesrodrigo and @chessels (as well as a similar issue with the api component).

@jlukic if everything looks good can you please do a new npm release for us? Thanks!

**Comment by jlukic** [comment]
I'll take a look at this specifically for a patch monday. Still coralling things together for a larger `2.1` release with some new features possibly later in week.
