### ISSUE TITLE
Site documentation inaccurate for Popup - Settings - Position

### ISSUE THREAD

**Issue by kocsenc** [Semantic-Org/Semantic-UI#1879]
In the [Popup Settings](http://semantic-ui.com/modules/popup.html#/settings) page, it mentions that the default position is `top center`. In reality, however, I am fairly certain that when not specifying any position, its `top` or `top right` but not `top center`.

**Comment by jlukic** [comment]
You're right, docs are off.

**Comment by jlukic** [comment]
4f37e174f4186e9a39ef8af2e09f99006f351cf0 fixed

**Comment by kocsenc** [comment]
Thanks @jlukic . I'll have more motivation to open a PRequest next time.
