### ISSUE TITLE
[Modal] Custom Hide Logic - Open Another Modal Bug

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#1880]
Due to needing to be have more than a just a positive/negative button on the modal actions, I return false in onApprove and manually call .modal('hide') on the button clicks.  In one case I open up another dialog immediately after.  This causes the second modal's dimmer to show, but not the dialog.

Here is a jsfiddle with a demonstration: http://jsfiddle.net/daneren2005/nk3u4vha/.  Click the close button on the first dialog and the second will never appear properly.

This artificial example is easy to work around, but in my case it is actually dependent on how long a ajax call takes.  If it takes less then about 500 ms, this happens.  If it takes longer than that, it does not.  If it takes longer though, I don't want to just leave the first modal there waiting for the ajax call to finish and the subsequent second modal to take it's place.

**Comment by jlukic** [comment]
Triggering both `hide` on first and `show`  on second seems to cause issues in your case since when the first `hide` is called, no other modals are on page.

This can be fixed simply enough. Just remove the line that hides the first modal, this will happen automatically when showing the second.http://jsfiddle.net/pxL0h7du/

**Comment by daneren2005** [comment]
That only works if the ajax call return quickly.  I need to hide the modal since the ajax call may take a long time (10-20 seconds in some cases).  I don't want to just leave the modal hanging there in those cases.

**Comment by jlukic** [comment]
Your test case is fixed in `next`.

**Comment by daneren2005** [comment]
Thank you.  I know this was a fairly uncommon error.
