### ISSUE TITLE
Incorrect Icon when rotating 'clockwise'

### ISSUE THREAD

**Issue by kocsenc** [Semantic-Org/Semantic-UI#1881]
When attempting to rotate an icon clockwise by adding `clockwise rotated` class, the result is the clockwise icon, instead of the intended rotated icon.

This also reflects in the [icon defenitions page](http://semantic-ui.com/elements/icon.html#/definition). => see rotation

**Comment by jlukic** [comment]
Thanks, must have been added in last icon update.

**Comment by jlukic** [comment]
Fixed in `next`
