### ISSUE TITLE
[Step] a ordered sequence of steps in IE10 show in small font size.

### ISSUE THREAD

**Issue by goslife** [Semantic-Org/Semantic-UI#1884]
http://semantic-ui.com/elements/step.html

In IE10
![sematic_step_ie27-2-2015 18-51-46](https://cloud.githubusercontent.com/assets/919501/6412125/7a2e355c-beb2-11e4-85f5-a024f68deebf.jpg)

In Chrome
![sematic_step_chrome27-2-2015 18-52-39](https://cloud.githubusercontent.com/assets/919501/6412143/95860438-beb2-11e4-892f-e213e321a61d.jpg)

**Comment by jlukic** [comment]
I can confirm this is fixed in IE10 with `flexbox` rewrite for `steps` in `2.0`. 

I really apologize about the delay in getting back about this.
