### ISSUE TITLE
Got 'undefined is not a function' when using API 'Sending Data'

### ISSUE THREAD

**Issue by fuhaiq** [Semantic-Org/Semantic-UI#1889]
I am trying to commit form by using ajax, and I am referring API usage http://semantic-ui.com/behaviors/api.html#/usage

Here's HTML code :
``` html
<script type="text/javascript">
$(document).ready(function() {
   $.fn.api.settings.api = {
      'quick login': '/user/login'
   };
   $('form .submit.button').api({
      action: 'quick login',
      serializeForm: true
   });
});
</script>
<form class="ui form">
<div class="two fields">
  <div class="required field">
    <label>Username</label>
    <div class="ui icon input">
      <input type="text" name="username" placeholder="Username">
      <i class="user icon"></i>
    </div>
  </div>
  <div class="required field">
    <label>Password</label>
    <div class="ui icon input">
      <input type="password" name="password">
      <i class="lock icon"></i>
    </div>
  </div>
</div>
<div class="ui submit button">Submit</div>
</form>
```

But I always got 'undefined is not a function' in the error console. Can anyone takes a look ? thanks.

BTW: How could I adapt existing validation rules to an ajax form ? I am thinking do validation in the 
`beforeSend` method.

**Comment by jlukic** [comment]
serializeForm relies on a third party library [as the note in docs](http://semantic-ui.com/behaviors/api.html#serializing-form-data) mentions. However, it looks like the check for whether it exists is accidentally calling it. (d3b4315)

Fixed error in displaying error in `next`, or you can include [serialize object](https://github.com/macek/jquery-serialize-object) to fix it immediately.

**Comment by jlukic** [comment]
Doing ajax validation before API is rather simple. The two modules hook into each other.

```javascript

$.fn.api.settings.api = {
  'quick login': '/user/login'
};

$('.ui.form')
  .form({
    name: {
      identifier  : 'username',
      rules: [
        {
          type   : 'empty',
          prompt : 'Please enter your name'
        }
      ]
    },
    password: {
      identifier : 'password',
      rules: [
        {
          type   : 'empty',
          prompt : 'Please enter a password'
        },
        {
          type   : 'length[6]',
          prompt : 'Your password must be at least 6 characters'
        }
      ]
    }
  })
  .api({
    method: 'post',
    action: 'quick login',
    serializeForm: true
  })
;
```

**Comment by jlukic** [comment]
Here's a jsfiddle of above example:
http://jsfiddle.net/snozft6L/

**Comment by jlukic** [comment]
In `1.10.4`

**Comment by fuhaiq** [comment]
Many thanks! @jlukic 

Everything goes well now.

I should check the document more seriously.
