### ISSUE TITLE
Problem loading font on icon.css

### ISSUE THREAD

**Issue by pinguxx** [Semantic-Org/Semantic-UI#1894]
icon.css for default theme its trying to load ./assets/fonts/icons.woff2 but doesnt exist, also its not loading the otf font

**Comment by jlukic** [comment]
I'm seeing the path correct in `dist/` [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/icon.css#L20). Can you point to what file you are seeing this issue in?

**Comment by pinguxx** [comment]
The fonts in the default theme are:
 * icons.eot
 * icons.otf
 * icons.svg
 * icons.ttf
 * icons.woff
 * icons.woff2

But in the basic theme they are:
 * icons.eot
 * icons.svg
 * icons.ttf
 * icons.woff

the dist its omitting the otf from the default theme

dist icon.css file
```
src: url("../themes/default/assets/fonts/icons.eot");
src: url("../themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'),
url("../themes/default/assets/fonts/icons.woff2") format('woff'), 
url("../themes/default/assets/fonts/icons.woff") format('woff'), 
url("../themes/default/assets/fonts/icons.ttf") format('truetype'), 
url("../themes/default/assets/fonts/icons.svg#icons") format('svg');
```
But if you use icon alone as like in [semantic-ui-icon](https://github.com/Semantic-Org/UI-Icon/) it doesn't contains the woff2 and still doesnt load the otf file
 
ui-icon file:
```
src: url("assets/fonts/icons.eot");
src: url("assets/fonts/icons.eot?#iefix") format('embedded-opentype'), 
url("assets/fonts/icons.woff2") format('woff'), 
url("assets/fonts/icons.woff") format('woff'), 
url("assets/fonts/icons.ttf") format('truetype'), 
url("assets/fonts/icons.svg#icons") format('svg');
```

**Comment by jlukic** [comment]
Font Awesome discontinued using `otf` in their css when they added `woff2`. I'll go ahead and remove the asset to avoid any confusion.

I've added a `@src` variable and fixed the `src` for `basic` font. 

I am not able to replicate any issues with paths. If you are using custom LESS compilation you will have to rewrite asset paths between `src` and `dist`, they have different folder structures. This is already built into our gulpfile.

**Comment by jlukic** [comment]
I've also removed the `basic` subclassing. Not sure why it was ever there.
