### ISSUE TITLE
Popup problem with iphone

### ISSUE THREAD

**Issue by startswithaj** [Semantic-Org/Semantic-UI#1895]
Popups do not dismiss properly on scroll and other actions. Meaning if you click to open a popup, then scroll, the popup disappears but if you click on the same element to activate that pop up again it does not reappear. 

To Replicate:

Visit http://semantic-ui.com/modules/popup.html#basic on an iphone. Click one of the example popup buttons. Scroll down a little. Popup should disappear now click the same button to try and activate the popup again. 

There is another slight bug where popups in the same element container fire because the click bubbles up. You can see this by clicking the first example "Type" [+] button. The code <> popup displays as well as the popup that says "add users to your feed".

**Comment by jlukic** [comment]
Not sure what happened here. Will look

**Comment by jlukic** [comment]
Looks like `mouseenter`  is no longer retriggering on touchscreen without another element gaining focus. Will work around.

**Comment by jlukic** [comment]
Fixed in `next`
