### ISSUE TITLE
Why i cant nest column in a column?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1898]
I try to make it work like the documenation, but i cant nest them:

http://jsfiddle.net/0djhjpym/

and the link to stackoverflow: http://stackoverflow.com/questions/28816744/how-to-nest-column-in-a-column

**Comment by jlukic** [comment]
That's appearing exactly as you specified it to, A two column grid inside one of four columns.

**Comment by abdelouahabb** [comment]
so it doesent work? because i thought when i do this, it will divide the percentage, so every column is just a container that received the values from its divided parent?

**Comment by jlukic** [comment]
You are dividing 4 into 2, so that's 1/8th. Those columns are appearing as 1/8th. The text isn't large enough to fit into a container that small.

**Comment by abdelouahabb** [comment]
But why I get it outside? it should fit inside `ui segment` ? I tried using `ui items` but it was the same? What am i doing wrong? what is the best solution for this  problem? and sorry again.
![sans titre](https://cloud.githubusercontent.com/assets/2527234/6450740/35256546-c12a-11e4-953a-112da5f87291.jpg)

**Comment by jlukic** [comment]
In HTML text doesn't automatically resize to fit into available width. If you are using large text, like in a `ui statistic` you need to make sure there is enough room to display it. 

You will need to use a large column width. Probably something like `three column grid` with `doubling` for mobile.

**Comment by abdelouahabb** [comment]
so, i have to adjust manually the size of the police, and how to center the elements? because `centered` will center the whole grid, and not its elements?

**Comment by abdelouahabb** [comment]
and about the police resizing, here is an idea:
use `$("#time").height()` and `$("#time").height()` and resize the text depending on the divided `column` ? I tried and the police `font-size` can take percent as value (the initial value of `statistic= 4em, which is 400% ` ) so i guess it will work?

**Comment by jlukic** [comment]
I'm sorry but this is beyond the scope of this board which is specifically for reporting bugs and requesting features.

**Comment by abdelouahabb** [comment]
sorry, and thank you again ^_^

**Comment by abdelouahabb** [comment]
@jlukic 
here is an update, if i use size+1 when going to the second level i can nest them!
using the same value:
![three](https://cloud.githubusercontent.com/assets/2527234/6578379/240bcb4a-c744-11e4-8957-6d3ae8b60692.jpg)

using value+1
![four](https://cloud.githubusercontent.com/assets/2527234/6578388/2c4348a6-c744-11e4-8062-b4c566f849c9.jpg)
