### ISSUE TITLE
Search onSelect with ajax call

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#1899]
When creating a search, onSelect does not appear to work when it loaded via apiSettings.  When passing in the exact same data via source, it works.  Inside of onSelect, both arguments are undefined, as well as if you try to check the value of the input directly it has not been updated yet.  You can see what I am talking about via this fiddle: http://jsfiddle.net/daneren2005/snvor2gs/

There are two searches: one with apiSettings and one with source.  The one with apiSettings will alert null when selected, and the one with source will return the value of the item you selected correctly.

**Comment by jlukic** [comment]
I'm seeing both examples output the name of the country onSelect. 

Can you describe the exact steps to reproduce in your example?

**Comment by jlukic** [comment]
I'm seeing both examples output the country name on select. Can you give exact steps to reproduce?

**Comment by daneren2005** [comment]
Just selecting anything on the top search box alert null for me.  I just tried it on both FF and Chrome on Windows.  What are you using to test?

**Comment by jlukic** [comment]
I'm using Chrome on Win. It might be dependent on the specific order of events, so if you can outline exactly the steps from page load it would help.

**Comment by jlukic** [comment]
This is weird, I'm only getting this issue sporadically

**Comment by daneren2005** [comment]
I am getting it consistently, so it may be a timing issue affected by how powerful the host machine is. Here is an uploaded video to Youtube: https://www.youtube.com/watch?v=9XFi0-hBOW4&feature=youtu.be

**Comment by jlukic** [comment]
Fixed in `next`
http://jsfiddle.net/ezdnybx4/

**Comment by daneren2005** [comment]
Thank you

**Comment by davishayden** [comment]
You guys are awesome, just searched for so long on this same problem.
