### ISSUE TITLE
Unable to close a message

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#190]
Or doc is incomplete, or there is something to fix

```
<div class="ui message">
  <i class="close icon"></i>
  <div class="header">
     Welcome back!
  </div>
  <p>This is a special notification which you can dismiss if you're bored with it.</p>
</div>
```

**Comment by Morrolan** [comment]
I know that this is closed but this is exactly the problem I'm having - how and where do I put this piece of JS to listen for the close event?

**Comment by sistematico** [comment]
@Morrolan put this:

`<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>$('.close.icon').on('click', function() { $(this).parent().transition('fade'); });</script>`

Before de </body>.
