### ISSUE TITLE
Validation: how to add custom validation rule for remote validation?

### ISSUE THREAD

**Issue by supermarioim** [Semantic-Org/Semantic-UI#1902]
I have tried creating custom rule with ajax request to check uniqueness of email address on my registration form. I get correct result from backend but validation always fails. I tried "async: false" and "$.when().then()" but nothing works.

```javascript
$.fn.form.settings.rules.exists = function(value) {
        $.when(
            $.ajax({
                url: '/check-email',
                type: 'POST',
                dataType: 'json',
                data: { email: value }
            })
        ).then(function(data) {
            return !!data.valid;
        });
    }
```

**Comment by jlukic** [comment]
Callbacks are synchronous so you can't return values from async processes like AJAX. [See this general JS explanation](http://stackoverflow.com/questions/6847697/how-to-return-value-from-an-asynchronous-callback-function)

Instead, add your own validatrion logic in `onSubmit` `return false` to prevent default form submit, and when ajax validates submit form.

**Comment by supermarioim** [comment]
Yes, as I thought

Thanks
