### ISSUE TITLE
Tiny Material Theme bug

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#1905]
On the material theme fluid buttons jumps to another row just before switching to tablet mode.

![screenshot_2015-03-03_09-37-58_pm](https://cloud.githubusercontent.com/assets/907195/6471701/931fb0de-c1ed-11e4-884b-ba008f4ebcac.jpg)

````
.ui.button {
  min-width: 72px;
}
````

I guess this shouldn't be there?

**Comment by jlukic** [comment]
I stole that line from one of Google's properties. Maybe Google Inbox.. they set a min width for buttons. Will remove.

**Comment by jlukic** [comment]
Shipping in `1.11.0`
