### ISSUE TITLE
[ACCORDION] - Decoupling trigger from .title

### ISSUE THREAD

**Issue by Marschant** [Semantic-Org/Semantic-UI#1908]
Hi there, is it currently possible to decouple accordion trigger events from .title wrapping element and assign them to an element within the parent wrapper?

In essence I need to maintain the .title > .content relationship, insert additional elements into .title (some extra icons and status placeholders) and have the toggle functionality attached to a toggle icon within .title

If that's not possible, how can I go about reversing the .title click propagation so that elements within .title can fire their mouse events?

As an aside, thank you for the fantastic work done so far.

**Comment by jlukic** [comment]
Added in `next` patch
