### ISSUE TITLE
Semantic UI website sources?

### ISSUE THREAD

**Issue by rubytastic** [Semantic-Org/Semantic-UI#1909]
Are the Semantic UI website source are available on github?
Amazing job and would be very interested to look how it was done

**Comment by geemang2000** [comment]
There are some examples (https://github.com/Semantic-Org/Semantic-UI/tree/master/examples) but there is a thread #1837  that I believe is related.

**Comment by jlukic** [comment]
It's a docpad server, you can run locally if you follow the instructions in the readme.
https://github.com/Semantic-Org/Semantic-UI-Docs
