### ISSUE TITLE
Dropdown causes Postback on initialization

### ISSUE THREAD

**Issue by jankukacka** [Semantic-Org/Semantic-UI#1912]
This is issue regards the behavior of dropdown when used in ASP.NET (4.5, but I guess it is not version dependent) environment. In older versions (ca. 1.9) this worked properly.

When there is a `asp:DropDownList` element with property `AutoPostBack=true`, a postback is triggered upon initializing the dropdown. This makes Semantic UI dropdown useless in the ASP.NET.

Minimal working example is below:

```html
<%@ Page Language="C#" AutoEventWireup="true"  %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="../semantic/semantic.min.css" type="text/css" rel="stylesheet" />
    <script src="../js/jquery.js" type="text/javascript"></script>
    <script src="../semantic/semantic.min.js" type="text/javascript"></script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:DropDownList runat="server" AutoPostBack="True" CssClass="ui dropdown">
        <asp:ListItem>Abcd</asp:ListItem>
        <asp:ListItem>Efgh</asp:ListItem>
    </asp:DropDownList>
    </div>
        <script>
            $(document).ready(function() {
                $('select').dropdown();
            });
        </script>
    </form>
</body>
</html>
```

**Comment by jlukic** [comment]
I'm not sure what conditions cause autopostback to trigger in ASP.net, but the select is moved on init to accommodate the new html. The value shouldn't be adjusted, but it is detached from the dom and reattached.

**Comment by jankukacka** [comment]
A `DropDownList` with Autopostback property set to `true` renders like this:

```
<select onchange="javascript:setTimeout('__doPostBack(\xxxx\',\'\')', 0)" ... >
	...
</select>
```

Raising the `onchange` event launches a zero timeout which calls the `__doPostBack` function. Problem therefore seems to be launching the `onchange` event during dropdown initialization.

**Comment by jlukic** [comment]
Perhaps you're looking for 
```javascript
$('.ui.checkbox').checkbox({
  fireOnInit: false
});
```

**Comment by jankukacka** [comment]
Yes, this **solved the problem** - thank you! (Now I feel silly for opening a new issue, which has solution "read the docs" :smiley: ) However, this discussion might be usefull to others who have the same problem.

Perhaps it could be usefull to use this as the default behavior - although I don't know in which scenarios it is useful to use `fireOnInit: true`. And modifying default behavior in future releases might be always tricky...

**Comment by jankukacka** [comment]
I have done a second check and `dropdown` does not contain setting called `fireOnInit`. OnChange is still being fired on initialization.

**Comment by jlukic** [comment]
Are you using `1.11.5`? I backported some of the bugfixes from `2.x` channel

**Comment by jankukacka** [comment]
Yes, tested with 1.11.5.

I created a JSFiddle example to test the issue: https://jsfiddle.net/jankukacka/3Ly97y1p/

In correct case, `postback` function should not be triggered on initialization, but should be triggered after every change. Unfortunatelly, it is not possible to change the inline event declaration.

**Comment by jlukic** [comment]
Thanks for the test case this helps

**Comment by jlukic** [comment]
Fixed in `2.x`
