### ISSUE TITLE
Select dropdown generation and angularjs

### ISSUE THREAD

**Issue by mbeckenbach** [Semantic-Org/Semantic-UI#1913]
I've created a small angularjs directive that simply applies .dropdown() to a simple html select.
Works like a charm but there is a problem with angular's form validation css classes. 

When the selection changes angular adds and removes several classes to/from the select element. This happens twice. Once with the angular-animate classes and after some milliseconds again with the final classes that stay until next change.

The semantic dropdown div is not reflecting those class changes from the select element. Any idea how to solve it?

I created a plnkr to show what happens:

http://plnkr.co/edit/eYy07a?p=preview

**Comment by mbeckenbach** [comment]
I found a way to solve this issue on angular side using some 1.3 magic. It's not the best way of doing this but it works.

It can simply be solved by using the formController and a watch.
I updated the plnkr. Note that i use underscore.js to find the array index of the control inside the form.

The rest is pure angular and some jquery.

http://plnkr.co/edit/eDOej3zJ0bwQ1xyX1LDI?p=preview

**Comment by mbeckenbach** [comment]
Anyway: The semantic ui component should handle the class cloning in my opinion.

**Comment by jlukic** [comment]
Dropdowns clone classes when initializing select elements. Check out [these lines](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L203) from `setup select`. 

You might want to check out the [angular repo](https://github.com/Semantic-Org/Semantic-UI-Angular) for some advice. There are a couple team members there who may know more

**Comment by mbeckenbach** [comment]
@jlukic The problem is not in initialization. For angular the classes have have to get cloned again whenever they change on the hidden select element to get 'native-near' angular usage.

**Comment by jlukic** [comment]
This requires more knowledge of angular than i currently possess. Let me know if you reach any conclusions with your investigation and I'll update accordingly.

**Comment by mbeckenbach** [comment]
For the moment the directive that i posted is the only way i found. :-(
