### ISSUE TITLE
Table in Grid column overflows its parent column

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#1914]
See example here http://jsfiddle.net/82h1osLv/ 
You may need to narrow your page to see the overflowing table. 

I could no find any standard SUI combination of classes for table, grid, columns, rows or segment how to overcome this problem, Probably tables were not considered to be inside column of a grid.

**Comment by jlukic** [comment]
There's a simple css fix, but its outside the scope of the framework.

http://jsfiddle.net/n206jj8a/

**Comment by kvetoslavnovak** [comment]
Great, thank you. I believe css fix may be sufficient at this moment. You can close this issue and focus on more important things.

**Comment by geemang2000** [comment]
NOTE: I had to use word-break:break-all as word-wrap seems to only work if there are spaces in the long string. If you remove the spaces from your fiddle is doesn't wrap.
