### ISSUE TITLE
.dropdown.search with onChange

### ISSUE THREAD

**Issue by kbariotis** [Semantic-Org/Semantic-UI#1916]
I have a select searchable (`.dropdown.search`) box defined with `onChange` function. 

When i select an element the `onChange` function fires but the textbox inside (cause of the `search` class) remains focused. So when i click anywhere in the page the `onChange` function fires again.

This doesn't happens without the `search` class.

Any ideas? 

[Fiddle](https://jsfiddle.net/15vw7en1/4/).

Steps to reproduce:
1) Select an item from the dropdown menu. Alert pop ups. 
2) Click Ok. Input Text box is focused.
3) Click anywhere in the page. Alert pop ups again.

Thanx

**Comment by jlukic** [comment]
Can you provide a JSFiddle that shows this behavior, and a set of reproducible steps. This will help facilitate debugging.

**Comment by kbariotis** [comment]
Yeap @jlukic sorry, here [you are](https://jsfiddle.net/15vw7en1/).

Select an item from the dropdown menu. Alert pop ups. Hitting OK alert pop ups again.

Try replacing the `alert` with a `console.log`. After you select an item, input textbox is focused. If you click anywhere in the page, `onChange` will trigger again. :/

**Comment by foxlance** [comment]
Well, somebody beat me to it. Anyway, I prepared a commit to showcase the problem, but the Fiddle snippet above shows the same problem I'm experiencing.

Or, see https://github.com/foxlance/Semantic-UI/commit/7456293407d099803500d28e84077a6203237fb4

**Comment by jlukic** [comment]
Sorry about that bug, quite nasty. Fixed in `next` release.
