### ISSUE TITLE
[Search] Add Category Search To Local Search

### ISSUE THREAD

**Issue by brianlawasdf123** [Semantic-Org/Semantic-UI#1917]
The condition `result && result.length > 0` is never true because result is an object with no length property.

```
 result: function(value, results) {
            var
              result = false
            ;
            value   = value   || module.get.value();
            results = results || module.get.results();
            if(settings.type === 'category') {
              module.debug('Finding result that matches', value);
              $.each(results, function(index, category) {
                if($.isArray(category.results)) {
                  result = module.search.object(value, category.results)[0];
                  if(result && result.length > 0) {
                    return true;
                  }
                }
              });
            }
            else {
              module.debug('Finding result in results object', value);
              result = module.search.object(value, results)[0];
            }
            return result;
          },
```

Also shouldn't the return value be `false` to exit the loop?

**Comment by jlukic** [comment]
Category view local search has not been implemented.

**Comment by joaobarcia** [comment]
Is this still the case? Does this mean it is not possible to have a category search on a local object?

**Comment by Firegarden** [comment]
Agreed - why is it not possible to have a category search with a local object? Seems easy enough to me.

**Comment by megamaiku** [comment]
It's been 2 years....is this really not implemented yet?

**Comment by turkhero** [comment]
Waiting this feature

**Comment by saikrishnadeep** [comment]
I hope this will be implemented some time soon!

**Comment by ytzvan** [comment]
Any news on this ?

**Comment by saikrishnadeep** [comment]
Using a `mockResponse` does the job as a temporary fix to make a decoy to remote request and result the results as category 
**Callback:**
``js
$blah.search({
  apiSettings: {
    mockResponse: function () {
}
}
})
```

**Search settings:**

```js
$.extend($.fn.search.settings, {
  duration: 0,
  searchDelay: 0,
  cache: false,
  type: 'category',
  minCharacters: 1,
  selectFirstResult: true
})
```

**Comment by MarcelWouters** [comment]
Here a working example of category search in local objects

[https://embed.plnkr.co/UpsopAn0iWCN4cvdLAvL/](url)

**Comment by Chez-pas-qui** [comment]
@MarcelWouters, the link is disabled, do you have a code or another link ? :)

**Comment by MarcelWouters** [comment]
@chez-pas-qui try this one http://embed.plnkr.co/UpsopAn0iWCN4cvdLAvL/

**Comment by Chez-pas-qui** [comment]
I'll try it, thank you very much for helping ! :)
