### ISSUE TITLE
Build error in npm version 1.11.0

### ISSUE THREAD

**Issue by gensmann** [Semantic-Org/Semantic-UI#1918]
Hi,

I seem to get the following build error after a npm install semantic-ui:

Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    variable @selectPreInitHeight is undefined in file /code/semantic-ui/semantic/src/definitions/modules/dropdown.less line no. 351
Details:
    type: Name
    filename: /code/semantic-ui/semantic/src/definitions/modules/dropdown.less
    index: 7546
    line: 351
    callLine: NaN
    callExtract: undefined
    column: 10
    extract: select.ui.dropdown {,  height: @selectPreInitHeight;,  padding: @selectPadding;
    lineNumber: 351
    fileName: /code/semantic-ui/semantic/src/definitions/modules/dropdown.less

I don't get the same build error if i do a bower install semantic-ui, nom install and then build.

**Comment by jlukic** [comment]
Is this in the LESS repo? I'm about to patch. Looks like a variable from `next` got in somehow.

**Comment by gensmann** [comment]
This is in the standard repo (when doing: "npm install semantic-ui")

**Comment by dharma-guardian** [comment]
Had the same problem. Cleaning the npm cache via `npm cache clean` solved it for me. Seems like npm does not pull from the latest tag, but from `next`

**Comment by jlukic** [comment]
Just published a one fiesta `1.11.1`

**Comment by gensmann** [comment]
Perfect. It works now.

And BTW thanks for some really good work with semantic. Definitely one of the best and most interesting dev frameworks currently out there.

**Comment by jlukic** [comment]
You're welcome! :smiley_cat:
