### ISSUE TITLE
Faulty files: site.min.css and header.min.css

### ISSUE THREAD

**Issue by davekc** [Semantic-Org/Semantic-UI#1919]
In version 1.9.0 the files were OK :smiley:

Then in 1.11.0 and 1.11.1 **site.min.css** causes the browser to render Arial font, and **header.min.css** removes the bottom margin of headers under IE :disappointed_relieved:

The files seem messed up by compression or something.

OTOH **site.css** and **header.css** are fine...
Thanks for your good job! :+1:

**Comment by jlukic** [comment]
There's something funny in the minified output of `site.min.css`. I'll take a look

**Comment by jlukic** [comment]
It looks like this was caused by a bug in clean-css https://github.com/jakubpawlowicz/clean-css/issues/476

I'll disable restructuring for now which will fix the issue.

**Comment by jakubpawlowicz** [comment]
It's fixed in clean-css 3.1.4 so you can just make sure that's the version you use. But turning off restructuring will fix it as well.

**Comment by davekc** [comment]
Thank you guys for the fix!
