### ISSUE TITLE
[IE10+] A little suggestion...

### ISSUE THREAD

**Issue by davekc** [Semantic-Org/Semantic-UI#1921]
When using input with icons under IE10+ it may get strange; here's an idea...
```
input::-ms-clear {
	display: none; /* Prevent the 'x' to appear under IE10+ */
}
```
Of course, I may tweak it up as I wish... just a suggestion :wink:

**Comment by jlukic** [comment]
IE appears to be placing the X in legible spots for `icon input` just fine.
