### ISSUE TITLE
[input] Bug with transparent input solved with the tag (!important)

### ISSUE THREAD

**Issue by ma1793** [Semantic-Org/Semantic-UI#1924]
I have a bug with transparent input, because when I use it, the input has the normal appereance (not transparent)

I proved it, adding the tag (!important) in the three elements, and was solved the problem.

.ui.transparent.input input {
    border-color: transparent !important;
    background-color: transparent !important;
    padding: 0em !important;
}

**Comment by jlukic** [comment]
Can you create a test case to demonstrate your issue? What circumstances cause it not to receive the correct style?

**Comment by ma1793** [comment]
Well, with the version 1.3.2, the transparent input works in any place, but with the newest versions the input doesn't receive the style if is located inside a form, here is the test case:
http://jsfiddle.net/ma1793/27k6xynu/1/

**Comment by jlukic** [comment]
Thanks

**Comment by jlukic** [comment]
Fixed in `next` minor release.
