### ISSUE TITLE
bower+less?

### ISSUE THREAD

**Issue by Kroid** [Semantic-Org/Semantic-UI#1926]
Maybe, will create bower package for less repository? It is only css now.

**Comment by jlukic** [comment]
I can add a bower file to the less repository
https://github.com/Semantic-Org/Semantic-UI-LESS

But bower doesn't support install scripts like npm, and treats its package folder as a `temp/` directory, so it will clear your `theme.config` and any site themes stored there on upgrade. See POV in #1385
