### ISSUE TITLE
Bug with dropdown when visibility is toggled

### ISSUE THREAD

**Issue by joshbodine21** [Semantic-Org/Semantic-UI#1927]
If a dropdown is hidden on page load, and then is displayed via a toggle checkbox, when clicking on the dropdown, the menu items get hidden underneath any content that follows. If the dropdown is visible on page load, then there is no issue.

Here is the test case of a mock up form: http://jsfiddle.net/gf96hf5n/

**Comment by Iconoblast** [comment]
I experienced a similar issue, with dropdowns inside an accordion. Basically, `transform: translateZ(0);` (which is there to trigger 3d acceleration) messes up z-index and makes the content get hidden behind the rest of the stuff that's in flow.

At least, I think we're having a similar issue...

**Comment by jlukic** [comment]
There used to be a bug where animations with `transform` would jump `1px` when transform was removed after the animation finishes. `transform: rotateZ(0deg)` was meant to preserve `gpu` rendering which would fix the issue. 

This was several years ago now though. I'm not sure the bug still exists in latest FF/chrome. I'll take a look tomorrow.

**Comment by jlukic** [comment]
It's removed in `next`

**Comment by jlukic** [comment]
This actually seems to cause bad flickering when removed. I dont think its possible.
