### ISSUE TITLE
Enhancement: using popup on external SVG?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1928]
Hi,
I tried to test `popup` on external SVG, by using `data-title` for example, it dident worked, to work, I have to include directly the file as `<svg>` instead of using `<object data="/filesvg" type="image/svg+xml"></object>` even if the CSS (hover) works when using the `<object>`

**Comment by abdelouahabb** [comment]
Here is the code, I think it will be usefull for someone, notice that when the path is big, the popup will show far away ...
http://jsfiddle.net/3xkrx/132/

**Comment by abdelouahabb** [comment]
here is using a custom html, the idea is using the `visibility:hidden` from the beginning because it is outside the node:
https://jsfiddle.net/3xkrx/134/

**Comment by jlukic** [comment]
This seems to be working fine for me. The positions might be a little funky because the position is reported by their bounding rectangles.
https://jsfiddle.net/0mt77b63/

**Comment by abdelouahabb** [comment]
@jlukic but sadly the interractivity doesent work with `<object data="/filesvg" type="image/svg+xml">`

**Comment by abdelouahabb** [comment]
@jlukic  am sorry if  it is out of subject, but how to add `inverted` to the  popup, http://stackoverflow.com/questions/29040547/how-to-change-popup-color 

I dont see it in the docs,

**Comment by jlukic** [comment]
Inverted
https://jsfiddle.net/vx59te34/
