### ISSUE TITLE
Checkbox Component - Radio Status of "checked" is not being removed

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#1929]
I am styling the radio options base on the "checked" class applied to the selected options.  However, it seems this class is not being removed if I select another radio options.  The checkboxes does remove their "checked" class.

Thanks

**Comment by jlukic** [comment]
Please create a JSfiddle to show your issue. There is a link to fork in the readme.

Here's an example of working radios
http://jsfiddle.net/morL2ypc/

**Comment by emage** [comment]
@jlukic  looking at your jsfiddle you can also see that the "checked" status is still visible even if you select another options, so eventually all options will have the "checked":

&lt;div class=&quot;ui radio checkbox checked&quot;&gt;
&lt;div class=&quot;ui radio checkbox checked&quot;&gt;
&lt;div class=&quot;ui radio checkbox checked&quot;&gt;

**Comment by jlukic** [comment]
Thanks

**Comment by jlukic** [comment]
Fixed in `next`.
