### ISSUE TITLE
[Label] Add Coupling to Match Table Cell Padding

### ISSUE THREAD

**Issue by natdouglas** [Semantic-Org/Semantic-UI#1930]
Minor issue - when I add the ribbon label to a table row, there is a small gap between the ribbon and the table.

<table class='ui table'>
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><div class='ui blue ribbon label'>Food</div>Not Happy</td>
            <td>Friday</td>
            <td>Email</td>
        </tr>
      </tbody>
</table>

![image](https://cloud.githubusercontent.com/assets/11181248/6588720/f91b82d6-c76b-11e4-9eba-0567000f7edc.png)

This is similiar to another reported issue - #45 (https://github.com/Semantic-Org/Semantic-UI/issues/45) which is closed now.  I was able to resolve my issue with an inline style change:

<div class='ui blue ribbon label' style='left:calc(-1rem - 1.0em);'>

<table class='ui table'>
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><div class='ui blue ribbon label' style='left:calc(-1rem - 1.0em);'>Food</div>Not Happy</td>
            <td>Friday</td>
            <td>Email</td>
        </tr>
    </tbody>
</table>

![image](https://cloud.githubusercontent.com/assets/11181248/6588801/5b2aa334-c76d-11e4-9210-5bab284357d8.png)

**Comment by jlukic** [comment]
Added in `2.1`
