### ISSUE TITLE
Horizonatal scroll when using basic grid

### ISSUE THREAD

**Issue by narayanpai** [Semantic-Org/Semantic-UI#1931]
When using ui grid, horizontal scroll appears due to negative margin.

http://jsfiddle.net/fedguy/htdogsk6/3/

**Comment by jlukic** [comment]
Grids use negative margins to offset columns. I can remove them from direct descendents of `body`, but then grid contents will no longer sit flush.

I recommend using `body { overflow-x: hidden }` this is already necessary for `ui sidebar` to push page contents off stage.

**Comment by jlukic** [comment]
Fixed by default in `next`
