### ISSUE TITLE
Suggestion: Remove pushable class when sidebar is hidden.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#1933]
This will solve hard-to-debug layout problems.

**Comment by tmikaeld** [comment]
Only seems to happen on the first time, every next hide triggers.

**Comment by jlukic** [comment]
I agree there might be rooms for optimization here. I know that adding `pushable` before animations would cause 30-50ms of additional layout time in my original tests 

![image](https://dl.dropboxusercontent.com/u/2657007/pushable.jpg)

But I'm willing to entertain revisiting this.
