### ISSUE TITLE
[Dropdown] Dropdown inside vertical menu receives vertical menu child menu formatting

### ISSUE THREAD

**Issue by iamscottfreeman** [Semantic-Org/Semantic-UI#1934]
Nested Dropdown elements appear to be applying their own set of rules. This causes issues when the 'on' behaviour is set to 'hover', and animation quirks for grandchildren Dropdowns.

See the Fiddle for an example: http://jsfiddle.net/scottfreeman/y0vz71gf/

**Comment by jlukic** [comment]
http://jsfiddle.net/9htuLqdb/ 
You dont need to add `ui dropdown` to submenus of a dropdown.

The formatting however appear to be receiving sub-menu formatting on child dropdown menus. I'll take a look.

**Comment by jlukic** [comment]
Fixed in `next` along with menu rewrite.
