### ISSUE TITLE
JS Transition module is braking tests on PhantomJS 1.9.

### ISSUE THREAD

**Issue by esbanarango** [Semantic-Org/Semantic-UI#1935]
Thank you for this project!

Right now I'm using Semantic-UI on an Ember.js project but `semantic.js` is braking some of my tests. The error I'm getting is:

`'[object Object]' is not a valid argument for 'Function.prototype.apply' (evaluating 'settings')`

Which references [semantic.js#L13789](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js#L13789):

`````js
        ....
        queue: function(animation) {
          module.debug('Queueing animation of', animation);
          module.queuing = true;
          $module
            .one(animationEnd + '.queue' + eventNamespace, function() {
              module.queuing = false;
              module.repaint();
              module.animate.apply(this, settings);
            })
          ;
        },
       ....

**Comment by jlukic** [comment]
What tests is it breaking? What parameters is transition called with?

**Comment by kvetoslavnovak** [comment]
It seems like it does not know what "this" in 
" ...  module.animate.apply(this, settings); ... " 
reffers to.

**Comment by apendua** [comment]
@esbanarango Have you already tried PhantomJS 2.0?
