### ISSUE TITLE
CSS and JS payload

### ISSUE THREAD

**Issue by joetm** [Semantic-Org/Semantic-UI#1936]
The payload of Semantic UI is massive! The minified CSS is 441KB and the minified JS is 221KB.
This huge payload makes the framework unusable for anything but prototypes.

What is the recommended way to reduce the amount of components in the build and to select only the ones I need? Hack the files in src/definitions? That would greatly reduce the flexibility and advantages offered by the framework. I would have to maintain one source set per site. Adding definitions would be painful. Updating them would not be possible at all.

**Comment by jlukic** [comment]
Check out our getting started guide. Choose your components during install

![image](https://camo.githubusercontent.com/b9662e806f832c1ed8cb4c4d0e259fbcae20c222/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323635373030372f696e7374616c6c2e676966)

**Comment by joetm** [comment]
Okay, thanks for the reply.

**Comment by mjnaderi** [comment]
I have chosen used components. But after building, `semantic.min.css` is still huge.
Is there a way to remove some parts of a component and let other parts remain? For example I want to remove some variations of "form" that I have not used.

**Comment by jlukic** [comment]
There's no way to do that outside of manually editing it.
