### ISSUE TITLE
Widescreen only row.

### ISSUE THREAD

**Issue by khephiri** [Semantic-Org/Semantic-UI#1937]
Is it possible to make widescreen visible only row? I'm tried to do some different responsive rows - mobile, tablet and computer works fine, but I didn't found a way how to do widescreen only row.

**Comment by jlukic** [comment]
It doesn't currently exist. The assumption is that usually existing content needs to be re-adjusted for large screens but new content doesn't need to appear/disappear. 

I'd recommend using custom breakpoints in your css

**Comment by kvetoslavnovak** [comment]
Maybe this can help you:
DevTps: How to Make a Full Screen Landing Page (HTML & CSS) 
https://m.youtube.com/watch?v=hExwnLlj2xk
