### ISSUE TITLE
[Checkbox] incorrect cursor for disabled state.

### ISSUE THREAD

**Issue by PSyton** [Semantic-Org/Semantic-UI#1941]
See http://jsfiddle.net/pt9jusoe/

**Comment by gabormeszoly** [comment]
@PSyton your link is a default SUI Fiddle content.
-G

**Comment by PSyton** [comment]
Sorry http://jsfiddle.net/5m24e927/1/

**Comment by jlukic** [comment]
Fixed in `next`
