### ISSUE TITLE
[Form validation] Icon in input is centred in (input+validation message), but should be centered inside input only

### ISSUE THREAD

**Issue by Immelstorn** [Semantic-Org/Semantic-UI#1942]
If form has input field with icon and inline validation, when validation error is raised icon will be shifted down and became centered in (input+validation message) field.

Here is jsfiddle. https://jsfiddle.net/kw10oo37/7/
Try to type something inside input and look at lock icon.

**Comment by jlukic** [comment]
That is indeed a bug. Ill take a look

**Comment by jlukic** [comment]
Actually I take that back, you combined field with `ui input`. In general you can't combine two elements unless explicitly states in the docs. 

Nest `input` inside `field` instead:
https://jsfiddle.net/83cb2akd/

**Comment by Immelstorn** [comment]
Thanks.
