### ISSUE TITLE
Suggestion: When removing popup instances, remove html too.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#1943]
I noticed that if i use a popup on an input and then call ajax update with a popup destroy, that the HTML stays statically on the page. When destroying, we should probably also make sure the HTML is removed.

**Comment by abdelouahabb** [comment]
the idea you can use right now, is using the html as `visibility:hidden`

check this example: https://jsfiddle.net/3xkrx/135/

**Comment by jlukic** [comment]
Popup `destroy` only removes a popup if `preserve` is set to `false`

If you need to force its removal you can call `$('.foo').popup('remove popup');`

```javascript

        destroy: function() {
          module.debug('Destroying previous module');
          // remove element only if was created dynamically
          if($popup && !settings.preserve) {
            module.removePopup();
          }
          // clear all timeouts
          clearTimeout(module.hideTimer);
          clearTimeout(module.showTimer);
          // remove events
          $window.off(elementNamespace);
          $module
            .off(eventNamespace)
            .removeData(moduleNamespace)
          ;
```

**Comment by tmikaeld** [comment]
Oh, thanks you for clearing that up.

I'm sorry for being lazy, i should have read the source...
