### ISSUE TITLE
onHide/onRemove not called if another popup is activated

### ISSUE THREAD

**Issue by jwr** [Semantic-Org/Semantic-UI#1945]
I expected to be able to get a callback for when a popup is hidden or removed. But it seems that no callback function gets called if I click on another element on the page for which there is a popup.

onHide/onRemove callbacks *do* get called when I click outside of the popup.

Debugging shows that the new popup gets created and logs "Pre-existing popup found".

I use on-click popups that contain UI elements and would really like to get notified when they get destroyed. I think not calling onHide/onRemove is a bug.

**Comment by jlukic** [comment]
Please provide a test case, there is a jsfiddle link to fork in the readme that should make it easier. 

Is this different than  #1852?

**Comment by jwr** [comment]
I don't think a test case is necessary, as this seems to be no different than #1852. It seems this has already been fixed and the issue can be closed.

**Comment by jlukic** [comment]
Cool. Let me know if you still have any issues.
