### ISSUE TITLE
Semantic UI and Bootstrap at same file, can it possible?

### ISSUE THREAD

**Issue by opvini** [Semantic-Org/Semantic-UI#1946]
Hi everyone,
I want to use some components like datepicker, slider, masked input and others.
These components exists to bootstrap, and my question is: can I use it with semantic?

Sorry my english, I am from Brazil.
Thanks

**Comment by abdelouahabb** [comment]
I guess yes, since they use different `class` names

**Comment by opvini** [comment]
Cool.
I will test, but do you recommend me to do this?

Thanks

**Comment by abdelouahabb** [comment]
You have to avoid what will make confusion, like grid system, and you have to use what exist only in one framework.
