### ISSUE TITLE
Node invalid command

### ISSUE THREAD

**Issue by FurryFaust** [Semantic-Org/Semantic-UI#1947]
After running: "mkdir ~/local
echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
git clone git://github.com/joyent/node.git
cd node
./configure --prefix=~/local
make install
git clone git://github.com/isaacs/npm.git
cd npm
make install"

The last make install says that Node is an invalid command.

**Comment by kvetoslavnovak** [comment]
For me worked only the last and most recent tip ( https://gist.github.com/isaacs/579814 ):

# install node wherever.
# use sudo even, it doesn't matter
# we're telling npm to install in a different place.
 
echo prefix = ~/local >> ~/.npmrc
curl https://www.npmjs.org/install.sh | sh

**Comment by FurryFaust** [comment]
I get this:

sh: 1: Moved: not found

**Comment by jlukic** [comment]
If you have any issues on installing try googling around. I'm sure you'll find answers.

The best resource for me, was the one @kvetoslavnovak has already posted
https://gist.github.com/isaacs/579814
