### ISSUE TITLE
Label styling in inputs without enclosing container with class="ui form"

### ISSUE THREAD

**Issue by kapooostin** [Semantic-Org/Semantic-UI#1948]
I'd like to get this without being obligated to wrap ```.ui.input``` or ```.field``` in ```.ui.form``` element because ```<label>``` styling depends on this class.
![image](https://cloud.githubusercontent.com/assets/467097/6650745/c17eea46-ca33-11e4-8dfe-1898e6deffa0.png)

Would it break any guidelines set up for the framework to isolate fields from parent ```.ui.form``` class?

**Comment by jlukic** [comment]
If you prefer, you can. Input will not get labels in any future releases.

**Comment by kapooostin** [comment]
You mean ```ui labeled input``` will be gone?
