### ISSUE TITLE
right floated or left floated any content

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1949]
I have the usecase where I'd like to 'right floated' a div (with content in it).  Sematic-UI already has this for most types. 

I'm basically copying the following style and changing the selectors. 
```
.ui.dropdown > .text > [class*="right floated"],
.ui.dropdown .menu .item > [class*="right floated"] {
  float: right !important;
  margin-right: 0em !important;
  margin-left: 1em !important;
}
```
I think it be a useful feature to have floated support for any div our of the box.  E.g. ui right floated

**Comment by jlukic** [comment]
No free floating helper classes in Semantic UI. I think these things should be done in CSS and not in class names, unless they are specifically defined in the context of an element.
