### ISSUE TITLE
public website Kitchen sink bug

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1950]
http://semantic-ui.com/kitchen-sink.html

The 'Modules' section on the right of the page is blank. I'm assuming this should be set of links to jump to the different module sections.

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-Docs/commit/ae5a8d9abc74b4544e23870753f5fcfed5e55c1c
