### ISSUE TITLE
[Checkbox] Input selector selects all nested inputs

### ISSUE THREAD

**Issue by MartijnThomas** [Semantic-Org/Semantic-UI#1954]
I'm trying to combine an inline dropdown and radio buttons in a form. This is the grouped fields, radio buttons part of the form (the form element including the `ui form` classes are present.

All looks normal and works fine, until you select on of the dropdown inline items, after that you are not able to pick between the radio options. 

It does not matter if the inline dropdown part is within the label element or outside of it.

```html
<div class="grouped fields">
	<label for="subscription">Subscription</label>
	<div class="field">
		<div class="ui radio checkbox checked">
			<input type="radio" name="subscription" checked="" value="pay-as-you-go">
			<label>
				<div class="header">Pay as you go</div>
				<div class="description">Pay per transaction</div>
			</label>
		</div>
		<div class="ui radio checkbox">
			<input type="radio" name="subscription" value="monthly">
			<label>
				<div class="header">Montly</div>
				<div class="description">sell 
					<div class="ui inline dropdown" tabindex="-1">
						<input type="hidden" name="books_per_month" value="50">
						<div class="text">max. 50 items per month</div>
						<i class="dropdown icon"></i>
						<div class="menu" tabindex="-1">
							<div class="item active selected" data-text="max. 50 items per month" data-value="50">
								max. 50 items per month
							</div>
						<div class="item" data-text="max 100 items per month" data-value="100">
								max 100 items per month
							</div>
						</div>
					</div> at once.<br>
				</div>
			</label>
		</div>
	</div>
</div>
```

I'm using jQuery 2.1.3, Semantic 1.11.4 and both the Semantic-UI dropdown and checkbox options are enabled:

```js
$('.ui.dropdown').dropdown();
$('.ui.checkbox').checkbox();
```

Is this a bug or did I do something wrong?

**Comment by jlukic** [comment]
Please create a JSFiddle to reproduce your issue when presenting a bug (per readme instructions) It gets very frustrating not just having to fix bugs but also handle pruning everyones bug reports as well.

http://jsfiddle.net/8u4th08g/

**Comment by jlukic** [comment]
This was an issue with the nested dropdown input affecting the radio input selector. Fixed in `next`

**Comment by MartijnThomas** [comment]
@jlukic My bad for not creating a JSFiddle, I tried to be as explicit as I could, but simply forgot to include a fiddle (I even created one for my own to test it :( ).

Anyway wsome that you fixed it!
