### ISSUE TITLE
Default value for dropdown

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1958]
Sorry another dropdown question. 

Is a hidden input (value) the only way to statically set the default value of a dropdown (without using the API that is)?

**Comment by jlukic** [comment]
Default text is considered whatever the value is on page load.
Placeholder text is "default text" that displays prompt text on page load.  You can set placeholder text by using a `<select>` with a blank value, or by adding `default text` to the dropdown on load.

In combination with #1957, default values are stored in metadata as whatever the `text()` and input `value` are on page load. See [this bit of code](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L1023)
