### ISSUE TITLE
Grid column height

### ISSUE THREAD

**Issue by bhnedo** [Semantic-Org/Semantic-UI#1959]
I would like to make the grid columns to grow in height until the boundaries of the viewport. The following fiddle https://jsfiddle.net/uw9op8sc/1/ illustrates what I want to achieve, but can't find the way in semantic to do it. The purple column where pointing menu is placed is taking the height of the menu + paddings. I can't make it to grow 100% in height. I tried by setting the heights of menu, body, column to 100% , but with no effect. How can I do it?

Thanks

**Comment by jlukic** [comment]
This is not the place to ask for help. Try stackoverflow or our gitter chat.

**Comment by jlukic** [comment]
Since you asked , here's an example loosely based on what you want to accomplish. http://jsfiddle.net/ea04tkwo/

**Comment by bhnedo** [comment]
Thanks Jack. That was helpful.

**Comment by 2ne** [comment]
@jlukic Thank you for you jsfiddle, I did not know about the 'padded' class on 'ui grid' elements. This class should be utilised in the [login examples](https://semantic-ui.com/examples/login.html) as the body is not 100% without using the 'padded' class.
