### ISSUE TITLE
primaryColor and secondaryColor changes not reflected on gulp watch output

### ISSUE THREAD

**Issue by jcano** [Semantic-Org/Semantic-UI#1960]
I've been trying to change the color palette on `site/globals/site.variables`, monitoring changes with `gulp watch`. Independently of the changes I made (changing the color variables hex values or the values of `primaryColor` and `secondaryColor`), the site would look exactly the same. When building with `gulp build` the site shows the new colors.

**Comment by jlukic** [comment]
I guess `site.variables` should rebuild all files since all files inherit from them.

**Comment by jlukic** [comment]
Site.variables will now rebuild all files in `next`

**Comment by jcano** [comment]
Great! Sorry I couldn't help more with this one, I know nothing of Gulp
