### ISSUE TITLE
Bookish style has inverted sizing variables

### ISSUE THREAD

**Issue by jcano** [Semantic-Org/Semantic-UI#1962]
The bookish style defines the following variables for sizing:

    /* Sizing */
    @tiny: 1.5em;
    @small: 1.33em;
    @medium: 1.33em;
    @large: 1em;
    @huge: 0.9em;

when it should be:

    /* Sizing */
    @huge: 1.5em;
    @large: 1.33em;
    @medium: 1.33em;
    @small: 1em;
    @tiny: 0.9em;

**Comment by jlukic** [comment]
Fixed in `next`
