### ISSUE TITLE
Simple dropdown triggered from outside of vertical menu

### ISSUE THREAD

**Issue by nojhamster** [Semantic-Org/Semantic-UI#1963]
In a vertical menu with simple dropdown items, hidden submenus have a slight height (due to 1px border I think). So they appear when the cursor is next to the menu. (and browsing a submenu can make the other submenus appear and replace the one we are browsing)

I'm not sure to be clear, anyway here's a test case : http://jsfiddle.net/xfhua248/6/

**Comment by jlukic** [comment]
I've tested this in the `next` release, and this appears to no longer be an issue. `menu` has been rewritten for next release.
