### ISSUE TITLE
Horizontal Divider not displaying properly in IE11

### ISSUE THREAD

**Issue by dmalik** [Semantic-Org/Semantic-UI#1964]
If you visit http://semantic-ui.com/elements/divider.html in IE11, the horizontal divider HR on the left hand side does not show up. 
![hrie](https://cloud.githubusercontent.com/assets/869108/6670148/88aea390-cbd3-11e4-94c7-da40e93bbd34.jpg)

**Comment by jlukic** [comment]
Fixed in `next`
