### ISSUE TITLE
Dropdown - Dropdown menu item width issues in IE

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#1966]
In IE9 and IE10 (don't have IE11) the dropdown menu item's width are shorter then the initial selection box/input. 

 For example, in the semantic documentation country selection example - all the countries option only goes about 80% of the width -- same with the gender example.

Firefox and Chrome expands the full width making it nice!

**Comment by geemang2000** [comment]
Which version of windows are you using?

**Comment by gabormeszoly** [comment]
Test cases from my daughter Win IE11 :)

Figure 1 with original style
![dd_ie11_figure_01](https://cloud.githubusercontent.com/assets/1769854/6742609/62db9086-ce91-11e4-889f-db0e9ea22fab.jpg)

Figure 2 with disable min-width calc
![dd_ie11_figure_02](https://cloud.githubusercontent.com/assets/1769854/6742637/a354105c-ce91-11e4-8275-f5c37f8481c4.jpg)

**Comment by jlukic** [comment]
I think this calc rule is getting precalculated incorrectly by LESS
[input](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.less#L400)
[output](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/dropdown.css#L386)

**Comment by gabormeszoly** [comment]
Hi Jack,
Here is a solution: http://codepen.io/gabormeszoly/pen/embEXX

**Comment by jlukic** [comment]
Tagged the wrong issue but fix here 683b5aa5fcb14d181a140093aa925c629f4cc127
