### ISSUE TITLE
public website Win7 IE9 does not render well

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1967]
Unfortunately I need to support IE9+  

1) IE 9+ (Browser prefix only)  - what does prefix only mean? 

2) Attached is a screenshot of the public website. 
(FYI - https://www.modern.ie/en-us ) is a good site to get different IE versions (virtualbox images) and test IE compat.

![screen shot 2015-03-16 at 9 22 12 pm](https://cloud.githubusercontent.com/assets/392233/6680268/c658e378-cc22-11e4-90c2-bcf27b9c42a3.png)

**Comment by joshbodine21** [comment]
IE9 is not a supported browser. See the following for a workaround (basically, load css files individually)

**Comment by jlukic** [comment]
IE9 is not a supported browser. Looking forward to the day when IE10 will be on the same list.
