### ISSUE TITLE
non-detachable modals don't scroll properly

### ISSUE THREAD

**Issue by topmindinc** [Semantic-Org/Semantic-UI#1968]
If you use  {detachable: false} to create a long modal such that it is scrolling, the modal disappears behind the dimmer.

**Comment by jlukic** [comment]
After years of fixing bugs for people that don't bother to read the readme, from now on I will be automatically closing any threads that do not contain a test case with a set of reproducible steps to replicate a bug.

You can only say "read the readme" so many thousand times before you realize that you have to start changing policies.

**Comment by topmindinc** [comment]
Sorry about that! Here is a test case:

- Go to http://semantic-ui.com/modules/modal.html#/examples
- Open up Chrome console. Run `$('.long.test.modal').modal({detachable: false}).modal('show')`

We need to use {detachable: false} because we're using Semantic-UI with ReactJS, and detaching the element from DOM breaks React. I spent literally about 3 hours trying to fix it but couldn't, and I thought someone might have a way to fix it. Thanks for your amazing work on Semantic UI!

**Comment by jlukic** [comment]
I've fixed in `next` undetachable `scrolling modal` for the most common scenarios, like inside of a page with a `sidebar` and direct descendent of `body` or sidebar `pusher`.  However if your modal is inside a content container with a z-index you may still have issues.

**Comment by jlukic** [comment]
Example
http://jsfiddle.net/6oony3xu/

**Comment by topmindinc** [comment]
It works great, thank you!!
