### ISSUE TITLE
Creating inverted dimmer modals.

### ISSUE THREAD

**Issue by jenil27** [Semantic-Org/Semantic-UI#1969]
Hey guys,

What would be a good way to create inverted dimmer modals? Or will have I have use some javascript hack?

**Comment by jlukic** [comment]
Dimmers can be supplied a `variation` setting through modal

http://jsfiddle.net/0ou28yn2/

```javascript
$('.ui.modal')
  .modal({
    dimmerSettings: {
    variation: 'inverted'
    }
  })
  .modal('show')
;
```

**Comment by jlukic** [comment]
I've added `inverted` setting in `2.0` as a useful shortcut

**Comment by kcahir** [comment]
The shortcut works for me the first time, but fails to apply the `inverted` class when I close and reopen the modal.

https://jsfiddle.net/cch3sdkz/

```
$('#openModal').click(function () {
    $('.ui.modal').modal({
      inverted: true
      }).modal('show')
})
;
```

**Comment by jlukic** [comment]
You're re-initializing it on every click
https://jsfiddle.net/r9crtn17/

**Comment by avalanche1** [comment]
Thank God! I've spent good 3 hours solving that...
