### ISSUE TITLE
Dynamic semantic modal

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#1971]
Hi, how do dynamic modal like angular js:
ng-repeat inside without breaking it?

**Comment by jlukic** [comment]
This forum is for bug reports and issues. Please see readme. Angular issues are in a separate repo under semantic-org.

**Comment by anil1712** [comment]
Hi, @TeodorKolev, Did you get any solution for dynamic modal issue. I want to do the same in angular2.
