### ISSUE TITLE
Google font import fails (404) for some UA

### ISSUE THREAD

**Issue by loris** [Semantic-Org/Semantic-UI#1972]
Getting a lot of 404 requests lately in my server logs on the following path:

`/assets/css/https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin`

Looks like the way the fonts are imported (`@import 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin';`) might be at fault on some devices, any ideas?

**Comment by jlukic** [comment]
If you have more evidence let me know. Not too much I can do practically with this, but I'll keep my eye out.

**Comment by wordempire** [comment]
@loris, do you know any specific UA for which this happens?

**Comment by loris** [comment]
Actually, it looks kinda unrelated to UA, here is the list of the latest 10 UA getting an error:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B440 Safari/600.1.4
Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4
Mozilla/5.0 (Linux; Android 4.2.2; GT-I9205 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; fr-fr; SAMSUNG SM-G901F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.6 Chrome/28.0.1500.94 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 5.0.1; Nexus 5 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 2.3.3; fr-fr; GT-I9100 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 4.2.2;fr-fr; STARTRAIL4 Build/BQ_ZTEV1.0.0B07) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.3; fr-fr; Ultym5 Build/Ultym5) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 625) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
```

Not sure it has anything to do mobile vs desktop neither, my website being targeted for mobile users specifically.

**Comment by Dreampie** [comment]
how to use local fonts？

**Comment by Einkoro** [comment]
@loris Sounds like the asset path is being prefixed to the import URL. Do see the incorrect path in the CSS itself then? Are you building your own or pulling in the default css components?

**Comment by loris** [comment]
The path looks correct in the CSS (the 404 only occurs for a little fraction of requests). I am directly using the `node_modules/semantic-ui/dist/semantic.css` file in my build flow, the resulting import statement is 
`@import 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin';`

Could it be something related to enterprise firewall or something? maybe a rule forbidding importing CSS over HTTPS when main site is HTTP?

**Comment by jlukic** [comment]
Perhaps try changing to the relative protocol
``//fonts.etc`

There were about 5 issues on this originally, we settled on `https` working across the most amount of environments

**Comment by loris** [comment]
Thanks @jlukic 

I changed the `@googleProtocol` variable from `https://` to `//` in `site.variables` file a few hours ago and haven’t seen any 404 since.
