### ISSUE TITLE
Responsive layout for menus

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#1973]
I'm wondering if it's available to stack sub-menus when screen resolution goes tiny.
One example is http://semantic-ui.com/collections/menu.html#secondary-menu that goes multi-line when screen resolution is not enouth wide to show completely.

Is it possible to allow SUI to stack sub-menu (menu class children of ui menu) in order to stack all the sub elements into a dropdown menu.
What do you think about?

**Comment by jlukic** [comment]
I've tried several times to do this, but what ends up happening is the rules are too damn long. It basically means having to duplicate all the `vertical menu` rules which is another 10+kb (and layer of complexity).

In the next release i've added a simple `stackable` variation, with the caveat (and note in the docs) that it will not work correctly with complicated menu structures.

**Comment by Einkoro** [comment]
@jlukic What about simplifying it? If it was to require javascript the class could be swapped to save on some media queries similar to whats done here: http://foundation.zurb.com/docs/components/topbar.html
