### ISSUE TITLE
Checkbox behavior "can check" is wrong

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#1974]
Hello.
When using the checkbox behavior "can check" it fires an error saying "The method you called is not defined". I looked in the code of the module and I found out that the code implemented for that behavior is ["can change"](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/checkbox.js#L171) and ["can uncheck"](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/checkbox.js#L174), but neither of them are listed [in the docs](http://semantic-ui.com/modules/checkbox.html#/usage).

**Comment by jlukic** [comment]
Sorry the docs were off on that. Adjusted to `can change` and `can uncheck` in next.
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/688d21afc1eb26ba6e53d900a401c3cd317631e7
