### ISSUE TITLE
New card view like google plus ?

### ISSUE THREAD

**Issue by fuhaiq** [Semantic-Org/Semantic-UI#1975]
Is there any plan for the team to introduce a new card view like google plus ?
![screenshot from 2015-03-18 12 59 36](https://cloud.githubusercontent.com/assets/5200755/6703040/5ff0bf3a-cd70-11e4-97d6-b12b4fdba574.png)

**Comment by foxzool** [comment]
Pinterest like or waterfall ?

**Comment by fuhaiq** [comment]
@foxzool I don't know the difference between them. They look like the same for me : D

**Comment by jlukic** [comment]
If you're talking about styling, please try using variables and theming. A lot of this can be done there. 

Default theme will always stay true to SUI's style, not emulating others.
