### ISSUE TITLE
Dropdown on a right item menu, cover the item

### ISSUE THREAD

**Issue by francodgstn** [Semantic-Org/Semantic-UI#1977]
When dropdown is used on a right item menu, it cover the item. I tried with position:relative but nothing changes.

```
<div class="ui right  pointing  dropdown link item">
  <i class="dropdown icon"></i>
  <span class="text">User Menu</span>
  <div class="menu">
    <a href="#" class="item">
      <i class="home icon"></i>Profile
    </a>
  </div>
</div>
```

**Comment by jlukic** [comment]
See readme

**Comment by francodgstn** [comment]
Sorry, I didn't read how to submit issue.
This is the jsfiddle link for the issue, if you click on the menu item the dropdown cover the parent menu item.
http://jsfiddle.net/bxms2Ldo/2/
