### ISSUE TITLE
Can i specify borderless table?

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#1980]
Looks like not ....

**Comment by jlukic** [comment]
Very basic

**Comment by hrstoyanov** [comment]
Yes, i knew about it, but it still draws lines under the rows,
unfortunately.

/Hristo Stoyanov

**Comment by jlukic** [comment]
Modify the theme

**Comment by jordmax12** [comment]
Three word question, literally lol'd at Starbucks. Regardless, the OP has a point. Will we be able to have borderless tr's in the future?

**Comment by vinayakkulkarni** [comment]
Hack, that works at the moment: 

Using `ui very basic table` class and this custom css:

`.ui.table tr td {
    border-top: 0px !important;
}`

**Comment by alernerdev** [comment]
any updates on this?  Its been several years.  thanks

**Comment by mthrsj** [comment]
Got stuck in the same problem here. Instead of modifying the `td`, the solution was changing the `th` bottom border.

```css
.ui.table tr th {
  border-bottom: 0px !important;
}
```
