### ISSUE TITLE
Language selection dropdown not scrollable

### ISSUE THREAD

**Issue by goldnead** [Semantic-Org/Semantic-UI#1981]
The language selection dropdown menu list of each site on http://semantic-ui.com is too long and therefore not fully visible when opened. A scrollable dropdown menu would be proper with so many translations.

**Comment by jlukic** [comment]
Agreed

**Comment by jlukic** [comment]
I've added this in using a searchable dropdown menu
![image](https://dl.dropboxusercontent.com/u/2657007/language.jpg)
