### ISSUE TITLE
[Sidebar] - Sidebar with Context Stays Fixed

### ISSUE THREAD

**Issue by Goldfinch** [Semantic-Org/Semantic-UI#1983]
I need fixed sidebar menu when is open, use context inside body, when content page is large.
How it is best implemented? and is it possible?

Here's what I mean (sidebar not fixed)
http://jsfiddle.net/rLfd0a6x/

**Comment by jlukic** [comment]
Sidebar inside `context` will scroll with page content, its a known limitation. 

I can imagine a PR that would fix this, it would have to calculate offset of container on init for sidebar, and use position fixed. 

You can mimic this in css if you know the left offset, here's an example
http://jsfiddle.net/52qusntn/

**Comment by Goldfinch** [comment]
left offset is static.. possible to do position fixed relative to the main container (.main)? which has a fixed length and aligned by center? or the only way out is to count the left offset of the current permit?

thanks, jlukic

**Comment by jlukic** [comment]
The thing about position fixed is that its always relative to `body` or `transform` context (except in IE which doesnt create a new context on transform [fun!]) 

I wish it was easier to do in css with positioning, the reality is you'll need some javascript to attach it. If you check out `sticky` it operates under this premise for fixed content. Having to position it relative to `body` using the offset from the `context`

**Comment by Goldfinch** [comment]
anyway, thanks for answers
