### ISSUE TITLE
Recalculate DOM information associated with Visibility automatically or manually

### ISSUE THREAD

**Issue by theyaserfox** [Semantic-Org/Semantic-UI#1984]
Visibility calculations about DOM, don't recalculate automatically each time DOM elements changes. I tried to at least run recaluation manually by invoking $(element).visibility('refresh') but nothing changed, I also wonder what is $(element).visibility('refresh') job ?

**Comment by jlukic** [comment]
Element constants like width/height are only refreshed
* If the `context` `resize` event fires
* If `observeChanges: true` it will recalculate automatically on DOM mutation inside the initialized element
* If user manually calls `$('.foo').visibility('refresh');`

**Comment by theyaserfox** [comment]
Somehow these three cases don't work with meteor's publish/subscribe methodology, once new content loaded into `$('.foo')`, it's visibility constant `height` stays the same, despite running `$('.foo').height()` shows the updated value. This problem don't happen with sync cases where I call sync function adds content to the DOM, but with async case where meteor subscription adds content after polling it from server this issue happens.

**Comment by jlukic** [comment]
Let me know if you make any more headway
