### ISSUE TITLE
Making body "pushable" breaks scrollTop value on iOS devices

### ISSUE THREAD

**Issue by apendua** [Semantic-Org/Semantic-UI#1985]
When I use `sidebar` module, it automatically adds `pushable` class to my `body` tag
```css
.pushable {
  height: 100%;
  overflow-x: hidden;
  padding: 0em !important;
}
```
Frankly, even though we only disable horizontal scrolling, the `document.body.scrollTop` will always return `0` with this setup on iOS devices. This is problematic because on the other hand (see #1979) we have this iOS fix:
```css
/*
  iOS incorrectly sizes document when content
  is presented outside of view with 2Dtranslate
*/

html.ios {
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}
```
which makes `window.pageYOffset` always return 0.

As a result, it seems there's no way to access the current scroll position.

**Comment by apendua** [comment]
I created a simple project demonstrating the problem:

https://github.com/apendua/semantic-issue-1985

The demo is available here:

http://semantic-issue-1985.meteor.com

![zrzut ekranu 2015-03-19 o 11 41 03](https://cloud.githubusercontent.com/assets/1971195/6728794/df4f0f18-ce2c-11e4-8fcc-3b965edf735a.png)

To reproduce open it on an iOS device / emulator and note that the scroll position does not change until you switch off `pushable` class on the `body` element. To make sure it's not related to the possible lack of support for scrolling events, I am just probing the values 10 times per second.

I have observed that
```css
body.pushable {
  overflow-x: initial;
}
```
solves the problem, but of course the content will overflow horizontally producing unwanted scrollbars when the sidebar is active. My suggestion is to use `overflow-x: hidden` only when the scrollbar is active. This should solve all the issues I described above.

Moreover, on a real device there's also a performance issue caused by the same thing. It manifests itself on fixed positioned elements. Namely, when `overflow-x` is `hidden` on `body`, the elements fail to update their position smoothly when the user scrolls the view. They would only update after the scrolling is done, which produces a really ugly visual artifacts. This is also visible on your very own page here

http://learnsemantic.com/guide/expert.html

Looks how the top menu is reacting to scroll events on a mobile device.

**Comment by apendua** [comment]
Just as a side note, `overflow-x: hidden` set on the `body` tag breaks some `jquery-ui` plugins as well, e.g. `scrollable`, even in a totally "normal" browsers like Chrome for example.

**Comment by apendua** [comment]
For the sake of completeness, I have tried the workaround described above on a real device, namely dynamically changing the `overflow-x` value. Turns out that this is causing ugly "black flash" artifact and also it resets the `scrollTop` to 0. On the other hand, at least in my use-case, it looks like setting `body`'s overflow to `hidden` is not really required for mobile device. For some reason, nothing is really overflowing even if the sidebar is in the "active" state. But this may be caused by disabling the user scaling.

**Comment by jlukic** [comment]
I've noticed your meteor test case is down. Could you reupload? Or add as a jsfiddle?

**Comment by apendua** [comment]
@jlukic Thanks for heads up. I've redeployed the project. Should work now.

**Comment by jlukic** [comment]
I've noticed [slideout](https://github.com/Mango/slideout) adds `overflow: hidden` on `body` and `html` but only does so on visible sidebar. This would only affect grabbing `scrollTop` when the sidebar is open, which might be a viable compromise. 

I considered this earlier but disregarded it because adjusting `overflow` triggers `layout` in browsers which is expensive, which is the last thing you want right before a demanding animation. But maybe its worth reconsidering.

**Comment by apendua** [comment]
@jlukic I've also observed the performance drop caused by adjusting `overflow` dynamically. I don't really think this is a valid solution in our case.

What do you think about allowing users to use additional container with permanent `overflow-x: hidden`?

**Comment by jlukic** [comment]
I really wanted to solve this issue, and got lucky. 

```css
html, body {
  height: initial;
}
```

Will for some unknown reason cause `scrollTop` to be reported correctly on `document` or `body` even when html receives `overflow: hidden`. This is a much more adequate solve than emulating scroll events, or adjusting overflow dynamically as previously discussed. 

@apendua Thanks for your patience on this.
