### ISSUE TITLE
Checkbox right floated style support

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#1986]
It'd be great if there was right floated style out of the box for checkbox
```
        <div class="ui toggle checkbox right floated">
            <input id="active$index" type="checkbox" name="active" ng-model="item.active"/>
            <label for="active$index">Send this header</label>
        </div>
```

I created my own style:
```
.ui.toggle.checkbox[class*="right floated"] {
    float: right !important;
    margin-right: 0em !important;
    margin-left: 1em !important;
}
```

**Comment by jlukic** [comment]
I have no plans to add left/right float to arbitrary elements unless its a very common use case.

**Comment by hbthegreat** [comment]
I have also been using this functionality a lot in recent projects. It is easy enough to implement yourself as a user anyway. I wouldn't be opposed to seeing it more widely across the board though.

**Comment by afogelberg** [comment]
I would say that right float for a toggle checkbox is a very common use case. It is especially common in settings menus.

**Comment by Riddlerat** [comment]
I also need to have the checkbox on the right, I would be super helpful to have a left right option. It possible to move it using styling, we are trying to be as minimal with our style additions as possible as we build our new frontend.

**Comment by lubber-de** [comment]
The community fork https://fomantic-ui.com just merged a PR to support `right aligned` checkboxes for upcoming v2.8.8
https://github.com/fomantic/Fomantic-UI/pull/1670
![image](https://user-images.githubusercontent.com/18379884/92658000-18319280-f2f6-11ea-8727-330dab0a9bde.png)
