### ISSUE TITLE
search selection dropdown calls onChange on blur

### ISSUE THREAD

**Issue by jwr** [Semantic-Org/Semantic-UI#1987]
I've been getting duplicate onChange callbacks from dropdown and managed to trace it back to at least one reproducible test case:

https://jsfiddle.net/0da7ru98/8/

To reproduce:

1. Click on the resulting dropdown.
2. Choose "Male"
3. Click anywhere else to defocus (e.g. in the HTML area).
4. Observe how a second "onchange event Male" message gets logged in the console.

I would expect to get only one onChange callback, when the contents has actually been changed.

**Comment by jlukic** [comment]
This is a duplicate and has been fixed in `next` #1916
