### ISSUE TITLE
Required field indicators for grouped field labels should be on the group label

### ISSUE THREAD

**Issue by palmsey** [Semantic-Org/Semantic-UI#1988]
Demo: https://jsfiddle.net/3fd9wnkk/1/

The required field indicator (*) seems like it should go on the group label ("Would you like us to import your current settings?") rather than the individual radio button labels.

The markup in the fiddle is pulled from the docs, just added the "required" class to the grouped fields div.

**Comment by gabormeszoly** [comment]
SUI fiddle here: http://jsfiddle.net/am0pgkqp/

**Comment by palmsey** [comment]
Sorry, I forked that the first time, not sure what happened. 

Updated - http://jsfiddle.net/pktvcs1c/3/

**Comment by jlukic** [comment]
I guess `require fields` should be each when `:not(.grouped)`

**Comment by palmsey** [comment]
That's the solution I came up with too - I wasn't sure if I was missing some other way this was supposed to be set up though.

**Comment by jlukic** [comment]
No, it was just an oversight. I'll fix

**Comment by jlukic** [comment]
Added PR, closing issue
