### ISSUE TITLE
`font: inherit;` on select hides options

### ISSUE THREAD

**Issue by RobinJ1995** [Semantic-Org/Semantic-UI#1991]
I just spent the last 1.5 hours attempting to find out why the options in my select element weren't getting added. Turns out they were there the whole time, but Semantic UI hid them from me. When I disable the `font: inherit;` line they show up fine.

![screenshot_2015-03-20_10-48-09](https://cloud.githubusercontent.com/assets/3089559/6749269/d66e92b6-ceee-11e4-80fa-2c5358d396d4.png)
![screenshot_2015-03-20_10-48-21](https://cloud.githubusercontent.com/assets/3089559/6749271/d7867b8c-ceee-11e4-86d9-28ccf20efa9a.png)

This seems to be related to `font-size`. This solution also works;
`font-size: 18px;`

**Comment by RobinJ1995** [comment]
Ok, seems that this happened because I forgot to put the whole thing in a `.column`... Not sure if this means this is still a bug or just a PEBCAK. I'll leave you to decide.

**Comment by jlukic** [comment]
There are only a few `ui` items that still have to use a whitespace fix for `inline-block` content. Unfortunately `column` need it, so direct children of `grid` that are not in a wrapper have `font-size: 0;`

**Comment by jlukic** [comment]
Unfortunately `ui grid column` are `inline-block` which need a [whitespace fix](http://davidwalsh.name/remove-whitespace-inline-block) using `font-size: 0em;`. This means any child of `grid` **must be** in a column. I know this is frustrating to debug so apologies.

The bright side is as more elements get converted to `flex-box`, for example menu, this will be a non-issue.
