### ISSUE TITLE
[UI] Video Player

### ISSUE THREAD

**Issue by challet** [Semantic-Org/Semantic-UI#1994]
Hey guys, great work you're doing here! I've been using Semantic since the beta for my own projects, and I probably have some PRs to make once they've been cleaned ;)

I'd like to offer my help for the video module you're building though. I built this a few years ago http://mooplay.challet.eu/, then it kind of fell by the wayside (as MooTools went the same way). disclosure : I would still chose it over jQuery if I had a choice :D

What I was aiming for with that project was exactly what I feel Semantic is aiming for now - abstracting behaviour to one single (and simple) definition. It might not be completely obvious when you read my documentation, but it would be really great if you could have a look at it, give the implementation a go and let me know if you think it matches with what you're working on.
If you'd like my help, I'd be happy to :
- adapt the JS code and make it a semantic module. 
- provide .less definitions for the set of controls elements. edit: I don't even know if this is needed, since it would all be about using Semantic elements (buttons, progress, etc.) and add them a "video controling/monitoring behavior"
- extend them to work with the unified API you're working on 
- do domething with the subtitles feature. I already made it work standalone over a flash video (when HTML5 video is not available). edit : maybe not part of Semantic, you tell me

I'm not completely up to date with the current state of the video module, so feel free to give me a few pointers if you'd like to accept my offer to work on the project!

**Comment by challet** [comment]
Hi jlukic, would you allow me to fork the *video* branch and run some tests ? is the one labeled *next* ?

**Comment by jlukic** [comment]
Hi, it might make sense to separate this into two separate modules. Which I was thinking about doing. `embed` being the current component, which is specifically for embedding external videos from Youtube/Vimeo, and `video` a component like you are describing which works with `html5` video.

Do you think this makes sense? Also are you comfortable writing the module using the same module format used elsewhere? I can help you get started and provide documentation for getting started with the format.

**Comment by challet** [comment]
Hi, I'm going to try this as an independant module, whathever the final name will be. I'll try to stick on what is seen in other modules. By any chance, is there a yeoman generator (or equivalent) for semantic module ?

**Comment by jlukic** [comment]
I've added an online repo where I'll try to keep notes on SUI module format
https://github.com/Semantic-Org/Module-Examples

You can see the annotated source of current version here
http://semantic-org.github.io/Module-Examples/docs/module.html

**Comment by challet** [comment]
Hi @jlukic thanks for links, I've made a basic integration from it for the play/pause button https://github.com/challet/Semantic-UI/commit/aa3b21a3fa07098333edca46e5395a241cdecdbb#diff-60e295af5f7fe24b87a004491016c9c8
As a prototype it looks promising, but I'm not completly confident about the SUI integration. If you could have a look, that would be greatly appreciated.

**Comment by jlukic** [comment]
Can you create a pull request against the `next` branch where i can start evaluating this?

I've decided that the current video component will be changed to `embed` since this component was only specifically designed to work with embedded third party content. This also would allow me to include generic responsive embed containers, and possible future integration with Google Maps, Instagram and other common embeds.

**Comment by challet** [comment]
Sure, i'm adding a few more things and let you know through a PR. Current status demo can be seen here http://html5video.challet.eu/examples/video-player.html I've used ``htmlvideo`` as a module name for now, it can be changed easily.

**Comment by challet** [comment]
PR #2228

**Comment by brackmayhall** [comment]
@challet what is the status of the html5 video pull request for semantic-ui. it looks to have stopped moving as of jul 21 2015

**Comment by SrPatinhas** [comment]
@challet @jlukic any news on this?

**Comment by challet** [comment]
@brackmayhall @SrPatinhas sorry I haven't made new things on this for a while. I'd say it is usable ad for now, but might not be in line with SUI standards, and lacks of examples and documentations.
If you could advise me on what aspect should be priotized, I'll get back at it during the next weeks.
