### ISSUE TITLE
Avoid mixing piled with stacked

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#1996]
Hi,
here is what i get if i mix between them, i know, that doesent make sense, but maybe this will be helpful
![sans titre](https://cloud.githubusercontent.com/assets/2527234/6760791/71141b08-cf4c-11e4-9777-39a235996df7.jpg)

**Comment by jlukic** [comment]
Anything under "types" in a definition are mutually exclusive.

**Comment by abdelouahabb** [comment]
ah, thank you :)
