### ISSUE TITLE
Small Padding Modal Content  Variation

### ISSUE THREAD

**Issue by RyanThompson** [Semantic-Org/Semantic-UI#1997]
There needs to be a "small" padding variation for the modal content divs of 1rem.

Ill need to read up on contributing to this project otherwise I'd contribute this little tidbit.

This would make using components like vertical menus / secondary menus in a modal align nicer.

**Comment by jlukic** [comment]
I recommend adjusting this variable in your site theme
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/modal.variables#L41

**Comment by RyanThompson** [comment]
Yaaa that would change default behavior though which should have padding. 

Perfect example:

![screen shot 2015-03-27 at 1 36 28 pm](https://cloud.githubusercontent.com/assets/1099967/6874571/4f376636-d486-11e4-99e8-3e21f35f9941.png)

How perfect is that!? But it requires a small padding. And I would preferably not have to custom style anything at this point.
