### ISSUE TITLE
Custom Templates for Search

### ISSUE THREAD

**Issue by jwd2a** [Semantic-Org/Semantic-UI#1998]
It'd be great to be able to use custom templates for the search module. It might work well to spec a template like this: 
~~~
$(".ui.search").search({
   ...
   template: "myTemplate"
});

<div class="template">
   <h1>{{title}}</h1>
</div>
~~~

If this already exists and I missed it, apologies. Didn't see anything like this in the docs, tho.

**Comment by jlukic** [comment]
You can modify search templates by altering `$.fn.search.settings.templates`. 

[They are](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L965) currently simple JS concatenated strings, but could also work with compiled handlebar templates, although i haven't tested

If you want to add your own template just specify a new template name as `type` on init.

For example
```javascript
$.fn.search.settings.templates.special = function(response) {
 // do something with response
};
$('.ui.search')
  .search({
    type: 'special'
  })
;
```

You can also specify on init, but you'd have to do this each time.
```javascript
$('.ui.search')
  .search({
    type: 'special'
    templates: {
      special: function(response){
      
      }
  })
;
```

**Comment by jwd2a** [comment]
Awesome, thanks for that info. I'll go that route. Should I leave this open so it makes its way into the docs at some point?

**Comment by jlukic** [comment]
Yes

**Comment by jlukic** [comment]
Added to `2.0` docs with explanation

**Comment by zykadelic** [comment]
Should not these settings be found on [the settings page](http://semantic-ui.com/modules/search.html#/settings)?

**Comment by stephanngamedev** [comment]
I tried to use custom template (using items). But I can't control dropdown size. How to solve this?
![screenshot 2017-11-12 16 15 19](https://user-images.githubusercontent.com/3025661/32702354-bc0bf036-c7c4-11e7-99ae-ee1675180e07.png)
