### ISSUE TITLE
[Validation] Don't Attach Form Submit Behavior to Elements That Can Submit

### ISSUE THREAD

**Issue by digaev** [Semantic-Org/Semantic-UI#1999]
Hello,

I have a form with a multi buttons which have a same class and name but different values:

    <form class="ui form" method="post">
        <div class="required field">
            <label>Body</label>
            <textarea name="body" autofocus="true" required="required"></textarea>
        </div>
        
        <button class="ui submit button" type="submit" name="commit" value="post">Post</button>
        <button class="ui submit button" type="submit" name="commit" value="preview">Preview</button>
        <button class="ui submit button" type="submit" name="commit" value="draft">Draft</button>
        
        <div class="ui error message"></div>
    </form>

After I applying the form rules:

    $('.form').form({
        body: {
            identifier: 'body',
            rules: [{
                type: 'empty',
                prompt: 'Body is empty!'
            }]
        }
    });

Validation working fine, but button's value not posted. The problem is that I can't determine which button was clicked when I handling the request.

http://jsfiddle.net/xz497muh/

**Comment by jlukic** [comment]
Submit actions are attached to `ui submit button` automatically with javascript, this will overwrite  `<button type="submit">` native submit, and the button value will not submit with the form. 

Try changing it to `ui button` instead of `ui submit button`

**Comment by digaev** [comment]
Changing class to `ui button` resolves the problem with sending value, but validation stops work. It there any way to validate form too? Thanks.

Here is my workaround:

    $('button[type="submit"]').click(function(e) {
        return $('.form').form('validate form');
    });

http://jsfiddle.net/tkksfxvj/2/

**Comment by jlukic** [comment]
Removing submit should not cause any issues with validation not firing
http://jsfiddle.net/1w5rhtcg/

using input `required` will trigger native browser validation which will prevent the form from submitting (as well as native UI for showing error messages)

**Comment by digaev** [comment]
Got it. Thanks.

**Comment by jlukic** [comment]
Added in `next`, will not attach to `type=[submit]`
