### ISSUE TITLE
Fulltext Search uncorrect

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2000]
![image](https://cloud.githubusercontent.com/assets/5719547/6767647/b27aab6c-d03b-11e4-93bd-6035b5f87b07.jpg)

**Comment by jlukic** [comment]
This is correct. Full text search uses a [fuzzy searching algorithm](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L464)

https://github.com/bevacqua/fuzzysearch

**Comment by kvetoslavnovak** [comment]
OK, it is really no such an issue.

**Comment by sheyooo** [comment]
Is there a behavior where the result is just like the first and last result of that image search result? FuzzySearch is too extreme for my case and only matching from the beginning of the results is also not enough for me. Thank you.. looking forward to hearing from you.
Perhaps a way to override the default search?
