### ISSUE TITLE
Windows npm setup doesn't seem to install everything required.

### ISSUE THREAD

**Issue by Nathan-022** [Semantic-Org/Semantic-UI#2002]
Following the npm instructions on the 'Download' page (i.e. 'npm install semantic-ui') seems to download everything to the project folder specified, but when I then try to follow the getting started instructions:

'#install semantic dependencies'
npm install

it fails because there is no package.json. Am I missing something? Is this not how the node package is supposed to be used? If so, more detail should be added to the docs to make it clear what the setup procedure is.

(Note: I worked around this by just downloading the git repository, which did include the necessary files, but still feel this isn't an ideal setup experience and the documentation could be clearer)

**Comment by jlukic** [comment]
The getting started guide needs an update.

The whole procedure if installing from npm is just

```bash
npm install semantic-ui
// answer install questions
cd /install-folder
gulp build 
# or
gulp watch
```

**Comment by krainboltgreene** [comment]
I'm definitely having similar issues: https://gist.github.com/krainboltgreene/837ed6451fdab954c370 (Two things: Hang on after install, needs some library?)

**Comment by jlukic** [comment]
I've updated to `node 12.x` and NPM `2.11.x` and can now replicate this issue. 

Was not having issues with earlier NPM versions.

**Comment by jlukic** [comment]
I think there's an isssue with install script hanging from non zero exit conditions in later NPM. I'm working on it now.

**Comment by jlukic** [comment]
#1816 #2086 Closing as dupe
