### ISSUE TITLE
Material Theme - Same Color of Button and Text

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2003]
![button_material_theme](https://cloud.githubusercontent.com/assets/5719547/6769063/fff0da60-d08b-11e4-9131-81dde104adfd.jpg)

**Comment by kvetoslavnovak** [comment]
I have just  found according to this http://semantic-ui.com/globals/site.html that maybe I did not compile Material theme correctly, There is a global site variable for this theme that have to be changed to material too, am I right?

Anyway it would be very nice to have theme.config file variables overview for each theme in respect of particular relevant Gobal, Elements, Collections, Modules and Views variables. Toady we have to look for each one in the Semantic website whether it is or not listed in Themes dropdown button.

**Comment by zuher83** [comment]
same probleme with default. 
Beacause in button.less color is set:

.ui.green.button {
  background-color: @green;
  color: @greenTextColor;
.........

.ui.pink.button {
  background-color: @pink;
  color: @pinkTextColor;
.........

into your site folder change button.overrides:
.ui.green.button {
  background-color: @green;
  color: fff;
.........

**Comment by kvetoslavnovak** [comment]
I have recompiled my css file to be fully material themed including site material variable. 
Unfortunatelly the colors are really mismatched. Button colors does not respect site material theme, colors of buttons and their text are the same :-(

**Comment by jlukic** [comment]
There are technically 6 levels of inheritance.

Default site.variables, default element.variables
Packaged theme site.variables, packaged theme element.variables
Site theme site.variables, site theme element.variables

To use a `material` button theme you need to set both `site` and `button` to `material` in `theme.config`

**Comment by kvetoslavnovak** [comment]
This us exactly what I have done. But the resulting fully material css (material site as well as material theme overrides)  has bugs. 
- buttons colors do not respect site colors and instead have default colors
- the text color of buttons is the same as the color of button instead of white

Have a look at "fully materiale" css file:
https://gist.github.com/anonymous/f692d09deecb8ec0d5fd#file-semantic-ui-material-theme

**Comment by jlukic** [comment]
I'm not sure what you're doing differently, but I've confirmed locally colors etc are showing up correctly.

1) Installled via npm
2) Changed `theme.config`  like so

```less
/* Global */
@site       : 'material';
@reset      : 'default';

/* Elements */
@button     : 'material';
@container  : 'default';
@divider    : 'default';
@flag       : 'default';
@header     : 'default';
@icon       : 'default';
@image      : 'default';
@input      : 'default';
@label      : 'default';
@list       : 'default';
@loader     : 'default';
@rail       : 'default';
@reveal     : 'default';
@segment    : 'default';
@step       : 'default';
```

All colors for buttons appear as material

**Comment by kvetoslavnovak** [comment]
Strange, this is exactly what I am doing, but you can see in the resulting css that colors are not ok.

**Comment by kvetoslavnovak** [comment]
Does it mean that global site colors do not rebuild colors for all other elements that have colors (buttons, tables, segments etc.)?
