### ISSUE TITLE
rtl build and repeated elements.

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#2005]
Hi,
When building `rtl` version, this is a good idea to include `html{direction:rtl}`, because with a normal `rtl` build, if someone uses counting elements, they will be used from left to right, and not from right to left. here is an example:

1- with the `rtl` build, but without `html{direction:rtl}`
![normal-rtl](https://cloud.githubusercontent.com/assets/2527234/6772341/f8b76dca-d0fb-11e4-8394-f7bf4efb168f.jpg)

1- with the `rtl` build, but with `html{direction:rtl}`

![with-rtl](https://cloud.githubusercontent.com/assets/2527234/6772343/01e1a88e-d0fc-11e4-961f-4e531b301e15.jpg)

NB: because it is animating so i took screenshots at different moments, thie is why the background is different :dancers:

**Comment by jlukic** [comment]
I encourage you to check out our RTL build it uses [rtlcss](https://github.com/MohammadYounes/rtlcss) created by a contributor to transform floats, etc

**Comment by abdelouahabb** [comment]
adding `direction:rtl` for `html` did the trick, the rest, semantic ui took care of it :)
