### ISSUE TITLE
Fluid input actions broken in IE10 on Semantic's homepage for the new version 

### ISSUE THREAD

**Issue by eddywu0** [Semantic-Org/Semantic-UI#2006]
Fluid input with action is broken in IE10. The button extends outside all columns.

IE10.
V: 10.0.9200.17229

Screenshot taken from Semantic's demo page. 

![broke-fluid-input-action](https://cloud.githubusercontent.com/assets/413791/6787011/fd97d4dc-d14c-11e4-9627-209af4501759.png)

**Comment by jlukic** [comment]
Fixed in next `patch` 7a5654d9682f0f0836e547d986207efd3f4e995a
