### ISSUE TITLE
Text blurry in v1.11.5 on Chrome/Windows

### ISSUE THREAD

**Issue by pkaminski** [Semantic-Org/Semantic-UI#2007]
I'm trying to migrate from Semantic UI v0.18 to v1.11.5 and noticed that when I use certain elements all text on the page becomes blurry in Chrome v41 on Windows 7.  I believe it's caused by font smoothing changing from subpixel anti-aliased to plain old anti-aliased, which looks fairly terrible.  Compare:

![image](https://cloud.githubusercontent.com/assets/1646896/6791396/e341b912-d16b-11e4-9bd8-4cd01d7030ad.png)
![image](https://cloud.githubusercontent.com/assets/1646896/6791382/d04d11ee-d16b-11e4-9c5e-03905acaf938.png)

Digging deeper, it seems that some of the new styles cause Chrome to shift to a hardware-accelerated rendering context for the whole page, which doesn't support subpixel anti-aliasing.  I've identified two offenders so far but there's probably more:  `will-change: opacity` (and perhaps other values too), and the `ui loader` spinning animation (likely due to the `transform: rotate`).  Once an element causes the anti-aliasing mode to switch, it won't switch back until the element is removed even if the style changes.

I also noticed that there's now a `font-smoothing: antialiased` style on `body` by default.  This is probably a bad idea too, but Chrome appears to be ignoring this directive so it's not a factor at the moment.

Until/unless Chrome fixes this behavior, it might be better to take out all `will-change` styles and revert to animated GIFs for the loaders.

**Comment by jlukic** [comment]
Anything thats GPU accelerated, which includes hinting with `will-change` or css animations will render  differently but this is to be expected. Its actually gotten much better in the last couple years with modern GPUs and recent drivers, but it can still be blurry on older systems. This however shouldnt affect an entire page, just elements that, are animating, use hinting for css transitions, or use `transform` for positioning (like pointer arrows).

**Comment by pkaminski** [comment]
While my system is not new, it's hardly very old either:  Windows 7 (latest patches) with a GTX 670 (last month's driver).  I think that's pretty typical, or even a little bit ahead of, the average user.  And I can confirm that this issue affects the entire page and is persistent even though the offending styles are limited to the dimmer/loader (perhaps due to their non-static positioning?).

And yeah, ultimately I think this is down to a buggy Chrome renderer, but it's hardly practical to ask users to go flipping browser flags to use my site.  My contention is that this issue is sufficiently widespread that it's worth removing the offending styles until Chrome (or video drivers, or whatever) catch up and can offer a non-blurry experience to all users, especially since doing so will not significantly degrade the experience for others.

**Comment by jlukic** [comment]
If its related to having `body { font-smoothing: anti-aliased; }` I would be willing to remove, but I'm not sure we can do anything about css properties that trigger GPU rendering, which is actually a benefit for rendering.

**Comment by pkaminski** [comment]
AFAICT `font-smoothing` is not actually a thing and `font-smooth` is no longer in CSS3.  `-webkit-font-smoothing` exists but [shouldn't be used](http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/) anyway.  In any case, it doesn't affect this issue.

Have you measured the impact of the CSS properties that trigger GPU rendering, both in terms of performance and percentage of people affect by the blurriness issue?  If the former is small and the latter large, as I suspect, you might want to reconsider.  If not, is it at least possible to have a custom build / configuration option that disables the offending styles, for developers who don't want any of their users to get a blurry web site?  Thanks.

**Comment by jlukic** [comment]
GPU [is faster](http://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome) for layout because [compositing layers are awesome](http://www.html5rocks.com/en/tutorials/speed/layers/). Only some UI elements trigger compositing, and mostly just ones that are animating. 

I will re-open this issue if there's a specific test-case which can reproduce cross-platform display issues caused by `will-change`, `transform` that are avoidable.

**Comment by pkaminski** [comment]
Well, I don't know what it would take to convince you, but here's a trivial test case: https://jsfiddle.net/28up07sp/.  Note that the text area is separate from the dimmer, but gets affected by the dimmer being toggled on/off anyway.  It also doesn't matter whether the dimmer is active or not, so it's not just while animating.  I asked a few friends to try it out and the results are consistent (and hence likely independent of video card and driver):

On Windows:  Firefox and IE remain sharp all the time, Chrome gets blurry when the dimmer is on.
On OS X:  Chrome is always blurry, and Safari is blurry when the dimmer is off (!).

In my testing, these issues are avoidable if you get rid of `will-change` and rotation/scale `transform` (translation is OK).  What's the point of having smoother transitions / animations if the whole page gets blurry when you use them in some browsers?

**Comment by dreadiscool** [comment]
Can confirm this is an issue for me on Chrome as well

**Comment by elijh** [comment]
Can confirm this is an issue for me on Chromium under Linux

**Comment by Melmoth-the-Wanderer** [comment]
This is still the case in new Chrome. Please take a look at this [article about will-change property and weird Chrome behavior](http://greensock.com/will-change).

**Comment by kunokdev** [comment]
This is a huge issue IMO. Whole layout is blurry on Chrome. (Both Linux and Windows of higher resolutions) See here: [#3433](https://github.com/Semantic-Org/Semantic-UI/issues/3433#issuecomment-259411578) Meanwhile on IE and Firefox it works fine.
