### ISSUE TITLE
Modal not playing nice with other elements.

### ISSUE THREAD

**Issue by ThatsIT** [Semantic-Org/Semantic-UI#2008]
I had a modal that seemed to flash and jump when open and closing. I traced this down to it doing so when in same page as a kendo listview. http://demos.telerik.com/aspnet-mvc/listview/index 
After open and closing modal, fixed positioned elements get al jittery when scrolling. 
Thanks

**Comment by jlukic** [comment]
I can't speak for the interactions with a 3rd party lib without a test case.
