### ISSUE TITLE
How to set modal callback arguments

### ISSUE THREAD

**Issue by jie** [Semantic-Org/Semantic-UI#2010]
My code like this:

$('.ui.modal')
        .modal({
            onShow: function() {
                  console.log($(this));
            }
        }).modal('attach events', '.delete_button')

I use modal as delete data confirm dialog, so I need send some kind of index or id to modal's onShow (or other callback) callback as argument. Any idea is welcome, THX.

**Comment by jlukic** [comment]
Works just fine
http://jsfiddle.net/43gvg95t/

Please post a JSFiddle when demonstrating code so we can work with it easier, there's a link to fork in readme.
