### ISSUE TITLE
JavaScripts animations not working fluently

### ISSUE THREAD

**Issue by tahaeghtesad** [Semantic-Org/Semantic-UI#2011]
Due to using lots of Javascripts instead of CSS3, pages are heavy, and take a lot of time to animate.
Another thing, could you please include the fonts you are using in project? It's too slow to download them every time from Google servers.

**Comment by jlukic** [comment]
The library uses css animations not javascript animations. Please read the documentation on transitions.

You can disable google font imports with a single variable in `site.variables`
