### ISSUE TITLE
Search module always debugs to console

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2012]
Hi.

The Search module always debugs to console although the `debug` value defaults to `false` and even when it is set to `false` in the initialization code. Setting `verbose` to `false` doesn't work either (its default value is true).

**Comment by jlukic** [comment]
Test case, fork, jsfiddle, readme

**Comment by miniskulljob** [comment]
I can't reproduce the case in JSFiddle, it works fine when the source is a local object, it only happens when it has to go through the API. Even when you set `debug: false` in the `apiSettings` option, it debugs to console.
```javascript
$(".ui.search").search({
    apiSettings: {
        debug: false
    },
    debug: false
});
```
With that code, it always shows console debug messages like `>API: 0ms...`

**Comment by jlukic** [comment]
I've set search to pass along its debug settings to API. Chrome/FF will add XHR requests to console  by default, but now you won't receive the API debug.
