### ISSUE TITLE
hide message example doesent work

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#2013]
I thought it was a problem from my local build, but even here, it doesent work: http://semantic-ui.com/collections/message.html

NB: it works when applying the effect out of the doc.

**Comment by jlukic** [comment]
I probably should have the dismisable block function like the example.

**Comment by abdelouahabb** [comment]
ah, :+1:

**Comment by jlukic** [comment]
Fixed this

**Comment by abdelouahabb** [comment]
Ah, thank you ^_^
