### ISSUE TITLE
Custom build - don't generate minified files

### ISSUE THREAD

**Issue by startswithaj** [Semantic-Org/Semantic-UI#2014]
Is there a way using the gulp build system to specify the the .min.js and .min.css files not be also generated or be able to specify each as separate build tasks? It doesn't seem like there is support for this and the default is the generate both sets of files.

`build     = require('./semantic/tasks/build-uncompressed')`

`build     = require('./semantic/tasks/build-compress')`

**Comment by jlukic** [comment]
Currently build is one task for both. I could see this as separate tasks.
