### ISSUE TITLE
please reference a valid license uri

### ISSUE THREAD

**Issue by t1** [Semantic-Org/Semantic-UI#2015]
I'd like to add semantic-ui to [web-jars](http://www.webjars.org), but it fails, because the referenced license is bogous: `License 'http://semantic-ui.mit-license.org/' does not exist`. Could you please reference a valid license uri? Maybe `http://opensource.org/licenses/MIT`

**Comment by jlukic** [comment]
But it does exist! 
http://semantic-ui.mit-license.org/

**Comment by t1** [comment]
sorry... seems to be a bug in web-jars, then.
