### ISSUE TITLE
Search module "get result" isn't working as it should

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2017]
Hi.

In a Search field with items with similar values, when you select an item and try to get the `result` object via the `get result` behavior, it returns an object that's not correspondig to the selected item.

Example: http://jsfiddle.net/miniskulljob/87sjs2tn/

In the example, when you search for "1234" and select the item "1234" or "12345", the `result` it returns is always "123456", the first item in the list.

Edit: changed the JSFiddle with one forked from the one in the README, sorry.

**Comment by jlukic** [comment]
Wow, really sorry about that one. `onSelect` was incorrectly using the same startsWith regexp as the search which was matching incorrectly.
