### ISSUE TITLE
Dropdown with numbers

### ISSUE THREAD

**Issue by RadekD** [Semantic-Org/Semantic-UI#2020]
https://jsfiddle.net/30ws5rdf/5/

TypeError error occurs when using the onChange event with numeric values

**Comment by jlukic** [comment]
It's a mistake [on this line](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L881)

I'll fix tomorrow. Sorry about that 
![egg](http://renegadetribune.com/wp-content/uploads/2014/05/egg-on-face-egg.jpg)

**Comment by jlukic** [comment]
Fixed in `2.x`
