### ISSUE TITLE
[Card] Flexbox Displays Incorrectly in IE

### ISSUE THREAD

**Issue by karltud123** [Semantic-Org/Semantic-UI#2021]
there is a bug on cards on IE10, installed not emulate...

How to fix this? Thank you very much.

You can also open the semantic-ui site in IE 10 and the bug also exist.

This is my first time posting here so, thank you for welcoming me.

**Comment by geemang2000** [comment]
@karltud123 would you mind give more detail on the issue? Screenshot too?

**Comment by gabormeszoly** [comment]
i think is the same flex problem such as here #2006 i check this asap with IE

**Comment by gabormeszoly** [comment]
Card in IE11
![card-ie11](https://cloud.githubusercontent.com/assets/1769854/6848726/3b0a0c2a-d3cf-11e4-8c67-a8d4dea763d6.jpg)

**Comment by jlukic** [comment]
Can you post that jsfiddle

**Comment by gabormeszoly** [comment]
sure: http://jsfiddle.net/gabormeszoly/dpmnsLwb/

**Comment by gabormeszoly** [comment]
I also made an example without SUI: http://jsfiddle.net/gabormeszoly/6f2m8qjL/
This does not work in IE11. The bad news is: https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview#tabs

**Comment by jlukic** [comment]
Oh boy
https://github.com/Modernizr/Modernizr/issues/1301

**Comment by jlukic** [comment]
I've gone ahead and disabled flex for the time being in IE.  If you need an immediate fix use this css.

```
/* Disable flex in IE */
@media all and (-ms-high-contrast:none) {
  .ui.cards > .card,
  .ui.card {
    display: block;
  }
}
```

**Comment by jlukic** [comment]
If anyone finds a better solve I will be willing to re-open.

**Comment by karltud123** [comment]
thank you very much. nice support.
