### ISSUE TITLE
Headers/search don't work on dropdowns on a floating menu.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#2022]
You can even see it in the docs:
http://semantic-ui.com/modules/dropdown.html#pointing

Search inputs just become a thin line, i have tried everything i could conjure up but i can't get it to show.

**Comment by jlukic** [comment]
I should have backported this from `2.x` but this will be fixed in that release.

**Comment by jlukic** [comment]
Fixed in next `patch`
