### ISSUE TITLE
Color columns not working outside of rows

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#2023]
It was working some versions ago, but with the current version colored columns aren't working when outside of a row.

You can see that in this fiddle http://jsfiddle.net/trigoesrodrigo/a8xjkuzn/2/ 
It also happens on the website http://semantic-ui.com/collections/grid.html#row-and-column-backgrounds

**Comment by jlukic** [comment]
This is already fixed in `2.x`. Part of the bug fixes that have yet to be backported.
http://jsfiddle.net/j5xc4vjy/
