### ISSUE TITLE
[Table] Add Vertical Alignment

### ISSUE THREAD

**Issue by RyanThompson** [Semantic-Org/Semantic-UI#2025]
Would be great. To change vertical alignment to top instead of the default middle. Just a nice variation detail.

**Comment by jlukic** [comment]
This is in `2.0`

**Comment by RyanThompson** [comment]
How would I go about using 2.0? I didn't see the dev branch but would love to put it in our product.

**Comment by jlukic** [comment]
2.0 dev is being done in `next` branch. It's around  [170 commits](https://github.com/Semantic-Org/Semantic-UI/compare/master...next) ahead of current released version, but still needs some tinkering.
