### ISSUE TITLE
Nav Bar not working with latest CSS (1.11.5)

### ISSUE THREAD

**Issue by AlvaroAV** [Semantic-Org/Semantic-UI#2028]
Hi

I'm trying to use a collapsible Nav Bar following this examples:

- [Nav Bar Top](http://ehkoo.github.io/semantic-ui-examples/navbar/)
- [Nav Bar Static Top](http://ehkoo.github.io/semantic-ui-examples/navbar-static-top/)

My issue is with the new CSS my Nav Bar is showing like this when the display width is for mobile:

![navbar](https://cloud.githubusercontent.com/assets/5870043/6866432/747f9c1e-d478-11e4-977a-e839e12cb506.png)

The problem is not the margin-top, you can see that half of the nav bar is hidden, the issue is the right menu button. It should appear at the right of the navbar but it doesn't show anywhere, I checked and it seems is not rendering it. I followed the same structure on the examples but can make this work.

Is there any information to use the Collapsible Nav Bar with the new CSS ?

**Comment by jlukic** [comment]
The examples are from pre 1.0 release.

Closed until test case
