### ISSUE TITLE
My Report ISSUES, 1. Dropdown Menu, 2. Labeled

### ISSUE THREAD

**Issue by SunDi3yansyah** [Semantic-Org/Semantic-UI#2029]
##### 1. Dropdown Menu
Not showing arrow on top, dropdown pointing

![screenshot from 2015-03-28 02 28 12](https://cloud.githubusercontent.com/assets/3952281/6875609/b53698b4-d4f2-11e4-9d76-8525788d6a56.png)

##### 2. Labeled
right to use flex instead of flex-glow, maybe

![screenshot from 2015-03-28 02 31 15](https://cloud.githubusercontent.com/assets/3952281/6875634/f5246cf8-d4f2-11e4-93b4-0d25826eb39b.png)

I'm using Semantic UI - 1.11.6, OS Ubuntu 14.04

**Comment by jlukic** [comment]
Could you create a test case. 

w/r/t labels I think this is from incorrect default `flex-basis` value from 2009 syntax, perhaps just needs: `flex: 0 0 auto`

**Comment by SunDi3yansyah** [comment]
please check my demo page https://libscode.com
username: __stevie__
password: __secure__
arrows on the user panel does not appear

thanks before @jlukic :dancer:

**Comment by jlukic** [comment]
I'm not sure where i'm looking exactly for the bug you're referring to.

What's easiest for me is if you fork the JSfiddle in the readme, it will include Semantic UI already, and just paste the html and css.

**Comment by SunDi3yansyah** [comment]
you try to look at the code that I have prepared here
https://gist.github.com/SunDi3yansyah/002aeac2319534fa7c27
sorry I do not use JSfiddle, because I do not want to take the JS and CSS one by one

I ask is
why on the drop down arrow pointing not produce at the top, like this
![screenshot from 2015-04-06 03 07 38](https://cloud.githubusercontent.com/assets/3952281/6998360/2556d208-dc0a-11e4-8759-e47791e9a941.png)

thanks before :+1:

**Comment by jlukic** [comment]
Closed until stand alone online test case

**Comment by SunDi3yansyah** [comment]
sorry if I re-open this issue and make you tired, I've tried it here
http://jsfiddle.net/SunDi3yansyah/m31ncn23/
why on the drop down arrow pointing not produce at the top, like this
![screenshot from 2015-04-06 03 07 38](https://cloud.githubusercontent.com/assets/3952281/6998360/2556d208-dc0a-11e4-8759-e47791e9a941.png)
is it really like that? or not to be part of the menu?

**Comment by jlukic** [comment]
This is fixed in `2.0` 
http://jsfiddle.net/xmq90kvL/

**Comment by SunDi3yansyah** [comment]
Oke thanks
