### ISSUE TITLE
RTL Website

### ISSUE THREAD

**Issue by Kalmuraee** [Semantic-Org/Semantic-UI#2032]
Hello
While translating official arabic Semantic-UI website . iv'e noticed it isn't RTL 
Also isn't there a way to add an RTL switcher to switch the layout of the front end to make it as RTL ?

**Comment by jlukic** [comment]
Apologies about that. Its a bit difficult for me to maintain docs for the RTL version side by side because it uses a different version of SUI, and requires me adjusting other page styles to support rtl. 

I can at least have the body switch to `direction: rtl;` on load as a quick fix as I continue to look for a more complete solution.

**Comment by Kalmuraee** [comment]
‏Can we have a type of switch to switch the layout as a feature for semantic UI?                                                                                                                                     ‏                                                                                                                                                                                                                From: Jack Lukic‎Sent: Saturday, 28 March 2015 11:09 PMTo: Semantic-Org/Semantic-UIReply To: Semantic-Org/Semantic-UICc: KalmuraeeSubject: Re: [Semantic-UI] RTL Website (#2032)Apologies about that. Its a bit difficult for me to maintain docs for the RTL version side by side because it uses a different version of SUI, and requires me adjusting other page styles to support rtl. 

I can at least have the body switch to direction: rtl; on load as a quick fix as I continue to look for a more complete solution.

—Reply to this email directly or view it on GitHub.
