### ISSUE TITLE
How to validate an UI Modal.

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#2035]
How do I make validation when it comes to two modals (http://semantic-ui.com/modules/modal.html#/examples , the example `$('.coupled.modal')` ), It doesent get validates using browser validators, so how to do it with Semantic UI validator?

Here is the SO question: http://stackoverflow.com/questions/29319451/validate-a-form-when-using-modal

**Comment by jlukic** [comment]
This is not a forum for asking *how to* questions. Please use our gitter chat or stackoverflow.

**Comment by abdelouahabb** [comment]
sorry, because i thought it was kind of bug, since it doesent listen to the browser validation.

**Comment by jlukic** [comment]
If you are submitting a bug please submit a JSFiddle test case and steps to reproduce the behavior.

**Comment by abdelouahabb** [comment]
this dident worked here, i dont know, but it works on my machine: http://jsfiddle.net/rduvhn8u/19/

And the validation I did was trick: is to separate the two `modal` by sending the second one using ajax on the response, but sadly then, to close the window, the user must click somewhere else, and i wished to do that on client side...
