### ISSUE TITLE
changing theme

### ISSUE THREAD

**Issue by BenevidesLecontes** [Semantic-Org/Semantic-UI#2037]
I've tried so many times change my theme to material, but i had this error on gulp build
Plumber found unhandled error:
 Error in plugin 'gulp-less'

My output on terminal:
[07:33:55] Starting 'build'...
Building Semantic
[gulp] Created: dist/components/site.js
[gulp] Created: dist/components/site.min.js
[gulp] Created: dist/components/form.js
[gulp] Created: dist/components/form.min.js
[gulp] Created: dist/components/form.js
[gulp] Created: dist/components/accordion.js
[gulp] Created: dist/components/form.min.js
[gulp] Created: dist/components/checkbox.js
[gulp] Created: dist/components/accordion.min.js
[gulp] Created: dist/components/dimmer.js
[gulp] Created: dist/components/checkbox.min.js
[gulp] Created: dist/components/dropdown.js
[gulp] Created: dist/components/dimmer.min.js
[gulp] Created: dist/components/reset.css
[gulp] Created: dist/components/reset.min.css
[gulp] Created: dist/components/modal.js
[gulp] Created: dist/components/dropdown.min.js
[gulp] Created: dist/components/nag.js
[gulp] Created: dist/components/modal.min.js
[gulp] Created: dist/components/nag.min.js
[gulp] Created: dist/components/popup.js
[gulp] Created: dist/components/popup.min.js
[gulp] Created: dist/components/progress.js
[gulp] Created: dist/components/rating.js
[gulp] Created: dist/components/progress.min.js
[gulp] Created: dist/components/rating.min.js
[gulp] Created: dist/components/search.js
[gulp] Created: dist/components/shape.js
[gulp] Created: dist/components/search.min.js
[gulp] Created: dist/components/site.css
[gulp] Created: dist/components/site.min.css
[gulp] Created: dist/components/sidebar.js
[gulp] Created: dist/components/shape.min.js
[gulp] Created: dist/components/sticky.js
[gulp] Created: dist/components/sidebar.min.js
[gulp] Created: dist/components/sticky.min.js
[gulp] Created: dist/components/tab.js
[gulp] Created: dist/components/tab.min.js
[gulp] Created: dist/components/transition.js
[gulp] Created: dist/components/transition.min.js
[gulp] Created: dist/components/video.js
[gulp] Created: dist/components/video.min.js
[gulp] Created: dist/components/api.js
[gulp] Created: dist/components/button.css
[gulp] Created: dist/components/button.min.css
[gulp] Created: dist/components/state.js
[gulp] Created: dist/components/api.min.js
[gulp] Created: dist/components/state.min.js
[gulp] Created: dist/components/visibility.js
[gulp] Created: dist/components/visibility.min.js
[07:33:58] Starting 'package compressed js'...
[07:33:58] Starting 'package uncompressed js'...
[07:33:59] Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    'themes//material/elements/divider.variables' wasn't found. Tried - /Users/chissanga/Projecto dogão/Semantic-UI-1.11.6/src/themes/material/elements/divider.variables,themes/material/elements/divider.variables in file /Users/chissanga/Projecto dogão/Semantic-UI-1.11.6/src/theme.less line no. 19
Details:
    type: File
    filename: /Users/chissanga/Projecto dogão/Semantic-UI-1.11.6/src/theme.less
    index: 420
    line: 19
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: @import "@{themesFolder}/@{site}/globals/site.variables";,@import "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";,
    lineNumber: 19
    fileName: /Users/chissanga/Projecto dogão/Semantic-UI-1.11.6/src/theme.less
[gulp] Created: dist/semantic.js
[07:34:01] Finished 'package uncompressed js' after 2.07 s
[gulp] Created: dist/semantic.min.js
[07:34:01] Finished 'package compressed js' after 2.07 s

**Comment by jhliberty** [comment]
When submitting an issue you should be more thorough in your report. At the very least it would be beneficial to include your theme.config. 

My guess is you tried to set all of your theme to material when in reality it only includes a smaller subset. Look in these folders on your machine and make sure your theme.config doesn't contain any material themeing options you don't have available.

![screenshot](https://cloud.githubusercontent.com/assets/449321/6897538/040df1a8-d6ba-11e4-85c6-f5fd9bbf520e.png)

**Comment by jlukic** [comment]
There isn't a material theme for dividers. I've only taken the time to create example themes for `button` and `site`.
