### ISSUE TITLE
Error install for gulp

### ISSUE THREAD

**Issue by Galeups** [Semantic-Org/Semantic-UI#2038]
Hi, please help for installing.

1. Install Node.js
2. Install global gulp :  npm -install -g gulp
3. unzip Semantic-UI-1.11.6.zip to D:\projects\semantic
4. go to folder in command line node.js:  cd /d D:\projects\semantic
5. run: npm install

and have this error:
D:\projects\semantic>npm install
npm WARN package.json Dependency 'gulp-git' exists in both dependencies and devDependencies, using 'gulp-git@^1.1.0' from dependencies
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/derekslife/wrench-js.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/derekslife/wrench-js.git) undefined
npm ERR! git clone git://github.com/derekslife/wrench-js.git undefined
npm ERR! git clone git://github.com/derekslife/wrench-js.git undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\semantic\npm-debug.log

D:\projects\semantic>

Thanks!

**Comment by jlukic** [comment]
Ah, it looks like since we added a Git endpoint for [one of our packages](https://github.com/Semantic-Org/Semantic-UI/blob/master/package.json#L78), you will need to have `git` installed to grab it.

https://help.github.com/articles/set-up-git/

**Comment by Galeups** [comment]
Thank you, very much!!!
I started to use  http://git-scm.com/   and  it worked ))

Thanks! )

**Comment by jlukic** [comment]
Glad it worked
