### ISSUE TITLE
The keyword 'package' is reserved (215:36)

### ISSUE THREAD

**Issue by esbanarango** [Semantic-Org/Semantic-UI#2040]
Hello and thank you for this project.

Right now I'm using version `1.11.6` on my Ember app (with ember-cli) and just got this error:

````bash
File: bower_components/semantic-ui/tasks/admin/components/create
The keyword 'package' is reserved (215:36)
`````
which makes reference to this __var__ name: [create.js#L215](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/components/create.js#L215).

So, should be possible to use a different name for that var?

Thank you again.

**Comment by jlukic** [comment]
It shouldnt even load admin tasks unless you have `admin: true` in `semantic.json`. hmm 

no trouble to change though

**Comment by jlukic** [comment]
This is in `2.0`

**Comment by esbanarango** [comment]
Thanks @jlukic ! :+1:
