### ISSUE TITLE
Change events to be based on module and a selector

### ISSUE THREAD

**Issue by aaronbhansen** [Semantic-Org/Semantic-UI#2042]
Currently (at least for the modal) events are based on the elements that are preset when semantic modal is created. All semantic modules that use events should be changed to be dynamic and use event selectors. That way if the elements inside are changed, they don't need to be bound again. 

Example for the modal - We don't show the show/create the approve button on the dom until they can hit approve (i.e. creating a new user, all the information needs to be entered and valid). Currently the modal wires up events like

```
bind: {
  events: function() {
    $close.on('click' + eventNamespace, module.event.close);
    $window.on('resize' + elementNamespace, module.event.resize);
  }
},
```

but it would be better to do it like

```
bind: {
  events: function() {
    $module.on('click' + eventNamespace, selector.close, module.event.close);
    $window.on('resize' + elementNamespace, module.event.resize);
  }
},
```
Then any elements created inside the module after the initial modal initialization will be bound live to the right events. Otherwise we have elements created on the dom and we have to rebind them to the correct actions.

**Comment by jlukic** [comment]
Yeah this is an oversight in some modules. Dropdown and a few others do it better. Let me know if you see this anywhere else.

**Comment by aaronbhansen** [comment]
Looking quickly through the code, the only other two I see that don't bind live (based on your changes so far) are:
form.js
video.js

**Comment by jlukic** [comment]
Heh took a lunch break. I'll fix er up

**Comment by aaronbhansen** [comment]
Awesome thanks. This will help out a lot with our Ember code. Since ember removes and adds things to the dom based on template logic, the previous modules weren't always binding correctly when they were added later.

**Comment by jlukic** [comment]
I think that's everything.
