### ISSUE TITLE
[Tab] Closeable tabs. Preventing event from propagating on close

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2043]
Hi,

I've created closeable tabs by adding close buttons to tabs (`<i class="close icon"></i>`). All in all it works very well except for one issue.

Say, you have 2 tabs open and focus is on the last tab. I'd like to close first tab and not have onTabLoad fired on it. Basically, I'd like to stop event propagation when I click close button. I have the following code in place, but it's not very helpful:

``` javascript
.on('click', '> .item > .close', function(event) {
    event.stopPropagation();

   //close tab code follows
   //...
});
```

What can I do?

**Comment by jlukic** [comment]
I'm not sure your exact case but `tab` uses `api`, and `API` has an `abort` method to cancel the request

So most likely you can cancel the request by calling 
```javascript
$('.loading.tab').api('abort');
```

**Comment by andreyvk** [comment]
I think semantic ui ```onTabLoad``` event is still fired before my own ```click``` event. I tried adding exact code that you suggested and also tried ```$(this).closest('.item').api('abort');```, but nothing changed. Any ideas?

**Comment by jlukic** [comment]
I can't really say for sure without seeing the specific code. Abort will end the request if the tab is still loading

**Comment by andreyvk** [comment]
Hi @jlukic,

Sorry for the delay. I've created a [fiddle](http://jsfiddle.net/andreyvk/npxakcjg/10/) here to show what's happening.

**Steps to reproduce problem**:

1. After the whole thing loads, select last tab (Tab 3)
2. Click on an 'X' of the first tab (Tab 1)

**Outcome**: Tab 2 gets selected

**Desired outcome**: Tab 3 should remain selected

**Rationale**: It happens because semantic UI treats clicking on an 'X' same as clicking on a tab, so Tab 1 gets selected first before I even can stop 'click' event from propagating further. Then my code decides to move onto Tab 2, after Tab 1 is closed.

**Comment by jlukic** [comment]
Great I'll take a look shortly

**Comment by philrykoff** [comment]
Delegated jQuery events like you use in line 11 of your fiddle are seemingly executed later than directly applied events.

If you use direct event handlers, you can simply `return false` to stop the unwanted behaviour. Of course, you need to reapply them to every dynamically added tab (if that is intended).

Have a look here: http://jsfiddle.net/8ryzk8eo/
