### ISSUE TITLE
Add a note in README about IE9/IE8 support and CSS rule limit.

### ISSUE THREAD

**Issue by trevorlinton** [Semantic-Org/Semantic-UI#2048]
There's a little unknown bug on IE8/IE9 that these browsers are limited to 4095 rules per CSS file. 

This means semantic (with its 6000+ rules) breaks a lot on IE. But keep in mind, IT STILL WILL RENDER UP TO 4095 CSS RULES, then stop.

In other words, it sometimes half renders.

There's a fairly straight forward fix by using bless (it counts, then cuts up) the amount of rules into separate files that IE9/IE8 are happy to abide by.  

I'd imagine this will take care of quite a few of (at least questions) some may have about IE8/IE9.

http://blesscss.com

**Comment by jlukic** [comment]
Thanks for the thorough post. 

IE9 support is being dropped in next release with the addition of native `flex-box` implementations for `grid`, `menu` and other core UI. IE10 will be the newest minimum reqs for IE.
