### ISSUE TITLE
doubling.grid lose  :not(.row) restrict

### ISSUE THREAD

**Issue by zxfwinder** [Semantic-Org/Semantic-UI#2050]
doubling grid style: 
 `.ui[class*="xxx"].doubling.grid > .column` lose  `:not(.row)` restrict.

If applied below structure:
```
<div class="five column doubling ui grid">
	<div class="column"></div>
	<div class="column"></div>
	<div class="column"></div>
	<div class="column"></div>
	<div class="column"></div>
	<div class="four column doubling row">
		<div class="column"></div>
		<div class="column"></div>
		<div class="column"></div>
		<div class="column"></div>
	</div>
</div>
```
the width of `<div class="four column doubling row">` will be affected by `.ui[class*="five column"].doubling.grid > .column`.

**Comment by jlukic** [comment]
Thanks for your example. This is indeed a bug. Resolved in `2`
