### ISSUE TITLE
Popup - Variation - Wide and Very Wide -  Firefox is the same

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#2055]
On the popup component under variation - the Width option of "wide" and "very wide" popup the same width

IE and Chrome shows it correctly.
![popup](https://cloud.githubusercontent.com/assets/1778966/6975963/fef8e3b2-d957-11e4-80ae-3f0113485182.jpg)

**Comment by jlukic** [comment]
This is fixed in https://github.com/Semantic-Org/Semantic-UI/commit/3701bdc35f007228925545efa3d47cd52113540b (bad commit title)

min-width was set to `-moz-max-content` instead of `-moz-min-content`

If you dont want to wait for release add
```css
.ui.popup {
  min-width: -moz-min-content !important;
}
```
