### ISSUE TITLE
Labeled input fields with set widths overlap one another

### ISSUE THREAD

**Issue by tirdadc** [Semantic-Org/Semantic-UI#2057]
http://jsfiddle.net/5a6we429/5/

What's the recommended way to set the width of the labeled input fields while preventing overlapping?

UPDATE: I've finally managed to recreate the issue in this version of the jsfiddle. The last field that contains the button is overlapping / concealed because of this issue.

**Comment by jlukic** [comment]
If you're using column widths you will need to use `fluid input

**Comment by jlukic** [comment]
Scratch that. I think I can see some issue going on here. Will get back.

**Comment by jlukic** [comment]
It appears `flex-grow` with `width: auto` doesnt work correctly when the fluid width is below browser default input size.

**Comment by jlukic** [comment]
http://jsfiddle.net/1Lzkv4bc/
