### ISSUE TITLE
[Dropdown] Empty Text Shouldn't Change Selection on Blur

### ISSUE THREAD

**Issue by svansoeren** [Semantic-Org/Semantic-UI#2058]
Search field "default text" disappears after an item is selected and user begins to "re - search"

![screen shot 2015-04-03 at 2 25 14 pm](https://cloud.githubusercontent.com/assets/7727364/6986645/4f599b16-da0d-11e4-9086-ae1186f9db78.png)

![screen shot 2015-04-03 at 2 25 16 pm](https://cloud.githubusercontent.com/assets/7727364/6986648/54385aaa-da0d-11e4-83a4-616fa26f7c73.png)

![screen shot 2015-04-03 at 2 25 19 pm](https://cloud.githubusercontent.com/assets/7727364/6986652/64653876-da0d-11e4-88e3-d58aee69ccf2.png)

![screen shot 2015-04-03 at 2 25 21 pm](https://cloud.githubusercontent.com/assets/7727364/6986655/6bd1ee10-da0d-11e4-8ece-e0699d314c7b.png)

![screen shot 2015-04-03 at 2 25 26 pm](https://cloud.githubusercontent.com/assets/7727364/6986658/718722d0-da0d-11e4-8c38-a760431543b3.png)
![fix](https://cloud.githubusercontent.com/assets/7727364/6986784/b8efb0be-da0e-11e4-87cf-95afbd991102.png)

**Comment by jlukic** [comment]
I need to re-evaluate some cases of `forceSelection` for single search select.

**Comment by jlukic** [comment]
I believe the issue in current versions is that `forceSelection` will change to the currently selected dropdown value *even if* the value is blank (which should re-select last value).

**Comment by jlukic** [comment]
Finally fixed in `2.1`

**Comment by svansoeren** [comment]
Awesome. Thanks Man,
