### ISSUE TITLE
Example Layouts

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#206]
# UI Examples
### Developing

Examples is a major feature for 1.0 and will be found in `examples` branch.
### Implementation

Most useful examples will live in /build/examples/ as part of build distribution
- One css file, one js file and one html file per example
- Examples will use minified css/js
- Examples will be added to docs sidebar menu
- Example CTA will be added to homepage

Additional examples will be available in docs and downloadable from the web
### Distributed Examples

 http://getbootstrap.com/getting-started/#examples
- Homepage
- Grid
- Kitchen Sink
- Homepage
- Form Kitchen Sink (Steps, validation, all fields)
- Fixed Top Navigation
- Fixed Top and Sidebar

[Pure CSS Examples](http://purecss.io/layouts/)

More examples: http://demo.bootstraptor.com/blocks-salle.html#buy-now
### Doc Examples:
- RSS Feed - Existing
- Newspaper Grid - http://reliefweb.int/
- Ticketing page - http://www.eventbrite.com/event/8174364745/eorg
- Content List - http://teamtreehouse.com/library/programming
- App Page - https://www.bountysource.com/activity/bounties 
- Spec Page http://www.salsify.com/wp-content/themes/salsify/images/screenshot-of-salsify-product-content-management-system.jpg
- Simple Company - http://www.google.com/doubleclick/publishers/small-business/
- Course List - https://www.datacamp.com/courses/introduction-to-r
### Additional features
- Examples will each get injected a sidebar 
- Side will allow you to see, the components used with links to definitions
- Sidebar will link to codepen of example.
## Future

If examples get very large might break out into separate website.

**Comment by iceblade112** [comment]
I just noticed something. The homepage example doesn't have a responsive fixed/scrolling menu. Normal or no?

**Comment by wdmeeste1** [comment]
Is there alreay an email template for semantic ui?
