### ISSUE TITLE
Select dropdowns do not support keyboard selection

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI#2060]
When a plain `<select>` is opened or focused, you can use your keyvoard to navigate to an element. For example, if you have one with the options "foo", "foobar" and "flappy" (in this order), typing "f" will select "foo", but if you enter a lowercase L right afterwards, it'll select "flappy".

This is incredibly useful, especially for more technical people since scrolling through a big dropdown is kind of an unnecessary hassle if you already knoe what you want to select.

I realize there's the "Search Selection Dropdown" which does this, but I think it would make sense to provide functionality like in the native select widget even when not SSD.

**Comment by Einkoro** [comment]
Regular select and ui.dropdown side by side for easy comparison: http://jsfiddle.net/37yvutd0/1/

It looks like .ui.dropdown should close the list when you hit esc as well.

**Comment by jlukic** [comment]
For some reason the escape `hide menu` shortcut was set to only work when menu was already closed :unamused:

**Comment by jlukic** [comment]
I'm a bit afraid of the additional code overhead for adding the letter shortcuts into dropdown, but will investigate.

**Comment by jlukic** [comment]
@ThiefMaster @Einkoro 
Take back everything I said, I've gone ahead and implemented this and love it as a new feature :smile:
