### ISSUE TITLE
Wrappanel grid

### ISSUE THREAD

**Issue by antonkulaga** [Semantic-Org/Semantic-UI#2063]
It would be nice to have something like a wrappanel grid where I will be able to define max number of columns per and each extra column would automaticly go to "second row" and when the second raw will be filled - to third row and so on

**Comment by miniskulljob** [comment]
Well, you can already do that. Check out [this fiddle](http://jsfiddle.net/miniskulljob/7a4hs8j2/).
If you use the per column wide method, it will fill the row to the number of columns specified in the `@columnCount` variable and put the "extra columns" in the next row.
But if you use the grid and row column count method, you can control how many columns can be in a row and it will go "automatically" to the next row.

**Comment by antonkulaga** [comment]
Cool, I did not know that it was possible. Probably such example should be added to docs.

**Comment by miniskulljob** [comment]
It's in the docs:
* [Grid Column Flow](http://semantic-ui.com/collections/grid.html#column-flow)
* [Grid Column Widths](http://semantic-ui.com/collections/grid.html#column-widths)
* [Grid Column Count](http://semantic-ui.com/collections/grid.html#column-count)

You can see the source code of the examples by clicking the `< >` icon in the top right corner of the section.

**Comment by antonkulaga** [comment]
My mistake in such case
