### ISSUE TITLE
Request for Search behavior to clear cache

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2065]
Hi.

In case that we add new information to the DB that can be searched by the module, it would be great if we could clear the cache so it can access that new information. Right now, the only way to do that is setting the module to `cache: false` or reloading the page, but that's not a nice solution...

**Comment by jlukic** [comment]
Added

**Comment by paladin2005** [comment]
Is there any solution for clear cache in the remote dropdown?

**Comment by hendrikbl** [comment]
This functionality is not documented in the[Documentation](https://semantic-ui.com/modules/search.html#/settings). I'm not sure where to put it so I'm hesitating to create a pull request.
