### ISSUE TITLE
Api metadata will not be observed with search module

### ISSUE THREAD

**Issue by oqq** [Semantic-Org/Semantic-UI#2066]
Hi Guys!

In the most cases i use html5 attributes metadata for api calls. But this will not work for the search module, unless i add an empty apiSettings parameter. 

A short example:

```html
        <div class="ui fluid search" data-action="find customer">
            <div class="ui fluid icon input">
                <input class="prompt" type="text">
                <i class="search icon"></i>
            </div>
            <div class="results"></div>
        </div>
```

This will work:
```javascript
    $.fn.api.settings.api = {
        'find customer': '/customer/search-data?filter={query}'
    };

    $('.ui.search').search({
        apiSettings: {}
    });
```

And this will result in a "Search Module: No search endpoint was specified" error:

```javascript
    $.fn.api.settings.api = {
        'find customer': '/customer/search-data?filter={query}'
    };

    $('.ui.search').search();
```

Thanks for attention!
Oqq

**Comment by jlukic** [comment]
The check for `noEndpoint` forgets to check against metadata. This is a bug.

**Comment by jlukic** [comment]
Sorry about that. Fixed in `2`

**Comment by fluidlog** [comment]
For information, I have this error too when the search content is empty... (1.12.1).
