### ISSUE TITLE
Items added dinamically to Dropdown can't be selected programmatically

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2067]
Hi.

When you add more items to a Dropdown (like via `$(elem).append(item)`), they can't be selected by the behavior `set selected`. The only workaround I could find was initializing the Dropdown again.
You can test it in [this fiddle](http://jsfiddle.net/miniskulljob/n3t1eovp/).

**Comment by Einkoro** [comment]
You will need to use ``.dropdown('refresh')`` rather than reinitializing after appending options to the select. See https://github.com/Semantic-Org/Semantic-UI/issues/953

**Comment by miniskulljob** [comment]
Oh, thank you, I didn't know that there was that method implemented in the module. It isn't specified in the docs.

**Comment by Einkoro** [comment]
Good catch, I think I learned of that method from the gitter channel. I'll mark this a doc issue.

**Comment by jlukic** [comment]
Thanks for the catch. It will automatically observe changes in `<select>` if you a converted select menu, but i dont believe the menu will catch changes without calling refresh

**Comment by jlukic** [comment]
`next` actually observes both changes without having to call refresh

See [observe changes](https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js#L131)
