### ISSUE TITLE
Search module fails when selecting an item in category mode

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2070]
Hi.

Using the Search module in category mode, and making requests to the server, it fails when you select an item from the list when there's more than one item listed. I found the problem in the method `get.result`, lines [314](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L314) and [315](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L315):
```javascript
/*311*/ $.each(results, function(index, category) {
/*312*/     if($.isArray(category.results)) {
/*313*/         result = module.search.object(value, category.results)[0];
/*314*/         if(result && result.length > 0) {
/*315*/            return true;
/*316*/         }
/*317*/     }
/*318*/ });
```
The method `module.search.object` returns an `array`, but it's selecting the first item (`[0]`), so `result` contains an `object`. That makes the `if` fail the condition on each iteration of the loop. More so, even if the condition was fulfilled, `return true` is making the loop continue through the next iterations, resulting in an unexpected behavior. The correct `return` value to stop the loop is `false`.
For the time being, I did this:
```javascript
/*311*/ $.each(results, function(index, category) {
/*312*/     if($.isArray(category.results)) {
/*313*/         result = module.search.object(value, category.results)[0];
/*314*/         if(result) {
/*315*/            return false;
/*316*/         }
/*317*/     }
/*318*/ });
```

**Comment by jlukic** [comment]
Can you create a test case. You can use the fake api endpoints on semantic-ui

```javascript
$.extend($.fn.api.settings.api, {
    categorySearch : '//api.semantic-ui.com/search/category/{query}',
    search         : '//api.semantic-ui.com/search/{query}'
  });
```

**Comment by miniskulljob** [comment]
I did a test case, but I can't find anything in the fake api to test it out...

[Test case fiddle](http://jsfiddle.net/miniskulljob/gbu00f16/)

**Comment by jlukic** [comment]
Thanks for taking the time to create the test case. 

If you have a `JSON` payload that causes the error, you can use jsfiddles `echo/json` endpoint. Or you can just post your JSON, and I can test it locally.

**Comment by jlukic** [comment]
Just from perusing the code again, title is used as a unique matcher for search terms. If two results have the same title it will always return the first element. I think this is the intended behavior.

**Comment by jlukic** [comment]
Continuing discussions in #2059

**Comment by jlukic** [comment]
Sorry about the delay on all this. This should be resolved with the rewrite of `search object` in `2.0`
