### ISSUE TITLE
[search] Add support for transforming data from server response

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2071]
Currently, if you are using the search module with a remote data source, it must return the correctly formatted JSON for the search module to be able to consume it. However, if the server does not return correctly formatted JSON, and if you can't modify the response the server sends server-side, then you can't use it with the search module.

There should be a way to transform the data received from the server response with a user-defined function client-side, the return value of which would then be passed into the search module (similar to [Typeahead.js's `filter`](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote)). This would allow users to use the search module with any data source, provided that they transform it correctly.

**Comment by mnquintana** [comment]
@jlukic Do you think it would be better to implement this in the search module or in the API module? I was thinking about adding it to the API module, since the ability to transform server responses seems like it would be useful in any module that can pull from remote data sources, not just search.

**Comment by jlukic** [comment]
I think it makes sense to add in API module, pre JSON `successTest`

**Comment by jlukic** [comment]
Closed with #2092
