### ISSUE TITLE
What is the Release date of Semantic UI 2

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2073]
We are working on big project, we complet the dev of all Layer, now we are working on the Presentation Layer, our Team leader said we must made it Bootstrap, but we find that Semantic UI is an interesting Framework, so we decide to try it.
And now we are waiting for your next version (v2), bcz you said that you are working on it...
So plz, is there any information about release date or Roadmap.

Thanx for All your Hard work.
Respect.

**Comment by jlukic** [comment]
The middle of this month

**Comment by ikourfaln** [comment]
OK, Thank you a lot :+1: 
Waiting for Beta, we must have something to work with or,  if there no big changes,  we will start with the current release.

**Comment by jlukic** [comment]
Release notes are [maintained here](https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md) for 2.0

**Comment by ikourfaln** [comment]
Ow, thanx for all your hard work... I love you

**Comment by abdelouahabb** [comment]
Any  updates?

**Comment by jlukic** [comment]
Its June 1st, #2216
