### ISSUE TITLE
Video module - id does not work

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2077]
Have there been any changes to the video module? Data id seems not to deliver the video. 

By the way is there any possibility how to link data id to a video stored on the website server itself and not youtube or vimeo?

**Comment by jlukic** [comment]
There hasn't been any changes. 

Can you provide a jsfiddle?

**Comment by kvetoslavnovak** [comment]
You can try defsult Semantic example http://semantic-ui.com/modules/video.html

**Comment by jlukic** [comment]
Damnit they took down the kitty video! I will have to find a new one

**Comment by jlukic** [comment]
Added new bear video in `next`
