### ISSUE TITLE
Search module closes modal when element is select with a mouse click.

### ISSUE THREAD

**Issue by siannone** [Semantic-Org/Semantic-UI#2079]
I'm using the search module inside a modal and everything's working fine if I use the keyboard to select one of the search results, but if I select it using the mouse the modal closes together with the search dropdown.

This is how I initialize the search module:

    $('.searchTeam').search(
        {
            type : 'standard',
            source : customers,
            searchFields : [
                'title',
                'description'
            ],
            onSelect : function(result, response)
            {
                $scope.callback({recipient : result});
            }
        }
    )

And this is how I initialize the modal:

    $('#modalMessages')
        .modal({
            onApprove : function() { return false; }
        })
        .modal('show');

**Comment by jlukic** [comment]
Can you create a test case I can use to help debug. There's a jsfiddle to fork in the readme

**Comment by siannone** [comment]
I'll try to create a test case ASAP.

**Comment by cspeer** [comment]
http://jsfiddle.net/cspeer/q2pb0qkd/2/
In the search box all possible results start with an **A**. Make sure to select a result by *using your mouse*!

Thanks :)

**Comment by siannone** [comment]
@cspeer Thank you so much for providing a test case, I really had no time to do that.

**Comment by jlukic** [comment]
Regardless of where you put the sidebar you will need to wrap the "pushable content" in an element with the class "pusher"

The init script is forgiving and will create it for you but it's a huge performance drop to modify DOM on page load

**Comment by cspeer** [comment]
@siannone sure :)
Any idea what's causing this @jlukic and/or a quick workaround?

**Comment by jlukic** [comment]
It looks like search results are removed from dom before click bubbles to dimmer causing [this check](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/modal.js#L224) to fail.

**Comment by cspeer** [comment]
Hmm,
I "worked around" it by setting the modal to be non-closable. That fixes my problem for now.

Thanks a lot for your awesome work @jlukic !

**Comment by jlukic** [comment]
Fixed in `next`. 

You could try using the source from `next` for now, or wait for it to come out.

There's also another option to overwrite internal methods per-module that i never really discussed anywhere but could be used here.

```javascript
$('.modal').modal('internal', 'event click', function(event) {
  var
    $target   = $(event.target),
    isInModal = ($target.closest($module).length > 0),
    isInDOM   = $.contains(document.documentElement, event.target)
  ;
  if(!isInModal && isInDOM) {
    module.debug('Dimmer clicked, hiding all modals');
    if( module.is.active() ) {
      module.remove.clickaway();
      if(settings.allowMultiple) {
        module.hide();
      }
      else {
        module.hideAll();
      }
    }
  }
});
```

**Comment by siannone** [comment]
@jlukic Thank you for your amazing job!
