### ISSUE TITLE
there is a horizontal scrollbar ---- ui grid

### ISSUE THREAD

**Issue by weiheli** [Semantic-Org/Semantic-UI#2082]
why there is a horizontal scrollbar when i use "ui grid" like this: 
&lt;div class="ui grid"&gt;
    &lt;div class="four wide column"&gt;1&lt;/div&gt;
    &lt;div class="four wide column"&gt;2&lt;/div&gt;
    &lt;div class="four wide column"&gt;3&lt;/div&gt;
    &lt;div class="four wide column"&gt;4&lt;/div&gt;
&lt;/div>

**Comment by jlukic** [comment]
Grids use negative margins. If you have a page level full width grid use `padded grid`
