### ISSUE TITLE
[Search Dropdown] Add Match Setting

### ISSUE THREAD

**Issue by xiechao06** [Semantic-Org/Semantic-UI#2083]
Some times, it may make the filtered results to be strange. for example, if the dropdown contains a group of telephone number and the value of each "\<option\>" is id of the telephone number, when you input a number,   the seemingly irrelevant results will displayed.
jsfiddle: http://jsfiddle.net/xiechao06/9mjnt91r/8/, input "1" and check the filtered results.
code: dropdown.js, line 413

```javascript
          $item
            .each(function(){
              var
                $choice = $(this),
                text    = String(module.get.choiceText($choice, false)),
                value   = String(module.get.choiceValue($choice, text))
              ;
              if( text.match(exactRegExp) || value.match(exactRegExp) ) {
                $results = $results.add($choice);
              }
              else if(settings.fullTextSearch) {
                if( text.match(fullTextRegExp) || value.match(fullTextRegExp) ) {
                  $results = $results.add($choice);
                }
              }
            })
          ;
``` 
please don't match value against input , or at least provide a switch option.

**Comment by jlukic** [comment]
This should be a setting.

**Comment by jlukic** [comment]
Added as setting `match` in `2.0`
