### ISSUE TITLE
[Dropdown] Calls on <select> are not passed to ui dropdown correctly

### ISSUE THREAD

**Issue by xiechao06** [Semantic-Org/Semantic-UI#2084]
in this fiddle(http://jsfiddle.net/xiechao06/efp8z6Ln/133/) (use \<select\> as dropdown), I failed to invoke "clear", after spending several minutes, I found that the actually "dropdown" is not the "\<select\>", but a generated tag. please add some notes to '.ui.dropdown', that when use "\<select\>" as a dropdown, you should call "$select.dropdown().dropdown(methodName)" to invoke a dropdown method.

**Comment by jlukic** [comment]
This is actually a bug. It is suppose to catch for that error automatically [in the code](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L77) but it appears not to correctly invoke the method with the new context correctly.

**Comment by jlukic** [comment]
Added in `2`
