### ISSUE TITLE
Reset CSS

### ISSUE THREAD

**Issue by vautrinr** [Semantic-Org/Semantic-UI#2085]
Hi there ! 
I am a newbie in Semantic UI, which I find very nice. 
I found these properties active in my chrome web browser : 
h1{
  -webkit-margin-before: 0.67em;
  -webkit-margin-after: 0.67em;
  -webkit-margin-start: 0px;
  -webkit-margin-end: 0px;
}

inactive with this code :
     ````<h1 class="ui left floated header">Test</h1>```
active with this code : 
    ```<h1 class="ui left floated header">Test</h1><a class='ui red button right floated'>Click me</a>```
Am I missing something? Should I import a css reset or something ?

**Comment by jlukic** [comment]
There's a reset included with SUI
http://semantic-ui.com/globals/reset.html

**Comment by vautrinr** [comment]
Okay, thanks. Even in the reset 'test' page, the h1 margin is not set to 0. Should I make my fix only for my website ? Or is this a bug ?

**Comment by jlukic** [comment]
It uses normalize.css

If you are including `site` component in your build this will add default `h1-h6` stylings
