### ISSUE TITLE
Local gulp not found

### ISSUE THREAD

**Issue by matt-dease** [Semantic-Org/Semantic-UI#2086]
In an empty directory I'm running:
```
npm install semantic-ui
cd semantic/
gulp build
```
The gulp command errors out with:
```
Local gulp not found in ~/dev/test-project/semantic
Try running: npm install gulp
```
I can see gulp is installed locally at ~/dev/test-project/node_modules/semantic-ui/node_modules/gulp along with all the gulp plugins, not sure why it's not seeing it.
Manually installing gulp via npm as it suggests fixes the missing gulp message but then I'd need to install all the other semantic-ui dependencies too.

I'm running OSX 10.10.2, I did get a friend to test on Ubuntu and they couldn't reproduce the issue.

**Comment by jlukic** [comment]
it sounds like npm isnt grabbing `peerDependencies`. Are you using an old version of npm that doesn't support them?

**Comment by matt-dease** [comment]
I'm running npm 2.7.5, was getting these warnings for each peerDependency when doing npm install:
```
npm WARN peerDependencies The peer dependency gulp@3.* included from semantic-ui will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
I did actually try downgrading to npm 1.4.28 (which my friend was running) but had the same issue.

**Comment by jlukic** [comment]
oh lord this is a new message.. i need to check over on the npm boards

**Comment by jlukic** [comment]
Looks like peer deps is deprecated
http://blog.npmjs.org/post/110924823920/npm-weekly-5

Now to investigate NPM3s approach to resolving deps... preliminary glance shows maybe this will be a good thing for SUI

**Comment by jlukic** [comment]
Discussion going on here https://github.com/npm/npm/issues/6565#issuecomment-74971689

**Comment by aristidesfl** [comment]
I have the same issue with peerDependencies not being installed automatically.
What are the install commands to work around this? Should the documentation be updated?

npm 2.13.1
node v0.12.7
OS X 10.10.4

**Comment by jlukic** [comment]
@aristidesfl Those should only be warning flags and will not affect install until `npm@3` launches.

**Comment by aristidesfl** [comment]
@jlukic but it does
```
20:54:33] Using gulpfile ~/Work/test/node_modules/semantic-ui/gulpfile.js
[20:54:33] Starting 'install'...
[?] Set-up Semantic UI: Automatic (Use defaults locations and all components)
[?] We detected you are using NPM. Nice!

    Is this your project folder?
    /Users/user/Work/test Yes
[?] Where should we put Semantic UI inside your project? semantic/
Installing
------------------------------
Installing to semantic/
Copying UI definitions
Copying UI themes
Copying gulp tasks
Adding theme files
Creating gulpfile.js
Creating site theme folder /Users/user/Work/test/semantic/src/site/
Adjusting @siteFolder to:  site/
Creating src/theme.config (LESS config) /Users/user/Work/test/semantic/src/theme.config
Creating config file (semantic.json) /Users/user/Work/test/semantic.json
Install complete! Navigate to semantic/ and run "gulp build" to build
[20:54:41] Finished 'install' after 7.59 s

^C~
user at unknown in ~/Work/test
$ cd semantic/

user at unknown in ~/Work/test/semantic
$ gulp build
module.js:338
    throw err;
          ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/Work/test/node_modules/gulp-help/index.js:1:82)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by jlukic** [comment]
I'll keep looking..

**Comment by jlukic** [comment]
In your example you have
`^C~`

It looks like you exited after install script using `ctrl+c` before deps finished resolving.

**Comment by aristidesfl** [comment]
It says `[20:54:41] Finished 'install' after 7.59 s`

Is the install not finished even though it says so?

**Comment by jlukic** [comment]
No, peer dependencies install after `install` scripts run.

**Comment by jlukic** [comment]
I've found a fix for this. Looks like the install scripts need to call `process.exit();` in later NPM or else will hang.

**Comment by let4be** [comment]
It clearly states `Finished 'install' after`
but I have the same problem as topic starter...

**Comment by jlukic** [comment]
I'm working on this currently. I know this is a huge annoying deal for those who are experiencing it.

The `install script` is not terminating the process correctly. In older versions of NPM everything works fine, but more recent versions have this issue. Since peerDeps resolve after install scripts, they will never get installed.

I'll try to have a fix today or tomorrow.

**Comment by let4be** [comment]
Thanks @jlukic

**Comment by let4be** [comment]
Okay it seems like you just need to run `npm install semantic-ui` twice :|

**Comment by jlukic** [comment]
Can anyone try against `next` branch from a fresh project? I think I have resolved the issues

```bash
npm install Semantic-Org/Semantic-UI#next
```

**Comment by aristidesfl** [comment]
@jlukic 

```
$ npm install Semantic-Org/Semantic-UI#next
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
-
> semantic-ui@2.0.6 install /Users/user/Work/test/node_modules/semantic-ui
> gulp install

module.js:338
    throw err;
          ^
Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/Work/test/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "Semantic-Org/Semantic-UI#next"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.0.6 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.0.6 install script 'gulp install'.
npm ERR! This is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Work/test/npm-debug.log
```

**Comment by jlukic** [comment]
Can you gist your npm-debug.log?

**Comment by undercase** [comment]
I'll try the next branch right now, I've been trying to fix this issue for the past hour or so.

**Comment by undercase** [comment]
The next branch fixes this issue! Semantic installs and works out-of-the-box. The solution does seem somewhat hacky however, and from what I understand migrating away from using peerDependencies should make the install script go much smoother.

**Comment by jlukic** [comment]
There is another branch `npm3` which is compatible with the upcoming NPM release. Flat dependencies rule.

**Comment by jlukic** [comment]
This was incorrectly tagged as `2.1.0` and has already been resolved.
