### ISSUE TITLE
Search In Menu: Results Hidden

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#2088]
When a search is embedded in a secondary menu, the results are hidden.  Here is an example fiddle showing the issue with 3 examples:

1) Embedded and broken search
2) Broken search with my work around.  It looks like crap but it at least shows up.
3) A stand alone search that works fine with the same exact settings

http://jsfiddle.net/daneren2005/rg2g9mw6/1/

**Comment by jlukic** [comment]
Hi, this has been fixed in `2.0` with menu rewrite. Hopefully you can hold on

Fiddle from `next` branch
http://jsfiddle.net/pcLk1861/

**Comment by daneren2005** [comment]
Luckily it's for a non-public facing feature so I am in no hurry.  Glad to hear it is already fixed.
