### ISSUE TITLE
Site colors inheritance by other elements with colors

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2089]
Does global site colors rebuild colors for all other elements that have colors (buttons, tables, segments etc.)?
It seems to me that they do not. So if a user bulds css with own site colors there is a mix of site colors and default colors.

**Comment by jlukic** [comment]
No site.variables does not rebuild all files currently. This is changed in `2.0`.  See [note 2](https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md#version-200---march-xx-2015) under enhancements.
