### ISSUE TITLE
.ui.search fires ajax request on every keyup

### ISSUE THREAD

**Issue by drepo** [Semantic-Org/Semantic-UI#2091]
When using a remote API with `.ui.search`, the remote API is called for every keyup. This leads to unnecessary bandwidth consumption and strain on the server.

Some implementation of remote auto complete, I have come across, use small (ex.: 300ms) `setTimeout` after every keyup to trigger remote call. This leads to call being executed only when there is small break in the typing flow.

Another optimization is to cancel the previous `jqXHR` when a new request is triggered and previous is still pending.

PS: I am too new to SUI to submit a reliable pull request.

**Comment by jlukic** [comment]
Search fires with a [self clearing timer](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L520), it does not fire on each keydown. The default delay is 300ms but you can adjust with `searchDelay` setting.

**Comment by drepo** [comment]
Thanks for that! :+1: Marking closed.
