### ISSUE TITLE
Semantic Encapsulation

### ISSUE THREAD

**Issue by Avnerus** [Semantic-Org/Semantic-UI#2093]
Hi,
I've encountered a dilemma while trying to implement Semantic UI in my project.
I would like to have the following html:
```
<a class="delete-button" href="/delete"> Delete </a>
```
When using Bootstrap, I can import the LESS code into my own file, and then define the following class:
```
.delete-button {
  .btn;
  .btn-danger;
  .btn-lg;
} 
```
This generates my delete-button class to match bootstrap's along with the :hover status, or any related behavior that I would get by using bootstrap's classes. I can also use the ```.button-variant()``` mixin to generate a themed button.
I tried to do something similar with Semantic UI but I couldn't get it work. The closest I got was doing:
```
.delete-button {
    .ui.button;
    .ui.big.button;
    .ui.red.button;
}
```
But it still didn't inherit any extra behavior such as hover. 
This gets even more complicated when trying to encapsulate more complex elements such as 'checkbox' with my own classes.
Is there any way to achieve this effect with Semantic UI?
Thanks!

/Avner

**Comment by jlukic** [comment]
Hi thanks for posting. Your post was well articulated and a good question, and thats much appreciated. 

Our LESS implementation uses a very minimal amount of "LESSlike" syntax. When I was starting to create preprocessed css my goal was to make the codebase readily portable to other preprocessors like SASS etc. This means the implementation use only two mix-ins: one to load google fonts and another to adjust the dynamic import paths to themes. 

Aside from that we use just variables and css color and calc functions. Even those I've tried to personally limit to `site.variables` to make sure they could be programmatically adjusted to the syntax of other libraries.

The way I intended to have UI extensible is by allowing sites to add their own vocabulary on top of the library using UI site or theme specific overrides, for example `site/elements/button.overrides` allows you to define custom css that will be carried along with the button definition, and has access to all button variables (with theme variable processing) in that scope. The prepackaged theme examples like `amazon button` etc all use this approach to extend the CSS using theme specific code.

The idea being that if the UI is specific to your business you should carry it with you between projects as part of your site's theme and not in layout specific code. 

Regarding your example, we have an `error  button` and `negative button` as part of the core button ui, which you might consider. Additionally if you think there's an important `variation` or element `type` that is missing you can always propose it as an addition to the library.

**Comment by Avnerus** [comment]
Hi Jack,
Thank you very much for such a quick and elaborate response!
If I understand correctly, the ```*.overrides`` provide more extensibility than encapsulation, but that is also useful. Using Semantic-UI has great benefits so I think I can work around this issue with good theming and 'web component' style encapsulation.
Maybe you would consider in the future adding this ability. Looking for example at how bootstrap implements their .btn classes: https://github.com/twbs/bootstrap/blob/master/less/buttons.less
It seems quite simple to allow for such semantic encapsulation. Only a matter of how your organize your class hierarchy.
Perhaps to avoid the portability issues, you can provide a PostCSS package that will allow you to use mixins with the already compiled css. Maybe using something liike this: 
https://github.com/postcss/postcss-mixins
Semantic-UI  enables a clear description of what will be displayed, but it will be great to be able to encapsulate it with meaningful application level classes.
Thanks!
/Avner

**Comment by Einkoro** [comment]
Wouldn't extend work for this either using compiled themes or per component includes of the LESS files into your own project? AFAIK it would not work for plain ol' CSS imports and then trying to extend from them. I am not sure if the scoping work around for per component LESS includes would affect extend.

**Comment by jlukic** [comment]
I appreciate the simplicity of extending with min-ins, but I'm wary of the complexity it brings for the library, especially in terms of debugging specificity issues.

**Comment by Einkoro** [comment]
Mixins would not be required for extend. It will extend from another selector if it's from a LESS import. Should work as is without changes although I'm unsure about how the scope work around may affect it when pulling individual less components in.

----
Jan Pingel
jan.pingel@me.com
+1 (778) 678 2248

**Comment by jlukic** [comment]
Not that it matters but I think these are technically called "mix-ins" within LESS
http://lesscss.org/features/#mixins-feature

The parenthesis from what I understand are optional.
```less
.a, #b {
  color: red;
}
.mixin-class {
  .a();
}
.mixin-id {
  #b();
}
```

**Comment by Einkoro** [comment]
extend(selector) is what I was thinking. Usually what I use to avoid lots of duplicate rules when I need to add features.

----
Jan Pingel
jan.pingel@me.com
+1 (778) 678 2248
