### ISSUE TITLE
Bug about .ui.card image CSS Style In IE11

### ISSUE THREAD

**Issue by Troevil** [Semantic-Org/Semantic-UI#2094]
hello,
i use the semantic ui, it's so cool.But i found a bug about style in IE 11.
but it's i try to use it stand alone ,but it still occurred.
in the picture , the image's height  is dislocated
Can you give me  a solution ?

pic from in docs ->progress
![origin](https://cloud.githubusercontent.com/assets/9956097/7083812/bd0ffdf4-df98-11e4-8e60-1b6e399a7a1c.png)
pic from test stand alone.
![test](https://cloud.githubusercontent.com/assets/9956097/7083823/f37de766-df98-11e4-8961-70c1dd0c64ab.png)

**Comment by jlukic** [comment]
Hi, this is fixed in `2.x`, [check issues](https://github.com/Semantic-Org/Semantic-UI/issues?q=is%3Aissue+card+is%3Aclosed)
