### ISSUE TITLE
Website giving 404

### ISSUE THREAD

**Issue by diogobernini** [Semantic-Org/Semantic-UI#2097]
The www.semantic-ui.com is returning 404.

**Comment by zuher83** [comment]
confirm!!!

**Comment by diogobernini** [comment]
working again :+1:

**Comment by jlukic** [comment]
Sorry. On a side note, beta docs are now up. These are still a work in progress and responsive breakpoints havent been addressed yet.
http://beta.semantic-ui.com

**Comment by zuher83** [comment]
working again!!!
