### ISSUE TITLE
Colums are not responsive.

### ISSUE THREAD

**Issue by mllamazares** [Semantic-Org/Semantic-UI#21]
I was checking the grid examples, I redimensionated the browser, and this is the result:

![untitled](https://f.cloud.github.com/assets/5461023/1148425/0c846b5c-1ec2-11e3-920f-e0baf4e03ead.JPG)

**Comment by luisalves73** [comment]
Looks like Semantic Ui doesn't tackles responsiveness properly. For instance how can we change the class of a div according a certain breakpoint/device? something like class="pc-4-wide tablet-eight-wide mobile-sixteen-wide" without having to duplicate code 3 times and apply different classes to each block?

**Comment by happy2deepak** [comment]
@jlukic  How to handle this scenario in Tablet devices? support In each Row, I want to show 4 grids in Desktop, 2 in Tablet and Stack in mobile? How shall I handle it?

**Comment by javiersuzuki** [comment]
Hi guys,
The grid seems to have responsive issues (at 768px) when having 2 columns with a menu in one and a segment in the other one, like the example below:
<div class="ui stackable grid">
  <div class="four wide column>
    <div class="ui vertical menu">Menu</div>
 </div>
  <div class=" twelve wide column">
    <div class="ui segment">Segment Content</div>
 </div>

![screen shot 2017-10-23 at 8 41 21 am](https://user-
images.githubusercontent.com/688636/31866607-004f5712-b7ce-11e7-902d-3608ba829978.png)

Cheers
