### ISSUE TITLE
Some icons is missing?

### ISSUE THREAD

**Issue by jamalsoueidan** [Semantic-Org/Semantic-UI#2103]
I'm using Semantic UI on a new rails project, I have included font-awesome, but some icons is not visible for some reasons?

Anyone knows what's wrong?

When I also implement Card with stars, the stars is not visible, do I need to add JS to make them visible?

Thank you,

![screen shot 2015-04-12 at 14 23 56](https://cloud.githubusercontent.com/assets/115714/7105541/28090952-e11f-11e4-8c4a-c1b51dbdd9ce.png)

**Comment by jlukic** [comment]
I'm not sure what your environment is, but that should not be the case. Can you create a reproducible test case?
