### ISSUE TITLE
Horizontal divider issue - margin-left ?

### ISSUE THREAD

**Issue by blankdots** [Semantic-Org/Semantic-UI#2104]
There seems to be an issue with the Horizontal divider when I load it into my project. On the Semantic UI website it seems to work fine.
Browser: Chrome Version 41
Semantic UI version built for node: v1.11.6

![screen shot 2015-04-13 at 01 53 52](https://cloud.githubusercontent.com/assets/47524/7108230/1db6bc2c-e180-11e4-831e-1ba0ab5894cb.png)

```css
margin-left: calc(-50% - 1em);
margin-right:0;
```

**Comment by jlukic** [comment]
This is most likely fixed for you in `2.0` 
http://beta.semantic-ui.com/elements/divider.html#horizontal-divider

Horizontal dividers have been re-worked to use a more cross-browser friendly method
