### ISSUE TITLE
Serious cards height issue in IE11

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#2105]
See screenshots:

![screenshot_2015-04-13_10-56-38_am](https://cloud.githubusercontent.com/assets/907195/7112648/f304638e-e1cb-11e4-8b49-83907c3be978.jpg)

http://www.browserstack.com/screenshots/e5d10051f00e1b26da8cd72f0b4490fa1989a07b

**Comment by jlukic** [comment]
This should be an IE only bug, has been discussed in other threads and has been fixed in `next`.

**Comment by jlukic** [comment]
#2094 #2021

**Comment by tmikaeld** [comment]
Sorry, i searched but didn't find it. Glad it's fixed

**Comment by jlukic** [comment]
Releasing a patched version today to `1.x` channel
