### ISSUE TITLE
Show dependecies when trying to build?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#2106]
Hi,
I wish you could provide the dependecies when someone will try to build its own version of SUI (even in the docs), because there are parts, if unchecked, others active parts will not work.

**Comment by jlukic** [comment]
The dependencies are listed in `package.json`
https://github.com/Semantic-Org/Semantic-UI/blob/master/package.json#L47

**Comment by abdelouahabb** [comment]
@jlukic sorry, this is not what i meant, what i meant is when i build it, if i desactivate an element, another element can not work, and not about javascript modules.

**Comment by abdelouahabb** [comment]
@jlukic here is what I meant, Am sorry for my lack of english, I was talking about `Compenents to include`
![sans titre](https://cloud.githubusercontent.com/assets/2527234/7122970/d401e5c4-e216-11e4-9006-cc577952d6d5.png)

**Comment by jlukic** [comment]
The only components that necessarily rely on other components are modules that use `transition`, otherwise all relationships are loose couplings

**Comment by abdelouahabb** [comment]
ah, so can you please add this near transition as a warning?

**Comment by jlukic** [comment]
Individual components will produce errors in the console if they are missing required components.

**Comment by abdelouahabb** [comment]
Ah, sorry then :D
