### ISSUE TITLE
Minor Typo on Site

### ISSUE THREAD

**Issue by krishnaglick** [Semantic-Org/Semantic-UI#2108]
In the examples section for Sidebars on semantic-ui.com, the code for custom context has the comment '// showing multiple'. It should say something along the lines of '// custom context'.

**Comment by jlukic** [comment]
Thanks this was a copy and paste mistake

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-Docs/commit/c22aaab7db60050692c0d1acf992d1af2054c8cb

You can also PR these changes directly from the docs repo by clicking the edit button on a page if you are so inclined.
