### ISSUE TITLE
vertical buttons bug

### ISSUE THREAD

**Issue by alfcrowd** [Semantic-Org/Semantic-UI#2109]
```
			<div class="ui vertical buttons">
				    <button class="huge green ui labeled icon button">
				      <i class="signup icon"></i>
				      Kayıt ol
				    </button>
				    <button class="huge facebook ui labeled icon button">
				      <i class="facebook icon"></i>
				      Facebook ile giriş yap
				    </button>
				    <button class="huge twitter ui labeled icon button">
				      <i class="twitter icon"></i>
				      Twitter ile giriş yap
				    </button>
			  </div>
```
Chrome: http://goo.gl/dijy6o

Safari: http://goo.gl/jGSFz9

Vertical buttons doesn't work with Safari.

**Comment by jlukic** [comment]
Hi, i just tested this locally with safari and am not seeing your results. 

Can you provide a live test case where this is occurring?

**Comment by oytunistrator** [comment]
Version;
Safari  8.0.5 (10600.5.17)
Mac OSX 10.10.3

**Comment by oytunistrator** [comment]
Same problem: http://goo.gl/a9NZ6g
Facebook and twitter buttons not visible on Safari 8.0.5.

**Comment by avalanche1** [comment]
Closing until there's a test case.

**Comment by avalanche1** [comment]
Closing until there's a test case.
