### ISSUE TITLE
[UI] Nag

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#211]
## Nag

Nag is a component for providing important alerts above your website. These alerts can be dismissed and not shown again by a user with the value being stored by cookie, local storage, or api endpoint.

https://github.com/jlukic/Semantic-UI/blob/master/src/modules/nag.js
### Required for 1.0
- Create documentation
- Create examples
- Minor code retooling
### Required for 2.0
- Nag can be automatically hidden after a set number of seconds
- Multiple nags can appear as growl style notifications at the top of the page

**Comment by dharma-guardian** [comment]
The module seems to be broken. The example page http://semantic-ui.com/modules/nag.html throws 'Nag: undefined'.
On OSX 10.10 Chrome v42 / ubuntu 14.04 Chromium v41 + Firefox v37

**Comment by iamolivinius** [comment]
Looks like jquery-cookie plugin is missing. Load it right after jquery and you'll be fine.

**Comment by jlukic** [comment]
It's borked. Probably from when i reworked global includes in the docs. Will reupload tomorrow.

**Comment by jlukic** [comment]
Main docs should not be broken anymore, just reuploaded
http://semantic-ui.com/modules/nag.html

I'll try to write out simple docs for this for 2.0. Probably wont have time to recode it.

**Comment by iamolivinius** [comment]
Just found out the the Nag component has the Popup component as a hard dependency. Without the Popup component the Nag component can not be dismissed correctly. 

I like the idea that components can be loaded separately but I suggest that dependencies should be listed in a subsection of each components documentation.

**Comment by jlukic** [comment]
Nag doesnt have any dependencies. It can use `$.cookie` for storing values, but otherwise none.

**Comment by iamolivinius** [comment]
Without the popup module the `easeOutQuad` function won't be available. Problem: the nag message does not hide.

Without the icon module the `close` icon won't be visible. Problem: the nag message can not be dismissed.

For me, from a users point of view, these are dependencies to get the nag module up and running regarding to the current documentation.

http://jsbin.com/ziweqeqasu/1/edit?html,js,output

**Comment by jlukic** [comment]
Ahh its the damn easing equations. I can fix that.

**Comment by jpeffer** [comment]
Are there any currently scheduled plans to include colors to the nag component? It would make sense if the same styles as the Message collection. Nag really feels very similar to the dismissible Message, with the exception that the decision to dismiss is persisted.

**Comment by d8vjork** [comment]
Nag continue using $.cookie (jQuery Cookie: https://github.com/carhartl/jquery-cookie), but this component was moved, now is JS Cookie (https://github.com/js-cookie/js-cookie).

Please update Nag component.

**Comment by unki** [comment]
@d8vjork see #2905, seems to be already in pipeline

**Comment by Jabark** [comment]
@jpeffer Just add this to your _nag.overrides_ in your theme files:

```
.ui.nag.black {
    background-color: @black;
}
.ui.nag.blue {
    background-color: @blue;
}
.ui.nag.green {
    background-color: @green;
}
.ui.nag.grey {
    background-color: @grey;
}
.ui.nag.orange {
    background-color: @orange;
}
.ui.nag.pink {
    background-color: @pink;
}
.ui.nag.purple {
    background-color: @purple;
}
.ui.nag.red {
    background-color: @red;
}
.ui.nag.teal {
    background-color: @teal;
}
.ui.nag.yellow {
    background-color: @yellow;
}
```

**Comment by niittymaa** [comment]
As @iamolivinius already said just include before jQuery and it worked for me.

`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>`

https://cdnjs.com/libraries/jquery-cookie/

**Comment by lubber-de** [comment]
We removed the general jquery plugin dependency, added colors and sizes, fixed bugs and did some more enhancements to the nag module in the community fork Fomantic-UI by
https://github.com/fomantic/Fomantic-UI/pull/1795

**Comment by d8vjork** [comment]
That's actually good news as Semantic UI seems dead
