### ISSUE TITLE
Flicker when scrolling on mobile 

### ISSUE THREAD

**Issue by specimen151** [Semantic-Org/Semantic-UI#2110]
On several of the pages on the home page and on learn semantic-ui site, there is a "black flicker" on the bottom third of the page when scrolling. This leaves the impression that is slow or buggy. 

I've surfed on many other css frameworks and semantic is the only one having this problem. I use an iPhone 6. 

Also there is a noticeable delay when pressing buttons. This has been mentioned before in a suggestion to integrate fastclick.js.

**Comment by Futurama56** [comment]
We are experiencing similar issues - 

http://areaaperta.com/nicescroll/

Seemed to calm things down for now

**Comment by avalanche1** [comment]
Which pages exaclty exhibit flicker?

**Comment by xmehaut** [comment]
hi
i experiencing the same behavior on tablet or mobile (here iphone and ipad), which doesn't occur for instance with mdl or boitstrap.
It happens on many widgets, especially checkbox, slider, buttons, scrolling, ...

**Comment by specimen151** [comment]
When I tested it last, it was on the semantic-ui website. Most pages,
especially longer pages with more components, had flicker. It seemed to me
that SUI was just slower compared to other frameworks (big and small), and
that's why the flicker came. I was using iPhone 6 at the time, with the
newest iOS always.

Just tested now, and the front-page www.semantic-ui.com has the flicker.
iPhone 6, newest iOS. Need to "flick" to scroll fast to get the problem.
Could be lazy loading maybe? So that if I scroll too fast, then it needs to
build the part of the page that was previously hidden? I wouldn't react if
it wasn't that I didn't see the same problem in e.g. bootstrap.

**Comment by carlosgoce** [comment]
Hello,

i am using an iPad and I was reading the docs, evaluating if I should choose Semantic UI for my next project, and I am having the same issue. Is extremely buggy and the feeling is that the website is broken.

Like this URL: https://semantic-ui.com/introduction/new.html
