### ISSUE TITLE
Request: Additional Tag Label

### ISSUE THREAD

**Issue by wetux** [Semantic-Org/Semantic-UI#2111]
Can we have this additional tag labels ?

Example:
![Tag Label](http://i.imgur.com/O480u0Y.png)

and

![Tag Labels](http://i.imgur.com/phDrrmG.png)

http://www.cssflow.com/snippets/sliding-tags

**Comment by jlukic** [comment]
I like those. Trying to get `2.0` out the door, but could see this as an addition like `animating button`.

**Comment by wetux** [comment]
Very nice, thank you.
