### ISSUE TITLE
[API] Globally pre-process ajax response

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2112]
Hi,

I would like to globally pre-process ajax response from the server (much like it's done with ```$.ajaxSetup``` in jQuery). I've read that this can be achieved with ```$.fn.api.settings``` and so I added the following code in my body:

```javascript
$(function() {
    $.fn.api.settings.onComplete = function(response, element) {
        console.log('onComplete fired');
    };
});
```

However, I does not seem to work for me. What am I doing wrong?

**Comment by jlukic** [comment]
`onComplete` is working as you used it. 
http://jsfiddle.net/qun8fmj3/

If you want to pre-process before sending to server, `beforeSend` allows you to cancel requests and adjust url path and settings, and `beforeXHR` allows you a "last chance" to adjust the payload. 

If you are looking to pre-process xhr response before onSuccess/onFailure, then perhaps #2092 is what you're looking for. 

In the future please include a jsfiddle reproducing your issue, this helps me tackle bugs more efficiently when maintaining the library.

**Comment by andreyvk** [comment]
My apologies. I guess I've made a mistake somewhere on the way there. Will include the fiddle next time. Cheers
