### ISSUE TITLE
[Progress] Add Segmented Progress Bar 

### ISSUE THREAD

**Issue by mstnorris** [Semantic-Org/Semantic-UI#2115]
If possible, I would like a segmented progress bar.

Thank you for producing this library, there are so many more controls than Bootstrap.

**Comment by jlukic** [comment]
Thanks for the suggestion

**Comment by lubber-de** [comment]
@mstnorris Perhaps the `multiple progress`, available since Fomantic-UI 2.7.4, is the desired feature you are searching for?
https://fomantic-ui.com/modules/progress.html#multiple-bars
![image](https://user-images.githubusercontent.com/18379884/57161521-1d223000-6dec-11e9-92a2-f7a9e311f7cc.png)
