### ISSUE TITLE
Rise of HTML5 and better documentation.

### ISSUE THREAD

**Issue by Announcement** [Semantic-Org/Semantic-UI#2116]
From a design standpoint Semantics looks really nice ( other than the buggy sidebar )
the code could be a lot better if we'd stop with the "tag agnostic" design and used proper html 5 tags for things. 

Also trying to find out what I'm doing is a nightmare. The documentation is practically useless, I ended up just looking at the source and modifying things for now, which is definitely not ideal. 

Also on the feed example one of the tabs has a pop out but instead of doing that it puts a scroll bar at the bottom of the sidebar and you have to scroll to see it... that just doesn't feel right at all.

Sorry if what I'm saying has already been said or cleared up, I'm just new and frustrated... please help?

**Comment by ph7vc** [comment]
Since everything is tag agnostic, you should be able to use whatever html5 tag you want to represent what you need.

**Comment by Announcement** [comment]
Just saying span class item is worse than just li

**Comment by jlukic** [comment]
This is an issue i've talked about for several years, and am passionate about. Check   https://github.com/Semantic-Org/Semantic-UI/issues/1070#issuecomment-55134853 and other related responses on GitHub issues. 

My interest is in [semantics](http://plato.stanford.edu/entries/montague-semantics/) and [descriptive linguistics]((http://instruct.westvalley.edu/lafave/DFW_present_tense.html)), this is a project about a different way to understand usage, as the conventions created by a group of language speakers (read programmers) and not prescription from authority, like the Technical Architecture Group (TAG) at the W3C.
