### ISSUE TITLE
Vertical alignment issue when using checkbox and input[type=text] side by side

### ISSUE THREAD

**Issue by drepo** [Semantic-Org/Semantic-UI#2118]
When a `checkbox` field and an `input[type=text]` field are nested within a`.fields` container, The vertical alignment breaks and the checkbox input appears aligned with the label of the text field. 

PS: A code sample to reproduce the error - https://jsfiddle.net/z2o1ecqv/embedded/result/

**Comment by jlukic** [comment]
Hi, checkboxes are inline fields and probably shouldnt be aligned with fields that include their label on top. 

If you wanted to do this you could try something like 
https://jsfiddle.net/wqv1tmgm/

**Comment by quanganhtran** [comment]
Hello, but even when no label is present, the shorter height of checkbox component compared to the input (with input box, when not `transparent`) would make them appear not to be vertically aligned (by the base of the letters)
