### ISSUE TITLE
Issue with simple dropdown menu inside vertical menu

### ISSUE THREAD

**Issue by glen-84** [Semantic-Org/Semantic-UI#2119]
See: http://jsfiddle.net/rjx4qmsv/

Place your mouse cursor over "Tags" (h2), and then move it in a downward direction. The drop down menu will be displayed, because it has a border which is hidden with `opacity: 0`.

Does it not make more sense to use `display: none`?

**Comment by jlukic** [comment]
Hi, `2.x` branch does not show your issue with the `ui menu` rewrite.
http://jsfiddle.net/bhgbfshf/

In order for css opacity transitions to work they must occur from an element with already has display. This is why we place a simple dropdown offstage using `left` instead of using `display: none`

**Comment by glen-84** [comment]
Thanks Jack! :smile:
