### ISSUE TITLE
[UI] State Control

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#212]
## State

State is a simple state machine for controlling the look and feel of an element based on what state it occupies. For example, changing the text of a button from `follow` to `following` on a successful API action

https://github.com/jlukic/Semantic-UI/blob/master/src/modules/behavior/state.js
### Required for launch
- Create documentation
- Create examples
- Minor code retooling
### Required for 2.0

TBD

**Comment by tmikaeld** [comment]
I was looking for a way to trigger button states without manipulating classes and this seems to be it. 

- Will the state module be independent from the API or will they always be intertwined?
- Any ETA on this or are it subject to change?

**Comment by jlukic** [comment]
This is complete, just not documented. 

It can work independently of API. See settings object at bottom of `state.js` in src for an idea about config.
