### ISSUE TITLE
Form validation cancels React.js onSubmit

### ISSUE THREAD

**Issue by ticup** [Semantic-Org/Semantic-UI#2120]
Hi,

When I use form validation on my form, it doesn't trigger the React.js onSubmit anymore.
My guess is that in general, more semantic ui js events might cancel the React.js events.

Here is a small test case. If you remove the form validation, you'll see it does trigger the onSubmit, but it doesn't with the validation: https://jsfiddle.net/zza2furx/7/

```
var FormBox = React.createClass({
  handleSubmit: function (e) {
      e.preventDefault();
      alert('it works');
  },
  componentDidMount: function () {
      $('form').form({
      foo: {
                    identifier  : 'foo',
                    rules: [
                        {
                            type   : 'empty',
                            prompt : 'Please enter your foo'
                        }
                    ]
                },
      },
      {inline: true,
      on: 'blur'});
  },
  render: function() {
    var user = this.props.data;
    return (
   <form className="ui form" onSubmit={this.handleSubmit}>
   <input name="foo" type="text" placeholder="enter text"/>
   <button className="ui primary submit button"> submit</button>
   </form>
    );
  }

}); 
React.render(<FormBox />, document.body);
```

Not sure if this is React.js' fault or semantic's, but my guess it's on semantic's side and the way that they trigger the submit of the form?

Thanks

**Comment by kevinptt0323** [comment]
Maybe you can use callback ``onSuccess`` provided by Semantic-UI.
For example: ``onSuccess: this.handleSubmit``
See more: http://semantic-ui.com/behaviors/form.html#callbacks

**Comment by ticup** [comment]
Oh that's true. Thanks for that Kevin.
Maybe it's not a bad idea to consider triggering the default onsubmit when the validation succeeds?

**Comment by jlukic** [comment]
Form validation attaches itself to `onsubmit` and will trigger it on succesful validation as long as `onSubmit` does not return false.

**Comment by SimonXianyu** [comment]
It seems that event's method preventDefault()   can be used to cancel event.

example:
 handleSubmit: function(e) {
    if (!$('#loginForm').valid()) {
      e.preventDefault();
    }
  }
