### ISSUE TITLE
Form Validation code in javascript is imported twice

### ISSUE THREAD

**Issue by kevinptt0323** [Semantic-Org/Semantic-UI#2122]
In semantic.js, the "Form Validation" part is imported twice.
In https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/defaults.js line 68 and 102.

**Comment by jlukic** [comment]
This code is just used for the file glob that matches against files when running `gulp build` it will not cause it to import twice.

**Comment by kevinptt0323** [comment]
But I see form validation in semantic.js twice, indeed.
Start from https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js line 498 and 16042.
Maybe it doesn't cause any bugs.

**Comment by jlukic** [comment]
Well that is weird. Thanks

**Comment by jlukic** [comment]
Here's the fun file glob thats created

Here's the offending code

```bash
gulp.src(source.definitions + '/**/' + globs.components + '.js')
  .pipe(plumber())
  .pipe(flatten())
  .pipe(replace(comments.license.in, comments.license.out))
  .pipe(gulp.dest(output.uncompressed))
  .pipe(gulpif(config.hasPermission, chmod(config.permission)))
  .pipe(print(log.created))
  .pipe(uglify(settings.uglify))
  .pipe(rename(settings.rename.minJS))
  .pipe(gulp.dest(output.compressed))
  .pipe(gulpif(config.hasPermission, chmod(config.permission)))
  .pipe(print(log.created))
  .on('end', function() {
    gulp.start('package compressed js');
    gulp.start('package uncompressed js');
  })
;
```

And the file glob that creates the mess
```bash
src/definitions/**/{reset,site,button,divider,flag,header,icon,image,input,label,list,loader,rail,reveal,segment,step,breadcrumb,form,grid,menu,message,table,ad,card,comment,feed,item,statistic,accordion,checkbox,dimmer,dropdown,modal,nag,popup,progress,rating,search,shape,sidebar,sticky,tab,transition,video,api,form,state,visibility}.js
```

Surprisingly including a value in a globs bracketed section `{}` twice will actually cause the file to match twice.
