### ISSUE TITLE
Full Height Columns

### ISSUE THREAD

**Issue by mbpakalin** [Semantic-Org/Semantic-UI#2125]
Hello,
First of all thanks for the this awesome project.
I'm using code like that, i just want to make the this two column full height.
I'm new at grid systems i don't know how its done.
My Code:

    <div class="ui two column row vertically padded grid">
    <div class="four wide column" style="background:red;">
        left_menu
    </div>
    <div class="twelve wide column" style="background: blue;">
        content
    </div>
</div>

Thanks

**Comment by jlukic** [comment]
in `1.x` you can use `equal height` in `2.0` it is default.

**Comment by devsli** [comment]
Thanks @jlukic! It's elegant solution if you want to make columns _equal_ size.

If you need _full_ height column instead - you could either [try `stretched` class](http://semantic-ui.com/collections/grid.html#stretched) or set `min-height` to 100%.

```css
.ui.grid {
	min-height: 100%;
}
```
