### ISSUE TITLE
Is there a datetime picker?

### ISSUE THREAD

**Issue by neo20** [Semantic-Org/Semantic-UI#2126]
just like http://jqueryui.com/datepicker

**Comment by zelenin** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues?utf8=%E2%9C%93&q=is%3Aissue+datepicker

**Comment by namelysweet** [comment]
I use this 
https://github.com/xdan/datetimepicker 

for the screenshot 
https://raw.githubusercontent.com/xdan/datetimepicker/master/screen/1.png
https://raw.githubusercontent.com/xdan/datetimepicker/master/screen/2.png
https://raw.githubusercontent.com/xdan/datetimepicker/master/screen/3.png
https://raw.githubusercontent.com/xdan/datetimepicker/master/screen/4.png

**Comment by jlukic** [comment]
Please continue discussion in #191
