### ISSUE TITLE
[Search] Dont Require Matching on Title

### ISSUE THREAD

**Issue by fbsstar** [Semantic-Org/Semantic-UI#2128]
I am writing a app to find location matched with items in the database.  I use search component to let customer to choose which one you want to show on the map.  However, the search content might have  many items with same title but with different description like
[{
title: "York"
"description": "York->USA"
},{
title: "York"
"description": "York->York->USA"
}
]

When I override onSelect function, I always get first one no matter which one I click on.  I have a look at the code, find that it will return the item by finding title in results. However, the title is same, so it always return first item.  

Is there any way I could know which one I really click ?

**Comment by jlukic** [comment]
It's matching against the original JSON based on title, since the server response doesn't require any unique id.

**Comment by jlukic** [comment]
This has been fixed in `2.0`. Matching no longer uses `title`. See other related threads from commit.
