### ISSUE TITLE
Create a ajax call to auto complete select

### ISSUE THREAD

**Issue by tallesdantas** [Semantic-Org/Semantic-UI#2129]
I'm trying to make a search with auto complete but its not working my js code is:

$('.ui.search')
    .search({
     debug: true,
      apiSettings: {
        action:'search',
        url: '/chat/addamigo/cod/{query}'
      },
    })
  ;
the return of the call is:

[{"title":"taaaaaalles","description":"552eecea80bc7be41a00002d"}]
and the html is:

<div class="ui search">
                    <input class="prompt" type="text" placeholder="... etc" >
                    <div class="results"></div>
                </div>
but it keeps showing me the blank message

"No Results Your search returned no results"

what can i do to create an ajax auto complete in semantic

**Comment by jlukic** [comment]
the call needs to wrap this in a `results` property of a JSON object.

**Comment by tallesdantas** [comment]
How, can i do this?,  please help,  im newb at semantic ui.,  where do i
put the callback.
Em 16/04/2015 13:12, "Jack Lukic" <notifications@github.com> escreveu:

**Comment by Einkoro** [comment]
http://semantic-ui.com/modules/search.html#/usage

Check the Server Responses section. Your /chat/addamigo/cod/{query} route will need to return a JSON response like:
```
{
  "results": [
    {"title":"taaaaaalles","description":"552eecea80bc7be41a00002d"}
  ]
}
```

**Comment by jlukic** [comment]
Try out stackoverflow or google group for help. This is not the appropriate channel.
