### ISSUE TITLE
[Question] No border radius

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#2130]
Hi,
Congrats for the elegant framework.
I have this project where i don't need rounded corners, so i made a class that sets the border radius to 0 in all of it's children.
Wouldn't be better if this was included in the framework ?

**Comment by jlukic** [comment]
You can set default border radius across all UI with one global variable.

Add this to  `/src/site/global/site.variables`

```less
@defaultBorderRadius: 0em;
```

**Comment by shadoWalker89** [comment]
Yes,
But sometimes within the same project, we need some items with rounded corners and others without rounded corners.
Having this class built in is a little nice feature.

**Comment by jlukic** [comment]
I dont think this makes sense to add for everyone. You can also specify border radius on a UI level.

**Comment by jloveric** [comment]
I'm running into the same issue.  I think a good example is a header in a phone application.  If it's black you see small corners of white due to the rounding, whereas elsewhere (buttons for example) the rounding is fine.  In my case, I somehow need to fix the header.
