### ISSUE TITLE
I find a new Website for Semantic templates, snippets and examples

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2132]
Hi,

I find a NEW Website for Semantic templates, snippets and examples:

http://www.semantickit.com

It looks like an Official website, is it related to you ?

**Comment by jlukic** [comment]
This is not an official website.

**Comment by ikourfaln** [comment]
I see, I checked the about page:
made by: Will Wallace and Travis Valentine

They said:

"SemanticKit would not be possible without Jack Lukic and the many contributors behind Semantic UI"

and I agree
