### ISSUE TITLE
[Validation] RegExp pattern validator.

### ISSUE THREAD

**Issue by morteza** [Semantic-Org/Semantic-UI#2133]
Any plan to add a validation rule to test by a custom regexp (just like html5 pattern attribute)? I've looked at the codes and recent commits for v2 and could not find anything.

Anyway, I've added the following rule to the `form.js` rules.

```js
// value match a pattern
pattern: function(value, text) {
  var
    patternRegExp = new RegExp(text, "")
  ;
  return patternRegExp.test(value);
}
```

Here is a sample to validate a value using this rule:

```js
title: {
  identifier: 'research.title',
  rules: [
  {
    type: 'pattern[^[a-z0-9_]{2,}$]',
    prompt: 'Invalid title.'
  }
  ]
}
```

Some further tests might be necessary to validate the extra parameter.

**Comment by iagomelanias** [comment]
+1

**Comment by jlukic** [comment]
Added

**Comment by jlukic** [comment]
f552fdb90fd8aaeb986c289657a9145e897ce4e6

**Comment by jlukic** [comment]
Moved all regexp used by matching functions to an object, and added a regExp matcher.

I've also verified rules with bracketed expressions still work correctly.
