### ISSUE TITLE
Dropdown goes blank after choose 2 times the same option using the search

### ISSUE THREAD

**Issue by iagomelanias** [Semantic-Org/Semantic-UI#2134]
I recorded a video to explain:

![semantic-dropdown-bug](https://cloud.githubusercontent.com/assets/6279712/7198880/6d04f660-e4c6-11e4-8d0f-97ab88a931e2.gif)

**Details:**
* I'm using the dropdown shown in the documentation of the Semantic UI: http://semantic-ui.com/modules/dropdown.html, "Search Selection".
* SO: Ubuntu 14.04 LTS
* Browser: Google Chrome 42.0.2311.90 (64-bit)
* Date of the test: 04/17/2015, 05:55 UTC-3
* This happens in any website i tested and any dropdown with search i tested.

Also, great job! I'm really appreciating the framework and also saving much time.

**Comment by jlukic** [comment]
This looks to be fixed with multiselect rewrite in beta, but not in `1.x`
http://beta.semantic-ui.com/modules/dropdown.html#search-selection

**Comment by iagomelanias** [comment]
Thank you.

There is any information about the 2.0 version, as release beta date or new features?

**Comment by jlukic** [comment]
Sitting at around 140 new things, see notes here
https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md

**Comment by iagomelanias** [comment]
Thank you for the support, Jack!
