### ISSUE TITLE
[Search] Highlight search query matches in results

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2135]
It would be incredibly awesome if search matches were highlighted in the results, much like how typeahead.js works. There should also be an option to enable / disable it. Since this is an essential feature in the project I'm working on, I may try implementing it myself in the next several days.

![screenshot 2015-04-17 09 47 07](https://cloud.githubusercontent.com/assets/823545/7203175/ccb8146e-e4e6-11e4-8ede-17c95f0964ee.png)

**Comment by jlukic** [comment]
I think this is a great idea as a setting.
