### ISSUE TITLE
[Form] Some styles for input don't work in .ui.form

### ISSUE THREAD

**Issue by kevinptt0323** [Semantic-Org/Semantic-UI#2137]
Some styles for input don't work in .ui.form.
http://jsfiddle.net/0f0h100x/1/
I'm not sure whether this is a feature or not.

**Comment by jlukic** [comment]
It seems some input defaults from `ui form` take precedence. Inputs can receive error styling by adding `error` to field. 

Transparent inputs appear correctly nested inside from in next
http://jsfiddle.net/h0t06hf0/
