### ISSUE TITLE
Dropdown multiselect don't show tags after save

### ISSUE THREAD

**Issue by zuher83** [Semantic-Org/Semantic-UI#2138]
Hi,
The problem with multiselect, after save a form, the field becomes empty.
Yet the data are well recorded.

How can I solve this problem?

Thanks

![capture1](https://cloud.githubusercontent.com/assets/8025881/7210327/22059f3a-e551-11e4-8045-ffd7b0ed5730.JPG)
![capture1-1](https://cloud.githubusercontent.com/assets/8025881/7210330/27172318-e551-11e4-8c8e-f12a436af54c.JPG)

![capture2](https://cloud.githubusercontent.com/assets/8025881/7210334/2ae122aa-e551-11e4-97bf-3a47ca30d088.JPG)

**Comment by jlukic** [comment]
I'm still working on this daily.
Can you confirm this is still a bug in latest in `next`
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js

**Comment by zuher83** [comment]
Hi,
Yes I confirm this latest "next".

http://jsfiddle.net/gk0shfuu/

The problem, after the save the form it doesn't reload the selected options. Yet the given are properly saved in database.

After saving the form, when the page reload <select><option  selected = "selected" ......> attribute is written.

Thank you

**Comment by jlukic** [comment]
This appears to be a bug with matching against non string values with multiselect

$('select').val(); on a select multiple will always return the string value, i.e. "4" instead of 4

**Comment by jlukic** [comment]
Check against the latest next in your  codebase. I believe it should be fixed.

**Comment by zuher83** [comment]
You are fabulous !!!
Fixed
