### ISSUE TITLE
[Search][next] onSelect only returns all results instead of selected result

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2139]
The onSelect callback currently seems to only have access to all of the search results and the element `.search` is called on, but not the specific result element or specific result object selected (ie. clicked on). 

This might be a bug with [`module.get.result`](https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/search.js#L142), or I may be misunderstanding the intended behavior. But nonetheless, there is currently no way to get the selected element or the select result object from the arguments passed to the callback.

**Comment by jlukic** [comment]
Can you provide an example using the next jsfiddle

**Comment by jlukic** [comment]
Derp mistake in rewrite
http://jsfiddle.net/he6q9981/

**Comment by mnquintana** [comment]
I'm still getting `undefined` for the first argument (`result`) on the latest commit of `next`. I'm working on a test case now.

**Comment by mnquintana** [comment]
It seems that using a `mockResponse` produces the expected behavior, but using a real remote doesn't. Still investigating.

**Comment by mnquintana** [comment]
@jlukic Here's a test case: https://jsfiddle.net/wisew/Lp4gvvcr/

`result` in the `onSelect` callback always returns `undefined`.

**Comment by jlukic** [comment]
Fixed example
http://jsfiddle.net/haob052y/
