### ISSUE TITLE
Cards - Now with flexbox? IE9 support?

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#2140]
I am using the older card.css which doesn't use flexbox - works on IE9 - now with the new cards I'm afraid to upgrade - any fallback?   Testing on IE10 and changing to browser mode for IE9 seems to work, but I am not sure if the real IE9 will work

any suggestions or fallback solution will be helpful or should I just no upgrade

**Comment by jlukic** [comment]
IE9 is no longer supported.

**Comment by emage** [comment]
:(  ok
