### ISSUE TITLE
Content Horizantally Overflow

### ISSUE THREAD

**Issue by mbpakalin** [Semantic-Org/Semantic-UI#2141]
Hello,
I'm trying to solve grid system and i had a problem like this.
My Code is like that:

    <div class="ui two column grid">
    <div class="column" style="background:red;"></div>
    <div class="column" style="background:blue;"></div>
    </div>

And it overflows horizantally, you can see in https://data.mbpakalin.net/test/grid.html

If i can do ;

    body { overflow-x: hidden }
it solves but still content overflows :/

Sorry for my english.

**Comment by jlukic** [comment]
See #1931 Use a `horizontally padded grid`
