### ISSUE TITLE
Push Sidebar Style Tag Bug

### ISSUE THREAD

**Issue by oniisaki** [Semantic-Org/Semantic-UI#2143]
On semantic UI version 1.12.0, it seems if I use the "title" attribute for any of my css style tags, it would break the sidebar top push effect measurements. It still pushes, but the sidebar would cover some of the pusher content, and only "slightly" pushes the content down.

Here is the reproduced code.
http://jsfiddle.net/qw6L1g77/2/

**Comment by jlukic** [comment]
That's a bug. It should only remove style with matching title

**Comment by jlukic** [comment]
For some reason having no title on the injected style causes it to work again. No clue, but fixed in `2.0` channel.

**Comment by jlukic** [comment]
http://jsfiddle.net/j5uqr2oL/
