### ISSUE TITLE
Top Sidebar Visible Class Behaviour

### ISSUE THREAD

**Issue by oniisaki** [Semantic-Org/Semantic-UI#2144]
When top sidebar is set to have the "visible" class straight off, it has the behavior where it doesn't push content and covers it, unlike the horizontal sidebars.

http://jsfiddle.net/p8eoj7sm/1/

**Comment by jlukic** [comment]
There are currently any predefined size variations for `top` and `bottom` sidebar. Visible on load sidebars work off predefined offsets defined by size.

**Comment by oniisaki** [comment]
Just an update on the solution jlukic hinted out.
Decided not to use CSS method that requires specifying the sidebar height before hand.

Used JQuery onload instead to dynamically adjust to sidebar height:
http://jsfiddle.net/63Lts4v7/2/

JQuery Code w/o Comments:
````
function getTransform(el) {
	var results = $(el).css('transform').match(/matrix(?:(3d)\(\d+(?:, \d+)*(?:, (\d+))(?:, (\d+))(?:, (\d+)), \d+\)|\(\d+(?:, \d+)*(?:, (\d+))(?:, (\d+))\))/)

    if(!results) 
		return [0, 0, 0];
    if(results[1] == '3d') 
		return results.slice(2,5);

	results.push(0);
    return results.slice(5, 8);
}

$('.sbb').on("click", function()
{
	$('.sidebar')
	  .sidebar('setting', 'transition', 'push')
	  .sidebar('toggle')
	;
});
var tsh = $(".top.sidebar").innerHeight();

var xyzArray = getTransform($(".pusher"));
var x = parseInt(xyzArray[0]);
var y = parseInt(tsh);
var z = parseInt(xyzArray[2]);

var test = $(".pusher").css("transform", "translate3d("+x+"px, "+y+"px, "+z+"px)");
````

**Comment by jlukic** [comment]
Another option is just to call the internal behavior that adds the offset css.
http://jsfiddle.net/3vszfmzw/

```javascript
$(.ui.sidebar').sidebar('add body CSS');
```

**Comment by oniisaki** [comment]
@jlukic
Both mine and your method apparently worked on JSFiddle, but when I copied and tested it under a html file, it does not seem to work as expected **most** of the time, due to Semantic UI sidebar code apparently adjusting it's final height too late.

That is, code is getting the wrong sidebar height value due to incorrect loading order.

Need an event that fires after the top sidebar gets it's final height.
Tried Semantic UI's onShow & onVisible property, but it doesn't seem to fire with a visible top sidebar after it finishes loading. Also tried JQuery's $(document).ready(), but that also seems to fire before sidebar is completely loaded.

At this point, my solution was to use setTimeout function to force the code to run after the sidebar get its final height, which isn't a good solution:
````
	setTimeout(function()
	{
		$('.ui.sidebar').sidebar('add body CSS');
	}, 500);
````

**Comment by jlukic** [comment]
If your sidebar has image content you probably need to wrap it in document load. 

```javascript
$(window).load(function() {
  $(.ui.sidebar').sidebar('add body CSS');
});
```

**Comment by oniisaki** [comment]
Thanks jlukic, your a great help.
That was apparently the problem. Had an image added there in the sidebar.
Embarrassingly, I didn't know the difference between $(document).ready() and $(window).load().

**Comment by oniisaki** [comment]
The below code no longer works in new versions of Semantic UI (I tried it with 2.1.7):
  $(.ui.sidebar').sidebar('add body CSS');

Are there any equivalent code with new semantic UI versions?

**Comment by oniisaki** [comment]
Figured it out it was changed to:
`$('.ui.sidebar').sidebar("add inlineCSS")`

The Semantic UI sidebar documentation needs to be updated from "add body CSS" to "add inlineCSS".
http://semantic-ui.com/modules/sidebar.html#/usage
