### ISSUE TITLE
[next] Let menu/button/etc. font inherit from body?

### ISSUE THREAD

**Issue by glen-84** [Semantic-Org/Semantic-UI#2145]
Is it possible to let element fonts inherit from body by default? Right now, each element is re-setting the font to Lato, so I can't change it in one place (without a custom build).

**Comment by jlukic** [comment]
If you're changing the default fonts you should probably be using a custom build, otherwise it'll pull Lato from google fonts without being used.

**Comment by glen-84** [comment]
That's true.

I was trying to avoid a custom build, but I also want the GitHub theme as a base, so I guess I need to figure out a way to set up custom builds while still utilizing NPM or JSPM (if that's even possible).

**Comment by jlukic** [comment]
NPM works with custom builds.
