### ISSUE TITLE
Scroll not available on top overlay sidebar.

### ISSUE THREAD

**Issue by rlora** [Semantic-Org/Semantic-UI#2147]
When the content of a top overlay sidebar exceeds the window height, it is not possible to scroll to the bottom. And it might not be possible to close the overlay at all.

Example: http://jsfiddle.net/k44zcd65/2/

I think I'm missing something, because right/left sidebars seem to work properly.

**Comment by jlukic** [comment]
Top and bottom sidebars should have a maximum height of `100vh/100%`

**Comment by jlukic** [comment]
Fixed in `2.0` branch

**Comment by jlukic** [comment]
Fiddle showing behavior in `2.0` http://jsfiddle.net/5bmq9jtq/

**Comment by rlora** [comment]
Awesome, thank you very much @jlukic.
