### ISSUE TITLE
[1.12.0] menu issue with Chrome (latest, 42)

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#2148]
I wonder if this is a bug in the latest Chrome browser or SUI 1.12.0. 
Try this:
1. Do Ctrl-I and  switch your desktop Chrome browser to mobile mode (for example - pick Apple 5 emulation)
2. Go to stocks4grab.com
3. From the let top sandwich menu item, select Help

What you'll see is the menu bar only contains the sandwich item to the left.

4. Now slightly re-size the "mobile" frame. What happens is that to the right side of the menu bar you will see a search and login items "automagically" appear?

The issue is that the search and login items should have been there without the need to resize.

I think this is some kind of bug, because:
1. This never happens in Chrome desktop mode, only in mobile mode emulation. I can confirm that the glitch is present when browsing with real Android device, though.
2. This never happens in Firefox.

Any clue?

**Comment by jlukic** [comment]
That's very odd. Sorry you're having this issue. I've never heard anything like it. 

You may want to try against `2.0 beta` version that includes a rewritten `menu`
http://beta.semantic-ui.com/collections/menu.html
