### ISSUE TITLE
Prevent modal onApprove from firing if buttons have .disabled class

### ISSUE THREAD

**Issue by brendon** [Semantic-Org/Semantic-UI#2149]
I noticed that even if I disable the modal action buttons, they'll still trigger `onApprove` etc...

Would it be a good idea to check that the `.disabled` class isn't applied to the button before triggering `onApprove` and `onDeny`?

**Comment by brendon** [comment]
A quick solution is to augment the selectors:

```
selector:
        approve: '.actions .positive:not(.disabled)'
```

etc...

**Comment by jlukic** [comment]
You can also change the onApprove callback to return false if they have class disabled.

**Comment by brendon** [comment]
That's true, this just seems like it'd be as reasonable a default as the current default approve and decline buttons.
