### ISSUE TITLE
Button in groups are not set as active 

### ISSUE THREAD

**Issue by gabro** [Semantic-Org/Semantic-UI#2150]
In the documentation examples, when I click on a button within a group it becomes `active`.

I can't seem to reproduce the same behavior. I'm using Semantic 1.12.0, here's a fiddle: http://jsfiddle.net/mvmakmqb/

**Comment by jlukic** [comment]
It's just custom javascript. Anything that adds class `active` to the element will do.

**Comment by gabro** [comment]
Oh, thanks, I thought it was provided by semantic.

~ gabriele
