### ISSUE TITLE
Table cell BG color is cleared in mobile size

### ISSUE THREAD

**Issue by mietek** [Semantic-Org/Semantic-UI#2153]
#### Expected result
Table cell BG color remains the same whether in mobile or non-mobile size.

#### Actual result
Table cell BG color is cleared in mobile size.

#### Reproduction
Look at the [Positive / Negative section](http://semantic-ui.com/collections/table.html#positive--negative) of the Semantic UI Table page in a mobile-sized browser.  The backgrounds of the "None" and "Requires call" cells, normally green and red, will be transparent.  Color will be inexplicably restored on hover.

**Comment by jlukic** [comment]
This is because stacked tables use padding on first and last column, which is incompatible with table cell background colors (will appear stretched if first or last row).

There is probably a better solve. I havent looked at this in about a year.

**Comment by jlukic** [comment]
Fixed in `2.0`
