### ISSUE TITLE
Fixed-width column for the grid

### ISSUE THREAD

**Issue by stagor** [Semantic-Org/Semantic-UI#2154]
Hello,

Could you help me to find out how this can be implemented in Semantic-UI? I would like to have a fixed-width column in the grid as I do not want my content to shrink when the website is viewed on a smaller devices. I want to have one column that is not responsive with a constant width. Are there any example with this?

Thank you.

**Comment by jlukic** [comment]
I think this is a use case where its perfectly appropriate for you to specify your own custom css. 

In `2.0` `container`s will be added which make `ui grid` fixed width across a device (as oppose to the fluid width of `page grid`) which might make your life simpler.

**Comment by stagor** [comment]
Thank you for your reply.
