### ISSUE TITLE
Web site issues

### ISSUE THREAD

**Issue by oytunistrator** [Semantic-Org/Semantic-UI#2155]
Some icons problem with Safari on your site: http://goo.gl/UfSj0Y
Facebook icons doesn't show and right sidebar is very small.

My safari version: 8.0.5 (10600.5.17)

**Comment by jlukic** [comment]
Are you using an adblocker? I've noticed they like to block social icons.

**Comment by oytunistrator** [comment]
Thanks for help. I removed extensions.
