### ISSUE TITLE
List item link button text with wrong color.

### ISSUE THREAD

**Issue by ahtinurme** [Semantic-Org/Semantic-UI#2157]
If you create a list with a item that's content is a button, the button text color is always overrided (see the last button in this jsfiddle: http://jsfiddle.net/1512gb5m/3/ )

Solution would be to exclude the .ui.button types from override.

**Comment by jlukic** [comment]
Fixed in `2.0`

**Comment by ahtinurme** [comment]
Will this also be backported to 1.x? Since it's also broken there.

**Comment by jlukic** [comment]
No, everything is being lumped in together for a 2.0 release which will be in the next couple weeks.

**Comment by ahtinurme** [comment]
Good :+1:
