### ISSUE TITLE
Feature Idea / Request: Custom element wrappers for some of the modules

### ISSUE THREAD

**Issue by mmacaula** [Semantic-Org/Semantic-UI#2159]
Wanted to throw this out as idea, perhaps an 'integration'.  It's somewhat related to #1872, but without the shadow DOM.  I wrote a [blog post](http://michaelmac.org/semantic-ui,/custom-elements,/ampersand,/backbone/2015/04/08/custom-elements-to-solve-simple-problems.html) about this idea in much greater detail.  By only worrying about custom elements, you can reach a lot more production ready websites.

**Comment by jlukic** [comment]
Thanks for writing the article. I find this kind of component implementation quite compelling as a developer. Although some aspects of Shadow DOM seem, to me, a bit obtuse, the basic premise of elements as tags seems very reasonable and useful.

As a framework developer however, I'm still waiting for a sea change in adoption before I consider making the plunge for the library.

**Comment by mmacaula** [comment]
For me, it wasn't so much as being able to wrap elements as tags, for that, we'd need that shadow DOM to be really useful.  I was suggesting more that we take some of the modules that have javascript to add behavior and auto-initializing them when they're added as custom elements, the dropdown being a prime candidate.  Saves the developer from having to remember to call `.dropdown()` on the element.  

I'm thinking something like this would be an 'opt-in', almost a separate js file you could include which would auto-register the element.  To me, there could be two ways to (using the dropdown as an example) use the dropdown.  I can just make a div with a `ui dropdown` on it and then make sure i call `.dropdown()` on it, or I can just insert a `<semantic-dropdown>` tag and in 90% of the cases, that's all I need to worry about.  The code would be relatively small, as is the shim for custom elements.  I'll try to see if I can get a better working example than the one I have on the post.

**Comment by jlukic** [comment]
People have been asking about auto-init for a while so I can see the demand. Bootstrap has allowed this through a poorly performing [data api](http://getbootstrap.com/javascript/#js-data-attrs) which I did not want to emulate.

Part of the benefit of keeping initialization explicit in SUI means that the user is given full control of the life cycle of the element, which is usually an important thing when people are using SUI with Meteor, Ember, Angular, etc where this control must be left to the overarching framework. 

The other concern I have is that JS settings often come from other dynamic sources, AJAX, other javascript values, which cannot be passed in if the element auto-inits itself on insertion.

I think this would be a useful addition to the framework for those that prefer to use components as tags, but I dont know if it will become the primary *recommended* means of using Semantic UI, until this practice has more adoption and it can be considered a convention.

From watching Poylmer evolve over the last couple years, it seems like web components are a great approach in a 'walled garden' where you control every aspect of the code, but in a codebase that typically does not rely on web components it can be a bit jarring when only a small fraction of your codebase uses them.

**Comment by atomicpages** [comment]
I took a stab at writing polymer components for Semantic UI using Polymer 1.x. I was nearly able to finish the elements before Polymer 2.0 was released. Some issues I found are as follows:

* Polymer 2.0 uses Shadow DOM APIs which has significant limitations in terms of stylings
* Polymer 1.0 uses ShadyDOM out of the box which allows for external styles to "bleed in"

Consider the following Polymer 1.0 fragment:

~~~html
<dom-module id="polymer-button">
    <template>
        <div class$="ui {{size}} button">
            <slot></slot>
        </div>
    </template>

    <script>
    Polymer({

        is: 'semantic-ui-button',

        properties: {
            size: { type: String }
        }

    });
    </script>
</dom-module>
~~~

Using ShadyDOM, we can import `semantic.css` and go on our merry way; however, using Shadow DOM we run into issues where we're unable to style/access _inner_ elements of the custom element in the light DOM. I'll discuss this further...

Considering the following fragment in Polymer 2.0:

~~~html
<dom-module id="semantic-ui-button">
    <template>
        <div class$="ui {{size}} button">
            <slot></slot>
        </div>
    </template>

    <script>
        class SemanticButton extends Polymer.Element {
            static get is() {
                return 'semantic-ui-button';
            }
            static get properties() {
                return {
                    size: { type: String }
                };
            }
        }

        window.customElements.define(SemanticButton.is, SemanticButton);
    </script>
</dom-module>
~~~

Without using the ShadyDOM polyfill in Polymer 2.0, we're unable to allow styles to "bleed in" to the inner elements. The solution the Polymer team recommends is to use CSS mixins and variables:

~~~css
--button: {
    background: #ccc;
    border-radius: 4px;
    color: #444;
};
--button-big: {
    font-size: 5rem;
    padding: 6px;
    background: #76daff;
};
~~~

These mixins would ideally come as a port of Semantic UI, but then more issues arise when we need to pass variables into mixins:

> It’s a useful practice to pass variables to mixins depending on which applied rules may vary.
> Unfortunately it cannot be done for `@apply` rule as if you define it on a global scope (`:root`) it will always use variables only from that scope, so you cannot pass your local values.
> It’s sad, but at least you can copy/paste your mixins to your “scopes” using e.g. preprocessor and than your local CSS variables would work. &mdash; [Serg Hospodarets](https://blog.hospodarets.com/css_apply_rule#passing-variables-to-mixins)

There are some other alternatives I've considered:

* Importing external styles in the component
    * Polymer 2.0 seems to have an issue with this:

    ~~~html
    <dom-module id="semantic-ui-button">
        <template>
            <style>
                @import url('path/to/button.min.css');
            </style>
            <div class$="ui {{size}} button">
                    <slot></slot>
                </div>
        </template>

        <script>
        class SemanticButton extends Polymer.Element {
            static get is() {
                return 'semantic-ui-button';
            }
            
            static get properties() {
                return {
                    size: { type: String }
                };
            }
        }

        window.customElements.define(SemanticButton.is, SemanticButton);
        </script>
    </dom-module>
    ~~~

* Leverage something like [vulcanize](https://www.npmjs.com/package/vulcanize) to load styles during build time
    * This can lead to **very** large files that exist in the Shadow DOM each time the custom element is used.
    * Note: I have not tested this approach

-------

These are some of things I've found when attempting to make this feature happen. If anyone wants to check out my progress on the matter let me know and I'll make the repo public.

**Comment by slavap** [comment]
@atomicpages What exact issue Polymer 2.0 has with @import url('path/to/button.min.css') ?
