### ISSUE TITLE
Virtual Keyboard Input Mobile Safari 

### ISSUE THREAD

**Issue by Futurama56** [Semantic-Org/Semantic-UI#2160]
iOS has a nasty bug with Safari browser that shows a 3-5px gap between the input and the virtual keyboard.  You can notice this even on the semantic-ui website - and it's really messing with our sites too.  

Here is the issue : https://www.evernote.com/shard/s6/sh/890be8cd-2c28-472b-b358-cadcbd6a0e48/ac995645812468a155763e45dc6c48c2

To test, try 

.message_input{
position: fixed;
bottom: 0;
width: 100%
}

The only way we can fix this is by using a very bad / nasty css selector : then the problem disappears
    $('#message_input input').on('focus', function(event){
   $(window).scrollTop($(document).height() - 301);
    });

The value 301 - has to change depending on the screen size - so this is why we are writing for your help!  This is crazy.  I imagine we are not the only ones working with Safari that have seen this - 

Why does this only appear with semantic-ui (not bootstrap or native) and how do we get it fixed?

**Comment by jlukic** [comment]
I can see this bug occurring specifically on pages with a sidebar. I need to circle around on adequate fix.

**Comment by adrazich** [comment]
I'm seeing the same thing. I have a search bar on a sidebar (attached to the bottom of the screen) and when it opens the keyboard there is a ~10 px gap.

**Comment by v3rron** [comment]
same here...

**Comment by jlukic** [comment]
I haven't experienced this in IOS9 beta, hopefully should be remedied in Sep
