### ISSUE TITLE
search.onSelect fails to obtain `result` if searchFields is other than `title`

### ISSUE THREAD

**Issue by pokehanai** [Semantic-Org/Semantic-UI#2162]
While using `search` like the following, 
```js
var content = [{ title: 'foo', attr: 'bar' }];
elementSegment.search({
    source: content,
    searchFields: ['attr'],
    searchFullText: false,
    onSelect: function (result) {
        assert(result);   // fail
    }
});
```
search.onSelect fails to obtain `result` because it goes as:

a. item is matched by `attr`
b. click handler tries to obtain `result` by calling `module.get.result()` with `results` and `title` of selected element

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L150
```js
            click: function(event) {
              module.debug('Search result selected');
              var
                $result = $(this),
                $title  = $result.find(selector.title).eq(0),
                $link   = $result.find('a[href]').eq(0),
                href    = $link.attr('href')   || false,
                target  = $link.attr('target') || false,
                title   = $title.html(),
                name    = ($title.length > 0)
                  ? $title.text()
                  : false,
                results = module.get.results(),
                result  = module.get.result(name, results),
```

c. but in `result` function, it searches `title` in `searchFields`(it is [`attr`]) of each `results`

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L454
```js
          object: function(searchTerm, source) {
            var
              results         = [],
              fullTextResults = [],
              searchFields    = $.isArray(settings.searchFields)
                ? settings.searchFields
                : [settings.searchFields],
              searchExp       = searchTerm.replace(regExp.escape, '\\$&'),
              searchRegExp    = new RegExp(regExp.exact + searchExp, 'i')
            ;

            source = source || settings.source;

            // exit conditions on no source
            if(source === undefined) {
              module.error(error.source);
              return [];
            }

            // iterate through search fields in array order
            $.each(searchFields, function(index, field) {
              $.each(source, function(label, content) {
```

**Comment by jlukic** [comment]
Thanks for the  accurate description. I regret using lookup to grab the row for `onSelect` it should be stored in metadata when constructing the search results per element.

**Comment by pokehanai** [comment]
Yes, I totally agree with you and looking for the new design. :)

**Comment by jlukic** [comment]
I've add a mechanism to inject results into metadata when writing html. This occurs after templates generate html, so shouldnt disrupt anyone using custom templates. The results are now retrieved from metadata on click and not searched for across the result object.

I've preserved the `get results` method for looking up results, just in case users are using it externally. However this now works using a unique id generated by position. For simple results this is a results index, for category results its `A-Z` + position, i.e. "A0" is first result for the first category.

**Comment by jlukic** [comment]
Here's a fiddle using next
http://jsfiddle.net/cotqmo2n/
