### ISSUE TITLE
search.searchFields would contain `description` if setting.searchFields contains only one field

### ISSUE THREAD

**Issue by pokehanai** [Semantic-Org/Semantic-UI#2163]
when passing one `searchField`, search module looks up 'description', too.
```js
currentSegment.search({
    content: [{ title: 'foo', description: 'bar', attr: 'none' }],
    searchFields: ['attr']
});
```

that is result of how `$.extend()` works.

to pass more than one field is a workaround for the issue currently.
```js
currentSegment.search({
    content: [{ title: 'foo', description: 'bar', attr: 'none' }],
    searchFields: ['attr', 'attr']
});
```

**Comment by jlukic** [comment]
This is unintentional. Another option is to use 
```javascript
  currentSegment.search('setting', ['attr']);
``` 

after init since this replaces the value instead of extending the settings object.

**Comment by jlukic** [comment]
I've fixed this by calling a method `determine search fields` on init. 
https://github.com/Semantic-Org/Semantic-UI/commit/cbd8702b946d30dc719bca585db21497ee197fe0#diff-4e161c35adbd2f29fee16df255c9f359R109

**Comment by jlukic** [comment]
Example fiddle using `next`
http://jsfiddle.net/cotqmo2n/
