### ISSUE TITLE
[Tab] Setting for Parsing Scripts

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2165]
Hi,

When a **cached** tab is selected, it seems that whatever javascript is inside its content, it fires again. Here's the [fiddle](http://jsfiddle.net/andreyvk/fbge6ynp/).

**Steps to reproduce**
1. Fiddle loads, tab loads its ajax content and alert is displayed
2. Click on tab again and alert shows up

This does not, however, happen when tabs are not [AJAX loaded](http://jsfiddle.net/andreyvk/s5nbkj7t/)

**Expected result**
Well... JavaScript isn't executed again :)

**What to do?**
- Is this a normal behavior?
- If yes, then how to avoid it? When javascript re-executes, it screws my inner tab stuff and bound jQuery events stop working
- If no, then how can I go around for now?

**Comment by jlukic** [comment]
Both paths call `update content` internally which uses `html()` that parses `<script>` tags. The work around would to prevent script execution would be to swap for innerHTML.

I'll look into the best way of integrating this as a setting.

**Comment by jlukic** [comment]
The more I think about it caching should be a part of `api` instead of `search` and `tab` having its own implementation. Will look into revisiting that as well

**Comment by andreyvk** [comment]
Thanks! So this will be available from 2.0 and onwards only?

**Comment by jlukic** [comment]
It is available as part of 2.0. You can grab the source code from `dist/` in branch next
https://github.com/Semantic-Org/Semantic-UI/blob/next/dist/components/tab.js

JSfiddle of fixed version
http://jsfiddle.net/oatddfov/

And by the way, `2.0` has `mockResponse` and `mockResponseAsync` for faking AJAX data. Check out the fiddle.

**Comment by andreyvk** [comment]
:+1:  for ```mockResponse``` functionality. That saves some time on writing tests. And thanks again for the fix!
