### ISSUE TITLE
[Modal] IE11 scroll position

### ISSUE THREAD

**Issue by Drol** [Semantic-Org/Semantic-UI#2166]
Problem
Scroll position is moved to top in IE11 (possibly any IE version) when the modal is refreshed.

Steps to reproduce:
1. Open scolling modal on http://www.semantic-ui.com/modules/modal.html#/examples
2. Resize window or do something else that will trigger a modal refresh.

Expected
The scroll position should stay intact.

**Comment by jlukic** [comment]
Well that is weird. Thanks IE :wink:

**Comment by Drol** [comment]
Well, at least it works in project spartan ;-) /IE

**Comment by jlukic** [comment]
I have looked at this for a half hour and have no clue. If anyone has a lead on this please advise. As far as I can see it, IE is not correctly storing the scrollPosition when `overflow` changes on a container.

**Comment by Drol** [comment]
I didn't dive that deep in to the problem. It is a good start to know that much.

I guess in some situations it is a lot less annoying then others. For example when re-sizing the window.

We got bug reports from users when they were filling form inputs inside the modal and that is really annoying. So what we did as a workaround was to disable dom mutation observation of the modal subtree (modal.js#148)

`observer.observe(element, {
  childList : true,
  **subtree   : false**
});`

**Comment by Drol** [comment]
Won't that change have a lot of consequences? For example if the height of the modal content change to not fit on screen?

**Comment by jlukic** [comment]
Sorry for late reply. I believe having it 'opt-in' is an adequate solution for those who are loading content into modals after the fact.

**Comment by Drol** [comment]
Yeah I've been running the same change you did in 2.0 in 1.X and no problem so far.
