### ISSUE TITLE
How to automate build?

### ISSUE THREAD

**Issue by Hywan** [Semantic-Org/Semantic-UI#2170]
Hello :-),

I know this question has been opened several times here but I don't find the answer.
I have a specific `semantic.json` file. So far, I don't redefine anything in themes, I just select specific components. I have something that looks like this (generated automatically):
```json
{
  "base": "semantic/",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "rtl": "No",
  "components": [
    "reset",
    "site",
    "button",
    "header",
    "icon",
    "image",
    "input",
    "label",
    "list",
    "loader",
    "segment",
    "form",
    "grid",
    "menu",
    "message",
    "table",
    "checkbox",
    "dimmer",
    "dropdown",
    "modal",
    "progress",
    "transition"
  ],
  "version": "1.12.0"
}
```
Pretty classic.

I install Semantic UI by using NPM. So, I expect `npm install semantic-ui` to consider my `semantic.json` file and install only required components. In fact, I am still prompted to select components etc.

I saw in several issues that we must “mimic” the `semantic/` directory. What I don't know is: What to keep? What is regenerated? etc.

I experimented the gulp and tasks files are not regenerated. The `definitions/` directory must be present, but not filled if empty (whereas I expect my list of components to be installed). The `site/` directory must be present and commit, which is logical, along with the `theme.config` file. What about the `theme.less` file?

Actually, here is the workflow I would like to have:
```sh
$ npm install
$ make
```
where `make` will run `gulp build` in the correct directory to build the `semantic.*.js` and `semantic.*.css` files. I guess that's why we have a `semantic.json` file: To avoid being prompted each time we `npm install` and automate build.

Thank you for your project and your help.

**Comment by jlukic** [comment]
Check out the [readme in src](https://github.com/Semantic-Org/Semantic-UI/tree/master/src)

Current process is
```bash
npm install semantic-ui
# run post install scripts that generate semantic.json
cd semantic/
gulp build
```

You can read some more about theming on learnsemantic
http://learnsemantic.com/developing/customizing.html
http://learnsemantic.com/themes/overview.html

**Comment by Hywan** [comment]
So I must commit all the `semantic/` directory? I guess I can remove some themes. Thank you for your answer. Will try.

**Comment by jlukic** [comment]
Yeah, the additional themes should probably not be in the main package, but we don't have any theme dist setup yet.

**Comment by Hywan** [comment]
Got it. Thank you very much, very helpful :-).

**Comment by Hywan** [comment]
Any place where we could see all themes in action?

**Comment by jlukic** [comment]
Yes, semantic-ui.com 

Use the themes dropdown on each element page.
http://semantic-ui.com/elements/button.html

**Comment by Hywan** [comment]
Oh, I was expecting something like “All UI” with a dropdown button ;-). But nevermind, it's cool. Thanks.

**Comment by gabro** [comment]
Is there a chance to avoid versioning the whole `semantic` directory? I would really like to version exclusively my theme and let npm automatically handle the rest.

**Comment by jlukic** [comment]
Npm updates will leave themes alone that are not the default theme. You can add the other semantic paths to `.gitignore` if you would like to ignore them from your version control.

**Comment by gabro** [comment]
That's what I'm doing right now, however it's less than optimal since I have to include a few MBs in my version control, as opposed to a few KBs of my theme.
Anyway, thanks for the prompt answer :)

**Comment by sstok** [comment]
I can't give the Gulp file, but in a project I'm working for we solved this by using the less-only version and then copying the definitions and themes folder to `some-path/semantic` (where the semantic ui stuff lives) when running Gulp.

We only keep the site-theme and theme.config within in the repository `some-path/semantic` folder.
You only need the provided build system if you want to create a CSS-only version.
