### ISSUE TITLE
[Gulp] Add Source Maps

### ISSUE THREAD

**Issue by vikeri** [Semantic-Org/Semantic-UI#2171]
Hi!

Just wondering if there are plans for adding sourcemap support so that one could more easily debug the less code? I fiddled around and got it to work for the normal .css but to get it working I had to comment out autoprefixer and I also had to inline the sourcemap into the css-file which is obviosly less than ideal.

`build.js`

``` javascript

19  sourcemaps   = require('gulp-sourcemaps'),
...

68 // unified css stream
69  stream = gulp.src(source.definitions + '/**/' + globs.components + '.less')
70    .pipe(plumber())
71    .pipe(sourcemaps.init())
72    .pipe(less(settings.less))
73    .pipe(sourcemaps.write('.'))
74    // .pipe(autoprefixer(settings.prefix))
75    // .pipe(replace(comments.variables.in, comments.variables.out))
76    // .pipe(replace(comments.license.in, comments.license.out))
77    // .pipe(replace(comments.large.in, comments.large.out))
78    // .pipe(replace(comments.small.in, comments.small.out))
79    // .pipe(replace(comments.tiny.in, comments.tiny.out))
80    .pipe(flatten())
81 ;

```

**Comment by jlukic** [comment]
I originally added source maps but had difficulty with some gulp plugins which at the time did not support them. I would accept any PR that added.

**Comment by noobiwan** [comment]
Any update on this?

**Comment by xpd** [comment]
Interested in this as well.

**Comment by dimti** [comment]
+1
Today me need to be interesting this

**Comment by spidoche** [comment]
Any update? It will a be very useful feature

**Comment by Dimyas313** [comment]
@jlukic, has there been any further developments about css source maps? This is an important feature for writing and debugging themes, etc.

**Comment by Benew** [comment]
closed ? stale ? no !!! any hint on how to use sourcemaps when developing themes ?
