### ISSUE TITLE
form + grid + labeled input + Webkit = bug

### ISSUE THREAD

**Issue by Hywan** [Semantic-Org/Semantic-UI#2172]
Hello :-),

Try http://jsfiddle.net/ggk0krgs/ on Gecko and Webkit:
```html
<div class="ui form segment">
  <div class="ui middle aligned page grid">
    <div class="six wide column">
      <label>
        <i class="disk outline icon"></i>
        Foo:
      </label>
    </div>
    <div class="ten wide column">
      <div class="ui labeled input">
        <div class="ui label">
           abcdefghijklmnopqrstuvwxyz
        </div>
        <input type="text" />
      </div>
    </div>
  </div>
</div>
```
Here are the result on Gecko:
![result on Gecko](https://cloud.githubusercontent.com/assets/946104/7320204/3eb31ffa-ea9b-11e4-8639-5b2a646d58a0.png)
… and on Webkit:
![result on Webkit](https://cloud.githubusercontent.com/assets/946104/7320203/3eae944e-ea9b-11e4-88a6-66c196ed6b74.png)

If we remove the `form` class, it works. But it is no longer a form and we have new issues, so removing it is not the solution ;-).

Thoughts?

**Comment by jlukic** [comment]
Seems to be fixed in `2.x`
http://jsfiddle.net/4tdsa88p/

**Comment by jlukic** [comment]
I'm backporting to `1.x` in release tonight.

**Comment by Hywan** [comment]
Thank you very much!
