### ISSUE TITLE
Form: set value not working in 2.0 (next)

### ISSUE THREAD

**Issue by Verbat** [Semantic-Org/Semantic-UI#2173]
Have functionality to set input values changed in next or is it a bug? 
In Semantic 1.12 it works:
http://jsfiddle.net/efp8z6Ln/139/

Same code in 2.0 (next) is not working
http://jsfiddle.net/efp8z6Ln/138/

Thanks and  a nice weeken to you all.

**Comment by jlukic** [comment]
It's probably a bug, I'll investigate. 

There's also issues with form reset triggering `radio` `checkbox` validation.

**Comment by mbroadst** [comment]
Not sure if this is related, though seems probable. I'm using a checkbox in conjunction with aurelia.io, and when I style the checkbox input with semantic-ui view events are not triggering the two way binding. If I don't style it, there's no problem picking up the event with their dirty checking. I can confirm this doesn't work on 1.12.0 and next

**Comment by jlukic** [comment]
These are not related functions, we're talking about `form('set value')`

**Comment by jlukic** [comment]
It appears there was an issue with a module not instantiating itself correctly when invoking a method immediately. 

Form has a new syntax in `2.0` which passes validation as `field` object (to be in line with other modules), it still supports the old syntax but will give deprecation warning in console, so it uses a little bit different of an `initialize` function to support both.

**Comment by Verbat** [comment]
Many thanks, just tested in a a simple form and it worked. :)

**Comment by jlukic** [comment]
Glad to serve :+1:
