### ISSUE TITLE
[Table] table header size

### ISSUE THREAD

**Issue by mbroadst** [Semantic-Org/Semantic-UI#2174]
This is a feature request, but it would be great to be able to apply the conventional "tiny", "small", etc sizes to a table header to control its height. e.g.

```html
<thead class="small">
  <tr>
    <th></th>
    <th>Username</th>
    <th>Role</th>
  </tr>
</thead>
```

**Comment by jlukic** [comment]
I think you should modify it as part of your site theme overrides, as the associated theme variables, or using themed css. I dont believe this is widespread enough to warrant adding additional css overhead.

**Comment by mbroadst** [comment]
@jlukic yeah I can definitely do that (and am doing that currently), however I think its an issue of convention. It was my natural inclination to just add "small" to the class of the header, as its used in many other contexts - it would have been a great surprise if just adding "small" to the header did exactly what I thought it would. Anyway, just a suggestion :smile:
