### ISSUE TITLE
[Form] suggest validating form after 'set value' called should be settable

### ISSUE THREAD

**Issue by kevinptt0323** [Semantic-Org/Semantic-UI#2175]
I think that "set value" do "setting" without "validating" is more semantic.
The result to the program like this is not semantic.
http://jsfiddle.net/0t3e7zmt/2/

**Comment by jlukic** [comment]
Thanks, revisiting this there is no reason it should be calling `validate form` automatically. `remove value` etc do not trigger, and the native input change events should automatically trigger if `on: blur` is set.
