### ISSUE TITLE
A circular icon have a margin problem.

### ISSUE THREAD

**Issue by zaxad23** [Semantic-Org/Semantic-UI#2176]
It's on the top.

http://jsfiddle.net/vm9jg5n1/

**Comment by Anachron** [comment]
Well it works when you add the `reset.css` styles ... :+1: 

https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.12.0/components/reset.css

http://jsfiddle.net/d988a4at/1/

**Comment by zaxad23** [comment]
ok thanks :+1:
