### ISSUE TITLE
Background images not loading anymore after sidebar is shown

### ISSUE THREAD

**Issue by karltud123** [Semantic-Org/Semantic-UI#2177]
Good day dear semanticers,

I have used Semantic UI framework, you've done a really nice work, in one of my personal projects.

It can be found in this URL: developerkarl.appspot.com

Now, my problem is, when the page is viewed with 600px less screen width: it shows the fixed top menu, then when i click the menu button.. it shows the sidebar on the left.. the images afterwards doesn't load anymore, the images i am talking about is the background images in every title.

You can duplicate the problem by going in this url, developerkarl.appspot.com, then resizing your browser up to 600px or until the black top menu shows up. then click the menu button!

Thank you very much for the incoming help!

GodBless!!

**Comment by jlukic** [comment]
I'm not seeing this issue in Firefox or Chrome PC. Are you still seeing this issue, what browser are you using?

**Comment by karltud123** [comment]
Thank you for your response.

I am using Google Chrome Version 42.0.2311.135 m.

And yes I am still seeing the issue. The background images I am referring to are the one in the title.

For example the background-image on "me", it shows on the first load but after showing the sidebar, it does not load anymore..
