### ISSUE TITLE
[Tab] Preventing tabs from sending data-tab value as a part of URL in ajax call

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2178]
Hi,

Say I have the following tab settings:

```javascript
{
    cache: true,
    auto: true,
    path: '/foo/bar'
}
```

and the tab itself is:

```html
<a class="item" data-tab="tab1">...</a>
```

Is it somehow possible to prevent this tab from calling ```/foo/bar/tab1```? i would just like it to call ```path``` only.  Thanks in advance.

**Comment by jlukic** [comment]
Don't use auto and adjust the ajax settings url

**Comment by andreyvk** [comment]
Worked like a charm. Thank you!
