### ISSUE TITLE
[Menu] Selection Menu Rendering Bug

### ISSUE THREAD

**Issue by NETChaser** [Semantic-Org/Semantic-UI#2179]
In menu bar

    <div class="ui menu">
        <div class="item">
            <div class="ui dropdown" tabindex="0">
                <div class="default text">Gender</div>
                <i class="dropdown icon"></i>
                <input type="hidden" name="hidden-field">
                <div class="menu" tabindex="-1">
                    <div data-value="0" class="item">Male</div>
                    <div data-value="1" class="item">Female</div>
                </div>
            </div>
        </div>
    </div>

![2015-04-25 22 50 40](https://cloud.githubusercontent.com/assets/11858282/7334048/5a0c7102-eb9f-11e4-9bf1-914f16732fe2.png)

In Form (for comparsion)
![2015-04-25 23 09 31](https://cloud.githubusercontent.com/assets/11858282/7334063/40e8cd78-eba0-11e4-9d49-79c9d4546dc9.png)

**Comment by jlukic** [comment]
http://jsfiddle.net/zra8zqwk/

**Comment by jlukic** [comment]
I read this incorrectly. This is not a bug.

Add `ui dropdown` to `item`
http://jsfiddle.net/btow9o6f/
