### ISSUE TITLE
Dropdowns shouldn't require manual wireup

### ISSUE THREAD

**Issue by phillip-haydon** [Semantic-Org/Semantic-UI#218]
It seems drop downs require you to use JavaScript to make the drop downs function, shouldn't this be automatic? 

Given

```
  <div class="field">
    <label>Gender</label>
    <div class="ui dropdown selection">
      <input type="hidden" name="gender">
      <i class="dropdown icon"></i>
      <div class="default text">...</div>
      <div class="menu">
        <div class="item" data-value="male">Male</div>
        <div class="item" data-value="female">Female</div>
      </div>
    </div>
  </div>
```

Although it renders, its not usable. You're forced to call:

```
$('.ui.dropdown')
  .dropdown()
;
```

It seems very un-semantic to have to do this just to get it to work...

**Comment by matanster** [comment]
I don't know, I came here to have a look, but I guess it's really cool if this is likely the single thing that requires javascript wireup for default behavior.

**Comment by jakcharlton** [comment]
Consider this means that mobile devices dont give their usual dropdown
selector
