### ISSUE TITLE
[Popup] Pages with Horizontal Scrollbars Do Not Calculate Offstage Position Correctly

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#2180]
The popup content become thin and very tall even though there is a lot of room left in the window.

![popup](https://cloud.githubusercontent.com/assets/1778966/7335544/1f10890c-eb7d-11e4-8097-d6b327da6773.jpg)

From the screenshot above:

I have an element box positioned absolute to the "container" and is centered.  I have a button positioned absolute to the "box"..  I have the "error" warning icon positioned absolute to the "button" at top right -- the popup error content appears when you hover over this warning icon.

From the screenshot you can tell that the popup content is quite short and tall.  I tried the following and either did it wrong or not working:

1.  Tried setting to options to inline: true
2.  Tried setting option to context: 'body'
3. Tried setting varation: 'wide'

This seems to occur with positioned elements or floated elements.

I don't know how to jsfiddle and include files so these are my setup:

CSS USED:
&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/font-awesome.min.css&quot;&gt;
&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/transition.min.css&quot;&gt;
&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/bootstrap.min.css&quot;&gt;
&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/popup.css&quot;&gt;
&lt;link rel=&quot;stylesheet&quot; href=&quot;css/main.css&quot;&gt;

MARKUP HTML:

&lt;div class=&quot;container&quot;&gt;
       		&lt;div class=&quot;box&quot;&gt;
            	&lt;div class=&quot;button&quot;&gt;button
                	&lt;span class=&quot;tip&quot;&gt;&lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;&lt;!-- /box --&gt;
       &lt;/div&gt;&lt;!-- /container --&gt;
       
&lt;!-- this popup will be place anywhere --&gt;
 &lt;div class=&quot;ui custom popup&quot;&gt;
 I'm not on the same level as the button, but i can still be found.
&lt;/div&gt;

CSS FOR THE TEST

.container {
	position: relative;
}
.box {
	position: absolute;
	top: 50%;
	left: 50%;
	margin-top: -200px;
	margin-left: -200px;
	width: 400px;
	height: 400px;
	background: #5B5959;
	-webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.3);
	   -moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.3);
			box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.3);
}
.button {
	position: absolute;
	top: 100px;
	left: 100px;
	width: 150px;
	height: 50px;
	background: #fff;
}
.tip {
	position: absolute;
	width: 20px;
	height: 20px;
	top: -10px;
	right: -10px;
}
.tip:before {
	display: inline-block;
	font: normal normal normal 14px/1 FontAwesome;
	font-size: inherit;
	text-rendering: auto;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	transform: translate(0, 0);
	content: "\f06a";
	color: #CF1E20;
	background: #fff;
	border-radius: 50%;
	font-size: 20px;
}

JS USED:
&lt;script src=&quot;js/vendor/jquery-1.11.2.min.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;js/transition.min.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;js/popup.min.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;js/main.js&quot;&gt;&lt;/script&gt;

INSIDE THE MAIN.JS FILE:
$(document).ready(function() {

$('.tip')
  .popup({
    popup : $('.custom.popup'),
    on    : 'hover'
  });

});

Thanks!

**Comment by jlukic** [comment]
I know there are some issues with how `max-width: 100%;` when using an inline popup in some positions. 

Can you create a jsfiddle (fork link in readme) demonstrating the bug?

**Comment by emage** [comment]
Here is the demo: (https://jsfiddle.net/sn77zmw6/)

**Comment by jlukic** [comment]
Hi this is related to how absolutely positioned elements flow when inside a container.

You can solve this by setting a min-width
```css
.custom.popup {
  min-width: 200px;
}
```

I've added a note to documentation explaining the drawbacks to using `inline` popup

**Comment by emage** [comment]
@jlukic  thanks for the workaround!  I have another issue now tho.  My web app is a popup window and some of those error notes are close to the edge.  When the message FIRST appear it displayed it correctly to the left, however, if you hover it again now it goes offscreen and part of it is hidden.

What is the proper way to deal with this?  I use the prefer: opposite setup

Here is a demo:  https://jsfiddle.net/qmyb4dge/

**Comment by jlukic** [comment]
Hi, sorry for taking a while to get back. It looks like popup did not take into account horizontal scrollbars when checking boundaries for offstage content, so any content that appeared scrolled left would be "offstage".

This has been fixed in above commits.
