### ISSUE TITLE
'selector' option for component delegation

### ISSUE THREAD

**Issue by Greenype** [Semantic-Org/Semantic-UI#2182]
It would be nice to have a "selector" option in every component to enable delegation, just like in bootstrap, to make it easier to bind the components to dynamic HTML content.

Example:
$(document).dropdown({selector: '.ui.dropdown'});

**Comment by jlukic** [comment]
Keep in mind there is already a `selector` setting for each module which allows you to adjust the internal element selectors.

**Comment by jlukic** [comment]
I don't think this will be feasible anytime soon. Closing
