### ISSUE TITLE
Fix the background color of an inverted menu on hover

### ISSUE THREAD

**Issue by Lichtso** [Semantic-Org/Semantic-UI#2185]
The rule

```
/*--- Hover ---*/

.ui.link.inverted.menu .item:hover,
.ui.inverted.menu .link.item:hover,
.ui.inverted.menu a.item:hover,
.ui.inverted.menu .dropdown.item:hover {
  background: rgba(255, 255, 255, 0.1);
  color: #ffffff;
}
```

is overwritten by the rule:

```
/*--------------
  Active Hover
---------------*/

.ui.vertical.menu .active.item:hover,
.ui.menu .active.item:hover {
  background-color: rgba(0, 0, 0, 0.03);
}
```

which causes visual bugs when hovered (tested in webkit browsers).
As you would expect it to be highlighted instead of being dimmed.
There might be a need for a ".ui.inverted.menu .active.item:hover" rule.

Simular to: #993

**Comment by jlukic** [comment]
Hi, this is fixed with menu rewrite in `next`. Just hold off for a week or two and it will be out.
