### ISSUE TITLE
[Segment] Basic attached segments

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2186]
Hi,

Is there any way to use basic attached segments? The margin between 2 basic segments, if detached, is too high.

Here's a [fiddle](http://jsfiddle.net/andreyvk/8dh7bbwd/) that demonstrates the differences.

**Comment by jlukic** [comment]
Are you suggesting that `basic segment` should not have margin? They are currently designed to have the same positioning as `segment` but without styling.

**Comment by andreyvk** [comment]
Yes, I'm suggesting that bordering ```basic attached``` segments don't have a double margin (just like *normal* attached segments). What do you think?

**Comment by jlukic** [comment]
basic attached and attached do have the same margin
http://jsfiddle.net/enhr600j/

**Comment by andreyvk** [comment]
Sorry for misunderstanding here. I assumed that basic segments don't have borders, since example on the site shows none. Then my question would be: is there any way to make ```basic attached segment``` borderless? (maybe change the title of this post as well?)

Consider the following [fiddle](http://jsfiddle.net/andreyvk/2cmtn4gp/). If I use detached basic segments, then the gap between the button and the list is way too wide (debatable on a narrow screen). The wider you make your screen the more this gap seems to grow.
