### ISSUE TITLE
field below grouped fields lacks padding

### ISSUE THREAD

**Issue by mbroadst** [Semantic-Org/Semantic-UI#2188]
I've got a few fields which I want to conditionally hide, so I've placed a wrapping div around them. When I do this, the fields below are no longer properly padded: http://jsfiddle.net/ut1tq809/1/

**Comment by jlukic** [comment]
Just use `fields` groups
http://jsfiddle.net/sk29ojc3/

**Comment by mbroadst** [comment]
ah, ```class="grouped fields"``` is the key here, I missed that in the docs apparently. Thanks!
