### ISSUE TITLE
disable an entire form

### ISSUE THREAD

**Issue by mbroadst** [Semantic-Org/Semantic-UI#2189]
It's possible to apply a "loading" class to a form in order to dim the entire form and show a spinner, but it doesn't seem possible to add a "disabled" class to just dim the entire form. Is this possible? Or do you have to disable individual elements of the form instead?

**Comment by jlukic** [comment]
Hi, this is not the place to ask questions like this. Use gitter or stackoverflow. I use Github Issues to organize bugs and enhancements to the project.

http://jsfiddle.net/bwneLkm8/

**Comment by avalanche1** [comment]
As of 2.1.8 it is possible, but all the controls on the form are still active.
