### ISSUE TITLE
semantic ui icons not loading although everything is fine at console and network log

### ISSUE THREAD

**Issue by owaishanif786** [Semantic-Org/Semantic-UI#2192]
![sc1](https://cloud.githubusercontent.com/assets/6272263/7397832/712c61f8-eec4-11e4-88e1-df4da04f4c42.png)

**Comment by jlukic** [comment]
Could be related to CORS headers on your server

**Comment by owaishanif786** [comment]
I don't think so because I am loading from same origin I mean all I serving through localhost...

**Comment by owaishanif786** [comment]
Everything is working fine after deleting cache both in chrome and firefox.
