### ISSUE TITLE
[Card] Doesn't display correctly when nested inside ui-page-grid

### ISSUE THREAD

**Issue by stanzakh** [Semantic-Org/Semantic-UI#2193]
It seems that the content of the card is cut off. [Here's the fiddle](https://jsfiddle.net/jdfro2uu/1/).

**Comment by jlukic** [comment]
In `1.x` all content must be nested inside a column, this is because of the `font-size: 0;` used to remove white-space from inline block. (See other threads). 

This is different in `2.0` which uses flexbox.
