### ISSUE TITLE
semantic-ui modal how to hide with transition ?

### ISSUE THREAD

**Issue by xpurer** [Semantic-Org/Semantic-UI#2194]
semantic-ui modal how to hide with transition ?

I find when i click the close button , semantic-ui modal hide with transition .

But, when i use .modal('hide'), there is no transition effect .

**Comment by jlukic** [comment]
Calling hide uses transitions. Please create a test case showing your issue, there's a jsfiddle to fork in the readme.

**Comment by jlukic** [comment]
Closing due to no test case.
