### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by pencilcheck** [Semantic-Org/Semantic-UI#2195]
http://semantic-ui.com/collections/grid.html#full-width-backgrounds

Seems like the code below in the link above doesn't work. The background color for the last two segment is white when in the code it seems to indicate otherwise.
```
<div class="ui vertically padded page grid">
    <div class="teal column">
      <h2 class="ui inverted header">Column Background</h2>
      <p>Third section of content</p>
    </div>
  </div>
<div class="ui vertically padded page grid">
    <div class="black column">
      <h2 class="ui inverted header">Column Background</h2>
      <p>Fourth section of content</p>
    </div>
  </div>
```

**Comment by jlukic** [comment]
Is fine in `next`, will hopefully be getting 2.0 out very shortly
http://beta.semantic-ui.com/collections/grid.html#row-and-column-backgrounds
