### ISSUE TITLE
Can't change the font.

### ISSUE THREAD

**Issue by zaxad23** [Semantic-Org/Semantic-UI#2196]
I'm using a Semantic-UI from there:http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.12.0/semantic.min.css

It's using a Lato font, but i want Open Sans.
So i write code like this:
```
body {
  margin:0;
  padding:0;
  min-height: 100%;
  height: 100%;
  background-image:url(background.png);
}

html, body {
    font-family: "Open Sans", Arial, Helvetica, sans-serif !important;
}
```

...and font is always Lato!

What can I do?

**Comment by jlukic** [comment]
You need to work with the LESS version and change the font in `site.variables` otherwise you'll be loading both fonts.

**Comment by zaxad23** [comment]
But can I do it only with CSS?

**Comment by jlukic** [comment]
No, you will have to adjust or disable the google font `@import` rules.

This is for bug tracking and suggested features for the project, please use our Gitter or stackoverflow for these discussions.
