### ISSUE TITLE
New size level between 'tiny' and 'mini' (mainly for 'image')

### ISSUE THREAD

**Issue by behdad-keynejad** [Semantic-Org/Semantic-UI#2197]
Is it possible to add a new size level between 'tiny' and 'mini?
There are lots of situations in which a tiny image is too big and mini is too small.
A new level with 40px width is really needed.

Thanks

**Comment by ikourfaln** [comment]
I think 8 sizes is more enough, SUI cant satisfy all situations !!
we must use CSS in some cases ;)

**Comment by avalanche1** [comment]
```we must use CSS in some cases ;)```
well, it's kinda hard after using SUI...:sweat_smile:

**Comment by jlukic** [comment]
I think the amount of sizes are enough, the default sizes are arbitrary and should be changed for your project.
