### ISSUE TITLE
.search.dropdown cannot move cursor

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2199]
After I've selected an item from dropdown list, i cannot delete that item pressing 'delete' key and cannot navigate the text of the item using right\left keys.

**Comment by jlukic** [comment]
I'm not sure what happened there, but it appears there's some regression with `1.x` keyboard shortcuts

**Comment by jlukic** [comment]
Fixed in patch today.

**Comment by avalanche1** [comment]
Jack, the fix don't work.
Checked it on my meteor project and on SUI.com

**Comment by jlukic** [comment]
Seems to be fine at semantic-ui.com at http://semantic-ui.com/modules/dropdown.html#search-selection

Clear cache?

**Comment by avalanche1** [comment]
Cleared. Still serving 1.12.1 on sui.com. You sure everything's fine with sui.com link to master repo?

**Comment by avalanche1** [comment]
But anyway, I have 1.12.2 in my meteor app and the fix doesnt seem to work. I'll make a fiddle once the versioning confusion is sorted.

**Comment by avalanche1** [comment]
well, maybe this needs reopening.
still aint working.http://jsfiddle.net/pybxztu2/1/

**Comment by jlukic** [comment]
Delete key and arrow keys seem to be fine in your fiddle?

**Comment by avalanche1** [comment]
Is it a question or a statement?
In the fiddle the keys ```delete, left, right``` aint working after I've selected an item from dropdown list.

**Comment by jlukic** [comment]
The bug I fixed was left/right arrows not working during selection. 

This is expected behavior. After making a selection it adjusts the underlayed text content. This could contain other non string values like images or labels and is unselectable. It is not part of the current input.
http://beta.semantic-ui.com/modules/dropdown.html#search-selection
