### ISSUE TITLE
[enhancement] add another option for form validation error

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2200]
It'd be nice to be able to customize form validation to produce errors in rich text just **below input field**, like in the example:  
![image](https://cloud.githubusercontent.com/assets/10534563/7444462/34b4769c-f195-11e4-898c-2c55b4c2c5b6.png)
(*errors say 'required field' in Ru*)

**Comment by jlukic** [comment]
This is similar to what's added with `inline:  true`. 

I will consider revisiting the stylings of inline form validation.

**Comment by avalanche1** [comment]
Well, for one thing, my proposal is not so obtrusive as inline notifications and imho more elegant.
Plus, inline:true usually shifts elements below them further down (when they popup), which imo is kinda nasty looking.

Ps thanks for being so responsive! :thumbsup:
