### ISSUE TITLE
Stop modal from closing if form not valid

### ISSUE THREAD

**Issue by jackbarham** [Semantic-Org/Semantic-UI#2203]
I'm trying to stop a modal from closing when the form is not valid. I've also tried adding .disabled class to the submit button but i can't find any way of listening to the form and removing the .disabled class when the fields are valid? - I know this is a question but I was hoping this is possible?

**Comment by jlukic** [comment]
Attach events to onSuccess, onFailure
http://semantic-ui.com/behaviors/form.html#callbacks

**Comment by jackbarham** [comment]
I've tried everything and I can't get the modal to stop closing. The close below will display the error as soon as the submit is pressed. However, if you press the submit again (without updating any forms), it will close the modal:

if ($('body').hasClass('newuser')) {
    $('.modal-newuser-open')
        .modal({
            closable : false,
            duration : 460
        })
        .modal({
            onShow: function() {
                $('#welcome')
                    .form({
                        website_title: {
                            identifier  : 'website_title',
                            rules: [
                                {
                                    type   : 'empty',
                                    prompt : 'Enter your title'
                                },
                            ]
                        }
                    },
                    {
                        inline: true,
                        on: 'blur',
                        transition: 'fade down',
                        onFailure : function(event){
                            console.log('failed');
                            event.preventDefault();
                        }
                    }
                );
            }
        })
        .modal('show');
};

**Comment by jlukic** [comment]
this is pseudo code but something like

```javascript
if ($('body').hasClass('newuser')) {
    $('.modal-newuser-open')
        .modal({
            closable : false,
            duration : 460
            onApprove: function() {
                return false;
            }
        })
        .modal({
            onShow: function() {
                $('#welcome')
                    .form({
                        website_title: {
                            identifier  : 'website_title',
                            rules: [
                                {
                                    type   : 'empty',
                                    prompt : 'Enter your title'
                                },
                            ]
                        }
                    },
                    {
                        inline: true,
                        on: 'blur',
                        transition: 'fade down',
                        onSuccess: function() {
                            // do some sort of ajax submit
                            return false;
                            $('.modal-newuser-open').modal('hide');
                        },
                        onFailure : function(event){
                            console.log('failed');
                            event.preventDefault();
                        }
                    }
                );
            }
        })
        .modal('show');
};
```

**Comment by jackbarham** [comment]
Thanks - I've played around withe code and can't get the modal not to close (on second click). I've also tried listening to errors and toggling the `disabled` class on the submit button, but there doesn't seem to anyway of listening in real time. Are there any examples around of a modal not closing until the form is valid?
