### ISSUE TITLE
dropdown callback

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2212]
Ok, maybe I'm doing smth wrong here, but I expect the callback to fire after I've selected an item from dropdown. But instead it fires on dropdown initialization.
http://jsfiddle.net/sLc3ceth/3/

**Comment by jlukic** [comment]
You are calling alert during init. This will call alert() as soon as you run your code.

You need to attach a function
http://jsfiddle.net/pybxztu2/

**Comment by avalanche1** [comment]
Well that's not obvious from the docs.
Provide me with a link to site docs repo and I'll PR my vision of docemntation of callbacks.
