### ISSUE TITLE
2.0 (next branch) Dropdown module is forcefully setting data-value to lower case

### ISSUE THREAD

**Issue by laurynas-karvelis** [Semantic-Org/Semantic-UI#2213]
Hi,

first of all thank you so so much for all the work you've been doing so far. The entire package is super sick and slick!

I've been fiddling around with "next" branch, and I've noticed that when {"allowAdditions": true} setting is passed into the module setup any label's value that gets added to the system is forcefully lowercased.

There are some use cases when entered value should be kept as-is instead of transformations, maybe adding a new parameter or just leaving values untouched would be a smarter way to go?

Cheers,
Laurynas

**Comment by jlukic** [comment]
Oh, that shouldn't be

**Comment by jlukic** [comment]
Fixed. User values were not storing correctly.
