### ISSUE TITLE
Harmonize Element Class Names

### ISSUE THREAD

**Issue by saden1** [Semantic-Org/Semantic-UI#2215]
Right now there are various elements with different class names that could probably be harmonized. Header element has 'dividing' class while list element has 'divided' class. There's also "detail' and 'description'  and 'sub head' classes in various elements that could all probably be called detail.

The less variation between element class names that server similar purpose the better.

**Comment by ph7vc** [comment]
The `dividing` class for the header is describing the element; in that it will have a divider after the header content. Similarly, the list element is a container for list items, which again the `divided` class is describing the content of the list; saying that the child elements should have a divider in between them.

If you're referring to the card subclasses like `details` or `description` or `meta`; they each have distinct order they should go in as well as style characteristics. Given that; we really couldnt simplify it into a single class.

I know Jack thinks very carefully about his class names and the examples listed are mutually exclusive elements; so they really couldn't share style attributes.

**Comment by jlukic** [comment]
I think there are subtle distinctions, for example `dividing` - divides places a divider between an element and other content, and `divided`, divides an element into parts.  

The hardest issue with naming is there's no going back. Once we support a name removing it means breaking changes. I think generally an argument for 'the most common english word' for a thing, seems to be the best decision, but even then there are individual preferences which may add some inescapable subjectivity.

[The Ongoing Struggle of Garlic Hangers](http://www.oxforddictionaries.com/us/external/files/Garner_s_American_The_Ongoing_Struggles_of_Garlic-Hangers.pdf?version=2014-10-15-1630)
