### ISSUE TITLE
2.0 Announcement

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#2216]
Hey Everyone

I plan on launching 2.0 of Semantic UI on *June 1st*. This is a date I've set in stone to make sure I can get as much packed into 2.0 without delaying all the important fixes for longer than is necessary.

I plan on having a launch party in New York for those who are available to attend. If you haven't already signed up for our newsletter, on [semantic-ui.com](http://www.semantic-ui.com) be sure to do so.

The current plan is to try to raise funds with Kickstarter in coordination with the June 1st launch, to fund production of dedicated theming and layout websites, as well as continued UI development on the project. 

The theme site would be similar to [NPM](https://www.npmjs.com/) for sharing/releasing Semantic UI themes, and would include a built in theme builder tool which could let you interactively create UI themes. 

The layout site  would help users find re-usable layouts like 'credit card forms', 'profile pages', etc using Semantic UI components. These could be shared and added using a [Codepen](http://codepen.io/) like interface that lets users create and share layouts with the community.

I'll be sure to post any more updates in this thread as they develop. 

Thanks everyone for contributing to the project so far, and looking forward to sharing more shortly.

**Comment by ikourfaln** [comment]
OMG Im waited for 2.0 about 1 month :(
Im working on personal project, and I waited for 2.0 to apply it. But now you said until June.
Anyway Thanx for All your hard work :+1: 
Can I work with Beta version in Production until you release the stable one ? (http://beta.semantic-ui.com)

**Comment by jlukic** [comment]
Yes please start using the beta version and giving feedback. You can always consult the release notes for any new changes.

**Comment by ikourfaln** [comment]
OK thanx for info

**Comment by ph7vc** [comment]
You've done amazingly well for being a single maintainer. 

I think it's catching a lot of traction, and it was even mentioned on [Treehouse show](https://www.youtube.com/watch?v=pshb8rPRsKg) last week (tho they didn't do it justice imo). It is hard when Bootstrap is the go-to framework for non-frontend developers; but hopefully that will change.

Perhaps SUI could also adopt a model similar to the Linux kernel, where (mostly) volunteers maintain a particular domain in the project; and deal directly with that part. Things like bug reports, fixes, and everything of the like; are distributed. And just like Linus has the final say to everything being added to Linux; you could approve or deny new features or patches. 

I wish you the best of luck and am very excited to see the future of SUI.

**Comment by ikourfaln** [comment]
Hmmmm Treehouse are interested in SUI.
I see that TutsPlus made a tutorial for SUI, but its old and not pro, they just apply whats in Docs.

**Comment by gonssal** [comment]
Just to make it clear. Is 2.0 supposed to be backwards-compatible? Or in other words, should everything that worked in 1.x work without any modifications in 2.x?

**Comment by ikourfaln** [comment]
@gonssal you can check the Migration Guide here:
https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md

**Comment by gonssal** [comment]
@ikourfaln i've just read that. I was concisely speaking about grids and their columns. And more specifically, nested grids. I understand a `container` class has been added, but grid should still work.

I have a page with nested grids and dividers, and after updating to 2.0 it goes nuts: dividers appear borched, columns dont respect `x wide` classes and switch lines when not expected, etc...

Just wanted to know if it's worth creating issues for things like this or I should just start tweaking the markup until I get everything fixed.

**Comment by ph7vc** [comment]
@gonssal I had a few minor issues when i switched to the beta 2.0 version; everything for the most part works fine. Some of the menus and segment formatting was off, but it was a simple fix.

**Comment by jlukic** [comment]
Yes, please create issues with the `next` branch as you experience them. Especially with `grid`.

**Comment by xiongchen2012** [comment]
Is 2.0 compatible with 1.x?

**Comment by thinksaydo** [comment]
Sounds like an interesting approach. How much are you looking to raise for a successful Kickstarter? And if you don't raise what you need, what does the future of Semantic UI look like? I understand maintaining this project is tremendous amount of work, but I know you need to make a living too.

**Comment by thinksaydo** [comment]
There's more about the long term plan in this comment: https://github.com/Semantic-Org/Semantic-UI/issues/2201#issuecomment-98766267

**Comment by varunmohapatra** [comment]
Can't wait for 2.0! Hope everything is on track.

**Comment by jlukic** [comment]
@xiongchen2012 Yes, check the [release notes](https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md) for specific changes

**Comment by abdelouahabb** [comment]
wonderful! a week to go! cant wait!

**Comment by wetux** [comment]
+1 great job.

**Comment by bilalahmed70** [comment]
where can I download beta 2.0 from? https://codeload.github.com/Semantic-Org/Semantic-UI/zip/2.0.0 doesn't work. Thanks.

**Comment by zelenin** [comment]
https://github.com/Semantic-Org/Semantic-UI/archive/next.zip

**Comment by bilalahmed70** [comment]
thank you so much @zelenin

**Comment by bilalahmed70** [comment]
Font Awesome not working, icons showing as squares now.

**Comment by geomorillo** [comment]
Big news !!!

**Comment by BusyJay** [comment]
+1 great job!!!

**Comment by abresler** [comment]
Congrats!!

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by jlukic** [comment]
So today is June 1st, and I'm excited to report that outside a [few marked bugs](https://github.com/Semantic-Org/Semantic-UI/milestones/2.0%20RC) everything is ready for a `2.0` release. 

Since I have been devoting the majority of my time to getting the code ready, there are still, however, a few documentation issues which I need to get straight before releasing 2.0 publicly. 

As discussed in #2201, a successful launch is pretty critical for the continued development of the project. Major releases get a lot more eyeballs than is normally typical for the project. I need to make sure the docs for 2.0 are ready for new users. 

Semantic UI is pretty much a *one man thing*, which means my bandwidth is pretty limited for handling a lot of the other operational tasks necessary for running a project. To get things up to par I need to dedicate time before an official launch, exclusively to making the project more accessible to a wider audience of programmers.

Since I know I'm *late* I will keep an up to date guide in this post, with completed tasks, and an estimated "Official Launch Day" based on the time estimates for each missing task. 

## Current Estimate for Official Release: 
### June 11th (8 days)

## Left to Do 
- [ ] New Getting Started Guide (**1 day**)
- [ ] Tablet/Mobile 2.0 Doc styling  (**1 day**)
- [ ] Change homepage - Add "new in 2.0", add style adjustments to appear "new" (**1 day**)
- [ ] Add [Layout Examples](**https://github.com/Semantic-Org/Semantic-UI/tree/next/examples) to Docs, method for** automatically building from SUI repo. (**1 day**)
- [ ] Remove `page grid` from docs and rewrite container elements to explain page grid deprecation
- [ ] Add donation CTA and download page (**1/2 day**)
- [ ] Create a standalone blog and a 2.0 launch post detailing new features (**1 day**)
- [ ] Create a 2.0 launch e-mail newsletter. Determine most cost effective way to send newsletter to 3000+ people. (**1/2 day**)
- [ ] Finish any bugs marked [`2.0 Release Candidate`](https://github.com/Semantic-Org/Semantic-UI/milestones/2.0%20RC) (**2 days**)
- [ ] Set a date and location for a launch party in NYC (not in estimate)

## Ways You Can Help
- Report any critical bugs in 2.0 which should be fixed in a Release Candidate
- Use the "Edit this page" button in [beta docs](http://beta.semantic-ui.com) to submit Pull Requests for poor language in documentation 
- Help add [missing UI examples](https://github.com/Semantic-Org/Semantic-UI/tree/next/examples/components) for a completed [theming example](https://github.com/Semantic-Org/Semantic-UI/blob/next/examples/theming.html) to the UI repo.
- Email me ideas for cool cheap/no room cost venues in NYC for a launch party.


I will be releasing `2.0RC1` at the end of the day, in order to keep up with my promises. However, this is **not the official 2.0** release. So I urge you to reserve **submitting the links along to any social aggregator** like hacker news until everything is finalized.

Thanks again for your understanding

**Comment by lemartialou** [comment]
Warmest thanks for all of your hard and outstanding work !!!

To me, the best date for an official 2.0 release is: `when it's ready` ;)

Now for a little bug: the "edit this page" button in beta docs leads to the `master` branch and not the `next` one as expected.

Thanks again, I won't say it enough: YOU ROCK !!! ^^

**Comment by jlukic** [comment]
@lemartialou https://github.com/Semantic-Org/Semantic-UI-Docs/commit/5ee58d17cc5f8582e64b958f899621ae3242a61f fixed the link

**Comment by lemartialou** [comment]
Great! Now one last thing about the "edit this page" button, it's missing on:
- UI Examples (+ missing space between the buttons and the page tabs)
- The 2 "Globals" pages (no missing space)
- The 3 "Behaviors" pages (+ missing space between the buttons and the page tabs)

**Comment by jlukic** [comment]
Please create a thread on Docs, GitHub. I'm going to squelch the conversation here to keep things organized.

**Comment by Aproducktion** [comment]
Yeah you rock @jlukic. Thank you for all your work!

**Comment by ikourfaln** [comment]
@jlukic  I love you man :+1:

**Comment by jonathanmartin** [comment]
If you'll have the party in Seattle.  We'll host.  :)

**Comment by abresler** [comment]
Great work Jack and everyone who has helped along the way, I'll see if I
can think of possible spaces that may work

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

Warmest thanks for all of your hard and outstanding work !!!

To me, the best date for an official 2.0 release is: when it's ready ;)

Now for a little bug: the "edit this page" button in beta docs leads to the
master branch and not the next one as expected.

Thanks again, I won't say it enough: YOU ROCK !!! ^^

—
Reply to this email directly or view it on GitHub
<https://github.com/Semantic-Org/Semantic-UI/issues/2216#issuecomment-107715988>
.

**Comment by avalanche1** [comment]
Gonna have to skip this one( Will make sure to visit SUI 3.0 launch party though)

**Comment by KapuzenSohn** [comment]
Thanks man :+1:

**Comment by gensmann** [comment]
@jlukic : Regarding newsletter posting, I'm able to hook you up with a free account at www.ubivox.com, where I'm one of the co-founders. Would 10.000 subscribers, unlimited monthly e-mails be enough for a start?

We are currently looking into using Semantic UI as part of our "in development future email delivery service" (cant spill that many beans in public though :-) and we'll be happy to help you out with what we can.

**Comment by geomorillo** [comment]
+1

**Comment by jlukic** [comment]
@gensmann That would be a **huge** help. 

I haven't been sending any newsletter updates the last six months since the list started growing above the free limits at mailchimp.  It's at 3204 subscribers now, so that gives plenty of room for growth.

I've gone ahead and made a free account as "semantic-ui" @ ubivox.

**Comment by nooitaf** [comment]
good stuff :)

**Comment by ppawel** [comment]
How is it going with the release? I have been using the `next` branch for a while and it looks pretty solid.

**Comment by jlukic** [comment]
I've adjusted the original post to have the most up to date launch date assessment. I've ended up spending more than two days on bug fixes in `2.0`, which has put me a little behind schedule for the rest of the content, but not too much. 

Here's whats been completed
* Container is finalized, page grid is removed from docs
* 2.0 docs finally have responsive stylings, still a couple pages left to fix but mostly there
* Most significant `2.0RC` bugs have been smashed including some I didnt originally plan on doing
* @gensmann Has set me up with his email service which should make the newsletter smooth sailing

**Comment by peterrobertz** [comment]
YOU ARE GREAT! <3

**Comment by abresler** [comment]
Congrats Jack, you are a rockstar!

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by jskz** [comment]
Still on board for 2.0 today?

Amazing work, thank you so much for your discipline & dedication in staying with this project.

**Comment by jlukic** [comment]
Unfortunately I'm not ready to launch today. 

Although I'm more or less ready code-wise, and I'd encourage anyone to start using `2.0` branch today, I'm still worried about on-boarding with the project, making sure that users who aren't familiar with Semantic have an easy time getting set-up and understanding the project. I don't think that experience is ready yet. 

The tasks above still more/less are the blockers. Although my original assessment seemed a fair bit optimistic on how long each thing should take. (Setting up a blog and writing a first post in one day.. hmmm) I've also added some new goals like creating a "what's new" page, adding a theming and module overview page.

I'm still going to launch "shortly in June" just need a little more finesse time.

**Comment by ikourfaln** [comment]
Thanx @jlukic  for all your hard work

**Comment by tryIO** [comment]
Hi! I don't want to bother too much since I can assume you got a lot of work to do, but is the beta web-site of SemanticUI constantly updated with the 'next' branch? :) just to know if the documentation on it is gonna have other 'major' updates or it has all we need to know about 2.0.0 version.

**Comment by jlukic** [comment]
Yes, it is being updated once or twice daily.

**Comment by cwonrails** [comment]
Thanks for focusing on the new user onboarding experience prior to launching 2.0. I'll be rebuilding my website from the ground up in Semantic and am looking forward to the release!

**Comment by mohamedsabil83** [comment]
I can't wait to the releasing SUI2 but as I show the beta site I didn't find anything about 'Price Plan'. Isn't be in this version ??

**Comment by jlukic** [comment]
Hey everyone. Just thought I'd give you guys an update.

I'll be releasing Semantic UI 2.0 on **Tuesday June 30th**

I will be just fixing critical bugs [marked RC](https://github.com/Semantic-Org/Semantic-UI/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+RC%22) on GitHub for launch. 

If you feel a bug/enhancement should be addressed that is not currently set to that milestone, feel free to @ ping me in the thread for that issue. Keep in mind I still have to polish several guides & other docs work before launch, so my coding throughput is limited.

The launch party will be in New York in mid July, most likely **the week of the 13th**. I'll be sending out a an RSVP email after launch to those subscribed to the newsletter. 

Thanks for everyone who has contributed with reporting bugs, helping answer others questions, submitting pull requests, translating, and all other amazing things that you guys do. I'm really looking forward to next week. It has been a tremendous effort across the board.

**Comment by ikourfaln** [comment]
Hi @jlukic,

I think that it will be useful if you add those feature to SUI 2.0:

* Animation (Transition) to Tab module (when you switch between Tabs)
* DatePicker & TimePicker elements

and thanx for all your hard work.

**Comment by leecade** [comment]
Treeview +1

**Comment by humanitiesNerd** [comment]
I would really appreciate a datetimepicker too

**Comment by step4wd** [comment]
DateTimePicker is missing in SUI 2.0? I was really hoping for new controls and better grid

**Comment by ricardoemerson** [comment]
yes. Date and time picker will be awesome.

**Comment by mohamedsabil83** [comment]
+1 **Date and Time Picker**. Hope to added to SUI asap.

**Comment by jlukic** [comment]
I will most likely release files *after work at around 6pm EST* tomorrow. I want to make sure I can get a little sleep tonight and still finish up loose ends for tomorrow.

Thanks everyone.

**Comment by ikourfaln** [comment]
thanx @jlukic  for all your hard work :+1:

**Comment by SilverwingGames** [comment]
@jlukic Get some rest man, You deserve it

**Comment by mohamedsabil83** [comment]
thanx a lot @jlukic for everything

**Comment by avalanche1** [comment]
@jlukic You sdnt impose those strict time restrictions upon yourself. Best products are ready *when they are ready*. Get some rest)

**Comment by jlukic** [comment]
Here goes nothing..

**Comment by Dashed** [comment]
Awesome! :+1:

**Comment by jlukic** [comment]
Launched the damn thing. Time to pass out. If there's any urgent bugs please e-mail me.

**Comment by geomorillo** [comment]
damm you are awesome

**Comment by jdrago999** [comment]
:rocket: Congratulations!!

**Comment by ikourfaln** [comment]
Ow thanx, but Get some rest man

**Comment by KapuzenSohn** [comment]
Nice :+1:

**Comment by nooitaf** [comment]
\O/

**Comment by tryIO** [comment]
Thanks for the effort man! I try to spread the word of SemanticUI by contributing to the Webjars project (although bower is the way to go nowadays for pure Javascript web-development).

**Comment by jlukic** [comment]
Hey everyone if you can help by upvoting [this hackernews thread](https://news.ycombinator.com/item?id=9815439) it'd help us get some new users.

**Comment by jdrago999** [comment]
Position 85 (page 3) as of right now.

**Comment by geomorillo** [comment]
really great

**Comment by jlukic** [comment]
This thread is actually getting better traction 
https://news.ycombinator.com/item?id=9815788

I cant figure out how this site works. Hopefully will get better traction after I sent a newsletter.

**Comment by lemartialou** [comment]
Congrats on the release!
:+1: :+1: :+1:

**Comment by jlukic** [comment]
Thanks everyone for the positive remarks. I'll be taking the weekend off of coding for the 4th of july holidays, but will be back working on `2.0.1` next monday. 

Going to try to enjoy a weekend off :stuck_out_tongue_winking_eye:
