### ISSUE TITLE
[Collection] Add Footer

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2217]
I would like to add this feature as Enhancement.
A Footer Collection (or Element), a regions at the bottom of a screen that can contain various types of content. (Like Sticky footer used in Bootstrap Examples)

![footer](https://cloud.githubusercontent.com/assets/9744226/7486152/8be60052-f398-11e4-896b-66354666df3c.png)

Useful in mobile 

![footerm](https://cloud.githubusercontent.com/assets/9744226/7486158/a696c7ec-f398-11e4-90a1-e7a83fde4635.png)

**Comment by ph7vc** [comment]
Already exists: http://semantic-ui.com/modules/sticky.html#/settings

You can use `sticky` to stick it to the bottom of the view port. It's also really simple CSS that could be used to do the same.

**Comment by ikourfaln** [comment]
Ops, I didnt think about that, Thanx and Im sorry
