### ISSUE TITLE
[Icon] Suggestion to have "avatar" sized icon or align avatar image size to icon sizes

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2218]
Hi,

It's a minor suggestion, but I felt like proposing it. I was using cards the other day and came across ```extra content``` height misalignment when mixing icons and avatars. Here's an [example](http://jsfiddle.net/andreyvk/keLawmte/). I tried different icon sizes and non of them matches avatar size. This is relevant in cases when user still has no avatar assigned and a generic icon is used instead. 

Again, this is a minor. If you feel that this is irrelevant, do close the issue :) Thanks

**Comment by ph7vc** [comment]
Have you thought about using a placeholder image instead? That's usually my go-to option, then I don't have to worry bout formatting extra markup.

**Comment by andreyvk** [comment]
Hi @ph7vc,

Yes, i have. In all cases a placeholder image must either be manually created or bought or searched up in a manner that no copyright violation happens. Too much hustle for some (like me :)). Having an ```avatar``` sized icon is very simple and useful IMO.

**Comment by ph7vc** [comment]
It would be super simple to make one using Gimp. Especially if you like the icon; you can use that as an image.

**Comment by hmaesta** [comment]
This is not *super-important*, but I think it's interesting.

Why load another image in my app if I already load FontAwesome with a lot of good placeholders? (Like in this example.)

I think we can maybe add ```avatar``` class to icon (just in ```ui card```) so both have the same size.

**Comment by andreyvk** [comment]
@ph7vc that works of course, but that's not the point. I prefer using Paint.NET in my case.

@hmaesta  Definitely not super important. Any time in ```2.x``` would be a nice-to-have :)

**Comment by jlukic** [comment]
I think its safe to say that `avatar` should probably be `2em` and not the slightly awkward `2.5em`

**Comment by andreyvk** [comment]
Sounds good. Thakns @jlukic
