### ISSUE TITLE
[UI] Rich Text Editor

### ISSUE THREAD

**Issue by comtom** [Semantic-Org/Semantic-UI#222]
It would be very nice & handy to have a full featured text editor as a component.

There are several examples, like CLEditor or TinyMCE. TinyMCE is one of the most popular, but there are some better like this one:

http://mindmup.github.io/bootstrap-wysiwyg/

it has some bugs but is great. I've encountred problems while pasting MS Word styled text, except that it works great.

**Comment by salarmehr** [comment]
I would be nice to have a lightweight markdown editor.

**Comment by rubydog** [comment]
@oknoorap Have you been able to get pen editor working? In my case the javascript seems to be working fine but it I can't see the tooltip when I select text in text area.

**Comment by hubertguillemain** [comment]
Coming back on this topic: there are many Rich text editors out there, absolutely
I think the requirement is to maintain look and feel with the rest of Semantic UI (buttons, font, focus, ....)
