### ISSUE TITLE
@import fonts.googleapis lead to browser can't load page in some country

### ISSUE THREAD

**Issue by gwuhaolin** [Semantic-Org/Semantic-UI#2220]
In semantic.css
```
@import 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin';
```

In some country(China) Google's service is block,which lead to browser can't get font from google,and the page won't show until the get font request has finish.

**Comment by ShawnOceanHu** [comment]
Hi just download the fonts to your server as static files

**Comment by jlukic** [comment]
See #1768 #1305
