### ISSUE TITLE
Output files in another directory/folder

### ISSUE THREAD

**Issue by hmaesta** [Semantic-Org/Semantic-UI#2221]
Hello.

My Semantic build folder is located in ```my app / resources / semantic```,
so by default all the ouput files are in ```my app / resources / semantic / dist```. 

How can I set for this files (compressed CSS, JS and theme assets) be built at ```my app / resources```?

I already changed ```semantic.json``` without success.
```
    "output": {
      "packaged": "../",
      "uncompressed": "../components/",
      "compressed": "../compressed/",
      "themes": "dist/themes/"
    },
    "clean": "../"
```

Btw, theres how save Javascript files in ```resources/js``` and CSS files in ```resources/css```?

Thank you.

*Ps: This is the first time I use gulp and npm. Be patience and sorry about my English.*

**Comment by ph7vc** [comment]
I see no reason you couldn't go up several levels. `../../` should take you to the `resources` directory. (Though I have no idea which directory it's starting from)

Alternatively; this would solve both your problems with no config changes; if you're using a Linux or OSX operating system; you could setup symbolic links to the `semantic/dist/` files. 

http://www.cyberciti.biz/tips/understanding-unixlinux-symbolic-soft-and-hard-links.html

Thats what I did on my system so I can have a single build of semantic that I can keep up to date with all my projects

**Comment by jlukic** [comment]
JS and CSS files are not set up to have separate output directories in the current build system.

**Comment by hmaesta** [comment]
@jlukic Thank you for the answer. I will try @ph7vc solution with Symbolic Links. Thank you both.
