### ISSUE TITLE
Dropdown buttons no longer populate the hidden input field associated with them

### ISSUE THREAD

**Issue by danr1979** [Semantic-Org/Semantic-UI#2223]
I've upgraded my Semantic UI installation from 1.11.4 to 1.12.2 and have found that the hidden input field is no longer populated on my button dropdown.  The code for my dropdown is below:

    <div class="ui floating dropdown labeled icon small button">
        <input type="hidden" name="mc_code" value="" />
        <i class="search icon"></i>
        <span class="text">Select a Merchant Category Code</span>
        <div class="menu">
            <div class="ui left pointing dropdown link item" data-value="itemA">
                <i class="dropdown icon"></i>
                Item A
     	        <div class="menu">
                    <div class="ui left pointing dropdown link item" data-value="itemAA">
                        <i class="dropdown icon"></i>
                        Sub Item A
                        <div class="menu">
                            <div class="item" data-value="itemAAA">Sub Sub Item A</div>
                            <div class="item" data-value="itemAAB">Sub Sub Item B</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

If I select an item from the final dropdown the button text and the hidden input value do not change.  If I try again using version 1.11.4 it works fine.

Thanks.

**Comment by ph7vc** [comment]
http://jsfiddle.net/khtpm9qL/

Looks fine to me

**Comment by danr1979** [comment]
Nope. Try clicking the sub menu & you'll see it doesn't appear as the text
of the button (which it should unless specified otherwise). Furthermore,
the input field isn't populated with a value.

The same HTML works fine with version 1.11.4.

Cheers.

**Comment by ph7vc** [comment]
Can you show a fiddle of it working in 1.11.4?

Also, I'm not sure if i'm understanding the problem correctly, but shouldn't the `data-value` attribute determine the value loaded into the hidden input?

**Comment by danr1979** [comment]
Yes the data-value does determine that as I understand it.

I've tried to get it working using 1.11.4 on jsfiddle but I can't reproduce
it, which is strange.

I'm sure what I'm expecting is how it should work unless someone else can
correct me?

Thanks.

**Comment by jlukic** [comment]
Keep in mind you do not need to initialize `dropdown` on sub menus. So don't add the `ui` class to sub menus or else it will trigger events twice.
