### ISSUE TITLE
Consider rethinking dependencies and post install script

### ISSUE THREAD

**Issue by timkelty** [Semantic-Org/Semantic-UI#2224]
Semantic UI currently makes the assumption that the dev will `npm install semantic-ui`, go through the build process, and use the resulting files.

However, if the dev already has their own build solutions in place and wants to use semantic-ui's source files directly, this doesn't necessarily work very well.

For example, we use [Webpack](http://webpack.github.io/), alongside Gulp. Therefore, what I _want_ to do is `npm install semantic-ui --save-dev` and then require the source files directly. However, the post-install script forces me to go through a build step I don't want. (yes, I could `npm install --ignore-scripts`, but then I'd have to every time).

Along the same lines, if I'm using my own frontend tooling, then much of what is listed as a `peerDependencies` and `dependencies` may conflict.

E.g., when I run `npm install semantic-ui --ignore-scripts`:
```
npm ERR! peerinvalid The package gulp-plumber does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer semantic-ui@1.12.2 wants gulp-plumber@0.*
```

I think those would be better served as `devDependencies` (or maybe `optionalDependencies`).

Thoughts?

**Comment by jlukic** [comment]
We run separate parity repos semantic-ui-less and semantic-ui-css which provide the same structure without any of the build tools.

**Comment by timkelty** [comment]
Thanks, I didn't realize those repos existed.

And I see now that it appears that all of the JS components have their own repo as well, so we should be able to pull directly from those.

**Comment by jlukic** [comment]
Yes the build script for pushing those repos is [quite hilarious](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/distributions/update.js).

**Comment by timkelty** [comment]
Hah! well I'm glad you do it. Just what I was looking for. Thanks a ton.
