### ISSUE TITLE
Monetize brand icons?

### ISSUE THREAD

**Issue by pcj** [Semantic-Org/Semantic-UI#2227]
Apologies if this is a little off-topic, but expands on #2201.  Maybe a dumb idea, maybe not.  Thought I'd put it out there for discussion.

I wonder if there is any way to monetize these brand icons in the framework?  Whenever I see you @jlukic add new brand icons to the semantic framework, I feel like you might be giving away a free lunch.  Putting a brand icon in a major front-end framework is a pretty serious endorsement.  It's almost like a Pre-IPO list.  If people really want a BuySellAds icon, they can just include font-awesome directly or many other ways.   I dunno.  I think each one of these is worth at least $10,000 (or better yet some amount of money on a recurring basis), particularly for these borderline cases where most users don't really need the icon, but the company itself would love this form of brand validation.  I'm sure @davegandy has pondered this question, curious what his answer would be.

Problem is (like most of us), we're the widget guys/gals... our hearts are in building stuff, not necessarily  in selling it.  I suspect you are the same.  You'd need a salesperson.

**Comment by ph7vc** [comment]
Interesting thought, but seems kinda silly to do that. Since those icons are part of [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/), I would imagine a company would rather sponsor font awesome vs a framework using it.

Perhaps a company that wants an icon for themselves included in the framework could make a small donation for it to be added?

**Comment by jlukic** [comment]
Just wanted to start off by saying thanks @pcj  for thinking about ideas for helping making the project financially stable. 

I'd have to agree with ph7vc however. The icons are all Dave Gandy's work, I can't really use them for generating revenue.

**Comment by pcj** [comment]
That's fine, thanks for the feedback.  Of course Dave Gandy made the icons, and he's a wonderful icon designer.  

But through semantic, you implicitly have the demographic eye of the people that are building what tomorrow will look like.  In my view, it's analogous to sponsoring a pro cyclist.  The logo gets splashed all over the shirt, and then all of the sudden you have a million cyclists buying Trek jerseys, and they're definitely not getting paid.  I personally don't get why amateur cyclists wear such garb, but they do, in spades.

You/semantic are/is the cyclist, and I think brands would pay for the eyeballs and the mindshare they get through inclusion into a quality framework.  Just sayin'
