### ISSUE TITLE
[UI] Plan Selector

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#223]
## Overview

`ui plans`
A view for presenting choices between pricing plans for a website.
## Content
- **Plan**: A group of plans can contain individual plan choices
- **Features**: A plan can contain a list of features
- **Action**: A plan can contain a button linking to a follow up action
## Types
- **Vertical**: A plan picker that is formatted vertically to show lists of options in a table
## Variations
- **Size** (Plans): A plan picker can vary in size
- **Featured** (Plan): A plan can be featured to show it is the emphasized plan choice
## Examples

https://proto.io/en/signup/
http://useqwitter.com/
http://demo.designwall.com/dw-simplex/?page_id=493
http://www.trunkclub.com/features

http://bootsnipp.com/snipps/pricing-table-example
http://bootsnipp.com/snipps/crowdfunding-grid

**Comment by confact** [comment]
So waiting for this!

**Comment by hason** [comment]
:+1:

**Comment by listepo** [comment]
+1

**Comment by avalanche1** [comment]
+1

**Comment by listepo** [comment]
http://codepen.io/alirezaaa/pen/rabbQG

**Comment by spaquet** [comment]
+1
I like this one https://proto.io/en/pricing/, really in the spirit of semantic

**Comment by sangyoo91** [comment]
When will we be able to see this?

**Comment by Un3qual** [comment]
+1 yes please

**Comment by lastnoob** [comment]
Is it coming?

**Comment by listepo** [comment]
http://codepen.io/j-w-v/pen/DIcJx

**Comment by ilikebits** [comment]
:+1:

**Comment by henwen** [comment]
+ :100:

**Comment by Tusharsb** [comment]
+1

**Comment by romanzipp** [comment]
I created an example with cards, labels and dividers:

https://codepen.io/romanzipp/pen/XKvGXz

**Comment by brainscript** [comment]
@romanzipp Looks awesome! :smile_cat:

**Comment by tridcatij** [comment]
@romanzipp Looks great! I've added .link class to the cards, so it more interactive with user

**Comment by basememara** [comment]
There's also this one: https://codepen.io/caiosantossp/pen/vNazJy

It would be great if this was built into Semantic-UI though.

**Comment by rlingineni** [comment]
I just made my own with a UI grid, Statistic and Segments. Very easy.

https://codepen.io/rlingineni/pen/vRrpmq/
