### ISSUE TITLE
Best jQuery version (1.x or 2.x) for SUI 2.x + CDN

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2231]
HI,
Im just wandering, is it fine to work with jQuery  2.x ?
I check the Source Code of the SUI (2.0) Homepage (http://beta.semantic-ui.com), I find that your check for things before loading jQuery:

```javascript
(function () {
  var
    eventSupport = ('querySelector' in document && 'addEventListener' in window)
    jsonSupport  = (typeof JSON !== 'undefined'),
    jQuery       = (eventSupport && jsonSupport)
      ? '/javascript/library/jquery.min.js'
      : '/javascript/library/jquery.legacy.min.js'
  ;
  document.write('<script src="' + jQuery + '"><\/script>');
}());
```

But I want to use a CDN, and I prefer to work with jQuery 2.x, is that fine ?
and What about a CDN for Semantic-UI 2.x, is there an Official one, if not can someone provide best updated CDN for SUI 2.x.

**Comment by jlukic** [comment]
You can use any jQuery version > 1.8.

**Comment by ikourfaln** [comment]
Thanx @jlukic for reply
But if there is no problem with jQuery 2.x, why are you checking for querySelector, addEventListener and JSON support !!!

**Comment by jlukic** [comment]
1.x branch is for IE9 support and non standard compliant browsers, the code in the docs is just another version of saying. 
```
<!--[if lt IE 9]>
    <script src="jquery-1.9.0.js"></script>
<![endif]-->
<!--[if gte IE 9]><!-->
    <script src="jquery-2.0.0.js"></script>
<!--[endif]-->
```

I'll remove the legacy jquery links with beta docs. IE9 is no longer a supported browser.

**Comment by ikourfaln** [comment]
:+1:  thats what Im saying... Thanx

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/82248f68b375766e86c44fee05c970b75631d3eb
