### ISSUE TITLE
.ui.dropdown .menu > .input min-width:200px in semantic.css

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2232]
```min-width: 200px```
http://jsfiddle.net/efp8z6Ln/143/
Is this intentional? I have shorter fields in my app)

**Comment by ikourfaln** [comment]
I think that was fixed on new version  (SUI 2.0) as I see is this commit:
https://github.com/Semantic-Org/Semantic-UI/commit/cfe3b2ec5645e0f89d9263e9c6da6f4b682fce72

**Comment by jlukic** [comment]
The min width of the default theme have been reduced in `2.0`. I'm happy with current values.

**Comment by ikourfaln** [comment]
thanx for clarifying :+1:

**Comment by daniel18387** [comment]
**Note to anyone else with this issue:** Adding the class `fluid` to a `dropdown` will remove the `min-width`.

**Comment by ikourfaln** [comment]
thanx @daniel18387 for infos 😉
