### ISSUE TITLE
docs: add javascript code to examples

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2234]
Hello, Jack!
I think it'd be nice to include javascript code in examples on SUI.com besides plain HTML.
I like your examples very much, but do not have the faintest idea how some of'em work.
E.g. category search here : http://semantic-ui.com/modules/search.html How do you output animals results in such nifty manner?)

**Comment by ph7vc** [comment]
They work just like a jquery plugin works.

You use a selector: `$('.ui.search')`
Then you call a plugin method on it; in the case: `$('.ui.search').search()`

Most plugins in SUI accept a JSON object as a parameter; ( those which can be applied are in  the settings tab ) which can override the default value. 

There is also the behaviorial methods you can call, so a good example is like: `$('#myModal').modal('show');`

Hope that helps!

**Comment by jlukic** [comment]
I think what's missing is a general introduction to using modules.

You can check out legacy examples if that helps
http://legacy.semantic-ui.com/module.html#/init

**Comment by avalanche1** [comment]
thank you for the link.
learnsemantic should definitely be appended by these docs in the future

**Comment by avalanche1** [comment]
especially articles from 'Introduction' block
