### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by sazap10** [Semantic-Org/Semantic-UI#2235]
Hi, 

I am wondering how to use custom fonts within a custom packaged theme, I have placed my fonts inside the `themes/mytheme/assets/fonts` however running gulp build doesn't output those files into the dist folder. Is there a solution to this?

**Comment by ph7vc** [comment]
This file: https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables

You can set the Google font you want to use but it doesnt look like there is a 'standard' way to use your own local font.

**Comment by jlukic** [comment]
@sazap10 Currently assets are only copied if the files match the name of a ui element. Try adjusting your font name to `icon.ext` or `icons.ext`
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/watch.js#L214
