### ISSUE TITLE
Rails 4 / Bower configuration help needed

### ISSUE THREAD

**Issue by pixxelboy** [Semantic-Org/Semantic-UI#2239]
Not going to flood, here's the deal : http://stackoverflow.com/questions/30174920/proper-semantic-ui-bower-rails-4-configuration
Thanks for your support :+1:

**Comment by jlukic** [comment]
If you are using less source files without npm (which includes an installer), you will need to manually create  `theme.config` from `theme.config.example`
https://github.com/Semantic-Org/Semantic-UI/tree/master/src#config-files

**Comment by pixxelboy** [comment]
Hi @jlukic, thanks for your quick reply. Could you be more specific, especially on where to install these files ? And how to tangle them all together ? Should these files and folders go in the rails app/assets/stylesheets folder ?

Thanks!

**Comment by pixxelboy** [comment]
Ok so here's what I've come up to until now.
semantic-ui is properly installed in vendor/assets
![capture d ecran 2015-05-12 a 13 13 17](https://cloud.githubusercontent.com/assets/656110/7586025/ddbad640-f8a8-11e4-868e-0344f50c0149.png)
Lib is loaded via semantic.css.less as below
![capture d ecran 2015-05-12 a 13 15 23](https://cloud.githubusercontent.com/assets/656110/7586042/0cdcb09c-f8a9-11e4-8efb-d6641e45c471.png)
Now I'm bumping on using the custom site.variables, .variables .overrides files from assets/stylesheets/site folder.

They're obviously not used. Thanks for your support!

**Comment by GrimReaperSam** [comment]
Hi @pixxelboy 
Have you found a solution? I'm having the same problem at the moment.
Any help is appreciated.
Thanks!

**Comment by danielmcoelho** [comment]
+1 
Can't find a way to have .overrides and .variables (custom theme) in the "app/assets/..." instead of directly change "vender/assets/bower_components/..." files. 
Kinda defeats the propose of bower, where you should be have to upgrade without overriding files.
Also I'm a bit confuse on which "autocompiler" to use: Rails default assets pipeline (with a less gem) or gulp (only because I don't want my teamworkers to have to install gulp and have to do the "watch" command all the time).
Help! :/ Thanks!

**Comment by bsssshhhhhhh** [comment]
@pixxelboy 

A year later, but did you ever manage to resolve your issue? I'm having the same issue (different specific setup, but same problem). All I want to do is override 1 variable (making the border color on inputs a bit darker) without modifying anything inside the bower directory. I don't want to create an entire new theme. I want to use the default theme, with that one change.

I've now wasted three hours trying unsuccessfully to do that. With Bootstrap it's as simple as setting the variable before importing the main Bootstrap less/sass file, but with Semantic it seems I have to jump through seventeen extra hoops to integrate it.

**Comment by bsssshhhhhhh** [comment]
Ok I just ended up overriding what I want using my own css rules with `!important` after `@import 'semantic';`. Not worth the trouble to figure out how to do it 'correctly'
