### ISSUE TITLE
[Validation] - Validate Individual Fields

### ISSUE THREAD

**Issue by phillip-haydon** [Semantic-Org/Semantic-UI#224]
Would be nice to invoke validate on a single field.

i.e

`var result = $('.ui.form').form('validate field[email]');`

Where `email` is the key of the validation property:

```
            email: {
                identifier: 'Email',
                rules: [{
                    type: 'empty',
                    prompt: 'Please enter an email'
                }, {
                    type: 'email',
                    prompt: 'Invalid email'
                }]
            },
```

Also would be nice to be able to mark a field as invalid manually:

`$('.ui.form').form('get[email]').setInvalid('Email already in use');`

`$('.ui.form').form('get[email]').setValid();`

For when custom validation is written outside of Semantic.

**Comment by Enelar** [comment]
@jlukic up

**Comment by avalanche1** [comment]
+1

**Comment by sos0** [comment]
+1
