### ISSUE TITLE
[Dropdown] Add Keyboard Shortcuts for In-Menu Input

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2240]
How can I navigate to the search field with 'tab' key?
http://jsfiddle.net/efp8z6Ln/146/
Wouldn't it be logical that upon opening the dropdown - search field would be autofocused?

Also it would be nice that when i have 'transport' selected and press 'up' key, search field would get focused.

**Comment by jlukic** [comment]
I've marked this as a future enhancement.

**Comment by michgeek** [comment]
Hello guys, any update on this one ?

**Comment by avalanche1** [comment]
Additional request: when dropdown is open, on 'Home' and 'End' keys - 1st and last items in dropdown sd be selected
