### ISSUE TITLE
(DOC) bad link in dropdown documentation

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#2241]
Description
A dropdown menu can contain a description.

=> description points to icon element

**Comment by deneuxa** [comment]
Same problem with

Image
A dropdown menu can contain an image
=> "image" points to input element

**Comment by ikourfaln** [comment]
This is a Doc issue, you must submit it here:
https://github.com/Semantic-Org/Semantic-UI-Docs
Anyway, I see that label points to input element, I made a pull requests to fix that. waiting for merge.

**Comment by jlukic** [comment]
Appears to be fixed
