### ISSUE TITLE
How to add avatar in header

### ISSUE THREAD

**Issue by marijang** [Semantic-Org/Semantic-UI#2242]
How to add avatar in header?

**Comment by ikourfaln** [comment]
what do you mean, can you be more specific ?
Because you can use image as avatar in header, example:
http://semantic-ui.com/elements/header.html#image

**Comment by marijang** [comment]
i m using top menu. Always get padding more then other items in menu
![menu](https://cloud.githubusercontent.com/assets/1381443/7598117/7cb35d04-f8f8-11e4-8eb4-abc1b8f12657.PNG)


<div class="ui grid">
        <div class="computer tablet only row">
            <div class="ui fixed inverted menu medium">
                <div class="container">
                      <div class="ui right pointing user dropdown  item " tabindex="0">
                          <img class="ui  avatar image " src="https://graph.facebook.com/v2.2/10203681708616974/picture?type=small">
                           Marijan 
                          <div class="menu transition hidden" tabindex="-1">
                              <a class="item">Action</a>
                                <a class="item">Seperated link</a>
                                <a class="item" ui-sref="index" ng-click="navbar.doLogout()" href="#/">Log Out</a>
                    </div>
 </div>

**Comment by marijang** [comment]
I post code of my example. Sory i was thinking about menu not header.
By the way great work:D

On 12 May 2015 at 22:35, Jack Lukic <notifications@github.com> wrote:

> Closed #2242 <https://github.com/Semantic-Org/Semantic-UI/issues/2242>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/2242#event-303214635>.
>



-- 
Marijan Greguric

**Comment by jlukic** [comment]
Menus are rewritten in 2.0, see closed threads related to flexbox vs inline block. 1.0 does not resize vertically with oversized content
