### ISSUE TITLE
[Dropdown] 'set selected' does not recognize dynamically added items?

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2247]
Hi,

Here's a [fiddle](http://jsfiddle.net/andreyvk/spn2k9th/) to reproduce the issue, if it's an issue of course. I have doubts that I am doing something wrong here. But anyways...

Here's the problem:
1. We have an existing dropdown
2. ```menu``` items in dropdown change dynamically and we need to select a new value.
3. But for some reason ```.dropdown("set selected", "new value")``` does not kick in

**Comment by jlukic** [comment]
Works fine
http://jsfiddle.net/px4kzo62/

**Comment by andreyvk** [comment]
Understood. Thanks @jlukic

**Comment by avalanche1** [comment]
seems like an undocumented feature

**Comment by jlukic** [comment]
Yes, there's a few features like that which are just designed to allow developers to be lazy and everything can 'just work'.

**Comment by achimkoellner** [comment]
The refresh-method doesn't seem to work if the source element was a select element:
http://jsfiddle.net/nfsfb87y/
Couldn't find any documentation on set selected.
If I use a timeout after I append options to the select box it works.

http://jsfiddle.net/nfsfb87y/1/

I think the request method sould maybe return a promise such as

	$("[name=productIds]").dropdown("refresh").then(function() {
		$("[name=productIds]").dropdown("set selected", "3"); 
	});


I looked at the refreshSelectors method #4486 and to me it looks like a select element wouldn't be refreshed, is that possible?

**Comment by sarbona** [comment]
I had the same problema as achimkoellner.
The "set selected" didn't work after dynamically fill a select element.
I tried the "refresh" before the "set selected" method but still didn't work.
The only solution was to use a setTimeout to call "set selected" async.

for (var id in championships) {
	var $option = $("<option value=\"" + id + "\">" + championships[id].name + "</option>");
	$select.append($option);
}
$select.dropdown('refresh');
if (defaultValueId)
	setTimeout(function () {
		$select.dropdown('set selected', defaultValueId);
	}, 1);

**Comment by brunotourinho** [comment]
same problem here with the <select>

+1 for @sarbona workaround

**Comment by JotaMiller** [comment]
+1 for @sarbona workaround.

Works like a charm

**Comment by milkymura** [comment]
+1 for @sarbona . worked for me! :)

**Comment by rpsirois** [comment]
I had the same problem. I also couldn't dynamically add options with value="" (empty string).

**Comment by basistam** [comment]
+1 @sarbona Isn't this a bug?

**Comment by dcastro2** [comment]
+1 @sarbona

**Comment by dodyeast** [comment]
Cool.. +1 @sarbona

**Comment by SantiagoMarcelino123** [comment]
+1 @sarbona saved my day

**Comment by viicviicviic** [comment]
+1 @sarbona thanks, bro!

**Comment by douglasg14b** [comment]
This would be good to document, it's one of the many "gotchas" I've found when attempting to use semantic UI with angularjs.

**Comment by Jameron** [comment]
Is setTimeout() still the only way to get this to work? Whenever I see setTimeout() as the accepted solution I want to jump off a cliff.

**Comment by andreyvk** [comment]
@Jameron no, if you look at earlier posts you'll find that you can use `$(".ui.dropdown").dropdown("refresh");`

**Comment by Jameron** [comment]
What about if I just dynamically added a list item?

$('#entity').dropdown('refresh');
$('#entity').dropdown('set selected', newEntity[0].id);

The set selected is failing. If I run it in console it works, seems like it needs a timeout or promise to stop async?

**Comment by andreyvk** [comment]
Then it's setTimeout(), i guess. I myself have a bunch in the code already. Nowhere to run

**Comment by tribaltrading** [comment]
Instead of setTimeout, you can also put your on observer on the select element you're using as a dropdown like so: [http://jsfiddle.net/XfxJu/2/](url).

**Comment by jaswinderahuja** [comment]
I am also facing same issue as if I am using remote content in dropdown list dynamically in that case 

$('.remote.ui.dropdown').dropdown('refresh');
$('.remote.ui.dropdown').dropdown('set selected',this.props.params.id); 

is not working

**Comment by jaswinderahuja** [comment]
I want to prepopulate the value when form is loading and also to give the option to the user to select the option from given list which is coming remotely using apiSetting parameters.

  $('.remote.ui.dropdown').dropdown({
      apiSettings: {
        url: '/api/call'
      },
      filterRemoteData: true
    });

    $('.remote.ui.dropdown').dropdown('refresh');
    $('.remote.ui.dropdown').dropdown('set selected',2);

**Comment by yaumsnus** [comment]
+1 for @sarbona ! Thanks a lot !

**Comment by coder8keyboard** [comment]
I use Aurelia framework. Both refresh and timeout did not work for me due to async operations. I had to wrap my code with a Micro Task Queue to make it work. It allowed the 'set selected' method to run right after getting ajax data.

**Comment by binarygit** [comment]
I had the same issue as @sarbona 
Mine went away after I explicitly set the `value` attributes in my `option` elements.

**Comment by andreyvk** [comment]
If you're not too far in with the project you might wanna look into using [Fomantic UI](https://fomantic-ui.com/)
