### ISSUE TITLE
kitchen sink page continuously using 20 to 25% CPU 

### ISSUE THREAD

**Issue by bw2** [Semantic-Org/Semantic-UI#2248]
When I open http://semantic-ui.com/kitchen-sink.html#/elements in chrome or firefox on MacOSX or windows, it continuously uses > 20% CPU. Comparable non-semantic-UI pages drop down to < 10% after the initial CPU spike. I've seen people mention the CPU load on forums comparing semantic UI to other frameworks and am worried that high CPU usage is an inherent aspect of Semantic UI's design. Is there some specific feature(s) that can be disabled to reduce CPU usage?

![image](https://cloud.githubusercontent.com/assets/6240170/7615845/3f5a200c-f96e-11e4-9d8e-1da899b545f1.png)

**Comment by pcj** [comment]
This is likely due to the demonstration of about 20 different spinning loading icons all on the same page.  Animating all that requires continuous CPU time.  Real-world pages don't typically have this issue (unless a game of course).

http://jsfiddle.net/ka98j2pv/3/

**Comment by bw2** [comment]
Thank for your help! That makes sense, and I confirmed that removing the spinners from the jsfiddle and/or from kitchen-sink.html eliminated the CPU load.

**Comment by jlukic** [comment]
The progress bars are all auto updating on that page as well :heavy_multiplication_x:

**Comment by dandv** [comment]
See also #2316.
