### ISSUE TITLE
Sidebar Pusher and Sticky "Flickers"

### ISSUE THREAD

**Issue by oniisaki** [Semantic-Org/Semantic-UI#2250]
I think I found a minor browser compatibility bug.

It seems when I meet the following conditions, it sometimes causes a bug, i.e. sticky "flickers" while scrollng:
1. Have a sticky
2. Trigger the sidebar pusher transition
3. Then scroll under chrome
4. Run the file as HTML, or PHP under WAMP localhost

May need to repeat 2 and 3 a few times, since it doesn't always occur.
The bug doesn't occur under Firefox, Internet Explorer or with Online Playgrounds such as plunker and JSFiddle. It seems specific to chrome.

Here's the plunker link. This does not demonstrate the issue. As I mentioned, the problem seems to only reproduced under certain conditions.
http://plnkr.co/edit/ZV3OCSHDLL3gf4hnoR2S?p=preview

Note: 
Used plunker instead of JSFiddle since it provides a download option to make it easier to reproduce this problem.

**Comment by thinksaydo** [comment]
I downloaded the code and ran locally, but could not reproduce this behavior in latest Chrome. Might be a plugin causing trouble. What happens if you run this in an Incognito window?
