### ISSUE TITLE
Feature Request: float labels

### ISSUE THREAD

**Issue by marijang** [Semantic-Org/Semantic-UI#2251]
It will be nice to have something like this
[link](https://www.gosquared.com/blog/login-screen-design-flow)

What do you think?

**Comment by ikourfaln** [comment]
I think Semantic-UI not interested on UX design, it cant include all Animations and Effects !!
Semantic-UI is for UI, and include just the important and must useful things, @jlukic working hard to fix bugs and enhancing Docs.
you can find cool things in the web, just google, example:
http://tympanus.net/Development/TextInputEffects/index2.html
and use theme with SUI.
As I said, I think that what SUI is.

PS: Im sorry for my bad english language, but you catch the idea.

**Comment by jlukic** [comment]
This isn't in the scope of the project. Please make specific suggestions for new types of user interface components or specific feature enhancements to existing components. If you would like to share interesting links to discuss use our chat room.

**Comment by listepo** [comment]
+1 http://bradfrost.com/blog/post/float-label-pattern/
