### ISSUE TITLE
checkbox suggestions

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2255]
It'd be nice to have smaller sizes available for toggles and sliders.
And to be able to set colors to all checkbox variations.

**Comment by jlukic** [comment]
There's a colored theme available in beta docs. This can all be done with theming.
http://beta.semantic-ui.com/modules/checkbox.html

I dont recommend changing checkbox sizes for UX reasons. Generally this isn't done, and any smaller hitbox is bad for mobile UI
