### ISSUE TITLE
Implement the "center" class for dropdowns

### ISSUE THREAD

**Issue by nicbarker** [Semantic-Org/Semantic-UI#2256]
I really like how the semantic popup supports the class "center" (i.e .center.left) to position the popup vertically or horizontally centered compared to it's parent, like so:
![screenshot 2015-05-11 21 08 43](https://cloud.githubusercontent.com/assets/2264338/7644923/fba5f862-faef-11e4-9cbe-68ade785833b.png)
Any plans to expand this functionality to include dropdowns as well? At the moment I believe only the left, right, top and bottom classes are available, so dropdowns always appear like this:
![screenshot 2015-05-15 10 50 48](https://cloud.githubusercontent.com/assets/2264338/7644931/4493e4b2-faf0-11e4-8e84-0179d1268a92.png)
 I'm also happy to implement and PR myself if needed.

**Comment by jlukic** [comment]
I recommend using popup for content that needs to be placed explicitly. Dropdowns are designed explicitly for user selection, not overlays.
http://beta.semantic-ui.com/collections/menu.html#popup-menu
