### ISSUE TITLE
[Bug][Dropdown] Selected count when disabling Text Labels

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2259]
As you can see in those examples:
http://beta.semantic-ui.com/modules/dropdown.html#text-labels

when you select item, its fine:

![exa1](https://cloud.githubusercontent.com/assets/9744226/7661373/01edc966-fb4a-11e4-8c8b-63b05019cea4.png)

when you deselect items, it stuck at 1 selection:

![exa2](https://cloud.githubusercontent.com/assets/9744226/7661377/080973f4-fb4a-11e4-9cfe-1cfdd5e7d6a1.png)

**Comment by jlukic** [comment]
Thanks, that was a bug.

**Comment by ikourfaln** [comment]
Thanks for fixing
