### ISSUE TITLE
Sidebar causing black page at the bottom of pusher

### ISSUE THREAD

**Issue by yevta** [Semantic-Org/Semantic-UI#2261]
I have a left sidebar, but it doesnt fit with pusher. Look at the bottom of the pusher. There is a blank/black page instead a fixed bottom of page.
how to solve it?
Thank you...

![black](https://cloud.githubusercontent.com/assets/8588461/7664317/7c51bbba-fbac-11e4-9f2a-19e5568a630a.png)

**Comment by jlukic** [comment]
Closing due to no test case.
