### ISSUE TITLE
A problem in shape of SemanticUI 

### ISSUE THREAD

**Issue by zysdcyymyw** [Semantic-Org/Semantic-UI#2262]
I made a simple login page.
It has a div contains two .sides in it.
I put two buttons on the page,one is inside the shape and another is outside it.Both of them have a class named 'btn_reg'.
I wrote following code in the onready event of document:
$('.btn_reg').on('click',function(){
$('.shape').shape('flip left');
});
When I click the button outside the shape, the beautiful animation shows normally.
But when I click the button inside the shape, the animation disappears quickly.
I tested it in both Firefox and Chrome. But this problem exists in both of them.
The link of this problem is http://muncs.vipsinaapp.com/system/
What should I do to solve it?

**Comment by jlukic** [comment]
Please provide a JSfiddle with the minimum html required to recreate the layout issues. Removing your site specific code. 

You can find a JSFiddle link to fork in the readme.

**Comment by zysdcyymyw** [comment]
http://jsfiddle.net/ayuqk4w7/1/

**Comment by zysdcyymyw** [comment]
@jlukic The JSfiddle link is over here,what should I do to make it work normally?

**Comment by jlukic** [comment]
I'll take a look tomorrow. It looks like just removing `transition` from the button fixes it as well.

**Comment by zysdcyymyw** [comment]
@jlukic Here is a page with more codes.The previous active side looks as if it disappears when I click the buttons.But sometimes it shows normally.

http://jsfiddle.net/pqwoocwr/

**Comment by jlukic** [comment]
This appears to be a chrome bug, https://code.google.com/p/chromium/issues/detail?id=455240

**Comment by zysdcyymyw** [comment]
@jlukic But its transparency in Firefox also has some problems.The previous side is nearly transparent as soon as I click the button sometimes.It looks very strange.

**Comment by hmaesta** [comment]
I guess it's working fine here. Chrome 42.0.2311.152 (64-bit) OS X.

**Comment by jlukic** [comment]
Closing since I dont think theres a fix forthcoming.

**Comment by vnmone** [comment]
I have the same behaviour (not bug?)(chrome 49.0.2623.110)
Removing transition from button helps me.
