### ISSUE TITLE
Inverted menu pointing

### ISSUE THREAD

**Issue by Thijs5** [Semantic-Org/Semantic-UI#2263]
When inverting a pointing menu there is a bug with the 'pointer'. The colors don't realy match and the spacing isn't completely right. See screenshots below. The first screenshot is the regular active state. The second screenshot is the active state while hovering the item.
![screen shot 2015-05-16 at 19 14 57](https://cloud.githubusercontent.com/assets/1286325/7667208/518f09c4-fc00-11e4-9a57-0f4641ef6ca5.png)
![screen shot 2015-05-16 at 19 18 47](https://cloud.githubusercontent.com/assets/1286325/7667213/725dc460-fc00-11e4-919c-202aad0beee2.png)

**Comment by ikourfaln** [comment]
+1 you right

![menu](https://cloud.githubusercontent.com/assets/9744226/7667450/f96a9326-fbff-11e4-93d2-d1193773658f.png)

**Comment by jlukic** [comment]
Adjusted positioning example
http://jsfiddle.net/gccq2fz2/
