### ISSUE TITLE
[Button] Add Text color to Basic Button :focus

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2264]
```.basic.button :focus``` should have the same styling as ```.basic.button :hover```
otherwise you cannot visually distinguish where your focus is at when tabbing through them
http://jsfiddle.net/efp8z6Ln/150/ (try tabbing through all btns)

**Comment by ikourfaln** [comment]
+1

**Comment by jlukic** [comment]
This added a few kb to rules but is probably worth it in the long run. I've moved all docs examples to be keyboard focusable to help demonstrate.

**Comment by avalanche1** [comment]
Wow, that was a lot of work! But definitely worth it! You're my hero!

**Comment by avalanche1** [comment]
`color` is still not changed on `:focus`.

**Comment by jlukic** [comment]
I can confirm text color is missing from `:focus`

**Comment by jlukic** [comment]
Added in `2.1
