### ISSUE TITLE
How to use image.variables 

### ISSUE THREAD

**Issue by funkytaco** [Semantic-Org/Semantic-UI#2265]
According to the docs:
`Semantic uses arbitrary default values for image sizes from mini to massive. It is recommended to update these with values used in your project in image.variables.`

But no information is given on how to do this and I couldn't find anything with my google-fu.

Thanks.

**Comment by jlukic** [comment]
http://learnsemantic.com/developing/customizing.html

**Comment by funkytaco** [comment]
That page mentions button.variables, site.variables. I've no clue what to put inside of image.variables without at least some information.

would I just put something like:
    mini: 50px;
    tiny: 100px;
    huge: 250px;

because I tried that and it didn't work.

**Comment by jlukic** [comment]
`@miniWidth` etc, in all cases you need to look up the variables available by checking the default theme file. In this case, `default/elements/image.variables`

I believe this is explained on learn semantic.
