### ISSUE TITLE
[Search] Search ignores minCharacters length on "set value"

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2266]
Hi,

I suspect that ```search``` ignores ```minCharacters``` setting, when doing ```.search("set value", "")```. 

Here's a [fiddle](http://jsfiddle.net/andreyvk/usvmejd0/). 

Just click the *Clear* button to reset field's value and trigger ```onSelectQuery()``` callback

Im found this on version ```1.12.2```. ```set value``` behavior also triggers an ajax call for me.

**Comment by jlukic** [comment]
Yes, the min character check was part of input event not `query` so setting programmatically did not trigger. This should fix.

**Comment by andreyvk** [comment]
Thanks
