### ISSUE TITLE
Cards - Multiple bottom attached buttons

### ISSUE THREAD

**Issue by jaypanares** [Semantic-Org/Semantic-UI#2267]
Hi, trying to create multiple bottom attached buttons in the card view.  Is there any way for the bottom attached buttons to display horizontally instead of stacking on top of one another?  Thanks!

**Comment by jlukic** [comment]
Closing due to lack of test case

**Comment by jaypanares** [comment]
Sorry about that.  Please see the jsfiddle below:

http://jsfiddle.net/jaypanares/Loatezun/1/
