### ISSUE TITLE
Form submitting repeatedly after sucessfull validation

### ISSUE THREAD

**Issue by anishpsla** [Semantic-Org/Semantic-UI#2268]
My form validation using semantic ui form validation is not working correctly. I follow a tutorial from YouTube. It works perfectly. But the form is submitting repeatedly after validation. To test the code, I put an alert on validation success block. I got two alerts one after another. Here is my code.
```
var validation  = {
cusname:{
identifier:'cus-name',
rules:[
   { type:'empty'}
]
}}

var settings = {
onSuccess:function(){
alert('test');
return false; 
}};

$('.ui.form').form(validation,settings);
```

**Comment by jlukic** [comment]
Please create a jsfiddle, theres a link to fork in the readme.

**Comment by anishpsla** [comment]
Here is the Jsfiddle. I change the Jquery version to latest to work the example

http://jsfiddle.net/ye86hm47/1/

**Comment by tangxuezhi** [comment]
I came across this issue, too. and if use the original submit mechanism, for example "$form.form('submit');", validate success callback function will call repeatly, debug log show "Maximum call stack size exceeded". jsfiddle: [https://jsfiddle.net/tangxuezhi/fpj3th04/1/](https://jsfiddle.net/tangxuezhi/fpj3th04/1/)

**Comment by jlukic** [comment]
@tangxuezhi 

Calling `submit` in `onSuccess will revalidate the form

Instead just call submit on the form button
https://jsfiddle.net/d8L58xay/

**Comment by jlukic** [comment]
@anishpsla You've initialized form twice, because you have two `ui form` elements. So it attached the events twice.

Fixed version
http://jsfiddle.net/wfux9o2w/

**Comment by anishpsla** [comment]
Thanks for the help. The problem caused by copying the example directly from example. Now it's ok
