### ISSUE TITLE
Angular popup -- css only

### ISSUE THREAD

**Issue by vautrinr** [Semantic-Org/Semantic-UI#2270]
Hello,
I am loving semantic UI. :)
However, I am facing few problems : 
I am using angular for a ng-repeat, and a semantic UI popup. The jQuery for the popup is not triggered since the angular comes after the jquery. Is there any full-css version like for the dropdown ? 

Thanks by advance, 
Rémi

**Comment by jlukic** [comment]
You might want to check out GitHub Issues on [Semantic-UI-Angular](https://github.com/Semantic-Org/Semantic-UI-Angular/issues) they are better equipped to help you.
