### ISSUE TITLE
column color spec not honored for some examples at http://semantic-ui.com/collections/grid.html

### ISSUE THREAD

**Issue by stuartallenmills** [Semantic-Org/Semantic-UI#2272]
The color specification is ignored in the following declarations at http://semantic-ui.com/collections/grid.html (tested Windows IE, FireFox, Chrome).  Also ignored in my code. Specifying a row appears to be required to get the color to work.

<div class="ui vertically padded page grid">
    <div class="teal column">
      <h2 class="ui inverted header">Column Background</h2>
      <p>Third section of content</p>
    </div>
  </div>

<div class="ui vertically padded page grid">
    <div class="black column">
      <h2 class="ui inverted header">Column Background</h2>
      <p>Fourth section of content</p>
    </div>
  </div>

    <div class="eight wide teal column">
      <h2 class="ui inverted header">Sitemap</h2>
      <p>Second section of content</p>
    </div>

**Comment by ikourfaln** [comment]
that was fixed on version 2.0:
http://beta.semantic-ui.com/collections/grid.html#full-width-backgrounds

**Comment by jlukic** [comment]
Thanks Stuart. This does seem critical enough to warrant a backport to `1.x`. Although this is part of the quite sizable `2.0` [release](https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md#version-200---march-xx-2015) coming June 1st.

**Comment by jlukic** [comment]
Adding patch release today as `1.12.3`
