### ISSUE TITLE
add .popup({closable}) setting for 'on:focus' (similar to on:click)

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2274]
Try opening this http://jsfiddle.net/avalanche1/n1o3v45h/ on ur phone.
When you click input field with the 'long' popup (3rd), ur phone's screen kb will pop up:grimacing: and the view will zoom in, but the input field still will get out of sight (somewhere north). When you try to drag the screen up to see, what you are actually typing, the popup will disappear.
This doesnt happen if I set .popup(closable:'false', on:'click'), but i need the popup to appear when i'm tabbing through my inputs on PC, thus I have to set .popup(on:'focus').

**Comment by jlukic** [comment]
This is a different setting, `hideOnScroll: false`

**Comment by avalanche1** [comment]
Ah, yes, that's exactly what's needed.
but the documentation is *far* from obvious.
I can update it and PR with smth like
```
Whether popup should hide on scroll and touchmove, auto only hides for popups withohut on:click
Set to *off* to prevent mobile browsers from closing popups on input fields.
```
And also move this setting descr next to ```closable``` as they seem to be kinda related..

**Comment by jlukic** [comment]
PR sounds great. Be sure to add it to `next` branch of Sematic UI Docs
https://github.com/Semantic-Org/Semantic-UI-Docs/tree/next

**Comment by avalanche1** [comment]
done
