### ISSUE TITLE
Howto create a Select all for checkboxes

### ISSUE THREAD

**Issue by tobybowers** [Semantic-Org/Semantic-UI#2275]
Hi, I'm trying to create a select all button to toggle all checkboxes (toggles) to an On state.
I'm managed to get the On state set via the $(".toggle.checkbox").addClass('checked', true) but the visual state of the checkboxes does not update.

I've also tried adding .checkbox('refresh') but again this does nothing for the visuals.

What do I need to do to refresh the visuals of the checkboxes?

Thanks & Regards,
Toby

**Comment by ikourfaln** [comment]
You can Attach Events to other Elements, just check Docs example:
http://beta.semantic-ui.com/modules/checkbox.html#attaching-events-to-other-elements

**Comment by jlukic** [comment]
```javascript
$('.ui.checkbox').checkbox('check');
```

**Comment by ikourfaln** [comment]
Thanx @jlukic :+1:
