### ISSUE TITLE
semantic-ui.com down

### ISSUE THREAD

**Issue by GibsonSG76** [Semantic-Org/Semantic-UI#2276]
Hi !
Your website (semantic-ui.com) doesn't work anymore.

**Comment by peterchoo** [comment]
The CSS file is not found: http://semantic-ui.com/dist/semantic.min.css

**Comment by jlukic** [comment]
Must have been an error deploying after release. I will republish.

**Comment by jlukic** [comment]
And we're back up

**Comment by peterchoo** [comment]
:+1:

**Comment by GibsonSG76** [comment]
thanks !
