### ISSUE TITLE
Overlapping select & accordion elements

### ISSUE THREAD

**Issue by xarmy** [Semantic-Org/Semantic-UI#2277]
Howdy! 

Using:
Semantic-UI 1.11.4 & also tested with 2.0.0 (beta) 
Chrome Version 42.0.2311.135 (64-bit), Firefox 38.01

I have a sidebar which is intended to allow easy access to application settings such as database, favorites, etc. within an accordion.  My issue is that when the options for a floating dropdown/select within an accordion content div overlay another accordion tab, not only does the default transparency of the options cause issues reading the option text, but selecting an item/option over the underlaying accordion title causes that accordion title & content div to activate and the selection clicked over the accordion title does not update the value of the select element.  On my system, this happens whether I'm using a select element or a floating search div.  

I tried to create a [jsfiddle](http://jsfiddle.net/b2by0b7w/1) to demonstrate the trouble, but I couldn't fully replicate it there for some reason - in the fiddle the select box just works and the floating search dropdown doesn't drop anything down at all...  Here's a screenshot of the overlay problem on my system (note the bleed-through of text from the underlying accordion title to the first item in the floating search dropdown):

<img src="https://cloud.githubusercontent.com/assets/12531513/7732783/40821c84-fef8-11e4-981f-58ec034bf440.png" width="40%" height="40%"/>

I think as a workaround I will move the accordion trigger to the dropdown arrow and try to tweak the transparency of the item elements, but thought this was significant enough to report and hope for a fix.

Thanks for any help!

**Comment by xarmy** [comment]
Sorry, had the wrong link to the fiddle...

**Comment by xarmy** [comment]
This appears to be a general problem with floating dropdown elements:

<img src="https://cloud.githubusercontent.com/assets/12531513/7734186/4fe9f3e0-ff02-11e4-8fdd-8ad4a1449d59.png" width="40%" height=40%"/>

**Comment by xarmy** [comment]
Hi Jack,

Maybe this additional info will help narrow down where to look...  Using the example you provided in this [fiddle](http://jsfiddle.net/7mz0nkbb/2/) I was able to sort of get the two fluid dropdown selectors laid out together as desired:

<img src="https://cloud.githubusercontent.com/assets/12531513/7773490/c69b3d66-0072-11e5-81fb-b1745758a264.png" width="40%" height="40%"/>

It works fine if you load the page and open the sidebar with the accordion open to the content div containing the dropdowns:

<img src="https://cloud.githubusercontent.com/assets/12531513/7773511/ebd648b4-0072-11e5-80aa-9916342d769c.png" width="40%" height="40%"/>

But as soon as you open another accordion content div and go back to the accordion with the dropdowns, OR if you load the page with the accordion all closed, OR if you programmatically close the accordion before the sidebar opens, you get this:

<img src="https://cloud.githubusercontent.com/assets/12531513/7773545/294bd1aa-0073-11e5-8481-2677a72f5820.png" width="40%" height="40%"/>

Updated the [fiddle](http://jsfiddle.net/b2by0b7w/4/) but again, the dropdowns don't behave the same way there so...

Thanks again for your help!

**Comment by jlukic** [comment]
Sorry I've been a bit busy trying to get `2.0` ready by next week. Other bugs might be slower than usual to respond to, but I will eventually circle back.

**Comment by ddresch** [comment]
Any news on this one? Can confirm this behavior.

I'm using the Meteor package 2.1.8. any hint where to check for the issue is also helpful.

**Comment by philrykoff** [comment]
I updated the last fiddle to actually construct `dropdown`s: http://jsfiddle.net/0ju6jpth/.

Cannot reproduce. With closed accordeons or opened ones. Or after closing and opening again (while dropdown opened or closed). All seems fine now.

**Comment by Banandrew** [comment]
Can somebody please confirm if it was fixed at some point?
