### ISSUE TITLE
active menu item is missing left black border on webkitgtk

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2278]
I would probably not complain if i wasn't using webkitgtk 2.8 on epiphany 3.16, which is on the left, compared to latest chromium on the right.
![capture du 2015-05-21 01 49 35](https://cloud.githubusercontent.com/assets/131406/7739047/b2c8fb10-ff5b-11e4-880f-b78d184e8224.png)

**Comment by jlukic** [comment]
The active border has been removed in `2.0` as a stylistic change to make the default theme more neutral.
