### ISSUE TITLE
[Table] Add Info Color

### ISSUE THREAD

**Issue by hmaesta** [Semantic-Org/Semantic-UI#2279]
Hello.

Suggestion: why not a **neutral state** for tables?
We already have positive, warning and negative, but nothing using blue color.

![Table](http://i.imgur.com/gPYtkaY.png)

**Live example:** http://jsfiddle.net/p4sjxvr5/
_(Using colors of .ui.info.message)_

Btw, would be super just use color names to give style to a table cell, like [colored segments](http://semantic-ui.com/elements/segment.html#colored).

**Comment by jlukic** [comment]
Miscategorized this

**Comment by rpsirois** [comment]
Bump. Good suggestion (also relevant to anyone looking for Bootstrap migration).

**Comment by joshbodine21** [comment]
+1

**Comment by ssarkisy** [comment]
+1

**Comment by sunjith** [comment]
+1

**Comment by domenkozar** [comment]
This would be really nice. Maybe generalizing to all supporting colors would be more consistent.

**Comment by lubber-de** [comment]
All available colors are support in table cells/rows since 2.7.0
https://fomantic-ui.com/collections/table.html#colored
