### ISSUE TITLE
[UI] Add Additional Colors

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI#2280]
Hi!

First thanks for this awesome project, it's really inspiring, and I think I'm going to use it for my next personal project :)

I'm still trying to learn how it works, so forgive me if I misunderstood something.

So my suggestion is about the common named colors, here is a short but interesting article which kind of summarize what I'm trying to do:

http://thelandofcolor.com/11-basic-color-names/

And here is the more in-depth wikipedia starting point (not really necessary to read):
http://en.wikipedia.org/wiki/Linguistic_relativity_and_the_color_naming_debate

> We have only 11 unambiguous colour terms in English: White, Black, Grey, Yellow, Red, Blue, Green, Brown, Pink, Orange, Purple.” ~Berlin & Kaye Research 1969

I know this is a complicated subject, and I know this is kind of english/western oriented, but by enhancing this list just a little bit I think we can make almost everyone happy without adding too much colors to the current list.

So, **Brown** is the only one really missing in Semantic UI, it would be really great to have it.

**White**, **Black** and **Grey** are there but not really, they are mainly used semantically as "default", "inverted" or "neutral" colors.

For example currently (next branch) I can't set a grey column, a gray or white button, and there's no difference between an "inverted" segment and an "inverted black" segment.

I think black, grey and white should be treated as real first citizen colors, "default" colors could be set to whites (or grays), "inverted" colors to blacks and "neutral" colors to grays, but this should be independant to the default color **names**. That would allow greater flexibility for the designer.

You added to the default "11 unambiguous colour terms" the **Teal** color, and I like it ^^
So this is one of the "ambiguous" color term, but we can see it more generally as the "blue-green" color that we can define, it's nice to have it.

I made a little fiddle, trying to show what I'd like to have, I think we could have a pretty nice range just by adding to the current list 3 more color names (besides grey and white):

https://jsfiddle.net/lemartialou/7m3z5ony/10/

So, what's added:

- **Brown**: well brown is brown, "unambiguous" (my example is just a suggestion for brown, I don't mind what the default value would be since we can tweak it)

- **Black**, **Grey** and **White** as first citizens (I tinted them a little bit just so we can differentiate them in the example)

- **Olive** (or it can maybe be named *Grass*, but *Olive* sounds good ;): to describe a green-yellow color.

And Purple would be divided in 2 shades: 
- **Violet**: more blue, less red. (note: I used your version of purple for this one ;)
- **Purple**: more red, less blue.

Here would be the "final" list of color names:
Red - Orange - Yellow - Olive - Green - Teal - Blue - Violet - Purple - Pink - Brown - Black - Grey - White

The perfect 14-color palette, all you need to describe colors, no more, no less! ;)

(Note: I think in the documentation examples the colors should be presented in that order, not in the alphabetical order, it would be more useful and more pleasing to the eye)

I've got more ideas about coloring, but first I'd like to know what you think about this, I'm a github noob but I can try to make some PR if you think that would help ^^

Cheers!

**Comment by jlukic** [comment]
Thanks for the detailed, thoughtful post. 

I agree with pretty much everything you're saying. 

I particularly enjoyed this insight
> All languages contain terms for black and white.
If a language contains three terms, then it contains a term for red.
If a language contains four terms, then it contains a term for either green or yellow (but not both).
If a language contains five terms, then it contains terms for both green and yellow.
If a language contains six terms, then it contains a term for blue.
If a language contains seven terms, then it contains a term for brown.
If a language contains eight or more terms, then it contains terms for purple, pink, orange, and/or gray.

Some notes
* One of the difficulties with named colors that I still don't have a great solution for, is that brands often have many distinct variations of the same "named" color
* Teal seems to be one of the [most common](https://xkcd.com/color/rgb/) non-obvious color. 
* I think adding neutrals as a color option is complicated because the default UI use types of neutrals heavily already, so they won't necessarily mesh.
* One of the huge difficulties is maintaining text contrast. Yellowish shades can be very difficult to pull off without swapping text colors specifically for certain hues.

Actionable Changes
* Add `brown` color
* Add in a second purple'ish color. I think `magenta` is [slightly more common](https://xkcd.com/color/rgb/) for a redish purple.
* Add in a second greenish color, I think `olive` is good
* Adjust docs samples so they appear in chroma order

**Comment by lemartialou** [comment]
Hey thanks for the positive feedback! ^^

> Adjust docs samples so they appear in chroma order

So that would be [my first pull request](https://github.com/Semantic-Org/Semantic-UI-Beta-Docs/pull/3) (ever! yay! ^^), I hope I've done everything correcttly and you'll accept it :)

> I think olive is good

Cool! ^^

> I think magenta is slightly more common for a redish purple

I think that too, but here is why (to me) and why it may not be the best term to use:

[Magenta](http://en.wikipedia.org/wiki/Magenta) can be an ambiguous term, but for people like me, using RGB and CMYK color systems for a while,  it means a really precise color or shade, not ambiguous at all: rgb(255,0,255) or cmyk(0,100,0,0), same amount of red and blue, in print the name "magenta" is often used to mean this fundamental color component that needs to be used to render an image on paper, it's a really particular shade.

I might be biased because I'm french, and when [purple](http://en.wikipedia.org/wiki/Purple) seems to be the most common word used in english, [violet](http://fr.wikipedia.org/wiki/Violet) [fr] is the most common word used in french for the same type of shade, "purple" meaning a darker more redish shade: [pourpre](http://fr.wikipedia.org/wiki/Pourpre) [fr].

Despite my bias I'm trying to adapt to english, and I have the feeling that between "Violet", "Purple" and "Magenta":
- **Violet** says *"I'm a purple kind of color, I'm going towards blue"*
- **Purple** says *"I'm the general term, I can go anywhere, but I guess you'll more often see me going towards red"*
- **Magenta** says *"I'm Magenta, end of discussion... ok if you insist you can make me go towards red, a little bit"*

... well... it's exagerated I know... But I have the feeling that "Violet" is the only one that would naturally allow to go in the blue shades whereas both "Purple" and "Magenta" would make you go more on the red side.

Ok enough hairsplitting, if you choose Magenta that will be fine with me, the most important thing is having 2 shades of purple, so I... err... I won't mind ;)

On a side note **Cyan** is the other "fundamental" color not present in Semantic UI, I don't think it's needed for the same reasons, well, I might be wrong.
We can already see some Cyan-like color with some inverted *Teal* elements, maybe a Magenta-like color could be used as an inverted *Purple* on the same kind of elements (when purple is divided in 2).

> I think adding neutrals as a color option is complicated because the default UI use types of neutrals heavily already, so they won't necessarily mesh

I'm still digging through the code, but I can effectively see that the neutrals, black and grey are the core colors of Semantic UI.

Let's put in another way: I don't want the "neutrals" as color option, I'd like the *Black*, *White* and *Grey* **names** as color option, with the same treatment as the other color names.

I'm not sure I understand everything (still digging), my guess here is that there would be a variable name clashing problem, because the neutrals variables are using color names like "lightGrey" or "White".
"Black" and "Grey" are also used by core elements, "Grey" is listed as an official site color variable but in fact it is more kind of the "default" color, you can't use it for coloring, "Black" is only sometimes behaving like that too.

I know it's more complicated than that, but can this problem be resolved this way:

- move "black" and "grey" site color variables to the neutrals
- rename all these "neutrals" variables by giving them for example a "default" namespace ("black" becomes "defaultBlack", etc..., or maybe better "defaultDark" to be more "neutral")
- refactor what needs to be refactored in order to use the new default variable names (that might be the not easy part ^^)
- add new "black", "white" and "grey" color to the site color names and implement them like any other color (same way the new "Violet" color would be implemented ;)
- assign the "defaulBlack" to "black", the "defaultWhite" to "white", etc... in order to set the default values.
- maybe (or not) rename "neutrals" to "defaults" to make more sense (or not)

Et voilà! Full control on all the core default colors, "defaultBright" could be the "white" variable value, but it also could be yellow, or beige, or whatever without altering the "white" variable.

If I understand correctly the problem is that a lot of the core default colors are "hard coded" to whites, blacks or greys without using the global variables, so that would have to be treated to get real full control.

What do you think? Am I missing something? I know this shouldn't be your top priority right now, but do you think it would be a good idea?

> One of the difficulties with named colors that I still don't have a great solution for, is that brands often have many distinct variations of the same "named" color.

Custom user defined color names FTW! ;)

**Comment by lemartialou** [comment]
Going through the code again, I noticed this: "grey" , "greyHover", "greyFocus", "greyDown" and "greyActive" seem to be already "free", since they are only used in "site.variables" and nowhere else. Can you confirm they are "orphan" variables?

**Comment by jlukic** [comment]
Implementation isnt too difficult with colors. There's an [inheritance system](http://learnsemantic.com/themes/overview.html) with semantic ui, generally all components inherit from `globals/site.variables` with there being 3 levels of inheritance for site variables, default, packaged theme, and site.

W/rt neutrals. Grey was originally intended to be used as a color, but was removed. It's not that there aren't uses for grey, but that in most cases they don't conform in usage to other colors. For example, `inverted grey` doesn't really make sense in english, or using `grey` as an accent color on a table, or segment isn't distinct from the shading of the table. I've tried to limit the options in SUI to only things that make sense in terms of design usage, removing possible but aesthetically unappealing options to avoid misuse. 

I'm fine with choosing violet over magenta. I see your argument. 

Standby for some code.

**Comment by jlukic** [comment]
One unfortunate side effect of expanding colors rules is they are rather dense. They end up taking up about 60kb (65%) of the definition for button, which is a huge.

**Comment by jlukic** [comment]
Well that ended up being 4 hours of work. Haha. It's done though.

**Comment by lemartialou** [comment]
Wow! Tremendous work! Thanks a lot! ^^

> Add in a second greenish color, I think olive is great

**I think poor `olive` has been forgotten, I hope it's just by mistake (crossed fingers).**

> There's no need for labeling variables as @default since this is what the default theme is for.

I understand what you mean, you're right, I think I didn't put the problem the right way.

Now with all those changes (and me familiarizing with the code) the situation is a little bit different: we've got `black` and `grey` available as site colors, and usable "where it make sense".

To me `white` should be listed under 'site colors' too, it would make more sense by presenting the full palette under the same category.

But I see in your last changes that you removed the "white" class possibility to the few elements that where able to deal with it (grid and icon).

I understand your motivation behind this, white is "expected" in a lot of cases, like black, and like grey.

But I still think we could enjoy less "rigidity", so I'll try to present the problem another way and make a new suggestion (hope you don't mind ^^) : 

So, we can define site colors, neutral colors, user brand colors, famous brand colors, emotive colors...

What's nice is that everything is decoupled, colors can be independently tweaked...
Everything? No. **Site colors and neutral colors are coupled**, black on one side used as neutral, white on the other side that can't be used as a color name anymore, and grey going... well it's moving...

To me:
-  **site colors** should represent all the color names options and behave consitently. If I can paint a segment or a column in "pink", I should be able to paint it in "black", "white", or "grey" or any color name available. I know on some occasion it won't make sense, or it would be redundant, but there are a lot of situations where that could totally make sense. And it's a user triggered action, optional, I think the user should be able to know that it's not a good idea to create a black segment when the text is already black ;)
- **neutrals** should represent (ideally) all the colors used for the core elements, "uncolored", the "monochromatic" Semantic UI. Blacks, whites and greys are used as core colors, but these colors should be independant from the colors used for coloring (they would be linked by default `neutralBlack = black`, `neutralWhite = white`, `...`)

Ideally we could be able to **tint the monochromatic Semantic UI just by tweaking the neutrals and without affecting the site colors**

Won't it be cool? ^^

> One unfortunate side effect of expanding colors rules is they are rather dense. They end up taking up about 60kb (65%) of the definition for button, which is a huge.

Yes, I can see that, this "waste of space" feeling might not be liked by users using just a few colors for their projects, and more generally it feels "non-optimal".

Wouldn't it be possible to use some [LESS magic](https://github.com/seven-phases-max/less.curious/blob/master/articles/for-each.md) to resolve this problem?

- In `site.variables` we would have something like:

`availableColors: red, green, blue, facebook, positive;`

(unnecessary to put `neutrals` in this, neutrals wouldn't be optional because they would be the "monochromatic core" ;)

- in `button.variables`we would have something like

`buttonAvailableColors: availableColors;`

(overrideable for maximum customizability ^^)

- and in `button.less` we would have in the coloring section a loop iterating over the `buttonAvailableColors` and generating only the desired CSS.

I know it's more complicated than that, but won't it be a nice feature to have?
- you could choose your colors at build time, globally or element by element for minimum file size.
- that would open the way to "custom user colors"

My posts are reaaally too long, sorry for that ;p
Thanks again for your tremendous support!

**PS: Don't forget poor `olive`! ^^**

**Comment by lemartialou** [comment]
Still thinking about the "neutrals" (i know)
Shouldn't they be at least treated **semantically** like the "emotive colors"?

There is no "red" variable in the emotive colors, but "negativeColor" (which uses "red" as a value)
There shouldn't be "white" or "black" in the neutrals but "brightColor" and "darkColor".

Just food for thoughts ^^

**Comment by jlukic** [comment]
There aren't any explicit control structures (loops) in LESS, there are idiosyncratic ways to accomplish loops with mix-ins, but this would add a level of complexity which might be prohibitive.  

I did miss olive somehow while adding colors. It will be a bit of a chore to add given the amount of time i have available before June 1st, but will see if i can squeeze in.

**Comment by jlukic** [comment]
Added olive, fixed some typos from previous commits.

**Comment by lemartialou** [comment]
Thanks again for your tremendous support, YOU ROCK ! :)

I know SUI 2.0's launch is around the corner, so I'll stop bothering you with my suggestions (for now ;)

Until then I'll try to concentrate on helping you finding typos or bugs in the new docs.

Cheers! ^^

**Comment by lemartialou** [comment]
It seems that `inverted menu` can't be set to `grey`, any reason why?

**Comment by dsslimshaddy** [comment]
allow all colors like rgba and hls instead of only named
