### ISSUE TITLE
Sidebar "Scale Down" Animation

### ISSUE THREAD

**Issue by Orbyt** [Semantic-Org/Semantic-UI#2281]
Whats the jquery for the scale down animation of the sidebar?

**Comment by jlukic** [comment]
```
$('.ui.sidebar')
  .sidebar({
    transition: 'scale down'
  })
;
```

**Comment by Orbyt** [comment]
Thanks, where is this in the docs?

**Comment by jlukic** [comment]
http://semantic-ui.com/modules/sidebar.html#/settings

**Comment by Orbyt** [comment]
@jlukic Ah I see. You should add a part explaining that the settings are just key:value pairs, as it wasnt obvious looking at the docs. Thanks for the fixes.
