### ISSUE TITLE
getting the width of a field 2/3 of parent's

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2283]
How can I make a layout like this using `.field` or other techniques?
I need field 5 to take up 2 field spaces.
![image](https://cloud.githubusercontent.com/assets/10534563/7744928/5ad596cc-ffb8-11e4-9a6f-cadc5c061ac1.png)

**Comment by Anachron** [comment]
Use a row with `three column wide grid` and then use `one wide column` and for the field5 use `two wide column` as wrapper?

**Comment by jlukic** [comment]
Requires #2095

**Comment by avalanche1** [comment]
@Anachron your solution didnt work. Resolved by manually setting widths for fields 4&5.
Waiting for https://github.com/Semantic-Org/Semantic-UI/pull/2095
