### ISSUE TITLE
Add icons to semantic-ui namespace

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2285]
SUI includes Fontawesome iconset, but I need to add more icons.
E.g. I'd like to add a chopper icon and use `chopper` class on `i` tag.
How can I do that?

**Comment by jlukic** [comment]
Please use stackoverflow or gitter for asking questions.

**Comment by avalanche1** [comment]
Yep, asked the same a week ago - nobody answered.

**Comment by jlukic** [comment]
You would need to use a site like icomoon and a custom theme.
