### ISSUE TITLE
dropdown grouped with button

### ISSUE THREAD

**Issue by Eagllus** [Semantic-Org/Semantic-UI#2286]
I have a situation where I would like to have a dropdown grouped with a button.

```
<div class="ui right floated buttons green">
  <div class="ui action input">
    <div class="ui dropdown selection" tabindex="0">
      <select name="selection">
        <option value="">----- Select one -----</option>
        <option value="a">a</option>
      </select>
      <i class="dropdown icon"></i>
      <div class="default text">----- Select one -----</div>
      <div class="menu" tabindex="-1">
        <div class="item" data-value="a">a</div>
      </div>
    </div>
    <button name="button" type="submit" class="ui button green">Select</button>
  </div>
</div>
```

Without any changes to my css this will look like.
![screen shot 2015-05-21 at 14 37 54](https://cloud.githubusercontent.com/assets/411073/7748690/ff059040-ffc6-11e4-8179-a5e6bc514af9.png)

by adding
```
.ui.action.input .ui.dropdown:first-child {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}

.ui.action.input .ui.dropdown:last-child {
	border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

in my css I was able to get 
![screen shot 2015-05-21 at 14 39 48](https://cloud.githubusercontent.com/assets/411073/7748726/490ad81c-ffc7-11e4-8ebf-baef6ad535d0.png)

not sure if this helps anyone but thought I share it.

**Comment by jlukic** [comment]
Thanks

There's also a couple examples of this in 2.0, and this is supported out of the box.
http://beta.semantic-ui.com/elements/input.html#action

**Comment by Eagllus** [comment]
Thank you for pointing that out to me! Will integrate the input into my project.
