### ISSUE TITLE
Icon-Groups in next broken

### ISSUE THREAD

**Issue by Anachron** [Semantic-Org/Semantic-UI#2287]
See http://beta.semantic-ui.com/elements/icon.html#/definition

![icongroups](https://cloud.githubusercontent.com/assets/589800/7749704/bcde1cec-ffcf-11e4-8660-11cbc9fc3181.JPG)

Windows 7 - Professional - 64Bit
Firefox 38.0.1

**Comment by jlukic** [comment]
This was a side effect of removing line height from icon, I've had to adjust any absolute positioned icon in other ui uses.
