### ISSUE TITLE
Semantic-UI Dropdown Not Working

### ISSUE THREAD

**Issue by ars-skype** [Semantic-Org/Semantic-UI#229]
![10-10-2556 17-17-04](https://f.cloud.github.com/assets/5643893/1305350/5dd76776-3195-11e3-82ea-bb6afcc55fb1.png)

![10-10-2556 17-20-33](https://f.cloud.github.com/assets/5643893/1305375/a947b3e6-3195-11e3-910d-6ccbe702fffa.png)

im try http://jsfiddle.net/MXZR7/ it ok.

run true not working.

Help Me. Thk <3

**Comment by agongdai** [comment]
+1 @pdemilly . And the JS version doesn't work for 'dropdown item active': http://jsfiddle.net/VL2Zq/21/

**Comment by stevangoldduck** [comment]
@dsomel21 maybe ur version of Jquery. Try using this jquery 
`<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>`

**Comment by gionel73** [comment]
Same issue, still not working... 
$(...).dropdown is not a function

**Comment by ImSanchez** [comment]
> Same issue, still not working...
> $(...).dropdown is not a function

I fixed this by adding async to jQuery script tag and defer to the Semantic-UI script tags at the bottom of the document. I hope this helps. Added a sample below.

` <script src="semantic.js" integrity="sha384-S8k/vI9n9uJx1pJ/XWhwQK8excdPDNcfQRBYl96sqVq6fhRoE7nVhthQjcAHJNCo" crossorigin="anonymous" defer></script>
  <script src="main.js" defer></script>`

**Comment by Nana-asiamah98** [comment]
> @ars-skype ah, okay. I think the problem is you're including the jQuery `<script>` tag before the Semantic-UI `<script>` tag.
> 
> Move jQuery's `<script>` above Semantic-UI's `<script>`

Thanks,it **works** now

**Comment by singhkumarhemant** [comment]
> @ars-skype ah, okay. I think the problem is you're including the jQuery `<script>` tag before the Semantic-UI `<script>` tag.
> 
> Move jQuery's `<script>` above Semantic-UI's `<script>`

its working fine..
