### ISSUE TITLE
Larger icons do not properly pad

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#2294]
Trying to use larger icons makes the actual icon go off the page

https://jsfiddle.net/7x1kk5a9/1/

**Comment by jlukic** [comment]
I'm familiar with this, line height issue, will resolve after the holiday on Tuesday.

**Comment by Anachron** [comment]
@jlukic should be fixed with:
https://github.com/Semantic-Org/Semantic-UI/commit/73b05865f93acb9f2b7eb92e82a658e5e2574e6b

**Comment by jlukic** [comment]
Fixed
