### ISSUE TITLE
Two loading icons inside search component when using an action input

### ISSUE THREAD

**Issue by renatodinhani** [Semantic-Org/Semantic-UI#2295]
I am using an action input with an icon button inside the search component. The problem I am having is when the search component changes to the loading state, two loading icons appears instead of only one. This is related to the icon button because when I remove it, the problem disappears.

You can see the problem in the following image.

The left one is expected, but the middle one is wrong.

![two loading icons](https://cloud.githubusercontent.com/assets/1139781/7790972/f902d70e-026c-11e5-835b-d473a11dbb95.png)

You can reproduce the problem with the folowing HTML.
```
<div class="ui loading search">
    <div class="ui left icon action input">
        <input class="prompt">
        <i class="search icon"></i>
        <button type="button" class="ui icon button blue">
            <i class="icon add"></i>
        </button>
    </div>
    <div class="results"></div>
</div>
```

**Comment by jlukic** [comment]
Fixed in `2.0`
