### ISSUE TITLE
[Dropdown] Use `.attr('data-value')` instead of `.data('value')` to allow non-string item value

### ISSUE THREAD

**Issue by peterfyj** [Semantic-Org/Semantic-UI#2296]
If the `data-value` attribute of a dropdown item is set to a value that can be parsed as something other than string, e.g. `data-value="true"`, we cannot select the item properly, as shown in this [JSFiddle](http://jsfiddle.net/8e1bj3f6/4/).

I did some examination in source, and I believe this is caused by using `.data('value')` in dropdown, which tries to parse the attribute, instead of regarding it as string. For plain string retrieval, we need `attr('data-value')`.

One of the solutions is to pass boolean value as well: `.dropdown('set selected', true);`. However, most of the time the value being selected is string and is extracted elsewhere (for example from query string), and I think it odd to make type check/conversion for the value.

**Comment by jlukic** [comment]
Thanks for the easy to understand test case. I'll take a look at what I can do.

**Comment by jlukic** [comment]
Fixed in `next`, will use string matching now when not strict.
