### ISSUE TITLE
Triggering a change event when a hidden input is updated

### ISSUE THREAD

**Issue by nathanpalmer** [Semantic-Org/Semantic-UI#230]
Would be awesome (essential in my case) to trigger a change event on the hidden input for a .ui.dropdown. I understand there is an onChange event but as I'm enabling these globally it would be tedious to have to trigger .dropdown on each element specifically just so I can get access to the onChange event.

However, if when a value is set on a hidden input, we trigger a change event I can subscribe to that just like I did before on a <select>. Somewhere around here I suppose.

https://github.com/jlukic/Semantic-UI/blob/master/src/modules/dropdown.js#L251

Also, as a side note it would also be nice to be able to use a bare select and not build out a ui.dropdown. It does work but the style doesn't show a dropdown icon. Which I believe is intentional due to the difficulties of styling a select (issue #152)

**Comment by batata004** [comment]
Does anyone know how to trigger the onchange event of a dropdown?
