### ISSUE TITLE
(next branch) multiple selection dropdown : 'clear' does nothing

### ISSUE THREAD

**Issue by matthieu60** [Semantic-Org/Semantic-UI#2303]
The 'clear', 'restore defaults', 'set text' and maybe other behaviors do not work on multiple selection dropdown.

**Comment by jlukic** [comment]
The explanation is clear, but please create a test case from the JSfiddle under `next` in readme.

**Comment by jlukic** [comment]
Actually its fine, I'll do it.

**Comment by jlukic** [comment]
These methods were not adapted to work with multiple. I've rewritten them.

`set text` does not work with multiple unless no labels are showing. 

Will have to wait a min for rawgit.com to update but heres an example fiddle
http://jsfiddle.net/uduq3nvk/

**Comment by matthieu60** [comment]
Thanks a lot !
