### ISSUE TITLE
[next] Small bug with default secondary and tertiary inverted segment

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI#2306]
Background color is not correctly set for those elements.

Here is the fiddle to demonstrate:
http://jsfiddle.net/lemartialou/rduvhn8u/25/

**Comment by lemartialou** [comment]
Updated the fiddle to test all the color variations:
http://jsfiddle.net/lemartialou/rduvhn8u/26/

So only the default one has a problem, even `black` is working fine.

**Comment by jlukic** [comment]
It looks like an inheritance issue, ill fix.
