### ISSUE TITLE
Initial checkbox state in modal not actioned

### ISSUE THREAD

**Issue by tobybowers** [Semantic-Org/Semantic-UI#2307]
Hi,
Sorry I can't create a jsfiddle for this issue.
I have a view button that when clicked fires off an ajax request. This returns the div content to be used within a modal. My issue is that when the modal opens, all checkboxes set with class or input as checked still show as unchecked.

If I have the input set as checked and use the following line in the modal content
$(".checkbox").checkbox("refresh");
Then the checkboxes change to the initially set states. 

So, that would appear to be all good apart from the fact that the checkboxes in this case should be read only and it appears the refresh returns them to an active state even if read-only is still in the div class and readonly="readonly" is set in the input.

Is there some other method i'm missing that will give the desired effect?

**Comment by jlukic** [comment]
Refresh only [refreshes selector cache](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/checkbox.js#L95), should not adjust a checkbox appearance. 

I cant really comment without seeing an example, since its behaving abnormally and I have never seen this behavior.

**Comment by tobybowers** [comment]
Hi,

I've managed to extract most of the page to http://jsfiddle.net/0o1kg5Lk/ and it's working.
I've kicked my machine really hard (rebooted) and it appears to be working now. Must of been a flaky cache issue.

**Comment by tobybowers** [comment]
Actually no, Starting state is showing correctly but still not read-only.
