### ISSUE TITLE
main content is offset when displaying an always visible sidebar

### ISSUE THREAD

**Issue by mbroadst** [Semantic-Org/Semantic-UI#2312]
relevant example: http://jsfiddle.net/sf3c3akt/

**Comment by jlukic** [comment]
This is how a sidebar behaves. It doesn't squeeze content but pushes it.

**Comment by mbroadst** [comment]
Oh I see, I misread "start visible" as "always visible". So there are no current plans to support an "always visible" sidebar?

**Comment by jlukic** [comment]
No, not currently.

**Comment by uyab** [comment]
+1, semantc-ui website use always-visible-sidebar in all pages. At least give me some 'cheat' how to do it :)
