### ISSUE TITLE
Multiselect dropdown 2.0, options disappear after removing items

### ISSUE THREAD

**Issue by slb235** [Semantic-Org/Semantic-UI#2313]
Steps to reproduce:

- Select Items
- Remove Items
- *Add different Item* (only removed items will be listed)

Fiddle: http://jsfiddle.net/3mbrke0x/1/
Browser: Current Chrome + Firefox

**Comment by jlukic** [comment]
This is a pretty bad regression. I'll take a look

**Comment by jlukic** [comment]
Should fix.. will give fiddle in a sec

**Comment by jlukic** [comment]
Actually you can check your same jsfiddle
http://jsfiddle.net/3mbrke0x/1/

**Comment by slb235** [comment]
Thanks for the quick fix. Nice work :+1:
