### ISSUE TITLE
horizontal statistics is a misnomer

### ISSUE THREAD

**Issue by mbroadst** [Semantic-Org/Semantic-UI#2314]
http://semantic-ui.com/views/statistic.html#horizontal-statistic defines a set of horizonal statistics that are laid out vertically in a group, I believe it's a misnomer to name these "horizontal statistics". Rather, it seems the markup should look more like

```
<div class="ui vertical statistics">
  <div class="horizontal statistic">
    <div class="value">
      22
    </div>
    <div class="label">
      Breeds of Dog
    </div>
  </div>
  <div class="horizontal statistic">
    <div class="value">
      31
    </div>
    <div class="label">
      Famous Dogs in Films
    </div>
  </div>
  <div class="horizontal statistic">
    <div class="value">
      22
    </div>
    <div class="label">
      US Presidents Owned Dogs
    </div>
  </div>
</div>
```

**Comment by jlukic** [comment]
Horizontal statistics (those that display their stats horizontally, are best displayed in groups that appear vertically. 

Vertical statistics (default), appear best in groups that display side by side. Although this might seem counterintuitive, it enforces best UX practices by default.
