### ISSUE TITLE
binding namespace not used

### ISSUE THREAD

**Issue by FloLinn** [Semantic-Org/Semantic-UI#2315]
form.js line 100:

        attachEvents: function(selector, action) {
          action = action || 'submit';
          $(selector)
            .on('click', function(event) {
              module[action]();
              event.preventDefault();
            })
          ;
        },

does not use namespaces 
"event-preventDefault"-handlers pile up when I initialize and destroy form-validation successively.

I am writing my first issue ever, so I hope this was ok

**Comment by jlukic** [comment]
Hi, thanks for your clear bug report and for taking the time to join the community.

This has been fixed already in `2.0` which will be coming in June. 
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/behaviors/form.js#L119

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/commit/97e8bf5fdaf703b41c16175bb2771d1d5c9f9719
