### ISSUE TITLE
Progress bar eats 10% CPU

### ISSUE THREAD

**Issue by dandv** [Semantic-Org/Semantic-UI#2316]
I wouldn't normally care, but it turned out that Semantic UI's progress bar caused my laptop fan to start spinning at http://semantic-ui.com/. After removing the progress bar, CPU utilization fell below the threshold.

Here's a screencast. It's a little slow to allow the CPU usage to stabilize.
![progress bar eats 10 cpu](https://cloud.githubusercontent.com/assets/33569/7877489/098243cc-0591-11e5-9454-337d19125a0a.gif)

Measured with [Process Hacker](http://processhacker.sourceforge.net/) on Windows 7 64-bit. Chrome 43.0.2357.81 m.

**Comment by jlukic** [comment]
Seems like the blinking cursor and progress bar both have to be removed to get CPU usage down to 0. Kinda amazing how much CPU usage comes from a simple css transition.

**Comment by jlukic** [comment]
Ignore that commit, incorrectly tagged. 

I've gone ahead and removed blinking cursor after animation finishes, and removed progress bar from homepage examples.

I still need to redo homepage for launch.

**Comment by lauri-elevant** [comment]
The latest version is still eating absurd amounts of CPU cycles for rendering this strange animation that does not seem to have any meaningful semantics to my mind. If you set the percentage of the progress bar to anything above 0,, it starts this sweeping animation that is supposed to say that it is .. what exactly? I can't really figure it out.

Anyways:
```
    .ui.active.progress .bar::after {
      -webkit-animation: none !important;
      animation: none !important;
    }
```

Before and after:
![screenshot from 2018-10-11 18-33-10](https://user-images.githubusercontent.com/5912488/46816313-609c4a80-cd85-11e8-9021-f459b0a0cb7f.png)

**Comment by lubber-de** [comment]
Fixed in https://github.com/fomantic/Fomantic-UI 2.6.3
