### ISSUE TITLE
Erratic overlay display on Kitchen Sink in lists

### ISSUE THREAD

**Issue by dandv** [Semantic-Org/Semantic-UI#2317]
![image](https://cloud.githubusercontent.com/assets/33569/7877589/074b85c2-0592-11e5-9a12-a27416529299.png)

I've tried to isolate the reproduction steps, but without luck. Maybe others can chime in.

**Comment by ph7vc** [comment]
I've seen this a few times. I believe it has something to do with the icon font not being loaded or rendered properly

**Comment by jlukic** [comment]
This might be related to the interaction of 'hash state history tabs' and sticky content 'refreshing'. 

Anyone see this in `2.0`?
