### ISSUE TITLE
safari pc = destroyed layout

### ISSUE THREAD

**Issue by peterrobertz** [Semantic-Org/Semantic-UI#2321]
hey,

i love semantic and use it in production, however, on a pc (not mac) in a safari browser, the layout gets destroyed.

you can check it by yourself, if you download safari for pc and visit semantic-ui.com or beta.semantic-ui.com

any suggestions?

<3

**Comment by Anachron** [comment]
Could you please be so kind and actually provide any screenshot or do some debugging yourself?
Not all of us have an apple pc... (I use linux as my daily os for example)

**Comment by jlukic** [comment]
Safari PC is [no longer supported](http://appleinsider.com/articles/12/07/25/apple_kills_windows_pc_support_in_safari_60) by Apple. It's an old version of webkit which does not adequately support flexbox.

**Comment by peterrobertz** [comment]
thanks for this information!
