### ISSUE TITLE
[1.12.3] Popup on clicks with mobile/touch devices (iPhone 6, etc)

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#2322]
Hi all,
I walked into an Apple store and tried a web site built with Semantic UI 1.12.3.
To my surprise, popups showed on clicking, but they are configured to show up on hover only, which is not possible with a touch screen, right?

Any explanation? Note, this can be seen only with a real device, not with Chrome/Firefox simulations.

**Comment by jlukic** [comment]
This is expected behavior, added a new setting to disable.
