### ISSUE TITLE
[UI] Count-Up Numbers

### ISSUE THREAD

**Issue by ns-phennessy** [Semantic-Org/Semantic-UI#2323]
I've seen a few sites that animate the SUI equivalent of statistic to the number value it is. So it just counts up from 0 to how ever much your value is over X amount of time.

Not a high priority but would be cool to have.

The example I saw was here: http://saltstack.com/ (scroll down)

**Comment by ikourfaln** [comment]
Just use CountUp.js
https://github.com/inorganik/CountUp.js

**Comment by ph7vc** [comment]
@ikourfaln: good find! ill def check that out
