### ISSUE TITLE
[API] Serializing Form Data (jQuery Serialize Object) not working !!

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2324]
Hi @jlukic 

as you said here: http://beta.semantic-ui.com/behaviors/api.html#serializing-form-data
I add macek's serialize object converter, its detected by SUI API but Data are not serialized !!
![api](https://cloud.githubusercontent.com/assets/9744226/7894168/ad3be73a-065d-11e5-9afa-3766acad9976.png)

my source code:
```javascript
$.fn.api.settings.api = {
        'add activity': '/Api/Agence/Program/2/Activity/Add'
    };
    $('form .submit.button').api({
        action: 'add activity',
        method: 'POST',
        serializeForm: true,
        beforeSend: function (settings) {
            console.log(settings.data);
            return settings;
        }
    });
```

**Comment by jlukic** [comment]
Serialize object modifies parameters with names like `name="name[first]"` and `name="name[last]" to be submitted as an object 
```javascript
{
  name: { 
    first: 'foo',
    last: 'baz'
  }
}
```

**Comment by ikourfaln** [comment]
ow !! ops Im sorry.
Thanx

by the way, you said here: http://beta.semantic-ui.com/behaviors/api.html#/settings that possible values for method are post, get. I test other verbs (DELETE, PUT) and it works :+1:
