### ISSUE TITLE
How to do fluid for cards?

### ISSUE THREAD

**Issue by piya23300** [Semantic-Org/Semantic-UI#2325]
I use cards (http://semantic-ui.com/views/card.html#cards)

I can not modify class like a fluid card (http://semantic-ui.com/views/card.html#fluid-card)

I would like to do fluid card for cards.

Could you suggest code for me?

**Comment by jlukic** [comment]
What do you mean you cannot modify class?

**Comment by piya23300** [comment]
@jlukic 
I mean
I try to copy a fluid card class to use fluid cards class. 
do you have example code for fluid cards?

**Comment by jlukic** [comment]
http://jsfiddle.net/fLkzcjhs/

**Comment by mindbits** [comment]
sorry about reopening but like the jsfiddle example shows, fluid cards + flexbox don't work together?
