### ISSUE TITLE
Equal Height Column Not Centered

### ISSUE THREAD

**Issue by oniisaki** [Semantic-Org/Semantic-UI#2326]
I have a sixteen wide centered grid. Three columns are defined with four columns wide each. "equal height" class was defined for the grid to it would have the same height.

The expected output was a total of 12 column wide content, with equal column height, but that's not the case. The "equal height" class seems to makes the content take the full page width, and not centering.

http://jsfiddle.net/ddbaawrd/2/

**Comment by jlukic** [comment]
This is fixed in `2.0` which will be available imminently.
http://jsfiddle.net/ds5hrb73/
