### ISSUE TITLE
Form submit not working when using <div class="ui submit button">

### ISSUE THREAD

**Issue by jaypanares** [Semantic-Org/Semantic-UI#2328]
I can't seem to get my form to submit.  My code below:

http://jsfiddle.net/jaypanares/vdp3mwqc/1/

Currently using divs with `class="ui submit button"` but it does not work.  Replacing the divs with `<button>` tags seem to do the trick, but the example in the docs have the submit buttons as divs.  Is there something wrong with my code?  I'd prefer to use divs because buttons have that "glow" effect when clicking. Thanks!

**Comment by jlukic** [comment]
Using a `submit button` by itself doesn't submit a form unless you initialize the JS component
http://jsfiddle.net/gxwuemg0/

**Comment by jaypanares** [comment]
Thanks so much!  I didn't realize 2.0 was around the corner.  Hoping for more good things!
