### ISSUE TITLE
Semantic UI Dropdown is not showing the drop down but everything else is working

### ISSUE THREAD

**Issue by aishwaryashiva** [Semantic-Org/Semantic-UI#2329]
Please go to http://stackoverflow.com/questions/30551424/semantic-ui-dropdown-is-not-showing-the-drop-down-but-everything-else-is-working for detailed description of this issue. 

It's working on this fiddle http://jsfiddle.net/ow2by6av/1/ but not in my project.

**Comment by ikourfaln** [comment]
Check out SO, I reply your question

**Comment by aishwaryashiva** [comment]
Yeah but I tried that in this fiddle. The problem is that the drop down itself is not showing up. When I disable display:none in inspect menu. Its showing the dropdown menu but not by clicking on the dropdown button.

**Comment by ikourfaln** [comment]
Check SO
