### ISSUE TITLE
$.modal('hide') doesn't hide the dimmer

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#233]
Calling `$('.ui.modal').modal("hide")` doesn't hide the dimmer.  

Calling `$('.ui.modal').modal("hide dimmer")`is the same as `$('.ui.modal').modal("hide")`  (hides modal, but not the dimmer).
- [`"hide"` fiddle](http://jsfiddle.net/2hts6/)
- [`"hide dimmer"` fiddle](http://jsfiddle.net/2hts6/1/)

---

Side note: `$('.ui.modal').modal('hide').modal('hide')` causes the hide animation to play twice (it hides, shows, and hides). If it's already animating out it should know that, and not hide again (perhaps calling onHide again would be fine, though).

**Comment by weldan** [comment]
now if you hide dimmer it will also hide modal. so funny

**Comment by advancewarsbest** [comment]
Still having the same issue; hiding the modal also hides the dimmer still.

**Comment by vitaliy-kuzmich** [comment]
@advancewarsbest  thank you!

**Comment by vitaliy-kuzmich** [comment]
bug still exists...

**Comment by jihantoro** [comment]
$('#test').click(function() {
			$('.basic.modal')
			  .modal('setting', 'closable', false)
			  .modal('show');
			});
	$('#ea').click(function() {
				$('.ui.modal')
					.modal('hide', function(){
						$('.ui.modal').modal('hide')
                	});
			});

**Comment by jihantoro** [comment]
i dont know for what, but dimmer also hidden

**Comment by DeveloperSlope3** [comment]
This still happens sometimes with v2.4.2 -_-
