### ISSUE TITLE
[List] Support 3 digit count values with ordered list.

### ISSUE THREAD

**Issue by oytuntez** [Semantic-Org/Semantic-UI#2332]
Example: https://jsfiddle.net/cn054odg/

I tried to play with calc() and counters(), but it didn't really work out well. If we revert to browser rendering of lists (with numbers aligned to right, instead of left), it may work. Or we could introduce a new set of classes to specify the maximum number of digits in the numbering, although this may not be the best experience: `1-digit`, `2-digit`, `3-digit`, `4-digit`, `5-digit`...

``` html
<div class="ui 5-digit ordered list">
  <a class="item">Getting Started</a>
  <a class="item">Introduction</a>
  <a class="item">Getting Started</a>
 <!-- more items totaling to something between 10000 - 99999 -->
</div>
```

This would set the margins according to the highest numbered item.

**Comment by jlukic** [comment]
Your jsfiddle is blank

**Comment by oytuntez** [comment]
Oops, I was playing with it. Updated the link.
