### ISSUE TITLE
[Learn Semantic] - Using outdated SUI version

### ISSUE THREAD

**Issue by postbud** [Semantic-Org/Semantic-UI#2333]
On the page http://learnsemantic.com/guide/expert.html, the last separator:
[div class="ui horizontal divider"][i class="circular heart icon"][/i][/div]
the icon:
[i class="circular heart icon"][/i]
is not in the center.

**Comment by avalanche1** [comment]
you can make a PR which corrects this

**Comment by jlukic** [comment]
I really need to update learn semantic..

**Comment by jlukic** [comment]
I'm going to close this, since this should be on learn semantic issues.
