### ISSUE TITLE
Support of attachable button group

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#2334]
Currently only `ui bottom attached button` is supported. It will be very helpful if a button group can be attached as well, i.e., `ui bottom attached buttons`.

Thanks in advance!

**Comment by jlukic** [comment]
Hi attached button groups are supported but undocumented.
http://jsfiddle.net/kyqkL0zd/

It appears some case might still have 1 pixel offsets due to mix of border widths. I'll take a look

**Comment by jlukic** [comment]
Added examples to beta docs, JSFiddle of next
http://jsfiddle.net/yw8htqf5/

**Comment by kfei** [comment]
:100:
