### ISSUE TITLE
[Menu] Container not working with some menu types 

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#2335]
This is an inverted labled icon menu (class="ui inverted labeled icon menu") :

![menu](https://cloud.githubusercontent.com/assets/9744226/7912226/7e52e3a4-085d-11e5-8050-4fe60e5b0539.png)

**Comment by ikourfaln** [comment]
Another issue, items icons in in "labeled icon menu" are not labeled !!
example : http://jsfiddle.net/rduvhn8u/28/

**Comment by jlukic** [comment]
Fixed

**Comment by ikourfaln** [comment]
@jlukic  Thanx  alot for your hard work, labled icons are fixed, but other problems apears:

![menu](https://cloud.githubusercontent.com/assets/9744226/7923273/99708a0a-08a9-11e5-9655-fd0acad93a04.png)

I can fix that with some css codes, but we wanted fixed on the Framework... I Love SUI and I will supported forever.
As I said before Im Back-end Developper, thats why Im not making a lot of PR, but I after I finish a project, I will made a lot of PR in Docs and Languages (I speek French and Arabic)

**Comment by jlukic** [comment]
Some more fixes. Icon menu wasnt intended to work with dropdown, but should now.
http://jsfiddle.net/4zjs6uqc/

**Comment by ikourfaln** [comment]
Thanx :+1:  works fine now
