### ISSUE TITLE
[Segment] Add Clearing Segment Variation

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#2336]
HI @jlukic ,

I continue follow quite close SUI project as I think it's the best UI Framework I ever seen yet.
For my website I updated SUI to use (currently beta) 2.0 and noticed a display issue while having a form with only a button whithin a segment.

Here is my example : https://jsfiddle.net/cazsan/80v3gqco/

I hope this issue were not already reported.
Anyway, thumbs up and cheers for the next

**Comment by jlukic** [comment]
A container with only a floated element needs a clearfix. Segments used to have this built in, but it would cause issues when you didnt want a segment to clear content. This is a css limitation.
https://jsfiddle.net/e0to74dm/

**Comment by jlukic** [comment]
Added
