### ISSUE TITLE
Add simple box-sizing support to Firefox 29-below

### ISSUE THREAD

**Issue by ewuletstalk** [Semantic-Org/Semantic-UI#2337]
I'm getting tired of having to manually add this with each update, so can you please include it in the new release?

Semantic is virtually unusable in Firefox 29-down because box-sizing is broken. But it can easily be fixed by making this update in reset.css:

*,:after,:before{
-webkit-box-sizing:inherit;
-moz-box-sizing:inherit;
box-sizing:inherit
}

html{
-webkit-box-sizing:border-box;
-moz-box-sizing:border-box;
box-sizing:border-box;
}

I noticed it wasn't in the newest Semantic-UI-1.12.3, which it probably should be. Thoughts? Thanks.

**Comment by jlukic** [comment]
Our reset includes this if you choose to use it
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/globals/reset.less#L31

**Comment by ewuletstalk** [comment]
It's missing -webkit and -moz versions which is why it's breaking in Firefox, or am I missing something?

-webkit-box-sizing:inherit;
-moz-box-sizing:inherit;

-webkit-box-sizing:border-box;
-moz-box-sizing:border-box;

**Comment by jlukic** [comment]
Vendor prefixes are [added](https://github.com/Semantic-Org/Semantic-UI/blob/next/tasks/config/tasks.js#L115) in [build tools](https://github.com/Semantic-Org/Semantic-UI/blob/next/tasks/build/css.js#L64) and appear in `dist/`
