### ISSUE TITLE
Menu dropdown item not working; code copied exactly from doc

### ISSUE THREAD

**Issue by paulwal** [Semantic-Org/Semantic-UI#2338]
Here it is: http://www.sessionlessons.com/t1

I copied the markup directly from an example on the Menu documentation page. I also copied the script and stylesheet links the documentation page is using. The dropdown menu is not appearing, though it does appear for me on the documentation page.

I had previously been trying to get it to work with Semantic 2.0 to no avail: http://www.sessionlessons.com/8

I'm on Mac OS X 10.10 and I'm experiencing the issue in both Safari and Chrome. I haven't tried other browsers.

**Comment by slb235** [comment]
First example is missing jQuery. Both examples are missing dropdown initialization code. Read usage tab in docs, basically u need ```$('.ui.dropdown').dropdown()```

**Comment by paulwal** [comment]
Awesome, that was it. Thanks a ton. I'll RTFM better here on out.

**Comment by paulwal** [comment]
Perhaps it'd be beneficial to note this in the Menu doc to help noobs who haven't read the Dropdown doc yet. Like maybe just adding this to the Menu examples that have a dropdown:

    <script>
        /* Initialize the Dropdown module (see Dropdown doc) */
        $('.ui.dropdown').dropdown();
    </script>

**Comment by omairabdullah** [comment]
A related usage question... if I click on the any item in the menu, then the active class is not changing to that item. Is there some other setup required to enable that?
