### ISSUE TITLE
[UI Suggestion] Tour Component

### ISSUE THREAD

**Issue by jdrago999** [Semantic-Org/Semantic-UI#2339]
Hi -

I'm looking for an example of using SemanticUI to produce a tour, like Foundation's [Joyride](http://foundation.zurb.com/docs/components/joyride.html) or [jQuery Tourbus](http://ryanfunduk.com/jquery-tourbus/).

Another option (perhaps) would be to allow a modal to be "anchored" to an element on the page somehow.

Thoughts?

**Comment by jlukic** [comment]
#1053
