### ISSUE TITLE
[Sticky] - Bugs with sticky menu (seen in beta docs)

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI#2340]
It happens on pages shorter than the menu, like the [Reset page](http://beta.semantic-ui.com/globals/reset.html) or the [API page](http://beta.semantic-ui.com/behaviors/api.html)

1. Go to one of those pages.
2. Scroll down a little bit: the menu "jumps" to `bound bottom`.
3. Try to scroll up again: the menu keeps being `bound bottom`, you can't get back to the top.

**Comment by lemartialou** [comment]
Found another one:

1. Go to any page in the docs with a sticky menu.
2. **Don't scroll:** stay at the top of the page.
3. Reduce the browser's width until you get the mobile layout, the menu should disappear: **it won't**
4. Scroll down: the menu disappear as it should.
5. Scroll to the top of the page again.
6. Resize the browser width by just a few pixels if needed: the menu comes back!

Scroll down again and the menu disappears again, so it seems to happen only when you're at the top of the page.

**Comment by jlukic** [comment]
I haven't done any mobile/tablet styling yet. It's literally just broken currently. haha

**Comment by lemartialou** [comment]
Are you sure this is a styling problem?
To me it looks more like a `sticky` module behavior problem, javascript related (the first bug I mentioned doesn't involve mobile/tablet layout at all, the second one happens only when you're at the top of the page, not when you've already scrolled down)

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/3661bf759547646108d93c46eacc875db2ec4a70

Generally this was just an issue with docs not specifying a context for the sticky content.

**Comment by lemartialou** [comment]
Great! Sorry for misunderstanding the problem ^^'

The responsive layout plays very nice with the menu now, everywhere except on the [Reset page](http://beta.semantic-ui.com/globals/reset.html) and on the [API page](http://beta.semantic-ui.com/behaviors/api.html) where the menu is currently broken (we can only see the bottom and it's not scrollable)

**Comment by jlukic** [comment]
Yes I haven't added responsive styles for special pages yet (short ones, 3 column, no sidebar)
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/db8188471dacdcf519b9123336ac8572b22e3833

**Comment by lemartialou** [comment]
Great! Keep it up ! :+1:
