### ISSUE TITLE
2.0: Centered Menu in Container with Right Menu

### ISSUE THREAD

**Issue by hastebrot** [Semantic-Org/Semantic-UI#2343]
Seems the `ui item` in the `right menu` is not aligned to the right when within a `ui container`.

~~~html
<div class="ui attached menu">
    <div class="ui container">
        <a class="ui item">left item</a>
        <div class="right menu">
            <a class="ui item">right item</a>
        </div>
    </div>
</div>
~~~

This is a modified version of the "Centered Menu" example from http://beta.semantic-ui.com/elements/container.html#/examples

**Comment by hastebrot** [comment]
Sorry. Must have been some issue with my browser cache. This actually works. 

Closing.

**Comment by hastebrot** [comment]
It depends on the screen width. In mobile mode the `right menu` element is not aligned to the right.

**Comment by jlukic** [comment]
Also 6f6a7f95b0e5a232115e1131ec811546afd921d2
