### ISSUE TITLE
[Search] Category search provides undefined result in onSelect() in all categories except last one

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2344]
Hi,

Here's a [fiddle](http://jsfiddle.net/andreyvk/qtepdk51/)

Strangely, when selected, the result is `undefined` for all categories except the last one. Just type something in and try selecting an item from the first category. Then do the same for the last category. Is it a bug or am I doing something wrong?

I also tried using `mockResponse`, but API said *API: API action used but no url was defined search*. So I had to use `mockjax` for this one.

**Comment by miniskulljob** [comment]
This bug has been fixed in 2.0 but has been left unresolved in current version: https://github.com/Semantic-Org/Semantic-UI/issues/2070

**Comment by jlukic** [comment]
As mentioned, will be fixed with 2

**Comment by andreyvk** [comment]
Thanks
