### ISSUE TITLE
JavaScript-only npm package

### ISSUE THREAD

**Issue by 1vasari** [Semantic-Org/Semantic-UI#2345]
Semantic already has a [bunch of package variations](https://github.com/Semantic-Org/Semantic-UI#additional-versions) in place. However for my project, I am in need of a JavaScript-only version.

In my project I'm using Browserify to pull everything together. I'm loading Semantic's CSS using [cdnjs](https://cdnjs.com). I'm wanting to be able to do `require('semantic-ui-js`)` (or similar) but I don't understand how to set that up.

I'm pretty sure there's a way to do this that I've missed. Any help would be great. :smile:

**Comment by vennamo** [comment]
You can use npm version of semantic-ui. Then include those js-files from src/definitions/ that you need, or use the bundled semantic.js file from dist folder. Global jQuery is needed.

**Comment by trigoesrodrigo** [comment]
I had some problems in the past with that (see #1878). Apparently the related bugs are already sorted out, although I didn't test the changes yet.

Another way to make everything work easily is to use browserify-shim to expose jquery to semantic-ui in your package.json.
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "sui": "./semantic/dist/semantic.js"
  },
  "browserify-shim": {
    "sui": {
      "depends": [
        "jquery:jQuery"
      ]
    }
  }
```
Then, in  the app you could just require('sui') and use the modules without problems. It's not as clean as just requiring the exact modules used but it gets the job done.

**Comment by 1vasari** [comment]
Thanks @trigoesrodrigo. I'll try that out. It looks like the solution I'm looking for.

**Comment by ekremkaraca** [comment]
Hey guys,

I'd like to use js-only version with Rails project which recently was allowed to add components via yarn. As described in #4801, yarn and semantic-ui (npm package) has a conflict ongoing. For css, there is no problem because of being shipped as css-only. But it would be better if there would also being shipped as js-only package.
