### ISSUE TITLE
[Comments] Add Inverted Variation

### ISSUE THREAD

**Issue by paulwal** [Semantic-Org/Semantic-UI#2348]
Hi, I'm trying to switch between day & night views; so toggling between a light color scheme and a dark color scheme. I like how Semantic UI makes this really easy with the Menu using the "inverted" class. 

To illustrate what I'm trying to do, go here and click Chat:
http://www.sessionlessons.com/8

You can see the Comment view with the default styling. Now click Config and turn on night view. The "Night view" text color css is changed manually via javascript. Now click back to Chat and you can see its colors are unchanged. Is there a way to change it using the inverted class or does it just need to be styled manually? Also, is there a list of which elements/collections/views/modules that the inverted class can be used on? Thanks

**Comment by jlukic** [comment]
Comments is definitely missing an inverted variation. I'll add that as an enhancement.

In general, variations like `inverted` are only defined in the context of UI components.  Inversion is often more complex than just flipping a single text color, and other element variations may need to be adjusted as well.  For example `inverted menu` has to define inversion in the context of all other types & variations, `pointing`, `secondary`, `text`, etc.

**Comment by paulwal** [comment]
Ok great, thanks for the explanation.

**Comment by tmikaeld** [comment]
So inverted text menu is coming as well?

**Comment by Atulin** [comment]
Opening again, 3 years later. How's the progress?
