### ISSUE TITLE
Version 2 on June 1

### ISSUE THREAD

**Issue by karltud123** [Semantic-Org/Semantic-UI#2350]
I thought version 2 will be released on June 1?

I know there must be some problem or anything, because I am also a developer, but isn't there should be at least a notification or announcement about the delay?

Any thoughts?

Thank you very much.

BTW, Semantic UI rocks.

**Comment by ph7vc** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/2216#issuecomment-108029167

Read Jack's post about the release. Still some things left to do for a complete release.

U can contribute or preview it at http://beta.semantic-ui.com

**Comment by karltud123** [comment]
oooh! I see this was I was looking for.. thank you!
