### ISSUE TITLE
Modal still closing even after closable false and returning false in callbacks

### ISSUE THREAD

**Issue by jaypanares** [Semantic-Org/Semantic-UI#2351]
Hi, the modal I am using is still closing even though I seem to have the correct settings for it to be not closable on click:

http://jsfiddle.net/jaypanares/csqg5uz1/1/

The .js was copied directly from the docs.  I had to fallback to not using `div.actions` for modal buttons.

*I apologize that I've been posting bugs quite a lot recently, but I try and check out existing and closed issues before I post mine.*

**Comment by jlukic** [comment]
`onCancel` and `onApprove` only trigger if the selector matches `approve` or `deny`

**Comment by jlukic** [comment]
http://jsfiddle.net/y968awqy/

**Comment by jaypanares** [comment]
Thanks!  Excellent work as always.
