### ISSUE TITLE
UI suggestion - dropdown search on keypress

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2352]
It would be nice to have this behaviour:
I have a dropdown with 2 items: 'abc', 'xyz'. When I have dropdown toggled (`$(.ui.dropdown).dropdown('is visible') = true`), if I press 'a' key on keyboard, 'abc' gets hovered (if I next press 'enter', 'abc' will become dropdown's value). Correspondingly, if I press 'x', 'xyz' gets hovered.

**Comment by jlukic** [comment]
It does this in `2.0` already

**Comment by avalanche1** [comment]
:+1: :+1: :+1:
