### ISSUE TITLE
.ui.form .fields:last-child, .ui.form .field:last-child

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2353]
As you can see here http://jsfiddle.net/avalanche1/n1o3v45h/9/ - Metro field receives `margin-bottom: 0em`, while' it is not the last field in the form and should have `margin-bottom: *1em*`

**Comment by jlukic** [comment]
Everything seems fine with inputs
http://jsfiddle.net/afatzua7/

**Comment by avalanche1** [comment]
oops, seems like my fiddle didn't get updated with inputs, but you still caught my meaning) kool!
