### ISSUE TITLE
transition fallback to "No animation defined in css" in android browser 

### ISSUE THREAD

**Issue by planeth44** [Semantic-Org/Semantic-UI#2354]
Use case : modal module
When using it with Android browser or chrome 40.xxx. transition module fail with error "No animation defined in css", and static animation fallback is not triggered.
I chased it down to line :684 in transition.js.
Quick fix : i commented lines 684-687 to let static animation fallback kicks in

**Comment by jlukic** [comment]
Can you elaborate. This isn't enough for me to triage a bug.

**Comment by planeth44** [comment]
@jlukic 
Exemple in Backbone
`  events: {`
`    'click #see-cgu' : 'showCgu'`
`  },`
`  showCgu: function showCgu(evt) {`
`    $('#modalContainer .actions').before(this.cgu);`
`    $('#modalContainer').modal('show');`
`
When I click on #see-cgu, the modal do not show and I get "No animation defined in css" error message in the dev tool console.

**Comment by avalanche1** [comment]
Closing until there's a codepen or jsfiddle test case.
