### ISSUE TITLE
Sticky header overwrites top of content.

### ISSUE THREAD

**Issue by geverit4** [Semantic-Org/Semantic-UI#2356]
This might be the designed behavior, but I can't figure out how to get the body content that is below a sticky header to appear below the sticky header.  

Here is a fiddle that shows the problem:

https://jsfiddle.net/geverit4/jrkozrem/6/

How can I get the sticky menu bar overlay to push the following content down, or get the main page content to have a margin at the top?

**Comment by jlukic** [comment]
Since we are dealing with CSS only there's no way for it to know what content needs to shift.

This is when it makes more sense to pull out some custom css.
https://jsfiddle.net/n8wsxLmf/

**Comment by geverit4** [comment]
Perfect.  Thanks for indulging my n00b question.
