### ISSUE TITLE
Adding and removing dropdown menu items programmatically

### ISSUE THREAD

**Issue by pcj** [Semantic-Org/Semantic-UI#2357]
In order to add or remove dropdown menu items using javascript, I have to add a `<div class="item">` child to the `<div class="menu">` DOM, then re-initialize the dropdown module.  If the dropdown initialization is complex, this makes for messy and seemingly unnecessary code.

Any plans for this?  I could take a stab at it, but would appreciate a recommended approach.

**Comment by miniskulljob** [comment]
You can do `$(".menu").dropdown("refresh")` everytime you add or remove an item.

**Comment by pcj** [comment]
Great, I'll try this.  Perhaps it should be documented?

**Comment by jlukic** [comment]
In `2.0` dropdown automatically watches for DOM mutations not just in `<select>` [but also `menu`](https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js#L148)
