### ISSUE TITLE
Right-labelled input has excessive padding-right

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2361]
This occurs in both 1.12 and 2.0 - the screenshots below are directly from the Semantic docs site after typing "a really long search string to make the box scroll" into each input.

![](https://i.imgur.com/It6IShv.png)
![](https://i.imgur.com/EqQAFDO.png)

The first one looks fine, this is the extra padding-right leaving space for the icon. But the second one doesn't need that padding-right and is just wasting space. For a particularly short input with a label it ends up wasting a good third of the space or more.

Could the padding-right only be applied when its needed? (corner label only?)

**Comment by jlukic** [comment]
The css on this was incorrect, and was not applying correctly to only `corner labeled  input`. Should be fixed.

**Comment by celsworth** [comment]
Thank you for the quick fix :)
