### ISSUE TITLE
Right sidenav opening from left side of page. 

### ISSUE THREAD

**Issue by debutmyname** [Semantic-Org/Semantic-UI#2362]
Just getting started with semantic-ui. 

Seem to have run into a problem with the right sidebar opening from the left side of the page. Only  happens while there is a visible left sidebar. Do I need to put each sidebar in a different container div?

http://jsfiddle.net/rduvhn8u/30/
click inside the Need Help input box to load right sidebar.

Prelim debug:

If I take out the left sidebar the code runs and the right sidebar works great.

**Comment by jlukic** [comment]
If you call sidebar with an init object it will reinitialize and destroy the previous instance.

Try syntax like this
http://jsfiddle.net/bzx2x929/

**Comment by debutmyname** [comment]
Thanks. Worked great!
