### ISSUE TITLE
First child of item with left border in borderless menu

### ISSUE THREAD

**Issue by hastebrot** [Semantic-Org/Semantic-UI#2363]
~~~html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="bower_components/semantic-ui/dist/semantic.min.css">
	<style>
		/* workaround: */
		.ui.menu.borderless > .container > .item:first-child {
			/*border-left: 0 !important;*/
		}
	</style>
</head>
<body>
	<div class="fixed ui attached yellow inverted borderless menu">
	    <div class="ui container">
	        <a class="ui item">left item</a>
	    </div>
	</div>
</body>
</html>
~~~

Without workaround:

![semantic-issue-borderless-menu-1](https://cloud.githubusercontent.com/assets/496255/8006012/0b602b00-0b90-11e5-8d34-2ce4abc4b93e.png)

With workaround:

![semantic-issue-borderless-menu-2](https://cloud.githubusercontent.com/assets/496255/8006013/0d9183e2-0b90-11e5-90b0-e2ea3e6e119c.png)

The css rule `.ui.menu:not(.secondary):not(.text):not(.tabular) > .container > .item:not(.right):first-child` that causes this was last changed in 6f6a7f95, but I think this issue is older than this change.

**Comment by hastebrot** [comment]
Ok. "Older that this change" means not more than seven days old:

In this changeset the left border was not shown:

~~~
$ git checkout `git rev-list -n 1 --before="7 days ago" next`
Note: checking out '7951b32c19e9eefeefc86b51e3ad06fe68a967e7'.
~~~

**Comment by jlukic** [comment]
This was added intentionally.

**Comment by hastebrot** [comment]
@jlukic So the border in the `.borderless.menu` is intentionally? If this is true, then this issue can be closed. I have this workaround to fix the border for my use cases.

**Comment by jlukic** [comment]
Oh I missed `borderless menu` that's a bug.

**Comment by jlukic** [comment]
Accidentally commiteed with c1ace94d43077c8d600a01e6ae96f0b8b7552553. One of the uglier lines of the library..
