### ISSUE TITLE
Changing search inputs value through clicking context menu doesn't send any browser .trigger()s

### ISSUE THREAD

**Issue by Andygmb** [Semantic-Org/Semantic-UI#2365]
Meaning it's not possible to add a callback because there is no trigger to attach it to.

example:

http://i.imgur.com/MhtmW0e.gif

when you click on the suggested value, the <input>'s value is changed using .val(), which doesn't send a .trigger() meaning you can't do something like $(input).on("change", function()). Please update the search to also add a trigger() when the val is being updated. 

Thanks

**Comment by jlukic** [comment]
theres a callback `onSearchQuery` which can be attached whenever a value is searched. There is also `onSelect` callback.

**Comment by mishak87** [comment]
@jlukic It is labeled as Already Fixed shouldn't it be closed?

**Comment by jlukic** [comment]
Yes, sorry the boards need a little pruning.

**Comment by mishak87** [comment]
No problem, will try to help with that when I'm bored. :-)
