### ISSUE TITLE
[Docs] [Sticky Menu] Bug on pages shorter than the menu

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI#2366]
Hi,
Nice work on the new responsive layout, but the first bug mentioned in #2340 is still valid

So it happens only on pages shorter than the menu: the [Reset page overview](http://beta.semantic-ui.com/globals/reset.html) and the [API page overview](http://beta.semantic-ui.com/behaviors/api.html)

1. Go to one of those pages.
2. Scroll down a little bit: the menu "jumps" to `bound bottom`.
3. Try to scroll up again: the menu keeps being `bound bottom`, you can't get back to the top of the menu.

**Comment by jlukic** [comment]
I've added sticky footers to docs as well.
