### ISSUE TITLE
site.variables file not found

### ISSUE THREAD

**Issue by joetm** [Semantic-Org/Semantic-UI#2367]
I use the meteor package of semantic ui (semantic:ui).
When I start meteor, I get this error:
Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried - client \js\vendor\semantic-ui\themes\default\globals\site.variables,c:\www\htdocs\projects\www\client\js\vendor\semantic-ui\themes\default\globals\site.variables, themes\default\globals\site.variables

That file is indeed not present in the themes folder. (There is not even a globals folder in that folder.)

theme.import.less specifies:
@import "@{themesFolder}/default/globals/site.variables";
But that file is not supposed to be changed.

theme.config.import.less has all themes set to default.
and:
/* Path to theme packages */
@themesFolder : 'themes/';
/* Path to site override folder */
@siteFolder  : 'site/';
@import "theme.import.less";
/* End Config */

**Comment by jlukic** [comment]
Hi, please create issues related to meteor in the related repo. The maintainers can help you there
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues
