### ISSUE TITLE
.ui.icon.message inside form doesn't use flex rendering

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2368]
I don't see whether this is explicitly supported or not within the docs so I'm not sure if this is a bug, but I noticed that .ui.icon.message does not render properly when used inside a form:

![](https://i.imgur.com/AIyujNF.png)

vs outside a form as you'd expect:

![](https://i.imgur.com/QRJQ3TE.png)

This seems to be due to the un-hiding of a .message inside a form applying `display: block` rather than `display: flex`. I trivially fixed it by simply applying:

```css
.ui.form.error .icon.error.message {
  display: flex;
}
```

(obviously this is against the next branch btw) :)

**Comment by jlukic** [comment]
457f9c5868fce946a4ac74493655e7d4139f031d
