### ISSUE TITLE
beta docs don't display in Safari

### ISSUE THREAD

**Issue by terraling** [Semantic-Org/Semantic-UI#2370]
None of the documentation pages are displaying in Safari (Version 8.0.6 (10600.6.3))

e.g. http://beta.semantic-ui.com/kitchen-sink.html displays the left black sidebar with navigation, but none of the linked pages display content, which is blank.

Displaying as expected in Firefox, Chrome.

Looking at the compatability for it says Safari 6. Does that mean only version 6 and not 6+?

**Comment by jlukic** [comment]
@terraling Thanks, just realized some flexbox rules in docs are missing vendor prefixes. Will fix

**Comment by jlukic** [comment]
Fixed with https://github.com/Semantic-Org/Semantic-UI-Docs/commit/07a5196fd72e64aa2c31479dd0179836a8863f95 and deployed
