### ISSUE TITLE
[Input] Add styles for errored labeled input

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2372]
When you apply an error to a labeled input field, the border-radius doesn't seem to get updated properly for a left label; see screenshot and fiddle:

![](https://i.imgur.com/05WXUFM.png)

http://jsfiddle.net/dty52sw8/2/

First one shows the issue. Second one shows it works ok for a right label.

The third one was just me playing with a bit of extra styling for an otherwise unstyled label in the error case, what do you think about including it? (if a label inside an errored field does not have a colour of its own, inherit the error colours)

**Comment by jlukic** [comment]
This seems like an easy enhancement, but will have to wait until after `2.0` launch

**Comment by uyab** [comment]
Any update about this issue?
