### ISSUE TITLE
Numbers and special characters in css definitions

### ISSUE THREAD

**Issue by joetm** [Semantic-Org/Semantic-UI#2375]
Is it possible to turn off the use of numbers in css definitions?
Definitions like this:
```
  .ui.\32.buttons > .button,
  .ui.two.buttons > .button {
    width: 50%;
  }
```
will break third party tools.

**Comment by jlukic** [comment]
Which tools does this break?

**Comment by joetm** [comment]
Background: I load semantic UI on top of existing CSS rules. Some of those rules clash with Semantic UI. I therefore need to prefix the semantic UI CSS to avoid interference with the existing CSS.
To do this, I used gulp-prefix-css. That tool is built on prefix-css, which in turn uses cssp:
https://github.com/css/cssp
So it's cssp that breaks at the "\" characters.

**Comment by jlukic** [comment]
I've removed these for 2.0 and added deprecation to release notes.
