### ISSUE TITLE
Checkbox .first problem

### ISSUE THREAD

**Issue by mbpakalin** [Semantic-Org/Semantic-UI#2376]
Hello,
My problem is as you can see on this picture.
All of the first checkbox elements is in wrong alignment.

![hata](http://data.mbpakalin.net/test/semantic_first_hata.png)

**Comment by BigGrecian** [comment]
Do you have the code for this - I assume you are using a grid or table to assist?

**Comment by mbpakalin** [comment]
Yes here it is => http://codepen.io/anon/pen/zGwdvj

**Comment by celsworth** [comment]
You need to wrap every 4 checkboxes in a new "four fields" div, so the margins will line up

**Comment by mbpakalin** [comment]
Thanks so much, it worked!
