### ISSUE TITLE
Incompatibility with Bootstrap using Modal

### ISSUE THREAD

**Issue by opvini** [Semantic-Org/Semantic-UI#2377]
Hi everyone.
I want to use some objects that needs Bootstrap like DatePicker, MaskedInput, TagsInput.

When I include "bootstrap.min.css" and I try use a Modal, it doesn't works fine.

I really need use these components that doesn't exists on semantic.

Thanks a lot.

**Comment by opvini** [comment]
I am using bootstrap-datepicker, and not jquery ui datepicker...

**Comment by ikourfaln** [comment]
You cant use both, semantic and bootstrap !!!!!!!! bcz you can find classes in Bootstrap and SUI with the same name.
the component bootstrap-datepicker is just for Bootstrap, so you cant use it with SUI.

I google for you and the only DateTime picker for SUI that I find is:
https://github.com/pinguxx/sm-datepicker
it require:
https://github.com/lhorie/mithril.js and https://github.com/pinguxx/sm-calendar

**Comment by opvini** [comment]
I am using a jQuery UI with SUI, and jQuery datepicker and it works fine now.
Thank you a lot!

**Comment by ikourfaln** [comment]
Yes you can use any widgets built on top of the jQuery.
