### ISSUE TITLE
Dynamic dropdowns set selected not working (AngularJs)

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#2379]
See this http://jsfiddle.net/teodor_kolev/b0gu3rw1/2/
Two same dropdowns. 1st is Angular dynamic and second is static.

Any Ideas how this thing start working?

**Comment by jlukic** [comment]
What is not working? The second value is set to female? Perhaps this might make more sense to ask over on [Semantic-UI-Angular](https://github.com/Semantic-Org/Semantic-UI-Angular/issues) or their [Gitter](https://gitter.im/Semantic-Org/Semantic-UI-Angular).
