### ISSUE TITLE
this great framework can not be used in a product, it dose not work well with ie

### ISSUE THREAD

**Issue by hiwjcn** [Semantic-Org/Semantic-UI#2386]
i test with ie9,win7. and it

can not provide a good performance.....

its just a toy framework,just for artist or some one  
stupid

**Comment by hiwjcn** [comment]
forgive my rude

**Comment by GibsonSG76** [comment]
WTF ? It's work on ie ..

**Comment by vautrinr** [comment]
#rules number 1 : Don't feed the troll ^^

**Comment by GibsonSG76** [comment]
Okey !

**Comment by jlukic** [comment]
This is a framework intended for the next generation of websites, not the previous. I understand not all web projects can live in this world though. Hopefully you can join soon :)
