### ISSUE TITLE
[Form Validation] Do you have something to make abstract rules for form validation?

### ISSUE THREAD

**Issue by DruidKuma** [Semantic-Org/Semantic-UI#2388]
I've tried to find something to help me with creating abstract rules for form, but didn't find such functionality. Can you either give a hint where to find it, or pay attention to implement such thing in next release?
e.g.
I have a form:
```html
<form id="form">
    <input type="text" data-validation="not-empty" name="firstName">
    <input type="text" data-validation="not-empty" name="lastName">
</form>
```
and rule for this:
```javascript
$('#form').form({
        not-empty: {
            identifier: 'not-empty',
            rules: [
                {
                    type: 'empty',
                    prompt: 'This is required field'
                }
            ]
        }
    }, {inline: true, on: 'blur'});
```
How can I make it work, validate every field separately against the same rule without duplicating the same rule for every field?

**Comment by jlukic** [comment]
You have to repeat all `empty` rules in a settings object. There's no other way implemented currently.

You can implement your own rules by adding them to `$.fn.form.settings.rules`, check out end of `form.js` for plenty of examples.

**Comment by neokio** [comment]
My questions is related enough that I'll just post it here:

There are many cases where I want to validate across many fields, presenting a custom error, without attaching to any one particular identifier. My workaround has been to add a junk hidden input, to allow me to use a custom rule.

Is there a better way?

```html
<form class="ui small form">
	<input name="IGNORE_ME" type="hidden">
	<div class="field"><input name="input_1"></div>
	<div class="field"><input name="input_2"></div>
	<div class="field"><input name="input_3"></div>
	<div class="field"><input name="input_4"></div>
	<div class="ui error message"></div>
	<button class="ui button">Save</button>
</form>
```

```javascript
$.fn.form.settings.rules.multicheck = function(value) {
	var valid = true;
	for (var what of ['input_1','input_2','input_3','input_4']) {
		if ($('input[name='+what+']').val()=='') {
			$('form').form('add prompt', what);
			valid = false;
		} else {
			$('form').form('remove prompt', what);
		}
	}
	return valid;
}

$('form').form({
	onSuccess: function(){
		console.log('SUCCESS');
	},
	fields: {
		
		// other rules here
		
		IGNORE_ME: {
			rules: [{
				type   : 'multicheck',
				prompt : 'Please fill in all 4 fields'
				}]
			}
		}
	}
});
```
