### ISSUE TITLE
Collapsible sidebar

### ISSUE THREAD

**Issue by rcarjan** [Semantic-Org/Semantic-UI#2391]
I am not sure wether this is a good place to ask this question, but I haven't had a response anywhere else, so here goes: 

I am trying to make a sidebar using Semantic-UI which, when collapsed, still has a portion visible. Something like [this](http://rdash.github.io/), to be more precise.

I have managed to do [something similar](http://rcarjan.me/sidebar-test/), but it's not exactly what i want. Even thugh the sidebar looks okay, there are still some things that I would like it to be able to do, as in the previous example: items changing appearance/visibility depending on wether the sidebar is collapsed or expanded(such as the labels which I would want not to show when it is collapsed) and the content of the page itself is pushed to the right, however I would like it to be squished to fit the page width.

Is there any possible way of doing it using semantic, without having to write the whole sidebar javascript/css from scratch?

Thank you in advance, and I am sorry if this is not the right place to ask this.

**Comment by ph7vc** [comment]
Well with CSS you could add a custom rule to hide the labels when the sidebar is not visible. If you look; when it is in the open state, it adds the `visible` class, so you could set a rule for those labels to be hidden.

The "squishing" behavior is not part of semantic at the moment. It could be a future improvement.

Would the `overlay` mode work for what you need?

**Comment by rcarjan** [comment]
Thank you, I might just do that, it would solve the problem fairly easily. Regrarding the "squishing", the overlay isn't quite what I want, however, I think I will try to modify the "scale down" mode, to see if I can make it work.

Thank you.

**Comment by rahulchandrangb** [comment]
jhqjwq
