### ISSUE TITLE
dropdown overflow out of (viewport) screen

### ISSUE THREAD

**Issue by ranbuch** [Semantic-Org/Semantic-UI#2392]
When using the dropdown component and the dropdown is on the bottom of the screen some the options aren't visible due to the positioning (absolute).

I noticed there's you've provided a solution for the problem by adding the class "upward" to the "ui dropdown" class but I was thinking if there is a way to auto-detect the situation (like the native select menu does) because some of the times the component is dynamically positioned on the screen and because of that the "upward" class isn't the best option.

Thank you!

**Comment by yairneumann11** [comment]
Hey Ran,
This issue happened to me just last week and like you suggested I added the "upward" class
but it would be great if the framework would support your suggestion  of auto-detecting the dropdown height/width

cheers!

**Comment by jlukic** [comment]
In `2.0` dropdowns will automatically open upward if it is too low. One more week...
http://beta.semantic-ui.com/modules/dropdown.html

**Comment by ranbuch** [comment]
Thanks!
by the way semantic-ui is the #1 web client UI library in my opinion. you've done a great job :+1:
