### ISSUE TITLE
onSelect for Search input

### ISSUE THREAD

**Issue by sacdallago** [Semantic-Org/Semantic-UI#2393]
#### UPDATE

I also tried using 'standard' and 'category' templates, while with the latter the html doesn't even build up, being that there is no "title" attribute in the result of the API, with "standard" template I see empty html rows, but still, when clicking the result in console is undefined for the result.

////

Dear community & developers,

I am trying to implement a search for addresses using google maps api, styling the responses from the API to something more user friendly. The problem I have is that I cannot seem to get the selected value on the onSelect event of the search input.

I copy the code below, in sections:

HTML
```
<div class="ui attached segment">
				<div class="ui fluid search">
					<input class="prompt" type="text" placeholder="Am schaeferanger, 15">
					<div class="results"></div>
				</div>
			</div>
```

JS-API
```
$.fn.api.settings.api = {
  'get location': 'https://maps.googleapis.com/maps/api/geocode/json?address={query}',
};
```

JS-search
```
$('.ui.search.fluid').search({
        apiSettings: {
            action: 'get location',
            successTest: function (response) {
                return response && response.status == "OK";
            }
        },
        type: 'list',
        templates: {
            list: function (response) {
                var html = '';
                if (response.results !== 'undefined') {
                    $.each(response.results, function (index, result) {
                        html += '' + '<div class="result">' + '<small class="name">' + result.formatted_address + '</small>' + '</div>';
                    });
                    return html;
                }
                return false;
            }
        },
       onSelect: function (result,response) {
            console.log(result);
            console.log(response);
            return true;
        }
    });
```

###### Example
Searching for "marien":
![results](https://cloud.githubusercontent.com/assets/6240943/8105179/24120988-1037-11e5-9b35-57f2d376ac31.png)

Console logs undefined for result and the entire result set for response:
![result](https://cloud.githubusercontent.com/assets/6240943/8105191/48680ddc-1037-11e5-8880-a8ded3032e40.png)

I assume the problem lies in the template I built, any indication as to how to fix that is very, very, very appreciated.

**Comment by jlukic** [comment]
Try against search in `2.0` aka `next` branch. See release notes for changes to search. Specifically to `onSelect`

**Comment by jlukic** [comment]
You can also use `onResponse` in 2.0 to adjust the JSON before it appears in other callbacks like `onSuccess`

**Comment by sacdallago** [comment]
Thanks @jlukic I will try that tomorrow at work :)

**Comment by jlukic** [comment]
http://beta.semantic-ui.com/introduction/new.html#translates-any-api

Example with github api
