### ISSUE TITLE
[API] Encode URI before doing URL substitutions

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2394]
I'm trying to connect to a remote API that requires a query string with characters that need to be properly URI-encoded. I discovered that Semantic UI's API behavior module currently doesn't URI encode the `url` settings at all, which is a bit of an issue, because I can't encode the query string myself since I need to use a URL substitution to capture the user's query (if I do, it'll try to encode the curly brackets from `{query}`, which will cause URL substitution to be skipped. Would it be possible to URI encode the `url` before performing the substitutions?

(I'm on the `next` branch)

**Comment by jlukic** [comment]
The URL is encoded during the `$.ajax` call. 

Try going to the search page, for example, and typing in the prompt `áááá`. You will see in inspector/firebug that hte URL is `http://api.semantic-ui.com/search/%C3%A1%C3%A1%C3%A1`

**Comment by tirdadc** [comment]
Try this out with the @ symbol, it doesn't get encoded to %40 which causes 502 bad gateway errors for some results on your link.

**Comment by jlukic** [comment]
Searching for `@` and `@@` both work for me and return normal responses. The API endpoint sometimes gives `502 bad gateway` because the nginx server cant handle too many simultaneous requests.

**Comment by tirdadc** [comment]
I see that now, but it's still not getting escaped. Try with % and it'll return a 400 Bad Request. Point is you should be consistently seeing escaped characters like %40 and %25. I can't manually work around this either with encodeURIComponent() because {query} doesn't seem to get interpolated when I do this:

```
apiSettings: {
  url: '/users/autocomplete/email/' + encodeURIComponent('{query}')
}
```

**Comment by jlukic** [comment]
You would have to do as
```javascript
apiSettings: {
  url: '/users/autocomplete/email/{query}',
  urlVariables: {
    query: encodeURIComponent(query)
  })
}
```
I can see both sides here. My fear is double encoding which becomes an issue when blackboxed JS code (like this API module) happens to modify your strings.

**Comment by daneren2005** [comment]
For anyone else who comes across this, it is fairly easy to fix on the calling end with:

```
apiSettings: {
    url: 'get.php?term={query}',
    beforeSend: function(data) {
        data.urlData.query = encodeURIComponent(data.urlData.query);
    }
}
```

**Comment by jlukic** [comment]
I'll be revisiting this shortly in `2.1`

**Comment by jlukic** [comment]
Added in `2.0.5`, should check if value is already encoded to avoid issues during replacement. 
Keep in mind if you were encoding in `beforeSend` like @daneren2005 's example, you may double encode.

**Comment by jlukic** [comment]
Added `encodeParameters` setting in `2.1`
