### ISSUE TITLE
[Menu] Add Fixed Menu To Docs

### ISSUE THREAD

**Issue by hpohl** [Semantic-Org/Semantic-UI#2400]
Recently I've tried out Semantic UI 2.0 and ran into an issue: I've been using a sticky menu bar which should be totally fine. My page body is a grid and somehow overrides the lower part of the menu.

https://jsfiddle.net/yrmnu5gq/2/

Scrolling up and down or setting the offset to 1 makes it work again, but that's definitely not what we want.

Tested with Chrome 43 and Firefox 38.

**Comment by jlukic** [comment]
Sticky is designed to stick to other content. It hasn't been tested to be used with `body`

If you want an element just to fix to viewport when passed use visibility APIs, the simplest version is.
```javascript
$('.ui.sticky.menu')
    .visibility({
      type: 'fixed'
    })
  ;
```

**Comment by hpohl** [comment]
Oh, I didn't even see there was that visibility API thing, nice. But it creates a placeholder, which creates space I don't want. Can I just hide it or is there a way to turn it off? Also there is a little bug with pointing menus, a small pointer in the middle of the following div: https://jsfiddle.net/yrmnu5gq/3/

**Comment by jlukic** [comment]
If you want an element to be always fixed to viewport, just use `top fixed menu`, or in your css `position: fixed`

**Comment by hpohl** [comment]
Just `position: fixed` did not work, tried that one before. `top fixed` works perfectly, though! Where was I supposed to find the combination of `top` and `fixed` in the docs?

**Comment by jlukic** [comment]
I've added new examples to the docs.
http://beta.semantic-ui.com/collections/menu.html#fixed

**Comment by hpohl** [comment]
Nice :+1:
