### ISSUE TITLE
Semantic UI Progress Start from 10%

### ISSUE THREAD

**Issue by darkcyber** [Semantic-Org/Semantic-UI#2401]
Hi i just initialize UI Progress and work correctly with little ammout 1-10, (1=10%, 2=20%, and so on) but if i try to progress 1000 total ammount, why progress bar start from 10% instead of 1% or depends on calculation, so when progress bar reach 100% and show 1000 Checked, my process still running.

Is this bug or something ?

**Comment by jlukic** [comment]
Can you provide a JSfiddle test case? I'd like to debug any issues you're facing
