### ISSUE TITLE
Performance concerns.

### ISSUE THREAD

**Issue by avaz** [Semantic-Org/Semantic-UI#2404]
Hi,

I'm learning SemanticUI, so I'm staying a lot of time on SemanticUI sites (http://semantic-ui.com and http://learnsemantic.com/) and I noted that the CPU of my machine (MacBook Pro 2.8GHz) stay on ~130% when I'm with one of this site on focus. The landing page of learsemantic.com is one of more cpu consuming, reaching consuming up to 160% of CPU. The fan of MacBook keep at right RPM doing a lot of noise.
The same is observed is the browsers: Safari, Chrome and Firefox.
Is that normal? Should I be concerned in use semantic-ui in production because of it?

Thanks!

**Comment by oytuntez** [comment]
I have almost the same setup, the CPU looks fine in mine (even in Chrome). How are other websites like Facebook behaving? On reload, Semantic UI goes up to 80% for a moment and then declines which is the expected behavior.

Also take a note that Semantic-UI homepage is bloated with examples (not LearnSemantic, though).

**Comment by celsworth** [comment]
The LearnSemantic homepage has an animation on it which pushes CPU usage right up for me (as does the Semantic-UI homepage, to a lesser extent), but the other pages (barring the kitchen sink) seem fine to me.

**Comment by jlukic** [comment]
The learn semantic homepage as discussed in other threads has several animated 3d layers. Having your machine jump up in CPU usage is very normal for 3D. The homepage of semantic-ui, has an animated radial gradient, and a pulsating progress bar, both of these usually leave some residual cpu usage. 

Either of these things have to do with how browsers use CPU to process continuous animations. This is true for anything of this sort on the web, Semantic UI included. 

Generally the same will only be true for a website using Semantic UI, if it has continuous animations as well. (A never-ending loader throbber, an animated progress bar, etc).
