### ISSUE TITLE
Where's all the documentation?

### ISSUE THREAD

**Issue by karlmayer** [Semantic-Org/Semantic-UI#2408]
I really like what I'm seeing with Semantic UI, but I feel like I'm missing _critical_ documentation to be effective.  

For example, the [dropdown module](http://semantic-ui.com/modules/dropdown.html) is fairly well documented. 

But [menus](http://semantic-ui.com/collections/menu.html) appear to be missing all the JavaScript documentation.

Same with [cards](http://semantic-ui.com/views/card.html).  Where is http://semantic-ui.com/javascript/card.js documented?!

And why does http://learnsemantic.com/ not cover the necessary JavaScript to initialize Semantic UI anywhere?  Only after reading docs.js in some of the demo pages, I figured how to make some examples work.

I see that a 2.0 release is coming up, but it doesn't even feel like a 1.0 release yet.  Am I missing something essential?

**Comment by kevindice** [comment]
There's basically 1 guy (Jack) working on this whole project.  Right now, he is working very hard to get 2.0 out there and fix any outstanding bugs.  I'm sure he would welcome contributors though... ;)

**Comment by karlmayer** [comment]
I understand the resource limitations and the immense complexity with developing a framework of this scale.  However, imho, the 2.0 branding and "Enterprise Ready" designation on the home page are misleading and detract from the work that's actually complete.  Best of luck in the 2.0 implementation.

**Comment by slb235** [comment]
Modules have javascript parts, cards and menus are css only (imho all elements, collections and views are). So there is nothing missing.

http://semantic-ui.com/javascript/card.js is part of the SemanticUI page, not the framework, and all it does is activate the [rating module](http://beta.semantic-ui.com/modules/rating.html) on the cards documentation page.

I never used http://learnsemantic.com/ but the other points u are bringing up are pretty invalid.

**Comment by karlmayer** [comment]
I won't belabor my points.  I'm just pointing out that I think to improve uptake, better documentation is necessary.  

I get that ratings are a separate module.  The "View Source" for the card with ratings shows the necessary HTML, but not the necessary JavaScript.  Example code for menus is also useful, whether they need it or not -- a menu without code isn't going to do anything.

I may have overlooked it, but I could not even find the necessary code to initialize 'window.semantic' object in documentation.
