### ISSUE TITLE
Sidebar closes when selecting from inside to outside the sidebar

### ISSUE THREAD

**Issue by emink92** [Semantic-Org/Semantic-UI#2409]
Hey guys!

So these days I've been working with the Semantic-UI Sidebar and I realised that if you try to select some text and you drag it outside the sidebar it closes it automatically.

Is there any way to prevent this?

Example:
![myi9y](https://cloud.githubusercontent.com/assets/9529536/8180209/9b3ec5da-141c-11e5-9795-acfe8ba2e1b9.gif)

**Comment by philrykoff** [comment]
Not reproducable on SUI homepage with Chrome 56 + FF 46. Maybe it was fixed in between?
