### ISSUE TITLE
managing Semantic config files in bower_components

### ISSUE THREAD

**Issue by myriamgoude** [Semantic-Org/Semantic-UI#2410]
Hello, this is my first post here !

I just installed an app Angular/semantic-ui and stuck in the process : 
Semantic is installed as bower_component. All config files are IN bower_components/

So my question is about working in a team : as we don't have to push bower_components/ folder in repo, how can we share all configs + dist/css with teammates via git versionning ? Is there a good practice to adopt here ? ( we are using grunt on main app )

**Comment by KapuzenSohn** [comment]
You can specify `overrides` in the bower.json file, where you save all dependencies. Example:

``` JSON
  "overrides": {
    "semantic": {
      "main": [
        "dist/semantic.css",
        "dist/semantic.js",
        "dist/themes/default/assets/fonts/**"
      ]
    }
  } 
```

In the example I override the `main` files. Important is that you have to add the overrides to the bower files from your project and not to a bower file of a dependency

**Comment by myriamgoude** [comment]
Top ! that works like a charm (thanks for your reactivity !)
