### ISSUE TITLE
[Segment] Attached segment does not have raised variation

### ISSUE THREAD

**Issue by moen-io** [Semantic-Org/Semantic-UI#2411]
Not sure whether or not this is by design.

JSFiddle: http://jsfiddle.net/8px6860p/

**Comment by jlukic** [comment]
It's by design. The raised shadow would overlap whatever content it was attached to.

**Comment by jlukic** [comment]
I've added new group variations for `stacked`, `raised`, and `piled`. However they will only work with plural grouped `segments`.
