### ISSUE TITLE
Output css and js to separate dist directories

### ISSUE THREAD

**Issue by kevindice** [Semantic-Org/Semantic-UI#2413]
_About to submit a PR for this._

I think it would be helpful to most people to have the ability to output css and js to separate directories.

**Comment by kevindice** [comment]
Don't pull this yet.  After a whole project regex search, I realized I forgot to make necessary changes to  tasks/watch.js

**Comment by jlukic** [comment]
#2221  Please be sure to check any PR against `next` and remember legacy support for existing `semantic.json` is essential

**Comment by kbajpai** [comment]
Did this issue got fixed?

**Comment by fuzenco** [comment]
Looking through the 2.2 documentation and Learn Semantic, I don’t see any way of defining the paths. Has this not been implemented yet?

**Comment by kevindice** [comment]
No, not yet.
