### ISSUE TITLE
2.0 Video source plays youtube no matter if we specify vimeo

### ISSUE THREAD

**Issue by ciokan** [Semantic-Org/Semantic-UI#2415]
Title self explanatory. The following code attempts to play a youtube script even though vimeo is specified as a source:

`<div class="ui embed active" data-source="vimeo" data-id="117778145" data-placeholder="http://i.vimeocdn.com/video/514537226_640.jpg">....`

embed.js code responsible ~line 608:

```
    vimeo: {
      name   : 'vimeo',
      type   : 'video',
      icon   : 'video play',
      domain : 'vimeo.com',
      url    : '//www.youtube.com/embed/{id}',
      parameters: function(settings) {
        return {
          api      : settings.api,
          autoplay : settings.autoplay,
          byline   : settings.brandedUI,
          color    : settings.colors || undefined,
          portrait : settings.brandedUI,
          title    : settings.brandedUI
        };
      }
```

**Comment by jlukic** [comment]
Yeah, very clear and embarrassing typo.

**Comment by ciokan** [comment]
No issues. The codebase is huge.

**Comment by ciokan** [comment]
Closed it by mistake. I'll reopen it and let you manage the ticket as you like.

**Comment by jlukic** [comment]
This has been fixed now.
