### ISSUE TITLE
How to "stop" closing modal if form invalid

### ISSUE THREAD

**Issue by antondachauer** [Semantic-Org/Semantic-UI#2417]
Hey guys,

I have a form in a Semantic UI Modal, and I use the jQuery Form Plugin (http://malsup.com/jquery/form/#validation) to submit the form via ajax. The "submit" process of the form is triggered by the modal "ok" button. But if the form is invalid, the modal is still closed.

How can I "stop" the modal close procecedure?

Thanks a lot!

**Comment by jlukic** [comment]
Adjust the `selector` object for `close` in settings. 
http://beta.semantic-ui.com/modules/modal.html#settings
