### ISSUE TITLE
[Modal] How to determine which item invoked a modal?

### ISSUE THREAD

**Issue by shatgupt** [Semantic-Org/Semantic-UI#2418]
I have a list of items which have a button to delete. On clicking deleting, it pops up a modal which confirms the action.
I can add class .deleteme to all delete buttons and get the modal to invoke by:
```javascript
$('.deleteConfirm')
    .modal({
      onApprove : function(e) {
        console.log(this);
        console.log(e);
      },
      transition : 'fade'
    })
    .modal('attach events', '.deleteme', 'show');
```
But to actually delete, I need to know which delete button was clicked. I cant find a way to determine that in onApprove callback.
Here is a demo of what I am trying to do : http://jsfiddle.net/dxxwrfpe/1/

EDIT: I think I can do by attaching click event to the delete buttons, but is there a way I can determine in callback only without any extra code?

**Comment by jlukic** [comment]
This is one of the 200ish new things in `2.0`, it is passed as first parameter.
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/modal.js#L222

**Comment by shatgupt** [comment]
As I have understood, and also from the output console.log(e) statement in the above code, the first argument gives the element which was used to approve/deny inside the modal, not the element which invoked the modal in the first place.

For example, in the below code:
```html
<div class="ui selection list">
  <a class="item deleteme">Delete 1</a>    
  <a class="item deleteme">Delete 2</a>    
  <a class="item deleteme">Delete 3</a>    
  <a class="item deleteme">Delete 4</a>    
</div>
```
each of the .deleteme opens the modal, but how do i know which one (ie Delete 1, Delete 2 etc) opened it?

**Comment by jlukic** [comment]
Oh, sorry I read too quickly. I was assuming you wanted what item triggered `onApprove`. 

There's no mechanism built into Semantic UI for tracking what element from `attach events` was used. I'd recommend using something like this

```javascript
var 
  activatingElement // use me to track
;
$('.deleteme')
   .on('click', function() {
     activatingElement = this;
     $('.ui.modal').modal('show');
   })
;
```

**Comment by shatgupt** [comment]
Thank you. I was also thinking the same, but wanted to know if there is any built in method.
I think it would be good option to have especially for confirm/prompt usecases of modal.

**Comment by jlukic** [comment]
I think it's best to use custom code for this.
