### ISSUE TITLE
Menu item: mouse-down on text, mouse-release off the text, doesn't register click in Safari

### ISSUE THREAD

**Issue by paulwal** [Semantic-Org/Semantic-UI#2420]
In Safari, click down on the text of a menu item, drag your mouse slightly over so that it's off the text but still on the menu item and then release the mouse button. A click will not be registered. 

It works in Firefox and Chrome but not in Safari. Tested on OS X 10.10 using SUI 2.0.0.

**Comment by jlukic** [comment]
Does this behavior occur on other sites? Perhaps safari just registers clicks differently? I'm not sure there's much I can do in terms of code to solve this.

**Comment by paulwal** [comment]
That might be the case and I just hadn't noticed it before. On this page, the same behavior is present for the Sign In and Register buttons:
http://en.lichess.org/login

So yeah, it may be unfixable. It's such a minor issue anyway, I probably shouldn't have even posted it.

**Comment by jlukic** [comment]
Thanks anyways. I always appreciate the input.
