### ISSUE TITLE
[Search] Use EM add additional sizes

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2421]
I noticed that with varying a form size, most of the input elements are resized, but ones inside a .ui.search div are not:

![](https://i.imgur.com/MCLsGH0.png)

Demo'd in fiddle: http://jsfiddle.net/27ncqpkr/2/

**Comment by celsworth** [comment]
After a bit of fiddling, this seems to be caused by this rule:

```css
.ui.search {
  font-size: 1rem;
}

I see there's also a .ui.large.search but no small one. And it seems odd to have to declare it as a large search in a large form?

**Comment by jlukic** [comment]
Fixed
