### ISSUE TITLE
[Menu] stackable doubling

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2424]
It seems to make sense to add this variation.

**Comment by jlukic** [comment]
I'm not sure including a menu two by two makes sense. Do you have an example of somewhere else on the web this pattern is used?

**Comment by kapouer** [comment]
Indeed i have not.
The use i had in mind was in the specific case of a "top attached stacking four item menu" at the bottom of a fluid card in a grid layout, so as to get two x two items instead of four vertical items.
Ignore the request if too specific ;)
I tried to do it myself and couldn't easily arrange a solution.
