### ISSUE TITLE
Column visibility

### ISSUE THREAD

**Issue by GibsonSG76** [Semantic-Org/Semantic-UI#2429]
Hi !
Is it possible to hide or show column according to screen type.
For example, I have this html code:
```HTML
<div class="ui page grid">
            <div id="menu" class="four wide computer column">
                      <div class="ui stacked segment"></div>
            </div>

            <div class="twelve wide computer sixteen wide mobile column">
                  <div class="ui stacked segment"></div>
            </div> 
</div>
```

I would like to hide the menu on mobile and show on tablet.
Best regards

**Comment by jlukic** [comment]
http://beta.semantic-ui.com/collections/grid.html#device-visibility
http://semantic-ui.com/collections/grid.html#responsive-visibility
