### ISSUE TITLE
Sticky footer for scrollable dropdown

### ISSUE THREAD

**Issue by Joe312341** [Semantic-Org/Semantic-UI#2433]
Hello,

Is there a way to have a sticky footer for a scrollable dropdown? 

I tried adding two items in a dropdown (one containing a scrollable menu) the other containing an item that would always show up. But this approach does not work.

Fiddle for the attempt:
https://jsfiddle.net/07e5u34g/

As you can see the menu appears on the side 

Is there any way to achieve this with semantic ui?

Here is a clean jsfiddle with just the scrollable dropdown
http://jsfiddle.net/eezz34b6/1/

Thanks,
Joe

**Comment by jlukic** [comment]
2.0 has

**Comment by jlukic** [comment]
2.0 has a scrolling menu variation. You can set its max height manually if its different than default.
http://jsfiddle.net/u6oyk2k2/

**Comment by Joe312341** [comment]
great, thank you :)
