### ISSUE TITLE
[Checkbox] Review Input Z-Index to Allow Simpler Markup

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2434]
While i was doing a circular checkbox like http://jsfiddle.net/fwze097b/2/
i've raised (using z-index) the input over the label and gave it full width and height, so that there would be no need for javascript or "for/id" attribute.
It seems it works almost everywhere - IE<=9 excluded, see https://www.browserstack.com/screenshots/6b6311a508ecca9fca2ba5d3796a979987bd2ff9

Am i missing something ? is it impossible to support IE9 using that technique ?

**Comment by jlukic** [comment]
It's worth considering to make it easier for people who don't want to bother with `for` `id` matching or javascript. But even if an unstyled input could capture clicks, the label would still not correctly activate the input when clicked. 

I'll review this before shipping.

**Comment by jlukic** [comment]
So with JS checkboxes, there issues with using native change events for controlling state. This is [the best writeup i've seen](http://blog.mindscapesolutions.com/2012/06/12/preventing-html-checkbox-toggle-with-javascript/) on explaining the issues.

The only reasonable way to proceed is to allow checkbox to remain on top *until initialization* in javascript, and then moving it under so it can't be clicked natively anymore.

**Comment by kapouer** [comment]
:+1:

**Comment by jlukic** [comment]
I'm very happy with this addition. Thanks for the suggestion.

Examples will be in the what's new section tomorrow.
