### ISSUE TITLE
Buttons Forced Blue Highlight / Box Shadow

### ISSUE THREAD

**Issue by ImSanchez** [Semantic-Org/Semantic-UI#2437]
Hello, I sincerely apologize for any errors or mistakes - this is the first time using Github. 

Line 744 of the master CSS has a forced box-shadow with a blue highlight on all buttons.

<code>
/*--------------
      Focus
---------------*/
.ui.button:focus {
  background-color: '';
  color: rgba(0, 0, 0, 0.8);
  background-image: '' !important;
  box-shadow:0 0 0 1px transparent inset,0 0 1px rgba(81,167,232,.8)inset,0 0 3px 2px rgba(81,167,232,.8)!important
}
</code>

![24ae15dd374b1a3b66caad4bd2bd1460](https://cloud.githubusercontent.com/assets/2328269/8275783/853cc554-187a-11e5-98b5-5439dd0f58df.png)

The documents say "A button will only be keyboard focusable if you set the property <code>tabindex="0"</code>, or if you use a <code>&lt;button&gt;</code>."

So should it be this instead?
"A button will only be keyboard focusable if you set the attribute <code>tabindex</code>, or if you use a <code>&lt;button&gt;</code>."
<code>
/*--------------
      Focus
---------------*/
.ui.button:focus {
  background-color: '';
  color: rgba(0, 0, 0, 0.8);
  background-image: '' !important;
  box-shadow:0 0 0 1px transparent inset
}
button:focus, .ui.button[tabindex]:focus { box-shadow:0 0 0 1px transparent inset,0 0 1px rgba(81,167,232,.8)inset,0 0 3px 2px rgba(81,167,232,.8)!important }
</code>

Also, an option to opt out of the highlight for buttons too would be great.

**Comment by ImSanchez** [comment]
It seems that it was changed / fixed in 2.0.

**Comment by jlukic** [comment]
Focus colors have been improved in 2.0 for buttons.
