### ISSUE TITLE
[Form Validation] Add a float/double validation rule

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2438]
Hi,

Please shelf this until you are done with 2.0 release :)

I know there's `integer` validator available, but in my case almost all fields in the application are price/money fields and those sometimes need a floating point.  Maybe just add a `number` validator, which would accept all types of number.

Of course, meanwhile I can use regExp but what do you think?

**Comment by TonnyORG** [comment]
I was trying to find the way to validate floats today and found your issue, I just created a PR so I hope Semantic team could migrate it soon :)

**Comment by andreyvk** [comment]
Thanks @TonnyORG for the reponse. I've actually created a custom rule in `$.fn.form.settings.rules` instead :) I think it's neater this way

```
$.fn.form.settings.rules.number = function(value) {
    return value.match(/^([0-9]+)|([0-9]*(\.[0-9]+))?$/);
};
```

and now I can do: 

```
$(".ui.form").form({
    fields: {
        name: {
            identifier: 'name',
            rules: [
                 {type: 'number', prompt: 'Enter a valid number'}
            ]
        }
    }
});
```

Cheers!

**Comment by jlukic** [comment]
Number and decimal was already added
