### ISSUE TITLE
[Project] Add Test Coverage

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#244]
## Test Coverage

Will be integrating with Travis CI, and using [Karma](http://karma-runner.github.io/0.10/index.html) with [Jasmine](http://pivotal.github.io/jasmine/)

Tests are ready to go and can be added to `test/` 
## Tests

Will try to keep an active list of tests needing to be written here
### All Modules
- Instance exists in metadata after initialize is called
- Setting changes when adding default setting
- Setting changes when modifying setting after initialize
- Setting changes when modifying setting during initialize
- No events exist after destroy is called
- Changing setting for one element in a group does not change settings for other elements
### Modal
- Modal show programmatically occurs only once
- Modal hide programmatically occurs only once
- Modal attach events adds events to element
- Modal hides by simulated click on close
- Modal hides by simulated click on action
- Modal hides by simulated click on dimmer
- Modal doesnt hide when closable false on dimmer click
- Transition occurs exactly once on modal hide and modal show
- Transition occurs with correct parameters on hide and show

**Comment by listepo** [comment]
+1000

**Comment by listepo** [comment]
@jlukic any progress? do you need my help?

**Comment by dmitriz** [comment]
Help seems needed as tests appear rather empty.
