### ISSUE TITLE
[Dropdown] onChange doesn't fire if used with action: 'hide'

### ISSUE THREAD

**Issue by shatgupt** [Semantic-Org/Semantic-UI#2442]
I have a simple dropdown on icon and I dont want to have ```'.selected .active'``` on selection of the particular item, so I am simply using ```action: 'hide'```. I also want to do custom action on change, so I have onChange too as suggested here : http://beta.semantic-ui.com/modules/dropdown.html#specifying-select-action

But onChange is not firing. If i change to ```action: 'select'``` or remove ```action``` , it works.
Here is fiddle of my case: http://jsfiddle.net/v4b088th/

**Comment by jlukic** [comment]
Hide does not store values.

Use `action: 'select'`
http://jsfiddle.net/h3f6010r/

**Comment by shatgupt** [comment]
I dont want to have ```'.selected .active'``` on selection of the particular item, that is why I used ```hide```.
Anyways, if this is not supported then you should remove it from examples. This code is taken exactly from the last example as described here:  http://beta.semantic-ui.com/modules/dropdown.html#specifying-select-action
The above example led me to believe that this will work.

Also, for my particular case of having to take action on select, but not having the selection highlighted, what do you suggest? Should I use ```onclick``` on the item and just ```action: 'hide'``` on dropdown?
