### ISSUE TITLE
Button text color is the same of button background color

### ISSUE THREAD

**Issue by n3wtron** [Semantic-Org/Semantic-UI#2447]
changing theme.config setting button 'github' the css attribute color: of [color].button is the same of background color.

**Comment by n3wtron** [comment]
I've temporarly fixed it, modifying buttons.variables of github theme adding :
@greenTextColor: #FFFFFF;
@blueTextColor: #FFFFFF;
@blackTextColor: #FFFFFF;
@redTextColor: #FFFFFF;
@orangeTextColor: #FFFFFF;
@purpleTextColor: #FFFFFF;
@yellowTextColor: #FFFFFF;
@pinkTextColor: #FFFFFF;
@tealTextColor: #FFFFFF;

**Comment by jlukic** [comment]
Are you seeing this in beta? Looks fine after using theme selector
http://beta.semantic-ui.com/elements/button.html

**Comment by n3wtron** [comment]
If you want you can see the problema here https://asciinema.org/a/22345

**Comment by jlukic** [comment]
@n3wtron I believe this commit fixes your issue.
https://github.com/Semantic-Org/Semantic-UI/pull/2477#issuecomment-116934949
