### ISSUE TITLE
Internet Explorer slows (long running script alert) when render many items

### ISSUE THREAD

**Issue by maggX** [Semantic-Org/Semantic-UI#2450]
Hi, I´m using semantic-ui table. When I test my page in Internet Explorer, it slows a lot, the browser freezes and "long execution Script" warning appears. The same table and the same number of items (25 or more items) are rendered very fluid in other browsers like chrome and mozilla firefox (no freezes, no slow, all right).

In each row of the table I implement action buttons with semantic: toggle checkbox and buttons. It seems like the nested elements in rows are the reason of the poor performance in IE.

other libraries in my page:
- Knockout.js

Any Ideas to improve the performance in IE? Thanks in advance.

Here´s All the markup of my table, including the knockout data-bind attributes:

<table class="ui striped compact table" id="tblUsuarios">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Ap. Paterno</th>
                    <th>Ap. Materno</th>
                    <th>Usuario</th>
                    <th>Correo</th>
                    <th style="width:60px;">Estatus</th>
                    <th style="width:160px;">
                        
                        <div class="ui search">
                            <div class="ui icon input">
                                <input class="prompt" type="text" placeholder="buscar usuario..." data-bind="value: textoBuscarUsuario">
                                <i class="search icon"></i>
                            </div>
                            <div class="results"></div>
                        </div>    
                    </th>
                </tr>
            </thead>
            <tbody data-bind="foreach: UsuariosCollection">
                <tr>
                    <td data-bind="text: Nombre"></td>
                    <td data-bind="text:ApellidoPaterno"></td>
                    <td data-bind="text:ApellidoMaterno"></td>
                    <td data-bind="text: UserName"></td>
                    <td data-bind="text: Email"></td>
                    <td data-bind="css: { positive: Activo(), negative: !Activo() }">
                        <div class="field" data-bind="click: $parent.HabilitarDeshabilitarUsuario">
                            <div class="ui fitted toggle checkbox">
                                <input type="checkbox" data-bind="value: Activo, checked: Activo">
                                <label></label>
                            </div>
                        </div>      
                    </td>
                    <td>
                        <div class="ui icon buttons">
                            <div class="ui mini icon button" title="Editar Usuario"
                                 data-bind="click: $parent._EditarUsuario">
                                <i class="write icon"></i>
                            </div>

                            <div class="ui mini icon button" title="Resetear Contraseña"
                                 data-bind="click: $parent.AbrirPopupResetearContraseña, visible: Activo()">
                                <i class="repeat icon"></i>
                            </div>
                        </div>
                    </td>

                </tr>
            </tbody>
            <tfoot></tfoot>
        </table>

**Comment by jlukic** [comment]
If you are using our tables its just css. Most likely the performance issues are in your application logic. 

I'd recommend using internet explorer's debugger tools and 'profile' mode.
