### ISSUE TITLE
animate the parent

### ISSUE THREAD

**Issue by nor-bu** [Semantic-Org/Semantic-UI#2451]
hi semantic team,

i have a segment with date and locations infos inside and inside this segment a details button.
when i animate the details container inside the segment works fine. but the parent element (the segment), is jump to the new state.

how can i animated the parent also?

i love semantic ui!!!

thanks for help

**Comment by jlukic** [comment]
You can use two separate calls to `transition()` to specify if you want an element and its parent to animate.
