### ISSUE TITLE
(next) gulp build fails because missing peerDependencies

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#2453]
I installed the next branch with `npm install --save semantic-org/semantic-ui#next`
After the installation with the default/automatic values, did a `cd semantic && gulp build` but it fails because it can't find the `map-stream` and `yamljs`modules.

Just depending on them explicitly lets the build to succeed. Probably the peerDependencies section in the package.json needs to be updated.

You can see the process [here] (https://asciinema.org/a/dindrc72jkyomrqvuyvj706vc)

**Comment by jlukic** [comment]
I've reproduced these errors. I'm looking into it now.

**Comment by jlukic** [comment]
Adding to peerDeps resolved the issue. To be honest I'm not sure where those dependencies got introduced.. but I dont really have the time to look into it now.
