### ISSUE TITLE
(next) Tab switching fails when data-tab contains uppercase characters

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#2455]
See [this fiddle] (http://jsfiddle.net/trigoesrodrigo/u4y3rof5/2/).
It was working before 2.0. Is this new expected behaviour, or is it a bug?

**Comment by hrstoyanov** [comment]
I have the same issue after switching to next - tabs stopped working

**Comment by jlukic** [comment]
Will fix today. The matching should be case insensitive. Right now its just lowercasing one part of the match.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/commit/98de07d98c379c5fd160e0ff0cbf6bf555113f7e

**Comment by jlukic** [comment]
So attribute filters used internally are all case-sensitive. 

Rather than add complexity by having to adjust each call to a filter function (there's a half dozen references internally), I'm going to remove the enhancement and keep tabs case sensitive.

**Comment by BigGrecian** [comment]
The tab change will now work also if you are using AJAX tabs and your tab name is a file such as "statement.php"  for exampe if I try and use ''''$.tab('change tab', 'statement.php');'''' the console will return "undefined"  If the ".php" is missing it works fine.  For practical purposes though a lot of my tabs are in .php files so the only way I can fire them is by clicking a link which is annoying as I can't control the tab without user input.
