### ISSUE TITLE
Vertical Tabs have incorrect border radius.

### ISSUE THREAD

**Issue by thinksaydo** [Semantic-Org/Semantic-UI#2456]
If you look at the what's new in 2.0 page, you'll see the vertical tabs have a border radius on the top left and top right, instead of the top left and bottom left. Picking up the wrong style from a parent class.

http://beta.semantic-ui.com/introduction/new.html#vertical-tabs

**Comment by jlukic** [comment]
My kingdom for a css specificity property that acted like z-index.
