### ISSUE TITLE
(next) checkbox label-input order causes toggle not to work

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#2457]
If the order of the input and label inside a checkbox is input first, label second (just like in the docs) everything works as expected. However, if the order is switched, the checkbox appearance doesn't change when toggling the control. In 1.x it was working both ways, so if this behavior is intended, then people (like me) might find their websites breaking. 

See [fiddle] (http://jsfiddle.net/trigoesrodrigo/fbwr7kj4/1/)

**Comment by jlukic** [comment]
This was a straight up bug. `create labels` was failing to pick up elements initialized this way.
