### ISSUE TITLE
Icons don't work

### ISSUE THREAD

**Issue by bw2** [Semantic-Org/Semantic-UI#2458]
I can see the icons on the demo page:
http://semantic-ui.com/elements/icon.html

but on my site none of the icons work when I add, for example:
```<i class="github icon"></i>```

I followed the build instructions at
http://learnsemantic.com/guide/expert.html
and then copied `semantic.css` and `semantic.js` from the `dist` folder into my site so that this works:
```
<link rel="stylesheet" href="/static/css/semantic.css" />
<script type="text/javascript" src="/static/js/semantic.js"></script>
```
Based on Issue #1405, it seems there are other files I need to copy from `dist`, but I'm not sure which.

**Comment by jlukic** [comment]
Custom fonts won't load from local filesystem in some browsers due to file security issues.

**Comment by miniskulljob** [comment]
You have to copy the `themes` folder in `dist` to the same path where you've put `semantic.css`.

**Comment by bw2** [comment]
Thanks. That fixed it.
