### ISSUE TITLE
borderless menu has borders, but not for items

### ISSUE THREAD

**Issue by fvpDev** [Semantic-Org/Semantic-UI#2459]
Checked the example menu and it looks like the element is not inheriting the borderless class at all. Just uses ".ui.menu"

http://beta.semantic-ui.com/collections/menu.html#borderless

In fact, I can't even find on that page how the dividing borders are there for each menu item... The "computed" styles in the Firefox inspector reveals 0px border-width all the way around for the bordered menu items, so...

How did you do it? :D

**Comment by celsworth** [comment]
Look at the `background` property of the `::before` pseudo-element :)

**Comment by fvpDev** [comment]
*facepalm
