### ISSUE TITLE
[UI] Generators

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#246]
## Generator

Generator is a UI behavior for creating UI element stubs from a templated version of the element, This would be a stand alone component and not required for usage with any other module, but can be used along-side it as an enhancement.
## Syntax Ideas

``` javascript
$
  .generate({
    element: 'modal',
    data: {
      title       : 'A question',
      image       : 'http://whatever.jpg',
      description : 'Would you like to do that?'
      yes         : 'Ok',
      no          : 'Cancel'
    }
  })
  .modal()
;
```
### Required for 2.0
- Decide on template format (Handlebars?)
- Generator has a template definition for each major UI component that allows for creation of element

**Comment by ivantcholakov** [comment]
Related: Alert/Confirm/Prompt #241
