### ISSUE TITLE
base  Alert UI   and  layout  ?

### ISSUE THREAD

**Issue by raymondZhong** [Semantic-Org/Semantic-UI#2461]
![2015-06-25_131909](https://cloud.githubusercontent.com/assets/1297621/8347760/ea6931c8-1b3c-11e5-82fd-14c1ea05d62f.png)

Don't have  the  layout?
AND

We need  base  Alert UI !

**Comment by jlukic** [comment]
We have a growl/notification system as a flagged enhancement. #1430 

I understand the need for resizable panes, but in my (humble) opinion, i think this design pattern is on its way out. Most modern web apps use fixed panels. I'm sure it still fits some use-cases, but for me its a low priority.

**Comment by lubber-de** [comment]
Regarding the suggested "Alert UI": A Toast Component available since Fomantic UI 2.6 https://fomantic-ui.com/modules/toast.html
