### ISSUE TITLE
dropdown menu items ignore keypress events

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2462]
`click` event works, `keypress `- doesnt
http://codepen.io/avalanche1/pen/LVpxdO

**Comment by jlukic** [comment]
Keypress doesnt work on divs without tabindex. 
http://stackoverflow.com/questions/3149362/capture-key-press-or-keydown-event-on-div-element

**Comment by avalanche1** [comment]
I don't agree this has to do with tabindex (i've update my codepen to demonstrate).
I think key events aren't caught because SUI somehow overrides them with own event catcher, like [here] (https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L534-L555).
So, the question is: *how can I hook my own keypress events (namely up & down arrows) to dropdown menu items without hacking into SUI code?*

**Comment by jlukic** [comment]
Menu items don't get focus so they do not receive any keydown input. The dropdown is the focused element when opened. You would need to use `tabindex="0"`, but even in this case the dropdown will close on blur.

If you need keyboard shortcuts, capture the keydown event on the dropdown, or on the page then either check `event.target` or your page state to determine what the user was doing. This is similar to what is being done internally.

**Comment by avalanche1** [comment]
Thanks, ended up doing like you suggested)

**Comment by gilperon** [comment]
Sorry for bringing this up but I am still facing the problem related in this post; I have a modal window with 2 buttons. I already configured tabindex="0" and I can tab across the buttons but if I press ENTER or SPACE the browser does nothing... it should simulate a click event on the button. How to solve this problem?

**Comment by avalanche1** [comment]
```coffee
$(btn).on 'keypress', (event)->
  #if clicked\pressed LMB, space, enter
  if  if event.which is 1 or event.which is 32 or event.which is 13
    doYourThang()
```

**Comment by gilperon** [comment]
Yeah, I already did that... but not good approach since every other UI on the internet has this usability issue solved.
