### ISSUE TITLE
Cannot use custom grid size with Manual Tweak column sizes?

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2465]
At the bottom of the grid documentation, there's a section about "Manual Tweaks". This works great if you stick with the default sixteen wide column, but not if you need to change the number of columns in the grid.

In my case, I need 3 columns on computer, 2 columns on tablet, and one on mobile, so the obvious solution is a six wide grid. I did try doubling but that goes from 3 to 2 to 2, so not quite right.

See this fiddle, hopefully it helps explain: http://jsfiddle.net/tjdeq5ab/1/

The closest I can get unfortunately wastes one column width on computer (3*5=15 used)

Is this a bug, should manually tweaking column widths work inside a custom sized grid? Could it be made to do so?

Hope this is clear, let me know if I can explain better.

**Comment by celsworth** [comment]
Alright, actually found a solution for 3-2-1, add `stackable` to force the 1 column on mobile. Not sure if this would still make a useful feature request for other usage cases.

**Comment by jlukic** [comment]
Some `doubling variations` that are small column count prefer two on mobile because stackable can always force one column.

**Comment by celsworth** [comment]
Yeah, thats understandable. Unless anyone can see a pressing need to support manual tweaks on a grid size other than sixteen columns, please feel free to close this :)
