### ISSUE TITLE
[Progress] - Issues with Increment and Values Lower than 1%

### ISSUE THREAD

**Issue by emil-nasso** [Semantic-Org/Semantic-UI#2466]
I have reproduced the bug in this fiddle: http://jsfiddle.net/r81er1Lt/1/
It's basically an copy of the example called "custom labels" on this page: http://semantic-ui.com/modules/progress.html#/usage , but with an increased data-total.

If i set the data-target to 100 or below, i get the expected results, i get one uploaded image per click on the button. If i set it to 101 or above, the first click increments the value by 100 and every subsequent click increments it by one.

**Comment by emil-nasso** [comment]
I think i found the issue.

First, increment is called:
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/progress.js#L122

This calls `module.set.progress(1)` as argument, as that is the new value.

The function converts it to a percentage here:
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/progress.js#L520
`percentComplete = (1/200)* 100`
So `percentComplete = 0.5` in this case.

Next `module.set.percent(0.5)` is called.
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/progress.js#L350

And here we have the issue:
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/progress.js#L355

As the percentage is `0.5%` but is < 1, it is converted to 50%.

A fix would be to add a check here:

https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/progress.js#L520
```javascript
percentComplete = (numericValue / module.total) * 100;
if(percentComplete < 1) {
  percentComplete = 1;
}
```

Kind of an ugly hack though. But i'm not sure how you could fix it without breaking backwards compatibility/functionality, as begin able to call `percent(50)` and `percent(0.5)` and getting the same result would still be wanted.

**Comment by jlukic** [comment]
Thanks for making this issue crystal clear, I'll add a fix today for Tuesday's 2.0 launch.

**Comment by jlukic** [comment]
There was a lot in there that needed to be cleaned up. Haven't looked over the code in a while. 

Fiddle from next release
http://jsfiddle.net/n45pg1jd/

**Comment by vsn4ik** [comment]
Progressbar on jsfiddle (http://jsfiddle.net/n45pg1jd/) example not changes after 100 clicks.

Reproduce:
1. Append to JS section and click "Run".
```
for (var i = 0; i < 99; i++) {
$('#thebutton').trigger('click');
}
```
2. Two click on button.

**Comment by jlukic** [comment]
Thanks, 0day bugs...
