### ISSUE TITLE
[Grid] Grids that are not container grid receive spacing on mobile

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2467]
Hi, me again with the grids ;) I made a new issue for this rather than piggyback the other one which can probably be closed.

So I've adopted the `three column doubling stackable ui grid` as mentioned before. This works, but there's some odd padding issues that I don't think should happen:

This is fine, computer width:
![](https://i.imgur.com/BGygSed.png)

Tablet width has padding on the right which makes things look odd and wastes some space:
![](https://i.imgur.com/PbGklsy.png)

Mobile width has padding on both sides :(
![](https://i.imgur.com/63A6STg.png)

Any way to prevent this, or is it a bug?

http://jsfiddle.net/14ypo70q/3/

**Comment by celsworth** [comment]
So, there seems to be two issues at play here..

For the tablet, this piece of CSS seems to be artificially limiting the width, taking into account the negative margins I don't think 100% wide is wide enough? Removing this fixes the tablet case but I don't know what else it might break:

```css
.ui.doubling.grid {
  width: 100% !important;
}
```

For the mobile case, it seems to be the padding on the columns, but I don't know if setting `padding-left` and `padding-right` to zero on mobile on a stackable grid will break anything else either.

**Comment by jlukic** [comment]
There's still some issues here with stackable and doubling due to rules that were left over from before the grid were flex. Lots of fixes coming.  Sorry it takes me some time to circle back without a good reminder. 

I'll be adding a new example layout with responsive patterns from all UI. Will link in this thread when done.

**Comment by jlukic** [comment]
Fixed your case and some others

New responsive examples in docs
http://beta.semantic-ui.com/examples/responsive.html

**Comment by celsworth** [comment]
Looks good, thanks! :)

**Comment by celsworth** [comment]
I'm not sure if it was this change or something after, but the basic stackable case seems to have broken:

http://jsfiddle.net/8ohLf5jg/1/

This no longer stacks at mobile width. Seems to be the `width: .. !important` on the `three column wide` class.

**Comment by jlukic** [comment]
Refixed
