### ISSUE TITLE
Dimmer animation gets stuck

### ISSUE THREAD

**Issue by awishformore** [Semantic-Org/Semantic-UI#2469]
On the latest beta, I had an issue with an image that dims on hover. The image would sometimes remain stuck in the dimmed state, with further mouse hovers doing nothing.

I was able to reliably reproduce the problem by *very* quickly moving the mouse across the picture several times.

The JS of Semantic UI bugs out at line 16972:

    return module.cache.animation || false;

The message:

    Uncaught TypeError: Cannot read property 'animation' of undefined

I didn't dig into the code, but adding the following to the currentAnimation function seems to solve the issue:

```
if (module.cache === undefined) {
    return false
}
```

**Comment by startswithaj** [comment]
+1 get this same problem

**Comment by jlukic** [comment]
I'll look at this tomorrow.

**Comment by jlukic** [comment]
I've gone ahead and fixed the JS error. I don't have a reproducible test case so closing for now.
