### ISSUE TITLE
Theme.less uses @type and @element error undefined

### ISSUE THREAD

**Issue by stunjiturner** [Semantic-Org/Semantic-UI#2470]
In the theme.config i do not @type and @element set any where, but i see that each individual less file describes and sets @type and @element in /src folders for definitions, etc. So why am i getting the the Error Below:

LESS Name error : variable @type is undefined
  LESS File : /Users/sturner/sightuary/groups/works+labs/dd/MochaProjects/Javascript/Keystonejs/seekeystone/public/styles/semantic-ui-less/theme.less 12:8
Name Error thrown for request: /styles/site.min.css
{ [Error: variable @type is undefined]
  type: 'Name',
  filename: '/Users/sturner/sightuary/groups/works+labs/dd/MochaProjects/Javascript/Keystonejs/seekeystone/public/styles/semantic-ui-less/theme.less',
  index: 242,
  line: 12,
  callLine: NaN,
  callExtract: undefined,
  column: 8,
  extract: 
   [ '@import "@{themesFolder}/default/globals/site.variables";',
     '@import "@{themesFolder}/default/@{type}s/@{element}.variables";',
     '' ],
  message: 'variable @type is undefined',
  stack: undefined }

**Comment by jlukic** [comment]
theme.less is included from a `src/definition/` file. This is the entry point to the library. See [semantic.less](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/semantic.less)
