### ISSUE TITLE
[Segment] inverted segment doesn't inherit white text colour for everything?

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2471]
Messing about with an inverted segment, I noticed that some things don't inherit the new default whilte colour - should they?

![](https://i.imgur.com/WkKW0kI.png)

These are the only ones I've found so far. For the statistic I can invert it as well, but I don't see a way to fix the sub header to be white.

Fiddle: http://jsfiddle.net/u6c43nya/1/

**Comment by jlukic** [comment]
Each element has its own inverted variation. Currently you will need to specify this variation even if the element is nested. 
http://jsfiddle.net/dufgjsfw/

**Comment by celsworth** [comment]
Thanks, so long as that is the intended result, that works for me :)
