### ISSUE TITLE
[Beta] Problem centering cards without fluid

### ISSUE THREAD

**Issue by awishformore** [Semantic-Org/Semantic-UI#2472]
I have run into a very frustrating issue when trying to center cards. You can reproduce with this code:

```
<main class="ui three column centered relaxed grid container">
	<div class="column">
		<div class="ui card">
			<div class="image">
				<img src="image.png">
			</div>
		</div>
	</div>
	<div class="column">
		<div class="ui card">
			<div class="image">
				<img src="image.png">
			</div>
		</div>
	</div>
	<div class="column">
		<div class="ui card">
			<div class="image">
				<img src="image.png">
			</div>
		</div>
	</div>
</main>
```

To my understanding, the centered attribute on the grid container should make the columns center their content. As you can see on the first screenshot, this is not the case:

![cards1](https://cloud.githubusercontent.com/assets/3630494/8396698/75d76614-1db1-11e5-885a-4e0a5f02fde2.png)

The space on the left is smaller than the space on the right, which led me to believe that the columns were still left aligning their content. On closer inspection, though, it turns out that they actually do center it:

![cards3](https://cloud.githubusercontent.com/assets/3630494/8396704/9bc0573c-1db1-11e5-91ca-2a4c79a17b23.png)

As you can see, the columns center their content. The issue seems to be that the card takes up the whole space, but inside the card itself, the content is placed on the left, leaving the remaining space on the right to stay empty. This is even more visible when you check the card div:

![cards2](https://cloud.githubusercontent.com/assets/3630494/8396706/c38f1532-1db1-11e5-9126-cb5be7afd223.png)

As you can see, the card div takes up the available space as if it was fluid, but it will not fill its entire space with the content, leaving the empty space and causing the columns to appear not centered.

I think it should be possible to center the content inside the orange card element. However, I have not yet found a way to do so. This leads to a very ugly experience with stackable grids on mobiles. Cards will be displayed one per line, on the very left side, with a lot of empty space on the right.

**Comment by awishformore** [comment]
After understanding the issue better, I looked into the CSS and managed to fix my issue.

I changed this:

```
.ui.card {
  margin: 1em 0em;
}
```

To this:

```
.ui.card {
  margin: 1em auto;
}
```

I'm not a CSS expert, so I'm not sure if this won't break something in some browser or under some circumstances.

**Comment by jlukic** [comment]
You can use a `fluid card` to expand the cards to the width of the columns.

Centered columns align center themselves amongst over columns but do not change column content positioning.

**Comment by awishformore** [comment]
I'm aware of the fluid property. However, when using fluid cards, they turn out too big in certain configurations, i.e. on mobile. I don't want a card to take up the entire width on mobile when the cells are stacked. I also prefer having more space between cards in the widest configuration.

What if I want to center a card's contents in a grid cell without having it take up the whole cell? It does not seem possible at the moment. Why do card divs take up more space than they need for their contents? Why do they align their contents to the left of this space?

If you check out my screenshots, I don't think this particular case has to do with the column's content, but rather with the card's content. The column cells seem to be centered just fine. It's the inside of the card that seems to be off.

**Comment by jlukic** [comment]
I'm adding a `centered card` variation. This should handle your case.

You have to keep in mind semantic is based of CSS layout, so we're limited to the kludgy system which these layout principles are inherited in css.

**Comment by awishformore** [comment]
That seems sensible. I actually tried using it, but it didn't work and I obviously didn't find it in the variations of the card documentation either. Great to see it so quickly solved/added. Cheers.

**Comment by xalcolm1** [comment]
Hi Im having this exact same issue , and I tried all of what you have posted here with no luck, Im curious if you ever found a solution
