### ISSUE TITLE
Add item dynamic, how to load checkbox() ?

### ISSUE THREAD

**Issue by youyi1314** [Semantic-Org/Semantic-UI#2473]
As title, how do i keep class .checkbox load checkbox() for the div i just append by jquery dynamically?

Thanks

**Comment by jlukic** [comment]
Just call `$('.ui.checkbox').checkbox()`

**Comment by youyi1314** [comment]
Hi, i try but not work or i'm wrong?

$('.segments .home.feed').prepend($(response.html).hide().fadeIn('slow'));
$('.ui.checkbox').checkbox();

it not work after prepend. or any idea?

**Comment by arthurlacoste** [comment]
A simple example with a DOM change (like adding html to a id) : 

```js
$(document).on('DOMSubtreeModified', '#listitems', function () {
  $('.ui.checkbox').checkbox();
});
```
This need to be more documented, isn't ?

**Comment by lukvaratskhelia** [comment]
Will calling the `$('.ui.checkbox').checkbox();` many times (like 20 or more) affect the page performance?
