### ISSUE TITLE
[Popup] Does not show in some cases when popup specified in settings

### ISSUE THREAD

**Issue by quentinlampin** [Semantic-Org/Semantic-UI#2474]
I just stumbled upon this bug when trying to add popups to elements inside a sidebar. 
In short, as exemplified by this fiddle : https://jsfiddle.net/tyhgxvLn/1/ , adding a popup to an element inside a sidebar using the `popup:selector` options does not work.

While browsing github for related issues, I've noticed that the fiddle.js proposed in #1641 by @jlukic  ( http://jsfiddle.net/L1mc8prw/ ) exhibits the same behaviour/bug.

**Comment by quentinlampin** [comment]
Hey, a little update on that issue. It appears that:
when `settings.popup` is defined and when the parent of the popup is different from the activator parent (https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js#L6623-6627) then the popup is moved to the parent of the activator. In this case : the sidebar which has the overflow:hidden property, hence the popup not showing up. 

It'd be great if that behaviour could be documented in here (http://semantic-ui.com/modules/popup.html#/usage)

Also, I now understand the reason for the need of a  `movePopup` setting. Among other reasons, it provides a way to define (implicitly) the parent of the popup element and therefore to avoid styling issues inherited from the activator's parent. 

Still, if I may, I find the behaviour inconsistent with the default behaviour (using `$body`).
Would it be possible to enforce the default behaviour, i.e. move the popup element to `$body` unless `settings.context` is set to another element, or eventually a more explicit setting, i.e. `popupParent` that would let us defines which parent to use?

Anyways, I'm unsure it stills qualifies as a bug, thoughts?

**Comment by quentinlampin** [comment]
here is an attempt to address the "inconsistency"  mentioned earlier : https://github.com/quentinlampin/Semantic-UI/commit/528d33f36667d03049e0ed88877b431974e8f3f5

**Comment by jlukic** [comment]
I haven't had a chance to evaluate any of this.

**Comment by jlukic** [comment]
@quentinlampin I can help explain here

> when settings.popup is defined and when the parent of the popup is different from the activator parent (https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js#L6623-6627) then the popup is moved to the parent of the activator. In this case : the sidebar which has the overflow:hidden property, hence the popup not showing up.

If an element has a 3d transform context (like an open sidebar) it will act as an `offsetParent` for returned co-ordinate offsets, but is not returned by `.offsetParent()`. This is due to an issue with w3c spec related to whether 3d transform contexts should be used for positioning context 

From the [2d spec](http://www.w3.org/TR/2011/WD-css3-2d-transforms-20111215/)
```
Any value other than ‘none’ for the transform results in the creation of both a stacking context and a containing block
``

Unfortunately IE (seemingly correctly) is the only browser who does not create a stacking context (since its a bit absurd) despite the nature of the spec. So what we have to [look for an offset context](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/popup.js#L565) manually and then move any pre-existing popup to the same context to avoid issues with positioning.

**Comment by philrykoff** [comment]
This can be closed, as it seems to be working now. No issues here when trying the JSFiddle mentioned above to be erroneous (http://jsfiddle.net/L1mc8prw/).

**Comment by jlukic** [comment]
Thanks @philrykoff
