### ISSUE TITLE
[UI Suggestion] A 'blur-able' directive just like the dimmable

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#2475]
Just like a dimmed background when popping out modal. Maybe we could have a `blurable` to create a blurred view (e.g., the login page on www.icloud.com)?

Not a high priority but would be cool to have.

**Comment by jlukic** [comment]
There are blurring dimmer in 2.0
http://beta.semantic-ui.com/modules/dimmer.html#blurring
