### ISSUE TITLE
[UI Suggestion] Rounded buttons

### ISSUE THREAD

**Issue by Paklausk** [Semantic-Org/Semantic-UI#2476]
I know S-UI has rectangular and round buttons, but in my personal opinion it should also have rounded buttons.

I think it would be great for S-UI 2.0 to have native implementation of beautiful rounded buttons, because it's one of few must have things for UI oriented frameworks, for example paging looks really great with rounded buttons at the corners.

Example url: http://1.bp.blogspot.com/-VPHXCnhqCoE/VUhxJKV5akI/AAAAAAAAHkw/aDSyCuLc4nw/s1600/round%2Bcornered%2Bbutton%2Busing%2Bbootstrap%2Bwith%2Bicons.jpg

**Comment by jlukic** [comment]
This can be done fairly simply with user theming very easily in current SUI and 2.0
