### ISSUE TITLE
a faceted searchbox   with semantic

### ISSUE THREAD

**Issue by mikeatm** [Semantic-Org/Semantic-UI#2478]
How easy would it be to create a faceted searchbox with  semantic (kind of like  visualsearch.js from documentcloud?), is this something that could be useful  to others? 
I need some pointers on where to look to make this happen.

**Comment by jlukic** [comment]
Although we have some pretty complex search controls, there's nothing like that currently. You could probably rig something with [search](http://beta.semantic-ui.com/modules/search.html) though if you had some time.

**Comment by mikeatm** [comment]
I would like to look into that, if you have some specific  advice on how to approach that, it would be nice
