### ISSUE TITLE
Sticky row in AngularJs table

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#2480]
When I call sticky with function on click in angular I get:
Sticky: Element is hidden, you must call refresh after element becomes visible [td.ui.sticky, context: td.ui.sticky]
for every single element which has a class of sticky.
How to fix that?

**Comment by jlukic** [comment]
Sticky content does not support tables.

**Comment by TeodorKolev** [comment]
gj

**Comment by SimonVuong** [comment]
if sticky content does not support tables, what is the following mean inside the sticky doc?

"Sticky does not work in tables without using table-layout: fixed to prevent automatic resizing with content"
