### ISSUE TITLE
little decalage between tab and content (when using two.item.tabular.menu)

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#2482]
http://jsfiddle.net/23xop67n/1/

![capture d ecran 2015-06-30 a 16 08 18](https://cloud.githubusercontent.com/assets/359847/8432797/66df5120-1f42-11e5-8697-5b4c4e45f7e3.png)
![capture d ecran 2015-06-30 a 16 08 10](https://cloud.githubusercontent.com/assets/359847/8432798/66e6707c-1f42-11e5-9aac-9057121479d5.png)

**Comment by jlukic** [comment]
Already fixed in `2.0`, see ya at the end of the day :)
http://jsfiddle.net/9zy2yn0m/
