### ISSUE TITLE
website - 1.0 docs unavailable 

### ISSUE THREAD

**Issue by BillyParadise** [Semantic-Org/Semantic-UI#2484]
Congrats for the release, but I need access to the 1.0 docs. Am I just hitting the site at a bad time (during your release?) or did you neglect to move legacy to alpha and 1.0 to legacy?

I'd love to update to 2.0 but will have to wait for the rails gem to be updated (yes there are still some rails people out here) :+1: 

Congrats again, I can't wait to try out the new stuff.

**Comment by jlukic** [comment]
See #2485, later this week

**Comment by BillyParadise** [comment]
Wah, mine was first ;)

Keep up the awesome work.
