### ISSUE TITLE
[Docs] Add 1.x Docs

### ISSUE THREAD

**Issue by KhadeerMojostreet** [Semantic-Org/Semantic-UI#2485]
Hi @jlukic

Now your using semantic-ui 2.0.0 but i am developed my website(www.truesemantic.com) in semantic-ui 1.7.3 please add that page on your site look likes legacy docs. Please i want that documents pages.

**Comment by KapuzenSohn** [comment]
Maybe you should think about updating? I mean version 1.7.3 is from the beginning of the year, and since them there where some updates and many improvements

**Comment by jlukic** [comment]
Legacy docs will be up in the next couple of days. I have to manage some launch tasks, but it's on my list. 

In the meantime, have you thought about downgrading to Semantic UI 0.x? http://legacy.semantic-ui.com/ :dancers:  jk

**Comment by KhadeerMojostreet** [comment]
Hi @jlukic
When i am added new css that is semantic 2.0.0. some issues are coming. I am used semantic 1.7.3.
How to update old css and new css and js? I am add new css on my website i.e (www.truesemantic.com) header layout is gone, so how to fix. And you maintain old version website semantic 0.93 i.e. legacy docs, so same as maintain another version semantic 1.7.3 docs website.

**Comment by jlukic** [comment]
Yes, see above comment. I'm a bit swamped the next couple of days with important launch tasks. But I will rehost legacy documentation soon.

**Comment by kfei** [comment]
+1 for this.

**Comment by BillyParadise** [comment]
For those left in limbo, might I suggest archive.org

http://web.archive.org/web/20150618045443/http://semantic-ui.com/ seems to be the last snapshot before 2.0

**Comment by jlukic** [comment]
I've hosted 1.0 docs, just waiting for subdomain DNS to replicate
http://1.semantic-ui.com/

**Comment by jlukic** [comment]
DNS is now up, links are now fixed in docs. All is a go!

**Comment by KhadeerMojostreet** [comment]
Thank you @jlukic
