### ISSUE TITLE
Labeled input size issues

### ISSUE THREAD

**Issue by CakalSG** [Semantic-Org/Semantic-UI#2486]
Hi,

input size (mini,small, ...) very nice.

But labeled input size not same. input and label not same ratio.

Example: http://jsfiddle.net/cakal/03u8gg5L/1/

<div class="ui mini right labeled input">
    <input type="text" placeholder="Search mini..." /> <div class="ui label">http://</div>
</div>

inspect element and 

.ui.labeled.input>.label {
  -webkit-box-flex: 0;
  -webkit-flex: 0 0 auto;
  -ms-flex: 0 0 auto;
  flex: 0 0 auto;
  margin: 0;
  /* font-size: 1rem; */ -->> uncheck

.ui.big.label, .ui.big.labels .label, .ui.huge.label, .ui.huge.labels .label, .ui.label, .ui.labels .label, .ui.large.label, .ui.large.labels .label, .ui.massive.label, .ui.massive.labels .label {
  /* font-size: .85714286rem; */ ------> uncheck

.ui.mini.input {
  font-size: .71428571em; --> check 

good result

**Comment by jlukic** [comment]
Fixed with `font-size: inherit`. I'll add in first patch

```css
.ui.labeled.input>.label {
  font-size: inherit;
}
```

**Comment by kylerm42** [comment]
It seems that labels themselves are having a similar issue. Medium, large, big, huge, and massive are all the same size: http://semantic-ui.com/elements/label.html#size

**Comment by jlukic** [comment]
Found the culprit. Can you spot the error? :laughing: 
```less
/* Sizing */
@mini    : @9px;
@tiny    : @10px;
@small   : @11px;
@medium  : @12px;
@large   : @medium;
@big     : @large;
@huge    : @big;
@massive : @huge;
```
