### ISSUE TITLE
form field margin

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2487]
Is it by design https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/form.less#L52 has `.ui.form .field .field` instead of `.ui.form .field`?
This messes up my layout somewhat..

**Comment by miniskulljob** [comment]
Looks like a typo, it should be `.ui.form .fields .field` or `.ui.form .field` like you said.

**Comment by jlukic** [comment]
I'm not sure.. yet.. whether it was intentional or not. Will visit

**Comment by jlukic** [comment]
I don't see any downsides to removing. I think there was a use-case where multiple `fields` receive same label, for example [name in first example](http://www.semantic-ui.com/collections/form.html#form) but this should be fine since `fields field` handles the margin effectively.

**Comment by avalanche1** [comment]
yep, me thinks so as well)
