### ISSUE TITLE
ui button: <button> and <a> vertical alignment issues when font-size != 14px

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2489]
http://jsfiddle.net/n7noj48p/embedded/result/

Depending on your config, one of the button can be off one vertical pixel.

I do not understand what's happening.
Using a different vertical-align for .ui.button (say, middle instead of baseline) make
the buttons aligned again.

**Comment by kapouer** [comment]
It's weird. If i open the link they are aligned. If i resize the window it doesn't change. If i maximize the window the first button is off one pixel.

**Comment by jlukic** [comment]
imho `<button>` tags are the work of the devil in terms of browser idiosyncrasies. The worst bit is the focus styles getting stuck on click.. 

I'm not sure what's going on but I'd look into it if anyone has any ideas.

**Comment by kapouer** [comment]
More weirdness
```
/* aligned buttons */
.ui.button {line-height: 0.9999999em;}
/* bug */
.ui.button {line-height: 0.99999999em;}
```

**Comment by kapouer** [comment]
At least it has some kind of predictable behavior, see my experiments with
http://jsfiddle.net/n7noj48p/2/

I set vertical-align top to button.ui.button only if it has some neighbors.

**Comment by jlukic** [comment]
One thing I've noticed about vertical-align is that when you think you're solving it in one case, it usually breaks another. Even further down the page with the exact same code. I'm struggling with this as well with multiple select dropdowns.

**Comment by jlukic** [comment]
Closed until a better solution arises
