### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by tcigrand** [Semantic-Org/Semantic-UI#2490]
I'm getting a 404 at http://semantic-ui.com/

![semantic-ui](https://cloud.githubusercontent.com/assets/1585301/8463246/17e2d59c-1ff6-11e5-904c-aa68726d5034.png)

**Comment by schisma** [comment]
same

**Comment by jlukic** [comment]
Back up `cname` was set to `beta.semantic-ui.com` broke build
