### ISSUE TITLE
[Menu] - old active menu style seen in semantic 2.0

### ISSUE THREAD

**Issue by DavodOsanlo** [Semantic-Org/Semantic-UI#2491]
in new semantic changes in some element , for example menu , in the old menu we have seen a border on top of active menu , in new semantic release doc changes this design and is good , but i test any menu and old design still worked for menu 

however i test this in the new project and installing new release for this project

this screenshot as this bug

![capture](https://cloud.githubusercontent.com/assets/10121643/8465338/97b5b09c-205e-11e5-961d-f028d5f5606c.JPG)

**Comment by jlukic** [comment]
You shouldn't be seeing the active border in 2.0. There's just no code for it.

**Comment by DavodOsanlo** [comment]
hi Jack 
i test it again and re-install semantic , in this test everything is fine 
maybe my localhost cache it
good luck bro
