### ISSUE TITLE
AJAX Tabs  in 2.0

### ISSUE THREAD

**Issue by BigGrecian** [Semantic-Org/Semantic-UI#2493]
The loader has disappeared in version 2.0 and no longer displays whilst an ajax tab is being processed and sent by the server.

**Comment by jlukic** [comment]
Please create a test case. Perhaps its just loading too quickly :). 

AJAX tabs in 2.0 use session storage, which means if you have already loaded a tab once in a browser session it will reload instantly the next time.

**Comment by BigGrecian** [comment]
Surely if the code is  as follows it shouldn't cache : 
````$('.fixed.home.menu .item')
  .tab({
    context : 'parent',
    auto    : true,
	alwaysRefresh : true,
	parseScripts : true,
	ignoreFirstLoad  : true,
	cache : false,
    path    : './',	
	
 });````

**Comment by jlukic** [comment]
Top level cache setting is not currently passing api settings correctly. 

For now you can use
```javascript
$('.fixed.home.menu .item')
  .tab({
    context : 'parent',
    auto    : true,
    alwaysRefresh : true,
    parseScripts : true,
    ignoreFirstLoad  : false,
    apiSettings: {
      cache: false
    },
    path    : './', 
 });
```

Will fix.

**Comment by BigGrecian** [comment]
Already tried that, unfortunately with no avail :
![image](https://cloud.githubusercontent.com/assets/12722365/8490652/346f5866-20fa-11e5-9a4c-be26f76a3e95.png)

**Comment by jlukic** [comment]
I'll fix in first patch

**Comment by jlukic** [comment]
I've fixed tab to go back to using its own internal caching. This was necessary as well for `evaluateScripts: 'once';` to work correctly. 

I've added additional examples to docs as well.
