### ISSUE TITLE
[Docs] Label Word Order Dependent Variations

### ISSUE THREAD

**Issue by inad9300** [Semantic-Org/Semantic-UI#2494]
Simply –and strangely– enough, `ui red right ribbon label` works all right, while with `ui right red ribbon label` the `right` part is lost.

**Comment by jlukic** [comment]
It's word order sensitive

**Comment by inad9300** [comment]
The question then is why. I've quickly check the CSS code and you are using selectors like `.ui[class*="right ribbon"]`. Why about using just `.ui.right.ribbon`, so you get a order insensitive, even more readable selector? Maybe there is a good reason for choosing the former over the later, but I cannot see it now.

**Comment by jlukic** [comment]
because you may have a `left aligned right ribbon label`

**Comment by inad9300** [comment]
I see; things get complicated. The only solution I can think about then is to say it properly in the documentation, perhaps as a warning messages in several places – and sorry if I'm suggesting something already done, I can't say I have read each corner of it.

**Comment by jlukic** [comment]
I think clear messaging in the documentation would be best. I want to do this, I just haven't had the time to add. If anyone wants to PR to at `ui label` on headers saying `word order required` i would love to add :)
