### ISSUE TITLE
Form Validation (required conflict)

### ISSUE THREAD

**Issue by Goldfinch** [Semantic-Org/Semantic-UI#2496]
Conflict with the required attribute.

```html
<form class="ui form">
<div class="field"><input type="text" name="page[title]" required="required"></div>
<div class="field"><input type="text" name="page[subname]" required="required"></div>
<input type="submit" class="ui submit button" value="Login">
</form>
```
```javascript
  $(document).ready(function()
  {
	  $(".ui.form").form({
		  fields: {
			  'page[title]':{identifier:'page[title]',rules:[{type:'empty'}]},
			  'page[subname]':{identifier:'page[subname]',rules:[{type:'empty'}]}
		  }
	  });
	
  });
```
if we use required attribute in any field and submit form like this:
```html
<input type="submit" class="ui submit button" value="Login">
```
validation for this field is not working (instead, a standard HTML5 validation), but if we replace input submit for div
```html
<div class="ui submit button">Login</div>
```
works fine

In 1.12.3 it all works.

**Comment by Goldfinch** [comment]
if add selector
```javascript
  $(document).ready(function()
  {
	  $(".ui.form").form({
		  fields: {
			  'page[title]':{identifier:'page[title]',rules:[{type:'empty'}]},
			  'page[category]':{identifier:'page[category]',rules:[{type:'empty'}]}
		  },
		  selector : {
			  submit : '.submit'
		  }
	  });
	
  });
```
fields valid, but the standard HTML5 also displayed

and I do not understand why the addition of 'selected' influences the validation if it defaults to the same exact

**Comment by jlukic** [comment]
Can you create a JSFiddle that reproduces the issue?

**Comment by Goldfinch** [comment]
https://jsfiddle.net/q525obog/

**Comment by jlukic** [comment]
Actual test case
http://jsfiddle.net/2n673cvo/

Browser `required` does the same thing as our form validation, I'd recommend using either built in browser methods or our validation, but not both.
