### ISSUE TITLE
Semantic ui 2.0 on packagist.org

### ISSUE THREAD

**Issue by emil-nasso** [Semantic-Org/Semantic-UI#2497]
Are there any plants to add semantic ui 2.0 for composer?

https://packagist.org/packages/semantic/ui

**Comment by jlukic** [comment]
It looks like packagist crawls once a week.
https://packagist.org/about

Will have to wait for them to update. We include a `composer.json`

**Comment by emil-nasso** [comment]
@jlukic There is a webhook you can set up on github. With that in place packagist will be instantly updated when code is pushed to github.

Information about it is available at the bottom of the link you provided. In the "GitHub Service Hook"-subsection of the "How to update packages?"-section.

It seems fairly straightforward. You just go to the settings of the github repository, add a service, search for packagist and enter the packagist credentials there.

![https://dl.dropboxusercontent.com/s/1nyv6yj7y8moq8c/2015-07-03%20at%2009.53.png?dl=0](https://dl.dropboxusercontent.com/s/1nyv6yj7y8moq8c/2015-07-03%20at%2009.53.png?dl=0)

**Comment by jlukic** [comment]
I'll do this. Thanks for digging further.

**Comment by jlukic** [comment]
Should be set-up
![](https://dl.dropboxusercontent.com/u/2657007/packagist.jpg)

**Comment by emil-nasso** [comment]
@jlukic Ok. Nice.

Yeah, still not updated. Did you use credentials for your own account at packagist? Maybe we need credentials from @rendom to get it working?

It has been five days since the release of 2.0, so it should "solve itself" within two days. ;)

**Comment by jlukic** [comment]
Yeah, I used my own credentials. I can't find any contact info, but i see an @rendom. Can you help us :)

**Comment by rendom** [comment]
Sorry for the delay.. I will add @jlukic as an administrator for this package.

**Comment by jlukic** [comment]
Thanks @rendom, hopefully next sync will work automatically with hooks

**Comment by mishak87** [comment]
@jlukic I have checked 2.0 is on packagist. Can be closed.

**Comment by mishak87** [comment]
Actually 2.0.7 is not there still might be some issue.

**Comment by jlukic** [comment]
It appears the web hooks aren't working..

**Comment by vinayakkulkarni** [comment]
It's showing 2.2.10 on the Packagist website.
