### ISSUE TITLE
Attached labels leave a small gap

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2500]
This is really quite a minor defect, but attached labels don't quite have the same `border-radius` as the segment they're in; this is from the Semantic docs:

![](https://i.imgur.com/UEs7cPR.png)

Easier to see with a brighter colour; an orange corner attached label inside an orange segment.

![](https://i.imgur.com/IgpG9P8.png)

Be nice if that little flash of white gap wasn't there so it looked all nicely integrated :)

**Comment by jlukic** [comment]
Although the labels match the border radius of outside segment. I think this is a math thing with radius of the "inside" of the border vs "outside" (since these are offset from edge of border).

Pretty sure I can solve this by reducing border radius by a pixel.

**Comment by jlukic** [comment]
I've reduced the border radius of inner label corners which should make this appear closer. This is still an approximation since the border radius cannot match.
