### ISSUE TITLE
Bottom attached segment has two values in margin-bottom

### ISSUE THREAD

**Issue by ElliottRoche** [Semantic-Org/Semantic-UI#2503]
[Line 14856 of dist/semantic.css](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L14856) appears to have two values specified for margin-bottom, which seems to cause the style to be ignored by the browser.

When I remove the second value everything looks correct and the browser shows the style correctly applied.

**Comment by jlukic** [comment]
Fixed in patch
