### ISSUE TITLE
Form reset/clear

### ISSUE THREAD

**Issue by beggiatom** [Semantic-Org/Semantic-UI#2504]
Hi, I have a number of forms each with a different ID and a CLASS equal.
In version 1.x when I called the reset method on all forms of the page, the values returned to its original state, but with version 2.0.0, each field is cleared of any value including fields that had a value already set.

Init form:

```html
<form class="reply-form" id="form_1">
   <input type="hidden" name="post_id" value="1"/>
   <textarea name="message"></textarea>
</form>
<form class="reply-form" id="form_2">
   <input type="hidden" name="post_id" value="2"/>
   <textarea name="message"></textarea>
</form>
```

javascript reset
```javascript
$('form.reply-form').each(function() {
    $(this).form('reset');
})
```

In 1.x version all good they return as "init form", while in 2.0.0 version forms become

```html
<form class="reply-form" id="form_1">
   <input type="hidden" name="post_id" value=""/>
   <textarea name="message"></textarea>
</form>
<form class="reply-form" id="form_2">
   <input type="hidden" name="post_id" value=""/>
   <textarea name="message"></textarea>
</form>
```

It is as if I had called the clear method.

**Comment by jlukic** [comment]
Hi, for form to correctly reset values you will have to call `$('.ui.form').form();` on page load. The first time it is invoked it will save the default values to return to with `reset`.

**Comment by jlukic** [comment]
I've gone ahead and changed the default reset behavior to "do nothing" in this case, as oppose to abnormally clearing values.

**Comment by jlukic** [comment]
I've also added a new note to docs explaining this limitation.
