### ISSUE TITLE
[Form] Clarify RegExp Rules

### ISSUE THREAD

**Issue by bautrukevich** [Semantic-Org/Semantic-UI#2512]
Hello everyone! Please, can anybody explain how to use regExp validation in semantic ui validation? I have this regExp: ([a-zA-Z0-9\s_\\.\-:])+(.doc|.docx|.pdf)$ I've tried this way:
```
resume: {
						identifier : 'js-file-type',
						optional   : true,
						rules: [
							{
								type : 'regExp[([a-zA-Z0-9\s_\\.\-:])+(.doc|.docx|.pdf)$]',
								prompt : 'The file must be a file of type: jpg, jpeg, bmp, png, pdf, doc, docx.'
							},
						]
					},
```
but this don't work : ( If I choose *.docx file I'll have errors anyway. How to do this correct?

**Comment by jlukic** [comment]
This was solved in gitter chat. 

For those wondering, Regexp currently should be specified as `/regExp/` not `regExp`

**Comment by jlukic** [comment]
Updating docs with clarification
