### ISSUE TITLE
Fix the menu

### ISSUE THREAD

**Issue by TTATPuOT** [Semantic-Org/Semantic-UI#2514]
Hello!
Not working menu in 2.0. Watch here:
![menu](http://i.imgur.com/vsfRoSk.png)
In older version all working.

**Comment by moxet** [comment]
@TTATPuOT share your code please

**Comment by TTATPuOT** [comment]
@moxet https://gist.github.com/TTATPuOT/9319dfe6e35d2e7b5069

**Comment by celsworth** [comment]
Looks ok to me: http://jsfiddle.net/09towerm/

Seems to be something else in your css?

**Comment by celsworth** [comment]
Same code in a fiddle looks ok, apart from the missing search form, which you didn't include?

http://jsfiddle.net/09towerm/

**Comment by jlukic** [comment]
Not seeing any issue
http://jsfiddle.net/7m62kfLe/
