### ISSUE TITLE
[Grid] - text alignment in grid

### ISSUE THREAD

**Issue by DavodOsanlo** [Semantic-Org/Semantic-UI#2515]
hi
when use "right aligned" class for gride, instead text align to right , aligned to left
and use  "left aligned" , text aligned in right

and i suggest when we are used "semantic.rtl.css" for stylshit, grid floated in right and the first column on the right

**Comment by jlukic** [comment]
Hi, I don't believe rtlcss which we rely on for RTL builds supports adjustment of flex rules yet. https://github.com/MohammadYounes/rtlcss/issues/33

**Comment by MohammadYounes** [comment]
@DavodOsanlo Would you provide an online sample to illustrate the issue?!

**Comment by DavodOsanlo** [comment]
@MohammadYounes After reading this https://github.com/MohammadYounes/rtlcss/issues/28 i  understood why this was

But i have a question there...
i need support IE9  but "flex-box" is not suported in IE9  , how i can don't use this update(flex) for any component , but i can use the new update?

**Comment by MohammadYounes** [comment]
I believe IE9 is not officially supported, see Semantic UI [browser support](https://github.com/Semantic-Org/Semantic-UI#browser-support).

**Comment by jlukic** [comment]
IE9 is not supported. My apologies

**Comment by DavodOsanlo** [comment]
thanks Jack And Mohammad , i was interested in learn SUI and use to my project but in my country users still use IE9 and lower

thanks for the answer

**Comment by philrykoff** [comment]
Because it's a lot of work for a 5 year old browser with a global market share of 0.27% (at least that's what caniuse has measured).
