### ISSUE TITLE
[Dropdown] Cycle Results on Keypress, Adjust Shift Commands

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2516]
1.When  selecting using first letter of item, selection sd cycle through all items beginning with that letter, instead of stopping on the first one, like: Tennessee, Texas stops on Tennessee.
2.When selecting tags with `shift+left`,`shift+right` deselecting sd be done with `shift+right`,`shift+left` respectively (mimicking OS behaviour) instead of current deselecting pattern of `right`,`left`respectively.

**Comment by jlukic** [comment]
I've modified letter shortcuts to cycle between same letter (same as os default).

I prefer keeping the shift shortcuts as is, I think these shortcuts make more sense than OS defaults which don't allow you to move a group of selections together.

**Comment by avalanche1** [comment]
What do you mean ` move a group of selections together`?
If key combos won't correspond to familiar OS shortcuts, how does one guess which keys to use?

**Comment by jlukic** [comment]
If you select a group with `shift+right` then press `right` it will move the group right one space. I think this is fairly intuitive.

**Comment by avalanche1** [comment]
Ahh, I see we have a little misunderstanding)
What I meant in my original issue is that there is no way to deselect back the group. Say, you have Alaska, Alabama & Arizona (in this exact order) selected in mulptiple dropdown. Then, if you click Arizona, press `shift+left`, you get Alabama added to the group. But there is no way to remove Alabama from the group using keyboard. I suggest to add `shift+right` to deselect Alabama.
