### ISSUE TITLE
menu item selection color

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2517]
I'd suggest setting `.ui.dropdown .menu > .item:hover, .ui.dropdown.selected, .ui.dropdown .menu .selected.item` and other related classes to have `background: @primaryColor, color: white` for contrast purposes.
Current `background: rgba(0,0,0,.03);` produces a very hard to discern contrast even for me, though I am far from colour-blind...

**Comment by jlukic** [comment]
I dont have plans to swap out neutral colors in base theme. I encourage people however to get comfortable with theming so they can make these choices in their own websites.
