### ISSUE TITLE
popup parent position ~absolute/fixed will not display

### ISSUE THREAD

**Issue by fentas** [Semantic-Org/Semantic-UI#2518]
Hi there,
Following test case: http://jsfiddle.net/Le9ys6zk/

If parent element is positioned fixed or absolute, popup will not show up.
Due to this `if` in popup component `module.set.position()`:
```js
           if(target.top === 0 && target.left === 0) {
             module.debug('Popup target is hidden, no action taken');
             return false;
           }
```

Targets position will be calculated in `module.get.calculations()` which uses `jQuery().position()` method. Quote:
> The .position() method allows us to retrieve the current position of an element relative to the offset parent. 

I don't know if this is intended.
A position solution would be eventually to explode jquerys `offsetParent` method to check if element is somehow positioned relative before dismissing it for good.

**Or** get rid of this `if` statement to resolve this. Normally if it's really hidden the browser will not render it anyway.

Btw.: top == left == 0 means that element is in top left corner. That said a popup with the setting position bottom will also not work, which makes no sense to me.

**Comment by jlukic** [comment]
This is an incorrect way to check for hidden.

**Comment by fentas** [comment]
Another way to check for visibility is `jQuery().is(':visible')` maybe?
But way bother in the first place?

**Comment by jlukic** [comment]
We have cached values already from `calculations` so better to avoid causing browser to recalculate styles.
