### ISSUE TITLE
Mini image size mismatch

### ISSUE THREAD

**Issue by lumatijev** [Semantic-Org/Semantic-UI#2521]
In documentation it's stated that 'mini image' has a size of 20px but example of such has size of 35px (also in source code it's stated 35px).
Place where I found that size matches 20px is in dropdown menu that contains image (mini avatar image). The reason for that is `max-height: 2em` property of aforementioned.

**Comment by jlukic** [comment]
Hi, the table should read `35px` for mini sizes. Images inside dropdown items are also limited by a maximum height when inside `dropdown item`
