### ISSUE TITLE
Message in dropdown has improper link.

### ISSUE THREAD

**Issue by athahersirnaik** [Semantic-Org/Semantic-UI#2523]
Follow this link:
http://semantic-ui.com/modules/dropdown.html

In Message Section, the message href is pointing to 
http://semantic-ui.com/elements/message.html

instead of 
http://semantic-ui.com/collections/message.html

And the example given is also not working.

**Comment by jlukic** [comment]
Thanks, please let me know if you encounter any other broken examples. There's a lot to maintain.

**Comment by athahersirnaik** [comment]
Welcome, Sure

**Comment by jlukic** [comment]
Oh yeah.. fixing that now and redeploying
