### ISSUE TITLE
Multi select - cannot delete added item on iPad/iPhone

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2524]
Items added in multi select cannot be deleted using the x icon on iPad/iPhone.

**Comment by celsworth** [comment]
This works for me, I have a `ui multiple search selection dropdown` and I can tap the X to delete selections on iPad. Can you provide a fiddle?

**Comment by jlukic** [comment]
Touch events are still not  handled wonderfully in dropdown. You will see click lag on mobile without using `fastClick`. The use cases are pretty complex. You can't assume someone with touch events will not use a mouse (consider a tablet with a mouse attached). 

I will have to delay providing a proper solve for this. I should however prevent `multiple` from toggling on touch

**Comment by kvetoslavnovak** [comment]
I am using iPad 2 Safari directly with Semantic UI official website examples.

**Comment by jlukic** [comment]
I'm no longer having issues with this after updates. I

**Comment by kvetoslavnovak** [comment]
It is ok now.
