### ISSUE TITLE
Problem with Input fields in IE

### ISSUE THREAD

**Issue by Gumlokt** [Semantic-Org/Semantic-UI#2525]
Hello everyone!
Cyrillic characters in input fields are displayed incorrectly when I use Internet Explorer (I tried with IE-11). Field displays something like "?@825B" instead of "привет". Does anybody know how to fix it?
FF and Google chrome displays characters correctly.
Try at http://semantic-ui.com/elements/input.html

**Comment by jlukic** [comment]
Sorry that commit was tagged incorrectly and is not related to this issue.

**Comment by avalanche1** [comment]
Closing until there's a valid test case.
