### ISSUE TITLE
Menu items squeeze together and overlap

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI#2529]
If you have many menu items, they squeeze together, even overlapping so they are hard/impossible to get to. This is new in 2.0.0. In older versions the menu items dropped down, so that you could have two or three or any number of stacks of items on top of each other. Now you are forced to add "stackable" which is the ugliest thing ever when you have many menu items.

**Comment by jlukic** [comment]
I dont agree that menu content should allow for wrapping. If you do want to enable this for a menu add `flex-wrap: wrap;` to the menu which you do not want to collapse.

**Comment by cyllu2** [comment]
That worked, thanks. Also, I meant a tabular menu, I don't know why I forgot to mention that.
