### ISSUE TITLE
[Usage question] Dropdowns and pure custom inner HTML/content

### ISSUE THREAD

**Issue by SantzDesign** [Semantic-Org/Semantic-UI#2531]
Hey. Note I'm not using the whole Semantic UI framework, of course, just the code I need.

So... I installed the Transition + Dropdown plugins (JS + CSS) and I got example dropdowns working on my site.

**The problem arises when I instead of using (for instance) this snippet:**

```html
<div class="ui dropdown">
  <div>This 'div' should be an avatar</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item">This should be a title, not a link/action</div>
  </div>
</div>
```

**I use (notice I'm ONLY changing a div's class inside the .menu div):**

```html
<div class="ui dropdown">
  <div>This 'div' should be an avatar</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="myOwnClass">This should be a title, not a link/action</div>
  </div>
</div>
```

**What I need to get done**, is a simple user dropdown. The user clicks an avatar instead of text, and a dropdown menu opens with his name (not clickable), and a couple of links to other pages (such as Personal profile, Account settings, Favorites, whatever...) and a logout button.

*Is this doable with Semantic UI?* If not, I should of course give this up and build a different approach.

Thanks in advance for any help.

**Comment by jlukic** [comment]
Dropdowns currently will not open if there are no `item` inside. This is to prevent filtered dropdowns from showing empty results. 

You can use arbitrary class names on menu content, but the idea of a dropdown if a selection from a list of `items`, so you will need at least one of those.

If you just want an arbitrary container that appears in place above an activating element use a [popup](http://www.semantic-ui.com/modules/popup.html)

**Comment by SantzDesign** [comment]
Great answer. I cannot believe I didn't try that myself before.

I mean, I can then do this, right? (I'm asking to know if I'm going to run into any trouble, and to know if there's any precaution I need to take).

```html
<div class="ui dropdown">
  <div>This 'div' should be an avatar</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="menu-head">
      <h4>My name</h4>
      <button class="btn-logout">
        <i class="icon-logout"></i> Logout
      </button>
    </div>
    <div class="item"><a href="#">Profile</a></div>
    <div class="item"><a href="#">Account</a></div>
    <div class="item"><a href="#">Stuff</a></div>
    <div class="item"><a href="#">More stuff</a></div>
  </div>
</div>
```

Thanks again!

**Comment by jlukic** [comment]
Yes, just dont need to nest `a`

```javascript
$('.ui.dropdown')
  .dropdown({
    action: 'hide'
  })
;
```
```html
<div class="ui dropdown">
  <div class="text">This 'div' should be an avatar</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="menu-head">
      <h4>My name</h4>
      <button class="btn-logout">
        <i class="icon-logout"></i> Logout
      </button>
    </div>
    <a class="item" href="#">Profile</a>
    <a class="item" href="#">Account</a>
    <a class="item" href="#">Stuff</a>
    <a class="item" href="#">More stuff</a>
  </div>
</div>
```

There's an example of a list using external links in dropdown examples, near the bottom.

**Comment by SantzDesign** [comment]
Amazing @jlukic, thank you for the help. I won't nest the `<a>`, thanks for the tips!
