### ISSUE TITLE
[Dropdown] - Search Dropdown does not clear value on hideAndClear

### ISSUE THREAD

**Issue by phillip-haydon** [Semantic-Org/Semantic-UI#2533]
http://semantic-ui.com/introduction/new.html

Using latest version of Chrome on Windows 8.1

![image](https://cloud.githubusercontent.com/assets/895629/8537810/9a519cd0-2496-11e5-8291-79f9348cbbf0.png)

Type into the favourite animal, click an item:

![image](https://cloud.githubusercontent.com/assets/895629/8537818/a831c33e-2496-11e5-878f-fec9eb8b2e1f.png)

**Comment by jlukic** [comment]
This is a regression in `2.0.1` ugh..

**Comment by jlukic** [comment]
Resolved will patch today.
