### ISSUE TITLE
[Tab] Just load an url

### ISSUE THREAD

**Issue by emil-nasso** [Semantic-Org/Semantic-UI#2535]
I have tried to figure out how to use the tab component for loading ajax content, but i really cant figure it out.

I need a few tabs and i want them all (or just a few of them) to load content through ajax.

Just setting `auto:true` and setting `data-tab = "/test/something?query=123"` gives me an error:

```
Activated tab cannot be found for this context. [a.item, context: a.item] [body.hello, prevObject: b.fn.b.init[1], context: document, selector: "body"] $.fn.tab.$allModules.each.module.error @ 482339a_semantic_5.js:13420(anonymous function) @ 482339a_semantic_5.js:13160b.extend.each @ 482339a_jquery.min_1.js:3$.fn.tab.$allModules.each.module.changeTab @ 482339a_semantic_5.js:13083$.fn.tab.$allModules.each.module.event.click @ 482339a_semantic_5.js:12996b.event.dispatch @ 482339a_jquery.min_1.js:3b.event.add.v.handle @ 482339a_jquery.min_1.js:3
```

The documentation about use an "api" for it is a bit lacking. I have no idea where to even start.
http://semantic-ui.com/modules/tab.html/usage#with-an-api-behavior
(That link seems to be broken, history urls doesnt work in the documentation. Go here: http://semantic-ui.com/modules/tab.html , click usage and scroll to ...with an API Behavior).

All i really want is to be able to put an url on the divs, like this;

```
<div class="ui top attached tabular service menu">
        <a class="item active" data-tab="first">First</a>
        <a class="item" data-tab="second">Second</a>
    </div>
    <div class="ui bottom attached tab segment active" data-tab="first" data-action="first">
        Some preloaded content
    </div>
    <div class="ui bottom attached tab segment" data-tab="second" data-url="/some/url?with=queryparams">
    </div>

```

And have the first tab preloaded with content and the second tab loaded when i click it.

Is that possible with semantic ui?

**Comment by emil-nasso** [comment]
I ended up (or will probably end up) doing it manually.

```javascript
  $('.ui.tabular.ajax.menu .item').tab({
    history: true,
    onTabInit : function(tabPath,parameterArray, historyEvent){
      url = $(this).data('url');
      if(url){
        _this = $(this);
        $(this).addClass('loading');
        $.get(url, function(response){
          _this.html(response);
          _this.removeClass('loading');
        });
      }
    }
  });
```

With that in place i can have a menu that looks like this.

```html
    <div class="ui top attached tabular service menu">
        <a class="item active" data-tab="first">First</a>
        <a class="item" data-tab="second">Second</a>
        <a class="item" data-tab="third">Third</a>
    </div>
    <div class="ui bottom attached tab segment active" data-tab="first" data-action="first">
Preloaded-content
    </div>
    <div class="ui bottom attached tab segment" data-tab="second" data-url="/echo/THE_SECOND_TAB">
    </div>
    <div class="ui bottom attached tab segment" data-tab="third" data-url="/echo/THE_THIRD_TAB">
    </div>
```

**Comment by jlukic** [comment]
It's really simple actually 
```javascript
$('.ui.tabular.ajax.menu .item').tab({
  apiSettings = {
    url: 'some/url/or/another?tab={tab}'
  }
});
```

**Comment by scoman81** [comment]
This is pretty confusing still, or maybe I'm just dense.

The code you wrote has "apiSettings = {}" ... that's not supposed to be "apiSettings: {}" ?

Also, the code you wrote uses {tab} but the docs say {$tab}. 

The docs never show the option of an object field called apiSettings, as far as I can see. What the docs say is to assign a mapping object to the global $.fn.api.settings.api, and then name the action on the tab using $(xx).api({}). Maybe I've missed a big chunk.

Could you please show an example that uses the same syntax as the docs, using $.fn.api.settings.api, and then the .api() function on the tab control? I've tried every combination, and while I can get tabs to make an ajax call using the "auto: true" format, I can't get tabs to make an ajax call using the API.

Any help would be greatly appreciated!

**Comment by scoman81** [comment]
Sorry, the "apiSettings" field is indeed shown on the examples page! My bad. But there's no example using "url" there. 

After further testing, this code gets me closer:

    $('.menu .item').tab().api({
      url: 'pages/{tab}.php'
    });

This indeed makes an ajax call to "pages/tabname.php"  where tabname is the data-tab value from the A tag with the class of "item."

**Comment by jlukic** [comment]
The code you're looking for is

```javascript
$('.menu .item').tab({
  apiSettings: {
    url: 'pages/{tab}.php'
  }
});
```

**Comment by scoman81** [comment]
Thanks! This totally worked!
