### ISSUE TITLE
[Site] Sizing Not Adjusting Correctly from emSize

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI#2538]
I turned the base sizes to
@emSize: 16px;
@fontSize: 15px;

This turned most of my text bigger, but the text inside message boxes only got smaller, ~~except some headers which now look ridiculously big in comparison~~. Basically this broke my entire design and now I have to go in and make pinpoint precise changes to the font-sizes of all elements.

**Comment by deneuxa** [comment]
I had the same problem,
message box dont use the @fontSize variable but a derivated one @mediumSize. 
Just change thoses variables and it will go fine : 

You just have to adapt the 10 / 12 /14 / 16 / 20 / 22 / 24 / 26 to whatever you want : 

@miniSize        : (10 / unit(@emSize));
@tinySize        : (12 / unit(@emSize));
@smallSize       : (14 / unit(@emSize));
@mediumSize      : (16 / unit(@emSize));
@largeSize       : (20 / unit(@emSize));
@bigSize         : (22 / unit(@emSize));
@hugeSize        : (24 / unit(@emSize));
@massiveSize     : (26 / unit(@emSize));

@jlukic  => it could be nice to replace thoses "fixed" number by  @fontSize +/- % ? or something like that ?

**Comment by jlukic** [comment]
Hi, there was a bug. I just want to clarify here what's suppose to happen in terms of sizing. 

1) `@emSize` specifies `1em` size for all sizing values.
2)  Coarse size variables like `@miniSize`, `@smallSize` provide "general ratios" for how large things should be relative to base em. These are coarse values and **do not** round to exact pixel values. They should not change if `@emSize` changes
3)  Exact Size variables like `@mini` are calculated by multiplying the coarse values by `emSize` and , rounding to the nearest pixel value and then expressing these exact ratios in `em` and `rem`
