### ISSUE TITLE
dropdown onChange callback fires before dd item changes

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2539]
Docs say: `on Change Is called after a dropdown value changes. Receives the name and value of selection and the active menu element`
http://codepen.io/avalanche1/pen/GJyJZe
If you select any item, alert shows your previous dd value, while it should show newly selected value.
I understand that I can get `text` argument of `onChange`, but `.dropdown('get text')` sd work as well.

**Comment by jlukic** [comment]
I think it makes sense to update text before.
