### ISSUE TITLE
Menu without round corner

### ISSUE THREAD

**Issue by elgs** [Semantic-Org/Semantic-UI#254]
The menu with a tiny round corner is great. However, when I put the menu all the way to the up left corner, and when the menu is inverted, there are two small blank areas at the top corners because of the round corner. Is it possible to have a non-round-corner version of the menu?

Thanks,
Elgs

**Comment by oniisaki** [comment]
Another solution is to overwrite the semantic ui css for menu:
.ui.menu {
	border-radius: 0px !important;
}

**Comment by jlukic** [comment]
You can also use `attached`

**Comment by elgs** [comment]
Thanks!
