### ISSUE TITLE
Checkboxes can no longer be validated when initialized with JavaScript

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI#2540]
First I misdiagnosed a bunch of errors with the new checkboxes, but that was due to another bug in my code. Here's one that remains, though:

You can no longer validate checkboxes when you initialize them with JavaScript. I have a checkbox that I want to begin checked, however when I do

`$('.ui.user-agreement.toggle').checkbox('check')`

the validation will no longer fire when it's changed.

**Comment by jlukic** [comment]
Can you please create a JSFiddle to demonstrate this issue. 

My understanding is that toggling a checkbox ussing `checkbox('check')` causes form validation to fail?

**Comment by jlukic** [comment]
Closing due to lack of test case.
