### ISSUE TITLE
[Usage question] Fullscreen layout using SUI

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#2542]
Hi there!

Using SUI for a long time now I decided to update my app to a fullscreen app.
I checked documentation to find out what's the best way to implement fullscreen but did not found a reliable solution.
As you all are experienced UI designers I'm asking to you what would be the best (and lightweight) solution to implement it (supporting also native responsive design from SUI).

First of all, I found that some CSS (html5) attributes would help me : viewport heigh / with (see http://codepen.io/ckor/full/cf2134280cd25e8ac7e57f1b05bb0b49/).
Then, we need to deal with SUI grid collection to create some "regions" we could use to set custom elements, using grids and removing gutters (Previouly in SUI 1.x there was some definitions but I did not found again in SUI 2.x).

That's my point of view for now, if some better way to do it exists, I'd be glad to know it :)

**Comment by jlukic** [comment]
Just set something like `height: 90vh;` on a custom wrapper then nest a grid. I think that's a fine start

**Comment by cazzoo** [comment]
Yea, that's what I tought too, maybe with an overflow: none; added to be sure that the scrollbars wont show up
