### ISSUE TITLE
Probably grid problem

### ISSUE THREAD

**Issue by KotasMan** [Semantic-Org/Semantic-UI#2543]
Hello, when i minimize chrome, i can horizontally scroll for a few pixels.
Here is my code http://pastebin.com/SAGQ91sF, screenshots are below.
I hope you understand me, im sorry for my bad english.

![not_scrolled](https://cloud.githubusercontent.com/assets/8343385/8547785/62cd28f8-24c1-11e5-95ff-9fd710f6a876.png)
![scrolled](https://cloud.githubusercontent.com/assets/8343385/8547784/62ca9a7a-24c1-11e5-949b-07f086264d8d.png)

**Comment by jlukic** [comment]
Appears to be working fine
http://jsfiddle.net/zcppmnhz/
