### ISSUE TITLE
[Step] -Switching to Github or Basic Theme breaks the steps styling 

### ISSUE THREAD

**Issue by danmv** [Semantic-Org/Semantic-UI#2545]
**Steps to Reproduce**
1. Click on the theme button, select Github or Basic
2. Look at all the step examples and I can see the triangle's position is off 

**Expected**
Behave as the default theme. 

**Result**
The Step does not do this

**Comment by jlukic** [comment]
Thanks the github step theme is broken.

**Comment by jlukic** [comment]
Fixed in `2.0.3`
