### ISSUE TITLE
Enable scroll when open modal

### ISSUE THREAD

**Issue by ozgrozer** [Semantic-Org/Semantic-UI#2546]
Hello,

Scroll doesn't change when we open a modal in legacy.semantic.
http://legacy.semantic-ui.com/modules/modal.html

But in Semantic 2, scroll disabling and it's a bad UX in my opinion.
http://semantic-ui.com/modules/modal.html

I tried .long.modal class but my content is just one line and it doesn't help me.
Is there any way to enable scroll when open modal in Semantic 2?

Thanks.

**Comment by mishak87** [comment]
@jlukic Another adept for closing :)
