### ISSUE TITLE
Issue adding less variables to menu.less

### ISSUE THREAD

**Issue by toddler4372** [Semantic-Org/Semantic-UI#2547]
I'm adding new variables to semantic/src/definitions/collections/menu.less and defining the variables in semantic/src/themes/continu/collections/menu.variables, but when compiling I get errors that the variables in menu.less are undefined.  Thing, they worked for the first 10 or so variables that I added, and then would not build after that.

1.  I couldn't find it in the documentation, but can I add variables to the list of predefined ones in these .less definition files?  If not, how can I add further properties to menu elements without referencing an outside .css file?

**Comment by jlukic** [comment]
I'm not sure your build setup.

But if you are adding variables they should be added to `/src/site/collections/menu.variables` and used in `/src/site/collections/menu.overrides`

**Comment by toddler4372** [comment]
Thanks for the response.  So I can't add any arbitrary new variables to /src/themes/mytheme/collections/menu.variables?  Some of these I don't want site-wide, but only for this theme.

**Comment by jlukic** [comment]
Yes, the functionality works both on a 'packaged theme' and 'site theme' level. Each level overriding the previous.
