### ISSUE TITLE
[Card dimmer] dimmer content problem on touch device

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#2548]
http://jsfiddle.net/z0z080nd/show/

when there are some <a href="may be dangerous"> in a card dimmer, user touch may trigger the <a> which unexpected. Should we disable content "pointer-events" when dimmer animating ?

**Comment by jlukic** [comment]
There's unintended consequences sometimes to the "nuclear" option of disabling all pointer events. Although it would appear to solve this case. 

I'll have to revisit this.
