### ISSUE TITLE
Problems with horizontal segment in IE 11

### ISSUE THREAD

**Issue by hermanhmchan** [Semantic-Org/Semantic-UI#2550]
Hello,

I found an issue in 2.0. Please refer to the attached screen capture below. I am using IE 11.
http://semantic-ui.com/introduction/new.html

![capture](https://cloud.githubusercontent.com/assets/13231139/8563165/42f7078a-256e-11e5-9328-59a52e518a3d.PNG)

http://semantic-ui.com/elements/segment.html

![capture2](https://cloud.githubusercontent.com/assets/13231139/8563215/cce34904-256e-11e5-8e1e-c858774d8cd5.PNG)

Please help to check it. Thanks.

Regards,
Herman

**Comment by kevindice** [comment]
IE's implementation of flexbox is likely to blame here.

**Comment by jlukic** [comment]
Sorry this got stranded in the ether. I need to fix this.

**Comment by jlukic** [comment]
Added separate flex rules for IE for `horizontal segments` appears to be fixing. Also fixed the text rendering of code samples in IE.

I'm a bit worried about `stretched grid` functionality with images using intrinsic aspect ratios in IE. But there's no solve there.

**Comment by hermanhmchan** [comment]
May I know will this fix be included in next release? And when will be next release? Thanks.

**Comment by jlukic** [comment]
You can see releases and related milestones under the special [milestones tab](https://github.com/Semantic-Org/Semantic-UI/milestones). `2.0.4` will probably be out by friday

**Comment by hermanhmchan** [comment]
The problem still exists in 2.1. Please help to check.
