### ISSUE TITLE
[Dropdown] - Direction direction fail on second attempt

### ISSUE THREAD

**Issue by pedrosanchezpernia** [Semantic-Org/Semantic-UI#2551]
I have a "ui bottom fixed menu" with a dropdown as an item.
The dropdown is activated when the item is clicked.
The direction detected is upward and show nested items.

However on following attempts, the direction is not well detected and the dropdown goes down, therefore invisible for the user (remember the menu is fixed bottom).

As a solution I am forcing this particular menu always upward:
$('.upward.ui.dropdown')
       .dropdown({
        direction: 'upward'
        })
;

Anyway, I guess it should be reported.

**Comment by jlukic** [comment]
Hi, I'm not able to replicate issues with `direction: upward` not preserving direction on repeated shows.

Can you create a test case? The easiest way is to fork the JSFiddle available in readme.

**Comment by pedrosanchezpernia** [comment]
Well, I'm not able neither to reproduce the issue in a JSFiddle https://jsfiddle.net/pedrosp/38cj9mrj/ .
It's a plain copy-paste, and even trying to match the query version.
It works.

I'm using Semantic UI in a Drupal environment, I guess the detection logic that lead to upward or downward is colliding with some other process in there. 
I propose to close this issue, as it seems related to my particular case.

**Comment by jlukic** [comment]
Can you confirm you are using `> 2.0`, I know a similar bug in beta releases and `1.x`

**Comment by pedrosanchezpernia** [comment]
Yep, * # Semantic UI - 2.0.2

**Comment by jlukic** [comment]
I'll leave this open, but wont be able to triage pending a test case that displays the issue.

**Comment by jlukic** [comment]
Re-open with test case

**Comment by turbcool** [comment]
I found out that this problem is caused by 'hidden' class that is added to 'menu' block after each dropdown close.
My solution was to remove 'hidden' class from dropdown 'menu' in onOpen callback.
