### ISSUE TITLE
[Step] last step has right arrow if active

### ISSUE THREAD

**Issue by naabster** [Semantic-Org/Semantic-UI#2552]
If the last step is marked active, it has the little arrow to the right.

![screen shot 2015-07-08 at 11 07 18](https://cloud.githubusercontent.com/assets/1961461/8566895/8adb20a2-2561-11e5-942b-0ffc9f976e96.png)

this should fix it:

    .ui.steps .step:last-child:after {
      display: @lastArrowDisplay !important;
    }

**Comment by jlukic** [comment]
Sorry about that.

**Comment by naabster** [comment]
no worries :)
thanks for all your work!
