### ISSUE TITLE
[Message/Header] - Add Support for Icon Groups

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI#2553]
Hi.

When using a group of icons in a `message`, they lose their size and margin. Test in [this JSFiddle](http://jsfiddle.net/miniskulljob/bss9w27k/).

**Comment by jlukic** [comment]
Most components currently *do not* support icon groups. I could see including support for message and header, which might use this pattern more frequently, but changing all instances of `icon` across components would be a big deal lib wise.

**Comment by Enelar** [comment]
You may consider about `.icon.icons` if it suitable across whole library

**Comment by jlukic** [comment]
Would have to replicate the whole rule in each case, i.e 

```css
.ui.icon.message > .icon:not(.close),
.ui.icon.message > .icons {

}
```

**Comment by Enelar** [comment]
@jlukic why '.icon.icons' not valid?
It steal matching
```css
.ui.icon.message > .icon:not(.close) {
}
```

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) now supports icon groups in `header` and `message` by
https://github.com/fomantic/Fomantic-UI/pull/1798 and 
https://github.com/fomantic/Fomantic-UI/pull/1799
