### ISSUE TITLE
[Dropdown] - Search selection shows typed value under option

### ISSUE THREAD

**Issue by VitalikL** [Semantic-Org/Semantic-UI#2557]
**Steps to Reproduce**
1. Click on Search Selection example of Dropdown
2. Start typing first letters (ex. Canada_
3. Click on "Canada" option 

**Expected**
Should show option and do not show typed text

**Result**
Shows typed text under option

**Comment by jlukic** [comment]
It looks like the version of SUI in the docs somehow is [out of date](http://semantic-ui.com/dist/semantic.js) its using `2.0.1`, this bug was fixed in `2.0.2`.

My apologies

**Comment by jlukic** [comment]
I've redeployed now this should be fixed.
