### ISSUE TITLE
[GRID] - Assume full width with one column doesnt work

### ISSUE THREAD

**Issue by startswithaj** [Semantic-Org/Semantic-UI#2559]
https://github.com/Semantic-Org/Semantic-UI/blob/a16c1402c8cf11b5e5dda74bd56b18a4c9f927d9/src/definitions/collections/grid.less#L212

**Steps to Reproduce**
Create a ui grid with out row and a single column with ten.wide
.ui.grid
  .row
    .ten.wide.column

**Expected**
The column should assume full width as its on only child

**Result**
```
.ui.grid > .row > [class*="ten wide"].column, .ui.grid > .column.row > [class*="ten wide"].column, .ui.grid > [class*="ten wide"].column, .ui.column.grid > [class*="ten wide"].column {
  width: 62.5% !important;
}
.ui.grid > .column:only-child, .ui.grid > .row > .column:only-child {
  width: 100%; //This gets over ruled
}
```

Repro here
http://jsfiddle.net/vjevbw9n/1/

**Comment by jlukic** [comment]
This is functioning as expected. It should only assume 100% width if no column width is specified.

**Comment by startswithaj** [comment]
Ahh apologies you're right. 

I am using it with row equal height and in version 1 that would apply the below css to the column which would make it fill the full 16 columns even if it was declared ten wide.

In version 2 row.equal.height applies flex to the row not the column. So this no longer happens. Should have investigated it more thoroughly. 

```
ui.grid>[class*="equal height"].row>.column, .ui[class*="equal height"].grid>.column, .ui[class*="equal height"].grid>.row>.column {
  display: block;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
  -ms-flex-positive: 1;
  flex-grow: 1;
}
```
