### ISSUE TITLE
Why Substring matching?

### ISSUE THREAD

**Issue by Isigiel** [Semantic-Org/Semantic-UI#2561]
The `* column grid`classes use substring matching to determine the coulmn width: `*= "five column"`
I'd prefer to have `fiv.column.grid`for that, because substring matching as is defines the position. When using frameworks like angular the new class always is the last -> `ui column grid five`which is a problem atm, but the class selectors would work anyways.
Why is substring matching used and would it be possible to change that?

**Comment by jlukic** [comment]
See #396
