### ISSUE TITLE
Checkbox on Array name

### ISSUE THREAD

**Issue by c0m3nk** [Semantic-Org/Semantic-UI#2563]
PHP need checkbox name in array when submit multiple ckecker
![screen shot 2015-07-09 at 5 43 11 pm](https://cloud.githubusercontent.com/assets/982692/8593466/257759fe-2662-11e5-921e-1c7fae27b587.png)
when I give name not in array checkbox have correct behav..

but.. when I give array on name, checkbox not give a correct result
![screen shot 2015-07-09 at 5 46 04 pm](https://cloud.githubusercontent.com/assets/982692/8593504/7be85a54-2662-11e5-9a30-f8b267e6bcde.png)

****
note: on safari and chrome is fine, only on firefox

**Comment by jlukic** [comment]
Can you include the outputted html in a jsfiddle so i can debug?
