### ISSUE TITLE
Semantic Modal Bug

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#2564]
When we use Angular.js and we got two buttons that open same modal. First one has empty fields inside, on second are filled. The bug: When switch couple of times and page swap - modal becomes lazy. Did not show correct data. In console, or if data is not in modal, is shown proper - it changes. But in modal start showing only first button data result, or only second - it stops to respond.
Any ideas?

**Comment by jlukic** [comment]
Can you create a test case.

**Comment by TeodorKolev** [comment]
Unfortunately, no, but you can create your own by yourself following the instructions

**Comment by TeodorKolev** [comment]
Nice support

**Comment by JonathanRosado** [comment]
+1

**Comment by AndreeaDora** [comment]
+1
