### ISSUE TITLE
Button BG Color Modal Problem

### ISSUE THREAD

**Issue by abagshaw** [Semantic-Org/Semantic-UI#2567]
Hi! I am using Semantic UI 2.0.2 and I ran into a problem having a button trigger a modal. I haven't built my modal yet - just using a test one but I've already run into a problem:

When I set the button to trigger the modal everything works fine, except when I close the modal the button then clicks back to its "hover" background color (a slightly darker grey) and then when I click somewhere else on the page it goes back to normal.

See below:

https://jsfiddle.net/n3cnrnrt/

This isn't quite the latest version of Semantic UI that I pulled in for the jsfiddle but it's the same problem I'm having with 2.0.2.

Any ideas?

Thanks!

Andrew

**Update: When my button is created with `<button>` I get this problem but when I create it with a `<div>` like on the Semantic UI modal page it works fine. So this is probably still a bug because I think it should be able to work both ways.**

**Comment by jlukic** [comment]
This is an accessibility "feature" of `<button>` tags and pretty annoying. Buttons will retain focus after being clicked. The same issue will also occur in all the button docs examples.
