### ISSUE TITLE
Gulp not adding Semantic from Bower

### ISSUE THREAD

**Issue by sebastialonso** [Semantic-Org/Semantic-UI#2568]
Not really sure if it's an issue with Semantic-UI, but if someone else is experiencing this, it may be of help.
I'm using [Gulp-Angular](https://github.com/Swiip/generator-gulp-angular) to compile my Javascript, automagically import JS and CSS from Bower into ``index.html``. I installed semantic using bower, but Gulp isn't inserting the needed files by its own. I thought this may have been Gulp's problem, but then I tried to do it *manually* and still didn't work.

**I only installed Semantic to use the styles and some of the JS**, I'm not interested in special directives.

Maybe it has something to do with the Bower package. Has anyone else experienced something like this?

**Comment by jlukic** [comment]
You may want to ask this over in semantic-ui-angular's issues or chat.
