### ISSUE TITLE
[Sidebar] - add .scrollable class

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2569]
As you can see [here](http://semantic-ui.com/behaviors/visibility.html) page has a lot of whitespace below the article due to long sidebar. If it was scrollable, this issue wouldn't arise.

**Comment by jlukic** [comment]
I'm happy with the design decisions in docs. I prefer auto scrolling left bar using `sticky` over using a dedicated second scroll bar.

**Comment by avalanche1** [comment]
Well, that's strange, because on the homepage sidebar has its own scrollbar and you're ok wit it.

**Comment by jlukic** [comment]
It's not always visible
