### ISSUE TITLE
Nothing is really equal height

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI#2571]
In the version notes you claim that "columns are now all equal height by default. "

However, this is demonstrably false. Check out this simple fiddle for an example: http://jsfiddle.net/63h8Le5d/

So what do you actually mean by "equal height"? And is there actually a way to accomplish that? Adding the class "equal height" does not work.

**Comment by jlukic** [comment]
Columns are equal height but column contents do not automatically stretch unless you specify.

See stretched variation
http://jsfiddle.net/2xpr7wmh/
