### ISSUE TITLE
[Docs] Note about Blurring Modal Performance

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#2574]
I love the new blurring ability of the modal. However, I have significant frame loss when I use; it's extremely noticeable. 

My computer is pretty beefy (4.4ghz i7, 32gb RAM, gtx980ti). I'm running Ubuntu 14.04 with Chromium 43. I have 2x 144hz 1080p monitors

I did a little quick analysis using the chrome FPS counter; and I was usually painting ~100fps, but i drop to about 15 when using the blurring feature. 

Curious if anyone else has noticed this.

**Comment by jlukic** [comment]
Yes, no one should ever use full screen blurring for everything. I was going to write a note about performance, but I figure people would catch on.

**Comment by jlukic** [comment]
Blur will not perform well on full screen modals under almost any circumstances. This is a limitation of full screen filters. I should probably make a note about this in docs.

**Comment by jlukic** [comment]
Oh wait there already is a note in docs..

**Comment by ph7vc** [comment]
@jlukic: For me it's not isolated to just full screen modals, but any modal using the blur. 

I'm betting it has to do with applying this CSS style:

```
.blurring.dimmed.dimmable>:not(.dimmer) {
  filter: blur(5px) grayscale(.7);
}
```

Looks like it will select every element on the page and apply that style to it; so if it's a rather deep DOM tree (like the docs are), I could see how this could cause a performance hit. If it was applied only to the highest element in the DOM; and modals and page dimmers were outside that, then that would work; but that would probably be a lot of recoding.

Not a huge deal; but idk how usable this feature will be :(

**Comment by jlukic** [comment]
It is only applied to children of body that are not the dimmed content. Check the `>`
