### ISSUE TITLE
[Modal] - sets body height when modal can't fit but does not set it back when modal closes

### ISSUE THREAD

**Issue by startswithaj** [Semantic-Org/Semantic-UI#2576]
```
          screenHeight: function() {
            if( module.can.fit() ) {
              $body.css('height', '');
            }
            else {
              module.debug('Modal is taller than page content, resizing page height');
              $body
                .css('height', module.cache.height + (settings.padding * 2) )
              ;
            }
          },
```
This code runs on modal.show
but no code sets the body height back to '' when the modal closes

repro:

have modal thats bigger than body, show modal, close modal. Height still set on body.

**Comment by jlukic** [comment]
It was set to [leave it in place](https://github.com/Semantic-Org/Semantic-UI/commit/6fbabf4c2bc996341c13995d220c47f4d20bce22#diff-717f2a98ed6bb3badb6deeb18648d1e6L501) I dont recall why but I'm fairly certain it can safely be removed.

**Comment by startswithaj** [comment]
Yeah I just call body.css height, '' when I hide the modal and haven't seen anything untoward.

**Comment by iLavs** [comment]
i have the issue with performance of simple modal window. my code look like:
<div class="main-header">
    <div class="container">
           <span class="main-logo">
        <img src="/img/logo.jpg" alt="logo" />
    </span>

        <button class="ui button btn-fire btn-login" (click)="SignInModal.show({ transition: 'vertical flip'})">Login</button>

        <sm-modal title="Sign in form" class="" #SignInModal>
            <modal-content>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </modal-content>
        </sm-modal>
    </div>
</div>

but Modal doesn't work correctly.  Someone please help me with it?
![7](https://cloud.githubusercontent.com/assets/11498700/18101433/62f86c44-6ef7-11e6-9c7c-bee6076e60e3.png)

**Comment by abomusab** [comment]
I solved the problem by adding 



    .modal {
            bottom: auto;

        }

to your page

**Comment by lackneets** [comment]
```css 
.modal { bottom: auto; }
```

Solved too. Seems like Bootstrap conflicts with Semantic modal
