### ISSUE TITLE
Standard INPUT field displays cyrillic characters incorrectly in IE

### ISSUE THREAD

**Issue by Gumlokt** [Semantic-Org/Semantic-UI#2577]
**Steps to Reproduce**
1. Simply type something in input fields with Russian keyboard layout using IE (in my case IE-11) on this page http://semantic-ui.com/elements/input.html.
2. Standard input field displays cyrillic characters correctly if I copy russian text from somewhere and paste there.
3. Other browsers like FF or Google chrome displays cyrillic characters correctly.

**Expected**
привет

**Result**
?@825B

**Comment by avalanche1** [comment]
Smth wrong with your codepage. Everything's fine on my IE11.

**Comment by Gumlokt** [comment]
I have tried both CP-1251 and UTF-8. But it does not work as I expect

**Comment by Gumlokt** [comment]
![semantic-ui](https://cloud.githubusercontent.com/assets/9348101/8615105/4c38d868-2709-11e5-855c-0e9509aaffa9.png)

**Comment by Gumlokt** [comment]
Sorry, after resetting Internet Explorer settings cyrillic characters displays correctly.
I have used this "how to": https://support.microsoft.com/en-en/kb/923737/en
