### ISSUE TITLE
[Validation] - Make Identifier Optional

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2579]
Form validation code would be DRYer if we could omit specifying field `name` two times.
```jade
.ui.form
  input(name='category') Select category
```
Instead of:
```coffee
$('.ui.form').form
  fields:
    category:
      identifier: 'category'
      rules:[
        type: 'empty'
        prompt:'Specify a category']
```
I propose by default:
```coffee
$('.ui.form').form
  fields:
    category:
      rules:[
        type: 'empty'
        prompt:'Specify a category']
```
In case user needs to have differing fieldname and identifier name - he can explicitly specify `identifier`.

**Comment by jlukic** [comment]
I think this makes sense as an enhancement. Allow both

**Comment by jlukic** [comment]
New style added for `2.1` for form validation
![](http://i.imgur.com/SW8vDzM.png)

**Comment by listepo** [comment]
+1

**Comment by jlukic** [comment]
Identifiers are now optional.

**Comment by jlukic** [comment]
I've added a new form shorthand that works like this
```javascript
$('.ui.form')
  .form({
    fields: {
      name     : 'empty',
      gender   : 'empty',
      username : 'empty',
      password : ['minLength[6]', 'empty'],
      skills   : ['minCount[2]', 'empty'],
      terms    : 'checked'
    }
  })
;
```

Will automatically expand out to full validation settings

**Comment by listepo** [comment]
@jlukic, Thank you for your hard work

**Comment by jlukic** [comment]
:smile:

**Comment by avalanche1** [comment]
yay! thanks, Jack!
the next best thing for Validation would be allowing assigning the same rule to multiple fields: https://github.com/Semantic-Org/Semantic-UI/issues/667, https://github.com/Semantic-Org/Semantic-UI/issues/829

**Comment by jlukic** [comment]
I was hoping to do that as well, but there are complications with how it's handled internally.

**Comment by davehayes** [comment]
Can one keep a copy of the "fields" object and alter "prompt" to change the actual error message displayed? 

Alternatively can "prompt" optionally be a function that returns the error message?

**Comment by snowshine09** [comment]
It seems the shorthand version could not be used in conjunction with the full version for validation rules. It would be more reasonable to be flexible in these forms.
