### ISSUE TITLE
[Validation] - default 'type' rule

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2580]
I have lots of fields which only need to be checked for `type: 'empty'`. Thus I'd like `type: 'empty'` to be default validation rule and thus be omitted altogether.
Instead of:
```coffee
$('.ui.form').form
  fields:
    category:
      identifier: 'category'
      rules:[
        type: 'empty'
        prompt:'Specify a category']
```
I propose by default:
```coffee
$('.ui.form').form
  fields:
    category:
      identifier: 'category'
      rules:[
        prompt:'Specify a category']
```

**Comment by jlukic** [comment]
I think although it is a bit verbose, having empty rules help clarify exactly what rules are being applied. 

If you want to set up a list of 'usual suspects' to avoid redefining across multiple forms consider [setting up validation defaults](http://semantic-ui.com/behaviors/form.html#setting-site-defaults)

**Comment by avalanche1** [comment]
I think it's always best to let end user have a freedom of choice, if it's technically possible.
So it would be nice to be able to define a default rule, which would apply to all fields by default. And the user might or might not wish to explicitly specify type:empty if he so wishes.
I'd even make a PR if you concurred with my proposal.

**Comment by jlukic** [comment]
I think UX wise most forms should give user feedback for why a form has failed. Although it makes sense for developers to shorten the process of form validation by allowing shorthand, it will not allow for custom error messages for each input field.

Form validation I think needs a complete rewrite and I'm still wary at adding too many new features to its current iteration. In general I think the way form validation should work is something like this

* Developer creates form 
* Developer runs js pluging with a special flag `$('.form').form('create validation');`
* Form plugin runs in special interrogative mode, asking about each field, whether it should be validated, should be autofilled, etc. 
* Interrogative mode uses Chromiums [built in regex for autofill](https://gist.github.com/jlukic/6749676#file-gistfile1-js-L9) to guess form fields and then suggest common validation patterns. 
* After completing questions *interrogative mode* generates a form validation settings object that developer pastes back into code

**Comment by avalanche1** [comment]
Yep, that'd be really nice to have)
Can't wait for SUI 3.0 :smile:
