### ISSUE TITLE
[Form] Fieldset Does Not Support Flex

### ISSUE THREAD

**Issue by malacalypse** [Semantic-Org/Semantic-UI#2582]
http://jsfiddle.net/5h1qkf0n/

Unsure of whether the markup is correct, but when <div class="two fields"> is uses within a form, and one of the fields contains a dropdown select, the fields stack inelegantly at ~50% width instead of laying horizontally. (This is when the window is wide enough for them to lay side-by-side without reverting to responsive stacking.)

This happens regardless of whether the dropdown is wrapped in a .field wrapper or contains the field class directly.

**Comment by jlukic** [comment]
Swapping `fieldset` for `div` will fix. There appear to be some unclearable browser styles on fieldset that are not affected by our reset.
