### ISSUE TITLE
[Transition] gets destroyed by new transition call in onComplete

### ISSUE THREAD

**Issue by hpohl** [Semantic-Org/Semantic-UI#2583]
https://jsfiddle.net/zeneL1ha/3/

Calling .transition in onComplete causes the transition to not show at all but still change the visible state.

**Comment by jlukic** [comment]
This is happening for me only in FF and not chrome. I'll see if I can find a fix.

**Comment by hpohl** [comment]
It's also happening in Chrome 45.

**Comment by jlukic** [comment]
I'm testing in Chrome 43 and seems alright, but a few behind. I've marked this for next patch.

**Comment by jlukic** [comment]
This was modified in #2402, complete was not occurring at true "end of animation". `force visible` / `force hidden` is now called before `onComplete`

**Comment by hpohl** [comment]
Nice :+1:
