### ISSUE TITLE
search dropdown deletable labels behave like buttons - shouldn't they be buttons then ?

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2585]
There is some level of inconsistency between their semantic class and their usage in the context of the dropdown: they are labels that behave like buttons ?
Furthermore, it's not possible to reproduce the same graphic effect outside the dropdown (without adding some styles, of course).

Just saying - this is not complaining ;)

**Comment by jlukic** [comment]
I think when going by the SUI definition "a label displays content classification" they fit more under labels than buttons. 

Labels inside multiple dropdowns are subclassed versions of labels, squished to fit inside inputs. This is similar to how dropdown menus are modified when appearing inside `ui menu`
