### ISSUE TITLE
[Accordion] Rewrite to Remove JS Animations

### ISSUE THREAD

**Issue by SantzDesign** [Semantic-Org/Semantic-UI#2590]
This component should be optimized for better performance on modern browsers.

I would suggest making it like [Bootstrap's collapse](http://getbootstrap.com/javascript/#collapse), using `transition: height 0.3s ease;`, leaving aside the low-performant jQuery `.slideUp()` and `.slideDown()` functions.

Thanks!

**Comment by jlukic** [comment]
CSS transitions do not work with `height: auto`, however there is probably a way to handle this simply programmatically

**Comment by SantzDesign** [comment]
I know @jlukic! I'd love to help but I don't do JS. I'd suggest checking out how the Twitter guys are achieving it on their Bootstrap accordions. They don't transition `max-height`, they transition `height`.

**Comment by witrin** [comment]
It's really simple. Starting with the class `collapse` on toggle: Calculate the target height and set it in the `style` attribute. Add the class `collapsing` and remove `collapse`. At the end of the transition (by using a callback) add the classes `collapse` and `in`, and remove the class `collapsing` and the clear the `style` attribute. The inverse, starting with the classes `collapse` and `in`: Calculate the current height and set it to the `style` attribute. Add the class `collapsing` and remove the classes `collapse` and `in`. Change the height to `0` in the `style` attribute. At the end of the transition (by using a callback), add the class `collapse`, remove the class `collapsing` and clear the `style` attribute.

**Comment by GreggOD** [comment]
Just a note here guys, although what @witrin has said is totally plausible and great it must be known that animating height causes massive layout changes which is a heavy operation in the browser.

When doing animations you should always consider the cost of it, especially on mobile. I see people complaining about slow accordion animations on mobile. I mean if you consider what its doing you'll understand quickly why its slow.

Please Read: https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/
