### ISSUE TITLE
[Validation] - Update Label Styling

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2593]
I suggest adding the fol markup
```stylus
.prompt.label
		white-space: normal;
		text-align: center;
		margin-right: auto;
		margin-left: auto;
```
Current vs proposed: http://codepen.io/avalanche1/pen/WvJarg

**Comment by jlukic** [comment]
New style added for `2.1` for form validation, variables added to customize in form
![](http://i.imgur.com/SW8vDzM.png)

**Comment by avalanche1** [comment]
looks nice :)

**Comment by rashidali-pk** [comment]
how to change the label color ??
