### ISSUE TITLE
[Validation] - url rule error

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2595]
url rule throws `TypeError: e.fn.form.settings.regExp.url.match is not a function` in console
http://codepen.io/avalanche1/pen/oXdQxq/?editors=101

**Comment by jlukic** [comment]
This was fixed in `2.0.3`

**Comment by avalanche1** [comment]
I see. Some probs on http://atmospherejs.com then...

**Comment by avalanche1** [comment]
This rule sd only run if the field being validated is not empty.
I have an optional 'video' field which may be left blank. Thus I need it to be checked for valid URL format only if it has text inside.

**Comment by jlukic** [comment]
Use `empty` to validate for empty fields.
