### ISSUE TITLE
[Segment/Menu/Table] - Fix Doubled Borders in Some Attached Cases

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2599]
I noticed that my tables had a slightly different width from their attached menus while in a grid, see http://jsfiddle.net/zsu3k0nt/1/

It only seems to happen in a grid, and might be because the table width calculation is "less accurate" than the others? For example, looking at it now and I have a width of 260.750px on the segment and menu, but 260.000px on the table, which seems to end up getting rounded differently as follows:

![](https://i.imgur.com/4grsVlY.png)

You might have to change the width of the preview panel to see it in action.

**Comment by jlukic** [comment]
The borders should not be doubled between segment->menu and menu->table  when `attached`. I need to do more tests with mixed component attachment.

With regard to width being off by a partial amount on tables. That could be related to rounding with table, but I can't verify. Maybe `table-layout: fixed` might behave differently.
