### ISSUE TITLE
Modals in Tabs

### ISSUE THREAD

**Issue by BigGrecian** [Semantic-Org/Semantic-UI#2600]
Scenario : AJAX tab loads with caching set to false.

Result : Modal shows multiple times when the modal is displayed :+1: 

There needs to be a way of destroying a modal on page load so it can wipe the previous one.

http://jsfiddle.net/BigGrecian/heh9nuf2/

**Comment by jlukic** [comment]
I'm not sure I understand the issue. You are opening two separate modals on button click. I'd recommend just adding a class or id to distinguish.

**Comment by BigGrecian** [comment]
Ok sorry I haven't been clear, neither was the jsfiddle

Attempt 2 : http://jsfiddle.net/BigGrecian/heh9nuf2/1/

On 1st load of tab A : modal displays fine as Modal A

![image](https://cloud.githubusercontent.com/assets/12722365/8638413/bb04f9b8-2888-11e5-98be-abf806251d64.png)


Navigate to a different tab B, and now come back to Tab A : modal displays as follows  in Modal B
![image](https://cloud.githubusercontent.com/assets/12722365/8638420/d82670e4-2888-11e5-80ef-e51671c0dece.png)

As soon as you close Modal B which fades out  - Modal A is displayed, i.e the modal has been loaded to the client on the ajax tab load with the different php time and displays both.
You could open the ajax tab 2,3 times and this just increases the number of modals.

**Comment by jlukic** [comment]
You are opening two modals at once, this is not a bug.

**Comment by musemega** [comment]
That's really not an answer.  I'm experiencing the same thing with a Meteor page. 

In my case, a modal is being defined and shown on a "show details" button click.  

Then, the user navigates to a new route (Iron Router).  The page should be torn down.  

However, when the user navigates back (via the back button) two modal are being created when the "show details" button is clicked.  This does not seem right.

**Comment by jlukic** [comment]
From above
http://jsfiddle.net/vy1qbc9w/

From below
Check discussion of modals in meteor board, but you need to use `detachable: false` otherwise modal will be moved on init and Meteor wont properly tear down.

**Comment by king2** [comment]
I met same behaviour.

Assume, that we have a tabs with AJAX loaded content. We are loading tab A, with modal HTML inside, and we are trying to init this modal after tab loading. OK, Semantic gets this window from tab's DOM and places it into body. When we are trying to display modal window, it shows window for us. So far so good.
We have modal attached to body and no modal HTML in ajax tab DOM.

Then, we are selecting tab B, and then tab A again. OK, tab A loads AJAX content AGAIN, with ANOTHER FRESH modal HTML inside, so now we have two modal with same id - one from previous load attached to body, and another, fresh loaded. After tab content loading complete, it runs modal init code again, it moves modal code into body, and from this time we have two modals (with same id) attached to body.

So, when we are trying to show our modal, we will get TWO modals on screen.

Next reload, three modals, and so on.

As I understand, it is needed at modal init to check if we have modal with same selector attached to body, and remove it from body if yes.

Now I have to do something like this:
`$('.ui.dimmer.modals > ' +modal_selector).remove();`
just before init modal in tab's code.
