### ISSUE TITLE
[Popup] Apply Variations Even if Pre-Existing Content

### ISSUE THREAD

**Issue by vsivsi** [Semantic-Org/Semantic-UI#2601]
Hi, some of this may be a documentation issue, but I also think there's a bug here.

In the following sample code, all six buttons end up with popups, but only the popups of buttons 1 and 6 are inverted. It seems that either popup 2 or 3 should work (I'm not sure which, this is where the docs could be improved) and popups 4 and/or 5 should definitely work IMO, so that seems like a bug...

Or does the `inverted` variation only apply to non-html popups (text provided via a `content` string)?

![screen shot 2015-07-11 at 5 26 40 pm](https://cloud.githubusercontent.com/assets/428642/8635846/06326782-27f2-11e5-8eb3-87934276cad8.png)

Initializing JS:
```js
$('#button1').popup();
$('#button2').popup();
$('#button3').popup();
$('#button4').popup({
  variation: "inverted"
});
$('#button5').popup({
  inline: true, 
  variation: "inverted"
});
$('#button6').popup({
  content: "This is button #6",
  variation: "inverted"
});
```

HTML:
```html
<body>
  <div class="ui container">
    <h1 class="ui header">Semantic UI Button Popup Test</h1>
    <div class="ui panel">
      <div id="button1" class="ui button" data-content="This is button #1" data-variation="inverted">
        Button 1
      </div>
      <div id="button2" class="ui button" data-variation="inverted">
        Button 2
      </div>
      <div class="ui popup">
        This is button #2
      </div>
      <div id="button3" class="ui button">
        Button 3
      </div>
      <div class="ui popup" data-variation="inverted">
        This is button #3
      </div>
      <div id="button4" class="ui button">
        Button 4
      </div>
      <div class="ui popup">
        This is button #4
      </div>
      <div id="button5" class="ui button">
        Button 5
      </div>
      <div class="ui popup">
        This is button #5
      </div>
      <div id="button6" class="ui button">
        Button 6
      </div>
    </div>
  </div>
</body>
```

**Comment by vsivsi** [comment]
After some more poking around in DOM nodes generated by Buttons 1 and 6 in the above example, I see that they add `class="inverted"` to the popup `<div>` elements they create.

So, the following variation of Button 3 works:
```html
      <div id="button3" class="ui button">
        Button 3
      </div>
      <div class="ui inverted popup">
        This is button #3
      </div>
```

Knowing that solves my issue, and it appears that specifying `variation = "inverted"` really is only for when Semantic will be generating the popup from content/title strings. This is confusing and the documentation should really describe the use of the `inverted` class and the relationship between that and the inverted variation as it pertains to popups.  Would have saved me a couple of hours...

**Comment by jlukic** [comment]
You hit the nail on the head. Variations are only applied programmatically currently when the popup is dynamically generated. It does not modify a pre-existing popup. 

To make this simpler and safe headache for other people I think it should just uniformly apply `variation` even if popup is pre-existing.

**Comment by vsivsi** [comment]
Agreed.  Calling `.popup({variation:"inverted"});` and getting a non-inverted popup just seems wrong.

**Comment by jlukic** [comment]
Added in `2.1`

**Comment by vsivsi** [comment]
Awesome, thanks!

**Comment by jlukic** [comment]
Example jsfiddle
http://jsfiddle.net/rnrhadot/

**Comment by tomcowle** [comment]
Hi, sorry, I realise this is an old issue, I am having the same problem with the 'wide' variation, did the fix only apply to inverted? Go ahead and update the fiddle using 'wide' instead of 'inverted' and you'll see the issue.
