### ISSUE TITLE
Pointer cursor disappears from the links in the menu after manually resize page in Chrome

### ISSUE THREAD

**Issue by mzygmunt** [Semantic-Org/Semantic-UI#2604]
Problem: pointer cursor disappears from the links in the menu after manually resize page in Chrome (only in Chrome, in Safari works fine)
JSFiddle: https://jsfiddle.net/rduvhn8u/51/
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by avalanche1** [comment]
Update to Chrome 44 and report here again.
On the same setup I don't see that prob.

**Comment by mzygmunt** [comment]
Under Chrome 44 works fine.
