### ISSUE TITLE
[Sticky] Rails skipping when rail higher then screen.

### ISSUE THREAD

**Issue by fpoirier1** [Semantic-Org/Semantic-UI#2605]
Hi,

The rail's seem to be skipping up when it is goes out the screen and you start scrolling. See the codepen repo here : http://codepen.io/fpoirier1/pen/mJLLMP

Am I missing something here ?

**Comment by jlukic** [comment]
I'm not seeing the issue.  It appears to be sticking correctly. Can you clarify what you mean?

**Comment by fpoirier1** [comment]
Yes, I understand for continuing to scroll when content is heigher than the screen. What I mean is if you scroll slowly, you see the rail skipping.

Like the example below, shouldn't the **Stuck Content** still be visible? It seems to be jumping from Item 0 to Item 6...

<img width="635" alt="screen shot 2015-07-12 at 11 41 07 am" src="https://cloud.githubusercontent.com/assets/1587658/8638483/ecae8720-288a-11e5-85e2-7b39f19ea5da.png">

**Comment by jlukic** [comment]
Sorry my screen was too tall. I'm seeing the issue now.
http://codepen.io/anon/pen/NqMZGQ

**Comment by fpoirier1** [comment]
Thanks ! At first glance, when the `position:fixed` is not  apply the `top` property is subzero based on the context but when it becomes `position:fixed` the `top`property must be set relatively to the `Window`.

**Comment by jlukic** [comment]
Scroll position is adjusted with `requestAnimationFrame` which means the delta has to be calculated from last scroll position. This is probably an issue with edge conditions.

**Comment by jlukic** [comment]
JSFiddle of next
http://jsfiddle.net/38nngpww/
