### ISSUE TITLE
Table structured + selectable bug

### ISSUE THREAD

**Issue by wrycu** [Semantic-Org/Semantic-UI#2606]
If you make a table both structured and selectable and create an entry with a height of more than one row, then mouse over entries, only the first entry properly highlights.

Expected Behavior:
![correct](https://cloud.githubusercontent.com/assets/4709746/8639089/18ba920c-289d-11e5-90f2-f2c80027c864.png)

Unexpected Behavior:
![incorrect](https://cloud.githubusercontent.com/assets/4709746/8639091/256ec176-289d-11e5-9723-3e1606e2abec.png)

**Comment by jlukic** [comment]
I don't think there's any way to fix this with CSS selectors. CSS is unaware of `colspan` and `rowspan`. You will probably have to use custom JS for this case.
