### ISSUE TITLE
[Checkbox] - Review Issues with Colors on Focus

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2607]
`.slider` and `.toggle` don't change color and remain grey if toggled by pressing `enter` or `spacebar`.
If you click anywhere on the page after that - color appears...
Don't know about regular `.checkbox` - needs testing.

**Comment by avalanche1** [comment]
Also, if I toggle it by clicking, then tab away to next field, then tab back - instead of blue it becomes gray!

**Comment by jlukic** [comment]
This seems to be an issue with browser being lazy at updating css with pseudo selectors like `:checked`. I'm not sure what conditions trigger this.

**Comment by avalanche1** [comment]
Ok, this causes this 'mystery':
```
/*--------------
  Active Focus
---------------*/

.ui.checkbox input[type="checkbox"]:indeterminate:focus ~ .box:before,
.ui.checkbox input[type="checkbox"]:indeterminate:focus ~ label:before,
.ui.checkbox input[type="checkbox"]:checked:focus ~ .box:before,
.ui.checkbox input[type="checkbox"]:checked:focus ~ label:before {
  background: #f9fafb;
  border-color: rgba(34, 36, 38, 0.35);
}
```
We sd remove gray background being applicable on focus.
Maybe use diff opacity for showing focus.

**Comment by jlukic** [comment]
This occured because of css specificity changes when i removed `input[type="checkbox"]` from `:checked` rules. 

Resolving by adding `activeFocus` variables and styles.. fix coming shortly

**Comment by jlukic** [comment]
Example from `next` with fixed checkbox focus
http://jsfiddle.net/65rgdhdo/

**Comment by avalanche1** [comment]
Nice!
But for `active` checkbox and slider  there is no special styling when they have focus. So no way to determine if they are currently selected. (unlike toggle, which changes color slightly)

**Comment by jlukic** [comment]
They change color subtly.

**Comment by avalanche1** [comment]
:microscope: ah, yes!
