### ISSUE TITLE
[Build] Automate Atmosphere Deploy

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2608]
See https://github.com/percolatestudio/atmosphere/issues/395#issuecomment-120751201.
I thought everything was automated...

**Comment by jlukic** [comment]
This needs to be added to admin scripts used to register component repos, as part of deploy process.
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/register.js

I wish they just auto-updated with tagged git releases...

**Comment by jlukic** [comment]
Oh wait. I forgot we're using [autopublish](https://autopublish.meteor.com/).

**Comment by jlukic** [comment]
Will have to see how this goes..

**Comment by avalanche1** [comment]
2.0.4 updated fine
https://atmospherejs.com/semantic/ui-css

**Comment by jlukic** [comment]
I manually pubilshed the css release. Autopublish is not working for the rest. I contacted the author he's on vacation. Fix will come soon

**Comment by avalanche1** [comment]
Could you push `2.0.7`?

**Comment by jlukic** [comment]
Published, auto-publish is still failing..

**Comment by avalanche1** [comment]
Jack, any progress on this?
https://atmospherejs.com/semantic/ui-css is two releases behind.

**Comment by kPanesar** [comment]
Any plans on updating the atmosphere package to the latest version soon? A workaround if not would be helpful.
