### ISSUE TITLE
[Checkbox] - Fitted .toggle is taller than .slider and standard ones

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2609]
![image](https://cloud.githubusercontent.com/assets/10534563/8639655/03c843d0-28f2-11e5-81de-d649f02f7934.png)

**Comment by jlukic** [comment]
This is normal. I think it's okay for different styles of checkboxes to have different heights. The important thing is that their height accurately matches the size of their contents.
