### ISSUE TITLE
[Grid] - ui four column grid inside of a row doesn't work (Fiddle provided)

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#2611]
Not sure if i'm doing anything wrong here, but kind of expected this to work?

http://jsfiddle.net/r3772wkt/

Check the 4th column, it's on a new row.

**Comment by Illyism** [comment]
Use `four column row` instead.

https://jsfiddle.net/illyism/1quLm7Lv/1/

**Comment by jlukic** [comment]
Check nested grid example, nested grid should still appear inside `column`
http://jsfiddle.net/nh1zuxko/

http://semantic-ui.com/collections/grid.html#nesting-grids
