### ISSUE TITLE
Restrict usage questions to SO

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2612]
I suggest we forward all [usage questions](Semantic-Org/Semantic-UI/labels/Usage%20Question) (like you practiced some time ago) to Stackoverflow. This will free up some of your time and will help build some hype on SO, as the more questions, the more attention SUI gets. Am I right?
And maybe you could once a week rummage through long unanswered questions on SO and help some folks in case they get really stuck..

If you agree, I would amend the [guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

**Comment by jlukic** [comment]
I understand when people aren't sure whether their issue is a bug or just improper usage. It seems to me for people who are uncertain to post here. Although I definitely need some help moderating.

I am going to start being a bit harsher on people who don't bother following the bug report guidelines, omitting test cases etc. Not worth the comment anymore.

**Comment by avalanche1** [comment]
btw, I've already amended them once!
strange, that you've removed https://github.com/Semantic-Org/Semantic-UI/commit/9b661cca3dedb124222cb7a1098d91769942149f#diff-6a3371457528722a734f3c51d9238c13

**Comment by pcj** [comment]
I certainly support shunting away entry-level usage questions to SO.  GitHub issues can be used for whatever, obviously, but when issues bloat up, it creates mental baggage (for you, as a the project head,  that they need to be cleaned up), and it dilutes the experience for people like me, which check up on new issues once a week or so.  SO is a better place for Q&A, and provides better discoverability and later evolution of the answers.

**Comment by jlukic** [comment]
Actually, I see your point and I think I agree.

**Comment by philrykoff** [comment]
This can be closed, as it's already being done  (gitter).
