### ISSUE TITLE
loading semantic.js with defer attribute on script tag triggers "no css animation matching" error

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2613]
Hi,

this usually happens on chrome or webkit with something like
```
<link href="semantic.css" />
<script defer src="semantic.js"></script>
<script defer src="custom.js"></script>
...
<select multiple class="ui dropdown"><option value="me" selected>me</option></select>
```
where custom calls `$('.ui.dropdown').dropdown()` 

Is the missing "a.ui.label.hidden.transition" animation that important  - semantic could just ignore it instead of erroring out ?

I'll make a jsfiddle to demo the issue if support for "defer" loading is something you want.

**Comment by kapouer** [comment]
Oh, i didn't explained what was happening: semantic.js + custom.js are run before semantic.css is loaded - which results in missing css.

**Comment by jlukic** [comment]
Stylesheets should be blocking, I'm not sure in what way they could be affected by deferring javascript.

**Comment by kapouer** [comment]
Here's a test case
http://kiwi.edagames.com/~eda/semantic-defer-2613.tar.gz

i've put it online, but odds are against me and the problem doesn't reproduce with my bandwidth.
It does everytime on localhost.
The problem is triggered by initializing a multiple select with one selected option - it animates the adding of the option before the stylesheet is fully loaded.
After a while i read this
http://www.html5rocks.com/en/tutorials/speed/script-loading/
and stopped using defer...
