### ISSUE TITLE
Modals look weird

### ISSUE THREAD

**Issue by tillkruss** [Semantic-Org/Semantic-UI#2614]
The basic modals started to look weird since the upgrade to version 2. I'm only including the `semantic.min.css` and `semantic.min.js` from the `/dist/` folder. Am I missing a theme or something?

This is how they look:
![screen shot 2015-07-13 at 19 01 14](https://cloud.githubusercontent.com/assets/665029/8648289/f0a61836-2991-11e5-9526-c0b7ab398788.png)

This is how I exspect them to look:
![screen shot 2015-07-13 at 19 01 34](https://cloud.githubusercontent.com/assets/665029/8648318/3d134bc6-2992-11e5-937e-d2f63493413e.png)

**Comment by Illyism** [comment]
You probably want to include your HTML.

**Comment by tillkruss** [comment]
<div class="ui basic editnag modal">
        <i class="close icon"></i>
        <div class="header">Title</div>
        <div class="content">
            <div class="image"><i class="warning sign icon"></i></div>
            <div class="description"><p>Lorem Ipsum dolor sit amet.</p></div>
        </div>
        <div class="actions">
            <div class="two fluid ui inverted buttons">
                <div class="ui red basic inverted button"><i class="remove icon"></i> Edit</div>
                <div class="ui green basic inverted button"><i class="checkmark icon"></i> Okay</div>
            </div>
        </div>
    </div>

**Comment by Illyism** [comment]
[Fiddle](https://jsfiddle.net/illyism/bq6ydyqp/) for the [basic](http://semantic-ui.com/modules/modal.html#basic) example.

**Comment by jlukic** [comment]
See release notes for 2.0, specifically breaking changes for `image content` on modal.
https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md#version-200---june-30-2015

**Comment by Illyism** [comment]
Isn't this a docs issue? I copied over the [basic code example](http://semantic-ui.com/modules/modal.html#basic) but it still has the breaking change not corrected. The code for the modal is also different when you run the code versus the source code you see when you expand to view the code.

**Comment by jlukic** [comment]
Yes it is a docs issue. I didnt realize it was incorrect in docs.

**Comment by tillkruss** [comment]
New sample code works great, thanks guys!
