### ISSUE TITLE
[Visibility] refreshOnResize Missing Default Value

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#2615]
1."settings.refreshOnResize" only appear once in the code, and it seems invalid when window.resize
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/visibility.js#L167

2.Docs use "settings.checkOnResize" but the code use "settings.checkOnRefresh"?
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/visibility.js#L1175

3.Can one element use visibility twice ? I need different offset but it seems invalid when using visibility twice.

thank you so much!

**Comment by jlukic** [comment]
1/2) . refreshOnResize is missing its default setting. This is a typo and a bug. 

* `checkOnRefresh` checks position anytime it refreshes (which could be other reasons)
* `refreshOnResize` should be a separate setting that determines whether browser resize should refresh positions

3) You can overload any UI with two modules by changing the namespace `$('.foo').visibility( namespace: 'visibility2'});` I intend to put examples of this in the module docs whenever I get time.

**Comment by faller** [comment]
thanks for answering.
