### ISSUE TITLE
Problem with icon in fluid button under Firefox

### ISSUE THREAD

**Issue by mzygmunt** [Semantic-Org/Semantic-UI#2617]
Problem: Problem with icon in fluid button under Firefox (only Firefox).
JSFiddle: https://jsfiddle.net/rduvhn8u/67/
Screen: ![image](https://cloud.githubusercontent.com/assets/13297558/8653128/0a8a8d2c-2983-11e5-862f-29b70568d9e3.png)
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by jlukic** [comment]
See [flegbugs issue #9](https://github.com/philipwalton/flexbugs#9-button-elements-cant-be-flex-containers)

I probably should swap fluid buttons from using flex since many people use this pattern.

**Comment by jlukic** [comment]
Removed flex from `fluid`
