### ISSUE TITLE
modal {inverted: true} does nothing

### ISSUE THREAD

**Issue by mkoczorowski** [Semantic-Org/Semantic-UI#2618]
$loginModal.modal(
						closable: false
						observeChanges: true
						inverted: true
						blurring: true
)

setting inverted true /false does nothing for me

**Comment by jlukic** [comment]
http://jsfiddle.net/chfaa5cj/

**Comment by nblackburn** [comment]
I have having the same issue

**Comment by topclaudy** [comment]
This happens when we have multiple inverted modals on the same page. The 'inverted' class is not always applied to the dimmer.
