### ISSUE TITLE
can close modal with escape key even if closable is set to false

### ISSUE THREAD

**Issue by luisrudge** [Semantic-Org/Semantic-UI#262]
today, we can still close a modal even if the closable option is set to false.

**Comment by larsbo** [comment]
I think this should be achieved by two options. There are use cases where the previous behavior (modal not closable by clicking but by pressing escape) is desired e.g. a slideshow with clickable arrows inside a modal.

The description for the ```closable```option mentions only the click behavior, by the way :wink:
> Setting to false will not allow you to close the modal by clicking on the dimmer

**Comment by evenfrost** [comment]
In my project I need exactly this behaviour, i.e. prevent closing a modal when clicking on the dimmer, but allow this on pressing Esc button. Tried to pass `closable: false, keyboardShortcuts: true` options, but this didn't work.

**Comment by smartm0use** [comment]
What does `keyboardShortcuts` stand for?
I need the same behaviour, prevent closing when clicking on the dimmer, but allow closing when pressing Esc button. How can I reach that?

**Comment by Banandrew** [comment]
@smartm0use If you need this functionality, you can fork the modal component and implement the changes by @larsbo that you can find here #3625. Read the first post to understand how to use it. Also, since you’re forking the modal, don’t forget to exclude it from being built in `semantic.json`.
