### ISSUE TITLE
Popup broken when inside .ui.container

### ISSUE THREAD

**Issue by ksr583** [Semantic-Org/Semantic-UI#2620]
Check this [Codepen](http://codepen.io/krobinson/pen/gpKMPQ).

When I put a triggering element for a popup inside of a .ui.container, the popup doesn't show up. Not a problem without the container. I tried several different settings to try and get around this, to no avail.

**Comment by ksr583** [comment]
To clarify, it only seems to matter if the triggering element is inside the container.

**Comment by jlukic** [comment]
Adding your test case to the open issue for next milestone. #2526
