### ISSUE TITLE
Using <b> or <span> inside .ui.icon.message break everything  :)

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#2622]
very strange bug !

http://jsfiddle.net/erf2zsLx/

<img width="586" alt="capture d ecran 2015-07-13 a 23 25 07" src="https://cloud.githubusercontent.com/assets/359847/8661215/6c902c2e-29b6-11e5-91d0-8a37ec114055.png">

**Comment by jlukic** [comment]
Icon message requires a content wrapper otherwise all elements will have flex rules applied.

**Comment by jlukic** [comment]
http://jsfiddle.net/khp256ud/

**Comment by deneuxa** [comment]
oups OK sorry !

2015-07-13 23:39 GMT+02:00 Jack Lukic <notifications@github.com>:
