### ISSUE TITLE
[API] Setting global api setting does not affect search

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#2623]
I tried to set a global do not cache for all search boxes on my site via:

`$.fn.api.settings.cache = false;`

But this did not seem to have any affect on my search. See the JSFiddle

https://jsfiddle.net/rduvhn8u/68/

Additionally, `onResponse` is working in my version of semantic (2.0.2) but does not get called in the "next" version.

**Comment by jlukic** [comment]
The default api settings are overwritten by default search settings.

Try
```javascript
$.fn.search.settings.apiSettings = { cache: false };
```

**Comment by fpayer** [comment]
It would be useful to have have global settings be inherited by the search settings

**Comment by jlukic** [comment]
I am happy with the existing setup.
