### ISSUE TITLE
[Dropdown] Search selection does not clear placeholder text when placed inside a menu

### ISSUE THREAD

**Issue by mxth** [Semantic-Org/Semantic-UI#2624]
http://jsfiddle.net/rduvhn8u/69/
Try to search something. The default text isn't filtered in the second dropdown.

I believe this is where the problem comes from
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2723

**Comment by jlukic** [comment]
Yep tis bug

**Comment by jlukic** [comment]
Fixed
