### ISSUE TITLE
Bug showing videos on modals

### ISSUE THREAD

**Issue by csilvav** [Semantic-Org/Semantic-UI#2625]
I have been coding an App that work with media and interactive UI, so when I was trying to display a YouTube video in any modal everything was Ok, although when I was going to change from standard view to full-screen mode, the video and the modal did crashing.

**Comment by owenzoocha** [comment]
Same here

**Comment by jlukic** [comment]
I'd love to solve with a test case.

**Comment by nicely** [comment]
Same here not working on Chrome Browser

**Comment by avalanche1** [comment]
Closing until there's a test case.
