### ISSUE TITLE
[Dropdown] Selecting  Value in Original <select> should adjust Rendered Dropdown

### ISSUE THREAD

**Issue by quentinlampin** [Semantic-Org/Semantic-UI#2626]
I've encountered multiple bugs when using semantic UI's dropdown to prettify a `select multiple` bound to an angular controller.

Issues arise 
- when the controller updates the selection, e.g. when clearing the model once the form is submitted. In that case, selection labels are not cleared, the UI does not reflect the model state.
- when `dropdown('clear')` is used, causing angular to raise an error (probably trying to access the length of the selection array which has been wiped by `dropdown('clear')`).

The following plunker shows the encountered issues:
http://plnkr.co/edit/r93SZXKQ8w5pAzlD1TlK?p=preview

**Comment by jlukic** [comment]
Thanks for the thorough test case, its appreciated. 

Refresh does not currently automatically modify state to match `<option>` selection. This would be considered an enhancement.

**Comment by quentinlampin** [comment]
Thanks for the feedback. I understand your opinion, yet I believe we should
address it sooner than later as I see quite a lot of cases where this
would bite again.
In my case, this was in a form  that needs to be refreshed once the user
press the submit button. Think of an address bar a la gmail where you type
in a few letters and, when matched, add the recipient's name as a label in
the field. once the mail is sent, the field needs to be cleared...

Obviously, you could suggest me a solution without angular but this
framework is quite popular and that I'm sure issues like this one will pop
up often.

That said, I'm willing to help but I need help/hints as where to start.

On a side note, for the time being, it might be interesting to put a
warning in the docs on that matter.

Sorry for the long post!

**Comment by jlukic** [comment]
Dropdown now watches for `change` event on original `<select>` and automatically sets selected values. Since there is no way to generically "listen" for changes in a DOM property outside of  the poorly adopted [Object Watch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch) event listeners.
