### ISSUE TITLE
[Validation] Legacy Settings Detection Incorrectly Duck-Types

### ISSUE THREAD

**Issue by smangelsdorf** [Semantic-Org/Semantic-UI#2629]
JSFiddle: http://jsfiddle.net/jev4qec3/1/

If it's relevant, I'm using Chrome.

I hit this problem while porting an application forward from Semantic UI 1.x. After refactoring my validations to use the new form validation API, one form was still reporting the following error:

```
Form: Starting in 2.0 forms now only take a single settings object. Validation settings converted to new syntax automatically.
```

After that, attempting to submit the form gives the following error:

```
Uncaught Error: Syntax error, unrecognized expression: #[object Object] 
```

The JSFiddle linked above has validations configured with an added underscore to work around the issue. Removing the underscore triggers the error.

**Comment by jlukic** [comment]
It looks like an object is being passed in as a validation identifier, I'm unsure the exact issue without a test case, but it seems clear to me that `get field` should do some basic type checking.

**Comment by jlukic** [comment]
I've gone ahead and added type validation, if you have a test case that produces the error when passing in a normal string identifier let me know.

**Comment by smangelsdorf** [comment]
@jlukic: I'm not sure if I'm understanding you correctly, but I may not have explained myself clearly.

I followed this example [from the documentation](http://semantic-ui.com/behaviors/form.html#validation-definitions):

```javascript
$('.ui.form')
  .form({
    fields: {
      name: {
        identifier  : 'name',
        rules: [
          {
            type   : 'empty',
            prompt : 'Please enter your name'
          }
        ]
      },
      skills: {
        identifier : 'skills',
        rules: [
          type   : 'minCount[2]',
          prompt : 'Please select at least two skills'
        ]
      },
      // ....
    }
  })
;
```

The specific issue is when instead of `skills`, the second field is called `identifier`. In that case, Semantic UI appears to detect the top level `fields` object as being an old style validation because it has an `identifier` property. (When in fact, the `identifier` property is just a validation on a field called `identifier`)

And then, later in the code, attempting to treat the validations for the field `identifier` as an identifier causes the error.

**Comment by jlukic** [comment]
Sorry I think the first post when I visited didn't have a test case (or i missed it). I'll take a look at a fix.

**Comment by jlukic** [comment]
Sorry about the confusion, fixed in patch.
