### ISSUE TITLE
why does semantic ui use ui.grid[class*="center aligned"]  not ui.grid.center.aligned for css selector?

### ISSUE THREAD

**Issue by liangzai-cool** [Semantic-Org/Semantic-UI#2630]
i use semantic ui 2.0.3 & angularjs 1.4.2  for admin system,
for example bellow :
```html
<div ng-class="(1 == 1 ? 'ui middle aligned center aligned grid' : '')">
</div>
```
but i get bellow:
```html
<div class="ui middle aligned center grid" ng-class="(1 == 1 ? 'ui middle aligned center aligned grid' : '')">
</div>
```
just one class `aligned` added, this maybe angularjs bug, but i don't understand why not use `ui.grid.middle.aligned` and `ui.grid.center.aligned` for css selector?

and i found the sematic ui 0.9.5 use the css selector like `ui.grid.middle.aligned`, can you tell me why change it ?

thanks!

**Comment by jlukic** [comment]
See #396 and the discussion there.

**Comment by bitIO** [comment]
Sorry to bug you on a closed issue but this is still happening to me in Meteor and I'm still not sure which is the solution? I keep on having one aligned and that breaks the layout. What am I missing?
