### ISSUE TITLE
Semantic-UI 2.0: Specify docs directory?

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#2633]
Hi there,

in Semantic UI 1.0 together with Semantic-UI-Docs there has been the file
> /tasks/admin/docs.json

where one could specifiy a directory to create the output of Semantic UI "build-docs" process.
Apparently, after installing Semantic UI 2.0, the above mentioned file "docs.json" doesn't seem to exist anymore.

Could you please clarify, how to specify the docs directory?

Thanks,
Sascha.

**Comment by jlukic** [comment]
No problem, the path has been adjusted. We specify this in the [Running Docs Locally](http://semantic-ui.com/introduction/advanced-usage.html#running-docs-locally) section of docs.

The new file
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/docs.js

**Comment by srissel** [comment]
Thanks a lot for your reply!
BTW, is learnsemantic.com still valid as a learning site?

**Comment by jlukic** [comment]
My aspiration is porting over the most relevant material to main docs, but I haven't finished. I think having separate sites was confusing people, and I know from the traffic a lot of visitors never went over there.
