### ISSUE TITLE
Vertical Icon Button Toolbar incorrectly aligned.

### ISSUE THREAD

**Issue by pjacferreira** [Semantic-Org/Semantic-UI#2634]
Hi,

I was trying to create a vertical toolbar and I noticed that, after the 1st button, all the buttons were slightly pushed to the left.

I tracked down the problem to following css rule:
.ui.buttons>.basic.yellow.button:not(:first-child) {
  margin-left: -2px;
}

Even though, the 1st and last button have the border radius correctly (in the vertical button group),
the rule above incorrectly compensates the margin (i.e. as if the toolbar was horizontal).

Example Code:
<div class="ui icon vertical buttons">
        <button class="ui green basic button">
          <i class="green thumbs up icon"></i>
        </button>
        <button class="ui yellow basic button">
          <i class="yellow outline thumbs up icon"></i>
        </button>
        <button class="ui black basic button disabled">
          <i class="comment icon"></i>
        </button>
        <button class="ui red basic button">
          <i class="red thumbs down icon"></i>
        </button>
</div>

**Comment by avalanche1** [comment]
Closing until there's a test case.
