### ISSUE TITLE
[Validate] minCount does not work for 1

### ISSUE THREAD

**Issue by princeandrew01** [Semantic-Org/Semantic-UI#2636]
Good Day,

I was using the minCount validation to validate a multiple select field. initially I just wanted to make sure that the field was not empty, so I tried to use the empty but that did not work .Then I tried the minCount[1] and it did not validate. Finally I changed the 1 to 2 and it worked but it is checking for 2 elements.

I am trying to use JSFiddle to post some sample code but I am not getting it to display the multi select dropdown. 

EDIT: Updated the JSFiddle:
has minCount set to 1: http://jsfiddle.net/rduvhn8u/79/
has minCount set to 2: http://jsfiddle.net/rduvhn8u/78/

**Comment by jlukic** [comment]
Fixed in `next`

**Comment by jlukic** [comment]
I've added examples for each validation type to docs.
http://semantic-ui.com/behaviors/form.html#rule-examples

**Comment by princeandrew01** [comment]
Thanks so much! Great examples!
