### ISSUE TITLE
[Dropdown] "set selected" does not work for empty ('') value (using placeholder: false)

### ISSUE THREAD

**Issue by michtill** [Semantic-Org/Semantic-UI#2637]
http://jsfiddle.net/y7axjw2y/2/

I am using .ui.selection.dropdown with placeholder:false to have the empty value option in the list.
User can select it to set value ''.
But I am not able to set this option in code. In fact the component is not able to do it it self on initiate.
If I set any other value as the value of hidden input it is selected as option on start and the onchange 
event is called on the input. But by using '' for the value='' option it does not work. 

Calling .dropdown('set selected', '') does not work.

In fact calling .dropdown('clear') does not work, if there is not the div with class "default text" and any non empty content. &lt;div class="default value"&gt;&lt;/div&gt; does not work too.

So the empty value option is possible to have in the list now, but it is not fully supported by the component.

In any case thank you for all nice component and this one as well!!!

**Comment by jlukic** [comment]
Demo with `next` branch
http://jsfiddle.net/ud2qxebd/

Clear will now correctly set value to "" when no placeholder. Fixed several placeholder issues, particularly with `restore defaults`.

Available in `2.1`

**Comment by michtill** [comment]
Hello,

Works now perfectly.

Thank you very much!

Michal Tiller
Dne 12. 8. 2015 0:17 napsal uživatel "Jack Lukic" <notifications@github.com

**Comment by jlukic** [comment]
Glad to know :)
