### ISSUE TITLE
Focus dropdown in semantic old version 0.19.3

### ISSUE THREAD

**Issue by KhadeerMojostreet** [Semantic-Org/Semantic-UI#2641]
Hi @jlukic 

When i press tab button on keyboard that time not focus dropdown in semantic old version 0.19.3. How to fix that issue? please give me suggestion

**Comment by KhadeerMojostreet** [comment]
Hi @jlukic 

I fond the issue i am using tabindex="0" add in div tag, but i want use only through css please give me any suggestion.

**Comment by jlukic** [comment]
Please use stackoverflow or gitter. This is a place for submitting bug reports for current SUI versions.
