### ISSUE TITLE
apiSetting onResponse seems not working properly

### ISSUE THREAD

**Issue by levelel** [Semantic-Org/Semantic-UI#2643]
I tried using standard type search box but always failed on prompting the fetched data from server.

At last I gave up, and tried hardcoding the data in onResponse method, still failing!

This one
```javascript
$('.ui.customers.search')
    .search({
        source: [{title: 'wil'}, {title: 'wilhelm'}];
    });
```
works fine, but

```javascript
$('.ui.customers.search')
    .search({
        apiSettings: {
            //action: 'search customers',
            url        : '/search/customers/{query}',
            onResponse: function (queryResponse) {
                return [{title: 'wil'}, {title: 'wilhelm'}];
            }
        }
    });
```
does not.

Why??

**Comment by levelel** [comment]
I've tested the url, it response the json object correctly. So it was not a server issue.

**Comment by jlukic** [comment]
http://semantic-ui.com/modules/search.html#/usage
Server response is different from local search object. Check docs.
