### ISSUE TITLE
Sidebar changes directions if called twice

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#2644]
I'm having a strange issue with sidebars. My page has two sidebars, one on the left and one on the right. The structure of my code means the sidebar function is called twice, once to initialise it, and once to attach an event to a button that will make it visible when in a mobile view:

    $('.primary.sidebar').sidebar({ transition: 'slide along' });
    $('.secondary.sidebar').first()
        .sidebar('attach events', '#navigation .item.show-resource-sidebar', 'toggle');

Fairly standard, and more or less how the documentation shows how to do it (without the first step though?)

My two sidebars are defined in the HTML as so (sorry, using HAML):

    .ui.left.vertical.primary.sidebar
    .ui.right.vertical.secondary.resource.sidebar

The primary sidebar is working as expected, however the secondary sidebar is behaving unusually. The initial `sidebar` call works fine, but when the second call to attach events is run, the sidebar moves and becomes a left sidebar. `Semantic-UI` is changing the class from `right` to `left` without me requesting it.

I've tried to replicate in a fiddle, and had partial success. I can't replicate it when my second call is to attach an event, it seems to work as expected, however if I ignore that and make two calls to the initialise itself, it is reproducing it.

https://jsfiddle.net/9hn5fw8w/1/

The second call to `dropdown` is commented out, and as you'll see it works correctly. But if you uncomment the second call, the sidebar is moved to the left of the screen.

**Comment by pareeohnos** [comment]
Slight update. I realised that my code was slightly bugged in terms of the order in which the code was running. The `attach events` call was occurring before the initialisation call. Here is a new fiddle replicating it now.

https://jsfiddle.net/wLukcamc/1/

**Comment by jlukic** [comment]
http://jsfiddle.net/pe8gv405/

If you use a different animation like `overlay` you need to specify the animation in JS as well. Appears to be working fine.

**Comment by pareeohnos** [comment]
I'm still seeing the issue, even specifying the transition in JS.
See these examples:

https://jsfiddle.net/o4w62q58/1/
https://jsfiddle.net/nsjzg2ts/1/

The first example is simply calling the sidebar initialiser twice. Both calls are explicitly specifying the transition effect, yet it is still being moved to the wrong side.

The second example is what was actually happening in my code due to the script order, but nevertheless still highlight the issue. The first call is attaching the events, and the second call is initialising it, which is again moving it the wrong side even with the transition specified

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sidebar.js#L123

**Comment by pareeohnos** [comment]
I guess it's not really a major issue. My issue was resolved by just having the code execute in the correct order. And I guess people shouldn't be attempting to initialise it twice, but it is slightly unexpected behaviour. No major reason to change though.

**Comment by jlukic** [comment]
It seems safe to remove and will reduce user headaches.
