### ISSUE TITLE
"Error: Cannot find module 'semantic/tasks/watch'"

### ISSUE THREAD

**Issue by TehCrucible** [Semantic-Org/Semantic-UI#2648]
Hi, hope someone can help, I'm pulling my hair out and can't figure out what's going wrong.  Steps so far, in a new empty project folder, using default options:
```
npm init
npm install --save semantic-ui
cd semantic
gulp build
```
Works fine so far. Everything installs, including dependencies, and builds OK.  The problem is integrating the tasks into a new gulpfile.  So I create a new, blank gulpfile.js at the root directory, require gulp and copy in the code to import tasks as per the documentation:
```
// Include gulp
var gulp = require('gulp');

var
  watch = require('semantic/tasks/watch'),
  build = require('semantic/tasks/build')
;
// import task with a custom task name
gulp.task('watch ui', 'Watch Semantic UI', watch));
gulp.task('build ui', 'Build Semantic UI', build));
```
This in itself is an issue as it won't run `gulp build ui` with the additional close brackets at the end of the `gulp.task` entries.  Remove those and then I get this error:
```
Error: Cannot find module 'semantic/tasks/watch'
```
Which doesn't make any sense because that's obviously the path.  Perhaps I'm just doing something stupid as I don't really have much experience with gulp.  Full exception listed below.  Hopefully someone can point me in the right direction.
```
C:\Users\jamie_000\OneDrive\Crucible\Crucible\testSite>gulp build ui
module.js:338
    throw err;
          ^
Error: Cannot find module 'semantic/tasks/watch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\jamie_000\OneDrive\Crucible\Crucible\testSite\gulpfile.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by TehCrucible** [comment]
Further to this, changing the path to the tasks to
```
./semantic/tasks/watch
```
Seems to work  for watch but running build fails with the following:
```
[13:59:23] Starting 'build-ui'...
Building Semantic
[13:59:23] Task 'build-javascript' is not in your gulpfile
[13:59:23] Please check the documentation for proper gulpfile formatting
```

**Comment by jlukic** [comment]
Hi, sorry this was a mistake on my part. Sub-tasks of build and watch were undefined causing `gulp.run` to fail if you just import those tasks without also having their sub tasks imported. 

I've added the sub tasks as a separate collection in `tasks/collection/` and required them from `tasks/build/`
