### ISSUE TITLE
Windows line endings in some (5) less files

### ISSUE THREAD

**Issue by pawtom** [Semantic-Org/Semantic-UI#2649]
I don't know if this is an issue, but the following files have Windows line ending, the rest of the files has Linux line endings.

semantic/src/definitions/elements/image.less        
semantic/src/definitions/modules/accordion.less        
semantic/src/definitions/modules/embed.less        
semantic/src/definitions/modules/nag.less        
semantic/src/definitions/modules/popup.less

**Comment by jlukic** [comment]
Thanks the headsup is appreciated. Unfortunately this will mess with git history, but worth it to fix. Not sure where they were introduced...
