### ISSUE TITLE
[Install Error] Error with "gulp install"

### ISSUE THREAD

**Issue by timdoes** [Semantic-Org/Semantic-UI#2650]
Hi.

I am running into an error during the install on my mac.

```
npm install semantic-ui
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
\
> semantic-ui@2.0.3 install /Users/user/Project/node_modules/semantic-ui
> gulp install

module.js:338
    throw err;
          ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/timdoes/Projects/react-starter/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "semantic-ui"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.0.3 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.0.3 install script 'gulp install'.
npm ERR! This is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Project/npm-debug.log
```

Thanks,
-Tim

**Comment by jlukic** [comment]
Maybe https://github.com/jgoux/generator-angulpify/issues/3#issuecomment-61510802

I'd just recommend trying to clear `node_modules` if possible and re-install.

**Comment by timdoes** [comment]
Thanks @jlukic 

That fixed the first install problem. But now the install hangs.

```
Installing
------------------------------
Installing to semantic/
Copying UI definitions
Copying UI themes
Copying gulp tasks
Adding theme files
Creating gulpfile.js
Creating site theme folder /Users/user/Project/semantic/src/site/
Adjusting @siteFolder to:  site/
Creating src/theme.config (LESS config) /Users/user/Project/semantic/src/theme.config
Creating config file (semantic.json) /Users/user/Project/semantic.json
Install complete! Navigate to semantic/ and run "gulp build" to build
[10:32:53] Finished 'install' after 2.27 min
```
It hangs right after the line saying Finished 'install' for at least 20 minutes.

Then I hit `Control + C` to exit the process and Navigate to semantic/ and run "gulp build" to build and get the following error:

```
semantic(master) > gulp build
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-help'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/Project/semantic/gulpfile.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Thanks again for any help on this. It is much appreciated!

**Comment by jlukic** [comment]
Peer dependencies unfortanately install after the install scripts finish.  If you hit `ctrl+c` you are cancelling the peer deps install.

Are you on a particularly slow connection?

**Comment by timdoes** [comment]
hmm... that's strange. My download speed is 120 Mbps. I guess I will have to manually install them.

Thanks for taking the time to look at this with me.

-Tim

**Comment by Nickersoft** [comment]
@jlukic I have experienced this issue before as well. I don't believe this "hanging" is the result of the installation of peer dependencies. During the initial install process, you must install Semantic UI via NPM, Ctrl-C after it starts hanging, navigate to node_modules/semantic-ui and run `npm install`, *then* navigate back to the semantic folder and run `gulp build`. Once these initial steps have been taken, upgrading Semantic UI will install peer dependencies correctly. During upgrades, instead of hanging, NPM outputs the installation status of the peer dependencies after `Finished 'install'...` appears. For some reason it only hangs during the initial install. Is there a particular reason why? I hope my explanation makes sense.

**Comment by jlukic** [comment]
What version/platform are you using with NPM? Just tried with blank dir in Ubuntu and had no issues getting through install.

**Comment by timdoes** [comment]
**I am using:**
1. OSX El Capitan version 10.11 Beta (15A215h)
2. node v0.12.7
3. npm  v2.11.3

**Comment by inad9300** [comment]
This fixed it for me (apparently gulp could not run because node was not in the $PATH): https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-18951288
