### ISSUE TITLE
[Examples] Complete Component Examples

### ISSUE THREAD

**Issue by robmoggach** [Semantic-Org/Semantic-UI#2651]
Please add the [kitchen-sink](http://semantic-ui.com/kitchen-sink.html) page to the provided examples. By 'kitchen-sink' I'm referring to the following link...

```
http://semantic-ui.com/kitchen-sink.html
```

**Comment by jlukic** [comment]
I'm not sure if I want to add it back in. I think  people get the wrong impression when they see a page like this and it "feels" laggy because it has so much going on.

**Comment by robmoggach** [comment]
sounds great - i agree that page is bit slow - for now I've taken the "theming examples" sample layout and split it up into separate templates in meteor so I can add in the extra bits I need to build my custom theme.
