### ISSUE TITLE
Colored `<p>`, `<span>`, etc.

### ISSUE THREAD

**Issue by robmoggach** [Semantic-Org/Semantic-UI#2654]
Please expose the color palette for individual text tags like `<p>` or `<span>` or better yet, make them globally accessible with `class="ui red"` to define `color: @redTextColor`.

I understand this may break some of the deep references so leave it to you as to best way to approach. For now I am creating a site override for each as `.ui.red: { color: @redTextColor; }` etc.

> I don't believe this goes against the idea of not creating css that is 1-2 lines as there are 14 colors?

Is there a thread somewhere discussing this already?

**Comment by jlukic** [comment]
See  #1885, generally there are no free floating class names in Semantic UI, but only class names that have meaning in context of the component they modify.

**Comment by yaboi** [comment]
"paragraph" could be considered a component...

```html
<p class="ui text">This is a paragraph component.</p>
<p class="ui text blue">This is a paragraph component.</p>
<p class="ui text red">This is a paragraph component.</p>
[...]
```

With sixteen +1's in #1885 and some pretty compelling [reasoning](https://github.com/Semantic-Org/Semantic-UI/issues/1885#issuecomment-170665144) I would hope a dev team would reconsider a feature request.

**Comment by ozeebee** [comment]
+1 totally agree with @yaboi arguments

**Comment by sullyme** [comment]
+1

**Comment by lubber-de** [comment]
Implemented. Example here: https://jsfiddle.net/63z148gb/
