### ISSUE TITLE
[Checkbox] Make Checkbox Checking Cancellable

### ISSUE THREAD

**Issue by flyyang** [Semantic-Org/Semantic-UI#2656]
I have a problem with processing this situation:

I have to reject the checked action if there is already anther checked checkbox.So i add a handler to the onChecked  property. Check if the checked checkbox number greater than one.If so,rejected and `set unchecked`.

Problem is the checked action no need to fire at all.But there is no other `onBeforeChecked` behavior to use. I thinks this is very common issue.The `onBeforeChecked`  behavior is required...

Besides, why the `this` keyword in the onChecked refer to the input element not the checkbox itself?

**Comment by jlukic** [comment]
Checkbox `this` context can't be changed without breaking any live code using SUI. It perhaps could have been squeezed in with `2.0` but I didn't want to cause huge headaches for people. 

I can see the idea but I'm not sure if its adding necessary complexity to checkbox. Removing checked on checked has very little difference than preventing checked before the property changes.

**Comment by flyyang** [comment]
Thanks for the reply @jlukic.

I see your points. But calling `set unchecked` from `onChecked` is not an elegant way to approach that situation, especially the checkbox show as a slider or a toggle. People can see the unexpected animation twice:checked,unchecked.

That's why i recommend `onBeforeChecked` :)

**Comment by jlukic** [comment]
I guess its not much to ask. 

I think the simplest way to handle this that matches the rest of the libraries conventions is to use the names `beforeChecked` and `beforeUnchecked`

**Comment by jlukic** [comment]
@flyyang 

Thanks for your patience. I've added four new callbacks for `beforeChecked`, `beforeUnchecked` etc. (see notes). 

I've also added new behaviors for querying permission, `should allow checked`, `should allow unchecked` etc.
