### ISSUE TITLE
Comment actions issue inside modals look wrong

### ISSUE THREAD

**Issue by federico-elumen** [Semantic-Org/Semantic-UI#2659]
Hi, 

I'm using a `comment` inside a `modal` and when I try to add `actions` to it things go bad:
![Comment issue]
(http://pynfo.com/public/comments-actions-issue.png)

It seems that the rule for the `modal`'s actions is getting mixed up with the `comment`'s.

My solution was to change the rule for modal actions so that it only works with direct descendants of the modal...
from this: ``` .ui.modal .actions```
to this: ``` .ui.modal > .actions```

The end result looks as expected.
![Comment fix]
(http://pynfo.com/public/comments-actions-issue-fix.png)

Is there any other way to fix this mixup?

**Comment by jlukic** [comment]
That should be child selector as you said.
