### ISSUE TITLE
[Divider] 'vertical divider' in 'stackable grid' not display properly when stacked

### ISSUE THREAD

**Issue by evanzeng** [Semantic-Org/Semantic-UI#2661]
'vertical divider' in 'stackable grid' not display properly when stacked:

![20150718102749](https://cloud.githubusercontent.com/assets/872641/8759991/30eaf0c0-2d38-11e5-8b03-76b7ab11107f.png)

**Comment by manojhl** [comment]
To reproduce

```html
<div class="ui two column middle aligned container stackable grid">
  <div class="center aligned column">
    <div class="ui form">
      <div class="ui blue submit button">Login</div>
    </div>
  </div>
  <div class="ui vertical divider">
  </div>
  <div class="center aligned column">
    <div class="ui big green labeled icon button">
      <i class="signup icon"></i>
      Sign Up
    </div>
  </div>
</div>
```

**Comment by evanzeng** [comment]
The following code will reproduce the problem:
        <div class="ui container">
          <div class="ui two column middle aligned very relaxed stackable grid" style="position: relative">
            <div class="column">
              <div class="ui form">
                <div class="field">
                  <label>Username</label>
                  <div class="ui left icon input">
                    <input type="text" placeholder="Username">
                    <i class="user icon"></i>
                  </div>
                </div>
                <div class="field">
                  <label>Password</label>
                  <div class="ui left icon input">
                    <input type="password">
                    <i class="lock icon"></i>
                  </div>
                </div>
                <div class="ui blue submit button">Login</div>
              </div>
            </div>
            <div class="ui vertical divider">or</div>
            <div class="center aligned column">
              <div class="ui big green labeled icon button">
                <i class="signup icon"></i>
                Sign Up
              </div>
            </div>
          </div>
        </div>
But the following code has no problem:
        <div class="ui two column middle aligned very relaxed stackable grid container" style="position: relative">
          <div class="column">
            <div class="ui form">
              <div class="field">
                <label>Username</label>
                <div class="ui left icon input">
                  <input type="text" placeholder="Username">
                  <i class="user icon"></i>
                </div>
              </div>
              <div class="field">
                <label>Password</label>
                <div class="ui left icon input">
                  <input type="password">
                  <i class="lock icon"></i>
                </div>
              </div>
              <div class="ui blue submit button">Login</div>
            </div>
          </div>
          <div class="ui vertical divider">or</div>
          <div class="center aligned column">
            <div class="ui big green labeled icon button">
              <i class="signup icon"></i>
              Sign Up
            </div>
          </div>
        </div>

**Comment by evanzeng** [comment]
The following code will reproduce the problem:
```
<div class="ui container">
  <div class="ui two column middle aligned very relaxed stackable grid" style="position: relative">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <input type="text" placeholder="Username">
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <input type="password">
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="ui blue submit button">Login</div>
      </div>
    </div>
    <div class="ui vertical divider"></div>
    <div class="center aligned column">
      <div class="ui big green labeled icon button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
</div>
```
But the following code has no problem:
```
<div class="ui two column middle aligned very relaxed stackable grid container" style="position: relative">
  <div class="column">
    <div class="ui form">
      <div class="field">
        <label>Username</label>
        <div class="ui left icon input">
          <input type="text" placeholder="Username">
          <i class="user icon"></i>
        </div>
      </div>
      <div class="field">
        <label>Password</label>
        <div class="ui left icon input">
          <input type="password">
          <i class="lock icon"></i>
        </div>
      </div>
      <div class="ui blue submit button">Login</div>
    </div>
  </div>
  <div class="ui vertical divider"></div>
  <div class="center aligned column">
    <div class="ui big green labeled icon button">
      <i class="signup icon"></i>
      Sign Up
    </div>
  </div>
</div>
```

**Comment by jlukic** [comment]
It appears to me the test case provided by @evanzeng is functioning correctly (Chrome Win)
http://jsfiddle.net/zpayz02y/

The testcase by @manojhl does not include any text. So it will not appear correctly.
If you want to divide a grid without text use `divided grid` variation. 
http://jsfiddle.net/rqq0hm1g/

**Comment by evanzeng** [comment]
Divided grid is just what I need. Thanks!
