### ISSUE TITLE
[menu] with secondary pointing having issue with input elements vertical height(position)

### ISSUE THREAD

**Issue by manojhl** [Semantic-Org/Semantic-UI#2663]
the `align-self: flex-end;` property affecting the vertical position of input element.

The input is placed little below compared to the beside HELP text/link, which can be observed 

**html to reproduce**
```html
<header class="ui top fixed secondary menu">
	<div class="right menu">
	    <a class="item active">Help</a>
	    <div class="item">
	    	<div class="ui transparent icon input">
	    		<input type="text" placeholder="Search...">
	    		<i class="search link icon"></i>
	    	</div>
	    </div>
	</div>
</header>
```

with `align-self: flex-end;` on `.secondary.pointing` variant  
![image](https://cloud.githubusercontent.com/assets/4166764/8762069/8c63339c-2d8b-11e5-8a0f-9da70b86586c.png)

`align-self: flex-end;` removed
![image](https://cloud.githubusercontent.com/assets/4166764/8762073/ae5b1cbc-2d8b-11e5-8268-afe92a8e8b35.png)

**Comment by jlukic** [comment]
I'd recommend just specifying `flex-start` for that particular item. `secondary pointing menu` generally requires `flex-end` for any activating item, Otherwise the "active" line will not correctly overlay.

**Comment by manojhl** [comment]
I think you need to consider removing `flex-end` for items with input elements

**Comment by jlukic** [comment]
There's no parent selector in css.
