### ISSUE TITLE
[Message] icons are differently sized when the message text is longer

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI#2665]
Fiddle here: http://jsfiddle.net/6zyornbb/

With "differently sized" I don't mean visually, but something is clearly wrong because the text that comes after it is very close to the icon, and when inspecting the element I found no difference except the size of the icons.

**Comment by jlukic** [comment]
It looks like this might be resolved by changing icon flex to `flex: 0 0 auto;`

I'll investigate

**Comment by jlukic** [comment]
Fixed in `2.0.5`
