### ISSUE TITLE
[dropdown] Remove Label Errors Under Certain Conditions

### ISSUE THREAD

**Issue by seddonm1** [Semantic-Org/Semantic-UI#2666]
Hi,
There is an issue on the multiple selection search drop down where you are able to add multiple items from the dropdown but cannot remove them:
Uncaught TypeError: Cannot read property 'split' of undefined

You can reproduce this on the official Semantic-UI site if you go to this link (http://semantic-ui.com/modules/dropdown.html#search-in-menu) look at the second drop down (the "ui multiple dropdown" one) add any item then try to remove it by clicking the cross icon.

**Comment by jlukic** [comment]
I'll patch this asap.

**Comment by jlukic** [comment]
Mixed in the commit with another feature, but `remove label` was not correctly pulling input value.
