### ISSUE TITLE
[Question] Policies for contributions

### ISSUE THREAD

**Issue by ns-phennessy** [Semantic-Org/Semantic-UI#2667]
As far as contributing new components goes, what requirements do we have for them to be accepted? 

1) What is the target browser support? How much of HTML5 is permitted?

2) Some components (like calendar) would be simpler to be filled out via JavaScript minus a few lines of markup, how much of this is permitted? Or another way to ask this, how explicit should the markup be for certain components?

3) There is a distinct style to how each component's JavaScript. Is there a boilerplate or an example with a lot of comments?

**Comment by jlukic** [comment]
1) Browser support is in the project readme
2) Whether or not pre-existing html should be used I think varies by component. For example a calendar it would make sense to generate the popup selector off an existing input. 
3) The module format [is documented online](http://semantic-org.github.io/Module-Examples/docs/module.html). In general, I haven't had any successful PR yet with regards to adding new modules. I'm very cautious about adding third party code that doesn't match the rest of the ilbrary stylistically. I think one of the things that separate SUI from some other libraries is the uniformity of the underlying codebase.

**Comment by ph7vc** [comment]
2) I meant like if I wanted to say like
`<input type="date" class="ui calendar" data-month="Jan">`

then init it in JS, I could fill it out with different markup to more easily apply CSS styles, so like
```
<div class="ui calendar">
    <input type="text">
        <div class="header">January</div>
        <div class="body">
            <span class="day">1</span>
            <span class="day">2</span>
        </div>
</div>
```

Obviously we wouldn't expect the user to write out the markup for each individual day. How much behind the scenes markup should be allowed in JS?

**Comment by jlukic** [comment]
What's sensible given the UI context is correct :smile: see #2 above.

**Comment by J-tt** [comment]
@jlukic 
Don't mean to necrobump, but it seems this issue is no longer relevant, and can be closed :)
