### ISSUE TITLE
tab navigation stopped working on checkbox

### ISSUE THREAD

**Issue by amitos80** [Semantic-Org/Semantic-UI#2669]
I noticed that in the latest version 'hidden' class is added to checkbox's input tag,
that causes the tab navigation to skip the checkbox.
when i remove this class everything works like before.
is this addition necessary?
is there other solution?

**Comment by jlukic** [comment]
Checkbox adds its own tabindex. Please create a test case for verifying bug claims.

**Comment by avalanche1** [comment]
I've had the same issue.
Check that you don't have this css somewhere:
```
.hidden
	display: none !important
```

**Comment by jlukic** [comment]
The hidden class moves the checkbox to an unselectable position when using JS. This prevents double firing of events on click, and allows non-js components to work without rigging `for`/`id` tags.
