### ISSUE TITLE
[Popup] Hide Gracefully Should Check Mousedown Target

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#2670]
I am using the tooltip module and have noticed behavior where if a user highlights text within the tooltip, but releases their selection outside of the tooltip, it will close. Looking at the code, it seems like this is because the hideGracefully handler is being passed a click event, which only reports the element the mouse releases on. Would it be possible to use onMouseDown to prevent the tooltip from closing when a text selection is finished outside of the tooltip?

**Comment by jlukic** [comment]
I think the close event must occur on click. Occuring on `mousedown` doesnt allow a user to "cancel" it by finishing the click elsewhere. 

However I think `hideGracefully` should check the target of both `mousedown` and `click` event, to ensure they didn't occur inside popup.

**Comment by fpayer** [comment]
For reference, I believe the same issue occurs with modals.

**Comment by jlukic** [comment]
Yeah and sidebar
