### ISSUE TITLE
[Popup] Arrow offset

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#2671]
It would be helpful to specify the arrow offset on the bubble created by the tooltip. This is a feature in the hopscotch library with their "arrowOffset" option. See https://linkedin.github.io/hopscotch/#all-step-options

**Comment by jlukic** [comment]
That's already a setting check the docs

**Comment by jlukic** [comment]
You can specify both distance away and offset

**Comment by fpayer** [comment]
I tried both, but neither has the behavior I am looking for. Both distance away and offset move the bubble away from the target, but I want to be able to move the arrow independent of a the bubble. Would a JSFiddle help for an example?

**Comment by jlukic** [comment]
You want to move the arrow without moving the contents of the popup?

**Comment by fpayer** [comment]
Yes, exactly. 

Here, in this JS Fiddle: https://jsfiddle.net/tj867f2n/1/

I want to be able to have a popup open from the left side of the bar. However, because the icon is so close to the top of the page, the popup opens with the "bottom right" position. 

In the position example on the docs, http://semantic-ui.com/modules/popup.html#positioning, the popups tend to "hug' the top and the bottom. All each corner is aligned with the top or the bottom. This means you cannot have a popup in a corner where the contents of the popup come out to the side.

**Comment by fpayer** [comment]
This specific example could be solved by #2584, but there could be some use cases where the arrow offset would need to be set manually.

**Comment by dbhalalahutwork** [comment]
any update on this arrow offset in popup?
