### ISSUE TITLE
segment text wide

### ISSUE THREAD

**Issue by nor-bu** [Semantic-Org/Semantic-UI#2674]
Hi,

i have a problem with the content in a standard segment.

![semantic-segment](https://cloud.githubusercontent.com/assets/10696903/8770598/dd61a79a-2eb4-11e5-965a-18f4984f1cf3.jpg)

that is my code:

```
<div class="ui segment">
   <p>
       askdfhajksadsfasfasfasdfaföalsdnflkasdfjlabslkdfbjaksdbfjkasbldfbljkabsdjfk
   </p>
</div>
```

thanks for help

**Comment by avalanche1** [comment]
Closing until there's a test case.
