### ISSUE TITLE
Search input in secondary pointing menu

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#2675]
I've noticed that trying to use a transparent search input within a secondary pointing menu positions it slightly incorrectly. Every other menu seems to be fine, and other search input types are also fine, but specifically the transparent search.

Here is a fiddle replicating it

http://jsfiddle.net/ctr7pjcj/1/

As you can see, the search input is positioned lower than the button to the right of it. I've commented out the CSS that seems to fix the issue, but I don't have much experience with the flex layout, so not 100% sure if this would break other issues, but looking through the styling of a non-pointing secondary menu, the `align-self` property is set to `center`, whereas the pointing variation has it set to `flex-end`. Replacing this resolves the issue.

**Comment by jlukic** [comment]
#2663
