### ISSUE TITLE
Can't get dropdown to initialize after upgrading to SUI 2.0.4

### ISSUE THREAD

**Issue by paulwal** [Semantic-Org/Semantic-UI#2679]
http://www.sessionlessons.com/-/1

Look at line 100 of the html for the dropdown markup, and line 3 of /js/studio.js for the dropdown initialization. It worked fine in 2.0.0 (see: http://www.sessionlessons.com/-/0 )  but now it stopped working for some reason. What am I missing? Thanks

**Comment by paulwal** [comment]
I forgot to mention I've tested this on Chrome and Safari in OS X 10.10.4.

**Comment by jlukic** [comment]
I'm seeing a js error 
```javascript
TypeError: localVideo is null
	localVideo.addEventListener('loadedmetadata', function(){}
```

**Comment by jlukic** [comment]
Your dropdown does not include any `items`. Dropdowns are intended for user selection, and require at least one `item` to open. 

If you need to display overlay content try `ui basic popup` with `slide down` animation.

**Comment by paulwal** [comment]
Thanks, Jack. That makes sense. I appreciate the kind words, and thanks for the suggestion. The `ui basic popup` looks perfect. I'll use that instead.
