### ISSUE TITLE
Bring back fluid layout

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#2680]
One of the main attractions of Semantic UI, for me, was the fluid grid with harmonically sized percentage gutters (using `ui page grid`).

I'm puzzled by your decision to scrap this in favor of a fixed width design.

Maybe it's easier to style things at a fixed width, but then again, not using a responsive design at all would be still easier – the point should be getting the best possible design/UX.

Please bring back fluid layout to Semantic UI. Thanks.

**Comment by jlukic** [comment]
After building a couple big websites using a fluid grid, I've realized what I originally though was a feature of the library was actually a detriment. 

When a container is fluid across all browser widths it becomes impossible to maintain maximum content width. You also have the bizarre behavior where a fluid % snaps at each breakpoint causing content below a breakpoint to be wider than immediately after a breakpoint. 

I think containers and particularly `text containers` make many layouts simpler. They also make it easier to make compatible structures for `menu` and other elements which may need to maintain the same width as a grid.
