### ISSUE TITLE
[Form Validation] Add Data-Validate Example

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2683]
Hi,

I've come across an issue, when I need to validate an array of input fields (i.e. fields having identical names ending with `[]`). The validation sends an error to console saying `Uncaught Error: Syntax error, unrecognized expression: #field-name[]`. 

It looks like semantic is trying to first look for fields that have id `field-name[]`, but expression is invalid for ids. How can I make validation work in this case?

**Comment by fpayer** [comment]
Please post a code example

**Comment by andreyvk** [comment]
Sure thing. Here's a [fiddle](http://jsfiddle.net/andreyvk/ho5f6of7/). Basically, all the fields there in the example expect an integer, so you could type some random string in and then lose focus. Keep your console open to see the error. Cheers

**Comment by fpayer** [comment]
Your problem is that you are using duplicate names and each field should have it's own rule. See this working fiddle https://jsfiddle.net/sdr27a2j/

**Comment by fpayer** [comment]
The duplicate names would not be a problem if you have unique Ids for each field. But regardless, you need a rule for each field.

**Comment by andreyvk** [comment]
It's working in your example, but that's nothing to do with array of fields. As you can imagine things might get much uglier if you have, say, forms with multiple dynamically created addresses, where an address is a collection of fields for street, city, country, etc. 

Of course we can write a piece of JS code to do custom validation in `onSuccess`, but that's not also what I was asking about. My sole interest is in validating array of fields and if there's any provision for that functionality in the future.

**Comment by fpayer** [comment]
Yes, I suppose that would be a useful feature. Let's see if this gets put on the roadmap.

**Comment by jlukic** [comment]
If you are using an id with `[]` just use `data-validate` and a name with `[a-Z]` i.e. `<div name="field-name[]" data-validate="email">`

**Comment by fpayer** [comment]
I want to post this [JSFiddle](https://jsfiddle.net/ho5f6of7/2/) here for future reference then because I do not see an example of this usage in the docs:

**Comment by jlukic** [comment]
I'll add an example

**Comment by andreyvk** [comment]
Thanks guys

**Comment by joshbodine21** [comment]
There isn't an example, but it is explained in the message right at the top of the page under usage: http://semantic-ui.com/behaviors/form.html

**Comment by jlukic** [comment]
Added example in next

**Comment by Gaffi81** [comment]
Hi jlukic!

The example provided by You (http://jsfiddle.net/92p8fkbb/) doesn't work as expected.
It validates all three fields based on the first one.
The problem is, that the validator function is fired only once, with 'this' set to the three inputs, and the 'value' set to the first input value. It should be fired three times with the three inputs and their values.

**Comment by lubber-de** [comment]
Individual field error handling for input array formfields is now fixed in https://github.com/fomantic/Fomantic-UI/pull/387
See http://jsfiddle.net/a1cnph4f/1/
Supposed to be part of upcoming Fomantic-UI 2.7,2

**Comment by andreyvk** [comment]
@lubber-de  That's good news )) What is Fomantic anyways? Have I missed out on some transition/renaming of semantic?
