### ISSUE TITLE
[Grid] Add Reverse Variations

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#2685]
In version **1.x**, I could make the first column in a grid `right floated` in order to pull the next column up on its left side. This way, when the columns stack on mobile, I could make the content to the right show first on the scroll.

Did this feature disappear out of thin air? Most of the layouts on my site depend on it.

**Comment by dalgard** [comment]
Adding a set of classes to change flex properties, such as flow direction, might be a good way to go.

**Comment by jlukic** [comment]
You can use `right floated and `left floated` still however they should appear in normal flow order. `right floated` needs to be last.

**Comment by dalgard** [comment]
This is exactly the problem that I'm pointing out.

**Comment by jlukic** [comment]
This is just how floating works in `flex` it uses `margin: auto`.

**Comment by dalgard** [comment]
I figured out the `column-reverse` property – it's a good solution, and I definitely think you should add a class for it. For the time being, I've added it as an override.

**Comment by jlukic** [comment]
Implemented in `2.1` as `reversed tablet`, `reversed mobile` etc
