### ISSUE TITLE
"ui fluid buttons" seems have bugs in semantic ui 2.0.5

### ISSUE THREAD

**Issue by playniuniu** [Semantic-Org/Semantic-UI#2686]
Hi 

I have use ui fluid buttons like this

```html
<div class="ui two column centered grid">
    <div class="column">
        <div class="ui blue fluid buttons">
        </div>
    </div>
</div>
```

It seems ok in the large width like this:

![screen-01](http://niuniuimages.s3-website-ap-northeast-1.amazonaws.com/githubbugs/semantic-ui/screen-1.png)

but when i resize it, it look like buggy:

![screen-01](http://niuniuimages.s3-website-ap-northeast-1.amazonaws.com/githubbugs/semantic-ui/screen-2.png)

I test it in sematic ui 2.0.2, it's ok, 

![screen-01](http://niuniuimages.s3-website-ap-northeast-1.amazonaws.com/githubbugs/semantic-ui/screen-3.png)

so could any one know which is the problem?

Thanks

**Comment by jlukic** [comment]
Check the release notes #2617 
https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md#version-204---july-17-2015

Please create a test case

**Comment by avalanche1** [comment]
Closing until there's a test case.
