### ISSUE TITLE
[Readme] Remove IE9 Support Clause

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#2687]
Hi there,

according to your section "Browser Support" (https://github.com/Semantic-Org/Semantic-UI#browser-support) Semantic-UI is compatible to IE9, using prefixes.

I now inspected my work with Semantic UI and saw that grid layouts make heavy use of flexbox CSS.
When I open my HTML prototype in IE9, the layout is messed up.

Can I make Semantic UI avoid using flex box layout?
Or is there a JS lib / polyfill available to get it work in IE9?

This is quite important for me, since I am developing for Enterprise customers, they are still depending on IE9...

Kind regards,
Sascha,

**Comment by jlukic** [comment]
The readme is out of date. We do not support IE9 and cannot. Most of the library uses flexbox which is unsupported below IE10.

**Comment by jlukic** [comment]
I've revised the readme
