### ISSUE TITLE
[Dropdown] - Add "set exactly" behavior

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#2689]
**Expected**
The Dropdown should remove existing selected values in the dropdown and replace them with the new ones.

**Result**
The Dropdown does not set the selected options and appends the newly selected values to the current selection. 

**Testcase**
https://jsfiddle.net/gaa545jc/8/

**Notes**
Calling "clear" prior to calling "set selected" works as a temporary solution. However, there seems to be some weird effects on "get value" after calling "clear" and "set selected"

**Comment by jlukic** [comment]
`set selected` is meant to add a value as selected, and does not clear. This is how it is used internally so this feature can't be changed.

However `clear` does appear to have a bug where values set while a label is animating out of view, fail to be set. #2690

**Comment by fpayer** [comment]
Ok, I would also recommend updating the description of "set selected" in the docs because the description would lead devs to believe it overwrites any previous value.

**Comment by jlukic** [comment]
I can easily add `set exactly` which does `clear` and then `set selected`

**Comment by fpayer** [comment]
Yes, that would be a great solution. Much appreciated.

**Comment by jlukic** [comment]
I'm also seeing a related bug when using `<select>` when nothing is selected, value will report '', which will trigger selection on `value=""` and cause the array to have an improper comma, i.e. `,VT,VA`

**Comment by jlukic** [comment]
This is actually really fascinating, setting a multi value to `''` will then retrieve its value with `.val()` as `['']` if there is a matching `option`.

**Comment by cashsun** [comment]
Hi, I think there's a bug in 'set exactly' - the selected labels are not in the same order of passed array.

i.e. $dropdown.dropdown('set exactly', ['d', 'a','c', 'b']);
result: the multiselect shows 'a', 'b', 'c', 'd' as selected, in that order. Which is not exactly 'set exactly'....
