### ISSUE TITLE
Broken link in Tab documentation "Examples" section

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [Semantic-Org/Semantic-UI#2692]
There is a broken link in the tab part of the documentation in the `examples` section. http://semantic-ui.com/modules/tab.html#/definition

**Comment by jlukic** [comment]
Thanks. I'm not sure when that happened

**Comment by jlukic** [comment]
Deploying fix now. This was caused by an example demonstrating history using html5 state breaking the normal page navigation (which uses hash state)
