### ISSUE TITLE
[UI] Textarea

### ISSUE THREAD

**Issue by UAhmad7** [Semantic-Org/Semantic-UI#2693]
I think there should be an option to automatically add a new row to textarea instead of adding a scrollbar if all rows are filled or on enter key press.

**Comment by Pandahisham** [comment]
+1

**Comment by jlukic** [comment]
I'm thinking of this as a `.textarea()` component, with maximum length, character count display, and auto expanding input size.

**Comment by UAhmad7** [comment]
Yes, these would be very useful additions to the component.

**Comment by michgeek** [comment]
:+1:

**Comment by thomasdola** [comment]
:+1:
