### ISSUE TITLE
[sidebar] Can pusher be fluid ?

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#2695]
When using a left sidebar, "overlay" let left part blocked, and "push" let right part blocked.
I want an effect like changing pusher left only, to ensure all content is visible. 
Thank you very much!

**Comment by jlukic** [comment]
Hi, this has been discussed in previous threads but pusher cannot "squish" content. Animating `padding` is not hardware accelerated, and the constant content reflow would cause performance issues.

Previous versions of SUI did this behavior by default by animating `padding` on `body` but it was not performant.
