### ISSUE TITLE
Mozzila Firefox Sticky Problem

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#2697]
http://jsfiddle.net/aduew9uo/ Open at Chrome and Firefox to see the difference.
Please, some advice to fix that. css or something...

**Comment by TeodorKolev** [comment]
any update on this one???

**Comment by jlukic** [comment]
Like I said in the previous thread #2480 sticky is not intended to be used with tables. You will run into a host of issues with column resizing automatically because of `table-layout`.  Use at your own discretion.

**Comment by TeodorKolev** [comment]
so there is no way to fix that?

**Comment by TeodorKolev** [comment]
which is the thing that broke it in firefox
