### ISSUE TITLE
Artifacts in the popup's 

### ISSUE THREAD

**Issue by postbud** [Semantic-Org/Semantic-UI#2698]
Loading json data in 'popups' outer layer as text with characters '\n', '\', etc.
If everything is correct:
![correct](https://cloud.githubusercontent.com/assets/12687205/8748974/a7aab758-2cb7-11e5-9faa-4666a49b6015.jpg)

but more often:
![incorrect](https://cloud.githubusercontent.com/assets/12687205/8748992/c7b0b84a-2cb7-11e5-8604-1f4dabe7c994.jpg)

To correctly view the need to refresh the page.

**Comment by avalanche1** [comment]
@postbud ping

**Comment by postbud** [comment]
***avalanche1***  I'm afraid I do not understand you

**Comment by jlukic** [comment]
You need to post a test case

**Comment by postbud** [comment]
Unfortunately, the problem has ceased to occur. The code has been changed significantly, and therefore can not fully reproduce the problem.
Anyway, below the React component code:
<div className = "ui card">
      <div className = "blurring dimmable image">
        <div className ="ui dimmer transition hidden">
          <div className = "content">
            <div className = "center">
              <i className = "play circle huge icon video_card-icon" onClick = {this.showPlayer}></i>
            </div>
          </div>
        </div>
          <img src={this.props.value.thumbnail_url}></img>
      </div>
        <div className = "content">
          <a className = "ui tiny header video_item_header">{this.props.value.title}</a>
            <div className ="ui popup video_item-popup">
                <div className = "ui tiny header">{this.props.value.title}</div>

                <div className = "ui divider"></div>

                <div className = "video_item_description">{this.props.value.description || this.props.value.title }</div>

                <div className = "ui divider"></div>
                                        
                <div className = "ui bottom attached label extra content view_count">
                    <div className = "left floated"><b>{published_at}</b></div>
                        <div className = "right floated">
                            <span>
                                <i className = "unhide icon"></i>
                                 {this.props.value.view_count}
                            </span>
                            <span className = "right floated">
                                <i className = "caret down icon"></i>
                                 {this.props.value.dislike_count}
                            </span>
                            <span className = "right floated">
                            </span>
                            <span className = "right floated">
                                <i className = "caret up icon"></i>
                                 {this.props.value.like_count}
                            </span>
                        </div>               
                </div>  
            
            </div>
        </div>
 
      </div> `
javascript:
`$('.ui.tiny.header').popup({inline: true});`

**Comment by jlukic** [comment]
Closing issue for now. Assuming this has to do with react pipeline.
