### ISSUE TITLE
Disabled dropdown fields receive focus

### ISSUE THREAD

**Issue by trigoesrodrigo** [Semantic-Org/Semantic-UI#2699]
When tabbing through fields on a form, disabled dropdown fields receive focus and expand the dropdown. See http://jsfiddle.net/trigoesrodrigo/97wbogct/1

However I can't replicate the issue in the docs, the disabled dropdowns behave properly.

**Comment by jlukic** [comment]
Thanks! Helped me catch a typo.  Will be fixed in patch. Disabled fields will still receive keyboard focus but will not open.
