### ISSUE TITLE
Add a select dropdown with a search input

### ISSUE THREAD

**Issue by mllamazares** [Semantic-Org/Semantic-UI#27]
I wnat to talk about the possibility of adding a select dropdown with input search, some like Select2, Selectize or Choosen... but restyled to fit to the apperance of semantic-ui.
With an animation when the dropdown appear. 
Would be epic. I think would be very useful.

**Comment by geemang2000** [comment]
I've been trying to use Selectize.js . Functionally it seems to work well with the semantic-ui . The challenge is to get the CSS styling to match up well. E.g. errors don't work well
