### ISSUE TITLE
Ordered List Number Collides With Items

### ISSUE THREAD

**Issue by ProjectCleverWeb** [Semantic-Org/Semantic-UI#2701]
[JSFiddle](http://jsfiddle.net/rbxdutqc/) 

The list numbers collide with the list items after 99 items. 

**The below was produced in Chrome 43.0.2357.130 on Windows 7**

![list error](http://i.imgur.com/Qxnt7j8.jpg)

(also the fiddle you give to fork in the readme under "Submitting Bugs and Enhancements" uses broken paths for the semantic.min.js and semantic.min.css files)

**Comment by jlukic** [comment]
Duplicate #2639
