### ISSUE TITLE
Fluid Cards + Flexbox

### ISSUE THREAD

**Issue by mindbits** [Semantic-Org/Semantic-UI#2702]
Like the jsfiddle example at http://jsfiddle.net/fLkzcjhs from #2325 shows:

Do fluid cards + flexbox not work together or am I missing something?

**Comment by jlukic** [comment]
What's not working?

**Comment by mindbits** [comment]
Yes, I expected that the height of Elliot Fu's card would adjust to the height of the other two when the screen gets smaller. 

I'll look into plurality then.

Thank you!
