### ISSUE TITLE
[Form] input[type="date"] renders slightly taller

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#2704]
(Chrome 44)

![screen shot 2015-07-22 at 11 22 28 pm](https://cloud.githubusercontent.com/assets/3354585/8842517/2d0f3ad0-30c9-11e5-9291-54d38d214440.png)

**Comment by jlukic** [comment]
I'll take a look to see if this is solvable.

In the future please include a test case.

**Comment by jlukic** [comment]
It looks like the vendor styled inputs use `18px` height for the "spinner", which is larger than any standard input line height.
