### ISSUE TITLE
[Form] Min-width Interfering with Appearance in (X) Fields

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#2705]
[this](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/dropdown.variables#L126) declaration of `14em` is used with `min-width` property [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.less#L362) which overrides declarations like `.ui.form.field > .selection.dropdown { width 100% }`.  (or in my case `.three .fields`)

It may be okay when in standard `.container`, but I'm using custom container widths (smaller than default) which causes the dropdown to extend out of bounds.

![screen shot 2015-07-22 at 11 41 30 pm](https://cloud.githubusercontent.com/assets/3354585/8842677/3c3eb182-30cb-11e5-9891-952f443a3d79.png)

Set `.ui.selection.dropdown` property `width` instead of `min-width` fixes; but will that have unintended conflict with other things? ...

**Comment by jlukic** [comment]
Generally selection dropdowns get awkward when really small. So we try to provide a reasonable minimum width. 

However there probably should be no minimum width when inside a form.

**Comment by jholl** [comment]
Can we do min-width only in media query for small screen since it seems the driving issue is screen size?

If we limit the exception only to not in form it may creep up again in three columns grid outside form?

On Jul 23, 2015, at 10:43, Jack Lukic <notifications@github.com> wrote:

Generally selection dropdowns get awkward when really small. So we try to provide a reasonable minimum width.

However there probably should be no minimum width when inside a form.

**Comment by jlukic** [comment]
The driving issue is not screen size but word-wrapping on `menu item`. I think the default is sensible as long as nothing else is adjusting its width.

**Comment by jlukic** [comment]
Working through this test case
<form class="ui form">
  <div class="three fields">
    <div class="field">
      <input type="text" />
    </div>
    <div class="field">
      <input type="text" />
    </div>
    <div class="field">
      <input type="text" />
    </div>
  </div>
  <div class="fields">
    <div class='five wide field'>
      <div class='ui labeled input'>
        <div class='ui label'>from:</div>
        <input type="text" class="" />
      </div>
    </div>
    <div class='five wide field'>
      <div class='ui labeled input'>
        <div class='ui label'>to:</div>
        <input type="text" class="" />
      </div>
    </div>
    <div class='three wide field'>
      <div class='ui right labeled input'>
        <input type="text" class="" />
        <div class='ui label'>value</div>
      </div>
    </div>
    <div class='three wide field'>
      <div class="ui button red icon"> <i class="trash icon"></i>

      </div>
    </div>
  </div>
  <div class="four fields">
    <div class="field">
      <label>Label</label>
      <input type="text"></input>
    </div>
    <div class="field">
      <label>Label</label>
      <input type="text"></input>
    </div>
    <div class="field">
      <label>State</label>
      <select class="ui fluid dropdown">
        <%- @partial('examples/single/state-options') %>
      </select>
    </div>
    <div class="field">
      <label>Country</label>
      <div class="ui fluid search selection dropdown">
        <input type="hidden" name="country">
        <i class="dropdown icon"></i>
        <div class="default text">Select Country</div>
        <%- @partial('examples/single/flag-menu') %>
      </div>
    </div>
  </div>
  <div class="inline fields">
    <div class="field">
      <label>Label</label>
      <input type="text"></input>
    </div>

    <div class="field">
      <div class="ui icon input">
        <input type="text"></input>
        <i class="calendar icon"></i>
      </div>
    </div>
  </div>
