### ISSUE TITLE
equal width button in button group doesn't fix when is only one button

### ISSUE THREAD

**Issue by yordis** [Semantic-Org/Semantic-UI#2706]
If we only have one button we should use just ```ui two buttons``` classes in the container or just use ```fluid``` class in the buttonbut rather than that, I think is better support ```ui one buttons``` so that way some javascript framework (this is my case) have a defined procedure for put the classes because even the ```fluid``` class is at the button layer no at the button group layer

Example: http://jsfiddle.net/ws_ubi/z1jo3qzg/6/

**Comment by jlukic** [comment]
If you have one button you should always just use `ui button`. `ui buttons` does not add any additional value. 

I think any wrapper for `ui buttons` should just error out if < 2

**Comment by yordis** [comment]
@jlukic I fully understand about use the correct class, the singular one, is just about who have the responsibility on this.

Let say I have some backend code that send me some arrays of buttons or whatever dynamic way to do it, rather than put a condition for check how much buttons I have (and then will be my responsibility) you just support for one button inside the button group. You just have to add one css class and done.

One use case is: using button group for filtering out, like toggles (that's coming)

All the repos are there: https://github.com/React-UI/, go and take a look any help testing will be great for me, BTW, I am using JSPM.

**Comment by jlukic** [comment]
I think conceptually the React components should be identical to SUI components. Otherwise these barriers will exist when separating button from buttons. In my book they are both instances of the same "thing"

**Comment by yordis** [comment]
@jlukic even when I pick to use Semantic UI but I am trying to create generic components and I would like to see if you can support me on that. As you can see here: https://github.com/React-UI/button/blob/master/src/stylemap.js all the classes are mapped there because I don't want to have that dependencies to the UI framework that much.

And specs can change and for you button and buttons is the same, for component base are two different things, one, is button and the other is a grouping of button. That's the way I see it.

**Comment by jlukic** [comment]
I just know i don't want anyone ever generating a button group with the class name `one buttons` as this isn't english. 

If someone is using `buttons` they should know they are using 2 or more, and `button` one item. 

I understand the difficulty in determing allowable class names for the grouping vs singular. 

This will be alleviated once I'm able to generate JSON spec files for 'acceptable class names' for each variation from the docs. Conceivably this is already possible (since we use this to highlight the correct classes in code samples in yellow in docs), but a scraper hasnt been written yet.

**Comment by yordis** [comment]
@jlukic OK, I will removed that support because as you say that isn't english and they can take the responsibility.

If you don't mind join to gitter for future discussions before I actually create some issue in github because I will work almost fulltime on this project and I like to have any support from Semantic UI team
