### ISSUE TITLE
Sticky refresh bug

### ISSUE THREAD

**Issue by TeodorKolev** [Semantic-Org/Semantic-UI#2708]
http://jsfiddle.net/aduew9uo/ Open at Chrome and Firefox to see the difference.
I know that is not recommended to use sticky on table, but which is the thing that broke it in Firefox. Please, explain, show source code or do something useful for users, instead of closing issue without any solution

**Comment by KapuzenSohn** [comment]
I cant see any difference between Firefox and Chrome, bot are on the newest version. I see with both browsers the problem you describe.

**Comment by TeodorKolev** [comment]
I don't see the problem in chrome. The problem is: when you small result window to see mobile view, and then back resize to original view, scroll down and click on table: in chrome header row is resized proper. In firefox header row table dates all from second one are on top of another.

**Comment by jlukic** [comment]
Teodor, opening repeated threads for same issue is not alright. Please read the contributing guide, this is not the intention for this board. Please look for help elsewhere. #2697 #2480
