### ISSUE TITLE
[Dropdown] - Search Selection Dropdown example incorrect

### ISSUE THREAD

**Issue by zxlin** [Semantic-Org/Semantic-UI#2712]
In the search selection dropdown example, I believe the item divs should all be child to the menu div. 

http://semantic-ui.com/modules/dropdown.html#search-selection

![capture](https://cloud.githubusercontent.com/assets/5447705/8854516/3f77c182-312e-11e5-8d90-827b95ffbcd6.PNG)

**Comment by jlukic** [comment]
They are, the formatting is just off because of how the templates are generated. (This is included from a partial)
