### ISSUE TITLE
Dropdown menu items disappearing when option picked

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#2721]
I'm not sure what's going on, and as far as I can tell I've created a dropdown exactly the same as those found in the documentation, however when I try using it, all of the menu options get removed when one is selected.

http://jsfiddle.net/ujpratsz/2/

The fiddle replicates this. I'm really hoping I've just missed something simple as it's been a long day, but I'm lost as to what's going on here.

**Comment by Airforce111** [comment]
You can try removing the 'text' class.

**Comment by jlukic** [comment]
http://jsfiddle.net/yo3bqjct/

Adding text to input is not correct.

**Comment by pareeohnos** [comment]
Ah great thanks! Is there a way around this though?
I'm using SUI in a rails application, and the library I'm using for forms (simple_form) automatically injects that class onto the wrapper which you can't really control, so I don't get a huge amount of choice as to whether or not the 'text' class is there :(

**Comment by jlukic** [comment]
No class names all have meaning in SUI. You will need to find a way to remove it from the hidden input.

**Comment by pareeohnos** [comment]
Understood. Out of curiosity though, why does having the 'text' class cause it to wipe all the options? It's certainly not a documented quirk and there aren't any documented dropdowns using the 'text' class (other than the default text)

**Comment by jlukic** [comment]
Not sure, whatever it normally would look for and apply to dropdown text it was doing to your input.

**Comment by pareeohnos** [comment]
Fair enough. Thanks for helping me sort it :)
