### ISSUE TITLE
Form validation bullets show up as literaly 'â€¢' in Chrome for Linux

### ISSUE THREAD

**Issue by nickretallack** [Semantic-Org/Semantic-UI#2722]
![Screenshot](http://i.imgur.com/qKZgLrK.png)

This is what [this page](http://semantic-ui.com/behaviors/form.html) looks like when I click Submit in Chrome for Ubuntu.  They look like bullets in Firefox though.

**Comment by zxlin** [comment]
What specific version of Chrome are you using? I'm on latest and it looks fine for me. 

![chrome](https://cloud.githubusercontent.com/assets/5447705/8887871/ca6da2da-3263-11e5-9956-5eaebfd99279.png)

**Comment by zxlin** [comment]
What specific version of Chrome are you running? I'm on latest and it looks fine to me.

**Comment by avalanche1** [comment]
This is definitely not a SUI bug. You should narrow it down to your config. May be smth with your codepage.

**Comment by undercase** [comment]
This is definitely not the case, I'm typing this from Chrome on Ubuntu right now, and form validations look fine.

**Comment by avalanche1** [comment]
FF tends to break a lot of stuff in my SUI proj. But validation bullets work fine (tested on OS X).
Don't think that FF+Ubuntu config has a significant user share to be worth investigating.
Let's wait for @jlukic 's say.

**Comment by mcantor** [comment]
If anyone stumbles on this, cold and alone in the far reaches of the internet like I did, you might want to check out this StackOverflow QA on this exact problem:

- http://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of

**Comment by jgreens** [comment]
Add the following line to your HTML page:
`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`
