### ISSUE TITLE
Changing DOM in Modal while transition isn't completed causes invalid position

### ISSUE THREAD

**Issue by Siprah** [Semantic-Org/Semantic-UI#2725]
I found really weird problem in modal. When you showing it and at the same time you're running eg. ajax request which updates DOM in modal, it makes invalid position. It appears when request is too fast and visibility transition isn't completed. When I add ajax trigger to `onVisible` callback, everything is fine, but I think this is just ugly hack.

**Comment by Siprah** [comment]
Okay, so... I can reproduce that bug but... It's only in Semantic 1.x, sample code here: https://github.com/Siprah/Semantic-dynamicmodal-Bug

So, everything depends on whether Semantic 1.x line is still supported. I'm still using it in my project, because it has for 3 months, and Semantic 2.x is in stable branch since recently.

**Comment by jlukic** [comment]
I'm fairly certain this is similar to #2402, I cant offer support since I have fixed this bug already, but perhaps you can find the relevant code to patch from the commits there.

**Comment by Siprah** [comment]
Nevermind. I just upgraded my project to 2.x.
