### ISSUE TITLE
[Form] Add Credit Card Validation

### ISSUE THREAD

**Issue by mayhem-ahmad** [Semantic-Org/Semantic-UI#2729]
hey guys,

Is there a ready Credit Card Payment form validation script i need to use it in my magento store .

the reason i'm asking for this because i have the credit card form in a standalone page the don't contain prototype.js and magento validation JavaScript library .

can you please help me with this ?
Thanks!

**Comment by undercase** [comment]
No, there is not one included in the library. You must write your own using Semantic UI's [form validation library.](http://legacy.semantic-ui.com/modules/form.html)

**Comment by jlukic** [comment]
I would consider a PR that adds a standard credit card validation as `type: 'credit card'`

**Comment by sstok** [comment]
FYI you can have a look at the https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Validator/Constraints/CardSchemeValidator.php (MIT licensed)

**Comment by jlukic** [comment]
I think the syntax should probably support specifying card type.

I.e. 

```
// any known credit card type
type: 'credit card'
```
```
// only visa or mastercard
type: credit card[visa, mastercard]
```
