### ISSUE TITLE
form validation not have remote validation

### ISSUE THREAD

**Issue by Ive4** [Semantic-Org/Semantic-UI#2730]
some time,we need remote validation some data,but i'm not found in semantic
can you add it in the future?

**Comment by Ive4** [comment]
some time,a field has two or more rule,the first rule return invalid,i want to interrupt the validator
but i'm not found in semantic
such as:
 username: {
        identifier : 'username',
        rules: [
          {
            type   : 'empty',
            prompt : 'Please enter a username'
          },
          {
            type:'length[4]',
            prompt:'Please enter 4 words'
          }
        ]
      }
when is empty,i just want check first rules and ignore other

**Comment by undercase** [comment]
What you want can easily be done by using a callback, such as `onInvalid`. Just have one rule:

    rules: [
      {
        type: 'empty',
        onInvalid: function(field) {
          if (field.length > 0) {
            // It is less than 4 characters long
          } else {
            // It is empty
          }
        }
      }
    ]

**Comment by Ive4** [comment]
thanks
some time,we need remote validation some data,but i'm not found in semantic
can you add it in the future?
i'm a semantic fans

**Comment by jlukic** [comment]
You can do this with `$.ajax({ sync: false });` although it's not pretty. Would require async which form does not support currently.

**Comment by Ive4** [comment]
thanks for your help
I know too
so i suggest developers add this in the future
