### ISSUE TITLE
Shape Animation Problem on Safari

### ISSUE THREAD

**Issue by robmoggach** [Semantic-Org/Semantic-UI#2731]
"Shape" 3D animation on safari 8.0.7 is broken -
Take a look at this -

https://youtu.be/JrwWjbZxcOw

**Comment by jlukic** [comment]
It's probably an issue with animating height.

**Comment by frankapimenta** [comment]
I updated to last version and is still raising the same issue....

**Comment by quique1233** [comment]
Does anyone know how to fix this? i have the same issue

**Comment by klozano** [comment]
+1 @quique1233

**Comment by frankapimenta** [comment]
I still have this issue in safari. Any ideas how to solve it?

**Comment by jlukic** [comment]
I've added a new setting in `2.2` that lets you specify whether a shape should take the width of its `new` side or the `previous` side when animating. I've found in my own tests that this solves that this solves a lot of issues.

**Comment by Duozhasht** [comment]
is it possible to update to 2.2 already ? Need this fix so much

**Comment by frankapimenta** [comment]
ex: how does this works? 
```javascript
$('.shape').shape('set width initial').shape('flip over');
```
does not work for me.

**Comment by frankapimenta** [comment]
It is solved by setting with for shape sides and side css classes.
ex.:
```css
div.shape
  width: 300px
  div.sides
    width: 300px
    div.side
      width: 300px
    div.card
        width: 300px

```

**Comment by frankapimenta** [comment]
@jlukic maybe this can be closed now?
