### ISSUE TITLE
[Dropdown] Pointing Dropdown does not displayed properly at the bottom of the screen

### ISSUE THREAD

**Issue by inad9300** [Semantic-Org/Semantic-UI#2733]
When the page is scrolled down that much that the dropdown doesn't completely fit on it, the background and other styles disappear.

![semantic_dropdown_bug](https://cloud.githubusercontent.com/assets/3440331/8915953/70350de8-34a8-11e5-88f5-e6f799c3d0bb.png)

It only happens apparently with the pointing dropdowns. I think you shouldn't care that much about the style, but about displaying the dropdown in the proper direction, as with the other kinds of dropdowns.

I hope this was not reported already.

Cheers.

**Comment by jlukic** [comment]
I'm able to replicate this in chrome, unsure of cause.

**Comment by inad9300** [comment]
Sorry for not clarifying that, I was using Firefox 39.0 at the moment I took the screenshot.

**Comment by jlukic** [comment]
Fixed in `2.1`
