### ISSUE TITLE
[Transition] - Types should be documented

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2735]
Currently there is no mentioning that 'in' and 'out' transitions are possible. Only a vague mention in the Types paragraph in #usage section.
These types of animations sd have examples.

**Comment by jlukic** [comment]
What about [transition direction](http://semantic-ui.com/modules/transition.html#transition-direction) notes?

**Comment by avalanche1** [comment]
Definitely not enough.
There sd be a stand alone example demonstrating 'in' and 'out' animations explicitly. That is very important - I was struggling with `.addClass('transition visible')` and other voodoo magic until i've had a brainwave and experimented and found out that there **is** the 'in' animation.
I would PR docs but I cannot grasp how to insert html examples and js code.

**Comment by jlukic** [comment]
I'll add an example

**Comment by undercase** [comment]
Hey @jlukic, I've been trying to grok editing the docs, I'll try my hand at adding the example - I've used Semantic UI transitions extensively.

**Comment by undercase** [comment]
Unfortunately, DocPad is screwed up when you don't install npm as superuser, so I can't use it :0! I can't add this to the docs :(.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/c5af407b021f1e2556af6576d67f8e016965944b
