### ISSUE TITLE
Modal autofocus option doesn't work

### ISSUE THREAD

**Issue by azazel75** [Semantic-Org/Semantic-UI#2737]
The paramenter "autofocus" for the modal() module has no  effect.
I have a modal dialog with a login form inside and and none of the input fields gets focused after show.

The [code of modal.js](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/modal.js#L567) reveals that the problem seems to be the use of $module.filter(':input') to select the input elements. In my case $module is the jquery-wrapped "div" containing all the dialog contents and filter's job is to filter an array of elements by applying a selector to them, not that of "finding" child elements.

**Comment by jlukic** [comment]
This code is just wrong. Sorry about that

**Comment by davialexandre** [comment]
What about making this autofocus feature more flexible by allowing it to receive a boolean or a function/callback that would set the focus? 

I am thinking about scenarios where I wouldn't want to the set focus on the first input or where my first field isn't exactly an input (e.g a select2 dropdown).

**Comment by azazel75** [comment]
You always have the "show" action callback to perform more complex tasks that's the one i'm using now to focus the first input. By the way, are you sure $(':input') doesn't match a select2 dropdown. I've tried here https://select2.github.io/examples.html but without a clear answer

**Comment by jlukic** [comment]
But we have a multi select :smile:

**Comment by davialexandre** [comment]
Right now I am using the show action callback for this, but it doesn't seems quite "right" to me. Also it took me sometime to figure I could pass a callback to it, since there's no example of this in the documentation.

Maybe something with an onVisible callback would make more sense, but it will be called before autofocus :(

**Comment by davialexandre** [comment]
@jlukic multi select currently doesn't have all the features I need :(

**Comment by jlukic** [comment]
What features?

**Comment by davialexandre** [comment]
I created an issue about they: https://github.com/Semantic-Org/Semantic-UI/issues/2746

**Comment by bianjp** [comment]
Met the problem. Hope 2.1 will come soon.
