### ISSUE TITLE
docs full of typos?

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI#2738]
I'm trying to learn semantic but the docs don't make much sense to me. Are they full of typos?

there is no examples folder nor is there a themes folder in src/site. 

>Files in the examples/ folder of your project can be useful for testing out changes in your UI. For example, you might run gulp watch download a new theme to src/site/themes/ then adjust your theme.config file with the name of the new theme and refresh examples/kitchensink.html to inspect changes in the theme.

Is this all just wrong?

There are a lot of places in the doc which seems wrong. Makes it hard for me to get started.

**Comment by jlukic** [comment]
Examples folder is available in this repo. 
https://github.com/Semantic-Org/Semantic-UI/tree/master/examples

`src/site/themes/` is a typo, this should be `src/themes/`

**Comment by Maxhodges** [comment]
Thanks. @jlukic are you aware of any outstanding third-party tutorials? I saw there is a some video series on TUTSPLUS, but it's a bit older. Do you think something pre 2.0 would create more confusion?

Basically and friend and I are both trying to use Semantic UI for a new product, but we both have many of the same questions, like when to use overrides vs variables vs definitions. I feel the docs aren't clear enough for me. He things we should only use overrides, but I hired someone on upwork to help get the product started and he made a lot of additions to definitions files. So its just a bit confusing what the rules of thumb are here. Also gulp stopped working about we committed to git. Not sure why. Guess I'll just install semantic and gulp again and copy over my files and see if that sorts it out. I there there are over 100 issues regarding gulp on here on this repo. Seems to be a bit temperamental!

Anyway, if you know if any reputable tutorials or books I'd be grateful to hear about them.

**Comment by jlukic** [comment]
The best content we have no for explaining variable usage, and paths is the [theming guide](http://semantic-ui.com/usage/theming.html). 

I'm currently starting work on an [example project](https://github.com/Semantic-Org/example-github) that uses SUI via npm, and site overrides, packaged themes etc.

Since i'm the only one available to work full time on the project, the speed is currently going at the power of one. The weeks I'm bugfixing (the last couple) I get nary a tutorial update, and vice-versa. And lets not talk about fundraising...

**Comment by Maxhodges** [comment]
Yeah we've already read that a few times. Oh well. I like the idea of Semantic, but in practice the learning curve it too high (a site can have multiple themes which have 6 levels of overrides and 3 level of inheritance). It's hard to know how to make heads or tails our of this stuff. Seems very bloated already for something which is v2.0

I got a PSD from a design which I need to built out. So I just need to make a custom "theme" for a single web page. I start with default theme but there isn't a white button in default which I need for my theme. Should I add a new style to definitions? to overrides? to variables? Should I make a site override or override default or override something other level? I think the separation of concerns here is too over-engineered. It feels like the tyranny of the minority is at work here to ruin the experience for the majority.

**Comment by Maxhodges** [comment]
If raising money would help, what would you charge for a one-hour jump start tutorial?  I've been hiring people on upwork to learn from but they don't have clear answers to these questions either.

**Comment by jlukic** [comment]
PM me on Gitter, that is probably a better venue for this kind of communication. I'm sorry you're not happy with Semantic UI, but keep in mind this is a forum for constructive criticism. It doesn't really help the project to express blame or non-specific statements of dissatisfaction.

**Comment by Maxhodges** [comment]
understood. I:m trying to be constructive but also don't want to respect your time, so trying to avoid going into countless details over how statements in the doc create confusion and lead us to dead ends. If I could interview you until I this stuff made sense to me, then maybe I could help write up something to help others. 

Will try Gitter.

Cheers,
