### ISSUE TITLE
[Search] Pass query to onSearchQuery callback

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2741]
It would be extremely helpful if Search's `onSearchQuery` callback had direct access to the actual query when it's triggered.

**Comment by jlukic** [comment]
onSearchQuery receives query as first parameter. This is just missing from docs.

**Comment by jlukic** [comment]
Added https://github.com/Semantic-Org/Semantic-UI-Docs/commit/10e421502205983b51fccfe419ba0bee03105995

**Comment by mnquintana** [comment]
Awesome, thanks @jlukic!
