### ISSUE TITLE
Container Fluid Overflow

### ISSUE THREAD

**Issue by sangyoo91** [Semantic-Org/Semantic-UI#2744]
**main.jade**
```
  .ui.container.fluid
    .ui.inverted.fixed.main.menu
      a.active.item
        | Home
      a.item
        | Messages
      a.item
        | Friends
    .ui.stackable.two.column.padded.grid
      .row
        .column
          .ui.segment
            p row 1 col 1
        .column
          p row 1 col 2
      .row
        .column
          p row 2 col 1
```

Hey guys.

I am using jade, so I apologize if this is hard to comprehend.

I have the following layout, and it works fine except in mobile, the `two column grid` overflows the viewport width.

Is there something that I am doing wrong?

### **Edit 1**
I noticed that even in the docs, the `.container.fluid` overflows content on the right side of the screen.
Is this a bug?

**Comment by jlukic** [comment]
Can you paste the outputted html into a JSFiddle, there's a link to fork in the readme.

**Comment by sangyoo91** [comment]
@jlukic  Here you go.

http://jsfiddle.net/3jbc1qmL/2/

**Comment by jlukic** [comment]
It appears if removing `fluid container` wrapper  solves issue. 
http://jsfiddle.net/at7be4aL/

Since fluid container is equivalent to 100% this seems to have no effect on the display. I'm still seeing whether this issue can also be solved for the test case as submitted

**Comment by jlukic** [comment]
`fluid container` was causing overflow at mobile resolution due to specificity issue in selectors, added to `2.1`

**Comment by sangyoo91** [comment]
@jlukic Thank you so much!

**Comment by jlukic** [comment]
Containers aren't necessary, `fluid container` are only useful to apply things like text alignment to a section of content.
