### ISSUE TITLE
how to install semantic-ui for a second project

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI#2745]
the method of installed semantic-ui in [getting started] (http://semantic-ui.com/introduction/getting-started.html#install-semantic-ui) can only be used for one project.

When you try to run it a second time in a new project folder, you get this error  `Current version of Semantic UI already installed`

How to install semantic again for a second project?

```
maxMBP:wrehome-semantic maxhodges$ sudo npm install semantic-ui
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
|
> semantic-ui@2.0.7 install /Users/maxhodges/node_modules/semantic-ui
> gulp install

[00:13:09] Using gulpfile ~/node_modules/semantic-ui/gulpfile.js
[00:13:09] Starting 'install'...

Current version of Semantic UI already installed
semantic-ui@2.0.7 ../../../node_modules/semantic-ui
├── map-stream@0.1.0
├── extend@2.0.1
├── wrench@1.5.8
├── mkdirp@0.5.1 (minimist@0.0.8)
├── run-sequence@1.1.2 (chalk@1.1.0)
├── jquery@2.1.4
├── gulp-json-editor@2.2.1 (deepmerge@0.2.10, detect-indent@2.0.0, through2@0.5.1, js-beautify@1.5.10)
└── gulp-prompt@0.1.2 (event-stream@3.0.20, inquirer@0.3.5)
maxMBP:wrehome-semantic maxhodges$ gulp install
[00:13:18] No gulpfile found
maxMBP:wrehome-semantic maxhodges$ ls
maxMBP:wrehome-semantic maxhodges$ 
```
nothing installed

**Comment by jlukic** [comment]
Semantic crawls up folder structure looking for a `semantic.json` file. 

This is the file that defines the root of a project using SUI. If  one already exists and the versions match, then the install script will do nothing.

**Comment by Maxhodges** [comment]
so how to install semantic for a new, empty  project folder? 

create a semantic.json file in the root with a different version so that the installer doesn't do nothing? 

or do I misunderstand something? should I just copy my old project to a new folder and copy the src files manually from the semantic  repo?

**Comment by jlukic** [comment]
If your project has `semantic.json` and the path specified in that file points to valid definition files, the installer will stop. If you are creating a new project by copying another folder, you'll already have all the files required.

**Comment by Maxhodges** [comment]
>Semantic crawls up folder structure looking for a semantic.json file.

OK so the first time I installed semantic here /Users/maxhodges/

Now I have a new project where I'd like to use semantic
/Users/maxhodges/Documents/github/wrehome

So yes, if you crawl up the folder structure eventually will find semantic, and therefore do nothing.

But you could give me a more direct answer to my direct question
How to install semantic again for a second project?

Because if you use the installer you can pick components to install, but when creating a second project, it seems if I can only install by copying then I lose the ability to selectively choose which components to install right?

I hate to keep asking the same question three times, but I still don't see the way forward in your two replies.

**Comment by Maxhodges** [comment]
my original project was only 14MB when checked into git. 

My second project is 100MB, after setup by cloning the semantic-ui repo (since the installer wouldn't work a second time)

Based on the information you provided, I guess I can still use the installer as long as I never nest a new project under an older project

 /Users/maxhodges/newProject/oldProject/oldestProject 
This is ok because you always install a newer project higher up in the folder hierarchy

so when created a new project, first move the previous project down and insert a new folder above it for the new project. seems a bit weird, but that's basically what you are implying right?

**Comment by Maxhodges** [comment]
Basically you're answer provides a bit of context, but I'm still left trying to figure out the solution based on the implications of your reply (moving folders around). Is that your recommended way to get started with semantic on a second web design project?

**Comment by jlukic** [comment]
My recommendation is just make sure to have your projects in adjacent directories

i.e.
* `~/myhome/project-one/
* `~/myhome/project-two/`

This is intended to work with `git` and generally git operates off the same principle. Having an initialized git repository in a parent folder will make changes appear to occur as part of that project.

**Comment by Maxhodges** [comment]
OK thanks for your help! I found a semantic.json file in /Users/maxhodges which had been orphaned. that was pretty much screwing up all the installation attempts.

**Comment by avalanche1** [comment]
@jlukic , Maybe we should document this?

**Comment by Maxhodges** [comment]
Yeah I feel like a lot of things are not really explained at all, and a lot of the explanations are rather 'fragile'. Explaining some of the more difficult concepts two or three different ways is likely to help more people.

I try to rewrite a section of the docs to show you what I mean. I have technical writing experience, and as a Semantic UI newbie, I might be in a good position to understand what kind of traps and pitfalls new users will experience.

**Comment by avalanche1** [comment]
@Maxhodges PRs to docs are very welcome!

**Comment by jlukic** [comment]
Please let me know @Maxhodges what you think. If you prefer to write in markdown or another format that works as well. I'll happily convert the code for docs.

**Comment by Maxhodges** [comment]
just got started here
https://github.com/Semantic-Org/Semantic-UI/wiki/Unofficial-Supplemental-Guide-to-Semantic-UI

but launching a new product today, so will back to come back to this!
