### ISSUE TITLE
Accordion height is the same for all items

### ISSUE THREAD

**Issue by magestican** [Semantic-Org/Semantic-UI#2747]
I am having an issue with the accordion functionality, all the different options in the accordion take the same height regardless of their content, like this :

Height is perfect ( matches the end of content) 
![image](https://cloud.githubusercontent.com/assets/4212255/8983039/9ea14d4e-3701-11e5-9a2c-588c22576b12.png)

Height is wrong (takes the same height as the previous accordion option)
![image](https://cloud.githubusercontent.com/assets/4212255/8983060/bb43673e-3701-11e5-8e07-d8108716e88b.png)

I have tried using .accordion("refresh") but no results

Is it supposed to work this way or is this a bug? Anyways it would be good to see this working correctly..

**Comment by jlukic** [comment]
Please create a test case.

**Comment by gutosan** [comment]
Seens like you are adding accordion in a sidebar.

This fix the height of the contents:
```javascript
$('.ui.accordion').accordion({
        onOpen: function() {
            $('.ui.accordion .content').attr("style", $('.ui.accordion .content').attr("style") + "height: auto")
        }
    });

**Comment by avalanche1** [comment]
Closing until there's a test case.
