### ISSUE TITLE
[Menu] item text color change when scrolling over elements

### ISSUE THREAD

**Issue by mallinus** [Semantic-Org/Semantic-UI#2751]
Hi, 

First of all great work on the framework guys, I really like it so far. However, I've encountered one strange bug;

So when using a fixed menu and scrolling down the page, the color of the ui.blue.bordless.item changes. I've already checked all CSS properties and the styling of the element not being changed at all. This is also happening only on Chrome browser (I tested on Edge and FireFix and it did not occur).

This is how the menu looks like default:

![](http://i.imgur.com/amh6I3n.png)

And  this is how it looks like when I start scrolling on the page: (as you can see it gets a lighter color)

![](http://i.imgur.com/B3rrqZ7.png)

For some reason it also only changed color when scrolloing over certain content (transparant inputs, ...) and on other content it keeps its original color.

This is my HTML code:
```html
<div class="ui fixed stackable menu">
	<div class="ui container">
		<a href="feed" class="ui borderless item">
			<img src="/images/logo.png">
		</a>

		<a href="profile" class="ui active blue borderless item"><b>Mathias</b></a>
	</div>
</div>

**Comment by Deall0c** [comment]
I noticed the same strange bug, when scrolling some elements the menu changes slightly

**Comment by mallinus** [comment]
After some debugging it seems like when disabling the box-shadow of the .ui.menu it doesn't occur.

```css
box-shadow: 0 1px 2px 0 rgba(34,36,38,.15);

**Comment by Deall0c** [comment]
There's an issue made on the semantic repo [here](https://github.com/Semantic-Org/Semantic-UI/issues/2751)

**Comment by jlukic** [comment]
I don't think there's anything we can do here. This will be resolved as browsers GPU rendering support is improved.

**Comment by mallinus** [comment]
I'm not a CSS expert but aren't there ways to use alternative stylings instead of box-shadows?

**Comment by jlukic** [comment]
Box shadows are the only way to add shadows in css.
