### ISSUE TITLE
[Dropdown] Number valued items can not be removed after other remote search

### ISSUE THREAD

**Issue by dgurkaynak** [Semantic-Org/Semantic-UI#2754]
I'm trying to use dropdown module with multiple selection and remote content. And I came across with a bug. If item value is a number, after another search (when new items arrived), previously added items can not be removed. 

Fiddle: https://jsfiddle.net/juswr4o0/

To reproduce:
- Search and add an item.
- Clear query, search and add another item.
- Then try to remove items by pressing backspace or clicking `x` icon on the labels.

Demo:
![demo](http://i.imgur.com/xRxTve8.gif)

After a little bit digging, I realised that there is no problem with string values. I guess the problem is `jQuery.data()` is returning number value and semantic's dropdown module searchs that value in array with string values.

My workaround is treating all the values as string.

Btw, testing with v2.0.7.

**Comment by jlukic** [comment]
Re-implemented using very similar code, credit given. Fixed in `next`
