### ISSUE TITLE
Label Tag - problem with long text

### ISSUE THREAD

**Issue by AlanRR** [Semantic-Org/Semantic-UI#2756]
Using class "ui tag label" has the same problem with long text. It goes outside of their container. 

This was resolved for Multiselect: Multiple Select - problem with long texts #2288 

Is it possible instead of go to a second line for overflow, have the option of keep the label tag in one line with ellipsis ("one-line" property doesn't work because it show always one label tag for line when I tried to display several tags)

**Comment by avalanche1** [comment]
Closing until there's a test case.
