### ISSUE TITLE
[Dropdown] Support for search in-menu selection

### ISSUE THREAD

**Issue by ppawel** [Semantic-Org/Semantic-UI#2757]
Dropdown with a search input inside the menu is perfect from UX point of view for my use case but it seems that it cannot be used when a dropdown has `selection` class on it:

![screenshot from 2015-08-01 12-11-59](https://cloud.githubusercontent.com/assets/469990/9021531/92ef11a2-3846-11e5-97c0-cd8f5f869f24.png)

I guess it is only supported when dropdown is a button?

I'd be willing to try to develop this but please let me know if this even makes sense and is in-line with your roadmap / design vision of the dropdown component.

**Comment by jlukic** [comment]
Selection menu are a special type of dropdown that only support `item`.  (Think of it as a reskin of a `<select>`

Only normal dropdowns support `header`, `divider`, or `input`
