### ISSUE TITLE
[Transition] this is Not Correctly Set on Callbacks

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2758]
`$('#mainPhotoLabel').transition('fade out', {onHide:-> this.removeClass('hidden'})`
I would like to be able to remove class `hidden` from `#mainPhotoLabel` after animation is finished.

**Comment by startswithaj** [comment]
Yeah I can see what your saying here.

In transition.js module.hide() calls settings.onHide.call(this); which sets the context to the semantic Module. The semantic module instance has access to but does not expose $module (the underlying jquery wrapped element).

You could change it to settings.onHide.call($module); or you could leave it and do

```
this.$module = $module
settings.onHide.call(this);
```

but I would say $module is obscured for a reason.

**Comment by jlukic** [comment]
This is a bug, on this line `this` should be `module`
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/transition.js#L771
