### ISSUE TITLE
[Popup] Popup Cannot Escape Parent Overflow

### ISSUE THREAD

**Issue by nehalist** [Semantic-Org/Semantic-UI#2759]
A non-inline popup within a dropdown works fine:
![popup-ok](https://cloud.githubusercontent.com/assets/1016497/9023651/1ec6adbc-38a5-11e5-8bc8-fbd1915e4be0.jpg)
```
<div class="item tooltip" data-content="Issue information" data-position="left center" data-variation="inverted" data-value="hello world" data-text="#1234">
                                        <span class="description">#1234</span>
                                        <span class="text">hello world</span>
                                    </div>

// js
$('.tooltip').popup();
```

But inline popups doesn't work
![popup-notok](https://cloud.githubusercontent.com/assets/1016497/9023672/cd8790dc-38a5-11e5-9860-b4de28240910.jpg)

```
<div class="item tooltip" data-content="Issue information" data-position="left center" data-variation="inverted" data-value="hello world" data-text="#1234">
                                        <span class="description">#1234</span>
                                        <span class="text">hello world</span>
                                    </div>
<div class="ui special popup">
                                        this is a test, this is a test, this is a test
                                    </div>

// ---
$('.issue-tooltip').popup({ inline: true; });
```

Positioning the popup `left center` hides the popup completely. Reason seems to be the fact that the popup container is "trapped" within the dropdown.

Another bug I've found while playing around with dropdowns and popups:
The not-working attempt with the inline popup also triggers the following error when scrolling down:

> Popup: Popup does not fit within the boundaries of the viewport

**Comment by jlukic** [comment]
This is a limitation of `overflow` css property, is that `inline` content cannot escape its parent's overflow, in this case `scrollable menu`. Generally this is why most popup libraries only support popups as children of `body`. The `inline` feature is a somewhat unique enhancement to semantic ui.
