### ISSUE TITLE
[Embed] Remove Console Logs

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#2760]
There are four `console.log` expressions in **embed.js**. Is it an expected behaviour?

  - https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/embed.js#L100
  - https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/embed.js#L135
  - https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/embed.js#L146
  - https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/embed.js#L454

**Comment by jlukic** [comment]
bad bad bad bad me
