### ISSUE TITLE
No way to submit form without using a mouse

### ISSUE THREAD

**Issue by TonnyORG** [Semantic-Org/Semantic-UI#2761]
I'm trying to implement a "TAB" friendly form but I found that there's no way to make it works properly.

The problems here are two:
1- There's no way to focus on buttons (at least not for submit, you can see in your [own documentation](http://semantic-ui.com/collections/form.html)) if you just move using TAB button (no mouse).
2- If you're using form validations, there's no way to submit form without press submit button (ENTER button doesn't work when you use-> inline: true & on: 'blur' and fill all required data properly, you can see a sample at [your own documentation too](http://semantic-ui.com/behaviors/form.html#validating-on-blur-and-other-events)).

Regards!

**Comment by TonnyORG** [comment]
@avalanche1 thank you for your useful response. Semantic-UI official docs have the same issues so I don't think you already resolved this.

**Comment by jlukic** [comment]
I think this was incorrectly tagged. I'll look at this.

**Comment by TonnyORG** [comment]
Thank you @jlukic, if you've idea what it could be just let me know and I can try to help you with the solution.

**Comment by jlukic** [comment]
I just moved into a new apartment today, but will be back to usual bug queue tomorrow.

**Comment by jlukic** [comment]
Looking at current docs with `2.1` I'm not seeing this issue. If you continue to see it let me know and I will re-open.
