### ISSUE TITLE
[Label] - Flashing Black if Toggled With Javascript

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2763]
http://codepen.io/avalanche1/pen/OVZRJX - click chckbx
Before becoming red, label flashes black.

**Comment by avalanche1** [comment]
This is caused by this
```stylus
.ui.corner.label:after
  -webkit-transition: border-color 0.1s ease;
  transition: border-color 0.1s ease;
```

**Comment by jlukic** [comment]
I'll look at transition property to see why this was set originally

**Comment by avalanche1** [comment]
Jack, could you take a peek at this. Looks really ugly.

**Comment by jlukic** [comment]
I dont think it's possible to animate class from no class to `ui red label` without triggering css transitions improperly. 

`ui label` and `ui corner label` have two different constraints for possible transitionable properies.

I'd recommend animating from `ui corner label` to `ui red corner label` or in your particular case setting

```css
.ui.corner.label {
  transition: none;
}}
```
