### ISSUE TITLE
[Icon] UTF Content Accidentally in Class Name for Cube

### ISSUE THREAD

**Issue by idleberg** [Semantic-Org/Semantic-UI#2765]
I'm not sure what this icon is supposed to be called, but  `\33d` looks like a typo to me (see [line 2504](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/icon.css#L2504))

The corresponding Font Awesome class is `fa-cube`, here's what it looks like:

![box](https://cloud.githubusercontent.com/assets/1504938/9027308/e7af8478-3950-11e5-863f-8d6f910eaeaa.png)

**Comment by jlukic** [comment]
This is a typo. I'll fix

**Comment by jlukic** [comment]
I removed the duplicate rule since `cube icon` is already defined. Not sure what the intended alias would have been.
