### ISSUE TITLE
Dropdown on Hover or Click

### ISSUE THREAD

**Issue by abagshaw** [Semantic-Org/Semantic-UI#2773]
I would like my dropdown menu to be activated on hover, however on touch devices that makes it pretty much impossible to use the menu. Is there a way to activate the dropdown menu on **either hover or click** - or better yet is there a way to set the dropdown to activate on hover when on mouse and keyboard devices but on click when on touch devices?

**Comment by jlukic** [comment]
This [happens automatically](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L475) when using `hover.
