### ISSUE TITLE
Consistency in button group

### ISSUE THREAD

**Issue by yordis** [Semantic-Org/Semantic-UI#2775]
I am following this example and the button on the middle doesn't have an icon class, my understanding about is if I have a icon inside the button I should put the icon class in the button element or could be in the buttons element level but I can't put an icon there because will break the UI (it will remove some margin right).

I prefer if we just put the icon class in the button element.

```html
<div class="ui buttons">
  <button class="ui labeled icon button">
    <i class="left chevron icon"></i>
    Back
  </button>
  <button class="ui button"> // this doesn't have an icon class
    <i class="stop icon"></i>
    Stop
  </button>
  <button class="ui right labeled icon button">
    Forward
    <i class="right chevron icon"></i>
  </button>
</div>
```

**Comment by jlukic** [comment]
`icon button` is used for a button with *only an icon*. This removes the right margin from the icon so it sits flush inside the button. Otherwise, it'll assume there is text next to it and add right margin.

**Comment by yordis** [comment]
@jlukic so if I have a text and I should't put the icon class in the button? Is that right? Because then I need to do some changes.

**Comment by jlukic** [comment]
Yes, check definition 
"A button can have *only* an icon"
http://semantic-ui.com/elements/button.html#icon

**Comment by yordis** [comment]
Got it
