### ISSUE TITLE
conflicting javascript when open a side iframe

### ISSUE THREAD

**Issue by thanush** [Semantic-Org/Semantic-UI#2776]
i'm using iframe in my project when i'm opening that iframe in event total css and js effecting like below image
![task](https://cloud.githubusercontent.com/assets/6806782/9059254/f9f63c14-3ac5-11e5-9498-4f6c1ab82c92.gif)

**Comment by jlukic** [comment]
It looks like content in the center column is not properly reflowing in chrome when opening the right sidebar. Try forcing layers using `will-change: transform;` or `transform: rotateZ(0deg);` on each section of the view.
