### ISSUE TITLE
[Label] - Corner Label Border Radius

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2780]
The way corner label is currently implemented doesn't allow for adding corner radius to parent el - the label will still be having a 90deg angle.
![image](https://cloud.githubusercontent.com/assets/10534563/9068284/ad7e9aba-3af3-11e5-903b-fa757b9181dd.png)
Is there another way to allow for rounded label? Like here: http://stackoverflow.com/questions/22930838/how-to-create-triangle-with-only-one-rounded-corner-using-css-or-css3

**Comment by devcline** [comment]
Any news on this issue? i cant make it borderless too
