### ISSUE TITLE
[Popup] .popup('is visible') initially returns DOM element

### ISSUE THREAD

**Issue by hpohl** [Semantic-Org/Semantic-UI#2781]
http://jsfiddle.net/yzjop769/1/

When the popup never has been opened, the target element is returned instead of `false`.

**Comment by homerjonathan** [comment]
Seems there is the same issue with sidebar.  When calling is visible and it has not been toggled then it too returns the target element.

**Comment by jlukic** [comment]
@hpohl @homerjonathan 

Thanks for your patience here. `is visible` was returning `undefined` in the case where `$popup` was undefined. This was making the invocation fail and revert to chaining instead of returning the result. 

I've modified the booelan to correctly return `false`.
