### ISSUE TITLE
[Input] Input with icon and label

### ISSUE THREAD

**Issue by Buom01** [Semantic-Org/Semantic-UI#2782]
# Hi,
It's seem that an input with an icon and a label doesn't show correctly;
- Input with icon:
![input icon](https://cloud.githubusercontent.com/assets/1537208/9072148/cc91a48c-3af9-11e5-8fc0-05a051d9ca8e.png)

- Input with icon and label:
![input icon-label](https://cloud.githubusercontent.com/assets/1537208/9072117/a1c691ea-3af9-11e5-93fb-a9b810728708.png)

http://jsfiddle.net/efp8z6Ln/168/

Using semantic:ui-css 2.0.7 on meteor (actually the lastest)
This worked before the 2.0.0

Is it a bug or a missing function ?

**Comment by jlukic** [comment]
This needs significant word order to distinguish left.

**Comment by geemang2000** [comment]
:+1:

**Comment by jlukic** [comment]
Fixed in `2.1`
