### ISSUE TITLE
[Input] Fix Errored Placeholder Text Color

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#2786]
[see this fiddle](http://jsfiddle.net/jholl/d65saLsg/)

Any interest in working a little lighter coloring for the placeholders into default theme for input states?  Could just be my eyes, I don't have any stats on accessibility or proper spec.

**Comment by jlukic** [comment]
Thanks

**Comment by jlukic** [comment]
Fixed in next, colors for error placeholder are much lighter
http://jsfiddle.net/gsw6zmqn/

**Comment by Goatic** [comment]
Has this been fixed? :) my input placeholders default to black and not gray

I'm running the meteor package with default theme, all components included.
