### ISSUE TITLE
[Dropdown] "0" value appears as placeholder text

### ISSUE THREAD

**Issue by caiotarifa** [Semantic-Org/Semantic-UI#2788]
Possibly like the #2072.

I found a series of bugs related to the topic of this issue.
**DEMO:** http://codepen.io/caio/full/vObeoM/

### First Case: select with value.
If we have `value` and `text content`, all works.

---

### Second Case: select without value.
So, if we remove the `value`, the dropdown shows it like a `placeholder`, but you can't re-select this `option`.

---

### Third Case: select without value and text content.
Now we remove the `value` and the `text content`, the dropdown doesn't show the `option` and you can't re-select that.

---

### Others
Form `reset` and `required attribute` doesn't work as expected. :disappointed:

**Comment by jlukic** [comment]
Placeholder values should only match `value=""` not `value="0"` as you mention. This is probably a side effect of other fixes with dropdown and `===`.

To disable placeholder text, or specify it programmatically you can always use `placeholder` setting.
http://semantic-ui.com/modules/dropdown.html#frequently-used-settings

**Comment by caiotarifa** [comment]
No @jlukic, you got it wrong.

The "0" `value` is not acting as a `placeholder` and when I changed this, everything worked normally and resolved the main issue. :smile: 

But the `required` and `reset` issues still exist.

**Comment by jlukic** [comment]
Oh i misread when scanning through the code. Everything is behaving as normal then. 

Required doesn't work on hidden inputs. Built in form validation is limited in scope (and awfully styled), i'd recommend using our form validation. 

You can also reset dropdowns using 
```
$('.ui.form').form('reset');
$('.ui.form').form('clear');
```

**Comment by caiotarifa** [comment]
Oh, it helped me a lot!

Thank you! :+1:
