### ISSUE TITLE
Recommended to adjust the size of Gutter

### ISSUE THREAD

**Issue by zhangfisher** [Semantic-Org/Semantic-UI#2789]
Grid component
Recommended to adjust the size of Gutter.

eg. none,mini,small,normal,large

**Comment by jlukic** [comment]
This already exists. `relaxed` and `very relaxed`.
http://semantic-ui.com/collections/grid.html#relaxed

**Comment by nick-lee** [comment]
relaxed seems only increase the gutter size, may I decrease the size ?
in mobile device I want to decrease the size of gutter to make it more fit to screen .
