### ISSUE TITLE
[Form/Checkbox] form behavior 'get values' ignores unchecked checkboxes

### ISSUE THREAD

**Issue by ho-ho-ho** [Semantic-Org/Semantic-UI#2792]
When using checkboxes that can be either checked or unchecked ( no special validation ), they are only included into the result of the `get values` behavior when checked.

Result of $(...).form('get values') when unchecked: `Object {}`
Result of $(...).form('get values') when checked: `Object {enabled: true}`

I think it would be better if `Object {enabled:false}` would be returned if unchecked.

Fiddle: https://jsfiddle.net/37s2x453/

**Comment by jlukic** [comment]
This has already been fixed in unreleased `2.1` build
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/behaviors/form.js

**Comment by ho-ho-ho** [comment]
Very nice, thanks ! :)
