### ISSUE TITLE
[UI] Dropzone

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#2796]
A dropzone would be a large box which a file could be dragged & dropped to trigger file upload dialog. 

This would include a class "file upload" dialog as well to allow users to navigate their file system.

**Comment by pklink** [comment]
+1

**Comment by swhgoon** [comment]
+1

**Comment by dbrw** [comment]
+1

**Comment by brainscript** [comment]
+1

**Comment by crewow** [comment]
We need dropzone jlukic

**Comment by xiwc** [comment]
+1

**Comment by AdamBCo** [comment]
+1

**Comment by AdrienFery** [comment]
+1

**Comment by apark0720** [comment]
+1

**Comment by blu94** [comment]
+1
