### ISSUE TITLE
[Header] Top attached header followed by attached has no dividing border

### ISSUE THREAD

**Issue by nothingisdead** [Semantic-Org/Semantic-UI#2798]
I believe this issue was introduced in 62110fc51fd8416fecdfe1ed08a5db76259bdee1. When you have a top attached header element followed by an attached segment element, there is no bottom border on the header, and no top border on the segment, and therefore nothing to divide them.

The issue is visible on the kitchen sink page in the attached header example:
http://semantic-ui.com/kitchen-sink.html#header

**Comment by jlukic** [comment]
I've been using [this example layout](http://semantic-ui.com/examples/attached.html) for debugging attached, looks like I missed this case.

**Comment by jlukic** [comment]
Sorry for the slowness with this, It was a pretty simple fix.
