### ISSUE TITLE
Touch event cant trigger penetrate '.pusher' when sidebar shown.

### ISSUE THREAD

**Issue by elantion** [Semantic-Org/Semantic-UI#2801]
I'm new in SUI. I have used Bootstrap a long time. 
As the title said. I am struggle with the touch event problem. Dose anyone seen the issue before?
PS: I'm using AngularJs.
```html
<div class="ui sidebar left" id="left-sidebar">
    <div id="sidebar-menu-top">
        <a class="item left-sidebar-btn">
            <i class="sidebar icon"></i>
        </a>
        <a href="#" class="item">
            <span><i class="home icon"></i>Home</span>
        </a>
        <a href="#" class="item">
            <span><i class="search icon"></i>Search Jobs</span>
        </a>
        <a href="#" class="item">
            <span><i class="empty star icon"></i>Saved Jobs</span>
        </a>
    </div>
    <div id="sidebar-menu-bottom">
        <a href="#" class="item">Privacy Policy</a>
        <a href="#" class="item">Term Conditions</a>
        <span class="item">xxxx</span>
    </div>
</div>
```

```javascript
$(document).ready(function () {
    'use strict';
    $(document).on('touchend', '.left-sidebar-btn', function (event) {
        event.preventDefault();
        $('.ui.sidebar.left').sidebar({
            mobileTransition: 'overlay'
        }).sidebar('toggle');
    });
});
```

**Comment by jlukic** [comment]
What is the problem that occurs?

**Comment by elantion** [comment]
Sorry for my suck English. I explain again and plus images.

I click the sidebar trigger button
![qd741st_vept5 e9l 7z s2](https://cloud.githubusercontent.com/assets/1912695/9158261/eef3b8c6-3f45-11e5-8ecc-c3a80a55726f.png)

Sidebar open then click search button
![ha8upttv5 3s xn_ ked5md](https://cloud.githubusercontent.com/assets/1912695/9158271/12d74406-3f46-11e5-9b1b-ddd64440a5a4.png)

Browser jump to the search page
![37e 4 aso _shzdoa zqk](https://cloud.githubusercontent.com/assets/1912695/9158275/256bf5a8-3f46-11e5-90f6-fb9e50a276d1.png)

I expect it don't trigger the search button link. I just want the sidebar close. I mean the click event has penetrate to the search button and this is not correct. I hope you can understand. Thanks for your time.

**Comment by elantion** [comment]
It's weird. I found this problem only happened in desktop browser simulate mobile environment (Chrome mobile simulator). I test in mobile and Chrome native desktop environment, both don't have this problem.
I don't know is it valuable to fix this issue?

**Comment by jlukic** [comment]
I think this is just related to chrome touch emulation.

**Comment by zh1lu0** [comment]
It also happened in Chrome on iOS 9

**Comment by m4ikel** [comment]
I was able to reproduce this same issue within the current build within both Firefox and Chrome, using touch events. Issue is connected to overflow:x;overflow:y; properties causing 'mouse down' to penetrate the pusher layer.

To me this seems like some sort of brower bug.

For testing, add and the issue should be resolved.
```
.pushable > .pusher{
overflow-x: initial;
overflow-y: initial;
}
```

Unsure why overflow-x/y are being set, but you can actually reproduce this issue on the current Semantic UI website.

**Comment by chethan1095** [comment]
can anyone help me with this after opening sidebar menu inside that if i click a button it should trigger how to do it for ex: i had a form inside sidebar if i click on save button without entering any values validation messages should come how to do it??
