### ISSUE TITLE
[Checkbox] Special case for <a> tag to allow clicks

### ISSUE THREAD

**Issue by Siprah** [Semantic-Org/Semantic-UI#2804]
For example:

     <div class="ui toggle checkbox rnr-register-accept">
         <input type="checkbox" ng-model="accept">
         <label>Accept <a href="/myPage">rules</a></label>
     </div>

Checkbox's event are blocking url. This should be fixed.

**Comment by jlukic** [comment]
Agreed, that's no good.

**Comment by tcigrand** [comment]
Am I missing something or is this not reproducible? 

http://jsfiddle.net/efp8z6Ln/175/

**Comment by Siprah** [comment]
@tcigrand You forgot about JS: http://jsfiddle.net/efp8z6Ln/176/

**Comment by tcigrand** [comment]
Gotcha, thanks, sorry to muddle up the issue.

**Comment by jlukic** [comment]
Fixed in `next`
