### ISSUE TITLE
[Modules] Trim function does not exist in IE 10-11 

### ISSUE THREAD

**Issue by TheSlider2** [Semantic-Org/Semantic-UI#2806]
Greetings,

I have an issue where IE 10-11 messes up my sexy admin tools.
I get an error about trim not being a valid function so i replaced it with "replace(/^\s+|\s+$/g, '')"

Error was reported on line 4246 ( semantic.js  v1.12.3 )
real lines were 4249 and 4250
```
? $choice.html().trim()
: $choice.text().trim()
```
becomes
```
? $choice.html().replace(/^\s+|\s+$/g, '')
: $choice.text().replace(/^\s+|\s+$/g, '')
```
Didn't test much but no more errors + working tools = good enough.

I'll check if this was updated on 2.0 when i'll be upgrading next week.

Cheers

**Comment by jlukic** [comment]
Easy enough

**Comment by jlukic** [comment]
Sorry about delays here, in `next`.
