### ISSUE TITLE
Headers in dropdown menus cause sub-menus instead of header effect

### ISSUE THREAD

**Issue by malacalypse** [Semantic-Org/Semantic-UI#2807]
http://jsfiddle.net/uqqn8vf6/2/

Expected behaviour: Unless the sub-menu is itself a .dropdown.item, the menu should be within the root sub-menu, similar to example for menu header.  Only .dropdown.items should trigger an additional side-menu render.

There are related issues with dropdown menus I'll be filing (and trying to fix, if I get time). This one I'm a bit stuck on right now.

**Comment by jlukic** [comment]
header are expected to be children of menu, a header inside a dropdown does not have any built in functionality.
