### ISSUE TITLE
[Divider] Remove Left Property When Positioned Between Columns

### ISSUE THREAD

**Issue by fstanis** [Semantic-Org/Semantic-UI#2808]
I tried to create a two column grid divided by an *OR* divider, exactly like the [vertical divider example](http://semantic-ui.com/elements/divider.html#vertical-divider). However, when I decided to make the left column narrower than the right, a problem arose - the divider is always exactly on the middle instead of being between the two columns ([fiddle here](http://jsfiddle.net/fstanis/hbyw1y4v/1/) - it's a good idea to increase the width of the *Result* area).

This turns out to be caused by CSS rule for **.ui.vertical.divider** that states *left: 50%*. After removing this rule, the divider positions itself perfectly. Here's a [second fiddle](http://jsfiddle.net/fstanis/hbyw1y4v/2/) which demonstrates this. Is there any reason to keep this *left: 50%* property?

**Comment by jlukic** [comment]
I think this makes sense to add for `ui.grid > .column + .divider`. I'm sure you're also familiar with `ui vertically divided grid` which does this without labels.

In cases outside a grid hwoever, a divider has to assume it needs to position itself.
