### ISSUE TITLE
[Dimmer] - Add gradient dimmers

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#2814]
I just tought that having a partial dimmable elements would be really nice to presents content to user.

The idea is to provide some behiavior attributes in dimmable module to allow dirrection (or side on which we start to dimm) and dimensions (percentage and/or width if possible).
We could for exemple have an image with a 1/5 dimmer from bottom and add some text on this dimmer.

Is it possible?

**Comment by lubber-de** [comment]
Partially Dimmers are available since Fomantic-UI 2.6.4 using `top dimmer`, `center dimmer` or `bottom dimmer`
https://fomantic-ui.com/modules/dimmer.html#partially-dimmer
