### ISSUE TITLE
[Dropdown] onChange not fired when set action: 'hide'

### ISSUE THREAD

**Issue by bianjp** [Semantic-Org/Semantic-UI#2818]
JSFiddle: http://jsfiddle.net/jbcea2cj/3/

According to the documentation about [Specifying Select Action](http://semantic-ui.com/modules/dropdown.html#/usage), the onChange callback should work with `action: 'hide'`,  but in fact it doesn't.

**Comment by jlukic** [comment]
part of this was hidden in a commit earlier today, but will be fixed in `next.

Hide will now `set value` which means you can retrieve using `get value` and use `onChange`
