### ISSUE TITLE
[Build] Install Fails when node_modules found in parent of path

### ISSUE THREAD

**Issue by larrygeams** [Semantic-Org/Semantic-UI#2821]
Typing 'gulp build' can't build semantic and throws an error saying "Cannot find semantic.json. Run "gulp installation" to set-up Semantic though I already installed gulp

**Comment by jlukic** [comment]
How did you get semantic ui? Did you run the interactive installer?

**Comment by larrygeams** [comment]
I just followed it here.
http://semantic-ui.com/introduction/getting-started.html

I read some solution though. It says I need to copy the 'node_modules' inside my project folder and it turns out it works but is there any possible solution for this?

**Comment by jlukic** [comment]
That's really weird. Did you wait for peer dependencies to install? What version of npm are you using?

**Comment by larrygeams** [comment]
Npm version: 2.5.1

Yeah kinda weird. Based <a href="https://github.com/Semantic-Org/Semantic-UI/issues/2056" target="_blank">here</a>, the only solution I can find is copying the node_modules folder to the semantic project but it has tons of files. Would be great if have different solution to this case.

**Comment by mzygmunt** [comment]
I've the same problem. After copying npm_modules following solution - http://semantic-ui.com/introduction/getting-started.html work fine. But it's not convenient solution.

My npm version is 2.5.1 and node 0.12.7

**Comment by hmaesta** [comment]
Is there a solution for this?

**Comment by jonathan-stone** [comment]
It worked for me when I created an empty node_modules folder in the project folder before running npm install semantic-ui --save

**Comment by fo747** [comment]
It also worked to create an empty node_modules folder in the /semantic folder after having installed semantic (to avoid copying the parent node_modules folder).

**Comment by czechnology** [comment]
Unfortunately, creating empty `node_modules` directory doesn't work for me.
Why can't I somehow specify the exact location of the `semantic.json` config file? I'd like to separate my source files from the gulp etc. files (i.e. modules shouldn't be in my project directory at all).

**Comment by jackjwilliams** [comment]
Possible duplicate of #2056
