### ISSUE TITLE
[Selection Dropdown] Disappearing selected option after entering and removing the incorrect text into search field

### ISSUE THREAD

**Issue by mzygmunt** [Semantic-Org/Semantic-UI#2824]
Problem: Disappearing selected option after entering and removing the incorrect text into search field
JSFiddle: http://jsfiddle.net/eLhfshsp/2/
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
How to reproduce on JSFiddle:
1. Select manually any language.
2. Open dropdown and enter any incorrect text eg "adsfadsfadsfsda".
3. Click outside the dropdown.
4. Click on field.
Now you see only one language and the message "No result found" on the dropdown lists.
![image](https://cloud.githubusercontent.com/assets/13297558/9195577/1bec057a-4024-11e5-936a-a1d605249ca0.png)

This same issue occurs when I'll define a default value for the hidden field.
JSFiddle: http://jsfiddle.net/eLhfshsp/3/

**Comment by jlukic** [comment]
Thanks for the clear test case and steps, I can confirm this is a bug.

**Comment by jlukic** [comment]
Fixed in `2.1`

**Comment by mzygmunt** [comment]
I checked solution commit "c9a26af" of the branch "next" and not everything is correct. The message "No result found" is not displayed, but still there is a problem with the selected item when you type some text in the search box.
How to do it again:
1. Select an item.
2. Open the dropdown again.
3. Enter some text in the search box to occur "No result found".
4. Click in the area outside the drodown.
5. When you click on the field you see that you selected in step 1 element disappeared from the dropdown list.

**Comment by jlukic** [comment]
Thanks I appreciate your thoroughness in testing. It really helps out when I'm juggling issues.

Here's a fixed fiddle from `next`, should clear both test cases.
http://jsfiddle.net/t9vfxo5t/
