### ISSUE TITLE
[Form] Avoid display error block if empty

### ISSUE THREAD

**Issue by maturano** [Semantic-Org/Semantic-UI#2825]
Example: http://jsbin.com/mexanositi/edit?html,js,output

Suppose I have a section for displaying error messages within a form; in the example assume such messages could come from the server, regardless from the client-side validation.

Setting true the `inline` option, error section becomes visible even when empty. I think it could be a way and it would be good idea to avoid this. What do you think?

---

HTML:
```html
<form class="ui form segment" action="#">
  
  <div class="ui error message">
    <!-- For error from server -->
  </div>
    
  <div class="field">
    <label>Label</label>
    <input type="text" name="field">
  </div>
  <div class="ui blue submit button">Submit</div>
</form>
```

JavaScript:
```javascript
$('form').form({
    inline: true,
    fields: {
      field: {
        identifier  : 'field',
        rules: [{
            type   : 'empty',
            prompt : 'Please enter a value'
        }]
      }
    }
})


/*
 For later add error messages with something like:
 $('form').form('add errors', messages).addClass('error')
*/
```

Result: 
![2015-08-11-164308_562x243_scrot](https://cloud.githubusercontent.com/assets/5768813/9211465/1023e306-4048-11e5-9bcd-47eab161eec8.png)

**Comment by maturano** [comment]
I do not know CSS, but this patch seems to work at least in Firefox 40.0 and Chrome 44.0.2403.155

```diff
diff --git a/src/definitions/collections/form.less b/src/definitions/collections/form.less
index 6d10fbd..d3f0ad9 100755
--- a/src/definitions/collections/form.less
+++ b/src/definitions/collections/form.less
@@ -358,7 +358,7 @@
 ---------------------*/
 
 /* On Form */
-.ui.form.success .success.message {
+.ui.form.success .success.message:not(:empty) {
   display: block;
 }
 .ui.form.success .icon.success.message {
@@ -366,11 +366,11 @@
 }
 
 /*--------------------
-        Error
+        Warning
 ---------------------*/
 
 /* On Form */
-.ui.form.warning .warning.message {
+.ui.form.warning .warning.message:not(:empty) {
   display: block;
 }
 .ui.form.warning .icon.warning.message {
@@ -378,11 +378,11 @@
 }
 
 /*--------------------
-        Warning
+        Error
 ---------------------*/
 
 /* On Form */
-.ui.form.error .error.message {
+.ui.form.error .error.message:not(:empty) {
   display: block;
 }
 .ui.form.error .icon.error.message {
```

Should I make a pull request?

**Comment by jlukic** [comment]
Empty is a bit of an issue since text nodes don't count for the pseudo selector.

So
```html
<div class="ui error message">
   Warning you did something bad
</div>
```

Would actually not show up.

**Comment by maturano** [comment]
You mean if I can just add the `div.error` block dynamically?... I could, but I like the idea of indicating the location explicitly in the code, you know ... for semantic :smile:

I'm trying with this simple code and the block show for me: http://jsbin.com/porugo/edit?html,css,output ... maybe the issue you mention is with a specific browser or I didn't understand?

Sorry, my English sucks almost like my CSS :disappointed:

**Comment by jlukic** [comment]
Oh no, you are right. I'm thinking about `:empty` js selector which [does include text nodes](https://api.jquery.com/empty-selector/)

**Comment by maturano** [comment]
Excellent!. Thank you so much.

Only one minor observation. In my patch, I also corrected the "header comments". It said ["Error" when should be "Warning"](https://github.com/Semantic-Org/Semantic-UI/blob/8c829425ea20746e087abdef7d39f65f9c746487/src/definitions/collections/form.less#L383) and [vice versa](https://github.com/Semantic-Org/Semantic-UI/blob/8c829425ea20746e087abdef7d39f65f9c746487/src/definitions/collections/form.less#L395).

Something unimportant, but ... :stuck_out_tongue_winking_eye:
