### ISSUE TITLE
Site documentation bug - Item bottom

### ISSUE THREAD

**Issue by geemang2000** [Semantic-Org/Semantic-UI#2826]
The bottom example is not on the bottom: http://semantic-ui.com/views/item.html#vertical-alignment

![screen shot 2015-08-11 at 6 11 26 pm](https://cloud.githubusercontent.com/assets/392233/9213083/6d5294bc-4054-11e5-8c55-dfcd5aaee758.png)

**Comment by jlukic** [comment]
Thanks, this was an improper flex value.
