### ISSUE TITLE
Icon and icon button size differences

### ISSUE THREAD

**Issue by vennamo** [Semantic-Org/Semantic-UI#2827]
Take a look of this fiddle. http://jsfiddle.net/fdmao397/2/
Sizes vary between icon button's icon and circular icon's icon.

Those share same shape, but have different font sizes and paddings. Any way to make these two look the same as a default setting?

**Comment by jlukic** [comment]
I think it makes more sense that circular buttons have the same padding as button than as icon. Buttons generally require a larger hitbox, particularly for mobile. 

Circular icon aren't designed generally to be linkable, but used to emphasize an icon for something like an `icon header`
