### ISSUE TITLE
Loads of install errors with 2.0.8

### ISSUE THREAD

**Issue by kristianmandrup** [Semantic-Org/Semantic-UI#2829]
MacOSX, IOjs 3.0, npm 2.13

I had to install all of these modules manually using `npm install 'name` after  `npm install semantic-ui --save` failed in each case... I wonder why?
Will try to go back to install a previous release npm install semantic-ui@2.0.7 --save`

```sh
Cannot find module 'wrappy'
...
Cannot find module 'lodash._getnative'
...
Cannot find module 'lodash.isarguments'
...
Cannot find module 'lodash.isarray'
...
Cannot find module './lib/_stream_transform.js'
```

**Comment by kristianmandrup** [comment]
Turns out it was some issue with my system or particular project. When I tried again, installing semantic-ui as the first step, there was no problem..

**Comment by jlukic** [comment]
Cheers
