### ISSUE TITLE
destroy and remove not mentioned anywhere in the docs.

### ISSUE THREAD

**Issue by giantelk** [Semantic-Org/Semantic-UI#2831]
`destroy` and `remove` not mentioned anywhere in the Semantic UI docs. See below, I'm using this to remove an infinite scroller / visibility from the DOM. When using ReactJS, it triggers multiple times++ every time my React component re-mounts, hence I remove it in React's `componentWillUnmount()`. 

Is this the correct way to be removing `visibility`? It's not documented on the main Semantic docs site about using `destroy` and/or `remove`. http://semantic-ui.com/behaviors/visibility.html

`$('.my-feed').visibility('destroy').remove();`

**Comment by jlukic** [comment]
The plan was to have a tutorial specifically for all modules, including explanations of common methods, `setting`, `destroy`, `refresh`, `internal` etc. Explanation of how instances are stored in metadata, can be retrieved, how logging works, etc. 

Unfortunately, I haven't had the bandwidth to write it yet.

**Comment by giantelk** [comment]
Do you have anything started that I could use as a seed to help contribute?

On Wed, Aug 12, 2015 at 11:48 PM, Jack Lukic <notifications@github.com>
wrote:

> The plan was to have a tutorial specifically for all modules, including
> explanations of common methods, setting, destroy, refresh, internal etc.
> Explanation of how instances are stored in metadata, can be retrieved, how
> logging works, etc.
>
> Unfortunately, I haven't had the bandwidth to write it yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/2831#issuecomment-130521564>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by jlukic** [comment]
Yes, but I removed because it was out of date.
https://github.com/Semantic-Org/Semantic-UI-Docs/blob/1.0/server/documents/module.html.eco

**Comment by levithomason** [comment]
@giantelk There is now an officially supported Semantic-UI-React that implements components in the React paradigm without jQuery: https://github.com/TechnologyAdvice/stardust

I'll soon port it to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).

Cheers
