### ISSUE TITLE
Minified Build forgets reset.less?

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#2835]
Hello there,

I just came upon an issue, where it seems that the gulp build I am running to build Semantic UI forgets to include reset.less into semantic.min.css.
It's all behaving well again, when loading the unminified build.

I use Semantic UI's latest version 2.0.8 and running standard build
Could you please check that?

I'd include my build CSS files, but I don't know how to attach files here!?

Thanks,
Sascha.

**Comment by jlukic** [comment]
The files in `dist/semantic.min.css` appear to have reset included.
