### ISSUE TITLE
Circular icon in list item expands height with table-cell

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#2837]
I'd like to use circular icon instead of avatar image in a list item; however as the list item expands in height the padding-bottom of the circular icon gets stretched with table-cell.  I can fix by floating the icon left, but that may not be the best way.

[jsfiddle](http://jsfiddle.net/jholl/k0tsjph9/)

btw, thanks so much for building Semantic.

**Comment by jlukic** [comment]
Table cell is used to allow for `vertical-align`. It does have the limitation that content is stretched.
