### ISSUE TITLE
search, show results not working

### ISSUE THREAD

**Issue by mgrulich** [Semantic-Org/Semantic-UI#2842]
"show results" is not working with search, "hide results" works fine.

**Comment by jlukic** [comment]
Caused by
```javascript
if( !module.is.visible() && module.is.focused() && !module.is.empty() ) {
  // do show
}
```

I moved this check outside of the method, so it can be invoked when not focused.

**Comment by jlukic** [comment]
Ignore that last commit. heh

**Comment by mgrulich** [comment]
Hi @jlukic thanks for the fix, but can you tell me how can I fix my issue (small code example)? I'm not understand how the changes fixes my issue, sorry.

**Comment by jlukic** [comment]
Here
http://jsfiddle.net/acufknc2/

**Comment by mgrulich** [comment]
Thank you, has not worked in my first test after your commit, but I've now seen, I've tested with the wrong branch, sorry. Is working for me now.
