### ISSUE TITLE
[Search Selection Dropdown] Ability to search the entire string

### ISSUE THREAD

**Issue by mzygmunt** [Semantic-Org/Semantic-UI#2844]
I think that the ability to search the entire string would be useful. For example, in a situation where we have to find the time zone in the list:
"Europe/London
Europe/Paris
Europ /Zagreb
..."
Currently, the search starts from the beginning of the string and this is sometimes inconvenient.

**Comment by xaeroseven** [comment]
this would be a great addition as I've come across this as well

**Comment by jlukic** [comment]
This is already a dropdown setting `fullTextSearch: true`
