### ISSUE TITLE
Create alternate no radius support

### ISSUE THREAD

**Issue by dietrichg** [Semantic-Org/Semantic-UI#2845]
I often find myself having to override input fields, buttons, and otherwise circular elements pretty often since the application im designing is more squared design than curved. Would it be possible to add support for no-radius to the body to remove all border-radii? or individual element support?

For example:

< body class='squared' >
< a href='#' class='ui button squared'>link</ a >

I know i could make a theme, but I thought others would have this issue too.

**Comment by jlukic** [comment]
It's a global variable, adjusting this will modify all components to use a different border radius

```javascript
/*-------------------
    Border Radius
--------------------*/

/* See Power-user section below
   for explanation of @px variables
*/
@relativeBorderRadius: @relative4px;
@absoluteBorderRadius: @4px;

@defaultBorderRadius: @absoluteBorderRadius;
````

**Comment by dietrichg** [comment]
Well how about individual element support? I don't think the issue can be solved with a simple global fix .

**Comment by jlukic** [comment]
Please read up on theming, all variables are done on a per component or global level.

Add to `src/site/elements/segment.variables`
```
`@borderRadius 0px;` 
```

**Comment by dietrichg** [comment]
Seems quite messy. And and the more semantic way of doing it would default to non border radius, then add "circular", or "rounded" classes as you do similarly for images.

**Comment by jlukic** [comment]
Changing a variable to modify a setting is not messy. Please at least take the time to learn how this library works.

**Comment by dietrichg** [comment]
I understand precisely how it works, its not that complicated. I was simply saying the default should be the browser standard and to offer core support for this issue.

**Comment by dietrichg** [comment]
Its not about whether or not its plausible to change it globally, but if it should even be defined globally in the first place. Personally I think the better approach would be default expected behavior, and then classes to change that, hence semanticism.

**Comment by jlukic** [comment]
I understand where you're coming from, I'm sorry about any short-tempered'ness

**Comment by dietrichg** [comment]
Okay : ) . This field is often stressing, I understand.
