### ISSUE TITLE
Bold Font Weight Variable

### ISSUE THREAD

**Issue by aleesley** [Semantic-Org/Semantic-UI#2846]
Having a bold font weight site variable would be really useful for custom theme fonts with multiple weights. 

Example:
@boldFontWeight: 600;

**Comment by vinayakkulkarni** [comment]
https://github.com/Semantic-Org/Semantic-UI/commit/faf0192241db8cb00874f5e2e13c458e987eb857#diff-09e5b8255f2710bb86860637e7e2c02aR17

Isn't it already implemented?
