### ISSUE TITLE
[Popup] issue with setTimeout and on: manual

### ISSUE THREAD

**Issue by beggiatom** [Semantic-Org/Semantic-UI#2847]
I have a problem with the execution of the following code.

```javascript
    var timeoutTT = null;
    var popupDelay = 400;

// semantic-ui popup
    $('.tt').popup({
        on: 'manual',
        exclusive: true
    });

// Hover .tt
    $('body').on('mouseover', '.tt', function(e) {
        var that = $(this);
        timeoutTT = setTimeout(function() {
            that.popup('show');
        }, popupDelay);
    }).on('mouseout', function() {
        clearTimeout(timeoutTT);
    });
```

When you pass the mouse over the class .tt all right, waiting for 400 milliseconds and the popup is displayed.
The problem is that no longer disappears, unless you move the page or to open another popup.
is my problem or semantic?

jsfiddle http://jsfiddle.net/jw7hjmyv/

Semantic version 2.0.8

**Comment by jlukic** [comment]
There's a delay setting to do this automatically. 
http://jsfiddle.net/Lmotogpm/

**Comment by beggiatom** [comment]
My fault, I had read but I do not know why, I have not practiced hehehe.
