### ISSUE TITLE
Modals are broken in IE8 and IE9

### ISSUE THREAD

**Issue by gmol27** [Semantic-Org/Semantic-UI#285]
Getting a javascript error in jQuery's camelCase function (Object doesn't support this property or method) when calling .modal("show") on IE8 and IE9.

Seems fine on other browsers, and on IE10

**Comment by sdwarak** [comment]
I am having the same issue with modals in IE8 and IE 9. Works well with other browsers.
The JQuery version is 1.11.1. 
Semantic UI version: 2.1.14

I get the following error:

Message: 'console' is undefined
Line: 12
Char: 8424
Code: 0
URI: {...}/modal.min.js
