### ISSUE TITLE
[Search] Add setting to prevent close results after select

### ISSUE THREAD

**Issue by mgrulich** [Semantic-Org/Semantic-UI#2852]
I've added quick action buttons into my search results and I want do in some cases quick actions on multiple results. So I need a way to prevent auto close after select.

**Comment by jlukic** [comment]
You can `return false` from `onSelect` to avoid closing search
http://semantic-ui.com/modules/search.html#search

**Comment by mgrulich** [comment]
I've already, tried this solution. But if I'm ready with all of my tasks the results do not close on click on other areas on the page. The result is in this case only closing when I'm focusing the input and click into the page. This is solution is not very comfortable.

**Comment by jlukic** [comment]
You can call `hide results` afterwards. I'm not sure I understand what the expected behavior here is.
