### ISSUE TITLE
[Dropdown] new addition disappears whenever I press spacebar

### ISSUE THREAD

**Issue by dominicwong617** [Semantic-Org/Semantic-UI#2853]
When I have a multiple dropdown with allowAdditions set to true,
whenever I try to add any items with more than one word (such as 'Criminal Law') and there are no existing matches, the dropdown disappears when I am on 'Criminal' and I press the spacebar. The new addition re-appears again when I start typing 'L'. I think it should not disappear.

I notice that this is the behavior in the semantic-ui's website's demo as well. 
(under 'Dropdown' -> 'Tagging and User Additions' -> 'Multiple')

**Comment by jlukic** [comment]
This is a bug

**Comment by jlukic** [comment]
Fixed in 015a6fc70a277c820dbbeb1839654ce56ea1cca4
