### ISSUE TITLE
Is the goal to be able to build the docs from the main Semantic UI repo?

### ISSUE THREAD

**Issue by giantelk** [Semantic-Org/Semantic-UI#2855]
Is the goal to be able to build the docs from the main Semantic UI repo? Or should you only be able to build the docs from: 
https://github.com/Semantic-Org/Semantic-UI-Docs

See below when `gulp build-docs` from root of main Semantic UI rep:
```
npm install
gulp build-docs

users-MacBook-Pro:Semantic-UI carlf$ gulp build-docs
[22:42:29] Using gulpfile ~/Documents/dev/open source/Semantic-UI/gulpfile.js
[22:42:29] Starting 'build-docs'...
Building Metadata
Copying examples
Copying LESS source
Building Semantic for docs
fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, open '/Users/carlf/Documents/dev/open source/docs/out/metadata.json'
    at Error (native)
users-MacBook-Pro:Semantic-UI carlf$ 
```

**Comment by jlukic** [comment]
It's expecting two sibling folders one with each repo's contents, `ui/` and `docs/`

**Comment by morenoh149** [comment]
So to clarify. To build the docs one must clone this repo, then clone `Semantic-UI-Docs` into this repo's `docs/` directory?
