### ISSUE TITLE
[Modal] observeChanges does not work when embedding iframe

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#2856]
When embedding [Disqus](http://disqus.com/) into modal, seems that the `observeChanges` does not observe the non-blocking-loaded Disqus iframe.

A [jsfiddle](http://jsfiddle.net/e2qcu0u6/) is attached.

You can see that only the content header is middle aligned. But the Disqus iframe is overflowed and also not possible to scroll. Currently I work around this with a `setTimeout` to trigger `modal("refresh")`. But the time delay to refresh is just too hard and too ugly to determine.

Any advice on this? Thanks a lot!

**Comment by jlukic** [comment]
Mutation observers are generally a 'quick fix' solution. Third party APIs like Disqus typically provide their own set of callbacks. It appears Disqus includes an `afterRender` callback which you can run `refresh`.

This might be a good place to start looking for an answer
http://stackoverflow.com/questions/20714907/javascript-not-completely-accounting-for-the-height-of-an-element

**Comment by kfei** [comment]
Thanks for your kind and quick reply.

I've already tried `afterRender` and `onReady` callbacks provided by Disqus. `onReady` is almost the solution but it still a footstep to **ready** since the Disqus' *discoverbox* is rendered after it.

I believe that registering mutation observers on DOM elements inside the iframe can do the job. But currently I just disable the *discoverbox* in Disqus setting since it's actually not needed.

Just another thinking on this, is it possible to force a modal be **scrolling**? So that even the modal is overflowed and did not get observed, we can still scroll on it. (though the center positioning might be wrong)

**Comment by jlukic** [comment]
Sorry, but there isn't currently a way to force `scrolling` behavior. It's amazing how 3rd party libs like Disqus that are massively popular can still exist without these kinds of necessary callbacks.

**Comment by kfei** [comment]
Totally agree with you. :smile: 

I'll report back to this thread someday if there is any update from Disqus.
