### ISSUE TITLE
http://semantic-ui.com/collections/usage/theming.html 404 error

### ISSUE THREAD

**Issue by kurdd** [Semantic-Org/Semantic-UI#2859]
On a page http://semantic-ui.com/collections/usage/theming.html we have 404.

Link from http://semantic-ui.com/collections/grid.html#grids via link "theming variables"

**Comment by jlukic** [comment]
Fixed in `next`
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/693ba65f3721740ffec9d3f3deab896b560790e1
