### ISSUE TITLE
Dimmers are not animated when the class `active` is added dynamically

### ISSUE THREAD

**Issue by fixpunkt** [Semantic-Org/Semantic-UI#2861]
Hi there,

I'm using Semantic UI with React. I have a section that I want to dim. Using react means I don't want to call `$(element).dimmer('show')` on the section. Instead, I add the "active" class to the dimmer. However, this means that the dimmer suddenly appears instead of being animated.

Here is a Plunker that demonstrates the issue:

http://plnkr.co/edit/sCcLGArazoebprmZSD8n

I've tried fiddling with extra `transition`-attributes, but couldn't figure out how to make it work. Any ideas on how to fix this?

Cheers,

Jannik

**Comment by jlukic** [comment]
See [simple dimmer](http://semantic-ui.com/modules/dimmer.html#simple-dimmer)
