### ISSUE TITLE
[Menu] Support for sub menus in vertical text menus

### ISSUE THREAD

**Issue by xeophin** [Semantic-Org/Semantic-UI#2862]
Would be nice to have – the current implementation has inconsistent padding and margins with the combination of an active item in a sub menu in a vertical text menu. As an example, see [here] (http://xeophin.net/de/node/3180#block-menu-block-2) (in the footer, menu "Games").

[JSFiddle](https://jsfiddle.net/g5v1kasd/)

**Comment by jlukic** [comment]
Fiddle appears broken but I understand the issue

**Comment by jlukic** [comment]
Fixed in `2.1`
