### ISSUE TITLE
Optional Form validation

### ISSUE THREAD

**Issue by insaneSytex** [Semantic-Org/Semantic-UI#2864]
Hi there,

is it possible to implement an optional form validation?
It should not validate if the input field is empty but should validate if the user inserts any input.

That would be awesome if it is possible.

Example:
"Please insert any numbers:"

If the user inserts a letters or something else then there is a "blur"-message with the error message.

**Comment by jlukic** [comment]
This already exists, the setting is called `optional` check the docs.

**Comment by rodoneill** [comment]
I was looking for this as well, doesn't seem to be documented, unless I missed it too.
