### ISSUE TITLE
Semantic UI problem when adding a table within a grid

### ISSUE THREAD

**Issue by rufusthecat** [Semantic-Org/Semantic-UI#2867]
When we add a table within a grid it forces the next column to flow underneath and then you can't control your display for different devices sizes. Does anyone knows how to fix this

<div class="ui grid">
        <div class="sixteen wide mobile eight wide tablet four wide computer column">
            <p>1 row mobile - 2 tablet - 4 computer</p>
            <table>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                </tr>
            </table>
        </div>
        <div class="sixteen wide mobile eight wide tablet four wide computer column">
            <p>1 row mobile - 2 tablet - 4 computer</p>
            <table>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                </tr>
            </table>
        </div>
        <div class="sixteen wide mobile eight wide tablet four wide computer column">
            <p>1 - row mobile - 2 tablet - 4 computer</p>
        </div>
        <div class="sixteen wide mobile eight wide tablet four wide computer column">
            <p>1 - row mobile - 2 tablet - 4 computer</p>
        </div>
    </div>

Try removing the second table and you will see that it will replace itself properly
When you run the debug in chrome you see that it changes the class where the table is contained to 
sixteen wide mobile eight tablet four computer column

**Comment by jlukic** [comment]
Set `table-layout: fixed`, there's no way on a framework level to prevent tables from auto-expanding beyond `100% width`

**Comment by rufusthecat** [comment]
Do you have a timeframe for version 2.2.x as I have many places where I have a table withiin a grid (building an elearning content creation tool) and requires lots of advanced layout and need to provide a tablet and smartphone version

**Comment by jlukic** [comment]
This has to do with how `table` work in the browser and is not inherent to SUI. This will happen with any grid system.

**Comment by rufusthecat** [comment]
Have you looked at what I wrote above. The issue is with the SEMANTIC markup being changed when there is a table inside. If I am in the console and rewrite what was changed then it flows perfectly.

sixteen wide mobile eight wide tablet four wide computer column  -  IN THE CODE
sixteen wide mobile eight tablet four computer column  - IN THE RENDERED CODE

**Comment by jlukic** [comment]
There's a contributing guide to explain how to submit a bug report. This is not a suggestion but a mandate for your bug request to be evaluated correctly. You need to include a test case (fork the jsfiddle in readme) and accurately outline the steps to reproduce. 

Your code sample didnt appear correctly because you didnt include the  [markdown for code](https://help.github.com/articles/github-flavored-markdown/). Now that I've inferred what you intended, and created my own test case I can't reproduce the issue
http://jsfiddle.net/f3rauaqa/

**Comment by rufusthecat** [comment]
Fair enough
I created a meteorpad project for you to look at to properly view the issue

http://meteorpad.com/pad/opEoAS5vrPJ5Dxc2e/Semantic%20Grid%20and%20Table - automatic!
[meteorpad](http://meteorpad.com/pad/opEoAS5vrPJ5Dxc2e/Semantic%20Grid%20and%20Table)

**Comment by rufusthecat** [comment]
Just found out from Meteor that it is an issue with Blaze that will remove redundant class names when compiling to javascript. Will leave additional notes in Meteor / Semantic for other people who might have the same issue

**Comment by jlukic** [comment]
Check #1526
