### ISSUE TITLE
[Grid] Toggle Animation 

### ISSUE THREAD

**Issue by ChickenCoding** [Semantic-Org/Semantic-UI#2868]
Firefox 39.0.3, Linux

When i go to the [grid page](http://semantic-ui.com/collections/grid.html)
And I click on "show source code" button 
And I click on  "toggle animation" button
Then the animation does not work

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/0f1e78cb1b8ee314d08b685b2006154413338e1c
