### ISSUE TITLE
fluid input not work on safari

### ISSUE THREAD

**Issue by danyongliu** [Semantic-Org/Semantic-UI#2870]
Met two issues in safari:
1. fluid input not display well, see the snapshot below:
![safari](https://cloud.githubusercontent.com/assets/8786653/9328413/07bb0652-45db-11e5-9e03-ea73a4840cab.jpg)

2. the cards display in safari can't be stacked:
   for example: <div class="ui one cards">

**Comment by jlukic** [comment]
What version of Safari / Platform?

Please create an exact test case by forking the JSFiddle in the readme for each issue.

**Comment by avalanche1** [comment]
Closing until there's a test case.
