### ISSUE TITLE
[Input] Labeled Should Support Attached on Both Sides 

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#2871]
One thing I'm trying to do which seems to not be possible with SUI, is to add both a left and right attached label to an input. Currently only left, or right is possible unless I'm missing something. See here:

http://jsfiddle.net/nz8smghx/1/

I've tried playing around with various classes but it all ends up much the same. One label is fine, the other label is facing the wrong way. I completely understand why it's happening, just would be useful to have the option of adding both

**Comment by jlukic** [comment]
Under what circumstances would you need to markup an input on both sides?

**Comment by pareeohnos** [comment]
I'm trying to implement a form the kind of reads like a sentence in the way it is filled out, and want to use labels/dropdowns on both sides. For example

    [input][days after/days before]     [the tasks][input][start/end]     

Here the second input has the label attached to the left simply describing that the input is a selection of tasks, and the right of it contains a dropdown to specify the start, or the end of those tasks. It's quite hard to explain but hopefully this makes a little bit of sense?

**Comment by jlukic** [comment]
That makes sense, let me look into it.

**Comment by maturano** [comment]
@pareeohnos 
> the second input has the label attached to the left simply describing that the input is a selection of tasks, and the right of it contains a dropdown to specify the start, or the end of those tasks

As you explain, the "right label" it is in reality [an action](http://semantic-ui.com/elements/input.html#action). So, if I didn't misunderstood, we can do the following to get what you describe:

```html
<div class="ui right action labeled input">
    <div class="ui label">The label</div>

    <input type="text" placeholder="The input">

    <div class="ui dropdown button">
      <div class="text">The action</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <div class="item">Start</div>
        <div class="item">End</div>
      </div>
    </div>
  </div>
```

Live example: https://jsbin.com/soxeze/5/edit?html,output

**Comment by pareeohnos** [comment]
@maturano yeah that's right. Sure I tried that but that's spot on. What about the other way round, where the left side is a dropdown and the right side is the label?

**Comment by maturano** [comment]
Well ...`left action right labeled`: https://jsbin.com/sonuhulapo/1/edit?html,output

**Comment by pareeohnos** [comment]
what the hell! I swear I tried these :( well guess that sorts my issue out then. Thanks :)

**Comment by maturano** [comment]
Glad to help :smile: 

---
@jlukic Besides of that case (*label/input/action*), and as far I understand, for this issue it **have to** implement a `both sides` class to the input (as non English speaker, I don't know if there is "one word" to describe that)
```html
<div class="ui both sides labeled input">
  <div class="ui label"> Left </div>
  <input type="text" placeholder="the input">
  <div class="ui label"> Right </div>
</div>
```

Because I was thinking in the possibility of move the "position" class to the label:
```html
<div class="ui labeled input">
  <div class="ui left label"> Left </div>
  <input type="text" placeholder="the input">
  <div class="ui right label"> Right </div>
</div>
```

**Comment by maturano** [comment]
While I wait for comments, how do you do for highlight the classes in the examples of docs?

![2015-08-26-095920_403x247_scrot](https://cloud.githubusercontent.com/assets/5768813/9497176/656800c6-4bd9-11e5-81c2-47d6edf45d00.png)

**Comment by jlukic** [comment]
It highlights either any classes matching the title of the example, or the `data-class` (comma separated list) value on `<div class="example">`, put two word variations before one word ones in the class list, or it won't match.

**Comment by jlukic** [comment]
Position classes should be on `input` since there is no previous sibling selector in CSS. There's no way to say "the input before the label with class right". 

There's probably a better name than `both sides attached` I'll think about it.

**Comment by jlukic** [comment]
Added with PR tagged above
