### ISSUE TITLE
Modal close icon appears outside of modal bounds for widescreen monitor width 

### ISSUE THREAD

**Issue by mnquintana** [Semantic-Org/Semantic-UI#2873]
For widths greater than a certain breakpoint (it looks like `widescreenMonitorWidth` but I'm not totally sure), the close icon in a modal pops out of its containing modal. It looks fine at smaller widths, though.

![edit_fiddle_-_jsfiddle](https://cloud.githubusercontent.com/assets/823545/9338316/20e99a22-45b2-11e5-8870-f1856767395b.png)

Here's a test case: https://jsfiddle.net/wisew/etya3t25/1/

**Comment by jlukic** [comment]
This is intentional

**Comment by mnquintana** [comment]
@jlukic Thanks for the update! That makes sense, but I'm not sure if it looks intentional (it fits with the `basic` style modal, but it doesn't seem consistent with the placement of the icon at other viewport widths). Also, this isn't consistent with `fullscreen` modals - though it'd be more difficult, it would still be possible for header text to overlap with the close icon, but it's still displayed inside the modal.

**Comment by kmd1970** [comment]
With 2.2.6 and IE 11 if the browser window is made smaller than the actual modal, the close icon disappears. Firefox seems ok.  Also, I wish we had a (class) option to keep the X inside the modal header at all times for any modal type.

Example of the close icon issue:
[Imgur](http://i.imgur.com/dR56NyS.jpg)

**Comment by josemartindev** [comment]
I found an easy (bit ugly) solution. It works like a charm.

Before: 
![mauvaistruc](https://user-images.githubusercontent.com/43208594/51903830-6ca42a80-23bd-11e9-8b65-63dc2c1c10e4.png)

```
i.close.icon::before {
    cursor: pointer;
    position: absolute;
    font-size: 25px;
    color: red;
    left: -30px;
    top: 45px;
}
```
After: 
![bontruc](https://user-images.githubusercontent.com/43208594/51903869-86457200-23bd-11e9-87e4-ef5c65e561a9.png)

**Comment by Alfriend-xing** [comment]
<i class="orange close icon" style="position: absolute; top: 1rem; right: 1rem;"></i>

**Comment by josemartindev** [comment]
I prefer to leave my components with no inline style but if it works then that's great!

**Comment by ethernidee** [comment]
When multiple/nested modals are used, they overlap over each other and close icon from one modal is placed near close icon of the other modal, so it's a total mess. Moreover, close icon of parent modal can be clicked by mistake.

**Comment by lubber-de** [comment]
We prepared this in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1215
If you add `inside` to the `close icon` , it behaves the desired way
See example here https://jsfiddle.net/m59p0wq1/
