### ISSUE TITLE
try/catch in tasks/config/project/release.js covers too many cases.

### ISSUE THREAD

**Issue by Parakleta** [Semantic-Org/Semantic-UI#2875]
The try/catch block in [tasks/config/project/release.js](https://github.com/Semantic-Org/Semantic-UI/blob/3d002c72a0c778a63a414c847ad48d835df0a8cc/tasks/config/project/release.js#L17-L30) will bail to catch if either `semantic.json` or `package.json` is missing, whereas it should only do this if both are missing.

The changes introduced to this file in 57b35d2 need to be moved after the try/catch into a separate try/catch block.  Note also that this commit stores the version in the variable `version` whereas the value exported is `package.version`.

**Comment by jlukic** [comment]
Yeah this looks wrong. I'll check it out.
