### ISSUE TITLE
[Menu] - Fixed Bottom not visible in Safari

### ISSUE THREAD

**Issue by Belisar777** [Semantic-Org/Semantic-UI#2877]
This problem is  in Safari (8.0.7 ) in Mac or iPad.

**Steps to Reproduce**
1. I have two fixed menus (bottom and top) 
    bottom has classes: ui blue inverted three item bottom fixed menu
    top has classes: ui blue inverted three item top fixed menu

**Expected**
The Menus are visible

**Result**
The bottom Menu is hidden and top menu is ok.

**Comment by Belisar777** [comment]
My bottom menu is in default display: none. I set display: flex. In FF, Chrome, IE is ok. In Safari must be set -webkit-flex. Mea culpa.:-)

**Comment by jlukic** [comment]
Glad you found your issue
