### ISSUE TITLE
Dropdown Doesn't Support Remote Category Search

### ISSUE THREAD

**Issue by martindale** [Semantic-Org/Semantic-UI#2879]
When using a Dropdown with remote data, it doesn't seem possible to use a `type: category` in the remote search.  Instead, the listing is flat!

**Comment by jlukic** [comment]
Type `category` is a feature of search, not dropdown.

**Comment by martindale** [comment]
Hrm.  It seems dropdown has search-like capability, including similar `apiSettings`, so I expected the behavior to be similar.  How might one provide a multi-selection searchbox then, as it doesn't seem that Search supports this: http://semantic-ui.com/modules/dropdown.html#multiple-search-selection
