### ISSUE TITLE
Something wrong with Andriod System

### ISSUE THREAD

**Issue by blackxea** [Semantic-Org/Semantic-UI#2881]
there is something wrong with andriod system,such as class .cards, always inline on andriod browser

**Comment by jlukic** [comment]
Can you provide a specific test case, device/ android version?

**Comment by blackxea** [comment]
Samsung S5(SM-G9006V), andriod version5.0

**Comment by jlukic** [comment]
I'm not sure what to do as Samsung S4 appears fine using Chrome Emulation Tools. 

Will keep open if anyone has any specific ideas for a fix, or test case.

**Comment by arggh** [comment]
I just had a nasty bug where our onboarding process was using transitions, like this:

```
...
this.container.transition('fly right', {
      onComplete: () => {
          go('onboardingSuccess');
      }
});
```

on Samsung S5, the call for `go()` would never take place.

**Comment by Banandrew** [comment]
@arggh could it be that S5’s browser didn’t support the new-ish `() => {}` syntax?

**Comment by vinayakkulkarni** [comment]
can't you just use?

```javascript
 onComplete: function()  {
          go('onboardingSuccess');
      }
```
Closing this.

**Comment by ilarip** [comment]
In my case the code was of course being transpiled, so it wasn't about the syntax. The callback just wasn't called on a few devices -  actually nothing would happen.
