### ISSUE TITLE
[Examples] Add Sticky Footer Example

### ISSUE THREAD

**Issue by jonywtf** [Semantic-Org/Semantic-UI#2882]
Hi! How can i make sticky footer like 
http://getbootstrap.com/examples/sticky-footer/

"ui bound bottom sticky" is bad...
![bad_footer](https://cloud.githubusercontent.com/assets/7776600/9380581/d2760d74-4739-11e5-96da-89e12325db9e.png)

I can't find good example like bootstrap sticky footer
Thanks!

**Comment by jlukic** [comment]
This is the best way to do a sticky footer.
https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by ttasovac** [comment]
is there a fully working semantic-ui example for this somewhere?

**Comment by Dreyer** [comment]
@ttasovac I've been testing the flexbox layout mode as suggested above. Seems to come down to where you apply it. I've managed to get it working on one of the example layouts by doing the following:

```css
.pusher {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

.pusher > .footer {
  flex: 1;
}
```

I've modified the standard ['Homepage'](http://semantic-ui.com/examples/homepage.html) layout to shorten the content on the page:
https://jsbin.com/doyubanoge/edit?html,css,js,output

**Comment by ttasovac** [comment]
thanks a lot @Dreyer! looks great.

**Comment by jlukic** [comment]
@Dreyer It's perfectly fine to use any arbitrary flex containers around SUI elements.

**Comment by cyberwombat** [comment]
@Dreyer - that JSBin example is not working for me. The footer just stretches upward if I make my screen high enough.

**Comment by piya23300** [comment]
I have a problem the same @cyberwombat

**Comment by Dreyer** [comment]
@cyberwombat + @piya23300 - I had another quick look at the JSBin example. It's still working for me in Chrome and Firefox. Which browser and version are you using?

**Comment by cyberwombat** [comment]
@Dreyer - chrome and safari latest. Do this: Remove jsbin's top gray thingy, make your browser full screen and remove the h3 and P content. You should see the footer become taller.

**Comment by Dreyer** [comment]
@cyberwombat I think I see what you mean. For my purposes it wasn't really a problem but I've had a go at fixing it. How does this work for you? I had to move the footer outside of the `.pusher` and add `#content` so that only the main content area flexes.
https://output.jsbin.com/culavuxugi

Edit:
https://jsbin.com/culavuxugi/edit?html,css,js,output

**Comment by cyberwombat** [comment]
@Dreyer works for me!

**Comment by piya23300** [comment]
@Dreyer Thank you. it works for me.

**Comment by catimos** [comment]
@Dreyer Yes it works Thankyou!

**Comment by beauraF** [comment]
Hi ppl,

I implemented the last example of @Dreyer  but I get this result :
![capture d ecran de 2016-12-07 23-38-55](https://cloud.githubusercontent.com/assets/12185788/20997738/63ae4186-bcd6-11e6-84dc-0b93ff94cd65.png)

Has anyone ever encountered the problem ?

**Comment by yshterev** [comment]
@Dreyer Not bad but broken on IE 11

**Comment by jonaschn** [comment]
I followed the way @jlukic suggested.
@Dreyer Do you know why it is not working without a segment around the container
(around the grid)?
You can find an example [here](https://plnkr.co/edit/22vQxxmV8jTAD2BlUV4n?p=preview).

**Comment by mikecann** [comment]
If you are using React with Semantic UI, you can do something like this:

```
<div style={{ display:"flex", minHeight:"100vh", flexDirection:"column" }}>
  <PageHeaderMenu />
  <div style={{ flex:1 }}>
    <PageContent />
  </div>
  <PageFooter />
</div>
```

Im thinking it should be pretty easy to turn this into a React component for those wishing to.

**Comment by dionkas** [comment]
@mikecann's suggestion is great! Make sure if you use the Menu component to not add the "fixed" prop
