### ISSUE TITLE
Full height of some row

### ISSUE THREAD

**Issue by vomchik** [Semantic-Org/Semantic-UI#2883]
How can do this?

https://monosnap.com/file/kAugaWbteFgRuOkTuHdlVFYe8g7YUk

http://the-echoplex.net/flexyboxes/?fixed-height=on&display=flex&flex-direction=column&flex-wrap=nowrap&justify-content=flex-start&align-items=flex-start&align-content=stretch&order%5B%5D=0&flex-grow%5B%5D=1&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=stretch&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=stretch

**Comment by jlukic** [comment]
If you are trying to make a 100% page height layout you'll need to add your own flexbox wrapper.

Grids are `flex` themselves and will stretch correctly if you use them as children of a flex container.
