### ISSUE TITLE
Different results at onChange parameters when selecting an option at dropdown and when deselecting one

### ISSUE THREAD

**Issue by zisiszikos** [Semantic-Org/Semantic-UI#2888]
Parameters **value, text, $choice** of **onChange** event at multiple selection dropdown produces different values when selecting an item, and when deselecting it.

See the fiddle:
[http://jsfiddle.net/12xwxbzy/3/](http://jsfiddle.net/12xwxbzy/3/)

**Comment by jlukic** [comment]
I'm not understanding. It produces a different value because when you remove the value it is no longer selected?

**Comment by Zosimas** [comment]
If you see the console the result is very wierd. For example when I select an option I get this response:
```
value: ["AL"]
text: AL
choice: Alabama
```
and when I deselect it I get this:
```
value: []
text: Alabama
choice: [div.item.active, context: div.item.active]
```
**value** seems to be ok but the other two (text and choice) have weird results.

**Comment by sebradloff** [comment]
I had a similar problem on the multi select search dropdown for the onChange method. I solved it by using the onAdd and onRemove methods to customize behavior for both. The onAdd method takes (addedValue, addedText, selection) while the onRemove method takes (removedValue, removedText, selection).
