### ISSUE TITLE
Inverted Dimmer Not Working

### ISSUE THREAD

**Issue by aleesley** [Semantic-Org/Semantic-UI#2890]
The inverted dimmer does not appear to be working with a modal.

**Comment by jlukic** [comment]
http://jsfiddle.net/2p60q0ns/

**Comment by aleesley** [comment]
```
$(modalId).modal({
            inverted: true,
            onShow: function () {
                $(this).find('.ui.form').semForm();
                $('body').on('wheel.modal mousewheel.modal', function () { return false; });
            },
            onHide: function () {
                $('body').off('wheel.modal mousewheel.modal');
            }
   });
```

that is my code ... the inverted class isn't getting applied.

**Comment by aleesley** [comment]
The settings.inverted option is set to true when i debug.

**Comment by aleesley** [comment]
The last example is on this Semantic-UI page is supposed to be inverted and it does not work. 

http://semantic-ui.com/modules/dimmer.html#/examples

**Comment by aleesley** [comment]
The inverted dimmer is also not working on this Semantic UI page .. http://semantic-ui.com/modules/modal.html#dimmer-variations

**Comment by jholl** [comment]
See the comment on #2915; I think these issues are related; let's try and carry the conversation in one place, over there.
