### ISSUE TITLE
Semantic UI 2.0.8 Docs BUG

### ISSUE THREAD

**Issue by kazilotus** [Semantic-Org/Semantic-UI#2891]
http://semantic-ui.com/elements/icon.html
On the above page, When I click on the show code button on the first section (Web Content), the text that appears below it isn't properly formatted. There isn't any break after each line. I tried testing it on both chrome and firefox. Hope the issue is fixed soon.

**Comment by jlukic** [comment]
Thanks this is a bug

**Comment by jlukic** [comment]
Fixed. Issue with `code icon` (which is part of code sample) having special meaning in docs.
