### ISSUE TITLE
[Item] - Vertical Alignment - Bottom is not working

### ISSUE THREAD

**Issue by catalin07** [Semantic-Org/Semantic-UI#2894]
The bottom aligment for item is not working because is wrong used align-self in css

    .ui.items>.item>.image+[class*="bottom aligned"].content {
    -webkit-align-self: BOTTOM;
    -ms-flex-item-align: BOTTOM;
    align-self: BOTTOM;
}

The syntax for align-self permmits only:
align-self: auto
align-self: flex-start
align-self: flex-end
align-self: center
align-self: baseline
align-self: stretch
align-self: inherit 

Here is the link to exemple:
http://semantic-ui.com/views/item.html#vertical-alignment

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI/commit/203709bba970df759eac6c72ae6fb0277820c6b2 for `2.1` dupe #2826
