### ISSUE TITLE
Modals are moved to bottom from their container

### ISSUE THREAD

**Issue by nadimtuhin** [Semantic-Org/Semantic-UI#2897]
I feel its a bad practice to move the modals from their container. I am having problem with it in my react application.

**Comment by jlukic** [comment]
You can disable this behavior by using `detachable: false` setting. 

See explanation of purpose here:
http://semantic-ui.com/modules/modal.html#usage

**Comment by nadimtuhin** [comment]
thanks :D

**Comment by gianmarcotoso** [comment]
I'd like to point out, since it took me a while to find this out, that this appears to be required when using modals in React. At least this solved the Invariant Violation problem for me, since the DOM was being manipulated by something other than React.
