### ISSUE TITLE
[Form] Add Submit Behavior that Doesn't Trigger Validation / Add Docs Example of AJAX Submit

### ISSUE THREAD

**Issue by joshbodine21** [Semantic-Org/Semantic-UI#2900]
The following code creates an endless loop. I have a situation where, upon clicking the submit button I need to make an ajax call to update some data in one system, and only then submit the form to another system if the ajax call succeeds. I have been able to do this with other validation plugins, but it seems that the 'submit' behavior and 'validate form' behavior always calls onSuccess. Why is the 'validate form' behavior not de-coupled from submitting the form. Should I not be able to manually validate the form and then, if valid, call the submit behavior myself. If I call 'validate form' it submits it whether I wanted to or not. Is there a way to do this?

```
$myForm.form({
       "inline":true,
    "on":"submit",
    "onSuccess":function(e){
        e.preventDefault();
        $.when(myAJAXcall)
                .then(
                     function(data){
                          // ajax successful
              $myForm.form('submit');
             }, 
             function(data, textStatus, jqXHR){
                // my ajax error
             }
                );
    }
})
```

**Comment by jlukic** [comment]
I can see how this would be confusing with AJAX. 

Form validation has coupling with the API component, so that you can do AJAX submits. There isn't currently an example of this in the docs though. Something like..

```javascript
$myForm
  .api({
     url: myAJAXcall
  })
  // this will auto e.preventDefault, and call api endpoint on submit with form data
  .form({
       "inline":true,
      "on":"submit"
  })
;
```

Submit is expected to retrigger validation, to submit currently after AJAX use

**Comment by Errvald** [comment]
@jlukic Your example submits the form twice via ajax, with the first call cancelled and the form still invalid.
