### ISSUE TITLE
[Items] Add Unstackable Items Variation

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#2901]

**Comment by rlech** [comment]
+1 when is 2.2 coming? need unstackable items also ;) is there a workaround until 2.2 is released?

**Comment by zhe** [comment]
Hopefully it would support to switch the 'responsive' off in the future.

**Comment by rcrusoe** [comment]
Just ran into this issue, as well as unstackable tables (found another thread with that fix). Has unstackable items been released yet?

**Comment by elliottshort** [comment]
Hopefully this gets released soon - I could really use it as well.

**Comment by stevenspiel** [comment]
+1

**Comment by jlukic** [comment]
Added in `next`
