### ISSUE TITLE
Circular / bordered + size not works

### ISSUE THREAD

**Issue by tunnckoCore** [Semantic-Org/Semantic-UI#2903]
This not works if you are using this module as single.

```html
<link rel="stylesheet" href="https://cdn.rawgit.com/Semantic-Org/UI-Icon/master/icon.min.css">
<i class="circular users huge icon"></i>
<i class="bordered users huge icon"></i>
```

http://jsbin.com/vuboxa/1/edit?html,output

**Comment by tunnckoCore** [comment]
oops wrong place.

**Comment by jlukic** [comment]
This is the correct place for the issue. Most likely all components need a basic css reset.

**Comment by tunnckoCore** [comment]
@jlukic i include `latest normalize.css` and it not works. So SUI problem and UI-Reset.
