### ISSUE TITLE
Small glitch in Chrome on fieldsets with ribbon labels

### ISSUE THREAD

**Issue by gonssal** [Semantic-Org/Semantic-UI#2909]
There's a small glitch with the border in fieldsets with ribbon labels in Chrome. Image attached showing it. I'm using latest version (2.0.8). It didn't happen in version 1.x and doesn't happen in Firefox.

![semantic-fieldset-with-label-border](https://cloud.githubusercontent.com/assets/1172272/9484065/baa94a9a-4ba7-11e5-97f7-5bb922f417f5.png)

Note that there's a gap between the label and the start of the border.

**Comment by avalanche1** [comment]
Closing until there's a test case.
