### ISSUE TITLE
Colored tables color is hidden when they have top attached segments

### ISSUE THREAD

**Issue by gonssal** [Semantic-Org/Semantic-UI#2910]
When a colored attached table has a top attached segment, the color isn't shown. This didn't happen in version 1.x. Attached images from before (1.x) and after (2.x).

![semantic-colored-attached-table-1 x](https://cloud.githubusercontent.com/assets/1172272/9484631/0a0605cc-4baf-11e5-8652-b70567d90dbc.png)

![semantic-colored-attached-table-2 x](https://cloud.githubusercontent.com/assets/1172272/9484636/0e82dcba-4baf-11e5-8575-3a87581ac227.png)

**Comment by jlukic** [comment]
Please include a test case to reproduce the issue, there's a jsfiddle to fork in the readme.

**Comment by gonssal** [comment]
http://jsfiddle.net/7Lff0x2k/

**Comment by gonssal** [comment]
This still happens, as can be seen in the provided jsfiddle. 

If it's intended behavior, although it's a clear regression as can also be seen in the provided screenshots, then close it.
