### ISSUE TITLE
[React] Issue with Text Nodes Wrapped with <span>

### ISSUE THREAD

**Issue by hallister** [Semantic-Org/Semantic-UI#2918]
I'm currently working on a complete React implementation of Semantic UI and noticed an oddity: http://jsfiddle.net/mujjtumb/

As a technical limitation React adds `<span>` tags around free floating text so it can assign an internal id. As a result all free-floating header text will come out one of two ways:

```HTML
<h4 class="ui horizontal divider header">
    <i class="tag icon"></i>
    <span>Description</span>
</h4>
```

```HTML
<h4 class="ui horizontal divider header">
    <i class="tag icon"></i>
    <div class="content">Description</div>
</h4>
```

Technically this is a React issue, but the automated `<span>` tags are a technical limitation and can't be removed. Unfortunately it creates a very weird set of circumstances because sometimes wrapping the free-floating text in `content` divs results in problems, such as:

```HTML
<h4 class="ui center aligned icon header">
    <i class="circular users icon"></i>
    <div class="content">Friends</div>
</h4>
```

In this example, wrapping the Friends text in a `<span>` is the functional equivalent to not wrapping it at all, which is the opposite behavior of the above example.

This may be more time-consuming than it's worth, but it seems like `<div class="content">` should consistently produce "good" outcomes when wrapping header text, but it appears the center alignment is breaking it in the last example.

**Comment by jlukic** [comment]
Generally to avoid issues with nested components, common groupings like `content`, `item`, and `icon` , `column` use descendant selectors. 

This makes sure a `four column` grid inside a `three column grid` for example, receives the appropriate column widths. Or a `dropdown menu item` inside a `menu`.

I'm not sure if this can be reconciled with arbitrary span wrappers.

**Comment by hallister** [comment]
Hmm, maybe this is a bug on Chrome in Linux but I forked your jsfiddle and removed the content tag and it shows off-centered text on the `<div class="content">` text:

http://i.imgur.com/K2Qf8ri.png

The other examples are fine... they are different, but they line up, while this example there is a sizable padding to the left of the text.

**Comment by hallister** [comment]
Just an update to this. Having almost completed the core library in React, aside from the minor bugs listed below, the `statistic` component is completely broken. React will turn the `text value` from:

    10<br/>Label

to:

    <span>10</span><br/><span>Label</span>

Needless to say that completely breaks it. Wrapping a content span doesn't fix the issue in this case.

**Comment by levithomason** [comment]
React now uses inline HTML comments, no longer wrapping with span nodes.  This issue can be closed.
