### ISSUE TITLE
Dropdown module doesn't implement addResult message

### ISSUE THREAD

**Issue by Neaox** [Semantic-Org/Semantic-UI#2923]
I assume that `message.addResult` is used to format the add item message when `allowAdditions` is `true`.

This property is never utilised within the Dropdown module.

See: https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3198

**Comment by jlukic** [comment]
Implemented this, and the UX is much better. Now you can tell difference between user addition and normal selection.
