### ISSUE TITLE
Browser support and flexbox issues

### ISSUE THREAD

**Issue by borissamardzija** [Semantic-Org/Semantic-UI#2924]
Hi,

I am using Semantic UI 2.0 in my new mobile web application so I noticed that grid is broken on older (4.1 & 4.2) Androids and iOS 6 since they don't support new flexbox.

http://caniuse.com/#search=flexbox

Could you update browser requirements in readme to the correct ones?

I think they should be

Browser Support

Last 2 Versions FF, Chrome, IE 10+, Safari 7+, Opera
IE 10+
Android 4.4+, Chrome for Android 44+
iOS Safari 7+

Do you agree on that?

**Comment by jlukic** [comment]
It probably makes sense to make this more explicit.

**Comment by borissamardzija** [comment]
Great, it should be more clearly now for everyone. Thanks!
