### ISSUE TITLE
[Dropdown] Fails if rendered in a dom fragment

### ISSUE THREAD

**Issue by burka** [Semantic-Org/Semantic-UI#2930]
After the upgrade from 1.11.6 to 2.0.8 some of the dropdowns fail if rendered in a dom fragment. 

```
Transition: There is no css animation matching the one you specified. 
Please make sure your css is vendor prefixed, and you have included transition css. scale


var $html = $('<select name="sample[attributes]" multiple="multiple" class="ui dropdown"><option value="brown/red" selected="selected">yellow/red</option><option value="green">green</option></select>');
$html.dropdown();
$container.append($html);
```

If you append it to a hidden element and do the .dropdown() call on that it works as expected (but is slower).
See: https://jsfiddle.net/h1j8gLu4/1/

I switched to hidden rendering due to performance reasons on a page with 200+ dropdowns. Old computers took up to ten seconds just for the dropdowns, hidden rendering halved that time.
(And removed the flickering..) 
On my computer for 281 dropdowns it was 
- 703ms with dom fragment rendering (not working for some values),  
- 1149ms with hidden ('display: none;') rendering and 
- 3327ms with visible rendering.

**Comment by makedonian** [comment]
Any word on this? Can't seem to get around it when using semantic-ui and react.

**Comment by lsunsi** [comment]
@makedonian  Same thing here actually. React + Semantic-UI always worked out fine
