### ISSUE TITLE
[Button] Disabled Pointer-events should overwrite loading

### ISSUE THREAD

**Issue by peterfyj** [Semantic-Org/Semantic-UI#2933]
Default behavior of `.loading` button has been discussed in #1744 as being disabled. But in 2.0.8, `.loading` button has `pointer-events: auto`, and this cannot be overwritten even with the presence of `.disabled`.

See this [JSFiddle](http://jsfiddle.net/ey1at5fv/1/) for a test case.

**Comment by jlukic** [comment]
This came as a side effect for adding a variable specifically to control whether loading should have `pointer-events: none` (in most cases this will cause issues with `hover` retriggering with an idle mouse on an element which can be a big no-no)

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/button.variables#L125 should probably be `''` not `auto`.

**Comment by kmd1970** [comment]
same issue.
https://jsfiddle.net/kmd1970/55qog60h/

**Comment by jlukic** [comment]
Fixed in next

**Comment by kmd1970** [comment]
When is next release?

**Comment by jlukic** [comment]
t.b.d

**Comment by mciunne** [comment]
i am having this same problem today. is this fixed ? or is there a workaround ? thx.

**Comment by wassimdevox** [comment]
still not fixed?
