### ISSUE TITLE
[Popup] Will Not Remove Inline Popup in Some Conditions

### ISSUE THREAD

**Issue by nicbarker** [Semantic-Org/Semantic-UI#2934]
Apologies if this is explained in the docs somewhere that I didn't find. It seems that if you set the `inline` flag to `true` when initializing a popup, 'remove popup' and 'destroy' don't work anymore. See this fiddle:

[https://jsfiddle.net/ovck2v9d/1/](https://jsfiddle.net/ovck2v9d/1/)

**Comment by Banandrew** [comment]
Another test case from #5239:

>destroy, remove popup behaviors and preserve : false parameters have no effect on an inline : true popup. Popup contents remain on page.
>
>See here:
>https://jsfiddle.net/kmd1970/z2a25xj5/

**Comment by abolfazl-ziaratban** [comment]
yes this is a bug.
but you can use this way

```
$('#my-popup').popup('get popup').remove();
$('#my-popup').popup('destroy');
```
