### ISSUE TITLE
fail to "npm install semantic-ui --save"

### ISSUE THREAD

**Issue by ZetaChow** [Semantic-Org/Semantic-UI#2936]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "semantic-ui" "--save"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3

npm ERR! shasum check failed for /tmp/npm-1676-009611c7/registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
npm ERR! Expected: 93d9baa6550a4ca97193dd5433c76839fc3bd62e
npm ERR! Actual:   d7a2c5530bd6f5333eedcd154ad04278a622b5bc
npm ERR! From:     https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zeta/workspace/npm-debug.log

###npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'semantic-ui',
1 verbose cli   '--save' ]
2 info using npm@2.13.3
3 info using node@v3.2.0
4 verbose install initial load of /Users/zeta/workspace/package.json
5 verbose readDependencies loading dependencies from /Users/zeta/workspace/package.json
6 silly cache add args [ 'semantic-ui', null ]
7 verbose cache add spec semantic-ui
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'semantic-ui',
8 silly cache add   scope: null,
8 silly cache add   name: 'semantic-ui',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed semantic-ui@*
10 verbose addNamed "*" is a valid semver range for semantic-ui
11 silly addNameRange { name: 'semantic-ui', range: '*', hasData: false }
12 silly mapToRegistry name semantic-ui
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/semantic-ui
16 verbose addNameRange registry:https://registry.npmjs.org/semantic-ui not in flight; fetching
17 verbose request uri https://registry.npmjs.org/semantic-ui
18 verbose request no auth needed
19 info attempt registry request try #1 at 17:48:21
20 verbose request id 1e8c7ec944e88e15
21 verbose etag "2X71B3IZ0439ZXOPHW9ZO06AE"
22 http request GET https://registry.npmjs.org/semantic-ui
23 http 304 https://registry.npmjs.org/semantic-ui
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 01 Sep 2015 09:48:22 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"2X71B3IZ0439ZXOPHW9ZO06AE"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-nrt6125-NRT',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1441100902.339140,VS0,VE183',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/semantic-ui from cache
26 verbose get saving semantic-ui to /Users/zeta/.npm/registry.npmjs.org/semantic-ui/.cache.json
27 silly addNameRange number 2 { name: 'semantic-ui', range: '*', hasData: true }
28 silly addNameRange versions [ 'semantic-ui',
28 silly addNameRange   [ '0.18.0',
28 silly addNameRange     '0.19.3',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.1.2',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1',
28 silly addNameRange     '1.5.0',
28 silly addNameRange     '1.5.2',
28 silly addNameRange     '1.6.0',
28 silly addNameRange     '1.6.1',
28 silly addNameRange     '1.6.2',
28 silly addNameRange     '1.6.4',
28 silly addNameRange     '1.7.0',
28 silly addNameRange     '1.7.1',
28 silly addNameRange     '1.7.2',
28 silly addNameRange     '1.7.3',
28 silly addNameRange     '1.8.0',
28 silly addNameRange     '1.8.1',
28 silly addNameRange     '1.9.0',
28 silly addNameRange     '1.9.1',
28 silly addNameRange     '1.9.3',
28 silly addNameRange     '1.10.0',
28 silly addNameRange     '1.10.2',
28 silly addNameRange     '1.10.3',
28 silly addNameRange     '1.11.0',
28 silly addNameRange     '1.11.1',
28 silly addNameRange     '1.11.2',
28 silly addNameRange     '1.11.3',
28 silly addNameRange     '1.11.4',
28 silly addNameRange     '1.11.5',
28 silly addNameRange     '1.11.6',
28 silly addNameRange     '1.11.7',
28 silly addNameRange     '1.11.8',
28 silly addNameRange     '1.12.0',
28 silly addNameRange     '1.12.1',
28 silly addNameRange     '1.12.2',
28 silly addNameRange     '1.12.3',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '2.0.2',
28 silly addNameRange     '2.0.3',
28 silly addNameRange     '2.0.4',
28 silly addNameRange     '2.0.5',
28 silly addNameRange     '2.0.6',
28 silly addNameRange     '2.0.7',
28 silly addNameRange     '2.0.8' ] ]
29 silly addNamed semantic-ui@2.0.8
30 verbose addNamed "2.0.8" is a plain semver version for semantic-ui
31 silly mapToRegistry name semantic-ui
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/semantic-ui
35 verbose addRemoteTarball https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz',
36 verbose addRemoteTarball   '93d9baa6550a4ca97193dd5433c76839fc3bd62e' ]
37 info retry fetch attempt 1 at 17:48:22
38 info attempt registry request try #1 at 17:48:22
39 http fetch GET https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
40 http fetch 200 https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
41 silly fetchAndShaCheck shasum 93d9baa6550a4ca97193dd5433c76839fc3bd62e
42 verbose stack Error: shasum check failed for /tmp/npm-1752-f823d87e/registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
42 verbose stack Expected: 93d9baa6550a4ca97193dd5433c76839fc3bd62e
42 verbose stack Actual:   234d2559e5a1e597b7bd411c9bc77090c01fdc21
42 verbose stack From:     https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
42 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
42 verbose stack     at emitNone (events.js:72:20)
42 verbose stack     at ReadStream.emit (events.js:166:7)
42 verbose stack     at endReadableNT (_stream_readable.js:893:12)
42 verbose stack     at doNTCallback2 (node.js:429:9)
42 verbose stack     at process._tickCallback (node.js:343:17)
43 verbose cwd /Users/zeta/workspace
44 error Darwin 14.5.0
45 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "semantic-ui" "--save"
46 error node v3.2.0
47 error npm  v2.13.3
48 error shasum check failed for /tmp/npm-1752-f823d87e/registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
48 error Expected: 93d9baa6550a4ca97193dd5433c76839fc3bd62e
48 error Actual:   234d2559e5a1e597b7bd411c9bc77090c01fdc21
48 error From:     https://registry.npmjs.org/semantic-ui/-/semantic-ui-2.0.8.tgz
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by jlukic** [comment]
See https://github.com/npm/npm/issues/2701
