### ISSUE TITLE
[Dropdown] animation incompatible with jQuery 3.0.0

### ISSUE THREAD

**Issue by peterfyj** [Semantic-Org/Semantic-UI#2937]
The animation of a dropdown menu is incompatible with jQuery 3.0.0.

In [this JSFiddle](http://jsfiddle.net/ecf78o0e/1/), when we choose jQuery 2.0.2, everything is fine, but when we switch to jQuery 3.0.0, the appearing animation of the menu is stuck.

**Comment by jlukic** [comment]
jQuery 3 is still in alpha. I will be able to debug against a Release Candidate build if the issue still exists, but this is far too early.
