### ISSUE TITLE
Too much dependencies

### ISSUE THREAD

**Issue by yhjor1212** [Semantic-Org/Semantic-UI#2938]
1. my app does not use gulp, building semantic require to add much those gulp related packages that makes my app large
2. when I run npm install in clean directory, it will ask if I need automatic or custom install and I found it annoying

I love what semantic provide but I, at the same time, hate what the workflow that force us to do.

These are just comments. Hope it will be better.

**Comment by veke** [comment]
You can always install the semantic to other than your project folder. Configure semantic build folder to project folder.

**Comment by jlukic** [comment]
Please check the contributing guide for the kind of commentary intended for GitHub Issues.
