### ISSUE TITLE
Vertical Menu with Bottom Menu option

### ISSUE THREAD

**Issue by purplecones** [Semantic-Org/Semantic-UI#2940]
Similar to how a normal menu works with ```class="right menu"``` :
```
<div class="ui menu">
  <a class="item">Browse</a>
  <a class="item">Submit</a>
  <div class="right menu">
    <a class="item">Sign Up</a>
    <a class="item">Help</a>
  </div>
</div>
```
can we have the same for a vertical menu with ```class="bottom menu"```?
```
<div class="ui vertical menu">
  <a class="item">Browse</a>
  <a class="item">Submit</a>
  <div class="bottom menu">
    <a class="item">Sign Up</a>
    <a class="item">Help</a>
  </div>
</div>
```

**Comment by jlukic** [comment]
I'm not sure this would be possible without a recode, nested menus inside vertical menus are treated as sub-menus. 

I would imagine using attached menus and `display: flex` on container would be easiest solution.

**Comment by gebbber** [comment]
Old question, but I've solved this in a similar application by wrapping the bottom elements in a ``<div>`` with some (simple) manual CSS. Following is React code, but hopefully should help:
```
<Menu vertical>
    <Menu.Item>...</Menu.Item>
    <Menu.Item>...</Menu.Item>
    <Menu.Item>...</Menu.Item>
    <div style={{position:'absolute', bottom:'0', width:'100%'}}>
        <Menu.Item>...</Menu.Item>
        <Menu.Item>...</Menu.Item>
    </div>
</Menu>
```

I'm working with a vertical menu that is taking up the whole viewport, so the correct positioning might be a coincidence, but if you're working with a shorter vertical menu you may have to set `position:'relative'` with no specified offset on the <Menu> element, and solve any problems from there...
