### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by homerjonathan** [Semantic-Org/Semantic-UI#2946]
### Context Menus - Feature Request ###

Not sure if it breaks design rules for semantic-ui but I would like to suggest a feature to have a context menu on **right mouse** click.  There does seem to be most of the functionality required already working.  

For example the popup function with wide menu as shown in the popup examples is very close to creating this feature.

```
$('.example .custom.button')
  .popup({
    popup : $('.custom.popup'),
    on    : 'click'
  })
;
```

Just changing the *on* event to support 'context' or 'rightclick'.

**Comment by jlukic** [comment]
#203 Continue discussion there
