### ISSUE TITLE
[Button] Modify Basic Button Style

### ISSUE THREAD

**Issue by gitblit** [Semantic-Org/Semantic-UI#2947]
Thanks for the great project!  I really love it!

I like the improvements and new options in 2.1 but I have to say the removal of the hover-based coloring behavior is not a win-win for me.  There are times that I will definitely reach for the new design but...

I have two gripes with it as the only way to do `basic button`.
1. The UI elements in my app are now competing with user data for brain/eyeball attention.  The hover-based option allows for a sophisticated UI without interfering with focusing on user data while still allowing the user to get (fun) visual feedback about an action they might choose.
2. The hover state on `basic {color} button` is almost indistinguishable from the non-hovered state.  Maybe filling in the background on hover like the inverted buttons do would be better?

Really what I'd like is to have my cake and eat it too.  I'd like to still have the _option_ of hover-based coloring while not interrupting your design plans.  Perhaps there can be a `basic hoverable {color} button`  or something similar?

And if there can't be, then I guess I'll adapt.
Thanks for your consideration.

**Comment by jlukic** [comment]
My concern is that colored on hover creates a [mystery meat](http://www.webpagesthatsuck.com/mysterymeatnavigation.html) navigation scenario. 

The colors are suppose to give a user affordances to an elements purpose, but a user doesn't have any idea what the cues should mean until they hover their cursor over each element.

I think the solve is to use `basic button` wherever an element should be recessed in a design, and use basic colored button when an element should be recessed overall compared to other page design elements but still needs color cues.

**Comment by jlukic** [comment]
@gitblit After thinking about this I think it makes sense to keep things somewhere in the middle with text color appearing on normal state, and border color appearing on hover.
