### ISSUE TITLE
[Form] Wrong direction of left/right pointing labels in form

### ISSUE THREAD

**Issue by diolive** [Semantic-Org/Semantic-UI#2950]
`left` and `right` labels in form validation labels looks at up only.
Fiddle: http://jsfiddle.net/1ps3bz7f/1/
Even in documentation: http://semantic-ui.com/elements/label.html#pointing

**Comment by diolive** [comment]
I've find the source of issue. There are absent rules for `class*=["pointing left"]` and `class*=["pointing right"]`, only for `left pointing` and `right pointing` in `label.less`.
In the same time we can use `below pointing` and `pointing below`.

What is the **true** way: use the only allowed class order or fix the styles?

**Comment by jlukic** [comment]
Yeah, I recently redid these to use transform instead of negative margins. It looks like it's busted.

**Comment by diolive** [comment]
It can be _fixed_ be using classes in only proper order (like in [fiddle](http://jsfiddle.net/1ps3bz7f/3/)).

**Comment by jlukic** [comment]
Oh I see now. Sorry checking from phone. 

Significant word order was added to support variations like `top attached bottom pointing`
http://jsfiddle.net/jaL3eycx/

I just need to update docs

**Comment by Siprah** [comment]
@jlukic Docs are still outdate.

**Comment by jlukic** [comment]
I've updated docs for next release
