### ISSUE TITLE
Class order matters, makes it incompatible with hamlc

### ISSUE THREAD

**Issue by rpbaltazar** [Semantic-Org/Semantic-UI#2951]
When compiling hamlc to to html, the classes are not being written in the same order as the original (this might be an open bug on the compiler I'm using).
e.g.
<div class= align eleven column right wide> ... </div>
does not do the same as
<div class= column eleven wide align right> ... </div>
But as far as my understanding goes, class order within the same element should not have different behaviours.
Is that the expected behaviour?

I understand that one can economize the size of the css, but at what cost?

**Comment by jlukic** [comment]
Short answer is yes, `left floated right aligned` is diferent than `right floated left aligned`, best discussion of this is in other threads. #396 #1526
