### ISSUE TITLE
font-awesome icons & semantic-ui

### ISSUE THREAD

**Issue by jmls** [Semantic-Org/Semantic-UI#2952]
For the life of me, I don't get what I should be naming the icon 

for example,

fa-floppy-o (http://fortawesome.github.io/Font-Awesome/icon/floppy-o/)

I've tried
<i class="fa-floppy-o icon"></i>
<i class="fa.floppy.o icon"></i>
<i class="fafloppyo icon"></i>

and numerous other iterations

what's the magic incantation ? ;)

thanks

**Comment by KapuzenSohn** [comment]
For floppy it would be:
`<i class="save icon"></i>`

You simply search in the semantic ui doku for the icon you want and then open the examples and then you copy it or you insert the name of the icon like I did

**Comment by jmls** [comment]
so all of the font-awesome icons have been renamed in semantic-ui ?

**Comment by KapuzenSohn** [comment]
I don´t think all, but some. Just look in the documentation and you find the names you need.

**Comment by jlukic** [comment]
Icons have generally all been renamed.

**Comment by lp741** [comment]
just edit **site/elements/icon.overrides.import.less** and add the following code
```
/*******************************
         Site Overrides
*******************************/

/*******************************
            Icons
*******************************/

/* new 4.5.0 icons */

/* Web Content */
i.icon.hashtag:before { content: "\f292"; font-family: FontAwesome}
i.icon.percent:before { content: "\f295"; font-family: FontAwesome}
i.icon.shopping-bag:before { content: "\f290"; font-family: FontAwesome}
i.icon.shopping-basket:before { content: "\f291"; font-family: FontAwesome}

/* Brand Icons */
i.icon.bluetooth:before { content: "\f293"; font-family: FontAwesome}
i.icon.bluetooth-o:before { content: "\f294"; font-family: FontAwesome}
i.icon.codiepie:before { content: "\f284"; font-family: FontAwesome}
i.icon.edge:before { content: "\f282"; font-family: FontAwesome}
i.icon.fort-awesome:before { content: "\f286"; font-family: FontAwesome}
i.icon.mixcloud:before { content: "\f289"; font-family: FontAwesome}
i.icon.modx:before { content: "\f285"; font-family: FontAwesome}
i.icon.product-hunt:before { content: "\f288"; font-family: FontAwesome}
i.icon.reddit-alien:before { content: "\f281"; font-family: FontAwesome}
i.icon.scribd:before { content: "\f28a"; font-family: FontAwesome}
i.icon.usb:before { content: "\f287"; font-family: FontAwesome}

/* Payment Icons */
i.icon.credit-card-alt:before { content: "\f283"; font-family: FontAwesome}

/* Video Player Icons */
i.icon.pause-circle:before { content: "\f28b"; font-family: FontAwesome}
i.icon.pause-circle-o:before { content: "\f28c"; font-family: FontAwesome}
i.icon.stop-circle:before { content: "\f28d"; font-family: FontAwesome}
i.icon.stop-circle-o:before { content: "\f28e"; font-family: FontAwesome}
```

**Comment by thelamborghinistory** [comment]
> Icons have generally all been renamed.

I think that's a terrible idea. They should have all the same classes from Font Awesome.

**Comment by tvrtkos** [comment]
The renaming of icons is bad for the following reasons:

FA icon was general in meaning and could be used in all kinds of contexts, semantic icon has single specific meaning. For example: FA "times" icon (X) can mean "remove" as you say, but it can also be "close" and "error". 

It is also hard to find icons because you can't search icons by literal meaning, you must translate to some abstract notion. I can't search for "phone" I must browse all icons and find out that it is a "call" icon. I don't want to "call" anybody, I want to display the user's phone information.

Maybe the most important reason is having to learn two sets of icon names.

**Comment by humbertocruz** [comment]
hello, I'm building a Mobile App with fontawesome and it's has a web admin with react-semantic. I need a class name "translation" table to be able to choose a icon on both interfaces, anyone already done this? something like: {"add to calendar":"calendar-plus-o",...}
