### ISSUE TITLE
Icon inputs in form fields no longer fluid (since 2.1)

### ISSUE THREAD

**Issue by erikdahlstrand** [Semantic-Org/Semantic-UI#2953]
Hi,

After upgrading to 2.1 the icon inputs (in form fields) are no longer fluid. Is this intentional?

See example: http://semantic-ui.com/examples/login.html

**Comment by jlukic** [comment]
I'll have a patch for this shortly

**Comment by mrmoree** [comment]
Hello!

 

Important message, visit http://catenianprovince20.com/spent.php?yx4l

 

mrmoree@web.de

**Comment by gadielsandoval** [comment]
No soport input-sm when in input control
<"div class="ui fluid form segment">
<"div class="field">
                                        <"div class="form-groug form-group-sm">
                                            <"div class="col-md-4 col-sm-4 col-xs-4 ">
                                                <"label class="control-label" id="lblPrueba" for="lblPrueba">Prueba:</label>
                                            </div>
                                            <"div class="col-md-8 col-sm-8">
                                                <"div class="ui corner labeled input">
                                                    <"div class="input-group">
                                                        <"span class="input-group-addon"><"i class="glyphicon glyphicon-user"></i></span>
                                                        <"input id="txtPrueba" name="txtPrueba" type="text" placeholder="Prueba..." class="input-group-addon" maxlength="15"/>
                                                    </div>                                                    
                                                    <"div class="ui corner label">
                                                        <"i class="asterisk icon"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
</div>

using corner <"div class="ui corner label"><i class="asterisk icon"></i></div"> in version 2.1.6
