### ISSUE TITLE
[Checkbox] - Checkbox do NOT passing value when form is submited

### ISSUE THREAD

**Issue by KrzysztofBorowiak** [Semantic-Org/Semantic-UI#2954]
**Steps to Reproduce**
1. Create form with checkbox:
<div class="ui checkbox">
		<input type="checkbox" name="test" value="MyTestValue" checked="checked">
		<label>Test</label>
	</div>
2. Add javascript to submit form $('.ui.form').form({...});
3. Submit

**Expected**
The Checkbox should pass - MyTestValue

**Result**
The Checkbox passing true or false - depend if checkbox is checked or not

**Testcase**
http://jsfiddle.net/rduvhn8u/98/

**Comment by jlukic** [comment]
This is standard POST behavior, see [stackoverflow explanation](http://stackoverflow.com/questions/11424037/does-input-type-checkbox-only-post-data-if-its-checked)

**Comment by KrzysztofBorowiak** [comment]
Did you tried to understand? Checkbox is checked. Value is not send. Rather than real value - _POST has boolean "true" or "false".

Did you run Testcase?

**Comment by KrzysztofBorowiak** [comment]
I think this is BUG in 2.1
When downgraded to 2.0 it started works as expected.

**Comment by maturano** [comment]
@jlukic I know you misunderstood, but just to be clear:

> You must use the value attribute to define **the value** submitted by this item. Use the checked attribute to indicate whether this item is selected

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-type

So, yes, it's a bug.

**Comment by jlukic** [comment]
I see, I've never seen anyone use value with checkbox before and didn't realize. It seems a bit weird to me that the checkbox either passes value or false, but if that's what's expected.. who's to argue.

**Comment by KrzysztofBorowiak** [comment]
Thank you for your response!

I have situation where items need to be selected and passed as array - input name with square brackets. For example:

/ input type="checkbox" name="serverID[]" value="1234" checked /

I expect POST data with serverID = array of IDs (not true or false). 

<img width="1177" alt="screen shot 2015-09-10 at 09 03 10" src="https://cloud.githubusercontent.com/assets/4264014/9783338/7c268a30-579b-11e5-886c-e9114b6dd4c4.png">

I understand returning true/false to find if checkbox is checked in javascript. Not when sending form data.

Having "value" in checkbox is perfectly fine according to:
http://www.w3.org/TR/html-markup/input.checkbox.html

Thanks!
