### ISSUE TITLE
problem of middle aligned grid

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#2959]
"middle aligned" not work when wrapping with a row, see http://jsfiddle.net/nzhtvz7a/1/

 .ui[class*="middle aligned"].grid>.column:not(.row)

may change to

 .ui[class*="middle aligned"].grid .column:not(.row)

**Comment by maturano** [comment]
I believed this is on purpose; the `row` is who needs be `middle aligned`, you know, "*for semantics*": https://jsbin.com/bilupa/2/edit?html,output

**Comment by jlukic** [comment]
I can confirm this is not intentional. Aligned grid should pass its alignment on to columns.

**Comment by jlukic** [comment]
Fixed in `2.1.4`
