### ISSUE TITLE
Sidebar and Modal components mess up the layout to unusable state.

### ISSUE THREAD

**Issue by v3rron** [Semantic-Org/Semantic-UI#2964]
Just spent a couple of hours trying to debug the broken layout on iOS Safari and iOS simulator. Turns out that after using modal and sidebar components they leave lots of unnecessary and risky HTML and CSS which are not cleaned properly.
HTML before sidebar is shown:
````
<body>
  <div class="ui vertical menu bottom sidebar">
    <a class="item ui button">Edit</a>
    <a class="item ui button">Delete</a>
    <a class="item ui button">Cancel</a>
  </div>
</body>
````
HTML after sidebar was closed:
````
<body class="pushable"> <!-- note the pushable class -->
  <div class="ui vertical menu bottom sidebar">
    <a class="item ui button">Edit</a>
    <a class="item ui button">Delete</a>
    <a class="item ui button">Cancel</a>
  </div>
</body>
````
More classes being added when using it with modals. HTML before modal is shown:
````
<body class="pushable"> <!-- pushable class still here -->
  <div class="ui vertical menu bottom sidebar">
    <a class="item ui button">Edit</a>
    <a class="item ui button">Delete</a>
    <a class="item ui button">Cancel</a>
  </div>
  <div class="fullscreen ui modal"></div>
</body>
````
HTML after triggering modal from sidebar and closing the modal:
````
<body class="pushable dimmable blurring"> <!-- note the pushable dimmable and blurring classes -->
  <div class="ui vertical menu bottom sidebar">
    <a class="item ui button">Edit</a>
    <a class="item ui button">Delete</a>
    <a class="item ui button">Cancel</a>
  </div>
  <div class="fullscreen ui modal"></div>
  <div class="ui dimmer modals page transition hidden"></div> <!-- note this entire div left after showing the modal, which sometimes stays active after closing the modal, probably because of the conflicts with sidebar dimmer being rendered at the same time -->
</body>
````
<b>Here's a jsfiddle that I created to reproduce the issues.
In order to see the issue, you need to open this on iOS Safari or by opening a regular Safari and the setting Develop > User Agent > Safari iOS 8.1</b>

http://jsfiddle.net/wkztxqpq/3/

<b>PS: Also the Sidebar dimmer doesn't seem to work on iOS, it just covers the entire screen in black instead of transparent background.</b>
PPS: I know there's a lot of issues like this, I think this is pretty crucial bug to make it <b>high</b> priority.
#1459 , #2087, #1933, #1624, #2261, #2177,

**Comment by v3rron** [comment]
was this issue postponed?

**Comment by jlukic** [comment]
Yes, time issues

**Comment by jlukic** [comment]
Sidebar and modal both have expected markups to work, `modals dimmer` wrapper for modal, and `pusher` wrapper for sidebar. The components try to degrade gracefully by adding the required DOM elements if you haven't specified them in your code. 

Ideally they should already be there when you initialize them to avoid detaching the entire page DOM and messing with your css selectors.

Sorry, I realize this is a lot of time lapsed for such a simple answer.
