### ISSUE TITLE
TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by sonyarianto** [Semantic-Org/Semantic-UI#2970]
I use fresh install of 2.1.3 and I experience this error while I build with `gulp build`
~~~
/home/assets/lib/ui/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
TypeError: Cannot call method 'match' of undefined
~~~

**Comment by shodanuk** [comment]
I experienced a similar error when running Node 0.10.38. Switching Node 0.12.x fixed it for me.

**Comment by jlukic** [comment]
I'm unsure of cause, but not receiving any errors when running latest npm/node stable with install

**Comment by rlora** [comment]
I had the same issue using Node 0.10.29. There are several warnings indicating that node 0.12.x is required during build process.

i.e. gulp-autoprefixer@3.0.1: wanted: {"node":">=0.12.0"}

After upgrading to 0.12.x works as expected.

**Comment by athap** [comment]
Updating NodeJS fixed this issue for me
