### ISSUE TITLE
'hidden content' does not hide

### ISSUE THREAD

**Issue by rachellji** [Semantic-Org/Semantic-UI#2972]
Hey,

I'm not sure if I'm using "hidden content" in the right way. It does not hide element for me. 

What I wanted to do is to show/hide menu based on authentication. But the menu does not hide. So I did some simple experiment. It's not my Facade not working. It's 'hidden content' does not work.

JSFiddle experiment: 

        <div class="ui menu">

       <a class="ui item">
           <i class="home icon"></i> Home
        </a>
        <a class="ui item hidden content">
            <i class="user icon"></i>User
       </a>

        </div>

JSFiddle link experimenting 'hidden content' : http://jsfiddle.net/epp3hb88/

Thanks!

**Comment by veke** [comment]
There is no global "hidden content" selector. There are some elements that you can hide with .hidden or .hidden content selectors. You can hide menu item by creating your own .hidden class.

**Comment by jlukic** [comment]
`hidden content` only has meaning inside `ui reveal` and `animated button`
