### ISSUE TITLE
sidebar issue : no menu on iOS8 Safari / apple-mobile-web-app-capable

### ISSUE THREAD

**Issue by h4mzt3r** [Semantic-Org/Semantic-UI#2976]
Hi, 

On iOS 8.1.4 (iPhone 5) with Safari / apple-mobile-web-app-capable, sidebar doesn't work correctly : when I click on my sidebar trigger I get a whole black page instead my menu. 

Work properly on desktop with Chrome / Firefox (except a lil' annoying other bug : when you open a sidebar, your body background change automatically his color to white and the content disappear...)

**code sample**
```
<div id="sb_profile_panel" class="ui sidebar">
    <div class="ui grey inverted large fluid vertical menu">
        <a class="item"><i class="sign out icon"></i> Logout</a>
    </div>
</div>

<div class="ui top large secondary inverted blue fixed menu">
    <div id="sb_profile_trigger" class="item">
        <i class="sidebar icon"></i>
    </div>
    <a class="center item">FEED</a>
</div>
    
<div class="pusher">{{content}}</div>
    
<script type="text/javascript">
    $(document).ready(function() {
        $('#sb_profile_trigger').click(function () { $('#sb_profile_panel').sidebar('toggle'); })
    });
</script>
```

**Comment by jlukic** [comment]
Please create a standalone test case on jsfiddle without templating / serve side code.

**Comment by h4mzt3r** [comment]
Here is the link : https://jsfiddle.net/h4mzt3r/s59u2r6o/

**Comment by h4mzt3r** [comment]
After many other tests, it's fine. 
Works great after a cache reset (probably an iOS Safari issue). 
I close this issue.

**Comment by jlukic** [comment]
Sorry about that, thanks for taking the time to follow through.
