### ISSUE TITLE
[Dropdown] Usage of the onLabelCreate($label) callback

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#2977]
According to the [document](https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/documents/modules/dropdown.html.eco#L2584) it seems a label can be modified before it get added (in a `allowAdditions = true` context).

What I want is to lowercase the label before it get added. But I have no clue how to modify the being-added label since the callback function only get `value` and `text` arguments which are both passed by value. Probably add an example to the document?

Many thanks!

**Comment by jlukic** [comment]
onLabelCreate receives the $label element which is expected to be returned. 

To lowercase you could use something like `return $label.html( $label.html().toLowerCase() );`

**Comment by kfei** [comment]
It seems `onLabelCreate` receives `value` and `text`, and then returns `$(this)` [(source)]( https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3266). Am I got anything wrong?

Many thanks again.

**Comment by jlukic** [comment]
You can modify `data-value` parameter to modify its value, [relevant underlying bits](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js)
