### ISSUE TITLE
[Dropdown] Search in selection dropdown is not visible when opened

### ISSUE THREAD

**Issue by veke** [Semantic-Org/Semantic-UI#2980]
Here is a reproduced fiddle:
http://jsfiddle.net/geoyxoqz/1/

If you open the dropdown you need to scroll to top to reveal the search input.
Should be visible when dropdown is opened.

**Comment by veke** [comment]
And as a follow up question: How can we reset the search keywords programmatically. 
Behaviour methods $(elem).dropdown('clear'), restore defaults etc... did not work. Or I don't understand the behaviour api.

**Comment by jlukic** [comment]
To be honest I had no idea this would even work. I don't think it really makes sense to use `selection dropdown` styling with a nested search menu. Just UX wise its really jarring. 

I would imagine doing it like this
http://jsfiddle.net/emtyfo5o/
