### ISSUE TITLE
[Dropdown] Remote fetch data using jsonp

### ISSUE THREAD

**Issue by goofansu** [Semantic-Org/Semantic-UI#2986]
Hi, I'm making a jsonp request which has a dynamic callback method, such as "jQuery21406973864631727338_1441793704275".

Sometimes it will say "Uncaught TypeError: jQuery21406973864631727338_1441793704275 is not a function",  but now always. 

My question is, why it sometimes reports this error while in most cases it's ok.

Did I miss a setting? Thank you very much for any advice.

If anyone want to debug this request, I can provide you the `<MY_PRIVATE_KEY>'`

Following is my code:

```
<div class="ui fluid search selection dropdown">
  <input type="hidden" name="address">
  <i class="dropdown icon"></i>
  <div class="default text">选择您的地址</div>
  <div class="menu">
  </div>
</div>

<script>
 $('.search.dropdown')
    .dropdown({
      apiSettings: {
        url: 'http://restapi.amap.com/v3/assistant/inputtips?s=rsv3&city={city}&key={key}&keywords={query}',
        dataType: 'jsonp',
        stateContext: '.search.dropdown',
        urlData: {
          key: '<MY_PRIVATE_KEY>',
          city: 'shanghai'
        },
        onResponse: function(response) {
          var result = {};
          result["success"] = true;
          result["results"] = response.tips;
          return result;
        },
        onFailure: function() {
          console.info("fail");
        }
      },
      fields: {
        name: 'name',
        value: 'location'
      }
    });
</script>
```

This is the result preview:

![screenshot of google chrome 9-9-15 6 23 55 pm](https://cloud.githubusercontent.com/assets/1143191/9759484/f85032f4-571f-11e5-88a1-9717af12fe42.png)

**Comment by jlukic** [comment]
Interesting, I haven't experienced any errors with using JSONP and `api`. 

Any jQuery AJAX settings can also be passed here, you might want to try 

```javascript

      apiSettings: {
        url: 'http://restapi.amap.com/v3/assistant/inputtips?s=rsv3&city={city}&key={key}&keywords={query}',
        // add this
        callback: 'sameCallbackAlways',
        stateContext: '.search.dropdown',
        urlData: {
          key: '<MY_PRIVATE_KEY>',
          city: 'shanghai'
        }
      }

**Comment by goofansu** [comment]
Thanks, I tried it. It remains the same error with "mySpecialName is not a function".
I found the response is something like `mySpecialName({JSON_DATA})`.

Here is a discussion about `jsonpCallback`: http://forum.jquery.com/topic/jsonp-and-randomly-generated-callback-function. If jsonpCallback is not defined, jQuery will generate dynamic callback and process the response with this callback.

Anyway, this is not a bug in semantic-ui, so I close this issue.

**Comment by goofansu** [comment]
By the way, is there any event to trigger the api query after I stop the input? Thanks

**Comment by jlukic** [comment]
`$('.button').api('query');`

Hope you find the additional answers you need

**Comment by goofansu** [comment]
@jlukic :+1:
