### ISSUE TITLE
Reverse Order  is not working (Error)

### ISSUE THREAD

**Issue by LeslieMeneses** [Semantic-Org/Semantic-UI#2987]
Hello!
## I`m try to run this code "Reverse Order" put is not working.

```
<div class="ui mobile reversed equal width grid">
  <div class="column">
    First
  </div>
  <div class="column">
    Second
  </div>
  <div class="column">
    Third
  </div>
</div>
```

---

http://semantic-ui.com/collections/grid.html#reverse-order

I need something more code?
can somebody help me?

**Comment by LeslieMeneses** [comment]
Now is working, I was in a outdated version. ;)

**Comment by vinayakkulkarni** [comment]
Closing this as it's resolved

**Comment by TheWizard91** [comment]
@kathcode could you please, please let us know what do you mean by outdated version?
