### ISSUE TITLE
Broken label menu horizontal

### ISSUE THREAD

**Issue by tbp** [Semantic-Org/Semantic-UI#2989]
On semantic 2.1 horizontal label menu and vertical label pointing menu is broken. 

See this 
![2015-09-09 21-05-58](https://cloud.githubusercontent.com/assets/638728/9770093/b33e5d6e-5736-11e5-9614-82c02268c1e0.png)

and this

![2015-09-09 21-07-03](https://cloud.githubusercontent.com/assets/638728/9770101/c4847158-5736-11e5-9db0-900ea7544593.png)

**Comment by avalanche1** [comment]
Closing until there's a test case.
