### ISSUE TITLE
[Dropdown] - Search value is not cleared (if there is value) after running set selected

### ISSUE THREAD

**Issue by jaimehing** [Semantic-Org/Semantic-UI#2991]
**Steps to Reproduce**
1. Make a dropdown a search selection
2. Search something from the dropdown
3. Leave the search value there and in the code, There's a button that will run this dropdown("set selected", <value here)

**Expected**
The Dropdown should clear the search value then set a dropdown value.

**Result**
The Dropdown does this:
![bug dropdown](https://cloud.githubusercontent.com/assets/6761602/9779059/5ca9530e-57aa-11e5-8b55-b4135a72816f.PNG)

**Comment by jlukic** [comment]
I'm unable to reproduce
http://jsfiddle.net/1f1xub26/

**Comment by jaimehing** [comment]
HI jlukic,

I can reproduce the bug from your link. Upon refreshing the page, I've tried to search for 'aaa' then press the button. Please see attached image for reference.

![github](https://cloud.githubusercontent.com/assets/6761602/9851728/d4edada8-5b2c-11e5-8e6e-2a9df4c39e8b.png)

**Comment by jlukic** [comment]
Ah I see, this bug only appears to happen first time after page load.
