### ISSUE TITLE
Using sidebar with Meteor without context

### ISSUE THREAD

**Issue by reel** [Semantic-Org/Semantic-UI#2998]
When using a sidebar with Meteor, the sidebar gets moved outside of the `<div id="__blaze-root"></div>` if it is not triggered without context.

If we want to use the Blaze events, it needs to be inside the blaze-root div.

**Comment by jlukic** [comment]
Context is designed to support that use case specifically. I'm not sure there can be a second solution. Sidebar and modal both expect to be children of body.

**Comment by reel** [comment]
The problem I am facing is:

1. Use it without context and don't use the `Template.myTemplate.events` and use jQuery in `onRendered`
  Result: it works, my menu and sidebar keeps their fixed behavior on top of the screen but i get warnings in console as for pusher/pushable classes and lose my `.events` 
2. Use it with a context.
   Result: the top fixed menu is fixed on top until I fire the sidebar toggle. Once the DOM is modified, the sidebar and menu are no longer fixed on top and scroll with content. (maybe this can be fixed with appropriate wrapper attributes)

**Comment by brajt** [comment]
What if you specify body tag as blaze-root instead of div? You can do that f.e. [this way](https://github.com/kadirahq/blaze-layout#set-different-root-node).

**Comment by reel** [comment]
I will try that. Thank you

The code i am testing is: http://meteorpad.com/pad/mz5pfx26zfWD5vNGC/Semantic-UI-TEST

**Comment by brajt** [comment]
I vote to close this as it's easily solvable from Meteor side and doesn't really touch Semantic UI.

**Comment by reel** [comment]
Works fine with meteor + react. closing.
