### ISSUE TITLE
Radio buttons with value "false" cannot be clicked

### ISSUE THREAD

**Issue by malacalypse** [Semantic-Org/Semantic-UI#2999]
http://jsfiddle.net/149c3upw/1/

Introduced sometime shortly before 2.0.7, I think. Still current, as the fiddle shows.

I haven't been able to spend any time debugging this one yet, sorry!

**Comment by jlukic** [comment]
http://jsfiddle.net/zbvnLb0t/

**Comment by maturano** [comment]
The cause is you have it as `readonly` element...

```html
<input class="..." readonly="readonly" type="radio" value="false" ...>
```

***Not a bug***

**Comment by jlukic** [comment]
Thanks @maturano, i appreciate your helpfulness on these boards

**Comment by malacalypse** [comment]
Ah. Whoops. Sorry for the noise.
