### ISSUE TITLE
Menu State - Hover: example code class should be 'link' not 'hover'

### ISSUE THREAD

**Issue by IceDragon13** [Semantic-Org/Semantic-UI#3000]
Item class in example source code for the [Menu State - Hover](http://semantic-ui.com/collections/menu.html) seemingly conflicts with denoted usage:
> Menu items are only hoverable if they are ```a``` links, or given the class name ```link```

Current:
```
<div class="ui compact menu">
  <div class="hover item">
    Link
  </div>
</div>
```

Suggested:
```
<div class="ui compact menu">
  <div class="link item">
    Link
  </div>
</div>
```

**Comment by jlukic** [comment]
No idea why that's there.. will fix

**Comment by jlukic** [comment]
Fixed in next
