### ISSUE TITLE
[Validation] default promt for rule

### ISSUE THREAD

**Issue by listepo** [Semantic-Org/Semantic-UI#3001]
# Example:

Declaration:
```javascript
$.fn.form.settings.defaultPrompts = {
    'empty':'Field is required',
    'creditCard': '{{placeholder}} contains an invalid value: {{value}}'
}
```

* ```{{placeholder}}``` - current input placeholder
* ```{{value}}``` - current input value

Usage:

```javascript
$('.ui.form')
  .form({
    fields: {
      name: {
        identifier  : 'name',
        rules: [
          'empty', // or {type: 'empty'}
          'creditCard',
          {
            type   : 'minCount[2]',
            prompt : 'Please select at least two skills'
          }
        ]
     }
  }
});
```

**Comment by jlukic** [comment]
I've added a form of this in https://github.com/Semantic-Org/Semantic-UI/commit/edc9b34928bbe7360ee01689b0f0ce7b67c3228c

I have not yet added support for those templates values

**Comment by listepo** [comment]
@jlukic, thanks :+1:

**Comment by jlukic** [comment]
I'm using four templates values 
* `{value}` - Current value
* `{ruleValue}` - bracketed value from rule, i.e. minLength[100] = 100 
* `{identifier}` - Name from identifier
- `{name}` - Text from corresponding field form label

**Comment by listepo** [comment]
many people use a form without a label, may make sense to add placeholder?

**Comment by jlukic** [comment]
Will default to placeholder or `This field` when no label

**Comment by listepo** [comment]
it's cool :+1:
