### ISSUE TITLE
dropdown tabindex

### ISSUE THREAD

**Issue by mohsensafari** [Semantic-Org/Semantic-UI#3002]
Hi, I think there is a bug on dropdown tabindex functionality. if dropdown has not got a "search" class the semantic dropdown module give it a tabindex of "-1" in remove:tabbable function and then it never change on set:tabbable with a tabindex of "-1" the tab ordering of modules not work properly

**Comment by jlukic** [comment]
Please fork the JSFiddle in the readme to create a test case.

**Comment by NeverI** [comment]
Here is the JSFiddle http://jsfiddle.net/xs81ghub/1/

**Comment by jlukic** [comment]
Thanks neverl for picking this up.

**Comment by RobinKuiper** [comment]
It's getting tabindex='0' all the time for me, any news on this?

**Comment by jlukic** [comment]
Thanks for your patience here.

**Comment by RobinKuiper** [comment]
Awesome!

**Comment by jlukic** [comment]
Should have been fixed in `2.1.5`, this bug was mistagged.
