### ISSUE TITLE
[Item] Possible bug with "Item" view. Unlimited content width.

### ISSUE THREAD

**Issue by treble-snake** [Semantic-Org/Semantic-UI#3003]
Here is an example: http://jsfiddle.net/esco613c/1/
Not sure, if it's a bug or a feature, but: as you can see, e.g. card component has "width: 100%" property on div.content block, so its max width corresponds to parent's max width.
And item does not, so content expands widely, breaking a layout.

**Comment by jlukic** [comment]
Images don't by default have a max width. `ui image` sets a max width by default of `100%` its suggested you use this when using image content.

http://jsfiddle.net/to8x731a/
