### ISSUE TITLE
[POPUP] Popup does not fit within the boundaries of the viewport

### ISSUE THREAD

**Issue by qimus** [Semantic-Org/Semantic-UI#3004]
if you do not have enough space for the popup appears this error, such as open console.

**Comment by jlukic** [comment]
That's correct behavior. You can specify a `lastResort` position in settings object if you need it to appear always even if it cannot fit.

**Comment by matikucharski** [comment]
I think default error throwing when popup cannot fit is not correct from UX point of view.

**Comment by avalanche1** [comment]
@matikucharski +1

**Comment by subhog** [comment]
@matikucharski +1

That's definitely not what users expect.

**Comment by jordmax12** [comment]
@matikucharski  +1

**Comment by mrkam** [comment]
max-height can be set to 100vh instead.

**Comment by claudiospro** [comment]
use element children and set scroll and max-height:
`
<div class="ui popup" style="top: auto; left: 1px; bottom: 69px; right: auto;">
<ul style="overflow-y: scroll; max-height: 400px;">
</div>
</div>
`
