### ISSUE TITLE
[Button] - add :active css to .ui.button

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3005]
Focusable button-divs (`div class="ui button" tabindex="0"`) should change their appearance when Return or Space is pressed.

**Comment by jlukic** [comment]
`:active` style is different. You can check this in chrome emulator by simulating both `:focus` and `:active` at the same time.

**Comment by avalanche1** [comment]
I'm talking about that this element doesn't visually change at all when Return or Space is pressed.

**Comment by jlukic** [comment]
I'm not sure what we can do from a purely css standpoint. There are active and :hover styles.

**Comment by avalanche1** [comment]
This is not about css.
`:active` style is not applied when either Space or Return is pressed.
Same goes for `<button class="ui button">` when Return is pressed.
Testing it in docs:
![image](https://cloud.githubusercontent.com/assets/10534563/9835347/aedc5c94-59f7-11e5-8598-a6c1a28db0dd.png)

At the same time ![image](https://cloud.githubusercontent.com/assets/10534563/9835349/d5bbd952-59f7-11e5-89d3-f812a564ce65.png) works fine

**Comment by jlukic** [comment]
I'm not sure what to say, button is only css. We cant solve for javascript problems
