### ISSUE TITLE
Bad modal position when the images in image content are appended

### ISSUE THREAD

**Issue by David-Tsui** [Semantic-Org/Semantic-UI#3008]
(My english is poor, sorry)

I use Modal to show each type of my products, thus I use getJSON to get the path of images then append them into the div of class image content.
However, the position of modal is usually not correct. 
Now I use setTimeout and modal method "refresh" to solve it, but it seems not perfert.
I guess that it might be the number of images vary with each products.
Does someone encounter this problem?

**Comment by jlukic** [comment]
Please create a test case to reproduce your issue. Or try project talk for usage discussion

**Comment by David-Tsui** [comment]
Test case:

http://speechlab.cs.nchu.edu.tw/project2/test.html

Just press the button :DDD

Thank you.

**Comment by jlukic** [comment]
Thanks, I'll check it out

**Comment by CakalSG** [comment]
can you test set image width/height ? because image not loaded before showing modal 

sorry my eng.

**Comment by David-Tsui** [comment]
I have used "ui medium image"

**Comment by CakalSG** [comment]
i think u must control image is really loaded ?

can u change and test ?

    $(document).ready(function() {
      $(".modalBtn").click(function(e) {
        var caller = e.target;
        var call_id = $(caller).attr("id");
        var text = $("#" + call_id).html();
        $("#modal-header").html(text);
        $.getJSON("js/test.json", function(data){
          var paths = [];
          for(var i = 0; i < data.length; i++) {
            if (text == data[i].name) {
              paths = data[i].path;
              break;
            }
          }
          $("#image-place").html("");
          paths.forEach(function(path) {
            $("#image-place").append(
              '<img src="' + path + '" alt="image not found"/>' + '<br>'
            );
          })
        });
        $("#image-modal").modal("toggle");
      });
      $("#image-modal-closeBtn").click(function() {
        $("#image-modal").modal("toggle");
      })
    });

THIS;


    $(document).ready(function() {
      $(".modalBtn").click(function(e) {
        var caller = e.target;
        var call_id = $(caller).attr("id");
        var text = $("#" + call_id).html();
        $("#modal-header").html(text);
        $.getJSON("js/test.json", function(data){
          var paths = [];
          for(var i = 0; i < data.length; i++) {
            if (text == data[i].name) {
              paths = data[i].path;
              break;
            }
          }
          $("#image-place").html("");
          paths.forEach(function(path) {
            $("#image-place").append(
              '<img src="' + path + '" alt="image not found"/>' + '<br>'
            );
          })
        });
          $("#image-place img").load(function () {
              $("#image-modal").modal("show");
          });
      });
      $("#image-modal-closeBtn").click(function() {
        $("#image-modal").modal("toggle");
      })
    });

**Comment by jlukic** [comment]
An images height isnt known until the request returns from the server. So even if you set width like `medium image` does, `height` will still return an incorrect value. 

I think the best solution is to remove requirements for height being calculated for modal. But this means finding a solve that still handles `scrolling modal` correctly, and flexbox styles that work consistently with modal (its not using flex containers yet).

**Comment by David-Tsui** [comment]
CakalSG, it works lol~
Thank you~
