### ISSUE TITLE
Raised button

### ISSUE THREAD

**Issue by filipesarturi** [Semantic-Org/Semantic-UI#3009]
By adding the "raised" button in the theme.config, it is not compiled

**Comment by Nickersoft** [comment]
I can confirm this. The issue seems to also occur for the "chubby" theme, notably on the button and form elements. The gulp file simply stops compiling the CSS once it hits these compilation points. As a result, a partial CSS file is generated.

**Comment by filipesarturi** [comment]
exact

**Comment by Nickersoft** [comment]
If should be noted that this issue was extended upon in #3010

**Comment by jlukic** [comment]
Will be fixed in `next` release later today
