### ISSUE TITLE
[Sticky] - Refreshing content on scrolling back to top.

### ISSUE THREAD

**Issue by klenkovic** [Semantic-Org/Semantic-UI#3011]
**Steps to Reproduce**
1. Open http://semantic-ui.com/modules/sticky.html
2. Press "End" key
3. Press "Home" key

**Expected**
The Sticky should refresh contents of 1st and 3rd columns (rails). 

**Result**
The Sticky does not refresh contents until page is scrolled.
![capture 2015-09-06 at 10 46 09](https://cloud.githubusercontent.com/assets/3192858/9830926/12e55dbe-5942-11e5-83df-40b5fcf48810.png)

**Testcase**
http://semantic-ui.com/modules/sticky.html

**User agent**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

**Comment by rivanvx** [comment]
Can reproduce on Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Does not occur on Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by jlukic** [comment]
I'm unable to reproduce on Chrome/Win. Home/end seem to trigger `scrollchange` event, and everything appears fine.

**Comment by rivanvx** [comment]
@jlukic any chance you could try Chrome in a virtual machine?

**Comment by jlukic** [comment]
I've just tested on Chrome 45 / OS X Yosemite using BrowserStack.com 

Unable to reproduce.

**Comment by rivanvx** [comment]
Just tested on Windows, using Chrome: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

Can reproduce reliably. Open the page, wait until it loads. End, then Home. The elements appear as in the screenshot by @klenkovic and they are interactive (react to hover, links are clickable etc.). Switching to another tab and back doesn't change anything, but resizing the browser window makes the elements reappear in the correct place.

**Comment by rivanvx** [comment]
@jlukic any luck in reproducing?

**Comment by jlukic** [comment]
Yes. I realized my issue was I was using `page down` and `page up` not `end and `home`. These seem to work fine 

Might be something like #15847

**Comment by jlukic** [comment]
Fixed, pretty simple. Sorry about delay
