### ISSUE TITLE
[Segment] Fix 'padded' when used with 'vertical segment'

### ISSUE THREAD

**Issue by iamandrewluca** [Semantic-Org/Semantic-UI#3012]
Moving `.ui.vertical.segment` bellow `.ui[class*="very padded"].segment` would affect also `padded` and `very padded` segments, with this we can create nested padded segments creating something like a master header

before
![before](http://i.imgur.com/UXANlCu.png)

after
![after](http://i.imgur.com/pgVRa4I.png)

```
<div class="ui vertical inverted very padded segment">
    <div class="ui vertical inverted very padded segment">
        <div class="ui vertical inverted very padded segment">
            Lorem...
        </div>
    </div>
</div>
```

**Comment by jlukic** [comment]
Fixed in `2.2.8`
