### ISSUE TITLE
[Menu] - Menu with dropdown does not work

### ISSUE THREAD

**Issue by Jak3b0** [Semantic-Org/Semantic-UI#3013]
**Steps to Reproduce**
Use the code snippet found in the <b>Menu\Dropdown Item</b> [example] (http://semantic-ui.com/collections/menu.html).

**Expected**
Clicking on the item should open the menu

**Result**
The Menu does not open

**Testcase**
https://jsfiddle.net/knogfu7o/1/

**Note**
The <b>Simple</b> menu works...

**Comment by jlukic** [comment]
You're missing any javascript.
https://jsfiddle.net/5jmp6j30/

**Comment by JasonRodman** [comment]
It's not mentioned in the documentation that this is needed. Can you please add it to the docs for everyone else's sake.

**Comment by jlukic** [comment]
http://semantic-ui.com/collections/menu.html#dropdown-item
Has links to the associated docs for dropdown. 

Search and all other javascript components listed in menu are described in their own usage sections.
