### ISSUE TITLE
[Validation] - 'get validation' behaviour doesn't return validation rules for a given field

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3014]
http://codepen.io/avalanche1/pen/oXdQxq

**Comment by jlukic** [comment]
It works your call is just incorrect
http://codepen.io/anon/pen/BojyQR

**Comment by avalanche1** [comment]
I would clarify a lil bit - https://github.com/Semantic-Org/Semantic-UI-Docs/pull/121
