### ISSUE TITLE
Dropdown keypress event for comma key

### ISSUE THREAD

**Issue by lebedev-yury** [Semantic-Org/Semantic-UI#3016]
In many languages the key with keycode "188" (comma in en layout) is used for some letter. For example in russian language this key stands for letter "б".

Unfortunately, the semantic ui dropdown binds an event to this keycode, to separate tags (event for non multiselect fields), which makes typing the letter, assigned to this keycode impossible.

Is there some way to disable, or customize this functionality?

**Comment by fentas** [comment]
Sorry to bring this up again.
I looked into the docs and source code. It seems that this functionality (comma separation) is hard coded.
Or is there a way to disable this? (Even better change it.)

**Comment by jlukic** [comment]
There's a trick with current version, but its super ninja

`
$('.ui.dropdown').dropdown('internal', 'get shortcut keys', return {
              backspace  : 8,
              delimiter  : false,
              deleteKey  : 46,
              enter      : 13,
              escape     : 27,
              pageUp     : 33,
              pageDown   : 34,
              leftArrow  : 37,
              upArrow    : 38,
              rightArrow : 39,
              downArrow  : 40
            }
);

**Comment by tsubaie** [comment]
Dears,

I'm using version 2.2.6 and I still have the same bug.

**Comment by lubber-de** [comment]
It was finally fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2247
