### ISSUE TITLE
Automated code review(codeclimate)

### ISSUE THREAD

**Issue by listepo** [Semantic-Org/Semantic-UI#3017]
I think, it makes sense to connect [this service](https://codeclimate.com/oss) or alternative

**Comment by jlukic** [comment]
We've used this before but it didn't provide any meaningful insights for me.

**Comment by listepo** [comment]
It allows you to monitor the quality of the code and enter the code duplication, this can be done locally, but the service allows checking and PR

**Comment by listepo** [comment]
Locally I use https://github.com/danielstjules/jsinspect and on Semantic-UI he showed not a little duplication of code that is not terrible but not optimal.
