### ISSUE TITLE
[Header] Sub Header inside Header Should Force Display: Block

### ISSUE THREAD

**Issue by scoman81** [Semantic-Org/Semantic-UI#3020]
The icon header examples have invalid HTML markup, as div is not allowed inside an H2 tag, and won't validate.

**Comment by jlukic** [comment]
Don't worry validation is meaningless.

**Comment by scoman81** [comment]
I kind of agree about the validation (personally) but I'm sure some people will have project requirements they have to meet for clients.

Using a span requires some extra markup, because it doesn't do line breaks like a div does. It's easy to do, but I thought I'd mention it due to being another exception to the tag-agnostic approach of SUI. I'm guessing there's a CSS way to make a span work the same as a div in this case.

**Comment by jlukic** [comment]
I think it makes sense to force `display: block` on sub header to allow it to work correctly regardless of tag.
