### ISSUE TITLE
[Dropdown] Multiselect dropdown not allowing easy additions with search

### ISSUE THREAD

**Issue by hsmallbone** [Semantic-Org/Semantic-UI#3025]
I have a dropdown with API settings for searching from a remote endpoint as well as allowAdditions: true. When searching for something that does not exist on the remote I still expect a dropdown to occur while typing with the current input so it can be added easily using enter. At the moment the user has to click the arrow to dropdown and then click their input to add a selection.

**Comment by vinh123456789** [comment]
Hi, i having this same issue too. When user enter something not exist on the remote, sometime the dropdown will display the add selection button, sometime, it doesn't.
This is the test case: http://jsfiddle.net/1fj6cmzd/5/

**Comment by hsmallbone** [comment]
Thanks for that test case @vinh123456789 exactly shows my issue

**Comment by jlukic** [comment]
Hi i'm not sure I understand completely the issue.

I'm seeing that the "Add (X) choice" text in menu appears in dropdown, however the dropdown does appear to scroll to the first remote choice (not user addition) when it shows. 

Is this the bug you're referring to?

**Comment by hsmallbone** [comment]
@jlukic Looks like something has been changed to fix my original issue. The other issue is probably related to https://github.com/Semantic-Org/Semantic-UI/issues/3029 - after clicking 'Add (X)' and then clicking elsewhere, then clicking the multiselect again, the previously added value will still be present in the dropdown when it should have been cleared.

**Comment by vinh123456789** [comment]
@hsmallbone How do you fix that issue? My still the same.
@jlukic I had made a gif using the same test case for you to easy understand.
http://gfycat.com/OldfashionedEllipticalAcornwoodpecker
As you can see, when i type something not exist on remote, sometime the 'Add (X)' text not display immediately, i have to keep typing to make it display. It seem this happend randomly.

I just encounter one more issue using the same test case:
 - Enter something not exist on remote. e.g. '123456'
 - When the dropdown still have focus, click on anything except the jsfiddle 'Result' panel.
 - The dropdown automatically add the entered text as an item.

**Comment by hsmallbone** [comment]
@vinh123456789 not sure, I had your issue last night but today I reloaded the fiddle and 'Add (X)' came up instead of nothing.

**Comment by jlukic** [comment]
@vinh123456789 That's caused because the server hosting our API fails half the time. (502 bad gateway)

We should probably handle the error condition of API call so it still shows user addition message.

**Comment by vinh123456789** [comment]
@jlukic I never received 502 status code in my own local website (using my own local API) and in the jsfiddle test case. The only status code i received is '200 Ok' and '304 Not Modified'.
Can you show me how to handle the error condition?

**Comment by hsmallbone** [comment]
After some investigation I think I have discovered the source of the problem. https://github.com/Semantic-Org/UI-Dropdown/blob/master/dropdown.js#L182 does not check if the list of values received is empty, only if there is a missing value inside the list of results. This should be specified in the docs or changed so that an empty results list prompts the add message to be shown.

**Comment by hsmallbone** [comment]
@vinh123456789 I'm still having this issue, even after trying to match the fiddle exactly. I am testing with 200 OK responses. The only thing is that I use <select> syntax instead of <div> syntax, but that shouldn't matter.

**Comment by hsmallbone** [comment]
I found the cause of my issue finally - user error. I had showOnFocus set to false.
