### ISSUE TITLE
Transition callback is not firing.

### ISSUE THREAD

**Issue by v3rron** [Semantic-Org/Semantic-UI#3028]
For some weird reason, the "pulse" animation doesn't trigger any callback events except onStart.

http://jsfiddle.net/n5082rka/2/

In this example try to click on ellipsis circle and see that callbacks aren't triggered.
However if you change the animation to "scale", then it works as expected. Haven't tried it with other animations though, so I don't know exactly how many transitions are affected by this bug.

How do we trigger the callback after animation ended in this case?

**Comment by avalanche1** [comment]
I guess, pulse animation doesn't produce other callbacks. Because other animations work just fine.
