### ISSUE TITLE
dropdown restore defaults do not restore the default text

### ISSUE THREAD

**Issue by doubledaibo** [Semantic-Org/Semantic-UI#3033]
Hi,
 I use
    $("#city-searcher").dropdown('restore defaults');
to reset the dropdown it's initial state but it does not set the default text to original value, instead it just turns current value to gray color.

Thanks.

**Comment by doubledaibo** [comment]
The code looks like
<div  id = "province-searcher" class="ui selection search dropdown">
  	<input name="search-province"/>
	<i class="dropdown icon"></i>
  	<div class="default text">province</div>
</div>

It dose not set to "default text" to original value

**Comment by jlukic** [comment]
Please fork the jsfiddle in the readme to create a test case.

**Comment by doubledaibo** [comment]
Using the latest version solve the issue.
