### ISSUE TITLE
[Sidebar] Remove References to Duration

### ISSUE THREAD

**Issue by norn** [Semantic-Org/Semantic-UI#3034]
The following code has no effect:

``` javascript
$('.ui.sidebar').sidebar('setting', 'duration', 0).sidebar('toggle');
```

I checked the sidebar.js and found that duration variable is not used at all, except of default declaration of 500.

**Comment by jlukic** [comment]
Duration should be removed from docs. this applied to when fallback animations used javascript. 

The transition duration is set in css now, and can be edited using css variables, but is not available in javascript.
