### ISSUE TITLE
Disable automatic update

### ISSUE THREAD

**Issue by fstanis** [Semantic-Org/Semantic-UI#3035]
We have `semantic-ui` in our `package.json` and every time we do a full clone of our repo and `npm install`, Semantic UI automatically updates its version. This is not always desirable, as we fear it might break things for us sometimes, so is there any way to disable this auto-update process when doing `npm install`?

**Comment by jlukic** [comment]
You need to specify the version of Semantic UI you want to include in your package.json check www.npm.org for more info on how to do this.

**Comment by fstanis** [comment]
Great - thanks. I didn't notice our version string had a caret in it, making it update every time.
