### ISSUE TITLE
[Progress Bar] "reset" and "complete" doesn't work correctly

### ISSUE THREAD

**Issue by kevinptt0323** [Semantic-Org/Semantic-UI#3036]
http://jsfiddle.net/2yw95z8u/2/
As example, call "increment/decrement" after "reset/complete" doesn't work correctly.
"Reset" and "complete" only set the percent of progress bar, but do not set the value of it.

**Comment by jlukic** [comment]
Although in some cases it would make sense to save progress, this doesnt seem to be one of those cases.

**Comment by kevinptt0323** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/progress.js#L90
Because it only sets percent to 0.

**Comment by jlukic** [comment]
Sorry for the delay.
