### ISSUE TITLE
List description gets layout break

### ISSUE THREAD

**Issue by geodeveloper** [Semantic-Org/Semantic-UI#3037]
Hi,

I've used the List mark-up and I get the layout broken (the header and descriptions goes below the image) when the description is too long. Well, the issue appears when the text goes on new line. See screenshot: https://i.imgur.com/qacuw8E.png

**Comment by jlukic** [comment]
Can you provide a test case (fork jsfiddle in readme)

**Comment by geodeveloper** [comment]
Hi @jlukic . Here you have the test case:

https://jsfiddle.net/nq0kpo66/

**Comment by jlukic** [comment]
Use `<div class="ui image">` wrappers around `img` to fix this. 

`img` with content swaps back to `inline-block` because `img` will stretch in awful ways when using `display: table-cell`

http://jsfiddle.net/3f95gwx2/

**Comment by geodeveloper** [comment]
Great. Thank you.
