### ISSUE TITLE
Small error on Container Example page

### ISSUE THREAD

**Issue by rmstinson** [Semantic-Org/Semantic-UI#3038]
Hello,

On the Container Example page, (http://semantic-ui.com/elements/container.html#/examples), the class "ui four column doubling grid container" in the example code should be "ui four column doubling stackable grid container". (stackable was left out)

Thanks very much, love your work.

**Comment by jlukic** [comment]
Thanks for the catch!

**Comment by rmstinson** [comment]
No problem! Very new to front-end work, task runners, and Semantic-UI has
been a great way to learn. Thanks!

On Tue, Sep 15, 2015 at 6:33 PM, Jack Lukic <notifications@github.com>
wrote:

> Thanks for the catch!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/3038#issuecomment-140594514>
> .
>



-- 
517 750 7427

**Comment by jlukic** [comment]
Fixed
