### ISSUE TITLE
[Search] No results dialog message not being dismissed if it's clicked

### ISSUE THREAD

**Issue by jeff3yan** [Semantic-Org/Semantic-UI#3039]
If an API search is performed where there are no results, a _no results_ message pops up. After this popup appears, it can be dismissed by clicking anywhere on the page.

However, if the popup message itself is clicked after it appears - then it does not dismiss even after trying to click around on the page. Only if the search text field is refocused, and another search performed, does it finally dismiss.

**Comment by jlukic** [comment]
Although you didnt provide a test case this is clear enough to see as an issue in the docs.

**Comment by jlukic** [comment]
I've modified how input blur handles closing results.

Previously it would just look for a mousedown event on search results to assume that the results have been clicked, and that an action occurring there should decide whether results should close.

Now it sets a one type event to wait for `click` to bubble from results and determine if the click action actually makes the results close.
