### ISSUE TITLE
Important in css

### ISSUE THREAD

**Issue by nadimtuhin** [Semantic-Org/Semantic-UI#3041]
I see lots of important in css. Is it not considered an antipattern? Making it hard to overwrite.

**Comment by jlukic** [comment]
Please check my other threads where I've posted on this. CSS should have a specificity property for defining priority (it was part of the original discussion when creating css), however they left us with automatic weight calculations from an arbitrary point system. 

This is pretty terrible when you run into something that happens to be classified less ".ui.button" lets say, having to override '.ui.menu .ui.button' , there are only two solutions, arbitrarily increasing weight by repeating class names in selectors, or using important. 

I hope someday they resolve this by allowing a weight to be specified in the same vein as z-index. But this is currently not the case.
