### ISSUE TITLE
inverted menu no top-left border radius

### ISSUE THREAD

**Issue by fedot1325** [Semantic-Org/Semantic-UI#3048]
Here that little bastard:
https://gyazo.com/36b02b7578bdfd24ea96cb5457ab76d9
https://gyazo.com/fcac1cd9d9d41eb21872a3b61f5abcb1
To fix: 
before - ui.vertical.menu>.active.item:first-child{border-radius:0 .28571429rem 0 0}
after - ui.vertical.menu>.active.item:first-child{border-radius:.28571429rem .28571429rem 0 0}

**Comment by jlukic** [comment]
I'm not seeing this issue in the docs. Are you using the latest version?

**Comment by avalanche1** [comment]
Closing until there's a test case.
