### ISSUE TITLE
[Popup] borderColor less compilation error

### ISSUE THREAD

**Issue by veke** [Semantic-Org/Semantic-UI#3050]
Site.variables has @borderColor variable.

theme/default//modules/popup.variables is using the same and the default value is solidBorderColor.
If you want transparent borderColor used in popup (denined in site.variables) you get less compilation error.

site/modules/popup/popup.variables

@borderColor: @borderColor;

[Error: Recursive variable definition for @borderColor in file semantic/src/site/modules/popup.variables

**Comment by jlukic** [comment]
You are doing a recursive definition since @borderColor (the global value) has been rewritten in the component scope. You'll need to reference the variable in some other way.
