### ISSUE TITLE
Website theming doesnt work

### ISSUE THREAD

**Issue by lashae** [Semantic-Org/Semantic-UI#3054]
On semantic-ui.com theming doesnt work. 

To reproduce:

1. Go to http://semantic-ui.com/
2. Scroll down to "Unbelievable Theming" section.
3. Choose one the themes from the theme selection combo.

Console output is attached.

ps: Perhaps this issue should not be posted here, however I couldn't find `Semantic-Org/Semantic-UI-Website` repository.
![screen shot 2015-09-18 at 09 12 28](https://cloud.githubusercontent.com/assets/20574/9953017/8776c3be-5de5-11e5-9ab4-53994ae75286.png)

**Comment by jlukic** [comment]
Woah, thanks. Looks like a bad deploy

**Comment by jlukic** [comment]
Redeployed and all fixed. Thanks for taking the time to report this, it's very much appreciated.

**Comment by lashae** [comment]
You're welcome!
