### ISSUE TITLE
Video Fullscreen on Modal

### ISSUE THREAD

**Issue by markpolarisdesign** [Semantic-Org/Semantic-UI#3055]
I love SemanticUI ♥ but I have problem about video fullscreen on modal.

**Before click fullscreen**
![2015-09-18_13-26-29](https://cloud.githubusercontent.com/assets/13967962/9953203/ea740652-5e08-11e5-8505-ef94d563048e.jpg)

**After click fullscreen ( video not show )**
![2015-09-18_13-26-35](https://cloud.githubusercontent.com/assets/13967962/9953202/ea6fe018-5e08-11e5-85a0-ed405e23af5d.jpg)

How to fix ? please

**Comment by jlukic** [comment]
Perhaps related to using blurred modal?

**Comment by nicely** [comment]
no its not about blur , i still triyng to solve problem , it's occurs this issue on google chrome browser

**Comment by bonnici** [comment]
+1 I'm running into this issue. It seems to happen for all embeds within a modal  (youtube/vimeo/custom), even if I avoid using the modal component and just put the iframe div in manually. Page content goes above the fullscreen video somehow.

Here is a simple page that will show the problem:

```
<!doctype html>
<head>
    <title></title>

    <script src="//code.jquery.com/jquery-2.2.1.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.css">

    <script>
        $(document).ready(function() {
            $('.ui.button').click(function() {
                console.log('test');
                $('.ui.modal').modal('show');
                $('.ui.embed').embed({ autoplay: true });
            });

        });
    </script>
    <style type="text/css">
        .ui.button {
            margin: 10em;
        }
    </style>
</head>
<body>

<div class="ui button">Show modal</div>
<div class="ui fullscreen modal">
    <i class="close icon"></i>
    <div class="content">
        <div class="ui embed" data-source="vimeo" data-id="125292332"></div>
    </div>
</div>

</body>
</html>
```

**Comment by jlukic** [comment]
Can you please create a jsfiddle. There's a link to fork in the readme

**Comment by bonnici** [comment]
Looks like the jsfiddle result section is itself in an iframe that doesn't allow fullscreen, so the fullscreen button doesn't show up. You can still see it if you use dev tools to add the allowfullscreen attribute to the iframe manually here: http://jsfiddle.net/bonnici/sqwgLe60/ . I also made a jsbin which allows the output to be directly shared: https://output.jsbin.com/jijadojayi .

**Comment by igorrarruda** [comment]
+1

**Comment by drisschelouati** [comment]
Iam developping a site with Semantic UI 2.1.8 and i ran through the same problem as the initial screenshot, only with google Chrome. Works with Firefox and IE. I tried inserting the modal in an additionnal `<div class="ui container">`, without success. Also tried to play with z-index without results (webkit fullscreen z-index is already at a very high value). Can we have a fix (or a hack until there is a real fix) for this as it can be really critical for sites that rely on video embeds?

**Comment by markpolarisdesign** [comment]
Now i use colorbox. It's work for Video Modal
http://www.jacklmoore.com/colorbox/example5/

**Comment by igorrarruda** [comment]
@markpolarisdesign bootstrap modal also works
http://getbootstrap.com/javascript/#modals

**Comment by bcbane** [comment]
I was able to fix this by overriding the css will-change property for the modal to not contain transform.  I added this to my own css:
```
.ui.modal{
    will-change:top, left, margin, opacity;
}
```

The semantic ui value for the whole thing is:
```
.ui.modal {
    display: none;
    position: fixed;
    z-index: 1001;
    top: 50%;
    left: 50%;
    text-align: left;
    background: #ffffff;
    border: none;
    box-shadow: 1px 3px 3px 0px rgba(0, 0, 0, 0.2), 1px 3px 15px 2px rgba(0, 0, 0, 0.2);
    -webkit-transform-origin: 50% 25%;
    -ms-transform-origin: 50% 25%;
    transform-origin: 50% 25%;
    border-radius: 0.28571429rem;
    -webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    user-select: text;
    will-change: top, left, margin, transform, opacity;
}
```

**Comment by drisschelouati** [comment]
Will try that and get back to you! Thanks for the effort!

**Comment by shalomeir** [comment]
I have a same problem. @bcbane css snippet did not working for me. Is there any kind of trick at all?;
