### ISSUE TITLE
Progress with zero items

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#3056]
I found the following unaspected behaviour after generated some progress bars dynamically. If the total count is 0, the bars behaves a bit weird:
instead of completing automatically it stays in unfinished state and if you increment the progress it actually increments randomly.
This might be the reason of the `random` setting but I think it's not the expected behaviour.

Example here: http://jsfiddle.net/svyh9452/1/

**Comment by jlukic** [comment]
Probably some sort of divide by zero.

**Comment by jlukic** [comment]
This is not a bug, if you set `total` to `0` it will use the random increment, decrement hops specified in the settings object.

**Comment by larsbo** [comment]
But why should it work randomly at all? The only feasible use case I can think of would be an example like in the docs but no real application. 
My semantic interpretation of a progress with 0 steps (left) should be completed and not randomly move forward. 
Just my two cents :smiley:

**Comment by jlukic** [comment]
Showing fake incremental progress can be used with indeterminate loading to simulate progress.

**Comment by larsbo** [comment]
ok, even though a bit special :)
Maybe the random progress should be bind to a ```random``` or ```simulation``` setting to make this clear?

**Comment by lubber-de** [comment]
We now fixed the behavior for 0 total values in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1567
The random increments should only take place when the total value is really not even set, wich is only the case by `false`  for the setting, or `undefined` for a non existing `data-total` attribute. The progress module did not differ between 0 and false/undefined
