### ISSUE TITLE
[Sidebar] Remove Reference to Support Multiple Push

### ISSUE THREAD

**Issue by iPaoo** [Semantic-Org/Semantic-UI#3057]
Hi

Not sure it is an issue or a misunderstood from myself, but it seems Multiple slider does not work in push mode. On the http://jsfiddle.net/Greggg/57zhz7py/1/  content is hidden by the top and left sliders. Clic on Entre Preview button to see them.

Regards
Greg

**Comment by jlukic** [comment]
This is specified in docs as a limitation, generally the css transition system isn't equipped to handle multiple element animations at same time.

**Comment by ZeGregg** [comment]
Hi 

The documentation advice to use overlay and recommend to set the transition to overlay. Nothing about  a limitation !

*Multiple sidebars can be displayed at the same time only when using a supported animation like push or overlay.*

Do you expect to allow Push or is there any turn around?

Thanks

**Comment by ZeGregg** [comment]
Here is a full CSS example on what it would be nice to do with Semantic Slider http://codepen.io/anon/pen/avNMYL

**Comment by jlukic** [comment]
You're right, the documentation is incorrect. However i can confirm its not supported

The 3dtranslate values are determined dynamically based on your sidebar's content size. This matrix does not support automatically generation for multiple sidebars.

**Comment by ZeGregg** [comment]
Hi Jack,

Do you think you will be able to find a solution in future release, or is there any chance to see multiple sliders working with push?

**Comment by jlukic** [comment]
This is not a high priority given the other roadmapped features for the project.
