### ISSUE TITLE
[Form Validation] Focus on first invalid field after validation

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#3059]
Does the validation api have a setting to focus on the first invalid field? 

Currently, when the form is validated no invalid field is focused.

``` javascript
$('.ui.form') .form({ focusInvalid: true });
```

Can this be done with `onFailure`?

``` javascript
onFailure: function(formErrors, fields){

});
```

**Comment by kmd1970** [comment]
Can we add focus() on first error or scroll to first error (handles hidden selects)? 

This example does focus() and scroll to first error field. (centers error in window)

https://jsfiddle.net/kmd1970/Ly0gx6bo/

Also, onFailure() callback should include first error field, example (formErrors, fields, firstErrorField) or only include fields that have errors.

**Comment by arist0tl3** [comment]
For anyone else looking for a solution here:

(This relies on inline errors)

```
onFailure: function (event, fields) {
        let elem = $('.ui.red.prompt:first').siblings('input');
        $('html, body').animate({scrollTop: $(elem).offset().top -100 }, 'slow', function () {
          $(elem).focus();
        });
      },
```

**Comment by jlukic** [comment]
I think it makes sense to add this as a setting.

**Comment by dopeboy** [comment]
Thanks @arist0tl3 - this is helpful and I'm using it. I noticed it doesn't work on checkbox fields. This is because the `input` tag is within a div and therefore not a sibling to the inserted prompt. I added this after your `let` statement to get it working:

```
if (elem == null || elem.length == 0) {
    elem = $('.ui.red.prompt:first').parent().find('input');
}
```

**Comment by kmd1970** [comment]
As of 2.2.8 this can be done with:

```javascript
onFailure: function(formErrors, fields){
  for (field in fields) {
       if( !$('.ui.form').form('is valid', field) ) {
             $('#'+ field).focus();
	     break;
       }
  }
   return false;
}
```
or
```javascript
onFailure: function(formErrors, fields){
  for (field in fields) {
       if( !$('.ui.form').form('is valid', field) ) {
             let elem = $('#'+field);
	     let dv = elem.closest('.field');
              $('html, body').animate({scrollTop: dv.offset().top - ( $(window).height() - dv.outerHeight(true) ) / 2 }, 'slow', function () {
                 elem.focus();
             });
	     break;
       }
  }
   return false;
}
```

**Comment by behouba** [comment]
This worked well for me, version 2.4.2
`onFailure: function (formErrors, fields) {
            for (field in fields) {
                console.log(field)
                if (!$('.ui.form').form('is valid', field)) {
                    let elem = $('.ui.form').form('get field', field)
                    let dv = elem.closest('.field');
                    $([document.documentElement, document.body]).animate({
                        scrollTop: dv.offset().top
                    }, 500);
                    return false;
                }
            }
            return false;
        },`

**Comment by behouba** [comment]
This worked well for me (version 2.4.2)
```
onFailure: function (formErrors, fields) {
            for (field in fields) {
                console.log(field);
                if (!$('.ui.form').form('is valid', field)) {
                    let elem = $('.ui.form').form('get field', field);
                    let dv = elem.closest('.field');
                    $([document.documentElement, document.body]).animate({
                        scrollTop: dv.offset().top;
                    }, 2000);
                    return false;
                }
            }
            return false;
        }
```
