### ISSUE TITLE
No difference between number and decimal field validation rules

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3060]
Hi,

Seems like there's no difference between `number` and `decimal` field validation rules.

For now it seems that the regular expression evaluating them is the same:

```
regExp: {
    . . .
    decimal : /^\-?\d*(\.\d+)?$/,
    number  : /^\-?\d*(\.\d+)?$/,
    . . .
},
```

**Comment by jlukic** [comment]
Decimal should probably *require* a decimal. This came from a PR i didnt evaluate carefully enough i guess.

**Comment by andreyvk** [comment]
I see now. Thanks!

**Comment by jlukic** [comment]
Fixed
