### ISSUE TITLE
prompt label transition changes label location 

### ISSUE THREAD

**Issue by amitos80** [Semantic-Org/Semantic-UI#3067]
hi

in my form i user inline: true, transition: 'slide up', 
the expected behaviour is the reverse animation upon passing validation.

the actual behaviour is that the prompt is pushed to the right side of the input and then removed.
can be seen in the video: http://goo.gl/akw04C

i searched for the place in semantic.js that handles the prompt removal and found that if i replace this (line 1074):
```
$prompt.transition(settings.transition + ' out', settings.duration, function() {
    $prompt.remove();
});
```
with just this:
```
$prompt.remove();
```
it solves the problem though i'm sure its not a good solution.
so its something to do with the transition that changes the prompt position/location on screen when applied.

any ideas on how this can be solved?

**Comment by jlukic** [comment]
It looks like this may be something particular to your layout. Slide up should generally not affect positioning.

**Comment by avalanche1** [comment]
Closing because no test case.
