### ISSUE TITLE
[Menu] "labeled icons" to "icons" on mobile

### ISSUE THREAD

**Issue by genofire** [Semantic-Org/Semantic-UI#3068]
It would be really nice, to implement a option like this:
If the mobile size is reached that the label would disappear of a icon labeled menu item
On this way the icon is only shown and the menu content is smaller
(sometime it will fit into one line)

**Comment by IonutBajescu** [comment]
Closing this since there's little interest in this feature from the community. If you think this is a mistake, feel free to reopen.
