### ISSUE TITLE
Feature suggestion: dropdown's could add an "onCreateNew" option?

### ISSUE THREAD

**Issue by xiechao06** [Semantic-Org/Semantic-UI#3069]
when a dropdown has option "allowAdditions" set to "true": I need to tell if a newly created selection is added or an existing selection, and more importantly, I need a way to ** control the actually added value/text ** (for example, I need to create a new student, and the addedValue is the student's id, and the student's name should be capitalized).

so instead of: 

```javascript
$('.ui.dropdown').dropdown({
    allowAddtions: true,
    onCreate: function (addedValue, addedText, $chioce) {
        if ($chioce.hasClass('addition')) {
          console.log('newly created selection');
        } else {
          console.log('existing selection');
          $.ajax(...).done(function (rsp) {
              // HOW COULD I CHANGE THE ADDED VALUE?
          });
        }
    }
});
```

I think this way is better:

```javascript
$('.ui.dropdown').dropdown({
    allowAddtions: true,
    onCreate: function (addedValue, addedText, $chioce) {
        console.log('existing selection');
    }, 
    onCreateNew: function (addedValue, addedText, $chioce) {
        console.log('newly create selection');
        var d = $.Deferred();
        // creat a new object
        $.ajax(...).done(function (rsp) {
            d.resolve([rsp.id, rsp.name]);
        });
        return d; 
        // or just return a new [id, value] if you just need synchronous operations
    }, 
});
```

Thank you very much!

**Comment by ubald** [comment]
Where did you get that ```onCreate``` option? The documentation says ```onAdd``` and even ```onAdd``` doesn't seem to work for me.

**Comment by jlukic** [comment]
This is over complicating, it's easy enough tO control the added text and values with metadata `data-text`, etc.

You can also use a custom `action` setting to trick out something more complex, for example a drop down choice that adds multiple values at once.
