### ISSUE TITLE
dropdown broken ?

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#307]
It look like something is broke with the last version.
i'm getting this error when clicking on every dropdown :
"Transition: There is no css animation matching the one you specified."

I don't know exactly if I'm doing something wrong because : 

-> when I use the packaged version , it's OK (was it built?)
-> but when I manually include the JS and less files it's broken.

I though I may have included the files in a wrong order, so I made a try with the @nd0ut 's gem https://github.com/nd0ut/semantic-ui-rails but I'm getting the same problem with it.

**Comment by hungryzi** [comment]
@deneuxa I think I'm having the same problem right now.  I tried including SemanticUI less and JS manually and transitions gave me the same error "Transition: There is no css animation matching the one you specified."

After reading this thread, I don't understand what caused it.  Could you please give me more details on how you fixed yours? Thanks!

**Comment by hungryzi** [comment]
@deneuxa, nevermind, I added autoprefixer gem and it works fine now :)  It wasn't clear to me that autoprefixer was needed.
