### ISSUE TITLE
[Tab] Feature request: scrollable tabs

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3076]
Hi,

**Problem**: too many tabs on the screen will hide some of the tabs that fell out of the screen width. Currently it is not possible to access those tabs at all.

**Possible Solutions**

- Have arrows appear on the left or the right of the tab menu, once cumulative tabs width exceeds the screen width. Below is an example:

![scrollabletabs](https://cloud.githubusercontent.com/assets/1415506/10021779/75e3ca64-616b-11e5-8c8a-268aad650d97.png)

- Group least used "out-of-screen" tabs into a dropdown at the end of the tab menu. Here's a quick mockup:

![tabswithdropdown](https://cloud.githubusercontent.com/assets/1415506/10022011/8306e766-616c-11e5-9940-4ba68aa1c7b2.png)

- Both of the above configurable using tab settings

**Comment by ph7vc** [comment]
I suppose it depends on the usecase for your tabs; I believe that it was designed to be used in static menu situations; and I would argue that if you have too many tabs; you could refactor your UI to incorperate that differently.

That being said; I think this would be a good excuse to make a carousal module, which could be used on tabs as well but could also serve the traditional role of presentation

**Comment by jlukic** [comment]
I think if you have more than the available tab width, you should consider a separate UI pattern like a dropdown, or a site-specific code solution to resizing or allowing scrollable overflow.

**Comment by andreyvk** [comment]
@jlukic, there's nothing site-specific about not being able to see tabs. While in my project we deal with at least 1024px-wide screen resolutions, the problem will become very commonplace with mobile devices and everyone will have to implement boilerplate code for handling "hidden" tabs.

Please consider adding this as an enhancement somewhere down the line. Thanks

**Comment by dev-fullstacktechnology** [comment]
Hello, I have six tabs on my page. But when I switched on the tablet view have a width of 1024px, It will staring to overflowing. I previously posted my issue on ng2-semanti-ui, but since it is an issue of design I am looking for a solution. I used this.

**Comment by salazarm** [comment]
An easy solution that Semantic UI could support would be to simply allow you to pass a wrapper container for the tab menu div. That way I can just set the wrapper to `overflow-x: scroll` for my particular case. It would open up a lot of flexibility too.
