### ISSUE TITLE
[Form] The Float Label Pattern

### ISSUE THREAD

**Issue by listepo** [Semantic-Org/Semantic-UI#3077]
Hi, it would be very convenient to have floating labels
examples: 
http://bradfrost.com/blog/post/float-label-pattern
http://codepen.io/simoberny/pen/gpddYQ
https://css-tricks.com/float-labels-css
http://mds.is/float-label-demo

**Comment by jdrago999** [comment]
Would you be willing to take a shot at it with a codepen yourself? Once started, perhaps others can begin to contribute.

**Comment by avalanche1** [comment]
Moving it to https://github.com/Semantic-Org/Semantic-UI/issues/3965
