### ISSUE TITLE
Custom build for development

### ISSUE THREAD

**Issue by Ganwel** [Semantic-Org/Semantic-UI#3079]
In a dev environment, building, compressing, concatenating, adding comment, etc.. for each changes is not optimal. Especially if semantic-ui is only a part of a wider system. There should be a way to choose to build/watch only for local development purpose.

**Comment by jlukic** [comment]
Precompiled `Dist/` files are always available to use directly. Build/compile/watch is available only if theming is necessary.

**Comment by Ganwel** [comment]
Thx for your answer.
Unfortunately we can't really use the precompiled files in dist/. For our team, semantic is just a part of a wider system. Therefore we can't just use a packaged theme and we need to make adjustment for every components. So we are using the variable and override files to custom our theme. And this is working great for us because we just have to change few things to make it compliant to the graphic project. But building the whole packaged (maven build) the target folder is cleaned first and then we need to build every part of the system, so semantic as well. When working on the front end, it would be nice to have an optimized build that would just build what we need to see the changes.
We have made this custom build and are looking forward what do you think about it.

**Comment by jlukic** [comment]
Use semantic-ui-less repo, that just has the source less files. There's lots of options here
