### ISSUE TITLE
[Dropdown] Query remote for dropdowns using custom values key

### ISSUE THREAD

**Issue by bradbird1990** [Semantic-Org/Semantic-UI#3080]
I'm working with remote query dropdown lists and I've noticed that the custom field key setting for values is not working... It gets completely ignored in fact. I don't know the Semantic UI codebase well enough to issue a pull request and I might break other things but perhaps someone else can fix it?

Example... Setting the field keys.

```javascript
$('.ui.dropdown').dropdown('setting', {
    apiSettings: {
        url: '<api_url>',
    },
    fields: {
        values: 'results', // Custom set result key
        name: 'name',
        value: 'id'
    }
});
```

In the combined semantic-ui.js file on line 4778. The code currently looks like this.

```javascript
onSuccess : function(response) {
  module.remove.message();
  module.setup.menu({
    values: response.results // This is HARD CODED to results. Should take value from custom defined key
  });
  callback();
}
```

Let me know if this needs explaining further or if I'm wrong... I've hacked the code to work for me now.

**Comment by johnschult** [comment]
It looks like this might be fixed on `master`:

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3388

However the `values` variable is never used...

**Comment by jlukic** [comment]
Original poster is correct, this is hard coded and shouldnt be.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L669

**Comment by infofarhadrahimi** [comment]
$('#DrDwName').dropdown({
        allowAdditions: true,
        hideAdditions: false,  
        allowReselection: true, 
        selectOnKeydown: false,
        apiSettings: {
            url: '',
            cache: true,
            method: 'POST',
            beforeSend: (settings) => {
                var text = $('#DrDwName input.search').val();
                if (text == '')
                    text = $('#DrDwName').dropdown('get text');
                text = text.split(',')[0].split('،')[0];
                settings.data = {
                    term: text,
                }
                return settings
            }
        },
        fields: {
            name: 'NameField',
            value: 'NameField',
            text: 'NameField'
        },
        onChange: function (value, text, choice) {
            if (isInteger(value)) {
                var val = $(choice).html();
                $(this).dropdown('set text', val);
                $('#Dist_TextBox').val(value);
            }
        }
    });

**Comment by infofarhadrahimi** [comment]
` $('#DrDwName').dropdown({
        allowAdditions: true,
        hideAdditions: false,  
        allowReselection: true, 
        selectOnKeydown: false,
        apiSettings: {
            url: '',
            cache: true,
            method: 'POST',
            beforeSend: (settings) => {
                var text = $('#DrDwName input.search').val();
                if (text == '')
                    text = $('#DrDwName').dropdown('get text');
                text = text.split(',')[0].split('،')[0];
                settings.data = {
                    term: text,
                }
                return settings
            }
        },
        fields: {
            name: 'NameField',
            value: 'NameField',
            text: 'NameField'
        },
        onChange: function (value, text, choice) {
            if (isInteger(value)) {
                var val = $(choice).html();
                $(this).dropdown('set text', val);
                $('#Dist_TextBox').val(value);
            }
        }
    });
`
