### ISSUE TITLE
Bower Webjar deploy issue

### ISSUE THREAD

**Issue by drumonii** [Semantic-Org/Semantic-UI#3082]
Unable to deploy the latest semantic-ui using the self deploy on [Bower WebJars](http://www.webjars.org/bower). 
```
Failed!
License at http://semantic-ui.mit-license.org/ was not plain text
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: semantic
Starting Deploy
```
The issue is the license is in a webpage and not plain text. See @jamesward 's comment about the issue [here](https://github.com/webjars/webjars/issues/1195#issuecomment-142609690). Is it possible to convert the webpage to text? Perhaps redirect to the actual license text like [tinymce](https://github.com/tinymce/tinymce-dist/blob/master/bower.json)'s license webpage?

**Comment by jamesward** [comment]
The root of the problem is that the license can't be programmatically determined.  An easy solution is to change the `bower.json` to use a SPDX identifier like the `package.json` does.

**Comment by jlukic** [comment]
I've modified the bower.json license, should this help?

**Comment by jamesward** [comment]
Thanks!  As soon as there is a new release a Bower WebJar can be created using the updated metadata.
