### ISSUE TITLE
[Icon] - Word casing

### ISSUE THREAD

**Issue by nmaxcom** [Semantic-Org/Semantic-UI#3083]
All the icons are named with capitalized words, even though for them to work they have to be all lowercase.

You show it correctly in the code section, but that's something you have to click on. 

I think it's misleading and uncomfortable to not being able just to copy paste from the icon's name.

Thank you for this amazing framework!

**Comment by jlukic** [comment]
I understand your sentiment but I think I prefer the sentence casing.

**Comment by nmaxcom** [comment]
Would you mind elaborating so I can understand willingly havingly a UX
deficiency with the easiest fix ever?

Thanks Jack.
