### ISSUE TITLE
[Dropdown] - fullTextSearch: true does not properly filter values

### ISSUE THREAD

**Issue by jaimehing** [Semantic-Org/Semantic-UI#3085]
**Expected**
I was expecting being filtered here are 
ANC - Acta Numerica
DRJ - Dance Research Journal

**Result**
Please see screenshot:
![snip20150924_1](https://cloud.githubusercontent.com/assets/6761602/10066614/54d03f8a-62c7-11e5-8782-ec41faafced8.png)

I think the search dropdown doesn't filter the exact values you've typed anywhere from the string. 

P.S. I'm filtering via text and not via values.

**Comment by scoman81** [comment]
Not sure if you just typo'd in the title or not, but the setting value is "searchFullText" not "fullTextSearch"

**Comment by jaimehing** [comment]
Hi,

this is what I'm seeing from your documentation:

![snip20150924_2](https://cloud.githubusercontent.com/assets/6761602/10068471/3a25f7be-62d7-11e5-84c6-4a401c01346b.png)

**Comment by furins** [comment]
same issue here (SUI 2.1.4). 

I confirm that the correct setting should be "fullTextSearch": "searchFullText" is meant for `search` components. This double wording be also the cause of the problem, by the way.

another setting that is not taken in account, apparently is `match`.
here is my code (sortSelect works, I've added this setting just to be sure that the dictionary is parsed) :

	$('#id_element').dropdown({fullTextSearch:true, sortSelect: true, match:'text'});

in my example code the actual result is a select tag converted into a searchable dropdown, with sorted options that are searched (erroneously, apparently) both for values and text and only at the beginning of the string.

**Comment by scoman81** [comment]
You're right - I was looking at the search code, not the dropdown code. My mistake! 

The option naming isn't consistent, and the fuzzySearch() function is confusing as all get-out, but my first inclination is that considering how amazing the rest of this library is, the author must have their reasons. Hopefully he'll comment at some point.  (I'd be super interested to know why .indexOf() isn't good enough after forcing case.)

**Comment by jlukic** [comment]
The naming difference between dropdown/search `fullTextSearch` and `searchFullText` was a mistake. But unfortunately you get stuck with those for backwards compatibility. 

I might consider adding a setting alias and removing in `2.0`.

Fuzzy search is an algorithm designed to return results even with common input mistakes.

**Comment by jaimehing** [comment]
so @jlukic, what can you suggest to solve my issue?

**Comment by jlukic** [comment]
This is the intended behavior with full text search. 

> The method will return true only if each character in the needle can be found in the haystack and occurs after the preceding matches.

**Comment by furins** [comment]
@jlukic ok for the `match` setting, I'll do it.

but still I have the issue with fullTextSearch (fuzzy). It does not seems to search the way you described, it search only at the beginning of the string. (in search components fuzzysearch algorithm works as expected). Now I'm at work so I cannot prepare a full test case/example. I'll try to do it tomorrow.

**Comment by jaimehing** [comment]
hi @furins do you have updates on implementing fullTextSearch exact or fuzzy?

**Comment by daneren2005** [comment]
It has been over a year since this was first opened.  Is this every going to be merged into master so we can actually use this?  The fuzzy matching is fairly flawed and really all I want is similar to those commits where it does a lower case match.

**Comment by daneren2005** [comment]
Ignore my earlier comment.  It appears that it already has been merged (though I'm not sure when).  It appears to only work correctly if `match: 'text'` even when there is no value attribute on the options:

http://jsfiddle.net/daneren2005/efp8z6Ln/400/
Type in `108910` and it filters correctly.  Comment out `match: text` and try it again and it doesn't filter correctly.
