### ISSUE TITLE
[Dropdown] - Selects a value when you ctrl + tab to another tab of browser

### ISSUE THREAD

**Issue by jaimehing** [Semantic-Org/Semantic-UI#3086]
**Steps to Reproduce**
1. Create a search dropdown with multiple selection
2. Focus on the search box of dropdown.
3. Type something that will make sure at least there are choices from your filter
4. Change browser tab by pressing ctrl + tab

**Expected**
If you go back to your application tab, no values selected since you didn't select anything

**Result**
Dropdown selects the first value of your options

P.S. Not sure if this happens as well with single selection

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by vinh123456789** [comment]
@jaimehing I don't see any dropdown in your testcase. But by what you had said, i think you can add "forceSelection: false" to dropdown to prevent this issue.

**Comment by jaimehing** [comment]
That explains it! thanks!
