### ISSUE TITLE
[Tab] tab.onFirstLoad fires multiple times

### ISSUE THREAD

**Issue by scoman81** [Semantic-Org/Semantic-UI#3087]
https://jsfiddle.net/vdff7xep/

tab.onFirstLoad is called multiple times when using tab.tab('change to', 'path'). When executing this command, you'll get the same number of callbacks through onFirstLoad() as you have tabs, yet each time the path parameter is the same (the one used in the command). If you don't use the change to command, then clicking on the tabs works as expected, with a single call through onFirstLoad for each clicked tab.

My intention is to use onFirstLoad to initialize the data in each tab segment on user demand.

**Comment by jlukic** [comment]
Technically you are calling `change tab` three times, because each `item` is invoking `change tab`

You can solve this by using 
```
$tabs.first().tab('change tab', 'one');
```
https://jsfiddle.net/qfdz44ps/
