### ISSUE TITLE
[Embed/Modal] GPU Layers affects Fullscreen

### ISSUE THREAD

**Issue by mxth** [Semantic-Org/Semantic-UI#3089]
http://jsfiddle.net/efp8z6Ln/218/

I put another embed which is outside of the modal for comparison

**Comment by jlukic** [comment]
http://jsfiddle.net/uf4ftsww/

Looks like 3d layers breaks full screen.

You can try 
```css
.ui.modal {
  will-change: initial;
}
```
http://jsfiddle.net/uf4ftsww/

I'll have to think about how to integrate this with lib, as `will-change` is important as an optimization for modal animations.
