### ISSUE TITLE
[Transition] onComplete does not fire for static animations

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3090]

**Comment by frickenate** [comment]
@jlukic It looks like this was closed as past of the 2.1.5 milestone without being addressed. Is this a limitation in the way static animations are run? With the `interval` setting only applying to groups, and no separate option to insert a pause/delay between iterations of `looping`, it's required to ignore `looping` entirely and simply use a `setInterval` which is not ideal.
