### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by val-samonte** [Semantic-Org/Semantic-UI#3091]
Example:
Typescript compiler would complain because jQuery doesn't have a function named modal.
$('.ui.modal').modal('show');

**Comment by jlukic** [comment]
I don't believe this is a bug with the library.

**Comment by DaSchTour** [comment]
This is not a bug in the library but it would be nice if somebody could create Typings for Semantic UI JavaScript Librarys. So Maybe this could be reopened as a feature request?

**Comment by val-samonte** [comment]
@jlukic I know this is not the right place to file the issue, but as @DaSchTour mentioned this would be better as a feature request? It is really convenient for the Typescript users if we had this one, or maybe submit a PR to DefinitelyTyped repo?

**Comment by hugohomesquita** [comment]
I started, we will continue :D https://github.com/hugohomesquita/DefinitelyTyped

**Comment by mikeesouth** [comment]
@hugohomesquita Can you submit a PR for your Semantic UI definitions to the DefinitelyTyped master repo?

**Comment by alfkonee** [comment]
Has this been merged with the main DefinatelyTyped Library

**Comment by tomtobac** [comment]
@hugohomesquita how we can use it? I installed `typings install dt~jquery --global` and still I don't have the references, and `typings search semantic-ui` gives _No results found_. Any clue? Thanks

**Comment by larvanitis** [comment]
@hugohomesquita I can't find it in your repo.

Is anyone working on it? If yes, where?

**Comment by tripflex** [comment]
Yes this would be very beneficial to have, especially so we can set it up in IDEs like PHPStorm, etc.

Here's what I found in his repo:
https://github.com/hugohomesquita/DefinitelyTyped/tree/master/semantic-ui

**Comment by tripflex** [comment]
@alfkonee no it has not, and I do not see any PRs open for it either.

**Comment by tripflex** [comment]
@jlukic does this mean you guys have no intention of adding typescript definitions?

**Comment by budiadiono** [comment]
Hi guys, I created a helper module to generate the type definitions. It's on https://github.com/budiadiono/semantic-ui-typescript. Or you just can use [semantic-ui.d.ts](https://github.com/budiadiono/semantic-ui-typescript/blob/master/output/semantic-ui.d.ts) directly.

**Comment by dusthub** [comment]
@budiadiono Will you plan to contribute your project to DefinitelyTyped/DefinitelyTyped ?

**Comment by budiadiono** [comment]
@dusthub It's good idea, but I'm not sure I have a chance to do that since semantic is modular so I have to create separated d.ts files for each module. But I'll think about it when I'm free.

**Comment by valepu** [comment]
9 hours ago someone made a Pull Request on DefinitelyTyped to add Semantic UI https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14252#pullrequestreview-18565205

**Comment by leonard-thieu** [comment]
This is merged now.

`npm install --save-dev @types/semantic-ui`

**Comment by atom-azimov** [comment]
Awesome ! Thanks for that :)

**Comment by subramn** [comment]
Are there examples on how to use this.

**Comment by larvanitis** [comment]
If you already have jquery's type definitions up and running, it is just a matter of `npm i @types/semantic-ui`. After that you can use it like:

```typescript
const settings: SemanticUI.DropdownSettings = {
  allowReselection: true,
  allowAdditions: 'abc', // <- this will produce an error since it is specified as `boolean` in typedefs
};

$('#my-dropdown').dropdown(settings);
$('#my-dropdown').dropdown('toggle');
$('#my-dropdown').dropdown('go nuts'); // <- this will produce an error since there is no such "behavior" specified in typedefs
```

**Comment by subramn** [comment]
thanks for the response, when i tried to use its saying dropdown is not a property of JQuery

**Comment by subramn** [comment]
import {Component, AfterViewInit} from '@angular/core';
import * as $ from 'jquery';
@Component({
  selector   : 'app-root',
  templateUrl: './app.component.html',
  styleUrls  : ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'app works!';

  ngAfterViewInit(): void {
    $('.ui.dropdown').dropdown();
  }
}

**Comment by larvanitis** [comment]
I do not want to create any confusion here. I am using my custom typedefs, which I have pubished here if you want to try them (https://gist.github.com/larvanitis/4d2b8c80eb70d8b2fb0bde7f3786378d). These work more or less the same way as the published `@types`.

I use the following setup, if it helps you.

- `package.json`
```json
    "@types/jquery": "^2.0.45",
    "jquery": "3.2.1",
    "ts-node": "3.0.4",
    "tslint": "5.2.0",
    "typescript": "2.3.2",
```

- `custom_typings/jquery.semantic-ui.d.ts` - the file from the gist I linked

- `webpack.config.js` - I have exposed Jquery as a global so I do not have to `import * as $ from 'jquery';` to use it
```javascript
    plugins: [
      new webpack.ProvidePlugin({
        '$': 'jquery',
        'jQuery': 'jquery',
        'window.jQuery': 'jquery', // this doesn't expose jQuery property for window, but exposes it to every module
      }),
    ],
```
