### ISSUE TITLE
".ui.form .divider" rule breaks ".ui.vertical.divider"

### ISSUE THREAD

**Issue by Parakleta** [Semantic-Org/Semantic-UI#3092]
As the subject line says.  There is a rule in `form.css` that adds a margin to all `.divider` inside `.ui.form` which messes up `.ui.vertical` divider alignment.  Consider using `:not(.ui)` or `:not(.vertical)` in the `form.css` rule.

**Comment by jlukic** [comment]
Please create a test case so I can evaluate the bug. There is a jsfiddle to fork in the readme

**Comment by Parakleta** [comment]
Here's the [fiddle](http://jsfiddle.net/parakleta/j15qk2pz/1/).

**Comment by jlukic** [comment]
Thanks, this is clearly a bug

**Comment by treble-snake** [comment]
Btw, it's not only about "vertical" rule. E.g. "fitted" rule is also broken.
http://jsfiddle.net/q39snkqw/1/
Guess there is more there.

**Comment by jlukic** [comment]
Should be solved in `2.1.6` (see commits) this was accidentally mistagged.
