### ISSUE TITLE
[Dropdown] Search autocomplete shared history

### ISSUE THREAD

**Issue by dwightbcoder** [Semantic-Org/Semantic-UI#3097]
I've discovered that all dropdown search inputs are inserted with no autocomplete attributes and with no name/id to associate autocomplete history.

This has resulted in dropdowns with search enabled and used for different fields to have shared autocomplete history and manifests itself (specifically in IE) as an additional menu appearing overtop the SUI dropdown menu.

I believe you can prevent this if the top level form has autocomplete="off" set by not on an individual field basis.

I believe the search input should have autocomplete="off" set by default as the UX is poor with two menus visible on top of each other.

**Comment by jlukic** [comment]
I think this makes sense, I'll add

**Comment by jlukic** [comment]
Added in 36c83c5
