### ISSUE TITLE
Dropdown 'set selection' not working on new options

### ISSUE THREAD

**Issue by lselbeck** [Semantic-Org/Semantic-UI#3100]
I am adding an option to a ui dropdown.  The next line I try to set it as selected with 'set selected', but it doesn't work; at least not on the first click.

Here's the fiddle repro: https://jsfiddle.net/lselbeck/1fq3ahfu/2/

I want to select the new option that I added, how?

**Comment by jlukic** [comment]
Mutation observers are asynchronous, so any other javascript run inline will occur *before* they fire.

You can fix your scenario by calling `setup select` after adding the option.
http://jsfiddle.net/up9db8wb/
