### ISSUE TITLE
multi-level menu inside selection dropdown

### ISSUE THREAD

**Issue by zoozalp** [Semantic-Org/Semantic-UI#3101]
I'd like to use multi-level menu inside a selection dropdown but sub items didn't play well with the dropdown. It works great with dropdown button but I need the selection dropdown for ui design consistency.

Please see my sample at https://jsfiddle.net/Zekai/tmag12u7/

Do you have a workaround for this? Your help is greatly appreciated.

**Comment by jlukic** [comment]
Selection dropdown are bordered on all sides, it doesn't make sense for them to also be multi-level. I'd recommend using either a multi level dropdown or a selection dropdown. They both function equally for user selection.
