### ISSUE TITLE
[Sticky] Stale cache for context.bottom

### ISSUE THREAD

**Issue by lauri-elevant** [Semantic-Org/Semantic-UI#3105]
else if( (element.height + scroll.top - elementScroll) >= context.bottom ) {
                  module.debug('Fixed element reached bottom of container');
                  module.bindBottom();
                }

Regarding this piece of code in sticky. If an element is being stuck to the top of the page it all behaves nicely until the height of the context is changed (an accordion opened, perhaps). This causes the context.bottom to be stale and the condition to be reached prematurely. The result is that the element suddenly jumps to the bottom.

As a quick workaround, I implemented something like that:

		onScroll: _.debounce(function() {		
			$context = $('main.container');
			$(this).data('moduleSticky').cache.context.bottom = $context.offset().top + $context.outerHeight();			
		}, 100),

.. do you see any alternatives?

**Comment by jlukic** [comment]
You can either set `observeChanges: true` or use `.sticky('refresh')`

**Comment by lauri-elevant** [comment]
http://jsfiddle.net/gz4746Lq/4/

I created a fiddle to demonstrate the issue further. The `.sticky('refresh')` of course works (not in my case, but this is not the issue here) but it really is not feasible in complex layouts to send the `refresh` calls on every possible event that may potentially affect the height of the content..

`observeChanges` does not work (DOM tree is unchanged)

Would you agree that re-calculating the height of the context only is perhaps not too intensive to call on each scroll?

**Comment by jlukic** [comment]
No i would disagree. Sticky is **heavily** optimized to avoid touching the DOM during scroll. It avoids querying for anything but scroll position. Scroll position is also dispatched using a pub/sub pattern to avoid multiple elements querying for the same value. I've spent a lot of time in chrome inspector getting the scroll event down to as tiny as possible.

Until there's a web API that dispatches events on element reflow, there's no way to know what event would trigger a change in content size. It could include things like an image without specified dimensions loading, a css class change, or a host of other things.

**Comment by lauri-elevant** [comment]
Thanks for taking your time to explain this. Your points are certainly valid.

I would suggest that a note should be added to the docs..
