### ISSUE TITLE
Hide dimmer page on modal

### ISSUE THREAD

**Issue by ZeGregg** [Semantic-Org/Semantic-UI#3109]
Hi

It seems, hide dimmer behavior does not work on modal. Here is a http://jsfiddle.net/Greggg/k78vjwyt/1/ 

Regards

**Comment by jlukic** [comment]
Dimmer has to be visible to hide it. Keep in mind hiding dimmer will hide the modal since a modal is inside a dimmer.
http://jsfiddle.net/7569mkdm/
