### ISSUE TITLE
[Modal] - Fix HTML for Basic Modal Example

### ISSUE THREAD

**Issue by imilina** [Semantic-Org/Semantic-UI#3110]
**Steps to Reproduce**
1. Create basic modal dialog (the same code from basic modal example)
2. Execute javascript to show the dialog

**Expected**
The dialog should look the same as modal on semantic ui examples page. Text should be centered, and action buttons right aligned.

**Result**
Modal have left aligned text (header and content) and action buttons stretching the whole width of the dialog.

**Testcase**
Using semantic ui 2.1.4:
http://jsfiddle.net/8zjzytcu/

**Comment by jlukic** [comment]
The example code in docs is incorrect. The demo is using `ui icon header`

**Comment by carnec** [comment]
![semantic-ui_code_doc_mismatch](https://cloud.githubusercontent.com/assets/5610515/10748256/a444a0a0-7c5e-11e5-8739-f80dba5ead2d.png)

**Comment by Banandrew** [comment]
Fixed with Semantic-Org/Semantic-UI-Docs#247.
