### ISSUE TITLE
[Tab] Consider adding $.address.update() in init

### ISSUE THREAD

**Issue by lauri-elevant** [Semantic-Org/Semantic-UI#3112]
Short story:

```
$('.ui.tabular.menu.edit-tabs .item').tab({
    history: true,
    historyType: 'hash'
});

$.address.update(); // workaround
```

It seems that by the time SUI does `$.address.bind('change', module.event.history.change)` in `initializeHistory` the `jquery.address.js` init routines may or may not have already ran. 

So if I go to a page like `/some/page#/tabXYZ` then sometimes the correct tab activates, usually it does not.

Should SUI perhaps run `$.address.update();` in the `initializeHistory` ? Perhaps even debounced 10ms in case there are many tabs to initiate..

Also, given the fact that `jquery.address.js` seems abandoned (last commit last year), do you have some plans regarding this?

**Comment by jlukic** [comment]
I haven't run into what you're describing. I would assume it would be related to the include order with `address.js`. I'll look into fitting `update` into init.  

I'd recommend binding anything that expects the tab to be open already to `onFirstLoad` of tab, but that's probably clear.
