### ISSUE TITLE
[Dropdown] Select Doesn't Sync on Prop Change, Only DOMInsertion

### ISSUE THREAD

**Issue by Parakleta** [Semantic-Org/Semantic-UI#3115]
I've had some trouble getting a dropdown to track changes to the `select` element it's wrapped around.  I want to do it this way because the `select` element is controlled by React, and I just want SemanticUI to prettify it for me.  I've found two solutions, one which could be added to the documentation, and the other is a bit more complex and hackish and requires code changes.

The simplest solution I found was to use the (currently undocumented) `restore selected` behaviour on the dropdown in the `componentDidUpdate` React lifecycle function.  This causes the dropdown to resynchronise with any changes React makes to the `value` property.

The more complex solution is a bit of a hack because the `MutationObserver` capability can only see DOM mutations, and not property mutations.  The only workaround I could find was to animate the `:checked` pseudo-class and trigger the update event off this.  The advantage of this method is that it could be completely automated within the dropdown code so I didn't have to add a binding in React, and it will "just work".  It will also track any other JS changes to the select element.

The main thrust of it is to add the following CSS:

```
select > option:checked {
    animate: checked 1ms;
}
select[multiple] > option:not(:checked) {
    animate: unchecked 1ms;
}
@keyframes checked { from: {}; to: {} }
@keyframes unchecked { from: {} to: {} }
```

For the animations to work the `select` element must be hidden using `visibility: hidden; position: absolute` rather than `block: none`.  Then an event listener can be added in `dropdown.js` similar to the following:

```
if (module.has.selectInput()) {
    $input.on('animationstart', function (ev) {
        if (ev.animationName === 'checked') {
            module.set.selected(ev.target.value);
        } else if (ev.animationName === 'unchecked') {
            module.remove.selected(ev.target.value);
        }
    });
}
```

**Comment by jlukic** [comment]
Currently the mutation observers on select just call an internal method that can be invoked manually to recreate dropdown from select.

```javascript
/// trigger dropdown to regenerate from select
$('.dropdown').dropdown('setup select');
```

**Comment by Parakleta** [comment]
Recreating the dropdown using `'setup select'` doesn't correctly track the change in properties `select.value` or `option.selected` unfortunately, which is where `'restore selected'` is required.

**Comment by steve-ross** [comment]
I'm having the same issue with this using Blaze (in Meteor)... definitely think it is something that needs fixing as web-apps become more 'reactive' this worked fine in 2.0.7

**Comment by destan** [comment]
`restore selected` doesn't clears unselected items though, they must be manually removed.

**Comment by levithomason** [comment]
@Parakleta @destan syncing jQuery DOM manipulations with React's Virtual DOM will be the end of you.  Luckily, there is now an official Semantic-UI-React project that solves this and lots of other issues: https://github.com/TechnologyAdvice/stardust

I'll soon port it to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).

Cheers
