### ISSUE TITLE
Text overflow in dropdown

### ISSUE THREAD

**Issue by hugomarisco** [Semantic-Org/Semantic-UI#3117]
Hello,

I've noticed that text overflows in dropdown items if there isn't any larger header:

https://jsfiddle.net/kp5p3asm/

I'm playing around to find the best solution. In the meanwhile I let this here for anyone who wants to check it.

Congratulations on the project! Looking really good.

**Comment by jlukic** [comment]
This can be solved by modifying `white-space` css on a particular dropdown.

**Comment by nickpoulos** [comment]
Can you elaborate on "modifying the white-space css on a particular dropdown"?  Because this still seems to be an issue? Unless I am missing something, the only way I've been able to get around this is by removing the min-width property from the original Semantic CSS.

**Comment by rammanoj** [comment]
I guess you can use the property `white-space: normal;` to prevent  the text-overflow in fixed width dropdowns. You can get some reference about it [here](https://www.w3schools.com/cssref/pr_text_white-space.asp)
