### ISSUE TITLE
[Table] Tablesort unable to sort by data-sort-value

### ISSUE THREAD

**Issue by minstrel** [Semantic-Org/Semantic-UI#3120]
In the jquery-tablesort that SUI's tablesort is based on, values in the td's "data-sort-value" attribute will be used in preference to the td's content when sorting (used to simplify sorting complicated content, or dates in their multitude of formats).  Would it be possible to duplicate that in SUI's tablesort.js?

[Fiddle here](http://jsfiddle.net/rdj240wv/2/)

The data-sort-value values in the fiddle are julian dates.  If the table is sorted by these the dates will be in the right order.
Sorting by the US style dates in the td content results in a string sort that gets the dates out of order.

I worked around this by inserting a hidden span element with the julian date as the first child of each td and this has worked so far, but seems like a bad hack.

**Comment by jlukic** [comment]
The tablesort plugin is  pretty hacked (crappy). I will hope to write a better one in the future, but I can't provide any support for it in its current iteration.
