### ISSUE TITLE
.ui.loading.form color is transparent; makes non <label> elements disappear

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#3122]
this makes all things non-label disappear (error messages, headers, paragraphs, etc) -- intended?

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/form.less#L612

http://jsfiddle.net/jholl/u8wkprct/

**Comment by jlukic** [comment]
This is pretty silly (aka a bug).

**Comment by jlukic** [comment]
Removed all the weird rules in `loading form`. I think thats one of those dark crevices I didn't address correctly in `2.0`.
