### ISSUE TITLE
.ui.label border-radius persists when defaultBorderRadius: 0em

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#3123]
maybe I should just set the `@absoluteBorderRadius: 0em` in the overrides; but in case this was unintentional, thought I would point it out.

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/label.less#L42

inherits the local variable `@borderRadius: @absoluteBorderRadius` which remains in default theme to be a value even if `@defaultBorderRadius` is set to 0em.  Perhaps this definition should inherit from `@defaultBorderRadius`.  This issue is visible for example when you set `@defualtBorderRadius: 0em;` and then build a `.ui.labeled.input` whereby the labeled part of the input still has outer border radius and rest of input does not.

@jlukic, thank you so much for building Semantic UI.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L42

Probably need to set both values.
