### ISSUE TITLE
Basic Buttons look strange in IE 11

### ISSUE THREAD

**Issue by Thomsos** [Semantic-Org/Semantic-UI#3126]
Hello,

The corners of a basic button element don't look great in IE 11, they are much thicker then the rest of the border. Anyone know how to fix this?

**Comment by Thomsos** [comment]
Example:

![basicbuttons](https://cloud.githubusercontent.com/assets/13591018/10246857/c5c92406-68e2-11e5-81ec-4bce7a3080d0.PNG)

**Comment by avalanche1** [comment]
This is IE specificity.SUI cant fix that.
