### ISSUE TITLE
Dropdowns not being read by NVDA accessibility software

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#3127]
Dropdowns not being read by NVDA accessibility software, everything shows up as "blank" instead of the options.

**Comment by Banandrew** [comment]
Linking a general accessibility discussion: #348.

**Comment by dingpengyu** [comment]
#Accessibility issues 3340
https://github.com/gogs/gogs/issues/3340

**Comment by dingpengyu** [comment]
#Gitea's accessibility problem Issue 7057 
https://github.com/go-gitea/gitea/issues/7057
