### ISSUE TITLE
gulp build-docs error

### ISSUE THREAD

**Issue by ondarox** [Semantic-Org/Semantic-UI#3129]
1. Have created 2 adjacent sibling folders UI and Docs
2. UI folder has been populated with Semantic-UI-Docs

However , when I try to run "gulp build-docs" inside the UI folder , I am getting an error message : 
"gulp file not found" . Any suggestions on how to rectify this ?

**Comment by jlukic** [comment]
UI folder should be clone of UI repo, not `npm install`
