### ISSUE TITLE
Use CSS3 filter for dimmer blurring

### ISSUE THREAD

**Issue by adityapatadia** [Semantic-Org/Semantic-UI#3133]
I can see that blurring on dimmer is not performant as per current implementation.

Can we use CSS3 blurring like ``` -webkit-filter: blur(5px)``` or ``` backdrop-filter: blur(5px)```? This is improve performance and simplify the implementation.

**Comment by jlukic** [comment]
It does use `filter: blur` but css filters themselves are not performant. 

Backdrop filter is only supported in Safari unfortunately but would simplify things.
