### ISSUE TITLE
Accordion example doesn't expand nested accordions

### ISSUE THREAD

**Issue by hoigo** [Semantic-Org/Semantic-UI#3137]
I'm a newbie here and I tried to work with the accordion. I just took your nested accordion example, but it doesn't work properly. When I try to expand e.g. "Level 1B" or "Level 1C" they expand for a millisecond, but then collapse immediately.

Do you have a hint?

Here's the example:

\<html>
	\<head>
		\<base href="/">
		\<link rel="stylesheet" href="temp/semantic.min.css">
		\<script src="temp/jquery-1.11.0.min.js">\</script>
		\<script src="temp/semantic.min.js">\</script>
	\</head>
	\<body>
		\<div>
			\<div class="ui styled accordion">
			  \<div class="title active">
				\<i class="dropdown icon">\</i>
				Level 1
			  \</div>
			  \<div class="content active">
				Welcome to level 1
				\<div class="accordion transition visible" style="display: block !important;">
				  \<div class="title active">
					  \<i class="dropdown icon">\</i>
					  Level 1A
				  \</div>
				  \<div class="content active">
					\<p class="transition visible" style="display: block !important;">Level 1A Contents\</p>
					\<div class="accordion transition visible" style="display: block !important;">
					  \<div class="title">
						  \<i class="dropdown icon">\</i>
						  Level 1A-A
					  \</div>
					  \<div class="content">
						  Level 1A-A Contents
					  \</div>
					  \<div class="title active">
						  \<i class="dropdown icon">\</i>
						  Level 1A-B
					  \</div>
					  \<div class="content active">
						  Level 1A-B Contents
					  \</div>
					\</div>
				  \</div>
				  \<div class="title">
					  \<i class="dropdown icon">\</i>
					  Level 1B
				  \</div>
				  \<div class="content">
					  Level 1B Contents
				  \</div>
				  \<div class="title">
					  \<i class="dropdown icon">\</i>
					  Level 1C
				  \</div>
				  \<div class="content">
					  Level 1C Contents
				  \</div>
				\</div>
			  \</div>
			  \<div class="title">
				\<i class="dropdown icon">\</i>
				Level 2
			  \</div>
			  \<div class="content">
				\<p class="transition hidden">Welcome to level 2\</p>
				\<div class="accordion transition hidden">
				  \<div class="active title">
					\<i class="dropdown icon">\</i>
					Level 2A
				  \</div>
				  \<div class="active content">
					\<p>Level 2A Contents\</p>
					\<div class="accordion">
					  \<div class="title">
						  \<i class="dropdown icon">\</i>
						  Level 2A-A
					  \</div>
					  \<div class="content">
						  Level 2A-A Contents
					  \</div>
					  \<div class="title">
						  \<i class="dropdown icon">\</i>
						  Level 2A-B
					  \</div>
					  \<div class="content">
						  Level 2A-B Contents
					  \</div>
					\</div>
				  \</div>
				  \<div class="title">
					  \<i class="dropdown icon">\</i>
					  Level 2B
				  \</div>
				  \<div class="content">
					  Level 2B Contents
				  \</div>
				  \<div class="title">
					  \<i class="dropdown icon">\</i>
					  Level 2C
				  \</div>
				  \<div class="content">
					  Level 2C Contents
				  \</div>
				\</div>
			  \</div>
			\</div>
		\</div>
		\<script>
			$(".accordion").accordion();
		\</script>
	\</body>
\</html>"

**Comment by jholl** [comment]
can you try and replicate the failing behavior in a jsfiddle and share that link?
you can fork this as a baseline http://jsfiddle.net/jholl/b6cvpqw2/
this will help quickly assess if it's an issue in Semantic or something else in your code.

**Comment by hoigo** [comment]
Well, I tried it here: https://jsfiddle.net/hoigo/1edob2wu/

**Comment by hoigo** [comment]
Did you reproduce it?

**Comment by jholl** [comment]
Yes, but had to do it on [codepen](http://codepen.io/jholl/pen/avwKVJ); I couldnt' get jsfiddle to render correctly.  This is going to make you flip ...

Your selector should be `$(".ui.accordion")` ... notice that the nested accordions do not have the `.ui` class; therefore since your selector is just `$(".accordion")` it's causing the bug.

Also, I assume you cut-paste from page, but you don't need the addition markup with `transition hidden` written into your source; just the `.active` class on the elements you want open should be enough.

**Comment by hoigo** [comment]
Thanks a lot. Now it works.

**Comment by heaven7** [comment]
Hi @jholl,
i also got this problem. your [codepen](http://codepen.io/jholl/pen/avwKVJ) still cannot open nested accordions. they just open and collapse after selecting one. did you fix this, @hoigo ?

**Comment by jholl** [comment]
Are you initializing the js with the correct class '.ui.accordion' or only with just '.accordion'?  And the element with '.ui.accordion' is just the top level element?

The codepen should work of you comment out/remove the first bit of js and uncomment/activate then second.  Notice the selector difference in the two.

**Comment by heaven7** [comment]
yes now it works with the class .ui on the top level.
thanks for that!
