### ISSUE TITLE
Some icons are broken

### ISSUE THREAD

**Issue by madela** [Semantic-Org/Semantic-UI#3139]
I think theses icons are broken:
retweet
facebook
facebook square
linkedin
linkedin square
twitter
twitter square

Here (http://semantic-ui.com/elements/button.html#social) you can see that the documentation is also broken

**Comment by robmoggach** [comment]
also look at `bordered inverted teal dashboard icon`
using bordered icons in a vertical menu isn't working for me.

**Comment by jlukic** [comment]
The icons are appearing normally for me. I'm not sure I know what you mean

**Comment by madela** [comment]
I found the problem. Adblock was blocking those icons. Mark it as solved

**Comment by EllaAb** [comment]
that exactly what I asking about ?
