### ISSUE TITLE
Disable @media adjustments

### ISSUE THREAD

**Issue by cadorn** [Semantic-Org/Semantic-UI#3144]
How do I disable all @media adjustments?

i.e. I want the page to look the same no matter what size the device viewport is.

e.g. I don't want tables to be re-arranged as the viewport size gets smaller. I just want the tables to shrink until they can no longer but keep the header and row layout in tact when it gets smaller (and potentially force a horizontal scroll).

**Comment by cadorn** [comment]
Using https://github.com/iamdustan/queryless to strip media

**Comment by jlukic** [comment]
There are `unstackable` table variations, responsive styles are mostly opt-in, opt-out.
