### ISSUE TITLE
[Progress] Progress bars stacked variation

### ISSUE THREAD

**Issue by LemonQ** [Semantic-Org/Semantic-UI#3145]
Hello,

It would be nice if we could stack several progress bars inside a single one, just like the stacked variation in Bootstrap. See here: http://getbootstrap.com/components/#progress-stacked

i'm really looking forward for this feature.
Thanks!

**Comment by LemonQ** [comment]
Bump

**Comment by shubhamchaudhary** [comment]
+1 for this

**Comment by pate** [comment]
Does anyone have some custom CSS to make this work and hopefully use some of Semantic's colouring?

**Comment by azmeuk** [comment]
Seems to be a duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6160

**Comment by lubber-de** [comment]
Multiple Progress Bars are implemented in Fomantic-UI 2.7.3 now 😄 
https://fomantic-ui.com/modules/progress.html#multiple-bars
![image](https://user-images.githubusercontent.com/18379884/55389068-d1524180-5534-11e9-9cac-9e949df72342.png)
