### ISSUE TITLE
[Dropdown] Issue with Similar Values

### ISSUE THREAD

**Issue by AliSepehri** [Semantic-Org/Semantic-UI#3147]
When I have two items which the name of one is equal with another one value, semantic select the wrong item. for example in following case:

`<select name="storeId" class="ui dropdown">`
`<option selected="selected" value="11">21</option>`
`<option value="1">11</option>`
`</select>`

semantic selects the item with value 1.

**Comment by jholl** [comment]
This seems to work as expected [here](http://codepen.io/jholl/pen/VvWBXO) ; check the console log after selection.

**Comment by AliSepehri** [comment]
@jlukic: jholl has written a test case for this problem.

@jholl: No! It doesn't work. For the FIRST time the page is loaded, the first item (21) should be selected BUT the second one(11) is selected. Attention to the item should be selected for the first time.

**Comment by jholl** [comment]
Ah! I see.  I added a few more examples in the pen to try some different things out.  If I get some time later I'll dig through the dropdown source also and see what I can figure out.

**Comment by philrykoff** [comment]
The included fiddle was broken. Here is one to reproduce the issue: http://jsfiddle.net/hhuvyw4c/.
