### ISSUE TITLE
There is a grey gap between sidebar and content

### ISSUE THREAD

**Issue by ZYWJ** [Semantic-Org/Semantic-UI#3149]
![image](https://cloud.githubusercontent.com/assets/5554211/10335813/4ba75fd8-6d26-11e5-9f07-5cd1f8732dc4.png)

I don't want it.

**Comment by jholl** [comment]
I don't think this is an issue specific to Semantic.  You can probably unset that with your own css.  It should be okay for your to close this issue unless I misunderstand how this relates to Semantic?

Look at the css `padding` of your element on the right, your issue is probably there.

**Comment by ZYWJ** [comment]
Sorry. It indeed  isn't a issue.
