### ISSUE TITLE
OTS parsing error when trying to decode icon files

### ISSUE THREAD

**Issue by zanamich** [Semantic-Org/Semantic-UI#3155]
I get the following error on browser:

Failed to decode downloaded font: https://staging-landing-pages.yotpo.com/styles/themes/default/assets/fonts/icons.woff2
OTS parsing error: invalid version tag

I get this for all files inside fonts directory.

**Comment by minfawang** [comment]
+1

**Comment by planeth44** [comment]
+1

**Comment by jholl** [comment]
Are you sure this call is coming from Semantic and not something in your own source?

![screen shot 2015-10-09 at 10 18 56 am](https://cloud.githubusercontent.com/assets/3354585/10396215/3845a2d4-6e6f-11e5-979b-646d5ab611dd.png)

You should be able to change that link url to `https:` bc google can serve the font stylesheets over `https:`  All of Semantic's calls to google in the default theme should be using the `@googleProtocol` variable which is set to `https:` [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L20)

Am I mistaken?

**Comment by zanamich** [comment]
I'll start from scratch..
I have an angular project, in which I use semantic-ui library.
fonts library is currently located inside the bower-components as shown here:
![screen shot 2015-10-11 at 11 15 51 am](https://cloud.githubusercontent.com/assets/6762118/10415963/36ee9bf6-700a-11e5-8c14-eb89da24d3d1.png)
When the page is loaded on staging/production env i get the following error:
![ots error](https://cloud.githubusercontent.com/assets/6762118/10415969/4dc55298-700a-11e5-8f56-9457b7186cee.png)

In dev environment It's OK. I guess since the the path styles/themes/default/assets/fonts/.* is relative to to location of the semantic.css file (locally it is also under bower-components dir).

Hope I shared enough info.

**Comment by zanamich** [comment]
I've manage to solve this by creating a grunt task to copy all font files into 'dist' folder, under the same path as the error shows.
Yet, I consider it as a hack.

**Comment by avalanche1** [comment]
SUI is looking for fonts in `themes\defaults\assets\` dir. Put them there.
