### ISSUE TITLE
Will you added color ability of a border elements in future?

### ISSUE THREAD

**Issue by enjoyiacm** [Semantic-Org/Semantic-UI#3156]
Sometimes it's very useful. For example, user avatars.

CSS like this:
```css
.ui.image.green.border {...}
```
And HTML:
```html
<img class="ui green border image" src="..." />
```
Output may have border, colored ``green`` and thickness ``1px``.
For more thickness — may use code like this:

```html
<span class="ui lagre green border">
  <img class="ui image" src="..." />
</span>
```

**Comment by jlukic** [comment]
No i don't think specifying image borders in css has enough utility to warrant being added.
