### ISSUE TITLE
'Reveal' plain text or label

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#3158]
Hi,

I got pretty excited with the reveal element, that works without any js call.
However, it does not seem to work with neither plain text nor with semantic labels. Please find the jsfiddle below with both the issues and potential reason explained:

http://jsfiddle.net/mikus/uvk5dL2d/1/

```html
<div class="ui fade reveal">
    <div class="visible content">Im on top</div>
    <div class="hidden content">Im hidden</div>
</div>
```

The problem with plain text is the transparent background and different width of both divs, while with labels it seems to be a the 'hidden' class that they share with reveal. Both usages might be not the most common ones, but properly working reveal applied to text gives really nice effect. 

Any ideas how to fix it without forcing elements to have background specified?

**Comment by Dumidu** [comment]
Hi @mikocot ,

You can fix the label issue like follow.

```html
<div class="ui fade reveal">
  <div class="visible content">
     <div class="ui label">
          I'm visible
     </div>
  </div>
  <div class="hidden content">
     <div class="ui label">
          I'm hidden
     </div>
  </div>
</div>```

**Comment by mikocot** [comment]
true, thanks, still I would be happier with the plain text solution :P

**Comment by jlukic** [comment]
Getting reveal to work with inline-block content, is .. something short of impossible in the general case. 

It should however work fine for block like `img`

**Comment by smartrack** [comment]
Here is the fix i used and it worked
.ui.move.reveal .hidden.content{
	-webkit-transform: translateX(-100%)!important;
	-ms-transform: translateX(-100%)!important;
    transform: translateX(-100%)!important;
}
.ui.move.reveal:hover .hidden.content{
	-webkit-transform: translateX(1%)!important;
	-ms-transform: translateX(1%)!important;
    transform: translateX(1%)!important;
}
.ui.move.reveal>.content {
    display: block!important;
}

**Comment by avalanche1** [comment]
Submit a PR for review pls

**Comment by ryanbarsatan** [comment]
smartrack answer worked!

**Comment by green-coder** [comment]
@smartrack If you have time, please submit a PR. Your fix would be greatly appreciated.

**Comment by rafayano59** [comment]
@smartrack worked for me! thanks
