### ISSUE TITLE
Following button in Semantic ui

### ISSUE THREAD

**Issue by amalprasad** [Semantic-Org/Semantic-UI#3159]
i need to create fixed following button like this http://legacy.semantic-ui.com/elements/button.html i cannot find js to add please help

**Comment by dsignr** [comment]
There's a lot of examples in the page you've shared and next, as far as I know, buttons can still be very much functional without the JS dependencies. Can you please share a JSFiddle link so at least I can understand (and try to help) what you're asking about?

Thanks!

**Comment by enjoyiacm** [comment]
@aaroncox https://jsfiddle.net/platonfedr/yj2a2ypg/ this can help you.
