### ISSUE TITLE
[Card] middle aligned content does not work

### ISSUE THREAD

**Issue by kfei** [Semantic-Org/Semantic-UI#3160]
When using `img` with floated element, the floated element can't get middle aligned.

In the [2nd example](http://semantic-ui.com/views/card.html) of cards, **Elliot** and **14h** are not vertical aligned.

[jsfiddle](http://jsfiddle.net/dc2LfLmg/)

Thanks in advance!

**Comment by jlukic** [comment]
Floated elements do not support vertical alignment only inline block.
