### ISSUE TITLE
【Not Funny Error】Hi,I got a problem when using popup: Popup does not fit within the boundaries of the viewport

### ISSUE THREAD

**Issue by duruitang** [Semantic-Org/Semantic-UI#3163]
This is a funny error just when Chrome Console opened ! It means if you close Chrome Console , everything will be OK !

Just now , I found it wasn't a funny error , please fix it , thanks !

![error](https://cloud.githubusercontent.com/assets/13196890/10414889/ccdbc2d4-7018-11e5-815d-698deb1367a3.png)

**Comment by duruitang** [comment]
Chrome error, IE11 is OK

**Comment by allthesignals** [comment]
Seeing this issue too.

**Comment by lholznagel** [comment]
Just a idea by reading the error message:
Make the popup smaller.

**Comment by IonutBajescu** [comment]
I'm not entirely sure what's the issue here. Could you please post a jsfiddle? Mind that in order to show a popup in semantic, you've got to have enough space on the screen since scrolling would make the popup disappear.

**Comment by philrykoff** [comment]
Same issue here. I "fixed" it by assigning a sensible `max-height` and `overflow-y: auto` to the content div.

**Comment by jlukic** [comment]
If a popup cant be positioned in any direction without a part of it appearing off the page, it will not appear unless `lastResort` specifies a direction of last resort.

**Comment by Captain-GaDo** [comment]
Same issue. In the same page example we can see the mistake

http://semantic-ui.com/modules/popup.html#/examples

Wide Popup Menu
