### ISSUE TITLE
Button size class in a menu div is being ignored

### ISSUE THREAD

**Issue by nynevi** [Semantic-Org/Semantic-UI#3164]
Button size classes even though they are irrelevant to their parent are being ignored 

http://jsfiddle.net/7xftjz41/5/ << tiny
http://jsfiddle.net/nynevi/7xftjz41/7/ << massive

http://jsfiddle.net/nynevi/7xftjz41/8/ << Semantic-UI docs example with tiny

Case here is that neither of the button size classes (even when they are applied to an anchor tag) work whereas putting it inside a div or a form (or just any) tag solves the issue but the solution increases height of the menu.

http://jsfiddle.net/7xftjz41/2/ << div
http://jsfiddle.net/7xftjz41/3/ << form
http://jsfiddle.net/nynevi/7xftjz41/6/ << made-up tag

**Comment by lubber-de** [comment]
Fixed since Fomantic-UI 2.7.2 by https://github.com/fomantic/Fomantic-UI/pull/334
See your adjusted jsfiddle here http://jsfiddle.net/szqkt6v5/
