### ISSUE TITLE
Form tag inside a modal breaks css

### ISSUE THREAD

**Issue by nynevi** [Semantic-Org/Semantic-UI#3165]
I try to implement a form inside a modal

http://jsfiddle.net/nynevi/efp8z6Ln/227/

but putting a form tag inside a modal breaks header content and action classes

http://jsfiddle.net/nynevi/efp8z6Ln/228/

**Comment by ZeGregg** [comment]
Just add form class to your form and some CSS on form header http://jsfiddle.net/Greggg/efp8z6Ln/232/

**Comment by nynevi** [comment]
I am embarresed :< Thanks @ZeGregg

**Comment by boblin** [comment]
Hi all,

I think that form tag inside a modal really breaks css.

Please see my example here:
http://jsfiddle.net/boblin/kshybf3L/7/

If you remove **<form> ** and **</form>** tags, modal looks OK.

Is it bug?
