### ISSUE TITLE
[menu][dropdown] dropdown items in secondary menu disappear before can be clicked

### ISSUE THREAD

**Issue by daniel0076** [Semantic-Org/Semantic-UI#3169]
put a dropdown and some items in a secondary menu, when I hover the dropdown, the item will appear.However before my mouse can reach the items, the dropdown just closed.

jsfiddle: http://jsfiddle.net/mbs4rwrL/1/

**Comment by daniel0076** [comment]
oh I am sorry :( the issue is same as #2444

**Comment by RubenWalraevens** [comment]
Is there already a solution for this problem?
