### ISSUE TITLE
[Modal] onClick events not firing with react

### ISSUE THREAD

**Issue by pcauthorn** [Semantic-Org/Semantic-UI#3173]
Please see [this fiddle](http://jsfiddle.net/pcauthorn/ubsczhw6/7/)

This shows the events working in the `segment` and not the `modal`.  

React version .14 

*Edited fiddle to be more clear*

**Comment by fxpoet** [comment]
+1

**Comment by fxpoet** [comment]
Finally I have solved this problem.

see, semantic/src/definitions/modules/modal.js
and then change default setting "detachable: false" to "detachable:true"
rebuild to semantic.min.js file  (use gulp build)
