### ISSUE TITLE
Can not type 'Б' letter in dropdown with 'allow additions''

### ISSUE THREAD

**Issue by monochromatique** [Semantic-Org/Semantic-UI#3174]
Funny.

It's because 'Б' character on button with comma.

But there is second letter in russian alphabet and there is no other button with this character.)))

Now use type-copy-paste with notepad.

**Comment by jlukic** [comment]
You can now replace the keycode for comma in `2.1.5`, see #3016

**Comment by lubber-de** [comment]
It was finally fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2247
