### ISSUE TITLE
modal positioning issue; not centering

### ISSUE THREAD

**Issue by MrOutput** [Semantic-Org/Semantic-UI#3175]
not sure why the modal is not centering on the page. 

We are using legacy semantic unfortunately and cannot upgrade. 0.x

![screenshot from 2015-10-12 17-06-23](https://cloud.githubusercontent.com/assets/8491687/10440043/abffc89e-7103-11e5-821e-7f4ac8bf2b24.png)

additionally, if the modal is too long, it is hidden under the browser window

### In addition

![screenshot from 2015-10-13 10-17-40](https://cloud.githubusercontent.com/assets/8491687/10459120/bb919acc-7193-11e5-965d-f002898ea814.png)

**Comment by ps1dr3x** [comment]
Same here, modals with a large .ui.fluid.image (or .ui.large.image) shows like your second screen. Strangely it happens only on the first opening (if i reopen the modal it shows normally).
First show:
![schermata da 2015-10-21 23-53-11](https://cloud.githubusercontent.com/assets/10249616/10651298/1b165c64-784f-11e5-8b28-9ffc4799f71c.png)
Second show:
![schermata da 2015-10-21 23-53-18](https://cloud.githubusercontent.com/assets/10249616/10651307/29fef876-784f-11e5-9f06-64d527d85079.png)

**Comment by Keten** [comment]
in javascript, add this setting to the modal:

observeChanges: true

And, if u are using ANGULAR... maybe a timeout for modal (100ms is enough) will fix too...

**Comment by ps1dr3x** [comment]
Yes, i confirm that angular was the problem. A timeout fixed it ;)

**Comment by MrOutput** [comment]
@ps1dr3x @Keten thank you, I was using angular as well. I managed to fix using a .refresh...and will use your solutions instead.

**Comment by RigobertoFelix** [comment]
thank you that setting is the solution.

**Comment by chethan1095** [comment]
in jquery the modal position is not centering when i opened first time later on its working fine any solution for that

**Comment by GregSithole** [comment]
Setting solution worked out for me, thanks!
