### ISSUE TITLE
[Dropdown] {Value} Should Be Passed with Dropdown's API Call

### ISSUE THREAD

**Issue by Banandrew** [Semantic-Org/Semantic-UI#3182]
Hello,

Semantic UI [should replace route {value} automatically](http://semantic-ui.com/behaviors/api.html#1-automatically-routed-url-variables), but it doesn't work for dropdowns that get their options from a remote source apparently, and you get an error:

> API: Missing a required URL parameter: value /search?query={value}

Please see [this JSFiddle](http://jsfiddle.net/Banandrew/s06v38gu/) with developer console opened; I was expecting it to get `.search` value and replace the route `{value}` automatically. The only way to make it work as far as I'm concerned, is to specify `beforeSend` setting like so: [JSFiddle](http://jsfiddle.net/Banandrew/s06v38gu/6/).

You might also want to read [this StackOverflow question](http://stackoverflow.com/questions/33072593/semantic-ui-doesnt-replace-the-value-in-a-get-route-when-loading-dropdown-opt) to get more information on the issue.

**Comment by jlukic** [comment]
This wasn't something I considered, but should be adjusted to match how it functions in search, passing {value} into API.

**Comment by jlukic** [comment]
@Banandrew This is  already passed as `query`, miscategorized this issue.
http://jsfiddle.net/nex9ozzf/

Value refers to the currently set value, which doesn't seem relevant to pass with search queries.
