### ISSUE TITLE
Menus can go off the edge of the screen

### ISSUE THREAD

**Issue by timothyarmes** [Semantic-Org/Semantic-UI#3184]
Currently menus and sub menus can go off the edge of the window. This is a particular issue on a narrow mobile screen where to go completely outside of the .ui.container that's filling the width of the screen.

Is there a way to ensure that they are always pushed into the visible area?

**Comment by jarrettv** [comment]
I have this problem too. I had to redesign to work around the issue.

**Comment by meteorimpact** [comment]
I ended up writing code that would reposition menus before they're opened. I call it on the the open hook.

**Comment by smatt92** [comment]
@meteorimpact Please elaborate!

**Comment by Banandrew** [comment]
I understand that it’s been a while, is it still an issue? Can somebody please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to create a test case?

**Comment by vinayakkulkarni** [comment]
Closing this till test case is presented.

PS. meanwhile, visit [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord](https://discordapp.com/invite/8rr9bsg) for any usage related questions.
