### ISSUE TITLE
Themes do not respect @{googleProtocol}

### ISSUE THREAD

**Issue by b-connect** [Semantic-Org/Semantic-UI#3188]
The most themes do not respect the protocol. I think it would be better to add a global protocol variable for embedding background-images.

Example in 
src/themes/material/elements/header.overrides 

``` less
@import url(http://fonts.googleapis.com/css?family=Roboto);
```

**Comment by jlukic** [comment]
Themes do support overriding font-face, or globals like `@googleFontProtocol`. 

The reason that variables are not used in child themes is because the docs on semantic-ui.com do not actually support variables in `.overrides` for in-page preview.
