### ISSUE TITLE
REQUEST: input box for replying comment like facebook/quora style

### ISSUE THREAD

**Issue by yudaprama** [Semantic-Org/Semantic-UI#3190]
![screen shot 2015-10-15 at 11 18 32 pm](https://cloud.githubusercontent.com/assets/12010368/10520004/6503c594-7392-11e5-806f-cef0561ab0e4.jpg)

with semantic style, this would be better

**Comment by jlukic** [comment]
You can string this together with a segment, avatar image, icon input and button.
