### ISSUE TITLE
[Modal] { inverted: true } works only on the first run.

### ISSUE THREAD

**Issue by alexandretperez** [Semantic-Org/Semantic-UI#3192]
$('.ui.modal').modal({  inverted: true }).modal('show');

Shows the modal with white background. After you close it and then open it again the background is now black.

Run Code twice at "Dimmer Variations" section to see the bug:
http://semantic-ui.com/modules/modal.html#/examples

**Comment by jlukic** [comment]
This is a bug related to doc initialization (the modals are re-used in all the examples), but I don't believe a bug with SUI?

**Comment by alexandretperez** [comment]
I did some changes and now it works.

Was need instantiate the modal only once.

Here is the test case:
http://plnkr.co/edit/RnUqli4JnYIuxs9v88YC

**Comment by larsbo** [comment]
I got the same unexpected behavior. Here is a common use case with an modal which lost it's inverted state after fired once: http://jsfiddle.net/8x15wobw/
The same result with ```dimmerSettings```:
```js
dimmerSettings: {
	variation: 'inverted'
}
```

**Comment by brunotourinho** [comment]
same problem here, even in the Examples pages the bug occurs:

> http://semantic-ui.com/modules/modal.html#dimmer-variations

on the first call to inverted modal, the dimmer is clear, if you make a second call, the dimmer goes dark.

**Comment by avalanche1** [comment]
@larsbo , you should not instantiate your modal on every click.
http://jsfiddle.net/8x15wobw/1/
