### ISSUE TITLE
[Sticky] Offset scroll is not taken into account

### ISSUE THREAD

**Issue by lauri-elevant** [Semantic-Org/Semantic-UI#3193]
The issue is demonstrated here:
http://jsfiddle.net/mncqdqcw/2/

Essentially the Sticky behaves differently when initialized (or refreshed) depending if the scroll context is currently scrolled or not. 

The issue is fixed by adding these 4 lines of code to `save.positions` method (just after the measurements are taken and before they are used to update the cache object):

        element.offset.top  += $scroll.scrollTop();
        element.offset.left += $scroll.scrollLeft();			
        context.offset.top  += $scroll.scrollTop();
        context.offset.left += $scroll.scrollLeft();

This fix only applies to the overflow case. I suspect that since `.offset()`returns values relative to the document, then the problem does not appear with the default scroll context. But in cases when the scroll context does not conveniently align with what the `offset() ` function returns, the scroll position needs to be taken into account if we ultimately intend to use `position: sticky` which is again relative to the viewport.

From the docs I get the vibe that maybe Sticky is really only designed to work relative to the viewport only. If this is the case, I am willing to put in some work to also make it work in the `overflow: scroll` scenario. I think that in many cases the main content of a site/app may reside inside `overflow: scroll`..

**Comment by lauri-elevant** [comment]
I just realised that in the fiddle I created an edge case where context == scrollContext. In this case, obviously, the context offset does not need to be adjusted by it's own scroll value. The case where the 4 lines of code seemed to fix my issues was when the context was inside the scroll context.

**Comment by lauri-elevant** [comment]
It also seems that this also always assumes the scroll context to be viewport only:

    fits : ( element.height < window.height ),

This fixes it:

    fits : ( element.height < $scroll.height() ),

**Comment by jlukic** [comment]
@lauri-elevant I've added a fix for `$scroll` not used `body` in `1.2.5`

**Comment by lauri-elevant** [comment]
Wow, thanks a lot for the fix! :) I assume you are extremely busy these days (word gets around). We are mind-release right now so I will definitely evaluate this change after the dust settles here. Should I close the issue after it solves my initial problem? 

A quick look though - does it solve the "fits" part as well (see my comment a day ago).

**Comment by jlukic** [comment]
No it doesn't solve fit case, adding now.

**Comment by lauri-elevant** [comment]
Awesome! Thanks!
