### ISSUE TITLE
Trigger different sidebar at same time will incorrect problem

### ISSUE THREAD

**Issue by chenghsuan** [Semantic-Org/Semantic-UI#3194]
I have problem when trigger two different sidebar at same time.

I found a problem that first sidebar will not push the content to left  when I trigger first sidebar then trigger second sidebar and trigger first sidebar again.

If sidebar is triggered at different time that will be normal.

Here is my JSFiddle:http://jsfiddle.net/qukaty1y/1/

**Comment by jlukic** [comment]
Most likely you need to close one before triggering another, these things are temperamental

**Comment by jlukic** [comment]
You are attaching events on click, causing the event to get attached multiple times.
http://jsfiddle.net/uxqcqrh0/
