### ISSUE TITLE
Any idea on Localization?

### ISSUE THREAD

**Issue by DieterLi** [Semantic-Org/Semantic-UI#3198]
How can I translate the messages in js file into the corresponding local language? Thanks in advance.

**Comment by ohartl** [comment]
As stated in my issue #3239, you can set some translations like this
```js
$.fn.dropdown.settings.message = {
     addResult     : '<b>{term}</b> hinzufügen',
     ...
};
```

**Comment by nquintal** [comment]
Is the search control translatable the same way?
There doesn't seem to be a message properties.

**Comment by jlukic** [comment]
Any component that uses english text pulls it from a setting, or a settings function that generates text. If you examine the settings object at the end of the source code it should be clear.
