### ISSUE TITLE
[Form Validation] - same rules for server-side validation

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3199]
It would be nice to be able to use SUI's validation logic on server as well - not to duplicate all client rules manually. 
Any ideas on how to achieve that?)

**Comment by kapouer** [comment]
It seems nice, however in practice you often need more sophisticated rules on the form.
For example a server api might have a JSON schema, however a client form might want to check two email fields are equal before the form is successful.
So a good solution would let server rules define a default set of form rules, with the possibility to add more rules on the form.
An implementation might be to convert server rules to html5 form validation attributes (required and stuff), parse them back in client form as semanticui rules, and augment the rules from javascript or from custom data-attributes.

**Comment by avalanche1** [comment]
I'm talking more of being able to REuse SUI's already written validation logic and not reinvent the wheel.
Eg, adding and exposed API which can be called server-side?
