### ISSUE TITLE
Destroy modal?

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#3200]
Seems it isn't documented and it isn't working?

http://jsfiddle.net/Ln57snr5/

**Comment by jlukic** [comment]
Modal destroy does teardown correctly, I'm not sure why your example isnt working. I'll take a peek

**Comment by Wangable** [comment]
maybe u can write this at the beginning to 'solve' this problem:
$('body .modals').remove()

each time u write a .modal('show'), semantic will automatically add a <div class='ui modals xxxxx active'> dom in <body>, u can remove it before the next time u use modal.

**Comment by mariusk** [comment]
+1 for @Wangable's comment. This bug hit me in a React app I'm writing, where the modal stopped working after a component was unmounted and remounted again. The callbacks (`onApprove` etc) simply were not being called. The solution was to call `remove` on the modal in the `componentWillUnmount` method. Then everything seems to work as expected.

**Comment by JonathanRosado** [comment]
I encountered something very similar to what @mariusk describes. The modal eventually reaches a "dead" state where none of callbacks are called.

**Comment by jlukic** [comment]
The dimmer was not properly removing events in destroy. I've also modified the element namespace variable to make the code a little simpler to read.

**Comment by coolblabla** [comment]
http://jsfiddle.net/Ln57snr5/
still haven't fixed in next branch?

**Comment by aristidesfl** [comment]
2.2.3 is still affected http://jsfiddle.net/y80eLgau/

**Comment by cyberbobs** [comment]
@jlukic 2.2.6 is affected too http://jsfiddle.net/k286azas/

**Comment by larvanitis** [comment]
This issue should be re-opened until properly fixed.

**Comment by isawk** [comment]
we used an if/else statement to manage the modal, this way if it was ever created we just execute model("show") else it is created from scratch.

```javascript
if (typeof mdlComponentVar != 'undefined'){
//show if we had already created before     
 mdlComponentVar.modal( "show" );
}else {
//create otherwise
  var mdlComponentVar = ...
}
```

**Comment by jlukic** [comment]
I'll revisit

**Comment by paradissimon** [comment]
Yes please properly fix this. When the modal is closed, I'd like to have them totally removed from the DOM. I am creating them dynamically in a SPA app and can't afford to leak/have multiple instance of the same dialog lying around.

**Comment by jlukic** [comment]
Since the modal DOM is not created from `initialize` it would be unexpected for it to be removed from DOM on `destroy`. 

I think a solution similar to @isawk above makes sense to me, and is similar to what I currently do in my implementation on private projects.

**Comment by paradissimon** [comment]
I ended up manually removing all modals from thé dom before displaying
another one. Seems to work fine on my case.

**Comment by nix1** [comment]
> Since the modal DOM is not created from initialize it would be unexpected for it to be removed from DOM on destroy.

@jlukic Perhaps not removed, but since the original DOM is modified, can I get it back to the initial state?
I  easily end up with an empty active dimmer, which was not there initially.

**Comment by geemang2000** [comment]
This still seems to be a valid issue

**Comment by mariusk** [comment]
As my previous suggestion either did not work, or at some time stopped working, we did another look today to try to work around it. This time we found a workaround where we instead of explicitely calling `hide`, we return `true` from the `onApprove` method. Seems the state handling in the modal component gets a bit lost when we try to control showing and hiding explicitely.

**Comment by sido420** [comment]
This could become a breaking change for many apps, so whenever its implemented (if ever), we also need a boolean setting that tells Semantic *not* to destroy the DOM element on hide.
```
destory_on_hide: false
```
