### ISSUE TITLE
One field bluring will trigger other fields validate

### ISSUE THREAD

**Issue by xiwc** [Semantic-Org/Semantic-UI#3202]
![image](https://cloud.githubusercontent.com/assets/8816203/10562138/2ecaa1b2-757e-11e5-9e84-d840ad282e62.png)

**Comment by xiwc** [comment]
![Uploading image.png…]()

**Comment by xiwc** [comment]
One field bluring twice will trigger all other fields be validated.

![image](https://cloud.githubusercontent.com/assets/8816203/10562222/8c36a0a4-7582-11e5-84f6-4b7df4e09dcd.png)

**Comment by xiwc** [comment]
Why no answer???

**Comment by jlukic** [comment]
Sorry I'm currently facing over 100 unread messages on this boards. I'm trying to get through them as best as I can.

Calling form validate makes sure `onSuccess` and `onFailure` callbacks get called, which are currently only in `validate form`

**Comment by xiwc** [comment]
I'd like to know, it's your purposeful design or a bug.
But, i prefer one field bluring will only trigger current field, but not all fields;

**Comment by sconstantinides** [comment]
Would love to see a fix for this.
