### ISSUE TITLE
Icon suggestions - hidden and hover visible

### ISSUE THREAD

**Issue by kmalakoff** [Semantic-Org/Semantic-UI#3203]
I spent time trying to find a solution to slight layout changes with icons appearing and disappearing when hiding and showing them [through React adding and removing them from the DOM](https://groups.google.com/forum/#!topic/semantic-ui/r806RBjnh-I).

I found a CSS solution that keeps the icon on the page, but hides it using opacity. At first in react, I was doing something like display:none, but using the below, it is more like visibility:hidden.

// hide the icon through toggling the hidden class
i.hidden.icon {
  &:before { opacity: 0; }
}

// start the icon invisible and turn it visible on hover
i.hover.visible.icon {
  &:before { opacity: 0; }
  &:hover:before { opacity: 1; }
}

This is my first issue for Semantic UI so not sure if this is the right place to submit new functionality ideas, or if this already exists, or if I should be submitting a pull request. Let me know!

**Comment by jlukic** [comment]
There already exists `link` icon for this purpose. 

You can modify the starting opacity with LESS variables.

**Comment by kmalakoff** [comment]
@jlukic thank you for getting back on this. I'm really enjoying Semantic UI.

This is a proposal for an icon independent, semantic way to make any icon start hidden and then appear visible when hovered over. 

It is independent of less and independent of the `link` type of icon...a user may or may not want this as a global setting for links and may not be using less.

Anyways, no big deal, I'm just collecting utilities across projects and thought this might be useful.
