### ISSUE TITLE
[SELECT] action input w/o border-radius

### ISSUE THREAD

**Issue by olszak94** [Semantic-Org/Semantic-UI#3218]
Select tag has `border-radius: 0` whenever it's in `action input` class, and there's only select and button in action div.

[jsfiddle](https://jsfiddle.net/raff/b34uqf6z/1/)

I've tried to add some stuff to `elements/input.less` but no success.

**Comment by aphofstede** [comment]
Note: In Chrome the (more specific) user agent stylesheet entry overrides it with a 5px radius, so it might not show up in that browser. (I think it's an issue in itself that semantic-ui does does reset that radius)
