### ISSUE TITLE
dropdown auto selecting

### ISSUE THREAD

**Issue by thanush** [Semantic-Org/Semantic-UI#3221]
hi,
when i'm using search and  select in semantic-ui, either i  clear the input box value it's automatically selecting the first option value as you can see below the gif, http://codepen.io/thanushsz/pen/ZGVYJY,
please help me...

![drop](https://cloud.githubusercontent.com/assets/6806782/10628460/36a9b280-77e3-11e5-8107-7f8958cc3753.gif)

**Comment by ocervell** [comment]
I have the same issue. Specifically with multiple-select dropdown where when I click away from the dropdown, it still selects the value even if I didn't click on it...

**Comment by nojacko** [comment]
@thanush and @ocervell 

You need to disabled to "forceSelection" setting. http://semantic-ui.com/modules/dropdown.html#/settings

```
$('.ui.dropdown').dropdown({
   forceSelection: false
});
  
```

**Comment by Banandrew** [comment]
@nojacko Hi and thanks. Closing as resolved.
