### ISSUE TITLE
.attached.segment within a .aligned grid doesn't have proper width

### ISSUE THREAD

**Issue by jholl** [Semantic-Org/Semantic-UI#3225]
here's a [codepen](http://codepen.io/jholl/pen/rOJLZO)
using default theme

the styles add `width: 100%` to all `.segment:not(.compact)` within variations of `.aligned` grids/columns.  This overrides the necessary `.attached.segment` declaration of `width: calc(100% + 2px)` to account for the `margin: 0em -1px` on `.attached.segment`

**Comment by jlukic** [comment]
Fixed with #3226
