### ISSUE TITLE
[Rating] and MeteorJS: Cannot read property 'previousSibling' of undefined

### ISSUE THREAD

**Issue by bblackk102** [Semantic-Org/Semantic-UI#3227]
I am unable to initialize the rating system due to above error. It creates rating for first found item only and doesn't reflect the rating score.

Any ideas? Using newest Semantic UI package from Atmophere.

My code: 
```javascript
Template.eventsList.onRendered(function(){
    $('.events .ui.rating').rating({
        maxRating: 5
    });
})
```

**Comment by bblackk102** [comment]
Noticed it only happens on the first element of the set, my current workaround consists of creating a dummy hidden first element and initialize rating module in a for loop starting from 1.

**Comment by KiransHub** [comment]
I'm having this problem... how do you initialise them individually? Please give an example.

**Comment by orion110217** [comment]
Currently experiencing this bug, is there any work around?

**Comment by orion110217** [comment]
Setting the initial rating to something with decimal point recreates this bug, Tested with "2.2, 2.5, 3.5 ....."

**Comment by balint42** [comment]
This seems not exactly a bug but (confusing) undefined behaviour caused by using Floats instead of Integers as rating. The module should check and `throw` if `Number` is not an Integer.
