### ISSUE TITLE
Dropdown example from documentation

### ISSUE THREAD

**Issue by hubciorz** [Semantic-Org/Semantic-UI#3228]
Hi guys,

I have just noticed that one of the dropdown's example (the first one, to be exact) in docs looks strange after the animation is finished. Take a look at the screenshot.

Chrome 46.0.2490.71 (64-bit), OS X 10.11

![image](https://cloud.githubusercontent.com/assets/6502822/10674973/08385ee4-78fe-11e5-8454-c56584417ab8.png)

In Firefox it looks fine:
![image](https://cloud.githubusercontent.com/assets/6502822/10675058/70ff0d6a-78fe-11e5-8f39-486fd0342435.png)

**Comment by Banandrew** [comment]
Hey,

Chrome 46.0.2490.71 (64-bit) on Windows 10 here, everything seems fine—like in Firefox on the second screenshot.

**Comment by hubciorz** [comment]
Hi guys,

That was a problem with one of my Chrome extensions (Don't remember which one now). Sorry for the problem

**Comment by IonutBajescu** [comment]
Thanks for the update @hubciorz.
