### ISSUE TITLE
[MODAL] Vertical center with CSS

### ISSUE THREAD

**Issue by Keten** [Semantic-Org/Semantic-UI#3230]
Hi everyone!

Right now, the modal assign margin-top % for vertical centering. But, if the modals content increase during show... the vertial align fail.

So, how can I modify the display: block !important in the dimmer... for: 
display: -webkit-box !important ??

With this change, and remove margin-top % and adding in .ui.page.dimmer:
-webkit-box-pack (and for IE and firefox) this fix this issue for modals vertical alignment

Thanks!!

**Comment by IonutBajescu** [comment]
https://css-tricks.com/centering-css-complete-guide/
