### ISSUE TITLE
Sticky combined with table header?

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#3232]
Hi, is there a way to combine sticky with table header to have independently scrolling table body?
There are no details in the documentation, but sticky module seems universal enough to be combined with table header and body.

Thank you very much.

**Comment by kvetoslavnovak** [comment]
Closing, it is duplicate to https://github.com/Semantic-Org/Semantic-UI/issues/1357

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) now prepared a `stuck table` variant which provides horizontal scrolling with stuck left/right columns as well as stuck thead/tfoot for upcoming 2.9.0 by https://github.com/fomantic/Fomantic-UI/pull/2148
