### ISSUE TITLE
[Dropdown] Performance issue with calling dropdown() on many <select> elements

### ISSUE THREAD

**Issue by pulsingbrain** [Semantic-Org/Semantic-UI#3233]
I've noticed that there's a big performance difference between using normal `<select>` elements, and select elements with the '`ui dropdown`' class. 

In a particular project that I work on, I'm dynamically populating a table when the page loads, with up to 200 rows, where each row contains 2 drop down boxes. This means 400 select boxes on one page.  
This page loads significantly slower when I format the select elements as 'ui dropdown' and especially when I call: ` $('select.dropdown').dropdown();`.

I've prepared a JSFiddle to show the difference in dynamically populating a table with or without the ui dropdown selects: http://jsfiddle.net/costyn/dskvg042/.

Whether showing 400 select boxes on the same page is useful to a user, is another question and I will look into improving the UI to make it more user friendly, but nevertheless it seems there is some performance issue deeper down in semantic-ui which makes it slow to render select boxes.

**Comment by Banandrew** [comment]
Initializing a dropdown with pre-existing html allows for greater performance than initializing a dropdown directly on a select element (~190ms vs ~1050ms on my end). [Here's your JSFiddle that I changed a bit](http://jsfiddle.net/Banandrew/p3sLsvLf/).

Other than that, you could implement pagination for your table to improve performance, or show a user [a loader] (http://semantic-ui.com/elements/loader.html) while you're preparing your table.

**Comment by pulsingbrain** [comment]
I will try the trick with the pre-existing HTML, instead of building the HTML elements per select. I've already added a loader for the user, so that the user can see that something is happening in the background. 

Thanks for your feedback!

**Comment by pulsingbrain** [comment]
Creating the HTML up front works only partially. It does speed up the loading of the page, however to be able to react on the change in selection of the dropbox, I do need to set a unique id/name per select node (to be able to find back the selected values for each select node). Do, the HTML is not so static and needs to be build dynamically after all.

To avoid the long(er) load time, I did review the layout of the page and am now working with 1) a loader indicator and 2) with paging so the number of selects to load is limited and within reason for the user's experience.
