### ISSUE TITLE
Links in menu dropdowns not working

### ISSUE THREAD

**Issue by ohartl** [Semantic-Org/Semantic-UI#3234]
In atleast 2.0.0-2.1.4

It is not possible to make links, and with that i mean <a>-tags under .ui.menu .dropdown, basically means i'm using 100lines of my own code to make a top navigation work, not nice!

Changing in example: http://semantic-ui.com/examples/fixed.html
```html
..
      <a href="http://semantic-ui.com/examples/fixed.html#" class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item">Link Item</div>
          <div class="item">Link Item</div>
          ..
        </div>
      </a>
..
```
to
```html
..
      <a href="http://semantic-ui.com/examples/fixed.html#" class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <a href="#" class="item">Link Item</a>
          <div class="item">Link Item</div>
          ..
        </div>
      </a>
..
```
or to
```html
..
      <a href="http://semantic-ui.com/examples/fixed.html#" class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item"><a href="#">Link Item</a></div>
          <div class="item">Link Item</div>
          ..
        </div>
      </a>
..
```
will break the page and result in:
![Top: Chrome, Bottom: Firefox (Google is the a.item)](https://cloud.githubusercontent.com/assets/1349515/10701505/177c0e98-79c4-11e5-8dd1-a8dc9cc847d4.PNG)

**Comment by DaniellaGiovanna** [comment]
I'm experiencing the same on 2.1.6, why was this closed?

**Comment by ohartl** [comment]
The problem was solved by changing my html code to

```html
<div class="ui simple dropdown item">
    Dropdown <i class="dropdown icon"></i>
    <div class="menu">
        <a class="item" href="#">Link</a>
        ..
    </div>
</div>
```

otherwise it wouldn't be semantic ;)

**Comment by hems** [comment]
@ohartl on the current version swapping <div> by <a> is breaking the dropdown :(

**Comment by danillo10** [comment]
Not working!

**Comment by ohartl** [comment]
@danillo10 There might have changed something since 2015. What version are u using? Just saying it doesn't work won't help others
