### ISSUE TITLE
Search result URL doesn't seem working

### ISSUE THREAD

**Issue by darrenchiusw** [Semantic-Org/Semantic-UI#3237]
Hi, 

seems that even if i map the url field with the result, click on the result itself won't link to the url.
say, the search github example on http://semantic-ui.com/modules/search.html#/examples

if I click on the result, it won't bring me to the corresponding url?

Thanks

**Comment by Banandrew** [comment]
There's already an issue (#3111) about it, [this commentary](https://github.com/Semantic-Org/Semantic-UI/issues/3111#issuecomment-145523096) is a fix. You can either quickly change it yourself in `\src\definitions\modules\search.js` for a `standard` or `category` type, or wait for a 2.1.5 that will be available soon.

**Comment by fabienb4** [comment]
Fixed with #3206

**Comment by jlukic** [comment]
#3111
