### ISSUE TITLE
Multilevel menu always has "on: hover" for second level onwards

### ISSUE THREAD

**Issue by balupg** [Semantic-Org/Semantic-UI#3238]
I might be doing something wrong, but " on:'click' " seems to be working only on the top level drop down.
How do i enable on click for a multi level dropdown?

http://jsfiddle.net/Balupg/f2rb36ov/6/

Regards,
Balu

**Comment by kvetoslavnovak** [comment]
$('.ui.dropdown').dropdown({
 on: 'click'
});

**Comment by balupg** [comment]
Hi kvetoslavnovak,
Thank you for your response. If you look at the jsfiddle, you will notice that only the top level (File) take onclick.
The second level - (Publish to web) remains onhover no matter what I try. Any suggestions?

Regards,
Balu
