### ISSUE TITLE
semantic.js better localizable

### ISSUE THREAD

**Issue by ohartl** [Semantic-Org/Semantic-UI#3239]
I have to translate some messages (from semantic.js) that are displayed to the enduser in multiple languages. I'm trying to do this via overriding settings, but not all texts are available via settings.

A good example is "$.fn.dropdown.settings.messages", this is the optimum.
But in "$.fn.search.settings" and I'm sure also different components there is no way yet.

Would be nice if all text's were available via settings, thats all. Maybe for next minor version?

**Comment by DieterLi** [comment]
It works very well. For further question, I haven't met such kind of scenario. If I did, I will keep you posted. Thanks a lot, and great job!

**Comment by jlukic** [comment]
You can override localized texts per init or globally. If you need a single component to be translated to multiple languages simply modify `settings.messages` on init.
