### ISSUE TITLE
[UI] In-Place Content Editor

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#324]
Any chance we can get an in-place editable grid in Semantic UI?

http://vitalets.github.io/x-editable/

http://www.smartclient.com/smartgwt/showcase/#grid_editing_cell

**Comment by Kestanous** [comment]
:+1: Really starting to need this, any existing solutions? May have to use an alternative table for now, which would be a shame.

**Comment by cramrov** [comment]
Any progress on this?

**Comment by jlukic** [comment]
No immediate plans, use a different library for now.

**Comment by jlukic** [comment]
Focusing this discussion specifically on "in place editor"

**Comment by A-Lightning** [comment]
What about this: http://www.jqueryscript.net/table/Simple-jQuery-Editable-Table-Plugin-For-Semantic-UI.html
