### ISSUE TITLE
Does semantic have <input> with type='file'?

### ISSUE THREAD

**Issue by Wangable** [Semantic-Org/Semantic-UI#3241]
While using <input>, I didn't find 'file' type in the document...Does semantic have rewrite this?

**Comment by dsignr** [comment]
No, but sometime ago I wrote a custom file upload button. The idea is simple, make use of the `label for` property:

**Comment by Wangable** [comment]
OK, it seems good. Thanks a lot

**Comment by dsignr** [comment]
You're welcome :)
