### ISSUE TITLE
npm install just not work in Windows

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#3244]
OS: Windows 10 Pro
node.js: 4.1.2 (x64)
npm: 2.14.4

http://semantic-ui.com/introduction/getting-started.html
follow the well written doc above, got problems:.
1. when do "npm install semantic-ui --save", can not use arrow keys to select automatic/express/custom installation
2. If the install path is short, it work, but if the path is long (I can't find other differences, but the length of the path, all without spaces), in my case 63 chars, when do "gulp build", it can't find "semantic.json"

**Comment by jmitchem** [comment]
I'm using git bash on windows and also cannot use the arrow keys.
