### ISSUE TITLE
Not possible to use animated buttons inside accordion (conflict of classes)

### ISSUE THREAD

**Issue by niieani** [Semantic-Org/Semantic-UI#3247]
Accordion styles for `.content` while animated buttons also style for `.hidden .content` and  `.visible .content`. Since they use the same keyword, the button ends up not working.

**Comment by TrevorHinesley** [comment]
Has any progress been made on this?

**Comment by jlukic** [comment]
Can someone give a reproducible test

**Comment by TrevorHinesley** [comment]
Any accordion with any animated button in it will work. It uses the content
class so it applies the margin/padding to the button that is actually
intended for the content class that expands inside the accordion
On Thu, Apr 7, 2016 at 10:22 PM Jack Lukic <notifications@github.com> wrote:

> Can someone give a reproducible test
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/3247#issuecomment-207194398>
>
-- 
Trevor Hinesley
CTO, Soundstripe
http://soundstripe.com
c: (334) 790-4500
e: trevor@soundstripe.com

**Comment by avalanche1** [comment]
Closing until there's a test case.

**Comment by TrevorHinesley** [comment]
Here's a reproducible test:

```html
<div class="ui styled accordion">
  <div class="title">
    <i class="dropdown icon"></i>
    The button inside this accordion should look exactly like the one below this accordion
  </div>
  <div class="content">
    <p>But as you can see, it doesn't.</p>
    <div class="ui animated fade button" tabindex="0">
      <div class="visible content">Sign-up for a Pro account</div>
      <div class="hidden content">
        $12.99 a month
      </div>
    </div>
  </div>
</div>


<div class="ui animated fade button" tabindex="0">
  <div class="visible content">Sign-up for a Pro account</div>
  <div class="hidden content">
    $12.99 a month
  </div>
</div>
```

And here's the CodePen showing this code:

http://codepen.io/trevorhinesley/pen/NrPbBp

**Comment by TrevorHinesley** [comment]
Shouldn't this be moved from Needs Test Case to some other label?

**Comment by JamesNock** [comment]
This issue is still present in Semantic 2.4.1. Codepen here: https://codepen.io/H2ONOCK/pen/zbvRdr
