### ISSUE TITLE
What is the best way to set "@importGoogleFonts : false;"?

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#3248]
The question is there, here is a suggestion:

The doc says:

> Override files are used for providing additional CSS rules which modify the baseline definition. Variable > files allow you to modify the many underlying variables of Semantic.

Intuitively, **site.override**  should override **site.variables**, but it is not true, why not make it true?

Here is my idea:

> globals/site.variables (a)
> globals/site.override (b)
> site/site.variables (c)
> site/site.override (d)

steps to generate the final variables:

> 1. final_variables = (a)
> 2. final_variables = (b) override final_variables
> 3. final_variables = final_variables + (c)
> 4. final_variables = (d) override final_variables

For consistency, (a) and (c) should not contain same variables, or step 2 become 'override', and in concept it is the same as step 3.

**Comment by Banandrew** [comment]
Hi @playgithub, it’s been a while, I’ll be closing the issue as a usage question as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md). Please let me know if you still want me to comment on both of your questions.
