### ISSUE TITLE
2.1.0 breaks labeled icon menus with header items/dropdown items

### ISSUE THREAD

**Issue by kzvaigzne** [Semantic-Org/Semantic-UI#3249]
http://jsfiddle.net/e1fae29q/2/

~~Would it be possible to provide an option to go back to pre-2.1.0 `labeled icon menu`?~~
Using `labeled menu` seems to function as the old `labeled icon menu` does

**Comment by IonutBajescu** [comment]
Closing this since @kzvaigzne has already fixed the issue himself.
