### ISSUE TITLE
problem with IE11  in windows 10

### ISSUE THREAD

**Issue by playgithub** [Semantic-Org/Semantic-UI#3250]
```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
	<meta charset="utf-8" />
    <script type="text/javascript" src="semantic-ui/semantic.min.js"></script>
    <link rel="stylesheet" type="text/css" href="semantic-ui/semantic.min.css">
</head>
<body>
    <div class="ui left icon input">
        <input type="text" placeholder="username">
        <i class="user icon"></i>
    </div>
    <div class="ui left icon input">
        <input type="text" placeholder="password">
        <i class="key icon"></i>
    </div>
</body>
</html>
```

* IE11 in Windows 10

 JavaScript runtime error: 'jQuery' is undefined

* Chrome works fine.
* Firefox works fine.

With the uncompressed version, no such a problem.

BTW, as you see, I haven't reference jQuery library anywhere, why it works.

**Comment by playgithub** [comment]
With jQuery all works.
BTW, both semantic-ui and jQuery are in version 2.1.4

**Comment by dsignr** [comment]
Hi @playgithub, could you please fork this fiddle to describe your problem?:
http://jsfiddle.net/rduvhn8u/1/

Please check this page out :)
https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md

**Comment by playgithub** [comment]
http://jsfiddle.net/rduvhn8u/103/

I found there semantic.js and semantic.css, should be semantic_2.1.4.min.js and semantic_2.1.4.min.js,
this makes difference, only the min version does not work.

**Comment by playgithub** [comment]
http://jsfiddle.net/rduvhn8u/104/

min version has been used, the problem occurs.

**Comment by IonutBajescu** [comment]
The fiddle doesn't work. In any case, I'm closing this since I assume you've already figured it out.
