### ISSUE TITLE
Menu dropdown item width limitation

### ISSUE THREAD

**Issue by felixis-1** [Semantic-Org/Semantic-UI#3255]
I have a menu in which if there are dropdown items with slightly long text, and they have a sub menu. the styling break because the dropdown icon comes below the item text.

**Comment by Banandrew** [comment]
Hi @felixis-1, I know it’s been a while, but could you please provide a test case? You can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by felixis-1** [comment]
Hi @Banandrew, no idea. This was way too long ago. We can close this. I don't remember encountering something like this anytime in the last almost 2 years and have been working with Semantic UI a lot.
