### ISSUE TITLE
[Accordion] - Second level of nested accordion not opening properly (2nd lvl self closing)

### ISSUE THREAD

**Issue by kdkwiatkow** [Semantic-Org/Semantic-UI#3257]
Is this my fault or bug?
Click on 1 then on 1.1:
http://embed.plnkr.co/OY1Wfk1bizsmqXqRmOVF/preview

**Comment by jholl** [comment]
nested accordions should not have class `.ui` --- you init the component in js with a call to `.ui.accordion` but children are simply `.accordion` ... consider in Semantic that, generally, a component begins with `.ui.component` (some component) but child elements (`.content`, `.item`,`.accordion`) do not have the `.ui`... it's generally reserved for the component top level and then properties filter down.

**Comment by kdkwiatkow** [comment]
Accordingly to your answer @jholl I removed repeated `.ui` classes so only top level accordion has one now and changed selector for initializing accordion to `.ui.accordion`. It works OK now. Thx!

**Comment by jholl** [comment]
@kdkwiatkow, super!  you can close this issue and it'll be one less thing for the maintainers to track.

**Comment by kdkwiatkow** [comment]
Btw, would it be correct to place `.ui` at `<body>` to handle all semantic components?

**Comment by jholl** [comment]
clever, but no. This gets out of scope for the current issue, and isn't really related to Semantic so open up a topic on stack-overflow and I'll answer it there.

**Comment by kdkwiatkow** [comment]
Ok. Thx.
