### ISSUE TITLE
Form validation validating non-visible fields

### ISSUE THREAD

**Issue by chronosx7** [Semantic-Org/Semantic-UI#3259]
I have a 'three-fold' form where some elements are shown or hidden(via jquery slideUp/down) according to the value of other fields. When form validation is triggered, non-visible fields are validated by semantic resulting in unnecessary error messages.

Is there a way to tell semantic to ignore non-visible fields when validating a form?

**Comment by gbourgneuf** [comment]
Did you found a way to do this ? I want the same behavior but I don't know how to do it.

**Comment by chronosx7** [comment]
I could not find a way to do this with semantic(unfortunately) so I opted for jquery-validation. It allowed me to perform validation only on visible fields. In hindsight it should be possible to create whole individual(Yet related) forms and parse them individually.... but it adds to the number of elements you must handle and does not solve the problem when individual form fields are hidden based on the value of other fields within the same form.
