### ISSUE TITLE
Lato font import

### ISSUE THREAD

**Issue by rui-infotrack** [Semantic-Org/Semantic-UI#3273]
In semantic.css, there is (first line):
`@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');`

Shouldn't this be
`@import url('//fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');`?

I'm having trouble to download the css unless I change `https://` to `//`.

**Comment by jlukic** [comment]
See #1403 for explanation
