### ISSUE TITLE
[Form] Validation error 'range.indexOf is not a function' error when integer range not specified

### ISSUE THREAD

**Issue by oliverlloyd** [Semantic-Org/Semantic-UI#3274]
When specifying `integer` s the content type for form validation the docs say both `integer` or `integer[1..10]` are allowed. But using just `integer` returns the error: `Uncaught TypeError: range.indexOf is not a function` because range is passed as `false` and there is no guard against false when checking for range.

Fiddle: http://jsfiddle.net/v3tax6tk/

Docs ref:
<img width="776" alt="screen shot 2015-11-01 at 09 19 36" src="https://cloud.githubusercontent.com/assets/1336821/10868157/79e73abc-807c-11e5-81a3-9cfab0d21922.png">

This [line](https://github.com/Semantic-Org/Semantic-UI/blob/8875b89125e8a1b42b5f88ac3e28ab1dfe64ba9f/src/definitions/behaviors/form.js#L1199) does not check for `!range`.
```
      if(range === undefined || range === '' || range === '..') {
        // do nothing
      }
      else if(range.indexOf('..') == -1) {
        if(intRegExp.test(range)) {
          min = max = range - 0;
        }
      }
```

Relates to #3045 & https://github.com/Semantic-Org/Semantic-UI/pull/997

**Comment by jlukic** [comment]
#3045 fixes, in `2.1.5`
