### ISSUE TITLE
Infinite Scroll on Sidebar does not work.

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#3276]
Here is Infinite Scroll: http://jsfiddle.net/m67y78o0/
Here is Infinite Scroll on Sidebar: http://jsfiddle.net/r54bjbrd/

**Comment by faller** [comment]
It seems to be a bug. @jlukic

**Comment by jlukic** [comment]
You need to set the `context` on visibility to whatever scroll container you are using.

**Comment by faller** [comment]
thanks

**Comment by faller** [comment]
still not work. see http://jsfiddle.net/r54bjbrd/1/

**Comment by avalanche1** [comment]
Don't see any bugs. Closing until a valid test case.
