### ISSUE TITLE
Checkboxes are picky about location of labels, toggle stops working, checkbox hidden

### ISSUE THREAD

**Issue by emil-nasso** [Semantic-Org/Semantic-UI#3278]
Found an old issue for this, but i'm still having the problem.
https://github.com/Semantic-Org/Semantic-UI/issues/2457

I'm also having issues when i leave out the label.

The example should be clear enough to explain the issues i'm having.

http://jsfiddle.net/zebqz16s/

Let me know if any more information is needed.

**Comment by Anima-t3d** [comment]
Same as described here: https://github.com/Semantic-Org/Semantic-UI/issues/3659

**Comment by jlukic** [comment]
There is only a "next sibling" selector in CSS, no "previous sibling". So we cant handle label before input without javascript.

To fix, simply initialize the JS module which will handle this use case.
http://jsfiddle.net/pj77x6m3/
