### ISSUE TITLE
Checkbox cannot be checked

### ISSUE THREAD

**Issue by elgs** [Semantic-Org/Semantic-UI#328]
It seems when an <input ...> is wrapped by a div with "ui checkbox" class, the checkbox cannot be checked. I created a JSFiddle example to show this problem.
http://jsfiddle.net/elgs/R2wux/

**Comment by geomorillo** [comment]
please correct the docs on http://semantic-ui.com/modules/checkbox.html#/definition
```
<div class="ui checkbox">
    <input name="fun" type="checkbox">
    <label>Make my profile visible</label>
  </div>
```
this should be:
```
<div class="ui checkbox">
    <input id="fun" type="checkbox">
    <label for="fun">Make my profile visible</label>
  </div>
```

**Comment by AlexanderSk** [comment]
Hello, the usage page still shows the wrong code regarding the check box without the fix.
http://semantic-ui.com/modules/checkbox.html#/usage

<div class="field">
    <div class="ui checkbox">
      <input type="checkbox" name="hot-deals">
      <label>I agree to the <a href="#">Terms of Service</a>.</label>
    </div>
  </div>

The correct usage is described here: http://semantic-ui.com/modules/checkbox.html#/usage
with the id and the for attr in the label.

**Comment by ryoia** [comment]
@brigand , will leaving off the initialization process (.checkbox()) mess anything up? such as changes not being detect?

**Comment by TeemuKoivisto** [comment]
I do not know if this is how it's supposed to work but if you put label _before_ the input the checkbox can't be checked.

This doesn't work:
```html
<div class="ui checkbox">
  <label></label>
  <input type="checkbox">
</div>
```

This works:
```html
<div class="ui checkbox">
  <input type="checkbox">
  <label></label>
</div>
```

Makes it the more confusing as in vanilla CSS the checkbox works both ways. Very frustrating bug either way. Took me way too long to figure it out.

**Comment by sandervanmook** [comment]
I'm having this problem using Symfony 3 with Semantic-ui 2.2. I copied the bootstrap template that comes with Symfony and adjusted it to support Semantic. I keep having trouble getting the check / radio buttons to work as I can't select them. I did include the needed JS. If someone has a working template to support forms in Symfony 3 I would like to use it very much :)

**Comment by alanondra** [comment]
Using this in a Laravel project, importing via Laravel Mix after processing with Gulp. So far everything else works okay, except checkboxes, whether Javascript is used or not. For out-of-the-box behavior, this is frankly unacceptable.

**Comment by brigand** [comment]
This is a html thing, you need to associate the label with the checkbox if they're not nested.

```html
<div class="ui checkbox">
  <label for="foo"></label>
  <input id="foo" type="checkbox">
</div>
```

**Comment by alanondra** [comment]
It's not an HTML thing. The HTML is properly formatted. Even if I use the example code from the documentation, the checkbox does not change to the checked state. I attached event handlers on the checkbox, one for the click event, one for the changed event. The former fires correctly but the latter does not. Something in Semantic prevents checkboxes from changing state at all.

**Comment by jlukic** [comment]
There's no way we can support labels before inputs without javascript.

CSS provides an [adjacent sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors) which lets us add the "checked" x style to the label conditionally
```
input:checked + label {
 // format next label after an input differently
}
```
but does not provide a "previous sibling selector".

This is an obvious and unfortunate limitation of the css specification.

**Comment by alanondra** [comment]
In my case the label follows the checkbox, but the checkbox still refuses to change state, even if I manually alter the element to have the `checked` attribute. This isn't a problem if I'm not using Semantic UI.

**Comment by Banandrew** [comment]
Hi @alanondra, could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) to create a test case?

**Comment by alanondra** [comment]
[Forked](https://jsfiddle.net/1swzf55m/). Literally copypasta of the example code in the [form documentation](https://semantic-ui.com/collections/form.html).

**Comment by pbrooks04** [comment]
Hi @jlukic 

  I'm sorry to bother you, but from your response dated to Nov 6, 2013 (your first response in this thread) you wrote that the page was missing JavaScript. This was indeed the problem for my page and the solution fixed it no problem.

  But I am a little troubled because the in the documentation you cited, 

http://semantic-ui.com/modules/checkbox.html#/usage

one of the first things listed is: "A checkbox does not require Javascript to function". This seems like a contradiction to me. Do you mind shedding some light on the matter? Thank you.


PS Although this is my first post, I owe you many thanks for your ongoing help in responding to many other issues in other threads. Keep up the great work!

**Comment by Banandrew** [comment]
@alanondra Thank you. Remove `.hidden` from a checkbox’s `input`, and it should start working again. It sets a `z-index: -1` for it, and I’m not sure why it exists, because it seems absolutely unnecessary. I’ll take a closer look at it this weekend to see if it’s something that should be removed, in any case, sorry for the inconvenience, we’ll fix the documentation.

**Comment by Banandrew** [comment]
Hi @pbrooks04, this thread is quite old, and I’m not sure what Jack meant back then, but the checkbox component has always worked with and without JavaScript initialization.

**Comment by graham-sportsmgmt** [comment]
@Banandrew  I just got trapped by the "hidden" class as used in the very first example on the Forms page.  Removed this class as you suggested and it all works fine now.

What was the purpose of including hidden in the first place?

**Comment by Banandrew** [comment]
@graham-sportsmgmt Hi, I still don’t know, and the maintainer never joined the discussion.

**Comment by elgs** [comment]
I believe @jlukic is the author of the whole thing.
