### ISSUE TITLE
[Sidebar] - Sticky having incorrect positions when scrolling while sidebar is shown

### ISSUE THREAD

**Issue by charlesgael** [Semantic-Org/Semantic-UI#3280]
**Steps to Reproduce**
1. Have page with sticky and sidebar
2. Open the sidebar
3. Scroll in order to make sticky disapear
4. Close sidebar

**Expected**
Sticky should remain in position

**Result**
Sticky has an incorrect position and is hiding part of the page

**Testcase**
Can be directly tested here:
http://semantic-ui.com/modules/sidebar.html

**Comment by Banandrew** [comment]
@charlesgael Hi, this seems to be fixed, can you please confirm?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
