### ISSUE TITLE
Search make 2 requests!!!

### ISSUE THREAD

**Issue by ekzarov** [Semantic-Org/Semantic-UI#3282]
I`m using search for semantic 2.0 taken from semantic-ui site. I assume this is the latest version.
Am I wrong, that search.js makes double(twice) queries on one search situation.

Is it a bug or I`m doing something wrong? Thank you!

**Comment by Anachron** [comment]
Do you care to set up a limited text code?

**Comment by ekzarov** [comment]
Sorry, I have no clue about text code? What is this? You mean minCharacters? Or what?
Sorry, maybe I`m to silly :) please give some link or something...
Thank you in advance!

**Comment by jholl** [comment]
perhaps @Anachron meant _test_ code... can you set up a jsfiddle to show the double queries

**Comment by ekzarov** [comment]
Spent some time (first time to publish somethig in fiddle :)) ), but anyway:
http://jsfiddle.net/ekzarov/b34z7t7c/1/

Do I something wrong here?

**Comment by jholl** [comment]
I don't think it's firing twice.  I added the property `debug:true` (as in this [forked fiddle](http://jsfiddle.net/jholl/ohky3wet/)) then pulled up inspect/console.  When I focus on search for first time and type "uuu" I can see on console a single debug item for Search.  If I explore that, I can see all of the methods called; only once.

I do notice that clicking back on the jsfiddle window brings focus on the search input which does cause the event to fire again.

Are you still seeing double firing within debug? 
Is it related to focus?
If you change `searchDelay` property does that have relate to double firing?

**Comment by ekzarov** [comment]
Well, maybe, but I don`t think so. Locally, on my machine it`s making definitely 2 requests on 3(third) symbol. I make key press each 5 second, just to avoid some time sheet. Also my fiddler shows me 2 requests with the same parameters and same results returned. On jsfiddle part if you try to see in fiddler you will see also 2 requests. How time belongs to this issue? We have the same request, the same parameters and same result. Please try with fiddler. What do you see?

**Comment by ekzarov** [comment]
Ok, I think I`ve got it. It makes 2 requests on first query :) then it makes it only once. But there was some times (I think so), that even on second time(4 symbol) and third time (5 symbol) I have checked this bug.
