### ISSUE TITLE
Sidebar not able to close in mobile browser, if tapped on the sidebar launcher icon

### ISSUE THREAD

**Issue by romanzmykulova** [Semantic-Org/Semantic-UI#3285]
I found same bug as in earlier 1.x.x version, so i just copied message:

This issue is reproducable in http://semantic-ui.com/modules/sidebar.html also under examples/trigger sidebar.

In my page, I had used attach event for setting launcher btn for sidebar as below
$('#sidebar-right').sidebar('attach events', '.sidebar-toggle-btn')

Step1 -> clicking on the sidebar-toggle-btn, shows the sidebar.

Step2 -> When using in Desktop => clicking on the sidebar-toggle-btn, triggers the sidebar toggle event and since sidebar is already visible, it hides the sidebar as expected.

Step 2 again in Mobile => clicking on the sidebar-toggle-btn, triggers the 'clickaway' function as the button is part of the dimmed page, also it moves to showing of the sidebar as well but it also ends up calling sidebar toggle event based on the 'attach event' setting and ends up closing the sidebar.

Couldnt figure out why it happens only in mobile.

I tried in my Mobile browser(chrome) and through browser mobile emulation - both had same results.

Please help me out guys.

Thanks in Advance.

**Comment by Banandrew** [comment]
That seems to have been fixed.
