### ISSUE TITLE
[Dropdown] - Not Work Menu on IOS

### ISSUE THREAD

**Issue by ralamgstromg** [Semantic-Org/Semantic-UI#3288]
**Steps to Reproduce**
1. Add Dropdown With Menu
2. On Desktop works well, but in mobile IOS work but not selected change.

**Expected**
This wil work well in both, desktop and mobile, tested in safary and chrome on IOS.

**Comment by sconstantinides** [comment]
Not sure what your problem is but this may be helpful: https://github.com/Semantic-Org/Semantic-UI/issues/3304#issuecomment-241954237

**Comment by Banandrew** [comment]
Hi @ralamgstromg, what iOS version were you using when it was noticed?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
