### ISSUE TITLE
Help with SUI Upgrade on Windows

### ISSUE THREAD

**Issue by danr1979** [Semantic-Org/Semantic-UI#3290]
Hi.

I've been using SUI for around a year now (it's fantastic!), but in order to streamline the upgrade process for our team I want to use npm.  So far I have done:

    npm install semantic-ui
    gulp build

and have a working installation which I have customised for our needs to build to different output folders.

However, I have recently tried to upgrade from version 2.1.4 to 2.1.5 and I'm not sure things are working for me as they should.  I did:

    npm update

from within the semantic-ui folder where I originally did the install.  This runs through fine and when I check the semantic version number in the node_modules\semantic-ui folder I see 2.1.5 so that's great.  The problem is that this version is not mirrored in the semantic-ui installation directory because the semantic.json file in there still reads 2.1.4.  I tried doing:

    npm install

from inside the semantic-ui installation folder but I get a load of errors relating to a missing package.json file.  I appreciate that the package.json file is sitting in the node_modules/semantic-ui folder and not in the semantic-ui install folder and that is why npm is reporting an error so I assume what I have attempted here is wrong.

I have read all of the documentation on installs/upgrades here:

[http://learnsemantic.com/guide/expert.html#running-installer](http://learnsemantic.com/guide/expert.html#running-installer)

but they aren't clear on what to do in my specific case to ensure that semantic.json shows the correct version telling me that my installation is running the latest version.

Could someone give me a hand understanding what I am doing wrong and what I need to do to upgrade cleanly please?

Many thanks.

**Comment by larsbo** [comment]
In my case running ```npm update``` didn't update semantic ui, my package.json still contained ``` "semantic-ui": "^2.1.4"```.
So I tried ```npm install semantic-ui@2.1.6``` which worked fine.
After switching into ```semantic/``` and ```gulp build``` I got the latest semantic ui version running.

Hope this helps :)

**Comment by danr1979** [comment]
Fantastic!  Thanks, that did it!
