### ISSUE TITLE
Unable to store complex data for each item of a dropdown

### ISSUE THREAD

**Issue by nathanpalmer** [Semantic-Org/Semantic-UI#3293]
Something we support on the Semantic-UI-Ember side is storing a model for each item of the dropdown and setting that model when it's selected. This works great for when you're setting up a relationship within Ember-Data.

However, it seems this change casts anything within data to a String and breaks this functionality completely.

https://github.com/Semantic-Org/Semantic-UI/commit/c43ea73f7f0622441dc13cbee067ecbb1114c5b9#diff-dbb1b936fdad1f63b3a01f86d9a54fd1L1565

For now we've downgraded to version 2.0.8 which is right before that part was released.

Here is an example of how we're using it: https://github.com/Semantic-Org/Semantic-UI-Ember/blob/ce7cff9b40a2d83f1231dd081f3dec878b195d93/tests/dummy/app/templates/modules/dropdown.hbs#L52

**Comment by jlukic** [comment]
Since dropdown is designed to replicate selection for an `input` it passes around strings for value which fixes issues when preset values like `<input value="false">` are compared to values set in javascript programmatically.

**Comment by nathanpalmer** [comment]
It makes sense when you're trying to match up with values that were defined in HTML only.

However, in our rich javascript world everything is wrapped in a component and upon initialization it is setting the value to what it should be. Having to work with strings will add some unnecessary complexity to any dropdowns that we have because on each value change we'll need to search the data store for the right corresponding record and then emit it from the component. Where-as now each record is bound to the item itself so we simply take that and return it.

From Semantic-UI-Ember we're trying to keep it a lightweight library on top of Semantic-UI since I find it unnecessary to re-implement the Javascript parts that have already been developed.

**Comment by nathanpalmer** [comment]
@jlukic I believe we have a good workaround for this with a component wrapper on the ember-side. We're using it on one of our apps now and will integrate it into Semantic-UI-Ember soon.

**Comment by jlukic** [comment]
Cool let me know how it goes.
