### ISSUE TITLE
[Popup] - config.inverted does nothing

### ISSUE THREAD

**Issue by mkoczorowski** [Semantic-Org/Semantic-UI#3294]
**Steps to Reproduce**
1. Do something
initialise popup with config.inverted = true

**Expected**
The Popup should be reverted

**Result**
The Popup does not do this

**Comment by IonutBajescu** [comment]
If anyone lands here, please use the "data-inverted" attribute as specified in the docs.

**Comment by uyab** [comment]
Please check https://github.com/Semantic-Org/Semantic-UI/issues/3367
