### ISSUE TITLE
Lists Inside Grid

### ISSUE THREAD

**Issue by xcrap** [Semantic-Org/Semantic-UI#3295]
```html
<div class="ui row stackable grid">
    <div class="ui relaxed list">
          <div class="item">
            <img class="ui avatar image" src="/images/logo_facebook.png">
            <div class="content">
              <a class="header">Rachel</a>
              <div class="description">Last seen watching <a><b>Arrested Development</b></a> just now.</div>
            </div>
          </div>
          <div class="item">
            <img class="ui avatar image" src="/images/logo_facebook.png">
            <div class="content">
              <a class="header">Lindsay</a>
              <div class="description">Last seen watching <a><b>Bob's Burgers</b></a> 10 hours ago.</div>
            </div>
          </div>
</div>
```

When having a list inside a grid container the images are not left align. 
Only the last one from the list. http://imgur.com/ATJccjD
I wonder if anyone encounter this problem or have a workaround.

**Comment by jlukic** [comment]
No elements can exist inside grid but column or row. See docs

**Comment by xcrap** [comment]
Actually it's inside a column, I forgot to copy the entire code because it's way bigger.

The list It's inside column:  <div class="ui four wide column">
The problem is that the .content with inside-blocks breaks with shorts width's in a list. 
In my situation using <div class="content" style="max-width:80%;"> works as a fix.
