### ISSUE TITLE
inverted divided grid .row:first-child:before bug

### ISSUE THREAD

**Issue by nautiluszrb** [Semantic-Org/Semantic-UI#3299]
Guys, found small bug
https://monosnap.com/file/0kuUgWjmzj2Blts5DCaegcc0AWOciD

**Comment by IonutBajescu** [comment]
Could you please create a jsfiddle with the minimum amount of html to reproduce this issue? As it is at the moment, we can't really figure out what the issue is from the screenshot. 

Feel free to reopen the issue once you've done that.
