### ISSUE TITLE
[Icon] - Missing font awesome 4.3 icons

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#3302]
Only submitting this because of the statement on the icons documentation page:
"Semantic includes a ***complete*** port of Font Awesome 4.3 designed by Dave Gandy for its standard icon set."

So far I only noticed 2 missing

**Icons missing:**
fa-balance-scale
fa-hourglass

**Comment by jlukic** [comment]
Balance scale is 4.4 http://fortawesome.github.io/Font-Awesome/icon/balance-scale/
as well as hourglass http://fortawesome.github.io/Font-Awesome/icon/hourglass/
