### ISSUE TITLE
Mobile - Iphone 6s dropdown - show on touch then closes immediately after animation.

### ISSUE THREAD

**Issue by amnevins** [Semantic-Org/Semantic-UI#3304]
Meteor.js environment.  Once project is in production, select elements converted to dropdowns, and dropdowns on IPhone 6s device, open on touch then immediately close after animation transition.  

Works in these cases:
- Touching the label will result in normal dropdown behavior. 
- If finger is held on dropdown it displays and stays open for selection.  

Dropdowns are working on Samsung S4 devices in every fashion implemented.

Is there a workaround for IPhone to exhibit expected behavior?

**Comment by activeperception** [comment]
+1 (Ipad + chrome)

**Comment by aessig** [comment]
Definitely an issue ! +1

**Comment by AbhishekBiswal** [comment]
@amnevins @activeperception @aessig
Don't run the dropdown initialization command on an iOS cordova app and it will use the native select functionality.

**Comment by sconstantinides** [comment]
This is a pretty major issue.

Oddly enough the "search" dropdown (.ui.search.dropdown) works fine for me on mobile. It's a pretty minor hack to the hide the search functionality...

```
.ui.search.selection.dropdown {
    > input.search {
        display: none;
    }

    .icon {
        left: 0;
        right: 0;
        margin-left: 0;
        margin-right: 0;
        padding-right: 1em; // adjust to taste
        text-align: right;
    }
```

**Comment by jrodgers87** [comment]
+1 Issue is still present in iOS, and oddly enough it is also happening for me in chrome, but only on mobile devices, and only in the browser. As an Android cordova app it doesn't work.

**Comment by arggh** [comment]
This happens on Meteor apps if package `fastclick` is installed (basically includes [ftlabs/fastclick](https://github.com/ftlabs/fastclick). Adding the class `needsclick` to the dropdown element as instructed in fastclick documentation does not help.

Quite annoying, since using `fastclick` is the de-facto choice for having a snappy mobile UX.

**Comment by AbhishekBiswal** [comment]
@arggh Try using this package instead of fastclick : https://github.com/versolearning/meteor-fastclick

**Comment by arggh** [comment]
@AbhishekBiswal The package you linked seems awfully outdated. The readme says " Once we can verify that a fix is merged by MDG, we can deprecate this package again.".. Do you know more of this issue? I couldn't find anything in the Meteor issues.

**Comment by MrHidalgo** [comment]
+1 iPhone 6s
