### ISSUE TITLE
[Sidebar] Remove Transform Hack from Sidebar Children

### ISSUE THREAD

**Issue by grovduck** [Semantic-Org/Semantic-UI#3306]
When embedding a dropdown within a sidebar, there is a CSS rule that is apparently interfering with the dropdown items being selectable.  I've posted on [stackexchange] (http://stackoverflow.com/questions/33619951/dropdown-items-within-sidebar-not-selectable-semantic-ui) and J4G's overriding rule works for me.  

The original jsfiddle that demonstrates the issue is at: http://jsfiddle.net/aqr81wzr/1/.

**Comment by harangue** [comment]
+1 Weird issue.

**Comment by jlukic** [comment]
Perhaps this rule can be taken out. The git blame doesn't really explain to me why it was there in the first place. Its a bit brutal.

**Comment by jlukic** [comment]
Fixed in `2.1.7`, transform hack removed.
