### ISSUE TITLE
Bug with message ui error

### ISSUE THREAD

**Issue by gilperon** [Semantic-Org/Semantic-UI#3308]
I have this code:

        <div id="xxx" class="ui error message hidden">
        
        	<i class="close icon"></i>
        
            <div class="header">Correct the errors:</div>
            
            <ul class="list"></ul>
            
        </div>

The problem is that I need to show/hide the error message but $("#xxx").transition('fade'); toggles the visibility of the error message. I mean, everytime I call transition('fade') in the first time it shows up, the second it hides, the third it shows up... I would like to have a "safe" call where I can $(this).parent().transition('show up'); and it shows up, even if I call it twice or 10 times. Is there a reliable function on semantic-ui that allows me to make the "fade" work without toggling?

**Comment by jlukic** [comment]
Use `fade in` and not `fade`. If you dont specify a direction it will assume you are transitioning in and out of view.
