### ISSUE TITLE
Sidebar scrollLock not work v.2.1.6

### ISSUE THREAD

**Issue by gboslee** [Semantic-Org/Semantic-UI#3309]
I tested
jQuery v.2.1.4 and v.1.11.3
Crome 46.0.2490.80 (64-bit)

Scroll bar of the main window is active

**Comment by Panman8201** [comment]
Humm... I'm noticing the same thing but being new to Semantic UI I'm not sure what is intended to happen.

**Comment by roomhero** [comment]
I have the same problem in Chrome.

**Comment by nburns217** [comment]
Bump, same issue here, any information from the dev team?

**Comment by seenasabti** [comment]
Its 2019 and no solution yet...

**Comment by kangwhiwon** [comment]
still
