### ISSUE TITLE
Bug using TAB

### ISSUE THREAD

**Issue by gilperon** [Semantic-Org/Semantic-UI#3310]
Hi,

I created a form using your own provided code and also used the tabindex as follow:

        <div class="ui green ok inverted button" tabindex="0">
        
        	<i class="checkmark icon fechar"></i> Fechar
        
        </div>

When I hit TAB the button gets focused (right!) but when I press enter, space... nothing happens. There is no point using TAB if you cant simulate a press on the button with ENTER or SPACE. Does this bug has an easy fix that I can change on the code provided by you?

**Comment by jlukic** [comment]
Use `<button>`

**Comment by gilperon** [comment]
Yeah, with button it works but semantic ui DOCS says that using tabindex on any element should work just fine. Anyway, thanks.!
