### ISSUE TITLE
Regex validation rule not working as expected

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#3313]
I'm having an unusual issue with a regex validation rule. It seems to work in some cases, however I'm trying to use it to validate a date however it's saying that the date is not valid, even though it is.

http://jsfiddle.net/efp8z6Ln/260/

This fiddle shows an input field with a valid date value being validated using a regex. The regex itself works as demonstrated, and matches what it should, yet the form validation still returns false.

**Comment by elbouillon** [comment]
I'm also having an issue with regexp validation.

This regexp : regExp[/^\+[0-9]{11}$/]
Don't validate +41791234567

I have that message in web console : 
Uncaught SyntaxError: Invalid regular expression: /^+[0-9]{11}$/: Nothing to repeat

**Comment by douglasg14b** [comment]
I'm also having regex validation issues with dates.

https://jsfiddle.net/tL5xx6m9/2/

**Comment by diuzzoli** [comment]
Is there a solution to this issue? 
I tried execute several RegExp with Semantic-ui form validation but always returns invalid field value.

**Comment by rishirebel** [comment]
Hi 
I was trying to use RegExp /(19|20)\d\d[/](0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])\s(0[1-9]|[12][0123])[:][1-6]\d/
for getting a date and time format like 1998/04/04 23:40, but it does not validate the same. I tested my RegExp several times on Regex testers, it works fine there, but it is not validating correctly on semantic ui

**Comment by Iheff** [comment]
+1

**Comment by Iheff** [comment]
Don't forget to double escape all the things. //d not /d for a digit for example.

**Comment by jlukic** [comment]
Can someone give me a simple js regexp that is not evaluating correctly? I would love to fix

**Comment by elbouillon** [comment]
Hi @jlukic, I don't remember exactly, but the problem is not regex, but mixing short rules and complet rules. There is  a thread mentionning that

**Comment by frangeris** [comment]
Having the same issue here, but with an string:

RegExp
`regExp[/rgb\((\d{1,3}), (\d{1,3}), (\d{1,3})\)/i]` 

String
`rgb(243, 243, 243)`

Regular expression tested here...
[https://regex101.com/r/gS7bD8/1](https://regex101.com/r/gS7bD8/1)

Where's the issue?

**Comment by frangeris** [comment]
@Iheff you're just right 👍 , for future references, I found the same solution [here](http://stackoverflow.com/questions/34684043/semantic-ui-regex-parser-does-not-seem-to-work-correctly?answertab=active#tab-top).

**Comment by jlukic** [comment]
I'll try to look over this as the last issues to put into `2.2`

**Comment by Iheff** [comment]
Have you double escaped that?

**Comment by daltonamitchell** [comment]
I had a similar issue with date validation but double escaping fixed it. Is this mentioned anywhere in the docs?

**Comment by Iheff** [comment]
It is touched on, I think, although I cant find it for looking now. I think I googled my way to an answer* on it but thought it would be good to leave it somewhere further up the google trail. 

*  [top answer on SO here: http://stackoverflow.com/questions/34684043/semantic-ui-regex-parser-does-not-seem-to-work-correctly]

You’d figure it out eventually though because it’s taking a string to pass a function that will run the regex so after a bit of head scratching it makes sense it should be re-escaped.

**Comment by newswim** [comment]
I was about to post an issue, having a hell of a time validating a phone number (which can be difficult in a lot of settings...)

**DOUBLE ESCAPE** special characters. 

ex. `\\d`

thanks @Iheff

**Comment by jlukic** [comment]
I've added a new syntax to make it simpler to pass in regular expressions 

Instead of using bracketed notation, you can now pass in a `value` with a non stringified RegExp
```javascript
$('.ui.form').form({
    fields: {
        date: {
          identifier: 'color',
          rules: [{
            type: 'regExp',
            value: /rgb\((\d{1,3}), (\d{1,3}), (\d{1,3})\)/i,
            prompt: 'test'
          }]
      }
    }
});
```

**Comment by jlukic** [comment]
I've also added this specific example to usage section of form validatio to make it more clear.

**Comment by newswim** [comment]
Thanks @jlukic !

I think this makes the validation a little more intuitive.
