### ISSUE TITLE
Checking checkbox with js

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#3314]
Hi, I have  checkbox like this:

                    <div class="ui toggle checkbox">
                    
                        <input type="checkbox" id="xxx">
                        
                    </div>

I need to make this checkbox checked with javascript. I tried the line of codes below and none work:

$("#xxx").checkbox("check");
$("#xxx").checkbox("action","check");
$("#xxx").checkbox("set checked");

**Comment by kolier** [comment]
This way:
```
<div id="xxx" class="ui toggle checkbox">
    <input type="checkbox">
</div>
```
