### ISSUE TITLE
Select dropdown - behaves oddly when clicking "Default text"

### ISSUE THREAD

**Issue by wreyniers** [Semantic-Org/Semantic-UI#3316]
I found this behavior on: http://semantic-ui.com/collections/form.html under "Send Receipt To:"

![select weirdness](https://cloud.githubusercontent.com/assets/2293035/11107447/2d7f0e3a-889b-11e5-87fa-ad8fb8b5ee91.gif)

**Comment by IonutBajescu** [comment]
Doesn't appear to be an issue anymore, it might've been fixed in the recent releases. 

@wreyniers feel free to reopen if the issue still exists on your machine.
