### ISSUE TITLE
[Sidebar]right menu will missing when sidebar visible

### ISSUE THREAD

**Issue by zmcool** [Semantic-Org/Semantic-UI#3317]
Hi,I am using SUI create my project and I met a problem.
When sidebar visible,right menu will missing
like this:
http://jsfiddle.net/rduvhn8u/107/
http://jsfiddle.net/rduvhn8u/108/
is this a bug or used incorrectly?
Thank you

**Comment by hierarchycms** [comment]
try add overlay class to avoid default behavior like this
```
<div class="ui left vertical menu visible overlay sidebar">
```

**Comment by Panman8201** [comment]
I'm seeing a similar issue; the right menu appears initially, stays in place when the sidebar is opened, but disappears once the sidebar is closed (but also re-appears when the sidebar is re-opened). My HTML layout is slightly different too, the menu and sidebar are at the same level (children of `<body>`).

While on my Android device using Chrome, I noticed some weird overflow stuff going on (I could pinch-out and see extra "gray" area to the right). It seemed like the right menu was likely still there but out of view, farther right, in that "gray" area. Oddly, scrolling down suddenly brought it back into view and the overflow "gray" area went away. So, I'm unsure if this is a Semantic UI issue or more of a browser thing...

**Comment by Banandrew** [comment]
It’s been a while, I explained it [here](https://github.com/Semantic-Org/Semantic-UI/issues/5200#issuecomment-289288498); closing as a duplicate.
