### ISSUE TITLE
How do we make things work?

### ISSUE THREAD

**Issue by trusktr** [Semantic-Org/Semantic-UI#3319]
Documentation only shows HTML snippets. Is that all we need to do? Or do we need to call things like `$(el).dropdown()` to make dropdowns work?

If so, where's this JavaScript API documented?

**Comment by trusktr** [comment]
Ah, I didn't see the "usage" tabs, as @ingrimmm [pointed out on Gitter](https://gitter.im/Semantic-Org/Semantic-UI?at=56451e1b10f6aea94fdd7ffb). It wasn't obvious to look there. My first thought would be that, while in the "definition" tab, clicking on the button to view the source would also show the JavaScript, not just the HTML.

**Comment by jholl** [comment]
Looking for left sidebar 'Modules' section ?

You do need to init certain things

**Comment by trusktr** [comment]
Re-opening. Things aren't clear. So when I click on "Menu" under the "Collections" section of the sidebar, I don't see the JavaScript usage there. I just see HTML examples.

**Comment by trusktr** [comment]
Or are those menus purely CSS based and we need to swap classes ourselves?

**Comment by jholl** [comment]
The first example for menu is a little tricky because it uses popup and dropdown.

[codepen](http://codepen.io/jholl/pen/WQLjBg)

This what yr looking for?

**Comment by trusktr** [comment]
For sure. It'd be really nice if those examples showed the JavaScript too. I'm capable of digging through the source and figuring it out, but it'd be a lot easier if it were just right there.

**Comment by jlukic** [comment]
http://semantic-ui.com/modules/popup.html#wide-popup-menu
Example is right here, with code

**Comment by steve-ross** [comment]
I tend to agree that it is easy to miss the 'examples' tab when viewing the docs (ran into the same problem when i first started using semantic)

**Comment by xDaizu** [comment]
So... reclose?
