### ISSUE TITLE
Bug: Showing/hiding modals while previous animation in progress

### ISSUE THREAD

**Issue by space-alien** [Semantic-Org/Semantic-UI#3320]
Please see this fiddle: http://jsfiddle.net/as1e6frd/

Update: The problem may not occur on the first run. Re-run the fiddle if necessary!

It seems that if we try to show or hide a modal while a previous show/hide is in progress, we get into a mess.

Now see this much more interesting fiddle: http://jsfiddle.net/ksw2ambq/

Despite explicit 'show' and 'hide' calls, the modal is clearly broken. Worse, the 'onShow' and 'onHide' functions are still called, even though the modal is no longer being shown or hidden.

**Comment by Dynasty9** [comment]
:+1: I've had issues with this.

**Comment by lubber-de** [comment]
Fixed in [Fomantic-UI](https://fomantic-ui.com)
See your adjusted example here http://jsfiddle.net/xuk3yswg/
