### ISSUE TITLE
Model's dimmer can't hide auto when there is a page dimmer. 

### ISSUE THREAD

**Issue by puzzlex** [Semantic-Org/Semantic-UI#3322]
Like #766.

There is a page dimmer in my page like the one on the docs  http://semantic-ui.com/modules/dimmer.html .
Then, when I open a modal, It worked.  
Then when I click on the modal body, some thing happend.I can't describe it.

Util this, Everything looks normal. When I click the dimmer of modal, the model's body is disappeared, But the dimmer still display!! 

I don't understand why this happend.

My English is weak to describe this problem,so , there is code:

<div class="ui page dimmer hidden" id="pageloading">
<div class="content"><div class="ui text loader">Loading...</div>
</div>

<div id="settingpanel" class="ui modal form">
... the form
</div>

$('#settingpanel').modal('show');

**Comment by puzzlex** [comment]
News.
Only when the page dimmer directly under the body tag, this bug can be reproduced. If I move the page dimmer into a other div, all works normaly.

**Comment by jholl** [comment]
Can you reproduce it in a jsfiddle?  Thanks.

**Comment by Banandrew** [comment]
It’s been a while, we can probably close the issue until there’s a test case.

**Comment by brendon** [comment]
This still exists. See this fiddle: https://jsfiddle.net/ca0rovs3/1286/

It's a weird one to trigger. In my implementation it just triggers anyway, but in the fiddle you need to click the space below the buttons on the modal. You'll see something funny happening in the background and then when you close the modal, one of the dimmers still exists.

The workaround is to put your custom dimmer into a div off of the body element.

![2018-11-06_12-51-44](https://user-images.githubusercontent.com/81871/48034124-f4193d80-e1c2-11e8-83f7-19a9b198407a.gif)
