### ISSUE TITLE
Javascript file not specified in the bower.json

### ISSUE THREAD

**Issue by yboenec** [Semantic-Org/Semantic-UI#3325]
Hi,

I'm using yeoman and the angular generator. When i'm building my project with grunt (using the command line 'sudo grunt build'), semantic's js files are not included in my index.html. I saw that the js file is not specified in the bower.json of the semantic component. 

So, I put in the bower.json
"main": [
    "transition.css",
    "transition.js"
  ]

This works fine but I want to know if this is the right way or an error.

Thank you.

**Comment by IonutBajescu** [comment]
Closing since this is no longer an issue.
