### ISSUE TITLE
Dropdown has a some problems. Need to fixing.

### ISSUE THREAD

**Issue by gokhanege** [Semantic-Org/Semantic-UI#3329]
I am created current problems. Is there something I missed? Thanks.

http://jsfiddle.net/gokhanege/f604Lqbz/

**Comment by jholl** [comment]
try using the [oss cdn links](http://osscdn.com/#/semantic-ui)

**Comment by jlukic** [comment]
Since dropdowns use `input` for storage, you're limited to strings (how input stores values). 

This prevents issues with type conversion when a component is initialized from an <option> or <input> with a preset value.

**Comment by IonutBajescu** [comment]
See above reply for closing reason.
