### ISSUE TITLE
semantic is not compatible with RTL languages

### ISSUE THREAD

**Issue by rasulian** [Semantic-Org/Semantic-UI#3330]
Today i just started pulling semantic-ui using npm and specified it for RTL languages and when I tried some Elements and modules but most of them didn't work correctly.
I captured some screenshots:

![hello](http://up.ashiyane.org/images/g7m42yltrb8bqo5r0uhr.png)

**Comment by jlukic** [comment]
Set `rtl: true` in your `semantic.json` to compile SUI with RTL settings.

**Comment by rasulian** [comment]
Already I've been set that to true.
It's my base html code:
```html
<!DOCTYPE html>
<html lang="fa">
<head>
	<meta charset="UTF-8">
	<title>صفحه اصلی</title>
	<link rel="stylesheet" type="text/css" href="semantic/dist/semantic.rtl.min.css">
	<script src="semantic/dist/semantic.min.js"></script>
</head>
<body>
<div class="ui action input">
  <input type="text" placeholder="جستجو...">
  <button class="ui icon button">
    <i class="search icon"></i>
  </button>
</div>
</body>
</html>
```
