### ISSUE TITLE
Wierd layout bug on ui horizontal divider header with an icon and some text when using React

### ISSUE THREAD

**Issue by silentwarrior** [Semantic-Org/Semantic-UI#3338]
Hello.

I have the following html snippet: 
```
<h4 className='ui horizontal divider header'>
                <i className='tag icon'></i>
                Basic Information
</h4>
```
Renders into something like: 
![Correct Example] (http://puu.sh/lnzJK/8bfb215a7a.png)

However, React will render this with the "Basic Information" inside a <span> element, since React has to "block in tags" every single renderable element.

Thus, this results in the following HTML (with some extra react ids and such that I removed) :

```
<h4 className='ui horizontal divider header'>
                <i className='tag icon'></i>
                <span>Basic Information</span>
</h4>
``` 
Renders into something like : 
![Incorrect Example] (http://puu.sh/lnzLB/e9e7a0b22d.png)

How can I fix this?
I can manually make it so that the "Basic Information" text is rendered inside a <span> or a <div> or anything for that matter with my own class/styling.

Also, I could be wrong, but I think the "correct example" as shown in the documentation of Semantic UI is actually incorrect HTML5, since its basically a orphaned child element.

**Comment by IonutBajescu** [comment]
Closing this since React doesn't wrap the floating text nodes in span elements anymore, more specifically since React v15 (2016-04-06) .
