### ISSUE TITLE
Multiple cards with same width centered

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI#3341]
I have been trying to center multiple cards, showing up side by side, but centered inside a container. Does anyone have a solution?

![screen shot 2015-11-17 at 6 05 23 am](https://cloud.githubusercontent.com/assets/2978646/11199641/3acd3756-8cf1-11e5-9272-0648d7c9033c.png)

They seem to stick to the left side, or take all available space.

**Comment by sylvaindeloux** [comment]
+1
