### ISSUE TITLE
Name !!! difficult

### ISSUE THREAD

**Issue by crperlin** [Semantic-Org/Semantic-UI#3344]
I found the name a little difficult ... very discrete memory, why not consider prefix naming it?
A similar bootstrap, foundation so;
such as :`btn-sm`,` btn-lg`

There are individual components that need to display more than one class of an effect, this is a little similar to building blocks, but if used for development, sometimes you need to add yourself to some special classes for judging, so it is very bloated ...

All kinds of little friends what a good idea it can be optimized?

**Comment by jlukic** [comment]
No
