### ISSUE TITLE
Bug with charset

### ISSUE THREAD

**Issue by gilperon** [Semantic-Org/Semantic-UI#3348]
Hi,

I have a page which uses "charset=iso-8859-1" and I have a list like this:

<ul class="list">

    <li>Testing</li>
    <li>Testing</li>

</ul>

The problem is that the bullet (the circular marker at left) does not show up and instead it shows a weird character. If I change the encoding of the page to UTF8 it works fine. Hope you can fix this.

**Comment by jlukic** [comment]
This is a UTF-8 character, so the same encoding is required.

**Comment by gilperon** [comment]
... so you wont solve the problem? Semantic ui is getting like shit, jquery ui support is much better and they really want to solve problems. They work across any encoding.

**Comment by surtic86** [comment]
UTF-8 is all what you / wee need :)

**Comment by gilperon** [comment]
@surtic86 I agree totally with you :) But unfortunatelly some customers with old websites have still ISO and I need to support it. jquery ui supports iso, bootstrap supports iso... every great library supports iso... it's no big deal making a library with iso support
