### ISSUE TITLE
Dropdown onShow : not working

### ISSUE THREAD

**Issue by manodupont** [Semantic-Org/Semantic-UI#3349]
I want the callback method onShow to be called.

It never works. onChange works fine, but onShow, I can't get it to work. Should be straight forward.

Code is like this ; 

// Configure semantic UI dropdown plug-in
	that.$btnTranspose.dropdown({
		action: 'activate',
		onShow: function() {
                        console.log('onShow');                                    // THIS DOESN'T WORK.
			return true;
		},
		onChange: function(value, text, $selectedItem) {
			 console.log('onChange', value);                     // THIS WORKS FINE.
			return true;
                }
         });

**Comment by jlukic** [comment]
Please create a test case

**Comment by avalanche1** [comment]
Closing until there's a test case.
