### ISSUE TITLE
<em> tag inside of a .ui.icon.message loses natural spacing

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#3352]
**Steps to Reproduce**
1. Create an .ui.icon.message within a `<p>`
2. Add emphasised text with `<em>`

**Expected**
Empahsised text should have leading and trailing space.

**Result**
Natural spacing around `<em>` tags are removed. (however, it works with a non-breaking space)

**Testcase**
http://jsfiddle.net/2jytb48b/2/

**Comment by jlukic** [comment]
There's no styles attached to `em` styles from semantic ui
