### ISSUE TITLE
Error on usage instructions

### ISSUE THREAD

**Issue by milincheta** [Semantic-Org/Semantic-UI#3356]
The usage section on the github page (https://github.com/Semantic-Org/Semantic-UI-Meteor#usage)
are wrong.
If you follow them you get an error as folows:
W20151118-21:48:50.019(-3)? (STDERR) ReferenceError: jQuery is not defined
W20151118-21:48:50.019(-3)? (STDERR)     at definitions/behaviors/api.js:1140:5

**Comment by steve-ross** [comment]
are you using meteor?

**Comment by jlukic** [comment]
Please post issues in the proper repo
