### ISSUE TITLE
Add modal event handler 'onClose'

### ISSUE THREAD

**Issue by saada** [Semantic-Org/Semantic-UI#3357]
Just like we have support for 'onApprove', 'onDeny'.
I need a way to handle the event when the user closes the modal by clicking on the dimmer.
Similar to onDeny, if this event handler returns false, the modal should NOT be closed.

Alternatively, rather than adding 'onClose' we could trigger the onDeny handler for this event instead.

**Comment by jlukic** [comment]
There is `onHide` and `onHidden`

**Comment by neokio** [comment]
This is a valid request. Deny does not equal Hide. One simple workaround is as follows:

```javascript
	$('#modal').modal({
		onApprove: function(){
			$('#modal').data('accepted',1);
			// add approved code here
		},
		onHide: function(){
			if ($('#lead_modal').data('approved') != 1) {
				// add not approved code here
			}
		}
	});
	$('#modal_opener').click(function(){
		$('#modal').data('accepted',0).modal('show');
	});
```

**Comment by ryanmills** [comment]
+1 - We need a onClose to fire when the modal has been closed due to dimming/click on the close icon.
