### ISSUE TITLE
[Popup] - Enhancment to be able to show over a overflow:hidden parent container?

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#3359]
I wanted to create a product slider that has key features as a popup content -- however the sliders requires an overflow hidden -- which crops the popup.  I try using  context: 'body' but it still doesn't work.

Any tips or workaround?

Here is a demo I was attempting using a custom scrollar:

https://jsfiddle.net/9v9z6w59/

NOTE: even without the scroller and setting the parent to overflow hidden also crop the popup

https://jsfiddle.net/22ugynzb/

Thanks

**Comment by xiwc** [comment]
i meet the same problem. 顶起!

**Comment by jlukic** [comment]
If you actually put the popup inside an overflow container, it wont be able to escape its overflow.

Use `data-html="popup contents"` and `inline: false` 

https://jsfiddle.net/tg2wgofz/

**Comment by tripflex** [comment]
For anybody viewing this with same issue/question, I was able to get it to somewhat work, but you have to set the `movePopup` value to false as well
