### ISSUE TITLE
Bower integration and theme.config

### ISSUE THREAD

**Issue by Zopieux** [Semantic-Org/Semantic-UI#3360]
## Development setup

Using _Brunch_, _Bower_.

What I have done:
- installed `brunch-less`
- `bower install semantic-ui` (as per README)
- `brunch-config.coffee` looks like:
  
  ``` coffee
  module.exports = config:
  files:
    javascripts:
      joinTo:
        'js/vendor.js': /^bower_components/
    stylesheets:
      joinTo:
        'css/vendor.css': /^bower_components/
  ```
## Issue description

When building the project with `brunch build`:

```
error: Compiling of 'bower_components/semantic/src/semantic.less' failed.
FileError:'../../theme.config' wasn't found. Tried - 
bower_components/semantic/src/theme.config,../../theme.config,
bower_components/theme.config in 
"bower_components/semantic/src/definitions/modules/transition.less:20:0"
```

Indeed, there is `bower_components/semantic/src/theme.config.example` but not `bower_components/semantic/src/theme.config`.
## Current workaround

Adding `bower_components/semantic/src/theme.config` and editing it there. This is a terrible idea: `bower_components/` is obviously git-ignored.
## Expected behavior

I should be able to configure Semantic (using `semantic.json`) without touching a single file from `bower_components/`. The wiki has no documentation about that.

**Comment by DaSchTour** [comment]
Struggling with the same problem since days. I tried to include Semantic-UI gulp tasks with require dir. But that doesn't help to make use of my semantic.json config in my root directory that links to the right folders.

**Comment by DaSchTour** [comment]
I know have a somehow working configuration with the theme.config in root as it seams that theme.config options from semantic.json are not used. But this only works when I start the gulp tasks from the semantic-ui folder and not from how I would like by adding several tasks to my own gulp file.

**Comment by jlukic** [comment]
There's examples of importing gulp tasks in the [recipes](http://semantic-ui.com/introduction/advanced-usage.html#importing-gulp-tasks) section. You might have already seen. 

You might also consider one of our alternative packages like `semantic-ui-less` if you want to just build the less using your custom pipeline.

**Comment by robertpitt** [comment]
This is an issue for me as well, I am using Laravel Framework and instead of bower I am using composer, same issue applies though.

The source is located `/vendor/semantic/ui` I then use elixir to compile my `application.lss` which calls `@import 'semantic'` but fails when a module file looks for `theme.less`.

See error below:

```
[22:34:09] gulp-notify: [Laravel Elixir] Less Compilation Failed: '../../theme.config' wasn't found. Tried - vendor/semantic/ui/src/theme.config,vendor/semantic/theme.config,../theme.config,../../theme.config in file vendor/semantic/ui/src/definitions/modules/transition.less line no. 20
{ [Error: '../../theme.config' wasn't found. Tried - vendor/semantic/ui/src/theme.config,vendor/semantic/theme.config,../theme.config,../../theme.config in file vendor/semantic/ui/src/definitions/modules/transition.less line no. 20]
  type: 'File',
  filename: 'vendor/semantic/ui/src/definitions/modules/transition.less',
  index: 331,
  line: 20,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: [ '', '@import (multiple) \'../../theme.config\';', '' ],
  message: '\'../../theme.config\' wasn\'t found. Tried - vendor/semantic/ui/src/theme.config,vendor/semantic/theme.config,../theme.config,../../theme.config in file vendor/semantic/ui/src/definitions/modules/transition.less line no. 20',
  stack: undefined,
  lineNumber: 20,
  fileName: 'vendor/semantic/ui/src/definitions/modules/transition.less',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function: bound ] } }
````

Cheers

**Comment by serieznyi** [comment]
+1

**Comment by deanbrophy** [comment]
I installed the full Semantic UI via NPM to an unwatched folder. I then created a less file in a watched folder which imported the theme. It seems like a waste is the cleanest way I could get running. Here is my example: https://github.com/deanbrophy/fantastic-garbanzo

**Comment by jasperdj** [comment]
Until Semantic-UI properly supports Bower, use Semantic-UI-Bower (2.2.8). 

`    bower install Semantic-UI-Bower
`
