### ISSUE TITLE
[Dropdown] Multiple Search Selection - Adding Values Dynamically

### ISSUE THREAD

**Issue by adrazich** [Semantic-Org/Semantic-UI#3362]
I was wondering if there is a way to add values dynamically to a multiple search selection dropdown?
##### Example

http://jsfiddle.net/713ex6dm/2/
##### Scenario

I have a set of emails the user can search and select from. I also want to allow the user to add more emails to this list so I have a separate form below with an input and submit button. When the user submits the new email I want it to dynamically update the dropdown with the new email. I want it to be visible and the value to be defined so if i 'get value' it's also returned to me.

Is this possible? I could reload in the template for the dropdown with the new values but I'm trying to just update it on the fly.

**Comment by adrazich** [comment]
##### Solution
http://jsfiddle.net/713ex6dm/5/

I found the above solution but I feel like it's a bad solution. I don't think I should need to modify the HTML to make this work. Is there a better way?

**Comment by goetzst** [comment]
Bumping as I too stumbled upon this problem. The problem with this solution is that adding options does not trigger the check for maxSelections (meaning if you could aditionally add something through the menu itself you would surpass the maxSelection by at least 1)
