### ISSUE TITLE
Conflict with Swiper.js

### ISSUE THREAD

**Issue by joannesalfa** [Semantic-Org/Semantic-UI#3363]
I've downloaded this lib to make slider

http://www.idangero.us/swiper

I've imported this lib on my page which uses semantic-ui, then it gave me a lot of errors in console:

pic related

![conflict semantic-ui vs swiper.js](http://i.imgur.com/QlccZPm.png)

**Comment by jlukic** [comment]
This would occur if you did not include the css related to transition.

**Comment by joannesalfa** [comment]
I'm not sure which is CSS file that I really don't know, by the way, this is jquery version of swiper.js which can cause problems related to semantic.js

Besides, pure javascript version of swiper.js worked and no console errors

You can try with semantic-ui template, then import pure javascript of swiper.js, it works, otherwise jquery version of swiper.js, it causes errors.

**Comment by witrin** [comment]
@jlukic The error here is thrown by your component because Swiper make calls like `jQuery.transition(0)` and this is their implementation if `!('transition' in jQuery.fn)`:

```
function (duration) {
   if (typeof duration !== 'string') {
        duration = duration + 'ms';
    }
    for (var i = 0; i < this.length; i++) {
        var elStyle = this[i].style;
        elStyle.webkitTransitionDuration = elStyle.MsTransitionDuration = elStyle.msTransitionDuration = elStyle.MozTransitionDuration = elStyle.OTransitionDuration = elStyle.transitionDuration = duration;
    }
    return this;
};
``` 

So in fact, the jQuery version of Swiper is currently not compatible with the Transition component of Semantic UI.

**Comment by endlessdev** [comment]
I had this problem too. but, now this problem has solved.
The solution is using swiper library javascript file without jquery

```Javascript
<script src="{{url('/assets/bower/Swiper/dist/js/swiper.jquery.min.js')}}"></script>
```
**instead of**
```JavaScript
<script src="{{url('/assets/bower/Swiper/dist/js/swiper.min.js')}}"></script>
```

Best regards.

**Comment by philrykoff** [comment]
This can be closed

**Comment by Banandrew** [comment]
Hi @philrykoff and thanks!
