### ISSUE TITLE
Check box (the toggleone) and dropdown problem

### ISSUE THREAD

**Issue by milkymura** [Semantic-Org/Semantic-UI#3368]
```
$('.test.checkbox').checkbox({
    onChecked:function(){
        $('#studyField').addClass('animated fadeOutLeft').one(animEnd,
            function(){
                $(this).removeClass('animated fadeOutLeft');
                $(this).addClass('closed');
                $('#eventField').removeClass('closed');
                $('#eventField').addClass('animated fadeInLeft').one(animEnd,
                    function(){
                        $(this).removeClass('animated fadeInLeft');
                    });

            });

    },
    onChange:function(){

        $('#eventField').addClass('animated fadeOutLeft').one(animEnd,
            function(){
                $(this).removeClass('animated fadeOutLeft');
                $(this).addClass('closed');
                $('#studyField').removeClass('closed');
                $('#studyField').addClass('animated fadeInLeft').one(animEnd,
                    function(){
                        $(this).removeClass('animated fadeInLeft');

                    });

            });

    }
});
$('.ui.dropdown').dropdown();
```

here is my code inside my javascript file. 

everything is working fine. the link src are properly arranged and the animations work. 

what my code does is hide/show a div containing a field where there is a dropdown input and div containing a field with out a dropdown input. 

THE PROBLEM: 

the first time I encounter the page I can properly use the dropdown input. 

but when I toggle the checkbox (http://semantic-ui.com/modules/checkbox.html#toggle)
which hides the div with a dropdown and shows the div without dropdown. 

the drop down input malfunctions

why?

when i toggle again the checkbox 
which hides the div without dropdown and show the div with a dropdown, everytime I click the dropdown it AUTOMATICALLY toggles the switchbox which is very weird. 

I hope you could help me out. answers are much appreciated

**Comment by milkymura** [comment]
it works well on firefox idk with chrome

**Comment by v3rron** [comment]
Have something weird happening with both `checkbox toggle` and `checkbox slider`.
This checkbox is controlling another bunch of hidden fields on my page. And sometimes when I click on a toggle, the whole screen goes blank on mobile safari. I debugged it with developer tools, and the only thing that fixed blank screen is to toggle off/on `z-index: -1` on the checkbox input element. And that is really weird because this z-index css attribute is only set on `.ui.checkbox input.hidden`
