### ISSUE TITLE
Dynamic added items can not be selected.

### ISSUE THREAD

**Issue by yandan66** [Semantic-Org/Semantic-UI#3371]
I have add a item dynamicly but can not by set select the item immediately. But can be set selected after add other item. 
example:http://jsfiddle.net/yandan66/n82v59g9/1/
 I don not know why. Anyone can help me?

**Comment by IonutBajescu** [comment]
Closing this since I'm unable to reproduce the issue.

@yandan66 feel free to reopen if you haven't fixed it in the meantime.
