### ISSUE TITLE
Facilitate sass port, and better ide support

### ISSUE THREAD

**Issue by klarezz** [Semantic-Org/Semantic-UI#3374]
Could you consider dropping usage of .loadUIOverrides and other dynamic imports in theme.less, and hard code imports instead. It would facilitate porting to sass (sass/sass#739 would no longer be required). And it would also allow better ide support (inspection, code navigation...)

**Suggested implementation:**

1/ move site imports from theme.less to definition files.
2/ move component theme imports from theme.less to site files

To change a component theme, one would change the import statements in site files. It would be a little more messy but the benefits seem worth it.

**Comment by klarezz** [comment]
Precision: in order to get rid from loadUIOverrides, theme import could be moved to the beginning of @{siteFolder}/@{type}s/@{element}.overrides files (theme.config could then be dropped)

**Comment by alp82** [comment]
Great suggestion. I'd love be able to choose whether i want to use less or sass.

**Comment by ravasthi** [comment]
Piling on. Sass support is a must for me, and I'd choose Semantic UI but for that. Please?

**Comment by jlukic** [comment]
Hard coding imports would prevent themeing which is a major feature for Semantic UI.

**Comment by klarezz** [comment]
According to my tests, theming is possible. But it should happen in site files, not `theme.config`. Eg:
1.breadcrumb.overrides could start with:
```less
/*-------------------
Theme Overrides
---------------------*/
@import (optional) "../../themes/default/collections/breadcrumb.overrides";
/******************
Site Overrides
*******************/
```
2.breadcrumb.overrides could start with:
```less
/*--------------------
Global variables
---------------------*/
/* nb: component theme */
@import (optional) "../../themes/default/globals/site.variables";
/* site */
@import (optional) "../../_site/globals/site.variables";
/*-------------------
 Component variables
---------------------*/
/* default theme */
@import "../../themes/default/collections/breadcrumb.variables";
/* nb: Component theme */
@import (optional) "../../themes/default/collections/breadcrumb.variables";
/******************
Site Overrides
*******************/
```
It's a little messier as I said but I find it worthy. There may be however other implications I'm not aware of.

**Comment by DaSchTour** [comment]
Maybe theming is a thing that could be done outside the sass compiler. Maybe there is a nice possibility to include this into the build process? So configuration could be done in a JSON and a smart build could choose the files that are needed for building the themed version out of the JSON.

**Comment by ikhilko** [comment]
+1 @DaSchTour, it's looks like all porting process stops because theming couldn't be implemented like in less. Maybe we need use more common way to make theming (e.g. build process)?

**Comment by davestewart** [comment]
Seems like hardcoded themes could work if symbolic links were used?
