### ISSUE TITLE
Poor user experience with scrolling dropdowns on mobile

### ISSUE THREAD

**Issue by jarrettv** [Semantic-Org/Semantic-UI#3376]
The scrolling area is way too small on mobile. You can only see three items regardless of how much screen space is available. With only three items showing, it is hard to scroll with your finger.

**Comment by jlukic** [comment]
You can change this if you prefer  something else, but 3 is the max safe size for mobile. 

`@selectionMobileMaxItems: 3;`
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/dropdown.variables#L176
