### ISSUE TITLE
Dropdown not working in Samsung Browser 3

### ISSUE THREAD

**Issue by Elephant-Vessel** [Semantic-Org/Semantic-UI#3377]
On the stock browser in Samsung Galaxy S6 (don't know about previous versions), the dropdowns are not working.

Go to http://semantic-ui.com/modules/dropdown.html on above mentioned browser and nothing works.

**Comment by Elephant-Vessel** [comment]
Why is there not action here? The samsung browser must have a quite high share of mobile users?

**Comment by arkmuay** [comment]
Damn :( Nothing work on samsung... I have to change all my front...

**Comment by IonutBajescu** [comment]
@Elephant-Vessel or @arkmuay, could one of you confirm if the issue still exists? It might've been fixed by one of the recent releases. Thanks.

**Comment by arkmuay** [comment]
Sorry, I can't test... What commits fix this issue? Thanks.

**Comment by jlukic** [comment]
#2718 Android Bubblegum
