### ISSUE TITLE
Disable building of components folder and uncompressed files.

### ISSUE THREAD

**Issue by DesignPixelZ** [Semantic-Org/Semantic-UI#3379]
I can't find a way to make gulp watcher / builder output only `semantic.min.css`, `semantic.min.js` and the required files from `themes` folder. I have no usage for `components/` or uncompressed files in my dist folder.

**Comment by IonutBajescu** [comment]
I'm afraid there isn't any, unless you manually go and change the build plan. 

Feel free to open this issue as a feature request. Although I'm not sure if it's worth the hassle. If you have no usage for some of the generated files, simply don't use them.
