### ISSUE TITLE
Skip compression of assets during development

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#3380]
Is it possible to skip the compression step when watching files during development?

I don't use the compressed assets during this phase and have my own minification step later, so I really don't need this processing delay.

**Comment by jlukic** [comment]
You will need to fork the gulp tasks in `watch.js` and remove the bits about compressed assets. You can then import these tasks in your gulp file using this method:
https://github.com/Semantic-Org/Semantic-UI/tree/master/tasks#how-to-use
