### ISSUE TITLE
dropdown menu is not working in IE and Firefox

### ISSUE THREAD

**Issue by amad4biz** [Semantic-Org/Semantic-UI#3381]
I tested it both in IE 11 and firefox 40
Please see it in this pen http://codepen.io/amad4biz/pen/MadQxo

**Comment by veke** [comment]
Move script tags inside body tag.

**Comment by amad4biz** [comment]
Have tried to moved earlier but it didi not work, I just did it also

**Comment by cazzoo** [comment]
Cannot reproduce with Firefox 42 or IE11.0.9600.18097

**Comment by veke** [comment]
Tested firefox on mac + ie11 on win. Works correctly.

**Comment by amad4biz** [comment]
ok i will restart my machine later and see
