### ISSUE TITLE
Why does .ui.grid have font-size: 0

### ISSUE THREAD

**Issue by afang** [Semantic-Org/Semantic-UI#3385]
I find myself manually setting `font-size: inherit` every time I nest segments inside a `.ui.grid`. What is the purpose of hiding text in nested elements?

**Comment by jlukic** [comment]
Grid in 2.0 does not use font-size reset. This is only necessary "pre-flexbox" when we had an inline-block grid, this "fix" prevents whitespace in code causing space between columns.

In 2.0 you'll notice there is no use of `font-size: 0`
