### ISSUE TITLE
[Popup] Add onUnplaceable callback, Fix Docs Description of Errors

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#3388]
The docs don't reflect the settings in popup.js

Should be:
````
  error: {
    invalidPosition : 'The position you specified is not a valid position',
    cannotPlace     : 'Popup does not fit within the boundaries of the viewport',
    method          : 'The method you called is not defined.',
    noTransition    : 'This module requires ui transitions <https://github.com/Semantic-Org/UI-Transition>',
    notFound        : 'The target or popup you specified does not exist on the page'
  },
````

Not:
````
error: {
  content   : 'Your popup has no content specified',
  method    : 'The method you called is not defined.',
  recursion : 'Popup attempted to reposition element to fit, but could not find an adequate position.'
}
````

**Comment by jlukic** [comment]
Thanks missed copy and paste.

**Comment by tmikaeld** [comment]
Is it possible to get a callback when the popup doesn't fit? When using it in admin interfaces it would be good to be able to inform the user to increase their browser height to fit an editing box.

**Comment by jlukic** [comment]
I agree that makes sense as well.

**Comment by jlukic** [comment]
Added. Deving on an offline VM but tagged commit will follow.

**Comment by tmikaeld** [comment]
Thinking more about this, it would make sense to have an additional position instead of displaying in a popup. "Center Center" - position the popup in the center of the element. Your thoughts?
