### ISSUE TITLE
Steps with long description issue

### ISSUE THREAD

**Issue by sszdh** [Semantic-Org/Semantic-UI#3395]
Hi there,

When we have steps with long description, each steps reformed and overlaps icons.

This is [pen](http://codepen.io/sszdh/pen/zvVWPa) to reproduce issue and shows the problem.

Thanks.

**Comment by IonutBajescu** [comment]
I'm unable to reproduce your issue. If you haven't resolved it already, please feel free to reopen.

![selection_126](https://cloud.githubusercontent.com/assets/5365516/16085038/ad9e10f8-3312-11e6-9228-9cd815685c78.png)
