### ISSUE TITLE
官网选择简体中文后为什么还有繁字体？

### ISSUE THREAD

**Issue by zaxlct** [Semantic-Org/Semantic-UI#3399]
官网首页，“用戶介面是網站的語言” 这是繁字体吧，
还有就是文档汉化的不彻底，很多地方还是中英文混合着来的

 = =，
我就是吐槽一下不用放在心上，唉，后悔没学好英文

**Comment by bestony** [comment]
大陆好像没人在做，而且，SemanticUI也找不到大点的QQ群

**Comment by jlukic** [comment]
对不起

**Comment by bestony** [comment]
吼吼，为啥没有国内的QQ群啊。我用semantic UI 蛮好用的

**Comment by zaxlct** [comment]
和bootstrap相比他有什么优点呢

**Comment by bestony** [comment]
语义化，理解方便。比如错误信息框添加 error类就行

**Comment by zaxlct** [comment]
Thanks

**Comment by skylee91** [comment]
@zaxlct 相比bootstrap, semantic-ui比较多components, 如：card, labeled button, rating, dimmer.

**Comment by KagamiChan** [comment]
作为最早的翻译者之一，我表示抱歉……现在因为自己的一些原因没有再跟进了。semantic-ui 的迭代速度比较快，原来翻的不少内容又已经过时了，而且新的名词的翻译也需要斟酌，总体来说还是有挑战的……

有兴趣的话可以向 @jlukic  申请一个 transifex 权限，就可以提交自己的翻译了
