### ISSUE TITLE
Progress bar: no pulse toggle setting

### ISSUE THREAD

**Issue by NilsJPWerner** [Semantic-Org/Semantic-UI#3402]
Having the progress bar enabled with javascript takes a steady 20% of my CPU because of the pulsing indicating animation. I haven't been able to find an option (at least in the documentation) to turn off the pulse.

**Comment by jlukic** [comment]
`showActivity` is the setting. 

Or you can modify the animation using a LESS variable.`activePulseDuration: 0s;`

**Comment by KevinKra** [comment]
How can I do this without using less?
