### ISSUE TITLE
[Build Tools] Bundle Wrench Tarball

### ISSUE THREAD

**Issue by Parakleta** [Semantic-Org/Semantic-UI#3404]
Is it possible to bundle the wrench tarball within Semantic-UI?  I'm trying to configure npm to work in a sometimes offline environment and I can run a registry from a pre-downloaded cache but I am stuck getting Semantic-UI to install because it needs to call out to the internet to fetch the wrench tarball (which is not cached by npm).

I'm a bit stuck as to what else to try.

**Comment by jlukic** [comment]
I'm not familiar with your suggestion on bundling tarballs with SUI. How is this different than other deps which are remote dependencies?

**Comment by Parakleta** [comment]
If the dependency is pulled from the npm repository then it can be proxied using the npm cache.  If the dependency is pulled from anywhere else then it must be accessible at install time.

One possible solution would be to just add the file `wrench.js` into the `tasks` directory since the only place it is used is in `task/install.js`.  Wrench is only around 500 lines and is a leaf dependency (and so requires nothing else).  Given that you're tracking a specific hashed version I don't see any specific advantage to pulling it from git rather than just adding the code to this project directly.

**Comment by immo-huneke-zuhlke** [comment]
All it needs is for the wrench dependency to be expressed in a proper version number (1.5.8) instead of a github URL. I'm having to write a script to correct the package.json after  the npm install of semantic-ui and then run a general npm install afterwards. This should not be necessary, as all the npms are cached within our internal Nexus server.

**Comment by jlukic** [comment]
I've marked this for a patch milestone

**Comment by jlukic** [comment]
Should have done this already

**Comment by jlukic** [comment]
Packaged in `2.2.8`

**Comment by ryanmcgrath** [comment]
Mmmm, FWIW, I'm the author of Wrench, and while I don't care if you package it... you really ought to be using something else. I killed the module for a reason.

You do you tho~
