### ISSUE TITLE
Turn off automatic [enter] key form submission for a field?

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI#3406]
The documentation states:

```
Built-in Events
Form will automatically attach events to specially labeled form fields

Fields will blur on escape key press
Fields will submit form on enter
Submit events will be attached to click on any element inside the form with class submit
Reset events will be attached to click on any element inside the form with class reset
Clear events will be attached to click on any element inside the form with class clear
```

Is there a way i could disable submission of form on enter, for a particular field or all fields? I think there are a lot of use cases for this, for example i am using a google maps autocomplete which i also validate with semantic ui form validator but i don't want it to submit the form when the user presses enter. Because that is also the key for selecting the option from the drop down.

**Comment by talha-asad** [comment]
got it: setting "keyboardShortcuts".
Thanks.

**Comment by cariquitanmac** [comment]
Hi how to set this in form?
