### ISSUE TITLE
[Search] Enter key selects active result, but doesn't follow its href

### ISSUE THREAD

**Issue by Banandrew** [Semantic-Org/Semantic-UI#3409]
Hello,

I decided to separate this issue, since the initial mentioning #3111 was closed. When you return search results with a `url` property, SUI pastes it inside a `href` attribute, and while you can click on a search result to follow it, or navigate using arrow keys, you can't follow a link by hitting Enter; it just pastes whatever it is inside a `.title` inside the search input.

Please see [this JSFiddle](http://jsfiddle.net/Banandrew/89hw2pze/) for an example: type "an", choose a result with arrow keys and hit Enter.

**Comment by larsbo** [comment]
:+1: 

there should be a setting to choose between the "follow url pattern" and the current "just put the chosen entry into the search field pattern".

**Comment by Neablis** [comment]
I am currently running into this bug. I change the line @larsbo recommended to

`$result.find('a[href]').eq(0)` === [] ? $result.find('a[href]').eq(0) : $result.eq(0),

Its not elegant but i didn't want to touch too much of there code.

**Comment by jlukic** [comment]
Added solve
