### ISSUE TITLE
[Breadcrumb] - Your Bug Name

### ISSUE THREAD

**Issue by psyOPs-** [Semantic-Org/Semantic-UI#3411]
the play music button directs to a broken link on soundcloud.

**Comment by jlukic** [comment]
Woah looks like it just broke. Must be the service i'm using to do the popup

**Comment by jlukic** [comment]
I just fixed the music player.

**Comment by ashwinuae** [comment]
Hi! Looks like it's broken again. It opens the Stratus 2 popup alright, but hit play on a track and nothing happens.
