### ISSUE TITLE
Divider with no text inside has a space in between

### ISSUE THREAD

**Issue by magestican** [Semantic-Org/Semantic-UI#3412]
I think there should not be a space in between the two lines as there is now when using vertical divider, this sounds like an issue, code to reproduce : 
http://codepen.io/anon/pen/epqXzv

And if there is a way to avoid this white space in between, is not in the documentation :
 http://1.semantic-ui.com/elements/divider.html

**Comment by xDaizu** [comment]
The space to write a word is great. In most cases. That being said, I think there should be a class to add if you don't want the space and just want a simple vertical line.
