### ISSUE TITLE
Feature suggestion: Make it possible to use the color classes within anchor tags

### ISSUE THREAD

**Issue by jonsa** [Semantic-Org/Semantic-UI#3420]
This [fiddle](http://jsfiddle.net/ndn5oez0/1/) pretty much sums it up but in short I'm suggesting making links color-able. This would give links a consistent behavior if one wanted to use, as in the example, a stacked icon as link content.

**Comment by jlukic** [comment]
You can use `link` icon to allow for an icon to be styled like a link

**Comment by jonsa** [comment]
Indeed you can. It does however create some weirdness when using a stacked icon as each icon is highlighted individually, see the updated [fiddle](http://jsfiddle.net/ndn5oez0/3/). Perhaps the ```link``` class should be supported in conjunction with the ```icons``` class.

It's also unfortunate, in my opinion, that opacity is used to indicate a linked icon. I can see that it's a preferable solution since it's a one method fixes all but it does make the icon look kinda washed out.
