### ISSUE TITLE
Internet Explorer 10 minimizes itself when a modal is shown

### ISSUE THREAD

**Issue by pereiren** [Semantic-Org/Semantic-UI#3422]
Hi folks,

I am experiencing a weird issue. I have a googlemap where there are some "markers" showing different locations,

When an user clicks on a marker, a modal is shown and if he clicks on "Yes" I render another stuff with calendars related to that location blahblahblah.

My issue happens when the modal is being shown. Once the modal is totally rendered, Internet Explorer minimizes itself. 

I don't know what is going on, I have a lot of modals thru my web app and it only happens when I want to show the modal from the googlemap markers.

You can test it here: http://jsfiddle.net/crrtwm93/1/

Any idea or similar case?

Thank you in advance and best regards,

Pereira

EDIT: I realized a thing, it only happens when there is just one tab opened XD When there are multiple tabs it works fine. Jsfiddle included, finally I got some time to do it.

**Comment by maris-erts** [comment]
Hi, is this issue solved?
I have exactly the same issue on IE 10.
