### ISSUE TITLE
[Dropdown][Search Selection] Match any part of the string

### ISSUE THREAD

**Issue by adrazich** [Semantic-Org/Semantic-UI#3424]
This is a feature request.

Currently, when you search in a dropdown it matches the string from the beginning only. You can't search for something in the middle of the string (LIKE% matches, %LIKE% doesn't). For example, if you want to search a dropdown of users and you type their last name but no results are found unless you type the first name first.

#### Example
http://semantic-ui.com/modules/dropdown.html

#### What happens
- Go to the country dropdown search select.
- Type **states**
- No results found.

#### What's expected
- Go to the country dropdown search select.
- Type **states**
- **United States** shown in the list as a match.

#### Example of expected
jQuery's autocomplete does this and there is an example here: https://jqueryui.com/autocomplete/#combobox

**Comment by kmd1970** [comment]
Under **Settings (tab), Additional Settings**:

http://semantic-ui.com/modules/dropdown.html#additional-settings

**fullTextSearch** :  Whether search selections should look for string match anywhere in string.

```javascript
$('.ui.dropdown').dropdown({ fullTextSearch: true });
```

Hope that helps.

**Comment by adrazich** [comment]
That works. Didn't see that in the docs. Thank you. :)

**Comment by duapraveen** [comment]
fullTextSearch=true doesn't appear to do a substring match for the query-string in the items. instead, it appears to match in order occurrence of all characters of the query-string in the item with any other characters interspersed (example : query-string 'temp' will match 'mytestmatchpick' and 'mytemperature' ).

Any idea how to restrict to a strict substing match behavior ?

**Comment by basselAhmed** [comment]
I can confirm @duapraveen  problem, we really need a fix for this

**Comment by duapraveen** [comment]
fullTextSearch=exact seems to do what i needed - looks for the query-string anywhere in the strings.

http://semantic-ui.com/modules/dropdown.html#additional-settings

**Comment by basselAhmed** [comment]
Thanks @duapraveen for your response but that didn't work for me in search 

http://semantic-ui.com/modules/search.html

Could you help in this ? I know it's out of this issue context but it's the same behavior in search, that's what got me here.

**Comment by NahuelKliphan** [comment]
Gracias kapo

**Comment by Jayashree-panda** [comment]
I am facing the same issue with react semantic ui. @duapraveen @kmd1970 Can you please help me with that.

**Comment by Shubhdeep12** [comment]
@Jayashree-panda if you are using semantic-ui react maybe this can help you https://github.com/Semantic-Org/Semantic-UI/issues/3424
