### ISSUE TITLE
[Dropdown] Two connected div-based dropdowns produce infinite recursion when no input:hidden provided

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3425]
Hi,

There's an infinite recursion that can happen on 2 connected dropdowns, if their definitions dont contain an `input:hidden`. Here's a [fiddle](http://jsfiddle.net/o3z7u87h/).

I am not sure if you can classify this as a bug, but it would be nice to add `input:hidden` automatically to a dropdown, if none was specified, so that this kind of problem does not happen. Or alternatively notify user in the console, that definition has none and it must be added.

**Comment by ronaldo-systemar** [comment]
:+1: 

Happened to me, @andreyvk helped me to solve. I had no idea about add a hidden input. May you could put <input hidden> in examples or even add dynamic element when initilizing script.
