### ISSUE TITLE
dropdown - with a item with a url - will not preserve style

### ISSUE THREAD

**Issue by ntgraph** [Semantic-Org/Semantic-UI#3426]
Hi, as soon as I put a link_to_route, the style is not preserved like the one with a text, I would like the one with the link has the same visual
<div class="ui inverted menu">
<div class="ui dropdown item">Select a language
   <i class="dropdown icon"></i>
    <div class="menu">
       <a class="item">{!!  link_to_route('lang.switch', $language, $lang) !!}</a>
        <a class="item">this one works</a>
   </div>
</div>
</div>

**Comment by aketai** [comment]
"require": {
    "laravelcollective/html": "5.1.*"
}
