### ISSUE TITLE
Flickering page while scrolling

### ISSUE THREAD

**Issue by bierik** [Semantic-Org/Semantic-UI#3430]
Tested with OS X 10.10.5 Yosemite Chrome Version 47.0.2526.73 (64-bit)

When scrolling on http://semantic-ui.com/behaviors/visibility.html the whole page is flickering with certain heights of the viewport.

In the demo I'm just scrolling downwards but the footer is just visible for some milliseconds.

See demo here:
![semantic_ui_visiblity](https://cloud.githubusercontent.com/assets/1637820/11561324/e8e4df24-99c6-11e5-841c-0b3437c8ea5f.gif)

**Comment by jlukic** [comment]
I'm not sure what's going on here but its probably something to do with tabs using `hashstate` for location.

**Comment by DanielSundberg** [comment]
Why was this closed? On Windows 10/Edge this looks much worse and is similar to a problem I'm experiencing on the site I'm working on (no simple way reproduce that problem though).

**Comment by mashaalmemon** [comment]
Am looking at a few frameworks to adopt in a project. Have noticed semantic-ui 2.2 on the demo page flickering when scrolling on iOS. If I thumb scroll quickly, as the page slows down there is a noticeable flicker. I am running Mobile Safari 10, iOS 10.2.1. An example page to try is the "Whats New in Semantic-UI 2.2" page: https://semantic-ui.com/introduction/new.html

**Comment by Banandrew** [comment]
The issue was closed, and we were tracking it in #5012—@jlukic, take a look at the thread, I linked a couple of related issues there.

**Comment by jlukic** [comment]
Works for me
