### ISSUE TITLE
Semantic produces blurry fonts in Chrome (Windows 7)

### ISSUE THREAD

**Issue by skydreamerr** [Semantic-Org/Semantic-UI#3433]
It's visible on screenshot.
![capture](https://cloud.githubusercontent.com/assets/313681/11589614/df8a0e8e-9a9a-11e5-940b-3fd51f7abb7f.PNG)

**Comment by jlukic** [comment]
Which text is blurry? Typically this is a driver/GPU issue, or an issue with cleartype settings in windows (configure in control panel)

**Comment by skydreamerr** [comment]
All fonts are blurry. The most noticeable is the green one.The  top browser is Chrome, bottom one is Firefox. I see the same issue on my own project since I've added semantic to page.

**Comment by skydreamerr** [comment]
Firefox works fine

**Comment by richardtallent** [comment]
This isn't Semantic-UI's fault.

Chrome uses your Windows ClearType settings. Firefox and IE use DirectWrite, which uses 2D acceleration and tends to not use subpixel aliasing on smaller fonts. (I *prefer* the Chrome version of your screen shot, so it really is a personal thing -- one person's "blurry" is another person's "not pixelated.")

If you tweak your ClearType settings, you should be able to get something that looks acceptable in Chrome.

**Comment by smartclash** [comment]
@skydreamerr Both looks same. Maybe you should search for cleartype setting at the control panel and disable it.

**Comment by kunokdev** [comment]
![screenshot_20161109_141200](https://cloud.githubusercontent.com/assets/13220754/20139476/971449d2-a686-11e6-9c88-b75e6ffc717b.png)

This is not Windows issue only, it also happens on Chrome on Linux.
This is Chrome related issue. Look at the screenshot. The left one is Firefox and the right one is Chrome. It's really blurry while Firefox is clear.
