### ISSUE TITLE
Unstackable step navigation

### ISSUE THREAD

**Issue by ddevaal** [Semantic-Org/Semantic-UI#3439]
How do I prevent step navigation from stacking on mobile devices? I would like to prevent stacking on mobile devices so I have horizontal small step navigation with only icons for example. Stacking seems to be automatic. How do I prevent this from happening?

**Comment by TemaSM** [comment]
You can just comment block of media-query, starting from [15600 line](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L15600) to [15652 line](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L15652).
But I'm waiting for better solution on how to do that more convenient way.

**Comment by jlukic** [comment]
There should be an `unstackable` variation.

**Comment by ddevaal** [comment]
Thanks @TemaSM and @jlukic!
