### ISSUE TITLE
Please don't recommend `maximum-scale=1.0` and `user-scalable=no`

### ISSUE THREAD

**Issue by dmitriz** [Semantic-Org/Semantic-UI#3441]
The main homepage example in http://semantic-ui.com/examples/homepage.html recommends to block the user from zooming by these declarations:

```
  <meta name="viewport" content="..., maximum-scale=1.0">
```

**Please don't!**

I have bad eyes and find it really frustrating when sites are blocking my attempts to zoom, to achieve a comfortable font size for my eyesight. You as designer may think your site looks perfect but the user will suffer and leave your site for the ones who care.

This is really a bad advise, please read here if this is still not convincing:

http://stackoverflow.com/a/30044183/1614973
http://blog.javierusobiaga.com/stop-using-the-viewport-tag-until-you-know-ho
http://www.lukew.com/ff/entry.asp?1945
http://ux.stackexchange.com/questions/37511/should-users-be-able-to-zoom-in-a-responsive-webdesign

**Comment by fowlerj** [comment]
Children with visual limitations use iPads to zoom into content that other students can see easily when maximum-scale isn't set.  Hopefully these settings will be removed by major browsers in the future and this won't further limit people that need to zoom in a bit but until then @dmitriz has brought to light a good suggestion.
