### ISSUE TITLE
'onShow' and 'onVisible' are inconsistent in 'Modal' and 'Sidebar' .

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#3442]
onShow  Modal   Is called when a modal starts to show.
onVisible   Modal   Is called after a modal has finished showing animating.

onVisible   Sidebar Is called when a sidebar begins animating in.
onShow  Sidebar Is called when a sidebar has finished animating in.

Should we make them unified? Thanks for answering.

**Comment by lubber-de** [comment]
We prepared consistency over all components in the community fork Fomantic-UI for 2.9.0 by https://github.com/fomantic/Fomantic-UI/pull/2213
