### ISSUE TITLE
Test credit card numbers do not validate

### ISSUE THREAD

**Issue by sconstantinides** [Semantic-Org/Semantic-UI#3443]
Using numbers from: https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm
- The first Diners Club number (30569309025904) validates but the second (38520000023237) does not
- The last Visa number (4222222222222) does not validate

**Comment by jlukic** [comment]
All these card numbers validate correctly in the docs example first form field which does not specify strict type. (Luhn check only)
http://semantic-ui.com/behaviors/form.html#payment

Generally not specifying a type will allow for a more lenient check.  I'm unfamiliar with what visa standard the 13 digit card numbers are based off of, but I have not seen these before. I do see Stripe's payment js supports this so maybe this is something new?

**Comment by sconstantinides** [comment]
Thanks for the quick reply :)

I couldn't find much detail on the short Visa numbers. It seems to be pretty rare.

An aside: I'm currently using jQuery.payment to format/validate card numbers. Would you be open to PRs to format fields? Phone numbers get quite complicated but card numbers seem like a good place to start.
