### ISSUE TITLE
[Dropdown] selecting item does not update styling

### ISSUE THREAD

**Issue by TylerPflueger** [Semantic-Org/Semantic-UI#3444]
When selecting an item from the search selection dropdown, the selected item becomes `active` but the first item in the dropdown keeps the `selected` class. I'm not entirely sure if this was intended since the regular dropdowns do update the selected item with `selected active`. Here's a [fiddle](//jsfiddle.net/tpflueger/peuszssw/6/).

**Comment by Cuel** [comment]
Yeah, the 'active' item has 'active selected' until you click the dropdown, at that point 'selected' gets moved to the first element. Not sure why this is?

**Comment by jlukic** [comment]
This is intended, search dropdown preserves search location on selection

**Comment by TylerPflueger** [comment]
But should it not also have `selected` even after preserving the location?

**Comment by Cuel** [comment]
Yeah I'd expect that if there was an 'active' element, it would be 'selected' until user inputs something into search, or starts hovering the dropdown

**Comment by jlukic** [comment]
`selected` refers to current keyboard selection. `active` refers to the currently activated element.
