### ISSUE TITLE
Validate Form Field Only If It's Visible / Some Value

### ISSUE THREAD

**Issue by nephix** [Semantic-Org/Semantic-UI#3450]
There's no option I'm aware of at the moment to dynamically change validation rules of a form.
This would be handy if you have a form that shows / hides input fields depending on how the user interacts with the form.

Here's a fiddle: http://jsfiddle.net/q2hLrm13/5/ (got it from https://stackoverflow.com/questions/34108280/semantic-ui-form-validation so props to them)

**Steps**:
1. Click on validate // form is validated
2. Select "youtube" from type // a new field shows up at the bottom
3. Enter a name and leave URL blank
4. Click validate again

**Expected result**:
The newly added field is validated or there's a behavior in Semantic UI to dynamically add **AND** remove specific rules from the rule set. A _validate_ property would also be ok that you can pass a true or false to, and Semantic UI either validates or doesn't validate the field.

In that case, the form should not be validated successfully and an error at  the YouTube URL should be shown.

I have to say here that I'm aware that I can call form.form({...}); again to initialize again the fields to be validated. However, if you have a huge form and rule set this means great overhead for just adding or removing a single validation rule.

**Actual result**:
The form is validated and no errors occur

**Comment by ateles** [comment]
Any update on this? In short, it should be possible to add/remove rules on individual fields. As it is now, it's all or nothing.
