### ISSUE TITLE
Popup showing in wrong element when multiple popups with same name

### ISSUE THREAD

**Issue by ShawnCholeva** [Semantic-Org/Semantic-UI#3451]
Hey all, I am having an issue with displaying popups like in the title.  I have an array of objects and each object is being displayed on the screen in a card.  On the cards I have an edit button that has the class ".my-object.button" to fire the popups.  This is the same name for each button's class on each different card.  This looks for the div id specified that is located in a popup component and loads the content.
```
$('.my-object.button')
            .popup({
                popup: '#objectItemPropertiesPopup',
                onShow: (element) => this.setSelectedItemForPopup(element)
            });
```

When the edit button is clicked it loads the properties according to each card fine.  This issue is that is seems some buttons randomly display their popups over previous buttons.  For example, if I hover over button 1 then button 2, when I go back to button 1 it will show the correct information but over button 2.  However, if I hover over a button that is being hovered over for the first time, it always works fine.  It seems to me that the element is somehow being stored incorrectly when there are multiple elements with the same name.  Any advice or thought on the matter?

**Comment by bryce27** [comment]
I'm also having this problem.

**Comment by avalanche1** [comment]
Closing because no test case.
