### ISSUE TITLE
Print problem with CSS parameter overflow:hidden in firefox.

### ISSUE THREAD

**Issue by asbiot** [Semantic-Org/Semantic-UI#3454]
# Problem

Firefox (current stable version v.42.0, OS: Linux and Win7) appears to have a problem with the CSS  parameter overflow-x and the value hidden.

``` javascript
overflow-x:hidden
```

Using it means that the browser only shows the first page in the print-preview and also only prints the first page. The CSS tag is used on the <body> tag in semantic.min.css.

To clarify, firefox appears to be the only browser suffering from this problem. However, it is a very popular browser...
# Solution

It should be investigated, whether the overflow command is really necessary. I set it to "visible" on my site to solve the problem and can't find any differences in the presentation of the site.

**Comment by jlukic** [comment]
This is to prevent issues with horizontal scrollbars caused by using negative margins. Removing this would cause issues with grids used directly nested from `body`.

**Comment by adamcollingburn** [comment]
Having issues with this at the moment - can we not fix this with by targeting print view with "@media print" and making relevant overflow/display changes there?

**Comment by MurzNN** [comment]
@asbiot can you describe in which place and css selector you change `overflow-x` for fix Firefox printing? I try in many places, but can't fix Firefox printing problem - it prints only first page.
Here is Firefox issue about this: https://bugzilla.mozilla.org/show_bug.cgi?id=258397#c46 but seems Firefox developers don't want fix it :(
So we must fix this in our side manually :(

**Comment by MurzNN** [comment]
I have found manually block that broke printing in Firefox on my website, here is removed lines from `semantic.css`:
```
.ui.grid {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}
```
After removing it - Firefox print all pages, after give back - only first page.

**Comment by Banandrew** [comment]
Does it make sense to keep the issue opened if it’s an issue with Firefox?

@MurzNN It seems to be an issue with Flexbox in the end: https://bugzilla.mozilla.org/show_bug.cgi?id=1241323

**Comment by asbiot** [comment]
I am happy to close the issue. It seems this thread offers two workarounds and we can hope that the firefox team may fix the underlying cause at some point.

**Comment by MurzNN** [comment]
The problem is that Firefox developers don't want to fix this problem. They describe that CSS frameworks must create special rules for media @print for normal printing (without any floating blocks), instead of move problem with printing responsive design to browser developers.

**Comment by Banandrew** [comment]
We can file it as enhancement—please let me know if you’d like me to do that—but I don’t think it will be implemented any time soon, as there’re more important things that should be fixed/added before that. So it’s that awkward situation where it’s not going to be implemented by Mozilla, and it’s not going to be implemented by SUI, or it will take years to do that, so maybe it’s better to leave the issue closed, and let the developers to somehow implement it where needed.

I understand that it’s probably a huge pain to fix, considering that the framework’s core layout component uses Flexbox, but yeah, not much can be done about it except for labeling. Maybe we can return to it when the browser support for CSS grids will reach adequate numbers, and it will make sense to rewrite the grid component to use CSS grids instead.

**Comment by asbiot** [comment]
I am happy to leave the issue closed as I don't have a problem with it currently. If someone else feels strongly about it and is of a different opinion, then please comment.

**Comment by MurzNN** [comment]
Yes, leave it closed, seems that Firefox developers starts fixing print bugs: https://bugzilla.mozilla.org/show_bug.cgi?id=939897
