### ISSUE TITLE
Add UI Docs search to website

### ISSUE THREAD

**Issue by kmalakoff** [Semantic-Org/Semantic-UI#3456]
I find myself going to google to search for topics in the left sidebar because my browser `find` pulls out text both in the sidebar, but also the active view plus it doesn't auto-scroll to the menu topic so sometimes I find it is highlighted, but off page.

If there was a way to search the UI Docs, it would make navigating much easier...unless I am missing that search already exists somewhere?

**Comment by calmdev** [comment]
@kmalakoff probably not the solution you're looking for, but it may be helpful for others. If you're using OSX, check out an app called [dash](https://kapeli.com/dash). There's a user contributed documentation set for SUI:

![screen shot 2015-12-14 at 2 38 32 pm](https://cloud.githubusercontent.com/assets/461249/11791778/a51e633e-a270-11e5-8511-76517c56b286.png)
