### ISSUE TITLE
Change the default font

### ISSUE THREAD

**Issue by nileshbits** [Semantic-Org/Semantic-UI#3465]
This is a nitpick, but a powerful one. On very close inspection, Lato is not a powerful default business font, like Arial and Helvetica, which are simple and look very good with well-defined strokes. I'm having to customize the default Semantic build for simply this reason. I think it would be best for the default Semantic build to stick with these fonts.

Just my 2 cents.

**Comment by jlukic** [comment]
I respectfully disagree, but I appreciate your feedback. Lato is used by Slack and i would consider at a strong default for nouveau-business style.
