### ISSUE TITLE
Decouple from Jquery?

### ISSUE THREAD

**Issue by Goatic** [Semantic-Org/Semantic-UI#3467]
Hi - will you by any chance consider decoupling semantic from jquery? With your modular approach, depending on a big framework like jquery would be nice to resolve with a pure js implementation of necessary utilities... Depending on how much coupling you have... Any thoughts on this?

**Comment by jlukic** [comment]
Appreciate your feedback, but realistically I dont believe I'll decouple from jQuery anytime in the near future.

**Comment by Goatic** [comment]
no worries :) thanks
