### ISSUE TITLE
setting source-property of search-element

### ISSUE THREAD

**Issue by Goatic** [Semantic-Org/Semantic-UI#3469]
Hello

I'm working with Meteor, and I have to update my search-source seamlessly. Is there any way I can do that, without ruining user experience while it happens?

I can't find any behaviours that let's me fiddle with the source

**Comment by jlukic** [comment]
Use `apiSettings` and `mockResponseAsync` 
http://semantic-ui.com/introduction/new.html#custom-backends

**Comment by Goatic** [comment]
thanks :)
