### ISSUE TITLE
Why use !importants...?

### ISSUE THREAD

**Issue by jason-engage** [Semantic-Org/Semantic-UI#3473]
Why the need for these importants? It forces me to add importants in my sass...

.ui.menu .ui.dropdown .menu>.item {
    margin: 0;
    text-align: left;
    font-size: 1em!important;
    padding: .71428571em 1.14285714em!important;
    background: 0 0!important;
    color: rgba(0,0,0,.87)!important;
    text-transform: none!important;
    font-weight: 400!important;
    box-shadow: none!important;
    -webkit-transition: none!important;
    transition: none!important;
}

**Comment by jlukic** [comment]
Check archived issues for threads discussing this.
