### ISSUE TITLE
Disabled input still got focus with tab index

### ISSUE THREAD

**Issue by dan-genty** [Semantic-Org/Semantic-UI#3474]
This is the sample of disabled input text from Semantic UI (http://semantic-ui.com/elements/input.html)
```html
<div class="ui disabled input">
  <input type="text" placeholder="Search...">
</div>
```
The input is not fully disabled because when I pressed tab key, the cursor focused on the input and then I could press anything I wanted

**Comment by jlukic** [comment]
Add `tabindex=-1` to the input to specify the intent to remove the element from tabbing order.
