### ISSUE TITLE
Tab - Add Settings to Remove Siblings Active vs All Activating Menus

### ISSUE THREAD

**Issue by exoego** [Semantic-Org/Semantic-UI#3475]
#### Steps to reproduce
1. Open https://jsfiddle.net/p5tv6ue3/3/ 
2. Click __Sub1__ tab in __right__ menu

#### Expected
Tabular menu should have single active tab even if the menu is divided into left and right,
so that users of Semantic-UI put some tabs of different purpose low importance in right menu.

Some example of such tabs can be found in http://semantic-ui.com/collections/menu.html#tabular

#### Actual result
Active tab appears both in left menu and right menu.

#### Issue reproduced on
- Firefox 42, 43
- Chrome 47.0.2526.106
- IE 11

**Comment by jlukic** [comment]
Currently `$tab` considers only siblings to remove `active`.

This should be a setting, whether to remove active from siblings or all elements initialized together.

**Comment by jlukic** [comment]
Added a new setting `deactivate` where you can specify whether all elements or siblings should be deactivated.
