### ISSUE TITLE
[Popup] - Popup with option({inverted:true}) does not use inverted colours

### ISSUE THREAD

**Issue by Qqwy** [Semantic-Org/Semantic-UI#3477]
**Steps to Reproduce**
1. Run the following JS

```
$('#new_user_email_input')
          .popup({
            title   : 'Could not add User',
            content : failure.error,
            on: "manual",
            inverted: true  
        });
        $('#new_user_email_input').popup("show");
```

**Expected**
The Popup should show with inverted colours.

**Result**
The Popup does uses its usual colours (It does not get the `inverted` class).

**Comment by uyab** [comment]
Check https://github.com/Semantic-Org/Semantic-UI/issues/3367
