### ISSUE TITLE
Attached Segment Following Tabular Menu Displays Incorrectly

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3479]
1px offset

http://jsfiddle.net/owdfposv/1/

**Comment by jlukic** [comment]
I've now supported this for a max of 2, `attached` segments following `tabular` menu.

**Comment by nite2** [comment]
There is another issue here - styles are applied only to first (and now second) bottom attached segments. But usually just use display:none on not-active tab, therefore there may be, for example with six tabs, five bottom attached segments (all with display:none) following the menu, and the sixth segment is visible, therefore this style will not be applied.
It can be tested on http://semantic-ui.com/modules/tab.html#/examples with first tab example, just surround each tab content (the text: "First","Second","Third") with block element (for example a div) and the third tab will resize by 2px on switch

**Comment by falco467** [comment]
Why is the Style not active for all .ui.bottom.attached.tab.segment ?
Should a **tab** segment not always use the style ?

**Comment by lubber-de** [comment]
The community fork Fomantic-UI fixed this for all tab siblings by https://github.com/fomantic/Fomantic-UI/pull/1480
