### ISSUE TITLE
Table headers within table body are not styled like those within table head.

### ISSUE THREAD

**Issue by codyburleson** [Semantic-Org/Semantic-UI#3482]
It seems that a table header within table body is not style appropriately. This is needed for tables where the headers flow down the left-hand side of the table instead of the top. As in the following case:

``<table class="ui celled table">
    <tbody>
    <tr>
        <th>
            <strong>Username</strong>
        </th>
        <td>john.doe5@example.org</td>
    </tr>
    <tr>
        <th>Password</th>
        <td>MyStr0ngP@ssw0rd#</td>
    </tr>
    </tbody>
</table>``

This renders as follows (doesn't have the nice grey background like normal table headers that flow across the top.

![tableheadersexample](https://cloud.githubusercontent.com/assets/7317733/11857234/14084da8-a41c-11e5-93da-6ec739806f34.png)

**Comment by jlukic** [comment]
I'd recommend modifying `definition table` styles and using `td`. Alternatively style the first row with `:first-child`

I wasn't familiar with using `th` inside of `tbody` (although it does seem to be legal and encouraged).   Generally the way SUI understands `th` is "the part that contains vertical header labels at the top of a table".

**Comment by codyburleson** [comment]
I can do that. Thanks. I just thought you might want to include it in the base code.
