### ISSUE TITLE
field and input does not work well together?

### ISSUE THREAD

**Issue by sondreb** [Semantic-Org/Semantic-UI#3484]
I'm using the fields/field classes and trying to append icons to them, and they clearly don't play well together. What is the proper way of using them in combination?

Here is a quick example: http://codepen.io/sondreb/pen/adNzJd

If you remove the "input" class on the first input element, everything looks fine but no icon appears.

Without:

![image](https://cloud.githubusercontent.com/assets/309938/11867868/3656484a-a4b4-11e5-9dc9-bf80cb2f20a5.png)

With: 
![image](https://cloud.githubusercontent.com/assets/309938/11867880/44dd4080-a4b4-11e5-9e3b-c1d71a8e2e2c.png)

Form (fields/field): http://semantic-ui.com/collections/form.html
Input: http://semantic-ui.com/elements/input.html

**Comment by iugo** [comment]
http://semantic-ui.com/elements/input.html#icon

```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.css">


<div class="ui form">
  <div class="fields">
    <div class="field">
      <label>Username</label>
      <div class="ui left icon input">
        <input placeholder="Username……" type="text">
        <i class="users icon"></i>
      </div>
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password">
    </div>
  </div>
  <div class="equal width fields">
    <div class="field">
      <label>First name</label>
      <input type="text" placeholder="First Name">
    </div>
    <div class="field">
      <label>Middle name</label>
      <input type="text" placeholder="Middle Name">
    </div>
    <div class="field">
      <label>Last name</label>
      <input type="text" placeholder="Last Name">
    </div>
  </div>
</div>
```

**Comment by jlukic** [comment]
Generally you cant join separate components, parts of a component on the same element unless explicitly done in the docs, i.e. `ui dropdown button`
