### ISSUE TITLE
Trying to use legacy gulp file to compile less.

### ISSUE THREAD

**Issue by ericwebster** [Semantic-Org/Semantic-UI#3485]
Hey Gang,

I'm trying to add semantic-ui with my projects existing gulpfile.

I am trying to use gulp-less to compile and minify semantic-ui from Bower to an dist folder.

I have installed Semantic via Bower and I have a semantic.json and theme.config in my project root.

From there I am doing the following in gulp ..

gulp.task('less', function () {
  return gulp.src(['assets/css/_.less', './plugins/bower/semantic/src/_.less'])
    .pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ]
      }))
    .pipe(gulp.dest('./dist')); 

however when I do this I am getting the following error.

> Potentially unhandled rejection [2] variable @themesFolder is undefined in file /Users/ewebster/Projects/CP/2015-holiday-card/plugins/bower/semantic/src/theme.less line no. 16

in the root of my folder I have a "theme.config" which seems to be utilized -- here are relevant less vars being set in it

/\* Path to theme packages */
@themesFolder : 'plugins/bower/semantic/src/themes';

/\* Path to site override folder */
@siteFolder  : 'site';

@import "plugins/bower/semantic/src/theme.less";

I'm sure i'm doing something silly on my end, but any thoughts would be awesome!

Is there a how-to to best integrate semantic-ui to a project with a pre-existing gulp file?

**Comment by sonicparke** [comment]
I'm having the same issue with import statements when using variables that are defined in a separate file.
