### ISSUE TITLE
An open gap on iOS 9

### ISSUE THREAD

**Issue by mikkhait** [Semantic-Org/Semantic-UI#3488]
In relationship to #1985

I believe that this needs to be removed now as it seems to be resolved in

``` javascript
html.ios,
html.ios body {
  height: initial !important;
}
```

Removing it, solve the problem

![screenshot 2015-12-18 22 24 10](https://cloud.githubusercontent.com/assets/1232731/11911768/2749066c-a5d6-11e5-808e-5b4faf5bf7f2.png)
 iOS 9

**Comment by blq** [comment]
I can confirm this. In iOS 9.1 and 9.2 basically the whole screen is covered by gray overlay - unusable! Keeping old css seems better.

**Comment by kntmrkm** [comment]
Yes, I also confirmed . (version 2.1.8)

<img width="373" alt="iphone_6_-_iphone_6___ios_9_2__13c75_" src="https://cloud.githubusercontent.com/assets/2703486/13196686/ae8b0836-d818-11e5-9c00-191ae4aac53c.png">

So, I added below css.

```
html.ios,
html.ios body {
  height: 100% !important;
}
```
