### ISSUE TITLE
animating events don't work after ajax request

### ISSUE THREAD

**Issue by milkymura** [Semantic-Org/Semantic-UI#3489]
basically I'm using ajax to get some items (with images that contain dimmer animations) 

after appending those 'div class="ui item"'      *example only just assume that I got it correctly because I really got it correctly there were no missing div classes. 

the dimmer class doesn't work 

this is the code that I used:
$('.item .image ').dimmer({
    on: 'hover'
  });

**Comment by avalanche1** [comment]
Closing because no test case.
