### ISSUE TITLE
[Slider] - It looks like that the slider never display

### ISSUE THREAD

**Issue by bin16** [Semantic-Org/Semantic-UI#3495]
**Steps to Reproduce**
1. Just open the page: http://semantic-ui.com/modules/slider.html
2. You will find that the slider never display in its position
I check it in both ff and chrome

Or it's my question?

**Comment by migajek** [comment]
Good question. There seem to be no slider module in Semantic sources at all.

**Comment by sanga** [comment]
Seeing same thing here. From chrome devtools

```
Uncaught TypeError: $slider.slider is not a function semantic.dropdown.ready @ slider.js:19 [snip...]
```

**Comment by martinduparc** [comment]
I was looking for the same thing and even if there is a listing on the semantic-ui site, it isn't ready (see https://github.com/Semantic-Org/Semantic-UI/issues/1336)

**Comment by sanga** [comment]
Fair enough. Perhaps it should be removed from the docs in that case? Or at least a note added that it's not implemented yet?

**Comment by thomthom** [comment]
Are there third party addons to fill this gap?

**Comment by jlukic** [comment]
I started work on this yet, but have not had a chance to complete it. 

Slider docs were mistakenly checked in from a feature branch.

**Comment by peyman-mohamadpour** [comment]
Feature not added yet? Is there any schedule on this for near future?

**Comment by xanview** [comment]
There is one here: https://github.com/tyleryasaka/semantic-ui-range - but it says "range" despite not supporting range selection :( - you can only select a single value, so one and only one handle on the slider.
