### ISSUE TITLE
Column attribute "justified" gets overwritten on centered grids

### ISSUE THREAD

**Issue by maxhq** [Semantic-Org/Semantic-UI#3496]
Example: http://jsfiddle.net/maxhq/ayxgqe97/

I think the problem is that in grid.less [line 955](https://github.com/Semantic-Org/Semantic-UI/blob/5062d0b5fb9f3c5605f04cd8e1cfa82499fe0d2a/src/definitions/collections/grid.less#L955) only takes care of `xxx aligned` but not of `justified`.
Fix should be as easy as adding `:not(.justified)`to `column` in all three lines.

Version: Semantic UI 2.1.6
Browser: Firefox 43.0.1 (Linux)

**Comment by jlukic** [comment]
Yep noticed as wel

**Comment by jlukic** [comment]
Added in `2.1.9`
