### ISSUE TITLE
[Header] Sub Header not inverted in basic modals

### ISSUE THREAD

**Issue by ProjectCleverWeb** [Semantic-Org/Semantic-UI#3499]
When a basic modal has a header it is inverted but if you add a `sub header` its text is not inverted, causing it to become unreadable on the darkened background

[Fiddle](http://jsfiddle.net/vLw8maLg/1/)

**Comment by jlukic** [comment]
Looks like a bug

**Comment by jlukic** [comment]
Hi, some elements still require `inverted` on nested sub-elements. Use `ui inverted header`

http://jsfiddle.net/jf6xokq4/
