### ISSUE TITLE
is there a custom form validation?

### ISSUE THREAD

**Issue by coolyrat** [Semantic-Org/Semantic-UI#3501]
I have 3 field in my form, and has to fill in at least one of them, and i am looking for a custom function to achieve the goal. Thanks=)

**Comment by xiechao06** [comment]
please check http://semantic-ui.com/behaviors/form.html
``` 
Validation rules are found in $.fn.form.settings.rules, to add new global validation rules, modify $.fn.form.settings.rules to include your function.
```

**Comment by jlukic** [comment]
Thanks @xiechao06

**Comment by xiechao06** [comment]
@jlukic, BTW, IMHO it's not so convenient to add a custom validation rule, I need to put validators into $.fn.form.settings.rules in order to use it. As a result, I insert boundless rules into "$.fn.form.settings.rules", and many of them are just used in one form.

why not just something like:

```javascript
$myForm.form({
      fields: {
            productionDate: {
                  identifier: 'production_date',
                  rules: [
                        function ($form) {
                               // this is the "input element"
                               if (this.value > $form.expire_date.value) {
                                     throw new Error("production date should be earlier than expire date!");
                               }
                        }
                  ]
            }
      }
});
``` 
here, the prompt is put in the error thrown.

**Comment by coolyrat** [comment]
@xiechao06 yes! this is exactly what i am looking for! i hope this support soon =)

**Comment by nikolaybobrovskiy** [comment]
I also vote for validation via function feature.

**Comment by xiechao06** [comment]
@nikolaybobrovskiy agree! I even think a validation function should always return a promise/$.Deferred, if everything is ok, just *resolve*, otherwise it will be *rejected* with the actually error reason
