### ISSUE TITLE
[Segment] [Message] 'compact' is overridden by other attributes

### ISSUE THREAD

**Issue by john-osullivan** [Semantic-Org/Semantic-UI#3502]
First off -- thanks to you contributors for making this great library.  I'm really enjoying working with the semantic mindset, the classes are all laid out very intuitively.  That said, I've run into a couple of bugs when I combine the compact class with others on the segment and message items.  The issues are similar, but I'll describe them separately.
### Segment

I am trying to simulate a segment header by using two segments and combining them with `top attached` and `bottom attached`.  Normally this works just fine.  However, when I also try to combine them with `compact`, the effects of `compact` are overridden --- both segments take the width of their container.

To test, compare the results of

```
<div class='ui secondary inverted compact segment'>
    Header
</div>
<div class='ui compact segment'>
    Content
</div>
```

with those of 

```
<div class='ui secondary inverted compact top attached segment'>
    Header
</div>
<div class='ui compact bottom attached segment'>
    Content
</div>
```

The former segments are compact and detached, while the latter are attached and container width.
### Message

The message bug is essentially identical, except the "offending" class is `icon`.  When I try to make a `ui compact icon message`, the `compact` CSS gets overridden and the message is full width again.  You can test it out with

```
<div class='ui icon compact message'>
    <i class='help icon'></i>
    <div class=content'>
        <div class='header'>Header</div>
        <p>Content</p>
    </div>
</div>
```

versus

```
<div class='ui compact message'>
    <div class=content'>
        <div class='header'>Header</div>
        <p>Content</p>
    </div>
</div>
```

The former will have the icon but be full width, while the latter removes the icon and only takes the space of its content.  These bugs aren't game-breaking, but I'd hoped to be able to mix and match these classes and still get good results.  Please let me know if this is intended behavior or a bug -- thanks!

**Comment by neokio** [comment]
I'm surprised at the lack of response to this. It's a valid and troublesome glitch, one I repeatedly encounter.

I get that compact's `display: inline-block` doesn't play nice with icon's flex box, and I personally don't have the CSS mastery to solve this quickly. Is there no interest in a solution?

**Comment by kspeakman** [comment]
Ran into this today, but found that this case is actually already covered and [documented](https://semantic-ui.com/elements/segment.html#compact) (sort of, not the message interaction with compact).

Don't try to put two compact segments next to each other. Instead, wrap them in a "ui compact segments" container. Each containing segment is automatically attached without specifying it and still compact. Also works with attached messages.

```html
<div class="ui compact segments">
  <div class="ui secondary inverted segment">
    Stuff
  </div>
  <div class="ui bottom attached icon message">
    <i class="blue info circle icon"></i>
    <div class="content">
      <div class="header">
        And Junk
      </div>
      <p>And Things</p>
    </div>
  </div>
</div>
```

Made a [codepen](https://codepen.io/anon/pen/wpwNRG) as well.
