### ISSUE TITLE
Is it possible to reduce the file size

### ISSUE THREAD

**Issue by liniu** [Semantic-Org/Semantic-UI#3503]
Is it possible to reduce the file size？

**Comment by sstok** [comment]
Yes. Remove all the content from the file and it should shrink :stuck_out_tongue_closed_eyes: 

No seriously, your question is a bit short and incomplete. :smiley: 
When you build semantic-ui or download the pre-compiled version it should also provide a minified version where all the comments whitespace (as much as possible) are stripped to reduce the file size.

Additionally you can choose to "disable" certain modules that you don't need.
See the documentation for more information.

The last thing you can do is enable compression.
https://developers.google.com/speed/docs/insights/EnableCompression

For more tips and advice please use StackOverflow as the issue-tracker is only used for reporting bugs and discussing new features.

**Comment by liniu** [comment]
thank you
