### ISSUE TITLE
Password strength meter with progress bar.

### ISSUE THREAD

**Issue by aketai** [Semantic-Org/Semantic-UI#3504]
Please advice to implement password strength meter with progress and js:

Must have capital letter, numbers and lowercase letters
var strongRegex = new RegExp("^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\\W).*$", "g");

Must have either capitals and lowercase letters or lowercase and numbers
var mediumRegex = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");

Must be at least 6 characters long
var okRegex = new RegExp("(?=.{6,}).*", "g");

Thank you

**Comment by sstok** [comment]
Please ask your question on StackOverflow, this has nothing to do with Semantic UI.
In fact. https://stackoverflow.com/questions/34453420/password-strength-meter-with-semantic-ui
