### ISSUE TITLE
[Dropdown] Incorrect direction calculation

### ISSUE THREAD

**Issue by parisholley** [Semantic-Org/Semantic-UI#3505]
Still trying to figure out what is actually causing the problem (I am using a custom react setup, was able to reproduce in chrome). The dropdown works the first time, but every open afterward is calculated wrong. I found that the "hidden" class causes the calculation.menu to produce the wrong numbers. Will submit a PR that seems to fix it for me, but not sure what its impact is or how to reproduce effectively outside my environment.

**Comment by jlukic** [comment]
@parisholley I'm holding off merging this in until I have a specific test case that I can confirm this fixes.

**Comment by lubber-de** [comment]
Fixed. See http://jsfiddle.net/47wtpcy8/2/
