### ISSUE TITLE
Happy Holidays

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3508]
I just wanted to take some time to let you know how thankful I am for all of the work that everyone in the community has given to Semantic UI. Thank you to everyone who's helped submit bugs, add pull requests, ask questions, or answer questions from others. 

You guys are the best, and help encourage me to work towards making Semantic UI better. 

Here's to another wonderful year with Semantic UI.

**Comment by SeanOceanHu** [comment]
Happy New Year :tada:

**Comment by sstok** [comment]
And thank you for making an amazing front-end framework :+1:

**Comment by kfei** [comment]
Thanks for your hard work! :smile:

**Comment by kvetoslavnovak** [comment]
Thank you!!!!

**Comment by deneuxa** [comment]
Thank you Jack !

**Comment by ronaldo-systemar** [comment]
Happy new year and thank you for the great SUI framework :tada:
