### ISSUE TITLE
[Dropdown] First Click on Dropdown Icon Does Not Query Results

### ISSUE THREAD

**Issue by loudandwicked** [Semantic-Org/Semantic-UI#3509]
When using responseAsync in apiSettings for dropdown, a dropdown does not show up when clicking a dropdown icon and it also does not fire an async request. When a dropdown gets input focus, an async request is sent and the response is loaded, and from then on a dropdown starts showing up when clicking this same icon.

Here's a jsfiddle with this behaviour: http://jsfiddle.net/71y63cbq/

**Comment by stokescomp** [comment]
I also see the dropdown arrow doesn't work if I use the url in apisettings.:
apiSettings: {
			url: 'script/search.js.php?q={query}'
		},

**Comment by woodcockjosh** [comment]
Big problem for usability. Users keep clicking on icon but it doesn't work. Any idea when we can fix this?

**Comment by luklapp** [comment]
Same issue here. Did someone find a fix for this bug?

**Comment by jlukic** [comment]
Fixed in `2.2.8`
