### ISSUE TITLE
[UI] Resizable Behaviors

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#351]
### Resizable

Resizable elements allow users to customize their interface.
#### Usage

``` html
<div class="ui resizable two column grid">
    <div class="column">
        I'm the left column
    </div>
    <div class="ui resizable divider"></div>
    <div class="ui column">
        I'm the right column
    </div>
</div>
```

``` javascript
$('.ui.resizable').resizable({
    snap: false,
    collapsible: false
})
```

Snap is a number, like `10`.  which represents the number of 'columns'.

Collapsible determines whether a column may be completely hidden.  When it's false, columns must be at least 1 grid unit wide (snap overrules the default 16).

**Comment by francisdb** [comment]
Did anybody ever implement this?

**Comment by ziacik** [comment]
It's 2017 now. Still no progress in this?

**Comment by philrykoff** [comment]
Would be great for modals, especially in combination with something like "moveable".

**Comment by brigand** [comment]
@jlukic you interested in having this feature?

**Comment by wiesesascha** [comment]
@brigand: would be great for sidebars/modals like @philrykoff said!

**Comment by agence104** [comment]
Id be really interested into this feature.

**Comment by jslay88** [comment]
Am needing it bad, and having to implement jquery UI on top of semantic to accomplish what I need without a lot of effort. Would be nice to have it built into Semantic from the start.
