### ISSUE TITLE
A "disabled loading" button is not disabled - it is still clickable and fires events

### ISSUE THREAD

**Issue by nileshbits** [Semantic-Org/Semantic-UI#3510]
to be specific, it is a semantic-ui form submit button.

**Comment by jlukic** [comment]
Disabled buttons should prevent javascript events.

**Comment by nileshbits** [comment]
i was using chrome 47

**Comment by nileshbits** [comment]
Is this fixed? Should I try again?

**Comment by kmd1970** [comment]
I have the same issue. If I combine "disabled" class with "loading" class, the button is still clickable. 

My example:
https://jsfiddle.net/kmd1970/55qog60h/

**Comment by jlukic** [comment]
Now in #2933

**Comment by unostar** [comment]
$.fn.api.settings.className.loading = 'loading disabled';
