### ISSUE TITLE
comment not fluid

### ISSUE THREAD

**Issue by MeKarina** [Semantic-Org/Semantic-UI#3513]
comment not fluid even tough adding `style="margin-left:0em; margin-right:0em"`

http://codepen.io/anon/pen/rxMoPg?editors=100

i feel like this is semantically wrong...

**Comment by jlukic** [comment]
Text content has a reasonable max length to avoid words per line being too high (this is a readability issue)

Modify `@maxWidth: none;` to change

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/views/comment.variables#L10

**Comment by MeKarina** [comment]
thank You for letting me know...

i'm sorry if that was annoying...

love semantic-ui... =))

**Comment by thiagomajesk** [comment]
Adding `style="max-width: 100%"`  to **.ui.comments** should do the trick :wink:
