### ISSUE TITLE
[Fixed Example] Use Padding-Top to Offset Page Container

### ISSUE THREAD

**Issue by cynecx** [Semantic-Org/Semantic-UI#3516]
The issue is that when having a fixed nav bar and content div below it uses margin-top: 5em, the scrollbar is appearing even when the webpage doesn't even have any content.
That is because of this definition in html, body which basically sets the height to 100%.
Bootstrap for example doesn't set this so it doesn't have the issue with the scrollbar.

![issue01](https://cloud.githubusercontent.com/assets/5961244/12020670/3b8b8234-ad7f-11e5-810c-aad503ad71ca.jpeg)

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/globals/site.less#L30

**Comment by jlukic** [comment]
This is caused by collapsible margins. Simple fix is to use `padding-top` instead of margin top. I'll update the example.

**Comment by cynecx** [comment]
I have a question though. What is the benefit of defining height: 100% ? Why wouldn't bootstrap doesn't set this ?

**Comment by cynecx** [comment]
https://jsfiddle.net/L7b0uyg5/
The problem is still there if I remove the padding-top which I don't understand why. When adding height: auto it works.

**Comment by arthurwhite** [comment]
What if we use a `.ui.text.menu` (which makes use of `margin`) on top?

Because of this questionable `html, body { height: 100%; }`, we must monkey patch a component that should work out of the box. 😞

**Comment by dietergeerts** [comment]
Though I love lots of concepts of semantic-ui, setting 100% on body and html is EVIL, especially if you want to print a page etc...
