### ISSUE TITLE
slider doesent work in the official docs.

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#3519]
Hi,
got an error in http://semantic-ui.com/modules/slider.html#/definition 

`Uncaught TypeError: $slider.slider is not a functionsemantic.dropdown.ready @ slider.js:19j @ jquery.min.js:2k.fireWith @ jquery.min.js:2n.extend.ready @ jquery.min.js:2I @ jquery.min.js:2`

![sans titre](https://cloud.githubusercontent.com/assets/2527234/12027273/3cc82fd6-adc4-11e5-96bb-2b86dbc1cc4b.png)

**Comment by jlukic** [comment]
This was accidentally in docs with `2.1.7` push. This is not ready and has been removed.

**Comment by abdelouahabb** [comment]
ah, thank you :)

**Comment by chrisbell08** [comment]
Hi Guys, just a heads up this still gets picked up by google... Do you know how far this away this module is from being ready?
<img width="850" alt="screen shot 2016-04-12 at 08 04 07" src="https://cloud.githubusercontent.com/assets/8242722/14452257/56f26a98-0085-11e6-8459-ec7c18d63a76.png">

**Comment by Asoul** [comment]
Is slider available now?
