### ISSUE TITLE
[Dropdown] Support Delimiters from Pasting

### ISSUE THREAD

**Issue by tkreis** [Semantic-Org/Semantic-UI#3521]
_Not sure if this is intended or a bug._

When you paste a string into the dropdown it gets pasted as a whole and not separated by the delimiter. 

This means a user can paste: AF, DF, CF but typing it directly in the input is impossible . 
![Gf of possible error](http://i.imgur.com/XAyX3QI.gif)

**Comment by jlukic** [comment]
It might be complicated to support this, but it does make sense that it should be supported.

**Comment by lubber-de** [comment]
Fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2167
