### ISSUE TITLE
Sidebar Closable Setting Issue

### ISSUE THREAD

**Issue by vrushank** [Semantic-Org/Semantic-UI#3523]
Hi,

It seems that even if closable state of sidebar is set to false sidebar closes and re-opening sidebar receives the new state.

For instance, I have two buttons:
1. toggle sidebar
2. fix sidebar

I have following code working for toggle sidebar,
$('.ui.sidebar')
    .sidebar('attach events', '.toggle-sidebar')
    .sidebar('setting',{
        transition:'overlay',
        dimPage:false,
        closable:true,
        debug:true
    });

Now, when I click on fix sidebar button, I want to set closable state of the sidebar to false. Means when someone clicks on content area sidebar should not disappear.

Following is the code wrote on fix sidebar button click,
$('.ui.sidebar').sidebar('setting',{
            closable:false,
            debug:true
        });

If I check the closable state in the console its set to false but still clicking on content area closes the sidebar.

Now when I click on toggle sidebar button and clicking on content area does not close sidebar.

Shouldn't it work on fix sidebar button?

Please guide me on the right direction.

Thanks,

**Comment by IonutBajescu** [comment]
Please post your code using jsfiddle.

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
