### ISSUE TITLE
Modal onApprove still closes if returning false

### ISSUE THREAD

**Issue by DHNCarlos** [Semantic-Org/Semantic-UI#3524]
Reading from the docs, I found out that I can cancel an `onApprove` from hiding the modal by returning false and from another issue (#2351) I found that it only works on buttons that have the `.approve` class so that is what I have done.

I have an `.approve` button inside the modal `.actions`:

```
<button class="ui green approve new repo button">Create</button>
```

I added some logging to my modal as well as set it to verbose logging (`verbose: true`).
So as a quick test I did

```
onApprove: function (click) {
        console.log("Reached onApprove", click);
        return false;
}
```

From my browser output I can see that `onApprove does get triggered by the button`

```
Reached onApprove [button.ui.green.approve.new.repo.button, context: button.ui.green.approve.new.repo.button]
```

But for some reason onApprove still closes the modal and compeltely ignores my false return. 

From the source it seems that when I return false, then it should verbosely log that false was returned but I'm not getting that verbose log entry in my browser.

This is with Semantic 2.1.7

**Comment by DHNCarlos** [comment]
Could this be due to how I attach a listener for the modal?

```
$newRepoModal.modal("attach events", ".new.repo.button");
```

**Comment by DHNCarlos** [comment]
After a bit of tinkering the issue is tied to `attach events`.

I tested by simply using `.modal("show")` and then return false works as it should. However when opening the modal using a button that has been added with `attach events` then it doesn't work.

**Comment by jlukic** [comment]
Please read the contributing guide to see how to distinguish posting issues with reporting bugs. As posted this should go on Gitter or our project talk board.
