### ISSUE TITLE
form inline fields display abnorma when use Chinese in label

### ISSUE THREAD

**Issue by huyinghuan** [Semantic-Org/Semantic-UI#3528]
if use english it is ok, but when use Chinese the label width isnt enough．
![image](https://cloud.githubusercontent.com/assets/3005433/12073667/e961c00a-b165-11e5-83ec-749229a61f13.png)
![image](https://cloud.githubusercontent.com/assets/3005433/12073668/f3ba1e8a-b165-11e5-93b0-f70874b725de.png)

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by vinayakkulkarni** [comment]
Closing this till OP replies.

Kindly visit [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord](https://discordapp.com/invite/8rr9bsg) for any Usage related questions.
