### ISSUE TITLE
Form Validation - "Depends" Setting

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3529]
This would be a new flag in a validation object which provides the ID of a field which a validation rule depends on. 

This would be different than `optional` which only validates when a value is filled out, instead, `depends` will only validate when a *different field value* is filled out.

**Comment by mathshane** [comment]
Excited to see that this is planned.

I suppose that in the meantime, I'll have to manually check if the fields have a value.

**Comment by jlukic** [comment]
Ive added this with the syntax `depends: 'fieldID'`, I've also added an example to validation docs.

This will also work with checkboxes, so that it depends on the value being set to `checked`

**Comment by akotulu** [comment]
How can I add dependency for fieldID value, eg dropdown value?
I have a usecase with dropdown where user can select a value, depending on chosen value, new fields are added to the form which are mandatory and some optional.
