### ISSUE TITLE
Local gulp not found

### ISSUE THREAD

**Issue by denvasden** [Semantic-Org/Semantic-UI#3530]
Hi!

I'm trying to install semantic-ui and perform "gulp build" command in "semantic" directory but it doesn't work.

Steps to reproduce:
1. npm install -g gulp
2. npm install semantic-ui --save (Use defaults locations and all components)
3. cd semantic/
4. gulp build
5. Output: Local gulp not found. Try running: npm install gulp.

Environment:
Windows 8.1
node 4.2.4
npm 2.14.12
gulp 3.9.0

Spent a lot of time looking for the answer but nothing useful was found.
Need help, please!

**Comment by ronaldo-systemar** [comment]
Have you tried in step 1 **npm install gulp** instead **npm install** *-g* **gulp**?

**Comment by denvasden** [comment]
Thanks I'll try it.

**Comment by mwwit** [comment]
I have the same issue - in windows 10. 

NPM and gulp install in roaming folder - maybe this will be important.
