### ISSUE TITLE
[Popup] - Showing popup on disabled element - enhancement?

### ISSUE THREAD

**Issue by emage** [Semantic-Org/Semantic-UI#3536]
On elements that are disabled -- the popup information are not showing.    I was using in forms and elements that tells user why a form element or button is disabled

**Comment by destan** [comment]
:+1: 

I came here to open exactly the same issue.

**Comment by emage** [comment]
@destan  I did it the Bootstrap way and it works for the scenario I was doing.  Hope this helps you:

To add a popover to a disabled or .disabled element, put the element inside of a <div> and apply the popover to that <div> instead.

http://getbootstrap.com/javascript/#popovers

**Comment by DimitryKislichenko** [comment]
@emage that will not work if there are few buttons that should go side by side.

**Comment by Ribesg** [comment]
Same issue here!
