### ISSUE TITLE
Allow conditional buttons to stack vertically on mobile resolutions

### ISSUE THREAD

**Issue by clairity** [Semantic-Org/Semantic-UI#3538]
Currently, if you have wide conditional buttons, it will force mobile browsers to scroll horizontally (https://jsfiddle.net/o4o8usw7/8/):

``` html
<div class="ui buttons">
  <button class="ui large button">A really long button label</button>
  <div class="or"></div>
  <button class="ui large button">Another long button label</button>
</div>
```

It would be really nice if conditional buttons would automatically stack with the conditional vertically & horizontally centered when on narrow screens, as simulated here (https://jsfiddle.net/o4o8usw7/7/):

``` html
<style>
  div.or {
    position: absolute !important;
    top: 2em;
    left: 8em;
  }

  button ~ button { margin-top: 0.65em !important; }
</style>

<div class="ui vertical buttons">
  <button class="ui large button">A really long button label</button>
  <div class="or"></div>
  <button class="ui large button">Another long button label</button>
</div>
```

**Comment by clairity** [comment]
afaik this is still an issue.

**Comment by havardthom** [comment]
Is there any progress or plans on supporting vertical conditional buttons?
