### ISSUE TITLE
[Dropdown] Error on calling "determine intent" method for dropdowns

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3540]
Hello,

Seems like `determine intent` is not working (at least for dropdowns). Here's a [fiddle](http://jsfiddle.net/andreyvk/939o70pq/). Firefox would throw the following error in cosole:

```
Dropdown: The method you called is not defined. ["determine", "intent"]
```

SUI docs say that this function provides a way to see if change was triggered inside dropdown or outside of it, is that correct?

**Comment by lubber-de** [comment]
The function `determine intent` was renamed to `determine eventInModule` (by f56d41575ab01b20869c0cba0fb3890fa5260d39 and finally by f2d7d0c2446485d540b07b1d70154419bd1d34b6) in 2014, but never updated in the docs.
We corrected that for the upcoming Version of Fomantic-UI by https://github.com/fomantic/Fomantic-UI-Docs/pull/124
See your adjusted fiddle here http://jsfiddle.net/9esu0pga/
