### ISSUE TITLE
[Breadcrumb] Add Inverted Variation

### ISSUE THREAD

**Issue by borglin** [Semantic-Org/Semantic-UI#3543]
I would really like to see an inverted version of breadcrumbs. Is this something you are planning to add?

At the moment the dividers are not visible since they are a transparent black.

**Comment by maturano** [comment]
Can you provide an example?

**Comment by borglin** [comment]
Here is an example with breadcrumbs inside an inverted menu: http://plnkr.co/edit/3HPWjOMRpQGwxZtgeeMr?p=preview

**Comment by lubber-de** [comment]
Prepared for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/720
See https://jsfiddle.net/1s9xgcvh/
