### ISSUE TITLE
visibility type: fixed, how to destroy?

### ISSUE THREAD

**Issue by veke** [Semantic-Org/Semantic-UI#3548]
I guess if you call $(elem).visibility({ type: 'fixed' }) you can also destroy it to its normal state.
https://jsfiddle.net/Lfu15p9o/

What I'm expecting is that clicking the button, fixed styles and placeholder are removed.

**Comment by krishaamer** [comment]
Also need this. Any update?

**Comment by jlukic** [comment]
I'll fit this in for `2.2`

**Comment by jlukic** [comment]
There goes the last issue for 2.2!
