### ISSUE TITLE
Clear description of dependencies or automatic management of dependent packages

### ISSUE THREAD

**Issue by tiborsaas** [Semantic-Org/Semantic-UI#3549]
I'm now playing with building my own versions of Semanic and it's not a really pleasant experience. I just want a few modules, but it seems one is depending on each other. 

For example I want the modal component. It seemed it needs the transition component, but it's nowhere stated. I get the error now:
`Transition: Element is no longer attached to DOM. Unable to animate. fade in`
ok, what to do with this? I have no idea.

My suggestion is that while building, modules that have dependencies, should be automatically pulled into the project, saving headaches.

**Comment by ronaldo-systemar** [comment]
It's not the first time someone complain about this. I saw in gitter a guy with this problem, but he is using React, this is your case?

Well, I agree, dependencies who has dependencies MUST be auto-included, but I dunno if gulp is capable to do this, I don't have much experience with gulp.

**Comment by tiborsaas** [comment]
I'm not using React, just vanilla JS. It should be possible to define some dependency variable in a module, but I haven't looked into how Semantic manages the build process.

I also just learned that in `semantic.json` order of definitions does matter. My inputs were messed up, because form preceded inputs in the components array. 

Finally I got everything working, skimming `semantic.min.css` to 196k and `semantic.min.js` to 69k

**Comment by fsworld009** [comment]
Hello
I'm having the same issue with popup, could you explain how did you solve the issue?
I'm using a build from "gulp build" command but I didn't change anything in semantic.json, and I do see "transition" component is listed.

Thanks in advance

**Comment by minfawang** [comment]
I'm using React and encountered this error message when using semantic-ui-popup

**Comment by jlukic** [comment]
Transition determines final display state by dry-running animation conditions. This error message means that the dry run had no `animation-name` defined at run-time.

**Comment by hitchcott** [comment]
I'm using react and ran into this issue. I had simply forgotten to import the `transition.css` module.

**Comment by fsworld009** [comment]
Forgot to come back to this thread.
Turns out not every theme has 'transition' module.
For example, I'm using 'material' but there is no transition in material theme, so I have to use 'default' for transition.

**Comment by jlukic** [comment]
The previous error message mentioned `transition not found matching specified name`, the error message was modified because in most cases, the transition isnt found because it is applied to an element already removed from the DOM. Perhaps the error message should mention both cases.
