### ISSUE TITLE
List Vertical Alignment Bug

### ISSUE THREAD

**Issue by cspeer** [Semantic-Org/Semantic-UI#3550]
Hi,

I just discovered that if you try to `middle align` the content of a non-horizontal list you end up with top alignment instead.
http://jsfiddle.net/a78xtrvb/1/

This is due to the image being set to `vertical-align: top` instead of `middle` I suppose.

Thanks a lot @jlukic 

Cheers,
Chris

**Comment by jlukic** [comment]
Unfortunately you'll need middle aligned on both elements to override their default position

http://jsfiddle.net/939pj4m1/

**Comment by Panman8201** [comment]
Digging up an old issue here, but I'm also trying to `middle aligned` a vertical list and just cannot get it to work. And actually, the floated list example in the docs (which is what I'm trying to achieve) is not working either...

http://semantic-ui.com/elements/list.html#floated

**Comment by avalanche1** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/10534563/20264603/799e4826-aa7d-11e6-8aa5-1ed1a1439a9b.png)

**Comment by Panman8201** [comment]
@avalanche1 Doesn't appear to be. Notice how the photo and name is _top_ aligned. Should be equally between the dividers.

**Comment by avalanche1** [comment]
The text is vertically centered in regards to picture.
That's exactly what the previous variation depicts:
![image](https://cloud.githubusercontent.com/assets/10534563/20280299/08de4470-aabd-11e6-8289-ff42220d77e9.png)
