### ISSUE TITLE
IE10 crash with pointing label

### ISSUE THREAD

**Issue by woodlandhunter** [Semantic-Org/Semantic-UI#3552]
It seems there's an IE10 crash/bug caused by some css. Using IE10 (the IE10 VM from Microsoft works) load this fiddle: https://jsfiddle.net/hpk1axns/

It was happening in my own application and I narrowed it down to this CSS rule in semantic.css:

```
.ui.pointing.label:before {
  position: absolute;
  content: '';
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
  background-image: none;
  z-index: 2;
  width: 0.6666em;
  height: 0.6666em;
  -webkit-transition: background 0.1s ease;
  transition: background 0.1s ease;
}
```

Removing the `content: '';` part made the crash go away (at the cost of losing the arrow portion of the label/button).

I'm hoping someone could find a workaround that preserves the arrow in IE10.

**Comment by jokeronaldo** [comment]
It's probably an OS problem, works fine here (IE 10). Try another computer.

**Comment by woodlandhunter** [comment]
@jokeronaldo 

I had already reproduced it on two computers. It was first reported by a user on Windows 8/IE 10, and I'd reproduced it on the Win7/IE10 VM microsoft provides.

Can you tell me the exact version of IE10 and your OS you tested with?

**Comment by jtimlin-immt** [comment]
We see the same issue here on our work PCs (not VMs), using the same IE and Windows versions listed by woodlandhunter above.

**Comment by jokeronaldo** [comment]
@woodlandhunter Can you provide a more detailed error information?
I tried in same win 10 version and it works here. May can you provide a error screen shot or an error log?

**Comment by woodlandhunter** [comment]
Unfortunately it's not much to work with:

![crash1a](https://cloud.githubusercontent.com/assets/6824706/13231967/904a8fd0-d972-11e5-9a90-6c78079c09a2.png)

After hitting *Close program* the tab attempts to reload one more time. After that fails, a generic error message is displayed in the browser: 
```
We were unable to return you to jsfiddle.net.
Internet Explorer has stopped trying to restore this website. It appears that the website continues to have a problem. 
```

From event log:
```
Faulting application name: iexplore.exe, version: 10.0.9200.17519, time stamp: 0x55fae7fd
Faulting module name: MSHTML.dll, version: 10.0.9200.17519, time stamp: 0x55fb0d27
Exception code: 0xc0000005
Fault offset: 0x00bcbfc5
Faulting process id: 0x9a8
Faulting application start time: 0x01d16dae9b600be4
Faulting application path: C:\Program Files\Internet Explorer\iexplore.exe
Faulting module path: C:\Windows\system32\MSHTML.dll
Report Id: dbf52436-d9a1-11e5-b382-080027d95be2
```

I know above probably isn't very helpful. I can provide other details if you let me know what could help.

**Comment by jokeronaldo** [comment]
I'm using **IE Tester** and it works. I will try on native IE 10.

**Comment by Banandrew** [comment]
Since IE10 has been unsupported for almost a year, I don’t think there will ever be a resolution to the issue. We can keep it opened, of course, but please let me know if you think it can be closed.
