### ISSUE TITLE
class="ui corner labeled input" is not well-displayed in Chrome Canary

### ISSUE THREAD

**Issue by irvanmohamad** [Semantic-Org/Semantic-UI#3553]
Here is the screenshot

<img width="238" alt="screen shot 2016-01-09 at 8 47 43 am" src="https://cloud.githubusercontent.com/assets/226691/12213606/e009f0f2-b6ad-11e5-966c-d6894b0e791b.png">

**Comment by Banandrew** [comment]
Hi @ngadimin, can you please check if it’s still an issue?
