### ISSUE TITLE
Radio Button Inline Validation creates an error for each Radio Button

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-Org/Semantic-UI#3556]
As the title says, example JSFiddle: http://jsfiddle.net/ebcn8xvq/2/

Referencing  this issue as well:  https://github.com/Semantic-Org/Semantic-UI/issues/2501

**Comment by clairity** [comment]
just ran into this as well. any plans to make a set of radio buttons only show one error message?

**Comment by douglasg14b** [comment]
rip
