### ISSUE TITLE
[Form Validation] Form Validation fails on input fields that no longer exist.

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-Org/Semantic-UI#3557]
When a field is removed the form still tries to validate it.

If I add in validation for a field that does not exist it does not try to validate it, which is what I would expect. However, if a field is removed after, the validation for it still fails.

Would there be any workaround for this if it is a bug?

https://jsfiddle.net/tL5xx6m9/4/

Edit: 

If the validation fields are set again (even with the exact same values) it seems to reset it to no longer check for the non-existing field. However, even though the validation returns `Form has no validation errors, submitting` it no longer submits the form. 

That can be seen here: https://jsfiddle.net/tL5xx6m9/5/

If I try an submit it manually with `('#myform').form('submit')` it also fails to submit.

**Comment by Banandrew** [comment]
Hi @douglasg14b, refreshing the selector with `$('.ui.form').form('refresh')` should solve the problem, so I'm interpreting it as a usage question.
