### ISSUE TITLE
Form validation passes for values that contain leading/trailing spaces

### ISSUE THREAD

**Issue by sconstantinides** [Semantic-Org/Semantic-UI#3558]
For example "   1   " passes as an integer.

Even if that is desired, the following shouldn't pass values with leading/trailing spaces since the regex matches to the start and end: regExp[/^[a-z0-9_-]{4,16}$/]

**Comment by sconstantinides** [comment]
A somewhat related issue: "01" passes as an integer.

**Comment by jlukic** [comment]
I think this is fine. 

I would consider leadings 0s not invalid, and I would expect the value to be read with `trim`
