### ISSUE TITLE
[Dropdown] Values displayed instead of content when using apiSettings

### ISSUE THREAD

**Issue by nquintal** [Semantic-Org/Semantic-UI#3560]
If you initialize a Dropdown with apiSettings, the options diplays the values of the element and not the content.

Here's a jsfiddle:
https://jsfiddle.net/qdyggmw5/

**Comment by kapouer** [comment]
There is something racey in that bug - testing on localhost sometimes doesn't reproduce, and sometimes does.

**Comment by kapouer** [comment]
It also seems it checks the values are compatible with remote values.
Maybe the problem and the race comes from that.

**Comment by kapouer** [comment]
Ok, here's what is supposed to happen, according to code:
- user clicks on dropdown, search something, selects it
- name/value pair is stored in SessionStorage
- when the page is opened again, the old name is restored from SessionStorage

So if the page pre-populates the select with options, they will show only the value.
Gonna PR that.

**Comment by kapouer** [comment]
Of course, `saveRemoteData: false` dropdown option could have "fixed" the issue by not trying to restore data, but then it just calls `clearValue()` which prevents us from populate the select before initialization.

**Comment by kapouer** [comment]
Also
```
<select name="test" multiple class="ui search dropdown">
<option value="" disabled>My Placeholder</option>
<option value="myvalue" selected>mytext</option>
```
logs
```
Saving default text as My Placeholder
Saving placeholder text as My Placeholder
Saving default value as ["myvalue"]
```
which is part of the problem. The default text does not match the default value.
Thus when restoring from session storage, a bare value is found with text.

**Comment by kapouer** [comment]
Example of a workaround without changing source (because i did not find a clever patch):
```
$('select[name="advisor"] > option[selected]').each(function(i, option) {
		$option = $(option);
		advisorOptions.push({value: $option.val(), text: $option.text()});
	});
	var advisorDropdown = $('.ui.dropdown.advisors:visible').dropdown({
		apiSettings: {
			url: '/api/publishers?text={query}',
			onResponse: function(advisors) {
				var results = [], ad;
				// semantic does not give me an array here
				for (var k in advisors) {
					ad = advisors[k];
					if (typeof ad == "object") {
						results.push({
							value: ad.id,
							name: ad.name + ' ' + ad.surname
						});
					}
				}
				return {
					success: true,
					results: results
				};
			}
		}
	});
	advisorDropdown.dropdown('clear');
	$.each(advisorOptions, function(i, option) {
		advisorDropdown.dropdown('add label', option.value, option.text);
	});
```

**Comment by noobiwan** [comment]
Hey guys, thanks for the good work. Any update on this issue? I see it as major bug.

**Comment by noobiwan** [comment]
For those looking for a solution, here is how I managed to restore the selected values:

- Store the value/name pairs in a variable (I'm generating this code from the backend)
- Generate the HTML of the select dropdown with the options to be selected (also from the backend)
- Loop through the value/name pairs calling `.dropdown('set selected', value)`
- I also set `saveRemoteData` to `false`

I tried using `'add label'` but it wouldn't actually select the values and the validation would fail.

**Comment by gouravmore** [comment]
I have done following changes and it works fine

**saveRemoteData:false**
And 
**cache:false**

```
.dropdown({
	apiSettings: {
	  url: 'url',
	  cache:false
	},
	saveRemoteData:false,
	fields: {
	  remoteValues : 'results',
	  values       : 'values',
	  name         : 'name',
	  text         : 'text',
	  value        : 'value'
	},
	forceSelection:false
})
```
