### ISSUE TITLE
[Search] - Category is not working

### ISSUE THREAD

**Issue by Giioaj** [Semantic-Org/Semantic-UI#3563]
**Steps to Reproduce**
Try to use a simple category search with local source.

**Expected**
Show the category results

**Result**
The Search does not do this

**Testcase**
http://jsfiddle.net/giioaj/gwxz08op/4/

**Comment by jlukic** [comment]
Unfortunately as mentioned in the docs, local search does not support category view
http://semantic-ui.com/modules/search.html#server-responses

**Comment by Giioaj** [comment]
Mmm I do not know where it says , but I see nothing wrong to do so locally.

Thanks.

**Comment by rubenanapu** [comment]
I could make this work by focusing on a "hidden" checkbox when `esc` is pressed, and then focusing again on the `#search`.
Something like:

```
<input type="checkbox" style="width: 0px" id="reset_search" >

<script>
        $(window).on('keyup', function(evt){
            if(evt.which == 27){
                $("#search").val('');
                $("#reset_search").focus();
                setTimeout(function(){
                    $("#search").focus();
                }, 50);
            }
        });
</script>
```
