### ISSUE TITLE
[Checkbox] Non-JS Checkbox Focus Styles Override Toggle Color

### ISSUE THREAD

**Issue by sanjeev2838** [Semantic-Org/Semantic-UI#3565]
http://jsfiddle.net/sanjeev2838/4ys59wsh/2/

**Comment by jlukic** [comment]
This does not appear to affect checkbox with JS
http://jsfiddle.net/L840zqmb/

**Comment by jlukic** [comment]
This is already fixed in `2.2` 
http://jsfiddle.net/unqaa354/
