### ISSUE TITLE
transition onComplete firing multiple times

### ISSUE THREAD

**Issue by t2** [Semantic-Org/Semantic-UI#3566]
I have a hidden div that, once a link is clicked, is made visible while the visible div is hidden. Common enough case. I am using the `transition()` API for this. The problem is, the `onComplete` function seems to be getting called multiple times.

```coffeescript
$('.change-number-link').on 'click', ->
    $('.confirmation-code-field').transition(
        onComplete: ->
            console.log 'Complete'
            $('.phone-number-field').transition()
    )
```

```haml
.field.phone-number-field{ style: @user.unconfirmed? ? 'display: none;' : '' }
    = f.input :phone, label: 'Phone Number', input_html: { class: 'phone' }
.field.confirmation-code-field{ style: @user.confirmed? ? 'display: none;' : '' }
    = label_tag 'user[confirmation]', "Confirmation Code"
    .ui.error.input
        = text_field_tag 'user[confirmation]', '', maxlength: 5, class: 'numeric'
        .hint
            = link_to 'Change Number', '#', class: 'change-number-link'
            |
            = link_to 'Send New Code', '#'
```

`Complete` is logged multiple times in the console. Anything jump out at you?

**Comment by ronaldo-systemar** [comment]
May onComplete is called by all hidden elements? Try to debug what element is calling the event, by id or any other property.

**Comment by t2** [comment]
@ronaldo-systemar You were spot on. Embarrassingly I had a duplicate field with the same class.

**Comment by ronaldo-systemar** [comment]
@t2 Mistakes happens. Have a nice coding =)
