### ISSUE TITLE
[Form Validation] onSuccess and onFailure are not called when a form is validated.

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-Org/Semantic-UI#3567]
As the title says.

The onSuccess or onFailure callbacks are not being called when they are assigned and "validate form" is called. It only seems to be called if I delete the form validation chunk.

JSFiddle: https://jsfiddle.net/1qvrys1f/

**Comment by jlukic** [comment]
You're re-initializing the form with new settings by calling `.form` twice. Check the syntax on the form validation page.

**Comment by jlukic** [comment]
https://jsfiddle.net/jlukic/00uw838s/

**Comment by SylarRuby** [comment]
@jlukic While it works, the form submits twice and in the console I see `Cannot read property 'preventDefault' of undefined`
