### ISSUE TITLE
[Grid] Sortable columns feauture

### ISSUE THREAD

**Issue by leventesen** [Semantic-Org/Semantic-UI#3569]
Can grid columns be sortable with `order: <number>` css attribute? 

Usage example (demonstration only):
```html
<div class="ui equal width sortable grid">
    <div class="order two on mobile column"></div>
    <div class="order one on mobile column"></div>
    <div class="column"></div>
</div>
```

**Comment by jlukic** [comment]
There's `reversing` which is a somewhat more common pattern.
http://semantic-ui.com/introduction/new.html#reversable-grid-columns

I dont think I'll support arbitrary order per device.

**Comment by leventesen** [comment]
Do you mean the `reversing` option is enough for sorting items?
