### ISSUE TITLE
Update LATO-font

### ISSUE THREAD

**Issue by Alex-Sokolov** [Semantic-Org/Semantic-UI#3572]
Update version of used LATO font for better support cyrillc symbols.

Now strings with cyrillic symbols fallback to Arial:
![default](https://cloud.githubusercontent.com/assets/4497128/12317166/8a662fe4-ba9f-11e5-90bb-a93aa2af588e.PNG)

From website http://www.latofonts.com/lato-free-fonts/#download
> The Lato 2.010 fam­ily now sup­ports 100+ Latin-​​based lan­guages, 50+ Cyrillic-​​based lan­guages as well as Greek and IPA pho­net­ics.

**Comment by jlukic** [comment]
The version of Lato we are using is served from Google Fonts, so we are stuck with the current version that Google hosts.
