### ISSUE TITLE
Dropdown not working on Android browser

### ISSUE THREAD

**Issue by davyvanlaere** [Semantic-Org/Semantic-UI#3575]
On this page:

http://semantic-ui.com/modules/dropdown.html

None of the dropdowns are working on :
- android browser (marshmallow) (it does work in chrome though)
- windows phone 8.1 version of IE

When you click them, nothing happens.

**Comment by deneuxa** [comment]
Same problem here : dropdown dont open when they dont have default value
(samsung s6 edge + chrome )

**Comment by deneuxa** [comment]
User confirming dropdown don't open at all with samsung s6 edge (including when they have a default value)

**Comment by deneuxa** [comment]
@quirkyjack @jlukic 
=> problem confirmed on all recent SAMSUNG / Android devices when using the default browser

**Comment by jlukic** [comment]
I don't have an Android device (or know of any I can borrow), and it's not reproducible in Chrome Emulator so I'm at a bit of a loss on how I can help.

**Comment by deneuxa** [comment]
we succeed to test on a Samsung S6,
this monkey-patch here does actually work : 
https://github.com/Semantic-Org/Semantic-UI/issues/2718

**Comment by jlukic** [comment]
I'll look at the fix in #2718, since that issue predates this one, moving conversation there.
