### ISSUE TITLE
[Dropdown] - Turkish İ & ı characters on search

### ISSUE THREAD

**Issue by ysayita** [Semantic-Org/Semantic-UI#3577]
**Steps to Reproduce**
1. Create a select control with options that contains İ and/or ı character.
2. Make a search dropdown with that select.
3. Do a search using i or I character

**Expected**
Dropdown should filter the elements and show results with "İ" when searched with "i" and show results with "I" when searched with "ı".

**Result**
Dropdown does not show items according to the Turkish language characters.

**Notes**
You may find an example select control attached within a html file. Try searching for alimar. There is an option "ALİMAR" and according to Turkish language rules, "ALİMAR" and "alimar" are the same words.
[index.zip](https://github.com/Semantic-Org/Semantic-UI/files/92033/index.zip)

**Comment by jlukic** [comment]
The character map required to support all diacritics is about 16kb, so i've been hesitant to add.
https://github.com/select2/select2/blob/master/src/js/select2/diacritics.js

I do think though it makes sense to include, at the very least, as an optional include as it does result in huge UX issues with foreign languages.

**Comment by brunotourinho** [comment]
Any progress on this issue?

**Comment by kmehmety** [comment]
@ysayita did you find any solution for this issue?

**Comment by lubber-de** [comment]
Added option `ignoreDiacritics` to dropdown and search module for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/422 :grin: 
See http://jsfiddle.net/t23uewyn/
