### ISSUE TITLE
Transition in fail to animate

### ISSUE THREAD

**Issue by Bitzz** [Semantic-Org/Semantic-UI#3579]
Test case: [Demo](http://bitz.nomsy.net/server-status.html) (The top right button with the bell has debugging enabled)

The issue is that all animation ins fails to play (simply appears), but the animation plays properly on losing focus.

**Comment by jlukic** [comment]
Can you be more explicit on how to trigger this issue on your site

**Comment by Bitzz** [comment]
Hi,
Yes. Simply click the button on the menu that has the light bulb icon.
Look at the console and you'll see the event for the transition out occurs, but not the transition in.

**Comment by Bitzz** [comment]
@jlukic, Updated first post to reflect what seems to be the real issue.
De-minified html so you can read it better.

**Comment by jlukic** [comment]
I'm not seeing the light bulb icon, 

It would be better if you could create a discrete test case using JSfiddle, there's a link to fork in the readme.

**Comment by Bitzz** [comment]
Sorry, I meant bell icon. I will try to replicate it, but it may not be possible as it seems to be specific to the code I have running right now, as in I can't replicate the issue as I don't know the cause.

**Comment by jlukic** [comment]
As a maintainer it would be difficult for me to find the bug cause in individual user code bases, but I'm happy to help debug and fix stripped down test cases.

**Comment by Bitzz** [comment]
Found the issue! God, I broke apart my website to find the issue and it was in literally the last thing left to redo.
Turns out [YUI compressor](http://yui.github.io/yuicompressor/), for some reason screwed up the minified css. Not sure how, but it did.
