### ISSUE TITLE
Extra space after action button in Models

### ISSUE THREAD

**Issue by ideadx** [Semantic-Org/Semantic-UI#3580]
<img width="1434" alt="screen shot 2016-01-17 at 3 07 38 pm" src="https://cloud.githubusercontent.com/assets/2369963/12375988/10239ace-bd2d-11e5-811c-81698f3511a8.png">

**Comment by ideadx** [comment]
here is a code snippet:
https://gist.github.com/ideadx/7bc52bd7ead1744e7e63

**Comment by ideadx** [comment]
@jlukic  Any idea on this?

**Comment by ideadx** [comment]
@jlukic

**Comment by xDaizu** [comment]
Thanks for the snippet but could you provide it as a working JsFiddle, please?

**Comment by avalanche1** [comment]
Closing because no test case.
