### ISSUE TITLE
Expand accordion triggers to be triggered from each accordion individually, and allow for triggers outside of the title.

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-Org/Semantic-UI#3583]
Accordion triggers seem to be tied to the title. This really limits easy functionality in areas where clicks on non title elements are expected to open hidden accordions. Being able to just open an accordion by finding the element would be amazing.

**Comment by IonutBajescu** [comment]
You can have triggers outside of the title by using the "open" behaviour. 

http://semantic-ui.com/modules/accordion.html#/usage
