### ISSUE TITLE
Horizontal Divider line height too narrow

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#3585]
Hello,

it seems as if horizontal divider's line height is too narrow.
This leads to the effect, that letters which stretch under the baseline are cut off.
Please have a look at:
http://jsfiddle.net/Windwalker/vv3r06bo/

In my opinion, it is sufficient to set

```
.ui.horizontal.divider {
    line-height: 1.2;
}
```
(instead of `line-height: 1.0`)

Kind regards,
Sascha.

**Comment by srissel** [comment]
Dear Semantic UI team,
is there any news on this?

Kind regards,
Sascha.

**Comment by jlukic** [comment]
Horizontal dividers should not have `overflow: hidden` set

**Comment by jlukic** [comment]
Fixed in `2.1.9`
