### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by svansoeren** [Semantic-Org/Semantic-UI#3588]
Would like semantic UI to create a responsive navbar similar to bootstrap. 

It is currently impossible to have the semantic UI dropdowns function correctly when collapsed in a mobile view.

Tried to use the "accordion" functionality when on mobile, but that solution does not convert well for desktop.

https://getbootstrap.com/examples/navbar-static-top/

**Comment by Thantifaxath** [comment]
__svansoeren__, Semantic UI has an outstanding "all-in-a-box" Sidebar menu (http://semantic-ui.com/modules/sidebar.html#/definition), which works great on tablets and mobiles. All you have to do is to hide navbar menu items on small screens and show a button that will trigger the sidebar menu.

However, bad thing is that you have to duplicate menu items for navbar and sidebar.

**Comment by svansoeren** [comment]
Thank you for the alternative page functionality and layout suggestion.

As well as the HTML / CSS re-structure suggestion. 

However, not really interested in duplicating the HTML and design elements (makes the content more difficult to maintain).

Still interested in seeing a responsive navbar developed. (if this does get completed it would not be difficult translate the responsiveness to the "sidebar").

**Comment by jokeronaldo** [comment]
Well, menu element duplication is wrong IMHO. May @jlukic consider this improvement.

**Comment by abijr** [comment]
Check issue #157

**Comment by dijonkitchen** [comment]
Agreed. Let's close this and keep it on #157.

**Comment by Banandrew** [comment]
See #157.

**Comment by dnhyde** [comment]
Hi,
Since [#157](https://github.com/Semantic-Org/Semantic-UI/issues/157) comments are blocked I post here, shall others have similar issues.
For me using https://react.semantic-ui.com/collections/menu#menu-example-stackable was enough on mobile.

**Comment by natzar** [comment]
I made this "plugin" - Semantic UI Hamburger Menu https://github.com/natzar/SemanticUiHamburgerMenu
