### ISSUE TITLE
[Table] selectable cell classes not in npm package (2.1.8)

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#3589]
There are no definitions for `td.selectable` both inside src and dist files. I tested version `2.1.8` - the styles should be there since `2.1.5`.

The github package looks fine. :smile:

**Comment by Banandrew** [comment]
Hi @larsbo, it seems that it’s been fixed at some point, can you please confirm?

**Comment by larsbo** [comment]
@Banandrew yes, looks fine now! 👍
