### ISSUE TITLE
Selection dropdown returns wrong value

### ISSUE THREAD

**Issue by ouabing** [Semantic-Org/Semantic-UI#359]
http://jsfiddle.net/vFPq2/4/

When some item's data value is setted to 0, the selection dropdown just returns the text in lower case.

**Comment by danielrobleM** [comment]
i'm using  Selection dropdown and returns  all the text in lower case.
 any help please ?

**Comment by jlukic** [comment]
Unless you specify a value, from the <select> or as data-value or will use the lowercase text as the value

**Comment by danielrobleM** [comment]
Thanks @jlukic , it's working perfectly.

**Comment by minafarid** [comment]
can somebody add this to the documentation

**Comment by mnquintana** [comment]
@minafarid Just opened https://github.com/Semantic-Org/Semantic-UI-Docs/issues/145 to document this.
