### ISSUE TITLE
[Segment] Attached alignment

### ISSUE THREAD

**Issue by daftspunk** [Semantic-Org/Semantic-UI#3592]
Hi, first time caller, long time listener. Probably more of a question than anything else. Refer to subtle differences the examples below:

http://jsfiddle.net/umfb3nc1/1/

Notice how the attached segment sits `1px` off either side of a regular segment. Contrary to what is accurate math, it looks like the negative margin has no impact on the calculated width.

I am trying to figure out: why not use no margin and 100% width to begin with? (As per the `.bugfix` class in the example). To rephrase, why is it necessary to have `margin: 0 -1px; width: calc(100% + 2px)` when these [are supposed to] cancel each other out?

Peace and love

**Comment by daftspunk** [comment]
I've gone ahead and removed these styles in my distributed code. Fingers crossed! :v:

**Comment by nathanhannig** [comment]
Having same issue, wish there was an answer :(
