### ISSUE TITLE
How to handle modals in Meteor / Blaze (modal is shown multiple times)

### ISSUE THREAD

**Issue by quape** [Semantic-Org/Semantic-UI#3602]
In Meteor, I'm showing a modal in a template on clicking a button. When Meteor renders the template again and I click the button, the modal is shown twice. This is because the modal html code from the first modal which Semantic created is still present in the DOM structure. So because the class names are the same, both modals are shown now.

So what's the problem here, did I do something wrong? Is it my job to remove existing modals from the DOM before? Should Semantic UI do it?

Any help appreciated.

**Comment by quape** [comment]
I now do it this way: Before rendering the page I remove every single modal from `body .modals` that have been created by Semantic UI when each modal was shown the first time. That works but is not nice.

I definitely consider this as a bug in Semantic UI. When moving the DOM structure of one modal into `body .modals` Semantic UI should check if this modal is not already there. Because otherwise, when the modal is shown it could pop up multiple times.

**Comment by ronaldo-systemar** [comment]
Are you openning modals with the same css selector? May you should define an id for every modal.

**Comment by quape** [comment]
You're right, it works when I access the modal by #id instead of classname! :-) Thanks!
