### ISSUE TITLE
[Form validation] - Form validation doesn't work correctly with the "on" setting set to "blur" 

### ISSUE THREAD

**Issue by hbaccara** [Semantic-Org/Semantic-UI#3606]
Steps to Reproduce
1. put the focus on one required field
2. then move the focus to another required field
3. the firstly focused field indicates an error at this step as it is required
4. now move back to the firstly focused field (the one already higlighting an error)
5. the secondly focused field indicates an error at this step as it is required
6. now move back to the secondly focused field

Expected
Nothing special should happen after step 6

Result
All the required form inputs indicate an error even those that were not focused at all.

Testcase
http://jsfiddle.net/hbaccara/w6h42611/1/

**Comment by beholdr** [comment]
Yep, very annoying behavior. On blur validation is most convenient for users, but with this bug I'm forced to use 'on submit' validation.

**Comment by jlukic** [comment]
Something seems pretty broken here.. not sure how this is happening.

**Comment by jlukic** [comment]
`next` release will only validate the current form field.
