### ISSUE TITLE
Form submit event doesn't fire in Meteor event handler if nested in a modal

### ISSUE THREAD

**Issue by opvasger** [Semantic-Org/Semantic-UI#3608]
Events in the template can't be fired, if the form is in a modal, and the modal is inside the template.

A quick fix is to wrap the outside of the template in the modal element, and have the template exist inside the modal.

sample code:

**template**:

```
<template name='loginModal'>
    <div class='ui basic modal' id='login-modal'>
        <form class='ui form' id='login-form'>
            <input type='text' name='username'>
            <input type='password' name='password'>
            <input type='submit' value='login'>
        </form>
    </div>
</template>
```

**event handler**:

```
Template.loginModal.events({
    'submit #login-form'(e, t){ //NEVER FIRED
        e.preventDefault()  
        //do stuff...
    }
})
```

**Comment by pikaupet** [comment]
I just encountered that yesterday. I ended up creating template for the inner content of the modal


    <template name='loginModal'>
        <form class='ui form' id='login-form'>
            <input type='text' name='username'>
            <input type='password' name='password'>
            <input type='submit' value='login'>
        </form>
    </template>

with events etc 

    Template.loginModal.events({
        'submit #login-form'(e, t){ //will get fired
            e.preventDefault()  
            //do stuff...
        }
    })

And then in code defiding the modal elsewhere

    <div class='ui basic modal' id='login-modal'>
        {{>loginModal}}
    </div>

It's an annoying workaround and I'd like to know where the problem is hidden, but it's better than nothing.

**Comment by Benco1** [comment]
Thanks for this. Able to accomplish what I need with your workaround on button click event (in place of your submit), but wasn't able to get the submit event working directly. Hmm. @pikaupet @Goatic
