### ISSUE TITLE
[multiple search dropdown] 

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#3609]
Click event will be triggered repeatedly when I click the input.search.
It also occur in my project  and http://semantic-ui.com/modules/dropdown.html#/examples.
I need some help. Thanks

**Comment by benjamin21st** [comment]
It was a quite annoying bug given how awesome this feature could be. I had a hacky work around: 
`
$('.dropdown').off('click');
$('.dropdown').on('click', function () {
   console.log('show menu');
   $('.dropdown .menu').transition('slide down');
})`

Basically it unbinds all click events to "dropdown", and rebinds a single click to display/hide the dropdown menu. 

I really hope they could fix this at some point.

**Comment by vinayakkulkarni** [comment]
It opens all the dropdowns and messes up everything
<img width="897" alt="screen shot 2016-12-20 at 4 36 16 pm" src="https://cloud.githubusercontent.com/assets/19776877/21348303/7858eb3a-c6d2-11e6-9943-fea40335d66d.png">

**Comment by vinayakkulkarni** [comment]
Someone close this issue. Similar to #4546 
Solution: 

http://semantic-ui.com/modules/dropdown.html#/settings

Set `forceSelection:false` and viola! Tested it just now. works.
