### ISSUE TITLE
[Dimmer] does not close

### ISSUE THREAD

**Issue by sondreb** [Semantic-Org/Semantic-UI#3612]
I'm unable to get the dimmer to close when the user clicks it. I have tried various settings and nothing seems to work. Setting opacity works fine, so the configuration of settings works fine.

I have tried to set on: 'click' and closeable to true, 'true', auto, 'auto' and leaving it as default. Neither will close the dimmer.

I have a jsfiddle here that demonstrates the problem, it is loading version 2.1.8 of Semantic UI.

http://jsfiddle.net/sonbje/ymh0rzn3/3/

**Comment by sondreb** [comment]
This actually works in Firefox and Edge, but not Chrome.

**Comment by cwbit** [comment]
worked for me in Chrome

**Comment by sondreb** [comment]
Touch click works on Chrome, not click with mouse. I will test on a few other computers and see. This computer is running Windows 10.

**Comment by sondreb** [comment]
I have verified that it works to close on a regular laptop WITHOUT touch capability. It is NOT closeable with mouse on Surface 4 and Samsung ATIV Book 9 Plus.

**Comment by sondreb** [comment]
Inside the bind events on the dimmer, and inside the following if: if( module.is.closable() ) {

There is some code that registers $dimmable.on. The problem is that the clickEvent is "touchstart" on a Windows device that supports touch, like any number of laptops, such as Microsoft Surface.

Problem is with the $allModules registration earlier in the code, where this is done:

```
   clickEvent      = ('ontouchstart' in document.documentElement)
          ? 'touchstart'
          : 'click',
```

One solution would be to do multiple event handlers, one for ontouchstart and one for onclick. This could be done in two ways, I'm not sure what would be most proper so I have not made a pull request yet, if that is wanted?

```
$dimmable.on(clickEvent + eventNamespace, selector.dimmer, module.event.click);
$dimmable.on('click ' + eventNamespace, selector.dimmer, module.event.click);
```

or two in one:

```
$dimmable.on(clickEvent + eventNamespace + ' click' + eventNamespace, selector.dimmer, module.event.click);
```

Please let me know if a pull request is wanted :-)

**Comment by btastic** [comment]
I just had the same exact issue. I have a secondary screen that has touch capabilities. This leads to to the same problem in Chrome as described above.
