### ISSUE TITLE
enhancement: API for search in dropdown

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI#3614]
What I want to do is simulate the effect of typing in a `.dropdown.search` field (for pre-populating and filtering the options, but make it ready to continue to type). The only way currently I've found to do this is:

    $( '.search.dropdown input.search' ).val( valueVariable ).trigger( 'keydown' )

Which works, but is not optimal of course.

**Comment by acidjunk** [comment]
I would also like to know if there is a better solution. We use to populate the dropdown; when you later want to edit it; the value that was choosen is not available.

**Comment by jlukic** [comment]
```javascript
let query = 'my search';
$('.ui.dropdown').dropdown('search', query);
```
