### ISSUE TITLE
How one might TURN ON verbose debugging messages?

### ISSUE THREAD

**Issue by pavelvasev** [Semantic-Org/Semantic-UI#3617]
Hi there!

I'm new to Semantic and I see some unexpected behavior / error messages during it's operation. 

During step-by-step debugging I discovered there are a lot of "module.debug" calls that I don't see ever, because settings.debug is turned to false.

How may I turn on all the debug/verbose messages of all modules? This will help me debug a lot..

Thanks!

**Comment by jlukic** [comment]
The site module is undocumented but allows for global settings to be changed across all modules.

```javascript
$.site('enable verbose');
```

You can also do 
```javascript
$('.ui.dropdown').dropdown({
  debug: true,
  verbose: true
});
```

Wherever you init (using any module)

**Comment by pavelvasev** [comment]
Hi Jack! Thank you for your reply!
