### ISSUE TITLE
Message element missing bottom border when attached to a form element.

### ISSUE THREAD

**Issue by nerdybeast** [Semantic-Org/Semantic-UI#3619]
I'm currently using version 2.1.8 and I noticed that when a "Message" component is attached to a "Form" component, it does not receive a bottom border. When attached to other components such as tables or lists, a bottom border is applied. This can be seen here in the docs: http://semantic-ui.com/collections/message.html#attached

For consistency sake, I feel that a bottom border should be applied the message component at all times when the "attached" class is applied.

**Comment by jlukic** [comment]
This is a bug
