### ISSUE TITLE
Why version control all semantic source using gulp install?

### ISSUE THREAD

**Issue by eyalw** [Semantic-Org/Semantic-UI#3620]
Your recepies suggest just doing `npm install semantic-ui` but then all the semantic-ui source code is added my project folder
(also see https://github.com/Semantic-Org/example-github )

I do not wish to mix both sources, and there's no need for me to version control your source files, but - what I do need is to version control the site .variables and .overrides which i add.

so what I did is added everything in /semantic to .gitignore except the my config folder /site.
but then when another teammate `npm install semantic-ui` it will override the /site folder....

I don't understand whats the strategy on theming and version control, 
thanks!!

**Comment by eyalw** [comment]
I thought about using git submodules, but still when i want to update semantic ui it will override my /site folder with custom code.

what do you suggest?

**Comment by jlukic** [comment]
Semantic UI includes install scripts that correctly manage updates without overriding theme changes. 
There is no simple way for theming to work with theme files inside your project and definitions inside `node_modules`.

**Comment by morenoh149** [comment]
this should be noted in the getting started page.
