### ISSUE TITLE
Destroying elements (removing event listeners etc to prevent memory leaks in SPA)

### ISSUE THREAD

**Issue by danr1979** [Semantic-Org/Semantic-UI#3624]
Hi.

I am using SUI with Ember JS and each SUI element is being implemented as an Ember component.  However, in Ember we are creating single page applications and as a result we need to teardown jQuery-based elements once they are ready to be removed from the DOM to prevent memory leaks.

Does anyone know how this can be done in SUI?  I've found a reference to "modules" and a "destroy" function/setting but I can't get these to work.

Any help that anyone could offer would be appreciated.

Thanks.

**Comment by jlukic** [comment]
All javascript components have a destroy method

`$('.ui.dropdown').dropdown('destroy')`

We also  have dedicated ember components. 
https://github.com/Semantic-Org/Semantic-UI-Ember

**Comment by danr1979** [comment]
Thanks for your help.
