### ISSUE TITLE
why reqeust font.gstatic.com while opening a page built by semantic-ui? page loading very slow

### ISSUE THREAD

**Issue by yeweishuai** [Semantic-Org/Semantic-UI#3626]
why the browser will request font.gstatic.com while opening the page wrote with semantic-ui ?

Semantic-ui is great. I am not a front-end developer, I just used semantic-ui to build my page. But the problem is as described, which caused the page loaded very slowly.

**Comment by Bitzz** [comment]
It's pulling the font from Google's servers. It sounds like your ISP is having some issues reaching their font hosting service. You can disable the remote font important and import it locally as outlined in #1305
