### ISSUE TITLE
[Validation] - use same prompt text for rules array

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3630]
This should work:

```
$('.ui.form')
  .form({
    fields: {
            password:
                rules: [
                    {type: ['maxLength[26]','minLength[16]'],
                    prompt: 'should be 16-26 characters long'}
```

**Comment by xDaizu** [comment]
...should it? It's missing a comma before "prompt"!

If that's not te problem (most likely a copy-paste typo), what is it? Is it not enforcing one of the rules? Is it not letting you to define it?

**Comment by avalanche1** [comment]
Added comma.
Currently that syntax isnt supported.
