### ISSUE TITLE
How to get checkbox value in "onChecked" callback

### ISSUE THREAD

**Issue by wanglingsong** [Semantic-Org/Semantic-UI#3631]
I would like to retrieve the value of checked checkbox when the "onChecked" callback invoked. However it seems impossible because there is no parameters provided in the callback and the "this" refer to the root object instead of context. is there any way to locate the triggered checkbox inside the callback?

**Comment by wanglingsong** [comment]
https://jsfiddle.net/km4vqq7j/

**Comment by jlukic** [comment]
`this` inside onChecked is the radio input. 
https://jsfiddle.net/hw3kuc4r/
