### ISSUE TITLE
[Sidebar] Fixed menu breaks if sidebar is used with context

### ISSUE THREAD

**Issue by utkuturunc** [Semantic-Org/Semantic-UI#3633]
Here is a demo: http://jsfiddle.net/w92734fa/

I have a fixed menu and I am trying to use context with sidebar. The sidebar works but the fixed menu gets broken (acts like regular menu).

If I remove the context setting, the menu is moved to body and everything works fine.

**Comment by jlukic** [comment]
This is expected behavior, fixed menus are pushed alongside pusher content.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sidebar.less#L214

Use overlay if you want it to overlap
http://jsfiddle.net/kyLy3fpb/
