### ISSUE TITLE
device only classes don't seem to work

### ISSUE THREAD

**Issue by guyjacks** [Semantic-Org/Semantic-UI#3636]
I'm trying to apply the computer only classes to a right menu element containing a button.  The menu shows up on mobile.

`<div class="right computer only menu">
                <div class="item">
                    <a href="#contact" class="ui primary button">
                        Get involved
                    </a>
                </div>
            </div>`

**Comment by jlukic** [comment]
Please create a new issue to re-open with specific test case.
