### ISSUE TITLE
[Comment] Allow Fluid Width

### ISSUE THREAD

**Issue by adrazich** [Semantic-Org/Semantic-UI#3640]
.ui.comments has a max-width set to 650px Can we override that using the fluid class to have a 100% width? 

#### Current
![screen shot 2016-02-02 at 10 17 04 am](https://cloud.githubusercontent.com/assets/1614075/12753708/350ecb86-c996-11e5-8683-ebd92d723acf.png)

#### Requested
![screen shot 2016-02-02 at 10 17 30 am](https://cloud.githubusercontent.com/assets/1614075/12753713/399162fe-c996-11e5-91be-d92a00104f82.png)

**Comment by jlukic** [comment]
#3513
