### ISSUE TITLE
Build older versions with npm and gulp?

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#3641]
Is there any way how to change package.json or gulpfile if I need to build old version of Semantic-UI? 
(We have to update older website with Sematnic-UI 1.12.0,cos  flexbox is show-stopper).

NPM node_modules for semantic-ui have version 2.1.8 pakcage and version 1.12.0 package. But npm and gulp respectively force me to use only 2.1.8 version. I have tried to change package.json as well as semantic.json, manually insert older src or npm install semantic@1.12.0. 
But with no luck. 
Npm install also  notifies me about an error that there is no git available for older versions

Can anyone help us please. It drives me crazy, I have spent whole day to solve this and feel really frustrated.

Thank you in advance

**Comment by KapuzenSohn** [comment]
Is before the version a `^`? When yes than remove it, maybe this helps, because npm than really only installs the version that you give him

**Comment by kvetoslavnovak** [comment]
I have already tried to delelte 2.1.8 version from node_modules, but npm install creates it automatically during install :-(
