### ISSUE TITLE
Search icons

### ISSUE THREAD

**Issue by IonutBajescu** [Semantic-Org/Semantic-UI#3644]
Hey guys,

I love this project, but I feel like searching icons could be improved so much. Using the browser search to search icons in the http://semantic-ui.com/elements/icon.html page is not that awesome as the project is. 

Fontawesome has a "search icons" feature, but the names were drastically changed in Semantic UI and we can't use it. https://fortawesome.github.io/Font-Awesome/icons/

It's there anything related to this issue planned for Semantic UI in the foreseeable future? I can assist with the implementation if @jlukic doesn't have time for it.

**Comment by jlukic** [comment]
I would consider a PR to add search to icons page. Consider checking out the docs repo to see how  docs are generated. Closing the issue here, but feel free to open on the docs repo.
