### ISSUE TITLE
[Dropdown] Add functionality to configure positioning 

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#3645]
Dropdowns can sometimes be placed in corners, causing the items to go off the screen when the dropdown is active. Being able to specify the positioning can help to resolve this problem.

The same functionality with popups would be sufficient. 
http://semantic-ui.com/modules/popup.html#positioning

See below for an example of a dropdown being used in the top-right corner of a menu.
<img width="321" alt="screen shot 2016-02-02 at 5 08 30 pm" src="https://cloud.githubusercontent.com/assets/5153189/12766067/b09a9332-c9cf-11e5-8f1b-0a76e60643e0.png">

**Comment by xDaizu** [comment]
You can configure if you want your menu [to open right or left](http://semantic-ui.com/modules/dropdown.html#menu-direction).

 If that didn't solve your problem, could you provide a JsFiddle with a problematic case?

**Comment by fpayer** [comment]
That seems to only resolve the issue with sub-menus. Here is the JSFiddle:

http://jsfiddle.net/cs3j0zvj/1/

**Comment by xDaizu** [comment]
@fpayer If you are using a "pointing dropdown" you need to tell it where the "pointing" is, in this case "top right" :)
```html
<div class='ui pointing dropdown top right' id='user'>
       <div class='text'>User</div>
       <i class='dropdown icon'></i>
       <div class='menu'>
          <div class='item'>User Settings</div>
          <div class='item'>Team Settings</div>
          <div class='item'>Redeem Game Code</div>
       </div>
 </div>
```

http://jsfiddle.net/ypvpajrL/

**Comment by fpayer** [comment]
Ah, ok. Wish this was more clear in the docs. I notice now that the property is used when displaying other features of dropdown, but there is no explicit example of that feature in the docs.

**Comment by xDaizu** [comment]
roger that!

@jlukic, add this to the overflowing list of *Things to do Examples About*! :joy_cat:

**Comment by jlukic** [comment]
#3716

**Comment by denchen** [comment]
Sorry to bring up an old topic:

Is there a way to resolve this *without* using `pointing`? With `pointing top right`, the menus appear just fine if my menu is in the top right corner. But without `pointing`, the menu goes off-screen.

**Comment by dearsina** [comment]
It's not an old topic if it still hasn't been resolved. Any update on this issue?

**Comment by s-devaney** [comment]
After several hours of head scratching, adding "pointing top right" solved my problem. Wish this was included in the docs.

**Comment by nicely** [comment]
add `style="right: 0;left: auto;"` into dropdown menu.

**Comment by anhldbk** [comment]
@nicely You've made my day! Thank you.

**Comment by akshitahluwalia** [comment]
@nicely You've helped me make my first PR. Thanks!.
