### ISSUE TITLE
[Modal] The .close.icon disappears on IE11 when using observeChanges or modal('refresh')

### ISSUE THREAD

**Issue by Akkenar** [Semantic-Org/Semantic-UI#3646]
**Problem**

When configuring a modal with `observeChanges: true`, on Internet Explorer 11 and if the modal's height is bigger than the size of the window, the close icon (.close.icon) seems to disappear. This is also happening when using `.modal('refresh')`.

This is working as intended on Chrome (please see below). I haven't tested on earlier/later versions of IE nor other browsers.

**Examples**

Please also refer to this fiddle as a demonstration: [here](http://jsfiddle.net/rt5unzxt/9/)
In case you're experiencing some trouble with this fiddle on IE, below is also an example of the code.

``` html
  <div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
      Modal Title
    </div>
    <div class="content">
      <div style="height: 1000px;">
        Modal Content
      </div>
    </div>
    <div class="actions">
      <div class="ui button">Cancel</div>
      <div class="ui positive button">OK</div>
    </div>
  </div>
  <script type="text/javascript">
    $('.ui.modal')
    .modal({"observeChanges": "true"})
    .modal('show');
  </script>
```

_**Internet Explorer 11** (notice the close (X) icon missing at the top of the modal)_

![ie11](https://cloud.githubusercontent.com/assets/1904504/12777724/fe707916-ca5e-11e5-8a73-94e41a87682e.PNG)

_**Chrome** (the close (X) icon is present)_

![chrome](https://cloud.githubusercontent.com/assets/1904504/12777725/fe7923d6-ca5e-11e5-8738-19963a5dfa7c.PNG)

**Comment by kmd1970** [comment]
I second that, same issue with 2.2.6 and IE 11. Firefox seems ok.
Example:
[Imgur](http://i.imgur.com/dR56NyS.jpg)

**Comment by Banandrew** [comment]
See #4676.
