### ISSUE TITLE
[Dropdown] removing "loading" class or "disabled"

### ISSUE THREAD

**Issue by cdutson** [Semantic-Org/Semantic-UI#3648]
Haven't found anything about this in the docs, so I'll ask here. I've got a dropdown that on page load doesn't have any content. As such I disable the element, and give it the loading class. I then fire off `.dropdown()` on it. That works as expected. But the rub comes when I load contents in after. 

If I look at the markup, I can see the content's been loaded, but the click events don't seem to fire off, and I cannot figure out how to remove these states from the dropdown and have it function properly agian.

example:
```
<select id="foo" class="ui loading disabled search dropdown">
[no options]
</select>
$('#foo').dropdown()
```

Then I load options into the select with an ajax call, and remove the classes from the select.

```
<select id="foo" class="ui search dropdown">
[options]
</select>
```

I've tried `$('#foo').dropdown()`, `$('#foo').dropdown('refresh')`, removing the classes manually from the select's parent(which fixes the visual half of the issue).

So if I init a select with loading/disabled on it, and then I want to REMOVE those AND have the click events work (they do not work after I load in contents)... how do I do it? I'm not seeing anything in the docs about this.

**Comment by cdutson** [comment]
Made a test case: http://jsfiddle.net/evgyh06L/

strangely in my example, removing the classes seems to work. I'll have to investigate in my actual usecase to see if I'm missing anything.

**Comment by cdutson** [comment]
As an update, I've figured out the issue.

I'm building this control in a React/redux environment, and populating a list of countries based on content from an api (not using the api settings OF the dropdown, though). What was happening was this:

- Render a select with className set to `ui search loading disabled dropdown`
- Set the dropdown with JS on componentDidMount

this is fine, but when the countries are loaded and passed to the component, the select is rerendering. This caused the classnames to be added again, so I ended up with markups like
<div class="ui search dropdown">
<input foo/>
<select class="ui search dropdown>
...stuff
</select>
</dropdown>

It's this re-addition of the classes to the select that was breaking everything. Not sure what you can do with this information (if you want to do anything at all), but that's what was causing the issue.

**Comment by jlukic** [comment]
This is just related to using the class name `disabled` on a dropdown.
