### ISSUE TITLE
[Table] Add the possibility to create a table with divs

### ISSUE THREAD

**Issue by niieani** [Semantic-Org/Semantic-UI#3650]
Using `<table>` tags when creating tables forces browsers to use special, strict semantics that make it impossible to use HTML components or custom elements as its rows. This causes problems when using frameworks such as Angular 2, React or Aurelia (e.g. https://github.com/aurelia/binding/issues/108), plus the performance of tables created with `<table>` is lower than than that of `<div>` with the right `display: table-(...);` CSS.

A solution would be to make it possible to create tables as divs, e.g. 
`<div class="table"><div class="thead"></div><div class="tr"></div>...` and so on...

**Comment by jlukic** [comment]
Things like fixed table headers on tables, would be much easier using different syntax than `table` `td` etc, unfortunately this is a complete rework of table, and probably not something I plan on addressing for quite a while in the library.
