### ISSUE TITLE
[Popup] - Popup destroys stretched table

### ISSUE THREAD

**Issue by Bullman** [Semantic-Org/Semantic-UI#3651]
**Steps to Reproduce**
Open JSfiddle on wide screen (for showing table column next to each other) and try click button. 
After clicking, the table layout is moved.

**Expected**
The popup should show and do not affect the table.

**Result**
After showing popup, table layout is moved.

**Testcase**
https://jsfiddle.net/ebc7uwnd/1/

**Comment by jlukic** [comment]
Use `inline: true`

https://jsfiddle.net/qvyntkzv/
