### ISSUE TITLE
Dropdown navigation for accessibility 

### ISSUE THREAD

**Issue by ajf-** [Semantic-Org/Semantic-UI#3652]
I am looking at the current implementation of `allowTab` option for the dropdown. But I don't think it's doing what it is supposed to do. 

Wouldn't one like to navigate the actual _dropdown items_ with tab? Here is a fiddle that tries to force the tabindex on the subitems, but it doesn't achieve complete navigation: http://jsfiddle.net/dd9ztapw/

Up/down arrow actually do work, and this would be all that is needed for proper a11y, but there is a problem with the fact that when up/down arrow is used, the element in the dropdown is not actually focused, but only just "visually activated".

I am trying to create an accessible navigation, something along the lines of: http://jsfiddle.net/cdwzjzao/, but I am not finding a way to actually navigate the elements in the dropdown. I can see the down/up arrows give the items the `active` class but a blind user can't see this. He can only hear the elements that are actually focused. I tried it in a screen reader and there no way to get feedback from the aria attributes in the dropdown item with the current up/down navigation. 

Any ideas? Thanks!

**Comment by jlukic** [comment]
This would mess with form tabbing. You can navigate dropdown menus using arrow keys or by pressing the first letter of the item (in selection dropdowns).
