### ISSUE TITLE
[Modal] Image Content in Chrome

### ISSUE THREAD

**Issue by dbybanez** [Semantic-Org/Semantic-UI#3654]
Hi, 

I have a modal that has an image content. Whenever I launch the modal (both Desktop and Mobile view in Google Chrome), the image seems to be distorted. 

Here's a screenshot (Chrome): 
![chrome](https://cloud.githubusercontent.com/assets/11720969/12836675/f990d52e-cbf5-11e5-9d5c-40dba5251b5c.PNG)

For Firefox, everything works fine:
![firefox](https://cloud.githubusercontent.com/assets/11720969/12836696/15bfaac2-cbf6-11e5-8194-dcae74c743f6.png)

No css classes or javascript added. Just plain semantic ui. 

Thanks.

**Comment by hankkk** [comment]
Maybe it is chrome's bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=583721

try CSS by using img { min-width: 0; min-height: 0; }

**Comment by atwoodjw** [comment]
I had better luck w/ this.

```
.ui.modal > .image.content {
  display: block;
}

.ui.modal > .content > .image {
  width: 100%;
}
```

**Comment by avalanche1** [comment]
Closing because no test case.

**Comment by jdpigeon** [comment]
The modal style properties seem to be applying flex properties that override the `display: block` required to get a non-distorted image.

@atwoodjw's solution worked for me (though I didn't need to set width):

```css
.ui.modal > .image.content {
  display: block;
}
```
