### ISSUE TITLE
Option Add All (solution)

### ISSUE THREAD

**Issue by brunokassss** [Semantic-Org/Semantic-UI#3656]
Hi,

This is not an issue, it's more a solution, it's a option to select all elements.

<h1>HTML file</h1>

<p>Multiple Selection with selectAll Option</p>

`<div class="clear dropdown example selectAll">
          <select name="skills" multiple class="ui search dropdown" >
            <option value="all">All</option>
            <option value="AG">Angular</option>
            <option value="CSS">CSS</option>
            <option value="GD">Graphic Design</option>
            <option value="EM">Ember</option>
          </select>
</div>`

<br>

<h1>Javascript file</h1>

$(document).ready(function() {

 $('.selectAll .menu div:first').click(function(){

```
  var todos= $('.selectAll .menu div:first').attr('data-value');
  var select =  $('.selectAll select option');
  var result = new Array();
  var i = 0;

  select.each(function(){
    result[i] = $(this).val();
    i++;
  });

  if(todos=="all") {
    if($(".selectAll .ui.dropdown a.label").length > 0){
      $('.clear.example.selectAll .ui.dropdown').dropdown('clear');//Clean list
    }
      $('.clear.example.selectAll .ui.dropdown').dropdown('set selected', result);
      $(".selectAll .ui.dropdown a:first .delete.icon").remove();//Remove icon
      $(".selectAll .ui.dropdown a.label").not(':first').hide();//hide other elements  
 }
```

   });
});

**Comment by jokeronaldo** [comment]
Please, can you provide a fiddle for test case?

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by GGaritaJ** [comment]
<addr>
$(checkbox).on("click", function (event) {
                if ($(this).hasClass("unchecked")) {
                    var options = $($(select).find("option")).toArray().map((obj) => obj.value);
                    $(select).dropdown('set exactly', options);
                    $(this).removeClass("unchecked").addClass("check");
                } else {
                    $(select).dropdown('clear');
                    $(this).removeClass("check").addClass("unchecked");
                }
            });
</addr>

This works to me, best!

**Comment by markpolarisdesign** [comment]
If you use selection class. You can use my code below.
eg. <div class="ui fluid multiple search selection dropdown"></div>

`
$('#SelectAll').checkbox({
      onChecked() {
         const options = $('#Dropdown > .menu > .item').toArray().map((obj) => obj.dataset.value);
         $('#Dropdown').dropdown('set exactly', options);
      },
      onUnchecked() {
         $('#Dropdown').dropdown('clear');
       },
})
;`
