### ISSUE TITLE
[Icon] - dropdown icon bug in layout

### ISSUE THREAD

**Issue by leandroluk** [Semantic-Org/Semantic-UI#3657]
## Steps to Reproduce
I created a side menu that contains a submenu with 2 levels. Additionally insert two icons, dropdown and cubes. when you have a description in one level of submenu to reach the minimum size, it makes the dropdown fall down text getting mangled

## Expected
needed icons are aligned with the text

## Result
the dropdown arrow fell down text

## Testcase
https://jsfiddle.net/leandroluk/048pq1p0/1/

**Comment by leandroluk** [comment]
this is my solution for this bug:

`.ui.menu .ui.dropdown.item .menu .item:not(.filtered) {
    display: flex;
    justify-content:flex-start;
}
.ui.menu .ui.dropdown.item .menu .item:not(.filtered) .icon.dropdown{
    flex: 2;
    text-align: right;
}`

**Comment by jokeronaldo** [comment]
Hello @leandroluk. Thank you for following contributing guide steps, it helps a lot.

**Comment by jokeronaldo** [comment]
You can easily fix this issue changing icon position.

Your code:
```
<i class="cubes icon"></i> Produtos <i class="dropdown icon"></i>
```

Fix code:
```
<i class="cubes icon"></i> <i class="dropdown icon"></i> Produtos
```

Follow the updated fiffle: https://jsfiddle.net/048pq1p0/3/
