### ISSUE TITLE
[Search] - Dynamic local source

### ISSUE THREAD

**Issue by aesmon** [Semantic-Org/Semantic-UI#3658]
I am having issues with reactive/dynamic local data source. I am using Semantic UI with MeteorJS so my local collection is subject to change. I noticed that Search module copies the source object at initialization and uses that instead of accessing the original function passed at initialization, even if cache is set to false. Is there a way to make it search via the original passed function again?

`$('.ui.search')
        .search({
            source: Template.users.__helpers.get('users')(),
            searchFields   : 'name',
            cache: false,
            minCharacters : 0,
            type: 'users'
        });`
Explanation:
`Template.users.__helpers.get('users')()` - This function accesses my local collection of users who are currently logged in so the returned list object will change. How can I run it on every search to retrieve current local collection?

**Comment by Ruj89** [comment]
I had the same issue, I tried to destroy the search with `$(element).search("destroy")` and recreate the search with updated options with no luck.
I solved cleaning the cache with `$(element).search("clear cache")`.

**Comment by uups** [comment]
Hi, I solved the issue.

get the search.js file from semantic, and store it locally.
change the line 607 in the search.js

the code looks like this:

source = source || settings.source; // this line copies the data locally and will never change in the future.
play with it how ever you want.

hurray, it is solved.
