### ISSUE TITLE
checkbox label place change behavior of the component

### ISSUE THREAD

**Issue by herau** [Semantic-Org/Semantic-UI#3659]
The checkbox works only if the `label` element is inserted before the `input` element in the DOM:

```html
<input id="no" type="checkbox" name="terms" tabindex="0" class="hidden">
<label for="no">No</label>
```

But if i want to put my label before (like many people do), the checkbox input isn't clickable 

```html
<label for="no">No</label>
<input id="no" type="checkbox" name="terms" tabindex="0" class="hidden">
```

**Comment by jlukic** [comment]
Please follow the requirements of the contributing guide.
