### ISSUE TITLE
API: beforeSend does not cancel request

### ISSUE THREAD

**Issue by vkruoso** [Semantic-Org/Semantic-UI#3660]
In the "Cancelling Requests" section of the API usage docs I can see that if ``false`` is returned from the beforeSend callback the request should be cancelled. This is not the case. The example itself does issue the request, as it is easily viewed in the console.

Is there any other way of cancelling the request?

**Comment by yaowenz** [comment]
I've encouter the same issue. Seems $(this).state('flash text', 'Requires Login!'); will block sending, but i think it's not the right way. I think state management is still under developing.

**Comment by jlukic** [comment]
Can you produce the minimal test case required to reproduce this.

**Comment by jlukic** [comment]
I'm fairly certain this is a bug that was introduced in a recent patch.. No good.

**Comment by jlukic** [comment]
This was probably introduced when API `request` was refactored into multiple functions. `get settings` was returning `{}` instead of `false` causing the beforeSend checks not to work.

**Comment by vkruoso** [comment]
@jlukic Sorry about not updating the issue with more information. As I can see the problem is now fixed! Thanks a lot.
