### ISSUE TITLE
Semantic visibility infinite scroll with semantic loader + React js

### ISSUE THREAD

**Issue by athap** [Semantic-Org/Semantic-UI#3663]
A simple example like this one http://jsfiddle.net/q17w57ca/ works for me.
BUT I have a slightly different use case where while waiting for ajax call to finish, I am showing a semantic loader spinner. With the loader, my infinite scroll just doesn't work. Below is the pseudo code

```
module.exports = React.createClass({
  getInitialState: function() {
    loaded: false,
    data: []
  },
  componentWillMount: function() {
    Actions.getDataByAjaxCall()
  },
  componentDidMount: function() {
    $('.myclass').visibility({
      once: false,
      observeChanges: true,
      onBottomVisible: function() {
        alert("please show up"); 
      }
    })
   },
   render: function() {
     if this.state.loaded {
       return this.showDataList()
     } else {
       <Loading />
     }
   },
   showData: function() {
     return <div className="myclass">
       {this.renderList()}
     </div>
   }
})
```
Loading: It is a simple react component utilizing semantic loader.
renderList: Renders a grid of semantic ui cards with images

What I tried: I tried playing with other options like
type: 'image'
offset: 2
refreshOnLoad: true

Is there something I am doing wrong ?
Any help is appreciated. Thanks

**Comment by athap** [comment]
Infinite scroll event works when I test directly in the browser console. Looks like its react virtual dom thats messing things up

**Comment by athap** [comment]
I wrote my own five lines of code to do infinite loading !!

**Comment by coder8keyboard** [comment]
Use plain Javascript to achieve infinite scrolling. I've found bugs with Semantic UI infinite scroller on different OS's.
