### ISSUE TITLE
[Documentation] Vital form documentation missing

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#3667]
In the [form section](http://semantic-ui.com/collections/form.html) of the documentation there should be a note indicating that **some elements like dropdowns must be *manually* initialized**. It took me way longer than expected  to find the little snippet in the [specific dropdown usage page](http://semantic-ui.com/modules/dropdown.html#/usage).

I had to go through the whole "Forms" and "API" sections **thrice**, until I decided to go to the specific element section. This delay and confusion *made me frown*, which, as you surely know is a terrible thing for the skin. My skin aged a couple months. Don't make others suffer the same.

Jokes aside, please, add a note about that in the form section. **Maybe even a link!** 
It might be a good idea to **include the JS required in the code snippets of the examples**, because, as they are, it seems *implicit* that that html code should produce that output *out of the box*. And it doesnt.

**Comment by avalanche1** [comment]
>  include the JS required in the code snippets of the examples
+1

**Comment by jlukic** [comment]
I appreciate your good hearted commentary, but I dont agree that this is hidden in docs. The form page includes includes the javascript for each element for init.
http://semantic-ui.com/collections/form.html#dropdown

All of the code samples also link out (with underlined html) to the appropriate sections.

**Comment by xDaizu** [comment]
I mean snippets like this one, which is supposed to be a "complete example" and one could be led to think that it works "automagically" (other libraries do), which it doesn't. Also helps to quickly see which elements need to be initialized and which dont =)
![form](https://cloud.githubusercontent.com/assets/7584835/13043035/c4b4a51a-d3c5-11e5-9c21-238e5d004864.png)

**Comment by avalanche1** [comment]
I concur.
Though, I understand that it is a lot of manual labour and not a priority.
I've filed a similiar issue to Docs project.

**Comment by xDaizu** [comment]
I agree it's not a huge priority; but shouldn't be overlooked, either. Good documentation/examples should never be overlooked; they create good DX (Dev eXperience), a feeling of confidence and, by showing the devs how to "properly" use your library, you actually reduce the number of issues. And teaching people how to use your tools is as important (or even more) than developing new features. 

*Better documentation* usually equals *happier devs*, devs who *spread the word*, which hopefully brings *more adoption*, and more *adepts* eventually turns into *greater developing workforce* (which is something @jlukic has actually asked for), which will become new (and hopefully *better*) features :D

Me, myself, would be interested in contributing to this library... but for that first I need to understand it; to really understand it, which I actually don't yet. And if it gets too hard or confusing or frustrating I'll end up using another library, because... you know... *path of least effort* and stuff... which would be a shame, because there is a *lot* that I like about this library =)

Also, **I dont think is really that much labour**, they're just a few lines (*10 tops?*) in a couple of snippets. It's just a little thing (that may also seem unnecessary or redundant), but it can mean the world for a newcomer. Trust me! I am one! :smile_cat:
