### ISSUE TITLE
BEM Flow

### ISSUE THREAD

**Issue by xaircore** [Semantic-Org/Semantic-UI#3671]
Use [BEM](https://en.bem.info) flow for html and css

**Comment by sstok** [comment]
You mixed the markdown :) `[BEM](https://en.bem.info)`

And can you explain the why? Whats the benefit, compatibility with existing versions, etc.

Looking at the website the information is very limited on explaining the "why", 
"Technology for creating web applications", this can literally anything!

And what I can find only talks about "how" you can do this, and requires me to learn a new language which is based on JSON?!

**Comment by jlukic** [comment]
Trolling.

**Comment by axpro** [comment]
One benefit: it would be easier to pick just a few components and integrate in an existing design. For example `.modal` `.image` `.text` `.header` `.content` are classes which have a big chance to interfere in an existing system but classes like `.ui-Modal` `.ui-Modal--image` `.ui-Modal__header` are much easier to integrate.

**Comment by jlukic** [comment]
They are scoped to components just not using BEM. There are no "free floating" class names

**Comment by axpro** [comment]
I was referring to the fact that a component used in an existing framework would have it's styles changed by the framework. I usually rewrite the classes but than I loose the ability to easily update to a new version. Anyway, thanks and great work on the framework.

**Comment by robclancy** [comment]
Semantic UI would be a no brainer for all our projects if it used an effective naming pattern instead of a gimmick. Used it in one project because it looks good and offers lots out of the box but have had to fix a lot of bugs related to the gimmicky naming. BEM is significantly better than semantic naming.
