### ISSUE TITLE
[Button] Animated button <-> Bootstrap conflict

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#3673]
You may think I'm actually *shooting myself in the foot* using both, and you might be right, but I do, and they *work* fine. They mostly play fine with each other as long as you keep them separated. I like Bootstrap's more mature grid system and semantic-ui's more stylish and fancy elements. 

*Aaaaanyways*, I'm rambling, what I mean is that so far the only conflict I've found is that someone in Bootstrap thought: <<*you know what's* ***really*** *cool?* ***!important rules!***>> So they decided to define:

```

.hidden{
    display: none !important
}

``` 
because why not.

And this which makes **.hidden.content**.... yes! you guessed it, *un-un-hidable*! So far I fixed it adding 
```
.ui.animated.button .hidden.content{
    display: block !important;
}
```
because two can play that game. But maybe someone can think of a more elegant solution.

PS: **I was gonna actually make a pull request** but when I started navigating what *appeared* to be the `src/css` section of the code I got lost, mugged, bumped into a TARDIS, increasilly dizzy, then scared, then another TARDIS (or *is* it the same?) then dizzy again and finally had to go out to get some fresh air, *so*.... **issue it like it's hot!**

**Comment by jlukic** [comment]
This is a bootstrap issue not a SUI.
