### ISSUE TITLE
using overrides files

### ISSUE THREAD

**Issue by Penderis** [Semantic-Org/Semantic-UI#3675]
I cannot seem to get the override files for either site/site.overrides or default/site.overrides to accept variable changes instance I added @black : red (and multiple other variables) to them assuming this would then change black to red without affecting the theme layer but gulp build and it just does not change a single thing.

How best can I just override variables without adding it to a custom css file?

**Comment by jlukic** [comment]
Make sure you're using valid LESS. Keep in mind variables work differently in LESS than standard "top to bottom" languages. 

Please keep the issues here on GitHub issues limited to specific feature requests, or bugs, not usage questions. See our contributing guide for more details.
