### ISSUE TITLE
Add Bitcoin currency icon

### ISSUE THREAD

**Issue by Polve** [Semantic-Org/Semantic-UI#3678]
The currency icon set misses the most important one: Bitcoin! ;-)

Here a couple of hints
https://cdn2.iconfinder.com/data/icons/money-operations/512/bitcoin-512.png
https://image.freepik.com/free-icon/bitcoin-digital-currency-symbol_318-53073.png

**Comment by jokeronaldo** [comment]
It's already in icon set.
Look into **Brands** or just **CTRL + F** (search in your browser) and type **bitcoin**
