### ISSUE TITLE
Content of side bar is not visible on Chrome and Opera on scroll.

### ISSUE THREAD

**Issue by alexandretperez** [Semantic-Org/Semantic-UI#3679]
I've created a sample of the problem:

http://embed.plnkr.co/UTGDCPo1Ujc5jF8FitGY/

At the sidebar, the content not visible on the viewport remains not visible when scrolling.

Scroll up and down to see the rendering problem.

Firefox, Edge and IE works as expected.

Chrome and Opera fail (maybe a Chromium issue?)

**Comment by jlukic** [comment]
What's the issue? I'm looking at this in chrome and the sidebar is scrolling normally

**Comment by alexandretperez** [comment]
Strange, the issue is remarkable for me.

Take a look here: https://youtu.be/Gk0CXoYKR0g

**Comment by Andrew1431** [comment]
I see this constantly with headers, and the sidenav. Every time i'm using semantic-ui's website this happens on chrome. This issue is absolutely brutal

**Comment by jlukic** [comment]
I have a fix in next point release, it got bad with last chrome update.

**Comment by Andrew1431** [comment]
awesomee thanks :+1:

**Comment by NoobProgrammer** [comment]
Currently I have faced the same issue on my device with android version 4.4.4. My Desktop, iPad(iOS11) and OnePlus2(Android 6.0.1) works perfectly. Is it the hardware issue?
