### ISSUE TITLE
[Form validation] Custom validation function

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#3682]
So... what if I want (or God help us, *need*) a custom function that has to do *very important science* to find out if the field is valid or not? I've gone through the documentation up and down and up again and I've found no example of that.

I guess I could call a function when clicking on the submit button and then call 

`$("#form").form("add errors", errors);`

but that would be pretty *inelegant*. Besides, the errors would be on the form, not the specific field. Wouldn't it be very *cool and fancy* if the `type` attribute accepted a `function`, or a function name with a simple and static API, like `return true` if everything cool, `return false` if it isn't... seems ***simple and useful***! :smiley_cat:  Something like:
```

$('#personal-data-form').form({
    fields: {
        firstname: {
           identifier: 'firstname',
               rules: [
                  {
                      type: 'empty',
                      prompt: pageDataContainer.personal_data_form_messages.firstname_empty
                      },
                  {
                      type: function(value){
                          if( <<rocketScience>> && <<someVodoo>> ){
                                 return true;
                                  }
                          return false;
                          },
                      prompt: pageDataContainer.personal_data_form_messages.rocket_science_failed
                      }
                 ]
          },
(....)
```

could also be the name of a function variable... like 

```
var rocketScience = function(value){ 
    // I'm not showing the code, I don't wanna blow your mind
    itworked ? return false: return true;
}

(...)

rules: [
                  {
                      type: rocketScience,
                      prompt: pageDataContainer.personal_data_form_messages.rocket_science_failed
                      }
                 ]

```
**PS**: If this option exists, consider the title as "*[Documentation] Why is this cool feature not documented?*"

**Comment by reel** [comment]
Looking at **/src/definitions/behaviors/form.js**, it might be easy to add a **custom** type running the function as parameters that should return a boolean value. If @jlukic feels like it might be added, i can spend some time on a PR. This would fix #3699 also.

**Comment by jlukic** [comment]
You can extend form to include custom rules already, but for some reason there is no example of this in docs.

Adding example to "Usage" section with `2.1.9"

**Comment by xDaizu** [comment]
Oh, that looks great! *Lotsa* thanks! :)

Just a little doubt, why is "2" passed as the 2nd parameter (*adminLevel*). Is it always passed as the second (so there can only be 2 parameters) or is it possible to define *n* parameters? That is not a requisite, just asking for clarification (maybe it could even be useful to mention it somewhere on the docs) =)

**Comment by jlukic** [comment]
Bracket is past as second parameter, first is always value. No option for more params

**Comment by xDaizu** [comment]
@jlukic Ok, that sounds great. Thanks again :)
Don't forget to make a little annotation for that on the *docs*, please!

**Comment by mrsaicharan1** [comment]
@jlukic How do we pass in a different field from the same form as a parameter to a custom validation rule?
Suppose here,

```
$('.ui.form')
  .form({
    fields: {
      dog: {
        identifier: 'dog',
        rules: [
          {
            type: 'adminLevel[2]',
            prompt: 'You must be at least a level-2 admin to add a dog'
          }
        ]
      },
dog: {
        identifier: 'cat',
        rules: [
          {
            type: 'adminLevel[dog]',
            prompt: 'some text'
          }
        ]
      }
    }
  })
;
```
