### ISSUE TITLE
Visibility as a standalone plugin

### ISSUE THREAD

**Issue by DaSchTour** [Semantic-Org/Semantic-UI#3687]
Hi,
while working on a project where we sadly do not use Semantic-UI I had a problem, that I could simply use by using the visibilty JS "Plugin". I think it would be great to make the Visibility Plugin a standalone function so that it can be simply used without Semantic-UI.

**Comment by jlukic** [comment]
Please do some simple searching
https://github.com/Semantic-Org/UI-Visibility

**Comment by DaSchTour** [comment]
Okay, than maybe a hint on the documentation of Semantic UI could lead people to the right repo.
