### ISSUE TITLE
Modal Displacement to Bottom and Unscrollable

### ISSUE THREAD

**Issue by mathshane** [Semantic-Org/Semantic-UI#3689]
I'm using:

`$modal('.ui.modal').modal('show');`

and getting a strange result where the modal extends to the bottom of the screen.

I'm using Semantic UI in Meteor (using the Semantic UI Meteor package) and double-checked to make sure there is _no_ Bootstrap or other UI kits in my project.

Pic of bug:
![skjermbilde 2016-02-13 kl 09 50 39](https://cloud.githubusercontent.com/assets/10103131/13028242/6183aaa2-d237-11e5-8139-15287fe168e1.png)

However, it works correctly for modals that do not require scrolling.

![skjermbilde 2016-02-13 kl 09 51 19](https://cloud.githubusercontent.com/assets/10103131/13028245/6d0a08e4-d237-11e5-83a1-fdfebc615236.png)

I tried using `ui long modal` and `ui fullscreen modal`, yet it didn't work for those either.

Additionally, I'd like to add that to get even a regular modal to work (as seen in the working pic), I had to disable all `background` CSS parameters (setting to `none !important`), otherwise the issue happened to non-long modals as well.

**Comment by kmamykin** [comment]
Had the same issue, ended up calling `.modal('refresh')` inside `onVisible` modal callback. 
```
    this.$modal.modal({
      ...,
      onVisible: () => {
        ...
        this.$modal.modal('refresh')
      }
    }).modal('show')
```

**Comment by IonutBajescu** [comment]
Could you please create a [jsfiddle](http://jsfiddle.net) so we can replicate your issue more easily?
