### ISSUE TITLE
modal open page scroll 

### ISSUE THREAD

**Issue by telakaya** [Semantic-Org/Semantic-UI#3691]
when modal open, page scroll stretching to page

**Comment by khrykin** [comment]
Can confirm this with `detachable: false` which i'm using in React environment.
Here is test [case](https://jsbin.com/zepesereni/edit?html,js,console)

**Comment by IonutBajescu** [comment]
I played a little with the test case and I can't figure out what the issue is, can you please answer these two questions? 

- What's the expected behaviour of the scroll?
- What's the actual behaviour of the scroll?

**Comment by khrykin** [comment]
@IonutBajescu I'd expect that scrolling context belongs only to the modal, not the whole page. As I can guess after studying some source code, this is just not implemented for `detachable: false`, is it?
