### ISSUE TITLE
An invalid form control with name='...' is not focusable.

### ISSUE THREAD

**Issue by Qqwy** [Semantic-Org/Semantic-UI#3694]
When creating a rich-text `ui search selection dropdown` with the `required` property, instead of giving any kind of notice when attempting to submit the form when it is still empty, the form seems to be broken to the end user, as only the following error message is printed to the browser console:

    An invalid form control with name='...' is not focusable.

I believe that this is something that is important to be fixed.

**Comment by jlukic** [comment]
I'd recommend using our form validation, build in browser validation is imho not a great set of  APIs.
