### ISSUE TITLE
Selection Dropdown will remove default value

### ISSUE THREAD

**Issue by Qqwy** [Semantic-Org/Semantic-UI#3695]
When converting a conventional select to a Semantic UI `.ui.selection.dropdown`, any blank options are removed, e.g. not selectable after selecting one of the other options.

Basically, a select with the following markup:

    <select name="ice_toppings">
      <option value>None</option>
      <option value="1">Chocolate Sprinkles</option>
      <option value="2">Rainbow Candy</option>
    </select>

after running `$('[name="ice_toppings").dropdown()` and selecting one of the non-*None* options, *None* will be unselectable.

I believe that there are many situations in which this behaviour is unwanted. I hope that an option is added to `dropdown()` to support inclusion of a blank option.

**Comment by jlukic** [comment]
This is a setting, check options on `placeholder`
