### ISSUE TITLE
top fixed menu width issue

### ISSUE THREAD

**Issue by telakaya** [Semantic-Org/Semantic-UI#3696]
i working for this 2 days, ui top fixed menu width overflow from my page width
![issue1](https://cloud.githubusercontent.com/assets/6050956/13033271/0f2d5590-d319-11e5-83a7-38cc07fd3108.JPG)

``<div class="ui left vertical sidebar menu active visible"></div><div class="ui top fixed menu"></div><div class="pusher" style="margin-top:50px!important"></div><div class="ui black inverted vertical footer segment"></div>``

**Comment by esargent** [comment]
I had a very similar issue. Changing

     .ui.menu.fixed
             {width:inherit} 
rather than

    {width:100%} 

fixes the problem. (and I had the menu inside a container)
