### ISSUE TITLE
 [Forms] [Feature request] $form.form("add field error",...)

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#3699]
Since [I can't define custom validation rules](https://github.com/Semantic-Org/Semantic-UI/issues/3682) (...can I?), it would be neat to have an "**add field error**", because if my "customAdditionalValidation()" finds and error, as for now, my only tool to communicate it is `$awesomeForm.form("add error", ["Invalid date"])`, for instance, which is neat... but it would be way _neater_ if I could also mark the faulty field(s), something like: 

``` javascript
$awesomeForm.form("add field error", "birthdate", "Invalid date")
```

, birthdate being the "name" of the field.

As for now the only thing I can come up with is adding something like:

``` javascript
$form.find('[name="birthdate"]').closest(".field").addClass("error");
```

which... feels kinda _hacky_ and I don't know if it can wreak havoc down the line... :sweat_smile:

**Comment by IonutBajescu** [comment]
There's already the `add prompt(identifier, errors)` method. Not documented yet, though.

**Comment by xDaizu** [comment]
> "If the user can't find it, the feature doesn't exist"

:stuck_out_tongue_winking_eye:

**Comment by jlukic** [comment]
I've added this function to docs
