### ISSUE TITLE
Scrolling is buggy on ios and maybe other mobile devices

### ISSUE THREAD

**Issue by ia3andy** [Semantic-Org/Semantic-UI#3700]
Hey mate,

I noticed that scrolling is buggy on ios and maybe other mobile devices.

This is due to a bug on mobile devices which have a bad handling of scroll if it's not on the html tag.
I fixed this bug for myself by adding this:
```
html{
  overflow-y: scroll;
  overflow-x: hidden; // To remove horizontal scroll on mobile devices
}
body{
  height: auto;
}
```

Hope it helps..
Cheers for your awesome ui toolkit, it really looks great!!

**Comment by jlukic** [comment]
I'm not sure what would be causing this, we dont modify scroll container in SUI.

**Comment by saulhudson** [comment]
I have to say that I had a similar buggy vertical scrolling (slow and wasn't flicking/momentum scrolling) on iOS using semantec and @ia3andy's fixed sorted it out perfectly. It may not be a Semantec bug but this fixed worked a treat if others are having the similar issues.

**Comment by jlukic** [comment]
`sidebar` used to use a different scroll context on `ios` but no longer does. Not sure how SUI could cause this.
