### ISSUE TITLE
HowTo Sidebar Overlay in iOS (mobile safari)

### ISSUE THREAD

**Issue by kntmrkm** [Semantic-Org/Semantic-UI#3701]
When using sidebar function in mobile safari. (Xcode simulator iOS 9.2)

I'm setting as `overlay` transition. but, push effect in iOS.

How to fix this?

Jsfiddle is https://jsfiddle.net/kntmrkm/2m5p8gf0/2/

In desktop browser works well. just ios.

thanks.

I found this issue https://github.com/Semantic-Org/Semantic-UI/issues/1985

but I don't know how to.

**Comment by jlukic** [comment]
you can set to a different effect for mobile and pc.

`mobileTransition` is used for mobile,

**Comment by kntmrkm** [comment]
great thanks a lot!

**Comment by LarsBuur** [comment]
This is not working in iOS 9.3. See attached image using your original jsfiddle.

http://fiddle.jshell.net/jlukic/5qdhn4dr/show/

![screen shot 2016-07-11 at 08 47 24](https://cloud.githubusercontent.com/assets/3585707/16722034/2d45de5e-4744-11e6-8dfa-fbab37476031.png)
