### ISSUE TITLE
Dropdown on left side of action input with wrong border-radius

### ISSUE THREAD

**Issue by ohartl** [Semantic-Org/Semantic-UI#3703]
The issues can be seen here:
http://jsfiddle.net/2gp655p0/

In an `.ui.action.input` a `.ui.dropdown` on the left side will be interpreted as action, so its not possible to combine a dropdown left and a button right and have them rounded correctly on the outside.

A simple fix on the first-child dropdown in an action input would be:
```
.ui.action.input:not([class*="left action"]) > .dropdown:first-child {
  border-radius: @borderRadius 0px 0px @borderRadius;
}
```

**Comment by jlukic** [comment]
Thanks for posting  this. Everything looks good. 

I've attached a milestone and will be reviewing this as soon as I can.

**Comment by jlukic** [comment]
I've gone a slightly different direction with the fix, but should resolve the issue.

**Comment by ohartl** [comment]
ok
