### ISSUE TITLE
input[type="search"] applying box-sizing: content-box;

### ISSUE THREAD

**Issue by kimoi** [Semantic-Org/Semantic-UI#3705]
I have the following HTML:

```
<form action="http://admin.laravel-test-vm/user" method="get" class="ui form ng-pristine ng-valid">
    <div class="two wide field">
        <label>Search name/email</label>
        <input type="search" name="search" placeholder="Search name/email">
    </div>
</form>
```

The `input[type="search"]` is having a `box-sizing: content-box;` rule applied, which causes the input to be wider than the parent `.field`. If I change the input `type` attribute to `text`, `email` etc. the box-sizing rule is not applied and the layout is working as expected.

See below two screenshots for example.

`input[type="search"]`
![search](https://cloud.githubusercontent.com/assets/7829319/13096514/db71efa4-d511-11e5-85b6-c9eab136a53b.jpg)

`input[type="text"]`
![text](https://cloud.githubusercontent.com/assets/7829319/13096533/fca8bce8-d511-11e5-9956-0ded80614933.jpg)

This is the line causing the issue in the dist CSS (which I am using): https://github.com/Semantic-Org/Semantic-UI/blob/ee3fe514070cf5d23c6a40bda042664d6f8128f6/dist/semantic.css#L429

**Comment by jlukic** [comment]
We should be ignoring that rule from `normalize.css`
