### ISSUE TITLE
sidebar must be at body level

### ISSUE THREAD

**Issue by bgrayburn** [Semantic-Org/Semantic-UI#3707]
Requiring the sidebar and pusher divs to be children of body makes it difficult to correctly implement this components using React since the SideBar Component will likely not be the top level component and a target container div will likely be used to render the top level component.

**Comment by jlukic** [comment]
They are not required to be at `body` level, check docs.

**Comment by jlukic** [comment]
Hi, GitHub issues is intended for tracking bug reports, and specific feature requests. 

This post falls under the umbrella of "usage questions". I'd recommend using either [the ProjectTalk message board](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI), [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) or [Gitter](https://gitter.im/Semantic-Org/Semantic-UI).

For immediate help [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) is probably your best bet. 

For more information on what should be posted here, please see our [contributing guide]
If you think this still represents a bug, or a feature request, please consider reposting this issue using the considerations recommended in our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)

**Comment by coolblabla** [comment]
![image](https://cloud.githubusercontent.com/assets/19633223/16339469/690326f0-3a55-11e6-9381-cd78621c0994.png)
any comments?
