### ISSUE TITLE
Sticky bound bottom

### ISSUE THREAD

**Issue by TITAN-UZ** [Semantic-Org/Semantic-UI#3708]
How to remove sticky bound bottom class to long item list

**Comment by jlukic** [comment]
Hi, GitHub issues is intended for tracking bug reports, and specific feature requests. 

This post falls under the umbrella of "usage questions". I'd recommend using either [the ProjectTalk message board](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI), [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) or [Gitter](https://gitter.im/Semantic-Org/Semantic-UI).

For immediate help [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) is probably your best bet. 

For more information on what should be posted here, please see our [contributing guide]
If you think this still represents a bug, or a feature request, please consider reposting this issue using the considerations recommended in our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)
