### ISSUE TITLE
Is there a way to cancel the installing of semantic ui to current project?

### ISSUE THREAD

**Issue by Jeff-Tian** [Semantic-Org/Semantic-UI#3711]
I have a project, say A, that dependent on `semantic UI`. There is no problem.
Now I have a project B which dependent on project A. Now the problem is when I type
`npm install A` inside project B, the `semantic UI` always self install to inside project A, which is not needed.

How to let the semantic UI not to install itself to project B?

**Comment by jlukic** [comment]
You could install semantic-ui as a dev dependency in Project A, so Project B will not install as a dependency. Check NPM resources for more info.

**Comment by Jeff-Tian** [comment]
Thank you.
