### ISSUE TITLE
[bug] onRate() for .ui.ratings is always called

### ISSUE THREAD

**Issue by cwbit** [Semantic-Org/Semantic-UI#3712]
There is a bug with `.ui.ratings` where the `onRate()` for `.ui.ratings` is always called (i.e. on page load) even before the user has interacted with it. This means all on-page ratings can fire API calls even if the user has not actually interacted with it yet.

Here is an [example](http://codepen.io/cwbit/pen/QyVdax?editors=1111).

@jlukic I'm also including your response to this from Gitter just in case 

> @cwbit It does seem the case, looks like rating needs a `fireOnInit` setting like `checkbox`
> https://github.com/qualialabs/qualia/blob/dev/app/client/lib/semantic_ui/definitions/modules/checkbox.js#L773
> Probably should default to `false`
> @cwbit this seems very clearly to be a bug, derp

**Comment by jlukic** [comment]
Thanks for filing
