### ISSUE TITLE
[Dropdown] Add Right/Left Menu Variation

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3716]
Add variation for forcing left or right menu alignment for dropdowns. Useful in menus.

**Comment by dogancelik** [comment]
Is there a way to make these pointing arrow show on left?

![arrows](https://cloud.githubusercontent.com/assets/486818/14684882/a8d715e6-073a-11e6-8bf6-dfcb6358efd6.png)

This is the HTML for it:

```html
<div id="nav-menu" class="ui top right dropdown icon item">
  <i class="sidebar icon"></i>
  <div class="menu">

    <!-- ... -->

    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text"><i class="file outline icon"></i> Page</span>
      <div class="left menu">
        <div class="item nav-reload" data-value="reload"><i class="refresh icon"></i> Reload</div>
        <div class="item nav-back" data-value="back"><i class="arrow circle left icon"></i> Go back</div>
        <div class="item nav-forward" data-value="forward"><i class="arrow circle right icon"></i> Go forward</div>
      </div>
    </div>

    <!-- ... -->

    <div class="divider"></div>
    <div id="nav-exit" class="item" data-value="exit"><i class="power icon"></i> Exit</div>
  </div>
</div>
```

**Comment by dogancelik** [comment]
I have noticed something. Even though menu item icons are left oriented, sub-menus don't open when you press left, they open when you press right (it assumes your sub-menu opens on right).

![menu](https://cloud.githubusercontent.com/assets/486818/14989493/d6640c3c-1160-11e6-8ee5-a25b19cb28aa.jpg)

**Comment by voidale** [comment]
how about adding a down menu option? as inside the same menu? That could be great to have dropdowns inside mobile here is an example:

![screenshot from 2016-05-07 14-12-57](https://cloud.githubusercontent.com/assets/4450730/15092043/d259742e-145d-11e6-919c-3fc39a5d7189.png)

I found myself frequently creating different ways for mobile to interact with dropdowns that work on desktop just fine, That could be huge improvement with i suppose not major changes.
