### ISSUE TITLE
Dropdowns do not show scrollbars on macs that have scrollbars disabled (default)

### ISSUE THREAD

**Issue by 5an1ty** [Semantic-Org/Semantic-UI#3720]
On macs that do not have show scrollbars set to always, dropdowns will not show their scrollbar, making it impossible for a user to see if a dropdown has more content then currently visible or not.

![image](https://cloud.githubusercontent.com/assets/5538404/13181595/1f5e1c56-d72e-11e5-9a7a-ed2b571f89f4.png)

The default behaviour for a new Mac is the first setting: "Automatically based on mouse or trackpad".

In the following jsfiddle without the added CSS in the CSS section I cannot see scrollbars on my Mac:
http://jsfiddle.net/u5h01hqf/3/

To replicate, try and remove the CSS and set your mac to "Automatically based on mouse or trackpad".

I think Semantic-UI should take this into account and make sure scrollbars are visible for dropdowns even if OSX has it disabled.

**Comment by jlukic** [comment]
I've been using this in my personal projects with SUI but havent included in mainline. 

Debating how users would think about using custom css scrolbars.

**Comment by Morrolan** [comment]
Personally, I feel that if scrollbars are disabled by the user, don't force-show them using CSS.

**Comment by geemang2000** [comment]
+1 In my UI the DD's are a little too clean and an uneducated user might not know the DD contains more values.

**Comment by nix1** [comment]
I agree with @Morrolan that we shouldn't force-show the scrollbars, but it's still a serious usability issue because people don't notice that there are more items.

What I did (and what I suggest might be the proper solution for this problem) is changing the height of the dropdown so that there is half of the next item visible.

```less
// semantic/src/themes/my_theme/modules/dropdown.variables

/* Responsive */
@selectionMobileMaxItems: 3.5;
@selectionTabletMaxItems: 4.5;
@selectionComputerMaxItems: 6.5;
@selectionWidescreenMaxItems: 8.5;
```

![image](https://cloud.githubusercontent.com/assets/1424680/22972921/0cb389e0-f37c-11e6-9484-4ebc184581d1.png)

By default, this change propagates also to search dropdowns.

**Comment by lubber-de** [comment]
We prepared a little optional swipe animation to the right of the dropdown (where the scrollbar should appear) in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1651
You only have to add `scrollhint` class to the dropdown menu 

Check here (using an iOS device):
https://raw.githack.com/lubber-de/fomantic-ui/jsfiddlefullscreen/jsfiddle/#!lubber/2mcak7xr/167/

![iosscrollhint](https://user-images.githubusercontent.com/18379884/90977728-cba13580-e547-11ea-8997-306f07e58fb6.gif)
