### ISSUE TITLE
How to Make footer stick to bottom

### ISSUE THREAD

**Issue by raviroyind** [Semantic-Org/Semantic-UI#3726]
Hi , I am new to Semantic-UI & having difficulty to make the footer stick to bottom of page always.
Please help.
![footer](https://cloud.githubusercontent.com/assets/11620278/13197756/d74bb258-d81c-11e5-838e-d2611f295963.jpg)

**Comment by Aniel** [comment]
take a look at this http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ works for me like a charm.

**Comment by IonutBajescu** [comment]
Flexbox is the way to go,.

Also, it is recommended that usage questions are posted on either ProjectTalk or stackoverflow. The **Github Issues Tracker** should only be used for bug reports and feature requests.

**Comment by redreamality** [comment]
The feature of adding a native class of "footer" might be popular

**Comment by voytecPL** [comment]
We have 2020 now and still no native Semantic UI footer.
I'd love to see that in near future.
