### ISSUE TITLE
[Embed] - No examples for google maps

### ISSUE THREAD

**Issue by vvsraju04** [Semantic-Org/Semantic-UI#3727]
**Steps to Reproduce**
1. Go to http://semantic-ui.com/modules/embed.html
2. In all the four tabs of this page no usage/example of google maps is mentioned

**Expected**
Documentation for google maps usage with embed .

**Comment by Morrolan** [comment]
@vvsraju04 This should ideally be added to the docs repo for fixing:  <https://github.com/Semantic-Org/Semantic-UI-Docs>

**Comment by jlukic** [comment]
Also all the youtube videos i've used have been since taken down :(

**Comment by jlukic** [comment]
I've fixed the video links in docs, google maps will come with a later milestone.
