### ISSUE TITLE
[Accordion] Loading elements not displayed properly

### ISSUE THREAD

**Issue by Marius2805** [Semantic-Org/Semantic-UI#3729]
**Steps to Reproduce**
Add an form or segment with class loading inside the content container of an closed accordion.

**Expected**
When activating/opening the according, loading element should be displayed properly.

**Result**
Elements are not visible at all. Only if accordion had active status on page load.
But after close and reopen the accordion elements are not visible anymore 

**Testcase**
http://jsfiddle.net/z645t2wh/

**Comment by IonutBajescu** [comment]
You forgot to save the fiddle.
