### ISSUE TITLE
[Rating] - visibility improvement

### ISSUE THREAD

**Issue by neil-s** [Semantic-Org/Semantic-UI#3730]
In the basic rating, unfilled stars are so light by default, they are barely visible. The example in the docs perfectly illustrates this, so not creating a separate repro jsfiddle.

Perhaps setting 100% opacity for the star icon, a darker color, or a thicker outline, would make it more usable. Of course, this is not strictly a bug, and easily modifiable in the site theme, but a more accessible default would be great.

**Comment by jlukic** [comment]
They probably should be filled like `star rating`
