### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rol4400** [Semantic-Org/Semantic-UI#3731]
Documentation doesn't even have the basics. The documentation that is there is mint but I can't even find a page on navbars. People use bootstrap because the documentation make it simple to learn and shows everything on one page. In essence semantic-ui is easier to learn than bootstrap but there is no where you can learn how to use it because the documentation doesn't include half of it. The documentation really needs to be fixed guys.

**Comment by sstok** [comment]
http://semantic-ui.com/collections/menu.html is this what you are looking for? Not all names are the same, as the menu component is much more advanced then just a navbar.
