### ISSUE TITLE
[Label, Step] problem with pointing basic labels in rtl version

### ISSUE THREAD

**Issue by mjnaderi** [Semantic-Org/Semantic-UI#3732]
Hi.
There is a problem with pointing basic labels in newer versions of Semantic-UI rtl build. Semantic UI version is 2.1.8.

```js
<div class="field">
    <label for="id_contact_name">نام</label>
    <input id="id_contact_name" maxlength="100" name="contact_name" type="text">
    <div class="ui pointing red basic label">این فیلد لازم است.</div>                    
</div>
```
![screenshot from 2016-02-22 09-02-25](https://cloud.githubusercontent.com/assets/2115303/13210297/09769ed8-d943-11e5-99f0-2bb90757db8c.png)

JSFiddle: https://jsfiddle.net/ty6j8ee5/

**Comment by mjnaderi** [comment]
This problem also appears in "step" module:
![screenshot from 2016-02-22 13-28-55](https://cloud.githubusercontent.com/assets/2115303/13215091/4a995318-d968-11e5-8e89-f4c35ef158dd.png)

**Comment by MohammadYounes** [comment]
Hi, 

I rechecked this and it's caused by RTLCSS not flipping multiple transforms, a fix will be published soon.

Thanks!

**Comment by MohammadYounes** [comment]
Fix released, update your packages and rebuild!

**Comment by mjnaderi** [comment]
Yes, it is fixed. Thanks!
