### ISSUE TITLE
Inline styling for checkboxes and radios is undesirable

### ISSUE THREAD

**Issue by j055** [Semantic-Org/Semantic-UI#3733]
There are a number of issues when displaying multiple radio/checkboxes inline.

http://jsfiddle.net/j055/efp8z6Ln/286/

1.	Multiple items break outside the container
2.	No horizontal scroll bar is present
3.	Each item is centred vertically. It would be better if they were top aligned.
4.	When the browser window is narrowed, the items are wrapped but scrunched up.
5.	[Not directly related] the label tag is incorrectly used to identity grouped items, i.e. labels should be associated with specific form controls. 

If we are displaying dynamic content then we need a better default styling, i.e. we can’t always know how many items and how long the labels will be at design time.

**Comment by jlukic** [comment]
You should use `grouped fields` for longer content. Inline content can only display so wide reasonably

http://jsfiddle.net/pzcahkj7/
