### ISSUE TITLE
Adding prefix option to avoid naming conflicts

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#3735]
In reference to: https://github.com/Semantic-Org/Semantic-UI/issues/2631 (didn't want to reopen)

Could there be a configurable option in the wizard to add a prefix to every function on build so it doesn't conflict with other functions?

Like, you choose `semantic_`, so every function would be registered as `$.semantic_modal()`, `$.semantic_dropdown()`, etc?

**Comment by tommytompkins** [comment]
I keep running into conflicts between Semantic UI and Bootstrap and would really love it if this was a configurable option somewhere.  Is this something that is being considered?

**Comment by zubinmehta** [comment]
+1
