### ISSUE TITLE
[Dropdown] Unable to attach handler to onChange or onAdd after a dropdown has been initialized

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-Org/Semantic-UI#3744]
If a dropdown has been initialized, you cannot add a handler for the onChange or onAdd events, it only works if they are added during initialization.

During init:

`$('#testThings2').dropdown({
    onAdd: function(addedValue){
            console.log(addedValue);
    }
});`

After Init:

`$('#testThings').dropdown('setting', 'onAdd', function(addedValue){console.log(addedValue)});`

JSFiddle: https://jsfiddle.net/q7yg99Ld/

**Comment by grsabreu** [comment]
any updates on this?

**Comment by shadoWalker89** [comment]
This feature is a must have

**Comment by jlukic** [comment]
As a sidenote, this is specifically related to calling `.setting()` on the original `<select>` element, if you use `setting('onAdd')` on the generated dropdown everything works correctly.

**Comment by grsabreu** [comment]
@jlukic is right! It doesn't work on the select element, you invoke it in the element where the dropdown was initialized.

**Comment by shadoWalker89** [comment]
@jlukic But i will have to do something like this each time

```javascript
$('#SomeSelect').closest('.ui.dropdown').dropdown('setting', 'onAdd', function(){});
```

What is expected is this

```javascript
$('#SomeSelect').dropdown('setting', 'onAdd', function(){});
```

Maybe you could add this and deprecate the `.ui.dropdown` solution.

**Comment by jlukic** [comment]
`module.setup.reference()`, which is used to match a select to dropdown when invoking methods, was not correctly pulling the original dropdown instance when modifying the reference. It was using a new instance. 

This still worked for methods like `set selected` etc that dont change the instance, but `setting` does so it failed to work

**Comment by douglasg14b** [comment]
@jlukic Happy to see you back and committing :)
Thats one hell of a pile of pull requests to sift through.
