### ISSUE TITLE
[Dropdown] Determine previously selected item

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3745]
Hi,

As an enhancement it would be great to know what the previously selected value was. I am frequently encountering this problem in my project, where previous value needs to be removed and new one added in the db, so i thought it would be quite useful.

Passing previous values in the `onChange` seems to be the best choice. Other implementations using separate callbacks will still force user to temporarily remember current value somewhere first and use it later when `onChange` fires (as a workaround, for instance, `onShow` could now be used to mark previous values)

**Comment by jlukic** [comment]
This makes sense
