### ISSUE TITLE
[Dropdown] allowAdditions: search term not being cleared when selecting existing item by clicking

### ISSUE THREAD

**Issue by eslachance** [Semantic-Org/Semantic-UI#3746]
I did not add a jsfiddle for this because it can be reproduced directly on the Examples page:
http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions

Typing in a partial search term in the **Multiple** box, then clicking on an existing term (for example, type in `info` then click **Information Architecture**) does not clear the search term, `info`. This makes it impossible to rapidly add multiple tags simply by typing then clicking on each term.

Steps to reproduce: 

1. Go to http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions
2. Enter `info` in the search box
3. In the drop-down, click **Information Architecture**

Result: The term `info` remains in the input box.

**Comment by jlukic** [comment]
#3779
