### ISSUE TITLE
[Dropdown] allowAdditions: Focus not returned to input box after clicking item

### ISSUE THREAD

**Issue by eslachance** [Semantic-Org/Semantic-UI#3747]
I did not add a jsfiddle for this because it can be reproduced directly on the Examples page:
http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions

Typing in a partial search term in the Multiple box, then clicking on an existing term (for example, type in `info` then click **Information Architecture**) does not return the focus to the input box. This makes it impossible to rapidly add multiple tags simply by typing then clicking on each term.

Steps to reproduce:

1. Go to http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions
2. Enter `info` in the search box
3. In the drop-down, click **Information Architecture**

Result: The focus is not in the input box. Searching again requires clicking in the input box.

**Comment by jlukic** [comment]
#3790
