### ISSUE TITLE
[Dropdown] allowAdditions: Search does not clear after selecting item with arrows + Enter

### ISSUE THREAD

**Issue by eslachance** [Semantic-Org/Semantic-UI#3748]
I did not add a jsfiddle for this because it can be reproduced directly on the Examples page:
http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions

Typing in a partial search term in the Multiple box, using the arrow keys to select an existing term and hitting Enter (for example, type in `info` then do **Down Arrow** **Enter**) does not clear the search in the drop-down. To reset the search, typing in a single character then backspace restores the search (aka, shows all existing items)

Steps to reproduce:

1. Go to http://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions
2. Enter `info` in the search box
3. Use the **Down Arrow** key, then hit **Enter**

Result: The search remains to the previously entered text (**info**) and the drop-down does not show all available items.

**Comment by jlukic** [comment]
Hi, i'm not able to reproduce your issue via keyboard.

A similar issue #3779 was recently closed that would produce your error when selecting a dropdown item with the mouse and not the keyboard.
