### ISSUE TITLE
No change event is fired when toggling a checkbox

### ISSUE THREAD

**Issue by iamolivinius** [Semantic-Org/Semantic-UI#375]
When you click a toggleable checkbox the input object does not fire a change event. 

To demonstrate this I created a [jsfiddle](http://jsfiddle.net/wwjkM/). Check your console for messages.

In my opinion a change event should be fired to have the opportunity to handle events instead of struggling with callback functions like it is documented in the settings sections of the checbox module documentation.

**Comment by fmilani** [comment]
Got the same issue with meteor + react + semantic UI.
Using `$('.ui.checkbox').checkbox('setting', 'onchange', function() {});` worked for me but, unfortunately,  react's onChange didn't.
I noticed that the checkbox always come with `class="hidden"` and only when I manually remove the class (i.e. inspecting the elements of the page) I can make react's onChange fire. Any thoughts? Thanks

**Comment by truongvan** [comment]
**Here is my solution:**

```
<Form.Field inline className="ui checkbox">
    <input onChange={this.handleChange} type="checkbox" name="checkBox" />
    <label>Yes or No</label>
</Form.Field>
```

**Or you can write new class**

```
class Checkbox extends Component {
  render() {
    return (
    <Form.Field inline className="ui checkbox">
        <input onChange={this.props.onChange} type="checkbox" name={this.props.name} />
        <label>{this.props.label}</label>
    </Form.Field>
    )
  }
}
```

**Then** 

```
<Checkbox onChange={this.handleChange} label="Yes or No" name="checkBox" />
```
