### ISSUE TITLE
Feed label does not support multiple icons

### ISSUE THREAD

**Issue by Qqwy** [Semantic-Org/Semantic-UI#3752]
When having the following:

```
<div class="event">
  <div class="label">
    <i class="large icons">
      <i class="comment icon"></i>
      <i class="corner add icon"></i>
    </i>
  </div>
  <div class="summary">
    <div class="user">
      Username
    </div>
    added a Comment to
    <a href="/projects/2/tasks/9">Create Activities</a>
    <div class="date">
      2016-02-24 12:19:36 UTC
    </div>
  </div>


  <div class="extra text">
    <p>This is a test</p>
  </div>
</div>
```

the icons in the label are not shown properly.

This is caused by line 72 in views/_feed.scss, which is, by default

```
.ui.feed > .event > .label .icon { .... }
```

This matches `.icon` elements _inside_ the `.icons` element. When changing this to something like

```
.ui.feed > .event > .label > .icon, .ui.feed > .event > .label > .icons { .... }
```

the icons display fine.

**Comment by Morrolan** [comment]
@Qqwy  Please can you create a jsfiddle demonstrating this?

<https://jsfiddle.net/Morrolan/cvfuLnsn/1/> (from copy/pasting your code) appears to work fine, but because of a lack of test case I'm not exactly sure what ti is you are trying to do?

It is possible to add multiple icons in the same row -  please see <https://jsfiddle.net/Morrolan/cvfuLnsn/2/>.

Again, a test-case demonstrating exactly what you mean is always advised, as stated in the [contribution guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

**Comment by Qqwy** [comment]
Thank you for your reply. I indeed should have provided a more clear test-case from the get-go. I will do so next time.

[https://jsfiddle.net/cvfuLnsn/5/](https://jsfiddle.net/cvfuLnsn/5/) shows what is going wrong. I would expect the `add` icon to show at the bottom right corner of the `twitter` icon. Instead, they are overlayed at the same size.

**Comment by jlukic** [comment]
I've mentioned this in other threads, but `icons` is only *extremely loosely* supports in other components. Generally other components expect an `icon` in that slot.

Perhaps in 3.0 i should reformat these as `icon group` (although this breaks consistency) to deal with this issue.

**Comment by Qqwy** [comment]
After thinking, I think the following might be a possible approach:

- Deprecate `icon group` in 3.0 (So current websites that upgrade will not break, but in new designs it will not be used)
- Introduce a replacement for it, called `composite icon`. I think that this naming is the most natural way to describe the combination of multiple icons in the way it is done now, while also keeping the 'icon' class so elements that apply extra styling to a contained `icon` will continue to work as expected.

What do you think?

**Comment by Morrolan** [comment]
I agree with you @Qqwy - I prefer 'composite icon' to 'icon group'.

**Comment by jlukic** [comment]
I think that seems to be simpler, generally it functions as one icon so `composite icon` is probably simpler
