### ISSUE TITLE
Changing themes

### ISSUE THREAD

**Issue by aderito7** [Semantic-Org/Semantic-UI#3753]
I am sure I'm missing something when it comes to changing themes for semantic, I've done a bunch of changes yet I cannot update my site's default theme to any of the other included themes.

**Comment by Morrolan** [comment]
Themes are not changed globally - instead they are changed on a per-type basis.

From **.../semantic/src/theme.config:**

```
/* Elements */
@button     : 'default';
@container  : 'default';
@divider    : 'default';
@flag       : 'default';
@header     : 'default';
@icon       : 'default';
```

If you change each of these to be the style you require, such as:

```
/* Elements */
@button     : 'bookish';
@container  : 'default';
@divider    : 'default';
@flag       : 'default';
@header     : 'amazon';
@icon       : 'github';
```

Then it gives you a lot more flexibility.

You can of course simply do a find and replace on this file and replace the word 'default' with whichever theme you wish to use from the themes directory.

**Comment by aderito7** [comment]
@Morrolan Thank you for that. The differences are so subtle, but I guess my one downfall was just changing the global site and assuming that was that. I see another thing I have to do is actually copy the theme folder from src/themes to dist/themes that I particularly want. I would assume this to be a bug since it would be something the build script would have had to complete (or can I say feature request?)
One more thing I find missing is icons for my Material Design and not all icons are present with github. I suppose this is another issue?

**Comment by Morrolan** [comment]
@aderito7 - I only know because I got caught out on the global thing.

If you're following the docs properly you shouldn't need to copy anything from src to dist, as your build tools should automatically recompile your CSS for you.  You can use 'gulp watch' <http://semantic-ui.com/introduction/build-tools.html#30-second-explanation> to watch for changes and recompile for you, or you can use software such as Prepress on OS X.

**Comment by Alinux61** [comment]
# dfsdfs# dfdfsdf
