### ISSUE TITLE
[Button] Wrong primary & secondary basic button styling

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#3756]
The primary and secondary basic buttons should behave like the colored ones. At the moment both the ```primary basic button```and the ```secondary basic button``` looks totally the same and didn't use the primary or secondary color:
http://jsfiddle.net/538xf16z/

**Comment by jlukic** [comment]
I'm going to prioritize this for next release. I've run into this as well.

**Comment by jlukic** [comment]
Added along with `positive` and `negative`
