### ISSUE TITLE
[Menu] Says pointing left but actually pointing top

### ISSUE THREAD

**Issue by YamiOdymel** [Semantic-Org/Semantic-UI#3758]
![2016-02-26 7 15 22](https://cloud.githubusercontent.com/assets/7308718/13350816/8bfb504c-dcbd-11e5-9661-af71f0b481de.png)

at the menu examples page.

**Comment by Morrolan** [comment]
This is an error with documentation and has an easy workaround.  

```'ui pointing label'``` defaults to pointing **up**.  The clarifier (left, up, down, right) needs to be BEFORE 'pointing', therefore ```'ui teal left pointing label'``` works as expected.

**Comment by YamiOdymel** [comment]
@Morrolan Okay, thank you so much to telling me this :D
