### ISSUE TITLE
input dropdown json search remote data

### ISSUE THREAD

**Issue by Rafabin** [Semantic-Org/Semantic-UI#3759]
**1- GET DATA REMOTE JSON**
	
	URL: http://192.168.1.20/system_data/pessoaTipo (return json obj)
	my JSON DATA: [{"value":"1","text":"Pessoa Fisica"},{"value":"2","text":"Pessoa Juridica"}]
	
**2- SEARCH DATA IN SQL QUERY**
	dropdown input text: Fisic...
	with ajax?
		
	my ajax:
		$.ajax({
			url: base_url("system_data/pessoaTipo"),
			type: 'post',
			dataType: 'json',
			data: text,
			success: function(ret){		
		}
	})
		
3- RESULT IN DROPDOWN INPUT (WITH MAX ITEM SEARCH LIST = 10)
		
4- ISSUE
	no response data on dropdown
        no search

**Comment by Morrolan** [comment]
Please can you add a test case on jsfiddle to demonstrate?

**Comment by Rafabin** [comment]
http://jsfiddle.net/3xkrx/244/
but my issue is load data from text search on keyup event using ajax

**Comment by jlukic** [comment]
Hi this would fall under the category of usage question, please see our contributing guide for how to structure posts on GitHub issues.
