### ISSUE TITLE
Modale windows have annoying "hard-move" appearance because of overflow:hidden for body-scrollbar

### ISSUE THREAD

**Issue by lubberscorrado** [Semantic-Org/Semantic-UI#3760]
The example http://semantic-ui.com/modules/modal.html shows the effect:
opening a modale window dimms the body tag which immediatly hides the scrollbar by `overflow:hidden;`
Unfortunately this make the window immedialty expand/shrink by the width of the scrollbar which looks annoying, or at least "wrong". You most likey recognize it when closing the modale window.

My suggestion would be to either remove the `overflow:hidden;` for the dimmed body for modale windows or add another class which will take care of that (just because removing it at all from the dimmed class would of course be wrong for all the dimming feature in general)

**Comment by H3ll0W0rld** [comment]
body::-webkit-scrollbar {
    width: 0;
}

As a workaround you can hide scrollbar in webkit browsers. I did not find any permanent solution for other browsers though.

**Comment by DaSchTour** [comment]
There was a similar problem with bootstrap modals. I guess they have fixed it somehow. So maybe it's worth to take a look an how bootstrap solved this.

**Comment by jlukic** [comment]
I'm aware of all the shenanigans [bootstrap does here](https://github.com/Semantic-Org/Semantic-UI/issues/2061#issuecomment-93818380).

**Comment by lubber-de** [comment]
We fixed this in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/468
See https://jsfiddle.net/smudoy1k/5/
