### ISSUE TITLE
[Checkbox] onEnabled/onDisabled setting misspelled or regressed

### ISSUE THREAD

**Issue by petruavram** [Semantic-Org/Semantic-UI#3761]
I managed to track down the cause of the bug. It is a regression that was introduced by fixing #3148. I don't think it's possible to fix this and avoid the backwards incompatibility unless both forms of the methods are defined as settings and called inside enable.

[Reproduced bug jsFiddle](http://jsfiddle.net/1jqfpgtm/1/)

**Comment by jlukic** [comment]
Thanks for the ping, I'll take a look

**Comment by jlukic** [comment]
Added both callbacks until 3.0 to avoid issues
ed98c55e8471ce27a9c76305f5fb2448d05e11e3
