### ISSUE TITLE
[Tab] - Inverted active tabs inconsistent

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#3762]
**Steps to Reproduce**
1. Create top attached inverted tabs
2. Create bottom attached inverted tab segment

**Expected**
Active tab style should match the active tab segment background color

**Result**
Active tab background color is different than the active tab segment that it is attached to. Also, the active tab has a border when it's corresponding segment does not.

**Testcase**
http://jsfiddle.net/n9f62yus/

**Comment by petruavram** [comment]
You forgot to save the jsFiddle.

**Comment by dmaison** [comment]
haha whoops
http://jsfiddle.net/n9f62yus/1/

**Comment by lubber-de** [comment]
This has been finally fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2082
