### ISSUE TITLE
Popup Menu example doesn't work

### ISSUE THREAD

**Issue by Morrolan** [Semantic-Org/Semantic-UI#3764]
Following the example from <http://semantic-ui.com/collections/menu.html#popup-menu> doesn't work - the popup menu appears then vanishes.

Please see <https://jsfiddle.net/Morrolan/ofrm6n7k/> for details.

**Comment by jlukic** [comment]
You need javascript, please read popup usage guide.
https://jsfiddle.net/zgjpyu7e/

**Comment by Morrolan** [comment]
Hi @jlukic - I am afraid that the JSFiddle example you provided me with also doesn't appear to work?

**Comment by qmarlats** [comment]
+1, the example on "Menu" page on Semantic UI website works but the one on "Popup" page and on JSFiddle doesn't work. And when I try to use it me it doesn't work.
