### ISSUE TITLE
remote dropdown doenst search. why?

### ISSUE THREAD

**Issue by Rafabin** [Semantic-Org/Semantic-UI#3768]
**HTML**
```
<label class="lbPessoaTipo">Tipo</label>
	<div class="ui selection dropdown search input mini pessoaTipoIdDropdown">
        <input type="hidden" class="input PessoaTipoId" name="PessoaTipoId" tabindex="0">
         <div class="menu"></div>
         <i class="dropdown icon"></i>
         <input class="search input">
         <div class="default text">Pessoa Tipo</div>
</div>
```

**JS**
```
$.ajax({
	url: base_url("system_data/pessoaTipo"),
	type: "post",
	dataType: "json",
	data:{
			
	},
	success: function(ret){
		result = ret;
	},
	complete: function(){
		$('.pessoaTipoIdDropdown').dropdown({
		  	on: 'click',
		  	//showOnFocus: false,
			fields:{
				name: "text", 
				value: "value" 
			},
		    	onChange: function(){
		    		
		    	},
		    	onShow: function(){
		    	
		    	},
				apiSettings:{
			        response:{
			            success: true,
			            results: result
			        }
		    	}
		}).dropdown("set value",1).dropdown("set text","Pessoa Fisica")
			
	}
});

```

**Comment by Rafabin** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/6231044/13374674/2de85478-dd62-11e5-9d45-caf224835612.png)

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
