### ISSUE TITLE
[Form] Api POST call skips successTest

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3770]
**Steps to Reproduce**
Have e9aca44c50ee057268c8fa45d69e7e280c11d545 installed using the non-minified version (semantic.js and semantic.css)
Add global successTest

    // Define API endpoints globally
    $.fn.api.settings.api = {
      'api user'  : '/api/user',
      'login'     : '/api/login'
    };

    // Define API success test globally
    $.fn.api.settings.successTest = function(response) {
      if(response && response.success)
        return response.success;

      return false;
    };

Add a form in HTML
Assign validation

    .form({
      fields: {
        username: {
          identifier  : 'username',
          rules: [
            {
              type   : 'empty',
              prompt : 'Please enter your username'
            }
          ]
        },
        password: {
          identifier  : 'password',
          rules: [
            {
              type   : 'empty',
              prompt : 'Please enter your password'
            },
            {
              type   : 'length[6]',
              prompt : 'Password must be at least 6 characters long'
            }
          ]
        }
      }
    })

Assign API call using POST

    .api({
        action: 'login',
        method: 'POST',
        serializeForm: true,
        cache: false,
        beforeSend: function(settings) {
          // Get CAPTCHA response
          var recaptcha = grecaptcha.getResponse();

          // Verify CAPTCHA
          if (_.isEmpty(recaptcha)) {
            // Add errors
            $(this).form('add errors', ['CAPTCHA is missing or invalid']);

            // Cancel API request
            return false;
          } else {
            // Add response to data
            _.assign(settings.data, { 'g-recaptcha-response': recaptcha });

            // Continue API request
            return settings;
          }
        },
        onSuccess: function(response) {
          // Valid response and response.success = true
          console.log(response);
          // -> Page refresh here <-
        },
        onFailure: function(response) {
          // Request failed, or valid response but response.success = false
          $(this).form('add errors', response.error);
        },
        onError: function(errorMessage) {
          // Invalid response
          $(this).form('add errors', [errorMessage]);
        }
    });

Submit form.
My api returns a boolean response.success which is false, because e. g. username or password is wrong. successTest should trigger `onFailure` but it doesn't.

**Expected**
Executing api call without page refresh and with correct successTest trigger.

**Result**
successTest gets skipped.
Page refreshes after onSuccess.

**Comment by HitomiTenshi** [comment]
Okay I figured out what caused the page refreshes. SuccessTest doesn't get executed and my code had a redirect on the onSuccess method, I'm 100% sure now. I tested logging the response in successTest and just returning false, both on the global and local definition of successTest.

**Comment by jlukic** [comment]
So the issue is you believe `successTest` is getting skipped for your code?

**Comment by jlukic** [comment]
Thanks for all the catches lately @HitomiTenshi it has been really helpful.
