### ISSUE TITLE
[Input] Input and button does not align

### ISSUE THREAD

**Issue by borglin** [Semantic-Org/Semantic-UI#3773]
If you place an .ui.input element next to a .ui.button element they don't align. The button is slightly smaller than the input (36px compared to 37px for the input) and they don't align vertically.

![screenshot 2016-02-29 21 17 09](https://cloud.githubusercontent.com/assets/6277414/13407649/dbc09ab0-df29-11e5-846e-d84922bb055a.png)

See this: http://codepen.io/anon/pen/dMPGgO

I am using Chrome 48 on Mac OSX Yosemite

**Comment by jlukic** [comment]
Button draws its `border` with box-shadow, while input draws it with `border`, you can vertically align them by specifying `vertical-align: top`

**Comment by borglin** [comment]
Of course you can solve it by aligning them yourself. I just didn't see why they don't align as is.

However, I did some more digging and it might just be an issue with Chrome and Safari. It aligns in Firefox and if I add a value or a placeholder to the Semantic UI input it aligns with the button in Chrome and Safari as well.

The only thing now bothering me is that the button is smaller than the input. Both Chrome and Safari shows the input as 37px (including the border) and the button is 36px. Firefox has the input at 38px. The box-shadow on the button seem to be inset with a spread radius of 1px so it is drawn inside the block.

Chrome 48 OSX Yosemite
![screenshot 2016-02-29 23 39 58](https://cloud.githubusercontent.com/assets/6277414/13411562/0ef9476a-df3e-11e5-8daf-d84b431194e6.png)

Firefox 44.0.2 OSX Yosemite
![screenshot 2016-02-29 23 45 26](https://cloud.githubusercontent.com/assets/6277414/13411630/8a3c55ca-df3e-11e5-9294-5b00f15a14f7.png)

**Comment by jlukic** [comment]
`basic button` draws its box shadow using `inset` so that it can overlay the background, allowing for shading with RGBA, unfortunately this does mean it is now shorter than the standard button.

**Comment by awei01** [comment]
Hi, not sure if this is related or not, but, it appears that when a `placeholder` attribute is placed in an `input` that is adjacent to another `input`, a similar result occurs. 

Chrome Version 54.0.2840.71 OSX 10.9.5

![screen shot 2016-11-03 at 4 14 44 pm](https://cloud.githubusercontent.com/assets/2857763/19983580/f6310e1e-a1e0-11e6-8af4-88c51899ade2.png)

https://jsfiddle.net/sgy9g6bg/10/
