### ISSUE TITLE
[Popup] 'SVGGraphicsElement' is undefined in IE 11

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3774]
Using the current next version (e9aca44c50ee057268c8fa45d69e7e280c11d545) I encountered an error when adding popups to SVGCircleElements on IE 11. No errors on Firefox or Chrome.

Error: 'SVGGraphicsElement' is undefined
semantic.js (10387,13)

The line in question is:
`if(target.width === 0 && target.height === 0 && SVGGraphicsElement && !(target.element instanceof SVGGraphicsElement))`.

Changing it to:
`if(target.width === 0 && target.height === 0 && (typeof SVGGraphicsElement === undefined) && !(target.element instanceof SVGGraphicsElement))`

fixed the error for me and displayed the popup correctly on IE 11.

**Comment by jlukic** [comment]
Thanks, related #3043
