### ISSUE TITLE
[Docs] Add Better Explanation of Behaviors / Invoking Internal Methods

### ISSUE THREAD

**Issue by haneefkassam** [Semantic-Org/Semantic-UI#3775]
Did you know, you can programmaticly validate individual form fields?  Did you also know you could add/remove prompts?  I didn't, and I've looked through the entire documentation, but turns out you can!

``` javascript
// Validate individual fields. Returns true/false
$('.ui.form').form('validate').field(<identifier>)

// Add prompt message to a form field
$('.ui.form').form('add').prompt(<identifier>,"message")

// Remove prompt message from a form field
$('.ui.form').form('remove').prompt(<identifier>)
```

To learn this I had to hunt through the code, and found the answer in this massive file (https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/form.js).  The problem is, I'm pretty sure Semantic-UI is used by a lot of designers, who aren't great at reading code (or even developers who reference documentation), and wouldn't know this is possible by going through the documentation.

The semantic ui documentation badly needs updating.  I mean, even a list/table of all the objects that can be returned from the form method (based on parameter) and the actions you can perform on each one, would be such a great help to utilize Semantic-UI to its fullest.  Have you looked at Bootstrap's documentation?  Or JQuery?  It's pretty clear what you can do with the framework.

**Comment by jlukic** [comment]
I didn't anticipate anyone using strings to return groups of methods like that, but its a pretty cool (unintended) idea. 

There's a list of invokable "behaviors", aka methods in the settings section. Typically sentence cased behaviors get looked up in the internal module and will map either to nested object or camel cased name. 
http://semantic-ui.com/behaviors/form.html#behavior

**Comment by haneefkassam** [comment]
The behaviours are kinda cool (being able to validate an entire form with one call), but it wasn't as fine-grained as I needed.  I needed to validate individual fields, or show custom prompts for specific fields.  I had no idea that I could return these objects which contain methods to perform this fine-grained control over the behaviour of the form control.  Granted, now that I know, it is pretty intuitive, but without that example in the docs, I would have no idea.

Appreciate the reworked title :)
