### ISSUE TITLE
Dynamically populating Semantic Ui Dropdown. Value doesn't get selected as default.

### ISSUE THREAD

**Issue by hadijaveed** [Semantic-Org/Semantic-UI#3778]
I fetch Instruments array from Mongo in Meteor to dynamically populate this dropdown. Is this some bug of 'set selected' or am I doing something wrong?

let dropdownMenuHtml = '',
        selectValueHtml = '',
        index = `0;`
    _.each(fundingInstuments, function(instruments) {
      if (instruments.default === true) {
        selectValueHtml += '<option value="' + index + '" selected="true">' + instruments.type + ' ' + instruments.currency + '</option>';
      } else {
        selectValueHtml += '<option value="' + index + '" selected="false">' + instruments.type + ' ' + instruments.currency + '</option>';
      }
      index += 1;
    });
    self.$('select[name="fundingInstrumentId"]').html(selectValueHtml);
    self.$('select[name="fundingInstrumentId"]').dropdown('set selected', 1);

**Comment by jlukic** [comment]
Please post a simple reproducible test case, there's an example of how to best do this in our contributing guide in the repo. You can feel free to re-open this as a new issue
