### ISSUE TITLE
Specify element theme per class? 

### ISSUE THREAD

**Issue by pedrorodrigues** [Semantic-Org/Semantic-UI#3780]
So I've changed the default form theme to be flat, but in some cases it doesn't fit as good as I wanted.
So what I want to know that I couldn't find anywhere, is if there is a way to specify a form theme based on a class or id. 
Perhaps doing something like:

> ```
> .ui.github.themed.form {
>      @form       : 'github';
> }
> ```
> But the meaning of that must be "only change the theme for that specific form and not the whole site definition"

For instance: 

> `<form class="ui github themed form">` would render a github based form, that would be the same as `@form       : 'github'` but just for that specific form

And if used normally:

> `<form class="ui form">` would render the form using the theme defined in the theme.config.import.less variable

**Comment by jlukic** [comment]
I understand the motivation, but this is not a feature I plan on adding at this time.
