### ISSUE TITLE
Vertical Menu Item specifies divider height twice

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#3781]
Just a small bug:
In Semantic UI's vertical menu, the divider height is specified twice:

- once using variable _@dividerSize_
- and absolutely: _1px_

Menu.less, line 533:
```
.ui.vertical.menu .item:before {
  position: absolute;
  content: '';
  top: 0%;
  left: 0px;
  width: 100%;
  height: @dividerSize;
  background: @verticalDividerBackground;
  height: 1px;
}
```

Kind regards,
Sascha.

**Comment by jlukic** [comment]
Thanks this is a bug.
