### ISSUE TITLE
[Menu] - Image width forces to 2.5em in menues

### ISSUE THREAD

**Issue by PD75** [Semantic-Org/Semantic-UI#3783]
**Steps to Reproduce**
1. Add `<img src="path"/> ` to menu item
2. Added css with height
**Expected**
1. The menu should stay the same height
2. Image should become smaller and fit
**Result**
1. The image is 2.5em, expanding the menu
2. Only height changes not width
**Proposal**
- Create class for images in normal height menu. Preferably with less padding, to allow slightly larger images then 1em.
OR
- Set max height and width for images, so they are easy to change (keep aspect ratio)

**Testcase**
http://jsfiddle.net/324ps1tm/5/

**Comment by jlukic** [comment]
I'm happy with this as a default, I'd recommend just using a little bit of css to size your image if you are unhappy with the menu size. It's difficult to predict a correct size because images can use very different aspect ratios.
