### ISSUE TITLE
[API] data added in beforeSend() is not sent when serializeForm == true

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#3787]
Hi,

I'm sending a form using the api, the problem is, when the serializeForm is true, the data added in the beforeSend() callback are not sent to the server.

Also data in the data attribute is not send too.

```js
$('form').api({
    serializeForm: true,
    data: {
        some_key: 'some data' //Not sent
    },
    beforeSend: function (settings) {
        settings.data.another_key = 'other data'; //Not sent

        return settings;
    }
});
```

**Comment by jlukic** [comment]
Hi, this looks like it could be a valid issue, but you're missing a test case. 

You can get started by [forking this jsfiddle](http://jsfiddle.net/efp8z6Ln/) to create an example showing your bug using *the minimum amount of code* necessary to reproduce this error. 

For more details on filing issues on this board, see our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) which outlines our best practices for submitting bug reports.

Thanks!

**Comment by jlukic** [comment]
I've gone ahead and created my own test case and was unable to reproduce your issue. All three keys are being added correctly, both in beforeSend, settings object, and from form.

http://jsfiddle.net/c4mcceho/
