### ISSUE TITLE
What about gulp 4?

### ISSUE THREAD

**Issue by sosnovskyas** [Semantic-Org/Semantic-UI#3793]
I want use gulp 4 in my project, but when try install semantic installation does not end successfully. If in project installed gulp 3 all good

**Comment by jlukic** [comment]
Gulp 4 has not been released yet, our gulpfile is written to work with the most current released version of Gulp.

**Comment by sosnovskyas** [comment]
Thank you!

**Comment by lubber-de** [comment]
Gulp 4 is used as of https://github.com/fomantic/Fomantic-UI 2.7.0

**Comment by leworking** [comment]
Same problem here, gulp4 gives an error when trying to `gulp build-css`

**Comment by ggcaponetto** [comment]
any update? this is a major problem i 2020...

**Comment by adimittal** [comment]
gulp 4 is not compatible with current semantic-ui@2.4.2.
So, you've to downgrade to gulp 3.x.
But the newer node 12.x is not compatible with gulp 3.
So, to use semantic-ui@2.4.2, you also have to downgrade node to 10.x or lower.

Now, they have branched semantic-ui out to fomantic-ui for the gulp4 based setup. They eventually plan to merge fomantic-ui back into semantic-ui. I don't know when that is.

So, if you want to use gulp4 and node12 for now, then use fomantic-ui.
https://github.com/fomantic/Fomantic-UI

Cheers,
Aditya Mittal
