### ISSUE TITLE
module.can.animate() always returns false in Phantom JS 

### ISSUE THREAD

**Issue by darlesson** [Semantic-Org/Semantic-UI#3796]
I am currently adding some test cases that include content in a modal, but I get "Element is no longer attached to DOM. Unable to animate."

The same tests pass on IE, Firefox and Chrome, but fails on Phantom 2.1.3 both locally and in the testing server.

I set duration to 0 in CSS and also forced 0 in the JavaScript settings but there is no change there. It is only possible to make it work if module.can.animate() is able to return true.

**Comment by darlesson** [comment]
Meanwhile, if anybody else is having problems with that, you can trick module.can.animate to return true by setting the animations in the exists object:

```javascript
if (/PhantomJS/.test(window.navigator.userAgent)) {
    
    var animations = {
        'vertical flip in': true,
        'vertical flip out': true,
        'fade in': true,
        'fade out': true
    };
    
    $.extend($.fn.transition.exists, animations);

}
```

**Comment by jlukic** [comment]
For context, `can transition` applies the specified animation classes to an offscreen test element then verifies that it reports an `animation-name` to make sure the specified animation exists. Once it determines an animation exists it caches it in an `exists` object.

**Comment by jlukic** [comment]
I'm not sure if there's a solution from within the lib for this.

**Comment by darlesson** [comment]
A better recommendation to get around this issue is to use [SlimerJS](https://slimerjs.org/) instead of PhantomJS. After I changed to it I have less test cases randomly failing including for the reason that PhantomJS is way slower.

SlimerJS works as a [Karma launcher](https://github.com/karma-runner/karma-slimerjs-launcher) and it can be used with Jenkins in Linux servers using the [Xvfb plugin](https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin).
