### ISSUE TITLE
Initializing form validation twice cause onSuccess to fire 4 times

### ISSUE THREAD

**Issue by kevinresol** [Semantic-Org/Semantic-UI#3798]
https://jsfiddle.net/Lehyvemg/

Open debug console and click "Submit" in the form. 
It can be seen that `onSuccess` is fired 4 times, if the form is initialized twice.

I need to re-init the form because I will add fields dynamically. (ref https://github.com/Semantic-Org/Semantic-UI/issues/910)

**Comment by jlukic** [comment]
Sorry about that, that was a terrible terrible oversight.
