### ISSUE TITLE
[Dropdown] onRemove not triggering

### ISSUE THREAD

**Issue by sagaio** [Semantic-Org/Semantic-UI#3799]
In the following fiddle `onChange` is triggering correctly but not `onRemove`.
1. Add two tasks to the "related tasks" dropdown
2. Add one of the same tasks to the "finished tasks" dropdown
3. Remove one of the tasks from "related tasks" (should remove the same from "finished tasks")
4. `onChange` is working, try adding a task in "finished tasks" that does not exist in "related tasks" and it should add it.

Am I doing something wrong or is this a bug?

Notice: Vue.js is being used here

https://jsfiddle.net/fierflash/p7de8bt3/1/

**Comment by jlukic** [comment]
You're reinitializing the first dropdown with new settings, destroying the previous instance.

Perhaps you are looking for something like this?
https://jsfiddle.net/js4p0c1v/

**Comment by sagaio** [comment]
Thank you, changing from `$choice` to `value` solved it!
