### ISSUE TITLE
Multiple modals of the same kind in Angular 2

### ISSUE THREAD

**Issue by aderito7** [Semantic-Org/Semantic-UI#3800]
I am using Semantic in Angular 2 and whenever I move away from a route and then come back I see that new HTML is added for each popup causing it to show multiple of the same popups each time.
Also when I call one popup with it's unique class names, other popups materialize as well.

**Comment by darlesson** [comment]
Semantic modals are moved under `<div class="ui modals"></div>` as direct child of `body`. If your modal is coming from a context different from that, you may need to remove the modal before the transition to the next route. In other words you need to clean up what was done out of the route context.

**Comment by aderito7** [comment]
What's working for me now is just putting a $(element).remove() in my ngOnDestroy. Seems a little hacky, but works for now
