### ISSUE TITLE
Toggle Form Validation on and off

### ISSUE THREAD

**Issue by Qqwy** [Semantic-Org/Semantic-UI#3806]
In my form, I have certain fields that are hidden when a checkbox is selected (specifically, checking the *the billing address is the same as the shipping address* checkbox hides all billing address fields). However, these hidden(using JQuery's slideUp() method; they have the inline css `display:none;` style attached) input fields are still validated using Semantic-UI.

Therefore, I would like to be able to call a JavaScript function to turn off the Semantic-UI validation for (part of a?) form.

What would be the proper way to do this?

**Comment by Siyanda** [comment]
Would removing the elements instead of hiding be an option ?

**Comment by jlukic** [comment]
You can use `validation('destroy')` which is fixed in #3798 in next
