### ISSUE TITLE
More examples for apps

### ISSUE THREAD

**Issue by hrstoyanov** [Semantic-Org/Semantic-UI#3807]
SUI still lacks a good set of bootstrap examples for app developers. Can you prepare skeletons like these:
https://github.com/GwtMaterialDesign/gwt-material-patterns

**Comment by avalanche1** [comment]
I guess he can not because he's a one man army here.

**Comment by hrstoyanov** [comment]
The examples I pointed to are also a one-man project. 
I remember Jack did some fake Gitgub skeleton, maybe I can glean some tricks from there ...but the /examples folder in sui is not very useful.

**Comment by Siyanda** [comment]
Here's a link to a few [CodePen demos](http://codepen.io/collection/DgPjkd/)

**Comment by jlukic** [comment]
Closing this as it is a somewhat vague issue for the project. I'd love to have more examples, but time-permitting.
