### ISSUE TITLE
[Loader] rename mini loader to tiny

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3808]
rename mini loader to tiny - to be in line with other elements of the framework

**Comment by IonutBajescu** [comment]
I'm not sure it's worth the breaking change it would cause? We could, instead, make `tiny` an alias for `mini`.

**Comment by Maxhodges** [comment]
```    <div class="ui tiny text loader">Loading</div>
tiny is still used in the docs

**Comment by IonutBajescu** [comment]
Interesting. 

It looks like it might've been fixed by https://github.com/Semantic-Org/Semantic-UI/commit/285aeec1e169c38f989247d4b42bccf3377be4c2. Thanks @Maxhodges for noticing.

@avalanche1 feel free to reopen if it hasn't actually been fixed in *v2.2*.

**Comment by avalanche1** [comment]
Looks like both mini and tiny have their place now :smile:
