### ISSUE TITLE
a.corner.label .icon, does not use pointer for the cursor.

### ISSUE THREAD

**Issue by willstott101** [Semantic-Org/Semantic-UI#3809]
This seems to be deliberately disabled... but I don't understand why. Definitely isn't intended behaviour on my end. [JsFiddle](https://jsfiddle.net/willstott101/qngjphxb/)

[Suspect source code:](https://github.com/Semantic-Org/Semantic-UI/blob/8875b89125e8a1b42b5f88ac3e28ab1dfe64ba9f/src/definitions/elements/label.less#L280)

```
.ui.corner.label .icon {
  cursor: default;
  position: relative;
  top: @cornerIconTopOffset;
  left: @cornerIconLeftOffset;
  font-size: @cornerIconSize;
  margin: 0em;
}
```

**Comment by Banandrew** [comment]
See #4238. I reposted your comment there.
