### ISSUE TITLE
[Dropdown] compact dropdown menu inside top menu visible on init

### ISSUE THREAD

**Issue by sagaio** [Semantic-Org/Semantic-UI#3810]
Check out the right dropdown menu.
https://jsfiddle.net/fierflash/y389ffc8/1/

This `<div class="ui vertical compact labeled menu">` is visible when loading the page and the workaround is to add `transition hidden` on initial classes. Removing `compact` makes it hidden again.

Is this a bug?

**Comment by sagaio** [comment]
What I want to achieve is a dropdown menu inside a `top menu` containing labeled icons like:  http://semantic-ui.com/collections/menu.html#labeled-icon

**Comment by Siyanda** [comment]
Looks like an open div tag was to blame I've forked your jsfiddle here's the [link](https://jsfiddle.net/1p4shk7n/1/)
