### ISSUE TITLE
Activate Not Working in Menu

### ISSUE THREAD

**Issue by gerdogdu** [Semantic-Org/Semantic-UI#3812]
Hi all
I have a problem with menu item activation. I have a below code

			<div style="float: right;">
				<div class="ui menu">
					<div id="'divItem_'{{item.id}}" ng-click="vm.pageItemSelected(item)" class="link item"
						ng-repeat="item in vm.pageItems">{{item.name}}</div>
				</div>
			</div>
`
`

When I click, this is the function I have:

`        function pageItemSelected(item){
            vm.itemsPerPage = parseInt(item.name);
            $('divItem_' + item.id).addClass('active');
        }`

But it never activates! How coud I fix it?

Thanks.

**Comment by Qqwy** [comment]
This does not seem to be a problem with Semantic-UI, but with AngularJS. I have no experience with Angular so I do not know exactly how its rewrite rules work, but what I suspect is that the function scope is not set up right; Maybe it might help to change the `ng-click` part in a function like this: `ng-click="function(){vm.pageItemSelected(item);}"` 

Again, I might be completely wrong.

**Comment by IonutBajescu** [comment]
In case you haven't fixed it already, please repost your question to either ProjectTalk or stackoverflow. The **Github Issues Tracker** should only be used for bug reports and feature requests.
