### ISSUE TITLE
Dropdown does not hide

### ISSUE THREAD

**Issue by ka7eh** [Semantic-Org/Semantic-UI#3815]
See this fiddle: https://jsfiddle.net/kaveh/f4zrds6q/
In the fiddle, if you select something from the dropdown, `onChange` will change the active tab. Now if you click on `tab1` and go back to the tab that contains the dropdown, you can see it is still open and does not hide, no matter what you do!

Any idea about what is going on there? Thanks

**Comment by sagaio** [comment]
I think It's because `.dropdown` uses class `.active` for its active state, that is when it's displaying the `<option></option>`s. Use something like `$('[data-tab=tab1]').removeClass('active');` instead perhaps.

**Comment by ka7eh** [comment]
@sagaio That was it; thanks! :)
