### ISSUE TITLE
[Divider] - Divider is not restrict to the grid

### ISSUE THREAD

**Issue by Sornii** [Semantic-Org/Semantic-UI#3817]
**Steps to Reproduce**
1. Create a form.ui.form>div.ui.two.column.grid(>(div.column>(div.field>input)*3)*2)+button.ui.button
2. Put a div.ui.vertical.divider between the columns

**Expected**
The Divider should be placed between the inputs

**Result**
The Divider does something crazy
Also, the button doesnt have a margin-top

**Testcase**
https://gist.github.com/Sornii/54129b9381ac92988509

**Comment by IonutBajescu** [comment]
You must include the divider within a `.column`. 

Also, it is recommended that usage questions are posted on either ProjectTalk or stackoverflow. The *Github Issues Tracker* should only be used for bug reports and feature requests.

**Comment by jlukic** [comment]
Appears fine in Chrome/FF
http://jsfiddle.net/hgd59c1p/

Please post a jsfiddle repro with your issue.
