### ISSUE TITLE
[Button] Proposal: add state "Unclickable"

### ISSUE THREAD

**Issue by sagaio** [Semantic-Org/Semantic-UI#3820]
I'm currently in the need of having a button not being in a disabled state but rather in a state where it shouldn't be "clickable" and just displaying the content as usual.

That would mean you can use whatever color, look or feel for the button but the button will not change appearance on events such as hover/focus/active.

What do you think of adding such a state?

**Comment by ulises-salinas** [comment]
Have you tried the state 'active'?

```
<button class="ui active button">
      <i class="user icon"></i>
      Follow
    </button>
```

**Comment by jlukic** [comment]
`active` state represents currently activated and unclickable content. I don't believe it makes sense to include a state that appears clickable but is not.

**Comment by aryan-firouzian** [comment]
I also came across to the situation, which I need this behaviour.
