### ISSUE TITLE
[Embed] - Not possible to add custom video content?

### ISSUE THREAD

**Issue by dabroz** [Semantic-Org/Semantic-UI#3822]
I have video attachments in my project. I was hoping to use embed component to load them on demand. However it seems that Semantic UI is trying to serve them as `<iframe>`, not a `<video>`.
I am using following code:

```
<div class='ui embed' data-icon='right circle arrow' data-placeholder='/system/f6d3068fe80cec7bdb5dc255d54033af74131a1a.jpg?1457870119' data-url='/system/015eb6418b1c178b444b66fbfa8aaf8b6c1f9141.MOV?1457870119'></div>
```

And the resulting HTML is:

```
<div class="ui embed active" data-icon="right circle arrow" data-placeholder="/system/f6d3068fe80cec7bdb5dc255d54033af74131a1a.jpg?1457870119" data-url="/system/015eb6418b1c178b444b66fbfa8aaf8b6c1f9141.MOV?1457870119">
  <i class="right circle arrow icon"></i>
  <img class="placeholder" src="/system/f6d3068fe80cec7bdb5dc255d54033af74131a1a.jpg?1457870119">
  <div class="embed">
    <iframe src="/system/015eb6418b1c178b444b66fbfa8aaf8b6c1f9141.MOV?1457870119?" width="100%" height="100%" frameborder="0" scrolling="no" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
  </div>
</div>
```

Also, bonus question: what would be a preferred way to insert them in the feed component? For every attachment I have a set of three files: small image thumbnail, medium-sized image thumbnail (which can be used as a placeholder for enlarged video) and the video itself. I would like to use small thumbnail first, and after a click switch to embed with a bigger placeholder. Currently it seems like there is no support for this, and the aspect ratio of a embed placeholder seems to be broken inside the feed component:

```
<div class='event'>
  <div class='content'>
    <div class='summary'>
      <div class='user'><a href="/users/1">dabroz</a></div>
      posted a comment
      <div class='date' title='2016-03-13 11:55:20 UTC'>
        3 minutes
        ago
      </div>
    </div>
    <div class='extra text'>
      A movie test
    </div>
    <div class='extra images'>
      <div class='ui embed' data-icon='right circle arrow' data-placeholder='/system/f6d3068fe80cec7bdb5dc255d54033af74131a1a.jpg?1457870119' data-url='/system/015eb6418b1c178b444b66fbfa8aaf8b6c1f9141.MOV?1457870119'></div>
    </div>
  </div>
</div>
```

![Embed inside feed](http://i.imgur.com/D7egaD2.png)

**Comment by IonutBajescu** [comment]
As a workaround for the embed module being limited to iframes, you could create a "bridge" page that contains a <video/> tag which loads your video.

For your second question, please post it on either ProjectTalk or stackoverflow.

**Comment by Fatih90** [comment]
> As a workaround for the embed module being limited to iframes, you could create a "bridge" page that contains a tag which loads your video.

@IonutBajescu could you please show an example, i dont want to switch back to bootstrap pls
