### ISSUE TITLE
Progress Bar not working on Id

### ISSUE THREAD

**Issue by hadijaveed** [Semantic-Org/Semantic-UI#3824]
```
<div class="ui indicating progress" data-value="1" data-total="20" id="example4">
  <div class="bar">
    <div class="progress"></div>
  </div>
  <div class="label">Adding Photos</div>
</div>
```

If you apply this java script on this progress bar doesn't work if you give it ID.
`$('#example4').progress('increment');`

But it works on the class
`$(".ui.indicating.progress").progress('increment');;`

Is this some sort of bug or is there something I am getting wrong ?

**Comment by ardamose123** [comment]
Just created a fiddle about this: https://jsfiddle.net/6jeh780w/

It seems to work fine with either the ID or the class in my Chromium browser, with Semantic UI 2.1.8 and jQuery 2.2.1.

**Comment by hadijaveed** [comment]
Thank you!! It was sort of an error on my client side...

**Comment by IonutBajescu** [comment]
Closing this since the issue was solved.
