### ISSUE TITLE
A scrollable popup

### ISSUE THREAD

**Issue by 5an1ty** [Semantic-Org/Semantic-UI#3827]
Example here:
http://jsfiddle.net/nhfe7mnb/13/

Click on the menu item.

I need a scrollable popup so I added some custom css to the popup component (max-height, overflow-y, ...).

I'm wondering if there is a less hacky way for achieving the same look?

**Comment by jlukic** [comment]
Since popup is designed to show any type of content, the correct vertical height for a popup will vary dramatically between usage. 

I think it makes sense to use custom css here, instead of adding a scrollable popup variation.
