### ISSUE TITLE
[Validation] Add 'emails' validation for comma separated

### ISSUE THREAD

**Issue by witold-markowski-sentaca** [Semantic-Org/Semantic-UI#3833]
The email validation passes when entered multiple email addresses in the form, like:

```
a@bc.de , f@gh.ij
```

Emails doesn't have to be "comma separated" in the example; you can enter multiple characters between emails and it will be still validated as a valid email address.
You can use [@paulborza's JSfiddle](https://jsfiddle.net/x0Lq0s8o/3/) from #3755 issue to test it.

Shouldn't it allow to enter only one valid email address?

**Comment by jlukic** [comment]
I think it makes sense to add another validation type `emails` for comma separated lists

**Comment by brunotourinho** [comment]
this would be a nice implementation. Any workaround? I'm interested in file types validation as well.
