### ISSUE TITLE
Entypo font set

### ISSUE THREAD

**Issue by 4tron** [Semantic-Org/Semantic-UI#3834]
This is just a suggestion to make the font set entypo http://www.entypo.com/ instead of font awesome. Although font awesome is a good set , it seems really overused and is becoming a bit stale . 

just a suggestion . Entypo is a really clean set

**Comment by KapuzenSohn** [comment]
I took a quick look and I am totally against it.

Some quick reasons:
- No really description how to use them
- No npm package
- The last time some new icons where added was 3.5.2015
- The Github Repo I found was the last update 2012

Maybe I oversee something, but I think that are some good reason against it

**Comment by 4tron** [comment]
ok cool .. just thought i would suggest
