### ISSUE TITLE
Wrong calculation of "rail" element variables

### ISSUE THREAD

**Issue by ikhilko** [Semantic-Org/Semantic-UI#3835]
Looks like variables `@closeWidth`, `@veryCloseWidth`, `@dividingWidth` has bad unit calculations here:
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/rail.variables#L26

As you can see
`@closeWidth: @width(300px) + @splitCloseDistance(1em);` will be calculated as `301px`; 
`@veryCloseWidth: @width(300px) + @splitVeryCloseDistance(0.5em);` will be calculated as `300.5px`;
`@dividingWidth: @width(300px) + @splitDividingDistance(2.5rem);` will be calculated as `302.5px`;

**Comment by jlukic** [comment]
Yes, this is very clearly, entirely incorrect. Not sure how this was introduced.

The `less` rule should ether be in a `calc` statement and use `border-box` or the width should remain `300px` and use `content-box`. Not sure how this was introduced.

**Comment by jlukic** [comment]
Thanks for your patience
