### ISSUE TITLE
Group Buttons and Stacking Issue

### ISSUE THREAD

**Issue by mixerp** [Semantic-Org/Semantic-UI#3838]
Wouldn't it be nice to have something like `ui stackable buttons`? Currently, `buttons` do not display correctly on mobile devices. For example, please view this simple fiddle and resize your browser and the fiddle page frame.

http://jsfiddle.net/5dwxg5f3/1/

**Comment by a8568730** [comment]
+1 too.
I referenced the `.ui.stackable.menu`, and I get stackable buttons as below:
```
@media only screen and (max-width: 767px) {
  .ui.stackable.buttons{
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    flex-direction: column;
    width: 100%;
  }
  .ui.stackable.buttons > .button{
    width: 100%;
  }
}
```
```
<div class="ui stackable two buttons">
     <button class="ui button">1</button>
     <button class="ui button">2</button>
</div>
```
I didn't test this very much, but hope it gives you some ideas.

**Comment by bvn13** [comment]
@a8568730 Thank you, it works fine!
