### ISSUE TITLE
Can 'set selected' use a data-value='0'?

### ISSUE THREAD

**Issue by sirganya** [Semantic-Org/Semantic-UI#3840]
I'd like to use `data-value=0` but `(set selected', '0')` doesn't work

You can see what I mean here

http://jsfiddle.net/ud2qxebd/3/

**Comment by mahdimp** [comment]
the values must be strings
this works 

` $('#zero').click(function(){
        $('.ui.dropdown').dropdown('set selected', 0);
    });
    
    $('#one').click(function(){
        $('.ui.dropdown').dropdown('set selected', 1);
    });`

**Comment by sirganya** [comment]
Thanks. My typo, should have been `'set selected'`. It's correct in the fiddle. Is there a reason why it works with numbers except for 0?

**Comment by jlukic** [comment]
Input `value` will cast all values to strings, matching against their javascript types will cause issues with strict matching.
