### ISSUE TITLE
Repeating typo in Docs at the page 'Item'

### ISSUE THREAD

**Issue by SemT** [Semantic-Org/Semantic-UI#3842]
In the Docs at the page "Item" under Views there is a repeating mistake of mentioning 'A item' instead of 'An item'.   
http://semantic-ui.com/views/item.html

**Comment by jlukic** [comment]
Thanks I'll fix

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-Docs/commit/0a0bc977421e3f38a206f237e4824dcd47666b51
