### ISSUE TITLE
Visibility Fixed on iOS

### ISSUE THREAD

**Issue by srissel** [Semantic-Org/Semantic-UI#3845]
Dear support,

we have implemented a page with a fixed header, we use Semantic UIs "Visibility Fixed".
As far a I understand, "Visibility Fixed" creates a placeholder element (visibility: hidden) within the browsers DOM, to keep the document's original element floating/ordering.
I can observe this using the Chrome's developer tools.

On iOS for some reason, 3 placeholder elements are created, which leads to some bad behaviour when dragging the page down (pull-to-refresh): some of these (superfluous?) placeholders become visible.

I tried to build a simple JSFiddle to reproduce the behaviour, but for some reason, this JSFiddle's "visibility: fixed" doesn't work on an iPad; presumably because the fiddle is embedded into an iFrame.

Anyway, here is the link:
http://fiddle.jshell.net/Windwalker/wj0hd7u7/show/light/

Do you have an explanation for this?

Kind regards,
Sascha.

**Comment by srissel** [comment]
N.B.:
Remote debugging this fiddle with an iMac, I can only detect one placeholder element within the DOM.
So I suggest, the behaviour described above (3 placeholders) is caused by some specific cause in our application.

Do you have any hint, how this could happen?

**Comment by jlukic** [comment]
Hi, I can confirm things look fine in your test case. Please re-open as a new issue if you are able to reproduce the issue in a discrete test case outside your app.
