### ISSUE TITLE
Turkish characters look weird

### ISSUE THREAD

**Issue by AOnurOzcan** [Semantic-Org/Semantic-UI#3847]
Hello. I am new to Semantic UI. I realised that turkish characters look weird. They seem bold even though they are not. I couldn't solve this problem. Should I change the default font? Thanks.
![untitled](https://cloud.githubusercontent.com/assets/7273908/13895289/383d1ec2-ed7a-11e5-90fc-a9cb1b285347.png)

**Comment by jlukic** [comment]
I'm not familiar, but it might be an issue with the default font `Lato`, see theming guide for how to load a diffferent google font, or custom font.

**Comment by AOnurOzcan** [comment]
Thank you @jlukic
