### ISSUE TITLE
Confused behavior on inline validation.

### ISSUE THREAD

**Issue by alexandretperez** [Semantic-Org/Semantic-UI#3848]
When we have a form with multiple fields to validate we just need focus/blur only one of them to all validations appear on the screen. I think this behavior is confusing to the users.

Go to the "http://semantic-ui.com/behaviors/form.html#/examples" and scroll down till the "**Validating on Blur and other Events**" section (a good example of what I'm talking about).

Click on the field "First Name", then click out of the form _(Only the "First Name" field is validated)_. Repeat the exactly same process. _(Now, all the fields are validated)_.

This is designed to be this way? Or it's a bug?

**Comment by Banandrew** [comment]
Fixed in 2.1.9. See #3606.
