### ISSUE TITLE
Multiple modal issue

### ISSUE THREAD

**Issue by MohanVijayakumar** [Semantic-Org/Semantic-UI#3853]
Hi , 
First thanks for the great UI and i am using this in all my projects

when using multiple modal , if first modal's height exceeds (i.e when scrolling added to the window) the window then the second modal comes after the first modal instead of coming on top of the first modal

**Comment by faouzzz** [comment]
Hi, same here... I wrote a comment in #1584

**Comment by jokeronaldo** [comment]
Duplicated at https://github.com/Semantic-Org/Semantic-UI/issues/1584
