### ISSUE TITLE
input[type='submit'] class "loading" not working

### ISSUE THREAD

**Issue by krtschmr** [Semantic-Org/Semantic-UI#3854]
if i have a submit button with .ui.button class, the .loading is not working correctly. instead just hiding the "value". no spinner pops up.

**Comment by Blue-EyesWhiteDragon** [comment]
Example of your HTML? Assuming you're submit button is in a form it should look something like this:

`<form id="form-1">
    <button type="submit" value="submit" form="form-1" class="ui loading button">Loading</button></form>`

Correct?

**Comment by krtschmr** [comment]
|<form class="ui form">
<input type="submit" value="submit" class="ui loading button" />
</form>|

**Comment by Blue-EyesWhiteDragon** [comment]
Oh it's the input element, my word that's strange since they share mostly everything...

**Comment by krtschmr** [comment]
exactly. i was confused too.

its just the loading class that's not working. on a button it was fine, 
if i remember correctly.

**Comment by Blue-EyesWhiteDragon** [comment]
Yeah I tried it on a button, and that works.

Hope they sort this out, I'll have a looksee and see if I can understand why that is happening by looking at the css.

I'll post a quick little oneline css code here if I do find out.

**Comment by jlukic** [comment]
There are no free floating helper classes in Semantic UI, only variations of components. For example a `loading button`. 

`loading` by itself will not produce any effect.

**Comment by krtschmr** [comment]
umm, obiously we talk about "ui loading button" which doesn't work if it's an input[type='submit']
its a bug and not a close...

**Comment by davidmccoy** [comment]
+1, input[type="submit"] doesn't work with loading.

**Comment by jlukic** [comment]
Just a single JSFiddle, that's all i ask. Please check the contributing guide. Code explains all.

**Comment by krtschmr** [comment]
well, than its prblem-slvd if its not possible. wont say its a bug then.
