### ISSUE TITLE
Modules using 'requestAnimationFrame' are broken within firefox extensions

### ISSUE THREAD

**Issue by iamolivinius** [Semantic-Org/Semantic-UI#3855]
I guess all of semantic-ui's modules are invoked like this.. more or less

```js
;(function ( $, window, document, undefined ) {
  ...
})( jQuery, window, document );
```

This works fine in the usual browser window environment but fails for example if you invoke the sidebar module from a Firefox extension's content script. 

`TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.`

Other famous JS libraries fixed similar issues by replacing the `window` object with the "real" global object. see: 

https://github.com/lodash/lodash/pull/1340
https://github.com/zloirock/core-js/pull/91

I was able to fix the error by adding the following code (extracted from core-js) to the sidebar module: 

```js
var global = typeof window != 'undefined' && window.Math == Math
  ? window : typeof self != 'undefined' && self.Math == Math ? self : Function('return this')();

;(function ( $, window, document, undefined ) {
  ...
})( jQuery, global, document );
```

TC39 is also making some efforts in this direction but the proposed `getGlobal` function is not reliable within Firefox extensions: https://github.com/tc39/proposal-global#rationale

**Comment by jlukic** [comment]
Thanks for the very well thorough bug post.

Pretty easy fix with no downsides. Will probably toss that sucker right in the SEAF

**Comment by jlukic** [comment]
Thoughts on
```javascript
...
})( jQuery, (typeof window != 'undefined' && window.Math == Math) ? window : (typeof self != 'undefined' && self.Math == Math) ? self : Function('return this')(), document );
```

**Comment by jlukic** [comment]
This should do it

**Comment by jlukic** [comment]
Argh messed up find & replace. Will fix in another commit.

**Comment by danmoller** [comment]
I still get this error when I try to put [angular](https://angularjs.org/) as a content script....
