### ISSUE TITLE
[Search] onSelect return false does not prevent results from closing

### ISSUE THREAD

**Issue by blazuka** [Semantic-Org/Semantic-UI#3856]
Per the documentation, returning false in this callback should prevent the search results from closing:

> The function should return false to prevent default action (closing search results and selecting value)

**Comment by jlukic** [comment]
.Hi, thanks for posting. Your issues missing a test case.

You can create a test case by [forking this JSFiddle](http://jsfiddle.net/efp8z6Ln/). It already includes the necessary dependencies and adding your test case. 

For more explanation, check out our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

**Comment by blazuka** [comment]
Test case here: [http://jsfiddle.net/8L5z3djv/](http://jsfiddle.net/8L5z3djv/)

You can see that the search term remains in the input after selection, but the results close.

**Comment by jlukic** [comment]
I've fixed this in 2.2, instead of preventing the bubbled event which could cause compatibility issues, I've decided to create a flag to track bubbled `blur` events from negated search clicks.
