### ISSUE TITLE
[Documentation] Please have someone make updating the online documentation a high priority  

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#3857]
I love Semantic UI, but the documentation need to be updated. Some are still missing hidden features (not mentioned). 

I always have scan through an entire module .js file or github issues list to find out about hidden features/settings (new or old). 

Example, there is no mention that the menu for dropdown.js can be edited and changed. (I searched for a while)

``` javascript
$.fn.dropdown.settings.templates.menu =  function(response, fields) {
    var
      values = response[fields.values] || {},
      html   = ''
    ;
    $.each(values, function(index, option) {
      html += '<div class="item" data-text="' + option[fields.label] + '" data-value="' + option[fields.value] + '">' + option[fields.name] + '<p class="title">' + option[fields.title] + '</p></div>';
    });
    return html;
  };
```

Also, some of the posted examples could use better explanations and we also need a better forum for asking "how-to" questions.  (fixing the docs will reduce the number of questions)

Pretty Please? :)

**Comment by jlukic** [comment]
All docs pages include a "fork this page" button that makes it pretty simple to add additional html. Unfortunately I haven't had the bandwidth lately to do major docs work, there are still entirely undocumented components like `state`, and `visit`.

**Comment by haneefkassam** [comment]
I just logged a bug about this too (https://github.com/Semantic-Org/Semantic-UI/issues/3881).  Also, where is the "fork" button?  I could not find it.
