### ISSUE TITLE
Gulp task help descriptors incorrect

### ISSUE THREAD

**Issue by ewhance** [Semantic-Org/Semantic-UI#3858]
Good Morning,

I noticed that the help comments are switched on two tasks, build-rtl reads "Watch files as RTL" and watch-rtl reads "Build all files as RTL".

I was also curious if there could be an effort to remove unneeded tasks conditionally based on your install options. Since I chose to not include RTL in my install, I would prefer that those tasks not be included.

Thanks,
ewh

**Comment by jlukic** [comment]
These options are removed conditionally.
https://github.com/Semantic-Org/Semantic-UI/blob/master/gulpfile.js#L76

**Comment by ewhance** [comment]
Thanks for the reply jlukic.

I did notice that there were conditional statements in ./semantic/gulpfile.js that should be working. Perhaps it is specific to my usage somehow. I'm working in VS2015 (using the task runner explorer), followed the recipes/advanced-usage guide on semantic-ui.com, and imported the watch and build tasks with the specified path (/semantic/tasks/watch and build); However, I have not been able to observe any impact to the tasks when the /semantic/gulpfile.js is edited or even entirely commented out. There doesn't seem to be any caching going on either. I suspect that the expected inheritance is not occurring. By chance are you familiar with this issue?

**Comment by ewhance** [comment]
I've also found that I actually have the gulpfile.js from https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/npm/gulpfile.js at /Semantic/gulpfile.js instead of the one you linked. Perhaps this is an issue?

**Comment by jlukic** [comment]
That is correct, there's actually two ways to install, from `npm install semantic-ui` and `gulp install`

I've modified the help text to swap them back
