### ISSUE TITLE
[Dropdown] Using API causes value to overwrite preset text

### ISSUE THREAD

**Issue by kosaben** [Semantic-Org/Semantic-UI#3860]
I posted  a JSFiddle: https://jsfiddle.net/baronz/5xj89sf2/5/ to illustrate the semantic dropdown behaving correctly.  The hidden element contains a value "12345" which maps correctly and displays the text "Article".

However, on this JSFiddle https://jsfiddle.net/baronz/5xj89sf2/4/ the only difference is that I added the "apiSettings" option.  The text now displays the value "12345" instead of the text.

Any help would be appreciated but in the meantime I think the workaround is to do something like:

$('.ui.normal.dropdown').dropdown('set selected',['12345']);

**Comment by kmd1970** [comment]
:+1:

**Comment by jlukic** [comment]
I've fixed this in 5a610c35f388af0000dcec488f47c901197dc93c and the next few commits.

**Comment by jlukic** [comment]
Example of bug in current
http://jsfiddle.net/0aL0takq/

Example of same code in next working correctly
http://jsfiddle.net/pzd6n5zt/
