### ISSUE TITLE
[Button] - Docs Missing State Component

### ISSUE THREAD

**Issue by gsonnenf** [Semantic-Org/Semantic-UI#3863]
**Steps to Reproduce**
Go to the button documentation web page, Click on the code for the toggle button. 

**Expected**
The toggle button code should include the following javascript: 

$('.ui.button.toggle') .state({
      text: {
        inactive : 'Vote',
        active   : 'Voted'
      }
    });

**Result**
The Button does not include that javascript so the user is unable to easily reproduce the example result.

**Comment by jlukic** [comment]
This is because it is using the undocumented state module #212 is the original issue here. Continue conversation in there.
