### ISSUE TITLE
[Dropdown] Add preserveType setting

### ISSUE THREAD

**Issue by nesk** [Semantic-Org/Semantic-UI#3866]
Is their any reason we can't pass JSON data to dropdown values? Here's an example:

``` html
<div class="ui selection dropdown">
  <i class="dropdown icon"></i>
  <div class="default text">Items</div>
  <div class="menu">
    <div class="item" data-value='{"id":1, "name":"Item 1"}'>Item 1</div>
    <div class="item" data-value='{"id":2, "name":"Item 2"}'>Item 2</div>
  </div>
</div>
```

``` js
$('.ui.dropdown').dropdown({
  onChange: function(value) {
    console.log(value); // Displays `[object Array]` instead of `[1, 2]`
  },
});
```

This is due [to those lines](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2165-L2167). If this isn't necessary, can we remove this cast?

**Comment by jlukic** [comment]
Form inputs are limited to string values, so we cast to string. This avoids many possible errors when matching values like 0, false, undefined, and makes sure the value returned after page reload (when stored in an input) matches the original value.

I'd recommend parsing json from the string.

**Comment by nesk** [comment]
Oh I understand, but then why retrieving the value with the `data` method (which automatically performs a `JSON.parse`) instead of the `attr` method?

Today, when I need to store some JSON data, I must prefix the string with some random characters to avoid jQuery parsing the data (and then getting a weird `"[object Object]"` string). When I receive the data (through the `onChange` event), I must remove the prefix and next I can finally parse my data.

By using the `attr` method in your code, I wouldn't have to prefix the stringified data.

**Comment by nesk** [comment]
@jlukic Any thoughts about my last message?

**Comment by jlukic** [comment]
Because input `value` are treated differently in browsers. Generally you'd run into the same issues if you were trying to store JSON objects elsewhere in forms. It should be negligible to serialize as a string then parse JSON.
