### ISSUE TITLE
[Modal] - control show and hide durations separately

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3869]
I'd like to be able to control show and hide durations separately.

**Comment by Rafabin** [comment]
var formModal = $(".formModal").modal({
		detachable: false,
		closable: false,
		transition: "fade in",
		duration: "1000ms",
		onShow: function(){
		    formModal.form('clear').form('reset');
		},
		onHide: function(){
			formModal.modal({
                transition: "fade out",
                duration: "200ms"
            })    
		},
		onHidden: function(){	
            var content = $(".tabList").html();  
            if(!content){
                search();
                content = null;
            }
		}									
	}).css({
        "min-width": "94%",
        "margin-left": "-47%"
	});

**Comment by lubber-de** [comment]
This has been implemented in the upcoming 2.8.8 of the community fork https://fomantic-ui.com by https://github.com/fomantic/Fomantic-UI/pull/1869 using `settings.transition.showMethod` and `settings.transisiton.hideMethod`
