### ISSUE TITLE
[Search] onSelect return false does not prevent closing results

### ISSUE THREAD

**Issue by tomazzlender** [Semantic-Org/Semantic-UI#3870]
It looks like setting return false to onSelect callback does not prevent closing results popup in the latest version 2.1.8.

In previous version it worked like you can see in the following fiddle
http://jsfiddle.net/vw35s0un/

But not with the latest version
http://jsfiddle.net/joqtdzan/1/

1. In both cases type something in the input field like "a"
2. Click on result.

In first fiddle (old semantic ui version) it closes in another (newest semantic ui version) it does not.

What should I do to prevent closing results popup when something is clicked inside popup?

**Comment by jlukic** [comment]
I'm not sure the best way to handle this, both cases make sense to me.

**Comment by jlukic** [comment]
Merged into #3856

**Comment by jlukic** [comment]
Fix in #3856
