### ISSUE TITLE
Statistic does not vertically center in parent container div

### ISSUE THREAD

**Issue by myrtleTree33** [Semantic-Org/Semantic-UI#3874]
Statistic does not vertically center in parent container div, even when using `middle aligned` in class.  Added in `content` and removed `statistic`, works.

After further investigation, happens in the `.statistics.statistic` rule: caused by the `margin: 0em 1.5em 2em;` property.

Turning this property off allows statistic to become centered again.  However, margins mess up.

**Comment by myrtleTree33** [comment]
Temporary fix using 
```
.middle.aligned.content.statistic {
  margin: 0 1.5em !important;
}
```

**Comment by jlukic** [comment]
Please re-open with an explicit test case. See contributing guide for how to best contribute. Regards
