### ISSUE TITLE
grid system broken internet explorer

### ISSUE THREAD

**Issue by partitect** [Semantic-Org/Semantic-UI#3875]
Grid system and segment is broken internet explorer 
![semantic](https://cloud.githubusercontent.com/assets/6050956/14061899/8b5b1962-f395-11e5-898f-a8706ee3a7a7.PNG)

**Comment by telakaya** [comment]
Hi,
grid system ie fix this code
`[class*='equal width'].ui.grid > :not(.row).column, [class*='equal width'].ui.grid > .row > .column, .ui.grid > [class*='equal width'].row > .column {
    -ms-flex: 1 !important;
    -webkit-flex: 1 !important;
    flex: 1 !important; /* IE 10 */
}`

**Comment by IonutBajescu** [comment]
Could you please create a [jsfiddle](http://jsfiddle.net) so we can replicate your issue more easily?
