### ISSUE TITLE
The mobile menu.

### ISSUE THREAD

**Issue by TVMax-A** [Semantic-Org/Semantic-UI#3876]
Hello! How to build a mobile menu with your framework? All the options presented in your documentation is not adapted to the screens of mobile devices and tablets. **(Written translator)**

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by jeveloper** [comment]
Its fairly straight forward , feel free to reach out, i can help
