### ISSUE TITLE
[Dropdown] Fastclick makes it fire twice

### ISSUE THREAD

**Issue by Almaju** [Semantic-Org/Semantic-UI#3880]
I was testing my website on iPhone and noticed that dropdown didn't work: it shows and then instantly hides.

After investigating, it seems this is because of Meteor fastclick package (https://atmospherejs.com/meteor/fastclick). It fires the touch event twice.

The quick & dirty solution is either to remove the package or to add `.needsclick` class to the dropdown elements.

**Comment by jlukic** [comment]
This looks like a known incompatibility. There have been a few other threads about fast click. Since I handle touch events natively I'm not sure I can accommodate this specific use case.
