### ISSUE TITLE
Variable global not defined in semantic.js

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3882]
Commit 4292ab5aa1411ae016f879c469322cc72629eb08
causes following error:

08:07:32.421 ReferenceError: global is not defined
<anonymous>semantic.js:497
1semantic.js:497:1

I see it's defined in the single components, but not in the all in one file.

**Comment by jlukic** [comment]
I've modified the logic here because it was incorrect
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js#L16
