### ISSUE TITLE
Docs: Reveal -> Variations images should be wrapped

### ISSUE THREAD

**Issue by petetnt** [Semantic-Org/Semantic-UI#3883]
In http://semantic-ui.com/elements/reveal.html ([reveal.html.eco#L145](
https://github.com/Semantic-Org/Semantic-UI-Docs/blob/6740235a60e40f5aa193bb007b533e1507f71bcd/server/documents/elements/reveal.html.eco#L145)) the items are not wrapped, which lets the images scale and overflow out of proportions:

![image](https://cloud.githubusercontent.com/assets/7641760/14105537/df2d9986-f5b4-11e5-85be-a31a5e0bdc84.png)

**Comment by jlukic** [comment]
I let this sit for 24 days :frowning:

**Comment by jlukic** [comment]
Fixed

**Comment by petetnt** [comment]
🐎  👍
