### ISSUE TITLE
Shape shrink form size before instantly return to it normal size during animation

### ISSUE THREAD

**Issue by vinh123456789** [Semantic-Org/Semantic-UI#3885]
Hi, currently i'm adding a feature that toggle display between two form using Shape. Everything went fine except during animation, the form that have bigger size shirnk down to the size of the other form: http://jsfiddle.net/n2mq51d6/2/
Is it a bug, or is there any config that can make the bigger form keep it size during animation.

**Comment by jlukic** [comment]
Having revisited shapes recently, theres a few things.

It was one of the first components I wrote, now about 4 years ago, and the basic architecture could use some improvements. Generally shape behaves inconsistently with centered content, block level content, and inline block content.

That being said, I've included a new setting in `next` build which lets you specify the width and height of the component on animation to either, the `next side`'s size, the `parent` size, or a specified width in pixels.
