### ISSUE TITLE
[Popup] - Multiple dropdown in popup

### ISSUE THREAD

**Issue by Bullman** [Semantic-Org/Semantic-UI#3887]
Hello, i have found bug which is caused by using dropdown in popup.

**Steps to Reproduce**
1. Open my JSFIDDLE
2. Click on "Users" in menu
3. Try delete some persons from dropdown using **cross in label**

**Expected**
Item from dropdown should be deleted and popup keep displayed

**Result**
Item from dropdown is deleted, but popup is hidden. When i want to delete more items i have to click on "Users" and show popup again and again.

**Testcase**
![cross](https://cloud.githubusercontent.com/assets/4174177/14141083/1c503544-f67d-11e5-81f5-4739c69c8ac3.png)

https://jsfiddle.net/d8L58xay/6/

**Comment by jlukic** [comment]
The issue was related to elements removed from DOM (like a dropdown label) would cause popup to think you clicked outside of popup (causing close).

**Comment by jlukic** [comment]
This was never completely fixed in first commit, fixed in 		50f5d8d
