### ISSUE TITLE
YouTube embed is not working with URL that contains "-" (Hyphen)

### ISSUE THREAD

**Issue by jiwonbest** [Semantic-Org/Semantic-UI#3888]
Hi,

YouTube embed is not working with URL that contains "-" (Hyphen).

Notice that even on Semantic website, the video is not working.
http://semantic-ui.com/modules/embed.html#/definition

Could this be resolved?
Thanks!

**Comment by jlukic** [comment]
The video in SUI was taken down unfortunately. I have this fixed in `next`, but have been holding off for releasing everything as a new minor version `2.2`

**Comment by jiwonbest** [comment]
Thanks for the reply jiukic. Do you know when v2.2 will be released? Our company is using Semantic UI in the production at the moment and we're experiencing handful of YouTube related problems due to this specific bug.

**Comment by jlukic** [comment]
I'll try to bundle up `2.2` in the next couple weeks. 

You might consider using the [`next` branch as an NPM dependency](http://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json) to get any changes now.

**Comment by jlukic** [comment]
Additionally if your'e experiencing any other bugs with `embed` don't hesitate to report (with test cases), this is generally a component that I have had less feedback on.

**Comment by jiwonbest** [comment]
Is this issue resolved? Thanks.

**Comment by jlukic** [comment]
Yes in unreleased `2.2` please hold

**Comment by mybridge** [comment]
When would this be available?
ᐧ
