### ISSUE TITLE
[Grid] Responsive Width: missing 'small monitor' variant

### ISSUE THREAD

**Issue by nix1** [Semantic-Org/Semantic-UI#3890]
Having a grid in a container, the container is automatically resized for 'small monitor'

`@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .ui.container {
    width: 933px;`

However, there is no matching class name for setting custom column width for small monitor. I can prepare separate variants for `mobile`, `tablet` and `computer` manually, but the layout would still break if screen width if between 992px and 1199px.

Expected usage:
`<div class="sixteen wide small monitor eight wide computer column">`

**Comment by rickmed** [comment]
+1

**Comment by nix1** [comment]
@rickmed thanks a lot! I somehow missed that in the code

For clarification, `grid`, _Width per device_ section has the following variants:
`mobile`: `(min-width: 320px) and (max-width: 767px)`
`tablet`: `(min-width: 768px) and (max-width: 991px)`
`computer` (Computer/Desktop, sizing called Small Monitor in Container): `(min-width: 992px)`
`large screen` (Large Monitor): `(min-width: 1200px) and (max-width: 1919px)`
`widescreen`: `(min-width: 1920px)`
