### ISSUE TITLE
[Dropdown] - Set selected on inline dropdown as object doesn't work

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#3892]
**Steps to Reproduce**
1. Attempt to set the default value of a dropdown using an object as a parameter

    $( '.ui.inline.dropdown' ).dropdown({ 'set selected' : 'value' });

**Expected**
This method should function the same as the following code, and set the selected value of the dropdown 

    $( '.ui.inline.dropdown' ).dropdown( 'set selected', 'value' );

**Result**
The dropdown does nothing

**Testcase**
http://jsfiddle.net/q827t59u/4/

**Comment by jlukic** [comment]
The syntax for using set selected was wrong in your test case, using `{ 'set selected' }` which is syntax for passing in a settings object, not invoking a method/behavior.

http://jsfiddle.net/wtckuxat/
