### ISSUE TITLE
Is semantic ui dead? Should I start using bootstrap?

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#3894]
I see there are hundreds of issues unreplied on Semantic UI. It's also long due an update on the library which already has at least 200 bugs well documents and not fixed yet. 

So I ask you if there is no intend to update this library anymore cause if that's the cause I will move on to bootstrap cause I really need a good and updated library to use on my projects instead of a buggy and old updated library.

**Comment by jlukic** [comment]
This is a loaded question, and obviously no, I look at these boards everyday and contribute code every week.

**Comment by batata004** [comment]
ok, so keep up with the good work but I really appreciate if you solve many of the bugs reported here cause this library is getting everytime more unstable with random effects on the websites I embed it.

**Comment by enjoyiacm** [comment]
@batata004 Think to go Bootstrap? Rly? Even latest version of SUI (at Jan 7, 2016) looks better and more functional than new Bootstrap 4.x :+1:

**Comment by batata004** [comment]
bootstrap is not as beautiful and as resourceful as Semantic UI but at least it works more reliable and their bug tracker is much less crowded than semantic ui which has lots of issues reported with 0 commetns. Anyway, keep up the good work guys, if you need any help I would be glad to contribute.
