### ISSUE TITLE
Dropdown login form

### ISSUE THREAD

**Issue by Skisas** [Semantic-Org/Semantic-UI#3896]
Hello, I came with a problem while trying to create dropdown login form.The problem is when I click any of input boxes it minimizes immediately. I searched in documentation, but found only one example (with class="ui input"), but that doesn't work for me.Here's my code:

               <div class="ui dropdown teal small button">
                        <i class="user icon"></i> Log In
                        <div class="menu">
                            <form class="ui form item">
                                <div class="sixteen wide field ">
                                    <label class="small">Username</label>
                                    <input type="text" placeholder="Username">
                                </div>
                                <div class="sixteen wide field">
                                    <label>Password</label>
                                    <input type="password" placeholder="Password">
                                </div>
                                <div class="sixteen wide field">
                                    <div class="ui checkbox">
                                        <input type="checkbox" tabindex="0" class="hidden">
                                        <label>Remember password and username</label>
                                    </div>
                                </div>
                                <button class="ui button" type="submit">Sign In</button>
                            </form>
                        </div>
                    </div>
and js:
`$('.ui.dropdown')
                .dropdown()
              ;`
Maybe someone have some ideas how to fix it ? 
P.s. Thanks for help

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
