### ISSUE TITLE
Sticky a grid's column

### ISSUE THREAD

**Issue by yamsellem** [Semantic-Org/Semantic-UI#3897]
Using `.ui.sticky` on a grid's `column` do not work properly.
I don't know if it's intended — there ain't no word about it in the doc, but it's an affix classic, say, detach a `column` with the navigation bar.

Anyway, here is a [fiddle](https://jsfiddle.net/yamsellem/rprLyf1z/) showing how I've fixed that.
Is there something wrong with this?
Should I create a PR with it?

Thanks for the great work on semantic anyway ^^.

**Comment by jlukic** [comment]
You probably won't be able to use sticky with a flex item. Using `visibility({ type: fixed})` will probably have better luck because it adds hidden placeholder content which preserves existing layout.
