### ISSUE TITLE
animated button restore state on click

### ISSUE THREAD

**Issue by rickmed** [Semantic-Org/Semantic-UI#3898]
this examples: http://semantic-ui.com/elements/button.html#animated

When I click a button, the hidden content stays showed. How can I can restore the visible content on click?

**Comment by jlukic** [comment]
Animated button show animation on `focus`, generally using `<button>` preserve focus on click as an accessibility feature.

If you want it to not preserve focus you can use `<div class="ui button">Click</div>`

**Comment by rickmed** [comment]
@jlukic thanks for the response!

using div instead of button does not work (still preserves focus)

**Comment by 12s** [comment]
replacing button tags to div tags broke the focus as described for me

**Comment by koloff** [comment]
Replacing the button tag with a div tag does not fix the problem for me. When I click the button it is still in :focus.

**Comment by icodebuster** [comment]
@jlukic 
I have tried changing the `<button>` tag to `<div>` still it's not working. Any other workaround.

**Comment by evanandrewrose** [comment]
If you're handling the events to the button manually, which is likely if you're trying to prevent the animation from being sticky when you hit the button, you'll want to prevent the browser from allowing focus to be applied to the button.

You can do this by eating the event that happens on 'mousedown'. For jQuery it's something like:

```
$('.no-sticky-animation').on('mousedown', function(event) {
  event.preventDefault();
});
```

If you're using the semantic/react bindings, you can just do:

```
<Button
  animated="vertical"
  onMouseDown={e => e.preventDefault()}
>
```

**Comment by I-NOZex** [comment]
> onMouseDown={e => e.preventDefault()}

Vue.js:
`v-on:mousedown.prevent="$event.preventDefault()"`
