### ISSUE TITLE
Gulp  4.x

### ISSUE THREAD

**Issue by salarmehr** [Semantic-Org/Semantic-UI#3899]
I got the following error when installing semantic vis npm:

```
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui" "--save"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.1.8 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.1.8 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.
```

**Comment by jlukic** [comment]
I can't reproduce on vanilla npm in windows 10.  Unfortunately the error message above doesn't point to any particular problem.

**Comment by salarmehr** [comment]
I noticed that the error stack started with the following message:

```
> gulp install

[17:41:05] 'install' errored after 2.63 s
[17:41:05] TypeError: gulp.hasTask is not a function
    at D:\www\www\mehr2\node_modules\run-sequence\index.js:19:22
    at Array.forEach (native)
    at verifyTaskSets (D:\www\www\mehr2\node_modules\run-sequence\index.js:13:11)
    at runSequence (D:\www\www\mehr2\node_modules\run-sequence\index.js:94:2)
    at Gulp.module.exports (D:\www\www\mehr2\node_modules\semantic-ui\tasks\install.js:430:1)
    at module.exports (D:\www\www\mehr2\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\www\www\mehr2\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\www\www\mehr2\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\www\www\mehr2\node_modules\orchestrator\index.js:134:8)
    at D:\www\www\mehr2\node_modules\semantic-ui\node_modules\gulp\bin\gulp.js:129:20
```

Checking:
```

gulp --version
[17:51:27] CLI version 0.4.0
[17:51:27] Local version 4.0.0-alpha.2

```
It seems the issue is from my gulp version. Is there any way to run Semantic UI gulp file when local version is 4.x?

Thanks.

**Comment by jlukic** [comment]
As mentioned in other threads, since `4.x` is a major release, we can't support the breaking changes introduced. When 4 has a public release we will support

**Comment by salarmehr** [comment]
Thanks for your reply. Since many developers are not using the gulp v4 and sooner or later SUI's gulp files will be migrated to the new version, it is very helpful to add both version to repository. So the user can choose his preferred version.

**Comment by jlukic** [comment]
This kind of forked support is out of my reach as a developer. I'll have to wait until 4 is released to update.

**Comment by sensedeep** [comment]
FYI: quite a few packages are migrating to version 4. E.g. Aurelia.  So we are in a half-way mode currently. So using Semantic with Aurelia is difficult.  Any acceleration on v4 support would be great.

**Comment by jonlb** [comment]
So, is there a work around for this? I'm trying to use Semantic-UI with Aurelia and not having much luck.....

**Comment by fargs** [comment]
Same. Trying to use with Aurelia and I am getting this error.

**Comment by david-steinberg-codes** [comment]
I'm in the same boat.

**Comment by geomorillo** [comment]
nobody cares? gulp.hasTask is not a function

**Comment by geomorillo** [comment]
I'm in the same boat.
--
we are drowning here

**Comment by lteacher** [comment]
Hmm yes I get this too, but erm v4 is released so... is help needed here? Should this be reopened? I dont really use gulp anymore till now but... surely can do upgrade easy?

**Comment by jungjuyoung** [comment]
Let me know if someone's done this!

**Comment by ColinFrick** [comment]
@jungjuyoung The community fork Fomantic-UI supports gulp 4 since 2.7.0 https://github.com/fomantic/Fomantic-UI/blob/master/RELEASE-NOTES.md#version-270---december-21-2018

**Comment by jungjuyoung** [comment]
> @jungjuyoung The community fork Fomantic-UI supports gulp 4 since 2.7.0 https://github.com/fomantic/Fomantic-UI/blob/master/RELEASE-NOTES.md#version-270---december-21-2018

@ColinFrick thanks for reply, Is 'Fomantic-UI' the same as 'Semantic-ui'?
I have to use Dropdown, the country of the Semantics UI.

**Comment by ColinFrick** [comment]
@jungjuyoung Fomantic UI is a community fork of Semantic UI and is compatible. We introduced many fixes and new features
