### ISSUE TITLE
[Project] Specification file to generate HTML code

### ISSUE THREAD

**Issue by dmitry** [Semantic-Org/Semantic-UI#390]
Make specification file, from which it will be able to generate HTML code of all the available: elements, collections or views. Each variation and type of the element should be defined as a separate “method” with strict interface (arguments).

The benefits of it:

**Testability**
* Visually in different browsers - at least in firefox and webkit it’s possible to do so easily and automatically from node.js. In details it’s a tool that checks the visual changes and reports if there are some changes. Existing tools that can be integrated into a project: http://csste.st/
* Unused code checking - possible using the https://npmjs.org/package/ucss. The library will be always clean from the junk it can save over iterations.
* Themed elements integrated into a production site can be broken after the semantic-ui version update. Prevent from happen this cases.

**Usage** - as the interfaces will be used (may be for someone it will be easier to understand it as a “methods with arguments”), even if the HTML code was changed in the following versions, it will be generated correctly even after the semantic-ui in a production code.
**Consistency** between example code (or styleguide) and the CSS code was written for it. It can be auto-generated after the new elements were added into a specification file.

There are lots of other advantages and benefits can be earned after the specification files of the elements will be implemented.

Think of `semantic-ui` as OOP:

* Abstraction - differentiate and divide elements into a smallest entities
* Interface - HTML generation
* Incapsulation (isolation) - testing
* Polymorphy - variations
* Inheritance - types

In the end it should be set of tools written on javascript and running on node.js and the libraries on other languages to generate HTML in other languages (I can help with ruby and javascript).

Some ideas how it’s possible to write the specification files and HTML generator:

https://github.com/mattyod/matic
https://github.com/zodoz/jquery-ZenCoding

I've seen [button spec file](https://github.com/Semantic-Org/Semantic-UI/blob/master/spec/elements/button.json). It lacks interface thing, for example for the button it should be the `link` and the `text`. I haven't defined yet the ideal structure of the specification, but we can start at least from something after the analysis of requirements from the perspective of the elements that are already in the library.

What do you think of that idea and what do you can suggest to start to work on getting it into a real life?

**Comment by jlukic** [comment]
Spec files were abandoned due to difficulty in implementation.

**Comment by dmitry** [comment]
@jlukic what about using something like this: https://github.com/FormidableLabs/radium-bootstrap/blob/master/modules/components/button.jsx? Isn't it solves most of the issues web-developers are facing while writing markup/styles for the large applications?
