### ISSUE TITLE
[Transition] - fade right is way less performant than fade in

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3904]
Fade right is way less performant than fade in. When testing on a throttled down cpu. Where fade right chugs like 5 fps, fade in performs without lag.
I can cook up a test case if need be.

**Comment by jlukic** [comment]
Directional fade animations use `translateX()` and `translateY` which are considered performant properties to use in css animations. I'm not sure any other way that this could be addressed on a framework level.

**Comment by avalanche1** [comment]
Ok. In that case we'll have to wait until I have the resource to do in-house research of that issue and contribute the results.
