### ISSUE TITLE
[Dropdown] Not working on IE 11

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3905]
Using commit 68b007461a257d301b6c606992c3bbec451451f4 on the next branch.

I have a dropdown set to drop down on click. On Firefox and Chrome it works fine, but now on IE it throws this error:

SCRIPT438: Object doesn't support property or method 'contains'
semantic.js (5605,15)

It's this code:

            var
              $target      = $(event.target),
              $label       = $target.closest(selector.siblingLabel),
    >>>          inVisibleDOM = document.contains(event.target),
              notOnLabel   = ($module.find($label).length === 0),
              notInMenu    = ($target.closest($menu).length === 0)
            ;

**Comment by sstok** [comment]
Which version of IE?

**Comment by HitomiTenshi** [comment]
To be exact it's:
11.0.10240.16724
Update Versions: 11.0.29 (KB3139929)

Though I don't think it has something to do with that exact version. I thought mentioning IE 11 in the title would suffice.

**Comment by jlukic** [comment]
I'll need a different solution than `document.contains` thanks for your constant help @HitomiTenshi

**Comment by IonutBajescu** [comment]
@jlukic Try using *document.body.contains*.

**Comment by jlukic** [comment]
Modified in 42dd3c7

I've confirmed locally it should fix IE11. Thanks for wait.
