### ISSUE TITLE
Add rtl support for Arabic, Farsi and Hebrew language

### ISSUE THREAD

**Issue by srabeat** [Semantic-Org/Semantic-UI#3906]
Is this something that you are planning to support? I would love to contribute if it's on your roadmap.

**Comment by VSG24** [comment]
RTL version is already available. But it has a bug. Import the semantic.rtl.min.css in your html and then set the direction attribute for container class to rtl:

```
                .container {
                    direction: rtl;
                }
```

I hope they include this fix in the nearest update.

**Comment by jlukic** [comment]
There's RTL support within our build tools, install with NPM and use custom install option, will ask for RTL.
