### ISSUE TITLE
[Dropdown] - Search in-menu doesn't support defaults

### ISSUE THREAD

**Issue by neil-s** [Semantic-Org/Semantic-UI#3908]
**Steps to Reproduce**
1. Replicate code in the Definitions > Search in-menu example
2. Set a default value by setting `value` on the hidden `input`. In my example, I've chosen the 'Retail' market as the preset value.

**Expected**
The Dropdown should show the default value (Retail) as selected

**Result**
The Dropdown shows the `text` value instead.

**Testcase**
http://jsfiddle.net/neil_s/pffh9976/5/

**Comment by jlukic** [comment]
It looks like you set `value` on the wrong input. The `hidden` input tracks the current dropdown value.
http://jsfiddle.net/rbu5g89z/
