### ISSUE TITLE
Form validation e-mail issue

### ISSUE THREAD

**Issue by AOnurOzcan** [Semantic-Org/Semantic-UI#3911]
Hello. 

I realised a bug today. Form validation accepts e-mails like that **name@name.com xyz** but it shouldn't accept **xyz**. Am I wrong?

Thank you.

**Comment by jlukic** [comment]
I does not accept xyz, check the docs.

**Comment by AOnurOzcan** [comment]
I'm sorry but I tried again at Semantic UI's own page but it still does. @jlukic 
![untitled](https://cloud.githubusercontent.com/assets/7273908/14387431/0c8454d8-fdb2-11e5-9b36-d61a37254e13.png)
