### ISSUE TITLE
Padding form field

### ISSUE THREAD

**Issue by gboslee** [Semantic-Org/Semantic-UI#3913]
Semantic UI - 2.1.7

http://jsfiddle.net/efp8z6Ln/310/

@media only screen and (max-width: 767px) {
  .ui.form .fields>.field {
    padding-left: 0;
    padding-right: 0;
  }
}

Please add style to smoothly display the form field for small screens .
By the screenshots can be seen as the field does not look smooth.
Indent left and right margins are different.

![1](https://cloud.githubusercontent.com/assets/5418890/14382857/6750a9c8-fdaa-11e5-8dd3-7253d01c3075.png)

**Comment by IonutBajescu** [comment]
Not able to replicate it by using your fiddle. Could you maybe share your browser details with us?

![](https://i.imgur.com/HX5o3Sk.png)

**Comment by gboslee** [comment]
http://jsfiddle.net/x4npur00/
Please look again

**Comment by jlukic** [comment]
Thanks @gboslee

**Comment by jlukic** [comment]
Fixed in `2.2` See example here (wait a few mins for cache to reset on next dist)
http://jsfiddle.net/mLp7qmL6/
