### ISSUE TITLE
container class should have a RTL direction

### ISSUE THREAD

**Issue by vsg24** [Semantic-Org/Semantic-UI#3914]
Currently the RTL version that's created using the generator, has a HUGE bug. The `container` class should have a direction value of `rtl` to work properly. This is essential to RTL web sites.

**Comment by jokeronaldo** [comment]
Can you provide a fiddle?

**Comment by VSG24** [comment]
https://jsfiddle.net/rnbpzf7s/

It's a horrible fiddle, I know that but it's enough to prove my point.
The css section contains the semantic min rtl version. The menus should be places on the right side. Now If you uncomment the `container` class override on the html section it works fine.

**Comment by MohammadYounes** [comment]
For RTL version to work properly, your document direction should be right-to-left. You need to set it either inside your HTML `<html dir="rtl">` or inside your CSS `html { direction:rtl; }`.

**Comment by VSG24** [comment]
This is an issue with semantic UI and has nothing to do with HTML. All
other RTL frameworks set the container class to RTL and so should Semantic.

**Comment by MohammadYounes** [comment]
This is has nothing to do with the container class, as I might use different components of Semantic without using the container class.

**Comment by VSG24** [comment]
Then you're probably doing it wrong.
