### ISSUE TITLE
[Form] Add Labels to Fields

### ISSUE THREAD

**Issue by salarmehr** [Semantic-Org/Semantic-UI#3920]
In search/filter forms, usually it is needed to allow user to choose a range. It is not clear from examples how to place a word/symbol between fields. May you please add such example to the docs. 

![1395-01-25 07_50_11-start](https://cloud.githubusercontent.com/assets/2582036/14482145/c3a22dc6-014e-11e6-82b9-460f9ab541a9.jpg)
or
![image](https://cloud.githubusercontent.com/assets/2582036/14482166/1d9eca82-014f-11e6-83a4-80e419efa73f.png)

**Comment by jlukic** [comment]
I've implemented something like this in my private usage of SUI, but havent brought it into the main lib. `labels` between fields are quite effective.
