### ISSUE TITLE
compressed / uncompressed files fail during build

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3921]
Hi, I wanted to try electron and did a new fresh install.

Though once I tried to execute gulp build I encountered an error during the compressed / uncompressed build variants of semantic-ui.

Using: 4a8eef36deedfafec3f488f93666ad9531ca2a79

Resulting error: `TypeError: through.obj is not a function`

log:
[log.txt](https://github.com/Semantic-Org/Semantic-UI/files/217114/log.txt)

My semantic.json:
[semantic.json](https://github.com/Semantic-Org/Semantic-UI/files/217136/semantic.txt)

The single variants work fine.
I installed semantic-ui with this command:
`npm install "git://github.com/Semantic-Org/Semantic-UI.git#next" --save`

**Comment by gizak** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI/issues/3554

**Comment by jlukic** [comment]
For the record I use Semantic UI with meteor/electron and it makes me very happy
