### ISSUE TITLE
Right/Left loss their meaning

### ISSUE THREAD

**Issue by salarmehr** [Semantic-Org/Semantic-UI#3922]
Consider this css file:

```
.float-right {
    float: right;
}
.float-left {
    float: left;
}
```

rtlcss convert that to:

```
.float-right {
    float: left;
}
.float-left {
    float: right;
}
```
As you can see now `.float-right` class make an item left floating. That is not natural and intuitive. It's better to use direction agnostic vocabulary for classes' name. e.g. `.far` and `.near`. far is right in LTR mode and left in RTL direction. 

Keeping old right/left classes make the new vocabulary backward compatible. 

Please also take a look at this: https://stackoverflow.com/questions/12875800/effective-development-and-maintenance-of-large-scale-css-for-multi-language-webs

**Comment by MohammadYounes** [comment]
This conversion is made so you can author one markup and serve both LTR/RTL languages. Changing the class names - in this case - requires different markup for each language direction.

This is explained in details [here](https://github.com/MohammadYounes/rtlcss/wiki/Why-Auto-Rename%3F).

If you look at it from content perspective it would make sense, so `float-right` means float to the right of the content. which in LTR is to your right and in RTL to the screen right :)

**Comment by jlukic** [comment]
This issue has been discussed in a lot of threads
