### ISSUE TITLE
[Dropdown] Examine jQuery 3 Usage

### ISSUE THREAD

**Issue by bersujamu** [Semantic-Org/Semantic-UI#3923]
Try to use jQuery version 3.0.0-beta1, and mouse move on dropdown's item doesn't work at all (whether on `ui dropdown` and `ui search selection dropdown`).

Will give you errors:

- `Uncaught TypeError: s.siblings(...).andSelf is not a function` from `
w.event.keydown` <~~ when moving cursor across items
- `semantic.min.js:13 Uncaught TypeError: n.size is not a function` from `w.event.search.blur` from `
w.forceSelection` <~~ when onblur

Everything is fine if you turn back to jQuery version 2.x.x

**Comment by Briareos** [comment]
This specific function ([`addSelf`](https://api.jquery.com/andself/)) is deprecated and removed in v3 in favor of [`addBack`](https://api.jquery.com/addBack/)

**Comment by jlukic** [comment]
I'll fix jQ 2.x issues today

**Comment by jlukic** [comment]
Fixed in 2afb4d95d201f40fb7ea77cf5d580f1f82c4fb97
