### ISSUE TITLE
[Message] Proposal: Add 'fluid' and change 'compact' behaviour

### ISSUE THREAD

**Issue by sagaio** [Semantic-Org/Semantic-UI#3924]
I propose:
- that a `fluid` class is added to Message to enable full-width and that it by default is only the size of its contents
- that the `compact` class reduces the padding of the Message instead

What do you think?

**Comment by jlukic** [comment]
Messages are typically block. What would be the purpose of fluid?

**Comment by sagaio** [comment]
`fluid` and `compact` are intertwined with each other. If `compact` were to be changed, the `fluid` option would have to be added since there would otherwise not be a way for the Message to become "fit-to-contents" if the Message is `display: block/fluid` by default. Therefor the Message also have to be "fit-to-contents" by default.

Does that make sense?
