### ISSUE TITLE
[Dropdown] multiple level selection not working on mobile

### ISSUE THREAD

**Issue by dragonfire1119** [Semantic-Org/Semantic-UI#3925]
Steps to reproduce:
1. Go to the semantic ui docs on your phone http://semantic-ui.com/modules/dropdown.html#multiple-levels
2. Try to select the Dogs > Poodle > Toy - You should not be able to see it.
3. Try to select the Dogs > Labrador - On mine you can't select it.

Tested browsers:
1. iOS Chrome
2. iOS Safari

iOS Version: 9.3

Chrome Desktop works.

**Comment by danparsonson** [comment]
I too have experienced this problem, on an Android (Marshmallow) phone.

**Comment by jlukic** [comment]
I have heard others describe this problem specifically on Android. I don't have an Android phone for testing (and Chrome emulator does not reproduce) so I have been unable to fix this. 

If anyone wants to donate an old Android phone to fix this e-mail me.
