### ISSUE TITLE
[SOLVED] Tab into a modal and responsivity

### ISSUE THREAD

**Issue by opvini** [Semantic-Org/Semantic-UI#3926]
Hi, I have a tab into a modal.
It works fine, but it is not responsive...
Can you test it?

![image](https://cloud.githubusercontent.com/assets/7398397/14542912/e8ec15aa-0267-11e6-8cf2-b74550365229.png)

![image](https://cloud.githubusercontent.com/assets/7398397/14542922/f93cdf2a-0267-11e6-8fe8-d9b757745c65.png)

**Comment by zxlin** [comment]
post a jsfiddle example

**Comment by opvini** [comment]
Right, sorry...

https://jsfiddle.net/opvini/sen3fdcf/

**Comment by NoSoyTsundere** [comment]
.ui.pointing.secondary.menu -> .ui.pointing.secondary.**stackable**.menu

[https://jsfiddle.net/sen3fdcf/1/](https://jsfiddle.net/sen3fdcf/1/)

This should be on [http://stackoverflow.com/questions/tagged/semantic-ui](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by opvini** [comment]
Thanks a lot @NoSoyTsundere !

**Comment by jlukic** [comment]
Thanks a lot community for helping
