### ISSUE TITLE
Form fields auto stacking on mobile width, chubby theme dropdown overflow

### ISSUE THREAD

**Issue by zayaisshawn** [Semantic-Org/Semantic-UI#3927]
AFAIK, unstackable feature is not implemented in 2.1.8. I'm using less version of sem-ui in meteor. Is there any css solution to keep the form layout as is on mobile. I.e. not automatically stacking on mobile screen. Also there is a weird bug with dropdown menu width in chubby theme.
![capture](https://cloud.githubusercontent.com/assets/7747134/14551085/be30172e-0309-11e6-84b9-0a8f91fc64a4.PNG)
Any workaround for this. Thanks guys.

**Comment by KennyZJ** [comment]
I think it happens not only in mobile env, but also in desktop browser, exactly looks the same. But I didn't find this in official website demo which is in version 2.2.x, so I guess it has been fixed in the latest version.
