### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by TVMax-A** [Semantic-Org/Semantic-UI#3931]
Hello! 

It's not updating and I was not wrong by writing this here!!! 

"Card" adapts to different screens. But if you do not specify a number in the string, then everything is fine. Here see for yourself: http://tvmax.96.lt.

**Comment by TVMax-A** [comment]
**+ I'm using the translator wrote.**

**Comment by jlukic** [comment]
Hi, I'm unable to understand the specific issue as reported. Feel free to open again with a more explicit bug explanation. Please read our contributing guide for an explanation of how to write this effectively

**Comment by TVMax-A** [comment]
In russian and understandable.

Нет адаптации карточек под мобильные экраны.

**Comment by TVMax-A** [comment]
No adaptation cards for mobile screens.

**Comment by TVMax-A** [comment]
?

**Comment by philrykoff** [comment]
Your site seems fine on iPhone. 

Your bug description is not helpful. Which number in which string?

Maybe you can create a fiddle about your issue?

**Comment by TVMax-A** [comment]
Card compressed, in place of having to be distributed. It should not be.

**Comment by lholznagel** [comment]
Please create a fiddle. Maybe we can help you. Also a description would be helpful and not a single sentence

**Comment by TVMax-A** [comment]
Have you tried with mobile on small cards to click? When reducing the diagonal of the monitor, the number of elements in the range should decrease.
