### ISSUE TITLE
semantic-ui-less integration in Meteor 1.3 (modules)

### ISSUE THREAD

**Issue by laurentpayot** [Semantic-Org/Semantic-UI#3933]
Since Meteor 1.3 meteor packages should be installed via npm.
Meteor 1.3.2 has just been released, it is now possible to import _less_ styles from node modules.

But with semantic-ui-less there are errors, described here: https://github.com/meteor/meteor/issues/6037#issuecomment-209330120
This issue was closed on the Meteor side, but maybe there are things to do on the Semantic side for a semantic-ui-less module import working "out of the box"...

**Comment by jlukic** [comment]
Like the poster said, I'm not sure of an actionable change on our end. If there's a specific suggestion on how to change the package feel free to re-open this as a separate issue, but for now I'm at an impasse
