### ISSUE TITLE
Bug with blurring modal with FireFox

### ISSUE THREAD

**Issue by opvini** [Semantic-Org/Semantic-UI#3934]
Hi guys,
I am using a blurring modal, but on Chrome it works fine, but on FireFox, when I open the modal, all the site unconfigures, and it also happens on the semantic site:

http://semantic-ui.com/modules/modal.html#/examples

**Comment by IonutBajescu** [comment]
Works fine on Firefox 45 / OS X.

Could you maybe share with us your browser details and a screenshot of the bug?

![](https://i.imgur.com/qkMHOMq.png)

**Comment by opvini** [comment]
I am using a FF 43.0.1.
I am using a fixed top menu and a fixed footer. When I open a blurring modal, it unconfigures all the elements. If I use a normal modal, it doesn't happen...

**Comment by jlukic** [comment]
I'm not sure there's any actionable bug here.

**Comment by DaSchTour** [comment]
I'm using only the ui-modal JS and CSS and when using bluring in firefox the page is all white.
