### ISSUE TITLE
Rename font-awesome.css to awesome.css

### ISSUE THREAD

**Issue by tuxy** [Semantic-Org/Semantic-UI#3935]
Rename font-awesome.css to awesome.css and awesome.min.css :-)

**Comment by KapuzenSohn** [comment]
Why? What reason is there?

**Comment by tuxy** [comment]
@KapuzenSohn Same idea like semantic.css and semantic.min.css instead of semantic-ui.css :-)

**Comment by jlukic** [comment]
What is this thread. (I love you guys)
