### ISSUE TITLE
[Meteor] Blaze seems to break responsiveness

### ISSUE THREAD

**Issue by cluxter** [Semantic-Org/Semantic-UI#3936]
Hi

I use semantic-ui in Meteor v1.3.1 (latest stable version) and semantic-ui package is up-to-date.

This code works fine:

`<div class="five wide computer twelve wide tablet sixteen wide red column">`
`<div class="ui">Project description: description</div>`
`</div>`

This one doesn't:

`<div class="five wide computer twelve wide tablet sixteen wide red column">`
`<div class="ui">Project description: {{description}}</div>`
`</div>`

The second code keeps displaying the column as five wide when the window width is reduced - when it should extend it.

I don't know if it comes from using the "{{" and "}}" characters or if the interaction with Blaze breaks something in the responsiveness of semantic-ui. Or maybe I missed something else?

Thanks

**Comment by jlukic** [comment]
See https://github.com/meteor/meteor/issues/3628 and https://github.com/meteor/meteor/pull/5753
