### ISSUE TITLE
Search POST Method Instead of GET ?

### ISSUE THREAD

**Issue by tuxy** [Semantic-Org/Semantic-UI#3938]
Is it possible to use .ui.search with POST method instead of GET ? Any examples is appreciated. Thank You!

```html
<div class="ui search">
  <div class="ui left icon input">
    <input class="prompt" type="text" placeholder="Search GitHub">
    <i class="github icon"></i>
  </div>
</div>
```

```javascript
$('.ui.search')
  .search({
    apiSettings: {
      url: '//api.github.com/search/repositories?q={query}'
    },
    fields: {
      results : 'items',
      title   : 'name',
      url     : 'html_url'
    },
    minCharacters : 3
  })
;
```

**Comment by IonutBajescu** [comment]
Have you tried using the "method" option? Like this: 

```js
$('.ui.search')
  .search({
    apiSettings: {
      url: '//api.github.com/search/repositories?q={query}',
      method: 'GET'
    },
    fields: {
      results : 'items',
      title   : 'name',
      url     : 'html_url'
    },
    minCharacters : 3
  })
;
```

**Comment by jlukic** [comment]
Method should have you covered. You can configure any normal API settings, see the api docs for more details.

**Comment by tuxy** [comment]
@IonutBajescu I think I was asking about ''POST'' not GET which is default.

@jlukic There is no POST example that I could find. Can you give an example please ?

**Comment by rizalgowandy** [comment]
We mean, how to put `{query}` on the post parameter?

we have tried this:

```
	$('#search-user')
		.search({
			apiSettings: {
				url: window.location.href,
				method: 'POST',
				data: {
					term: '{query}' // <--- this, but it doesnt replaced like on the `url` param
				}
			},
			fields: {
				results : 'items',
				title   : 'name',
				url     : 'html_url'
			},
			minCharacters : 3
		})
	;


```

**Comment by Banandrew** [comment]
Hi @rizalgowandy, the search component automatically takes an input value and replaces `{query}` in a `url` with it. Here’s an example, see the “Network” tab in your browser’s developer tools to see the request: https://jsfiddle.net/19fb6uLv/

**Comment by tlleech** [comment]
I'm using a "beforeSend" callback function in the apiSettings to modify the data like this: 
https://jsfiddle.net/pkdukdjv
