### ISSUE TITLE
Modal observeChanges doesn't react to accordion

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#3939]
Hi, I was very happy to find the option observeChanges on the modals, it saves a lot of error prone automatized 'refresh' calls

The only problem so far I have encountered is with accordions, I use them a lot within modals, and unfortunately when they open they dont update the modal position (or scrolling), jsfiddle follows:
http://jsfiddle.net/4rnnmm4f/

What is interesting it works when the window is very small from the beginning.
I dont expect observeChanges to be 100% preceise, but this would be a nice improvement.

The refresh works, so I can fix it calling it on accordion opening, but still would be nice to have it out of box. Especially I have found some issues when calling refresh on the model when another is opened behind.

**Comment by jlukic** [comment]
This is unfortunately a limitation of DOM mutation observers. 

They don't update when elements height or offset position change, only if they are removed or inserted. This is a frustrating part of the spec that also affects `visibility` and `sticky` quite dearly.

**Comment by Yrlish** [comment]
I stumbled upon this problem too.

My workaround is to manually add the `scrolling` class to both `body` and the actual modal.

```javascript
$("#my-modal").modal({
  onShow: function() {
    $("body, #my-modal").addClass("scrolling");
  }
}).modal('show');
```
