### ISSUE TITLE
Checkboxes and Radio buttons should support color

### ISSUE THREAD

**Issue by dbachrach** [Semantic-Org/Semantic-UI#394]
You should be able to include colors (and inverted colors) for checkboxes:

Examples:

``` html
<div class="ui gree radio checkbox"></div>
```

or

``` html
<div class="ui inverted green radio checkbox"></div>
```

**Comment by Maxhodges** [comment]
>I could see positive/negative checkbox, but i couldn't imagine other colors to work well UI wise.

Please see square_skin and flat_skin examples here if you have a hard time imagining how colors can work well in UI

http://fronteed.com/iCheck/

**Comment by jlukic** [comment]
These aren't variations these are themes. A colored variation would be so that developers could include both colored and uncolored checkboxes together on the same page.

**Comment by jlukic** [comment]
I've added an example theme in beta, its really only a few lines of code

```less
@checkboxActiveBackground: @primaryColor;
@checkboxActiveColor: @white;
@checkboxActiveBorder: 1px solid @primaryColor;

@sliderOnLineColor: @primaryColor;

@checkboxRadioActiveBackground: @primaryColor;
@checkboxActiveBulletColor: @primaryColor;
```

**Comment by pretentiousgit** [comment]
This could really use an update so we could have, ie:
red-green-blue-purple radio selectors to reflect selected colours in hardware controls (LEDs).

It's pretty tricky to figure out how to add multiple colours of radio buttons to Semantic-UI! I can't work out how to do it without adding a bunch of new components to the library.
