### ISSUE TITLE
[checkbox] Add different sizes

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3941]
We need size variations for checkboxes at least (not talking about toggles) - big, large, very large

**Comment by jlukic** [comment]
Agreed, this is difficult because this is one of the only components sized with `px` due to rounding issues.

**Comment by jamstarter** [comment]
+1

**Comment by onyxg** [comment]
+1

**Comment by dannyweb8** [comment]
+1

**Comment by unutoiul** [comment]
agreed

**Comment by unutoiul** [comment]
agreed, when is gong to be available?

**Comment by vinayakkulkarni** [comment]
Please use the github reactions instead of commenting +1.

Cheers 🥂

**Comment by apijay** [comment]
+1

**Comment by whitebyte** [comment]
Still actual, please reopen

**Comment by jwerardi** [comment]
has anyone found a way to increase checkbox sizes?

**Comment by TheSETJ** [comment]
It's requested in 2016 and it's 2018 now, still nothing?

**Comment by stefanzero** [comment]
I increased the size of a checkbox by adding a CSS rule
.myCheckbox {
  transform: scale(2);
}

**Comment by indrabinridwan** [comment]
2019. still nothing ??

**Comment by YiF-Zhang** [comment]
Adding following CSS rules may help:
```
.checkbox label:before {
  transform: scale(0.5);
}
.checkbox label:after {
  transform: scale(0.5);
}
```

**Comment by lubber-de** [comment]
Fixed for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/886
See https://jsfiddle.net/wtrxjupk/
![image](https://user-images.githubusercontent.com/18379884/61568456-a22ff380-aa83-11e9-9b0b-aa675533bbef.png)
