### ISSUE TITLE
Popup not work right in html5 doctype

### ISSUE THREAD

**Issue by WangJi** [Semantic-Org/Semantic-UI#3942]
The problem is when giving html file a DOCTYPE such as 
```
<!DOCTYPE html>
```
Popup will  show at the bottom of the page, far away from expected.
It seems that the `offsetParent` got a 0 height.

Here is the reproduce [jsbin link](https://jsbin.com/pugalozofo/edit?html,js,output).

Try to **REMOVE** the DOCTYPE, popup will work fine.

**Comment by jlukic** [comment]
You are missing the basic css reset. 

The pertinent rule is 
```css
html, body { 
  min-height: 100%;
}
```

https://jsbin.com/zirecepepa/1/edit?html,css,js,output
