### ISSUE TITLE
[Popup] In menu should render

### ISSUE THREAD

**Issue by skhavari** [Semantic-Org/Semantic-UI#3949]
###### Repro
* see https://jsfiddle.net/mez8xokt/2/ which does the following
* create a menu
* insert an item to display a popup
* wire up the js

###### Expect
* popup should display when trigger element is clicked

###### Actual
* popup doesn't display on click
* however, if you click and then resize the frame the popup becomes visible

`Version 2.1.8`

###### Workaround
* embed content in data-html and remove the popup element

**Comment by jlukic** [comment]
Popups can't operate in every location inside the DOM. 

Try it outside the menu
https://jsfiddle.net/u9n0uLxs/

**Comment by skhavari** [comment]
in case anyone else runs into this ...

looks like adding `position: 'bottom left'` in the js config allows the popup to sit next to the trigger.

https://jsfiddle.net/pbL5uo59/1/
