### ISSUE TITLE
Headers with link always show with link color

### ISSUE THREAD

**Issue by llturro** [Semantic-Org/Semantic-UI#3952]
<h1 class="ui header"><a href="">${title}</a></h1>

renders with link color.

To workaround this, I added this CCS

.ui.header a:not(:hover) {
  color: inherit;
}

Not sure if it's an issue or by design. I reported because ui item's header behave differently, header color when normal and link color when hovered.

**Comment by llturro** [comment]
`<h1 class="ui header"><a href="">${title}</a></h1>`

This was the previous markup :__)

**Comment by jokeronaldo** [comment]
I tought h1 headers, in it's purpose, is made to be a header, not a link. I can't see it as a bug.
Well, an override solve this.

Thank you for report.

**Comment by llturro** [comment]
You're right. Just wondering why headers in ui item behave differently. The situation arises when trying to show the same way a normal header and a ui item header. It happens with any header, not only h1.

Not a big deal.
