### ISSUE TITLE
[Dropdown] Clicking on label won't open dropdown

### ISSUE THREAD

**Issue by voidale** [Semantic-Org/Semantic-UI#3954]
I'm not sure if this is expected behavior but when clicking on selected option label it won't open the dropdown

http://semantic-ui.com/modules/dropdown.html#label
1. select label e.g. "Important"
2. click on the red label 

It will not open the dropdown menu. 
I found this is issue when I tried to have only label as a select option (for color picker).

EDIT: as a workaround i just used my own custom label(span) seems to work. I just wanted to report this if it's possible bug.

**Comment by IonutBajescu** [comment]
Confirmed bug on Chrome 49 - OS X.

**Comment by jokeronaldo** [comment]
Confirmed bug.
