### ISSUE TITLE
[Button] you can interact with loading button even if it's disabled

### ISSUE THREAD

**Issue by voidale** [Semantic-Org/Semantic-UI#3957]
If you disable a loading button, you can still click/interact with it.
1. go to http://semantic-ui.com/elements/button.html#loading
2. add disabled class to a loading button -> can still click on it only only css has changed.

seems like minor change adding !important `pointer-events: none !important;` fixes the problem.

**Comment by Ryuno-Ki** [comment]
@voidale What happens if you add `disabled="disabled"` to the button element? This way, you mark it as *disabled* in HTML and [AT](https://en.wikipedia.org/wiki/Assistive_technology) will handle it correctly, too.

**Comment by voidale** [comment]
@Ryuno-Ki it will work of course, but it's still one line css that can be fixed in future release good to report it :)

**Comment by Ryuno-Ki** [comment]
@voidale Okay, I rephrase the question :-)

Let there be a callback bound to the button's click event.
* If you add `pointer-events: none !important;` and click the event/focus and trigger it via keyboard/touch it, is the callback executed?
* If you add `disabled="disabled"`, does it behave the same? Is the styling correct?

**Comment by avalanche1** [comment]
+1
