### ISSUE TITLE
[Dropdown] if dropdown elements are added dynamically when you clear, there is no placeholder.

### ISSUE THREAD

**Issue by voidale** [Semantic-Org/Semantic-UI#3958]
The issue can be seen clearly here http://jsfiddle.net/rwokkayg/

I'm adding the menu dynamically through blaze (meteor), But i suspect it will be the same result with React and any other framework, cool solution for this could be if we saved a placeholder on the hidden input it will use that? 

Any workaround for this?

Thanks!

p.s if we use `save defaults` and then `restore defaults` it will restore the value, not the placeholder.

edit: hacking it for now with

```
$('.ui.dropdown').dropdown('clear');
$('.ui.dropdown .text').html('Placeholder');
```

**Comment by levithomason** [comment]
Just in case React users end up here looking for a solution, there is now an official Semantic-UI-React project: https://github.com/TechnologyAdvice/stardust

I'll soon port it to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).
