### ISSUE TITLE
Word Order Dependency

### ISSUE THREAD

**Issue by sgarbesi** [Semantic-Org/Semantic-UI#396]
I saw that there are stackable grids but that's not exactly what I'm looking for.

I'm looking to have 3 cols mobile, 6 cols tablet, 12 cols desktop.

Replicating elements that could be manipulated at different browser sizes but are trying to represent the same element would probably hurt performance not just with rendering but when it comes to JS bindings as well?

Ex: I add an element to my favorites, resize my browser, now the element appears not to be in my favorites even though it is.... something like that for example, I would then have to manipulate all 3 elements instead of 1? :/

Just throwing the concern out there. Is there anyway for me to achieve what I'm looking to do with this library. I'm a fan, the UIs pretty slick, and there's a lot of features. But for me to switch over from Bootstrap I at least need the same functionality :/

For example with bootstrap I would do this to achieve what I'm looking to do:

``` html
<div class="col-sm-3 col-md-6 col-lg-12">blah 1</div>
<div class="col-sm-3 col-md-6 col-lg-12">blah 2</div>
<div class="col-sm-3 col-md-6 col-lg-12">blah 3</div>
...etc...
```

**Comment by Isigiel** [comment]
I have Angular.js dynamically changing the column counts, but it doesn't work as angular puts the updated class always on last spot. This is an issue only cause by the word order thing.
I don't really want to change all the source stuff, especially when where will be updates and I'd have to apply my changes again.
It'd be great to find a way of keeping the sematics and being able to modify classes.
