### ISSUE TITLE
Transition: Element is no longer attached to DOM. Unable to animate.

### ISSUE THREAD

**Issue by swordling** [Semantic-Org/Semantic-UI#3960]
I'm unable to make a popup appear when hovering on an item. I'm trying to mimic the second demo of the menu collection. 

Here is my code: (Using Jade)
```
nav
      .ui.text.menu
        .item
          img(src='images/new-school.jpg')
        a.browse.item Browse Courses
          i.material-icons arrow_drop_down
      .ui.special.popup
        .ui.three.column.relaxed.divided.grid
          .column
            h4.ui.header Business
            .ui.link.list
              a.item Design & Urban Ecologies
              a.item Fashion Design
              a.item Fine Art
              a.item Strategic Design
          .column
            h4.ui.header Liberal Arts
            .ui.link.list
              a.item Anthropology
              a.item Economics
              a.item Media Studies
              a.item Philosophy
          .column
            h4.ui.header Social Sciences
            .ui.link.list
              a.item Food Studies
              a.item Journalism
              a.item Non Profit Management
```
```
var initialize = {
  popup: function() {
    $('nav .menu .browse').popup({
      popup: '.special.popup',
      inline: true
    });
  }
}
initialize.popup();
```

And I'm getting this in the console:
`semantic.min.js:17 Transition: Element is no longer attached to DOM. Unable to animate. scale in 
`
AtDhVaAnNkCsE

**Comment by swordling** [comment]
I was able to fix it. It turns out you cannot use the 'Amazon' theme under the transitions variable in the themes.config file. Changing that back to default fixed it.

**Comment by catimos** [comment]
it works @swordling

**Comment by BoleLee** [comment]
@swordling Would you mind telling me where the themes.config file is. I have the same problem like you when I use the semantic popup and swiper.js together. I use the semantic by semantic-ui-sass. Any tips would be appreciate.

**Comment by mdhtr** [comment]
I wanted to understand why setting a custom theme with missing definitions to all components worked for some components but not for others.  (i.e. it works for accordion, but not nor transitions)
I found the reason [here](http://learnsemantic.com/themes/overview.html#overrides-in-practice). The point is, that if you set a component to a custom theme, the overrides are not inherited from the default theme.
For components that do not have any overrides in the default theme, setting them to a custom theme can work just fine. However if there are overrides in the default theme for that component then they are ignored when the custom theme inherits from the default. And this is the case with Transitions. All the cool transitions are defined as overrides in the default theme. Even the ones that are used by i.e. accordion natively.

**Comment by tarvos21** [comment]
@BoleLee, the `theme.config` file is in `semantic/src/` directory, if you still need it.

@mdhtr, your explanation is great to understand the problem, thanks a lot, I got confused by this problem today.

**Comment by lukesnowden** [comment]
Occurs when transition.css is not being loaded in

**Comment by Enelar** [comment]
@lukesnowden you just saved my day!

**Comment by timkelty** [comment]
Seems like a bug that not including css triggers a js error, no?

**Comment by Steveb-p** [comment]
Happened to me as well when including default-themed components. Error is quite misleading :/

**Comment by CaddyDz** [comment]
@lukesnowden Thanks man
![image](https://user-images.githubusercontent.com/13698160/47954731-edee4b80-df8d-11e8-9384-278c037c381f.png)

**Comment by skwny** [comment]
I am experiencing this as well. All themes are default and transitions css is available.
