### ISSUE TITLE
Layout Pages

### ISSUE THREAD

**Issue by FingersKey** [Semantic-Org/Semantic-UI#3961]
Hello, I am a user from China, Can you add some backend layout? http://www.semantic-ui.cn/usage/layout.html
Thanks ~!

**Comment by IonutBajescu** [comment]
What exactly does `backend layout` mean in the context of a front-end framework?

**Comment by FingersKey** [comment]
Sorry~!  My English is not very good !    Similar to the layout of the Administrator Console

**Comment by IonutBajescu** [comment]
Could you please show us an example of a backend layout?

**Comment by FingersKey** [comment]
![image](https://cloud.githubusercontent.com/assets/15059533/14907985/ba73e6e8-0e02-11e6-8453-43e27378b7cd.png)
Like this

**Comment by moxet** [comment]
He is asking for examples, some demo modules setup in semintic UI which can easily be copy paste in projects.

**Comment by FingersKey** [comment]
yes! thank you for your help!

**Comment by moxet** [comment]
@FingersKey you can easily copy the structure of a site (built in Semintic UI) using firebug or view source option. It will give you static html just refine the tags and that's it.
