### ISSUE TITLE
Is Holygrail layout possible in Semantic-UI without adding custom styles?

### ISSUE THREAD

**Issue by AdityaDinesh** [Semantic-Org/Semantic-UI#3962]
We are exploring semantic ui for our web based project in which we are trying to create a holy grail layout to suit our dynamic content. Below is a neat example using flexbox but want to see if semantic ui can be used to achieve this. Any examples would be helpful.

https://philipwalton.github.io/solved-by-flexbox/demos/holy-grail/

**Comment by IonutBajescu** [comment]
Choosing a framework as Semantic UI only for its layout system doesn't sound like a good idea to me. 

Anyhow, as far as I know you will need custom styles at least for the *stickish* footer. 

By the way, as this is an usage question maybe you'd have more luck if you posted on the semantic ui forum? http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI

**Comment by AdityaDinesh** [comment]
Thanks @IonutBajescu
