### ISSUE TITLE
[Form] X Fields Wrapping

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#3963]
On older versions of Semantic UI (I am upgrading from 1.x) you guys had rules so if I did `<div class="three fields">` with 5 fields it would auto wrap the last two to the next line.  With 2.1.7 this does not appear to be the case.  I see you guys switched to using flexbox for the fields, so it was fairly simple to fix on my end:

```

.ui.form .fields {
  flex-flow: row wrap;
}
```

The issue and fix is trivially shown here: http://jsfiddle.net/daneren2005/dmqct3zs/1/

**Comment by IonutBajescu** [comment]
The bugfix has a padding glitch: ![](https://i.imgur.com/7cZoXrm.png)

**Comment by daneren2005** [comment]
Here is a new jsfiddle with that fixed: http://jsfiddle.net/daneren2005/dmqct3zs/3/.  I guess my point was less to provide an exact fix and more to point out the starting place of how to fix it.  If I remember correctly that is how Semantic UI used to do it because I first learned about nth-child selectors from looking at the css Semantic output.

**Comment by daneren2005** [comment]
So is this going to be fixed or should I just add this bug fix locally?

**Comment by IonutBajescu** [comment]
For now please just fix it locally. It could take a while until a bugfix makes its way into a stable release.
