### ISSUE TITLE
Don't use $('.ul.dropdown') in the React integraiton example

### ISSUE THREAD

**Issue by DelvarWorld** [Semantic-Org/Semantic-UI#3964]
From this page:

http://semantic-ui.com/introduction/integrations.html

```js
  componentDidMount() {
    $('.ui.selection.dropdown').dropdown({
```

This is not something you should encourage newcomers to do. Using refs and `ReactDOM.findDOMNode` is the correct way to access your DOM nodes after render.

Further reading: https://github.com/ryanflorence/react-training/blob/gh-pages/lessons/05-wrapping-dom-libs.md

**Comment by IonutBajescu** [comment]
Agreed, referencing the selector manually is not the React way.

You can do the required changes yourself if you want, that example is stored in a jsfiddle you can find here https://github.com/Semantic-Org/Semantic-UI-Docs/edit/master/server/documents/introduction/integrations.html.eco

**Comment by jlukic** [comment]
I'd update the jsfiddle link if someone wants to recommend a different example.

**Comment by levithomason** [comment]
@DelvarWorld @IonutBajescu and any others landing here, there is now an officially supported Semantic-UI-React project that implements components in the React paradigm without jQuery: https://github.com/TechnologyAdvice/stardust

I'll soon port it to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).

Cheers
