### ISSUE TITLE
let is not supported on Safari

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3967]
Using the keyword `let` results in following error on Safari:
`Unexpected use of reserved word 'let' in strict mode`

Fixed with pull request #3966 by replacing `let` with `var`. So far I haven't encountered any errors.

**Comment by HitomiTenshi** [comment]
Merged with 2599f7185a9da255e799233548d7b2720a565c74

**Comment by mcrawshaw** [comment]
I have found 4 more of these in my bundle.js generated from next branch.

**Comment by HitomiTenshi** [comment]
Are you sure you are using the latest code from the next branch?

**Comment by HitomiTenshi** [comment]
I just searched the whole project folder of the latest next code for a let keyword and it found 4 occurrences as you said.

All of them aren't relevant as those are actual words located in the readme and some other places.

I shouldn't have opened the issue so quick without checking, sorry. Closing it again.

**Comment by jlukic** [comment]
No worries, thanks Hitomi
