### ISSUE TITLE
[grid] Columns wrapping

### ISSUE THREAD

**Issue by andrew-anguiano** [Semantic-Org/Semantic-UI#3968]
I'm trying to create a three-column grid, however I seem to be having issues. The third item in the row always wraps. See this fiddle: http://jsfiddle.net/g860oyq6/

I saw someone having a similar problem on issue #719 but their solution didn't seem to work for me.

Any ideas?
Thanks!

**EDIT:** I've found that the issue occurs any time the columns add up to 16. If I have them add up to 15, I don't experience the wrapping issue. I've downloaded the Grid component directly from semantic-ui.com and am still seeing the problem (I thought maybe the bower package was outdated or something).

**Comment by IonutBajescu** [comment]
In you want to use only the grid component you'll have to set the box sizing yourself, as demonstrated here: http://jsfiddle.net/g860oyq6/3/
```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

Or you can import the 'reset' component. I'd recommend the second approach, but use whichever you like.

**Comment by andrew-anguiano** [comment]
@IonutBajescu Fantastic! That fixed it. Is there any way to mention that in the docs? I feel like it'd be helpful to know what "dependencies" are needed for the individual components to work correctly.

**Comment by IonutBajescu** [comment]
@andrew-anguiano Yeah, we could try sending a pull request to https://github.com/Semantic-Org/Semantic-UI-Docs. I'm sure @jlukic will be okay with adding a short note about dependencies in the docs.

Maybe you can give it a shot?

**Comment by andrew-anguiano** [comment]
Will do. Thanks!  
  
![](https://link.nylas.com/open/14fi1keme4o90tzzkelvwp7wv/local-6f07cdd5-ce11)

On Apr 27 2016, at 11:53 am, Ionut Bajescu &lt;notifications@github.com&gt;
wrote:  

> [@andrew-anguiano](https://github.com/andrew-anguiano) Yeah, we could try
sending a pull request to <https://github.com/Semantic-Org/Semantic-UI-Docs>.
I'm sure [@jlukic](https://github.com/jlukic) will be okay with adding a short
note about dependencies in the docs.

>

> Maybe you can give it a shot?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com
/Semantic-Org/Semantic-UI/issues/3968#issuecomment-215128163)![](https://githu
b.com/notifications/beacon/AROHnzNHaCxehpIKvGCWLUMW8WZrCJgiks5p74ZagaJpZM4IQIp
e.gif)

**Comment by Ryuno-Ki** [comment]
@andrew-anguiano FYI: As GitHub support confirmed me, Markdown is not supported in e-mail replies to issue notifications.
