### ISSUE TITLE
Input overlaps dropdown in a shape

### ISSUE THREAD

**Issue by Dyd0u** [Semantic-Org/Semantic-UI#3970]
Hello, I found a bug with the dropdown.

When you create a dropdown within a shape and there is an input after this shape, the input overlaps the opened dropdown menu.

Here is an example:
![dropdown](https://cloud.githubusercontent.com/assets/12045244/14868925/9dfc3304-0cd0-11e6-8664-d794c3fb0f64.png)
https://jsfiddle.net/fd9b57s3/8/

Can you fix it please ?

**Comment by avalanche1** [comment]
Quickfix: add z-index to dropdown menu.

**Comment by Dyd0u** [comment]
Hi, I already tried to add _z-index_, but it's not working, and if I add a _position_ attribute, it does not look like as expected :

<img width="212" alt="dropdown" src="https://cloud.githubusercontent.com/assets/12045244/14941685/d1cd3b5c-0fa4-11e6-806d-c4d8f6bd4341.png">

**Comment by avalanche1** [comment]
Ah, yes, it's 3-dimensional, so z-index wont help. Lets' wait for Jack's review

**Comment by IonutBajescu** [comment]
It would make more sense to attach the z-index directly to the shape.


Try this for example until we find a more elegant solution: https://jsfiddle.net/fd9b57s3/9/

**Comment by jlukic** [comment]
Shape uses `perspective` which adds a 3d context. 

This will have stacking issues but is necessary for it to correctly calculate 3d transitions.

Simple fix while inactive as `perspective: none;`
https://jsfiddle.net/25yL2nyh/
