### ISSUE TITLE
Loading icon spins off-center when placed in a button

### ISSUE THREAD

**Issue by jwr** [Semantic-Org/Semantic-UI#3971]
A loading icon, when placed inside an icon button, spins off-center, thus moving up and down. I expected it to spin without moving, just like when placed outside of a button.

http://jsfiddle.net/jrychter/6zmy5mfa/1/

**Comment by avalanche1** [comment]
Follow this up in https://github.com/Semantic-Org/Semantic-UI/issues/2271

**Comment by avalanche1** [comment]
I can reopen this if @jlukic reviews this as a bug. Or you can submit a PR

**Comment by cquiroz** [comment]
I'm observing this same effect for icons not in a button. Was this ever worked out?

**Comment by lubber-de** [comment]
We finally fixed this. See here http://jsfiddle.net/bztsj9wm/3/
