### ISSUE TITLE
Input issue in modal

### ISSUE THREAD

**Issue by KhadeerUi** [Semantic-Org/Semantic-UI#3972]
Hi,
This is khadeer,

When i am adding input in modal, Ex: if is there content more then window height, then add input content bottom after issue is there. when i am opening modal directly focus on input place if any type of input.
I am using semantic-ui 1.12.2 framework

**Comment by IonutBajescu** [comment]
Looks more like an usage question. 

If that's right, please repost your issue on the projecttalk forum and read the [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).
 
http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI

**Comment by avalanche1** [comment]
You should use the latest version of SUI and provide a test case.

**Comment by KhadeerMojostreet** [comment]
Hi avalanche1,

In latest version also this problem is there.

**Comment by jlukic** [comment]
Settings to the rescue. This weeks edition `autofocus`
http://jsfiddle.net/zrk3cfm8/
