### ISSUE TITLE
[suggestion] Class reference. 

### ISSUE THREAD

**Issue by salarmehr** [Semantic-Org/Semantic-UI#3977]
Providing a page to show use case of each class is really useful. It may be possible to generate such page by extracting comment from `less` files (perhaps by using cssdoc tools e.g. https://github.com/SC5/sc5-styleguide or http://warpspire.com/kss/)

**Comment by avalanche1** [comment]
Nice idea. Post it in https://github.com/Semantic-Org/Semantic-UI-Docs/issues.
