### ISSUE TITLE
Internet Explorer 8

### ISSUE THREAD

**Issue by sean-f** [Semantic-Org/Semantic-UI#398]
Hi,

I have been investigating this wonderful library and I am very keen to use it in some future products.  Unfortunately, it does not appear to support IE 8 which is still very much in use in the Corporate environments I deal with.  Can you please advise if you are likely to support version 8 and, if not, if any changes are likely that will at least make it render in a more usable fashion than it currently does (see screenshot)

Many thanks

Sean :-)

![image](https://f.cloud.github.com/assets/6086591/1656233/c293d934-5b6f-11e3-8676-be7bdfa2a0bd.png)

**Comment by zhangfisher** [comment]
<script src="/assets/javascript/elements.rem-polyfill.js"></script>
    <script src="/assets/javascript/elements.html5shiv.js"></script>
    <script src="/assets/javascript/elements.html5shiv-printshiv.js"></script>
    <script src="/assets/javascript/elements.selectivizr-min.js"></script>
    <script src="/assets/misc/css3pie/PIE_IE678.js"></script>

Where download???

**Comment by Anachron** [comment]
Beginning with next year Microsoft will not support IE8 anymore:
http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx?utm_medium=referral&utm_source=pulsenews

**Comment by jlukic** [comment]
2.0 will not support IE9 either
