### ISSUE TITLE
Eliminate Dependency on jQuery - Tasklist

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3981]
- [ ]  Create a list of all jquery functions SUI uses on the left and their modern alternatives on the right.
- [ ] next task

**Comment by The-Penultimate-Defenestrator** [comment]
Looks good. We can probably start with http://youmightnotneedjquery.com

**Comment by avalanche1** [comment]
I'm only a user of a few modules, not an active contributor. Jack is the expert here.

**Comment by henri-hulski** [comment]
It could be worth looking what @hallister and @asvetliakov have done for eliminating the jQuery dependency in [semantic-react](https://github.com/hallister/semantic-react). 
There is also an interesting discussion about replacing jQuery with React based modules at jessy1092/react-semantify#20.

**Comment by hrstoyanov** [comment]
I was talking to @jlukic before about dropping jQuery from SUI ... it is basically not going to happen. The JS module code is heavily dependent on jQuery. I learnt to live with it.

**Comment by Ryuno-Ki** [comment]
What about migrating to [jqLite](https://docs.angularjs.org/api/ng/function/angular.element) first?

This way, the first step would be to replace DOM accessors. Angular users would benefit from it I guess.

**Comment by SzymonSasin** [comment]
Problem with migrating to jqLite is that it is possible to hit the problem of missing implementation. 

It migth not be the easies but moving to vanila js or maybe TS(my preference) seems like a proper way.

**Comment by avalanche1** [comment]
@SzymonSasin what's `TS`?

**Comment by lholznagel** [comment]
I think TypeScript

**Comment by levithomason** [comment]
Adding our React implementation to this list, Stardust :)  My previous comment on a related thread:

>At TechnologyAdvice we are using https://github.com/TechnologyAdvice/stardust in production.  We have 6 humans and 2 robots working on it so far.  I spend the majority of my day job on Stardust.
>
>I am rewriting the modules without jQuery.  We first tried to keep SUI DOM manipulations in sync with  React state through each of the library's lifecycle methods, in the end, this just was not realistic.
>
>I've rewritten the Dropdown with selection, search, and complete keyboard navigation.  You can [**try it out here**](https://technologyadvice.github.io/stardust/#Dropdown-Content-AsyncOptions).  I will continue to move forward with all other modules as well.  If any one is interested in assisting, let me know.

**Comment by SzymonSasin** [comment]
@avalanche1: I mean typescript, I have edited my previus post.

@levithomason: it is great, but what is a point of moving from jQuery to React? People which are using any other framework than React might have problems. I think that possible solution is to add a thin layer to allow the use of differenet frameworks, similair solution to angular ones.

**Comment by levithomason** [comment]
My comment was in regard to https://github.com/Semantic-Org/Semantic-UI/issues/3981#issuecomment-216186917

>It could be worth looking what @hallister and @asvetliakov have done for eliminating the jQuery dependency in semantic-react. 
>There is also an interesting discussion about replacing jQuery with React based modules at jessy1092/react-semantify#20.

For those looking for a React implementation of SUI.  Since no matter the choice of JS SUI uses for DOM manipulation, it will always be incompatible with React's virtual DOM.

**Comment by asvetliakov** [comment]
@levithomason Glad you're going fine with stardust :smiley:

**Comment by italomaia** [comment]
Moving to "react" would be kind of bad for a lot of people. 
@Assassyn one could also use Flow instead of TS, which is less intrusive.

**Comment by levithomason** [comment]
To clarify, the React components are not intended to help non-react apps.  They are required for React apps as vanilla JS and jQuery DOM manipulations do not work in React.

**Comment by alanguir** [comment]
Maybe something tiny like https://umbrellajs.com/ (I'm not affiliated) could handle this. Umbrella is mostly jQuery compatible, and would not also bring on the pain of recreating everything jQuery had been doing. 

@franciscopop - any interest?

**Comment by franciscop** [comment]
@alanguir thanks for proposing my library and yes, I'd be really interested. Though I have to ask first, **what is the reason to remove jQuery**? And is jQuery available for people using the library or just used internally?

The codebase is really modular though many modules are tightly coupled (to optimize for size) so you could just remove some parts if they are not needed. It stands at **3kb min+gzip** right now. Some functions might also be missing so if it makes sense I'd be willing to implement them inside umbrella or as a separate file.

PS, great work with Semantic UI, I have known it for a while and I love it

**Comment by italomaia** [comment]
As chamadas ao jquery no semantic são estas:

1. $.Deferred,
2. $._data,
3. $.address,
4. $.ajax,
5. $.api,
6. $.contains,
7. $.cookie,
8. $.data,
9. $.each,
10. $.easing,
11. $.events,
12. $.expr,
13. $.extend,
14. $.grep,
15. $.inArray,
16. $.isArray,
17. $.isEmptyObject,
18. $.isFunction,
19. $.isPlainObject,
20. $.isWindow,
21. $.merge,
22. $.removeCookie,
23. $.site,
24. $.tab,
25. $.test,
26. $.trim,
27. $.visit,
28. $.when

It also uses $.fn a lot.
