### ISSUE TITLE
Font Awesome 4.6 support

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3982]
When can we hope to see it?
And is there a way to add a couple of missing FA icons to my proj manually?

**Comment by jlukic** [comment]
Font Awesome 4.5 support is in `2.2` unfortunately they have released yet more icons in `4.6` hard to keep up.

You an add them pretty easily in `site/elements/icon.overrides` see format in `default/elements/icon.overrides`

**Comment by IonutBajescu** [comment]
Let's ping the fonts master! 😃 cc @BreadMaker

**Comment by BreadMaker** [comment]
Roger, on it!

**Comment by BreadMaker** [comment]
There you have it! #3984

**Comment by avalanche1** [comment]
Thats awesome - cant wait to use it!
