### ISSUE TITLE
Translation of Chinese (Taiwan) is messed up and cannot be changed.

### ISSUE THREAD

**Issue by YamiOdymel** [Semantic-Org/Semantic-UI#3987]
I was editing the translation of Chinese (Taiwan), 

because some of them (**almost all of them**) were wrong.

--

For example:

some one used a **bad word** for 'Approve' (it should be '同意')

<img width="553" alt="2016-05-03 10 28 59" src="https://cloud.githubusercontent.com/assets/7308718/14986423/738b2e10-117e-11e6-8951-c2e894617b17.png">

and it's even **reviewed by a Chinese guy**, at this situation, **I can't change anything**,

I was wonder if there's any chance to take out all of the translated string of `Chinese (Taiwan)`

so I can make a fully and complete translation for `Chinese (Taiwan)`, thanks.

**Comment by jlukic** [comment]
@YamiOdymel Please email me at jack@semantic-ui.com I can help set you up with an admin account on Transifex so you can administer the translation. 

I'm sorry about the rudeness but unfortunately I'm unable to interpret the translations.

**Comment by jlukic** [comment]
@YamiOdymel I've added you as a coordinator for the language, you should have full access to review and modify existing strings.

If translation text gets stale feel free to PM me so that I can publish them

Thank you for your time and effort, you rule.

**Comment by YamiOdymel** [comment]
@jina I'm really appreciated for what you did, and I spotted another problem #4050,

there's too many 'untranslatable' strings, and I checked for other languages, 

they can't translate those strings too, hope you guys can fix it soon :D

**Comment by jina** [comment]
I don't think you meant to tag me in this

**Comment by YamiOdymel** [comment]
I don't know when to use tag, sorry
