### ISSUE TITLE
Popup closes incorrectly on touch in W10/IE11

### ISSUE THREAD

**Issue by dwightbcoder** [Semantic-Org/Semantic-UI#3990]
I have a popup with buttons in them and settings:
`{
	on: 'click',
	exclusive: true,
	preserve: true,
	hoverable: true,
	hideOnScroll: false
}`

In Windows 10/IE11 using a Touch interface tapping the buttons causes the popup to close.

Android/iOS behave correctly and keep the popup open.

**Comment by jlukic** [comment]
Can you provide a specific JSfiddle so i can test and fix.
