### ISSUE TITLE
Multiselect dropdown different behavior on return key vs mouse click

### ISSUE THREAD

**Issue by groeneveld91** [Semantic-Org/Semantic-UI#3991]
Wondering if this is expected behavior, it has confused some people I've been working with. https://gfycat.com/VillainousRectangularAldabratortoise

Notice when I mouse click on the selection, it keeps the text that I entered "af" as well as creating the label "African Elephant". However when I navigate down with my arrow key and press the return key it removes the text I entered and only shows the label in the input field (this is ideal). If this is expected behavior so be it, just looking for some clarity. Thanks! And Semantic UI is the bomb. Thanks so much for building it, such a game changer.

**Comment by jlukic** [comment]
This was actually intentional. If you jumped up to the menu with your cursor my thought was you'd probably be clicking more than one entry that appears in that list.

**Comment by groeneveld91** [comment]
OK thanks. Do please note that "enter" and arrow keys are not options when user is on mobile.
