### ISSUE TITLE
Animated button without widget.js

### ISSUE THREAD

**Issue by michalproch** [Semantic-Org/Semantic-UI#3993]
Hi, when I click on my IPad or IPhone on the animated button, with included "https://platform.twitter.com/widgets.js"  script everything works fine, but without script fails the animation. There is not any problem at another devices.

Not work:
`
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Example</title>
<link rel="stylesheet" type="text/css" class="ui" href="http://semantic-ui.com/dist/semantic.min.css">
</head>
<body>
  <div class="ui animated button">
    <div class="visible content">Horizontal</div>
    <div class="hidden content">
        Hidden
    </div>
  </div>
</body>
</html> 
`

Work:
`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Example</title><script src="https://platform.twitter.com/widgets.js" id="twitter-wjs"></script>
<link rel="stylesheet" type="text/css" class="ui" href="http://semantic-ui.com/dist/semantic.min.css">
</head>
<body>
  <div class="ui animated button">
    <div class="visible content">Horizontal</div>
    <div class="hidden content">
        Hidden
    </div>
  </div>
</body>
</html>`

**Comment by subrt** [comment]
without twitter http://jsfiddle.net/dscp2eo3/3/

with twitter http://jsfiddle.net/fLyL7xke/1/

**Comment by jlukic** [comment]
Pretty confused here. What does button have to do with Twitter JS APIs?

Also @subrt both your jsfiddle appear the same to me. Is that expected?

**Comment by michalproch** [comment]
@jlukic Please try both codes on your iPhone or iPad.

**Comment by subrt** [comment]
@jlukic 
> Pretty confused here. What does button have to do with Twitter JS APIs?

It does make the animation on the button work for iPad/iPhone. The thing is the documentation does contain twitter js api 
![twitter](https://cloud.githubusercontent.com/assets/371008/15423609/9daeb952-1e7e-11e6-9da6-261d748fd163.PNG)

the jsfiddle is different. one does include https://platform.twitter.com/widgets.js and one does not. you need to test that in safari and look for animation happening/not happening. we use browserstack for testing if you cannot repro the issue, we can do some time line capturing with debug so you can see the twitter js clearly interfering
