### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by ckocer** [Semantic-Org/Semantic-UI#3995]
Hi there. I've a form inside a MODAL. I want to submit this form via your API (for not to redirect page to form's target page).

I thnik there is an issue about using your api inside .click() method.
IF form is INVALID and i click the submit button, form says that fill the fields which is OK.
IF i fill the fields and validate the form then click the submit button, form IS NOT submits itself. I have to click TWICE to make it work

http://jsfiddle.net/hyncp66g/6/

**Comment by HerrAusragend** [comment]
1. the `.form()` method has no `serializeForm'` attribute (see http://semantic-ui.com/behaviors/form.html#/settings)
2. Try changing the 
`$("#btn-do-subscribe").click(function(){` to 
`$("#btn-do-subscribe").on('click', function(){`

**Comment by ckocer** [comment]
I've made the change. but result is the same. what am i doing wrong here :S

**Comment by dwightbcoder** [comment]
A few things in your example should be done differently, I believe.

First, try making your modal the form itself <form class="ui modal form">

You can attach the api directly to the form, without the need to wrap it in a function. This will cause the api to run when the form is submitted and it will automatically send the form data to the api endpoint (iirc).

**Comment by dwightbcoder** [comment]
Here's an example of what I was talking about:
http://jsfiddle.net/60y4y8hf/10/
