### ISSUE TITLE
html5 video and css

### ISSUE THREAD

**Issue by brackmayhall** [Semantic-Org/Semantic-UI#3996]
Hi all,

I have .mp4 links i would like to play. When I place these in a normal html5 video tag I run into css issues while using semantic-ui. Does anyone know how to properly format html/css in order to have html5 videos responsively adjust size?

side note: i have checked out the pull request:2230 but it was never merged and work on it looks like it was stopped around July of 2015.

Thanks,
Brackston

**Comment by jlukic** [comment]
It's a lot of work to handle a native video player. I havent started this undertaking and the PR to add this was not fully completed to the point where I felt comfortable merging it.

**Comment by jlukic** [comment]
#2230
