### ISSUE TITLE
[API] PUT Method fires twice

### ISSUE THREAD

**Issue by romanzipp** [Semantic-Org/Semantic-UI#3997]
In my application I have a form which adds a new User (Talent) to relation DB with a Name as unique index via the HTTP `PUT` method:

```javascript
$('form[data-action="talent-add"]').api({
	method: 'PUT',
	url: 	'/pool/talents',
	serializeForm: true,
	onSuccess: function(response){
		console.log(response);
	},
	onFailure: function(response) {
		console.log(response);
	},
});
```

```html
<form class="ui form" data-action="talent-add">
	<div class="field">
		<label>Name</label>
		<input type="text" name="name" placeholder="Name">
	</div>	
	<div class="field">
		<button class="ui button submit primary">Add Talent</button>
	</div>
</form>
```

But after hitting the `<button>` or pressing `[Enter]` I will get a SQL Duplicate Entry response (SQL Exceptions will be catched).
In conclusion, I think the `.api()` method fires twice, maybe with HTTP `OPTIONS` method?

In my backend I have configured [php-slim](https://github.com/slimphp/Slim) for handling requests:
```php
$app->put('/pool/talents', function() use ($app){
    # magic
});
```

**Comment by jlukic** [comment]
I'm not seeing this occur
http://jsfiddle.net/w7y2bmeg/
