### ISSUE TITLE
Message icon glitch during the transition

### ISSUE THREAD

**Issue by mikemix** [Semantic-Org/Semantic-UI#3999]
https://jsfiddle.net/y5x2c42d/

The icon in the icon message is moving during the transition lol. Happens in FF 46.0.1, IE 10, Chrome 50. Haven't tested in other browsers. Everything is working fine if I wrap the message with a div for instance and shake that wrapper instead. Is this expected to happen?

**Comment by Ryuno-Ki** [comment]
jQuery adds the following classes to the containing div while animating: `animating transition bounce`.

After comparing their CSS effects, I found `.visible.transition` setting `display: block !important` twice (transition.css:55 and semantic.css:32971). This overwrites `display: flex` for `.ui.icon.message` in semantic.css:21995 resp. `.ui.icon.visible.visible.visible.visible.message` in semantic.css:21933.

**Comment by jlukic** [comment]
It's fine without the `visible` class
https://jsfiddle.net/bc262x2d/
