### ISSUE TITLE
More Specification Information 

### ISSUE THREAD

**Issue by olekukonko** [Semantic-Org/Semantic-UI#4]
i want to say well done ... Good Job  :+1:  I think it would be nice to add more specification such as 
- Supported Browser
- CSS version 
- Possible Dependency (eg HTML5)
- Mobile Compatibility
- Performance 
- etc

**Comment by tmsimont** [comment]
http://www.theie8countdown.com/

still 11% in North America... that's a lot. 

As much as I'd love to ditch IE8 I can't just tell clients to forget about 1 in 10 of their user base. This is unfortunate and is probably a deal breaker for Semantic.

**Comment by jlukic** [comment]
Those numbers are way off. 

Here's a report of Wikipedia's global traffic share for April 2015
http://stats.wikimedia.org/archive/squid_reports/2015-03/SquidReportClients.htm
IE8 - *1.38%*
IE9 - *1.38%*

W3C Also is even lower
http://www.w3schools.com/browsers/browsers_explorer.asp
IE8 - *1.0%*
IE9 - *1.4%*

**Comment by tmsimont** [comment]
On a site I'm working on, Google Analytics reports 5% of the daily users are IE8. Out of 20,000 hits per day, that's about 500. I can't ignore 500 visitors each day.

Do you have any suggestions on how to hack together an IE8 fix? Or is this too hopelessly far away from IE8 support?

**Comment by jlukic** [comment]
In `2.0` we are moving many components to flexbox which is not supported below IE10. So this might not be an adequate framework for your current needs. 

The way I think about it, is if the framework can add more than 5% value over your current site, then it is a *net positive* over using a framework which supports older browsers. 

Google has the same policy, supporting only the last and previous versions (IE11-10) of major browsers
https://support.google.com/a/answer/33864?hl=en

**Comment by tmsimont** [comment]
OK, thanks. 

Google's primary function and widest reach is its search engine. They certainly support IE6-8 in their search engine, even if some features don't work. Their modern google apps (drive, calendar, gmail, etc), however, are different, so they don't need to support every browser. But, gmail still works in IE8, even if there are some error messages.

I'd say that Semantic is a fine framework for modern apps, but is not something you'd want to use for a marketing site that is supposed to be accessible by all.

It's been a fun ride with Semantic but I think this is where I have to say goodbye. Maybe I'll have a use for it in the future. Thanks for the hard work

**Comment by deneuxa** [comment]
I'm using SUI on a very large audience website.

The thing you can do is simply to tell users to install a correct browser as this : 

     

You can include a link to  to the browser you want them to install or to this http://browsehappy.com/?locale=en

In fact I'm not even accepting IE9 on my website

Before I switched to SUI ( a year ago), I had a watch to my analytics, and IE <9  was like 1-2% of my users.

**Comment by tmsimont** [comment]
I suppose it's all about your target audience. I'm working on a site where a large part of visitors are viewing from within corporate networks that have IT departments that are stuck on IE8. It's usually because there is some internal portal that was built for IE 5 years ago. I've seen them. They are terrible and they make my life miserable. I loathe the message that says "Your browser is not supported. We recommend Internet Explorer 8"

**Comment by webyom** [comment]
The marketing share of IE8 in China is 25%, really disappointed.
