### ISSUE TITLE
[Menu] - Missing the js to initialize the dropdown menu

### ISSUE THREAD

**Issue by xfletes** [Semantic-Org/Semantic-UI#4002]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**
The Menu should do this

**Result**
The Menu does not do this

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by IonutBajescu** [comment]
"Duplicate" of #4003.
