### ISSUE TITLE
[Menu] - Missing the js to initialize the dropdown menu

### ISSUE THREAD

**Issue by xfletes** [Semantic-Org/Semantic-UI#4003]
$(document).ready(function(){
  $('.right.menu.open').on("click",function(e){
    e.preventDefault();
    $('.ui.vertical.menu').toggle();
  });
    
  $('.ui.dropdown').dropdown();
});

**Comment by IonutBajescu** [comment]
What exactly is the issue you're encountering?

**Comment by xfletes** [comment]
Into the api docs

http://semantic-ui.com/collections/menu.html

Just copy and paste an example of a menu with dropdown, but it did not work
until I put the js.

Perhaps you could place the menu of "examples", "usage", "settings" like
anothers sections

2016-05-06 16:34 GMT-05:00 Ionut Bajescu <notifications@github.com>:
