### ISSUE TITLE
select dropdown return 2 value

### ISSUE THREAD

**Issue by zouliming** [Semantic-Org/Semantic-UI#4007]
when i use dropdown behavior,'get text' or 'get value' return 2 value,but i'm sure the elements is only one.i found the difference is that the select dropdown return 2 value , but input dropdown is correct ,only one value.

**Comment by jlukic** [comment]
@
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
