### ISSUE TITLE
Customising Modal

### ISSUE THREAD

**Issue by rajchourasia** [Semantic-Org/Semantic-UI#4011]
There are three modal sizes provided by default Full Screen, Large and Small. The design I am working on requires a modal which is smaller than the default Small modal that is provided as can be seen in the image attached. (The attached image is not designed in Semantic, this is what I am trying to recreate in Semantic)

As I know, these are the following ways this can be solved

1. Writing custom LESS code in modal.overrides which customises the modal. I can add a new class (tiny), so that for future I have a Tiny Modal.
2. Altering the existing Small type modal to suit this size. However that is not favourable as it would change Small modal universally.

I prefer the first option. Below are the questions wrt that

1. Is the approach correct or there is another better way?
2. Is there a standard approach for creating new classes? How do we maintain / organise / document new classes so that other developers can reuse it?

![screen shot 2016-05-11 at 10 03 03 am](https://cloud.githubusercontent.com/assets/11809006/15170090/209326bc-1760-11e6-9a32-7a2c57d4df1d.png)

**Comment by dwightbcoder** [comment]
I've run into this a few times as well. There are four CSS definitions controlling the sizes which could be added to if you are not using LESS:
`@media only screen and (min-width: 1200px) { .ui.small.modal { ... } }`
`@media only screen and (min-width:  992px) { .ui.small.modal { ... } }`
`@media only screen and (min-width:  768px) { .ui.small.modal { ... } }`
`@media only screen and (max-width:  767px) { .ui.small.modal { ... } }`

@jlukic Have you considered simply allowing grid sizing on modals? Such as "six wide ui modal"?

**Comment by jlukic** [comment]
The best approach is to modify the single variable which controls small modal width.

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/modal.variables#L123

**Comment by dwightbcoder** [comment]
I think the point here is that only two sizes of modal is not enough in many cases.

The small size is great for many things and far too large in other cases (such as login form). We don't want every small modal to be tiny. That would result in the same basic issue, only two available sizes to work with.

**Comment by rajchourasia** [comment]
@dwightbcoder exactly what you said.

I will try using grid sizing.
