### ISSUE TITLE
General Error in Search Component - API action used but no url was defined search Object {}

### ISSUE THREAD

**Issue by uNki23** [Semantic-Org/Semantic-UI#4017]
[EDIT]: removed the Angular2 related code - just plain jQuery now.

Hi there,

if you **click into** the search field and type "a" - it works.
if you **tab into** it (without clicking into it before!) you'll get an error in the console and have to reload the whole application to get the search component working again!

[see this Plunk to replicate the issue](http://plnkr.co/edit/Vx8TMiOzaMyJhXpfzBZB?p=preview)

**Error:**
- open Plunk
- open the console
- focus the preview area
- click tab key
- type "a"
- see error

**Working:**
- open Plunk
- click into search field
- typa "a"

another problem is that you cannot navigate through the results with the keyboard. the items get highlighted for a second and then the selection is gone:

- use the working scenario from above
- select an item with arrow-down key
- item gets selected and immediately unselected

thanks for any help!!

**Comment by jlukic** [comment]
`apiSettings` is a setting of search itself. 

http://jsfiddle.net/kappkxzt/

**Comment by uNki23** [comment]
thank you very much, works!

but the second issue regarding the keyboard navigation within the results list is still unresolved. any ideas on that?

thanks and best regards

**Comment by Ryuno-Ki** [comment]
@uNki23 Maybe better opening a new issue on that, since @jlukic already closed this one.
