### ISSUE TITLE
dropdown filter method displays all results if using api and queryRemote

### ISSUE THREAD

**Issue by jemarlin** [Semantic-Org/Semantic-UI#4019]

**Comment by jemarlin** [comment]
fix is to add module.filterItems( searchTerm ); in the queryRemote callback prior to calling afterFiltered()

`if ( settings.apiSettings ) {
  if ( module.can.useAPI() ) {
	  module.queryRemote( searchTerm, function () {
		  afterFiltered();
	  } );
  }
  else {
	  module.error( error.noAPI );
  }
}`

becomes

`if ( settings.apiSettings ) {
  if ( module.can.useAPI() ) {
	  module.queryRemote( searchTerm, function () {
		  module.filterItems( searchTerm );
		  afterFiltered();
	  } );
  }
  else {
	  module.error( error.noAPI );
  }
}`

**Comment by jlukic** [comment]
It's expected that your remote query would return only the dataset matching the query parameter. This would filter it twice.

**Comment by jemarlin** [comment]
I see what you're saying.  We are doing a post so variables aren't part of the url.  I'm extending .data in beforeSend to capture the query input and will filter server side.  Thanks!
