### ISSUE TITLE
[Form] - Loading Should Be Relative to Top

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#4020]
If form's height is more than the viewport then the spinner  of .loading form may be out of view. I suggest add a variation of form that will have a spinner fixed to the center of viewport?

**Comment by jlukic** [comment]
Tab uses a `loader` that is positioned relative to the [top of the content](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/tab.less#L62). Perhaps `form` should just use this style.

**Comment by avalanche1** [comment]
I don't think this will resolve my issue.
`If form's height is more than the viewport then the spinner of .loading form may be out of view. `○♥☻☺♦•♣◘○◙♂♀♪♫☼

**Comment by jlukic** [comment]
Not sure how to proceed on this, going to delay until a solve emerges.
