### ISSUE TITLE
[Form] - dropdown overflow

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#4024]
**Steps to Reproduce**
Two fields next to each other using class="n wide field" with dropdowns inside.

**Expected**
The dropdowns should stop at the div.field limit

**Result**
The dropdowns doesn't stop at the div.field limit.

![image](https://cloud.githubusercontent.com/assets/1449151/15270855/bfbe1352-1a2e-11e6-9a0c-2743fd616034.png)

**Testcase**
http://jsfiddle.net/me01mozy/1/

**Comment by jlukic** [comment]
This is expected. Dropdowns have a min width to make sure content doesnt get squished.
http://jsfiddle.net/zfchkgcs/

**Comment by shadoWalker89** [comment]
@jlukic If i use `div.two.fields>(.field*2)>select.ui.dropdown` the overflow problem doesn't exist.
It exist only when i specify N wide field
