### ISSUE TITLE
Modal scroll bar re-position

### ISSUE THREAD

**Issue by andresespinosapc** [Semantic-Org/Semantic-UI#4025]
When a modal shows up, the scrollbar disappears, so all the content moves a bit to the right, what is very ugly. Is there a way of fixing that?

 It also occurs when refreshing the modal so it now has more larger content and it needs scrolling (so the scrollbar shows up).

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by lubber-de** [comment]
We fixed this in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/468
See https://jsfiddle.net/smudoy1k/5/
