### ISSUE TITLE
[Accordion] - Nested accordion menus do not work

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#4028]
**Steps to Reproduce**
1. create a vertical accordion menu
2. create another vertical accordion menu within the item content of a parent accordion

**Expected**
The Accordions should both work independently from each other

**Result**
The parent Accordion functions fine, however when attempting to expand the child accordion, it does not open. (it opens very briefly then immediately closes)

**Testcase**
http://jsfiddle.net/gze9tmem/1/

**Comment by jlukic** [comment]
There's an example of nested accordions in the docs
http://semantic-ui.com/modules/accordion.html#nested-accordions

Generally you cant combine class names for multiple components on the same `div` unless it is explicitly states in the docs. The amount of ways components can be combined like this makes it impossible to handle CSS inheritance.
