### ISSUE TITLE
Comments Avatar Wrapper - Chubby Theme

### ISSUE THREAD

**Issue by tonyporto** [Semantic-Org/Semantic-UI#4032]
Beautiful framework, missing clearfix on the first Avatar "Elliot Fu" on page http://semantic-ui.com/views/comment.html - Chubby theme

`.clearfix:after {content:""; clear:both; display:block}`

```
<div class="ui comments">
      <div class="comment clearfix">
```

**Comment by IonutBajescu** [comment]
Could you please explain what purpose would the clearfix have?

![selection_065](https://cloud.githubusercontent.com/assets/5365516/15357346/16bed258-1cf6-11e6-858f-ef1e8e439eb3.png)
