### ISSUE TITLE
Wrong email validation!

### ISSUE THREAD

**Issue by kamaliev** [Semantic-Org/Semantic-UI#4033]
Try validate "my@mail.com."

**Comment by Ryuno-Ki** [comment]
@kamaliev Look at https://github.com/Semantic-Org/Semantic-UI/issues/3755#issuecomment-219307856

Which version did you use?

**Comment by kamaliev** [comment]
@Ryuno-Ki 

jquery@1.11.3_2
meteor@1.1.6
semantic:ui-css@2.0.7
underscore@1.0.3

**Comment by kamaliev** [comment]
/*
 * # Semantic UI - 2.1.7
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */

**Comment by jlukic** [comment]
my@mail.com works just fine on semantic-ui.com 
http://semantic-ui.com/behaviors/form.html#content-type
