### ISSUE TITLE
2.2.0 minified: Uncaught SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by cspeer** [Semantic-Org/Semantic-UI#4037]
Hi there,

when I load the 2.2.0 [minified javascript file](https://github.com/Semantic-Org/Semantic-UI/blob/next/dist/semantic.min.js) in a browser, I get the following error:
```
Uncaught SyntaxError: Unexpected strict mode reserved word
```

The problem appears to be exactly here:
https://github.com/Semantic-Org/Semantic-UI/blob/next/dist/semantic.js#L11966-L11968

It only occurs when I use the minified version.
To reproduce this problem, all you gotta do is create an HTML file that loads `semantic.min.js` in its head.

![screenshot 2016-05-18 14 53 16](https://cloud.githubusercontent.com/assets/326824/15359158/5d6a59c2-1d08-11e6-911b-68d5730ac84b.png)

Cheers
Chris

**Comment by jlukic** [comment]
I'll check into it

**Comment by cspeer** [comment]
This appears to be fixed with the latest update of https://github.com/Semantic-Org/Semantic-UI/blob/next/dist/semantic.min.js

So, I'd consider this a closed matter.
