### ISSUE TITLE
Search clear after selecting item.

### ISSUE THREAD

**Issue by rdzidziguri** [Semantic-Org/Semantic-UI#4038]
I have a situation where i am using Search input from Semantic UI to provide autocomplete for the data. and handle onSelect event so that i get selected item which i add to another list. What i want now is to clear input value after item selected. is there any way i can achieve this?

**Comment by rdzidziguri** [comment]
ok have no problem with reading that but can u please provide links for that? because this is not an issue so i asked for help from u guys and u just closed this without farther assistance or comment u could juts tell me if it is possible and provided any link

**Comment by Ryuno-Ki** [comment]
Usually @jlukic is adding a comment with this content when adding those tags:

> Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

> To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

> To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources.

> * [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
> * [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI)
> * Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by fomojola** [comment]
Leaving this here for anyone else who is looking: if you created your search like this:

```
var element = $('.ui.search');
element.search({});
```

then

```
element.search("set value", "");
element.search("query");

```
will clear the input and hide the dropdown.
