### ISSUE TITLE
[Dropdown] Remote content prevents icon from triggering dropdown

### ISSUE THREAD

**Issue by nandastone** [Semantic-Org/Semantic-UI#4041]
This behaviour is observable in the documentation: http://semantic-ui.com/modules/dropdown.html#remote-content

To reproduce click the icon located in the right of the Dropdown before remote data has loaded. Nothing happens. Click anywhere else in the Dropdown to trigger the remote data load. Clicking the icon then works.

![dropdown-remote-icon](https://cloud.githubusercontent.com/assets/199204/15385625/2f7ddece-1de6-11e6-850c-6aea8fd1743d.png)

The issue appears to be in the event handler for clicking the icon, which attempts to toggle the dropdown menu. This is prevented from happening if there are no child options or message in the dropdown, which is the case for a dropdown with remote data.

https://github.com/Semantic-Org/Semantic-UI/blob/2.1.8/src/definitions/modules/dropdown.js#L874-L879

I believe if the `module.is.search()` is true, it should work more like the text element handler:

https://github.com/Semantic-Org/Semantic-UI/blob/2.1.8/src/definitions/modules/dropdown.js#L880-L885

**Comment by jlukic** [comment]
Clicking the icon should focus the field in this case causing the dropdown to query for content.

**Comment by jlukic** [comment]
Fixed in `2.2.8`, show will now always query if no results and remote.
