### ISSUE TITLE
[Transition] module.can.animate does not exist

### ISSUE THREAD

**Issue by flyboarder** [Semantic-Org/Semantic-UI#4045]
I am getting the following error:
https://github.com/Semantic-Org/Semantic-UI/issues/3040

However I believe this i being caused by:
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/transition.js#L188

as `module.can.animate()` does not exist in file, should be `module.can.transition()`

**Comment by jlukic** [comment]
`can.animate` does [exist here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/transition.js#L728)

**Comment by flyboarder** [comment]
@jlukic are all the transitions included when using the semantic-css package, they seem to be.
