### ISSUE TITLE
Something went wrong with the "Slider" component example

### ISSUE THREAD

**Issue by omerbsh** [Semantic-Org/Semantic-UI#4054]
Hey,

I have noticed that something went wrong with the slider example in your's website - 
http://semantic-ui.com/modules/slider.html

It doesn't work and there is a JS error via the console.

please check it out :)

**Comment by martindale** [comment]
OMG, I am so glad this even exists.  Would love to see it working.

**Comment by felixis-1** [comment]
Just confirming because we really need this, is this officially supported?

**Comment by vinayakkulkarni** [comment]
Duplicate, please see:
#3519, #4295, #5295, #4863, #3495
