### ISSUE TITLE
[Modal] Dim Each Modal When Showing Multiple

### ISSUE THREAD

**Issue by lnaravindan** [Semantic-Org/Semantic-UI#4055]
Hi, 

I have multiple modal use case, where opening one modal from another modal with (allow multiple = true), should use a new dimmer which will dim the previous modal too. (All the dimmers must be page level dimmers)

As far as I checked, I haven't found any such option in the documentation. Could you please let me know if this feature is available and if so how can I implement it?. 

If it is not available, are there any chances that it will land in future versions?

**Comment by lnaravindan** [comment]
Any updates on this issues?

**Comment by Balu-S** [comment]
I'm too waiting for the same. Any update?

**Comment by l-christopher** [comment]
any updates...??

**Comment by japhfortin** [comment]
Hi, Is there an update regarding this issue?

**Comment by lubber-de** [comment]
Since Fomantic-UI 2.5.1 the previous modals are automatically dimmed when `allowMultiple` is iset to `true` by https://github.com/fomantic/Fomantic-UI/pull/119
https://fomantic-ui.com/modules/modal.html#multiple-modals
