### ISSUE TITLE
Problem with long modal window firefox 46.0.1

### ISSUE THREAD

**Issue by Superilya** [Semantic-Org/Semantic-UI#4058]
we use semantic, and we have problem with long modal window in firefox 46.0.1 
![2016-05-25 14 32 00](https://cloud.githubusercontent.com/assets/6960308/15533574/0717193c-2287-11e6-870f-1ba51144d9ea.png)

**Comment by NoSoyTsundere** [comment]
No problem on Windows 7 and Firefox 46.0.1 but tried on Ubuntu 15.10 and Firefox 46 and the problem exists.

**Comment by jlukic** [comment]
This looks like a graphical glitch related to browser rendering on Ubuntu, most likely issues with GPU accelerated rendering.
