### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#4059]
Hi,

I've seen hundreds of bugs reported in this really nice library SEMANTIC UI but it's been a while since any release was published. Is this project still alive or should I come back to bootstrap which has a much faster code fixes and releases?

I really hope this project is not dead but if it already is, please tell me cause I will move back to bootstrap cause there are too many bugs in the current version of semantic ui that is taking too long to have a fix.

**Comment by lholznagel** [comment]
A single person is running this project. Some days ago he just closed a bunch of issues

**Comment by jlukic** [comment]
Im sorry you're dissatisfied, you can see recent activity by monitoring commit history on `next`. 
https://github.com/Semantic-Org/Semantic-UI/commits/next

There is code changing every week. This is open source so it takes some time to trickle back into formal releases. It takes a while to test and write documentation.

**Comment by batata004** [comment]
One single person takes care of this project? That's really unsecure: what if this person gets ill? Dies? Will every website that trusted into this library get busted?

Anyway, I really like this library, it's very beatiful and easy to use but you should maybe gather more people, I would be glad to help!
