### ISSUE TITLE
Device only needs .ui.grid

### ISSUE THREAD

**Issue by yamsellem** [Semantic-Org/Semantic-UI#4061]
The [documentation says](http://semantic-ui.com/elements/container.html#/introduction) items can be hidden on given device with thanks to the `container` class.

``` javascript
<div class="ui container mobile only">
  <p></p>
</div>
```

But it seems that the rules target `grid` instead:

``` css
.ui[class*="computer only"].grid.grid.grid:not(.tablet), 
.ui.grid.grid.grid > [class*="computer only"].row:not(.tablet), 
.ui.grid.grid.grid > [class*="computer only"].column:not(.tablet), 
.ui.grid.grid.grid > .row > [class*="computer only"].column:not(.tablet)
```

This is working, though:

``` javascript
<div class="ui grid mobile only">
  <p></p>
</div>
```

Thanks for the great job anyway.

**Comment by vinayakkulkarni** [comment]
The [grid docs](https://semantic-ui.com/collections/grid.html#reversed) have been updated since.

There's `large screen only`, `computer only`, `tablet only` and `mobile only`
