### ISSUE TITLE
Supporting older browsers

### ISSUE THREAD

**Issue by jonnymaceachern** [Semantic-Org/Semantic-UI#4063]
I'm interested in using this framework but some clients still require support for IE9/10. The browser support clause mentions that "the grid and any other components using flex" are not supported in IE9/10. Is it possible to sub in a non-flex grid system and get away with using this framework, or is a significant portion of it reliant on flex?

**Comment by ikourfaln** [comment]
Hi,

You can use  a polyfill for the Flexbox, just google for it.
I find this [10up/flexibility](https://github.com/10up/flexibility)

**Comment by jonnymaceachern** [comment]
@ikourfaln I'll give it a try. Do you have any experience using it w/ Semantic UI?

**Comment by ikourfaln** [comment]
No !! but Polyfills doesn't have different behaviors with frameworks, if it works it works. its a polyfill, it add Flexbox Functionality to the browsers, its not an extension for frameworks.

**Comment by jokeronaldo** [comment]
Flex is a very important part of SUI. If you want to supports IE 9/10 it's not a good choice.

**Comment by jlukic** [comment]
i dont SUI will be the right choice for IE9/10
