### ISSUE TITLE
[Modal] Position and Color Should Be Correctly Set with Combination of Link Card and Detachable = False Modal

### ISSUE THREAD

**Issue by aaronmyhre** [Semantic-Org/Semantic-UI#4064]
Filddle: http://jsfiddle.net/vjfysmmy/6/

Setup: 
- link cards 
  - link card 
    - modal, detachable = false

Behavior:
On mouse over of the modal, its position and color flicker.

Expected Behavior: the modal should not move nor change color. 

Issue: I believe the modal is inheriting some of the transition css from the link card.

**Comment by jokeronaldo** [comment]
When I move the mousve over the modal, it blinks.
