### ISSUE TITLE
[Validation] Add support for validating only when field is not empty

### ISSUE THREAD

**Issue by gapipro** [Semantic-Org/Semantic-UI#4069]
Right now if I have a form for entering an optional url, that url validation always triggers even if field is empty, saying that field must be a valid url.

I would expect that behaviour if field had validation for required and url at the same time, but not when it has just url validation.

**Comment by ikourfaln** [comment]
Hi,

Try to add multiple Rules, empty and url.
example:
```javascript
$('.ui.form')
  .form({
    fields: {
      urlfield : ['url', 'empty'],
    }
  });
```

**Comment by ikourfaln** [comment]
PS: this is usage questions, as you can read here : [README](https://github.com/Semantic-Org/Semantic-UI/blob/master/README.md#getting-help)
 For these types of questions use [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui), [ProjectTalk ](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) or join the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by gapipro** [comment]
Oh, sorry, I completely missed this option.

**Comment by rseyferth** [comment]
This is still very confusing; why wouldn't you name `empty` `required` instead, and make all other validation optional?
