### ISSUE TITLE
Colored basic buttons hover states not working

### ISSUE THREAD

**Issue by olgaysezgin** [Semantic-Org/Semantic-UI#4070]
`<a class="ui basic button blue" href="javascript:void(0);">Devam Et</a>`
this element has same color normal state and hover state

**Comment by ikourfaln** [comment]
Yeh, this is not a bug, they are colored on hover state, but its almost indistinguishable from the non-hovered state. for more détail check this issue #2947 .
This was added as Enhancement in [2.2.x milestone](https://github.com/Semantic-Org/Semantic-UI/milestones/2.2.x)

**Comment by jokeronaldo** [comment]
Duplicated https://github.com/Semantic-Org/Semantic-UI/issues/2947
