### ISSUE TITLE
Feature request: input+dropdown improvemet as HTML5 Input datalist tag (ComboBox: editable Select)

### ISSUE THREAD

**Issue by JesusSD** [Semantic-Org/Semantic-UI#4071]
Feature request: input+dropdown improvemet as HTML5 Input datalist tag (ComboBox: editable Select)

You can insert any value in Input tag and you have a Drop Down icon for introduce optional sugestions with values, labels and Icons as editable select.

Examples:
Input tag with Data List (Drop Down icon show optional values with lavels in Chrome)
link: http://triancal.esy.es/?p=15&t=6.4951905284
![chrome label in datalist](https://cloud.githubusercontent.com/assets/12623174/15609078/24124b18-241e-11e6-88ec-f5fd3a178fb9.jpg)

NGPrime Input Autocomplete (optional sugestions with Icons)
link: http://www.primefaces.org/primeng/#/autocomplete
![primenginputautocomplete](https://cloud.githubusercontent.com/assets/12623174/15609087/32f4f662-241e-11e6-9a64-f974d9dc3350.JPG)

Other sugestions:

Input adicional parameters:

    X delete Icon shows when has any value (default true).
    Undo icon (Default: false). * Go Boton (Default: false)
    Select all text when focus default true.
    Esc key: Back to initial valueEditable: As Input or Label/Select tag role. (Default: true)
    Note: Icons don't alter tag width

Validation improvements:

    Realtime Auto Validation border colors while insert text.
    Numbers and Text (<, <=, >, >=, !=)
    Array of validators with Regular expressions and funtions().
    Internacional: examples: "e equal é" or "n diferent ñ"

DropDown adicicional options:

    Selected Item background Color (Default: Automatic (good contrast)).
    Max items (Default Max number of items in window)
    Scrollbar (Default: Enabled with effects)
    AutoOpen: open when focus. (Default: false)
    Show: Enable dropdown icon only when has values (Default: true)
    Automatic: display dropdown icon only when has focus: (default: true), (false=ever showed)
    Sort values (Internacional: example "e or é" or "n ñ") (Default: false)
    Note: All values are ever shows bellow with a divider.
    Multiple: Select some values with checkbox. (Defaut: false)
    Search: with hilights sugestions while you type (begin, contain, seam...)(Default: false)
    Exclusive: User only can insert DropDown list values default false
    Insert component as values
    Groups, disable, hidden and dividers.

    Thanks.

**Comment by jokeronaldo** [comment]
Thank you for suggestions.

**Comment by Cougar84** [comment]
It would be great to have a custom renderer for the elements of the list after a remote search.

**Comment by jlukic** [comment]
I'm not sure I understand the request. We include most of the settings you mention, search, showOnFocus, scrolling, maxItems (through css variables), groups, details etc. 

Please see our contributing guide to see how to make more effective suggestions by narrowing the focus to a specific feature.
