### ISSUE TITLE
usage/layout doesn't carry meaning

### ISSUE THREAD

**Issue by janat08** [Semantic-Org/Semantic-UI#4072]
http://semantic-ui.com/usage/layout.html
this page should have links to download source code, and the frontpage example must have some kind of accompanying js with it which is isn't in examples folder of repository

**Comment by janat08** [comment]
also music player won't work (sound cloud pop up player)

**Comment by janat08** [comment]
I shit you not, there're 3 menus in there (the front page usage).


<div class="ui vertical inverted sidebar menu">


<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">


<div class="ui large top fixed hidden menu">

**Comment by jlukic** [comment]
Closing, tone.
