### ISSUE TITLE
using Dropdown with variables, not api ?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#4073]
I try to combine `dropdown` with `search` modules, but from the docs, only the api can be used:

`$('.remote.example .ui.dropdown')
  .dropdown({
    apiSettings: {
      url: '//api.semantic-ui.com/tags/{query}'
    }
  })
;`

What I try to do, is to use a variable already existed in the document:

`source : someObject.value`

**Comment by jlukic** [comment]
You can use `apiSettings` along with `response` and a static object. See API docs.

**Comment by abdelouahabb** [comment]
ah, got it, thank you :)
