### ISSUE TITLE
Vertical Divider are not well displayed in Canary

### ISSUE THREAD

**Issue by Spica2** [Semantic-Org/Semantic-UI#4080]
Vertical Divider float to left
Version 53.0.2753.0 canary (64-bit)

**Comment by IonutBajescu** [comment]
Could you please share with us a few screenshots and a jsfiddle?

**Comment by Spica2** [comment]
<img width="1376" alt="bildschirmfoto 2016-06-06 um 20 08 03" src="https://cloud.githubusercontent.com/assets/1394405/15832461/9bdd6694-2c22-11e6-9d8b-2dd681a0e2bf.png">

I think a jsfiddle is not nedded, you can see it at dividers demo

**Comment by pierre-weceipt** [comment]
The exact same thing is happening on edge.

**Comment by jlukic** [comment]
I should post about this in the contributing guide, but I only plan on supporting display bugs on `stable` browser releases. It is too onerous to disentangle browser bugs from user lib bugs at that phase.

**Comment by pierre-weceipt** [comment]
I understand the point, still Microsoft Edge is not a beta anymore at least on windows.

**Comment by jlukic** [comment]
Track in
https://github.com/w3c/csswg-drafts/issues/401
and
https://bugs.chromium.org/p/chromium/issues/detail?id=633011

**Comment by flcoder** [comment]
I'm seeing the same with Chrome Version 52.0.2743.116 (64-bit) on Ubuntu 16.04

**Comment by arlyon** [comment]
Chrome ver 53 is also suffering from the same issue.

![image](https://cloud.githubusercontent.com/assets/8715352/18608020/d18a8220-7cdd-11e6-9020-b77af4350041.png)
