### ISSUE TITLE
How to undo or destroy dropdown keeping original select

### ISSUE THREAD

**Issue by miguelmota** [Semantic-Org/Semantic-UI#4083]
How to undo or destroy dropdown keeping original select? For example if I have a regular `<select>` with options and I call `$('select').dropdown()`, then how can I revert back to the standard `<select>`? I'm asking because calling the dropdown function wraps a bunch of code and I need to re-render it with new options

**Comment by jlukic** [comment]
There are mutation observers to watch the original select and update the menu when the select options change. You can also call `refresh menu`.

**Comment by lukesnowden** [comment]
jQuery Hack;

```javascript
$.fn.destroyDropdown = function() {
	return $(this).each(function() {
		$(this).parent().dropdown( 'destroy' ).replaceWith( $(this) );
	});
};
```

```javascript
$('select').destroyDropdown();
```

**Comment by renatodolza** [comment]
> jQuery Hack;
> 
> ```js
> $.fn.destroyDropdown = function() {
> 	return $(this).each(function() {
> 		$(this).parent().dropdown( 'destroy' ).replaceWith( $(this) );
> 	});
> };
> ```
> 
> ```js
> $('select').destroyDropdown();
> ```

Not have Behavior destroy...
