### ISSUE TITLE
disable device modes

### ISSUE THREAD

**Issue by Xyr2** [Semantic-Org/Semantic-UI#4086]
Hello,

is there a built in solution to disable some device modes? In my case I want to disable the "Large Monitor" and "Widescreen Monitor" sizes completly, so that in all cases "computer" is the widest container/grid etc. size.

Couldn't find anything about it in the docu.

Thanks for your help... :)

**Comment by IonutBajescu** [comment]
None that I know of. You'll have to code it yourself. 

Also, in the future, consider posting usage questions on ProjectTalk so we can keep github only for bug reports / proposals.
