### ISSUE TITLE
[Search] Give an option not to show the autocomplete, if the selected item is not changed

### ISSUE THREAD

**Issue by kelwang** [Semantic-Org/Semantic-UI#4087]
The current `can show` function only checked if focus, not visible and not empty
`show: function() {
       return module.is.focused() && !module.is.visible() && !module.is.empty();
 },`

Should give an extra option, check if the selected item had been changed or not.
A form may have multiple fields. When the selected item is not changed, autocomplete on focus or enter is unnecessary and annoying. 

See
https://jsfiddle.net/kelwang/vhvqz321/

**Comment by jlukic** [comment]
I've added a new setting `searchOnFocus` which enabled/disables this feature in `2.2.8`
