### ISSUE TITLE
[Dropdown] Should not lose z-index due to blurring modal

### ISSUE THREAD

**Issue by jlafleche** [Semantic-Org/Semantic-UI#4088]
See: http://jsfiddle.net/s3rux404/2/

<img width="307" alt="screen shot 2016-06-01 at 5 30 27 pm" src="https://cloud.githubusercontent.com/assets/13784646/15730119/b2a73682-281e-11e6-852a-2ae960d0d5eb.png">

Seems like whatever CSS is being applied when the modal dialog is activated with `blurring: true` causes some z-index confusion.  Disabling blurring fixes the issue.

**Comment by jlukic** [comment]
Blurring applies filters on any direct children to `body`. Filters like `transform` will affect stacking context due to bizarre w3c decisoins. 

Add a wrapping div to solve. 
http://jsfiddle.net/z3j2zzx2/
