### ISSUE TITLE
[Fixed single line Table] Being able to read text within the ellipsis

### ISSUE THREAD

**Issue by sarupbanskota** [Semantic-Org/Semantic-UI#4091]
The single line capability is quite cool; however it can get frustrating to not be able to read the text at all.

Would it be worthwhile to show the full content of the `td` within a tooltip if an ellipsis is involved? 
The tricky bit here would be to also think about how to deal with touch devices.

For reference: 
- Code for the ellips-ing: https://github.com/Semantic-Org/Semantic-UI/blob/42e41c2699691ff59c148a41a326a9b874a0f08e/dist/components/table.css#L463-L467
- Random example from the internet: http://jsfiddle.net/chadkuehn/nu5zk/

**Comment by jlukic** [comment]
I think you're solution is effective. I dont think this needs to be included in the library outside of a future grid-view/table module.
