### ISSUE TITLE
[Announcement] Semantic-UI now is a part of new ASP.NET Core templates

### ISSUE THREAD

**Issue by ikourfaln** [Semantic-Org/Semantic-UI#4092]
Hi,
After my request ([aspnet/Mvc/issues/2709](https://github.com/aspnet/Mvc/issues/2709)), I thought that the proposal was ignored. But today, I was watching a tutorial on how generate an ASP.NET project via Yeoman ([ASPNET-Monsters-Episode-38-Yeoman](https://channel9.msdn.com/Series/aspnetmonsters/ASPNET-Monsters-Episode-38-Yeoman)), and I discover that Semantic-UI is now a part of new ASP.NET Core templates ([OmniSharp/generator-aspnet](https://github.com/OmniSharp/generator-aspnet)) :smile: . 

![sans titre](https://cloud.githubusercontent.com/assets/9744226/15827753/012fb1ea-2bfc-11e6-8a53-9e4d4bf3a130.png)

So I return to my request [2709](https://github.com/aspnet/Mvc/issues/2709) and I see that finally the community react.
So thanx to [@jackjwilliams](https://github.com/jackjwilliams) for the hard work, the integration was completed because of him via this [pull request](https://github.com/OmniSharp/generator-aspnet/commit/7ebcab15d2691d175878c707085897fb90f2d121).
So @jlukic dont forget to react with the ASP.NET community if there are some break changes. and Who knows, maybe Semantic-UI will be the default template for ASP.NET and not bootstrap :wink:

**Comment by jackjwilliams** [comment]
Apparently I'm a little slow because I'm just now seeing this (over a year later). No problem, was a fun learning experience!
