### ISSUE TITLE
[Validation] Add ability to validate single element rather than entire form

### ISSUE THREAD

**Issue by jemarlin** [Semantic-Org/Semantic-UI#4093]
We had need in our project to conditionally perform validation on a single input element, but did not want to trigger errors on other inputs.  'validate form'.  We added this method to  form module.validate just before the existing module.validate.form method:

`  
element: function( elementName ){

```
  var element = validation[elementName];

  return module.validate.field( element, elementName );
```

  },

`

Which is called like so `$form.form( 'validate element', '[element name]' );`  This solved our problem and could potentially be useful to others.

**Comment by jlukic** [comment]
Seems like an easy add.

**Comment by marcellomontemagno** [comment]
+1

**Comment by jlukic** [comment]
I'm going to use a slightly different syntax by overloading some existing functions

```javascript
// validates only single field
$('.ui.form').form('validate field, 'fieldName');

// returns boolean of whether field is valid
$('.ui.form').form('is valid', 'fieldName');
```

**Comment by jlukic** [comment]
Added in `2.2.8` see release notes and docs for syntax
