### ISSUE TITLE
Facebook Video Embed

### ISSUE THREAD

**Issue by krishaamer** [Semantic-Org/Semantic-UI#4096]
Hello, would be awesome to support Facebook video in the default sources in embed.

Thanks,
Kris

**Comment by moxet** [comment]
Hi @krishaamer 

Hope this will solve your issue.

`<div class="fb-video ui 16:9 embed" data-href="URL OF VIDEO" data-width="500" data-allowfullscreen="true" data-autoplay="true"></div>`

Don't forget to include SDK code in body
`
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>`

[Demo](http://pkhive.com/hive/videos.php?v=1504)
