### ISSUE TITLE
[Dropdown] - 'set exactly' doesn't trigger any hooks

### ISSUE THREAD

**Issue by mkoczorowski** [Semantic-Org/Semantic-UI#4097]
'set exactly' on multiple selection dropdown used to trigger 'onLabelCreate' hook, allowing to customise label. This is not happening anymore. This means I'm able to create my own label when use select but I'm unable to recreate it on page refresh :/ Please help

**Comment by jlukic** [comment]
Please submit a test case so this can be triaged effectively.
