### ISSUE TITLE
[Checkbox] - "fireOnInit" setting does not seem to default to true

### ISSUE THREAD

**Issue by cneuro** [Semantic-Org/Semantic-UI#4098]
**Steps to Reproduce**

```html
<div class="ui checkbox">
  <input type="checkbox" name="example">
  <label>Example</label>
</div>
```

```javascript
$('.ui.checkbox').checkbox({
  'onChecked': function () {
    console.log('onChecked');
  },
  'onChange': function () {
    console.log('onChange');
  }
});
```

**Expected**
At least one of the console.log()s should output when the page is loaded and the element rendered.

Because:

![semantic](https://cloud.githubusercontent.com/assets/2691584/15827651/4a1e347a-2c0c-11e6-801b-b789ae943046.PNG)

http://semantic-ui.com/modules/checkbox.html#/settings

**Result**
Does not "fireOnInit", no console output.

**Workaround**
By manually setting within `.checkbox()` options:
```json
fireOnInit: true
```

**Comment by jlukic** [comment]
I'm not sure when this occurred but the docs just seem to be flat out wrong here.

**Comment by jlukic** [comment]
Fixed in docs.
