### ISSUE TITLE
Wrong color on inverted teal button

### ISSUE THREAD

**Issue by Dielz98** [Semantic-Org/Semantic-UI#4099]
![screen shot 2016-06-06 at 11 56 21 pm](https://cloud.githubusercontent.com/assets/17416861/15830430/6869b626-2c42-11e6-8b1f-b910bd5491d7.jpg)
![screen shot 2016-06-06 at 11 56 39 pm](https://cloud.githubusercontent.com/assets/17416861/15830431/6cecaf0a-2c42-11e6-86de-e51224801ae4.jpg)

**Comment by jlukic** [comment]
Light colors are different from dark colors. Check the css variables. This is for legibility and not a bug
