### ISSUE TITLE
[Modal] - Inverted Dimmer Variations In Modal

### ISSUE THREAD

**Issue by catwithlover** [Semantic-Org/Semantic-UI#4102]
**Steps to Reproduce**
this issue also appear on Semantic-Ui offical website, see this page: http://semantic-ui.com/modules/modal.html#dimmer-variations ,you can try to click 'run code' twice, trigger the modal on the variation which inverted is true, then you can see when we trigger modal the first time, the style of dimmer is inverted, but when you trigger modal again, the style of dimmer is not inverted. It looks like the variations is not working.

**Expected**
the variation "inverted" should work, the style of dimmer is always inverted no matter how many times we trigger the modal

**Result**
the inverted style of dimmer only works in the first time 

**Testcase**
see this page: http://semantic-ui.com/modules/modal.html#dimmer-variations

**Comment by fpoirier1** [comment]
+1
