### ISSUE TITLE
Dropdown not resetting placeholder after ajax request

### ISSUE THREAD

**Issue by ctilley83** [Semantic-Org/Semantic-UI#4105]
Currently there is no option to reset the placeholder div.  After creating a record, the "default text" class does not appear. This prevents the dropdown from displaying greyed out placeholder text. I'm having to do a workaround to get it to work.

Things I've tried:

`$('#ui.fluid.dropdown).dropdown('get placeholder text') #nope`
`$('#ui.fluid.dropdown').dropdown('get default text') #nope`
`$('#ui.fluid.dropdown').dropdown('restore defaults') #works except it does not grey out the placeholder`

The workaround to recreate the "default text" div:

`$('.ui.fluid.dropdown').dropdown('clear').append('<div class="default text">Choose Payee</div>')`

Expected behavior: one of the above options should recreate the placeholder div without having to manually append it to the end of the dropdown class.

Environment:
Rails 5.0 Rc1
Semantic-UI-Rails-LESS gem

**Comment by jlukic** [comment]
See `next`, branch and release notes. 
https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md

Code behind
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js#L1948

In current branch you can call  the unintuitively named `.dropdown('set placeholder text')`

**Comment by vannim152** [comment]
Hi @jlukic , will you support icon in placeholder text? Apparently, if the placeholder text is `"<i class='user icon'></i> Select a user"`, the `.dropdown('restore placeholder text')` only restore the text bit. People would expect icon + text
