### ISSUE TITLE
popup not working without including transitions

### ISSUE THREAD

**Issue by clemsontiger** [Semantic-Org/Semantic-UI#4106]
The popup documentation page states: "Named transition to use when animating menu in and out. Fade and slide down are available without including ui transitions"

One would infer it thus works without including ui transitions, by using transition: 'fade'.or just the default 'slide down', but neither work. But keeps throwing the following error:

"Popup: This module requires ui transitions"

Working example of issue:
https://jsfiddle.net/clemsontiger/9ddpudpw/12/

**Comment by jlukic** [comment]
Fallback javascript animations were removed from most components. This was to reduce the filesize of js components, and to avoid having to support multiple branches of animation code. 

For a lighter weight solution you might want to try `tooltip` (css only popups) available soon in `2.2`

**Comment by clemsontiger** [comment]
You'll want to change your documentation then, as the popup page documentation under Usage > Settings > transition specificly states "Fade and slide down are available without including ui transitions"

**Comment by jlukic** [comment]
Thanks

**Comment by jlukic** [comment]
Removed note from docs

**Comment by lulalala** [comment]
Not sure why but I can still see that note here https://semantic-ui.com/modules/popup.html#/settings

**Comment by Banandrew** [comment]
@lulalala Thank you, I opened a PR.
