### ISSUE TITLE
The size setting of label not displayed correct in Chrome browser

### ISSUE THREAD

**Issue by xqandpan** [Semantic-Org/Semantic-UI#4111]
Hello,

I use the semantic-ui label in my app to display some information. But When I set the size of label to mini, the size looks like normal size in chrome browser. But in firefox the size display correct.

And then I checked the example page from official web page
http://semantic-ui.com/elements/label.html

You can check the size segment, the Mini Tiny Small Medium looks like the same size.

Thanks.

**Comment by IonutBajescu** [comment]
The sizes look fine for me, I'm using chrome as well. What version of your chrome are you using?

![selection_112](https://cloud.githubusercontent.com/assets/5365516/15889403/ee78fae4-2d62-11e6-8eab-0a3246246258.png)

**Comment by xqandpan** [comment]
50.0.2661.102 m

**Comment by xqandpan** [comment]
51.0.2704.84 m not working, too

**Comment by hmaesta** [comment]
Fine here with the same Chrome as you, @xqandpan.
51.0.2704.84 64-bit, El Capitan.

**Comment by jackeyGao** [comment]
![image](https://cloud.githubusercontent.com/assets/2869650/15988405/dbba0dd6-3081-11e6-8baf-1b6c53456b75.png)

**Comment by jlukic** [comment]
We dont currently support bug request for development versions. Quite often display errors are mistaken for bugs in the renderer.

**Comment by jackeyGao** [comment]
@jlukic  Thanks! But, Problems also exist in Chrome 50.0.2661.102(64-bit) .
