### ISSUE TITLE
[Dropdown] Menus Should Open to the Left When Going Off-screen to the Right

### ISSUE THREAD

**Issue by andreiho** [Semantic-Org/Semantic-UI#4112]
Currently the horizontal positioning of the menus is not adjusted in any way, if the menu goes off-screen. This is extremely frustrating when building menus with multiple nested levels.

I know the direction of the menu can be set to open either to the left or to the right, but this is not ideal in a responsive website where the position of the menu items is not fixed and can change on any screen. Ideally the dropdown should know when a menu goes off-screen and open it in the opposite direction.

JSFiddle: http://jsfiddle.net/znhby35f/

Screenshot:

![screenshot 2016-06-08 13 12 55](https://cloud.githubusercontent.com/assets/9000674/15892570/bd354e98-2d7a-11e6-99da-fb4fdc8b99c8.png)

I'm not sure if this is already something confirmed or in progress, but I couldn't find a similar issue addressing this exact problem.

**Comment by mehi-shokri** [comment]
@andreiho after 2 years, do you remember how you solved it?

**Comment by andreiho** [comment]
@mehi-shokri This was fixed a while ago: https://github.com/Semantic-Org/Semantic-UI/pull/4211
