### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by cjloong** [Semantic-Org/Semantic-UI#4113]
Hi
I ran npm install but it fails with the following:

```
> semantic-ui@2.1.8 install C:\Users\chekjen\git\evo3\node_modules\semantic-ui
> gulp install

C:\Users\chekjen\git\evo3\node_modules\accord\lib\index.js:34
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 1.7.5 is not currently supported
```

**Comment by border-radius** [comment]
Looks like you are trying to add semantic to existing project with existing `less` dependency. I just encountered with this while trying to add semantic to generated express.js project.
Change your `less-middleware` dependency version in `package.json` like this:
```json
-    "less-middleware": "1.0.x",
+    "less-middleware": "~2.0.1",
```
And run `npm install` to update `less` and `less-middleware` versions. After that you can finally install `semantic-ui`.

**Comment by Banandrew** [comment]
Hello everyone, @cjloong, could you please confirm that the issue is resolved?
