### ISSUE TITLE
[Button] Labeled Icon is Not Compatible with Animated Button

### ISSUE THREAD

**Issue by hmaesta** [Semantic-Org/Semantic-UI#4114]
Button using `<a>` with classes `ui animated fade right labeled icon basic large button` have a weird alignment.

![button](https://cloud.githubusercontent.com/assets/741969/15917893/41369c22-2dd7-11e6-9a1f-967cdb7d4172.png)

**Demo: http://jsfiddle.net/efp8z6Ln/334/**

Chrome 50.0.2661.102 @ El Capitan

**Comment by jlukic** [comment]
Animated button and labeled icon are two `types` of buttons and are mutually exclusive (they cannot be mixed).
