### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by Morrolan** [Semantic-Org/Semantic-UI#4115]
Please add Semantic-UI's current level of support for the Microsoft Edge browser to the README.

**Comment by viicviicviic** [comment]
Did you add to the README? If you did, just make a pull-request. If dont, you free to do it :+1:

**Comment by Morrolan** [comment]
I know I can add to the readme and do a pull request, but that doesn't answer the question of IF Edge is supported, or if there are any peculiarities ;)

**Comment by viicviicviic** [comment]
Didn't get your answer at first, actually. Just understood now. Anyhow, did you ever tried to make a full test on IE Edge?

**Comment by jlukic** [comment]
Yes, it is.
