### ISSUE TITLE
How can user clear dropdown with search and additions.

### ISSUE THREAD

**Issue by DamodarSojka** [Semantic-Org/Semantic-UI#4116]
How can user remove selection from a dropdown with enabled search and additions?
Shouldn't backspace to empty text call onChange and remove selection?
I can just place clear/remove button next to a dropdown but I am looking for a better solution (I am using angular and this would require me to rearange something).

**Comment by DamodarSojka** [comment]
So is this functionality not available?

**Comment by lholznagel** [comment]
http://semantic-ui.com/modules/dropdown.html#multiple-selection try / read this

and for angular 1 I recommend https://github.com/machineboy2045/angular-selectize 
for angular 2 I recommend using the jquery version of selectize 2

**Comment by DamodarSojka** [comment]
I am not using multiple search+selections. I could set max number to 1 but this is not ideal.
Thanks for the recommendation but I have almost accomodated UI-semantic dropdown to my needs. 

If anyone is interested how clearing can be implemented here is what I have made.


        // Let user clear the selection
            // wrap the element in jQuery, angular jqLite doesn't support keyup
            $($elem.children().children()[1]).keyup(function(event) {
                // if box was empty and key was backspace empty the box
                if(!this.value && event.keyCode === 8){
                    $scope.model = {};

                    //change happens outside of angular, let it know something changed
                    $scope.$apply();

                    // clear the internal state of the dropdown
                    $elem.children().dropdown('clear');

                    // set the text of the div that contains default text
                    $($elem.children().children()[2]).text($scope.defaultText)
                }
            });
