### ISSUE TITLE
[Sticky] - Error message is missleading

### ISSUE THREAD

**Issue by pierre-weceipt** [Semantic-Org/Semantic-UI#4119]
Hi, jus a small suggestion : I spent a couple of hour trying to understand why my sticky rail initialisation made the following error 
```Sticky: Sticky element is larger than its container, cannot create sticky.```
I thought that the content Inside the rail was too large but instead by larger it meant higher which makes sense, the sticky cannot be higher than its context container. It would be nice to change the wording to have something less confusing :) 

Thanks!

**Comment by jlukic** [comment]
I believe the error message is valid, it is checking the `sticky` height against the containing element size. 

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sticky.js#L151

**Comment by pierre-weceipt** [comment]
That's exactly the point : Replacing larger by higher! 
Anyway that was more of a detail.

**Comment by Xsmael** [comment]
@pierre-weceipt  i strongly agree with you! but "higher" wont be a proper word either, since that could mean that it's position(location is above), i would suggest lengthier or bigger or saying clearly the height of this is bigger than the height of that... Thanks
