### ISSUE TITLE
[Idea] - Free Templates For The Community

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#4120]
Hi Jack,
Semantic UI has been the backbone of most of my projects. And because the industry I work in requires that we re-create a lot of user interfaces, I found myself re-inventing the wheel many a times. So, I came up with this idea for a repo that will host useful HTML templates for the SUI community so that it not only works as to show the use cases possible with SUI, but also helps to reduce re-inventing the wheel. So, let's say someone wants to create a standard login page, they can just fork a template from here and start using it. Frankly, I have a lot of templates created in HAML over the years and I'll be happy to share them with the community.

I just created a repo with a landing page in it. I'll slowly add more whenever possible.
### Demo:

http://jsfiddle.net/dsgnr/efp8z6Ln/335/embedded/result
### Repo:

https://github.com/Neverexplored/Semantic-UI-Templates

Cheers.

**Comment by jlukic** [comment]
Thanks @dsignr I've added this to the top of the wiki
https://github.com/Semantic-Org/Semantic-UI/wiki/Integration

**Comment by dsignr** [comment]
Thank you Jack, much appreciated 👍
