### ISSUE TITLE
[Build Tools] Externalize gulp configuration settings

### ISSUE THREAD

**Issue by originalwebgurl** [Semantic-Org/Semantic-UI#4122]
I'm using the [Less Only](https://github.com/Semantic-Org/Semantic-UI-LESS) version of Semantic UI, but I've copied over the Build & Watch tasks so I don't have to re-invent the wheel. 

Not sure if there's any demand for making the build tasks more configurable, but if so I've started to do this for my own projects - https://bitbucket.org/unicorn_admin/semantic-ui-boilerplate 

So far the 2 configuration changes I've made are:

**Allow custom filename for generated css and js file**
_semantic.json_

``` js
{
  ...
  "filenames": {
    // generated assets can be named and are saved to 'output.packaged'
    "concatenatedCSS": "app.css",
    "concatenatedJS": "app.js",
    "concatenatedMinifiedCSS": "app.min.css",
    "concatenatedMinifiedJS": "app.min.js"
  }
  ...
}
```

**Override Semantic UI's default evergreen browser support**
_semantic.json_

``` js
{  
  ...  
  "autoprefixSettings": {  
    "browsers": [  
      "last 4 versions",  
      "> 1%",  
      "opera 12.1",  
      "bb 10",  
      "android 4"  
    ]  
  }  
  ...  
}
```

If this is something you'd like to include I can package it up into a PR.

**Comment by jlukic** [comment]
I think it would make sense to surface more settings in semantic.json, but I would probably choose which on a case by case basis.

With task settings, these are all surfaced in [`tasks.js`](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/tasks.js). It would make sense to preserve the heirarchy and extend it with `tasks` object returned from `semantic.json`

I also agree filenames is a reasonable addition. 

Be sure when submitting a PR to preserve the code-style used in the rest of `tasks/` to expedite merging.
