### ISSUE TITLE
List in a Message is not displayed correctly

### ISSUE THREAD

**Issue by Blackvz** [Semantic-Org/Semantic-UI#4124]
Hey,

like the title already tells you, a list in a message is not displayed correctly.. Im using Chrome and I can see it on your official site : http://semantic-ui.com/collections/message.html and also when I use it in my project.

![auswahl_008](https://cloud.githubusercontent.com/assets/12122294/16025665/faa7b2f0-31c8-11e6-8abf-9ff539781414.png)

Love your framework by the way and will also donate after finishing my new project with it.

**Comment by jlukic** [comment]
What version of chrome? Stable or dev branch? Are you using a different language? Not seeing this.

**Comment by Blackvz** [comment]
Chrome Version 49.0.2623.87 (64-bit)
Semantic UI V. ^2.1, but I also see it on your official Site.
Language: German

**Comment by jlukic** [comment]
Try going to Chrome -> More Tools -> Encoding

Can you verify that encoding is set to "auto-detect" (this is default for Chrome)

**Comment by ascheffe-umd** [comment]
I can reproduce this reliably in chrome. I added the following issue before noticing this one
https://github.com/Semantic-Org/Semantic-UI/issues/4873.

**Comment by douglasg14b** [comment]
@Banandrew  I'm receiving this error now too....

And there doesn't seem to be an encoding option in the same path as @jlukic  posted.

**Comment by Banandrew** [comment]
@douglasg14b Chrome has got a supposedly reliable mechanism of automatic encoding detection now, so they hid the menu. Nothing is changed about the issue, though—we can’t fix what we can’t reproduce.

**Comment by tomsmalley** [comment]
Also seeing this issue. This is fixed by adding

```css
@charset "UTF-8";
```

to the first line of the semantic css file. Is there a reason why this can't be added?

**Comment by mail2tarkeshwar** [comment]
We may try replacing the content from • to â€¢ for the class .ui.message .list:not(.ui) li:before in semantic.css file, to fix this issue.

**Comment by tomsmalley** [comment]
@mail2tarkeshwar this results in chrome setting the content to `Ã¢â‚¬Â¢`.

**Comment by mail2tarkeshwar** [comment]
@tomsmalley Please use without changing any default settings of Chrome, it works, here is the screenshot attached...
