### ISSUE TITLE
Load themes on the fly

### ISSUE THREAD

**Issue by alexfromgalax87** [Semantic-Org/Semantic-UI#4130]
Hello dear coders, 

as seen on http://semantic-ui.com/usage/theming.html it is somehow possible to load themes on the fly.  From the tutorial i learned that in case to change a theme it is necessary to change the themename inside the theme.config and rebuild the project with gulp. This works fine, but i dont understand how to load such themes on the fly without rebuilding the project? Any help very appreciated.

**Comment by jlukic** [comment]
You can use `less.js` which can be compiled on the fly. 

Here's what Semantic-ui.com is doing
https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/files/javascript/docs.js#L512
