### ISSUE TITLE
Uncompressed directory seems to still contain "semantic.min.js" and "semantic.min.js"

### ISSUE THREAD

**Issue by chaitanyagurrapu** [Semantic-Org/Semantic-UI#4131]
I updated my semantic.json to file to split the output of compressed and uncompressed files.

![image](https://cloud.githubusercontent.com/assets/853059/16142027/0a22ab3e-34a5-11e6-8717-b4ce981f921e.png)

When I run the build, all the components have been minified properly in the correct directory.

![image](https://cloud.githubusercontent.com/assets/853059/16142191/8d763f04-34a6-11e6-943a-40ec4867a58f.png)

And the un compressed directory contains the uncompressed files.

![image](https://cloud.githubusercontent.com/assets/853059/16142183/7afebdd8-34a6-11e6-9cd7-4fb2034e2e2c.png)

Except for the semantic.css and semantic.js files ...

![image](https://cloud.githubusercontent.com/assets/853059/16142201/a537450c-34a6-11e6-8291-ea01805bff29.png)

is this the expected behaviour? I was hoping to just pass this uncompressed directory, along with a whole heap of other directories through my applications minification pipeline

**Comment by drupalshift** [comment]
This is expected , you can change packaged destination if you prefer another folder for **packaged** version of files ! ( packaged version includes all components in a single file )

**Comment by chaitanyagurrapu** [comment]
Even with the packaged variable set, it still seems to put the minified and unminifed css/js in the same directory ...

![image](https://cloud.githubusercontent.com/assets/853059/16720175/c37fd334-4776-11e6-86c7-70a79f1262b9.png)


Is there any way to separate them?
