### ISSUE TITLE
[Dropdown] Search Selection does not work with remote-content / API

### ISSUE THREAD

**Issue by mariusWeceipt** [Semantic-Org/Semantic-UI#4132]
My search dropdowns are loaded like that : 
```
$('#myDropdown').dropdown({
   apiSettings: {
   url:'...',
   saveRemoteData:false
   }
}
```
Options are loaded correctly, dropdown is opening and the input supports keyboard input ; **BUT** dropdown options are not filtered according to what you are typing in the input (all options are shown regardless what you type).

**Comment by reejosamuel** [comment]
What does your debugger say? are you getting any errors?

**Comment by mariusWeceipt** [comment]
Nope ! It just types what I type in the input, and the dropdown is open with all options provided - none filtered. And no errors.
I've tried .dropdown('refresh') before and after providing remote data, in case the 'change' event wasn't attached, but it doesn't change anything either.

**Comment by perke** [comment]
Same here, values are populated from remote but typing doesn't filter. If I hardcode output from remote to the dropdown, search is working.

Would love to supply fiddle but data are sort of private, if there is a fake api let me know and I'll add a fiddle.

**Comment by jlukic** [comment]
This should be on our forums

**Comment by mariusWeceipt** [comment]
Ok. Transferred to http://forums.semantic-ui.com/t/dropdown-search-selection-does-not-work-with-remote-content-api/129

**Comment by xxRockOnxx** [comment]
I am having this problem too: http://jsbin.com/bofoxawoxa/edit?html,js,output

Already looked at OP's thread on the forum but it still has no answer. Please consider this issue

**Comment by xxRockOnxx** [comment]
Ok so I guess mocking a response that will always be the result of the search.

I thought dropdown can search internally from it's options already. There should be an option for remote source or just local array. I know we can do <option> or <div item> but for users who uses ReactJS with Flux architecture which means who uses "Store" instead, we need to have that option.

I tried

```
$("#provinceDropdown").dropdown({
  apiSettings: {
        response: {
          "success": true,
          "results": [
            {
              // name displayed in dropdown
              "name"  : "Choice 1",
               // selected value
              "value" : "value1",
            },
            {
              "name"  : "Choice 2",
              "value" : "value2",
              "text"  : "Choice 2"
            },
            {
              "name"  : "Choice 3",
              "value" : "value3",
              "text"  : "Choice 3"
            },
            {
              "name"  : "Choice 4",
              "value" : "value4",
              "text"  : "Choice 4"
            },
            {
              "name"  : "Choice 5",
              "value" : "value5",
              "text"  : "Choice 5"
            }
          ]
        }
      },
      onResponse: function(response){
      	console.log('here is the response');
      	console.log(response);
      },
      saveRemoteData: false,
      fullTextSearch: 'exact',
      direction: 'auto',
      debug: true,
      performance: false
});

```

and then adding `onResponse()` right after the response but that did not work as well. Please open up this issue again

**Comment by enix223** [comment]
I got the same issue, anyone could help?

**Comment by enix223** [comment]
I have forked this repo & done some enhancement to support local search with remote API content.

If you have the same issue, have a look at my commit [here](https://github.com/enix223/Semantic-UI/commit/9efa3234880e6d1f7fd802a2872cf37e456fa24e) .

localSearch is default to true, so every api remote data will be search and filtered as expect.

If you need to turn this function off, simply set it to false as below:

```
$modelDropdown.dropdown({
  apiSettings: {
    url: '/api/data.json'
  },
  fields: {
    name  : 'name', // displayed dropdown    
    value : 'id'         // actual dropdown value
  },
  localSearch: false,
});
```

**Comment by ShukriChiu** [comment]
@enix223  can you pull request your edit ? it works well

@jlukic please reconsider this issue

**Comment by enix223** [comment]
@ShukriChiu had created a pull request #4815 as per your request. :-) #

**Comment by coder8keyboard** [comment]
It looks like onChange is not firing for 'set selected' on remote data. non-remote data works fine. Looks like a bug.
