### ISSUE TITLE
[Api] Gulp Buil Error

### ISSUE THREAD

**Issue by berkaybeyaz1** [Semantic-Org/Semantic-UI#4137]
Hello everyone, I'm writing ``gulp build`` console and after the console give me error.
error screen shot : 
![error](https://cloud.githubusercontent.com/assets/7584428/16173437/3f7d4e32-35aa-11e6-85fa-ca7d6d75218f.PNG)
thank you :smile:

**Comment by alwaystrong** [comment]
have a try:
`npm uninstall gulp-header
npm install gulp-header@1.8.2`

**Comment by mcrawshaw** [comment]
That worked for me.

**Comment by BruceMa7** [comment]
It works.

**Comment by nicbarker** [comment]
Confirmed this is broken for me too.

**Comment by HitomiTenshi** [comment]
Broken for me as well.

**Comment by clocked0ne** [comment]
This is fixed now in Gulp header, you can remove the specific dependency.

**Comment by berkaybeyaz1** [comment]
Thank you, im fixed, just need that change gulp header version from package.json

**Comment by bretonio** [comment]
Also me with `gulp build` 

In my case, the misbehavior is in `gulp-chmod`  ...

```bash
/home/bretonio/Harp-Iniciatives/harp-semantic/node_modules/gulp-chmod/index.js:2
const through = require('through2');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bretonio/Harp-Iniciatives/harp-semantic/semantic/tasks/watch.js:14:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
I selected "no" for setting permissions during the first guided install and  then tried again with "yes." 

No joy.  Rebuilding again I receive the message ´gulp-chmod@2.0.0 wanted but I have already uninstalled this module and `npm i gulp-chmod@2.0.0´ as you guys suggested in your case.

By the way, I am running ´gulp build´ in ´/semantic´ and not in ´/node_modules/semantic-ui´.

When I run it in the latter there is no problem. 

Am I going to reference the latter in my stylesheets and so on? I found the setup instructions a little vague on this point.

**Comment by fijixfiji** [comment]
@bretonio 
I also probably faced the same problem.
In my case, the reason was that the version of node was old.

Did the following sentences appear in the installation log?
```
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"v0.10.46","npm":"1.3.6"})
```
For `gulp-chmod` of semantic-ui, the version of node must be 4 or higher.

After updating the version of node v0.6.9, I could `gulp-build` properly without error, in my case.
