### ISSUE TITLE
[Icon] Add `cloud checkmark`

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#4141]
I made a request at https://github.com/FortAwesome/Font-Awesome/issues/9404#issuecomment-226408527, and it appears we can already do it with Font-Awesome and stacking icons.  Semantic's use of Font-Awesome doesn't seem to expose the stacking stuff though.  If there was a way to expose `cloud checkmark` as a valid icon that would be awesome.

**Comment by HitomiTenshi** [comment]
There's no need in adding a cloud checkmark as you can group icons together in semantic-ui.

See: http://jsfiddle.net/Ly8yug5e/1/

Just make sure to make the cloud bigger than the checkmark.
See icon sizes in the doc: http://semantic-ui.com/elements/icon.html#/definition

**Comment by daneren2005** [comment]
Alright I will use that then thank you
