### ISSUE TITLE
[Icon] File Image Outline Icon - Applies image style

### ISSUE THREAD

**Issue by icelord2** [Semantic-Org/Semantic-UI#4145]
**Steps to Reproduce**
1. Add the File Image Outline icon

notice since the icon has image in its class name it applies the following
.ui.header>.image, .ui.header>img {
    display: inline-block;
    margin-top: .14285em;
    width: 2.5em;
    height: auto;
    vertical-align: middle;
}

**Expected**
The width should be the same as the icon

**Result**
The Icon is applying the image style making it wider which can put it on a new line

**Testcase**
<i class="file image outline icon" ></i>

**Comment by selenir** [comment]
Overriding styles with
```
.ui.header>i.image {
  display: table-cell;
  margin-top: 0;
  width: auto;
}
```
should do the trick. I haven't dug in less files yet.

**Comment by yaboi** [comment]
The fix for this is to add `:not(.icon)` to line 82 in `src/definitions/elements/header.less`. Code would look like this:

```
.ui.header > .image:not(.icon),
.ui.header > img {
  display: inline-block;
  margin-top: @imageOffset;
  width: @imageWidth;
  height: @imageHeight;
  vertical-align: @imageAlignment;
}
```

**Comment by jlukic** [comment]
Thanks for your patience here. The fix you suggested is quite reasonable. Added in `2.2.8`
