### ISSUE TITLE
Dropdown items does not show correctly when parent element has overflow as hidden

### ISSUE THREAD

**Issue by MEspino** [Semantic-Org/Semantic-UI#4149]
I'm trying to create a menu component using Semantic-UI, the menu has in it an item with several dropdowns. The set of dropdowns has a vertical scroll (because I could have one or ten). The scroll works fine, but, in order to show a custom scroll button, I have to set the overflow property as hidden, the problem is that when the property has that value, the items in the dropdown menu doesn't show properly.

Please find the example code in the following fiddle link

[https://jsfiddle.net/ft4jhvcn/1/](https://jsfiddle.net/ft4jhvcn/1/)

Thanks in advance.

**Comment by bdlee** [comment]
I have a similar issue with dropdowns in a fixed vertical menu. I would like to be able to apply an overflow-y property of auto/scroll, but then the dropdown menu does not display properly

**Comment by QaysAlghazali** [comment]
I have the same issue 
<img width="507" alt="bugggg" src="https://user-images.githubusercontent.com/47455648/57549653-c192fd80-7329-11e9-909a-5d4a8a1cabbd.PNG">

it makes the parent div scroll-able

**Comment by xthree** [comment]
I too am having this issue. I have a dropdown at the bottom of a modal with a 'scrolling content' element. 

This is what happens
![image](https://user-images.githubusercontent.com/3744150/75079180-1e306500-54c5-11ea-84d6-e8af491994f6.png)

This is what happens when I use a regular content element, this is the result I need in a scrolling modal
![image](https://user-images.githubusercontent.com/3744150/75079236-47e98c00-54c5-11ea-9911-e4a51f858c27.png)

**Comment by blackhill** [comment]
Did anyone found a solution?

**Comment by Moseyza** [comment]
I have same problem.
running example [hear](https://jsfiddle.net/6xez4Lj0/)

**Comment by MEspino** [comment]
This was a while ago and I didn't get any reply from Semantic Team, but if I recall correctly I had catch the event of the click, and find the element and re-assign the context of option list outside the menu.

**Comment by blackhill** [comment]
Manuel, could you find the code again or its lost forever? ;)

**Comment by MEspino** [comment]
@blackhill 

Doing a quick search seems like context property is removed from JQuery version 3

[W3 Schools](https://www.w3schools.com/jquery/prop_context.asp)

`The context property was deprecated in version 1.8 and removed in jQuery version 3.0.`

[JQuery API Docs](https://api.jquery.com/context/)
`Note: This API has been removed in jQuery 3.0.`

But here is a pretty lame try to replicate the fix, you have to play with style and location (margin) to make the element appears below the menu.

https://jsfiddle.net/nahd9ckr/31/

**Comment by MEspino** [comment]
@bl
