### ISSUE TITLE
[Dropdown] Dropdown menu item should open upwards if there is not enough room on the screen

### ISSUE THREAD

**Issue by gdaunton** [Semantic-Org/Semantic-UI#4150]
The auto upward/downward open is not working correctly with the vertical menu item variation.

The issue is present in the [documentation](http://semantic-ui.com/collections/menu.html#dropdown-item) and is displayed by all of the dropdown items on the page.

**Comment by jlukic** [comment]
Im probably being pretty dull, but can you elaborate on how to reproduce? Does this require a menu with enough items to cause it to be off screen to the bottom but not the top?

**Comment by gdaunton** [comment]
Yeah.

So right now on the doc page, the dropdown menu items are going off screen.
<img width="1280" alt="screen shot 2016-06-26 at 6 39 46 pm" src="https://cloud.githubusercontent.com/assets/8468455/16365414/6824f8d4-3bcd-11e6-97a5-ea367f488cc6.png">

Instead of opening upward. 
<img width="1280" alt="screen shot 2016-06-26 at 6 41 52 pm" src="https://cloud.githubusercontent.com/assets/8468455/16365421/b583a170-3bcd-11e6-845e-a4d15cfc299a.png">
