### ISSUE TITLE
please fix permissions of fonts made executable to 644

### ISSUE THREAD

**Issue by cordoval** [Semantic-Org/Semantic-UI#4152]
They are executable right now, they should be:

/node_modules/semantic-ui-less/themes/default/assets/fonts/icons.eot

```
0 cordoval  staff     340 Jun 21 22:25 ..
-rw-r--r--   1 cordoval  staff   60767 Jun 21 22:25 icons.eot
-rw-r--r--   1 cordoval  staff   93888 Jun 21 22:25 icons.otf
-rw-r--r--   1 cordoval  staff  313398 Jun 21 22:25 icons.svg
-rw-r--r--   1 cordoval  staff  122092 Jun 21 22:25 icons.ttf
-rw-r--r--   1 cordoval  staff   71508 Jun 21 22:25 icons.woff
-rw-r--r--   1 cordoval  staff   56780 Jun 21 22:25 icons.woff2
```

**Comment by jlukic** [comment]
You can set what permissions you want for outputted files when using our build tools
https://github.com/Semantic-Org/Semantic-UI/blob/master/semantic.json.example#L20

**Comment by cordoval** [comment]
yeah for some reason this slight change does not work on my deploys, it is something else, just weird that it happens in that way. I also use semantic-ui-less and not the other main distribution.

**Comment by jlukic** [comment]
I think the permissions in the `node_modules` folder would be determined by npm and not related to the filemode on GitHub but I could be wrong.

**Comment by cordoval** [comment]
i just chmod 644 and committed files, thanks

**Comment by cordoval** [comment]
This was changed at some point, just wondering when that happened.
