### ISSUE TITLE
modal close not work in semantic-ui 1.12.2

### ISSUE THREAD

**Issue by KhadeerUI** [Semantic-Org/Semantic-UI#4158]
Hi,

When i try to click close icon and buttons modal not closing in semantic-ui 1.12.2 version. Please give me suggestion it's urgent. See this example - http://jsfiddle.net/b1sf6oxu/21/

**Comment by vinayakkulkarni** [comment]
jsFiddle doesn't work.

I would urge you to upgrade to latest SUI version.

Closing this for now, if you still have issue with latest SUI, can be re-opened.
