### ISSUE TITLE
Incompatibility with jQuery 3 - deprecated size() function is gone

### ISSUE THREAD

**Issue by noobiwan** [Semantic-Org/Semantic-UI#4160]
Hi friends, it seems Semantic-UI is not yet compatible with jQuery 3. I was trying to use form validation and got the following error:

>  semantic.js:868 Uncaught TypeError: $label.size is not a function (semantic.js:868)

The problem is that .size() is deprecated since jQuery 1.8 and we should use .length

> The .size() method is deprecated as of jQuery 1.8. Use the .length property instead.
> 
> The .size() method is functionally equivalent to the .length property; however, the .length property is preferred because it does not have the overhead of a function call.
> 

https://api.jquery.com/size/

Is there a reason the code wasn't updated yet?

How does the team stand on that?

**Comment by jlukic** [comment]
It's fixed in `next` the code hasnt been release yet.
