### ISSUE TITLE
Clicking a menu dropdown item should close it to improve mobile user experience

### ISSUE THREAD

**Issue by magestican** [Semantic-Org/Semantic-UI#4162]
I think that when you click a menu dropdown item or sub menu dropdown item it should close it, this way it becomes really easy to navigate through menus in a small screen.
I would like to help implement this, any idea where to begin?

**Comment by Banandrew** [comment]
Hi @magestican, there’s `action: 'hide'` property that does exactly this, can you please confirm?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
