### ISSUE TITLE
[Form Validation] Associative arrays as field names doesn't work properly

### ISSUE THREAD

**Issue by mzygmunt** [Semantic-Org/Semantic-UI#4163]
Field names like "test[]" works fine, but names like "test[en]" doesn't work. In this case Form Validation returns simple string "test[en]" instead of array.

**Comment by jlukic** [comment]
Thanks a lot for filing this issue, and including an easy to understand test case. I've added a milestone, and will try to take a look as soon as I can.

**Comment by jlukic** [comment]
I've fixed this, but by going a slightly different direction. The main reason it was failing with associative arrays was it was attempting to find an id tag first using an invalid value, which I know check for 6e88af1

**Comment by jlukic** [comment]
I've gone a slightly more generic route this also solves using identifiers like `identifier: 'value\''
