### ISSUE TITLE
Search - Data source other than HTTP/local?

### ISSUE THREAD

**Issue by bali182** [Semantic-Org/Semantic-UI#4170]
I'm trying to use Google's location [autocomplete service](https://developers.google.com/maps/documentation/javascript/reference#AutocompleteService) together with the Semantic search component, but I can't seem to find a way to provide a data source other than an url and local data. I was wondering if something like this is possible:

```js
$('#search-field').search({
  query: searchTerm => new Promise((resolve, reject) => {
    acService.getPlacePredictions({input: searchTerm}, results => {
      // let's say results is in an OK format format for autocomplete
      return results;
    })
  })
})
```

Or maybe

```js
$('#search-field').search({
  query: (searchTerm, onSuccess, onError) => {
    acService.getPlacePredictions({input: searchTerm}, (results, status) => {
      if(status !== 'OK') {
        onError(status);
      } else {
        // let's say results is in an OK format format for autocomplete
        onSuccess(results);
      }
    })
  })
})
```

If not, is there a workaround? I'm thinking of something like:

1. Setting local content to an empty array
2. Callback for user typing ( maybe `onSearchQuery`?)
3. In callback do the custom async task
4. When that returns, change the local data
5. Show the dropdown manually

```js
$('#search-field').search({
  content: [], // empty local results initially
  onSearchQuery: query => acService.getPlacePredictions({input: query}, (results, status) => {
    // change the local contents, which I don't know if possible / how to do
    // show the dropdown, which I also don't know how to do
  }
});
```

Is this possible somehow?

Thank you,
Balazs

**Comment by bali182** [comment]
**Update**

I tried it according to the "Behaviors" part of the [docs](http://semantic-ui.com/modules/search.html#/usage):

```js
// It's a react component
componentDidMount() {
  const $searchComponent = $(this.refs._search);
  $searchComponent.search({
    source: [], //empty source by default
    onSearchQuery(query) {
      $searchComponent.search('cancel query'); // cancel default behaviour
      geocode({ input: query }).then(results => {
        // build the suggestions list
        const suggestions = results.map(place => ({ title: place.description }));
        $searchComponent.search('generate results', suggestions); // set the new local data
        $searchComponent.search('show results'); // show
      })
    },
  })
}
```

But it doesn't seem to do anything for the `.search(method)` calls, cancel/generate/show doesn't seem to do anything. Am I doing something wrong?

**Comment by bali182** [comment]
**Update 2**

Ok, I managed to figure it out:

```js
const $searchComponent = $(this.refs._search);
$searchComponent.api({
  responseAsync(settings, callback) {
    const query = settings.urlData.query;
    geocode({ input: query }).then(places => callback({
      results: places.map(place => ({ title: place.description }))
    }));
  }
}).search({ /* other config, like searchDelay */ })
```

Can I help adding an example about this to the docs? It would have saved me roughly a day.

**Comment by jlukic** [comment]
API is a fairly complex module and a lot of its documentation remains separate from the components that use it. I'd be willing to accept PR on the docs repo for anything that enhanced others understanding of using API.
