### ISSUE TITLE
API Response of JSON type gets returned weirdly

### ISSUE THREAD

**Issue by ravishhacker** [Semantic-Org/Semantic-UI#4171]
On my page I have setup api for tab to load data from REST server. Even thought the data is marked as application/json on response from server. response from jquery is still string. 
This means below code in semantic.js file at 18882 line (uncompressed) is causing the response to become like {0:"r",1:"e"....}

? settings.onResponse.call(context, $.extend(true, {}, response))

I am not sure what is wrong, but it seems like it is not good idea to always extend response with {}.
It may not be an issue, but thought I will mention it here to get everyone's views.

Let me know if you need more information.

Server returns with below headers:
X-BACKEND →apps-proxy
content-length →1727
content-type →application/json
date →Sun, 26 Jun 2016 14:40:50 GMT
last-modified →Thu, 23 Jun 2016 10:17:57 GMT
server →Eve/0.6.4 Werkzeug/0.11.3 Python/2.7.6
x-total-count →6

Response is something similar to:
{"_items": [{"_updated": "Thu, 23 Jun 2016 10:17:48 GMT", "camera": 0,.....}

And when at onResponse for api I get following:
Object {0: "{", 1: """, 2: "_", 3: "i", 4: "t", 5: "e", 6: "m", 7: "s", 8: """, 9: ":", 10: " ", 11: "[", 12: "{", 13: """, 14: "_", 15: "u", 16: "p", 17:...}

Let me know if you need more information.

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
