### ISSUE TITLE
Question: UI-State with React

### ISSUE THREAD

**Issue by abogdan0505** [Semantic-Org/Semantic-UI#4172]
What about the state component how do we use it with react?. Its not on NPM. I'm trying to use it for menu items with react and it doesn't seem to work . I've been working with semantic for a while but i'm new to react. It doesn't seem to be included in version 2.2 either.
Can anyone take a look at this ? 
The css works fine but the active state of the items doesn't change.
This doesn't throw and error but it doesn't work either:

```
import React, { Component } from 'react'

import $ from 'jquery'
import jQuery from 'jquery'
window.jQuery = jQuery

import 'semantic-ui-menu/menu.css'
import 'semantic-ui-item/item.css'

var state = require('semantic-ui/dist/components/state')

export default class Nav extends Component {

  constructor(props) {
        super(props)
    }

    componentDidMount() {
        $('.item').state()
    }

    render() {
      return (
        <div>
            <div className="ui secondary pointing menu">
                <a className="active item">
                    Home
                </a>
                <a className="item">
                    Messages
                </a>
                <a className="item">
                    Friends
                </a>
                <div className="right menu">
                    <a className="ui item">
                        Logout
                    </a>
                </div>
            </div>

        </div>
      )
    }
}
```

**Comment by levithomason** [comment]
@abogdan0505 and any others landing here, there is now React support.  There is now an officially supported Semantic-UI-React project that implements components in the React paradigm without jQuery: https://github.com/TechnologyAdvice/stardust

I'll soon port it to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React).

Cheers
