### ISSUE TITLE
Television Icon

### ISSUE THREAD

**Issue by EQuimper** [Semantic-Org/Semantic-UI#4178]
Hey, I would like to know what happen with the television icon. I find it into your doc but this is a blank icon.

**Comment by jlukic** [comment]
Looks like it has disappeared. Time to investigate

**Comment by xaeroseven** [comment]
I noticed this as well.  It looks like 'tv icon' works in the meantime @EQuimper.

**Comment by EQuimper** [comment]
@xaeroseven `tv icon` don't work for me.

**Comment by xaeroseven** [comment]
@EQuimper here is a fiddle I made from the boilerplate fork example: http://jsfiddle.net/1bemvetf/, it's using 2.2.1 and `tv icon` looks to be working in my fiddle at least.  I haven't tried upgrading our Semantic 2.1.8 project yet to 2.2.1 so there might be an issue once I have everything built.  Sorry for the mislead on it

**Comment by awei01** [comment]
I'm haven't dug into the css generation code, but I suspect there's an issue with the less files. Looking at `semantic-ui-css` generated code, this is the result for `grab` and `television` icons. Notice the `:before` is missing after `grab` and `television`. Hopefully this will help someone track down the error in the less files. 

```
i.icon.grab {
  content: "\f255";
}
i.icon.hand.victory:before {
  content: "\f25b";
}

/* truncated */

i.icon.television {
  content: "\f26c";
}
```

**Comment by jlukic** [comment]
Thanks @awei01 that helped a bit narrowing it down.

**Comment by awei01** [comment]
@jlukic sure, np.
