### ISSUE TITLE
search module clear input after selection

### ISSUE THREAD

**Issue by brunotourinho** [Semantic-Org/Semantic-UI#4179]
hey there!
can you help me figure out a way to clear the search input after select the value... i tried return false, but the results wont close, tried onResultsClose but didn't work either.

**Comment by fomojola** [comment]
Leaving this here for anyone else who is looking: if you created your search like this:

```
var element = $('.ui.search');
element.search({});
```

then

```
element.search("set value", "");
element.search("query");

```
will clear the input and hide the dropdown.
