### ISSUE TITLE
[Shape] Shape new settings not working

### ISSUE THREAD

**Issue by vinh123456789** [Semantic-Org/Semantic-UI#4181]
Hi, i just tried the new shape settings, but it not working when i set width and height to "next". Browser's console display this error "$nextSide is undefined".
http://jsfiddle.net/nufdffts/1/

**Comment by jlukic** [comment]
There are a few bad bugs in shape it appears. I'm not sure how this got through. I'll try to solve quickly

**Comment by jlukic** [comment]
Fixed issues with next breaking. Variable order was incorrect..

The animations appearing incorrectly only occurs in jQuery 3.0. I'm not sure the cause. Investigating now.
