### ISSUE TITLE
Popup Example includes Not Supported Data-Delay

### ISSUE THREAD

**Issue by dorsha** [Semantic-Org/Semantic-UI#4182]
First, thanks for the new 2.2.x release, it is really great.

I'm trying to use the CSS-Only tooltips ability that was added.
This is  my code (according to the documentation):
```
      <div
        onClick={this.onButtonClick}
        data-tooltip="some text"
        data-position="bottom right"
        data-delay="2000"
      >
        <i className={iconClasses} />
      </div>
```

I also tried with `data-delay={2000}` (as number)

It seems that it does not work, the popup is shown immediately (It does not work also in your examples with `500` delay).

Am I missing something?

**Comment by antonkulaga** [comment]
I have the same problem

**Comment by jlukic** [comment]
`data-delay` is not supported in CSS only tooltips. `transition-delay` does not support `attr()` syntax, so there is no way to do this without javascript. It was something I experimented with but realized is not possible.

I'll fix the docs to compensate.

**Comment by jlukic** [comment]
I've removed `data-delay` from docs in the next release.
