### ISSUE TITLE
[Dropdown] Changing delimiter of the multiselect input 

### ISSUE THREAD

**Issue by robinsondotnet** [Semantic-Org/Semantic-UI#4186]
Now this is the way is filling the input :
`                        <input name="multipleElement" type="hidden" value="value1, value2">
`
Is it possible to change it to:
`                        <input name="multipleElement" type="hidden" value="value1; value2">
`

**Comment by jlukic** [comment]
The setting has the exact name you would guess
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3503
