### ISSUE TITLE
Tag Input

### ISSUE THREAD

**Issue by jamland** [Semantic-Org/Semantic-UI#419]
Can't find multi input like this in docs... That's not hard to create it myself but i think would be cool to have some default element/module.

![0 0 0 0_3000__](https://f.cloud.github.com/assets/188568/1712389/63740ed4-6172-11e3-8ecb-b4b6b0ed6a3f.png)

**Comment by esbanarango** [comment]
:+1:

**Comment by jlukic** [comment]
Multiselect in 2.0 supports user tagging

**Comment by The-Penultimate-Defenestrator** [comment]
Is this available from the search module? I don't see a way to do this with any elements besides dropdown, but the screenshot in the original issue shows a searchbar.

**Comment by shahidbasheer** [comment]
@jlukic is there option to insert new text tag if it is not available in the options list.

**Comment by jlukic** [comment]
Dropdown works with `api` to let you handle large lists

**Comment by Banandrew** [comment]
@Janatbek You can’t, order manipulation is a known enhancement—I can’t find the issue right now, but it’s there. You could get values from the dropdown, manipulate them, then `set exactly` using the new array.

**Comment by khan990** [comment]
Try using https://semantic-ui.com/modules/dropdown.html

```
<div class="ui loading fluid multiple search selection dropdown">
  <input type="hidden" name="country" value="kp">
  <i class="dropdown icon"></i>
  <input class="search">
  <div class="default text">Search...</div>
  <div class="menu">
    <div class="item">Choice 1</div>
    <div class="item">Choice 2</div>
    <div class="item">Choice 3</div>
  </div>
</div>
```

**Comment by Berger92** [comment]
Here's my solution based on vuejs, enjoy!
[JsFiddle](https://jsfiddle.net/Berger92/vz5ummn2/)

**Comment by khan990** [comment]
@deshario, hope this helps


![2020-08-24 09-21-01 2020-08-24 09_21_56](https://user-images.githubusercontent.com/2551269/91015419-6868df00-e5eb-11ea-93b4-14d4064b86d4.gif)


Write a new text and press enter. And try to check the version that you are using.

**Comment by deshario** [comment]
@khan990 What version are you using?

**Comment by khan990** [comment]
@deshario I recorded gif from https://semantic-ui.com/modules/dropdown.html#/examples. It should be 2.4.
