### ISSUE TITLE
tooltip sizes do not seem to work

### ISSUE THREAD

**Issue by antonkulaga** [Semantic-Org/Semantic-UI#4190]
In
```html
<div data-tooltip="some tooltip" data-delay="5000" data-position="bottom left" data-variation="tiny"
>some text</div>
```
delay and variation options do not have any effect. Note: I use version 2.2 (the one from the webjar), if it was fixed in an unpublished version - let me know.

**Comment by jlukic** [comment]
Tooltips are new in 2.2, they do not support sizes. You'll need to use `data-content` and `.popup()` initialization.
