### ISSUE TITLE
Conflict with Bootstrap JS Library /  I Want to use Semantic-UI dropdowns inside of Bootstrap framework

### ISSUE THREAD

**Issue by aguyinmontreal** [Semantic-Org/Semantic-UI#4191]
Ok guys,

I want to use Semantic-UI's forms, dropdowns and progress bars instead of the Bootstrap ones.

I added the form.css, form.js, dropdown.css, dropdown.js, progress.css and progress.js libraries to my Bootstrap project and activated the dropdowns with: 
`$(document).ready(function(){
        $('.ui.dropdown')
                .dropdown();
        $('.ui.search.dropdown')
            .dropdown({
                maxSelections: 2
            });
    });`

At that point the dropdowns didn't work. They were frozen.

**I had to add the full semantic-UI libraries (semantic.css and semantic.js) to make the dropdowns work. But now, when I resize the page's window, the Bootstrap framework dosen't hold anymore and all my html elements act crazy and go everywhere around the page.**

How do I fix that? Thanks!

**Comment by zubinmehta** [comment]
+1

**Comment by aguyinmontreal** [comment]
not fixed

**Comment by w96k** [comment]
@aguyinmontreal Can you reproduce your problem on jsfiddle or any similar resource? This way its much easier to help you.

**Comment by aguyinmontreal** [comment]
@w96k sorry for the confusion / the stale bot is driving me nuts, trying to close things that shouldn't be closed / however, foe this one the bot is right

I'm closing the issue
