### ISSUE TITLE
[Sidebar] Sidebar still occupies space on page when closed

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#4197]
While using the jquery-ui draggable feature, I noticed that dragging an item outside of the browser window would cause the space the sidebar occupies to come into view. I see that the sidebar uses `visibility : hidden` instead of `display : none`. Is there a specific reason for this? If not, would it be possible to change how the sidebar is being hidden as this edge case can be quite annoying.

**Comment by philrykoff** [comment]
You could hook into the `onVisible` and `onHidden` callbacks and set the `display` property yourself.

**Comment by fpayer** [comment]
Yah, that's a workaround. It would be cleaner to have semantic do it. I was wondering if there was any particular design decision regarding this. If not, I feel like changing the sidebar's css to use `display : none` may benefit some other people as well.
