### ISSUE TITLE
Dropdown does not work with Angular ngIf 

### ISSUE THREAD

**Issue by MichaelARoberts** [Semantic-Org/Semantic-UI#4198]
Not sure if there is a conflict with Angular and Semantic, or something that I'm doing wrong, but when a Semantic dropdown is placed in a ngIf the dropdown fails to work.

Example [here](https://jsfiddle.net/enyp432r/18/)

Notice that when the dropdown is placed outside the ngIf it works perfectly fine.

**Comment by jacquesgingras** [comment]
I experienced the same issue. This also happens if the you the ng-If on the dropdown div itself.

**Comment by subramn** [comment]
I am also facing the similar issue any workaround available?
