### ISSUE TITLE
[Bug] Extra blank space when using grid system between 320-400px screen width

### ISSUE THREAD

**Issue by lustan3216** [Semantic-Org/Semantic-UI#4199]
This bug still exists even after taking off the navbar and the css file. 

http://jsfiddle.net/1w7fwwed/
<img width="471" alt="2016-07-01 1 49 47" src="https://cloud.githubusercontent.com/assets/12712127/16499228/041ce744-3f32-11e6-91e5-8108504642ef.png">
<img width="528" alt="2016-07-01 2 13 18" src="https://cloud.githubusercontent.com/assets/12712127/16499229/04229838-3f32-11e6-8fd4-35bd658b64d0.png">

**Comment by jlukic** [comment]
You've only wrapped part of your page in a `container`. Wrapping the entire page in a container and removing padding from `body` will solve your issue.
http://jsfiddle.net/82myjr38/
