### ISSUE TITLE
[Menu] - cursor: pointer

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#4201]
``` html
<div class="ui three item menu">
  <a class="active item">Editorials</a>
  <a class="item">Reviews</a>
  <a class="item">Upcoming Events</a>
</div>
```

I don't think active item should have `cursor: pointer` on hover - it's already selected, is it not?

**Comment by IonutBajescu** [comment]
Not sure how important it is, but some people use the "active" element to refresh the page.
