### ISSUE TITLE
Webpack integration :improvement:

### ISSUE THREAD

**Issue by magestican** [Semantic-Org/Semantic-UI#4202]
I managed to somehow integrate 2.1.1 into my application using webpack, but version 2.2 which uses the new jquery 3.0 breaks everything, could you write documentation explaining how to integrate 2.2 with webpack ? 
Webpack is quite popular, particularly for react projects so I say semantic ui should have a guide for it.

**Comment by emzero** [comment]
I'm also struggling to integrate semantic-ui in a React/Webpack project.

**Comment by IonutBajescu** [comment]
Merging into #4195.
