### ISSUE TITLE
Modal blur has glitches on firefox

### ISSUE THREAD

**Issue by erkidhoxholli** [Semantic-Org/Semantic-UI#4208]
I noticed that when I set {blurring: true} on a modal, one panel below the modal moved about 100px on the top. I had to refresh, to put it back where it was.I tested it in firefox v47.It works well in chrome though.

After setting {blurring:false} everything works fine on all browsers.
If you want any more info (images etc) I cann provide it.Thanks!

**Comment by jlukic** [comment]
Blurring uses `filter` which is GPU dependent, which unfortunately varies based by browser and can sometimes have rendering issues. 

I'd recommend avoiding `blur` unless you are comfortable with the risks in rendering incorrectly. You might also experiment with using `will-change: transform;` to narrow down the rendering context.
