### ISSUE TITLE
High density flag assets

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI#4210]
Flag assets file should be either an SVG or have a @2x version for retina displays.

**Comment by lfilho** [comment]
This is probably a dupe of #1240 But I agree and +1'd it! :)

**Comment by lubber-de** [comment]
For version 2.9 of the active community fork Fomantic-UI, the sprite flags are going to be replaced by the same SVG icons as already available for the [emoji component](https://fomantic-ui.com/elements/emoji.html)
https://github.com/fomantic/Fomantic-UI/pull/1190
