### ISSUE TITLE
Tooltip break style of other element

### ISSUE THREAD

**Issue by Dielz98** [Semantic-Org/Semantic-UI#4213]
Just hover over the button:

https://jsfiddle.net/6nvtL8jf/

And it seems tooltip doesn't support long text

**Comment by pierre-weceipt** [comment]
I also noticed that you can't have tooltips on icons and it breaks ribbon labels : 
https://jsfiddle.net/vprpgc7s/2/

**Comment by jlukic** [comment]
Tooltips use `:before` and `:after` pseudo class. Any elements that already use these pseudo classes will appear broken. Use a separate `span` or `div` for the tooltip to fix. 

See the warning note in [popup docs](http://semantic-ui.com/modules/popup.html#tooltip)
