### ISSUE TITLE
[Popup] Popup without round corners

### ISSUE THREAD

**Issue by fpayer** [Semantic-Org/Semantic-UI#4214]
There does not seem to be a popup variation that does not have rounded corners. Would it be possible to create one that does not round the corners in the popup?

**Comment by Thantifaxath** [comment]
**fpayer**, you can always use your own CSS rules.
If you want to disable rounded corners in every popup just use this code:

`
.ui.popup {
    border-radius: 0;
    -moz-border-radius: 0;
    -webkit-border-radius: 0;
}
`

In case you want a specific one, check this:
http://jsfiddle.net/efp8z6Ln/346/

**Comment by jlukic** [comment]
Also another 1 line fix. Variables!
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/popup.variables#L22
```less
@borderRadius: @defaultBorderRadius;
```
