### ISSUE TITLE
sidebar slider

### ISSUE THREAD

**Issue by sameermalik** [Semantic-Org/Semantic-UI#4216]
Hi Semantic-Ui Team,
I hope you're doing great and the effort you put to make this framework to happen is awesome however i used the slide bar as u mentioned but whenever i click on menu(which shows sidebar) the web page stays static(i cant scroll after click on sidebar shower) also footer( which have flex in css) seems to be off.
please acknowledge with a best answer.
here is the code sample.
```
<body>
<!-- Mobile version -->
<div class="ui sidebar inverted vertical menu">
  <a class='item'>home</a>
  .
  .
  .
</div>

<!-- Mobile version Menu button only -->
<div class="ui top fixed menu ">
  <a class='item'> <i class="fa fa-bars" aria-hidden="true"></i>Menu
  </a>
</div>

<!-- Desktop version -->
<div class="ui top borderless fixed large pointing menu">
  <a class='item'>home</a>
  .
  .
  .
</div>

<div class='dimmer'>
  <div class="site-content">
    <!-- contends -->
  </div>

  <footer>
      <!-- content -->
  </footer>
</div>

</body>
```

**Comment by IonutBajescu** [comment]
Hey,

I appreciate you taking the time to describe your problem.

However, the Github Issue Tracker is not the right place to ask questions. If you want your question to have maximum visibility, you should instead post it on the forum, which is located at [forums.semantic-ui.com](http://forums.semantic-ui.com).
