### ISSUE TITLE
'ui simple scrolling dropdown' doesn't work - overflow is visible

### ISSUE THREAD

**Issue by franciscolourenco** [Semantic-Org/Semantic-UI#4219]
Overflow is visible:
https://jsbin.com/lezekicizo/edit?html,output

**Comment by emzero** [comment]
The simple dropdown example from the docs doesn't have a `scrolling` class.
http://semantic-ui.com/modules/dropdown.html#simple

Removing the `scrolling` class fixed the overflow.

If you want a `scrolling`dropdown follow the proper example: 
http://semantic-ui.com/modules/dropdown.html#scrolling

**Comment by aristidesfl** [comment]
I was under the impressions classes were supposed to be combined.

So this would be a enhancement proposal to support other dropdown options like `scrolling` in combinations with `simple`, since javascript is not strictly needed to implement a `scrolling dropdown`.

**Comment by vsiv** [comment]
+1 on @aristidesfl request

**Comment by lubber-de** [comment]
Prepared for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/718
