### ISSUE TITLE
[Form] Form Validation Behavior is not as expected

### ISSUE THREAD

**Issue by zhaoyao91** [Semantic-Org/Semantic-UI#4221]
The expected behavior is:
when the user submits the form (or blur the field if set on=blur), the validation will be triggered and the form errors will be shown. and after your correct the error field, the error should dismiss directly (or after blur the filed).

But by now, there seems some bug. If I set on=blur, only the field color is updated after blur, the form errors messages are maintained until another form submit is triggered.

**Comment by zhaoyao91** [comment]
and if I call `validate form` or even `is valid` in onValid callback, it will cause dead loop

**Comment by zhaoyao91** [comment]
if a `search dropdown` is in a form and you get error when you are tying
```
form.js:834 Uncaught TypeError: Cannot create property 'identifier' on boolean 'false'
```

**Comment by wunderBarr7** [comment]
@zhaoyao91 When initializing your form fields did you make sure that the 'identifier' property was set to reference the `input` and not the `div`? 

I was receiving the same error until I changed the 'identifier' property to reference the `input`.

**Comment by wenweih** [comment]
@zhaoyao91 how to fixed the error when there is search dropdown in form
