### ISSUE TITLE
[Dropdown] Remote content combined with <select multiple> causes incorrect selections

### ISSUE THREAD

**Issue by nandastone** [Semantic-Org/Semantic-UI#4226]
http://jsfiddle.net/bopdpL5e/1/

The third (red) dropdown shows the bug in action. Selecting an option appears to swap the remaining results to the values of the selected items. It all gets a bit messed up after that.

![screen shot 2016-07-06 at 4 24 25 pm](https://cloud.githubusercontent.com/assets/199204/16609269/24f69434-4396-11e6-81b2-123017be4751.png)

**Comment by jlukic** [comment]
This has been fixed in `2.23`, either from #4344 or #4316
