### ISSUE TITLE
I want to use just the Grid, but Semantic-UI forcing all sorts of defaults

### ISSUE THREAD

**Issue by arggh** [Semantic-Org/Semantic-UI#4228]
I wanted to use Semantic-UI Grid by importing only the grid component in my project, like so:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.1/components/grid.min.css">
```

It didn't work, so I made some research and found out I also have to include the semantic.css.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/g/semantic-ui@2.2.1(components/grid.min.css+semantic.min.css)">
```

Now the grid works, but also the rest of my styles are now ruined by **semantic.css forcing different sizes, fonts and whatnot over my own stylesheets.**

**How can I get just the grid, please?** Am I forced to generate my own build of Semantic-UI with just the grid and all default values in semantic.css modified accordingly to my project?

**Comment by anantoghosh** [comment]
Some resets are missing that's all
include `reset.min.css` *before* using the `grid.min.css`
or add
```css
html {
  box-sizing: border-box;
}
body {
  margin: 0;
}
*, *:before, *:after {
    box-sizing: inherit;
}
```
example https://jsfiddle.net/cef5eobv/

**Comment by arggh** [comment]
You are absolutely correct. I thought that was the first thing I tried without success earlier, but apparently not.
