### ISSUE TITLE
Gitter-IRC bridge

### ISSUE THREAD

**Issue by smcmurray** [Semantic-Org/Semantic-UI#4231]
https://github.com/Semantic-Org/Semantic-UI#getting-help states to use gitter for live chat. But gitter access is restricted and problematic. Gitter requires you to grant them entirely too much access to your github account.

Why not offer a gitter-IRC bridge that allows non-gitter users access to live support chat?

**Comment by jlukic** [comment]
Unless gitter supports IRC I dont believe this is something I personally have time to implement.
