### ISSUE TITLE
Image icon does not display

### ISSUE THREAD

**Issue by tommytompkins** [Semantic-Org/Semantic-UI#4232]
I can get all other icons to display, but the image icon will not display anything with the following code:

```
<i class="image icon"></i>
```

Not sure if this is a bug.  Can anyone confirm?

**Comment by philrykoff** [comment]
Does work here: http://jsfiddle.net/philrykoff/3xkrx/320/

It seems this was just committed 10 days ago with e6e95ecf23aa19507782e368ff175020c5049734. Maybe you should get a fresh copy of semantic ui :-)
