### ISSUE TITLE
changing position of menu based on screen size

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4233]
Is it possible to make changes to menu orientation from horizontal to vertical (example)?

Ref: http://semantic-ui.com/collections/menu.html

Can you give some guideline as to how this can be implemented?

**Comment by IonutBajescu** [comment]
Currently, there's no way to accomplish that automatically, see #157. For now, please create a separate menu for mobile devices and display it using media queries.

In case you need help with writing the media queries, please ask for help on the official forum - http://forums.semantic-ui.com.
