### ISSUE TITLE
Dropdown item in menu cant be controlled like all other dropdowns (hover triggers on its own)

### ISSUE THREAD

**Issue by magestican** [Semantic-Org/Semantic-UI#4234]
The sample is here in the site : http://semantic-ui.com/collections/menu.html#evenly-divided

I have got plenty of issues with mobile users since the hover default behaviour of the dropdown menu item has many inconsistencies across mobile browsers ( hold press to hide, hold press to show in safari, or not working if you remove the cursor style,etc)

Can this behavior on the dropdown be somehow overriden/ stop / disabled?

If you try to execute the $().dropdown function to change the behavior over these elements they also flicker since when you click the hover action also occurs ,etc.

**Comment by jlukic** [comment]
I dont understand the issue as presented. Can you please resubmit with a specific JSfiddle, expected result and actual result. Consult our contributing guide for more suggestions.
