### ISSUE TITLE
[Dropdown] Search In-Menu repeatedly opens/closes in IE11

### ISSUE THREAD

**Issue by Async0x42** [Semantic-Org/Semantic-UI#4237]
http://jsfiddle.net/j9nup1kv/2/

I can't get the jsfiddle to work on my IE11, but the code is the example here: http://semantic-ui.com/modules/dropdown.html#search-in-menu

In IE11 the dropdown will continue to 'bounce' open and shut repeatedly. The class alternates from visible to active over and over.

Browser: IE11
OS: Win10 x64

**Comment by jlukic** [comment]
Wow IE, thats pretty epic bad behavior. Confirmed

**Comment by christianklemp-imt** [comment]
+1 for a fix

Which milestone will this be added to now?

**Comment by joeweale** [comment]
any luck in getting this fixed?

**Comment by jockejon** [comment]
It seems like IE doesn't like the immediate focus on the search input when clicking the dropdown.
I made the following quick fix to make the search menu work in IE for my project:
Removed the entire <div class="scrolling menu">from the example code, it appears that it works better when the items in the dropdown is higher up in the hierarchy. 
See the label filter example on the semantics page.
But that only solved it about 50% of the time, I also hacked the dropdown,js file and commented out the following part:
if(module.has.menuSearch()) {
                    module.focusSearch();
                  }.

**Comment by moondawg69** [comment]
Any luck on a fix with this, got a huge admin UI going out and this is the only issue LOL ;)

**Comment by jockejon** [comment]
I solved it by styling the dropdown as a link which shows the search menu
onclick.

Den 8 nov. 2016 1:47 em skrev "Jez Timms" <notifications@github.com>:

**Comment by moondawg69** [comment]
That may not work being a large Angular app, I'll have to pass it onto the Angular devs. Thank you anyway.

**Comment by christianklemp-imt** [comment]
Anyone have a work around for this or know what exactly is causing this in IE?

**Comment by jlukic** [comment]
Triggering a menu item in IE in this scenario seems to retrigger focus on the dropdown causing it to re-open.

**Comment by jlukic** [comment]
I've fixed this in `next`, bizarrely `focus` is triggered in IE11 on `menu` when clicking an item, even though `tabindex=-1` on menu. 

Then when the menu is hidden my best guess is the `display: none;` from `transition: hidden` causes focus on dropdown to occur again. TBH this is some IE11 weirdness that hopefully we wont have to deal with in a few years.
