### ISSUE TITLE
[Icon] - External Icon listing on semantic site. Duplicate

### ISSUE THREAD

**Issue by shadowcodex** [Semantic-Org/Semantic-UI#4239]
**Steps to Reproduce**
1. look at page

**Expected**
There should only be 1 external icon.

**Result**
There are 2 external icons listed.

**Testcase**
To test go here: http://semantic-ui.com/elements/icon.html

**Comment by jlukic** [comment]
Yep yep yep

**Comment by jlukic** [comment]
F
