### ISSUE TITLE
[Statistic] - Add Charts - layered circles representing percentage/fraction 

### ISSUE THREAD

**Issue by janat08** [Semantic-Org/Semantic-UI#4241]
If you were to go in depth like we have this many users of which this many log on once a week and than this many have such amount of a factor conducive of using one of our product, youd have like a circle representing a user than innder circles representing fractions of other stats.

Alternatively like this many post ads for sale or something, this many will be viewed, and this many view it takes to make sale.

**Comment by janat08** [comment]
Any takers?

**Comment by 20ashah** [comment]
m
