### ISSUE TITLE
[All of Website] - Bug scrolling in sidebar/page

### ISSUE THREAD

**Issue by janat08** [Semantic-Org/Semantic-UI#4242]
Scrolling will scroll both the page and sidebar at all times simultaneusly on your website. Windows 10, chrome, chrome remote desktop.

**Comment by jlukic** [comment]
This is expected

**Comment by janat08** [comment]
Wouldn't that make scrolling through the longer "page" too slow and in reverse for most likely the page.

**Comment by philrykoff** [comment]
If both my page and sidebar (with overlay effect) have a scrollbar, they can be scrolled individually.
