### ISSUE TITLE
[Menu] - I am noticing in all the examples that the menus are not responsive as they do not breakdown into a hamburger icon and then dropdown for mobile formats

### ISSUE THREAD

**Issue by csdanmarker** [Semantic-Org/Semantic-UI#4245]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**
The Menu should do this

**Result**
The Menu does not do this

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by jlukic** [comment]
There is an open issue for making menu responsive

**Comment by jlukic** [comment]
There is an open issue for making menu responsive
