### ISSUE TITLE
[UI suggestion] Attached inputs and input groups

### ISSUE THREAD

**Issue by drcmda** [Semantic-Org/Semantic-UI#4249]
I wish i could chain inputs as i can chain buttons, dropdowns and segments. 

``` html
<div class="ui top attached buttons">
  <button class="ui button">One</button>
  <button class="ui button">Two</button>
  <button class="ui button">Three</button>
</div>
<div class="ui bottom attached inputs">
  <div class="ui input"><input type="text" placeholder="1"></div>
  <div class="ui input"><input type="text" placeholder="2"></div>
  <div class="ui input"><input type="text" placeholder="3"></div>
</div>
```

Is this possible or can it be made possible? Right now i am using "search dropdown button" in "ui buttons" and it can be somewhat hacked into behaving like it, but it gets quite verbose.

**Comment by jlukic** [comment]
There are `action` and `icon` inputs for attaching to dropdowns, labels, and buttons. I dont believe vertically attached is something I will support.
