### ISSUE TITLE
Missing fa-clock-o icon

### ISSUE THREAD

**Issue by emzero** [Semantic-Org/Semantic-UI#4251]
`fa-clock-o` icon was created in FA 1.0 but it's not available in SUI 2.2.
http://fontawesome.io/icon/clock-o/

Also, even though I appreciate the semantic class names for everything else, I'd prefer a 1 to 1 mapping with FA classes. It makes them much more easier to find.

**Comment by IonutBajescu** [comment]
It's already available under the name `.wait.icon`. 

I do agree with you that finding icons is hard in the existing documentation. I had a WIP branch that was adding a search functionality for the icons (#3644), I haven't had the patience to finish it yet though.
