### ISSUE TITLE
Dropdown behavior 'set selected' dont work rightly

### ISSUE THREAD

**Issue by zaoying** [Semantic-Org/Semantic-UI#4252]
`<select name="tags" multiple="" class="ui fluid dropdown">
<option value="" >Enter some tags</option>
  <option value="css">css</option>
  <option value="ruby">python</option>
  <option value="python">ruby</option>
  <option value="html">html</option>
</select>
`

`
$('.ui.dropdown').dropdown('set selected', ['python']);
`
**TWO OPTIONS will be selected!**

**Comment by ilanus** [comment]
Everything works 'rightly' please take a deeper look on Semantic's docs before posting unnecessary issue. First your HTML <option> tag showing "ruby" as value any python as text, python as value and ruby as text. Secondly you don't need to say ['python'] you want only python? do `$('.slector').dropdown('set selected', 'python');` if more then two is necessary `$('.slector').dropdown('set selected', ['python', 'ruby']);`

**Comment by zaoying** [comment]
how would i know how many options need to be selected?your solution only work rightly on one option！if there are more than one option, set selected should be specifily 'key' or 'value'！

**Comment by jlukic** [comment]
This does not have the minimum requirements for posting in GitHub issues, please review our readme
