### ISSUE TITLE
[Search] Search module onResponse Function no Callback In Safari

### ISSUE THREAD

**Issue by ilanus** [Semantic-Org/Semantic-UI#4253]
Hi! 

I'm using Semantic's search module to query a server for a response with my search. 
I am doing a onResponse: function(). Just like in the guide: http://semantic-ui.com/modules/search.html#/examples It works fine expect Safari browser. I Reproduced this issue on the official Semantic-ui website aswell:

![pasted image at 2016_07_09 08_39 pm](https://cloud.githubusercontent.com/assets/9677898/16709579/4bcc839e-4615-11e6-9d62-b218c74927d5.png)

As you can see, the search is going into "Loading" state and not getting back a response ... It also doesn't work on my Android's default browser. However responseAsync: function(settings, callback) seems to be working fine, has anyone came across this issue? 

Thanks

**Comment by jlukic** [comment]
I'm uncertain if this is fixable but I will review

**Comment by jlukic** [comment]
Checking this a year later and it appears to no longer be an issue in iOS Safari.

**Comment by ilanus** [comment]
:+1:
