### ISSUE TITLE
NPM package and jQuery 3.x

### ISSUE THREAD

**Issue by maksis** [Semantic-Org/Semantic-UI#4254]
At the moment [the semantic-ui npm package depends on jQuery 2](https://github.com/Semantic-Org/Semantic-UI/blob/3f5123783e28b364f8d7866f7d12db0e809f5b27/package.json#L80). If a developer using semantic-ui wants to upgrade to jQuery 3.x and adds an explicit dependency for it in his own package.json, it causes two conflicting version of jQuery to be loaded. This breaks everything (at least for webpack users), thus preventing people from upgrading to jQuery 3.x.

This could be solved by removing jquery from dependencies and putting it in [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) instead:

```
  "peerDependencies": {
    "jquery": "^2.2.3 || ^3.0.0"
  },
```

That would allow (or actually force) users to put jquery 2.x or 3.x (whichever they want to use) into their own package.json file. I can also confirm that Semantic UI works fine together with webpack and jQuery 3.1 when there is no conflicting version present.

(at the moment many of the packages listed in `dependencies` have also been copied to `peerDependencies` but I'm not totally sure why)

Possibly related issues: 

https://github.com/Semantic-Org/Semantic-UI/issues/4195
https://github.com/Semantic-Org/Semantic-UI/issues/4202
https://github.com/Semantic-Org/Semantic-UI/issues/4126

**Comment by IonutBajescu** [comment]
@jlukic This one might need your attention.

**Comment by KarandikarMihir** [comment]
Is there any progress on this front? I wish to use `semantic-ui` instead of `semantic-ui-css` (without jQuery) in my react + webpack project. Can I use jQuery 3.x?

**Comment by jlukic** [comment]
Peer dependencies have been deprecated in NPM3, I think should be solved by allowing either version in `dependencies`
