### ISSUE TITLE
[Search] Can't use it on mobile (no results are showed) when using onResponse or responseAsync

### ISSUE THREAD

**Issue by voidale** [Semantic-Org/Semantic-UI#4256]
The only browser it works with is chrome, the other aren't working (safari, default android).
There is no this results box maybe it has to do with some CSS bug.
![image](https://cloud.githubusercontent.com/assets/4450730/16710410/4ab70048-462d-11e6-938d-ce68f85376b0.png)

@jlukic this is a huge bug makes my main input on the home page useless, here is a jsfiddle we can test on https://jsfiddle.net/voidale/6aejuu6u/ any help on this one? I can't find a way to fix it! :-1:

**Comment by jlukic** [comment]
This is failing because you are using ES6 (for of and let) which is supported in chrome but not most browsers.

https://jsfiddle.net/27k3zema/

**Comment by voidale** [comment]
@jlukic the official documentation also doesn't work, I'm on meteor we have babel it's not the issue. 

Here is how to reproduce: Get any mobile phone (I used android) + default browser (not chrome) go to the official search component in semantic ui and it doesn't work.
