### ISSUE TITLE
[API][Tab] - Content is displayed on wrong tab

### ISSUE THREAD

**Issue by rav84** [Semantic-Org/Semantic-UI#4258]
**Steps to Reproduce**
1. Create two or more tabs with first tab api load remote content and second with static content.
2. Make sure the remote response taken sufficiently longer amount of time to response only after 3rd step.
3. When the first tab is loading the data, switch to second tab.

**Expected**
Remote response should load on first tab.

**Result**
Response from server is loaded onto second tab (which is presently active).

**Testcase**
http://codepen.io/ravish_hacker/pen/vKZdyZ
1. Click the first tab to start loading its content
2. Switch to tab second straight away. first tabs content will be loaded onto second tab.

**Comment by TomasZorvan** [comment]
Having same issue. Have you solved this somehow please?
