### ISSUE TITLE
[ISSUE] Contact Form Reset after Submit

### ISSUE THREAD

**Issue by Arturo23** [Semantic-Org/Semantic-UI#4259]
Hello,

For my website I was making a contact form. But I've a problem with the automatic form reset (And I think more people).

Check out my JSFiddle for the javascript code:
https://jsfiddle.net/mmnn5tt3/4/

I don't have a HTML and CSS code. The reason: It's a **javascript** issue.

I hope someone have make it already and can help me. I've trying a lot with 
`$('.ui.big.form').trigger("reset");`

But without succes unfortunately..

**Comment by ilanus** [comment]
Could you provide full code including some HTML for the example? I have used the form quite alot. never had this problem

**Comment by Arturo23** [comment]
I don't have a full code at the moment. Only the contactform. The HTML code is update and the link in the thread also!

**Comment by IonutBajescu** [comment]
Hey @Arturo23,

I appreciate you taking the time to describe your problem.

However, the Github Issue Tracker is not the right place to ask questions. Hence, if you haven't already fixed the problem yourself, please feel free to ask for help on the [Semantic UI forum](http://forums.semantic-ui.com).
