### ISSUE TITLE
[Sidebar] Sidebar in iOS

### ISSUE THREAD

**Issue by LarsBuur** [Semantic-Org/Semantic-UI#4264]
Continuing on issue #2087 (currently closed)

Using the example from @Eliasvdb the output from the fiddle is this url: 
http://fiddle.jshell.net/dzm8b28s/show/

The problem is that if you try to display that specific page in either iOS simulator or in safari on iOS then the height of the sidebar is only the height of the content - and the rest is hidden. Please see this image as an illustration.
![screen shot 2016-07-11 at 08 26 31](https://cloud.githubusercontent.com/assets/3585707/16721656/43cb60b6-4741-11e6-8608-79255af4bd6d.png)
I have tried to add this css (from the sidebar docs).

```
html.ios {
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}
html.ios,
html.ios body {
  height: initial !important;
}

```

it is not clear from the docs (to me) if I manually should add the userAgent detection any ideas how this could be resolved?

**Comment by LarsBuur** [comment]
Please also see latest note on #3701

**Comment by AndrewMDuke** [comment]
I am also having this issue. 

So far i have tried to add the CSS above, but from the documentation i feel that this is already included in the Semantic Ui CSS file. I have also experimented with height values for the sidebar, body and pusher div without any luck.

Have you had any luck finding a solution Lars?

**Comment by ArturSubotkevic** [comment]
Same problem, can't solve it..

**Comment by jlukic** [comment]
Sidebar detects ios in its initialization code and automatically adds class `ios` to html. 

I think I have a fix, but will have to verify it's all safe when i'm able to debug on my phone later this week.

**Comment by LarsBuur** [comment]
Bugger. Was hoping for this one in 2.2.3. Anything I can do to test your fix @jlukic ?

**Comment by arggh** [comment]
@jlukic Any updates on this? What's the proposed fix?

**Comment by pzi** [comment]
Fwiw, you can replicate the issue by going to any page on the Semantic UI site in iOS Safari, remove `.main.ui.intro.container` and `.ui.black.inverted.vertical.footer.segment` and you will get the following when opening the sidebar:

![image](https://cloud.githubusercontent.com/assets/2037851/19102712/f6b2a804-8b04-11e6-8d7b-35af136d3cb2.png)

**Comment by jlukic** [comment]
I dont believe the height rules are necessary in the iOS fix anymore. The overflow rules however I can confirm are still very necessary, removing them will cause the bottom/top of sidebar to get cutoff due to the way iOS auto resizes document height when sidebar is visible.
