### ISSUE TITLE
Collapsing cell/row on a fixed table does not render properly.

### ISSUE THREAD

**Issue by hisabimbola** [Semantic-Org/Semantic-UI#4265]
If I create a `fixed` table and try to collapse one of the rows, the row does not render properly as seen here. http://jsfiddle.net/3hz1bL8e/

**Comment by jlukic** [comment]
Icons can cause weird word wrapping. 

Try `single line fixed table`
http://jsfiddle.net/u5j0jm6v/

**Comment by loris** [comment]
@jlukic 
I'm having a similar issue, but has nothing to do with Icons, see here: http://jsfiddle.net/ozr76bof/1/
First column cells are supposed to collapse, but instead got shrinked.
