### ISSUE TITLE
[Input] - Disabled Should Not be Able to be Selected / Edited by Tabbing

### ISSUE THREAD

**Issue by wunderBarr7** [Semantic-Org/Semantic-UI#4266]
If a `ui disabled input` is tabbed into from another `ui input`, then the user is still able to edit the value of the textbox.

`<div class="ui input"><input id="input1" type="number" /></div>`
`<div class="ui disabled input"><input id="input2" type="number" /></div>`

Using the above code: 
1. Click into `input1`
2. Press tab
3. `input2` is now selected and able to be edited

*The above code works with `type` set to different values than `number`.

Environment:
Windows 10, Google Chrome v 51.0.2704.106 m (64-bit), Semantic v2.2.2 (NodeJS Distribution), JQuery v3.0.0

**Comment by wunderBarr7** [comment]
Update: Problem still occurs using JQuery 2.2.3

**Comment by jlukic** [comment]
Use `tabindex=-1` in html.
