### ISSUE TITLE
API loading not working

### ISSUE THREAD

**Issue by DanAtShenTech** [Semantic-Org/Semantic-UI#4268]
On [this page it explains](http://semantic-ui.com/behaviors/api.html#/usage) how the "loading" class is applied to an element when an API action is initiated so that the state of the user interface is modified automatically.  This had been working fine for me, but with the upgrade to 2.2 this functionality seems to be broken.  The loading class is now not being applied to the element when the API action is initiated, and if I put a beforeSend event in so that I can place the "loading" class on the element by hand, it still doesn't show the spinner on the element, and interestingly, after the API call is finished, the loading class that I added by hand has been removed from the element.  [Here is an attempt to replicate the problem](https://jsfiddle.net/dhswain/wjtsvet7/23/), however, in this case the "loading" class is not removed after the API call - but that could be because I'm using the mockResponse functionality of API.

**Comment by jlukic** [comment]
You're missing the callback in your async response so it remains forever loading.
https://jsfiddle.net/7bks2s1w/
