### ISSUE TITLE
Dropdown API cache filtering

### ISSUE THREAD

**Issue by smcmurray** [Semantic-Org/Semantic-UI#4269]
On a dropdown for which the menu items are obtained via API, once a list is obtained, further filtering of the list often should not require additional AJAX requests.

For instance, if the user types 'A' on a list of US states and the API returns all states starting with 'A', the API need not re-query the server when the user types 'L'. SUI could just filter all the 'A' items it already received.

SUI often retrieves a complete list the first time a user clicks the dropdown. So, depending on the app, no more roundtrips may be required at all.

Is it practical to have an option to bypass roundtrips in such cases?

**Comment by jlukic** [comment]
Yes, we have that already, in fact we even do `localStorage` caching between page loads. You can enable this using `apiSettings: {  cache: 'local' }`

**Comment by xxRockOnxx** [comment]
I'm so glad SUI have this feature! @jlukic does this cache all response? or does it respect the cache headers? When I check the dev tools I always see the server being hit.
