### ISSUE TITLE
Dropdown selection does not display

### ISSUE THREAD

**Issue by smcmurray** [Semantic-Org/Semantic-UI#4271]
http://jsfiddle.net/mbfyfa4v/9/

The dropdown does not show a placeholder, and it does not show the value of the current selection.

**Comment by IonutBajescu** [comment]
http://jsfiddle.net/ncqnLsv8/

You're missing the ".text" element. As a suggestion, generating the dropdown from a select might be simpler and less prone to mistakes. 

In the future, please post your question on the forums for a quicker response. 

Thanks.
