### ISSUE TITLE
[Modal] Add ability to align Modal to top of window

### ISSUE THREAD

**Issue by daggmano** [Semantic-Org/Semantic-UI#4272]
It would be useful to have the ability to show a modal attached to the top of the window.  This may be as simple as adding an `align` property to the Modal `settings` object, and if set to `top`, the Modal `set.position()` method sets `top` to 0.  This may be a naive implementation - I haven't done enough testing with scrolling pages or long modal boxes.

**Comment by jlukic** [comment]
I've been thinking about adding a setting for specifying valign %. I think personally these days I actually prefer something like 33%.

**Comment by daggmano** [comment]
The valign setting is a great idea.  Not sure if I'll get any time to work on it, but will if I can.

**Comment by chenfanggm** [comment]
Really want this too. 
Thanks for anyone could come back to implement this.
