### ISSUE TITLE
Modal onHidden and observeChanges clash

### ISSUE THREAD

**Issue by cbxp** [Semantic-Org/Semantic-UI#4274]
We create a modal like this:

```
$(selector).modal({onHidden: this.unmount, observeChanges: true}).modal('show');
```

However, when user clicks close (or clicks the dimmer), both modal and dimmer get hidden properly, also removing screenHeight(), e.g. height style from the body.

Then onHidden callback fires, which in our case clears the modal content. This triggers observeChanges on already hidden modal and sets screenHeight() to the body again, breaking our page layout.

Desired behaviour: observeChanges should be removed when modal gets hidden (before onHidden callback fires).

We use semantic 2.2.1.

**Comment by jlukic** [comment]
Can you create a test case to show `refresh` causing incorrect page stylings?
