### ISSUE TITLE
[Dropdown] Multiselect Without Labels Does Not Clear

### ISSUE THREAD

**Issue by sangkj** [Semantic-Org/Semantic-UI#4275]
When using a multiselect dropdown (with useLabel:false option), the dropdown items do not clear properly.  When "get value" is called on the dropdown after "clear" is called, the dropdown returns an empty string (expected), but the selected menu items are not deselected in the ui (problem).  Here is a jsfiddle to demonstrate the issue http://jsfiddle.net/k8z7aqro/1/

**Comment by jlukic** [comment]
I'm able to reproduce
