### ISSUE TITLE
Make modal closable option able to take a function

### ISSUE THREAD

**Issue by brendon** [Semantic-Org/Semantic-UI#4276]
Sometimes it'd be handy for the `closable:` option on modals to be able to take a function to be executed at the time that the dimmer is clicked.

In my case I would like to check if a particular form field is populated before allowing the modal to close.

**Comment by philrykoff** [comment]
This! Returning false from onHide should keep the modal open, too. Just like onApprove and onDeny do.

**Comment by brendon** [comment]
Ha! Yes I tried that way before to no avail :)

**Comment by jlukic** [comment]
No need `onHide` can cancel a modal closing
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/modal.js#L375

**Comment by brendon** [comment]
Oh ok, the documentation doesn't mention that. Would you like a PR to fix that?

**Comment by brendon** [comment]
Just following this up. Clicking the dimmer does trigger the `onHide` function, but it doesn't respect the `return false` and closes the modal anyway.

Conversely, clicking a `deny` type button triggers `onHide` and this time it does respect the `return false`.
