### ISSUE TITLE
Issue with Sidebar when using 'context'

### ISSUE THREAD

**Issue by hassanasad** [Semantic-Org/Semantic-UI#4277]
When updating from 2.1.8 to 2.2.1 i noticed that the sidebars which use 'context' are not working as expected. The transitions are laggy and (i assume) there is something wrong with 'z-index' as layers mess up.

Even on the example page: [http://semantic-ui.com/modules/sidebar.html#/examples](http://semantic-ui.com/modules/sidebar.html#/examples) the context example is not transitioning.

**Comment by hassanasad** [comment]
Ah - sorry, seems like its a bug in the latest version of Google Canary browser. Working fine in Google Chrome.

**Comment by jlukic** [comment]
Thanks for verifying yourself, much appreciated.
