### ISSUE TITLE
"Hidden input" taking a blank space when it's next to the "header tag"

### ISSUE THREAD

**Issue by AnDroidEL** [Semantic-Org/Semantic-UI#4278]
It's possible to see too how was solved this simple problem. But I still think it's a little strange.

[http://jsfiddle.net/AnDroidEL/qmarh3qh/2/](http://jsfiddle.net/AnDroidEL/qmarh3qh/2/)

**Comment by jlukic** [comment]
Components try to remove margins based on `:first-child` and `:last-child` theres nothing that can be done with regards to hidden inputs, or additional wrappers sometimes causing excess margins. 

I'd recommend massaging the component into place with some page specific css for your design.
