### ISSUE TITLE
Popup repositioning on scroll

### ISSUE THREAD

**Issue by philrykoff** [Semantic-Org/Semantic-UI#4281]
Popups hide by default, when you scroll. Yet, that feature can be deactivated.

Popups reposition themselves, when the window (their container?) is resized.

Feature request: if close-on-scroll is disabled, let the popup reposition itself, when the window (it's container?) is being scrolled.

Here is my current code:

`$('.my.scrolling.container').on('scroll', function() { $('.visible.popup').popup('reposition') });`

I guess it would be best to introduce a new property called `scrollingContainer`, because listening to `window` may cause problems (memory leak?) if the popup's element is being removed from the page.

What do you think? I would be open to create a PR if you are open for accepting it 😄

**Comment by jlukic** [comment]
Popups already include a scrollContext
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/popup.js#L987

**Comment by philrykoff** [comment]
Maybe I should really update my SUI. When I have done, I may reopen and hopefully include a PR. Thanks!
