### ISSUE TITLE
Using a SELECT tag to create a multiple selection dropdown with remote data doesn't not work correctly in version 2.2.X 

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#4282]
Using a SELECT tag to create a multiple selection dropdown with remote data doesn't not work correctly in version 2.2.X

After selecting a menu option, all menu options are removed (instead of filtering the selection). 

Also, the Values of the selected options are being displayed in the menu instead of the Name or Text.

A multiple selection dropdown constructed of a DIV tags with remote data works as expected.

This is a version 2.2.2 example showing the SELECT issue: 
http://jsfiddle.net/kmd1970/0dkceayx/

This is a version 2.1.6 example with both working correctly.
http://jsfiddle.net/kmd1970/vuc3zf90/

**Comment by jlukic** [comment]
I can confirm theres something fishy

**Comment by nandastone** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/4226

**Comment by jlukic** [comment]
This has been fixed in `2.23`, either from #4344 or #4316
