### ISSUE TITLE
[Button] - Wrong social colors

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#4284]
Some social button variations use outdated or wrong color codes, e.g.
- Twitter:
  - Official: #55acee (https://about.twitter.com/company/brand-assets)
  - Semantic-UI: #0084b4 
- Pinterest:
  - Official: #bd081c (https://business.pinterest.com/en/brand-guidelines)
  - Semantic-UI: #00aced (light blue instead of red?)
- Google+:
  - Official: #dd4b39 (https://developers.google.com/+/branding-guidelines#googleplus-icon)
  - Semantic-UI: #dc4a38 (almost)
- Instagram:
  - Official: no single color (http://brandcolors.net, https://www.instagram-brand.com)
  - Semantic-UI: #49769c

I didn't check all social buttons, just the ones I needed. And it seems as if there are more social button variants defined than visible on the docs page http://semantic-ui.com/elements/button.html#social

**Comment by jlukic** [comment]
They are a few years old. I'll revisit.

**Comment by jlukic** [comment]
It might be cool to fix the instagram button to use their standard gradient. I've fixed the other colors as mentioned.

**Comment by larsbo** [comment]
Yes, that would be a nice solution! :smiley:

**Comment by Francismori7** [comment]
Perhaps this needs a read: 

https://developers.googleblog.com/2016/11/moving-to-google-sign-in-for-a-better-user-experience-and-higher-conversion-rates.html

Google no longer allows the red "plus" buttons, and forbids the use of the PLUS icon
