### ISSUE TITLE
CSS only Popup doesn't appear above disabled button

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#4285]
Pretty simple issue, if there is a button defined as disabled:

`<button class="ui disabled button" data-tooltip="Not available yet">Do Action</button>`

The css only popup doesn't show. It might have been originally a feature, but I don't see why a popup would be disabled together with a button, meanwhile its a perfect case for showing 'Do something to make it available' tip

**Comment by jlukic** [comment]
Disabled buttons have `pointer-event: none` preventing `:hover`

You'll have to add `pointer-events: auto` to your custom css.
