### ISSUE TITLE
Incorrect image modal placement when the image is loaded slow.

### ISSUE THREAD

**Issue by BeSports** [Semantic-Org/Semantic-UI#4286]
I had this annoying issue where sometimes my modal wouldn't render correctly, and would render way lower than it should.

After some research, I found that, if the image isn't fully loaded before the modal is shown, it will position itself just like it would if the image was a broken image or as if there was no image.

You can simulate this effect in Google Dev Tools by throttling your connection speed. If you set it low enough, you'll always get a mispositioned modal.

I have enabled observerChanges, but that didn't seem to solve them.

What fixed it for me, was defining an image and attaching an onLoad function to it, which will then trigger the .modal('show').

```
var img = new Image();
img.onload = () => { this.showModal(); }
img.src = this.props.imageUrl;
```
with 
```
showModal: function() {
  $(this.refs.modal).modal('show');
  $(this.refs.modal).modal('refresh');
},
```

Is there any way to make this behaviour default?

**Comment by philrykoff** [comment]
Is it possible for you to define width and height attributes of the image?

Am Freitag, 15. Juli 2016 schrieb BeSports :

**Comment by BeSports** [comment]
Nope, image does not have fixed proportions.

**Comment by jlukic** [comment]
This is discussed in many other issues. There is no way to center the modal without knowing the size on show

**Comment by BeSports** [comment]
@jlukic Like my post clearly states, there is a way. For images, you can just wait for the source to actually be loaded.

**Comment by philrykoff** [comment]
I dont think this functionality belongs in a framework, it's to specific and can be easily implemented from outside.

**Comment by BeSports** [comment]
Then maybe include it in the docs somewhere?
