### ISSUE TITLE
How to remove default margin?

### ISSUE THREAD

**Issue by NoTalentGeek** [Semantic-Org/Semantic-UI#4294]
I want to remove the margin between my elements in the screenshot below. They are the white spaces between the text field and then the horizontal margin between the first row and the button element.

![https://s32.postimg.org/c6d8fb6z9/image.png](https://s32.postimg.org/c6d8fb6z9/image.png)

**Comment by lholznagel** [comment]
My idea would be to override the css element with: `margin: 0px`

**Comment by NoTalentGeek** [comment]
Hmmm, before it was like this.

![https://s31.postimg.org/6w8rutl9n/Image_001.png](https://s31.postimg.org/6w8rutl9n/Image_001.png)

Then I added, `margin: 0px` as you said.

```markdown
div.ui.stackable.two.column.grid{
    margin: 0px;
}
```

It became like this.

![https://s31.postimg.org/6w8rutl9n/Image_001.png](https://s31.postimg.org/6w8rutl9n/Image_001.png)

What I want is that all elements to be __exactly 0__ pixel to each other for every right, left, up, and down.

**Comment by lholznagel** [comment]
Hm, maybe set padding to 0?

Can you create a quick fiddle?

**Comment by NoTalentGeek** [comment]
I am not sure how to fiddle. I hope I make no mistake here, [https://jsfiddle.net/ep7aehr4/](https://jsfiddle.net/ep7aehr4/).

**Comment by lholznagel** [comment]
Works.

So I added the classes test and test2
``` html
<div class="column test">
   <input name="user-name" placeholder="User Name" type="text">
</div>



<div class="column test2">
  <input name="user-password" placeholder="Password" type="password">
</div>
```

``` css
.test {
  padding-right: 0px !important;
}

.test2 {
  padding-left: 0px !important;
}
```

Seems like there is still a pixel red between them, ...

**Comment by NoTalentGeek** [comment]
When the browser is half of my screen resolution it is like this.

![https://postimg.org/image/vpcyjmmv5/][img]https://s32.postimg.org/vpcyjmmv5/Image_001.png](https://postimg.org/image/vpcyjmmv5/][img]https://s32.postimg.org/vpcyjmmv5/Image_001.png)

But when the browser is full of my screen resolution it is like this.

![https://s32.postimg.org/k1iwp2xqd/Image_002.png](https://s32.postimg.org/k1iwp2xqd/Image_002.png)

I added this in my fiddle.

```markdown
button, input{
    margin-bottom: 0px !important;
    margin-left: 0px !important;
    margin-right: 0px !important;
    margin-top: 0px !important;
    margin: 0px;
    padding-bottom: 0px !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
    padding-top: 0px !important;
    padding: 0px;
}
```

**Comment by lholznagel** [comment]
Hm, try add `!important` to `margin: 0px` and `padding: 0px`

Tipp:
`padding` includes `bottom`, `left`, `right`, `up`. Same for `margin`.

**Comment by NoTalentGeek** [comment]
Thanks for your info.
However, it does not change anything since my last screenshot.

**Comment by IonutBajescu** [comment]
Hey @NoTalentGeek,

I appreciate you taking the time to describe your problem.

However, the Github Issue Tracker is not the right place to ask usage questions. Hence, if you haven't already fixed the problem yourself, please feel free to ask for help on the [Semantic UI forum](http://forums.semantic-ui.com).
