### ISSUE TITLE
[Slider] Does slider module has been deprecated?

### ISSUE THREAD

**Issue by hh54188** [Semantic-Org/Semantic-UI#4295]
I can't find slider module in doc's module sub-list, But when I search through keywords "semantic-ui slider" in Google, it still show me the slider module page: [http://semantic-ui.com/modules/slider.html](http://semantic-ui.com/modules/slider.html), but the slider demo in the page seem doesn't work any more.

So does slider module has been deprecated?

**Comment by GDay** [comment]
The slider page is indeed incomplete, but it looks like there is an update coming soon. Pull request: https://github.com/Semantic-Org/Semantic-UI/pull/4212

**Comment by jlukic** [comment]
Unfortunately there is no slider module currently.
