### ISSUE TITLE
Tooltip on disabled button

### ISSUE THREAD

**Issue by redrick** [Semantic-Org/Semantic-UI#4296]
Hi guys, 

hopefully I am not misplacing some CSS, but this is my usacase:

disabled delete button should have popup

as we use 2.2.2, I am using tooltip for it, but here I have it demonstrated:

https://jsfiddle.net/Redrick/uh9hbde2/

tooltip on disabled button not visible, was that intentional ?

Thanks :)

**Comment by larsbo** [comment]
The disabled button doesn't react on mouseover because of the css property `pointer-events: none;`.
You can solve that easily by wrapping the disabled button into another tag which has the popup settings instead:
https://jsfiddle.net/uh9hbde2/21/

**Comment by redrick** [comment]
Perfect, thank you 👍

**Comment by quanganhtran** [comment]
![screen shot 2018-11-09 at 11 09 15](https://user-images.githubusercontent.com/9863988/48253455-f15f5800-e40f-11e8-9d53-5931740c54cf.png)

To follow up on this, wrapping with span would still require a lot of customization to have it functional.

I have yet to try overriding `pointer-events`

**Comment by ColCh** [comment]
@quanganhtran it works for me https://jsfiddle.net/hyb32dxk/

<details>
<img src="https://user-images.githubusercontent.com/599439/48299540-356d5e00-e4df-11e8-875d-7eda05bb5391.gif" />
</details>
