### ISSUE TITLE
It does not work with the click Dropdown

### ISSUE THREAD

**Issue by afuno** [Semantic-Org/Semantic-UI#4297]
Dropdown without clicking work:
```<div class="ui simple dropdown">```

Dropdown with the click does not work:
```<div class="ui dropdown">```

I use a simple CSS version: https://github.com/Semantic-Org/Semantic-UI-CSS

What could be the problem?

I add this code, but it did not help:

```
$(document).on "page:change", ->
	$('.ui.dropdown').dropdown()
	return
```

**Comment by afuno** [comment]
Good. I got it.

No need to add code that I showed above, and need to add this code (without Turbolinks):

```
$('.ui.dropdown').dropdown()
```

Exclusively to this:

```
</body>
```

**Comment by user5885** [comment]
what does that mean?
