### ISSUE TITLE
Bug with Api when using with form

### ISSUE THREAD

**Issue by Errvald** [Semantic-Org/Semantic-UI#4298]
Here's an example code

```
<form class="ui form">
	<div class="field">
	    <label>Email</label>
	    <input type="email" name="email">
	</div>
	<button class="ui button primary">Send</button>
</form>

formEl
    .api({
        method: 'post',
        url: '/login',
        serializeForm: true
    })
    .form({
        on: 'submit',
        fields: fieldsRules
    });
```

Makes 2 requests:

- POST status 302
- GET

Using ``v.2.2.2``

**Comment by Errvald** [comment]
Upon further inspection this occurs when I'm posting from the same route.

Here are the routes in the backend:
```
Route::get('login',..
Route::post('login',..
```

If I post to ``login`` from ``domain.com/login`` I get those 2 requests.

**Comment by dreaming-augustin** [comment]
Errvald: did you ever resolve this issue? How?

**Comment by pbarney** [comment]
Errvald, you suck for closing this without explanation.
