### ISSUE TITLE
[Form][Validation] Validate a number range?

### ISSUE THREAD

**Issue by drsloth** [Semantic-Org/Semantic-UI#4300]
We can validate an integer range with integer[0..10] but we can't seem validate a number range as in number[0..10]. Is there a workaround?

**Comment by ubald** [comment]
Did you find anything?

**Comment by drsloth** [comment]
I ended up satisfying coverage with two separate rules, the semantic number validator and a custom validator that checks if the input value is between two given values.

Attaching custom rules is pretty easy:

$.fn.form.settings.rules.greaterThan = function (inputValue, validationValue) {
    return inputValue > validationValue;
}

and to reference it:

rules: [
  {
    type: 'number',
    prompt: 'A valid number is required for: {name}',
  },
  {
    type: 'greaterThan[validationValue]',
    prompt: 'Prompt Value',
  },
],
