### ISSUE TITLE
make sure sidebar and pusher are direct children of your body tag 

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4301]
I am getting the following error when I used sidebar for a different element/context than body.
```
semantic.min.js:17 Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag 
```

**Comment by siddo420** [comment]
see https://github.com/Semantic-Org/Semantic-UI/issues/4310 as well

**Comment by lholznagel** [comment]
Some code?
The first I would think about is that you have your sidebar outside ob the `<body></body>` tag

**Comment by jlukic** [comment]
Many other discussions of this in Github issues, please try searching
