### ISSUE TITLE
BUG - Popup does not fit within the boundaries of the viewport

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4306]
I have a simple reproducible test case (on Chrome at least).

```
<html><head>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <link rel="stylesheet" type="text/css" 
        href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <style>body{ padding: 2% 3em 0 3em;	}</style>
</head><body>

	<div class="ui attached icon message">		
	  <div class="content"><div class="header">Text here</div></div>		

      <div class="ui right aligned borderless vertical pointing menu"
		   style="border:0;background-color:inherit;box-shadow:none;min-height:0;width:auto"
		   id="settings"
	  ><i class="ellipsis vertical ui icon" 
		  style="font-size:1.4em;border:0"></i>
      </div>
	  <div class="ui popup bottom left transition hidden">
		<div class="column">
		  <h4 class="ui header">Fabrics</h4>
		  <div class="ui link list">
			<a class="item">Cashmere</a>
			<a class="item">Linen</a>
			<a class="item">Cotton</a>
			<a class="item">Viscose</a>
		  </div>
		</div>
	  </div>
    </div>
   <div class="ui attached segment pushable"  id="msgs_area"></div>
		
<script>
$(function(){  
	$( 'div#settings' )
	  .popup({
		    inline:     true
		  , exclusive:  true
		  , boundary:   $('body')
		  , hoverable:  true
	  });
});
</script>
</body></html>
```

Open in Chrome and hover mouse over the vertical ellipsis icon and see console output. Also, the menu does not open. This seems to be due to the padding on body tag.

**Comment by siddo420** [comment]
I've now modified the code in first comment (in this issue) and now it uses files directly from CDN, so no need to download etc and link files anymore.

- Copy and paste the code in an html file and
- open that file in a browser (Chrome) and
- click on the elliptical icon

you'll see the issue yourself. You can open console log to see errors.

**Comment by vinh123456789** [comment]
would be great if you can add a jsfiddle example

**Comment by siddo420** [comment]
here it is: https://jsfiddle.net/9amow2f2/1/

**Comment by vinh123456789** [comment]
Is there any reason that you want to add `boundary:   $('body')`, beacause if i remove that, popup seem to work fine.

**Comment by siddo420** [comment]
no special reason but just wanted to inform devs about it to make sure it does not break something else somewhere else

**Comment by vinh123456789** [comment]
I think it is an expected behavior... since your popup does not fit inside boundary, SUI log that warning for you to know.

**Comment by jlukic** [comment]
You can use `lastResort` to force a direction when a popup doesnt fit.
