### ISSUE TITLE
[Checkbox] Toggle Checkbox with two labels

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#4309]
In some situations it make sense to label both sides / options of a toggle checkbox.

I created a fiddle to demonstrate how it could look & work:

- clicking on the toggle element results in toggling as before.
- clicking on of the labels set the toggle input to the clicked option.

http://jsfiddle.net/5gs7m60w/

**Comment by jlukic** [comment]
I would prefer to do this as labels area itself, i.e. yes/no in the blue area of the toggle. I dont believe I've seen any other examples on the mainstream web of using multiple labels like your example.

**Comment by nico-martinucci** [comment]
> I would prefer to do this as labels area itself, i.e. yes/no in the blue area of the toggle. I dont believe I've seen any other examples on the mainstream web of using multiple labels like your example.

Was this ever implemented?
