### ISSUE TITLE
[Dropdown] - popup set on dropdown with on: 'focus' setting doesnt show when tabbing

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#4312]
http://codepen.io/avalanche1/pen/pbLjgq
popup set on dropdown with on: 'focus' setting doesnt show when tabbing; if you click on dropdown popup shows alright, but not when tabbing into the dropdown

**Comment by vinh123456789** [comment]
I tested it using Firefox and Chrome, both seem to work fine for me.

**Comment by vinh123456789** [comment]
My mistake, i thought you was saying dropdown suggest list...
Indeed popup does not show when tab on dropdown.

**Comment by jlukic** [comment]
I'm not sure the issue but it'd be easy enough to trigger this manually with dropdowns callbacks and `on: 'manual'`

**Comment by jlukic** [comment]
This is easy enough to do with callbacks.
http://codepen.io/anon/pen/grjazL

in the future can you use jsfiddle? Codepen is much less forgiving of anonymous accounts which makes it more difficult to edit

**Comment by avalanche1** [comment]
> I'm not sure the issue but it'd be easy enough to trigger this manually with dropdowns callbacks and on: 'manual'
This is what I'm doing currently. But it looks like a hack really. If popup is set to 'on: focus' - it should show on attached element's focus - no?

**Comment by avalanche1** [comment]
Actually, using dropdown callback is not efficient.
And also setting `on: 'manual'` and using jquery (`$dropdown.on('focus', =>$dropdown.popup('show')); $dropdown.on('blur', =>$el.popup('hide')`) doesnt work as well because this [line](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/popup.js#L325) blocks showing popups on active dropdowns.
I propose that line be changed to ` if(module.is.hidden() ) {`
