### ISSUE TITLE
The problem with multiple Tab

### ISSUE THREAD

**Issue by afuno** [Semantic-Org/Semantic-UI#4313]
On the page there is news. For example, their 10. Accordingly, they are generated in a cycle:

```
<div class="ui pointing secondary menu" id="js-tab-<%= news.id %>">
	<div class="header item">News <%= news.id %></div>
	<a class="active item" data-tab="news-<%= news.id %>-text" href="javascript:void(0);">Text</a>
	<a class="item" data-tab="news-<%= news.id %>-info" href="javascript:void(0);">Info</a>
</div>

<div class="ui active tab segment" data-tab="news-<%= news.id %>-text">
	Here the text of the news.
</div>

<div class="ui tab segment" data-tab="news-<%= news.id %>-info">
	Here information about the news.
</div>
```

In the same cycle in the end there is a line:

```
<script>$('#js-tab-<%= news.id %> .item').tab();</script>
```

In the end, I get the following error. All news are displayed when the page loads. The active tab - the text of the news.

But there is one thing. For example, select 4 news in the list. I click on her "Info" link. At 4 news information appears (this is the tab "Info"). All other news will be hidden all their tabs.

What is the problem and how to solve it?

**Comment by afuno** [comment]
This problem is solved as follows. On the official website there is an example: http://semantic-ui.com/modules/tab.html#/examples

Section: Multiple Tab Group.

**Comment by jlukic** [comment]
Looks like code sample there is broken #4314
