### ISSUE TITLE
ui container has left and right margins on mobile screen size 

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4317]
On http://semantic-ui.com/elements/container.html#/introduction, its mentioned that mobile width is 100% but I still see margins on left and right in smaller width/devices.

Thats because of margin-left and margin-right on "ui container".

Can this be changed through some setting in CSS? And more importantly, isn't this a bug?

**Comment by jlukic** [comment]
The gutter size is 1em as mentioned in docs. This is not a bug.

Can be changed with 1line of variable modifications
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/container.variables#L16
