### ISSUE TITLE
Proposals to improve the Rating component

### ISSUE THREAD

**Issue by afuno** [Semantic-Org/Semantic-UI#4321]
Hi guys.

In developing the project, which is closely associated with the component rating, I am having the following suggestions:

1. No support for floating-point numbers. As a result, there is no support icons "half star". This is actually a very an unfortunate fact.

2. No support for a description of the rating. What I mean? For example, the bottom of the rating would output the following:
> Your chosen estimate: 5.

3. Callbacks. Now there is only one method - onRate. And he gives only the value. It is also possible to add the parent class or ID. Now I have to duplicate the ID. I understand that it is most likely done with the expectation of instant AJAX request, but this is not always the case.

At the moment, that's all.

Good luck.

**Comment by user5885** [comment]
>  support for floating-point numbers

this is much needed.

**Comment by jlukic** [comment]
issue 1 is #1048 and would want as well

issue 2 It's negligible code to update text outside the component `onRate` no need to add to lib. 

issue 3 the `this` context of all callbacks is the component, it would be easy to grab metadata from the DOM
