### ISSUE TITLE
Bug with Card, Label and Popup

### ISSUE THREAD

**Issue by afuno** [Semantic-Org/Semantic-UI#4322]
Standard situation. From the documentation: 

![Screenshot 1](https://habrastorage.org/files/e8a/6dd/77a/e8a6dd77a967428a97568b65757ebb7c.png)

The next step is to add the Popup:

```
<div class="column">
	<div class="ui centered card">

		<div class="ui green right corner label" data-tooltip="Popup text" data-position="left center"><i class="bookmark icon "></i></div>

		<div class="content">
			<!-- content text -->
		</div>
	</div>
</div>
```

Result:

![Screenshot 2](https://habrastorage.org/files/a90/1aa/57c/a901aa57c72940c6a20eda6762d1ddf0.png)

Hovering the mouse:

![Screenshot 3](https://habrastorage.org/files/63c/10c/d42/63c10cd42c7c42cabb8d5e610dddf5a8.png)

I use Semantic UI CSS.

What is the problem and how to fix it?

**Comment by vinh123456789** [comment]
According to this doc: http://semantic-ui.com/modules/popup.html#tooltip
> Tooltips use an element's :before and :after psuedo classes. Elements like icon that already use these classes for styling will need to have the tooltips to a wrapping element, like a button, or a span to make sure tooltips work correctly. 

You need to change this line:
```
<div class="ui green right corner label" data-tooltip="Popup text" data-position="left center">
          <i class="bookmark icon "></i>
</div>
```
to this:
```
<span data-tooltip="Popup text" data-tooltip="Popup text" data-position="left center">
         <div class="ui green right corner label">
              <i class="bookmark icon "></i>
         </div>
</span>
```

**Comment by afuno** [comment]
@vinh123456789 Better, but still have a little problem:

![Screenshot 1](https://habrastorage.org/files/b05/c3c/a12/b05c3ca120c54989b7832ab8c06b3f1f.png)

In the screenshot: I have brought the mouse upper right label.

**Comment by vinh123456789** [comment]
It will be much easy for who want to help you if you can provide a jsfiddle...
If you want a easy solution, you can try:
```
data-position="top right"
```
For a more optimize solution, add this style in the span element:
```
position: absolute; width: 4em; height: 4em; right: 0;
```

**Comment by jlukic** [comment]
This is a conversation best for our forums and not Github issues
