### ISSUE TITLE
Performance issues using the progress bar with seconds?

### ISSUE THREAD

**Issue by voidale** [Semantic-Org/Semantic-UI#4324]
I'm using the following to animate the progress bar for 60 seconds, I've ran it on debug mode and the console gives this `Progress 60120ms` now I fear it may block the event loop for my webpage? I noticed some lag and was wondering if this might be the cause? 

Thanks!
```
    $progressBar.progress({
        duration : 60000,
        total    : 100,
        showActivity: false,
        autoSuccess: false,
    }).progress('reset').progress('complete');
```

**Comment by IonutBajescu** [comment]
If you remove the progress bar, does the performance improve? 

Also, could you please profile the application? (Using Chrome's profiler or something similar)

**Comment by jlukic** [comment]
Components might show erroneous timing in logs on the first init depending on how it is initialized.  This refers to the time between a callback firing and the first init on page.

Also keep in mind `2.2` rewrote progress to more efficiently handle rapid updates. See our release notes.
