### ISSUE TITLE
[Abbreviation] - Abbr Tags Have Got Two Underlines 

### ISSUE THREAD

**Issue by JnxF** [Semantic-Org/Semantic-UI#4325]
This bug is (only ?) in Firefox.

Demo: http://jsfiddle.net/0s851zy8/

**Comment by visvadw** [comment]
Indeed, on Firefox the underlinke looks a little bit bolder.

- on Chrome `54.0.2806.0 canary (64-bit)`
![image](https://cloud.githubusercontent.com/assets/14140226/17083508/eb4772d4-51ab-11e6-9e11-167783bda756.png)

- on Safari `9.1.2 (11601.7.7)`
![image](https://cloud.githubusercontent.com/assets/14140226/17083530/a7f0794e-51ac-11e6-8b80-64e2b7ee7f3c.png)

- on Firefox `41.0` / `47.0.1`
![image](https://cloud.githubusercontent.com/assets/14140226/17083512/250c6c68-51ac-11e6-8eec-1036a36e73d6.png)

And it looks quite the same with Semantic UI 2.2.1 also as shown in https://jsfiddle.net/9je7LqgL/1/

**Comment by jlukic** [comment]
Thanks @visvadw
