### ISSUE TITLE
Gulp not creating any files when used with build

### ISSUE THREAD

**Issue by thekillertoaster** [Semantic-Org/Semantic-UI#4326]
![image of issue](http://i.imgur.com/AXt4Gc1.png)

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, it does not include enough information to be considered a bug report. Feel free to re-open as a new issue if you can provide a reproducible test case (either a JSFiddle for JS issues, or a repo to clone for build issues)

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
