### ISSUE TITLE
It seems 'fireOnInit' doesn't apply on 'onRate'

### ISSUE THREAD

**Issue by alfredomirick** [Semantic-Org/Semantic-UI#4327]
Hello all,
First of all I appreciate what you builded. It's great 👍 
I think there is bug in rating. Here is my code : 
```
$('.ui.rating').rating({
  onRate: function(value) {
    console.log(value);
  },
  fireOnInit: false 
});
```
but onRate is called anyway ! how can I prevent onRate to be called at init?

**Comment by jlukic** [comment]
http://jsfiddle.net/jf0ybozk/

It does not fire on load.
