### ISSUE TITLE
[Dropdown] "is already setup" method returns a wrong value

### ISSUE THREAD

**Issue by challet** [Semantic-Org/Semantic-UI#4330]
The function [is.alreadySetup](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2983) seems to not work with the [documentation examples](http://semantic-ui.com/modules/dropdown.html#/usage) : it always returns false.

see http://jsfiddle.net/sk1wh7dj/1/

**Comment by jlukic** [comment]
Although this should be `true` , if I fix this it will always evaluate to `true`, as invoking a methodin a dropdown by calling `.dropdown('anything here)` will call `initialize` and `setup` before evaluating the behavior.

**Comment by challet** [comment]
Hi @jlukic, thanks for your answer, some things have been made clearer.

Though, what about the second part of the test (http://jsfiddle.net/sk1wh7dj/5/) where the behavior is called on the returned modules ?
The instance should be defined and the bahavior method called without initialize again, isn't it ?
