### ISSUE TITLE
Console error when using sidebar in context

### ISSUE THREAD

**Issue by adi8i** [Semantic-Org/Semantic-UI#4331]
It should be displayed as warning, not error. 
```
semantic.min.js?ver=1.0.0:17 
Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag <aside class=​"ui sidebar left">​…​</aside>​error @ semantic.min.js?ver=1.0.0:17
```

Here's the code I used 
```
  .sidebar({
    context: jQuery('.myclass')
  })
```

**Comment by jlukic** [comment]
This is a warning message, if the sidebar isnt already included in the page in the right location it will automatically move it for you to make it work. Unfortunately doing DOM mutations on page load is probably a bad idea, so that is the reason for the warning.

**Comment by Vic020** [comment]
Met the same problem.
But it's actually report a error message.So we ignore it ?
@jlukic
