### ISSUE TITLE
Help with search multiple selection dropdown

### ISSUE THREAD

**Issue by allochi** [Semantic-Org/Semantic-UI#4332]
Hi, I'm really sorry if this is a repeated question, I tried my best for the past several days to make this work.

I'm working on making a tags field, that searches a database of thousands of terms, so preloading with a `select` is not an option. I managed to get a multiple select and the search working, unfortunately I'm facing a problem, and it's probably something I'm missing when I read the document.

I have this as html and javascript:

```html
<div class="field">
  <label for="sources">Sources</label>
  <div class="ui search multiple selection dropdown" id="sources">
    <input type="hidden" name="sources">
    <div class="default text">Search Sources</div>
  </div>
</div>
```

```js
$('#sources').dropdown({
   fields: {name: 'name', value: 'name'},
   minCharacters:2,
   apiSettings: {
      url: '//api.semantic-ui.com/tags/{query}'
   }
});
```

1. How can I post multiple select values (just like if I'm using a `<select multiple="">`? (I'm submitting normal form - the only workaround I have in mind now is to submit a text field and split server-side)
2. How can I set the selected values when the form load? `$('#sources').dropdown('set selected',["Source A", "Source B"])` just doesn't work.

I would appreciate any guidance or help here, since I'm left with no other option but to use other than semantic-ui solution (which I don't want to)

Thanks in advance.

**Comment by allochi** [comment]
Ok, so I managed to solve the first problem :D

```html
<div class="field">
  <label for="sources">Sources</label>
  <select class="ui search selection dropdown" multiple="" name="sources" id="sources">
  </select>
</div>
```

The second is still not working, could someone advice. Thanks!

**Comment by lholznagel** [comment]
I think this is more a issue for the forum or StackOverflow. [Semantic-UI Forum](http://forums.semantic-ui.com/)

**Comment by challet** [comment]
Would it work if you set the selected options in the initial select ?

    <select class="ui search selection dropdown" multiple="multiple" name="sources" id="sources">
      <option value="A" selected="selected">Source A</option>
      <option value="B" selected="selected">Source B</option>
    </select>

By the way, this issue looks like [an usage question](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md#usage-questions).

**Comment by allochi** [comment]
I'm sorry for that, I will close the issue as I already solved the first problem. As for the other issue I will keep researching and see if I can find a solution. 

Again my apology to post the question in the wrong place.

**Comment by allochi** [comment]
Just for reference I tried @challet solution and it works, thanks a lot!
