### ISSUE TITLE
Searching through database

### ISSUE THREAD

**Issue by warlordsd** [Semantic-Org/Semantic-UI#4333]
Hello, i'm new to semantic-ui and also new to asp .net programming, so i'd like to ask something. How can i make my search bar from semantic-ui to search through my data and return results. Thanks a lot :)

**Comment by lholznagel** [comment]
This is more a [usage question](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md#usage-questions)
Another good source is [Semantic-UI Forum](http://forums.semantic-ui.com/)

**Comment by warlordsd** [comment]
Right now i am connected through entity framework and i had one html search box, which worked well, with some ajax in background, but for this search bar i don't know how to write any scripts or so... that's why i wrote here :)
Anyway thanks :)
