### ISSUE TITLE
[Table] - Text Alignment inside table for inputs

### ISSUE THREAD

**Issue by abinashintrocept** [Semantic-Org/Semantic-UI#4334]
**Steps to Reproduce**
1. Needed to write custom code to align text to right for inputs inside table

**Expected**
I expected that 'right aligned' would align text to right of inputs inside table

**Result**
Inputs inside table do not align their text.

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by jlukic** [comment]
Your test case is empty

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
