### ISSUE TITLE
[List] Icon's font should be "Icons" when using "header"-icon as list's bullet

### ISSUE THREAD

**Issue by arggh** [Semantic-Org/Semantic-UI#4339]
http://jsfiddle.net/yy3e3eaL/

The font-family for the `header`-icon gets replaced by the default font with List's CSS definitions for class `.header`, which results in a rectangle shown instead of the relevant icon.

**Comment by jlukic** [comment]
Your test case is a blank fiddle. Can you please repost.

**Comment by arggh** [comment]
@jlukic Here is the working fiddle, I forgot to name it.

http://jsfiddle.net/9x7m7s5e/1/

**Comment by arggh** [comment]
Opened new issue here: https://github.com/Semantic-Org/Semantic-UI/issues/4393
