### ISSUE TITLE
Proposals to improve the Embed component

### ISSUE THREAD

**Issue by afuno** [Semantic-Org/Semantic-UI#4340]
Hi guys.

In one of the projects I have been actively used Embed component. Here is with anything I encountered:
1. **Text. Description.** Very much lacks the ability to add to the cover (placeholder) text (title) or description. For example, there is one image. And it is used on five video. Evident identification in a simple header in the preview is not.
2. **No icons. Yes - text.** Instead of icons to use the text (for example, "Play kittens").
3. **Other components.** Go back to the first item. The text and the description - it's wonderful. But it is also wonderful - it's ratings and labels.

At the moment, that's all.

Good luck.

**Comment by joaobarcia** [comment]
Agree with this. Also would be great a max size like there is for images (mini, tiny, etc.). I ended up adding it via CSS, but not as elegant as doing it via an "embed.variable"
