### ISSUE TITLE
White buttons

### ISSUE THREAD

**Issue by Captain-GaDo** [Semantic-Org/Semantic-UI#4343]
Hi

First. Congratulations for your excelent css framework.

I want to put a white button in a black backgrounded top bar menu. How i can do this? 

Thanks

**Comment by IonutBajescu** [comment]
Please ask on the forums.

**Comment by batata004** [comment]
@hmontes have you got how to use a white button? I see no white button in semantic ui docs.

**Comment by vinayakkulkarni** [comment]
@batata004 : will this help? http://semantic-ui.com/elements/button.html#basic

**Comment by Banandrew** [comment]
@batata004 It doesn’t exist (basic buttons are transparent). You’ll have to implement it yourself, for example, open `installation_folder/src/site/elements`; the `button.overrides` is a file where you can put your custom [LESS](http://lesscss.org), and `button.variables` is a file where you can put all your custom variables and variable overrides. [Here’re](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/button.less#L1236) different color variations in the source, you basically need to copy any variation under a different namespace, say, `.ui.white.button`, and change its colors.

The best way to figure it all out is to explore SUI’s source to see what classes are available, what rules do they have, and what variables are used. Don’t forget to rebuild the framework every time you change the source files.

**Comment by batata004** [comment]
@Banandrew thanks a lot, I thought I was missing something cause a white button (in my opinion) should be essencial. I will do exactly as you said: copy a variation of another color and just change the color to white everywhere it appears.

Thanks a lot guys, you are awesome!
