### ISSUE TITLE
[Dropdown] - Remote Search Keyboard Navigation in Dropdown from Select is broken

### ISSUE THREAD

**Issue by juice** [Semantic-Org/Semantic-UI#4344]
Hello

the Keyboard Navigation in 2.2.x is broken if the Dropdown is build from a Select and Remote Search is used.

The Keyboard Navigation worked in previous Versions.

https://jsfiddle.net/L7736x8f/1/

**Comment by juice** [comment]
My current workaround:

```js
module.debug('<select> modified, recreating menu');
if(!settings.apiSettings) {
  module.setup.select();
}
```

**Comment by jlukic** [comment]
Fixed
