### ISSUE TITLE
[Modal] Changed settings not applied with onApprove event

### ISSUE THREAD

**Issue by grovduck** [Semantic-Org/Semantic-UI#4345]
I'm wondering if the following behavior is expected or is a bug in modal.  When creating a modal dialog, I try to set a different transition/duration for the ```onApprove``` event before hiding the modal dialog.  I posted [this question](http://stackoverflow.com/questions/38384283/semantic-ui-modal-updated-settings-not-triggered-on-hide) on SO and a working fix was to change the settings in the ```onShow``` event rather than wait to chain together the settings change and the hide in the ```onApprove``` event.  Are the settings change and the 'hide' call being fired asyncronously and thus the settings are not being updated?   Sorry for not understanding this better.

**Comment by jlukic** [comment]
Calling `modal` with a settings object will cause it to be re-initialized (if it exists currently `destroy` will also be called.

To "hot swap" settings, you need to call `settings` with a settings object

```javascript
  $('#test').modal({
    transition: 'horizontal flip',
    duration: 2000,
    onShow: function() {
      $('#test').modal({
        transition: 'fade',
        duration: 10000
      })
    },
    onApprove: function(){
      $('#test').modal('setting', {
        transition: 'fade',
        duration: 10000
      }).modal('hide');
    }
  }).modal('show');
```

Here's a working example of "hot swapping" settings on a component after init.
https://jsfiddle.net/qfghh5ek/

**Comment by grovduck** [comment]
@jlukic, thanks so much for the help.  Is the 'setting' behavior documented that I overlooked (I didn't the 'setting' behavior [here](http://semantic-ui.com/modules/modal.html#/usage))?  Also, this is a pretty minor detail, but the fade seems to be happening in 2000ms instead of 10000ms in the JS fiddle you provided.
