### ISSUE TITLE
Bug - Accordion (in form) remains open even after close()

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4346]
here is the JS fiddle for this issue

https://jsfiddle.net/hvnu8nxd/1/

Basically, form fields are not 'hidden' when accordion is opened

**Comment by jlukic** [comment]
The class names are wrong in this, I'd recommend using the forum for more feedback.

I've gone ahead and given you an example of the correct code
https://jsfiddle.net/6Laygdex/

**Comment by siddo420** [comment]
Thanks
