### ISSUE TITLE
 can not access https://fonts.googleapis.com/css?.....

### ISSUE THREAD

**Issue by zhangfisher** [Semantic-Org/Semantic-UI#4350]
In China can not access the google.com, so the use of semantic-UI is very slow.
The reason is unable to load "https://fonts.googleapis.com/css?family=Lato:400700400italic? 700italic&subset=latin, "
Therefore, I need to manually download "https://fonts.googleapis.com/css? Family=Lato:400700400italic, 700italic&subset=latin" to the local hard disk, and then each time update semantic-ui when manually modify semantic.min.css reference to the right.
I suggest that we can fix this problem, reduce the external dependence, thank you.

**Comment by zhangfisher** [comment]
For the same reason, access to http://semantic-ui.com/ is very slow.

**Comment by jlukic** [comment]
Hi please see #1305 #1768

**Comment by jlukic** [comment]
Use theming variables and set to `useso.com` which mirrors google fonts

**Comment by jo91** [comment]
this external dependence should be removed. It is not only a issue in china but also offline. please reopen.

**Comment by uniquejava** [comment]
The site `useso.com` closed long long time ago, and the solution above (and among other related issues) all not work, please reopen.

**Comment by Banandrew** [comment]
Hi @uniquejava, do you pull SUI from a CDN, or use it locally via NPM?

**Comment by arthurlacoste** [comment]
You can use font locally instead of using Google Font or any CDN :

```js
npm i semantic-ui-offline
```

**Comment by lubber-de** [comment]
Lato 2.0 fonts bundled and googlefont import removed in the official community fork https://fomantic-ui.com by
https://github.com/fomantic/Fomantic-UI/pull/2359
