### ISSUE TITLE
I followed the install guide and the dist folder is not getting created on running gulp build

### ISSUE THREAD

**Issue by dilbertoid** [Semantic-Org/Semantic-UI#4352]
![image](https://cloud.githubusercontent.com/assets/102093/17212508/5b5b68a2-54ed-11e6-8282-e1e8301145ee.png)

**Comment by rlightner** [comment]
I see you closed this issue. Did you actually figure out the problem? I've had this same issue and am scratching my head.

**Comment by vinayakkulkarni** [comment]
What was/is the solution? I'm scratching my head too 😦

**Comment by virtual** [comment]
I had to create a package.json in my project folder using `npm init` and then the dist files were created on build.

**Comment by Harkindey** [comment]
just make sure inside `semantic.json` output is like this
```
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    }
```
