### ISSUE TITLE
Add data attribute to dropdown option

### ISSUE THREAD

**Issue by redayoub** [Semantic-Org/Semantic-UI#4357]
I have a list of car models with an attribute data-brand for each option tag, but after applying the the dropdown plugin, the generated tag contain only data-value attribute. 

Is there a way to add additionnal attributes to each dropdown item ?

**Comment by redayoub** [comment]
up

**Comment by thekendog** [comment]
Did you ever figure this out?  I'm in the exact same position.

**Comment by redayoub** [comment]
Unfortunatelly no :/

**Comment by Banandrew** [comment]
Hi, try to initialize a dropdown on the full HTML pattern instead of initializing it on a `select` element directly:
```HTML
<div class="ui dropdown">
  <input type="hidden" name="gender">
  <i class="dropdown icon"></i>
  <div class="default text">Gender</div>
  <div class="menu">
    <div class="item" data-value="male">Male</div>
    <div class="item" data-value="female">Female</div>
  </div>
</div>
```

**Comment by ebower12** [comment]
I was able to get this to work pretty consistently by attaching a data attribute to the main dropdown object, then just going two more levels to get the selection I want, like this `'[data-testid="region-dropdown"] > div.visible.menu.transition > div:nth-child(4)'`
