### ISSUE TITLE
Blurring class affects dropdowns

### ISSUE THREAD

**Issue by nblackburn** [Semantic-Org/Semantic-UI#4358]
![screen shot 2016-07-29 at 12 46 57 pm](https://cloud.githubusercontent.com/assets/2931085/17247360/9f9339ee-558a-11e6-83a1-10627d8ff739.png)

When the `blurring` class is attached to the body, dropdown menus are displayed incorrectly.

**Showcase**: http://jsfiddle.net/y7a5qr5c/

**Comment by jlukic** [comment]
Blurring uses `filter` which causes a stacking context.

No way around it, except to wrap your page contents in a `div`
http://jsfiddle.net/ftLacj4q/
