### ISSUE TITLE
[Sticky] Dont Require Width/Height to be Set

### ISSUE THREAD

**Issue by Jabark** [Semantic-Org/Semantic-UI#4360]
I've found an issue with the sticky module in that when it initialises it adds height and width to the element, and then when more components are loaded a scrollbar appears which causes the parent container to shrink, however the sticky element does not because it already has the width set to it. I have this issue currently within a Meteor application, however as a quick example of what happens, here's a fiddle to simulate it:

https://jsfiddle.net/3szcuj5z/5/

**Comment by jlukic** [comment]
I think it makes sense to set `width/height` setting as a setting. Some cases are actually helped by forcing the element to a width, as `fixed` position will cause `width: 100%` to apply differently.

**Comment by jlukic** [comment]
Added a new setting in next version `setSize` which determines whether the sticky module should set the size automatically.

Also fixed another issue related to your test case wherer using a `ui sticky` in a relative width container would not resize when the browser size changed.
