### ISSUE TITLE
Visibility not working in Safari

### ISSUE THREAD

**Issue by RobinVerheijen** [Semantic-Org/Semantic-UI#4361]
Hey guys,

Visibility isn't working at all in Safari (macOS, iOS works fine), not in the demo and not in my own project. Using simple code like this:

```
$('.left-showcase-image').visibility({
        once: false,
        onBottomVisible: function (calculations) {

            if(!$(this).hasClass('visible')) {

                $(this).transition({
                    animation: 'fade left',
                    duration: '1500ms'
                });
            }
        }
    });
```

The elements visible in the window on load are triggered, but not on scroll.

I do see these errors: "Element is hidden, you must call refresh after element becomes visible" in the console. Calling the refresh() doesn't fix anything...

Is anybody else experiencing this issue? Does someone have a solution for this?

**Comment by FiF0o** [comment]
@RobinVerheijen I think you have to call .visbility('refresh') after on your element.
Have a look at checkOnRefresh and observeChanges when configuring visibility behaviour
http://semantic-ui.com/behaviors/visibility.html#/settings

**Comment by Banandrew** [comment]
Hi @RobinVerheijen, did it help to call `refresh` afterwards?
