### ISSUE TITLE
Lazload image items in tab

### ISSUE THREAD

**Issue by Teranode** [Semantic-Org/Semantic-UI#4362]
I have a problem where when i use the visible lazyload with tabs and switch to a different tab, the images doesnt load.

**Comment by GDay** [comment]
Confirmed: http://jsfiddle.net/enr5uonk/

When you remove the active class from the first tab and add that to the second tab, it works correctly.

**Comment by jlukic** [comment]
Visibility does not work on content with display none until refresh.

Simple workaround
http://jsfiddle.net/enr5uonk/
