### ISSUE TITLE
[Form] [Validation] "ui error message" div stays shown after field validation errors corrected.

### ISSUE THREAD

**Issue by davidkuhta** [Semantic-Org/Semantic-UI#4363]
Hi there! First: Semantic UI Rocks! Thanks for making it 😄 

Second: https://jsfiddle.net/hcpxqvtL/6/
1. Click submit on blank form
2. Individual fields show errors
3. Correct errors (enter a string and an email address) and red field error outline disappears on the individual fields, but: 
4. `<div class="ui error message"></div>` doesn't disappear (presumably because the error class remains on the form)?

Form worked as expected prior to the update to 2.2
Similar to the issue in #4221 

Note: I also tried adding `on: 'change'` with no success
https://jsfiddle.net/hcpxqvtL/7/

Mac OSX 
Browsers:
Chrome Version 51.0.2704.103 (64-bit)
Safari Version 9.1.2 (11601.7.6)

**Comment by jlukic** [comment]
I'm not seeing this in chrome with your test case. Performing normally with the message hidden.

**Comment by avalanche1** [comment]
@davidkuhta, I guess that is expected. See http://semantic-ui.com/behaviors/form.html - error message disappears only after pressing submit btn for the 2nd time.

**Comment by davidkuhta** [comment]
@jlukic I put together a quick screencast of the example in the SUI docs @avalanche1 mentioned.  It appears Kat had the same experience as me where the error message only disappears after hitting the submit button for the 2nd time.
<a href="http://www.screencast.com/t/QPh0u422" target="_blank">Link to SemanticUIFormValidation.mp4 at Screencast.com</a>

**Comment by lubber-de** [comment]
Fixed for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1611
