### ISSUE TITLE
"visibility()" sometimes cannot report the correct size in events ( "onTopPassed", "onPassing" )

### ISSUE THREAD

**Issue by wisonye** [Semantic-Org/Semantic-UI#4367]
For example I have a list of items, if an item has the <img> inside the DOM, then sometimes the "**height**" in  the **(calculations: IVisibilityCalculations)** is NOT CORRECT even already set the **_"type: 'image'"_**.

Take a look on the debug information:
<img width="1382" alt="visibility_bug_1" src="https://cloud.githubusercontent.com/assets/3477321/17274093/cc3a96b4-5723-11e6-85fc-91360d9ca628.png">
Here is the SAME ITEM DOM which apply "visibility()", Left side is the bad situation which report the wrong _**"height: 97"**_, right side is the correct situation which report the correct **_"height: 616"_**( include the height of the image ) _**AFTER resize the window to make it happen**_ !!!,  the different is **_"616 - 97 = 519px"_**, that's the image height exactly !!!

**Comment by jlukic** [comment]
Give your images defined heights, if you must set images to be fluid height then call `visibility('refresh')` after all images are loaded.  There's no way to determine an images aspect ratio until it is downloaded which will occur after JS fires (so refresh is necessary).

Keep in mind future bug reports should include discrete JSFiddle test cases. Screenshots are not adequate to triage and fix issues.
