### ISSUE TITLE
Angular-JS Checkbox-Radio Button

### ISSUE THREAD

**Issue by joarix3** [Semantic-Org/Semantic-UI#4369]
Im working with Angular-JS, and the Radiobuttons events and checkbox events, doesn´t trigger, and i can´t get the values of the selected item, any idea?

**Comment by GDay** [comment]
Have you added this to the end of your code (just before the `</body>` tag)?
```
<script>
$('.ui.radio.checkbox')
  .checkbox()
;
</script>
```
Have you also included a jQuery script?
If so, could you create a jsfiddle to show what you have done? That would make it easier to find the problem.

**Comment by goors** [comment]
same here. not working!

**Comment by devin42r** [comment]
I'm not sure if this is related, but there is a conflict between Semantic UI's ".checkbox()" and Angular's ng-model binding on the input values.  Trying to figure out a way around, but might have to end up ditching Semantic's styling because I can't see another way to access value Angular side.
