### ISSUE TITLE
Feed with dropdown-menu

### ISSUE THREAD

**Issue by hmontes** [Semantic-Org/Semantic-UI#4372]
Hi

I can't put a Feed in a dropdown menu. Like "Notifications" button on Facebook, linkedin, Udemy, etc.

It is possible to do that in semantic-ui?

Thanks

**Comment by H3ll0W0rld** [comment]
I don't think you can put Feed in Dropdown. But you can have semantic Popup and can be opened on click. Inside custom popup you can have any content you want.

Cheers
