### ISSUE TITLE
Semantic UI Getting Started

### ISSUE THREAD

**Issue by navigate27** [Semantic-Org/Semantic-UI#4373]
The tutorial for installing semantic for Windows is not for windows. The referring about the video. Well, I can say that it is just a minor lapse but for the beginners I'm worried they would confused. Thanks!

**Comment by vinayakkulkarni** [comment]
@navigate27, we understand if it may confuse users, hence
1. [github issues](https://github.com/Semantic-Org/Semantic-UI/issues)
2. [gitter](https://gitter.im/Semantic-Org/Semantic-UI)
3. [forums](http://forums.semantic-ui.com/)

Closing this as it has nothing to do with the framework itself.
