### ISSUE TITLE
[Button] "right labeled icon" buttons conflict with "pointing"

### ISSUE THREAD

**Issue by qmarlats** [Semantic-Org/Semantic-UI#4377]
Hi!
It's not possible to have a button with a right labeled icon with a center pointing. If I do something like "ui right labeled icon button pointing top dropdown" the pointing is on the right.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by qmarlats** [comment]
I'm sorry but this issue is pretty old and I absolutly don't remember what I was trying to do. ^^ I close this issue since I will never be able to reproduce the thing I wanted to do.
