### ISSUE TITLE
[Help] - Tabs with buttons

### ISSUE THREAD

**Issue by DarkSoulGaming** [Semantic-Org/Semantic-UI#4391]
I added a button inside a tab area which is supposed to change to the second tab but it doesnt so is there a way i can do it thanks.
Codes,
https://codepad.co/snippet/2EuZXDqO

**Comment by onanypoint** [comment]
I was able to get a workaround using the answer of @larsbo on #3544. Even tough you might already have found an answer, I post it here for others.

http://jsfiddle.net/onanypoint/yf0z1pud
