### ISSUE TITLE
[Dropdown] Search-in menu keeps opening and closing in IE 11

### ISSUE THREAD

**Issue by LennyDiggelen** [Semantic-Org/Semantic-UI#4392]
I have copied an example from http://semantic-ui.com/modules/dropdown.html#/definition which is the search-in menu (the gray one). 

When you try to open this element in IE11, it keeps opening and closing. I have the same issue with a project of mine. The example below this one works but the layout differs from the one that's buggy.

Can you have a look into it?

**Comment by LennyDiggelen** [comment]
If you debug, You will see the onOpen function fire non-stop

**Comment by arbiasgjoshi** [comment]
@LennyDiggelen - Did you happen to find any solution to it?

**Comment by lennardino** [comment]
@arbiasgjoshi no I haven't. We chose to go with a different approach and the  GitHub doesn't seem very quick with replies. 

You could catch the onOpen function and build somthing around it, but I don't think that's the way to go
