### ISSUE TITLE
UI Search Dropdown

### ISSUE THREAD

**Issue by tuxy** [Semantic-Org/Semantic-UI#4400]
Hey everyone, I have a search code something like this below. But I can't figure out a way on how to do few things like; Perhaps some of you may help with some of this. Some actual code examples are appreciated (exp: jsfiddle). Thank you so much in advance.

Issues:
* on Escape Key -- close the search dropdown box.
* onChange -- actually change the search input text (aka "prompt") form field with title.

HTML Code:
```html
<div class="ui right aligned category search item">
  <div class="ui inverted transparent icon input">
    <input class="prompt" type="text" maxlength="20">
    <i class="search link icon"></i>
  </div>
  <div class="results"></div>
</div>
```

JavaScript Code:
```javascript
$(document).ready(function () {
  $('.ui.search').search({
    apiSettings: {
      method: "POST",
      url: "http://domain.com/search?find={query}"
    },
    fields: {
      results: "items",
      image: "image",
      title: "title",
      url: "link",
    },
    error: {
      serverError: 'Nothing is found...'
    },
    onSelect: function(result, response) {
      window.location.href = result.link;
    },
    maxResults: 5,
    minCharacters: 5,
  });
});
```

**Comment by jlukic** [comment]
The relevant API bits are `$('.ui.search').search('hide')` and `$('ui search').search('set value', 'baz');`
