### ISSUE TITLE
[Icon] Comments icon being displayed in wrong sizes

### ISSUE THREAD

**Issue by marcelodeolive1ra** [Semantic-Org/Semantic-UI#4404]
The comments icon rules are conflicting with the rules of the `comments` component. When using, for example, `<i class="ui huge comments icon"></i>`, the size displayed doesn't correspond to the `huge` size. Same happens with other sizes:

http://jsfiddle.net/mndr1ozp/1/

**Comment by ilanus** [comment]
@marcelodeolive1ra Thanks! I've already made a pull request

**Comment by lubber-de** [comment]
Fixed in https://github.com/fomantic/Fomantic-UI 2.6.1
