### ISSUE TITLE
How to handle such as WARN deprecated ... ?

### ISSUE THREAD

**Issue by kwaninmacau** [Semantic-Org/Semantic-UI#4405]
Hi, 
When I install semantic-ui by gulp, I got such as warning as below:
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`
I check these modules and found some of them are already the latest version and some ones in some submodules are old version and some other in some submodules are the latest version.
Why?How should I do to handle these issue?
Thank you!

**Comment by lholznagel** [comment]
This is not an issue, this is more a problem from the package owner of the dependencies. You will find this sort of warning on many packages.

**Comment by ilanus** [comment]
npm install -g graceful-fs graceful-fs@latest

**Comment by kwaninmacau** [comment]
Thank you!

**Comment by IonutBajescu** [comment]
As @lholznagel said, you can simply ignore that warning.
