### ISSUE TITLE
Responsive grid not working as expected?

### ISSUE THREAD

**Issue by aristidesfl** [Semantic-Org/Semantic-UI#4414]
Hi, I'm trying to achieve different column sizes for computer vs tablet/mobile. The smaller row works fine (because it is shrunk on computer). The larger column, is always stays in the computer size. It never shrinks back to default size. 
How is this supposed to work?

http://codepen.io/anon/pen/rLQqao?editors=1100#

---

EDIT: The documentation code works because the column is shrinking on specific screen sizes. But it wouldn't work if the column was enlarging on specific screen sizes.

```
<div class="ui grid">
  <div class="four wide two wide large screen one wide widescreen column">
    <p></p>
  </div>
  <div class="four wide two wide large screen one wide widescreen column">
    <p></p>
  </div>
  <div class="four wide two wide large screen one wide widescreen column">
    <p></p>
  </div>
  <div class="four wide two wide large screen one wide widescreen column">
    <p></p>
  </div>
</div>
```

**Comment by adamcollingburn** [comment]
You're missing a device class at the start:

'four wide two wide' should be 'four wide tablet two wide'... etc.
