### ISSUE TITLE
[Grid] Middle Aligned, Celled Grids Should Have Cell Borders That Fill the Height of the Grid Row

### ISSUE THREAD

**Issue by scimed-external** [Semantic-Org/Semantic-UI#4424]
When using middle aligned in combination with celled grids, grid-line borders are only as tall as the height of the cell they apply to rather than filling the entire height of the grid row.

http://jsfiddle.net/4pxwktvc/2/

**Comment by Maregas** [comment]
I've the same problem, sad to see that issue was closed with no answer...
