### ISSUE TITLE
Vertical divider problem in Chrome

### ISSUE THREAD

**Issue by TheSwash** [Semantic-Org/Semantic-UI#4426]
With the last stable version of Google Chrome there is a problem with Vertical Divider. What's happening is the vertical line is placing at left of the content. You can see it here:
http://jsfiddle.net/Ivyk/s4jbnnap/

The problem is in the selector: 
`.ui.grid > .column + .divider { left: auto; }`

Cheers!

**Comment by jlukic** [comment]
This is a regression in Chrome 52, convo is here
https://bugs.chromium.org/p/chromium/issues/detail?id=633011#c11
