### ISSUE TITLE
Meteor integration with several errors

### ISSUE THREAD

**Issue by joaobarcia** [Semantic-Org/Semantic-UI#4427]
Hi everyone,

I had to jump a few hurdles in order to setup Semantic with Meteor:

## Challenge 1
I have just updated to the most recent meteor and was not aware what the package.json file was. Maybe the integration documentation could refer to https://guide.meteor.com/using-npm-packages.html

## Error 1
```
 While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from packages/minifier-postcss_plugin.js. Check your Npm.depends().
```
Fixed by running
`meteor npm install --save autoprefixer
`
## Error 2
Styling still not displayed. Fixed by manually creating custom.semantic.json as recommended in https://forums.meteor.com/t/semantic-ui-not-working/6535/4?u=joaobarcia

## Error 3
```
W20160811-18:13:46.219(1)? (STDERR) ReferenceError: jQuery is not defined
W20160811-18:13:46.220(1)? (STDERR)     at meteorInstall.lib.semantic-ui.definitions.behaviors.api.js (lib/semantic-ui/definitions/behaviors/api.js:1171:5)
```
Fixed by moving custom.semantic.json as per: http://stackoverflow.com/questions/31504801/jquery-is-not-defined-in-meteor-app#31786101

**Comment by jlukic** [comment]
You can just use our atmosphere packages. I'm not sure about NPM compatibility with Meteor, but my experience working with it hasn't been wonderful.

**Comment by joaobarcia** [comment]
@jlukic thanks for the quick reply. The process I described was using  the atmosphere packages. And in Meteor forums it seems a couple of people have been facing similar issues

**Comment by fvpDev** [comment]
+1 !!
