### ISSUE TITLE
CDN delivery - Javascript does not work

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI#4429]
Hi, when I try to add semantic from CDN it does not work. All styles work just fine, but javascript does not load. 

I used following

```
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.2/semantic.min.css">
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.2/semantic.min.js"></script>
```

And then in body:

```
$('#id').dropdown() // throws error that $(...).dropdown is not a function
```

Any idea?

[EDIT] 

The only way I could make it work is to do `npm i semantic-ui-css` and then `import 'semantic-ui-css/semantic.min.js'` in my client.js file.

**Comment by IonutBajescu** [comment]
Please provide a jsfiddle. 

Although I kind of have the impression you're loading jquery twice in your page, so please also check the network console and make sure jquery is loaded just once.

**Comment by tomitrescak** [comment]
@IonutBajescu could very much be the case of having two jqueries as I am using meteor and it possibly loads its own instance, any way I can check it out?

**Comment by IonutBajescu** [comment]
@tomitrescak Yeah, remove your own jquery from the page. If Meteor loads its own, you shouldn't be required to include yours as well. 

Also, I hope you're using the meteor integration - it might save you some hassle.
https://github.com/Semantic-Org/Semantic-UI-Meteor

**Comment by Banandrew** [comment]
Hi @tomitrescak,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
