### ISSUE TITLE
Multiple selection dropdowns

### ISSUE THREAD

**Issue by azmeuk** [Semantic-Org/Semantic-UI#443]
Hi,
It would be great to have the possibility to combine dropdown menus and checkboxes and allow multiple selection dropdowns.

**Comment by mattiasflodin** [comment]
I made a JS Fiddle example for people who come here from Google like I did. I think it works really nicely as an alternative to standard multi-select dropdowns and I didn't find any example in the docs so here you go: https://jsfiddle.net/jp8xj0wk/

**Comment by vandolphreyes** [comment]
@mattiasflodin thanks for sharing mate!
