### ISSUE TITLE
ui.celled.grid makes html/body higher than the view port

### ISSUE THREAD

**Issue by osenvosem** [Semantic-Org/Semantic-UI#4432]
Example:
https://codepen.io/osenvosem/pen/jAdWvm

**Comment by jlukic** [comment]
That's caused by margin-collapse a fun feature of css. It's not something I can control in a framework level, but there are a few fixes that can fix this, for example adding an `overflow` prop to the containing element.

https://codepen.io/anon/pen/YWBOGJ
