### ISSUE TITLE
[Icon] Add "Admin" User Type Icon

### ISSUE THREAD

**Issue by ronlut** [Semantic-Org/Semantic-UI#4433]
I think an admin icon can be a good addition to the "User Types" icon group.
Thanks :)

**Comment by nblackburn** [comment]
SemanticUI uses [FontAwesome](http://fontawesome.io/icons/) for it's icons so you have full access to hundreds of icons if you so wish.

**Comment by ronlut** [comment]
@nblackburn thanks, added there.
