### ISSUE TITLE
[Breadcrumb] Setting variable @verticalMargin has no effect

### ISSUE THREAD

**Issue by foliz** [Semantic-Org/Semantic-UI#4440]
I tested the breadcrumb as followed:
```
<div class="ui container">
    <div class="ui main small breadcrumb">
        <span>You are here: </span>
        <a class="section" href="index.html">Home</a>
        <i class="right angle icon divider"></i>
        <a class="section" href="services/whatido.html">What I do</a>
        <i class="right angle icon divider"></i>
        <div class="active section">Details</div>
    </div>
</div>
```
And I set `@verticalMargin: 1em;` in `site/collections/breadcrumb.variables` but it seems to have no effect due to the following code in `definitions/collections/breadcrumb.less`:
```
.ui.breadcrumb:first-child {
  margin-top: 0em;
}
.ui.breadcrumb:last-child {
  margin-bottom: 0em;
}
```
Indeed, `margin-top: 0em;` and `margin-bottom: 0em;` override whatever I put in `@verticalMargin`.

Is there something I am missing here?

**Comment by jlukic** [comment]
First and last elements have no top or bottom margins in SUI. This is so elements sit flush in their containers when first or last. Vertical margin will affect breadcrumb position when another sibling element is before or after it.
