### ISSUE TITLE
[Popup] Tooltip should work with disabled buttons

### ISSUE THREAD

**Issue by nix1** [Semantic-Org/Semantic-UI#4442]
**Current behaviour**
Popups, for instance pure CSS tooltips in particular, don't work with buttons that have a `disabled` class present.
Example: http://jsfiddle.net/fd9pnp3o/1/

**Expected behaviour**
It should be possible to add a tooltip also to a disabled button. A real use case is explaining why the button is not active.

**Comment by nix1** [comment]
Now a technical remark:
This is caused by `pointer-events: none;` set on the button, so the `:hover` state is never activated.
Also, tooltips would receive the same opacity that the disabled button has, which might make the right solution more difficult.

A simple workaround for now is overriding `pointer-events` to `auto` and using and `inline` variant of the popup (so that it's not a child of the button). Unfortunately then the button receives a light but still undesirable hover effect.

**Comment by larsbo** [comment]
This has been discussed several times, see #3536, #4285, #4296.

**Comment by nix1** [comment]
Thanks for your answer. I see that wrapping the button in another element looks cleaner than overriding `pointer-events`.

However, it pretty much means that the tooltips should always go into the wrapper if the button can ever enter the disabled state. Perhaps it would make more sense to set proper color on the button instead of using opacity? You can take a look at http://jsfiddle.net/fd9pnp3o/2/ .
