### ISSUE TITLE
[Popup] - observeChanges Option Never Gets Used

### ISSUE THREAD

**Issue by Francodes** [Semantic-Org/Semantic-UI#4444]
Hello guys,

Found a weird bug when working with popups on our Angular company web app.

In the documentation, it mentions that one is able to create a Popup and include the option `observeChanges` in order to toggle the `MutationObservers` to destroy the module based on DOM changes. 

When looking at the [source code](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js#L10125), this option doesn't seem to get used when setting up the Mutation Observers.

I noticed in the [Sticky module](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js#L16370), that there exists an if statement to gate this code path using the `observeChanges` option from the module's settings.

Shouldn't there be an if statement somewhere to gate this code path in the Popup module?

**Comment by jlukic** [comment]
Yep observeChanges is not obeyed in current release, the setting was accidentally omitted. This has been fixed in `next` release https://github.com/Semantic-Org/Semantic-UI/commit/549e61f35e5b7bf5612ca1df7be7eb72014f82dd

**Comment by Francodes** [comment]
Awesome! Thank you for the speedy response!
