### ISSUE TITLE
[Validation] - Dependant Validation should work with Radio Buttons

### ISSUE THREAD

**Issue by mwhiterabbit** [Semantic-Org/Semantic-UI#4445]
Hello,

I am trying to make certain textboxes required depending on which radio button is selected. But instead of only 1 textbox being required all are required and preventing submission. Using a checkbox works as intended in the docs. 

[js fiddle](https://jsfiddle.net/mwhiterabbit/6exxn5s7/)

**Comment by ultraN** [comment]
I've this problem too and I agree, also the depends field should also work with dropdown selection.

**Comment by lubber-de** [comment]
Implemented since Fomantic-UI 2.7.2 by fomantic/Fomantic-UI#372
