### ISSUE TITLE
Dropdown height is not equal to input height

### ISSUE THREAD

**Issue by dzolnjan** [Semantic-Org/Semantic-UI#4447]
http://semantic-ui.com/collections/form.html

In that second form example it is visible that CVC input and Expiration dropdown are not same height. (just slightly off but still visible, and it is more obvious when controls are bigger)

Is that a feature or bug?

**Comment by jlukic** [comment]
Duplicate #4279  the em calculations are actually fairly complex to get the rounding to work correctly with descending glyphs on inputs. I'm still working on a solution.
