### ISSUE TITLE
popup and labeled buttons

### ISSUE THREAD

**Issue by amirmasoud** [Semantic-Org/Semantic-UI#4449]
![untitled](https://cloud.githubusercontent.com/assets/4637052/17787305/ceff5d2a-659d-11e6-8625-9b1b519ac140.png)

button label left angle icon is on top of the popup.

**Comment by vinayakkulkarni** [comment]
@amirmasoud, Please provide a test case as per our contribution guidelines, you may fork [this jsfiddle](http://jsfiddle.net/efp8z6Ln/)

Closing this till you provide a test case.

**Comment by Banandrew** [comment]
Couldn’t reproduce as of `2.2.9`.
