### ISSUE TITLE
[validation] Form wish allowAdditions

### ISSUE THREAD

**Issue by LIN727** [Semantic-Org/Semantic-UI#4453]
i have allowAddtions dropdown When create a label  enterKey trigger whole form validation,but this form have one `<input type="text">` then not trigger form validation.

another Issues is Has been set `dropdown` maxSelections but  when click submit button `dropdown` Automatically creates a tag.

http://jsfiddle.net/IIN727/8jr2xor6/1/

**Comment by Banandrew** [comment]
Hi @LIN727, it’s been a while, please let me know if you’re still interested in the solution.
