### ISSUE TITLE
[Dropdown] restore defaults does not clear active item

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#4456]
Hi,

Seems to be a small glitch with dropdown, when `restore defaults` is used to reset it. Here's a [fiddle](http://jsfiddle.net/andreyvk/1yqgf3ap/)

**Steps to reproduce:**

1. Select an item from dropdown
2. Dropdown will immediately reset itself to defaults
3. Open dropdown and see the last selected item highlighted (in bold).

Looks like `active` class is not cleared out properly.

**Comment by jlukic** [comment]
This is because `active` is added after `onChange`. You can add a setTimeout, or set restore defaults after `onHide`

http://jsfiddle.net/jmzwsb4a/

**Comment by andreyvk** [comment]
@jlukic it's understandable that `active` state can be removed later manually, but i do not understand why shouldn't the library remove it automatically.  when calling `restore defaults` an `onChange` is being fired, which technically indicates that item's changed, but visually it didnt. how can you justify this behavior?
