### ISSUE TITLE
Link and Unlink icons not showing in 2.2.2

### ISSUE THREAD

**Issue by shamusmac** [Semantic-Org/Semantic-UI#4457]
Link and Unlink icons are not showing in today's download of https://github.com/Semantic-Org/Semantic-UI/archive/master.zip (2.2.2).

Reproduce with HTML:
`
<i class="link icon"></i>
<i class="user icon"></i>
<i class="unlink icon"></i>
`

Outcome:
Only user icon shows.

**Comment by Slowhand0309** [comment]
You should try change from `(un)link` to `(un)linkify`.
```
<i class="linkify icon"></i> <i class="user icon"></i> <i class="unlinkify icon"></i> 
```

**Comment by vinayakkulkarni** [comment]
Kindly read the icons docs [Here](https://semantic-ui.com/elements/icon.html#text-editor)

`linkify` and `unlinkify` are the classes to be used as @Slowhand0309 said.
