### ISSUE TITLE
[List] Horizontal List doesnt seem to work

### ISSUE THREAD

**Issue by saikrishna2deep** [Semantic-Org/Semantic-UI#4460]
Hi,

I've created 2 simple examples here

**Normal Vertical List** (working) :+1: 

http://jsfiddle.net/skd/at4z4m1a/

**Horizontal List** (broken) :-1: 

http://jsfiddle.net/skd/at4z4m1a/1/

I'm not sure why this seems to be happening. I checked it multiple times. I added some custom CSS for some elements in the item. But I don't think that seems to be the problem. Because even without the classes added it's causing a problem.

**Comment by jlukic** [comment]
This is related to your custom css with `actor`, and the additional styles on the page. Please try to show bugs using only SUI framework code and the minimum required code to reproduce.
http://jsfiddle.net/1vf0djgp/
