### ISSUE TITLE
UI Form validation-rules(regExp) does not work.

### ISSUE THREAD

**Issue by xiwc** [Semantic-Org/Semantic-UI#4462]
eg:
`regExp[/((^ssh-(rsa|dss))|^ecdsa-sha2-nistp256)\s(.{125,})\s.+@.+/]` does not work.

but, custom form validation rule work fine using the same regExp.

```
    // custom form validation rule
    $.fn.form.settings.rules.pubkey = function(value) {
        return /((^ssh-(rsa|dss))|^ecdsa-sha2-nistp256)\s(.{125,})\s.+@.+/.test(value);
    };
```

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by vinayakkulkarni** [comment]
@xiwc : Kindly provide a test case as per our guidelines, once you do, I'll reopen the issue.
