### ISSUE TITLE
add rtl css files to github

### ISSUE THREAD

**Issue by DediData** [Semantic-Org/Semantic-UI#4464]
Hi
Congratulations for this great framework
Just I need to have RTL CSS files in CDNs
I think you can add those files in github to update CDNs automatically

https://cdnjs.com/libraries/semantic-ui
or
https://www.jsdelivr.com/projects/semantic-ui

Thank you very much

**Comment by parsmizban** [comment]
Hi,
BUMP!

**Comment by parsmizban** [comment]
BUMP! Pleaseeeeeee
