### ISSUE TITLE
Keyboard control of search input is broken in 2.2.3

### ISSUE THREAD

**Issue by cbxp** [Semantic-Org/Semantic-UI#4469]
IMHO, this is a major bug that makes Semantic 2.2.3 unusable. 2.2.1 has no such problem.

Even here in the demo, try using up-down arrow keys to navigate between search results - the selection will start jumping erratically, making it very hard to use.

http://semantic-ui.com/modules/search.html#/definition

**Comment by jlukic** [comment]
Im going to try to hammer this out in a patch tonight.

**Comment by jlukic** [comment]
It's related to fix for zones.
https://github.com/Semantic-Org/Semantic-UI/commit/d028ed19b06ec25ddb033476eff8cebf2338abd7

**Comment by jlukic** [comment]
Fixed in just released `2.2.4`

**Comment by cbxp** [comment]
Thanks for the fix. Do you have any idea why semantic-ui-less 2.2.4 is not
available in npm?
