### ISSUE TITLE
[Form Validation] Tabbing between fields when “on:blur” is set should show error messages

### ISSUE THREAD

**Issue by neokio** [Semantic-Org/Semantic-UI#4475]
This is a two-parter:

1) Aside from the technical description on http://semantic-ui.com/behaviors/form.html#/settings, there is no clarification of ...
a) any differences in behavior,
b) whether or not different parameters can be combined, or if there's a way do one then another,
c) how to programatically trigger a .ui.error.message (such as with jquery+ajax)

2) With "on:blur", the .ui.error.message box does not appear! I've made a codepen illustrating the problem: http://codepen.io/anon/pen/QERYLW ...
a) Focus the first input, tab to the next. Here, I'd expect it to go red AND show my prompt.
b) With the second input focussed, hit tab. Again, it's red, but doesn't prompt why.
c) Now hit the Submit button. Prompts appear.

If this isn't a bug, I believe it's an unfortunate crippling of the validation feature. Hoping it's a bug and not an imposed limitation.

**Comment by neokio** [comment]
Ping.

**Comment by atotalpirate** [comment]
I found this trying to do the same thing.

**Comment by lubber-de** [comment]
This has been fixed in the community fork [Fomantic-UI](https://fomantic-ui.com) by https://github.com/fomantic/Fomantic-UI/pull/1809
See your adjusted example here https://jsfiddle.net/lubber/69x1uq4v/
