### ISSUE TITLE
[Label] use transparent basic label backgrounds

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI#4476]
## Issue

Currently, `basic` labels have a background color of `#FFF !important`.  This makes them unusable on backgrounds of other colors.
## Proposal

I propose the background for basic labels instead be transparent.  This way they are usable on any background.  Transparent basic backgrounds are also consistent with `ui basic button`.
## Comparison

![image](https://cloud.githubusercontent.com/assets/5067638/17913724/f5e05ff0-6950-11e6-951c-5978b3e4cb53.png)

![image](https://cloud.githubusercontent.com/assets/5067638/17913712/e4511752-6950-11e6-90b5-c261cab40e50.png)

**Comment by vinayakkulkarni** [comment]
This is an old issue and basic label has been implemented post 2.1

It's in the docs [Here](https://semantic-ui.com/elements/label.html#basic)

**Comment by Banandrew** [comment]
@vinayakkulkarni The issue is not that there were no basic labels, but that it’s inconsistent with other components. I’ll reopen it as enhancement, will submit a PR as soon as I can.

**Comment by levithomason** [comment]
See #6220
