### ISSUE TITLE
Backslash in css urls when building on windows

### ISSUE THREAD

**Issue by geleto** [Semantic-Org/Semantic-UI#4477]
Hello, there's a backslash in the css urls when building semantic-ui 2.2.2 on windows. In your css-only release this problem is not present, so I guess it's a windows-only issue:
```css
src: url(".\themes/default/assets/fonts/icons.eot");
src: url(".\themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), 
url(".\themes/default/assets/fonts/icons.woff2") format('woff2'), 
url(".\themes/default/assets/fonts/icons.woff") format('woff'),
url(".\themes/default/assets/fonts/icons.ttf") format('truetype'), 
url(".\themes/default/assets/fonts/icons.svg#icons") format('svg');
```
This messes up the resource loading in [aurelia](http://aurelia.io/).

**Comment by jlukic** [comment]
This was fixed in `2.2.3` 
https://github.com/Semantic-Org/Semantic-UI/commit/961b4c90680e8d3c1e423fbf9c0fdaf20d1e87af

https://github.com/Semantic-Org/Semantic-UI/issues/4174
