### ISSUE TITLE
[Message] - message not filling the whole width

### ISSUE THREAD

**Issue by geekrumper** [Semantic-Org/Semantic-UI#4478]
**Steps to Reproduce**
1. fork my fiddle

**Expected**
The Message should fill the whole given width (green background)

**Result**
The Message is being "compact" allthough that class attribute is not declared

**Testcase**
(fork this to get started)
http://jsfiddle.net/Geekrumper/rduvhn8u/134/

**Version**
2.2.2

**Comment by cwbit** [comment]
```html
<div class="ui sixteen wide column pink">
      <div class="ui floating message">
        <i class="icon check"></i> It's all about the sixteen wide, yo
      </div>
    </div>
```

**Comment by jlukic** [comment]
You need to put page contents inside `column`
