### ISSUE TITLE
[Modal] Prevent modal actions buttons from clicking twice

### ISSUE THREAD

**Issue by kbariotis** [Semantic-Org/Semantic-UI#4479]
Modal contains transitions to showing on the screen. Action buttons are able to be clicked more than once while a modal is transitioning.

Here's an example http://jsfiddle.net/rajsnzxw/10/. Open console and try to click the button more than once aggressively.

I was wondering whether this behavior is something that Semantic's code must handle. In my current project, there is no way to fix this issue globally without adding side effects on my code base.

Thank you

**Comment by jlukic** [comment]
Yes, we should probably handle rapid clicking on a framework level.

**Comment by jlukic** [comment]
Fixed in `next`

**Comment by kmd1970** [comment]
Unfortunately this is **not** fixed in 2.2.10

https://jsfiddle.net/kmd1970/8joakfjh/

**Comment by lubber-de** [comment]
@kmd1970 It is actually fixed. But your fiddle is slightly wrong: You've bound the show trigger to **all** buttons including the buttons from the modal itself: See your fixed fiddle here: https://jsfiddle.net/16o8Ly0n/
