### ISSUE TITLE
(Request) Fluid inline form please?

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI#4480]
Something similar to Bootstrap's `.form-horizontal` form where `<label>` is right-aligned and the `<input>` are always 100% in width.

I can make a work around for this but it's good for SUI to already have that option.

**Comment by ttv20** [comment]
Here is a simple solution with semantic-ui:
[https://gist.github.com/ttv20/58497240926ee87126550b9fdb2a631a](url)
Demo: [http://codepen.io/anon/pen/pRzBVw](url)
Its table without border and the labels column take minimum width

**Comment by vinayakkulkarni** [comment]
It can be achieved using the last example given [here](https://semantic-ui.com/collections/form.html#fields)
