### ISSUE TITLE
Attached menu not flush with segment sides

### ISSUE THREAD

**Issue by purplecones** [Semantic-Org/Semantic-UI#4483]
![edit_fiddle_-_jsfiddle](https://cloud.githubusercontent.com/assets/136654/17992499/d7ebcac2-6b15-11e6-90b5-c6d4dbdf4c2f.png)

http://jsfiddle.net/LrgocmLy/

**Comment by nblackburn** [comment]
Related to #4248

**Comment by purplecones** [comment]
Great, Thanks.
