### ISSUE TITLE
tabindex with input and dropdown

### ISSUE THREAD

**Issue by Rafabin** [Semantic-Org/Semantic-UI#4484]
the tabulation does not work in order
In this case, the order runs from 1 to 3

`<div class="seven wide column">
       <div class="field">
		<label class="lbGepPessoaId">Filial</label>
			<select class="ui input mini search GepPessoaId" name="GepPessoaId" tabindex="1"/></select>	 
	</div>
</div>`

`<div class="two wide column">
	<div class="field">
		<label class="lbAlmSolicitacaoQuantidade">Quantidade</label>
			<div class="ui input mini">
				<input type="text" class="AlmSolicitacaoQuantidade money inp_text_right" name="AlmSolicitacaoQuantidade" tabindex="2" value="<?php echo isset($result[0]->AlmSolicitacaoQuantidade) ? $result[0]->AlmSolicitacaoQuantidade : ''; ?>"/>
			</div>		 
		</div>
</div>`

`<div class="three wide column">
	<div class="field">
		<label class="lbEstPrioridadeId">Prioridade</label>
		<select class="ui input mini search EstPrioridadeId" name="EstPrioridadeId" tabindex="3"/></select>	 
	</div>
</div>`

**Comment by jlukic** [comment]
Please reopen using a JSfiddle test case forked from the readme.
