### ISSUE TITLE
Got a tweet for 2.2.5 but still stuck at 2.2.4, and 2.2.1 for Meteor: why, mate, why?!

### ISSUE THREAD

**Issue by fvpDev** [Semantic-Org/Semantic-UI#4485]
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/104

**Comment by jlukic** [comment]
The tweet was incorrect, the latest version is `2.2.4`, Ping @flemay in the meteor repo for updates to atmosphere package.
