### ISSUE TITLE
How hide the tags which are already entered into input

### ISSUE THREAD

**Issue by karmis** [Semantic-Org/Semantic-UI#4489]
Kind time.
  Whether there is an opportunity in dropdown.module or search.module in case of { allowAdditions: true } not to show the tags which are already entered into input in the list of tags loaded through ajax

ex: 
http://dl2.joxi.net/drive/2016/08/28/0004/1376/279904/04/d29ef42ab4.jpg

**Comment by jlukic** [comment]
You can use `onResponse` of `apiSettings` to modify the response to remove values from `get selected`
