### ISSUE TITLE
[Dropdown] Search In-Menu Should Open With Keyboard

### ISSUE THREAD

**Issue by andrewtrickett** [Semantic-Org/Semantic-UI#4490]
Search In-Menu dropdowns can't be opened by keyboard users on tab as it just skips to the next input.

If  a tabindex is manually placed on the dropdown then the dropdown opens and closes straight away.

[Fiddle](http://jsfiddle.net/xc6dkqka/)

**Comment by jlukic** [comment]
I believe `has.search` on this like should be `is.searchSelection` 
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2186

**Comment by andrewtrickett** [comment]
Thanks for the quick reply.

I changed the code to `is.searchSelection` and it does now add a tabindex="0" to the dropdown, but then it immediately closes the dropdown when you try and open it, like the last dropdown on the fiddle with a manually added tabinddex. It looks like it is closing the dropdown when the search input gets focus.

**Comment by James1x0** [comment]
I think I have also been bitten by this. [JSFiddle & repro instructions](https://jsfiddle.net/8yrkozeL/2/)

Makes a bad experience for power users.

**Comment by jlukic** [comment]
This is pretty bad

**Comment by jlukic** [comment]
Fixed in `next`
