### ISSUE TITLE
[Divider] - The horizontal divided is on  the left side instead of being in the middle

### ISSUE THREAD

**Issue by sunildhillon** [Semantic-Org/Semantic-UI#4491]
**Steps to Reproduce**
1. Just visit the main website of semantic ui, and visit the divider page. 

**Expected**
The Divider was supposed to be b/w the two columns, 

**Result**
The Divider is shown on the left side before the 1st column.

**Comment by jlukic** [comment]
Duplicate #4342 

See:
[Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
