### ISSUE TITLE
[Dropdown] (Multiple) Remote Should Allow Calls Like 'Set Selected'

### ISSUE THREAD

**Issue by Ribesg** [Semantic-Org/Semantic-UI#4492]
Just try it: http://jsfiddle.net/htnn93ww/
The button should work, it doesn't.

I added a few settings in my jsfiddle, because it should work in every cases, but it still doesn't work without any specific setting.

It should not check that the programmatically set parameters are possible values according to the remote endpoint, or maybe it could in the future via a setting, but I don't have any use case for this.

**Comment by Ribesg** [comment]
For people encountering this problem, here is a workaround. The procedure described here is to set the field's exact value, removing old values entirely, but you can adapt it.

Let's say our remote-dropdown has the id `dropdown`.

1. Remove old labels. Basically anything matching `#dropdown .ui.label`.
2. Add labels for your values. Insert this before `#dropdown input` for each value:

    ````
<a class="ui label transition visible" data-value="theValue" style="display: inline-block !important;">theValue<i class="delete icon"></i></a>
````
3. Remove old select options. Anything matching `#dropdown select option[value][value!='']`.
4. Add select options for your values. Append this to `#dropdown select`:

    ````
<option value="theValue" class="addition">theValue</option>
````
5. Finally, set the `select` value to your array of values.

Here is the code I am using (using jQuery, and I rely on the select having an id, not the dropdown):
````
        /**
         * Sets the value of a Semantic UI multi-select-dropdown, as a workaround to the
         * builtin way not working.
         * @param {string}   selector - The 'select' selector
         * @param {string[]} values   - The value to set, may be empty
         */
        setMultiSelectValue: function (selector, values) {
            var select = $(selector);

            // Remove old labels, if any
            var parent = select.parent();
            parent.find(".ui.label").remove();

            // Add labels for values
            var input = parent.find("input");
            for (var i = 0; i < values.length; i++) {
                var label = '<a class="ui label transition visible" data-value="'
                    + values[i] + '" style="display: inline-block !important;">'
                    + values[i] + '<i class="delete icon"></i></a>';
                input.before(label);
            }

            // Remove old select options, if any
            select.find("option[value][value!='']").remove();

            // Add select options for values
            for (var j = 0; j < values.length; j++) {
                var option = '<option value="' + values[j] + '" class="addition">' + values[j] + '</option>';
                select.append(option);
            }

            // Set select value
            select.val(values);
        }
````

**Comment by ctool-lenggi** [comment]
I have another workaround about this issue.
Everytime you have to set the value(s), redefine the dropdown with all options you already have added and extend the values with the needed items. Atfer the redefine of the object, call 'set selected' with all the selected values.

Maybe this need a little more performance, but you only use the semantic ui API.
Be sure, that the values and names are correct collected, the dropdown object doesn't check the URL on 'set selected'

Example:
```
$('.dropdown').dropdown({
  apiSettings: { ... },
  ...,
  values: [
    {name: 'Test #1', value: '1'},
    {name: 'Test #2', value: '2'}
  ]
});

$('.dropdown').dropdown('set selected',['1','2']);
```
