### ISSUE TITLE
[Dropdown] Menu Should Be Visible in `overflow: auto` Container in Mobile Devices

### ISSUE THREAD

**Issue by codynguyen** [Semantic-Org/Semantic-UI#4495]
Provided a container within a view port that has overflow set on mobile:

```
.viewport {
  overflow-x: auto;
  overflow-y: visible;
}
```

When tapping on the dropdown menu inside that container and the menu shows up, the container height expanded and we need to scroll down the container (not the page, the container is scrollable within the view port) to view the menu content.

This is strange because we can scroll vertically even though `overflow-y` is set to `visible`. Could this be because of the nature of browser's scrollviews?

Ideally the menu should not affect the container's height and should be visible when it goes outside of the viewport.

Here is the test case http://jsfiddle.net/56hwum35/1/ with 3 variants of the viewport for comparison

**Comment by codynguyen** [comment]
Hi guys, is there any plan on this? It's been almost 4 months now since it's first reported.

**Comment by jlukic** [comment]
The only way an absolutely positioned element can "escape" overflow is if its `offsetContext` is outside of the overflow container. 

This means you'll have to set `dropdown` to `static` and create a new `relative` positioned context outside of the overflow.
http://jsfiddle.net/qd6sjutp/

Unfortunately there isnt a way to accommodate this on a framework level.
