### ISSUE TITLE
Column count not working properly

### ISSUE THREAD

**Issue by brianveltman** [Semantic-Org/Semantic-UI#4496]
I have 
@columnCount: 12;

And 2 columns. One 10 wide and the other one 2 wide. It still shows up as 65.2% width and 12.5% width. Leaving a big margin on both sides. This happen after updating to 2.2.4

Yes I have set the @site global to my custom theme which has the @columnCount specified.

**Comment by Banandrew** [comment]
Hi @brianveltman, I’ve just tried it locally, it seems to have been fixed at some point. If it’s still an issue, please let me know.
