### ISSUE TITLE
XSS issue in semantic dropdown.

### ISSUE THREAD

**Issue by akila1996** [Semantic-Org/Semantic-UI#4498]
XSS issue is found in semantic dropdown. You can see the vulnerability in semantic docs page itself http://semantic-ui.com/modules/dropdown.html#/examples . Try it inject a script Eg `<script>alert(10);</script>` under `Tagging and User Additions` section's multiple input box.

**Comment by jlukic** [comment]
`preserveHTML` can be disabled. 
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3517

**Comment by akila1996** [comment]
`preserveHTML` is not working when `allowAdditions` is true.

**Comment by fenilkanjani** [comment]
@jlukic shouldn't the `query` be hmtl escaped [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2668) ?

I think the vulnerability @akila1996 is talking about is (correct me if I am wrong) while using add message property [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L2626).

Just a callback before rendering the `addMessage` would also help.

**Comment by daviian** [comment]
This is a major issue and definitely should be reopend IMHO.

@fenilkanjani Did you solve this for your own?

**Comment by lubber-de** [comment]
We implemented data sanitizing and added a security page to the docs
https://fomantic-ui.com/modules/dropdown.html#/security
