### ISSUE TITLE
Content under icon in header [Chrome]

### ISSUE THREAD

**Issue by ForzaSFerrari** [Semantic-Org/Semantic-UI#4503]
Hi,

I  don't understand where the issue is in the Chrome?

I builded a header like 
```HTML
<h2 class="ui header">
  <i class="settings icon"></i>
  <div class="content">
    Account Settings
  </div>
</h2>
```
but it will always shown like this one.
![header icon content](https://cloud.githubusercontent.com/assets/16107131/18066570/44e1c818-6e39-11e6-89df-8b06aeb6f9d0.PNG)

**Comment by IonutBajescu** [comment]
Looks fine to me.

What version of chrome do you have? 

![image](https://cloud.githubusercontent.com/assets/5365516/18268879/ab0fe81a-741d-11e6-9a51-c3af6406cd42.png)

**Comment by ForzaSFerrari** [comment]
At the moment I use the version 53.0.2785.89. In the past versions of Google Chrome it was from the first moment. Now it comes if I reload the page and it doesn't goes back.

**Comment by domialex** [comment]
Just make sure there's no white space the **<i>** and the **"content"**.

**Comment by Banandrew** [comment]
Hi @ForzaSFerrari,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
