### ISSUE TITLE
[Modal] - Neutral action button does not close modal

### ISSUE THREAD

**Issue by michtill** [Semantic-Org/Semantic-UI#4507]
**Steps to Reproduce**
1. Open MODAL with neutral action button (button without approve or deny class).
2. Click the "neutral" button.

**Expected**
The modal should close.

**Result**
The modal does nothing and stays on screen.

**Testcase**
http://jsfiddle.net/mcuru0b8/

**Comment by IonutBajescu** [comment]
You forgot to save the jsfiddle.

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by j-f1** [comment]
@Banandrew You should make a bot to ask people to post a test case if the “Needs Test Case” label is added, then close the issue with a comment 2 weeks later if the label is still present.
