### ISSUE TITLE
semantic search text box does not work on enter button

### ISSUE THREAD

**Issue by rishi07203** [Semantic-Org/Semantic-UI#4509]
I am using a semantic search text box in my project. After entering some search query the results are fetched but when i press enter key after the results are returned, nothing gets selected. I wanted the first result to get selected similar like dropdown. 

Below is my code snippet which i am using which i am using:

**HTML:**
`<div class="vertically fitted item">
                    <div class="ui search fac" data-content="Test.">
                        <div class="ui icon input">
                            <input class="prompt" type="text" placeholder="sitewide filter...">
                            <i class="search icon"></i>
                        </div>
                        <div class="results"></div>
                    </div>`

**Jquery:**

`$('.ui.search.fac').search({
        apiSettings: {
            url: '/GlobalFacilityFilter/GetFacilities?facility={query}'
        },
        //source: userfaclist,
        searchFields: ['facilityno','facilityname'],
        fields: {
            results: 'results',
            description: 'facilityname',
            title: 'facilityno'
        },
        success: function (results) {
            if (results.data == "Success!") {
                if (results.results == "") {
                    alert("Invalid Search");
                }
            }
        },
        searchFullText: false,
        onResults: function (response) {
            //alert(response.results.length);
            if (response.results.length == 0) {
                $('.ui.search.fac').find('.prompt').val("");
            }
        },
        onSelect: function (result, response) {
            //alert(result.facilityno);
            //$('.ui.search.fac').val(result); 
            var urls = "/TestFilter/SelectedFacility";
            $.ajax({
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                url: urls,
                dataType: "json",
                data: JSON.stringify({ fac: result.facilityno, controller: controllerName }),
                success: function (data) {
                    if (data.data == "Success!") {
                        location.reload(true);
                    }
                },
                error: function () {
                    //alert("My error");
                }
            });
        },
        onResultsOpen: function() {
            $(".ui.search.fac").popup('destroy');
        },
        onResultsClose: function () {
            //var Val = response.facilityno;
            var Value = $('.ui.search.fac').find('.prompt').val();
            //var val = $('.prompt').val();
            if (Value == "") {
                var urlclear = "/TestFilter/ClearSelFac";
                $.ajax({
                    type: 'POST',
                    contentType: "application/json; charset=utf-8",
                    url: urlclear,
                    dataType: "json",
                    data: JSON.stringify({ fac: Value }),
                    success: function (data) {
                        if (data.data == "Success!") {
                            location.reload(true);
                        }
                    },
                    error: function () {
                        //alert("My error");
                    }
                });
            }
            $(".ui.search.fac").popup();
        }
    });`

**Comment by stokescomp** [comment]
Use the command: selectFirstResult
http://semantic-ui.com/modules/search.html#/settings

This will highlight the first result so you can press enter to select it.

**Comment by Banandrew** [comment]
Closing as resolved.
