### ISSUE TITLE
[Dropdown] is opening and closing in loop on IE 11

### ISSUE THREAD

**Issue by lesnikowski** [Semantic-Org/Semantic-UI#4514]
Following code works correctly on FF and Chrome, however in IE11, clicking a button causes the menu to open and close in an infinite loop.

```
<div class="ui dropdown button">
  <div class="menu">
    <div class="ui search input">
            <input type="text" name="search">
    </div>
    <div class="item">Important</div>
    <div class="item">Announcement</div>
    <div class="item">Discussion</div>
  </div>
</div>
```

Here's the reproduction:
https://jsfiddle.net/3q5rn6dh/

**Comment by arbiasgjoshi** [comment]
I'm currently experience the same thing on my project. Is there any help on this regard?

**Comment by Mydoom** [comment]
+1  with IE 11 since Semantic 2.2.6

**Comment by Banandrew** [comment]
See #4237.
