### ISSUE TITLE
Multi SearchSelection selects the first option when clicks out of the selection options

### ISSUE THREAD

**Issue by PedroFagundes** [Semantic-Org/Semantic-UI#4516]
In the Multi SearchSelection, if you click out of the selection options, even if you don't want to select any of the options, it selects the first option automatically, forcing the user to "unmark" the unwanted selected option

**Comment by alexnicolaisen** [comment]
Just to add to this. If you select an item or more, and click outside, the first item you've selected unselects..... I had to downgrade to 2.1.7 again to get rid of this issue!

**Comment by gonssal** [comment]
I just checked and this bug was introduced with the 2.2.3 release.

Very annoying, especially if you have forms with a big number of dropdowns. I think it should be milestoned for the next version.

If you are affected by this, downgrade to 2.2.2.

**Comment by jlukic** [comment]
#4634 
I think im going to change this behavior because its driving everyone crazy.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/commit/5f393f6c33a5365b927eba415bebc6071f871541 Added in `2.1.8`
