### ISSUE TITLE
[Menu] - Down Item

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI#4518]
**Steps to Reproduce**
Look at the CSS for the `down` menu item on the doc site.

**Expected**
Some CSS rule for making the item appear pressed in, as noted

**Result**
There is no CSS for the `.down` class.  The `down` menu item appears exactly like a normal menu item.

**Testcase**

http://semantic-ui.com/collections/menu#down

**Comment by jlukic** [comment]
Bad docs, there is no class for pressed in

**Comment by jlukic** [comment]
Removed from docs
