### ISSUE TITLE
[Divider] - Vertical Divider style error in chrome

### ISSUE THREAD

**Issue by ironxu** [Semantic-Org/Semantic-UI#4520]
**Reproduce**
In google chrome, vertical divider style is error. My chrome version is 52.0.2743.116.
But in Safari the style is good.

This error page is: http://semantic-ui.com/elements/divider.html 

**Expected**
The vertical divider in it`s postion

**Comment by IonutBajescu** [comment]
This is known issue I'm afraid.

I know @jlukic is still trying to find some middle ground with Chromium / W3C. 

Closed as duplicate of #4342.
