### ISSUE TITLE
[DROPDOWN] Multi SearchSelection removes first selected when unfocused

### ISSUE THREAD

**Issue by alexnicolaisen** [Semantic-Org/Semantic-UI#4521]
As the title says, when selecting one or more from a multi searchselection and click outside, the first item you've selected unselects..... I had to downgrade to 2.1.7 again to get rid of this issue!

**Comment by dorsha** [comment]
@alexnicolaisen: This will solve your problem:
https://github.com/Semantic-Org/Semantic-UI/issues/4468#issuecomment-242882039

**Comment by alexnicolaisen** [comment]
@dorsha: Thank you for your answer. It works like a charm!

Really strange to have the forceSelection: false as default, but as long as I can sort it out :)

**Comment by dorsha** [comment]
yeah.. this behavior was changed from unknown reason.
