### ISSUE TITLE
Using different names for FA Icons...

### ISSUE THREAD

**Issue by FreeApophis** [Semantic-Org/Semantic-UI#4525]
This is actually not a bug - but a comment.

Please, do not change the names chosen by Font Awesome without a good reason. I especially have a beef with some of the stranger name choices you arbitrarily changed. I do understand why star half empty is a better name than star-half-o, but these seem not more 'semantic', and are hard to find:

link -> linkify? O'rly? (at least easy to find)
language -> translate. (I had to look through all icons to spot this one...)

The main problem: I do not see a pattern, it looks like it was chosen completley at random which icons gota new name. Changing concepts without a good reason is not semantic.

FA is pretty well known - keep it simple.

**Comment by jlukic** [comment]
I disagree with many of their naming choices

**Comment by FreeApophis** [comment]
Thanks for listening anyway.
