### ISSUE TITLE
Anchor tag inside dropdown menu not working

### ISSUE THREAD

**Issue by jstejada** [Semantic-Org/Semantic-UI#453]
Anchor tag inside dropdown menu is not working, it doesn't link to the href when clicked on.

**Comment by rqbukhari** [comment]
@jstejada make sure you are not inserting anchor tag inside an anchor tag in the dropdown menu.
Like if you are doing the following for dropdown menu
```
<a class="ui dropdown item">Dropdown
  <i class="dropdown icon"></i>
  <div class="menu ui transition hidden">
    <div class="item active">Action</div>
    <a href="#" class="item">Another action</a>
    <a href='#' class="item">Something else here</div>
  </div>
</a>
```
In this case the dropdown will not work because you are inserting an anchor tag inside another anchor tag.
Correct HTML for dropdown with anchor tags is below:
```
<div class="ui dropdown item">Dropdown
  <i class="dropdown icon"></i>
  <div class="menu ui transition hidden">
    <div class="item active">Action</div>
    <a href="#" class="item">Another action</a>
    <a href='#' class="item">Something else here</div>
  </div>
</div>
```

**Comment by ameotoko** [comment]
@rqbukhari Then how do I get the parent item linked? It's a common use case in nav menus.
 I spent hours trying to figure it out, is it not possible with Semantic-UI?

**Comment by i4umahesh** [comment]
<nav>
            <ul>
              <li class="user-profile">
                <a href="javascript:void(0)">
                  <p>Maheswarareddy Abbi..</p>
                </a>
                <div class="portfolio-dropdown">
                  <a href="">Feedback</a>
                  <a href="">Feedback</a>
                  <a href="">Logout</a>
                </div>
              </li>
            </ul>
          </nav>
