### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Isigiel** [Semantic-Org/Semantic-UI#4531]
I'm on latest npm and node, using the git bash on windows 10. I get this every time I try to npm-install semui
http://i.imgur.com/vq75ZNd.png
Hope that helps, I can provide additional info.

_edit_ Additional testing shows, it works fine with powershell
_edit 2_ Although the second question is not preselected to Yes (this is my project folder) and crashes the install if yes isn't actively selected

**Comment by ilanah** [comment]
Also setting up for meteor is not working - giving some errors

**Comment by MarkoCen** [comment]
@Isigiel 
I just successfully installed the latest npm on Windows 7, make sure you run the `cmd.exe` with administrator privileges

**Comment by Isigiel** [comment]
@MarkoCen I was using Git bash. I think that should works as well ...

**Comment by IonutBajescu** [comment]
Closing as a duplicate of #4292.
