### ISSUE TITLE
Search always re-requests data when input box gets focus.

### ISSUE THREAD

**Issue by davewthompson** [Semantic-Org/Semantic-UI#4533]
If the search box has a result from a previous query, on entering the search box the query will be sent to the server again, even though nothing has changed.

**Comment by davewthompson** [comment]
I believe this is only an issue if the cache is disabled for the search results. In our world we can't do this, because the data may have changed.

**Comment by Banandrew** [comment]
Hi @davewthompson, how did you work your way around it?

**Comment by davewthompson** [comment]
I intercepted the requests using the apiSettings's responseSync method: https://semantic-ui.com/introduction/new.html#custom-backends

New in 2.2 | Semantic UI<https://semantic-ui.com/introduction/new.html#custom-backends>
semantic-ui.com
Critical Bug Fixes. 2.2 brings many new bug fixes. For a complete list please check out our release notes. Here is a highlight of some critical bugs



________________________________

**Comment by Banandrew** [comment]
@davewthompson I see, thanks. I think the issue can be closed, please let me know if you think that the use case should still be addressed somehow.
