### ISSUE TITLE
Cannot use inline validation for labeled input with dropdown (or any other field)

### ISSUE THREAD

**Issue by cbxp** [Semantic-Org/Semantic-UI#4538]
Example:

```
    <div class="required field">
      <label>Amount</label>
      <div class="ui right labeled input">
        <input type="number" min="0.01" step="0.01" name="payment.amount">
        <div class="ui label scrollable dropdown" name="payment.currency">...</div>
      </div>
    </div>

    <script>
      $(this.form).form({
        inline: true,
        fields: {
          'payment.amount': ['empty', 'number', 'maxLength[15]'],
          'payment.currency': ['maxLength[3]'],
        },
        onSuccess: this.submitPayment
      });
    </script>
```

The problem is when e.g. amount field is invalid, but currency is valid - the latter instantly removes the validation error prompt inside of top-level field that was added for invalid amount.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
