### ISSUE TITLE
.divided.grid no divider

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#4539]
Hi,

http://jsfiddle.net/efp8z6Ln/361/

If a column takes up all the space for example two columns in one row that are sixteen wide we will not have a divider between the two columns.

Maybe we could have a border top on the second column.

**Comment by Banandrew** [comment]
@shadoWalker89 Hi, can you please elaborate, what’s your use case that you couldn’t use the `.vertically.divided` one and have columns in different rows?

**Comment by shadoWalker89** [comment]
I rest my case
