### ISSUE TITLE
There is no space between columns inside rows

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#4541]
Hi,

http://jsfiddle.net/efp8z6Ln/363/

In the first gird, you can see that there is space between the two columns.
But in the second grid when we put the columns inside a .row the space is gone.

**Comment by meze** [comment]
I may be wrong but the rows of the columns in the first example are implicit. Each column must look as if it had a .row parent. 
See: http://jsfiddle.net/b6v9y335/

**Comment by vinayakkulkarni** [comment]
@shadoWalker89: As per the docs: `Rows are groups of columns which are aligned horizontally.`
Hence, two columns which are vertically aligned don't have the same spacing if they aren't in a row.

you can do something like this: http://jsfiddle.net/vinayakkulkarni/dt7zwkhm/ or what @meze suggested.

If you have any suggestions, queries or problems, just ping in [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or post a thread on [SUI Forums](http://forums.semantic-ui.com)

Closing this now 😉

**Comment by shadoWalker89** [comment]
Thanks guys
