### ISSUE TITLE
HTML Tooltips in non-JS version?

### ISSUE THREAD

**Issue by denchen** [Semantic-Org/Semantic-UI#4542]
According to http://semantic-ui.com/modules/popup.html#tooltip, I can create a JavaScript-less version of Semantic's popup, which works great in my React app. My question is, is there a way to use this with HTML markup (as you can in the JavaScript version)? Or at the very least, is it possible to add line breaks to the tooltip text?

**Comment by YamiOdymel** [comment]
There's no possible way to add line breaks with pure CSS currently.

**Comment by philrykoff** [comment]
It is my understanding that one cannot generate HTML with the `:before` and `:after` pseudo classes, which Tooltip uses (as per doc: `Tooltips use an element's :before and :after psuedo classes.`).

So this will never be technically possible, unless the CSS standard changes or I am wrong. :wink:

**Comment by typeless** [comment]
https://stackoverflow.com/questions/2703601/how-to-line-break-from-css-without-using-br

Some approach is interesting.
Not sure if it's applicable for this circumstance though.
