### ISSUE TITLE
[Menu] Make a Menu containing another Menu stackable

### ISSUE THREAD

**Issue by gujiman** [Semantic-Org/Semantic-UI#4545]
Currently a menu containing another menu does not stack properly.

For example in http://jsfiddle.net/05d2qsgy/2/ you can see that the menu button "help" in the second menu is missing when the menu is stacked.

My solution is to add the following css code:

@media only screen and (max-width: 767px) {
  .ui.stackable.menu .right.menu,
  .ui.stackable.menu .right.item {
    display: block;
  }
}

Now you can see that the menu button "help" in the second menu is stacked properly http://jsfiddle.net/05d2qsgy/1/.

**Comment by Banandrew** [comment]
See #3604.
