### ISSUE TITLE
Multiple Search Selection, select undesired item

### ISSUE THREAD

**Issue by casper1149** [Semantic-Org/Semantic-UI#4546]
Hi,

I have noticed such strange and I assume invalid behaviour.
Using your example here http://semantic-ui.com/modules/dropdown.html under "Multiple Search Selection". If I select some item and then click "tab" or select any other control on the page, one more item is getting selected in the dropdown. If it is an expected behaviour, can you please let me know, how it can be avoided. Thanks!

**Comment by Illyism** [comment]
I have it as well. You can see it in the docs for **Multiple Search Selection**.

1. Click on the input
2. Click on a menu item
3. Click somewhere else

An additional item is selected on 3.

**Comment by casper1149** [comment]
It can be avoided if you do not click on the dropdown and select, but type, search and select by Enter. But anyway it seems to be a bug.

**Comment by shadoWalker89** [comment]
I thinks that the setting `forceSelection` should be false by default

**Comment by vriera** [comment]
I have the same problem and I have created a minimal jsfiddle for the developers to reproduce the problem: https://jsfiddle.net/tzj26adt/

The bug is somewhere between 2.2.2 and 2.2.3.

**Comment by rbrtmrtn** [comment]
+1

**Comment by rdsmartins** [comment]
+1

**Comment by HapLifeMan** [comment]
+1

**Comment by vinayakkulkarni** [comment]
http://semantic-ui.com/modules/dropdown.html#/settings
Set `forceSelection:false` and viola!

**Comment by vinayakkulkarni** [comment]
@jlukic, this can be closed too in my opinion.

**Comment by jlukic** [comment]
Cheers

**Comment by Boasbabs** [comment]
THANKS GUYS. I had the same issues but your comments helped resolved it. I am really in love with Semantic UI. 
From Nigeria.

**Comment by ajarti** [comment]
Hi @jlukic @vinayakkulkarni @Banandrew , just a heads-up .. this problem persists if the dropdown is multiple, forceSelection has no effect (2.2.10)  

Thanks for a killer framework  #Loveit!

**Comment by cluxter** [comment]
@shadoWalker89 Thanks a lot! I spent half an hour trying to figure out where my bug was and boom! Fixed!
