### ISSUE TITLE
[Form Validation] - Multiselect minimum selection rules

### ISSUE THREAD

**Issue by Giwayume** [Semantic-Org/Semantic-UI#4551]
**Steps to Reproduce**
1. Go to[ form validation page](http://semantic-ui.com/behaviors/form.html), first example.
2. Select 1 skill.
3. Submit.

**Expected**
Shoud see error at the bottom "Please select at least two skills".

**Result**
No error =(

**Testcase**
http://semantic-ui.com/behaviors/form.html

**Comment by Banandrew** [comment]
Hi @Giwayume, thanks, it was just a typo, and there’s a PR opened to fix it: Semantic-Org/Semantic-UI-Docs#299
