### ISSUE TITLE
[Dropdown] Search dropdown will automatically select the first item if reopen it again

### ISSUE THREAD

**Issue by enix223** [Semantic-Org/Semantic-UI#4552]
**_Issue_**

Search dropdown will not set the previous value as active value when reopen it and not choosing any value.

**_How to reproduce this issue_**

For example, the [search dropdown example](http://semantic-ui.com/modules/dropdown.html#search-dropdown) in the official website. If we have selected the `Dutch` item in the dropdown list, and then reopen the dropdown list again, without **choosing any value**, the dropdown will set to selected item to the first item, in this case `Arabic`, instead of our previous selected value `Dutch`. 

This will not happen for the dropdown without search function.

**Comment by Panman8201** [comment]
FYI, probably related to #4535 and the [`forceSelection` setting](http://semantic-ui.com/modules/dropdown.html#/settings). It seems like that option causes some odd side effects, try setting it to `false`.

**Comment by enix223** [comment]
Thanks, setting `forceSelection` to `false` works perfectly.

**Comment by almino** [comment]
It is not working for me. I'm using version 2.3.3.
