### ISSUE TITLE
Should Lazy Loading Images work inside Modals?

### ISSUE THREAD

**Issue by jjylha** [Semantic-Org/Semantic-UI#4553]
We can't get the images to lazyload inside modals with visibility (http://semantic-ui.com/behaviors/visibility.html#lazy-loading-images). Images lazyload fine if they are outside of the modal on the normal page but as soon as they are placed inside of a modal and the modal is opened they won't load anymore. Calling $('.elem').visibility('refresh'); on modal open will load the visible images in the modal but not the ones that will enter the screen when scrolling the modal.

So should the lazyloading of images with visibility work fine in the modals also or are we doing something wrong?

**Comment by Banandrew** [comment]
Hi @jjylha, you’re doing nothing wrong, and it makes perfect sense for it to work with modals—we labeled it as enhancement: #5079. It’s been a while, if you haven’t solved it, please take a look at the workaround there. Closing as a duplicate.
