### ISSUE TITLE
'clear' on dropdown erases options

### ISSUE THREAD

**Issue by Special-Dev** [Semantic-Org/Semantic-UI#4558]
selected elements in a multi-optional dropdown, are **completely erased** (being unselected and also disappear from options list) when using '.dropdown('clear')'

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).
