### ISSUE TITLE
Determine currently opened Semantic UI accordion ID

### ISSUE THREAD

**Issue by eXCom** [Semantic-Org/Semantic-UI#4560]
HTML:
`<div class="ui accordion">
	<div id="id_1" class="title">
		<i class="dropdown icon"></i>
		Title text 1
	</div>
	<div id="id_content_1" class="content">
		Content text 1
	</div>
	<div id="id_2" class="title">
		<i class="dropdown icon"></i>
		Title text 2
	</div>
	<div id="id_content_2" class="content">
		Content text 2
	</div>
</div>`

When i'm clicking on Title text 1, i need to get the id of this element, how can i do it ?
I was searching through web any way to do it but found only 1 thing:

JS:
`$('.ui.accordion').accordion({
    onOpening: function () {
        alert(this.index(".content"));
        console.log(this.index(".content"));
    }
});`

this method return me '0' when i'm clicking on first element and '1' when clicking on second .....
please don't recommend me this method because it's not working how i need, i need only ID because i'm going to load content via ajax

thanks for help in advance

**Comment by IonutBajescu** [comment]
You could do `this.find('.title').attr('id')`.

In case you need further help, please ask on the forums.

**Comment by eXCom** [comment]
i tried, it's undefined
