### ISSUE TITLE
Rating With Jquery 3.0

### ISSUE THREAD

**Issue by CardeDeveloper** [Semantic-Org/Semantic-UI#4561]
To use the rating i have to use jquery 2.1.3 you cant use with  3.0 or higher
i leave the example if you try use with jquery 3.1 for example you gonna have an error .
http://codepen.io/cardenas97/pen/YGGpKE

**Comment by avalanche1** [comment]
Not likely.
https://github.com/Semantic-Org/Semantic-UI/issues/1175

**Comment by Banandrew** [comment]
Hi @CardeDeveloper, it seems that it’s been fixed at some point, can you please confirm?

**Comment by CardeDeveloper** [comment]
Yes, just use the last versión of sematic And 3.1 jQuery Was fixed thanks
