### ISSUE TITLE
How to start semantic in my code

### ISSUE THREAD

**Issue by nynellie** [Semantic-Org/Semantic-UI#4563]
Please i need a guide to how to use semantic ui search select dropdown. do i copy the code and paste or what?
i also download the package but dont know what to do with it. Please a step by step approach will be helpful. Thank you.

**Comment by jlukic** [comment]
This is not appropriate for our bug tracker. 

Please use our [official forums](http://forums.semantic-ui.com) for this type of discussion. Please see our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for some guidelines on posting a bug report.
