### ISSUE TITLE
[help] Form Validation: Multiple dependency input / Array input

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI#4566]
How would I validate an array and specify multiple dependency?

For example: if at least on of the inputs has value, make all of them required.

I have a table with 4 inputs on each row. If one of the 4 inputs has a value I need the rest to be required.

My table consists of: Medicine, frequency, # of days, and instructions. So now, it's clear why I need it to be that way. Not only that, it's dynamic also because they can add another row. How do I solve this?

**Comment by Banandrew** [comment]
Hi @xxRockOnxx, it’s been a while, have you figured it out?

**Comment by xxRockOnxx** [comment]
Uhm, since another old issue was bumped again I already forgot it. Right now I use `jquery validator` and just made a custom default `highlight` and `unhighlight` function that makes it compatible with Semantic UI. I'll try to make a gist of it sometime.
