### ISSUE TITLE
[Divider] - Vertical Divider not working anymore

### ISSUE THREAD

**Issue by andreiculda** [Semantic-Org/Semantic-UI#4568]
The vertical devider is not working anymore (not even on http://semantic-ui.com/elements/divider.html)
http://jsfiddle.net/rrxh2prc/1/

**Comment by SwiTool** [comment]
I can confirm this from Google Chrome version 52.0.2743.116m

**Comment by jlukic** [comment]
#4342 

As mentioned there
> I've posted a bug with Chromium. There does not appear to be a workaround from a framework level. Hopefully Chrome team can fix this soon.

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
