### ISSUE TITLE
[Icon] Add primary and secondary colors to icons

### ISSUE THREAD

**Issue by joaobarcia** [Semantic-Org/Semantic-UI#4569]
Hi,

I am unable to apply a primary or secondary color on to an icon. Does this feature not exist? It seems useful and relatively straightforward to implement.

Thanks

**Comment by lubber-de** [comment]
As of [Fomantic-UI](https://fomantic-ui.com/introduction/new.html) 2.7.0 the `primary` and `secondary` values are part of the global color palette.
Thus, you can now use them for icons aswell. 🙂 
See https://jsfiddle.net/rnveb9yt/
