### ISSUE TITLE
[Form Validation] Not showing error prompt when select less values than minCount

### ISSUE THREAD

**Issue by tziporaziegler** [Semantic-Org/Semantic-UI#4570]
I was playing around with the first example on the Form Validation Usage page:
http://semantic-ui.com/behaviors/form.html

As you see in the below picture, the skills section requires at least two options to be selected:

> ![2016-09-20_0936](https://cloud.githubusercontent.com/assets/10053938/18675804/8d4ef2b2-7f21-11e6-845f-dc1adf577db8.png)

When I selected only one option though and pressed submit, I did not see any validation error message:

> ![2016-09-20_0935](https://cloud.githubusercontent.com/assets/10053938/18675820/99dcf1f0-7f21-11e6-8c29-40c3db6178a8.png)

If I don't select any skills, I see the error message "Please select at least two skills", so I am assuming this problem is with the minCount[2].

**Comment by Banandrew** [comment]
Hi @tziporaziegler, can you confirm that it’s not just a documentation error?

**Comment by tziporaziegler** [comment]
@Banandrew I didn't end up using Semantic-UI for the project I was working on, so I've only ever tried this out in the documentation. I just looked at the documentation again though, and this bug does still exist there.

**Comment by Banandrew** [comment]
@tziporaziegler Thanks! I checked, and it’s just a documentation issue, I’ll fix it, not a big deal. Closing as resolved.
