### ISSUE TITLE
dropdown selection on custom button

### ISSUE THREAD

**Issue by andrey-lizunov** [Semantic-Org/Semantic-UI#4571]
I'm not sure what's the best way to apply selection by some custom button?
By default it works on enter (keycode 13). 
I want same behavior on space or any other button.
Thx for any help.

**Comment by jlukic** [comment]
This is not appropriate for our bug tracker. 

Please use our [official forums](http://forums.semantic-ui.com) for this type of discussion. Please see our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for some guidelines on posting a bug report.
