### ISSUE TITLE
[Dropdown][Search] Search should work with groupped options

### ISSUE THREAD

**Issue by andyinaus** [Semantic-Org/Semantic-UI#4572]
Hi

I've been trying to use a search selection dropdown with the following html structure:

``` html
<div class="ui search selection dropdown">
    <input type="hidden" name="selection" value=""/>
    <div class="default text">whatever</div>
    <div class="menu">
        <div class="scrolling menu">
            <div class="header">123</div>
            <div class="item">1</div>
            <div class="item">2</div>
            <div class="item">3</div>
            <div class="header">456</div>
            <div class="item">4</div>
            <div class="item">5</div>
            <div class="item">6</div>
        </div>
    </div>
</div>
```

With this configuration on => {fullTextSearch: true, match: 'text'}

I'm using the header as group title, so I wonder is there a way we can make the dropdown itself recognize that header is for those items and if all the items under the header are filtered the header should also be hidden. e.g. if I search for "4", the items 1, 2, 3, 5 and 6 will be hidden but the header "123" is still visible. 

Is there a solution for this scenario? 

Any suggestion is appreciated

Cheers

**Comment by tkahn** [comment]
I have the same scenario. I will start looking into this on my own and post if I find something that would work.

**Comment by Banandrew** [comment]
This should also include the search component, linking the original issue as a reference: #5336.
