### ISSUE TITLE
Dropdown via Remote content - allows selecting values even from outside of dropdown list.

### ISSUE THREAD

**Issue by happy2deepak** [Semantic-Org/Semantic-UI#4579]
URL [Official Documentation Dropdown Section](http://semantic-ui.com/modules/dropdown.html#/examples)
when clicked on the Favorite Animals Dropdown, it accepts values even if you click outside the dropdown list box.
Have attached a zipped video for demo purpose.
[remote-dropdown_issue.zip](https://github.com/Semantic-Org/Semantic-UI/files/489172/remote-dropdown_issue.zip)

**Comment by brunjick** [comment]
`forceSelection: false`

**Comment by vinayakkulkarni** [comment]
@happy2deepak : in the [documentation](http://semantic-ui.com/modules/dropdown.html#/settings) it's specifically mentioned.

https://github.com/Semantic-Org/Semantic-UI/issues/4972#issuecomment-276961234
