### ISSUE TITLE
Dropdown is not shown, when allowAdditions is true

### ISSUE THREAD

**Issue by HalfLegend** [Semantic-Org/Semantic-UI#4580]
This is my code:
``` HTML
        <div class="ui fluid search dropdown selection multiple">
            <i class="dropdown icon"></i>
            <input class="search" autocomplete="off" tabindex="0">
            <div class="default text">prompt</div>
            <div class="menu transition hidden" tabindex="-1">
                <div....
                             items
                </div>
            </div>
        </div>
```
``` javascript
let jQueryItem = $(this._htmlElement.children[0]);
        jQueryItem.dropdown({
            forceSelection: false,
            allowAdditions: true,
            onShow: () => {return this._onShow(); },
            onAdd: addedKey => this._onAdd(addedKey),
            onRemove: removedKey => this._onRemove(removedKey)
        });
```
If I remove allowAdditions or set it to false, it will work fine.

If I add allowAdditions : true,   the dropdown will not show by clicking it. But if I enter something with keyboard, the dropdown will be fine. It will show, and if I click it after I typed something, it is also fine.

But if I just click it without typing anyting, nothing will happen.

So how can I fix it?

**Comment by HalfLegend** [comment]
I found the reason, but still don't know how to fix it.

Actually, the is no item in the dropdown in the begining. The items are added in the onShow callback, and they may come from remote server or from the cache in the browser or from cookies. So I can not use the ability semantic provided.

There is a check, module.can.show(), before showing the dropdown.
module.can.show is like:
``` javascript
    return !module.is.disabled() && (module.has.items() || module.has.message());
```

When allowAdditions is false, there will be a message:  No results found.
``` HTML
<div class="message">No results found.</div>
```
So module.has.message() will be true, and the dropdown can be shown.

But when allowAdditions is true, there will be no message.
So module.has.message() is false, and the dropdown will not show.

**Comment by jlukic** [comment]
You can add the results using `apiSettings`, which allows for custom request fulfillment with `responseAsync` setting.
