### ISSUE TITLE
[Button + Input] Button and input have different heights

### ISSUE THREAD

**Issue by arggh** [Semantic-Org/Semantic-UI#4585]
http://jsfiddle.net/rxjfnkwj/

I feel like I'm nitpicking, but.. the button element is 1px shorter than the input element. It looks funny when you have an input with a button next to it (quite a common scenario on the internet!)

<img width="1401" alt="semantic-button" src="https://cloud.githubusercontent.com/assets/17210302/18810776/2148b326-82a7-11e6-8638-c2f01c265c9a.png">

**Comment by jlukic** [comment]
#4279 This is roadmapped to be fixed in next patch release
