### ISSUE TITLE
Input type text only displays placeholder text on focus event

### ISSUE THREAD

**Issue by figalex** [Semantic-Org/Semantic-UI#4586]
I just updated to semantic ui version 2.2.4 in order to use some new features but after upgrading semantic-ui all my inputs only show placeholder text on the user clicks on the input (focus).

I'm trying with a simple input:

`<div className="ui icon input">
     <input type="text" placeholder="Search for something"/>
     <i className="search icon"></i>
  </div>
</div>`

**Comment by jlukic** [comment]
`class` not `className`
http://jsfiddle.net/hdrrvb28/
