### ISSUE TITLE
Upgrading from legacy to latest Semantic UI

### ISSUE THREAD

**Issue by vandolphreyes** [Semantic-Org/Semantic-UI#4588]
Where could I find tutorial or documentation for migrating old version of semantic to latest? Currently our site is using http://legacy.semantic-ui.com/ and we want to upgrade to the latest http://semantic-ui.com/.

**Comment by jlukic** [comment]
This is not appropriate for our bug tracker. 

Please use our [official forums](http://forums.semantic-ui.com) for this type of discussion and our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).
