### ISSUE TITLE
Can't initialize dropdown (Safari)

### ISSUE THREAD

**Issue by semeano** [Semantic-Org/Semantic-UI#4590]
This is what I get when I try to initialize a dropdown.

`'$(this.refs.dropdown).dropdown' is undefined`

I'm using semantic:ui Meteor integration, and this error only happens on Safari (at least 9.1.1 and 9.1.2).

Also, this only happens on a production build. Everything is fine on a development build.

**Comment by jlukic** [comment]
This can only be caused by the files not being included or something related to your particular build setup

**Comment by semeano** [comment]
Removing "async" from jquery script tag fixed the issue.
