### ISSUE TITLE
[Test Case] Form Validation does not clear error on type="file" input instantly

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI#4593]
Here's a test case: http://jsbin.com/vavulugaju/edit?html,js,output

The error will be removed after clicking on it again after adding an item. It does not get cleared unlike the others which get cleared on type if a text input, or on select if a dropdown.

**Comment by philrykoff** [comment]
There is no input type=file in the provided bin.

**Comment by Banandrew** [comment]
Hi @xxRockOnxx, I’m also confused, can you please elaborate?

**Comment by xxRockOnxx** [comment]
I'm closing this as even I myself already forgotten about it. It's been months already also.
