### ISSUE TITLE
Dropdown grey if default text = first item text

### ISSUE THREAD

**Issue by guillaumeko** [Semantic-Org/Semantic-UI#4597]
Hi, I think there is a way to do it but I don't know if it's a bug,
I have my dropdown with the code below, If I put the same text in the class .default.text and in the first .item, and In front I select the first item, it's all grey (even if it's selecting the good item on the server. If I put the default text as 'privacy' and the item as 'Public' it's working, but 'Public' and 'Public is not working ... (grey public, else it replace the default and become black'

What I want to do is select public by default, but if the user click on Public, He can .. And then has to display it in black color instead of grey

here is the code to see maybe What I mean:

```
`.ui.selection.dropdown.privacy.compact
    input(type="hidden" name="Privacy")
    I.dropdown.icon
    .default.text Privacy
    .menu
        .item(data-text="Public")
            i.unlock.icon
            span Public
        .item(data-text="Private")
            i.lock.icon
            span Private`
```

So I don't know if it's a bug or just Semantic doesn't accept the same word on default and first data ?

Thanks

**Comment by vinayakkulkarni** [comment]
Hey @guillaumeko, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
