### ISSUE TITLE
dropdown component send empty query to sever

### ISSUE THREAD

**Issue by petitchamp** [Semantic-Org/Semantic-UI#4598]
when I click the dropdown menu , component automatically send 2 query to server while no keyword has been entered 

my server got 2 requests like [28/Sep/2016 02:17:56] **_"GET /client/district//**_ HTTP/1.1" 404 3343

while it is supposed to be **_"GET /client/district/keyword/**_

**Comment by vinayakkulkarni** [comment]
Hey @petitchamp, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

Closing this till you reply :)

Cheers!
