### ISSUE TITLE
Dynamically added dropdown items not showing?

### ISSUE THREAD

**Issue by ArondeParon** [Semantic-Org/Semantic-UI#4600]
I convert my `select` elements to dropdown elements but need the ability to dynamically add  or remove `option` elements from the original `select` element.

I would expect modifications to the parent element to be reflected in the UI representation, but it seems not be the case.

Am I overlooking something?

Example: http://jsfiddle.net/hdwoLcug/1/

**Comment by Banandrew** [comment]
Hi @ArondeParon, closing the issue, as it seems that it was fixed.
