### ISSUE TITLE
"npm install semantic-ui" (the whole kit) cannot be non-interactive, and does not update references

### ISSUE THREAD

**Issue by ehudkaldor** [Semantic-Org/Semantic-UI#4607]
I am trying to install semantic-ui to use with Aurelia-skeleton app, the esnext-webpack version. as they use bootstrap, i need to remove it and install semantic. the project is meant to be a Docker container, and installing packages need to be automated as part of the build.

when i do "npm install semantic-ui --savce-dev", it takes me to the install wizard at the end, and expects answers. i cannot find a way to provide them as part of the command line, and there is no semantic.json to use.
and even if i do install it manually at runtime, it does not seem to update the plugin database (or whatever it is npm applications use to access plugins). so, "import 'semantic-ui';" errors on file not found.

 i have tried it with other npm modules and it works as expected. so, after "npm install aurelia-i18n --save-dev" i can do "import 'aurelia-i18n';" and it works. 

and here is the strange part: if i install a single component ("npm install semantic-ui-popup --save-dev") it does not take me to the wizard but completes quietly, and the import works.

**Comment by AnsonT** [comment]
semantic.json and autoinstall is supposed to save the state of the initial install and can be checked in for subsequent use. However, autoinstall doesn't work properly. This should fix the issue:

https://github.com/Semantic-Org/Semantic-UI/pull/4567

**Comment by saitonakamura** [comment]
Are you using some custom theming?
If not, consider using `semantic-ui-css` package which you can install silently

**Comment by Banandrew** [comment]
Hi @ehudkaldor, have you figured it out?
