### ISSUE TITLE
[Form Validation] Invalid positioning of inline validation error for checkbox

### ISSUE THREAD

**Issue by rseyferth** [Semantic-Org/Semantic-UI#4609]
![image](https://cloud.githubusercontent.com/assets/1991813/18988471/26fb85be-8707-11e6-80a5-f00886008bf1.png)
![image](https://cloud.githubusercontent.com/assets/1991813/18988486/38eac226-8707-11e6-93af-9ae293661f04.png)

As you can see in the screenshots above, the inline error label for the checkbox doesn't point to the left but upwards. Wrapping the checkbox in an `<div class="inline fields">` element does work as a workaround.

**Comment by matdavies** [comment]
I'm also seeing this issue.  The workaround that @rseyferth describes works ok unless on a mobile device, in which case it looks like this:

![inlinevalidationmessageissue](https://cloud.githubusercontent.com/assets/237089/19393924/c82b476c-922e-11e6-8a64-9f8aa96b79b3.jpg)

I think the non inline version should always display below?

**Comment by matdavies** [comment]
Actually, I think I might have been using it wrong.  If I do this:

<pre>
&lt;div class="field">  
  &lt;div class="ui checkbox">  
    &lt;input type="checkbox" id="TermsAndConditions" value="1">  
    &lt;label>I agree to the &lt;a href="">terms and conditions&lt;/a>&lt;/label>  
  &lt;/div>  
&lt;/div>
</pre>

I'm seeing the behaviour as reported by @rseyferth.  However, if I do this:

<pre>
&lt;div class="field ui checkbox">  
    &lt;input type="checkbox" id="TermsAndConditions" value="1">  
    &lt;label>I agree to the &lt;a href="">terms and conditions&lt;/a>&lt;/label>  
&lt;/div>
</pre>

It works as I suggested it should (validation message below, arrow pointing up)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
