### ISSUE TITLE
[search] issue with "showNoResults" property

### ISSUE THREAD

**Issue by lnaravindan** [Semantic-Org/Semantic-UI#4616]
When we have a dropdown configured with "showNoResults" property to "false" and we search with a value which doesn't have any results, no results are displayed. But when we go out of focus of the search box and come back to focus again, the last results div (containing the search results)  is shown.

Please check the jsfiddle,

https://jsfiddle.net/lnaravindan/gyqmew45/1/

**Comment by jlukic** [comment]
I can confirm this is a bug

**Comment by jlukic** [comment]
Fixed in `next` release
