### ISSUE TITLE
[Dropdown] Multiple selection should have an option to allow draggable/rearrangeable labels

### ISSUE THREAD

**Issue by vishakaw1** [Semantic-Org/Semantic-UI#4619]
Hi,
  I'm working on a project that I wanted a Multiselect dropdown control, which allows user to drag and rearrange selected values. your Multiselect dropdown is a possible candidate that I prefer to use if it gives me that option. Please let me know if there are any possible way that I can accomplish my requirement.

Thanks

**Comment by haiboli** [comment]
+1

**Comment by Banandrew** [comment]
Hi @vishakaw1, it doesn’t work this way. Would you like to file it as a feature request?

**Comment by vishakaw1** [comment]
yes please. That will be really worth for my future projects.

Thanks

**Comment by rolox05** [comment]
Hi, what is the state of this improvement?

**Comment by KLeval** [comment]
+1

**Comment by johnmikel** [comment]
bump

**Comment by andriuspetrauskis** [comment]
bump
