### ISSUE TITLE
[Sidebar] sidebar slide doesn't work for RTL

### ISSUE THREAD

**Issue by parsmizban** [Semantic-Org/Semantic-UI#4621]
Hi,

I converted this page to RTL : http://semantic-ui.com/examples/homepage.html
But sidebar slider doesn't work on RTL
Please help me , I should bring a site based on this

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
