### ISSUE TITLE
[Docs] Container Sizes is outdated

### ISSUE THREAD

**Issue by fstanis** [Semantic-Org/Semantic-UI#4623]
The [docs for Container](http://semantic-ui.com/elements/container.html) currently specify container sizes with the following responsive visibility classes:
- `mobile only`
- `tablet only`
- `small monitor only`
- `large monitor only`

However, reading the CSS file, it seems this is quite outdated - the actual responsive visibility classes (at time of writing) appear to be:
- `mobile only`
- `tablet only`
- `computer only`
- `large screen only`
- `widescreen only`

**Comment by slashwhatever** [comment]
Unless I'm missing something, the current CSS has [no responsive visibility classes](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/container.less) at all for container....?

**Comment by jlukic** [comment]
I'll clarify the documentation to make it clear it refers to visibility classes only available in `grid`

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/a35c62040c36b8acccde5793f72062873022e0f6
