### ISSUE TITLE
Semantic UI for latest version of Chrome 

### ISSUE THREAD

**Issue by akshayrpatel** [Semantic-Org/Semantic-UI#4629]
Hello,
Suddenly my app is experiencing front end issues on chrome but works fine on firefox. I did not make any changes to my app (no recent builds) and suddenly chrome is behaving weird - on scrolling some content scrolls up while some content just sticks to its original place. I view my console and get no errors in chrome but on the other side when I load my app on firefox (works fine) and view the console, it gives me 1000's of CSS warnings. I tried to look up those CSS properties and found them in semantic.css file & some in iconicons.css. 
I installed an older version of chrome and my app worked fine on chrome(no errors in console) and firefox(those errors persisted).
Does this have to do with compatibility between chrome and Semantic UI ?

I am using Semantic UI v2.0.0 & Iconicons v2.0.0

-Thanks

**Comment by SrPatinhas** [comment]
It looks like this new version of chrome messed up with several components. im having the same issue with the vertical dividers

**Comment by jlukic** [comment]
Vertical dividers are the only component I am familiar with being broken. 

I've posted a bug with Chromium. There does not appear to be a workaround from a framework level. Hopefully Chrome team can fix this soon.

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401

**Comment by akshayrpatel** [comment]
Any updates on this lately ?

**Comment by Banandrew** [comment]
Hi @akshayrpatel, have you resolved it since then?

**Comment by vinayakkulkarni** [comment]
Hey @akshayrpatel, did you resolve it? SUI is at 2.2.9 and you used 2.0.0 which is history 😛

**Comment by akshayrpatel** [comment]
@Banandrew @vinayakkulkarni the issue resolved on its own, I assume some Chrome update fixed it.
@vinayakkulkarni  hahaha true, the tool I worked on was built long time ago, probably that's why, nothing I can do...🙃
