### ISSUE TITLE
Mobile First?

### ISSUE THREAD

**Issue by dragonfire1119** [Semantic-Org/Semantic-UI#463]
Are you planning on for 1.0 making this awesome framework mobile first like Bootstrap & Foundation. Right now I'm having to use the grid system from foundation and combining it with Semantic UI.

**Comment by dearsina** [comment]
While "Mobile first" may be considered a buzz phrase, it means that the developer doesn't have to fiddle with complex coding, like with switching of menu types between screen sizes. Something I, as a Semantic-UI beginner, am really struggling with, but that was a relative breeze with Bootstrap.

Let me give you an example. I want to have a header-row of menu buttons on the desktop, but a sidebar menu on mobile. I don't want to have two sets of menus that just switch between screen sizes, the menus are complex, and nested. This has proven to be impossible with vanilla Semantic-UI, so yes, "mobile first" may be a buzz phrase, but it does also mean that common problems have been thought thru by the designers.

**Comment by Firegarden** [comment]
I have found the same frustration with Semantic UI. At first I loved S-UI but after fighting with it only to learn you have to create two different menus to get mobile and desktop ui support out of the box I am not thinking of going to foundation.
