### ISSUE TITLE
Using Semantic-UI-LESS effectivelly

### ISSUE THREAD

**Issue by ruifortes** [Semantic-Org/Semantic-UI#4632]
Sorry for posting here but Semantic-UI-LESS doesn't seem to get much attention.
I'm using Semantic-UI-React and Semantic-UI-LESS with webpack.
Including the semantic.less file makes builging take too much time.
Is the any documentation about incrementally including needed modules?
It would be nice not to edit the module directly.

**Comment by Banandrew** [comment]
Hi @ruifortes, have you figured it out?
