### ISSUE TITLE
Incorrect progress percent animation close to 0%

### ISSUE THREAD

**Issue by mrkam** [Semantic-Org/Semantic-UI#4633]
You can observe it even in http://semantic-ui.com/modules/progress.html first example. When progress bar is animated near 0%, it show 9+% values instead of 0+% values. I. e. when it is animated between 0 and 10%, the animated percent text will be changing in range 9 - 15% approx. Slow down the animation to see what's happening.
My analysis shows that percent shown corresponds to the bar width. Because of the min width, it will never get close to 0. Min width should be taken into account for correct animation.

**Comment by mrkam** [comment]
A funny way to see this is to invoke 

progress("set progress", 0) 

in response to user click when progress bar is already at 0%.

For a period of animation, the value will change to 9% and then back to 0% without any other changes to the progress bar appearance.

**Comment by Banandrew** [comment]
Hi, not sure I’m seeing it, please provide a hackable test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by philrykoff** [comment]
Cannot reproduce.
