### ISSUE TITLE
Incorrect select when using <div> in Multiple  Selection dropdown

### ISSUE THREAD

**Issue by fuwei54321** [Semantic-Org/Semantic-UI#4634]
In dropdown page States part, when using the loading function, when i select one option and click the blank place, then two result will be selected

**Comment by jlukic** [comment]
I know I've left what might seem like opposing views on this in different threads. But I'm fairly certain now, even with `forceSelection: true`, this should never happen for multiselect.

I'm going to go ahead and remove this behavior in next.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI/commit/5f393f6c33a5365b927eba415bebc6071f871541 Added in `2.1.8`
