### ISSUE TITLE
Broken build: dropdown not working

### ISSUE THREAD

**Issue by amingilani** [Semantic-Org/Semantic-UI#4639]
Hello

My dropdown isn't working, here's a [jsfiddle testcase](http://jsfiddle.net/gilani/67n6pqb1/1/)

**Comment by amingilani** [comment]
closing this and taking it to Gitter.

**Comment by amingilani** [comment]
Reopening this issue, since there seems to be a broken build. The js file was required through semantic-ui.com/dist/semantic.js and the bower build doesn't seem to be working for me, either.

**Comment by amingilani** [comment]
Maybe consider using travis to run a linter check?

**Comment by amingilani** [comment]
Don't mean to sound like an ass, but I really do think the current build in master is broken, and thus the bower builds.

This is a high priority issue
cc: @jlukic

**Comment by IonutBajescu** [comment]
@amingilani Good spot!

Merging this into #4523.
