### ISSUE TITLE
Collapsed comment 

### ISSUE THREAD

**Issue by ICE2017** [Semantic-Org/Semantic-UI#4641]
i see the Collapsed comment , how can i control collapsed comment hide and show,i did not find any thing in the document and issues,who can help me?

**Comment by Banandrew** [comment]
Hi @ICE2017,

SUI doesn’t offer its own way of doing that, but collapsed comments are hidden with `display:none;`, so you’re free to use anything that manipulates the property.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
