### ISSUE TITLE
Dropdown multiple selection

### ISSUE THREAD

**Issue by nestorvanz** [Semantic-Org/Semantic-UI#4645]
When you choose an item from dropdown and then you click out of the element, the dropdown auto select another item. You can check this on your own page http://semantic-ui.com/modules/dropdown.html#/usage.

**Comment by pangzhenzhou** [comment]
+1  
how to fix ?

**Comment by jbenezech** [comment]
+1

**Comment by jbenezech** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/4468

    dropdown({
       'forceSelection': false
    });

**Comment by nestorvanz** [comment]
I tried with this configuration:

dropdown({
   'forceSelection': false
});

and everything works well.

Thank you @jbenezech
