### ISSUE TITLE
Popup event binder not work with AJAX manipulated items.

### ISSUE THREAD

**Issue by kaanoo2904** [Semantic-Org/Semantic-UI#4652]
As now, binding popup listener in Semantic is:

```
$('.popupable')
  .popup()
;
```

This way, new DOM objects manipulated by AJAX won't get the binding. I tried something like this but it didn't work:

```
$('body').on('popup', '.popupable', {
        hoverable: true,
        inline: true,
        observeChanges: true,
        position: 'bottom center'
    });
```

**Comment by Banandrew** [comment]
Hi @kaanoo2904,

That’s just how it is, you’ll have to refresh selectors every time you show the remote data. Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
