### ISSUE TITLE
Data-tooltip is not binding the value in angular2 or angularjs

### ISSUE THREAD

**Issue by rameshyala** [Semantic-Org/Semantic-UI#4655]
Hi, i am giving like this in my html page

HTML Page:

<a class="header" data-tooltip="{{billDetailsHelpText}}" (click)="viewDetails()" (keyup.enter)="viewDetails()" >
    {{a.details}}
</a>

Component:
private billDetailsHelpText: String = 'Bill details';

It shows error:
 Unhandled Promise rejection: Template parse errors:
Can't bind to 'tooltip' since it isn't a known property of 'a'.

**Comment by Banandrew** [comment]
Hi @rameshyala,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
