### ISSUE TITLE
Vue.js2 and semantic UI Sidebar conflict

### ISSUE THREAD

**Issue by mehranrasulian** [Semantic-Org/Semantic-UI#4658]
As you may know, already we must mount Vue.js 2 to a normal element, not body. so if I have something like this, semantic-ui gives me `pusher` and `movedSidebar` console errors.

``` php
<!DOCTYPE html>
<html>
<head>
   //
</head>
<body>
    <div id="app">
        <div class="ui sidebar inverted vertical menu">
            <a class="item">
                1
            </a>
            ...
        </div>
        <div class="pusher">
            <!-- Site content !-->
        </div>
    </div>
</body>
</html>
```

and when I remove the `#app` element and mount Vue.js to the `body`, then it gives me this console error:
`[Vue warn]: Do not mount Vue to <html> or <body> - mount to normal elements instead.`

**Comment by zephraph** [comment]
I would think having a configuration option for where to mount semantic-ui would be a viable solution.

**Comment by IonutBajescu** [comment]
@zephraph that should actually be already implemented.

@mehranrasulian Does setting the `context` sidebar setting to `#app` fix your problem? 

You can find a few more available settings here http://semantic-ui.com/modules/sidebar.html#/settings.

**Comment by mehranrasulian** [comment]
@IonutBajescu Sorry for the delay!
Here is an example for when I have wrapped the #app around `semantic sidebar`: http://jsbin.com/toremi/edit?html,js,output

**Comment by IonutBajescu** [comment]
@mehranrasulian I see, yeah so as I said you need to set the context to `#app`.

https://jsfiddle.net/jdzbzjtp/3/

**Comment by mehranrasulian** [comment]
@IonutBajescu Many Thanks to you! It solved my problem!
