### ISSUE TITLE
[Enhancement] Inverted Theme

### ISSUE THREAD

**Issue by BananaPoop** [Semantic-Org/Semantic-UI#4659]
Currently, many components do have the inverted class which is very useful. However since my entire app is going to back dark, it seems wrong to just tag components as inverted since it takes up space, and I'm not sure if every component has an inverted, I have changed my sites variables and recompiled to make the site dark, however now that makes it impossible to have light sections.

Suggestion: could someone (Who is better at selecting colours than I am) make a semantic UI dark theme, which is the same except obviously darker, and with all the other colours changed to contrast well. Additionally in the dark theme 'inverted' should actually make things appear bright, whilst it's not problem for me to change the colours myself and have badly selected colours I think if someone is up to it, lots of people (myself included) would appreciate a well made dark theme.

That is assuming inverting everything is not the way to go.

**Comment by CrushedPixel** [comment]
I'd really like to see this as well, as I can't think of a pretty and simple way to dynamically add the `inverted` class to all `ui` elements when toggling night mode in my app.

**Comment by 1-14x0r** [comment]
we are currently working on a theme editor to allow you to style themes like old skool dreamweaver from adobe. however in the mean time check out this theme http://semantic-ui-forest.com/themes/bootswatch/darkly/ or http://semantic-ui-forest.com/themes/bootswatch/cyborg/

you can also import different themes on different views if you wish to use multiple themes. 

but yes you are correct about the inverted. you do not want to use inverted as a way to hack in a dark theme. I mean you can do it, but it gets messy fast, and like you said not all components support this.

GLHF;
