### ISSUE TITLE
[Label] Mini label class always floated right 

### ISSUE THREAD

**Issue by kjngstars** [Semantic-Org/Semantic-UI#4660]
The following snippet goes wrong:

![error](https://cloud.githubusercontent.com/assets/11659446/19446472/1dd484ee-94c3-11e6-8698-cb0889a4ef83.PNG)

This is the result:
![error1](https://cloud.githubusercontent.com/assets/11659446/19446494/38d3fe46-94c3-11e6-8c7a-b2c4718380a2.PNG)

But when i change to class="ui **tiny** label" then it works like what i want (it also works with any size classes except **mini**):
![error3](https://cloud.githubusercontent.com/assets/11659446/19446583/a999156c-94c3-11e6-9e81-d356854aa2d9.PNG)

Pls help me fix this, thank u guys so much.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
