### ISSUE TITLE
[Dropdown] Arrow icon does nothing when you are using "remote content" for the dropdown

### ISSUE THREAD

**Issue by sergez** [Semantic-Org/Semantic-UI#4661]
Steps to reproduce:
1/ Go to this page http://semantic-ui.com/modules/dropdown.html#remote-content
2/ Click arrow down icon in "Favorite Animal" field/control

Actual result:
Nothing happens. Dropdown isn't opened.

Expected result:
Dropdown should opens with the values in it.

BTW: If you are using simple dropdown (without remote content) it behaves as expected.

**Comment by jlukic** [comment]
This has been corrected in a previous version. You can confirm correct behavior at above link.
