### ISSUE TITLE
[Modal] - Whenever i set context option as my custom element, dialog appears vertically on top only.  There is no provision to fix dialog vertically centre.

### ISSUE THREAD

**Issue by Balu-S** [Semantic-Org/Semantic-UI#4665]
**Steps to Reproduce**
1. Do set some custom element ID as a context of the modal.

**Expected**
The Modal should position in the center of the body.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
