### ISSUE TITLE
How to FIX Semantic on Vue 2 SSR

### ISSUE THREAD

**Issue by afrianjunior** [Semantic-Org/Semantic-UI#4667]
if you import with

``` javascript
  import jquery from 'jquery'
  import semantic from '../semantic/dist/semantic.js'
```

  the result is `jQuery not defined`

but you can use this

``` javascript
  const inBrowser = typeof window !== 'undefined'
  if (inBrowser) {
    const jquery = require('jquery')
    const semantic = require('../semantic/dist/semantic.js')
  }
```

**Comment by mehranrasulian** [comment]
It works for me:

```javascript
window.$ = window.jQuery = require('jquery');

import '../semantic/dist/semantic.js';
```

**Comment by hasusuf** [comment]
This also works for me:

` javascript
window.$ = window.jQuery = require('jquery')
window.semantic = require('semantic-ui')
`

**Comment by vinayakkulkarni** [comment]
@afrianjunior seems the issue has been solved.

Closing the issue for now, if you still have the same problem, ping us on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI)
