### ISSUE TITLE
[Label] - Floating labels don't work in table headers

### ISSUE THREAD

**Issue by mrkam** [Semantic-Org/Semantic-UI#4670]
**Steps to Reproduce**
1. See the jsfiddle

**Expected**
The Label should be floating above the column headers

**Result**
The Label does not do this, they hide somewhere far right.

**Testcase**
http://jsfiddle.net/rduvhn8u/141/

**Comment by IonutBajescu** [comment]
Floating labels must be placed only inside elements with "position:relative".

http://jsfiddle.net/c1rztvyL/1/

**Comment by mrkam** [comment]
I've figured it out myself. But it seems to be missing in the docs.

**Comment by IonutBajescu** [comment]
That's right, it probably needs a message similar to the one for the corner labels.

>A corner label must be positioned inside a container with position: relative to display properly. If a container is rounded you will need to add overflow:hidden to the container to produce a rounded label.
