### ISSUE TITLE
Classes Documentation

### ISSUE THREAD

**Issue by vkbamania** [Semantic-Org/Semantic-UI#4672]
There is a need for classes documentation as the beginners are not able to figure out uses of various particular classes. There should be something like a cheatsheet for beginners where you give definitions and descriptions of all the classes used in semantic ui alphabetically.

**Comment by vinayakkulkarni** [comment]
There's one : [Kitchen Sink](http://semantic-ui.com/kitchen-sink.html)

For anything else, you can ping on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or use the [forums](http://forums.semantic-ui.com/)
