### ISSUE TITLE
Table sort removes objects bindings

### ISSUE THREAD

**Issue by Chris4Tune** [Semantic-Org/Semantic-UI#4677]
I have a table with dropdowns and other such bindings. The table sort function removed the bindings once the columns are order.

I fixed this issue by replacing the the following code:

```
  rows.each(function (i, tr) {
            fragment.append(tr);
        });
```

with the following code:

```
rows.each(function (i, tr) {
            var objectWithEvents = $(tr).detach()
            table.append(objectWithEvents);
        });
```

This also made the fragment variable redundant

**Comment by Banandrew** [comment]
Hi @Chris4Tune, the table sorting is not a part of the framework yet, so I’ll be closing the issue and rerouting it to the initial request: #500.
