### ISSUE TITLE
[Visibility] lazy load images on click (instead of on display)

### ISSUE THREAD

**Issue by siddo420** [Semantic-Org/Semantic-UI#4679]
It may already be implemented (in which docs should be updated at http://semantic-ui.com/behaviors/visibility.html#lazy-loading-images).

So, is it possible to lazy load (ie. copy data-src to src) when item is clicked?
The use-case is to show a slimmed down version of an image first and when clicked actually show the good quality version.

**Comment by Banandrew** [comment]
Hi @siddo420,

That’s not possible; lazy loading only gets triggered when a content appears in the viewport. Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
