### ISSUE TITLE
Example for left navigation used in UI Docs?

### ISSUE THREAD

**Issue by reft** [Semantic-Org/Semantic-UI#4681]
Hi,

Do you have any example in the docs for implementing the fixed left navigation used in the UI Docs?

[http://semantic-ui.com/modules/sidebar.html#/examples](Nav)

It's the same layout as the sidebar, but it's **always shown** and the content to the right of the navigation is not **pushed outside of the screen**, (otherwise i would have used the sidebar).

Thanks

**Comment by reft** [comment]
I can use the menu component found [http://jsfiddle.net/rkkmLtzn/](here), however the UI Docs navigation uses fixed container and scrolling down or up sets the **top** styling with js, (eg  top: -1100px; if you're at the bottom of the nav), and I cant seem to find the source of this. How did you implement this?

**Comment by ankitrg** [comment]
I am using a `left fixed vertical menu`, but other content to its right just gets pushed behind the menu item. So do we have a sample which @reft  asks for?

**Comment by Banandrew** [comment]
Hi @reft, have you figured it out?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
