### ISSUE TITLE
Semantic UI Dropdown not getting binded with AngularJS Model 

### ISSUE THREAD

**Issue by miteshmanani** [Semantic-Org/Semantic-UI#4682]
I am using the Semantic UI as Follows :- 
`<select required class="ui dropdown" ng-model="product.manufacturer.manufacturerId" ng-options="manufacturer.manufacturerId as manufacturer.manufacturerName for manufacturer in manufacturers" id="selectmanufacturer"></select>`

Initialising it in a Controller :- 

`$rootScope.$on('$viewContentLoaded',function(){
        $('#selectmanufacturer').dropdown();
    });
`

The Generated DOM for the same is as below :- 
`<div class="ui dropdown ng-pristine ng-untouched ng-valid selection" tabindex="0"><select required="" ng-model="product.manufacturer.manufacturerId" ng-options="manufacturer.manufacturerId as manufacturer.manufacturerName for manufacturer in manufacturers" id="selectmanufacturer" class="ng-valid ng-valid-required"><option label="Dell" value="number:1">Dell</option><option label="Lenovo" value="number:2" selected="selected">Lenovo</option><option label="Micromax" value="number:3">Micromax</option><option label="Sony" value="number:4">Sony</option></select><i class="dropdown icon"></i><div class="text"></div><div class="menu" tabindex="-1"><div class="item" data-value="number:1">Dell</div><div class="item" data-value="number:2">Lenovo</div><div class="item" data-value="number:3">Micromax</div><div class="item" data-value="number:4">Sony</div></div></div>`

Yet the "Selected" Value is not selected by the semantic UI.  This seems to be a issue since the DIV Menu tags dont seem to mark the selected value.

**Comment by matheusan** [comment]
@miteshmanani I have the same problem. And was using the ng-options approach as you are, that wasn't working. When the Semantic UI Dropdown kicks in, Angular still didn't finish rendering the select options. So I change it to <option ng-repeat.....> and it works fine. 
But it doesn't bind with the model. It changes the value in the input field that it creates, but Angular doesn't accept the value. 

Does anyone have the same problem?

**Comment by matheusan** [comment]
@miteshmanani I've found a solution. Works like a charm!

https://github.com/Semantic-Org/Semantic-UI/issues/1913

Credits go to @mbeckenbach on this one.

Cheers
