### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by Mrigank11** [Semantic-Org/Semantic-UI#4683]
I am unable to install semantic-ui on heroku.
I am getting this error:  
[log.txt](https://github.com/Semantic-Org/Semantic-UI/files/546340/log.txt)
I think this due to user interaction requirement during installation.
I have excluded `/semantic` from github project because that's quite huge, please tell me if it is causing the issue.
Please help me in fixing this problem ASAP.

**Comment by IonutBajescu** [comment]
Can you share your `semantic.json` file with us?

**Comment by Mrigank11** [comment]
Here it is,

[semantic.json](https://github.com/Semantic-Org/Semantic-UI/files/569024/semantic.json.txt)

**Comment by IonutBajescu** [comment]
Please set the `autoInstall` option to true in your semantic.json file.

**Comment by Mrigank11** [comment]
Oh, thanks a lot, it worked!!

**Comment by Mrigank11** [comment]
Wait that problem was solved but now I can't use files generated by semantic-ui, I mean heroku is deleting generated files(i.e. `libs/semantic` in my case).

I tried adding:

 `"cacheDirectories": [
    "node_modules",
    "libs/semantic"
  ]`

to my package.json it says: 

` Saving 2 cacheDirectories (package.json):
       - node_modules
       - libs/semantic (nothing to cache)
`

Do I need to upload the complete `libs/semantic` folder ?

**Comment by IonutBajescu** [comment]
@Mrigank11 you're supposed to check out the semantic folder in the git repo. (except for the dist directory, of course)
