### ISSUE TITLE
[Dropdown] Selection Search gets value of first item in collection on focus

### ISSUE THREAD

**Issue by theMK2k** [Semantic-Org/Semantic-UI#4684]
Hi there,

a search selection dropdown loses it's previous value after being focussed a subsequent time (the selection opens up) and leaving it (by either pressing ESC or clicking outside the selection).

This behaviour can be seen in the demo section:

**via mouse:**
1. click to focus (selection pops up)
2. selecting a value ("America Samoa")
3. click to focus (selection pops up, "America Samoa" is highlighted)
4. leave / click outside (first item "Afghanistan" is now the selected item <- BUG?)

![semantic-ui_search_selection01](https://cloud.githubusercontent.com/assets/16878526/19645300/596502c8-99f4-11e6-9e4f-404bdd39c2d3.gif)

**via keyboard:**
1. Shift+Tab to focus
2. Cursor Down + Enter for selection ("America Samoa")
3. Tab to leave
4. Shift+Tab to focus (selection pops up, "America Samoa" is highlighted)
5. ESC to quit selection
6. Tab to leave (first item "Afghanistan" is now the selected item <- BUG?)
![semantic-ui_search_selection02](https://cloud.githubusercontent.com/assets/16878526/19645316/637529aa-99f4-11e6-8fcf-eb29de6126ff.gif)

**Comment by juice** [comment]
#4506

**Comment by mrkam** [comment]
#4806
