### ISSUE TITLE
[Usage]OnLabelCreate

### ISSUE THREAD

**Issue by kkotwal94** [Semantic-Org/Semantic-UI#4686]
I am currently creating a dropdown list that has items that may look like this

```HTML
<div class="item active selected" data-value="Billable Projects-4" color="purple" workitemid="10000" categoryid="4">
    <div></div>
    <span class="ui purple label" color="purple" workitemid="10000" categoryid="4" data-value="Billable Projects-4" style="font-size: 11px;">Billable Projects</span>
    <a>Open Sub Categories</a>
</div>
```

When the Label is created I don't want it to be displayed the same way, i'd like to not have the <a> tag in there, so I figured I'd use OnLabelCreate, but doing it like this : 

```JS
 onLabelCreate: function (value, text) {
                console.log($(this));
                console.log("Created");
                var child = $(this).find('.label');
                console.log(child);
                var color = child.attr('color');
                $(this).css('background-color', color);
                return $(this);
            },
```

nothing is really fired or said, however onChange works just fine, and so does .dropdown('set selected'), am I missing something?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
