### ISSUE TITLE
[Dropdown] Add option to hide 'No results found' message.

### ISSUE THREAD

**Issue by tabeth** [Semantic-Org/Semantic-UI#4690]
The title pretty much explains it all.

**Comment by lperiodbose** [comment]
There is already the opportunity to customize the behavior...

```
$(".dropdown").dropdown(
  onNoResults: function(search) {}
);
```

If you even use the option with no function inside it prevents the default behavior. I realize that's not as sexy as being able to type "false" and requires 14 more characters, but it does start with "f" at least...

**Comment by tabeth** [comment]
I'm aware of that solution, but I think including empty functions for this kind of thing is an anti-pattern. Ideally the dropdown component would have a `showNoResults` setting, similar to the search component.

**Comment by mann579** [comment]
Is there an option in new version to hide the new results?

**Comment by mann579** [comment]
I find some solution but that was more like a hack with the help of CSS and JS. So prefer if library will provide this option. I think it is some of the basic needs. right @tabeth ?

**Comment by prudho** [comment]
```js
$.fn.dropdown.settings.message.noResults = '';
```

That should to the trick. If you want a more active community, as well as an updated framework with ton of bugfixes and new features, please take a look at Semantic-UI fork: [Fomantic UI](https://github.com/fomantic/Fomantic-UI).

**Comment by aditya-5** [comment]
The noResultsMessage="YOUR_TEXT_HERE" attribute can be used to modify the behaviour.

**Comment by amberyufangchiu** [comment]
> The noResultsMessage="YOUR_TEXT_HERE" attribute can be used to modify the behaviour.

this works perfectly! thank you!
