### ISSUE TITLE
[Dropdown] - Programmatically setting multiselect dd value triggers multiple onChanged callbacks

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#4691]
https://jsfiddle.net/avalanche1/ubqhfsff/
As you can see, in the console when multiple values are set programmatically on a dropdown - onChanged callback triggers the amount of times equal to number of values in array being set.
This may be right when mimicking user behavior - he selects values one after another; but when I need to programmatically set many values all at once this is incorrect.

**Comment by Banandrew** [comment]
Redirecting it to #4913.
