### ISSUE TITLE
Search drop-down keeps re-opening when selecting option on mobile device

### ISSUE THREAD

**Issue by malishew** [Semantic-Org/Semantic-UI#4693]
Hi,

It seems there is issue with _search selection dropdown_ where after typing part of search condition and selecting one of possible items the search menu will reappear and resets selection on mobile device.

Just to note, this does not happen on desktop device when either scrolling + clicking on item or going through options using up/down arrows and pressing enter key.

**How to replicate:**
Can be replicated on Semantic UI example page:
http://semantic-ui.com/modules/dropdown.html

Under section:
_Search Selection
A selection dropdown can allow a user to search through a large list of choices._

* While on mobile device go to previously mentioned section
* Type in search condition such as "Bur"
* Click on item "Burma"
* Dropdown reappears and clicking outside re-selects first item from menu.

See example here:
[http://www.tiikoni.com/tis/view/?id=3545d96](url)
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12526109/19786730/4f1603c6-9c97-11e6-84cc-fdf4cfded297.gif)

Tested on:
- Device: Samsung Galaxy S7 Edge
- OS: Android 6.0.1
App: 'Internet' Version 4.0.20-77, https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_GB
App: 'Chrome' Version 54.0.2840.68

**Comment by juice** [comment]
#4506

**Comment by malishew** [comment]
@juice 
Thanks, I've looked at the thread before and somehow only noticed 'forceSelection: false' for specific component. Initialising drop-down with:
$('#ID').dropdown({
    apiSettings: {
        url: URL
    },
    forceSelection: false
});
didn't do the trick.

However setting:
**$.fn.dropdown.settings.selectOnKeydown = false;
$.fn.dropdown.settings.forceSelection = false;**
does the charm.

Much appreciated!
