### ISSUE TITLE
Issue of gulp css min

### ISSUE THREAD

**Issue by HadesD** [Semantic-Org/Semantic-UI#4694]
I 've find this issue that:
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L21241
the value is background none
but when min css, it came to background: 0 0;
this issue make some things not display correct on ios device.
pls fix its

**Comment by IonutBajescu** [comment]
Good spot, @HadesD!

We can't fix this ourselves though, the minification is done through [clean-css](https://github.com/jakubpawlowicz/clean-css), which is out of our control.

Any chance you raise the issue there, alongside with details of which versions of iOS are affected?
