### ISSUE TITLE
Slow table sort, 400 <tr/> take 2.5sec

### ISSUE THREAD

**Issue by yamsellem** [Semantic-Org/Semantic-UI#4695]
The table sort, http://semantic-ui.com/javascript/library/tablesort.js, outside of semantic is a great tool.

But, for 400 elements, it takes 2.5sec to sort an array.
Can this be optimized?
Can this be added to semantic js core libraries?

Thanks for the great work anyway.

**Comment by Banandrew** [comment]
Hi @yamsellem, I can’t answer the first question, and it’s not a part of the core yet, but maybe you’ll be able to hack something up using [the library’s documentation](https://github.com/kylefox/jquery-tablesort). As for the second question, it’s a known request (#500), and I’ll be closing this issue as a duplicate.
