### ISSUE TITLE
flags croatia

### ISSUE THREAD

**Issue by idraganj** [Semantic-Org/Semantic-UI#4696]
In UI Docs, under "Flags", instead of Croatia you have Serbia and Serbian flag.

**Comment by jlukic** [comment]
Thanks for the find

**Comment by jlukic** [comment]
The flags for Serbia and Croatia appear to match wikipedia's flags.

**Comment by idraganj** [comment]
Countries are listed in alphabetical order. You have Costa Rica then Serbia(it should be Croatia) then Cuba..

http://semantic-ui.com/elements/flag.html
