### ISSUE TITLE
Question: Popups in a dropdown

### ISSUE THREAD

**Issue by Thomas12** [Semantic-Org/Semantic-UI#4697]
Trying to have a popup (data-tooltip / data-position) in a dropdown menu item does show the popup, but this popup is stucked within the borders of the dropdown menu, only see that scroll-bars come up. How can I liberate the popup to be shown on the (e.g.) right side (outside, not inside) of a dropdown menu item?

Thank you!

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Thomas12** [comment]
It turned out that the popup is only stuck in the parent div if you statically set the popup. 
If you assign it dynamically via $('.xxx').popup(...) then it works correctly.
