### ISSUE TITLE
Question: Nest Shape

### ISSUE THREAD

**Issue by Walk4Muscle** [Semantic-Org/Semantic-UI#4699]
I have a custom UI component implementing with 2 level nested shape. But when I shift the side in root node using `shape('flip left')`, it seems that the shape in the leaf node will be effected too, i.e. the the shape component in leaf node shift the side too.

How to prevent the shape in leaf node be effected? Is there any example about nested shapes?

**Comment by Banandrew** [comment]
Hi @Walk4Muscle, shape will animate all children with `.active` class, and it’s a known issue; you didn’t post an example, but I think that’s what happens in your case as well—see #4704.

**Comment by lubber-de** [comment]
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/464
See http://jsfiddle.net/mpkjave0/
