### ISSUE TITLE
[Flag] Add missing United Kingdom flags

### ISSUE THREAD

**Issue by Morrolan** [Semantic-Org/Semantic-UI#4703]
Flags are present for the United Kingdom, as well as 2 of it's 4 constituent countries, i.e. Scotland and Wales.  

Please add flags for the 2 remaining countries, England and Northern Ireland.

https://en.wikipedia.org/wiki/Flag_of_England
https://en.wikipedia.org/wiki/Flag_of_Northern_Ireland

**Comment by ilyauts** [comment]
English flag is there. 1st column, 9th flag from the bottom in Semantic-UI/dist/themes/default/assets/images/flags.png just doesn't appear in the documentation

**Comment by Morrolan** [comment]
The image may be there but there is no way to specify it - using <i class="gb en flag"> gives you the flag of the United Kingdom, and 'england' and 'english' don't return any images.

**Comment by zyzniewski** [comment]
England Flag: https://github.com/Semantic-Org/Semantic-UI/pull/5944
