### ISSUE TITLE
Link images don't get centered

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#4708]
```html
 <div class="ui vertical segment">
     <p>
          blablablabla
     </p>
         <img class="ui small centered image" alt='Disponible en Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/es_badge_web_generic.png'/>
         <a class="ui small centered image" href=''>
                 <img alt='Disponible en Google Play' src='https://play.google.com/intl/en_us/badges/images/generi/es_badge_web_generic.png'/>
         </a>
 </div>

```
First image gets centered, second one (the <a>) doesn't.

EDIT: Added Jsfiddle https://jsfiddle.net/n8u8he15/

**Comment by saitonakamura** [comment]
Can you create a jsfiddle illustrating the problem?

**Comment by mihokovic** [comment]
It's pretty obvious that in first image you assigned classes to `img`, while in second you didn't, but you assigned the same classes to `a`. That is probably causing the issue.

**Comment by saitonakamura** [comment]
`<a>` and `<img>` tags has `display: inline` by default
But semantic overrides this for an image to `block`, to make `margin: 0 auto` work
```
img.ui.image {
    display: block;
}
```
So as a workaround I suggest hack the css or inline style to `display: block`
[https://jsfiddle.net/0ch9yxs1/](https://jsfiddle.net/0ch9yxs1/)

**Comment by xDaizu** [comment]
@saitonakamura thanks, now I put it up for debate if either include this fix (we should check for other undesired interactions) or, as I expressed above, including a note about it in the documentation. 

I think one of those should be executed.

**Comment by lubber-de** [comment]
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1618
See your adjusted jsfiddle here https://jsfiddle.net/spq9kLd3/
