### ISSUE TITLE
search dropdown makes first item autoselected - how to avoid?

### ISSUE THREAD

**Issue by Thomas12** [Semantic-Org/Semantic-UI#4709]
class="ui search dropdown"

The "search" makes the first menu item auto-selected when opening the dropdown.
Can this be avoided? Because when you just look at the menu without selecting an item, the first item is selected though.

**Comment by saitonakamura** [comment]
Read the [docs ](http://semantic-ui.com/modules/dropdown.html#frequently-used-settings) more carefully, there is an option `forceSelection`, which is `true` by default and you should set it to `false` to achieve the desired behavior

**Comment by Thomas12** [comment]
Thank you very much, indeed haven't seen that option!
