### ISSUE TITLE
What does semantic ui has compare to twitter bootstrap?

### ISSUE THREAD

**Issue by topstarnetwork** [Semantic-Org/Semantic-UI#4710]
What does semantic ui has compare to twitter bootstrap? And why should I use it?
What are the pros and cons, thanks.

**Comment by UbaDeveloper** [comment]
Google is your friend

[https://www.upwork.com/hiring/development/twitter-bootstrap-vs-semantic-ui/](https://www.upwork.com/hiring/development/twitter-bootstrap-vs-semantic-ui/)
