### ISSUE TITLE
Popup inside a popup

### ISSUE THREAD

**Issue by Northgates-Systems** [Semantic-Org/Semantic-UI#4712]
I am trying to open a popup inside an existing popup but cannot seam to make it work properly.
Popups are generated on the fly.

Clicking on the owner popup to close the child popup does not close it, the child popup gets attached to the hover of the owner popup instead of closing.

Would anyone have an idea how to proceed?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by vinayakkulkarni** [comment]
Closing this till @Northgates-Systems replies.
