### ISSUE TITLE
Ribbons on cards

### ISSUE THREAD

**Issue by slashwhatever** [Semantic-Org/Semantic-UI#4713]
Card markup:
```
    <div class="ui card">
      <div class="content">
        <a class="ui right blue ribbon label">popular</a>
        <div class="ui bordered rounded centered image">
          <a href="/path/to/link">
            <svg width="100" height="100">
              <image href="image.jpg" x="0" y="0" width="100%" height="100%"></image>
            </svg>
          </a>
        </div>
      </div>
        <div class="content">
          <a href="/path/to/link">
            <div class="header">This OR That</div>
            <div class="meta">Quizzes</div>
          </a>
        </div>
    </div>
```

Screenshot: https://puu.sh/s798E/ed9bd79172.png

Looks like ribbons don't play nice with cards very well. Note this ribbon is declared to be right aligned as well as being slightly out of position. Is there a better place in the markup to declare the ribbon or is a CSS tweak necessary?

**Comment by saitonakamura** [comment]
can you create a jsfiddle illustrating the problem?

**Comment by slashwhatever** [comment]
Sorry, yes of course. Ill work one up asap (and probably find in the process it's some CSS clash of my own creation 😂)

**Comment by slashwhatever** [comment]
You. Closing. My own dumb CSS clashes causing the problem.
