### ISSUE TITLE
[Dropdown] - Dynamic load items doesn't change default selection

### ISSUE THREAD

**Issue by p33nty** [Semantic-Org/Semantic-UI#4714]
Please check https://jsfiddle.net/ycqozhyx/3/
1. First click [Go 1], you will get correct result.
2. Next click [Go 2], will be displayed "item_2", should be "item_B". The "item_2" does not exist now in dropdown.

The same if you click first [Go 2], next [Go 1], but you will get "item_B" for both clicks.

**Comment by Banandrew** [comment]
Hi @p33nty,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
