### ISSUE TITLE
how to Installing By Vuejs2?

### ISSUE THREAD

**Issue by imagine10255** [Semantic-Org/Semantic-UI#4715]
how to Installing By Vuejs2?

Recommendations can be added

    http://semantic-ui.com/introduction/integrations.html

**Comment by Jielde** [comment]
+1

**Comment by Banandrew** [comment]
There’s no complete Vue 2 integration for SUI, so. Not sure what’s the proper way of doing it, but I use Vue 2 with Webpack, and I’ve just done it by simply requiring the minified js-file from the installation folder before requiring Vue and setting up components. I understand it’s not very helpful, but it’s difficult to give advice without any knowledge on your personal Vue setup.

**Comment by imagine10255** [comment]
Hi~
You are saying that the direct import semantic-ui.min.js and semantic-ui.min.css ?

**Comment by Banandrew** [comment]
Hey,

Yes, or separate SUI’s modules, I mean, maybe you only need modals or transitions, for instance. That’s how I bootstrap everything:
```JS
// Load jQuery.
window.$ = window.jQuery = require('jquery')

// SUI's components and other libraries.
require('../semantic-ui/dist/semantic.min')

// Vue itself.
window.Vue = require('vue')

// Start building components and initiate a new Vue instance.
// const vm = new Vue({
//   el: '.vue_container'
// })
// etc.
```
You can use SUI’s CSS like would normally do with `<style>` tag.

**Comment by imagine10255** [comment]
I find time to try, thx

**Comment by doublemarked** [comment]
@Banandrew thanks for the very helpful snippet. This got me on the right track.

I ended up coupling this with the webpack ProvidePlugin,

```javascript
// webpack.conf.js
  ...
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    })
  ]


// src/main.js
import Vue from 'vue'
import App from './App'

import '@/assets/semantic/dist/semantic'
import '@/assets/semantic/dist/semantic.css'

new Vue({ ... })
```

Webpack will then auto-require jQuery if something tries to use it as a global.

I got this from the docs: https://webpack.js.org/guides/shimming/#components/sidebar/sidebar.jsx
