### ISSUE TITLE
Is it possible for transition to change the height of element's container smoothly?

### ISSUE THREAD

**Issue by destan** [Semantic-Org/Semantic-UI#4716]
When `.transition('slide down')` called on an element, the elemen't container's height is not changing smootly. Please see this sample: http://codepen.io/destan/pen/yVyYmx

However the container's height is smoothly changing when using jQuery's `slideToggle`.

Is there a way to achieve the same behavior with `transition`?

**Comment by jlukic** [comment]
In my last research attempts, I have found no effective way to animate height without precalculating height using offscreen elements and adding inline styles. Height cannot animate from 0px to`auto` unfortunately.
