### ISSUE TITLE
popup content messed up

### ISSUE THREAD

**Issue by 404noahfound** [Semantic-Org/Semantic-UI#4718]
I have a popup button within a three wide column. When the popup is activated, it does not exceed the boundary of the column div, and the content is all messed up. Can anyone help?
the screenshot: [https://s11.postimg.org/k8ce6wx7n/2016_11_08_12_41_31.png](url)

**Comment by saitonakamura** [comment]
If you consider this as a bug, please add a jsfiddle, as [Contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md#creating-bug-reports) suggested
Also, your link is broken

**Comment by Banandrew** [comment]
Closing until there’s a test case.
