### ISSUE TITLE
Performance degredation after version upgrade

### ISSUE THREAD

**Issue by dwightbcoder** [Semantic-Org/Semantic-UI#4719]
I just had to roll a client back after upgrading from 2.1.7 to 2.2.6 due to **drastically** slower performance in **IE11** after the upgrade.

In very heavy UI and JS features in the web application complete load times could go from <20s to several minutes causing the dreaded "Internet Explorer and only one of them has become unresponsive" message to appear and the window to grey out.

I haven't been able to pinpoint the origin but did spend hours debugging before discovering downgrading SUI resolved the issue.

Is there anything that jumps out as a potential cause? The main offending features I'm using do also use Google Maps.  It's not possible for me to rip them out as demo pages unfortunately.

**Comment by sstok** [comment]
Can you can try slowly incrementing the versions? to see if which version is causing the problem.
2.1.7 to 2.2.6 is a major jump!

Note that SUI uses jQuery which is known to cause problems in heavy JavaScript applications 🤔

**Comment by avalanche1** [comment]
@dwightbcoder You need to narrow it down to what exact version of SUI and which exact component causes this slowdown. And then file a new issue. Otherwise we won't be able to help
