### ISSUE TITLE
Not getting selected value from dropdown

### ISSUE THREAD

**Issue by SylarRuby** [Semantic-Org/Semantic-UI#4720]
How to get the selected value?

```
<div class="ui selection dropdown demo">
  <input type="hidden" name="gender">
  <i class="dropdown icon"></i>
  <div class="default text">Gender</div>
  <div class="menu">
    <div class="item" data-value="1">Male</div>
    <div class="item" data-value="0">Female</div>
  </div>
</div>
```

**JS:**

```
let output = $( ".ui.selection.dropdown.demo" ).dropdown('get value');
console.log(demo);
```
When selected, I should get either Male or Female in console.

**Comment by avalanche1** [comment]
Make a repro

**Comment by vinayakkulkarni** [comment]
Your `<input type="hidden" name="gender">` will add `value` attribute when you select the male or female.

**Comment by peyman-mohamadpour** [comment]
@avalanche1 is `<input type="hidden" name="gender">` the only way to get submitted value from dropdown? I am using Symfony thus should use submitted value for the original `<select>`. Is that possible? how? any links or documentations?

**Comment by avalanche1** [comment]
Closing until there's a clear reproduction of the issue.
@peyman-mohamadpour pls use stackoverflow for usage questions.

**Comment by vinayakkulkarni** [comment]
@peyman-mohamadpour : [Semantic-UI Docs](http://semantic-ui.com/modules/dropdown.html#/definition)

> Selection dropdowns can be initialized directly on a select or with the matching HTML and a hidden input.
