### ISSUE TITLE
Divider docs glitch

### ISSUE THREAD

**Issue by qoqaqola** [Semantic-Org/Semantic-UI#4723]
Check screenshot for more info:
![image](https://cloud.githubusercontent.com/assets/14312785/20101553/2d92ddea-a5cb-11e6-9913-ddadbe6ee036.png)

Using: Google Chrome Version 54.0.2840.71 m

**Comment by ignasbernotas** [comment]
I don't think it's a doc glitch, I'm having the same issue with my build (v2.2.6)

**Comment by jlukic** [comment]
I've posted a bug with Chromium. There does not appear to be a workaround from a framework level. Hopefully Chrome team can fix this soon.

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
