### ISSUE TITLE
ng grid is not working in angular2 without <link>

### ISSUE THREAD

**Issue by ccinar91** [Semantic-Org/Semantic-UI#4729]
I'm building an app in angular2 and using semantic ui for styling. I've had no problem with semantic so far and loving it.

I'm using angular-cli and using ng build to bundle up my project to the public folder and serve it from there using a node server.

I'm including semantic in the component.ts with "styleUrls" and everything is working except the semantic grid. This is my component.html:

```
<div class="ui centered grid">
  <div class="ui eight wide column">
      <div class="ui raised segment">
        <h1 class="ui header">
          {{title}}
        </h1>
        <div>
          <button class="ui tiny button" (click)="talk()">Talk to Server</button>
        </div>
      </div>
  </div>
</div>
```

but it's giving me full width segment no matter the number (one, two, eight, etc)

Since angular-cli is completely deleting and creating public folder when I use ng build, either I have to manually add the css folder into public each time I build or use ajax (which I don't want to use unless I have to) to get it from cloud.

Is there a way around for this? Is this an issue or am I misusing something?

**Comment by Banandrew** [comment]
Hi @ccinar91,

It’s not an issue with SUI, it’s likely an issue with Angular lifecycle, and I think it’s better to ask about it in Angular community. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
