### ISSUE TITLE
How to center form inline field?

### ISSUE THREAD

**Issue by sackery** [Semantic-Org/Semantic-UI#4733]

**Comment by saitonakamura** [comment]
Please consider the [community rules](https://github.com/Semantic-Org/Semantic-UI#getting-help)

> Please do not post usage questions to GitHub Issues. For these types of questions use [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui), [ProjectTalk ](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI)or join our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
