### ISSUE TITLE
[Modal] Scrolling bar does not appear when changing modal size

### ISSUE THREAD

**Issue by p33nty** [Semantic-Org/Semantic-UI#4735]
Please check https://jsfiddle.net/fvjws3kp/1/

1. Click button 'Show modal'
2. Click button 'Long text' - scrolling bar does not appear, I can't see what is at the bottom of the modal
3. Close modal by clicking on a background
4. Click button 'Show modal' - scrolling bar appears

Scrolling bar should appear at point 2, when changes size of the modal.

**Comment by balexandre** [comment]
you do need to refresh the modal to re-center it ... it's in the [documentation](http://semantic-ui.com/modules/modal.html#/usage) under behaviour

```
refresh: Refreshes centering of modal on page
```

try again with this update: https://jsfiddle.net/fvjws3kp/2/

**Comment by p33nty** [comment]
@balexandre I know that. But refresh with changing of size causes "jumping" of modal. In fact, I could use two independent modals, the same effect. In my opinion it is bad impression for end user. 
I display my modals on position top:50 (not center) and I increase size of them. It works ok, there is no "jumping" of modals until size is bigger than size of browser, then part of modal is hidden and I can't scroll it.

**Comment by Banandrew** [comment]
Hi @p33nty,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
