### ISSUE TITLE
scrolling menu upward not work ？

### ISSUE THREAD

**Issue by Marquis-H** [Semantic-Org/Semantic-UI#4737]
scrolling menu upward not work ？

**Comment by IonutBajescu** [comment]
Is this a bug report or a feature request?

**Comment by code-h** [comment]
![303219d3-e13d-4ef7-8ab6-0da3f9b09ec3](https://cloud.githubusercontent.com/assets/8198679/20294187/4366bbde-ab37-11e6-87d9-85a94d8e9ba8.png)

**Comment by vinayakkulkarni** [comment]
Please be more specific and provide a jsFiddle if possible?

Scrolling upward works perfectly for me.

**Comment by Banandrew** [comment]
See #3254.
