### ISSUE TITLE
Float right input text or other element

### ISSUE THREAD

**Issue by KarmitoHerry** [Semantic-Org/Semantic-UI#4739]
i try to find people with same problem with me using google and in this github.
i'm new on this css because before this i found this css on my admin template , i use bootstrap.

i try to make float right or left on other element like (label,input,etc) , i cannot found on http://semantic-ui.com/ as reference to edit my admin template.

i try on my self create own style on div tag , example on this link https://jsfiddle.net/karmito/mghc1Lg9/

if anyone found same problem , give a solution please without attach any style or create new custom css but default from semantic.css

**Comment by vinayakkulkarni** [comment]
use class `right aligned` class to the columns, it's in the docs: [Here](http://semantic-ui.com/collections/grid.html#columns)
PS. Here's your forked and fixed [jsFiddle](https://jsfiddle.net/vinayakkulkarni/torLudbf/)
