### ISSUE TITLE
[Divider] - Vertical Divider is displayed in the wrong place.

### ISSUE THREAD

**Issue by abshammeri** [Semantic-Org/Semantic-UI#4744]
**Steps to Reproduce**
1.  [See the second example in the doc page](http://semantic-ui.com/elements/divider.html):

**Result**
![screen shot 2016-11-15 at 10 15 09 am](https://cloud.githubusercontent.com/assets/815055/20296630/05b07a56-ab1d-11e6-9929-7675f8ecd130.png)

**Testcase**

http://jsfiddle.net/abshammeri/1gz81cs7/1/

**Comment by IonutBajescu** [comment]
Known issue I'm afraid, #4342.

There's no workaround at the framework level for the the time being. 

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
