### ISSUE TITLE
ShowNoResults not working

### ISSUE THREAD

**Issue by hemantthorat** [Semantic-Org/Semantic-UI#4745]
As per [http://semantic-ui.com/modules/search.html#/settings] ShowNoResults is false by default. I've enabled it by setting it true. But, still it is not showing "no results" message.
Below is coffee script code snippet,
`$('#topNav .ui.search, .heroImage .ui.search').search
  type: 'category'
  minCharacters: 2
  cache: false
  searchDelay: 300
  showNoResults: true
  fields:
    description: 'body'
  apiSettings:
    url: 'http://path/to/url?query={query}'
    onResponse: (response) ->
      response    
  onSelect: (result, response) ->
    window.location.assign result.url`

**Comment by Banandrew** [comment]
Hi @hemantthorat,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
