### ISSUE TITLE
nav-menu -> dropdown item -> menu > item, padding too big, can't change

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4746]
Hi, I use a simple dropdown menu on nav-menu, on the top, but the padding of items in the dropdow menu can not be adjusted, `vertically fitted`, `compact` do not work.
```
<div class="ui blue inverted massive borderless menu">
      <div class="ui container" id="nav-menu">
        <div class="header item">
          Check it out!
        </div>

        <div class="ui simple dropdown item">
          Countries
          <i class="dropdown icon"></i>
          <div class="menu">
            <a class="item">USA</a>
            <div class="ui divider"></div>
            <a class="item" id="cerulean" href="../cerulean/">China</a>
            <a class="item" href="../cosmo/">UK</a>
            <a class="item" href="../cyborg/">India</a>
           .......
```

The padding is too big, so the menu can be very long vertically. I try to change the padding by using classes, and custumizing css style, but it shows that the padding is defined in "!important", so I can not modify it, anyone have an idea? Thanks!

**Comment by Banandrew** [comment]
Hi again @tarvos21, if the issue is still a problem, you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) and mention me on Gitter. Thanks for closing!

**Comment by tarvos21** [comment]
@banadrew, thanks!
