### ISSUE TITLE
Dependency on jQuery not documented

### ISSUE THREAD

**Issue by MacLake** [Semantic-Org/Semantic-UI#4748]
While I can find a lot of discussions about the dependency on jQuery, i can’t find anything about the requirement to include jQuery. E. g. on http://semantic-ui.com/introduction/getting-started.html only including the JS and CSS files of Semantic UI itself is mentioned:

> ### Include in Your HTML
> 
> Running the gulp build tools will compile CSS and Javascript for use in your project. Just link to these files in your HTML.
> 
>     <link` rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css">
>     <script src="semantic/dist/semantic.min.js"></script>
> 

But apparently Semantic UI works only if jQuery is included before Semantic Ui’s JS file.

**Comment by Biarity** [comment]
Same here. Not sure if it's okay to just ignore the jquery dependency.

**Comment by MacLake** [comment]
Now it’s mentioned that you have to include jQuery and in the [HTML snippet](https://semantic-ui.com/introduction/getting-started.html) a link to a CDN version of jQuery is shown. That’s fine for me, so we can close this issue.
