### ISSUE TITLE
[Search] - infinite maxResults

### ISSUE THREAD

**Issue by yaboi** [Semantic-Org/Semantic-UI#4749]
This isn't a bug, but rather a feature request of sorts. As of right now I have to manually set an integer for `maxResults` or it defaults to 7. I'd like to have a `false` option or something that disables the required number so that I can show infinite (or all) results.

My results are always visible. If there is nothing in the search input, all search results objects are returned. Unfortunately, there is no way to tell how many this is or will be in the future so I'd like to be able to show them ALL.

**Comment by tabeth** [comment]
You could just set maxResults to be the maximum integer.

**Comment by yaboi** [comment]
@tabeth Seems like a legit solution for now, but would rather that be handled by Semantic with a simple `false` flag rather than in the options I pass to the component.

**Comment by eronaeon** [comment]
@larvata
