### ISSUE TITLE
How to change content when touch different tab

### ISSUE THREAD

**Issue by KeZhimin** [Semantic-Org/Semantic-UI#4751]
the code like this:
````html
<div class="ui container" style="margin-top: 10px;">
    <div class="ui  tabular menu">
        <a class="active item" data-tab="first">First</a>
        <a class="item" data-tab="second">Second</a>
    </div>
    <div class="ui bottom attached tab segment" data-tab="first">
    </div>
    <div class="ui bottom attached tab segment" data-tab="second">
    </div>
</div>
````

```` javascript
<script type="text/javascript">
    $('.menu .item').tab({
        cache: false,
        // faking API request
        apiSettings: {
            loadingDuration : 300,
            mockResponse    : function(settings) {
                var response = {
                    first : 'query1.json',
                    second : 'query2.json'
                };
                return response[settings.urlData.tab];
            }
        },
        context : 'parent',
        path    : '/'
    });
</script>
````

when I click the First tab, i want get the content from the url 'query1.json', when i click the the Secode tab, i want get the content from the url 'query2.json', the code like that dont work.

**Comment by bukaOK** [comment]
@KeZhimin maybe you need something like this..

`$('.menu .item').tab();
$('.tab[data-tab="first"]').api({
	url: 'query1.json',
	//Another settings
});
$('.tab[data-tab="second"]').api({
	url: 'query2.json',
	//Another settings
 });`

**Comment by Banandrew** [comment]
Hi @KeZhimin,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
