### ISSUE TITLE
[Divider] - Vertical Dividers not working on Chrome Win8

### ISSUE THREAD

**Issue by maxoys45** [Semantic-Org/Semantic-UI#4753]
**Steps to Reproduce**
1. Goto Divider section
2. Scroll to vertical divider section

**Expected**
The Divider should be placed between each section

**Result**
The vertical dividers all stack on top of each other on the far left

![image](https://cloud.githubusercontent.com/assets/7223240/20357360/9364cdd6-ac1f-11e6-8401-098c70d3f72e.png)

Running Windows 8, Chrome Version 54.0.2840.99 m

**Comment by IonutBajescu** [comment]
Known issue I'm afraid, #4342.

There's no workaround at the framework level for the the time being. 

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
