### ISSUE TITLE
I did not list the data with Dropdown Search Api

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#4754]
I receive data but can not list.
How can I solve it.

Incoming data : http://i.hizliresim.com/vXzj6p.png
My code : http://i.hizliresim.com/1VPJ6G.png

**Comment by oguzhansari** [comment]
I did it with the codes I found on the internet.

I write more than two characters.
The connection is interrupting.

I tried to tell with video.

I took a video http://sendvid.com/0x1pfzqh

**Comment by vinayakkulkarni** [comment]
Look at the [dropdown docs ](http://semantic-ui.com/modules/dropdown.html#/settings)

add `fullTextSearch: true` to your code and try again.

Pls post a jsFiddle

Closing this for now.. Ping on [gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [SUI Forums](http://forums.semantic-ui.com/)
