### ISSUE TITLE
[Dropdown] Issue with 'set value' when value is "0"

### ISSUE THREAD

**Issue by stijena** [Semantic-Org/Semantic-UI#4755]
I believe .form method is not displaying correct behavior for value "0" in dropdown. The code example is given below and is available on jsfiddle: http://jsfiddle.net/stijena/y7axjw2y/4/ .

```
<form id="form-create" class="ui form">
      <select name="port-type" class="ui fluid dropdown">
        <option value="0">Async</option>
        <option value="1">Sync</option>
        <option value="2">Ethernet</option>
      </select>
</form>

<script>

$('.ui.dropdown').dropdown();

function setToZero() {
	$("#form-create").form('set value', 'port-type', 0);
}
function setToOne() {
	$("#form-create").form('set value', 'port-type', 1);
}
</script>

<button onclick="setToZero()"> Set To Zero </button> 
<button onclick="setToOne()"> Set To One </button>
```

Method setToZero WILL NOT turn value of dropdown to 0 (Async option). However, method setToOne WILL set selected dropdown to 1 (Sync). Also, if 0 is cast to String, setToZero will also work - so I suppose it has something to do with how JS interprets zero value.

This seems to work fine in older version of semantic-ui (2.0.1), but not in newer versions as 2.2.3 and 2.2.6.

**Comment by Banandrew** [comment]
See #3840.
