### ISSUE TITLE
Showing modal #A then #B , then trying to close #A will close BOTH.

### ISSUE THREAD

**Issue by avilv** [Semantic-Org/Semantic-UI#4758]
jsfiddle : 
 https://jsfiddle.net/zq14c4uv/5/

this bug is extremely annoying, and basically breaks using modal for progress/loading notifications in my app.

**Comment by fstanis** [comment]
[As per the docs](http://semantic-ui.com/modules/modal.html#/settings), you need to set `allowMultiple: true` when you initialise the modal if you don't want hiding a modal to hide all other modals.

In addition, it still fails if you try to hide it *immediately*. This works fine though:

```
   var modal1 = $("#modal1").modal({ allowMultiple: true });
   var modal2 = $("#modal2").modal({ allowMultiple: true });
   
   modal1.modal("show");
   setTimeout(function() {
     modal2.modal("show");
   }, 2000);
   setTimeout(function() {
     modal1.modal("hide");
   }, 4000);
```
