### ISSUE TITLE
multiple tags dropdown form post with enter click 😢

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#4763]
Can add terms with commas!
But the "Enter" key sends the form!

I showed it on the video.
http://sendvid.com/aivrhodg

Keywords in Video;

"anahtar" (comma) "kelimeler" (comma) "deneme" (enter)

enter => form post 😢

**Comment by jtuttle87** [comment]
Ran into this as well, you can work around it by setting the delimiter to the enter key such as: 

$('.ui.dropdown').dropdown({
            allowAdditions: true,
            keys: {
                delimiter: 13
            }
        });

**Comment by vinayakkulkarni** [comment]
@oguzhansari : Did you try @jtuttle87 example?

**Comment by oguzhansari** [comment]
I will try and give information.

**Comment by oguzhansari** [comment]
It's just not enough (allowAdditions: true)

Adding this code has improved the problem.
    keys: {
        delimiter: 13
    }

Thank you.
