### ISSUE TITLE
[Icons] Upgrade to Font Awesome

### ISSUE THREAD

**Issue by brainscript** [Semantic-Org/Semantic-UI#4764]
[**Font Awesome 4.7**](https://github.com/FortAwesome/Font-Awesome/milestone/21?closed=1) is out and it's time to update I guess.
![bildschirmfoto vom 2016-11-19 18-40-05](https://cloud.githubusercontent.com/assets/8706734/20457259/9c95ba68-ae87-11e6-9c69-7daa648667a7.png)
@BreadMaker You did it last time when upgrading to 4.6.3. Would you mind doing it another time? :pray:
Otherwise I would try to get this done because I really need the new icons (especially the `telegram` one).

**Comment by BreadMaker** [comment]
I'm on it, it's always a pleasure to help.

**Comment by BreadMaker** [comment]
Done, let's continue at the PR #4766

**Comment by brainscript** [comment]
@BreadMaker Awesome! Thanks! :smiley:
