### ISSUE TITLE
[Divider] - Vertical Divider example not working in Chrome

### ISSUE THREAD

**Issue by vhflat** [Semantic-Org/Semantic-UI#4767]
**Steps to Reproduce**
1. Open chrome
2. go to http://semantic-ui.com/elements/divider.html

**Expected**
The Divider should go in the middle between the login form and the sign up button

**Result**
The Divider appears on the left of the login form. Its weird because it works fine in Safari and Firefox.

**Comment by oguzhansari** [comment]
😱 I realized when you told me.

But looks like there's no problem with the mobile version.  > http://i.hizliresim.com/pXYjOn.png

**Comment by jlukic** [comment]
#4342 

I've posted a bug with Chromium. There does not appear to be a workaround from a framework level. Hopefully Chrome team can fix this soon.

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
