### ISSUE TITLE
[Dropdown] Cannot create a new option when there is an option that partially matches with it

### ISSUE THREAD

**Issue by visualfanatic** [Semantic-Org/Semantic-UI#4768]
Using the code from the docs I've made a little example:
https://jsfiddle.net/mjkqseL6/

Try to create a new option: `R`.

**What I'm expecting:** a new option `R` should be added.
**What is actually happening:** existing option `Rails` is selected.

Is there any workaround? I've already tried setting `selectOnKeydown` to `false`, but it doesn't work.

**Comment by Banandrew** [comment]
Hi @visualfanatic, not sure if you figured it out, but there’s a workaround that’s related to #4052: set `hideAdditions` to `false`. Closing as a duplicate.
