### ISSUE TITLE
[Checkbox] - when I use radio checbox in chrome 53.0.2785.8 for windows, it seems failed

### ISSUE THREAD

**Issue by xuyongli** [Semantic-Org/Semantic-UI#4772]
**Steps to Reproduce**
1. I know : Browser Support , Last 2 Versions FF, Chrome, Safari Mac
2. I write code like radio example in http://semantic-ui.com/modules/checkbox.html
3. And my code was run in chrome which in 53.0.2785.8

**Expected**
The Checkbox should be checked when I click it

**Result**
The Checkbox was not checked when I clicked it

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
