### ISSUE TITLE
How to focus semantic drop down ?

### ISSUE THREAD

**Issue by shamseerk** [Semantic-Org/Semantic-UI#4774]
I want set a hot key for semantic drop down on Ctrl+Q.how can i do that.tried usual methods it is not working

**Comment by dopeboy** [comment]
Going to need more detail here. Do you want to intercept the crtl+q keystrokes and then focus a dropdown?

**Comment by larrifax** [comment]
I guess he wants a way to focus a dropdown programmatically when Ctrl+Q is typed. I'm interested in doing the same thing, but cannot seem to find a clean way of focusing the dropdown and giving the user the ability to type in a search or choose options. I've tried calling `focus()` on the `div.ui.dropdown`, but that doesn't work (I've tried it with & without `tabindex="-1"`).  The only way I've found, is to crawl the DOM until I find the `input.search` element and call `focus()` on that, but that feels like a hack to me.

**Comment by salaros** [comment]
https://github.com/Semantic-Org/Semantic-UI#getting-help


Please **do not post** usage questions to GitHub Issues. For these types of questions use [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui), [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) or join our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
