### ISSUE TITLE
[Dropdown] new setting option ignoreCase for sortSelect

### ISSUE THREAD

**Issue by Blaimi** [Semantic-Org/Semantic-UI#4775]
Right now sortSelect always sorts options to uppercase first followed by lowercase: [A, B, C, a, b, c]
A new setting option "ignoreCase" would be nice to have a sort result kind of: [A, a, B, b, C, c]
This could be achieved with:
```javascript
if(settings.sortSelect) {
	var aName = a.name;
	var bName = b.name;
	if(settings.ignoreCase) {
		aName = aName.toLowerCase();
		bName = bName.toLowerCase();
	}
	select.values.sort(function(aName, bName) {
		return (aName > bName)
			? 1
			: -1
		;
	});
}
```
around https://github.com/Semantic-Org/Semantic-UI/blob/0b1b59b0e1c780e842820df5c1904a162034812c/dist/components/dropdown.js#L1804

**Comment by lubber-de** [comment]
Implemented since Fomantic-UI 2.4 by additional values for setting `sortSelect`
https://fomantic-ui.com/modules/dropdown.html#/settings

![image](https://user-images.githubusercontent.com/18379884/57305609-a635b180-70e1-11e9-861f-9b761bdac1e1.png)
