### ISSUE TITLE
Placeholder on an <input type="number" ...> field is darker than other fields

### ISSUE THREAD

**Issue by Morrolan** [Semantic-Org/Semantic-UI#4776]
The placeholder is noticeably darker where the input type is `number` rather than `text`.

'**Postcode**' is of type `text`, and '**Radius (mi)**' is of type `number`.

![Image of Issue](http://i.imgur.com/3pt9RdF.png)

Not sure if this is by design or in error.

**Comment by dopeboy** [comment]
The placeholder of the component will be darker if it is focused. If they are both unfocused, the placeholder color is the same:

https://jsbin.com/zuzoyebefu/edit?html,output

**Comment by Banandrew** [comment]
Closing as resolved.
