### ISSUE TITLE
Scrolling Multiple Selection Dropdown?

### ISSUE THREAD

**Issue by adamcollingburn** [Semantic-Org/Semantic-UI#4777]
I'm trying to get the tokenizing dropdown to behave like a regular one and rather than expanding the input height - keep the tokens on one line and scroll the overflow.

I've added white-space: nowrap and overflow: scroll to the dropdown which obviously cuts the menu - but then removing relative positioning from the dropdown, adding it to a parent wrapper and then making the menu fixed should pull this out to the viewport and display it and it doesn't!

http://codepen.io/bezoerb/pen/AGgcu

You can see how this should work here, but I can't find out why the the fixed menu element is still relative to the dropdown - any ideas? Codepen below:

http://codepen.io/adamccc/pen/xRdGvY

**Comment by Banandrew** [comment]
Hi @adamcollingburn,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
