### ISSUE TITLE
[Header] Icon in the header: wrong vertical alignment

### ISSUE THREAD

**Issue by nZeus** [Semantic-Org/Semantic-UI#4780]
Here is a fiddle where you can see the problem:
https://jsfiddle.net/Kpblca4/8z2a0fgm/

When using a header with an icon inside, icon is not properly aligned. For the end-user it seems that the icon is lower than the text. I've found that [this line](https://github.com/Semantic-Org/Semantic-UI/blob/f725b162e70896e38257965424ac7f9af486b927/src/definitions/elements/header.less#L67) can be removed.

**Comment by sbmelvin** [comment]
I've encountered the same alignment problem when using icons in list items #4872.

**Comment by sbmelvin** [comment]
Actually, I just noticed that this is not the same (although related). My issue was was the horizontal alignment, not vertical. My fix was setting padding-right: 0; Perhaps the pull request by @ivannieto could be amended to include padding-right:0 as well?

**Comment by philrykoff** [comment]
In #4872, there is a solution to this issue.
