### ISSUE TITLE
Remove font-awesome

### ISSUE THREAD

**Issue by nicolas-goudry** [Semantic-Org/Semantic-UI#4781]
Hi,

I’m using Semantic in a React app and I don't want to have font-awsome included (I use my own icons from SVG sprites, which is clearly 1000× better than icon font), how could I achieve that?

I made a custom theme and, still, those icons are here! How to get rid of them in my theme, please?

Thanks!

**Update 1:**

For your information, I removed the `@font-face` rule from `definitions/elements/icon.less` and icons are ”removed” (sort of, because font is no more embedded in bundle but there is still icon rules (`content` property).

I think that's not the way to do this, there should be another clean way…

Whatever, now I no more have fa icons on the app, but dropdown are still using a font called `Dropdown`… This is endless :cry:

I really think CSS frameworks should let icon fonts being handled by another project, IMO that’s really a pain point of CSS frameworks!

**Update 2:**

I tried to unset icon font variables in my theme `icon.variables` file, like this:

```less
@fontName: '';
@fallbackSRC: '';
@src: '';
```

It works, but there is still base64 embedded Dropdown font… So I tried to unset it in `dropdown.overrides`:

```less
@font-face {
  font-family: 'Dropdown';
  src: '';
}
```

But it's not working for this one…

**Comment by nicolas-goudry** [comment]
For your information, I removed the `@font-face` rule from `definitions/elements/icon.less` and icons are ”removed” (sort of, because font is no more embedded in bundle but there is still icon rules (`content` property).

I think that's not the way to do this, there should be another clean way…

Whatever, now I no more have fa icons on the app, but dropdown are still using a font called `Dropdown`… This is endless :cry:

I really think CSS frameworks should let icon fonts being handled by another project, IMO that’s really a pain point of CSS frameworks!

**Comment by jlukic** [comment]
You can just remove `icons` from your `semantic.json` component list (if you're using our build system) or just skip `icon.less` if you are using your own.

**Comment by nicolas-goudry** [comment]
Hi @jlukic, thanks for your quick answer!

This is working only for font-awesome icons, so far that's cool but it answers only one of my questions. Actually, dropdown icon and accordion icon are still here due to font-face Dropdown :confused: 

No way to disable this behaviour? I’ll deal with it if we can't, because font is embedded in base64 so that's ok for me, but it would be great if we could do this too!
