### ISSUE TITLE
[Icon] - Errors in console

### ISSUE THREAD

**Issue by Splean** [Semantic-Org/Semantic-UI#4783]
**Steps to Reproduce**
When page is loading (eg http://semantic-ui.com/ and others in this site), i have some errors in chrome browser console.

![2016-11-24_14-06-02](https://cloud.githubusercontent.com/assets/1957556/20596373/41c48224-b24f-11e6-8dc2-de70b9c851f7.png)

**Comment by dopeboy** [comment]
Not quite sure this is issue worthy...

That said, turn off any adblock extensions and try again

**Comment by sbmelvin** [comment]
I agree with @dopeboy, this doesn't need to be an issue.
@Banandrew

**Comment by vinayakkulkarni** [comment]
This doesn't seem to relate to the framework issue.
Try disabling adblock as @dopeboy said.
