### ISSUE TITLE
[Typo] on kitchen-sink.html

### ISSUE THREAD

**Issue by vinayakkulkarni** [Semantic-Org/Semantic-UI#4784]
[Kitchen Sink URL](http://semantic-ui.com/kitchen-sink.html#statistic)

should be `Horizontal` but it says `Horizonal`

**Comment by dopeboy** [comment]
Definitely looks like a typo to me too! Thanks for spotting this. Try submitting a PR to this repo: https://github.com/Semantic-Org/Semantic-UI-Docs

**Comment by vinayakkulkarni** [comment]
Sent a PR : https://github.com/Semantic-Org/Semantic-UI-Docs/pull/260
