### ISSUE TITLE
.ui.buttons affect all nested button elements

### ISSUE THREAD

**Issue by max-payne-7** [Semantic-Org/Semantic-UI#4785]
The .ui.buttons affect all the nested button elements, although it should affect only the first level children with class "ui button".

Thank you for a great framework!

**Comment by vinayakkulkarni** [comment]
@max-payne-7 : kindly use this [jsFiddle](http://jsfiddle.net/efp8z6Ln/) to create a test case.
For anything else, just ping us on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI)
Closing this for now, if you have any serious question.. just ask 😃
