### ISSUE TITLE
[Dropdown] "Choose an option", goes away after first change

### ISSUE THREAD

**Issue by peyman-mohamadpour** [Semantic-Org/Semantic-UI#4786]
- **HTML**

      <form name="service" method="post">
        <div class="ui form" id="service">
          <div class="field">
            <div class="ui selection dropdown">
              <select id="choose_service" required="required">
                <option value="" selected="selected">Choose an option</option>
                <option value="1">Some service</option>
                <option value="2">Another service</option>
                <option value="3">Some other service</option>
              </select>
            </div>
          </div>
        </div>
      </form>
- **JS**

      $(document).ready(function () {
        $('.ui.dropdown').dropdown();
      });

**Problem:**
At first, the **Choose an option** shows up, but it goes away after first change.

**Environment:**

- Semantic-UI 2.2.6
- jQuery 2.2.4

**Comment by dopeboy** [comment]
This is the expected behavior. If you would like to restore the "Choose an option" option, you will need to restore the dropdown to its defaults via:

```
$('.ui.dropdown').dropdown('restore defaults');
```

I'll usually have a clear button next to my dropdown who's click handler runs the above code.

**Comment by peyman-mohamadpour** [comment]
Thanks for your message body, but I don't think if this behaviour always is desired. Imagine an example usage in which the placeholder option is titled:

**None of the below**

There you should be able to simply choose that option again, even after a wrong choice or missclick.

**Comment by dhvsandeep** [comment]
Do this, Remove the div with dropdown class and  add _**ui dropdown**_ class to select element.

Note : This worked for me !

**Comment by ashkonBG** [comment]
https://jsfiddle.net/xu4fv5n0/2/
