### ISSUE TITLE
[Table] - Sortable table JS is not included in the components of the semantic ui available for download.

### ISSUE THREAD

**Issue by sunildhillon** [Semantic-Org/Semantic-UI#4788]
**Steps to Reproduce**
1. The file required for sorting table is not present in the main  inlcudes>components

**Expected**
I expected this file http://semantic-ui.com/javascript/library/tablesort.js to be there in the components when downloading the whole semantic ui. 

**Result**
The Table does not do sort if the file is not present there, you need to explicity download the file and include it in the page.

**Comment by Banandrew** [comment]
Hi @sunildhillon,

The documentation clearly states that you need to include a specific library to make it work, as it’s not a part of the framework. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
