### ISSUE TITLE
Referenced tablesort.js in documentation is buggy

### ISSUE THREAD

**Issue by dopeboy** [Semantic-Org/Semantic-UI#4791]
**Steps to reproduce:**

1. Build a sortable table per the [documentation](http://semantic-ui.com/collections/table.html#sortable).
2. In a cell, put in a link using the `<a>` tag and attach an onClick handler to it. Click on the link - it will work as expected.
3. Sort the table by clicking on any column. 
4. Click on the link with the onClick handler.

**Result:**

The click handler does not work. 

**Fix:**

The tablesort.js linked in the documentation is old. The newest one, found [here](https://raw.githubusercontent.com/kylefox/jquery-tablesort/master/jquery.tablesort.min.js) does not result in this error. 

Happy to submit a PR to the docs repo - just wanted to get some initial reception here.

**Comment by vinayakkulkarni** [comment]
The one on the SUI docs is version `0.0.11` too.
