### ISSUE TITLE
Image size Attribute will by overwriten by corner

### ISSUE THREAD

**Issue by nexinto-gmbh** [Semantic-Org/Semantic-UI#4792]
[Codepen](http://codepen.io/anon/pen/yVXQXa)
i.icons .corner.icon { ... font-size: .45em; ... }
i.small.icon, i.small.icons { ... font-size: .75em; }
The corner selector is more specific than the "size" selector. So the a cornered item can't be sized.

We use react semantic ui with semantic ui css, but this is an independent problem.

**Comment by jlukic** [comment]
Please post in Semantic-UI-React
https://github.com/Semantic-Org/Semantic-UI-React/issues

**Comment by nexinto-gmbh** [comment]
I've posted this in the react repro and they ask me to submit the issue here.
https://github.com/Semantic-Org/Semantic-UI-React/issues/938

Which team is responsible?
