### ISSUE TITLE
Semantic UI dropdown with different input icon or without icon

### ISSUE THREAD

**Issue by kunokdev** [Semantic-Org/Semantic-UI#4794]
I am rendering dropdown search input like this:
```
<div class="field">
   <label>Foo</label>
   <select name="foo" class="ui search dropdown">
     <option value="">Choice</option>
   </select>
</div>
```
It creates standard SemanticUI dropdown input.

Is there possibility to tell Semantic to not render any icon or to render different icon in the input field?

**Comment by richardtallent** [comment]
If you are required to use a SELECT element, I don't think that would be possible without manually overriding the CSS. You can put an icon *beside* the SELECT element but not inside it. If you use a combination of a hidden INPUT and DIVs for the main element and options, you can add your own <I> icon to the main element.

**Comment by kunokdev** [comment]
There is solution as this same question is answered on Stackoverflow:

http://stackoverflow.com/a/40849515/5426743

By adding non-existing icon class to <i class=""></i> within element. (using divs rather than select is required, I think)
