### ISSUE TITLE
Multiple select dropdown with checkboxes !

### ISSUE THREAD

**Issue by dhvsandeep** [Semantic-Org/Semantic-UI#4795]
Is it possible to have multiple check boxes instead of options, a select all and unselect all options along?

On clicking the check box updates the name in select box with name or this many items selected !

**Comment by akshayrpatel** [comment]
I am also looking to implement something like this - http://phossa.github.io/smartselect/docs/demo.html#sec-3a
I want a "tree-type, multiple, search" dropdown

**Comment by Banandrew** [comment]
Hi @dhvsandeep,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
