### ISSUE TITLE
List icons have too much padding

### ISSUE THREAD

**Issue by ilyauts** [Semantic-Org/Semantic-UI#4797]
Unordered list and order list icons also inherit the following properties:

.ui.list .list, ol.ui.list ol, ul.ui.list ul {
    clear: both;
    margin: 0;
    padding: .75em 0 .25em .5em; <--------
}

Causing ordered list icon to have too much padding

**Comment by vinayakkulkarni** [comment]
You can always set custom padding if you want. 😉 

Also, join the discussion on [gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [SUI Forums](http://forums.semantic-ui.com/)

PS. Please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) by @Banandrew to make your case.
