### ISSUE TITLE
sidebar: lock content in pusher

### ISSUE THREAD

**Issue by ayushkov** [Semantic-Org/Semantic-UI#4798]
when I close the sidebar, tapping on overlay if I get on a link that is a transition on it, or set the focus on the input

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
