### ISSUE TITLE
Clear input search after search results

### ISSUE THREAD

**Issue by musixite** [Semantic-Org/Semantic-UI#4799]
Hi there,

Instead of displaying the result on the input search, I'd like it to get cleared once the search query has been executed (so I can do another search).

I tried playing with the callbacks without any success.

Is it possible?

**Comment by Banandrew** [comment]
Hi @musixite,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by deanmraz** [comment]
@musixite I ran across this issue as well. Did you end up getting an answer? Any guidance would be helpful. 

@Banandrew seems like this could be a bug in the docs, since there is not clear guide on how to do this. Also, maybe posting the end results here could help others when searching this issue tracker.

**Comment by Banandrew** [comment]
Hi @deanmraz, could you please elaborate on your use case, what are you trying to do, step by step?
