### ISSUE TITLE
[Dropdown] does not disable input when disabled class is added 

### ISSUE THREAD

**Issue by ubermanl** [Semantic-Org/Semantic-UI#4807]
A Dropdown Search still gets focus when disabled class is added to its div.
This http://jsfiddle.net/phfz3sz3/ fiddle shows the behaviour.

**Comment by jukestar** [comment]
If you add class multiple to the disabled select, its possible to delete its content with backspace

**Comment by lubber-de** [comment]
This was fixed in the community fork https://fomantic-ui.com 2.8.7 by https://github.com/fomantic/Fomantic-UI/pull/1606
See your adjusted jsfiddle here http://jsfiddle.net/lubber/r6o0ebwd/2/
