### ISSUE TITLE
Form Validator doesn't work when form submit by Enter key

### ISSUE THREAD

**Issue by paribux** [Semantic-Org/Semantic-UI#4808]
```
$(document).ready (function () {

                $('.ui.form')
                    .form({
                        fields: {
                            term: ['minLength[5]', 'empty']
                        }
                    });

                $.fn.api.settings.api = {
                    'search': '_endpoint/check.php'
                };

                $('#form').api({
                    action: 'search',
                    method: 'POST',
                    serializeForm: true,
                    onComplete: function (response) {
                        if (response.success == true) {
                        }
                        else {
                        }

                    }
                });

            });
```

If I submit form with clicking Submit button, there is no problem. But if I submit form with Enter Key, form validation and ajax request working together.

https://jsfiddle.net/so7jzpcz/3/

**Comment by Cyb3rWarri0r8** [comment]
You're not actually validating the form before you run the ajax call. `$('#form').form('validate') is what you want to do or use the `on: blur` validation option.

**Comment by Banandrew** [comment]
Hi @paribux,

You could also do something like that on submit:
```JS
$('form').submit(function() {
  if( $('form').form('is valid') ) {
    // Do an AJAX call.
  }
})
```
I’ll close this as an answered usage question. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
