### ISSUE TITLE
[Dropdown] Purely cosmetic dropdown?

### ISSUE THREAD

**Issue by Gh0zT** [Semantic-Org/Semantic-UI#4809]
First of all, I'm new to Semantic so my apologies if I'm missing something obvious.

For the past hour I've been trying to create a dropdown login form using Semantic UI but I just can't get it to work properly. So far I haven't found any way to create a dropdown that is purely for cosmetic purposes. Because I'm trying to include a form in the dropdown, I'd like it to not close the menu when clicking inside of it so the user can give input. I'd also like the dropdown's content to be unselectable and only close when clicking it again or when clicking anywhere outside it's content. Is there any way to achieve this using Semantic?

**Comment by ivantcholakov** [comment]
Maybe an accordion menu with one item would do the job. http://semantic-ui.com/modules/accordion.html#accordion-menu

**Comment by Gh0zT** [comment]
@ivantcholakov Thanks for your response, but unfortunately this is not an option as an accordion can't be nested inside a menu (or can it?)

**Comment by ivantcholakov** [comment]
I found, an accordion menu can be nested within an accordion menu again. But I don't know whether it would be suitable for your case.

**Comment by Gh0zT** [comment]
The solution to my problem was simple actually. I solved it by using a popup module. http://semantic-ui.com/modules/popup.html#/definition
