### ISSUE TITLE
Setting Progress Bar Value

### ISSUE THREAD

**Issue by AdamMikacich** [Semantic-Org/Semantic-UI#4811]
Hello. There seems to be an issue with setting a progress bar. Increment and decrement seem to work.

`$('.progress').progress('increment', 70);`

or

`$('.progress').progress('decrement', 30);`

Are working just fine. Personally I need to **set** this value.

`$('.progress').progress('set', 40);`

or anything like that does not work. I've also tried value instead of set. Please tell me if there is an issue with me or Semantic UI. I am on the latest version 2.2.6

**Comment by AdamMikacich** [comment]
By looking at the source code of Semantic UI I ended up making a make shift function to do this.

function setProgress(element, value) {
    $(element).attr("data-percent", value);
    $(element + ' .bar').css("width", value + "%");
}

I was still wondering if you could fix this. Thanks

**Comment by devrchancay** [comment]
I do not know if this solves your doubt, I use this way the progress bar.

```javascript
$('.progress').progress({
  percent: 22
});
```

**Comment by AdamMikacich** [comment]
Sorry devrchancay, that is just initiation. I need to constantly change this value.

**Comment by vinayakkulkarni** [comment]
http://semantic-ui.com/modules/progress.html#/usage

set percent(percent) | Sets current percent of progress to value. If using a total will convert from percent to estimated value.
------------ | -------------

?

**Comment by Javasamurai** [comment]
`$('.progress').progress('set progress', progress);`

**Comment by Banandrew** [comment]
Hi @AdamMikacich, is the issue still standing?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
