### ISSUE TITLE
[Transition] - FadeIn and Fadeout Not available

### ISSUE THREAD

**Issue by harishgilimi** [Semantic-Org/Semantic-UI#4813]
Addition to transition

1. I want fadeIn and fadeOut functionality in transitions

**Comment by fstanis** [comment]
Just use `fade in` and `fade out`.

`$('.something').transition('fade in');` works fine.

**Comment by vinayakkulkarni** [comment]
```javascript
$('#someid .someclass').click(function() {
  $('.area-which-you-want-transition').transition('fade in');
}
```

Pls read the documentation, it couldn't be more clearer 😛
