### ISSUE TITLE
onHide - return false not canceling the popup hide.

### ISSUE THREAD

**Issue by rajesh-ramakrishnan** [Semantic-Org/Semantic-UI#4819]
eg:
angular.element('.menu').popup({
      on: 'click',
      // scrollContext: '',
      hoverable: true,
      position: 'bottom left',
      closable: true,
      hideOnScroll: false,
      delay: {
        hide: 1000
      },
      onHide: function(ele) {
        return false; // This is not canceling the popup from hide
      }
    });

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
