### ISSUE TITLE
Compact labeled button left padding

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [Semantic-Org/Semantic-UI#4821]
Hello,

v: 2.2.2

current situation: _compact labeled_ buttons don't have left padding smaller than non-compact labeled button

suspected: _compact labeled_ button should have smaller left padding compared to _regular labeled_ button

since _compact_ button removes padding from all of the sides, it should also decrease the size of left padding in case of _labeled_ button. Currently the space between label and button text seems way too long.

Regards,
MP

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
