### ISSUE TITLE
Glitch - Accordion Grey Twitch

### ISSUE THREAD

**Issue by abubakir1997** [Semantic-Org/Semantic-UI#4825]
![screen shot 2016-12-10 at 6 33 48 pm](https://cloud.githubusercontent.com/assets/18533628/21076924/503259de-bf07-11e6-95b9-b864c3413a53.png)

When I click on an accordion the screen begin twitching this grey color like a glitch I have an image attached to illustrate what I am talking about. How could this be solved?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
