### ISSUE TITLE
When I set .ui.container's right margin to 300px, the left margin disappear

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4826]
The container's default left and right margins are the same and responsive on different screen sizes. But when I set the right margin of the container to 300px, or any number else, the left margin becomes zero,   or very small, not responsive anymore.
I want to put a 250px rail on the right, so I want to enlarge the right margin.
So can I set margin-right: 300px, and keep the margin-left still auto-responsive with the screen size? In order to keep left aligned with other container.

**Comment by Banandrew** [comment]
Hi @tarvos21, have you figured it out?

**Comment by tarvos21** [comment]
Hi, @Banandrew, I find there's no easy way to do that, defining the container's marin. At last, I set the `left: 827px`, or any number for the right rail to solve this, also add some media query, to make thinks looks right on different screens.

**Comment by Banandrew** [comment]
@tarvos21 You should be able to set the right margin easily, the SUI’s documentation does it as well. Did you use the rail correctly, putting it inside of the container? In any case, I’ll close it as solved, but if you want to keep talking about it, either answer here with your HTML structure, or find me on Gitter, maybe we’ll be able to do it properly.

**Comment by tarvos21** [comment]
@Banandrew, thanks, I just want to close it. It's a usage problem.
