### ISSUE TITLE
[Search] Custom HTTP_ACCEPT

### ISSUE THREAD

**Issue by AntoineDewaele** [Semantic-Org/Semantic-UI#4827]
I need to call a API in json:api format. So i need to accept 'application/vnd.api+json' in the HTTP_ACCEPT header. Is there a way to overload the header with a callback before the ajax request is sent ?

```coffee
  $('.ui.search')
    .search({
      type: 'recipe',
      apiSettings: {
        onRequest: (promise, xhr) ->
          xhr.setRequestHeader('HTTP_ACCEPT', 'application/vnd.api+json')
        url: '//staging-doeat.herokuapp.com/api/v1/recipes',
        onResponse: (response) ->
          console.log(response)
      },
  });
```

I would like to do something like this. But it doesn't work.

Thanks u for your responses.

**Comment by ardamose123** [comment]
The docs show there's a `beforeXHR` callback in the API settings (http://semantic-ui.com/behaviors/api.html#/settings).

So, in your example code, you can use `beforeXHR` instead of `onRequest` and remove the `promise` parameter. Haven't tried it, though.
