### ISSUE TITLE
Image List break header with long text

### ISSUE THREAD

**Issue by edipofederle** [Semantic-Org/Semantic-UI#4828]
Hi,

I am trying add a long text to a list, but it breaks the header, see:

![screenshot 2016-12-11 17 43 02](https://cloud.githubusercontent.com/assets/50778/21082826/a2497e46-bfca-11e6-862d-aa6798c41995.png)

This is a bug or there is a way to fix this ?

Thanks in advance

**Comment by IonutBajescu** [comment]
Hey,

That's odd, can you make a jsfiddle so we can play with the CSS?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
