### ISSUE TITLE
"ui multiple search selection dropdown" when lose focus, auto select item.

### ISSUE THREAD

**Issue by xiwc** [Semantic-Org/Semantic-UI#4832]
> reproduce here: http://semantic-ui.com/introduction/new.html#user-tagging

## DEMO
![2016-12-13_09-45-47](https://cloud.githubusercontent.com/assets/8816203/21124294/00f7226e-c119-11e6-9c57-0df856748cc0.gif)

**Comment by Mydoom** [comment]
Hello,

check this : https://github.com/Semantic-Org/Semantic-UI/issues/4535

It is already confirmed

**Comment by xiwc** [comment]
thks, got it
