### ISSUE TITLE
When I set all in theme.config to material, my search icon is wrong.

### ISSUE THREAD

**Issue by lbfreeze** [Semantic-Org/Semantic-UI#4834]

**Comment by lbfreeze** [comment]
In my html it is search icon , but in the chrome search icon is a 
Chinese character。

**Comment by Banandrew** [comment]
Hi @lbfreeze,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
