### ISSUE TITLE
[Progress] Add indeterminate state

### ISSUE THREAD

**Issue by kuy** [Semantic-Org/Semantic-UI#4840]
![indeterminate-progress-bar](https://cloud.githubusercontent.com/assets/151614/21307794/639e473e-c61a-11e6-9663-3c82a2857561.gif)

I have migrated from Material-UI and noticed that Progress component doesn't have "Indeterminate" state. Loading component has similar function but I can't put it by restriction of page layout.

**Comment by richardtallent** [comment]
You can get *close* using existing functionality. The trick is that `value` has to be <= 99% of `total`, otherwise the animation stops.

http://jsfiddle.net/richardtallent/efp8z6Ln/458/

**Comment by kuy** [comment]
Nice idea, thanks! It's better if we get explicit API for this.

**Comment by miguelcaravantes** [comment]
please reopen this request

**Comment by MrFojo** [comment]
Please add this functionality.

**Comment by lubber-de** [comment]
Prepared `indeterminate` states for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/735
See https://jsfiddle.net/nekc8v7m/8/
