### ISSUE TITLE
South Sudan is missing in Flag

### ISSUE THREAD

**Issue by neekey** [Semantic-Org/Semantic-UI#4842]
Hi, I am currently building a country select component, and I just found that the [Republic of South Sudan](https://en.wikipedia.org/wiki/South_Sudan) is not included in the flags.

![image](https://cloud.githubusercontent.com/assets/499870/21333930/9a7bf6f6-c6a7-11e6-958a-a0f6ae0a943e.png)

![image](https://cloud.githubusercontent.com/assets/499870/21333946/adae5318-c6a7-11e6-9275-bc6609edca3f.png)

**Comment by neekey** [comment]
Hi @Banandrew  any progress for this?

**Comment by jlukic** [comment]
If you can contribute a flag to the sprite.png file I will gladly add it.

**Comment by autohub7** [comment]
Do you have any update on this? I'm looking for South Sudan flag and Nagorno-Karabakh
