### ISSUE TITLE
[Form Custom Validation] Custom validation function need the submit action button

### ISSUE THREAD

**Issue by RicottaZhang** [Semantic-Org/Semantic-UI#4843]
I have a two submit button form, and each submit button requires a little different validations, could you please add a parameter for custom validation function to specific the action submit button, something like
$.fn.form.settings.rules.customValid = function(value, submit_button) {
  if (submit_button.name == 'save draft') {
    #save it anyway
    return true;
  } else {
    #valid the values here
    return valid;
  }
};

**Comment by Cyb3rWarri0r8** [comment]
This is a little unclear... Do you want to validate a form based on two different submit buttons? If that's what you are saying then just do validations with onClick handler's then submit when the conditions are met. Something like:
`$('#nextButton').click(function (e) {
                e.preventDefault();
                $('#addressForm').form('validate');
                if ( $('#addressForm').form('is valid') ) {
                    // Your code here...
                }
            });
$('#secondButton').click(function (e) {
                e.preventDefault();
                $('#addressForm').form('validate');
                if ( $('#addressForm').form('is valid') ) {
                    // Your code here...
                }
            });
`

**Comment by RicottaZhang** [comment]
@Cyb3rWarri0r8 Thanks, it works for me.
