### ISSUE TITLE
Fill a table cell with a progress bar ?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#4845]
Hi,

I try to use `progress` but it seems it doesent cover all the `height`, 

I made an example using `HTML5 progress` and `SUI progress`

![sans titre](https://cloud.githubusercontent.com/assets/2527234/21395448/d3039c40-c79c-11e6-9bfc-8244addd53e7.png)

**Comment by IonutBajescu** [comment]
Try using something like http://stackoverflow.com/questions/3215553/make-a-div-fill-an-entire-table-cell. 

Also, we encourage posting the usage questions on the Semantic UI forums or stackoverflow where it can get more attention than it'd get on the issue tracker.
