### ISSUE TITLE
Important: UI Grid broken in Safari

### ISSUE THREAD

**Issue by madela** [Semantic-Org/Semantic-UI#4847]
Latest version has broken many components on Safari. Many css rules started with -webkit has disappear from the css files. You can check it on: http://semantic-ui.com/collections/grid.html

**Comment by ljmelgui** [comment]
Semantic uses [autoprefixer](https://github.com/postcss/autoprefixer) plugin to parse CSS and add vendor prefixes to CSS rules. You can find supported browsers in [semantic's tasks.js file](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/tasks.js). Current value is:

    /* What Browsers to Prefix */
    prefix: {
      browsers: [
        'last 2 versions',
        '> 1%',
        'opera 12.1',
        'bb 10',
        'android 4'
      ]
    }

Autoprefixer uses [Browserslist](https://github.com/ai/browserslist) to specify browsers. Maybe you are using an old version of safari not supported.
You can use [http://browserl.ist/](http://browserl.ist/) to see what browser are really supported in the list.

**Comment by madela** [comment]
I'm using Safari 8.0.4

**Comment by ivantcholakov** [comment]
Semantic UI 2.2.6 says about browser support:

* Last 2 Versions FF, Chrome, Safari Mac
* IE 11+
* Android 4.4+, Chrome for Android 44+
* iOS Safari 7+
* Microsoft Edge 12 & 13

Accordingly I use this browser list for autoprefixer, it has been tested with Safari:

'> 1%',
'last 2 versions',
'Firefox ESR',
'Safari >= 7',
'iOS >= 7',
'ie >= 11',
'Edge >= 12',
'Android >= 4'
