### ISSUE TITLE
why the taiwan flag is not chinese flag?

### ISSUE THREAD

**Issue by miaoqiang123** [Semantic-Org/Semantic-UI#4849]
hereis this http://www.semantic-ui.cn/elements/flag.html
i.flag.tw part 
should`t be the the national flag of the People's Republic?

**Comment by philrykoff** [comment]
It seems that SUI is recognizing the Republic of China, Taiwan, as a sovereign nation. If you disagree, feel free to use the PRC flag for Taiwan, too... or rather not use it at all.

**Comment by ktmn** [comment]
Why would you need 2 classes to render the same flag?

**Comment by jlukic** [comment]
For the record, Taipei is one of my favorite cities <3
