### ISSUE TITLE
Dropdown mobile

### ISSUE THREAD

**Issue by RichTech** [Semantic-Org/Semantic-UI#4853]
Hello Semantic-UI team,

first: thanks for your beautiful work!

Issue: When you click on the dropdown icon on mobile devices nothing happens. The dropdown only shows/hides if you click on the dropdown directly and not on the icon.

**Comment by Cyb3rWarri0r8** [comment]
Make a fork of this fiddle and input your code so we can figure out what's wrong. http://jsfiddle.net/efp8z6Ln/

**Comment by RichTech** [comment]
Have updated

http://jsfiddle.net/efp8z6Ln/436/

**Comment by Banandrew** [comment]
@RichTech Hi, what device and platform were you using?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.

**Comment by Cyb3rWarri0r8** [comment]
I don't see what the problem is. I tested and could not reproduce. I used google chrome with the Nexus user-agent and it was responding to simulated touches.
