### ISSUE TITLE
Fixed sidebar messes up responsiveness of cards

### ISSUE THREAD

**Issue by Viliami** [Semantic-Org/Semantic-UI#4855]
Having cards within the pusher class of a sidebar will cause the cards to not be sized correctly.

Similar to problem here: http://stackoverflow.com/questions/40540970/sidebar-menu-messes-up-the-responsiveness-of-semantic-cards
![image](https://cloud.githubusercontent.com/assets/13442473/21477122/b9543b96-cba3-11e6-9b0c-0e6b61418cf4.png)
The cards are being pushed to the side and the overflow cut off.
Expected the cards to be resized to 3 cards per row (not cut off)

**Comment by Viliami** [comment]
Using the class container fixes the problem

**Comment by Viliami** [comment]
It still doesn't work, it's being cut off at the other side

**Comment by ivantcholakov** [comment]
I've faced a similar problem. If your work is urgent, you can try to avoid using the pusher at all, as I did. Login here http://iridadesign.com/starter-public-edition-4/www/admin/ and examine the implementation if you choose to use it.

**Comment by Banandrew** [comment]
Linking a test case here from the SO question: https://plnkr.co/edit/U7IuRq?p=preview

**Comment by Banandrew** [comment]
@Viliami can you please elaborate on how you used a sidebar? Was it a `push` variation?

**Comment by Banandrew** [comment]
Closing it as a usage question, because I think it’s an unintended use of the default sidebar rules. There’s another way of doing it via Flexbox, and the framework’s documentation does it similarly—please see [this JSFiddle](http://jsfiddle.net/Banandrew/bbosj0wg).
