### ISSUE TITLE
Try to define buttons backgroundImage to gradient, but failed

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4859]
`@coloredBakcgroundImage: none;`
`@primaryBackgroundImage: @coloredBackgroundImage;`
`@secondaryBackgroundImage: @coloredBakcgroundImage;`
`@positiveBackgroundImage: @coloredBackgroundImage;`

This is in the `button.variables`.
When I try to define:
`@primaryBackgroundImage: linear-gradient(lighten(@primaryColor, 30%), @primaryColor 60%, darken(@primaryColor, 40%));
`
It does nothing,
I have to change the `@coloredBackgroundImage` to change the button's background. But if I do that, all different buttons have the same backgroundImage.
What's the problem here? Can anyone help?

**Comment by Cyb3rWarri0r8** [comment]
What files are you declaring this in?

**Comment by tarvos21** [comment]
`src/themes/default/elements/button.variables`
Thanks for response!

I have found the problem, I need to write some `button.overrides` to redefine the buttons CSS, otherwise any definitions in the `button.variables` would not take effect.
