### ISSUE TITLE
Sub Header, upper case of 'i' letter in Turkish alphabet

### ISSUE THREAD

**Issue by kivancguckiran** [Semantic-Org/Semantic-UI#4861]
Hello,

First and foremost, thanks for this excellent framework.

I came across this issue a while ago. The sub header class, makes all the characters in the element uppercase as you are aware of. But, it does not know the locale i suppose.

English alphabet, lowercase 'i' -> uppercase 'I'
Turkish alphabet, lowercase 'i' -> uppercase 'İ'

So basically, what I've wanted to achieve was the sub header class should make the lowercase 'i' to uppercase 'İ' if I'm using the Turkish alphabet.

I don't know this is achievable or not, and this is a fiddle:

http://jsfiddle.net/g2rbc5a3/6/

Thanks!

**Comment by jlukic** [comment]
This appears to be an issue with `text-transform: uppercase;` not working with some characters. I'd recommend changing [`@subHeaderTextTransform`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/header.variables#L28) to `none` and using theming.

http://stackoverflow.com/questions/3777443/css-text-transform-not-working-properly-for-turkish-characters
