### ISSUE TITLE
Broken buttons at http://semantic-ui.com/introduction/getting-started.html

### ISSUE THREAD

**Issue by imaia** [Semantic-Org/Semantic-UI#4862]
Using firefox 50.1, there are a few buttons at http://semantic-ui.com/introduction/getting-started.html that do nothing when you click on them, like "mac, linux, windows" and "video, code"

**Comment by imaia** [comment]
Move issue to docs repository.

**Comment by jlukic** [comment]
It looks like there was a bad deploy with last build. I'll fix

**Comment by jlukic** [comment]
http://semantic-ui.com/introduction/getting-started.html 

Working again
