### ISSUE TITLE
[Step] - container should be resized respectively to steps

### ISSUE THREAD

**Issue by G07cha** [Semantic-Org/Semantic-UI#4867]
## Problem 

As you can see in attached screenshot steps will overflow own container in some cases

<img width="1280" alt="screen shot 2016-12-29 at 12 00 20" src="https://cloud.githubusercontent.com/assets/6943514/21541496/8ee45486-cdbf-11e6-9688-5d716adf59eb.png">

It located on [showcase page](http://semantic-ui.com/elements/step.html) so you can inspect it without jsfiddle.

## Details

Display resolution: 2560x1600
Page resolution: 1280x726
OS: macOS Sierra(10.12.2)
Browser: Google Chrome 55.0.2883.95 (64-bit)

**Comment by lubber-de** [comment]
This was fixed in Fomantic-UI 2.7.2 by https://github.com/Semantic-Org/Semantic-UI/issues/4867
See http://fomantic-ui.com/elements/step.html
