### ISSUE TITLE
[Divider] - vertical divider should be between elements

### ISSUE THREAD

**Issue by G07cha** [Semantic-Org/Semantic-UI#4868]
## Problem 

Seems like on the [showcase page](http://semantic-ui.com/elements/divider.html) vertical divider conflicting with `.ui.grid` styles and because of it, pinned to the left.

<img width="1276" alt="screen shot 2016-12-29 at 12 36 28" src="https://cloud.githubusercontent.com/assets/6943514/21542053/ee689f44-cdc3-11e6-9aca-6f9a088ea6dc.png">

## Details

Display resolution: 2560x1600
Page resolution: 1280x726
OS: macOS Sierra(10.12.2)
Browser: Google Chrome 55.0.2883.95 (64-bit)

**Comment by jlukic** [comment]
Known issue I'm afraid, #4342.

There's no workaround at the framework level for the the time being with the exception of one made by @Sarke: http://jsfiddle.net/xox5kt31/2/. 

[View Chrome Issue 633011](https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

https://github.com/w3c/csswg-drafts/issues/401
