### ISSUE TITLE
[Button] Loading with data-tooltip broken

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#4871]
You can't currently have a button with the state loading and with a data-tooltip.  The alternative of course is just to use a normal popup.  Here is a jsfiddle which shows both a normal loading button and one with the data-tooltip attribute set: http://jsfiddle.net/daneren2005/efp8z6Ln/429/

**Comment by jlukic** [comment]
This is a limitation of using css only tooltips. There is only `:before` and `:after` and `loading button` also uses those. 

If you use the javascript popup component it'll work.

**Comment by daneren2005** [comment]
Since this project is dead, here is some css in case anyone else wants to patch this themselves.  It is definitely not perfect.  I am probably overriding some stuff which doesn't really need to be overridden and possibly breaks other cases.  The animation track looks slightly off from what it should be.  But hey, it's close enough for me.

```
.ui.loading.loading.loading.loading.loading.loading.button[data-tooltip]:before {
	right: initial;
	bottom: initial;
	background: initial;
	font-size: initial;
	z-index: initial;
	box-shadow: initial;
	opacity: initial;
	transform: initial !important;
	transition: initial;
	transform-origin: initial;
	visibility: initial;
}
.ui.loading.loading.loading.loading.loading.loading.button[data-tooltip]:after {
	visibility: initial;
	bottom: initial;
	padding: initial;
	transform: initial;
	transform-origin: initial;
	background: initial;
}
```
