### ISSUE TITLE
[Icons] Varying widths causing list content to be misaligned

### ISSUE THREAD

**Issue by sbmelvin** [Semantic-Org/Semantic-UI#4872]
[JSFiddle](http://jsfiddle.net/efp8z6Ln/432/) demonstrating bug.

When using an icon within a list, the varying icon widths cause the content to be misaligned. I've found that overriding the following css rules to 0 fixes my alignment issues:
```
.ui.list .list>.item>i.icon, .ui.list>.item>i.icon {
    // padding-right: 0; fixes alignment issues
    padding-right: .28571429em;
}
```

![capture](https://cloud.githubusercontent.com/assets/172780/21579222/e7ca00e6-cf68-11e6-8cf6-1d444b9f6cc1.PNG)

**Comment by sbmelvin** [comment]
This issue is similar to #4780.

**Comment by jlukic** [comment]
Fixed in next release. `@lineHeightOffset` doesnt appear to be necessary in modern browsers.
