### ISSUE TITLE
Error message Bullet Broken on file loaded pages

### ISSUE THREAD

**Issue by ascheffe-umd** [Semantic-Org/Semantic-UI#4873]
From compiled semantic CSS 
https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.css

Is:
.ui.message .list:not(.ui) li:before {
  position: absolute;
  content: 'â€¢';
  left: -1em;
  height: 100%;
  vertical-align: baseline;
}

Encoding gets messed up when you load the page in chrome from the file system. The following fixes the issue. Using hex encoding of the bullet in the CSS.
.ui.message .list:not(.ui) li:before {
  position: absolute;
  content: "\2022";
  left: -1em;
  height: 100%;
  vertical-align: baseline;

![screen shot 2016-12-29 at 8 05 35 pm](https://cloud.githubusercontent.com/assets/3659508/21558036/3706e9ca-ce02-11e6-8f67-ea25044bac9b.png)

}

**Comment by Banandrew** [comment]
See #4124.

**Comment by 62696e617279** [comment]
@ascheffe-umd I realize this is an old post but thank you for posting your workaround!
The issue persists in Chrome and this solution works.

**Comment by mail2tarkeshwar** [comment]
We may try replacing the content from • to â€¢ for the class .ui.message .list:not(.ui) li:before in semantic.css file, to fix this issue.
