### ISSUE TITLE
Dropdown tab go to submit

### ISSUE THREAD

**Issue by yubitib** [Semantic-Org/Semantic-UI#4874]
while focus multiselect allowAdditions dropdown press tab key on computer it will focus next input element or button

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
