### ISSUE TITLE
[Popup] - With javascript not working when DOM is manipulated

### ISSUE THREAD

**Issue by budiadiono** [Semantic-Org/Semantic-UI#4875]
**Steps to Reproduce**
1. Go to official popup demo page: http://semantic-ui.com/modules/popup.html.
2. Try any example under **Javascript** section, everything should works fine.
3. On the example you've just try, now click **code** icon to view example source code.

**Expected**
The popup example should works fine after code example opened/closed

**Result**
The popup example is not working anymore after code example opened/closed

**Testcase**
I think I have similar issue with my VueJs project. I've made fiddle to illustrate the problem here: https://jsfiddle.net/budiadiono/3e2z3e7y/

**Comment by budiadiono** [comment]
I think this is false alarm. Giving `observeChanges: false` solves the problem.

**Comment by SwiTool** [comment]
`observesChanges: false` on visibility plugin does not make it work, could you reopen your issue and edit fiddle ?

**Comment by lukaspicha** [comment]
I have a still this problem. When i reloaded page by AJAX, popup doesn't work. I tried (true and false values), but no results. Can you help me please?
`$('a').popup({
          observeChanges: true
        });`

**Comment by budiadiono** [comment]
Here's the working fiddle: https://jsfiddle.net/5q15qbfz/

**Comment by lukaspicha** [comment]
I looked, but this is opening  popup after onClick event, and i try it on classic hover event, I set a property `on: hover` but still doesnt working.
My acutual code is:
`<i class="trash red icon" data-position="left center" data-content="Delete"></i>`
and in js file:
`$('i').popup({
          observeChanges: false,
          on: 'hover'
        });`
