### ISSUE TITLE
Dropdown right border smaller than input

### ISSUE THREAD

**Issue by HapLifeMan** [Semantic-Org/Semantic-UI#4878]
Hello, small fix: https://puu.sh/t9biF/9ca9b082aa.png :)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
