### ISSUE TITLE
Field is elevated in some specific circumstances.

### ISSUE THREAD

**Issue by romaninsh** [Semantic-Org/Semantic-UI#4881]
While testing my PHP UI integration I noticed that certain configuration makes field elevated when simply listed in-line.

<img width="1241" alt="screen shot 2017-01-04 at 13 45 54" src="https://cloud.githubusercontent.com/assets/453929/21644203/3ca466ce-d284-11e6-879f-b9799ef19dce.png">

The following conditions must be met for field to become sligthly elevated:

 - must have right label
 - must not have left label
 - must not have placeholder

I have narrowed down the case to this JS fiddle:

http://jsfiddle.net/xyyudbhe/1/

Unfortunately my CSS knowledge is too limited to narrow down the issue to a specific CSS rules.

**Comment by Banandrew** [comment]
Hi @romaninsh,

Using inputs in combination with `.ui.form` and `.fields > .field` seems to be fixing it. I’ll close it for now, as it seems to be a usage question to me.
