### ISSUE TITLE
Removing then adding prompt quickly in inline form causes message to not be visible

### ISSUE THREAD

**Issue by romaninsh** [Semantic-Org/Semantic-UI#4883]
If I have form with inline:true prompts then:

```
$('#atk_form').form('remove prompt', 'name', 'mesage');
$('#atk_form').form('add prompt', 'name', 'message');
```

causes prompt to be removed and then adds it again. Unfortunately due to animation adding prompt back does not make it appear.

It would be nice if previous animation would be cancelled before doing prompt fade-in.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
