### ISSUE TITLE
Semantic-UI has stopped developing?

### ISSUE THREAD

**Issue by zhangfisher** [Semantic-Org/Semantic-UI#4886]
Semantic-UI has stopped developing?
Are there any plans for the next release(semantic-ui 3)?

**Comment by philrykoff** [comment]
Well there are several matured pull requests (e.g. the calendar), which would greatly benefit semantic ui, yet, they this example has not been merged in more than 12 months. On the other side, semantic ui team members are active on these issues, so maybe such pull requests simply don't go in the right direction?

An official comment would be nice :-)

**Comment by AustinWinstanley** [comment]
Yea, this is what I'm wondering. There are a lot of pull requests, some going back months, and many with no responses. Is v3 a more concentrated effort among the core maintainers which is why they don't want to accept contributions?  That's understandable if the contributions don't match the vision of v3, but it would be nice to see an official response and a posted and up front message stating that so people know what to expect and whether to contribute. I can't think of any other reason for so many outstanding (and un-responded to) pull requests and issues.

**Comment by ivantcholakov** [comment]
From what I observed through the years I came to the conclusion that the "Donate" button is a project-killer. It creates wrong expectations and plans. For my public projects it is my conscious decision not to seek or accept donations, the support is through other commercial activities.

However there is no a universal recipe that I could suggest. No offense to anybody. Please think about variants for breaking the current status-quo.

**Comment by jokeronaldo** [comment]
May @jlukic (official developer) can answer you guys. He is the man who can definitely give us a direction.

**Comment by vinayakkulkarni** [comment]
Would absolutely love some input from Jack. 
Everyone's quite excited about the prospects of v3.x but when you see 900+ open issues, you tend to focus on solving those than working for v3. But that's just me. 😃

**Comment by philrykoff** [comment]
Is there already a roadmap for v3? We have many great ideas here as issues (some even as pull requests - 80 in total), maybe we need to make a long list and then prioritize?

**Comment by henriquearthur** [comment]
What we need most right now is a word from official developer @jlukic about how we gonna fix these 900+ open issues and what are the plans for v3.

**Comment by outluch** [comment]
Any news???? Is Semantic UI dead? If author is not interested in project, he could give it to somebody to maintain??

**Comment by jlukic** [comment]
I've been very busy lately, but my aspirations for SUI long term have not changed. I've outlined the next couple of minor releases in milestones, and you'll most likely see them pop out in the next few months.

I wish I had better news for those who are looking for specific fixes from the rest of the board but I'm sitting on 4000+ unread notifications, so I don't think its feasible for me to triage and address all of them promptly. 

I will return to working on SUI development full-time sometime in the near future (i'm currently splitting my time between NY & SF working with a SUI company), and you will see the same development you've seen before. 

I have larger aspirations for SUI which were not maintainable as a sole developer working off donations, so I'm trying to my best to secure a long-term future for the project and its larger aspirations to affect UI development on the web.

I've written some thoughts on SUI development recently over [on meteor forums](https://forums.meteor.com/t/state-of-css-in-meteor/33516/18?u=jlukic) that are somewhat relevant for those that are interested.

**Comment by vinayakkulkarni** [comment]
Glad to see Semantic-UI hasn't been dropped. I wish you best of the luck for getting enough funding which can in turn help you dedicate all your time to Semantic-UI!

Cheers 🍻

**Comment by richardtallent** [comment]
@jlukic, if there's anything we can do to crowd-source some of the issue-filing, documentation fixes, etc. so you can focus more on the code, please reach out.

**Comment by jlukic** [comment]
Yeah, anyone who would like to help moderate the SUI boards by tagging & closing issues. Email me at jack@semantic-ui.com.

**Comment by vinayakkulkarni** [comment]
Seems the question is answered, no need of keeping this open then :P

🍻

**Comment by ctilley83** [comment]
I't's nice to hear development will continue.  I love semantic ui. Hurry back!
