### ISSUE TITLE
[Accordion] Open level of accordion with hover

### ISSUE THREAD

**Issue by borjaMorilla** [Semantic-Org/Semantic-UI#4888]
Hi! I'm trying open a level of accordion when I'm over a title but I don't know how can do it because I don't know get the index of the level what i'm over it.

I was searching in documentation but i didn't see nothing... There is only the event `on:'click' `but there not is hover or something similar.

Thanks!

**Comment by websevendev** [comment]
```
$('.ui.accordion > .title:not(.active)').mouseenter(function(){
  $(this).trigger('click');
});
```

**Comment by borjaMorilla** [comment]
Thanks !!
