### ISSUE TITLE
[Form] revalidate option is being ignored on blur

### ISSUE THREAD

**Issue by gyuchang** [Semantic-Org/Semantic-UI#4889]
When a field has an error, the form will be revalidated on blur, even if `revalidate` option is set to `false`.

See [src/definitions/behaviors/form.js#L323](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/form.js#L323) vs  [src/definitions/behaviors/form.js#L341](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/form.js#L341)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by gyuchang** [comment]
JSFiddle: http://jsfiddle.net/0pu2pqy6/

I want the form validation happens only when the form is submitted. With the automatic revalidation on `change` events, the fields' state and the form's state can appear inconsistent since the field labels turned normal at the revalidation, but the form error message stays unchanged.

With `revalidate: false`, I can suppress the revalidation on `change` event, but it still happens on `blur` 

Steps to reproduce.

 1. While both fields are empty, click `Button`. This will cause the form level error messages to show up and change the fields into the error states.
 1. Click `Field 1` and enter a value. Then click `Field 2`. This will remove the `field 1`'s level error state - meaning the label and input field turn back to normal. If there's `onValid` handler, it will be fired.

What this means in effect it that the automatic revalidation cannot be turn off completely.

**Comment by Banandrew** [comment]
@gyuchang Your JSFiddle is empty.

**Comment by gyuchang** [comment]
Sorry, new JSFiddle: http://jsfiddle.net/1mpycce4/

(the previous comment is also updated)

**Comment by lubber-de** [comment]
This has been fixed in the community fork [Fomantic-UI](https://fomantic-ui.com) by https://github.com/fomantic/Fomantic-UI/pull/1809
See your adjusted jsfiddle here http://jsfiddle.net/lubber/g8n9c6kb/5/
