### ISSUE TITLE
Modal popup on button click

### ISSUE THREAD

**Issue by Noximity** [Semantic-Org/Semantic-UI#4890]
Hello I've recently been trying to get the modals working with Semantic-UI But I can't seem to get it to work how I want it to. I want to make it so that when a user clicks a specific menu on the sidebar a modal will pop up on the page where a user can input text. If anyone knows how to go about doing this please comment below! Thanks

```
        <a class="item">
          <i class="money icon"></i>
          Free Coins
        </a>
```

Thanks to anyone that can help!

**Comment by websevendev** [comment]
Add a unique ID or class to your item, create your modal and attach the events to it:

`$('.your.modal').modal('attach events', '.item');`
