### ISSUE TITLE
[Icon] Icon request: walking

### ISSUE THREAD

**Issue by lingxiaoyang** [Semantic-Org/Semantic-UI#4891]
Please see the next comment.

**Comment by lingxiaoyang** [comment]
Sorry, I accidentally hit the enter before completing this issue...

I would like to have a "walking" icon to be used for maps, like the one in Google Maps:

![image](https://cloud.githubusercontent.com/assets/8630726/21725475/991d7f66-d406-11e6-86b9-de2006697dfc.png)

I searched the icon doc of Semantic UI but didn't find a similar one.

**Comment by jokeronaldo** [comment]
Look at icons page: http://semantic-ui.com/elements/icon.html

If the icon you are looking for isn't there, you probably should work on a custom icon.

**Comment by lingxiaoyang** [comment]
@jokeronaldo Checked the 2.2 docs. In "Map" section I think there's nothing related:
![image](https://cloud.githubusercontent.com/assets/8630726/21780505/e4dd8b9c-d679-11e6-8576-5f1b200db313.png)

I tried to look at other categories for icons with a man, but they didn't really make sense of "walking" if used in parallel with, e.g., biking, bus, car, etc., or used alone:

![image](https://cloud.githubusercontent.com/assets/8630726/21780684/88c5b36a-d67a-11e6-8cbc-d4be0a650732.png)
![image](https://cloud.githubusercontent.com/assets/8630726/21780696/940cd6e0-d67a-11e6-82ff-f2c6d46320c9.png)
![image](https://cloud.githubusercontent.com/assets/8630726/21780727/b051de54-d67a-11e6-8a49-59350c24af77.png)

I would need help from other people as I don't know graphic design.

**Comment by richardtallent** [comment]
Semantic-UI uses Font Awesome's glyph library. Fort Awesome is currently working on a new version, so this would be an excellent time to voice your suggestion over there. Here's the ticket for a walking person icon:

https://github.com/FortAwesome/Font-Awesome/issues/844

**Comment by IonutBajescu** [comment]
As others have already mentioned, Semantic UI uses Font Awesome and that's probably the best place to ask for a new icon. Although I wouldn't get my hopes up, they get thousands of font requests (~3k open requests at the moment) and definitely can't do them all. 

So if you really want that font *right now* just use a custom font.

Closing this since there's nothing we can do on our end.

**Comment by lingxiaoyang** [comment]
Thank you!

**Comment by HunteRoi** [comment]
Hello there, @richardtallent @IonutBajescu @jokeronaldo @lingxiaoyang !

I am resurrecting this issue as FontAwesome released a walking icon a while ago and this is still not available on Semantic UI.
Here's the reference : https://fontawesome.com/icons/walking?style=solid

It would pretty much a great thing to have it rolled out soon! What do you think of it, guys? :smile:

**Comment by hammy2899** [comment]
@HunteRoi @lingxiaoyang The `walking` icon is apart of [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) as you can see here https://fomantic-ui.com/elements/icon.html
![image](https://user-images.githubusercontent.com/11588822/61301521-f44eeb80-a7db-11e9-849c-440631183a7f.png)

You could also use our CLI tool to generate them for yourself [create-fomantic-icons](https://github.com/fomantic/create-fomantic-icons) 🎉

**Comment by HunteRoi** [comment]
Yes but I am using [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React) components to box the icons in my app. I am thus not directly using Fomantic-UI.
