### ISSUE TITLE
When using custom "category" template - OnSelect callback is broken

### ISSUE THREAD

**Issue by chrme** [Semantic-Org/Semantic-UI#4893]
I'm trying to use a custom template for the category type, but OnSelect callback always returns false.
Here is example:
- with type 'category' - http://jsfiddle.net/jg8ghe3p/ works fine
- with type 'custom_category' (which is copy of 'category') - http://jsfiddle.net/aku1v8zy/ return false

Am i doing something wrong?

**Comment by Banandrew** [comment]
@chrme Hi, have you figured it out? I’ve just did a quick test on a project that was shipped recently—we used a custom template there as well—and `onSelect` worked as expected.

**Comment by chrme** [comment]
@Banandrew yes, i solve've the problem by patch the sources.
