### ISSUE TITLE
[Dorpdown] How get the vaules from Multi Selection

### ISSUE THREAD

**Issue by starock** [Semantic-Org/Semantic-UI#4894]
When choose multi  selections, how get the vaules of them?

Now just return the first one. Help, thx! :)

**Comment by lc-soft** [comment]
If your code is like that:

![qq 20170109104820](https://cloud.githubusercontent.com/assets/1730073/21756219/2503ff4c-d659-11e6-9e04-a420b5a05e23.png)

You can use `$('[name="skills"]').val()` to get values:

![qq 20170109105006](https://cloud.githubusercontent.com/assets/1730073/21756236/62e8f290-d659-11e6-9b86-d403d1d11791.png)

Or use `$('.your.element').dropdown('get value')` .
