### ISSUE TITLE
negativeColor, negativeTextColor definition cause gulp plumber error 'path' undefined

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4895]
It's quite strange problem, I am building a theme, in `mytheme/globals/site.variables`, when I write:

`negativeColor: #ff4136;`
`negativeTextColor: #fff;`

then `gulp build-css`, I will get the error 

`Plumber Typeerror, 'gulp-concat-css', can not ... property 'path' of undefined`. 

Then I write like this:

`negativeColor, negativeTextColor: #ff4136;`
`negativeTextColor: #fff;`

There is no error. I have no way to understand this problem.

positiveColor, warningColor are all OK.

**Comment by Banandrew** [comment]
Hi @tarvos21,

The correct syntax for variables in LESS is `@variableName`. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by tarvos21** [comment]
@Banandrew, thanks for your reply.
