### ISSUE TITLE
[Dropdown] Menu arrow has problem

### ISSUE THREAD

**Issue by lc-soft** [Semantic-Org/Semantic-UI#4896]
![qq 20170109104400](https://cloud.githubusercontent.com/assets/1730073/21756181/8d57bb98-d658-11e6-8b74-af58b78c6101.png)

**Comment by jlukic** [comment]
Confirmed when opening upward

**Comment by jlukic** [comment]
Fixed in `2.2.8`

**Comment by vinayakkulkarni** [comment]
Issue resolution officially committed : https://github.com/Semantic-Org/Semantic-UI/commit/9642bdaef8cf6258b1179410d3e04a3a23693d86 

Cheers! 🍻
