### ISSUE TITLE
jsDeliver CDN - old release of semantic ui 

### ISSUE THREAD

**Issue by adrianzailic** [Semantic-Org/Semantic-UI#4898]
On the recipes page of the documentation [http://semantic-ui.com/introduction/advanced-usage.html](http://semantic-ui.com/introduction/advanced-usage.html) under the CDN Releases section you will see a link pointing to the 2.2.7 release of the semantic ui but the latest one on the jsDeliver CDN is 2.2.6.

**Comment by sunnykgupta** [comment]
jsDelivr has a bot which automatically fetches the latest releases.
I've filed a separate issue there to report this error.
https://github.com/jsdelivr/jsdelivr/issues/15731

**Comment by vinayakkulkarni** [comment]
Seems it's fixed 😉
