### ISSUE TITLE
Icons appears only after resize windows

### ISSUE THREAD

**Issue by Nexmind** [Semantic-Org/Semantic-UI#4899]
Hi ! 

I'm using Semantic-UI with Angular 2. Each time i load a component with some icons, they dont appear directly. I need to refresh or resize the windows (in mobile size for example) and icons appear. After that, when i come back to full size is ok.

This problem is not present on all Browser. Only for Chrome and Safari. Work perfectly on Firefox and Opera.

First:
<img width="1022" alt="capture d ecran 2017-01-10 a 22 08 35" src="https://cloud.githubusercontent.com/assets/16007775/21826283/2d44d044-d787-11e6-9cd1-6b0ab212c0e3.png">

After refresh or resize windows:
<img width="1028" alt="capture d ecran 2017-01-10 a 22 08 48" src="https://cloud.githubusercontent.com/assets/16007775/21826284/2d480d36-d787-11e6-8fa6-0b455d4edc21.png">

**Comment by sunnykgupta** [comment]
Any fiddle with the issue replicated? Could help us get an idea of what exactly is going on.

**Comment by Nexmind** [comment]
It seems to be bugged when i put the icon in a h2 tag. The icon is right when i remove  the h2 tag

Working: ` <i class="circular user icon"></i>
        Données personnelles` 

<img width="1024" alt="capture d ecran 2017-01-14 a 14 39 44" src="https://cloud.githubusercontent.com/assets/16007775/21955252/3583a23e-da67-11e6-909b-c9ac8c815868.png">

Not working: `<h2 class="">
        <i class="circular user icon"></i>
        Données personnelles
    </h2>`

<img width="1034" alt="capture d ecran 2017-01-14 a 14 42 29" src="https://cloud.githubusercontent.com/assets/16007775/21955253/37cb74e0-da67-11e6-8dc8-4a66881739dc.png">

**Comment by Banandrew** [comment]
@Nexmind Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
