### ISSUE TITLE
How to enlarge the result box of Semantic Search Modules

### ISSUE THREAD

**Issue by stephenlam1** [Semantic-Org/Semantic-UI#4900]
Hello! It seems that I cannot stretch the suggested result list, please advise, thanks!
http://semantic-ui.com/modules/search.html#/usage

**Comment by Banandrew** [comment]
@stephenlam1 

Hello! Have you figured it out? If not, please elaborate on what you wanted to do, have I understood it correctly that you wanted to make the results container wider?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
