### ISSUE TITLE
[Dropdown] Mouse selection should lose its hover effect when a keyboard is being used, and vice versa.

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [Semantic-Org/Semantic-UI#4902]
I was adding a drop-down but was caught up with a problem.
There seem to be highlighting of two items when I use keyboard and mouse as well  for navigation.
It should remove selected class for an item once the navigation is through mouse.
And add selected class when one navigates through keys, implicitly removing mouse hover highlighting. From the current highlighted position.  

This is how it is
![This is how it is](https://cloud.githubusercontent.com/assets/20899846/21849851/ef14f644-d82d-11e6-9f5a-81fb0e3cfc4e.png)   

This is how it should be
![This is how it should be](https://cloud.githubusercontent.com/assets/20899846/21849957/59136bd4-d82e-11e6-89bb-5b6224ca08dd.png)

**Comment by Banandrew** [comment]
@Prabhakar-Poudel did you make those screenshots using a custom theme? I think it’s intended, because when you use the default theme the color of an element selected with keyboard is different from the color of an element selected with mouse. I’m fairly certain those are different variables in the framework’s source, I’ll dig deeper into it after you post an answer.

**Comment by Prabhakar-Poudel** [comment]
@Banandrew Yep the colors are obviously different than the default theme. But my point is when a user tries arrow keys, it is much better to hide the mouse pointer hover effect. And when he uses the mouse, it doesn't make sense to keep the keyboard selection active. Particularly in my case above if I allow mouse selection and keyboard selection together, and the color scheme has to be changed than the default as per the application requirements. I see two different selections one for mouse and one for keyboard. So if this is something that could be fixed it would be helpful, as for now I have allowed only mouse selection to suppress the confusion raised.

**Comment by Banandrew** [comment]
@Prabhakar-Poudel I see your point, and thank you for your time. I’ll tag it, maybe Jack will get to it someday, but it’s probably going to be a low priority enhancement for now—don’t expect it changed any time soon.
