### ISSUE TITLE
Dropdown on http://semantic-ui.com/ only lists "England" instead of UK, uses wrong flag

### ISSUE THREAD

**Issue by Borgol** [Semantic-Org/Semantic-UI#4905]
As stated in the title, the country selection dropdown menu on http://semantic-ui.com/ lists "England" instead of United Kingdom, and uses the UK flag for it instead of St. George's cross.
It doesn't include any of the other countries in the UK, so someone from Wales would be forced to choose "England," which may cause their eyeballs to explode with indignant rage.
The best course of action would be to change "England" to "United Kingdom."

**Comment by vinayakkulkarni** [comment]
Blame Brexit 🤣

**Comment by Morrolan** [comment]
I've already raised this as https://github.com/Semantic-Org/Semantic-UI/issues/4703.  Apparently the flag exists in the svg but no way to currently reference it.

**Comment by Banandrew** [comment]
See #4703. Thanks, @Morrolan!
