### ISSUE TITLE
[Dropdown] Search prevents dropdown from showing on click

### ISSUE THREAD

**Issue by jukestar** [Semantic-Org/Semantic-UI#4907]
If you have a dropdown with setting on: "click", adding class search to it prevents the dropdown from opening on click.

https://jsfiddle.net/dbr26njq/47/

**Comment by pranav-kural** [comment]
@jukestar it is suppose to work like that. Adding the search class to the drop down, turns the drop down to a search box, but values of drop down can still be accessed by clicking on the drop down icon. 

https://jsfiddle.net/2ujuymmo/

**Comment by jukestar** [comment]
@pranav-kural ok. Is there any way to make clicking on the search, to open the dropdown?

**Comment by dhvsandeep** [comment]
Try this 
`$('.ui.dropdown').on("click", function(){
  	$this = $(this).dropdown("show")
  })`

**Comment by pranav-kural** [comment]
@jukestar @dhvsandeep that code should be able to open the dropdown on click. But however, if you want it work like a normal dropdown, and close on the second (or alternative) click, you would do something like this:

    let x = 2;
    $('.ui.dropdown').on("click", function() {  $(this).dropdown((x % 2 === 0) ? "show" : "hide"); x++; });

That will also help in not affecting the normal working of any other drop down you might be using. (like the second one in the jsfiddle)

jsfiddle: https://jsfiddle.net/2ujuymmo/3/

**Comment by Banandrew** [comment]
@jukestar 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
