### ISSUE TITLE
UI modal question

### ISSUE THREAD

**Issue by xhh110** [Semantic-Org/Semantic-UI#4909]
![qq20170114-0](https://cloud.githubusercontent.com/assets/16145443/21951836/01fe4568-da49-11e6-89d5-e38159cc5bfa.png)
> Why is this happening? I've been testing on chrom, firfox, and so on

**Comment by pranav-kural** [comment]
@xhh110 please explain what problem are you having exactly, and also provide the code, or an extract from the code related to the problem or a link to a jsfiddle simulating the problem you're experiencing.

**Comment by vinayakkulkarni** [comment]
jsfiddle pls

**Comment by dhvsandeep** [comment]
Yes, there is a problem with Semantic modal, Try this, it works.
`$('#modalid').modal('setting', {observeChanges : true}).modal('show');`

**Comment by IonutBajescu** [comment]
@dhvsandeep's recommendation should do the job.

**Comment by xhh110** [comment]
I have been try it ... but  it not work!!!

![default](https://cloud.githubusercontent.com/assets/16145443/22175648/37b40634-e034-11e6-86ba-4d238897408e.png)

@IonutBajescu

**Comment by dhvsandeep** [comment]
@xhh110 try adding this line below that line in show_ui_modal
`$('#MODAL').modal('refresh');`

**Comment by Banandrew** [comment]
@xhh110 

Refreshing the modal should do it. It’s a common behavior when you use SUI in combination with a JavaScript framework. If refreshing won’t work, try pushing it to the event loop:
```JS
window.setTimeout(function() {
  $('#MODAL').modal('refresh')
}, 0)
```

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
