### ISSUE TITLE
[docs] the docs site use CPU non stop

### ISSUE THREAD

**Issue by ttv20** [Semantic-Org/Semantic-UI#4911]
To understand the bug just go to [http://semantic-ui.com/collections/form.html](url) in chrome, click Shift+Ctrl (chrome task manager) and wait.
On my computer the tab take 5~10 % of cpu all the time...
I try also with incognito mode (without extension)

**Comment by Banandrew** [comment]
I think it depends on a specific hardware, browser setup, and has little to do with the framework or its website; for instance, it’s a steady 0 on my machine. I’ll close this for now as something temporarily irrelevant to the development of the framework.

**Comment by ttv20** [comment]
I checked this  again
Its seen that its only when I on the tab, so it's probably GPU problem...

**Comment by doublemarked** [comment]
This happens to me frequently also, only in Chrome. In Firefox it's fine. Completely strange.
