### ISSUE TITLE
[Dropdown] onChange fires every value when setting or clearing values of a multiple selection dropdown

### ISSUE THREAD

**Issue by jukestar** [Semantic-Org/Semantic-UI#4913]
When setting values with "set selected/exactly" or clearing values with "clear", onChange gets triggered for each value that gets added/removed.

https://jsfiddle.net/dbr26njq/48/

1. Open dev tools, and watch the console
2. Click button "Set Values".
3. Click button "Clear Values".
4. Look at the console.log statements

Expected:
I would expect that setting and clearing multiple values only would trigger one onChange.

**Comment by jjylha** [comment]
Can you please re-open this. Not the same thing as disabling onChange all together (https://github.com/Semantic-Org/Semantic-UI/issues/5212)

There should be a option to trigger onChange only once for multiple values with "set selected/exactly", "clear" etc.

Or has anybody managed to find a workaround for this?
