### ISSUE TITLE
[Dropdown][IE11-only] “Search In-Menu” automatically closes after being opened for the second time

### ISSUE THREAD

**Issue by lc-soft** [Semantic-Org/Semantic-UI#4915]
**Reproduction**
Use IE11 browser to open http://semantic-ui.com/modules/dropdown.html#search-in-menu, click `Filter Posts` button.

**Screenshot**
![dropdown](https://cloud.githubusercontent.com/assets/1730073/21978777/00425e42-dc17-11e6-8a45-8449849fab79.gif)

**Browser**
Internet Explorer 11 (11.713.10586.0)

**Comment by Banandrew** [comment]
See #4237.
