### ISSUE TITLE
modal does not work in semantic ui

### ISSUE THREAD

**Issue by mohsen158** [Semantic-Org/Semantic-UI#4916]
i want to use semantic ui and modal of that
but i cant use this perfectly and it doesn't work
i include jquery correctly and semantic js is same
when my fn call modal does not show in page 

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src="{{ asset('semantic/dist/semantic.min.js') }}"></script>

    <link rel="stylesheet" type="text/css" href="{{ asset('semantic/dist/semantic.min.css') }}">
    <title>Laravel Quickstart - Intermediate</title>

    <script>
        function fn() {
            $('.ui.modal')
                    .modal()
            ;
        }
    </script>

    </head>
    <body>
    <div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
        Modal Title
    </div>
    <div class="image content">
        <div class="image">
            An image can appear on left or an icon
        </div>
        <div class="description">
            A description can appear on the right
        </div>
    </div>
    <div class="actions">
        <div class="ui button">Cancel</div>
        <div class="ui button">OK</div>
    </div>
    </div>
    <button onclick="fn()">sdfsdfsdfsdf</button>
    <div class="ui bottom attached segment">
    </div>
    <div class="ui container">
    @yield('content')
     </div>
        </body>
       </html>

if i use js of bootstrap the modal is show but why?
and i want to use semantic not bootstrap

**Comment by Darkesthour** [comment]
Just use some behavior from http://semantic-ui.com/modules/modal.html#/usage (see Behavior section)
If you look at the code, you'll see that calling `modal()` without arguments just initialize modal, but it doesn't apply any action on it (ex. show, hide and etc.)
