### ISSUE TITLE
Stop mentioning Project Talk in *md files.

### ISSUE THREAD

**Issue by fredkrudger** [Semantic-Org/Semantic-UI#4917]
There are two images in the README.md that are not seen, so you can upload them again

**Comment by eronaeon** [comment]
ghg

**Comment by eronaeon** [comment]
ggggggggggggggggggggggggg

**Comment by IonutBajescu** [comment]
Which images would that be?

**Comment by fredkrudger** [comment]
I guess it's the markdown

[http://prnt.sc/dy90db](url)

**Comment by IonutBajescu** [comment]
Oh, that'd be http://projecttalk.io. They're down for some unknown some reason, it's better to wait before removing their badge from the readme, although we're not really using the projecttalk forum anymore.

**Comment by fredkrudger** [comment]
Ok, true, it's better to wait then.

**Comment by Banandrew** [comment]
I’ve just talked with [Manuel Kallenbach](https://github.com/manukall), the creator of Project Talk, and he said it’s dead. I’ll submit a PR next week to resolve the issue.
