### ISSUE TITLE
[Dropdown] - Broken examples

### ISSUE THREAD

**Issue by imaia** [Semantic-Org/Semantic-UI#4918]
**Steps to Reproduce**
1. Open http://semantic-ui.com/modules/dropdown.html#/usage (tested with ff)

**Expected**
SUI widgets

**Result**
Plain select widgets

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by IonutBajescu** [comment]
I can't reproduce.

![image](https://cloud.githubusercontent.com/assets/5365516/22159111/624dfa06-df37-11e6-9d90-a051bb109469.png)

**Comment by imaia** [comment]
![broken_dd](https://cloud.githubusercontent.com/assets/14771411/22160449/44eaed88-df24-11e6-9268-3632cdd9bccb.png)

In my FF, it renders like that.

**Comment by IonutBajescu** [comment]
Can you please open the firefox console and check if there's any javascript error there?

**Comment by ciajulius** [comment]
There's a tooltip saying "Run Code", click it.

You took a screenshot of only one dropdown, and that dropdown is not styled by semantic automatically, so I guess that click will solve this problem

**Comment by imaia** [comment]
Ahhhhh, now it works. It was not crystal to me that "run code" would actually initialize the widget.
