### ISSUE TITLE
[Dropdown] - Document how to load initial value from remote

### ISSUE THREAD

**Issue by imaia** [Semantic-Org/Semantic-UI#4919]
Please, document at http://semantic-ui.com/modules/dropdown.html how to initialize/update a dropdown widget from remote. Docs are not clear about this.

**Comment by Cyb3rWarri0r8** [comment]
[http://semantic-ui.com/modules/dropdown.html#remote-content](http://semantic-ui.com/modules/dropdown.html#remote-content)

That is documentation on remote content. There are a few different ways to get remote content into the dropdown. You can either use the semantic API or get the data yourself and then construct the elements and push it to the dropdown.

**Comment by imaia** [comment]
What I mean is that the "semantic API" only works for search widgets. If you want to initialize it with remote content, you have to do it yourself. Docs are misleading on this particular matter.

**Comment by Cyb3rWarri0r8** [comment]
I see. Then the only way to do that without using the search variant is to get the data and build the html objects then inject them. I wouldn't so much as say they are misleading as they don't specify that you can only use them with search dropdowns. 
@jlukic Am I wrong in saying that remote content only works on search/input dropdowns? I haven't tried any other than the actual search api

**Comment by Banandrew** [comment]
@imaia 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
