### ISSUE TITLE
Reset Dropdown to Initial State

### ISSUE THREAD

**Issue by narayanpai** [Semantic-Org/Semantic-UI#492]
I'm using dropdown as per the spec. I need to reset my dropdown to its initial state.. 'Select Age' at some point, after the user has changed its value by selecting the items in the dropdown.

For, If the user has selected first option '20-30' and then after form submit How could I reset the dropdown to its initial value of 'Select Age'

```
<div class="ui dropdown">
  <div class="text">Select Age</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item" data-value="20-30">20-30</div>
    <div class="item" data-value="30-50">30-50</div>
  </div>
```

**Comment by ctilley83** [comment]
@oniisaki I honest to god don't think they've fixed this yet

**Comment by viicviicviic** [comment]
@ctilley83 thinking the same. When you got the "response" from a confirm dialog, the 'restore defaults' dosen't work pretty well.

**Comment by faribauc** [comment]
Confirmed not fixed in 2.2.2

**Comment by ShukriChiu** [comment]
yeah, I need to clear all the options and use apiSetting again to get new options

**Comment by Eromonsele** [comment]
@ShukriChiu Have you found a solution to this yet?
