### ISSUE TITLE
fs.js error 

### ISSUE THREAD

**Issue by lakhansamani** [Semantic-Org/Semantic-UI#4920]
Currently in am using Semantic UI version 2.2.1

Facing following issue

```
Uncaught TypeError: b is not a function
    at fs.js:83
```

**Comment by vinayakkulkarni** [comment]
Could you post a fiddle?

**Comment by Banandrew** [comment]
@lakhansamani 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
