### ISSUE TITLE
[dropdown] dropdown with compact doesn't resize on content change 

### ISSUE THREAD

**Issue by imaia** [Semantic-Org/Semantic-UI#4921]
If you create a empty dropdown (using select) with the compact class then add elements (options) to it, the dropdown element won't adjust the width. Should it? Should it through some action?

**Comment by vinayakkulkarni** [comment]
Can you please post a fiddle?

Thanks 🙇

**Comment by imaia** [comment]
There you go https://jsfiddle.net/gt0f7syb/

**Comment by dhvsandeep** [comment]
Compact class dropdown uses selected element's width, so you can do this by three ways

1) Use a placeholder text default by adding while creating select element itself
`<option value="">Gender</option>`
so it uses this placeholder's width.

2) First add all the options you want and then initialize dropdown.

3) Dynamically add your options and use set text and set value calls to update the option list.

**Comment by imaia** [comment]
1. works alright!
2. works alright!
3. "set value" did not work: https://jsfiddle.net/hn1uqfbr/

**Comment by dhvsandeep** [comment]
`$('select').dropdown('set text', "Male")`
`$('select').dropdown('set value', "1")`

**Comment by imaia** [comment]
Now it works! https://jsfiddle.net/hn1uqfbr/1/
Thanks @dhvsandeep To be fair, this last example you wrote would do quite nicely in the official docs.
