### ISSUE TITLE
How to show ribben label and scoll bar at the same time in the table?

### ISSUE THREAD

**Issue by wztscau** [Semantic-Org/Semantic-UI#4924]
When I set table'wrapper(div) to overflow=auto, and the ribbon label:after is hidden.
Such as 
`
             <div style="height:100px;overflow:auto;width:100px;margin: 0 auto">
                <table class="ui celled table">
                  <tr><td><div class="ui ribbon label">xxx</div></td></tr>
                  <tr><td><div class="ui ribbon label">xxx</div></td></tr>
                  <tr><td><div class="ui ribbon label">xxx</div></td></tr>
                </table>
             </div>
`
But when I delete the "overflow", I can see the whole label.
Can someone solve this problem

**Comment by Darkesthour** [comment]
Hello. Just add `padding-left: 12px` into your wrapper. And it will be a good idea to add `box-sizing: content-box;` to the wrapper as well

**Comment by wztscau** [comment]
Thanks a lot. It's done.
