### ISSUE TITLE
Hold on dropdown and scroll browser doesn't work on mobile!

### ISSUE THREAD

**Issue by erdemcam** [Semantic-Org/Semantic-UI#4926]
If you push and hold on dropdown on mobile than you can't scroll mobile browser because if you push on dropdown you see right away all options of dropdown.

**Comment by Banandrew** [comment]
@erdemcam Hi, could you please provide a test case? You can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
