### ISSUE TITLE
Search Modules: Create html element inside search result

### ISSUE THREAD

**Issue by agusmakmun** [Semantic-Org/Semantic-UI#4930]
Previously I used type `category` for my search... I want to inject a simply html to the result such as image below, what I should be do here...

![screenshot-127 0 0 1 8000 2017-01-20 22-51-43](https://cloud.githubusercontent.com/assets/7134451/22156335/6ae6f0cc-df65-11e6-9a49-a7a378720470.png)

```js
$.fn.api.settings.api = {
  'search': '/api/search/json/?q={query}'
};

$('.ui.search.quick-search').search({
  type          : 'category',
  minCharacters : 1,
  apiSettings   : {
    action: 'search',
    onResultsAdd: function(html) {
      // i can't inject here..
    },
    onResponse: function(searchApiResponse) {
      var response = {
        results : {}
      };
      // translate `searchApiResponse` response to work with search
      var numbThreads = 0, numbUsers = 0;
      $.each(searchApiResponse.items, function(index, item) {
        var
          model = item.model || 'Unknown',
          maxResults = 8,
          maxItems = maxResults/2
        ;
        if(index >= maxResults) {
          return false;
        }
        // create new model category
        if(response.results[model] === undefined) {
          response.results[model] = {
            name    : model,
            results : []
          };
        }
        if(item.model === 'Threads') {
          if (numbThreads < maxItems) {
            response.results[model].results.push({
              title: item.title,
              description: item.description,
              url: item.url
            });
          }
          numbThreads++;
        }else if (item.model === 'Users') {
          if (numbUsers < maxItems) {
            response.results[model].results.push({
              title: item.username,
              description: item.username,
              url: item.profile_url,
              image: item.gravatar_url,
              price: item.total_threads
            });
          }
          numbUsers++;
        }
      });

      selector = $(document).find('.ui.search.quick-search');
      injector = '<div class="ui divider"></div>'+
                 '<button class="ui red button">'+
                    'Show more options...'+
                 '</button>';
      selector.find('.results').append(injector);
      
      console.log(response); // return Object such as image below..
      return response;
    }
  }
});// EOF
```

![screenshot from 2017-01-20 23-12-33](https://cloud.githubusercontent.com/assets/7134451/22168704/05a049c0-dfa1-11e6-89c9-cb8280d911f5.png)

> I also has a problem to **_marked_** results by query. For example:

* Query = `text marked as bold`
* Results:
    1. Collaboratively extend fully tested networks for 2.0
    2. Proactively **text marked as bold** customer directed solutions via multidisciplinary.
    3. Continually lorem ipsum matrix excellent communities vis-a-vis team driven

**Comment by Cyb3rWarri0r8** [comment]
I believe your injector is fine to use but I always  push the elements to an array then join them.. not that it should make a difference.
Is it just not showing up on the menu? Your code looks fine.. only thing I could suggest is making the find function a little more narrow to maybe the `.ui.search.quick-search` containing `div`

**Comment by agusmakmun** [comment]
previously, a few days ago I am curious about this argument below at http://semantic-ui.com/modules/search.html#server-responses, but **_no demo_** on the documentation...

```
// optional action below results
  "action": {
    "url": '/path/to/results',
    "text": "View all 202 results"
  }
```

also the **fields** at **settings**: http://semantic-ui.com/modules/search.html#/settings

```
  action          : 'action',      // "view more" object name
  actionText      : 'text',        // "view more" text
  actionURL       : 'url'          // "view more" url
}
```

and then I look at the source of `components/search.js`, I found this at https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/search.js#L1236-L1238

```js
if(response[fields.action]) {
  html += ''
  + '<a href="' + response[fields.action][fields.actionURL] + '" class="action">'
  +   response[fields.action][fields.actionText]
  + '</a>';
}
return html;
```

This why I just added the action argument at the response and it worked well..

```
onResponse: function(searchApiResponse) {
    var response = {
      results : {},
      action  : searchApiResponse.action // dict action
    };
    ...
```

Here is my fiddle: https://jsfiddle.net/agaust/5854gae9/1/

--------------

> Unresolved is how to **_marked_** results by query?

**Comment by Cyb3rWarri0r8** [comment]
Yes, the search is something I also had a bit of a problem with in the beginning. The documentation is a bit benign but I found that it has to do with using the semantic api here [http://semantic-ui.com/behaviors/api.html](http://semantic-ui.com/behaviors/api.html). 
It appears that you have it all working right, is there something that I'm missing that your having trouble with? 
> How about mark text results by query?
Do you want them to highlight certain characters that match the query?

**Comment by agusmakmun** [comment]
hello @Cyb3rWarri0r8, yup like you are talking about, how I can do it?
an example like this forum: https://forums.meteor.com

![highlight](https://cloud.githubusercontent.com/assets/7134451/22277034/db14f0fa-e2ea-11e6-8ce7-679207b74ab7.png)

**Comment by Cyb3rWarri0r8** [comment]
Ah yes, for that I'd suggest using regex to match the text against whatever the user is inputting, then use `<b>` around it or change the style with CSS

**Comment by agusmakmun** [comment]
hello @Cyb3rWarri0r8, thank you for your suggestion.. 
but, can you give me an example whereis I should do it?

**Comment by Cyb3rWarri0r8** [comment]
```javascript
function search() {
            var queryString = $( "input#instantsearch" ).val();
            if ( queryString != '' ) {
                $.ajax( {
                            type: "POST",
                            url: "/newsearch.php",
                            data: { query: queryString },
                            cache: false,
                            success: function ( html ) {
                                $( "#dropdown" ).html( html );

                                $( '#instantsearch' ).focusout( function (e) {
                                    $( '#results' ).fadeOut(800);
                                } );

                                $( '#instantsearch' ).focusin( function () {
                                    $( '#results' ).fadeIn();
                                } );
                            }
                        } );
            }
            else {
                $( "#results" ).fadeOut();
                $('#dropdown').empty();
//                $('#instantsearch').val(null);
            }
            return false;
        }

        $( "input#instantsearch" )
                .bind( "keyup", function ( e ) {
                    $( this ).data( 'timer', setTimeout( search, 100 ) );
                    if ( $( "input#instantsearch" ).val() != '' ) {
                        $( "#dropdown" ).show();
                        if ( e.which == 13 ) {
                            window.location = "/search.php?search_term=" + $( "input#instantsearch" ).val();
                        }
                    }
                });
```
That is an idea of what to do, we have an instant search on our site but without highlighting. To add highlighting it would probably be something along the lines of this inside the ajax return on the search function above

```javascript
var splitString = queryString.split(' ');
$.each(splitString, function(index) {
    var matches = html.match(/splitString[index]/);
    $.each(matches, function(i) {
        matches[i] = '<b>' + matches[i] + '</b>';
// this is where you'd have to figure out how to get the matched text wrapped with the highlighting into the response again...
    });
});
```

**Comment by agusmakmun** [comment]
@Cyb3rWarri0r8 thank you so much for your explanation... but I'm not seen your code is combined with semantic ui? I mean, where I should put that function? an example; inside function of `onResultsAdd` or `onSearchQuery` or else...

**Comment by Cyb3rWarri0r8** [comment]
You don't use a callback. You'll probably have to figure that out. This was custom code we made for a site that is kinda half implementing semantic. (trying to bring the company site out of the stone ages :stuck_out_tongue_closed_eyes: ) Your going to want to perform the highlighting before the html is stuck on the results dropdown if possible. Now that I think about it you probably want to search the results since your using the api. I'd guess onResultsAdd is where you want to crawl the elements and then using the regex match the inner text then insert highlighting tags around using `$.wrap()` .

**Comment by agusmakmun** [comment]
finally... someone helped me to handle this problem at the backend, and of course using regex. I never think it before...

http://stackoverflow.com/questions/41985525/semantic-ui-search-api-how-i-can-highlight-certain-characters-that-match-the#comment71148868_41985525

> I think on `item.description` you should replace with a regex and wrap it with <strong></strong> usually I do it from the backend, but in this case this is the only way I think. – peterpeterson.

currently I doing this with django, and here is my backend script...

```python
import re

def highlight_query(query, text):
    """
    return injected the html element
    to the `text` that matched by query.
    """
    return re.sub(r'(%s)+' % query,
        '<span class="marked-query">%s</span>' % query, text)
```

Thank you so much @Cyb3rWarri0r8 and peterpeterson

**Comment by Cyb3rWarri0r8** [comment]
No problem!

@jlukic this can be closed

**Comment by Banandrew** [comment]
Closing as requested.
