### ISSUE TITLE
Multiple-selection dropdown behavior problems when using Webpack 2, VueJS 2 and Babel

### ISSUE THREAD

**Issue by richardsession** [Semantic-Org/Semantic-UI#4932]
I created a VueJS component in ES6 using 

- Webpack 2
- VueJS 2.0.1
- Semantic-UI 2.2.3 CSS 
- semantic-ui-api, semantic-ui-dropdown, and semantic-ui-transition versions 2.2.3 installed through NPM

When I added the component to my page, it renders correctly but once I begin typing the name of a new tag, it duplicates the text I am typing in a div with a class of "sizer". 

When I use the API module to generate a list of options for the multi-select, I can select an option but once it has been selected, the dropdown options do not disappear.  Also, when I begin to select another tag, the dropdown list is still visible and shows both selected tags in the text field and in the dropdown of options.

As a note, I have used the same configuration just using the regular dropdown settings (without multiselect options) and everything renders and functions properly.  Once I have added options for multiselect, things start acting weird.

Are there any known issues when using Babel through Webpack that would cause the behavior of a multiselection dropdown to behave differently than when it created normally within a page using script tags?

Here is the declaration I am using to initialize the multiselect dropdown:
`$('#' + this.id).dropdown({
                allowAdditions: true,
                maxSelections: 15,
                placeholder: 'Select Tags',
                apiSettings: {
                    url: '/tags/all/{query}'
                }
            })`

My .babelrc file is as follows:
`{
"presets": ["es2015", "stage-2"],
"plugins": ["transform-runtime"],
"comments": false
}`

Here is my webpack.config.js file:
`var path 			  = require('path'),
	webpack           = require('webpack'),
	jquery            = require('jquery'),
	precss            = require('precss'),
	autoprefixer      = require('autoprefixer')
	// ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
	context: __dirname + '/resources/assets',

	entry: './js/app',

	output: {
		path: path.resolve(__dirname, './public/dist/js'),
		publicPath: '/dist/',
		filename: 'bundle.js',
		chunkFilename: '[name.js]',
		sourceMapFilename: '[file].map'
	},

	resolve: {
		extensions: ['', '.vue', '.js', 'es6', '.css', '.less']
	},

	resolveLoader: {
		root: path.join(__dirname, 'node_modules')
	},

	module: {
		// only lint local *.vue and *.js files
	    preLoaders: [
	    	{
		    	test: /\.vue$/,
		        loader: 'eslint',
		        exclude: /node_modules/
	    	},
	    	{
		    	test: /\.js$/,
		        loader: 'eslint',
		        exclude: /node_modules/
	    	}
	    ],

		loaders: [
			{
				test: /\.js$/,
				loaders: ['babel', 'eslint'],
				exclude: /(node_modules|gulpfile\.js)/
			},
			{
				test: /\.vue$/,
				loaders: ['vue']
			},
			{
				test: /\.json$/,
				loader: 'json',
				exclude: /(node_modules)/
			},
			{
				test: /\.html$/,
				loader: 'raw',
				exclude: /(node_modules)/
			},
			{
				test: /\.css$/,
				loaders: ['style', 'css', 'postcss'],
				exclude: /(node_modules)/
			},
			{
				test: /\.less$/,
				loaders: ['style', 'css', 'postcss', 'less'],
				exclude: /(node_modules)/
			},
			/*{
				test: /\.less$/,
				loader: ExtractTextPlugin.extract(['css', 'postcss', 'less'])
			},*/
			{ 
				test: /\.(png|jpg|gif)$/, 
				loader: ['url'],
				query: {
					limit: [8192], // inline base64 URLs for <=8k images, direct URLs for the rest
					name: '[name].[ext]?[hash]'
				},
				exclude: /(node_modules)/
			},
			{
				test: /\.(eot|svg|ttf|otf|woff|woff2)$/,
                loader: ['url'],
                query: {
                	limit: 65000,
                	name: '../fonts/[name].[ext]'
                },
                exclude: /(node_modules)/
			}
		]
	},

	postcss: function () {
        return [
        	precss, 
        	autoprefixer
        ];
    },

    vue: {
		loaders: {
	    	// css: ExtractTextPlugin.extract("css"),
	      	// less: ExtractTextPlugin.extract("css!less")	// you can also include <style lang="less"> or other langauges
	    }
	},

	plugins: [
  		new webpack.optimize.CommonsChunkPlugin('common.js'),	// Creates a shared bundle file for common code in multiple entry points (helps with caching too)
  		new webpack.optimize.DedupePlugin(),
  		new webpack.ProvidePlugin({
		    $: "jquery",
		    jQuery: "jquery",
		    'window.jQuery': 'jquery'
		}),
  		// new ExtractTextPlugin('app', path.resolve('./public/dist/css/app.css'), {allChunks: false})
	],

	debug: true,
	devtool: '#eval-source-map'
}

if(process.env.NODE_ENV === 'production') {
	module.exports.devtool = '#source-map';
	module.exports.plugins = [
		// short-circuits all Vue.js warning code
		new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: '"production"'
			}
		}),

		new webpack.optimize.UglifyJsPlugin({
			compress: {
				warnings: false
			}
		}),

		// optimize module ids by occurence count
		new webpack.optimize.OccurrenceOrderPlugin()
	]
}`

**Comment by SwiTool** [comment]
How did you solve your problem ?

**Comment by douglasg14b** [comment]
Seriously, this is like the forum post where the person replies `nvm, solved it`.

What did you have to do?
