### ISSUE TITLE
Vertical Divider

### ISSUE THREAD

**Issue by Brodcouille** [Semantic-Org/Semantic-UI#4934]
![issue](https://cloud.githubusercontent.com/assets/5373281/22199088/b865672a-e159-11e6-8113-b75d8337aebd.png)
It seems that on Google Chrome the vertical divider has a problem (check the image) ! On Firefox it works well !

**Comment by dhvsandeep** [comment]
Can you post working fiddle, so that we can tweak little things.

**Comment by IonutBajescu** [comment]
I'm afraid this is a known issue :(

Please continue the discussion in #4342.
