### ISSUE TITLE
Submenu reopens on click

### ISSUE THREAD

**Issue by Stefanama** [Semantic-Org/Semantic-UI#4935]
Hello everyone, I'm working with menus and found this unusual behavior. Clicking on a submenu item will trigger the action 'hide' of the menu but then it immediately reopens.
![custom](https://cloud.githubusercontent.com/assets/7548528/22208650/e59be58c-e183-11e6-84c7-cc492e4fab0b.gif)

Anyone ever seen this happen? 
Thanks a lot

**Comment by dhvsandeep** [comment]
No, I haven't seen this. It'd be great if you post a fiddle here.

And check if you add any manual event handlers to that component.

**Comment by Stefanama** [comment]
It doesn't happen with all the submenus in my app. Still trying to figure out what are the differences with the others, but I've been having other more important issues, so I'll have to come back later on this one. Will update when I'll know more. 

Thanks

**Comment by Banandrew** [comment]
@Stefanama Hi, have you figured it out?

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
