### ISSUE TITLE
[Form] [Input] Add 100% opacity to Placeholder text color in Firefox

### ISSUE THREAD

**Issue by mdhtr** [Semantic-Org/Semantic-UI#4937]
["Firefox applies a default style of opacity: 0.54 to placeholder text."](https://developer.mozilla.org/en/docs/Web/CSS/::-moz-placeholder)

It would be nice to have the same opacity in Firefox too as in the other browsers. (opacity 1)

Demonstration: open http://semantic-ui.com/collections/form.html in Firefox (tested in 49.0.2) and look for the difference in input fields vs dropdown placeholder text.

**Comment by lubber-de** [comment]
Fixed in [Fomantic-UI](https://fomantic-ui.com) by https://github.com/fomantic/Fomantic-UI/pull/1797
