### ISSUE TITLE
Search icon size does not behave like other icons

### ISSUE THREAD

**Issue by qJake** [Semantic-Org/Semantic-UI#4938]
When using a `ui [size] icon`, any other icon would behave as you'd expect - `ui huge calendar icon` displays a huge calendar icon, for example.

But when using a `ui [size] search icon` specifically, the size defined in the Icon component is overridden by CSS in the Search component that does not have any qualifying HTML container. Here is the offending code:

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.less#L410

Take, for example, this HTML

```html
<i class="ui huge search icon"></i>
```

This should display a huge search icon (a magnifying glass), one would expect. Except it doesn't.

This CSS definition in the Search component, with no theme or site overrides, compiles to:

```css
.ui.huge.search {
    font-size: 1.42857143em;
}
```

This is overridden by, and clashes with, a previously loaded definition:

```css
i.huge.icon, i.huge.icons {
    line-height: 1;
    vertical-align: middle;
    font-size: 4em;
}
```

Chrome computes these definitions like so:

![Semantic search computation](https://i.imgur.com/8hi8ul5.png)

Notice the crossed out `font-size: 4em;` definition that is being overridden by the Search component.

This causes the search icon to render differently than other icons when used in a general context. [Here is an example Plunker demonstrating this behavior.](https://plnkr.co/edit/j2Sa656hBTTFjcNYKfqv?p=preview)

I would also like to point out that yes, a possible solution is to simply not include the search component, but for those of us who either want to use the Icons and Search components, or simply prefer to compile and use Semantic in its entirety, that is not an option. 

I believe the solution would be to qualify those Search size definitions with a container, though I don't know the right combination. Perhaps they need to be wrapped in a parent container called `.ui.search` or something similar?

**Comment by philrykoff** [comment]
The `icon` class does not need the `ui` class to work. Simply use `huge search icon` and there you go.

**Comment by qJake** [comment]
Thanks @philrykoff. Is this true anywhere, document-wide, or does that only apply if you are nested within any other `.ui.*` parent element?

**Comment by philrykoff** [comment]
I am currently on the go, but I dont remember the icon docs saying anything
about .ui - so imho it's true anywhere.

Jake Burgy <notifications@github.com> schrieb am Di. 24. Jan. 2017 um 15:06:

**Comment by qJake** [comment]
Awesome - thanks!
