### ISSUE TITLE
Nested grid help

### ISSUE THREAD

**Issue by dominicjameskelly** [Semantic-Org/Semantic-UI#4944]
I'm new to Semantic UI, coming from Susy, so I might be approaching things in the wrong way.

Here's a Semantic UI fiddle:

https://jsfiddle.net/6hbgz59d/7/

C1, C2 and C3 are all different widths. But I want them to be the same width. I want C2 and C3 to equal C1; the base grid.

In Susy, I'm able to do this. Here's a Susy fiddle:

http://www.sassmeister.com/gist/65d349368aa47c0da4a42d6a68d943b4

Is it possible to create the Susy demo using Semantic UI, using just class names?

In both cases, the HTML is the same, to keep things simple.

**Comment by dominicjameskelly** [comment]
I've just done a quick Bootstrap mock up which seems to work the same way as Semantic UI.

https://jsfiddle.net/54jb3L1e/2/

**Comment by ciajulius** [comment]
Is this what you wanted? C2 (ten) + C3 (six) = C1 (sixteen)? https://jsfiddle.net/so3dkhuj/3/

**Comment by dominicjameskelly** [comment]
Think I've sorted it sort of. I'm not familiar with this way of working with grids. Thanks anyway.
