### ISSUE TITLE
gulp build

### ISSUE THREAD

**Issue by dominicjameskelly** [Semantic-Org/Semantic-UI#4946]
When I run gulp built I end up with default, basic, github and material theme folders in dist. My theme.config only specifies default. Why are these getting created?

**Comment by dhvsandeep** [comment]
checkout theme.less file in src/, there you can find optional import for other packages like github, basic, material etc., Please try removing the import and re-run gulp build.

**Comment by dominicjameskelly** [comment]
I don't see any mention of any of those packages in my theme.less. Will theme.less get overwritten on update?

**Comment by dhvsandeep** [comment]
> /* Component's site.variables */
@import (optional) "@{themesFolder}/@{theme}/globals/site.variables";

> /* Packaged Theme */
@import (optional) "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";

these are the imports i mentioned. 
When you run a build, src/ wont be affected. So change the contents in src/ and src/themes/ as I mentioned and rebuild. It worked for me!

**Comment by dominicjameskelly** [comment]
So what are you changing these two lines to?

**Comment by dhvsandeep** [comment]
comment them or remove them

**Comment by dominicjameskelly** [comment]
So I only want to build the default theme, plus any of my themes. If I uncomment, then won't that ignore all themes?

**Comment by dhvsandeep** [comment]
yes, it'll ignore all other themes. If you want a particular set of themes, keep that particular themes in src/themes/ folder and use that above imports, so when you build, only that packages will be created in dist/

**Comment by dominicjameskelly** [comment]
ok thanks I'll give that a go
