### ISSUE TITLE
Unable to display menu item correctly that have links

### ISSUE THREAD

**Issue by pjc158** [Semantic-Org/Semantic-UI#4947]
up vote
0
down vote
favorite
I am new to semantic-ui and I am having trouble creating an html link for a menu item, below is my test code:

 <div class="ui blue borderless main menu">
<a href="#" class="blue item" data-vivaldi-spatnav-clickable="1">
  Home
</a>
<a href="#" class="ui floated dropdown item" data-vivaldi-spatnav-clickable="1">
  Products
  <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item" href="http://www.google.com">Google</a>
      <a class="item" href="http://www.zdnet.com">Zdnet</a>
    </div>
</a>
What I get displayed is: Home Products> Google Zdnet

What I want is Google and Zdnet to be displayed as items of Products:

Home |Products|
           |Google   |
           |Zdnet    |

Can anybody tell me what I need to do to my code to achieve this?

**Comment by Banandrew** [comment]
@pjc158 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
