### ISSUE TITLE
Packaged themes

### ISSUE THREAD

**Issue by dominicjameskelly** [Semantic-Org/Semantic-UI#4948]
The current project I'm working on will be heavily focused on theming. There will be one code-base, hosted on multiple sub-domains. I want a different SUI theme for each domain.

Before I looked into SUI fully, I expected to be able to switch themes easily on each domain, perhaps using a body class containing a theme name prefix. The SUI website has a theme drop down but that seems to parse the src less files in the browser - not ideal for my situation. 

Is it possible to publish multiple themes from a single SUI src folder? It seems as though I need to change the theme.config each time I want to publish a new theme, or I'll need multiple copies of the entire SUI folder which will therefore contain independent theme.config files.

**Comment by Banandrew** [comment]
@dominicjameskelly 

We talked a bit on Gitter, but I still have to post the standard response, as usage questions are in the process of being removed from GitHub Issues.

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
