### ISSUE TITLE
[Tab] doesnt work with `data-tab="some-dashed-thing"`

### ISSUE THREAD

**Issue by CodingFu** [Semantic-Org/Semantic-UI#4950]
Given this code
```html
<div class="ui secondary menu">
  <a class="active item" data-tab="test-one">One</a>
  <a class="item" data-tab="test-two">Two</a>
</div>
<div class="ui active tab segment" data-tab="test-one">One</div>
<div class="ui tab segment" data-tab="test-two">Two</div>
<script>$('.ui.menu .item').tab()</script>
```
Clicking tabs have no effect. However, if I remove all the dashes from `data-tab`, it suddenly works:
```html
<div class="ui secondary menu">
  <a class="active item" data-tab="testone">One</a>
  <a class="item" data-tab="testtwo">Two</a>
</div>
<div class="ui active tab segment" data-tab="testone">One</div>
<div class="ui tab segment" data-tab="testtwo">Two</div>
<script>$('.ui.menu .item').tab()</script>
```

**Comment by dhvsandeep** [comment]
I can't see a problem here, it is perfectly working for me. Can you reproduce the issue in jsfiddle and post it here.

**Comment by Banandrew** [comment]
@CodingFu 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
