### ISSUE TITLE
UI Embed url not valid anymore

### ISSUE THREAD

**Issue by musixite** [Semantic-Org/Semantic-UI#4951]
I tried using UI-Embed for youtube & vimeo videos.

However both urls provided are deprecated. 

YouTube
data-url: https://www.youtube.com/embed/O6Xo21L0ybE (works)
data-url: https://www.youtube.com/watch?v=fLEH7uDW0g8 (doesn't work)

The same happens with Vimeo urls.

I know there's an option to programmatically update the url but I don't know I'm supposed to configure it.

Could you please provide an javascript example to make this work along with the html?

Thanks!
- Vincent

**Comment by ciajulius** [comment]
If you are asking for a url converter, [this might help you out](http://stackoverflow.com/a/21607897)

**Comment by Banandrew** [comment]
@musixite 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
