### ISSUE TITLE
Option to build without all colours 

### ISSUE THREAD

**Issue by niksmac** [Semantic-Org/Semantic-UI#4954]
Option to build without all colours. 

Issue: I want to build a black and white website, and I want to avoid all other colors. Is that possible?

**Comment by Banandrew** [comment]
@niksmac 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
