### ISSUE TITLE
textarea can't transparent like input 

### ISSUE THREAD

**Issue by idock** [Semantic-Org/Semantic-UI#4956]

**Comment by Banandrew** [comment]
@idock 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
