### ISSUE TITLE
Inverted Bulleted Lists have Uninverted Bullets

### ISSUE THREAD

**Issue by Miserlou** [Semantic-Org/Semantic-UI#4958]
When doing something like
```html
          <ul class="ui inverted list">
            <li >Gaining Access</li>
            <li>Inviting Friends</li>
            <li>Benefits
              <ul>
                <li>Use Anywhere</li>
                <li>Rebates</li>
                <li>Discounts</li>
              </ul>
            </li>
            <li>Warranty</li>
          </ul>
```

You end up with this:

![screen shot 2017-01-29 at 6 13 18 pm](https://cloud.githubusercontent.com/assets/139987/22408874/a5bfe0b0-e64e-11e6-96e9-f578b33f221e.png)

It'd be very nice if those bullets were also inverted.

**Comment by Miserlou** [comment]
This does not happened for `ol`, only `ul`.

**Comment by Banandrew** [comment]
@Miserlou inverted how?

**Comment by Miserlou** [comment]
White text, black bullets.
