### ISSUE TITLE
Semantic UI Cards with different height in one row?

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4960]
![1-30-1](https://cloud.githubusercontent.com/assets/18745870/22419112/e7126470-e716-11e6-96bf-b395ad0e1916.png)

Hi, when I put six 'ui card' in a 'grid container', they are responsive, but all cards are in the same height in the same row. 

The middle card in the first row has little content, so can it take less height and let the middle card in second row go up? So all space is taken? 

Actually what I want to do is that, put any numbers of 'ui card' in a grid/container, and let them fullfil the container, leave no white space in a card. Is there a good advice?

Thanks a lot!

**Comment by bruno-schmidt** [comment]
Hello @tarvos21

I hope it's not too late for an answer. 

I think you won't find this feature in Semantic UI alone. :disappointed:  You are looking for the "waterfall effect". Try searching for "waterfall js" or "waterfall effect js" and you might find a lot of solutions!

**Comment by tarvos21** [comment]
@bruno-schmidt 
Thanks a lot for your great reply, it's never too late, I searched the keyword "waterful js", and got the effects I want, though I need to do some more research into it. Thanks again!

**Comment by ivantcholakov** [comment]
This is what I would try:
* To wrap the cars with left floating divs (with 33.33% or 25%, margins and paddings are to be adjusted experimentally). Alternative for trying is to wrap every card with div wit a variation of column class.
* After that, to use this script for compact rearrangement: https://github.com/desandro/masonry Here is a demo I've got, probably I should rework it someday for using cards: http://iridadesign.com/starter-public-edition-4/www/playground/masonry

**Comment by tarvos21** [comment]
@ivantcholakov, thanks, your solution is also good. I may use it to display short tweet cards with different width and height on a page.
