### ISSUE TITLE
Floating label on icon

### ISSUE THREAD

**Issue by asJulius** [Semantic-Org/Semantic-UI#4961]
Hi,

Is it possible to achieve something like this? I have menu at the top of my page, and items like messages/notifications I want to display as icons. I tried to add floating label to the item, but it floats way too high and half of it is out of view. [This is what I want to achieve](http://picpaste.com/pics/ZrtqHJOZ.1485802697.png)

**Comment by Banandrew** [comment]
@asJulius 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

**Comment by amaurymartiny** [comment]
@asJulius Did you find an answer? If yes mind sharing [on SO](https://stackoverflow.com/questions/47631666/floating-label-on-icon) for future reference? Thanks.
