### ISSUE TITLE
[Dropdown] Multiple Select with allowAdditions Security Vulnerability

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#4962]
When using a dropdown and allowing users to type their own additions to a multi select, I am getting an error if the user types in `\` at the end of the text.  This appears to be allowing the user to escape outside of the selector and can be used in XSS attacks.  Here is a jsfiddle with the setup: http://jsfiddle.net/daneren2005/rp4guxqm/.  Now type in `test\` and you will get an error in the console: `Error: Syntax error, unrecognized expression: [data-value="test\"]`

**Comment by daneren2005** [comment]
I should also note that if it loads in `test\` as the starting data you get the same error.  Here is a jsfiddle which shows the more worrying (from a security standpoint) case: http://jsfiddle.net/daneren2005/rp4guxqm/1/.

**Comment by jlukic** [comment]
Hi, using a backtick in a string will escape the value so `''Test\'` is not a valid value

Example
http://jsfiddle.net/daneren2005/rp4guxqm/1/

**Comment by daneren2005** [comment]
You are right.  I goofed and just checked for an error message, saw one, and didn't bother to check that it was the correct error message.  Sorry about that.

**Comment by jlukic** [comment]
Fixed in `2.2.8`
