### ISSUE TITLE
problem with dropdown when working with ng-repeat angularJS

### ISSUE THREAD

**Issue by slfan2013** [Semantic-Org/Semantic-UI#4964]
Please see the plunker:
https://plnkr.co/edit/YeOJjf6AZyJ7hAfpFfsK?p=preview

In the plunker, the _color_ is working fine but the _shape_ is not. For the _color_ I simply put the `<option></option>` in HTML while in the _shape_, I use `ng-repeat`.

Where is the mistake?

Thanks.

**Comment by vinayakkulkarni** [comment]
>Selection dropdowns can be initialized directly on a `select` or with the matching HTML and a hidden `input`.

https://plnkr.co/edit/0zOOgWEw6F7af5MBj0wc?p=preview

**Comment by Banandrew** [comment]
@slfan2013 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
