### ISSUE TITLE
Safari 8 - iPad Air 2

### ISSUE THREAD

**Issue by borntodesign** [Semantic-Org/Semantic-UI#4966]
Equal with buttons and full with inputs do not work on Safari 8. I have tested it on my iPad air and also on Browserstack on the Semantic UI Site.

<img width="1599" alt="screen shot 2017-02-01 at 10 38 20" src="https://cloud.githubusercontent.com/assets/4526618/22503691/cc2a28f0-e86a-11e6-96d7-f76ab8685a7d.png">

<img width="1680" alt="screen shot 2017-02-01 at 10 41 46" src="https://cloud.githubusercontent.com/assets/4526618/22503743/0ddae7e4-e86b-11e6-8064-adbb839af2d6.png">

**Comment by thalesrbs** [comment]
I have same problem.
