### ISSUE TITLE
How do I include icon files when loading CSS/JS through CDN?

### ISSUE THREAD

**Issue by jennet** [Semantic-Org/Semantic-UI#4967]
As the title says :-) What's the correct way to include icons when I've loaded the CSS & JS through CDN links?

Thanks!

**Comment by brianveltman** [comment]
You could create a separate css file with your icon overrides and make sure you load this css file after you have loaded the semantic-ui.css

**Comment by Banandrew** [comment]
@jennet 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
