### ISSUE TITLE
[search selection dropdown] How to prevent default selection

### ISSUE THREAD

**Issue by jdelatorreitrs** [Semantic-Org/Semantic-UI#4968]
Hi, first of all: thanks for all the support you are giving and your efforts doing Semantic UI.

I'm trying to prevent the default selection in a dropdown with search selection:
![image](https://cloud.githubusercontent.com/assets/18030290/22505460/ef6e933a-e87b-11e6-9e4a-faafe3d0154f.png)
As you see in the picture, when I click on the dropdown, the options are shown, but the first one is selected by default. So when I click out of the dropdown, this option is also selected by default:
![image](https://cloud.githubusercontent.com/assets/18030290/22505584/873d5be2-e87c-11e6-986f-f6d8d80ba246.png)

I tried to avoid this situation with the following:
```js
$example.dropdown({
      fullTextSearch: 'exact',
      onShow: function(){
        $example.dropdown("clear");
      },
      onHide: function(){
        var $itemSelected = $("#example .item.active.selected")[0];
        if($itemSelected) {
          // some irrelevant code in this example
        }
        $example.dropdown("restore defaults");
      }
    });
```

And actually it works fine as you see in the image:
![image](https://cloud.githubusercontent.com/assets/18030290/22505945/2010486a-e87e-11e6-8a58-11e34a2c3d14.png)

But unfortunately, when I click on any point out of the placeholder ('Compare with'), 
![image](https://cloud.githubusercontent.com/assets/18030290/22506066/b818aa1c-e87e-11e6-9d9f-5044564eae15.png)
I don't get the desired effect, and the the first option is automatically selected like in the first picture.

Anyone can help me with this, please?

**Comment by vinayakkulkarni** [comment]
Check out the comment, it's for the similar issue: 
https://github.com/Semantic-Org/Semantic-UI/issues/4972#issuecomment-276961234

PS. Pls read the docs :)

**Comment by jdelatorreitrs** [comment]
Thanks a lot!
Sorry. I've read the docs, but it seems I missed it! Maybe because my poor English ;)
