### ISSUE TITLE
How I can open a modal using button

### ISSUE THREAD

**Issue by crewow** [Semantic-Org/Semantic-UI#497]
I am using it first time and confused how to open modal on Button
<a class="ui red large labeled icon button"> Modal Open</a>

Where I write this code to open modal

```
  $('.test.modal')
    .modal('show')
  ;
```

Please Guide me I am trying it since 2 hours on buton

**Comment by jarvisjohnson** [comment]
This is ages old, but still comes up  at the top of goodle for 'semantic ui modal open on click' so putting the official version in here:

```
$('.test.modal')
  .modal('attach events', '#mymodalg', 'show')
;
```

From [modal examples page](https://semantic-ui.com/modules/modal.html#/examples)
