### ISSUE TITLE
[search selection dropdown] How to get the text in the search selection dropdown?

### ISSUE THREAD

**Issue by wztscau** [Semantic-Org/Semantic-UI#4971]
When I use the search dropdown and input some text. But I can't get my input text because there is not any `input` store my text. The value of `input` is always null. Like this `<div class="ui fluid search selection dropdown">
        <i class="dropdown icon"></i>
        <input type="hidden">
        <input class="search" autocomplete="off" tabindex="0"><div class="default text">def</div>
        <div class="menu" tabindex="-1"><div class="item" data-value="0">item1</div></div>
      </div>`
Can someone give me a hand?

**Comment by vinayakkulkarni** [comment]
Pls post a jsfiddle

**Comment by Banandrew** [comment]
@wztscau 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
