### ISSUE TITLE
Search dropdown issue

### ISSUE THREAD

**Issue by eddeyang** [Semantic-Org/Semantic-UI#4972]
I found that when you click other parts of the web page to hide the selections, an additional item will be selected. Take a look at the following gif:

![untitled](https://cloud.githubusercontent.com/assets/39968/22546302/84766952-e977-11e6-8ffb-a6c74c4e652e.gif)

I've created a demo to show the issue: 
[https://codepen.io/ogrishman/pen/VPXxbV](https://codepen.io/ogrishman/pen/VPXxbV)

**Comment by vinayakkulkarni** [comment]
It's mentioned in the docs. 

> set `forceSelection: false`
<img width="604" alt="screen shot 2017-02-02 at 7 16 15 pm" src="https://cloud.githubusercontent.com/assets/19776877/22551798/388bb83a-e97c-11e6-962c-ac3d7d14abfd.png">

Example:
```javascript
$(".ui.dropdown").dropdown({
        on: "click",
        forceSelection: false
    });
```

**Comment by eddeyang** [comment]
Thanks!

**Comment by ajarti** [comment]
Hi all, I see this issue a fair amount repeated and always closed with the explanation use: 'forceSelection: false' , this does not solve the problem, it persists, currently using 2.2.10.
