### ISSUE TITLE
Outdated semantic-ui-less repository

### ISSUE THREAD

**Issue by mardr** [Semantic-Org/Semantic-UI#4973]
I see the latest published version is 2.2.7 (December 21, 2016) but semantic-ui-less only has 2.2.4 (August 25, 2016). Any chance of updating to latest version?

**Comment by vinayakkulkarni** [comment]
It's probably done by a pusher bot, @jlukic must've disabled it i guess?

**Comment by Banandrew** [comment]
@mardr Robot returned 2 days ago and updated all, I think, stale repositories—closing as resolved.
