### ISSUE TITLE
Read-Only Checkbox

### ISSUE THREAD

**Issue by samroberts707** [Semantic-Org/Semantic-UI#4974]
I am trying to include checkboxes in my site that are read-only, I am following the documentation online but it doesn't seem to be having any effect and I can still toggle my checkbox on and off. 

Here is my HTML Mark Up for the checkbox
```
<div class="ui segment">
  <div class="ui read-only checkbox">
    <input id="4-1" type="checkbox">
    <label for="4-1">Read Only</label>
  </div>
</div>
```

Here is the corrosponding JS at the bottom of the page in a script tag

```
$('.checkbox.read-only .checkbox')
  .last()
  .checkbox({
    uncheckable: false
  });
```

**Comment by vinayakkulkarni** [comment]
can you post a jsfiddle?

also, can you just try this:

```javascript
$(".ui.read-only.checkbox").checkbox();
```

**Comment by Banandrew** [comment]
@samroberts707 

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forum](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
