### ISSUE TITLE
.dropdown("refresh") for dynamic content causes dropdown to immediately retract.

### ISSUE THREAD

**Issue by wsutton** [Semantic-Org/Semantic-UI#4976]
Hello,

I am having an issue when I refresh a semantic ui dropdown widget. The dropdown contains dynamic items so in order to update the view I do .dropdown("refresh") as is suggested. The issue I have is once I do that, the content/view has been updated but when I click on the dropdown, it immediately retracts upon opening, making the dropdown useless. I've noticed that if i do a .dropdown({on:"hover"}) it'll work fine but I'm hoping to keep it an on click dropdown like I have it initialized. Has anyone else had this problem? 

Thanks

**Comment by vinayakkulkarni** [comment]
did you pass in `{on:"click"}` with refresh? also can you please post a jsfiddle?

**Comment by wsutton** [comment]
That was it. I didn't realize could chain calls on dropdown. Thank you!
