### ISSUE TITLE
Stop dropdown from dropping down again with onchange

### ISSUE THREAD

**Issue by jamessampford** [Semantic-Org/Semantic-UI#4977]
I'm using the onchange to get the value of the selected item from a dropdown and then I open up a modal to process the selected item

To put simply, from the dropdown you can select an existing item or add a new one - adding a new one opens the modal, text gets entered in on the modal and goes into a hidden input upon closing - however, the dropdown reopens losing the selected item when it should remain collapsed - http://jsfiddle.net/sLc3ceth/4/

I've noticed a similar thing happens when calling an alert() when onchange fires too http://jsfiddle.net/pybxztu2/

I know I may be missing something but have tried looking through the docs to no solution thus far :S

**Comment by dhvsandeep** [comment]
That is maybe due to including  _**'search'**_ class in select element. I think search is automatically triggering. Try removing search class if you don't need. Meanwhile I'll try to check the root cause.

**Comment by Banandrew** [comment]
Hi @jamessampford,

You could do something like that to work around it, but there’re other ways to do it as well:
```JS
$('.ui.dropdown')
  .dropdown({
    onChange: function() {
      $(this)
        .dropdown('restore defaults')

      window.setTimeout(function() {
        addItem()
      }, 10)
    }
  })
```

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by lubber-de** [comment]
This is fixed in the community fork [Fomantic-UI](https://fomantic-ui.com)
See your adjusted jsfiddle here http://jsfiddle.net/lubber/7t529suh/
