### ISSUE TITLE
[Dropdown] A Multiple Search Selection Dropdown Should Not Select an Item By Just Focusing and Blurring

### ISSUE THREAD

**Issue by ziacik** [Semantic-Org/Semantic-UI#4979]
Hi. If you look at examples of dropdown with multiple search selection here, http://semantic-ui.com/modules/dropdown.html#multiple-search-selection

when you click into the dropdown and then just click away, Alabama gets selected though you didn't choose it.

This happens with Chrome 54.0.2840.71 (64-bit) on Linux, Gnome 3.

**Comment by kmd1970** [comment]
I was about to upgrade to version 2.2.6 and also noticed this issue.  

In a multiple select drop-down, if I select an option and then remove focus, the adjacent option (below) also gets selected. This would break all my multiple selects and frustrate users.

**Comment by kmd1970** [comment]
Same as [https://github.com/Semantic-Org/Semantic-UI/issues/4972](url)

**Comment by ziacik** [comment]
Thanks, @kmd1970 
I was looking for the similar issue but couldn't find one.
Closing.

**Comment by ajarti** [comment]
Hi guys, I see this is still an issue, 'forceSelection : false' has no effect and currently on 2.2.10 ?
