### ISSUE TITLE
<a> tag in the dropdown menu is not working with touch screen device

### ISSUE THREAD

**Issue by carlcarl** [Semantic-Org/Semantic-UI#498]
When I press `<a>` element in the dropdown menu, it can't link to the correspond url address. I think this issue may be related to #453 .

Here is the site url: http://g0v.tw/
And here is the part of the code:

```
<div class="ui fluid seven item menu">
    <a href="/index.html" class="active orange item">首頁</a>
    <div class="ui pointing dropdown link item">關於
        <div class="menu">
            <a href="/about.html" class="item">關於 g0v</a>
            <a href="/manifesto.html" class="item">零時政府宣言</a>
        </div>
    </div>
</div>
```

**Comment by peterrobertz** [comment]
hm, same here, newest semantic-ui version, 1.5.2.

the link doesnt get called

  <div class="ui inline link dropdown">
    <input type="hidden" name="gender">
    <div class="text">Shiba Inu</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">
        <i class="dropdown icon"></i>
        <span class="text">Dogs</span>
        <div class="menu">
          <div class="item">Shiba Inu</div>
          <a class="link item" href="/foo">FOOOOOOHOOOOOO</a>
          <div class="item">Labrador</div>
        </div>
      </div>
      <div class="item">
        <i class="dropdown icon"></i>
        <span class="text">Cats</span>
        <div class="menu">
          <div class="item">Aegean</div>
          <div class="item">Balinese</div>
          <div class="item">Persian</div>
        </div>
      </div>
    </div>
  </div>

<3
