### ISSUE TITLE
modal disappear completely after the first show 

### ISSUE THREAD

**Issue by badrsh** [Semantic-Org/Semantic-UI#4981]
Hi 
I have problem with the modal 
everything is fine but the problem is when i click on the button to open the modal its work 100% 
if i close it 
my model will gone completely and i will not be able to open it again 
I have opened the inspect element but there was nothing related to modal ( removed )

any idea ? ? 
I'm calling the show method from my angular file 

```
 $scope.StdModel = function () {
         $(".std>.ui.modal").modal("show");
    };
```

there is no error

**Comment by badrsh** [comment]
Ihave found the problem but i dont know the resone of it 

when i'm using 

`.std>.ui.modal`

its work for the first time but then it's not ( I dont know why)

i change it to` .ui.modal.std` and everything fine now

**Comment by Banandrew** [comment]
Hi @badrsh,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
