### ISSUE TITLE
label is not changing style if field is inline

### ISSUE THREAD

**Issue by AgentChris** [Semantic-Org/Semantic-UI#4989]
<Form.Input label='First name' placeholder='First name' inline error/>

this is happening because inline has the color black and is overwriting the red color from error class
inline:
.ui.form .inline.field>label, .ui.form .inline.field>p, .ui.form .inline.fields .field>label, .ui.form .inline.fields .field>p, .ui.form .inline.fields>label {
display: inline-block;
width: auto;
margin-top: 0;
margin-bottom: 0;
vertical-align: baseline;
font-size: .92857143em;
font-weight: 700;
/* color: rgba(0,0,0,.87); */
text-transform: none;
}
error:
.ui.form .field.error .input, .ui.form .field.error label, .ui.form .fields.error .field .input, .ui.form .fields.error .field label {
color: #9f3a38;
}

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
