### ISSUE TITLE
How I can make Multiple drop-down one depend on another

### ISSUE THREAD

**Issue by crewow** [Semantic-Org/Semantic-UI#499]
I want to make 2 drop-down one for countries and another for Cities.

If I choose Country value it will show Cities of that chosen country in 2nd drop down.

I have JSON Encode of Countries and Cities with me. 

Any one Help.

I already did it in Bootstrap but in semantic I am confused due to differnent type of Dropdown

```
http://crewow.com/PHP_Dynamic_Select_option_Via_Ajax.php
```

**Comment by Anushka-codergirl** [comment]
I'm using the code in Java but in the dependent dropdown, the search option is removed.
