### ISSUE TITLE
How do I create multiple sematic UI site projects?

### ISSUE THREAD

**Issue by saikrishnadeep** [Semantic-Org/Semantic-UI#4991]
I've cloned the repo and made quite a lot of customizations in my child theme at `npm/semantic-ui/src/site/` and compiled them using gulp. However, I now wish to create another child theme that uses most of the `npm/sematic-ui/themes/default/` definitions.

I'm sure I can somehow manually get this working by creating a new `site2` folder and changing the npm settings I suppose. But is there any other faster way of creating a new child-theme `site` folder and switching between each of these sub projects?

On a sidenote, how do I switch between themes like `default`,`material design`, `github` that are provided. How can I create separate workspaces/ projects to check out how each of the themes & childthemes compile?

**PS:** I could obviously git clone for every project but I'm sure I'm missing out a simple trick to handle "child-themes" using gulp and npm for semantic-ui

**Comment by Banandrew** [comment]
Hi @saikrishnadeep,

If I understood you correctly, I don’t think the framework supports multiple compilations like that. The fastest way is to have a separate SUI installation. If what you mean, is to switch on the fly, that’s not possible out of the box, for other usage please refer to [this documentation section](http://semantic-ui.com/usage/theming.html#using-packaged-themes). The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
