### ISSUE TITLE
Has Lato always looked like that?

### ISSUE THREAD

**Issue by websevendev** [Semantic-Org/Semantic-UI#4998]
I noticed the Lato on my site looks different than it used to.
I had some older tabs open overnight, so I compared.

Open in tabs and flick back and forth:
Before:
http://i.imgur.com/boAj26Q.png
After:
http://i.imgur.com/w6yCaVd.png

In dev tools, under Sources, a new source has appeared: fonts.gstatic.com

To me, the change has taken place on Semantic UI main page as well.

Which version is the intended look of Semantic UI? 

Have I been seeing some different Lato or did it get updated by Google?

**Comment by Banandrew** [comment]
I noticed it as well. It’s definitely not the promised v2.015, as [the issue](https://github.com/google/fonts/issues/6) is still opened, I also self-hosted v2 recently, and it looked pretty much the same. Linking your [other issue](https://github.com/google/fonts/issues/644) from [google/fonts](https://github.com/google/fonts) here in case someone’s interested in it as well.

**Comment by websevendev** [comment]
Looks like the Google Fonts Lato version got updated. Nothing to do with SUI so I'm closing this.

https://github.com/google/fonts/issues/644
