### ISSUE TITLE
progress  not complete in vue event

### ISSUE THREAD

**Issue by Dreampie** [Semantic-Org/Semantic-UI#4999]
```javascript
<template>
    <div v-show="show" class="ui top attached red progress" data-value="10" data-total="100">
        <div class="bar"></div>
    </div>
</template>

<script>
    export default {
        name: 'v-loading',
        data(){
            return {
                show: false
            }
        },
        methods: {
            start(){
                this.show = true
                const progress = $(this.$el)
                const progressInterval = window.setInterval(() => {
                    if (progress.progress('get value') < 85) {
                        progress.progress('increment');
                    } else {
                        window.clearInterval(progressInterval)
                    }
                }, 10);
            },
            complete(){
                const progress = $(this.$el)
                progress.progress('complete')
//                this.show = false
//                progress.progress('reset')
            }
        },
        mounted () {
            this.$bus.$on('v-loading:start', this.start)
            this.$bus.$on('v-loading:complete', this.complete)
        }
    }
</script>
```

when execute complete method `progress.progress('complete')` nothing happened

**Comment by Banandrew** [comment]
Hi @Dreampie,

Make sure `complete()` is being called, you could also try sending `progress.progress('complete')` onto the event loop with `window.setTimeout( f(){}, 0)`. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by Dreampie** [comment]
@Banandrew   show log complete,but progress not complete

![image](https://cloud.githubusercontent.com/assets/3667080/22788857/2481f25a-ef1c-11e6-9f2d-36441b8bc804.png)

**Comment by Banandrew** [comment]
@Dreampie have you tried the event loop?

**Comment by Dreampie** [comment]
like this, also not work
```javascript
complete(){
                console.log('complete')
                const progress = $(this.$el)
                window.setTimeout(() => {
                    progress.progress('complete')
                }, 1)

//                this.show = false
//                progress.progress('reset')
            }
```

**Comment by Banandrew** [comment]
I cloned your example, and everything works as expected, progress completes even without `setTimeout()`.

**Comment by Dreampie** [comment]
@Banandrew  are you change something?

**Comment by Banandrew** [comment]
@Dreampie not a single thing, just removed the `setTimeout()` wrapper, but you already ran the application without it.

**Comment by Dreampie** [comment]
I found if click menu this work, but refresh page not work

**Comment by Banandrew** [comment]
@Dreampie refreshing works on my machine, I think you need to dig deeper, there’s something wrong with your setup. Your server issues might also be the cause of #5001.

**Comment by Dreampie** [comment]
I'll try it
