### ISSUE TITLE
Activate segment dimmer on button click

### ISSUE THREAD

**Issue by bushcode** [Semantic-Org/Semantic-UI#5002]
How can i activate a segment dimmer on button click? please help

**Comment by Banandrew** [comment]
Hi @bushcode,

Something like that:
```JS
$('.ui.button')
  .click(function (event) {
    $('.ui.segment')
      .dimmer('show')
  })
```

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by vinayakkulkarni** [comment]
You beat me to it @Banandrew 😉

**Comment by vinayakkulkarni** [comment]
@bushcode: you can do something like this too: [jsFiddle](http://jsfiddle.net/vinayakkulkarni/efp8z6Ln/456/)

**Comment by bushcode** [comment]
@Banandrew @vinayakkulkarni Thanks guys got it to work now. And its noted for future questions.
