### ISSUE TITLE
References to external resources

### ISSUE THREAD

**Issue by jkufner** [Semantic-Org/Semantic-UI#5008]
`````
semantic-ui-less/themes$ grep 'url(http' . -r
./bookish/elements/header.overrides:@import url(http://fonts.googleapis.com/css?family=Karma);
./instagram/views/card.overrides:@import url(http://fonts.googleapis.com/css?family=Montserrat:700,400);
./chubby/elements/header.overrides:@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);
./chubby/elements/button.overrides:@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);
./material/collections/menu.overrides:@import url(https://fonts.googleapis.com/css?family=Roboto);
./material/elements/header.overrides:@import url(https://fonts.googleapis.com/css?family=Roboto);
./material/elements/button.overrides:@import url(https://fonts.googleapis.com/css?family=Roboto);
./material/modules/dropdown.overrides:@import url(https://fonts.googleapis.com/css?family=Roboto:400,700);
./material/modules/modal.overrides:@import url(https://fonts.googleapis.com/css?family=Roboto);
`````

Such references to external resources should not be used by default. It introduces hidden dependency on 3rd-party services and may cause unexpected problems when such external resource becomes unavailable (current reliability does not matter).

**Comment by Banandrew** [comment]
Hi, @jkufner. I don’t see a problem here, considering that all those themes aren’t complete—they exist for certain components only, and are there just to give a developer an idea on how packaged themes can be utilized. The default theme *maybe* would’ve been a different story, but it’s not the case there.

**Comment by jkufner** [comment]
The first problem is privacy. This little detail sends user activity to Google's servers. It can leak some private data via referer headers. That is not acceptable for many applications.

The second problem is that this external dependency is not documented. It is hidden deep in the source code, where I accidentally found it.

Moreover, if these themes are here “just to give a developer an idea on how packaged themes can be utilized”, then these should not be included in a production-ready package, they should be somewhere between examples.

**Comment by ryanmills** [comment]
opinion != should

**Comment by nebulade** [comment]
Just came here to search how to remove them in a custom build as well. In my case all access to google font servers are blocked and I would have instead provided the fonts from my server origin. 

Nothing against having them baked in by default, but if there are any pointers how to easily replace those urls, that could be helpful. Thanks.

**Comment by nebulade** [comment]
Thanks to #5024 this was actually already very smooth to get rid of the google fonts. Basically just set `@importGoogleFonts` to false in the `site.variables` of the theme you are going for and depending on the setup adjust the `@fontName` variable. Then rebuild the project.

**Comment by JSMike** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/theme.less#L50
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/globals/site.less#L25

These should be removed. Loading this library as an NPM module shouldn't have the side effect of loading an external package from the web. This breaks the patterns when bundling. The library shouldn't dictate that I go out to the web to load a font, when fonts can also be loaded as NPM modules and included. This is especially troublesome for internal deployments for where the client may not have access to Google. This should be replaced with documentation on how to add Google fonts to your page via both npm and through the web.
