### ISSUE TITLE
[Rating] 'set rating' not accepting variable as argument

### ISSUE THREAD

**Issue by vsimonovski** [Semantic-Org/Semantic-UI#5010]
I'm using semantic ui with my angular(1.5.9) app and have star rating rendering problem.

I'm ng-repeat-ing semantic ui cards nested inside angular directive, inside angular directive controller I want to initialize number of stars with property of repeated object but 'set rating' wont accept argument different than plain string.

```javascript
// this works
$('.ui.rating').rating('set rating', '5'); 
// this doesn't work
let movieRating = Math.floor(this.movie.vote_average) + '';
$('.ui.rating').rating('set rating', movieRating); 
```

**Comment by Banandrew** [comment]
Hi @vsimonovski,

I’ve just [tested it](http://jsfiddle.net/Banandrew/jt4zsv85/), and it does accept variables. I’m not familiar with Angular, but jQuery doesn’t play well with JavaScript frameworks, so the issue probably lies within Angular’s lifecycle. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
