### ISSUE TITLE
Dropdown mutiple selection with API not working well

### ISSUE THREAD

**Issue by nestorvanz** [Semantic-Org/Semantic-UI#5013]
I have a `<select>` dropdown list filled with an API, this works fine showing results and selecting one result, but when I try to add another option to it, is not adding the option into the dropdown, but the option disappears from the result options. This is my code:

```html
<select class="ui multiple search selection dropdown products" multiple ng-model="ctrl.brand.products" ng-optionss="product.id as product.name for product in ctrl.products">
    <option value="">Search for options</option>
</select>
```

```javascript
$('.ui.dropdown.products').dropdown({
  saveRemoteData: false,
  apiSettings: {
    url: 'http://localhost:5000/products?name={query}',
    onResponse: function( data ) {
      var response = {};
      response.success = true;
      for (var i = 0; i < data.length; i++) {
        data[i].value = data[i].id;
      }
      response.results = data;
      return response;
    }
  }
});
```

**Comment by nestorvanz** [comment]
I found what the problem is.

My API is returning an Array of results, but the 'onResponse' function is giving me back an object with the index as key instead the array of data.

My API result
````javascript
[
  { id: 1, name: "some name" },
  { id: 2, name: "another name" }
]
```

Te response function data
```javascript
{
  "0": { id: 1, name: "some name" },
  "1": { id: 1, name: "another name" }
}
```

Why is this happening? It suppose to have to work like that?

**Comment by Banandrew** [comment]
Hi @nestorvanz,

That’s most certainly a back-end issue. What technology stack do you use there, and do you send your API response with a `Content-Type: application/json` header? I’ll close the issue as a usage question, but feel free to keep this thread going; you might also want to copy the issue to [our Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI) in case you’re using a back-end technology I’m not familiar with. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
