### ISSUE TITLE
Custom Display properties not working inside Accordion

### ISSUE THREAD

**Issue by dhvsandeep** [Semantic-Org/Semantic-UI#5014]
Here I've some elements inside an accordion for which i've applied `display:none`, which is not getting effected inside accordion. The display property is getting over-written.

Here is the [jsfiddle](https://jsfiddle.net/dhvsandeep/kdsqk209/)

**Comment by Banandrew** [comment]
Hi @dhvsandeep,

That’s just how it is, but if your use case requires it, you could add a CSS rule that would override the accordion’s manipulations, something like that:
```CSS
.ui.accordion .content > a {
  display: none !important;
}
```

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
