### ISSUE TITLE
Placeholder images usage

### ISSUE THREAD

**Issue by websevendev** [Semantic-Org/Semantic-UI#5015]
Hello!

I have recently created a premium WordPress theme using Semantic UI and I'm wondering if it's okay to use the placeholder images from semantic-ui.com as placeholder images for my WordPress theme demo sites.

The images I'm referring to:
http://semantic-ui.com/images/avatar2/large/matthew.png
http://semantic-ui.com/images/avatar2/large/molly.png
http://semantic-ui.com/images/avatar2/large/kristy.png
etc...

I'm not sure about the origin of these images but they are beautiful.

**Comment by Banandrew** [comment]
Hi @websevendev,

I think it’d be faster to e-mail Jack directly: [jack@semantic-ui.com](mailto:jack@semantic-ui.com). The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
