### ISSUE TITLE
label in `ui labeled input` can not be vertical align

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#5019]
```
<div class="ui labeled input">
  <a class="ui label">Label</a>
  <input placeholder="Placeholder..." type="text">
</div>
```
```
.ui.labeled.input .ui.label {
  vertical-align: middle;
}

.ui.labeled.input {
  height: 5em;
}
```
![input](https://cloud.githubusercontent.com/assets/18745870/22920280/3a6829a2-f2cf-11e6-9af4-40a029fe2f6f.png)

http://jsfiddle.net/tarvos21/6pmzaxfz/2/

When input's height is increased, the label's text will not be in the center vertically, it's still on the top.

I have tried some solutions, one simple way is to set the label's line-height the same with the input's line-height.

**Comment by Banandrew** [comment]
Hi @tarvos21, `vertical-align` doesn’t work how you think it does, and has different behavior depending on where it’s used. [Here’s](http://phrogz.net/css/vertical-align/) some more information about it. Aligning something vertically with `line-height` definitely works, you could also set up a `table > tr > td` inside of the label and align it with `vertical-align`, or use Flexbox:
```CSS
.ui.labeled.input .ui.label {
  display: flex;
  align-items: center;
}
```
