### ISSUE TITLE
Vue+Semanti-UI: modal element changed,only can run seccuess once

### ISSUE THREAD

**Issue by Dreampie** [Semantic-Org/Semantic-UI#5020]
http://stackoverflow.com/questions/42219924/vuesemanti-ui-modal-element-changed-only-can-run-seccuess-once

**Comment by Banandrew** [comment]
Hi @Dreampie,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
