### ISSUE TITLE
Vertical divider is broken

### ISSUE THREAD

**Issue by dxyozh** [Semantic-Org/Semantic-UI#5023]
You can see the wrong behavior in official demo - http://semantic-ui.com/elements/divider.html#vertical-divider. 

This issue is that divider is not in its desired place. It is placed before the left element instead of in the middle place (between left and right elements).

Can be reproduced in latest Chrome (Version 56.0.2924.87 (64-bit)) on Ubuntu 16.04.

**Comment by Banandrew** [comment]
See #4342.
