### ISSUE TITLE
[Dropdown] - Search dropdown selects first item when selection is cancelled

### ISSUE THREAD

**Issue by ceremcem** [Semantic-Org/Semantic-UI#5027]
**Steps to Reproduce**
1. Go to http://semantic-ui.com/modules/dropdown.html#search-selection
2. Click dropdown and see countries are listed 
3. Do not select anything from list 
4. Click outside of dropdown 

**Expected**
The Dropdown should not select anything. 

**Result**
The Dropdown selects the first item in the list.

**Comment by Banandrew** [comment]
See #4506.
