### ISSUE TITLE
Where is ui vertical following fluid accordion text menu in the documentation? 

### ISSUE THREAD

**Issue by ceremcem** [Semantic-Org/Semantic-UI#5028]
I couldn't find the `ui vertical following fluid accordion text menu` in the documentation: 

![image](https://cloud.githubusercontent.com/assets/6639874/23041368/6d536c12-f49d-11e6-9b2a-82e98af689cb.png)

**Comment by Banandrew** [comment]
Hi @ceremcem,

It’s just a combination of components: there’s a [sticky](http://semantic-ui.com/modules/sticky.html), an [accordion](http://semantic-ui.com/modules/accordion.html) and a [.vertical.text.menu](http://semantic-ui.com/collections/menu.html). The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by douglasg14b** [comment]
One thing hurting this library is the general lack of information, and very poor support for things like this.

Google is filled with github issue links that are just shut down due to some draconic rules, and links provided to dead sources of knowledge.

**Comment by ceremcem** [comment]
I think reverse engineering is suggested.
