### ISSUE TITLE
Fluid tag on pop up has no effect when popup is inside of an item and a menu

### ISSUE THREAD

**Issue by JKiely** [Semantic-Org/Semantic-UI#5029]
Jsfiddle: http://jsfiddle.net/hb54c7r0/7/

When a popup is inside of a div with the item class attribute, which is itself inside of a menu, attributes like fluid will have no effect on it. It will appear the same width as the button, and the only way to force it wider is to set the min-width higher in css.

**Comment by philrykoff** [comment]
Well the doc states that `A fluid popup will take up the entire width of its offset container`. `item `has `position: relative`. Doesn't that mean, that `item` is the offset container?

In addition to that, if you look at the following example (http://semantic-ui.com/collections/menu.html#popup-menu), the popup is being declared outside the menu.

Here is a working fiddle: http://jsfiddle.net/c1e1gL99/.

**Comment by Banandrew** [comment]
That seems to be correct, the popup just doesn’t fit in there.
