### ISSUE TITLE
Dropdown click issue

### ISSUE THREAD

**Issue by Herb4t-** [Semantic-Org/Semantic-UI#5032]
Hi,
i've little problem with my semantic dropdown menu, when i click on it, the "upward" class appear and it change the menu direction

```
<div class="field">
          <label>Section : </label>
          <select name="section" class="ui dropdown" id="section">
            ***Some options lines ***
          </select>
          
</div>
```

![issue dropdown](https://cloud.githubusercontent.com/assets/6637814/23062306/89fa51ba-f505-11e6-96aa-fcbd79019a9e.gif)

**Comment by vinayakkulkarni** [comment]
@Herb4t- Can you please fork this jsFiddle and provide a test-case instead of a screenshot gif which will help us better identify the issue?

You can fork [this jsFiddle](http://jsfiddle.net/efp8z6Ln/)

**Comment by vinayakkulkarni** [comment]
Closing this till @Herb4t- provides a test case.

You can still comment on it @Herb4t- :)
