### ISSUE TITLE
Possible problem with multiple search dropdown

### ISSUE THREAD

**Issue by DanAtShenTech** [Semantic-Org/Semantic-UI#5033]
I was looking at the dropdown here:  http://semantic-ui.com/introduction/new.html#faster-dropdown-selection

In the multi-select, if I select an item and then click anywhere outside the dropdown (whether or not it's closed), it adds another item to the selection by itself without me picking it.

**Comment by Banandrew** [comment]
Hi @DanAtShenTech, try `forceSelection: false`. See #4506.
