### ISSUE TITLE
[ui action input] Input compressed, crushed when multi fields or wide field

### ISSUE THREAD

**Issue by dawadam** [Semantic-Org/Semantic-UI#5034]
Hi,
All is in the title.
The jsfiddle :

http://jsfiddle.net/sxyvwa4y/4/

Regards

**Comment by Banandrew** [comment]
Hi @dawadam,

I think it’s supposed to be used with dropdowns initialized with `$('.ui.dropdown').dropdown()`; the use case seems too narrow to me to be a part of the core, therefore I’m interpreting it as a usage question. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by dawadam** [comment]
Sorry,
For me, it was a bug.
Why should I use javascript?
Because without "multiple field" or "wide field", this works very well.
It would seem that this is only a CSS rectification to do.
Regards.

**Comment by Banandrew** [comment]
@dawadam You don’t have to, the solution is as easy as overriding one of the default rules (`.ui.form select`) that produces this behavior:
```CSS
.ui.dropdown {
  width: initial !important; 
}
```
Open `installation_folder/src/site/modules/dropdown.overrides` and put it there under a namespace, something like `.ui.simple.dropdown`, then rebuild the framework. I suppose you could override the mentioned `.ui.form select` rule in `installation_folder/src/site/collections/form.overrides` instead, but it’s up to you.

**Comment by dawadam** [comment]
Thanks.
