### ISSUE TITLE
ui list has issues

### ISSUE THREAD

**Issue by Heeday101** [Semantic-Org/Semantic-UI#5035]
So far, I found bugs in ui unordered lists where the text don't show properly at all on the browser.
Also ordered lists, when an embedded lists are present, the numbering + spacing fails...

Hope this gets fixed soon!
<img width="595" alt="screen shot 2017-02-17 at 23 06 20 pm" src="https://cloud.githubusercontent.com/assets/18669178/23091219/bee23ff4-f565-11e6-86e7-9bbdaae39af2.png">
<img width="908" alt="screen shot 2017-02-17 at 23 05 55 pm" src="https://cloud.githubusercontent.com/assets/18669178/23091231/f96e4a5a-f565-11e6-99e4-a18d20d43ae8.png">

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by vinayakkulkarni** [comment]
Closing this till @Heeday101 provides a test case.
