### ISSUE TITLE
[Dropdown] Submenu goes out of window's visible area

### ISSUE THREAD

**Issue by ak99372** [Semantic-Org/Semantic-UI#5036]
**Issues** :
Dropdown options (sub-menu) don't check when they go outside of window

![image](https://cloud.githubusercontent.com/assets/9924769/23098009/3a6e19c6-f5f8-11e6-8452-4b7943b7825f.png)

![image](https://cloud.githubusercontent.com/assets/9924769/23098085/bc06583a-f5f9-11e6-8e16-92a7cf7e0803.png)

More examples...
![image](https://cloud.githubusercontent.com/assets/9924769/23097946/a8ffc350-f5f6-11e6-8b09-9768b23db81a.png)

![image](https://cloud.githubusercontent.com/assets/9924769/23098062/799cdb5e-f5f9-11e6-9b02-aec79869137c.png)

**Expected behaviour:**
->Submenu should check it is displayed within visible window area and (re)position itself if necessary.
-> in rare case when the whole menu cannot fit into the visible screen then the visibility of the left and top side take priority 

**Tested Browser:** Chrome 55.0.2

**Comment by luisnomad** [comment]
Still no fix for this?
Any workaround?
