### ISSUE TITLE
setting @mobileGutter to any other value than 1 rem issue in Chrome mobile 

### ISSUE THREAD

**Issue by gh67uyyghj** [Semantic-Org/Semantic-UI#5037]
Hi all, whenever I change `@mobileGutter` in `container.variables` to any other value than its default value `1rem`  to, like for example (`0.5rem` or `10px`), I find that the width of the window becomes slightly larger than its fit in google chrome in my phone in all my app pages (i.e. you can drag the window to the right/left slightly); this issue does not happen in firefox mobile or even whenever I try to resize the browser in my PC, (tried on latest versions of chrome & firefox).

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln). Also, what Chrome for Android version is that?

**Comment by jlukic** [comment]
This actually seems like enough to go on seeing as this involves less.
