### ISSUE TITLE
[Form validation] the submit button should be enabled/disabled based on a form’s validation status

### ISSUE THREAD

**Issue by WojtekF** [Semantic-Org/Semantic-UI#5038]
I've created a form and I was trying to set it up in such way that after validating the field, form will be revalidated. I've set settings.on to be "change" and form is being revalidated only after submitting/pushing enter button. JS fiddle for reference

http://jsfiddle.net/8jn80vuo/1/

**Comment by Banandrew** [comment]
Hi @WojtekF,

If I understood you correctly, you could use `is valid` check:
```JS
function setEntry() {
  $("#form")
    .form('set values', { Name: "some name", Value: 11 })
    .form('is valid')
}
```

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by Banandrew** [comment]
If you read the e-mail, I suggested to use `is valid`—this is wrong, sorry about that; I thought about one thing, and typed another. Please see the edited reply.

**Comment by WojtekF** [comment]
Hi @Banandrew 
i think that I've not written correctly what the issue is. I've got another use case.
After setting values and validating the form onSuccess event is triggered and submit button is enabled.
After deleting the name the error message occurs so it means that field/form is not valid but submit button is still enabled so I can pass invalid data. on clicking submit button with these steps you'll see that the name passed is empty which is not correct behaviour.

Updated JSFiddle: http://jsfiddle.net/8jn80vuo/2/

**Comment by Banandrew** [comment]
@WojtekF Thank you. There’s currently no straightforward way to make the submit button disabled/enabled based on the validation status. The form is valid by default, so if you enter a valid value in one of the fields without touching the other, the form will be considered valid anyway, and you can’t really utilize available callbacks (as both of us tried); there’re several problems with that, but in short, the feature does make sense to exist in some form.

**Comment by WojtekF** [comment]
Hi @Banandrew,
The issue is not about the submit button but about onFailure/onSuccess not triggering after field validation. I've done some changes locally and my fix works for me. 
I'd create a PR but I'm newbie to JS (0 commercial yrs, 5yrs in OOP). I can share my fix if you want so.

**Comment by Banandrew** [comment]
@WojtekF I checked it yesterday as well, the do get triggered properly, but not at the point where it’d be possible to use them to switch the button’s disabled state, and that’s why I tagged it as a general validation enhancement. Glad you found a workaround, but there’s no need for a PR; Jack will get back to it as soon as possible.

**Comment by tmikaeld** [comment]
I also have the need to show another form after the first form have been validated, but onSuccess never trigger even when using on: 'change' event.
