### ISSUE TITLE
stackable right menu 

### ISSUE THREAD

**Issue by oottoohh** [Semantic-Org/Semantic-UI#5039]
hello im new with semantic ui, can you give me example how to stackable child of right menu item in to bottom of right menu, just part of right menu?

**Comment by vinayakkulkarni** [comment]
Dear @oottoohh, Please refer the SUI docs for examples as well as detailed usage.

http://semantic-ui.com/collections/menu.html

PS. you can visit [gitter](https://gitter.im/Semantic-Org/Semantic-UI) to chat with us.

**Comment by Banandrew** [comment]
Hi @oottoohh,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
