### ISSUE TITLE
Button's @textColor conflicts with Global @textColor

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#5040]
global/site.variables:
`@textColor           : rgba(0, 0, 0, 0.87);`
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L124

elements/button.variables:
`@textColor           : rgba(0, 0, 0, 0.6);`
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/button.variables#L26

It's confusing to discover that there are two `@textColor` variables, especially the one in `button.variables`, from the docs, one may get the idea that this kind of global variables are unique.

**Comment by vinayakkulkarni** [comment]
Hence, `button.variables` & `site.variables`

**Comment by Banandrew** [comment]
I suppose it could be done to dispel the confusion, but I also agree that namespacing is there for a reason. It might be better to just improve the documentation.

**Comment by jlukic** [comment]
I can see the frustration, but its par for the course with inheritance. I'd recommend checking the component variables first when changing styles for that component as it'll give a good idea of how global variables are modified in the scope of the component.
