### ISSUE TITLE
Making HUGE button become TINY

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5041]
Hi,

I have a button like this:

`<button class="ui icon button purple big"><i class="add user icon"></i></button>`

When the user screen gets smaller than 999px I would like it to become:

`<button class="ui icon button purple tiny"><i class="add user icon"></i></button>`

In my stylesheet I have this:

```
@media (max-width: 999px) {

}
```

I usualy just set width/height inside this part of my code so when the user screen gets smaller than 999px it applies that new width/height. But in the case of semantic UI I dont want to change manually the size (width/height) of the button, can I just replace big with tiny in someway inside a CSS file?

**Comment by Banandrew** [comment]
Hi @batata004,

There’s an option to do it with a bit of JavaScript if you’re interested, but CSS is just a styling language, it cannot actually edit the HTML. If you want to do it with just CSS, I’d suggest to copy the `.big` styles under a different namespace, like, `.my-button-class`, and then copy the `.tiny` styles to a `.my-button-class` under a media-query.

So, copy those styles and a media-query to `installation_folder/src/site/elements/button.overrides`, then rebuild the framework. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by batata004** [comment]
I am really sorry I thought semantc ui had some clever workaround. I am amazed how semantic ui works, it's simple and really beautiful !

Sorry and thank you for helping. I know how to do this with JS using onresize event but I thought there was someway to do this with pure css.

**Comment by Banandrew** [comment]
@batata004 No worries, join us on Gitter if you have other questions!
