### ISSUE TITLE
Catalonia's flag is absent

### ISSUE THREAD

**Issue by metallimiach** [Semantic-Org/Semantic-UI#5043]
In list of flags the Catalonia's flag is absent [https://en.wikipedia.org/wiki/Catalonia](url)

**Comment by vinayakkulkarni** [comment]
Catalonia isn't a country itself, it's a part of Spain which is a country.

From Wikipedia itself:
>On 9 November 2015, Catalan lawmakers approved a plan for secession from Spain by 2017 with a vote 72 to 63. The plan was suspended by the Spanish Constitutional Court
