### ISSUE TITLE
Wrong Date in Release Notes

### ISSUE THREAD

**Issue by sailerinteractive** [Semantic-Org/Semantic-UI#5046]
Great to see a new release! But we have 2017 already :-)

https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md

**Comment by jlukic** [comment]
Oops

**Comment by vinayakkulkarni** [comment]
Jack fixed it in https://github.com/Semantic-Org/Semantic-UI/commit/e91093724a7177ee692fd9a7c501d262611e9069
