### ISSUE TITLE
[Installation] Gulp install fails on missing 'wrench' dependency for SUI 2.2.8

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#5047]
Hi,

First of all huge thanks for the 2.2.8 rollout! Amazing job!

I've found that there's a `wrench` dependency missing when doing `gulp install`. 

Easy **workaround** would be to do a `npm install --save wrench` right after `npm install` fails at `gulp install` point.

Installing `wrench` globally doesnt work for some reason.

I am building SUI on Win 10. npm version `3.10.10`, node version `v6.9.5`

**Comment by guzuomuse** [comment]
+1
Os:
win7
versions:
node v6.9.5
npm  v4.1.2
gulp 3.9.1

**Comment by jbwl** [comment]
+1
OS: Mac OS Sierra

**Comment by jaimehing** [comment]
Is "adding wrench" as a dependency in the package the fix for this or wrench will be replaced since it's already deprecated? 

+1 on your temporary fix @andreyvk. thanks!

**Comment by jpsirois** [comment]
I got the same issue with this env :
```
OS   : macOS Sierra 10.12.3 (16D32)
node : 7.5.0
npm  : 4.1.2
gulp : 3.9.1
```

**Comment by brianespinosa** [comment]
@jaimehing `wrench` should definitely be replaced since it is deprecated.

**Comment by jlukic** [comment]
I'll look into something for this today

**Comment by jlukic** [comment]
Looks like I forgot to change a path in the install script. Sorry, released fix as `2.2.9`

**Comment by Banandrew** [comment]
The author of Wrench actually posted about it a few hours ago: https://github.com/Semantic-Org/Semantic-UI/issues/3404#issuecomment-281388078

**Comment by rlightner** [comment]
@jlukic 2.2.9 doesn't appear to be in the latest pull from git/master

**Comment by jlukic** [comment]
Wrench works well enough and it's not worth the testing to port the calls to a newer library at this time.
