### ISSUE TITLE
Menu - fixed menu has low z-index 

### ISSUE THREAD

**Issue by patie** [Semantic-Org/Semantic-UI#505]
Hi,

there is problem with fixed menu - his z-index is lower than corner label in form input.

**Comment by osmanraifgunes** [comment]
Same problem if menu is initialized with jq : 

`$('.main.menu').visibility({ type: 'fixed' });`

**Comment by ddresch** [comment]
Can confirm same issue here @osmanraifgunes 

Using the `fixed` class directly helps in this case.
