### ISSUE TITLE
CSS Only split of has semantic.min.js missing from 2.2.8

### ISSUE THREAD

**Issue by stefandoorn** [Semantic-Org/Semantic-UI#5050]
The 2.2.8 build introduced kind of a breaking change to the CSS Only split of. It might never have been intended to have a minified file in that repository, but now it's missing in the latest version and that is kind of a breaking change to (lots of) users. I'm posting it in here as I have no clue whether the split of repository is monitored very often.

https://github.com/Semantic-Org/Semantic-UI-CSS/issues/29

**Comment by jlukic** [comment]
The build script just ate some of the files

**Comment by vinayakkulkarni** [comment]
https://github.com/Semantic-Org/Semantic-UI-CSS/issues/29#issuecomment-281452097
