### ISSUE TITLE
2.2.8 release notes mention dropdown parameter filterAPIResults, but dropdown.js code uses filterRemoteData

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5051]
Not sure which one is correct, but the 2.2.8 release notes mention dropdown parameter `filterAPIResults` , but the dropdown.js code uses `filterRemoteData`. 

_**Dropdown** - Added new setting  `filterAPIResults` , when set to  true  API will be expected to return the complete result set, which will then be filtered clientside to only display matching results. Thanks @enix223 #4815_

dropdown.js 
```javascript
718                 if(settings.filterRemoteData) { 
719                   module.filterItems(searchTerm); 
720                 } 
```

**Comment by jlukic** [comment]
Sorry I've fixed the release notes, they corresponded with an earlier name from a pull request.
