### ISSUE TITLE
[Dropdown] Search in menu not selecting on click

### ISSUE THREAD

**Issue by VictorLeach96** [Semantic-Org/Semantic-UI#5052]
As of 2.2.8 search in menu dropdowns seem not to be working correctly. 

The options do not select through clicks however sometimes it does works once. Navigating and selecting through the keyboard does work correctly.

I have also noticed the dropdown is dismissed on touch down instead of touch up which may be causing the issue.

This can be reproduced using the official Semantic UI website.
http://semantic-ui.com/modules/dropdown.html#search-in-menu

Thanks!

**Comment by Banandrew** [comment]
Moving the issue to #5113.
