### ISSUE TITLE
[Fixed Table + Dropdown] - Dropdown options can not be displayed on fixed table

### ISSUE THREAD

**Issue by NoSoyTsundere** [Semantic-Org/Semantic-UI#5054]
**Steps to Reproduce**
1. Use a `.ui.fixed.table` or `.ui.fixed.single.line.table`
2. Insert `.ui.dropdown` inside a `td`
3. Open dropdown

**Expected**
Dropdown options must be displayed

**Result**
Dropdown options are not displayed

**Note**
`direction: 'upward'` does not make any difference

**Testcase**
http://jsfiddle.net/c599ak7p/6/

**Comment by Banandrew** [comment]
See #3246.

**Comment by NoSoyTsundere** [comment]
Thx @Banandrew , I'll look into it.

Cheers.
