### ISSUE TITLE
Use <span> (or other tag) for icons instead of <i>

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#506]
According to [HTML5Doctor](http://html5doctor.com/i-b-em-strong-element/):

> <i> — was italic, now for text in an “alternate voice”, such as transliterated foreign words, technical terms, and typographically italicized text

Using it for icons seems to go against the "semantic" part of "Semantic-UI". I believe <span> is the most semantically neutral and most qualified tag that I'm aware of for displaying icons.

**Comment by thaeny-dev** [comment]
I would love that the SUI don't bind the icons to the i-tag. I have a case in combination with PrimeNG-controls where it would be very handy to be able to bind icons to any kind of tags (in this case add an icon to tabpanel-header without extra code => span-element)
