### ISSUE TITLE
Serve the semantic ui website via HTTPS (SSL)

### ISSUE THREAD

**Issue by amingilani** [Semantic-Org/Semantic-UI#5060]
It's 2017, even through the semantic-ui website has no authenticated areas, and is a flat site, it's best practice to serve it via HTTPS.

If you're using Cloudflare's free DNS, switching to SSL is a click away.

**Comment by vinayakkulkarni** [comment]
It's something that is considered, but since this has nothing to do with the SUI framework, closing this.

For any suggestions like these, just ping us on [gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [SUI Forums](http://forums.semantic-ui.com/)

**Comment by vinayakkulkarni** [comment]
PS. There's already an open issue for this: https://github.com/Semantic-Org/Semantic-UI-Docs/issues/281
