### ISSUE TITLE
The Future of Themes

### ISSUE THREAD

**Issue by ktmn** [Semantic-Org/Semantic-UI#5062]
From: http://learnsemantic.com/developing/customizing.html

> ## The Future of Themes
> 
> Semantic provides out of the box several first party packaged themes, which are intended to showcase how easy it is to customize UI designs with Semantic. A specialized hub for Semantic themes is in the works which will make packaged themes more ubiquitous.

---

Is that plan still in motion?

**Comment by romaninsh** [comment]
http://semantic-ui-forest.com I've seen this and have some plans of my own. There was some other site I think.
