### ISSUE TITLE
ui grid container not working properly on safari

### ISSUE THREAD

**Issue by ydaniels** [Semantic-Org/Semantic-UI#5066]
specifying something like this between  three to sixteen  `<div class="ui three column   stackable grid container">` the last column does not stay on the same row instead it starts on the next row.

**Comment by vinayakkulkarni** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
