### ISSUE TITLE
Intuitive Javascript

### ISSUE THREAD

**Issue by robertocabellon** [Semantic-Org/Semantic-UI#5067]
After reading the following code sample, at home page, on section "Intuitive Javascript".

`$('select.dropdown')
  .dropdown('set selected', ['meteor', 'ember'])
;`

wouldn't be more intuitive something like follows?

`$('skills').dropdown.selected = ['meteor', 'ember'];`

**Comment by italomaia** [comment]
I believe the first example could improve, but the second is not it. Too imperative. Maybe something like:

`$('select.dropdown') .dropdown().set('selected', ['meteor', 'ember']);`

Although the first example looks good.
