### ISSUE TITLE
Documentation typo and question

### ISSUE THREAD

**Issue by duselguy** [Semantic-Org/Semantic-UI#5071]
Hello,
1) Typo in the doc at [http://semantic-ui.com/behaviors/form.html](http://semantic-ui.com/behaviors/form.html)
")" is missed in the code:
`if( $('.ui.form').form('is valid') {
  // form is valid (both email and name)
}`
2) Question for examples at [http://semantic-ui.com/behaviors/form.html#/examples](url)
Blur event causes only pink for the invalid field.
Submit causes pink for the invalid field and message.
Is it possible to provide the same behavior for blur?
Thanks,
LP

**Comment by vinayakkulkarni** [comment]
There's a PR sent by @Gsuz. Closing this since that PR will probably be merged soon.

PR: https://github.com/Semantic-Org/Semantic-UI-Docs/pull/293

**Comment by Banandrew** [comment]
Hi @duselguy, on your second question, we’ll be tracking the issue in a separate thread #3574.
