### ISSUE TITLE
[Dropdown] Add new commands to be able to add new options dynamically without having to do a `.dropdown('refresh')`

### ISSUE THREAD

**Issue by DanAtShenTech** [Semantic-Org/Semantic-UI#5076]
I view this as a very serious problem.  It makes dropdowns very unusable.  Here is a Fiddle in which the behavior can be seen in about five seconds:
https://jsfiddle.net/84un9dq6/

**Comment by DanAtShenTech** [comment]
After more experimenting, I just discovered that inserting a .dropdown('refresh') BEFORE issuing the 'set selected' causes it to work.  I'll try to issue a pull request to explain adding elements dynamically.  Would be nice if there were two new commands:  'add item' and 'add item selected'.

**Comment by kmd1970** [comment]
We also need this command to work if using a SELECT instead of a DIV.

Add a new "replace" behavior?
```javascript
$('.ui .dropdown').dropdown('replace', [ {
        // name displayed in dropdown
        "name"  : "Choice 1",
         // selected value
        "value" : "value1",
         // name displayed after selection (optional)
        "text"  : "Choice 1"
         // whether field should be displayed as disabled (optional)
        "disabled"  : false
       },
      {
        "name"  : "Choice 2",
        "value" : "value2",
        "text"  : "Choice 2"
      },
      {
        "name"  : "Choice 3",
        "value" : "value3",
        "text"  : "Choice 3"
      },
      {
        "name"  : "Choice 4",
        "value" : "value4",
        "text"  : "Choice 4"
      }]);
```
