### ISSUE TITLE
[Button]Error show in button groups that contain conditionals

### ISSUE THREAD

**Issue by cherryzhu** [Semantic-Org/Semantic-UI#5077]
Error snap:
![qq 20170224111935](https://cloud.githubusercontent.com/assets/7692520/23289202/21d88966-fa83-11e6-8ca2-7b35e1f5b609.jpg)
Code Source:
```
<div class="ui buttons">
	<button class="ui button">Cancel</button>
	<div class="or">or</div>
	<button class="ui button">Save</button>
</div>
```

This issue occurs in Chrome(version 56.0.2924.87) and Firefox(version 45.7.0) browser, the version of Semantic UI is 2.2.7.

I get the sample from [http://www.semantic-ui.cn/elements/button.html#conditionals](http://www.semantic-ui.cn/elements/button.html#conditionals), even though I add a 'positive' class into 'Save' button, the error still occurs, please check, thanks.

**Comment by Banandrew** [comment]
Hi @cherryzhu, I don’t see the issue on the Chinese version of the documentation. You don’t need to put “or” text inside of the `<div class="or">or</div>`, it should look like so:
```HTML
<div class="ui buttons">
    <button class="ui button">Cancel</button>
    <div class="or"></div>
    <button class="ui button">Save</button>
</div>
```

**Comment by cherryzhu** [comment]
Hi Banandrew, thanks for your comment.
