### ISSUE TITLE
[Dropdown] Multiple Selection Should Allow Overriding Label Display Poperty

### ISSUE THREAD

**Issue by RenaldasK** [Semantic-Org/Semantic-UI#5080]
I ran into issues using the dropdown multi select where the label elements representing selections have inline style `display: block !important;` which is impossible to override. I will try to recreate the issue in fiddle and post it here.

**Comment by vinayakkulkarni** [comment]
Hi @RenaldasK, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by RenaldasK** [comment]
In fact the dropdown multiselect is broken and won't allow selecting anything manually at all anymore! So I can't recreate the issue above. Fiddle: http://jsfiddle.net/dj6qor6v/1/

**Comment by Banandrew** [comment]
Hi @RenaldasK, your last message is a known issue (#5052) that appeared with one of the latest releases (2.2.8). We’ll keep this issue opened until the dropdown’s fixed; I’ll remind you about it then.
