### ISSUE TITLE
Inconsistency with size of elements

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5081]
Hi,

I assume that when I use certain size (button, dropdown, input) like big, huge, medium... the height of the elements is standard across all elements. That's true, I realized the height is indeed very standard across most elements except between button and dropdown.

Lets take a look at these 2 elements:

```

                <div class="ui fluid search selection dropdown medium elemento_ocorrencia" style="width:400px;">
                
                    <input type="hidden" name="ocorrencia">
                    
                    <i class="dropdown icon"></i>
                    
                    <div class="default text">Busque por ocorrências</div>
                    
                    <div class="menu">
                        
                        
                            <div class="item" data-value="teste">test</div>
                                                  
                   
                    </div>
                
                </div>   
                  
                <script type="text/javascript">
            
                $(".elemento_ocorrencia").dropdown();
        
                </script>
      






            <button class="ui icon button red medium" style="border-radius:0px 4px 4px 0px;"><i class="search icon"></i></button>
        
        
```

See image attached, there are 2 or 3 pixels difference in height between these 2 elements and it makes very hard to place this elements one close to another cause it becomes clear the difference in height and it looks like I was not paying attention to the design of the website I am doing.

Is there any work around?
![zoom](https://cloud.githubusercontent.com/assets/8988923/23306770/b3170b78-fa83-11e6-854f-d0ebfe8fe3a3.jpg)

**Comment by vinayakkulkarni** [comment]
Hi @batata004 , please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

Cheers!

**Comment by batata004** [comment]
Sorry! Here it comes -> http://jsfiddle.net/efp8z6Ln/465/

**Comment by batata004** [comment]
Hi I cant understand your last label NEEDS TEST CASE. I already publishd a very easy text case in jsfiddle as you asked me @vinayakkulkarni . What should I do so you can test?

**Comment by NoSoyTsundere** [comment]
@batata004 please check

> vinayakkulkarni **removed** the Needs Test Case label 4 hours ago

**Comment by batata004** [comment]
thanks!

**Comment by Banandrew** [comment]
Hi @batata004, wrap everything in a `<div class="ui action input">`.

**Comment by batata004** [comment]
@Banandrew  would you mind explaning why should I use `<div class="ui input">`? Actually you said I should use `<div class="ui action input">` but I tried just `<div class="ui input">` and it worked. Why?

**Comment by Banandrew** [comment]
@batata004 sure, `.action` class sets some styles for its child elements, and if you remove the `style` attribute from the red button, and remove the `.action` class, the red button will lose `border-radius`. I’d suggest to inspect the children of `.action` when it’s set to see what it does. You can read all about it [here](http://semantic-ui.com/elements/input.html#action) in a `Veriations -> Action` section.
