### ISSUE TITLE
[Dropdown] menu can't search item text/description depending on order.

### ISSUE THREAD

**Issue by komirad** [Semantic-Org/Semantic-UI#5086]
See: http://codepen.io/anon/pen/RpNZJa

The snippet below will only search the value/description, not the text. However, by removing just the description, I am able to start searching text.

This has to do with the order of the description/text. Only the FIRST span within item can be searched.

```
<div class="ui fluid search selection dropdown">
    <input type="hidden" name="search">
    <i class="dropdown icon"></i>
    <div class="default text">Select an items</div>
    <div class="menu">
        <div class="item" value="value">
                <span class="description">Description</span>
                <span class="text">Text</span>
        </div>
    </div>
</div>
```

**Comment by Banandrew** [comment]
Hi @komirad, I’ve just realized you can use `fullTextSearch: true` to enable a fuzzy full text search and fix the issue:
```JS
$('.ui.dropdown')
  .dropdown({
    fullTextSearch: true
  })
```
I will submit a PR to the documentation repository to make it clear; closing the issue as resolved.
