### ISSUE TITLE
[Dropdown] Add progress component integration

### ISSUE THREAD

**Issue by tripflex** [Semantic-Org/Semantic-UI#5087]
Would be great if it was possible to integrate the progress component with the dropdown.  Specifically I was looking for this as a way to give more feedback to the user when using a search dropdown.

It seems like the progress semi works if you set it as top/bottom attached, but would be great if the entire background gave some type of progress indication.

**Comment by kmd1970** [comment]
Dropdown already has a spinner to indicate remote searching, not sure how that would work with a progress bar.
