### ISSUE TITLE
[Modal] Modal position at the first time is wrong

### ISSUE THREAD

**Issue by huyphung1602** [Semantic-Org/Semantic-UI#5088]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**
The Modal should in the middle  at first time the page is loaded

**Result**
The Modal below the middle  at first time the page is loaded

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by Banandrew** [comment]
Hi @huyphung1602, your test case is empty. Please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
