### ISSUE TITLE
[Form] - dropdown js error

### ISSUE THREAD

**Issue by ferrisz** [Semantic-Org/Semantic-UI#5089]
**Steps to Reproduce**
$('select.dropdown')
  .dropdown()
;

**Expected**
$('.selection.dropdown')
  .dropdown()
;

**Comment by Banandrew** [comment]
Hi, I’m not sure what you mean, is it a typo somewhere? If it’s not, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
