### ISSUE TITLE
[Header] Add sub header colors

### ISSUE THREAD

**Issue by traverse** [Semantic-Org/Semantic-UI#5091]
I would like to request colors for sub headers because I've run into situations where it would be quite nice to be able to color them just like a regular header.

If there's any reason why you wouldn't want to support this please let me know.

**Comment by lubber-de** [comment]
Already possible: Just add the desired color class

```html
<h2 class="ui orange sub header">
      Price
    </h2>
```
Btw: In [Fomantic-UI](https://fomantic-ui.com) you can even add your own color names at a central place (not only for (sub) headeer) by adjusting https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/globals/colors.less
