### ISSUE TITLE
I did not found Nuget icon

### ISSUE THREAD

**Issue by metatypeman** [Semantic-Org/Semantic-UI#5092]
The icon of this resource: https://www.nuget.org/

I did not found this icon on http://fontawesome.io/icons/.

This icon would be much helpful for C # developers.

**Comment by brainscript** [comment]
@metatypeman https://github.com/FortAwesome/Font-Awesome/issues/2201
**+1** that issue and close this one. The SemanticUI team is not responsible for the icons.

**Comment by vinayakkulkarni** [comment]
As @brainscript said, once Font-Awesome releases a update, it'll probably be merged with SUI.
Cheers!
