### ISSUE TITLE
[API] Caching, API endpoints (URL) and methods (GET,POST) used.

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5093]
I might be wrong, but it appears that when **cache is ON** (default), a new AJAX request is only made when 
the actual API endpoint (URL) string is changed. This works for the default **GET** method because query parameters are included in the URL and changes every time you send a new value to the server. 

However, when using **POST** method, the API endpoint (URL) string remains the same because the parameters are sent differently. This causes only the first Ajax request to be sent to the server since the URL string never changes.

The code that evaluates whether to send a new Ajax request to the server (when cache is ON) should be changed to look for changes in the sent parameters (_{query}, {custom}, post variables_) and not the URL string. 

The jsfiddle below works fine because I am using default **GET** method  (with `{letter}` in the URL and `settings.urlData.letter = val` in beforeSend) and `cache:true`. However, if I switch it to **POST** (with `settings.data.letter = val` in beforeSend) only the first request is sent.  

One workaround is to also include the {letter} parameter in the URL for POST requests.

http://jsfiddle.net/kmd1970/bxcr3h8j/

(**Please note** this link needs to be http:// for the remote ajax to work properly and the API endpoint used in the example doesn't not allow POST requests)

**Comment by kmd1970** [comment]
```javascript
write: {
          cachedResponse: function(url, response) {
            if(response && response === '') {
              module.debug('Response empty, not caching', response);
              return;
            }
            if(window.Storage === undefined) {
              module.error(error.noStorage);
              return;
            }
            if( $.isPlainObject(response) ) {
              response = JSON.stringify(response);
            }
            sessionStorage.setItem(url, response);
            module.verbose('Storing cached response for url', url, response);
          }
        }
```

**Comment by kmd1970** [comment]
Possible solution?

```javascript
read: {
          cachedResponse: function(url) {
            var
              response
            ;
            if(window.Storage === undefined) {
              module.error(error.noStorage);
              return;
            }
            if (settings.method.toLowerCase() === 'post' && !$.isEmptyObject(settings.data)){
	       var v = '';
	       $.each(settings.data, function(index, val ) {
                  v += '|'+val;
	       });
	       response = sessionStorage.getItem(url+v);
            }else{
               response = sessionStorage.getItem(url);
            }
            module.debug('Using cached response', url, response);
            response = module.decode.json(response);
            return response;
          }
},
write: {
          cachedResponse: function(url, response) {
            if(response && response === '') {
              module.debug('Response empty, not caching', response);
              return;
            }
            if(window.Storage === undefined) {
              module.error(error.noStorage);
              return;
            }
            if( $.isPlainObject(response) ) {
              response = JSON.stringify(response);
            }
            if (settings.method.toLowerCase() === 'post' && !$.isEmptyObject(settings.data) ){
	      var v = '';
	      $.each(settings.data, function(index, val ) {
                v += '|'+val;
	      });
		sessionStorage.setItem(url+v, response);
            }else{
	        sessionStorage.setItem(url, response);
           }
          module.verbose('Storing cached response for url', url, response);
}
```

**Comment by lubber-de** [comment]
We fixed that in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2047
