### ISSUE TITLE
Responsive page is too wide on Safari

### ISSUE THREAD

**Issue by teatoast** [Semantic-Org/Semantic-UI#5105]
Responsive grids aren't properly spanning the correct page width for me, in the Safari browser on OSX and iOS.

This can be seen on examples/responsive.html:

This is how it loads:

<img width="1680" alt="screen shot 2017-03-01 at 07 11 03" src="https://cloud.githubusercontent.com/assets/26107491/23449638/5f861434-fe4f-11e6-9c21-95c35898b46a.png">

And you can see here that you can scroll horizontally, showing some whitespace on the right:

<img width="1680" alt="screen shot 2017-03-01 at 07 11 14" src="https://cloud.githubusercontent.com/assets/26107491/23449670/73e33ede-fe4f-11e6-863e-9bd4d409719c.png">

It doesn't do this on Firefox or Chrome.

This is especially noticeable on mobile because the page will shift around as you scroll down.

Any thoughts? Thanks.

**Comment by Banandrew** [comment]
This issue might be related: #5066.
