### ISSUE TITLE
The accordion close nested problem. I set the settings attribute closeNested true, when I close the outter accordion, the inner accordion doesn't close

### ISSUE THREAD

**Issue by YueLi386888** [Semantic-Org/Semantic-UI#5108]
The accordion close nested problem. I set the settings attribute closeNested true, when I close the outter accordion, the inner accordion doesn't close.
I appreciate your help.
My html is below:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="./Semantic-UI-master/dist/semantic.min.css">
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src="./Semantic-UI-master/src/definitions/modules/accordion.js"></script>
    

    <script language='javascript'>
        $(document).ready(function(){

            $('.ui.accordion').accordion();

        });
    </script>
</head>
<body>
<div class="ui vertical accordion menu">
    <div class="item">

        <a class="active title">
            <i class="dropdown icon">the</i>
            Size
        </a>

        <div class="active content">
            <div class="ui form">
                <div class="grouped fields">

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="size" value="small">
                            <label>Small</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="size" value="medium">
                            <label>Medium</label>
                        </div>
                    </div>

                    <div class="item">
                        <a class="title">
                            <i class="dropdown icon"></i>
                            water
                        </a>
                        <div class="content">
                            <div class="ui form">
                                <div class="grouped fields">

                                    <div class="field">
                                        <div class="ui radio checkbox">
                                            <input type="radio" name="size" value="small">
                                            <label>blue</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    
</div>
</body>
</html>

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by YueLi386888** [comment]
Thank you for your follow up, I have changed the code by myself.
