### ISSUE TITLE
[Dropdown] Dropdown with scrolling menu are not selecting

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#5113]
Visible in docs here:
http://semantic-ui.com/modules/dropdown.html#search-in-menu

Value is not selecting

**Comment by philrykoff** [comment]
If you enter a term in the search box and then click on an item, it works. Only if you directly click on an item, it doesn't work.

**Comment by Banandrew** [comment]
Also, from #5126:
>Now click exactly on the circle next to the selected tag. Nothing will happen despite the highlight.

**Comment by jlukic** [comment]
I'm going to fix this tomorrow

**Comment by jlukic** [comment]
It boils down to a single check in `search.blur`... 🤕

**Comment by jlukic** [comment]
It boils down to a single check in `search.blur`... 🤕
