### ISSUE TITLE
[Grid] Grid wraps columns in 2.2.9

### ISSUE THREAD

**Issue by dmagunov** [Semantic-Org/Semantic-UI#5119]
On the  latest Semantic release (2.2.9) grid wraps columns into another row on sixteen wide grid. On the  2.2.7 release all works perfectly. Issue found on MacosX under latest Safari/Firefox

**Comment by Banandrew** [comment]
Hi @dmagunov, can you please confirm that it can be seen on [this page](http://semantic-ui.com/examples/grid.html)?

**Comment by dmagunov** [comment]
Nope, all works fine in your example. I think the problem happens then inside the column placed the no-wrap fluid block.
