### ISSUE TITLE
How to combine the following two together

### ISSUE THREAD

**Issue by yangjianyi** [Semantic-Org/Semantic-UI#5120]
### How to combine the following two together？
```javascript
$(".ui.dropdown").dropdown('set selected', 5);
$(".ui.dropdown").dropdown({
    onChange: function(value) {
      var name = $(this).eq(0).attr('name');
      srcuritySetting(name, value, 'on');
    }
  });
```

**Comment by Banandrew** [comment]
Hi @yangjianyi, if I understood you correctly:
```JS
$('.ui.dropdown')
  .dropdown({
    onChange: function(value) {
      var name = $(this).eq(0).attr('name')
      srcuritySetting(name, value, 'on')
    }
  })
  .dropdown('set selected', 5)
```
If I didn’t, please elaborate on your question, what’s the problem exactly?

In any case, thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
