### ISSUE TITLE
[API] Add timeout property

### ISSUE THREAD

**Issue by ferrao** [Semantic-Org/Semantic-UI#5121]
With jQuery i could trigger and handle server timeouts with a timeout property:

```
$.ajax({
   type: 'POST',
   timeout: 5000,
   ....
})
```

There does not seem to be any way to achieve this using the api, would be nice to have a timeout setting to pass down to jQuery.

**Comment by ferrao** [comment]
I feel stupid for saying this, but even if not present on the documentation, I tried to set a timeout property on the `api` settings object and it worked, causing an XHR abort

I can not get the reason for such an abort from the api handler, but I can live with that.

**Comment by Banandrew** [comment]
I’m not sure if this should stay as enhancement, or be labeled as a documentation issue. The component [passes](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/api.js#L231) whatever properties a developer set to `$.ajax()`, so it’s possible to use all `$.ajax()`’s properties; on one hand, some of those properties can be better integrated into the component, on the other, it doesn’t matter all that much, and probably can’t be tackled for a while—maybe we should just explain it in the documentation.

**Comment by ferrao** [comment]
I agree, having it explained in the documentation is sufficient for this issue.

**Comment by ferrao** [comment]
I closed it by accident, reopening again..

**Comment by jlukic** [comment]
Any settings passed in to API will also be passed along to `$.ajax` allowing you to use any of jQuery's normal params.

**Comment by jlukic** [comment]
Added note to docs in next release
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/7eb7c9555e43af8b43fdb9cfe11461e9f757ffb6
