### ISSUE TITLE
[Dropdown] Dropdown is not opening if clicked on the label circle.

### ISSUE THREAD

**Issue by arapoport** [Semantic-Org/Semantic-UI#5126]
http://semantic-ui.com/modules/dropdown.html#search-in-menu

1. Select any value (first you might need to enter some text to be able to select, it's another bug). The dropdown will close and show the selected value.
2. Now click exactly on the circle next to the selected tag. Nothing will happen despite the highlight.

Happens in Chrome 56 and Firefox 51.

**Comment by Banandrew** [comment]
See #5113.
