### ISSUE TITLE
[Icon] `.id.card.icon` and `.address.card.icon` inherit the card component’s rules

### ISSUE THREAD

**Issue by kevinresol** [Semantic-Org/Semantic-UI#5128]
I think this is because the "card" in the icon name tricked the "cards" wrapper to believe it is a card object.

JSFiddle: https://jsfiddle.net/oL8792km/

**Comment by Banandrew** [comment]
Hi @kevinresol, I’m not seeing the problem with inheritance: I [tried giving](https://jsfiddle.net/Banandrew/oL8792km/2/) it a different namespace, and it looks exactly the same, am I missing something?

**Comment by kevinresol** [comment]
<img width="610" alt="screen shot 2017-03-05 at 5 46 27 pm" src="https://cloud.githubusercontent.com/assets/1103788/23586217/b25bf654-01cb-11e7-8e5b-0bce3242311e.png">

This is what I see, using Chrome Version 56.0.2924.87 (64-bit)

**Comment by kevinresol** [comment]
Inspect:

<img width="722" alt="screen shot 2017-03-05 at 5 49 29 pm" src="https://cloud.githubusercontent.com/assets/1103788/23586246/2542b2e8-01cc-11e7-906f-fd6e3752a1dc.png">

**Comment by Banandrew** [comment]
@kevinresol Got it, for some reason, I don’t see it using the same Chrome version as you, but was able to reproduce it in Firefox. The namespacing does seem to collide; we’ll fix it, thanks!

**Comment by Banandrew** [comment]
The PR was merged, closing as resolved.
