### ISSUE TITLE
saveRemoteData setting not work in dropdown with remote content

### ISSUE THREAD

**Issue by brainkit** [Semantic-Org/Semantic-UI#5130]
Semantic UI - 2.2.9
I set saveRemoteData:false in settings dropdown, but data still save always in Session Storage.
To fix this I add string "&& settings.saveRemoteData" to line 19987.
Code implemented so http://dl4.joxi.net/drive/2017/03/06/0005/2599/342567/67/b647644179.jpg

**Comment by jlukic** [comment]
I misread this issue. The code you have in your jpg is in `API` a separate component without remoteContent setting. 

You can prevent local caching of dropdown using 

```javascript
$('.ui.dropdown')
  .dropdown({
    apiSettings: {
      cache: false
    }
  })
;
```

As described in the docs

**Comment by sahilbest999** [comment]
> u can prevent local caching of dropdown by passing in specific API settings like

no it does not work, please fix the issue
