### ISSUE TITLE
iOS / Material Design Theme packs available?

### ISSUE THREAD

**Issue by pke** [Semantic-Org/Semantic-UI#5132]
I wonder if there are any iOS 10 and Android Material Design them packs available?
The default style is nice but doesn't look very native on any platform.

**Comment by philrykoff** [comment]
From the github repo (https://github.com/Semantic-Org/Semantic-UI/tree/master/src/themes), I would say: no.

**Comment by peacemakr** [comment]
is it possible to submit an app to App Store or Play store without an iOS/Android theme?  

Did anybody have success getting a Semantic app approved by App store?

**Comment by pke** [comment]
You are not required to follow any guidelines

**Comment by pke** [comment]
You are not required to follow any guidelines

**Comment by pke** [comment]
You are not required to follow any guidelines

**Comment by pke** [comment]
You are not required to follow any guidelines
