### ISSUE TITLE
[Checkbox]： how to use 3 states？

### ISSUE THREAD

**Issue by Dreampie** [Semantic-Org/Semantic-UI#5133]
like slide，left， middle，right  => No，UnDo，Yes

**Comment by Banandrew** [comment]
Hi @Dreampie, the checkbox doesn’t have an indeterminate state yet, but there was a proposal a few years ago, take a look at the example in the first post: #3216. Closing as a duplicate.

**Comment by lubber-de** [comment]
Prepared for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/491
See https://jsfiddle.net/cbyp1ego/
