### ISSUE TITLE
Multiple validation form and error message ui

### ISSUE THREAD

**Issue by BenedictusStevenAgre** [Semantic-Org/Semantic-UI#5134]
Sorry, i'm new in semantic ui. please help me on this case.

I have 2 form in 1 page. 1 for add item, 1 for edit selected item in semantic modal. how can i specify "ui.error.message" for each form? thanks.

**Comment by Banandrew** [comment]
Hi @BenedictusStevenAgre,

I didn’t quite understand what you’re trying to do, can you please elaborate or fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to create a test case? The following paragraph is a standard reply, but you can continue posting in this thread, and I’ll try to help you out.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
