### ISSUE TITLE
CSS Error

### ISSUE THREAD

**Issue by vandolphreyes** [Semantic-Org/Semantic-UI#5136]
In semantic.css, line 10292. Im not sure if it's a typo or added with a purpose (though I can see some sites also do this to prevent a css code to work) but this code is giving me hassle in my view. In PHPStorm, its giving me error. Also Im not sure if it's okay that I will fix it because maybe it will cause some problems.

![list_store - c__wamp64_www_list_store - _public_semantic-ui-css-master_semantic css - phpstorm 2016 3 2017-03-08 10 31 36](https://cloud.githubusercontent.com/assets/20592175/23687669/973151dc-03ea-11e7-9977-df4d856bc032.png)

**Comment by philrykoff** [comment]
It seems as if PHPStorm cannot handle CSS escaping sequences.

Here is an online escaper that shows that the sequence is correct: https://mothereff.in/css-escapes#0500px

**Comment by vandolphreyes** [comment]
I see, thanks for the response.
