### ISSUE TITLE
[Dropdown] - Add search for long dropdowns

### ISSUE THREAD

**Issue by patie** [Semantic-Org/Semantic-UI#514]
Hi,

what about searching in dropdown in case where is too many items there ? (for example countries)

something like http://ivaynberg.github.io/select2/

**Comment by akshayrpatel** [comment]
The Multiple Search Selection Dropdown in Semantic UI auto selects an option even if we don't want to. Eg : I select all my choices and then I click anywhere else on the page or press esc, the dropdown menu goes away but ends up selecting an option. 
Using Semantic UI - 2.2.4

**Comment by jlukic** [comment]
@akshayrpatel `forceSelection: false` setting
