### ISSUE TITLE
dimmer() on a child element

### ISSUE THREAD

**Issue by z1haze** [Semantic-Org/Semantic-UI#5140]
I would like to use the dimmer() function to on a child element. For example a 'card' component, I would prefer to have the dimmer be set when hovering anywhere on the card, but only dim the image in the card. I cannot seem to figure out how to do this. when I use dimmer on the card, it dims the whole card. and I don't see any options to determine which element gets dimmed

**Comment by Banandrew** [comment]
Hi @z1haze,

That’s basic jQuery, here’s the demo: http://jsfiddle.net/efp8z6Ln/482/

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by z1haze** [comment]
Thank you for taking the time to explain this.
