### ISSUE TITLE
[Docs] Add clear, step-by-step instructions on how to build dist files with a packaged theme, e.g. "Chubby"

### ISSUE THREAD

**Issue by jbwl** [Semantic-Org/Semantic-UI#5147]
I've been trying for a whole day to build semantic ui dist files with the packaged "Chubby" theme, but was not able to do so. I think the exact process should be a part of the documentation.

The current docs make it sound like it is sufficient to change the theme name for the @site variable in theme.config, but as soon as I do this, no css files are being built (only js). 
gulp build only works when all elements in theme.config remain at 'default'.

What's the deal with theme.config. Not all themes have styles for all elements. So do I need to check what elements the theme offers, and manually set *all* available elements to the specific theme in theme.config, or will it be sufficient to set the '@site' variable to the theme I want? Will it be wrong to just set all the variables to 'Chubby', and the build process will fall back on the default theme for all elements which "Chubby" has no styles for?

It's not clear why the packaged theme files exist, but only four themes are installed into my project when I npm install semantic-ui. Do I need to copy over the "Chubby" files? Or set config options pointing to the paths? If yes, where?

What is theme.less for? Anything I need to change in there when I want to try the "Chubby theme" ?

As you see, the currently available docs leave open a lot of room for speculation on how to use one of the packaged themes. For someone not too familiar with npm and gulp there should be better docs for the packaged themes.

**Comment by Banandrew** [comment]
Hi @jbwl, have you figured it out yet?

**Comment by jbwl** [comment]
I'm sorry - no I have not.

**Comment by Banandrew** [comment]
@jbwl The framework consists of components, and every variable in `theme.config` is a component, even `@site` and `@reset`, so when you set `@site` to be `'material'`, you change only that component. Theme name is a name of a folder in `/src/themes`, so it should be lowercase: `@button: 'chubby';`. And while the documentation says this:

>Themes are per component, so although, for example, material themes are available for menu, button, and site, changing all values to "material" will produce an error for components which are not included in that theme.

From what I’ve tested it actually falls back to the default theme, so it might have been changed at some point. I’d like somebody else to confirm it, though.

>but as soon as I do this, no css files are being built (only js).

>but only four themes are installed into my project when I npm install semantic-ui

I tried to replicate your issues, but everything worked as expected, so I don’t think there’re problems with build tools. You can safely add a theme to `src/themes` if it’s not there, or remove it if you don’t need it. If you tell me more about your project’s structure, I might be able to help you fix your build issues—it might be easier to continue this discussion on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by jbwl** [comment]
Thank you for your help! I guess I was under the wrong impression that setting "site" would be sufficient and means that I override the default. When I look up what components the specific theme includes, and set the corresponding variables, then the css gets built OK.
