### ISSUE TITLE
Items with image fullwidth

### ISSUE THREAD

**Issue by kamov** [Semantic-Org/Semantic-UI#5150]
How to make items wtih image in full-width like on mobile, with content on bottom. I mean there is a class for do this?

Like this:
![screen shot 2017-03-10 at 20 16 04](https://cloud.githubusercontent.com/assets/2345000/23809621/ad1fae22-05ce-11e7-8435-07024b6dade6.png)

Thanks

**Comment by Banandrew** [comment]
Hi @kamov,

There isn’t. You can easily create one by adapting mobile styles under a namespace like `.ui.my.items` to `installation_folder/src/site/views/item.overrides`, then rebuilding the framework. Or you could use the card component instead.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
