### ISSUE TITLE
Scrolling a dropdown causes the whole page to scroll also

### ISSUE THREAD

**Issue by callen5914** [Semantic-Org/Semantic-UI#5152]
We have several dropdowns on our pages. One thing we noted is that when you scroll through the options in a drop down the whole page will scroll with it. Any tips?

**Comment by vinayakkulkarni** [comment]
Hey Callen, Can you please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to demonstrate a test case as per the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

Thanks :)

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
