### ISSUE TITLE
Unit of measure 0 is redundant

### ISSUE THREAD

**Issue by kamov** [Semantic-Org/Semantic-UI#5153]
When there is for example margin: 0 it's redundant to add unit, example margin: 0em

**Comment by Banandrew** [comment]
The source in consistent with zero values, and I think that it’s going to be a waste of time to change it just for the sake of changing it, considering that units are getting removed when minified to `semantic.min.css`—it just doesn’t matter.

**Comment by kamov** [comment]
>considering that units are getting removed when minified to semantic.min.css—it just doesn’t matter.

Right, I agree.
