### ISSUE TITLE
semantic-ui.com is redirecting all http:// links to https://semantic-ui.com/ instead of the correct page

### ISSUE THREAD

**Issue by Joshfindit** [Semantic-Org/Semantic-UI#5155]
Examples

* http://semantic-ui.com/elements/button.html
* http://semantic-ui.com/behaviors/form.html
* http://semantic-ui.com/introduction/integrations.html
* *Etc*

On top of being a disruption to people looking up documentation, it's probably having a negative effect on traffic.

**Comment by Banandrew** [comment]
That’s in the process of being fixed: Semantic-Org/Semantic-UI-Docs#281.
