### ISSUE TITLE
[Docs][Icon] Address book icon is missing in the documentation

### ISSUE THREAD

**Issue by peyman-mohamadpour** [Semantic-Org/Semantic-UI#5158]
I notice some icons('address book' for example) have gone from [official website page](https://semantic-ui.com/elements/icon.html). Why and where?

    i.icon.address.book:before {
        content: "\f2b9";
    }

    i.icon.address.book.outline:before {
        content: "\f2ba";
    }

There are so many other ones. Would somebody please help me understand why and where?

How can I see a complete collection, if the documentation does not keep the updated version?

**Comment by Banandrew** [comment]
Hi @peyman-mohamadpour, sorry for the delay, SUI uses [Font Awesome 4.7.0](http://fontawesome.io/icons), so all icons that can be found there also exist in Semantic UI. I’ve opened a PR to the documentation repository, and am closing the issue as resolved.

**Comment by peyman-mohamadpour** [comment]
Thanks for your sincere response. But I dont think If someone can widely use Font Awesome 4.7.0 icons documentation, as THE NAMES ARE DIFFERENT.

For a instance, note the name difference:

`content: "\f00d";`

```
X: Semantic-UI name = `remove`
X: Font Awesome name = `times` & `cross`
```

So please complete the documentation to make it useful, or revert SemanticUI names to that of FA.

Thanks

**Comment by Banandrew** [comment]
@peyman-mohamadpour I understand, what I meant was that you could figure out the icon classes in the meantime, because they’re there in the source—just undocumented. You could also refer to the PR that was opened.
