### ISSUE TITLE
Semantic-UI searchable dropdown width 

### ISSUE THREAD

**Issue by srikalak** [Semantic-Org/Semantic-UI#5160]
How to set the width of dropdown to max width of available options in that dropdown instead of the width of  first element. Every time the width of drop down is set to the first element or the selected element of dropdown. But i would like to set it to the width of max width of available option in that dropdown. Also all the dropdowns are set to same width in the same page but it shouldnt be like that.

**Comment by Banandrew** [comment]
Hi @srikalak, can you please somehow elaborate?

**Comment by srikalak** [comment]
let me explain with an example
 <select class="ui search selection dropdown">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="SK">This should be really long text to see the width of dropdown</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
    </select>

    <select class="ui search selection dropdown">
        
        <option value="AL">Alabama</option>
        <option value="SK">blah blah blah blah</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
    </select>


here i have 2 dropdowns all i want is to set the width of fist drop down to the width of option "This should be really long text to see the width of dropdown" as this is longest text in the options of first drop down options, and set the width of second dropdown to the width of "blah blah blah blah" as this is the longest text in second dropdown option. how do i do this while using semantic UI search drodown? as it sets both dropdown to same size and i dont want that, or to the width of text that is selected or top most option. all iwant is to set the width as traditional dropdown while using semantic UI

**Comment by srikalak** [comment]
<select class="ui search selection dropdown">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="SK">This should be really long text to see the width of dropdown</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
    </select>


 <select class="ui search selection dropdown">
        
        <option value="AL">Alabama</option>
        <option value="SK">blah blah blah blah</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
    </select>

sorry my drop down got messed up in the previous comment

**Comment by srikalak** [comment]
let me explain with an example here are 2 dropdowns


<select class="ui search dropdown">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="SK">This should be really long text to see the width of dropdown</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
    </select>

<select class="ui search dropdown">
    
    <option value="AL">Alabama</option>
    <option value="SK">blah blah blah blah</option>
    <option value="AK">Alaska</option>
    <option value="AZ">Arizona</option>
    <option value="AR">Arkansas</option>
    <option value="CA">California</option>
</select>
 all i want is to set the width of first drop down to the width of option "This should be really long text to see the width of dropdown" as this is longest text in the options of first drop down options, and set the width of second dropdown to the width of "blah blah blah blah" as this is the longest text in second dropdown option. how do i do this while using semantic UI search drodown? as it sets both dropdown to same size and i dont want that, or to the width of text that is selected or top most option. all iwant is to set the width as traditional dropdown while using semantic UI

**Comment by Giwayume** [comment]
What you're asking for would be a very performance-expensive Javascript solution. The library would have to loop through each dropdown item, set it as the current value, and calculate the width of the the dropdown for each item.

Instead, you could just specify a custom width yourself with inline styles.
`<div class="ui search dropdown selection" style="width:300px">`

What you're trying to do is not compatible responsive web design.

**Comment by aldencolerain** [comment]
@Banandrew @Giwayume 

This response seems incorrect.  Why would you need to use java script to loop through the elements to get the width?  Can't you just hide the dropdown using visibility: hidden and set the height to zero to allow the dropdown menu to influence the size the parent container?

Also why are inline-block width's default behavior not considered responsive?

**Comment by rjworks** [comment]
it doesn't change the width
