### ISSUE TITLE
Gutter size

### ISSUE THREAD

**Issue by Isa79** [Semantic-Org/Semantic-UI#5161]
I am using the the semantic-react library to use Semantic UI in React. So I am forced to use the CDN than download Semantic UI and put it in my project.

How would I decrease the gutter size? I know that relaxed and very-relaxed increase it but is there anything for decreasing it?

**Comment by Banandrew** [comment]
Hi @Isa79,

If you use a CDN, you can’t properly override internal variables, and there’re no classes to make the gutter size smaller. You’ll have to calculate `@gutterWidth`, `@tableWidth`, `@stackableGutter` manually (see how they are used [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/collections/grid.variables)), then find them in [CSS definitions](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/grid.less) and do an override.
