### ISSUE TITLE
Card header height

### ISSUE THREAD

**Issue by J2BB** [Semantic-Org/Semantic-UI#5162]
Hi,

I use cards in a grid with equal-height columns.
The problem is that when the card's content is empty, the header's height is broken compare to a card not empty.

Browser : Google Chrome Version 58.0.3007.0 canary (64-bits)
Semantic-UI : 2.2.7
Code : http://jsfiddle.net/bv1jdwry/

Please see the JsFiddle : I would like the right card have the same header's height that the left card.

Does somebody know how can i fix the header's height in this case ? (without force it in CSS of course)

Thanks !

**Comment by Banandrew** [comment]
Hi @J2BB, try to change the first `.content` container for both cards to `.extra.content` instead.

**Comment by J2BB** [comment]
Alright ! It works perfectly !
Thank you :)
