### ISSUE TITLE
Request one more example

### ISSUE THREAD

**Issue by Hokwang** [Semantic-Org/Semantic-UI#5163]
Hello.

I want to make my web site just like your home page.

I mean simple,
left vertical menu, right context.
And it will be resposive. (when screen size is getting small, menu will be on top.)

But I can not understand your html codes and documents still yet.

I am not satisfied with semantic-ui.. there's ambiguous and not well-documents, few examples..

Below is my sample code, can you guide some points I missed?

```
<body>
	<div class="ui left vertical menu sidebar inverted visible">
		<div class="item">
			<div class="header">header</div>
			<div class="menu">
				<a class="item">Item 1</a>
				<a class="item">Item 2</a>
			</div>
		</div>
	</div>
    <div class="pusher">
	<div class="ui red segment">
		<form class="ui form">
			<h2 class="ui dividing header">Sample</h2>
			<div class="field">
				<label>Name</label>
				<div class="two fields">
					<div class="field">
						<input type="text" name="shipping[first-name]" placeholder="First Name">
					</div>
					<div class="field">
						<input type="text" name="shipping[last-name]" placeholder="Last Name">
					</div>
				</div>
			</div>
		</form>
	</div>
	</div> 
</body>
```

**Comment by vinayakkulkarni** [comment]
You might want to take a look at the docs: [Here](https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/documents/index.html.eco)

--
Closing this cause 1. Usage Question, 2. Solution in SUI Docs.
