### ISSUE TITLE
UTF-8 Form validator

### ISSUE THREAD

**Issue by sinhpn92** [Semantic-Org/Semantic-UI#5164]
I trying to use form validation to validate utf8 string input from user. I just want allow only utf8 characters and number which have length from 8 to 50. I tried regex `([\pL\pM 0-9]{8,50})` but it didn't work. What's wrong with my regex? Have any suggestion regex for my problem? Thanks

**Comment by vinayakkulkarni** [comment]
Dear @sinhpn92, as per our Contribution guidelines, this is neither an usage question or it's relevant to a issue in the framework but a simple RegEx question.

I urge you to read [Contribution Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) and request you to ask these sort of questions on our [gitter channel](https://gitter.im/Semantic-Org/Semantic-UI).
