### ISSUE TITLE
[api] aborted requests still cause redirects

### ISSUE THREAD

**Issue by dabeschte** [Semantic-Org/Semantic-UI#5174]
Using a submitbutton in a form, the api will always send a request and reload the page, even if I return false. If i return false, i even get an error message "....request aborted", but it still reloads the page.
Tried 2.2.9 and 2.2.0 with same results.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by dabeschte** [comment]
Hi! Here is my example. [JSFiddle](http://jsfiddle.net/hpkhkepa/)

It is the shortened form and does surprisingly not reload the page when used in JSFiddle, but it does reload the page when I'm using in on my own environment. Is JSFiddle using 2.2.9?

**Comment by Banandrew** [comment]
@dabeschte Yes, it’s 2.2.9. I tried the code you provided on my local machine, and it doesn’t submit the form—just like a JSFiddle. Maybe there’s something interfering with it on your end?

**Comment by dabeschte** [comment]
I can't reproduce it myself anymore. Maybe there was some bad combination of elements I used on my own page, but unfortunately I already replaced the api with my own version.
Thanks for the support, I will open a new issue once it happens again, but for now it seems like I can close this issue.
