### ISSUE TITLE
[Dropdown] shouldn’t open when a page is being scrolled on mobile

### ISSUE THREAD

**Issue by RaulOG** [Semantic-Org/Semantic-UI#5180]
Hello,

I hereby present you the problem description:

> When a mobile user tries to scroll but unfortunately trigger the touchstart event on the dropdown, they will open that dropdown instead of scrolling.

This is specially annoying for the user when a page contains several dropdowns. It is indeed a UX problem.

I have temporarily disabled this functionality by commenting out the bind.touchEvents() and the touchstart and touchmove intent bindings.

**Comment by larsbo** [comment]
I can confirm that after commenting out https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L534 there is a much better user experience on mobile without permanently opening dropdowns accidently during scrolling.

#4926 might be related.

**Comment by jox** [comment]
Confirming the very annoying and impractical behaviour.
Also confirming that commenting out `bind.touchEvents()` fixes the issue.
Anybody has an idea why that is that in there in first place? Without it, dropdowns on mobile work just as expected.
Tested on iOS and Android.

**Comment by searene** [comment]
Could you reopen this issue? It's still not resolved.

**Comment by nopjia** [comment]
Been running into this problem myself this past week. Reopen the issue please??
