### ISSUE TITLE
Clear value selection for dropdown

### ISSUE THREAD

**Issue by KevinGorjan** [Semantic-Org/Semantic-UI#5187]
Created this issue on https://github.com/Semantic-Org/Semantic-UI-React/issues/1484, but I was suggested to post it here.

Any chance we get an option to clear the selected value from a dropdown?

Like [react-select](http://jedwatson.github.io/react-select/) is doing?

![image](https://cloud.githubusercontent.com/assets/789614/24118759/3438f8e0-0daf-11e7-9d76-c198ac9f0bfb.png)

**Comment by Banandrew** [comment]
Hi @KevinGorjan, take a look at #3635.
