### ISSUE TITLE
Responsive fixed column grid

### ISSUE THREAD

**Issue by yamsellem** [Semantic-Org/Semantic-UI#5188]
I'm struggling with the most basic responsive grid:
* three columns on computer
* two columns on tablet
* one column on mobile

I can't make it work with the basic responsive grid (_phone, tablet & computer classes_), because 16 is not divisible by 3. Which gives 5 + 5 + 5 = 15, so a gutter on the right — or a centered grid, with gutters on both side.

```html
<div class="ui grid">
  <div class="sixteen wide phone eight wide tablet five wide computer column"></div>
  <div class="sixteen wide phone eight wide tablet five wide computer column"></div>
  <div class="sixteen wide phone eight wide tablet five wide computer column"></div>
</div>
```

What I would like, is the following grid, but, which don't seems to exist:

```html
<div class="ui two column tablet three column computer stackable grid">
  <div class="column"></div>
  <div class="column"></div>
  <div class="column"></div>
</div>
```

**Comment by vinayakkulkarni** [comment]
What about this?
```html
<div class="ui stackable grid">
  <div class="two column tablet three column computer row">
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
  </div>
</div>
```

**Comment by Banandrew** [comment]
Hi @yamsellem, try to set `@columnCount: 15;` in `installation_folder\src\site\globals\site.variables`, then rebuild.

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.

**Comment by adster13** [comment]
I was in a similar situation and just set `@columnCount: 12;` not 15 as mentioned above because 15 isn't divisible by 2.

Then the classes would be `<div class="twelve wide phone six wide tablet four wide computer column"></div>`
