### ISSUE TITLE
Why does standalone dropdown module looks like crap and working like crap?

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5189]
Hi there. So, i downloaded:
1. dropdown.min.js
2. dropdown.min.css
3. transition.min.js
4. transition.min.css

Added them to my page and it's completely looks like a shit. Nay, it's working like a shit. Not opening by pressing an arrow or not closing after choosing an element. 

![unnamed](https://cloud.githubusercontent.com/assets/17240507/24174877/e3e4ae14-0e9b-11e7-9814-f8241449ed84.png)

What have i done wrong?

**Comment by Banandrew** [comment]
Hi @JamesJGoodwin,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
