### ISSUE TITLE
[Website] Scroll doesn't work properly on Google Chrome mobile

### ISSUE THREAD

**Issue by radiocity** [Semantic-Org/Semantic-UI#5195]
There is some scroll hell on [theming](https://semantic-ui.com/examples/theming.html) page.
Browser: Google Chrome 56.0.2924.87
OS: Android 5.1 / Flyme
[Video](https://youtu.be/nPf2spEMPUc)

**Comment by Banandrew** [comment]
Hi @radiocity and thanks, closing as a duplicate of #5012. I reposted your data there.

**Comment by jlukic** [comment]
I've fixed this with https://github.com/Semantic-Org/Semantic-UI/commit/52dbc6288e327d1b671b0d86019a23ef6d601bcc and will be deploying this fix early to the docs.
