### ISSUE TITLE
[Icon] - The document icon has missing

### ISSUE THREAD

**Issue by hunzsig** [Semantic-Org/Semantic-UI#5196]
In [https://semantic-ui.com/elements/icon.html](url)
I had saw some new icons  in the past.But now they are lost.

**Comment by Banandrew** [comment]
Hi @hunzsig, can you please elaborate on what icons exactly are missing? There was a similar issue #5158 and a PR Semantic-Org/Semantic-UI-Docs#303 to add Font Awesome 4.7.0 icons, does it cover the icons that are missing?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
