### ISSUE TITLE
Contents of the sidebar doesn't refresh

### ISSUE THREAD

**Issue by AXIMEYE** [Semantic-Org/Semantic-UI#5198]
I have a table. On click of some of the rows, a diagram gets generated. Further, on click of each of those diagrams, content associated with those diagrams should be displayed in the sidebar. Content that needs to be displayed is disparate.

When I click on the table rows, and then on the diagram, content in the sidebar doesn't get updated. The same content get displayed for each of the diagrams.

Is there a way to "refresh" the contents of the sidebar?

**Comment by Banandrew** [comment]
Hi @AXIMEYE, you do you update the sidebar’s content?

**Comment by AXIMEYE** [comment]
Hi @Banandrew.

The application I'm working on uses Play framework. Everytime  appropriate table rows are clicked, one of the controllers passes data to a Scala template. Necessary html(content to be displayed) is generated by the template. Upon clicking the diagram, the generated html should be displayed in the sidebar.

At the moment, as a temporary workaround, I'm explicitly deleting the "div" that holds the previous content. Sidebar then adds the new content. But if I don't, the content remains the same.

**Comment by Banandrew** [comment]
@AXIMEYE Does it append that `div` after the previous one, or just sees that the `div` is there and does nothing?

**Comment by AXIMEYE** [comment]
No it doesn't append any div to the previously added div. In fact, when I was debugging, that is when I realized what was happening(the previously added div not getting modified) and came up with the workaround.

**Comment by Banandrew** [comment]
@AXIMEYE Unfortunately, there’s nothing SUI can do for you. You either have to remove the sidebar’s contents manually like you do, or use a JavaScript framework to automate all of your front-end manipulations.

Closing the issue as a usage question as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md). If you’ll have other questions in the future, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
