### ISSUE TITLE
Any solution for JQuery problem

### ISSUE THREAD

**Issue by delockdown** [Semantic-Org/Semantic-UI#5201]
Hi Guys, 
This very very cool library and one of best I ever seen but it can't still work it out. I tried serval thing but every time it shows me `Uncaught ReferenceError: jQuery is not defined
    at semantic.min.js:11`. ( Ahhh :worried:). Can some one suggest a solution for this issue. 
I'm using this on electron app with angular. I have tried CDN and build up process even. Every time it gives the same error. 

Thank you,
Regrads,
DELOCKDOWN.

**Comment by jihoon-oh** [comment]
You need to reference the jQuery script tag before referencing the Semantic-UI script tag in your header HTML file.
For example, assuming you're using the CDN for both, the correct order should be:
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>

You can also check out: http://stackoverflow.com/questions/30281258/how-to-use-semantic-ui-cdn

Let me know if it works!
Cheers

**Comment by delockdown** [comment]
Yes, I did that but it shows something like this and no didn't work this solution, still stuck on there 
<img width="662" alt="screen shot 2017-03-26 at 1 54 39 am" src="https://cloud.githubusercontent.com/assets/1327120/24325828/83b46e1a-11c7-11e7-9c0e-529f14725094.png">

**Comment by Banandrew** [comment]
@delockdown do you combine your JavaScript into one file? How do you include all those JavaScript files on your pages?

**Comment by delockdown** [comment]
@Banandrew, perviously i did that. Then I refer the comment of @jihoon-oh and did that, even that solution didn't work for me. 
Check [this codepen](http://codepen.io/anushkamahesh/pen/OpwONE), it has simple dropdown. It is not working at all.

Regards,
DELOCKDOWN.

**Comment by jihoon-oh** [comment]
In the codepen, you didn't include the following in your JS:
```
$('.ui.dropdown')
  .dropdown()
;
```
Took me a while to figure out what was wrong too, but realized [there is a tutorial](https://semantic-ui.com/modules/dropdown.html#/usage) on how to use the dropdown menu in the "usage" tab.

[Here is the exact same codepen, except now with the proper JavaScript code written in.](http://codepen.io/jihoonoh/pen/XMBZaG)

**Comment by Banandrew** [comment]
@delockdown Excuse me, you did what? You didn’t answer any of my questions.

**Comment by mohammadreza** [comment]
if you got the `Uncaught ReferenceError:  jQuery is not defined at semantic.min.js:11` error again in the console, first and the only thing you should to do is put jQuery link load before the SemanticUI link load.
in first load the jQuery and then load the SemanticUI.be consider about the orders.
**Wrong way** 

```
<script src="your_path/semantic.min.js" type="text/javascript"></script>
<script src="your_path/jquery.min.js" type="text/javascript"></script>
```
**Correct way**

<script src="your_path/jquery.min.js" type="text/javascript"></script>
<script src="your_path/semantic.min.js" type="text/javascript"></script>

**Comment by vlow** [comment]
@delockdown this is not an issue of semantic-ui or jQuery but a known caveat of the nodejs integration in electron. Take a look at the electron faq: https://electronjs.org/docs/faq#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron

Some alternative approaches to solve this problem are described in this issue: https://github.com/electron/electron/issues/345

**Comment by josuevalrob** [comment]
Same problem for Angular 6. Is there any solution like _ng-bootstrap_??

**Comment by Mempler** [comment]
Possible fix for that

```html
<script>
  const jQuery = require('jquery')
  const $ = jQuery
  require('./semantic/semantic.min.js')
</script>
```
