### ISSUE TITLE
Dropdown menu selection with items and childs items

### ISSUE THREAD

**Issue by J2BB** [Semantic-Org/Semantic-UI#5204]
Hi,

Is there a way to create a Semantic UI dropdown selection box with items and childs items ?

I try to mix Menu Selection and Menu Direction here : http://jsfiddle.net/vjn1hx7m/
But it does not work :(

Thanks !

**Comment by Banandrew** [comment]
Hi @J2BB, your JSFiddle is empty. Can you please give an example of such an implementation?

**Comment by J2BB** [comment]
Oops ! Sorry : http://jsfiddle.net/vjn1hx7m/

**Comment by Banandrew** [comment]
@J2BB I see, it seems to be a duplicate of #3101; no, it’s not possible, and the enhancement was declined.

**Comment by J2BB** [comment]
Sad news ! But thanks for your answer ;)
