### ISSUE TITLE
Lack of documentation in "Popup"

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5209]
Hi there. Is there any way to set popup inverted over javascript? Is there any way to insert html-markdown into popup's body? Maybe i'm blind, but i can't see those js-settings in documentation on the website. For example, i got written a function, that calling a popup on some element:

```javascript
function callPopup(el, txt, pos) {
    el.popup({
	hoverable: true,
	transition: 'scale',
	position: pos ? pos : 'bottom center',
	content: txt
    });
};

callPopup(#('.some-element'), 'Hi there! Click <a href="somelink.html">me</a>, to become awesome!');
```
And when popup is calling, link in popup displaying like plain text. Is there documentation missing or there is no functionality like this at all?

Thanks in advance.

**Comment by Banandrew** [comment]
Hi @JamesJGoodwin, yes, there’s `html` property that you can use instead of `content`, and it’s well documented.
