### ISSUE TITLE
[Bug] filterAPIResults: Add namespacing on sessionStorage

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI#5211]
Got really confused on why one of my dropdown was having a weird value. Turns out it was using that other dropdown's value.

`sessionStorage` stores results like: `value: text`

if one dropdown has value `1` and some other has `1` also, they will clash.

TL;DR when more than one `dropdown` is on the same page that has `filterAPIResults` their results will clash when both has same value.

**How To Reproduce:**
- Have at least two dropdown
- enable filterAPIResults
- Have different API return same `value`. When I say `value`, I mean the `value` the `dropdown`/`api` module is expecting: `{ value: '1', text: 'text', name: 'name' }`

Can't provide a fiddle cause I can't find a good fake API online. I gave the steps on how to reproduce it, I hope that's enough.

**Comment by Banandrew** [comment]
Hi @xxRockOnxx, are you sure that `filterAPIResults` works? Because it doesn’t exist—there was a mistake #5051 in naming and it’s [filterRemoteData](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3545) now.

**Comment by Banandrew** [comment]
Reminding to answer the question in the comment before.

**Comment by xxRockOnxx** [comment]
@Banandrew sorry. I'll try to reproduce it using the new option. I updated some stuffs and moved on to some other because I'm catching some deadline.

**Comment by Banandrew** [comment]
@xxRockOnxx No worries, I thought maybe you forgot; don’t rush it, it can wait until you’re done with your work.

**Comment by lubber-de** [comment]
Fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2046
