### ISSUE TITLE
[Dropdown] It should be possible to turn off the `onChange` trigger for `set selected` and possibly others

### ISSUE THREAD

**Issue by bhosalemahesh899** [Semantic-Org/Semantic-UI#5212]
I needs OnChange not to be triggered when 'set selected' or 'set value' is called.

On load I want to prepopulate the dropdown with selections from the server (using 'set selected') and only call the OnChange when the user manually selects an item (so it can be added to the server db too).

set selected could have a third parameter "silent", to prevent triggering onChange which is set to false by default. and I set it to true but nothing happens on change
el.dropdown('set selected', value, true);

my directive code is here

```JS
(function (module) {
	module.directive('searchableDropdown', ["$timeout", searchable]);

	function searchable($timeout) {
		return {
			restrict: 'E',
			require: 'ngModel',
			replace: true,
			scope: {
				orderBy: '@',
				valueField: '@',
				textField: '@',
				ngModel: "=",
				dropdownItems: '='
			},
			templateUrl: 'searchableDropdown.html',
			link: function (scope, el, atts, ngModel) {
				scope.searchableDropdownVm.getSelectedName = function (valueField, textField, selectedValue) {
					var itemObj = scope.searchableDropdownVm.dropdownItems.find(function (keyItem) {
						return keyItem[valueField] == selectedValue;
					});
					if (itemObj) {
						return itemObj[textField]
					}
					return '';
				};
				el.dropdown({
					onClick: function (value, text, choice) {
						scope.$apply(function () {
							ngModel.$setViewValue(value);
						});
					},
					onChange: function (value, text, choice) {
						debugger;
						scope.$apply(function () {
							//ngModel.$setViewValue(value);
							//ngModel.ngChange(value);
						});
					},
					forceSelection: false,
					selectOnKeydown: false,
					showOnFocus: true,
					on: "click"
				});
				ngModel.$render = function () {
					$timeout(function () {
						//el.dropdown('set text', scope.searchableDropdownVm.getSelectedName(scope.searchableDropdownVm.valueField, scope.searchableDropdownVm.textField, scope.searchableDropdownVm.ngModel));
						//el.dropdown('set value', '');
						el.dropdown('set selected', ngModel.$viewValue, false);
						//el.dropdown('set value', ngModel.$viewValue);
					});
				};
			},
			controller: ["$element", "$scope", Controller],
			controllerAs: 'searchableDropdownVm',
			bindToController: true,
		};

		function Controller() {
			var vm = this;
		}
	};
})(angular.module('app'));
```

**Comment by Banandrew** [comment]
#1351’s discussion is related.

There’re also #5055 and #4913—maybe the solution can be combined or addressed at the same time.

**Comment by bhosalemahesh899** [comment]
Hi thank you for the reply.
I didn't got exact answer
Can you please check "ng-change Call count = 1" on load in this plunker update in this? So that I can get exact answer.

https://plnkr.co/edit/5wx8rROBzAKTDRHM17aU?p=preview

**Comment by Banandrew** [comment]
Hi @bhosalemahesh899, I didn’t understand the question, can you please elaborate?

**Comment by bhosalemahesh899** [comment]
I the above plunker in output  dropdown "ng-change Call count = 1" on load. this should be 0. How I can prevent to trigger ngChange on load?

**Comment by Banandrew** [comment]
@bhosalemahesh899 You could use pre-existing HTML instead of initializing it on a `<select>` element directly:
```HTML
<div class="ui selection dropdown">
  <input type="hidden" name="name">
  <i class="dropdown icon"></i>
  <div class="default text">Default text</div>
  <div class="menu">
    <div class="item" data-value="value">Text</div>
  </div>
</div>
```
Populate the menu container first, then initialize it with `dropdown()`—then `onChange()` will only get triggered with user input.

**Comment by bhosalemahesh899** [comment]
Thank you Banandrew. It works

**Comment by neokio** [comment]
I needed to (a) set my dropdown `onChange` on init, and (b) dynamically add `.menu` items, followed by `.dropdown('clear')`.

But `onChange` was triggering with every clear. What worked for me was adding `if (val !== '')` inside the init, like so ...

```javascript
$('#blah').dropdown({
    onChange: function(val){
        if (val !== '') {
            // called via user interaction
            // or $('#blah').dropdown('set selected', 123)
            // but NOT by clearing
        }
    }
});
```

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) added support to prevent the change trigger for `set selected` by 
https://github.com/fomantic/Fomantic-UI/pull/1683
