### ISSUE TITLE
Dropdown Search Ignore Diacritics / Match Partial

### ISSUE THREAD

**Issue by brunotourinho** [Semantic-Org/Semantic-UI#5213]
Hi there,

Is it possible to change the dropdown filter/search to ignore diacritics like "fiancè" or "ciência", this issue comes from a long time already. Referenced in #3287 #4287 #3577

Another enhancement would be an option to match part of the string i.e.:
my search query would be: "ska"
and the results: "Alaska, Nebraska..."

for now, any workaround is welcome!

thank you

**Comment by Banandrew** [comment]
Hi @brunotourinho, unfortunately, it’s still not here; let’s track everything in one place. On matching partials, try either this:
```JS
$('.ui.dropdown')
  .dropdown({
    fullTextSearch: true
  })
```
Or this:
```JS
$('.ui.dropdown')
  .dropdown({
    fullTextSearch: 'exact'
  })
```

**Comment by brunotourinho** [comment]
Hi @Banandrew, the fullTextSearch worked great! Still waiting for the ignore diacritics option! Thanks

**Comment by Vitucho** [comment]
implementation proposal:

          exactSearch: function (query, term) {
            var diacriticsRegexByReplacement = {
              'a' : /[âãäåāăą]/g,
              'e' : /[èééêëēĕėęě]/g,
              'i' : /[ìíîïìĩīĭ]/g,
              'o' : /[óôõöōŏő]/g,
              'u' : /[ùúûüũūŭů]/g,
              'c' : /ç/g,
              'n' : /ñ/g,
            }
            query = unaccent(query.toLowerCase());
            term  = unaccent(term.toLowerCase());
            if(term.indexOf(query) > -1) {
               return true;
            }
            return false;

            function unaccent(str) {
              for (var replacement in diacriticsRegexByReplacement) {
                if (diacriticsRegexByReplacement.hasOwnProperty(replacement)) {
                  var diacriticRegex = diacriticsRegexByReplacement[replacement]
                  str = str.replace(diacriticRegex, replacement)
                }
              }
              return str;
            }

**Comment by brunotourinho** [comment]
Hi @Vitucho! Thanks for sharing! Where do I place your code to make it work? In a separated file or just replacing the original function?

**Comment by Vitucho** [comment]
Hi @brunotourinho i just replaced the entire function, look in the semantic.js code for the function `exactSearch` and replace the implementation it should do the trick!!

**Comment by Myst6971** [comment]
Is there any way of extensibility of this function, and not just adding it in built in code?

**Comment by brunotourinho** [comment]
@Myst6971, we've been waiting for this implementation for a long time, just like the calendar. Our friend @mdehoog managed to build a separated plugin to it. Maybe we should do the same for the search parameters.

**Comment by lubber-de** [comment]
Added option `ignoreDiacritics` to dropdown and search module for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/422 :grin: 
See http://jsfiddle.net/t23uewyn/
