### ISSUE TITLE
search.js

### ISSUE THREAD

**Issue by sante85** [Semantic-Org/Semantic-UI#5217]
when no result, we can emit an event please?

Thanks

**Comment by Banandrew** [comment]
Hi @sante85, you could use `onResults()` callback to determine if there were no results, and do something. Does it answer your question?

**Comment by vinayakkulkarni** [comment]
@sante85, did Andrew satisfy you with his answer? You can come on [gitter](https://gitter.im/Semantic-Org/Semantic-UI) channel to ask Usage related questions.

Closing this till you reply.

**Comment by Maxhodges** [comment]
or the forums http://forums.semantic-ui.com
