### ISSUE TITLE
Modal being closed but not dimmer on clicking browser back button

### ISSUE THREAD

**Issue by HemanthGowda** [Semantic-Org/Semantic-UI#5220]
The modal is being closed when i click on browser back button but the dimmer is still on. Interesting part is onHide method of modal is not called on clicking browser back button. But still the modal will be closed.

```
$('.first.modal')
.modal({
    onHide: function(){
       console.log('Hiding')
    }
}).modal('show');

```
Both modal and dimmer should be closed on clicking browser back button.

**Comment by Banandrew** [comment]
Hi @HemanthGowda, I can’t seem to reproduce on the latest Chrome `57.0.2987.133` on Windows 10. What were you using when you noticed that?

**Comment by hanssen** [comment]
I can confirm this behaviour on an android tablet, with the app wrapped in cordova.

**Comment by sido420** [comment]
I can confirm this on a Android Cordova phone app.

This is bad for usability.

**Comment by sido420** [comment]
this can also be easily reproduced in Desktop Chrome in dev mode and choosing a mobile device emulator and "Command + [" (on Mac). You obviously need the modal open while testing.

**Comment by sido420** [comment]
any updates on this? this can become a usability nightmare since app becomes unusable if dimmer is on and there is no way to remove it.

**Comment by dinhani** [comment]
I am having the same issue with desktop browsers.
