### ISSUE TITLE
JSFiddle that’s being used for test cases stopped working

### ISSUE THREAD

**Issue by Banandrew** [Semantic-Org/Semantic-UI#5223]
It seems that the range module was added to `http://semantic-ui.com/dist/semantic.js`, and there’s a comma missing in `$.fn.slider.settings` object right after `pageMultiplier` property.

**Comment by IonutBajescu** [comment]
Odd how this issue regressed, we had the same problem a couple of months ago #4523.

**Comment by Banandrew** [comment]
@IonutBajescu Sorry about that, should’ve just reopened it.

In any case, it seems that it was resolved when Jack updated the documentation’s files yesterday, and the slider component is now nowhere to be found in `/dist/semantic.js`.
