### ISSUE TITLE
data-tooltip pointer is huge

### ISSUE THREAD

**Issue by kvigor** [Semantic-Org/Semantic-UI#5224]
![datatooltip](https://cloud.githubusercontent.com/assets/800621/24563751/224d8542-1615-11e7-997e-9b7d8293030e.png)

The pointer of this tooltip is huge and it doesn't point exactl at element.  How can I get it to look like this:
![datatooltip_002](https://cloud.githubusercontent.com/assets/800621/24563874/934a69e0-1615-11e7-9fb9-bcba34eb0bb1.png)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/Banandrew/7z4vaeon/).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
