### ISSUE TITLE
[Form Validation] Validation not work when inside Modal

### ISSUE THREAD

**Issue by erlangp** [Semantic-Org/Semantic-UI#5225]
`Form Validation` not work when inside `Modal`. How to solve this problem? Thanks.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/Banandrew/7z4vaeon).

**Comment by erlangp** [comment]
owh i'm sorry.
i have test using JSFiddle.
other js lib make SUI Form Validation not working.
thanks for your help :D

**Comment by erlangp** [comment]
Test Case: https://jsfiddle.net/vm7p5zdr/

**Comment by remimarenco** [comment]
+1

**Comment by joneidejohnsen** [comment]
Any updates on this bug?
