### ISSUE TITLE
Multi UI Tabular Menu

### ISSUE THREAD

**Issue by tphilippiniTDF** [Semantic-Org/Semantic-UI#523]
Hi,

I wanted to add multiple tabular menu on my home page view.
I added errors because in tab.js, when i changed tab, all '.ui.tab' was desactivated.
I should added new class and changed selector. when i call tab() function.

And add new param for selector.tabs

<pre>
$('.demo.menu .item').tab({
      history: false,
      selector    : {
        tabs : '.ui.tab.demo'
      }
    })
</pre>

(Added history to false because, navigation tab bug when it changed)
Is it a problem or a normal menu process ?

On version : 0.11.0

**Comment by muppetjones** [comment]
Sorry--the last comment was a working version.

**Comment by wjh000123** [comment]
@jlukic is there solution for tabs that they have parents/children relationship? Looks like the context doesn't work for this scenario.

**Comment by jlukic** [comment]
I'm not sure specifics of your implementation, but next patch will add setting for whether menu should deactivate all tabbed instances or just sibling menus. 

Context should solve issues with multiple tabs in one page.
