### ISSUE TITLE
[popup] 'destroy', 'remove popup' behaviors and preserve : false parameter have no effect on an inline : true popup

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5239]
`destroy`, `remove popup` behaviors and `preserve : false` parameters have no effect on an `inline : true` popup.  Popup contents remain on page. 

See here:
https://jsfiddle.net/kmd1970/z2a25xj5/

Same issue as #2934?

**Comment by Banandrew** [comment]
Hi, yes, I think it’s a duplicate. I moved your post there, and we can always reopen it if needed.
