### ISSUE TITLE
[Dropdown][Enhancement] Allow onAdd() and onRemove() callbacks to fire for both single and multiple select dropdowns

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5240]
Currently, `onAdd()` and `onRemove()` callbacks only fire for **multiple** select dropdowns. We also need a way to tell if the user actual selected an option in a **single** select dropdown.  

The only way to do that now (for a single select) is to use the `onChange()` callback and check if value is not blank. (no user selection? was it a clear or some other behavior?)

One issue is that `onChange()` also fires if you perform a `$('.ui.dropdown').dropdown.('clear');` (which is perfectly fine) however, now you have to add additional checks to prevent your  code from executing.

**Comment by jprateragg** [comment]
I too would like to see this functionality. I was just struggling with this a few minutes ago and this page came up in my google results for it.
