### ISSUE TITLE
[Icon] - Wrong version on documentation

### ISSUE THREAD

**Issue by NoSoyTsundere** [Semantic-Org/Semantic-UI#5241]
The current [Icon documentation](https://semantic-ui.com/elements/icon.html) says:

> Semantic includes a complete port of Font Awesome **4.5.6** designed by Dave Gandy for its standard icon set.

But Font Awesome 4.7.0 is used since SUI 2.2.8 as shown on the [release notes](https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.2.8).

No big deal but may lead to some misunderstoods =)

**Comment by vinayakkulkarni** [comment]
Will be fixed soon. Already sent a PR https://github.com/Semantic-Org/Semantic-UI-Docs/pull/310

**Comment by vinayakkulkarni** [comment]
Will be fixed in PR https://github.com/Semantic-Org/Semantic-UI-Docs/pull/303

**Comment by NoSoyTsundere** [comment]
Great! =)
