### ISSUE TITLE
[Flag] Missing all these flags

### ISSUE THREAD

**Issue by KevinGorjan** [Semantic-Org/Semantic-UI#5243]
* Antartica: aq
* Curaçao: cw
* Guernsey: gg
* Isle of Man: im
* Jersey: je
* Kosovo: xk
* Saint Barthélemy: bl
* Sint Maarten: sx
* South-Soedan: ss

**Comment by peter-conalgo** [comment]
+1 for [the Crown Dependancies: GG, JE, IM](https://en.wikipedia.org/wiki/Crown_dependencies)

**Comment by Magtheridon96** [comment]
Bump.
Is this issue ever going to be addressed?
I need this sprite-based Flag component for platforms that don't support Flag emojis.

**Comment by CodeForcer** [comment]
This is still not solved in 2020, seriously?

**Comment by lubber-de** [comment]
The community fork https://fomantic-ui.com has a PR which covers all missing flags
https://github.com/fomantic/Fomantic-UI/pull/1190
