### ISSUE TITLE
[Dropdown] - Multiple searchable remote dropdown not removing items from list

### ISSUE THREAD

**Issue by pierre-weceipt** [Semantic-Org/Semantic-UI#5244]
Hi, it seems that when a dropdown is multiple and searchable and remote, items are not removed from the list when selected. Here is a js fiddle : http://jsfiddle.net/jeadv8xu/ , you just need to clic on dropdown, select first item, clic outside then again on dropdown and see that the item is still in dropdown.

A working workaround is to initialize dropdown again (simple refresh not enough) in the `oncomplete` event of `apisettings` like in the following jsfiddle : http://jsfiddle.net/q6ktzL6u/

**Comment by Banandrew** [comment]
Hi @pierre-weceipt, it’s a known issue: #4577.

**Comment by pierre-weceipt** [comment]
Ah sorry, I screened through the issues but did not find this one^^
