### ISSUE TITLE
Multi select without selected items in the input text

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5250]
I'm using Semantic-UI for developing my web application.
I created a Plunker to make me explain better to you:

https://plnkr.co/edit/xF38wE

    $('.dropdown1').dropdown({
      transition: 'fade down'
    });
    
    $('.dropdown2').dropdown({
      transition: 'fade down',
      useLabels: false
    }); 

I would like to keep the "search" functionality as it appears in the `dropdown1`, but I don't want that the selected items are saved in the input field.
In addition I would have options to be highlighted when they are selected, as happen in the `dropdown2`, but I don't want to get the "counter" strings in the input field.

![0jydy](https://cloud.githubusercontent.com/assets/5399265/24792257/8349afc0-1b7d-11e7-861f-c53bb403e539.png)

Do you know if there is any setting or workaround to make multiselect suit my needs?

**Comment by Banandrew** [comment]
Hi @smartm0use, I’m confused, can you please elaborate on what you want to see in the actual input? Because if it’s not labels, and not a counter, it becomes a regular dropdown, doesn’t it? Maybe what you’re looking for are customized labels like the first dropdown, the only difference is that they’d be looking differently?

**Comment by smartm0use** [comment]
I just want a select with search feature and with items that are bolder if they have been already selected.

**Comment by Banandrew** [comment]
@smartm0use Please [see](https://semantic-ui.com/modules/dropdown.html#search-selection) the `.ui.search.selection.dropdown` variation and let me know if it does the job.

**Comment by smartm0use** [comment]
I have update my Plunker, I have added one more dropdown element. Is that the variation you mean?

**Comment by Banandrew** [comment]
No, [this one](http://jsfiddle.net/Banandrew/hccd1tvu/).

**Comment by smartm0use** [comment]
Yes, but your solution is for single-selection. I'm talking about a multi-select.

**Comment by Banandrew** [comment]
SUI doesn’t have anything like that, it’s either labels or a counter. If you show me the image of a UI pattern that you’re talking about, I might be able to be more specific on now to customize labels.

**Comment by smartm0use** [comment]
I just need what you posted before, but it should let me select more than one item. Ok, so SUI doesn't have it. Thank you anyway for your support.

**Comment by smartm0use** [comment]
I solved using the following settings:

    message.count = '';
    useLabels = 'false';
