### ISSUE TITLE
[Form Validation][Enhancement] Please add 'validate field(field)' and 'reset field(field)' behaviors

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5253]
We really need a behavior to trigger validation (check rules, show error or success) for individual form fields:

 `$('.ui.form').form('validate field', 'first-name')`

**Edit** Looks like this (hidden?) behavior already exists, but has to be called like this:
```html
<label>First Name</label>
<input placeholder="First Name" name="first-name" class="firstname" type="text">
```
```javascript
$('.ui.form').form(
'validate field',
{
  identifier:'first-name',
  rules: [
      {
          type   : 'empty',
          prompt : 'Please enter your name'
      }
  ]
},'name',true);
```
this shortcut also works
```javascript
$('.ui.form').form(
  'validate field',
  $('.ui.form').form('get validation', $('[name="first-name"]') ),
  'name',
  true
);
```
**form.js line 853** (docs issue?)
```javascript
field: function(field, fieldName, showErrors)
```

Also, need a behavior to reset a field that currently has an error and message showing.

`$('.ui.form').form('reset field', 'first-name')`
or
`$('.ui.form').form('reset', 'first-name')`  (will only reset specified field in this case)

This can be done very easily:

**form.js line 201**
```javascript
reset: function(field) {
         // pass in a field identifier or leave blank, then use filter()
         field = (field !== undefined) ? field : '';
         field = ('[name="' + field +'"]');
          $field.filter(field)
            .each(function () {
              var
                $field       = $(this),
                $element     = $field.parent(),
                $fieldGroup  = $field.closest($group),
                $prompt      = $fieldGroup.find(selector.prompt),
                defaultValue = $field.data(metadata.defaultValue),
                isCheckbox   = $element.is(selector.uiCheckbox),
                isDropdown   = $element.is(selector.uiDropdown),
                isErrored    = $fieldGroup.hasClass(className.error)
              ;
```
**More**
Two more behaviors `add rule` (adds a new rule to a field) and `remove rule` (removes an existing rule from a field, example `empty`. This can be used to dynamically toggle required fields)

**Comment by jlukic** [comment]
After looking through you can just call 

```
$('.ui.form').form('validate field', 'someField'); 
```

This will validate the field with the existing ruleset.

I'm also adding in next version `add rule` `add field`  `remove field`, `remove rule`
