### ISSUE TITLE
Popup semantic ui possible bug

### ISSUE THREAD

**Issue by francesco-taioli** [Semantic-Org/Semantic-UI#5254]
there is a strange problem with semantic ui popup. I create a dynamic content in my page, this is a div with a popup.

```
container = $('<div/>',
            {
            'width': 50,
            'height': 40,
            'data-content': 'some content',
            'data-variation': "tiny",
            preserve: false
            });
```
then, in another section of page, i activate the popup

```
container.popup({
                silent: true,
                hoverable: true,
                title :'some title'

            }).popup('show');
```
All works fine, but in my page i've also a horizontal scroll. So, if i show the popup and the scroll to right, the popup still remain in the same position while the container move to left.

http://stackoverflow.com/questions/43283235/popup-semantic-ui-possible-bug

**Comment by kmd1970** [comment]
You need to use `inline: true` and attach the popup to some other element than body

**Comment by francesco-taioli** [comment]
@kmd1970 no, this not fix the issue.

**Comment by kmd1970** [comment]
it would help if you posted a jsfiddle example of the issue.

**Comment by francesco-taioli** [comment]
ok, i try to replicate it on a fiddle @kmd1970

**Comment by kmd1970** [comment]
take a look at this https://jsfiddle.net/kmd1970/0qtm2424/

**Comment by francesco-taioli** [comment]
@kmd1970  i see your fiddle, but with `inline:true` doesn't change anything

**Comment by francesco-taioli** [comment]
@kmd1970 maybe it happen because i've this error
`Popup: Popup does not fit within the boundaries of the viewport `
and i've set silent :true ?

**Comment by francesco-taioli** [comment]
@kmd1970  no, i've tried with the same html code and an horizontal scrollbar but there isn't this error. Maybe in my code there is a little conflict

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by Prabhakar-Poudel** [comment]
I am quite certain of it. Popup has a lot of bugs also with positioning. In my case, I created a popup with a button to show it in navigation bar. Once I scroll the page horizontally, the popup continues to move while the button it was suppose to stick with is somewhere else.
