### ISSUE TITLE
Grids are broken in Chrome/Safari/Dolphin apps for iOS

### ISSUE THREAD

**Issue by vicmarcal** [Semantic-Org/Semantic-UI#5256]
Hi!
Seems that the Semantic Grid is not correctly working in the Chrome, Safari, or Dolphin apps for iOS which are the most used ones in Ipad. Just Puffin seems to be showing it correctly.

![image](https://cloud.githubusercontent.com/assets/6674048/24833347/a11ba8c4-1cc6-11e7-97dd-80701329830c.jpg)
![image](https://cloud.githubusercontent.com/assets/6674048/24833348/a1400868-1cc6-11e7-8bf3-5952fee66def.jpg)
![image](https://cloud.githubusercontent.com/assets/6674048/24833349/a1400f3e-1cc6-11e7-9328-820df8a0f478.jpg)
![image](https://cloud.githubusercontent.com/assets/6674048/24833350/a1428bba-1cc6-11e7-9fb6-1878474c626c.jpg)

**Comment by vicmarcal** [comment]
Btw, not sure if the following workarounds would help you to enhance the cross-browsers compatibility:
https://github.com/philipwalton/flexbugs
Flexbox is an amazing way to ease the layouts, but it still really unsupported by a lot of browsers out there.
The CanIUse "Known issues" section seems to highlight probably some of the issues detected:
http://caniuse.com/#feat=flexbox

**Comment by Banandrew** [comment]
Hi @vicmarcal, what browser/iOS version was it?

**Comment by vicmarcal** [comment]
Well, I have tested it in two different devices:
Ipad Air 2, version iOS 8.1:
- The Safari version bundled in iOS7 up to iOS9(iirc) doesnt properly
support Flexbox. So basically current Semantic grid is not working in any
Safari versions from iOS 7 to 9, a "hack" is probably needed.
- The Chrome iPad version installed is 57.0.2987.137 and seems to not
support Flexbox neither as shown.
- The Dolphin iPad version installed is 9.24.1 and seems to not support
Semantic Grid/Flexbox as shown.
Both Chrome and Dolphin are updated to its latest versions.

Iphone 6, iOS 9.3.3:
- The Safari version seems to be showing correctly the Semantic Grid.
- The Chrome iPhone version installed is 57.0.2987.137, this versions shows
correctly the Semantic UI grid.
- The Dolphin iphone version installed is 9.23.2, seems to be showing the
Semantic Grid correctly.

**Comment by mvrhov** [comment]
It doesn't matter which browser you use on iOS as all of them use the rendering engine that comes with the iOS. That's the apple policy.

**Comment by sathishj21** [comment]
Any solution available for this issue...? I am also using this Sematic-UI-React Grid in my project. During cross-browser testing, we noticed this Grid is not working as expected in IOS version 8.0 device (ipad mini). We are using "semantic-ui-react" version "^0.72.0".  Please help me if there is any solution to this issue.
