### ISSUE TITLE
variable @mcolor is in the site.variables in side folder but when i build gulp it says @mcolor not defined in menu.less

### ISSUE THREAD

**Issue by rohitdesigner** [Semantic-Org/Semantic-UI#5257]

**Comment by Banandrew** [comment]
Add the variable to `src/site/collections/menu.variables` instead and try again.

I posted the standard reply (that’s below) in one of your other GitHub threads before to let you know that it’s against our contributing guidelines to post usage questions on GitHub—from now on, I’ll be closing GitHub issues that are usage questions without an answer;  please use one of our other support resources in the future.

---
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
