### ISSUE TITLE
Sidebar labeled icon visible

### ISSUE THREAD

**Issue by encry2024** [Semantic-Org/Semantic-UI#5258]
Greetings. This is my first time opening a new issue here. I would like to request a help from my problem here.

![screen shot 2017-04-09 at 7 57 22 pm](https://cloud.githubusercontent.com/assets/7674327/24837105/3d157532-1d5f-11e7-94d4-5c5457994cb6.png)

This is my code for my sidebar.

![screen shot 2017-04-09 at 7 57 43 pm](https://cloud.githubusercontent.com/assets/7674327/24837108/58f1eb00-1d5f-11e7-8809-6e9cbd87f20d.png)

This is how i setup my sidebar.

![screen shot 2017-04-09 at 7 58 04 pm](https://cloud.githubusercontent.com/assets/7674327/24837112/664b5188-1d5f-11e7-8d5e-cf0578eb6b9a.png)

**Comment by encry2024** [comment]
But after i hide it and toggle it again. The gray background is fixed.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by encry2024** [comment]
https://jsfiddle.net/encry2024/qj5fLkf7/

**Comment by Banandrew** [comment]
It doesn’t know the width of a sidebar, so it uses the default value to push the page. You could remove `.visible` from the sidebar and show it upon the initialization instead:
```JS
$('.ui.sidebar')
  .sidebar({
    context: $('body'),
    dimPage: false,
    closable: false
  })
  .sidebar('attach events', '.sidebar-toggle')
  .sidebar('show')
```
Please note that the sidebar component shouldn’t be used for always visible sidebars, I wrote about it [here](https://github.com/Semantic-Org/Semantic-UI/issues/5200#issuecomment-289288498); take a look at the example there to see how to make one. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
