### ISSUE TITLE
Input -> Action is not responsive

### ISSUE THREAD

**Issue by George3d6** [Semantic-Org/Semantic-UI#5259]
I tried using the following code (copy pasted  from the website):

```
<div class="ui right action left icon input">
  <i class="search icon"></i>
  <input type="text" placeholder="Search">
  <div class="ui basic floating dropdown button">
    <div class="text">This Page</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">This Organization</div>
      <div class="item">Entire Site</div>
    </div>
  </div>
</div>
```

Example: http://jsfiddle.net/kp6vupkr/1/

However the behavior is different from the one showcase, in that, clicking the dropdown icon doesn't tirger the menu options to show up.

Browser version I tested this in:
Chromium 57.0.2987.133
Mozilla Firefox 52.0.2

Semantic ui version (from npm):
2.2.10

Includes in the html head:

semantic.min.css (The default one, no customization, built with gulp)

Included after the body:
semantic.min.css
/static/semantic.min.js

The console shows no error log or message when I load the page or when I click the button.

Is there a missing part of the documentation for how to use this in the current version ?
Would you require any additional details/logs to debug this issue ?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by George3d6** [comment]
Sorry for that, 
Here is the issue in the fiddle: 
http://jsfiddle.net/kp6vupkr/1/

**Comment by Banandrew** [comment]
@George3d6, it’s a [dropdown component](https://semantic-ui.com/modules/dropdown.html), so you have to initialize it like that:
```JS
$('.ui.dropdown')
  .dropdown()
```
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Please use one of our other support resources in the future:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by George3d6** [comment]
Fair enough, but in that case the documentation could include the markup as:

http://jsfiddle.net/kp6vupkr/2/

```
<div class="ui right action left icon input">
  <i class="search icon"></i>
  <input type="text" placeholder="Search">
  <div class="ui basic floating dropdown button">
    <div class="text">This Page</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">This Organization</div>
      <div class="item">Entire Site</div>
    </div>
  </div>
</div>
<script>
$('.ui.dropdown')
  .dropdown()
</script>
```

Or at least a small note about the syntax being made in the input section.

At least it seems like it could reduce confusion a lot, the solution was in another section of the documentation. But that's just a suggestion, maybe there is a good reasoning for keeping it the way it is.

Either way thank you for clearing up the confusion.
