### ISSUE TITLE
inline links don't work inside tab

### ISSUE THREAD

**Issue by timdiacon** [Semantic-Org/Semantic-UI#5260]
If I include a link inside a tab it stops working. As soon as I move it outside the tab it works again?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
