### ISSUE TITLE
Pagination not Responsive

### ISSUE THREAD

**Issue by aravindlikes** [Semantic-Org/Semantic-UI#5264]
I have using datatable with semantic ui for displaying tables. but the pagination is not responsive.

here is my sample  [fiddle](https://jsfiddle.net/7gdk29o3/2/)

**Comment by Banandrew** [comment]
Hi @aravindlikes, pagination is basically the menu component, so you could add `.stackable` class to it to make it stackable at mobile resolutions.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by aravindlikes** [comment]
but thing is when i use datatables it automatically add the pagination dynamically. if you see the fiddle there is no pagination menu's code. but in output you can see pagination. i want to know is there any problem with semantic ui or datatables ??

**Comment by Banandrew** [comment]
@aravindlikes DataTables has nothing to do with SUI, so it’s best to research the solution on DataTables’ end.
