### ISSUE TITLE
Combining different labels

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5266]
Hello, I have a container with the following labels:

![screenshot from 2017-04-11 15 44 06](https://cloud.githubusercontent.com/assets/5399265/24912242/d9cb9310-1ecd-11e7-97a5-bfbe5ee8976c.png)

Now I want to add the following right corner label as well:

![screenshot from 2017-04-11 15 45 27](https://cloud.githubusercontent.com/assets/5399265/24912314/074bd7a0-1ece-11e7-8d52-a816c2f6723c.png)

I want to obtain the following result:

![label](https://cloud.githubusercontent.com/assets/5399265/24912657/0ed38c4c-1ecf-11e7-8cd4-a74fd7382890.png)

As you can see, since I have a rounded container I have to set `overflow: hidden`, according to the [documentation](https://semantic-ui.com/elements/label.html):

> A corner label must be positioned inside a container with position: relative to display properly. If a container is rounded you will need to add overflow:hidden to the container to produce a rounded label.

But if I set it to `hidden', I get this:

![label2](https://cloud.githubusercontent.com/assets/5399265/24912734/4f6e1538-1ecf-11e7-821a-9974308992eb.png)

How can I fix this?

**Comment by vinayakkulkarni** [comment]
Can you please provide a test case ? Fork this [JSFiddle](http://jsfiddle.net/efp8z6Ln)

**Comment by smartm0use** [comment]
Here is my test case: http://jsfiddle.net/j83010dz

Thank you for your JSFiddle.

**Comment by Banandrew** [comment]
Hi @smartm0use, open `installation_folder/src/site/elements/segment.overrides`, put the following there, and rebuild the framework:
```CSS
.ui.segment > .right.corner.label {
  top: 0;
  right: 0;
}
```
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Please use one of our other support resources in the future:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by smartm0use** [comment]
This worked. Thank you.
Anyway couldn't this be an issue or a feature request?

**Comment by Banandrew** [comment]
@smartm0use We’re already tracking it: #2780.
