### ISSUE TITLE
[Dropdown] Dropdown isn't clickable on firefox

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#5268]
Hi,

I have this example 

http://jsfiddle.net/h4w7xywm/1/

The dropdown items are not clickable on firefox.
I tried adding the z-index, but it didn't work
The dropdown is always behind it's parent `.column` and the siblings `.column` of it's parent.

**Comment by Kjaal** [comment]
The dev team is aware of this issue, and the fix for it is being released in the next update `2.2.10`:[#5113](https://github.com/Semantic-Org/Semantic-UI/issues/5113)

**Comment by Banandrew** [comment]
`2.2.10` is the current release, and #5113 is a different issue.

**Comment by Banandrew** [comment]
@shadoWalker89 It seems that it’s just how Firefox treats buttons, and is not a SUI issue. Can you please change `button` elements to `div` instead and confirm?

**Comment by shadoWalker89** [comment]
@Banandrew You are absolutely right, changing the `button` to `div` solves this.
