### ISSUE TITLE
[Input][Form] "error" class on input field doesn't work in some use cases

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5271]
I have an input with `error` class and it works with no problems as you can see here:

http://jsfiddle.net/urxvdcz4

I even have an (field) input with `error` class inside a `form` and it works:

http://jsfiddle.net/L11qxorL

But if I have an input with `error` class inside a `form` it doesn't work:

http://jsfiddle.net/6jhdve2f

As you can see, in the latter example it works only if I remove the parent tag `form` or if I add the class `field` within the `input` tag.
Could this be an issue?

**Comment by Banandrew** [comment]
Hi @smartm0use, we should probably fix it for consistency.

**Comment by marshallpierce** [comment]
I'm seeing this problem also.

**Comment by matiusnugroho** [comment]
i'm seeing this problem too, an ui error class inside pushable is not styled as usual
