### ISSUE TITLE
A little markup bug in Icon section of the main semantic-ui site

### ISSUE THREAD

**Issue by kodwi** [Semantic-Org/Semantic-UI#5274]
[Link](https://semantic-ui.com/elements/icon.html)

When I press "View source" of the Web content section, at the bottom of all icons the html code is out of human-readable wrapper.

**Comment by danial-k** [comment]
The same issue is also present in the "Computer and File System" section

**Comment by Banandrew** [comment]
Hi @danial-k, thank you, considering the maintainer’s workflow, I think it’s pointless to keep it opened here then.
