### ISSUE TITLE
[Search] Add fullTextSearch option for "exact"

### ISSUE THREAD

**Issue by sheyooo** [Semantic-Org/Semantic-UI#5275]
Can the option for fullTextSearch option for "exact" be added to the Search module just like it is in the Dropdown module

**Comment by Banandrew** [comment]
Hi @sheyooo, does setting `searchFullText` to `false` help?

**Comment by sheyooo** [comment]
@Banandrew no, it only matches from the beginning of the text I am searching through, but I want it to find exact matches even if it is not at the beginning of the text I am searching through. Thank you.

**Comment by jlukic** [comment]
I think this is fair

**Comment by sheyooo** [comment]
Please, can you direct me what file I need to modify locally on Semantic to achieve this. I can't wait for when this will be added to the library

**Comment by Banandrew** [comment]
@sheyooo `installation_folder/src/definitions/modules/dropdown.js`. Since you’re essentially forking it, exclude the dropdown component from being built in `semantic.json` and add it separately.

**Comment by sheyooo** [comment]
Ok thanks, I'll check that and get back to you
