### ISSUE TITLE
How to destroy a dimmer element with a video?

### ISSUE THREAD

**Issue by saikrishnadeep** [Semantic-Org/Semantic-UI#5279]
I'm trying to show a dimmer element along with a youtube video embeded in it as an iframe in the dimmer. I call the dimmer like this:

```javascript
$('.ui.movie.images').on('click','img',function(){
      $('.ui.dimmer').dimmer({
        'opacity': 0.97,
        'duration':{'show':0, 'hide':0},
        onShow: function(){
          crumb('add','Four Room')
        },
        onHide: function () {
          crumb('pop')
        }
      }).dimmer('show');
    })
```

However, the problem I face is, when I try to close the dimmer like:

```javascript
$('.big.close.icon').on('click',function() {
      $('.ui.dimmer').dimmer('hide');
    })
```

The video that was in the dimmer continues playing. I don't want to destroy this dimmer element, because I will be reusing it over and over. However, I don't see how I can stop the youtube video from playing in the background after hiding the dimmer. Is destroying and recreating the dimmer element, the only option? 

Any help is appreciated.

**Comment by Banandrew** [comment]
Hi @saikrishnadeep, I think YouTube has an API that allows you to control videos programmatically, have you tried it? You could also destroy videos instead, but it depends on what you do, and maybe it’s a good idea to measure if it’s any faster.

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
