### ISSUE TITLE
[Documentation] Grid page has no reference or example of "middle aligned" class

### ISSUE THREAD

**Issue by dancaron** [Semantic-Org/Semantic-UI#5280]
I was able to vertically center div contents using "middle aligned" on a "ui grid" div. This should be included on the documentation for the grid page.

**Comment by Banandrew** [comment]
Hi @dancaron, it’s already [there](https://semantic-ui.com/collections/grid.html#vertical-alignment), if it won’t automatically scroll, it’s “Definition” tab, and “Vertical Alignment” section.
