### ISSUE TITLE
[Input] - Double opacity applied to disabled inputs

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI#5283]
**Steps to Reproduce**
1. Create a `.ui.disabled.input` with an `input[disabled]` child.

**Expected**
The `input` should have an opacity rule applied to appear disabled.

**Result**
The `input` has two opacity rules applied and is hardly visible.  This is because the `.ui.disabled.input` wrapper receives `opacity: 0.4` while the `.ui.input input[disabled]` child also receives `opacity: 0.4`.  The result is an input element with an effective opacity of 0.16.

**Testcase**

http://jsfiddle.net/ebecpcLp/2/

![image](https://cloud.githubusercontent.com/assets/5067638/25095184/6697f394-234f-11e7-802c-b363fe9d7bd6.png)

**Fix**

The `input` element should only have opacity applied if the wrapper is not already also disabled:

**input.less**
```diff
.ui.disabled.input,
-.ui.input input[disabled] {
+.ui.input:not(.disabled) input[disabled] {
  opacity: @disabledOpacity;
}
```

**Comment by arntj** [comment]
What's the status on this one?

**Comment by levithomason** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI/commit/ae3845032fd26c9b5652a49989aedbb8f32f0367
