### ISSUE TITLE
stand alone grid.css is broken: only 15 columns fit, the last bumps down

### ISSUE THREAD

**Issue by dwenaus** [Semantic-Org/Semantic-UI#5285]
I am using the default standalone grid.css in my project (v2.2), when I try to add eight and eight columns It does not fit. I read (http://stackoverflow.com/a/28820844/545822) that I have to use the entire semantic.css is that true?

**Comment by dwenaus** [comment]
I tried it on the simplest possible situation, and the blue and red bars are on top of one another:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="grid.css">
</head>
<body>
<div class="ui grid">
    <div class="eight wide column blue"></div>
    <div class="eight wide column red"></div>
</div>
</body>
</html>
```

**Comment by dwenaus** [comment]
Seems like the reset.css is necessary. this is nowhere in the documentation. :)

**Comment by dwenaus** [comment]
A helpful

**Comment by Banandrew** [comment]
Opened a PR to the reset component’s documentation page; closing the issue as resolved.
