### ISSUE TITLE
js error in documentation

### ISSUE THREAD

**Issue by dwenaus** [Semantic-Org/Semantic-UI#5286]
there seems to be a js error on this page: https://semantic-ui.com/behaviors/visibility.html#fixing-content-to-viewport when you click the example code.
Mac OS Chrome and Safari.

**Comment by thedaviddias** [comment]
It says in the console:

```
"semantic.min.js:15 Popup: Popup does not fit within the boundaries of the viewport 
<div class=​"visibility overlay example">​…​</div>​"
```

**Comment by Banandrew** [comment]
Hi, can’t find it, can you please elaborate?

**Comment by dwenaus** [comment]
I get 4 errors:
Sticky: "Element is hidden, you must call refresh after element becomes visible. Use silent setting to surpress this warning in production."
https://semantic-ui.com/dist/semantic.min.js:7353:126

Visibility: "Element is hidden, you must call refresh after element becomes visible"
https://semantic-ui.com/dist/semantic.min.js:9461:126

those two repeat

**Comment by jlukic** [comment]
This is just because the page lazily initializes the sticky elements. The ones that are in the closed tabs are initialized before they are visible and so positions can't be determined on first init. 

I can fix this in docs code, but it shouldnt cause any bugs.
