### ISSUE TITLE
From version 2.2.10 onBottomVisible not firing

### ISSUE THREAD

**Issue by asaarnak** [Semantic-Org/Semantic-UI#5289]
Can be tested here:
https://semantic-ui.com/behaviors/visibility.html

On 2.2.9 works as expected.

**Comment by daneren2005** [comment]
I was able to use a work around similar to http://jsfiddle.net/budiadiono/x3cdqyta/1/ mentioned in another issue for now.  It is probably less performant though since it is running all of the calculation multiple times.
