### ISSUE TITLE
Infinite loop on clicking remote content dropdown

### ISSUE THREAD

**Issue by mamun-github** [Semantic-Org/Semantic-UI#5290]
Remote content dropdown creates infinite loop when clicked on it and server returns empty list response.
Apparently, clicking a remote content dropdown triggers `show()` function to `queryRemote()` with a callback to `show()` function. When server returns empty list, `can.show()` condition returns `false` because of  `has.items()` and `has.message()` is false. Which creates infinite loop. Is there anyway to resolve this issue, I mean with a message / something? 
jsfiddle: https://jsfiddle.net/dhfa4730/
**Step to re-produce:** after running fiddle, click dropdown arrow.
**Result:** infinite loop request to server.
Any response/guidance is much appreciated.

**Comment by Banandrew** [comment]
Hi @mamun-github, it’s a known bug: #5231, and I don’t think there’re any workarounds.
