### ISSUE TITLE
How to embed youtube with start from time?

### ISSUE THREAD

**Issue by QHose** [Semantic-Org/Semantic-UI#5291]
Hi,
This works fine:
https://www.youtube.com/embed/O6Xo21L0ybE

But what if I want to start the video from a certain time? t=3

https://youtu.be/O6Xo21L0ybE?t=2

kind regards Martijn

**Comment by ardamose123** [comment]
This question is more suitable for StackOverflow or some other Google support channel, since it's not specific to Semantic UI.

However, in this case, you have to use the `start` query parameter instead of `t`: https://www.youtube.com/embed/O6Xo21L0ybE?start=3

**Comment by Banandrew** [comment]
Hi @QHose,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
