### ISSUE TITLE
Unscrollable page

### ISSUE THREAD

**Issue by anhldbk** [Semantic-Org/Semantic-UI#5292]
Hi guys,

I'm reading the source code of [login example](https://semantic-ui.com/examples/login.html#). There's a bug when displaying the page in low-height screens. Users can not scroll to see hidden areas.

![screenshot from 2017-04-20 20-28-55](https://cloud.githubusercontent.com/assets/3270746/25233872/83b5d988-260a-11e7-9a92-3e81ccfad1b3.png)

Would you please tell me to fix the bug?

**Comment by Banandrew** [comment]
Hi @anhldbk, it seems that it’s not the issue with SUI, but rather with that example. Have you tried just copying the code from it and using it in your project?

**Comment by anhldbk** [comment]
@Banandrew Sorry! I managed to fix the bug. Should I make a PR against this issue?

**Comment by Banandrew** [comment]
@anhldbk If you have some time, any improvement will be much appreciated.

**Comment by anhldbk** [comment]
@Banandrew Ok! But first let's me close this issue
