### ISSUE TITLE
[Popup] - doesn't working after ajax reload

### ISSUE THREAD

**Issue by lukaspicha** [Semantic-Org/Semantic-UI#5294]
Hi, i red some issues with popup, but i can still find a solution.
i try this code `$('a').popup({ observeChanges: true });` and the same with false, but no results. How can i fix it?

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by NoSoyTsundere** [comment]
You need to reactive your popups after paste your ajax response because the module only affect to existing elements.

**Comment by lukaspicha** [comment]
[https://jsfiddle.net/ztfh7axf/1/](url) - did you mean reactive as in the fiddle?

**Comment by Banandrew** [comment]
@lukaspicha No, try `$('i').popup('refresh')` on success instead. It’s not obvious from you fiddle what you’re trying to do exactly, we might be able to help if you’ll set up a full example for us to see, HTML included.

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
