### ISSUE TITLE
[Dropdown] IE9 Compatability - Ignore Transitions

### ISSUE THREAD

**Issue by TheJuki** [Semantic-Org/Semantic-UI#5296]
I know that Semantic-UI does not support IE versions less than IE 11; however, I thought others may want to support IE9 using this fantastic UI framework!

I modified the dropdown.js file to get around the fact that IE9 does not support transition.js.

Basically, when a transition show or hide is necessary I used JQuery to manually show or hide without a transition instead of logging an error such as "noTransition".

[dropdown.js.zip](https://github.com/Semantic-Org/Semantic-UI/files/947844/dropdown.js.zip)

https://www.diffchecker.com/3xhaBT08

**Comment by aleksaToljic** [comment]
Thanks, it was helpfull
