### ISSUE TITLE
Dropdown Menu makes link items tiny and unclickable on mobile devices

### ISSUE THREAD

**Issue by ryanbarsatan** [Semantic-Org/Semantic-UI#5298]
I'm surprised nobody has run into this problem yet. ui dropdown menu makes all its items link elements tiny on mobile devices. Everything shows up and looks fine but when you try to click on an item in the dropdown menu nothing happens because the anchor tag is tiny.

**Comment by Banandrew** [comment]
Hi @ryanbarsatan, what device and OS version was it? Can you please take a screenshot?

**Comment by ryanbarsatan** [comment]
Hi @banadrew , I'm on iPhone 7 Plus. OS 10.2.1 will try to add screenshot tonight after work.
