### ISSUE TITLE
Cursor change on icon in the Corner Label doesn't happen. Bug?

### ISSUE THREAD

**Issue by bildsoe** [Semantic-Org/Semantic-UI#5299]
When you use the Corner Label on an image like so:

```
<div class="ui fluid image">
    <a class="ui left corner label">
        <i class="heart icon"></i>
    </a>
    <img src="/images/wireframe/image.png">
</div>
```

The mouse cursor does not change to indicate the Label is clickable when you're over the Icon.

Is this intended?

The behavior can be observed here: https://semantic-ui.com/elements/label.html#corner

BR
Thomas

**Comment by Banandrew** [comment]
Hi @bildsoe, thanks, but we’re already tracking it here: #4238.

**Comment by bildsoe** [comment]
Cool, thanks
