### ISSUE TITLE
[Table] Adding sortable class to inverted table defaults header colors

### ISSUE THREAD

**Issue by saikrishnadeep** [Semantic-Org/Semantic-UI#5300]
I think the title is pretty self explanatory. I'm not sure if this is intended, but doesnt seem like it.

Here is the reproducible bug: https://jsfiddle.net/skd/qkw0u16t/

**Comment by Banandrew** [comment]
Hi @saikrishnadeep, thanks, but we’re already tracking it in #5227. I reposted your test case in that thread.
