### ISSUE TITLE
Accordion and Jquery UI

### ISSUE THREAD

**Issue by francesco-taioli** [Semantic-Org/Semantic-UI#5304]
There is a conflict  with accordion and jquery.ui

Correct version : -> http://jsfiddle.net/taioli/tg21uLoh/11/
Error Version : -> http://jsfiddle.net/taioli/tg21uLoh/12/

stackoverflow question : -> http://stackoverflow.com/questions/43588391/semantic-ui-accordion-into-modal

**Comment by francesco-taioli** [comment]
https://jqueryui.com/download/
check all without accordion.
the error is  that Semantic.js and jQuery-ui.js have the same function 'Accordion'

**Comment by Banandrew** [comment]
Hi @francesco-taioli, I’ll be closing it, because it’s not an issue with SUI itself. Both SUI and jQuery UI try to do similar things, so any conflict between the two is expected.

**Comment by francesco-taioli** [comment]
But at least update the docs, the say nothing about this!

**Comment by pbx** [comment]
I agree that it would be a kindness to include a note in the [accordion docs](https://semantic-ui.com/modules/accordion.html) about this. It's quite baffling when one runs into it for the first time.

**Comment by etshy** [comment]
Usually, using 2 libraries for UI is not recommnded.
If the 2 libraries have the seme methods name, confilicts will happen, that's so obvious I don't think updating the docs is necessary.
