### ISSUE TITLE
[Dropdown] multi level icon position problem in Firefox

### ISSUE THREAD

**Issue by berkayunal** [Semantic-Org/Semantic-UI#5306]
Hi,

Is there a bug in or am i missing smthing for the multi level dropdown's icon position?

Screenshot: https://www.evernote.com/l/AAIhTsFOKrVM16zjR2z3J_hphy5dJjGQDhQ
Fiddle: https://jsfiddle.net/2rruuph6/1/

**UPDATE:** This happens only on Firefox (Mac - 52.02.2 64 Bit)

Thanks.

**Comment by ardamose123** [comment]
Place the `<i class="dropdown icon"></i>` before the "More" text, not after.

**Comment by Banandrew** [comment]
Sorry about that.

@ardamose123 Thank you, should’ve checked the HTML pattern.
