### ISSUE TITLE
Toggle sidebar and ios class

### ISSUE THREAD

**Issue by Emusp** [Semantic-Org/Semantic-UI#5307]
When you open the sidebar on an ios device, the css class 'ios' is added to the html tag.
But when the sidebar is closed the ios class is not removed. That gives some issues and inconsistency in the ui, scrolling speed etc. 

Is this just a bug, or by design? Do have to remove the ios class manually in js?

**Comment by Banandrew** [comment]
I don’t have access to an iOS device, but this issue might be related: #4264.

**Comment by Emusp** [comment]
Not sure if it's exactly the same issue, but I got two issues.

One is that you get two different scroll rates. 
When the sidebar has been toggled once and the ios class is applied.
You get that smooth fast scrolling (-webkit-overflow-scrolling: touch;)
But then the ios class is not applied, eg. if you refresh the page, you get normal scroll speed.

The second is hard to explain without a video.
When the ios class is applied and you have a fixed top menu. When you pull down like "pull to refresh" in an app, the background is going over the top fixed menu.

**Comment by Emusp** [comment]
Issue is fixed in 2.2.11
