### ISSUE TITLE
Dropdown performance issues with large datasets

### ISSUE THREAD

**Issue by neutraali** [Semantic-Org/Semantic-UI#5308]
We're handling a **Dropdown** (```.ui.dropdown.selection.multiple.search```) that has around ~85 items at present. We have a checkbox that can toggle between selecting all the elements of the dropdown or clearing it (programmatically).

At the moment it takes around **1.25 seconds**  to programmatically select all elements using ```set exactly```, where as it takes a _UX-breaking_  **5.5 seconds** (!!!) to reset the Dropdown using ```clear```. This is a bit of a serious issue from a usability standpoint. This is on a mid-range laptop with Chrome 57+ -
 Obviously the performance is much worse on mobile, going as far as doubling the lag...

Any plans to address this? Possible solutions welcome.

**Comment by Banandrew** [comment]
Hi @neutraali, thank you, but we’re already tracking it in #5236. There’re no immediate plans, so if it’s important, I’d suggest to either fork, or integrate a third party library.

**Comment by neutraali** [comment]
Thanks for the quick update; I completely missed that issue even though I searched the opened _and_ closed issues.
