### ISSUE TITLE
celled table in a definition table

### ISSUE THREAD

**Issue by Lulunx** [Semantic-Org/Semantic-UI#5310]
Hey,

I'm actually working on a website, and I've to put a celled table in a definition table. But as you can see, the first column of my celled table take the style of the definition table...

How can I do for have the 1st column of the celled table as a celled table style ?

thanks

![capture d ecran 2017-04-25 a 15 35 01](https://cloud.githubusercontent.com/assets/25199760/25387979/ce1230b0-29cc-11e7-9807-52134f18e7ff.png)

**Comment by Banandrew** [comment]
Hi @Lulunx, add `.ignored` class to the cell. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
