### ISSUE TITLE
semantic-ui.com top bar appears twice at certain window sizes

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Semantic-Org/Semantic-UI#5311]
![2017-04-25-171727_628x997_scrot](https://cloud.githubusercontent.com/assets/8045060/25390637/cc67af46-29dc-11e7-8e2c-0dfe579b40de.png)

The size of the `<body>` here is 603x436.

Update: reproducible in Chrome 58 and Firefox 53.

**Comment by ardamose123** [comment]
This is an easy fix.

In the page's home.css, lines 626 and 680 have media queries that hide the menus at different widths (600px and 650px, respectively). Just setting them to, say, 600px and 601px respectively, it makes the menus show and hide without conflict.

**Comment by jlukic** [comment]
Fixed in PR, thanks for waiting...
