### ISSUE TITLE
Attached menu is offset by 1px to the right

### ISSUE THREAD

**Issue by samt** [Semantic-Org/Semantic-UI#5312]
Screenshot is from the [Attached Example](https://semantic-ui.com/examples/attached.html) page, "Mixed Attached Content" section.

![screen shot 2017-04-25 at 7 15 50 am](https://cloud.githubusercontent.com/assets/150040/25390514/8997e5ae-2988-11e7-9cdc-15bc5cf34e4d.png)

There is something wacky deep within the menu definitions as it displays fine without `margin-left: 0em !important;` however omitting that rule breaks everything else relying on that to fix the `-1px` margin that seems to be coming from somewhere.

**Comment by Banandrew** [comment]
Hi @samt, thank you, but we’re already tracking it here: #4248.
