### ISSUE TITLE
[Search] - using undefined variable

### ISSUE THREAD

**Issue by gonoszcsiga** [Semantic-Org/Semantic-UI#5313]
Hi, i find a little ninja bug, in the `src/definitions/modules/search.js`
```php
results = module.search.object(searchTerm, settings.content),
```
Settings variable does not have key `content`, it must be `source`.
Not a big deal, because the object() function replace this to `settings.source` when the `source` argument is undefined, but later maybe become bigger problem.

**Comment by lubber-de** [comment]
Prepared a fix for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/712
