### ISSUE TITLE
[Dropdown] Add button-like attached variations

### ISSUE THREAD

**Issue by a-x-** [Semantic-Org/Semantic-UI#5314]
I use semantic-ui-react.
My issue: attached button and dropdown.
Button has attach prop, Dropdown hasn't.

```jsx
        <div>
          <DropdownSearch attached="left" {...getProps(7)} placeholder="Лицевой счет"/>
          <Button attached="right" primary>New Next</Button>
        </div>
```

**Comment by a-x-** [comment]
I need `Button.Or` in group with `Dropdown` (or any another control).
Can you create universal Group component as common version of Button.Group for groupping any components?

**Comment by a-x-** [comment]
Can you create universal Group component for any components grouping?

**Comment by dlynch29** [comment]
I could definitely use this. There is extra functionality that I would like to add to a dropdown (options like "Exclude all", "Select All", etc.) and an attached button makes sense for something like this.

**Comment by larsbo** [comment]
@a-x- I built an attached dropdown version (vertical only) some time ago: https://github.com/Semantic-Org/Semantic-UI/pull/3542

**Comment by dlynch29** [comment]
I was able to do it using `ui fluid action input` and adding `input` do the dropdown div like this: 
`<div class="ui fluid action input">
    <div class="ui multiple search selection input dropdown" 
         style="border-top-right-radius: 0px; border-bottom-right-radius: 0px;">
        <input value="default" type="hidden" />
        <i class="dropdown icon"></i>
        <div class="default text"></div>
        <div class="menu">
            <div class="item">Items go here</div>
        </div>
    </div>
    <button id="selectallbutton" class="ui basic blue right icon button" 
            onclick="$( this ).toggleClass( 'basic' );"             
            data-tooltip="Select All">
        <i class="asterisk icon"></i>
    </button>
    <button id="excludeselectedbutton" class="ui basic red right icon button" 
            onclick="$( this ).toggleClass( 'basic' );"
            data-tooltip="Exclude Selected">
        <i class="ban icon"></i>
    </button>
</div>`
