### ISSUE TITLE
Cannot set extra parameters while using api search

### ISSUE THREAD

**Issue by shubh3794** [Semantic-Org/Semantic-UI#5324]
Hey, I have been using semantic ui recently only, and I wanted to make a search call based on the input val and another parameter which has also been dynamically set. 

But I am unable to do so in Semantic.
`apiSettings: {
            url: HOST + 'api.example.com?action=get-stuff&search_param{query}&date=' + window.date
        }
`

And this is not working as it is always taking the default value of window.date which is being dynamically set everytime. I also tried to modify the value of {query} variable here but that is not working either

**Comment by Banandrew** [comment]
Hi @shubh3794, can you please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to show the front-end that you wrote?
