### ISSUE TITLE
[Search] Add "onResults" callback setting

### ISSUE THREAD

**Issue by AlexandreGagner** [Semantic-Org/Semantic-UI#5325]
Hi,
The actual callback `onResults ` is called only in `generateResults` function, so when there are new results from server.
It would be nice to have new callback,  when we have result from "Local search results" too.

The 'new' onResults would be called when showing results from previous search too.

**Comment by Kjaal** [comment]
I second this, the important thing here is that the new onResult callback still has the response so you can still do:
`onResult: function(response) {
    //Handle response data
}`
If you do not need the response data you can do `onResultsOpen` or `onResultsAdd`
