### ISSUE TITLE
[Sticky] - Sticky section disappear while height greater than context section

### ISSUE THREAD

**Issue by Serpentsoft** [Semantic-Org/Semantic-UI#5326]
**Steps to Reproduce**

**Expected**
You should set height for the Context section equal the sticky height in such case

**Result**
The Sticky section disappear while height greater than context section 

**Testcase**
https://jsfiddle.net/Serpentsoft/ews47feu/

Thanks for your great library,

Have a nice day

**Comment by Serpentsoft** [comment]
Any help, solution? I convert my whole project to Semantic-UI and suspended 'cause this issue.

**Comment by Banandrew** [comment]
Answered on Gitter. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by Serpentsoft** [comment]
When you make a big project like that, You should test it with a lot of options and listen to professional people who met a lot of issues every day,

After make your solution and calculate height before fires Sticky I had to adding [ui sticky] classes while page loading so Sticky section works fine on scroll down but jumps when reach the page's top and after remove [fixed top] classes it's not smooth.

I just told you this issue 'cause I liked this project, I was using stickyKit and it works fine but there's an issue in IE, So I tried this project but I surprised with your solution and this kind of support.

Anyway thanks for this project it'll facilitate a lot of people life, But in case you felt to test your sticky in a real project not some texts you should know it's not working good enough.

Thanks again, have a nice day.

**Comment by Banandrew** [comment]
@Serpentsoft I can certainly file it as enhancement, but it won’t be reviewed any time soon. Would you like me to do that?

**Comment by Serpentsoft** [comment]
It's up to you, in case you want to enhance your plugin .. I went back to StickyKIT

**Comment by jlukic** [comment]
This is not the right tone for addressing people working on issues for free in an open source project. Please see our contributing guide.
