### ISSUE TITLE
Styles Search UI inside Accordion UI.

### ISSUE THREAD

**Issue by jmiguelherazo** [Semantic-Org/Semantic-UI#5330]
The results div styles are affected by the accordion styles, punctually the .title and .content classes

**Comment by dlynch29** [comment]
I had this issue at one point as well. I ended up not needing to use a search inside of an accordion, but definitely had this issue. 

It only seems to happen with "styled" accordions. The documentation doesn't say anything about it. I don't think it's that unreasonable of a design choice if you have a form that you'd like to hide behind the accordion.

**Comment by Banandrew** [comment]
See #4928.

**Comment by cluxter** [comment]
Did anyone find a proper way to fix this without waiting for an official patch? I'm having this issue as well and I would really like to use a search box inside a styled accordion. I tried several hacky things but didn't succeed in anything (my skills in CSS are really basic).

**Comment by ArturoCT** [comment]
Hi cluxter, I added some css style to fix it:
```css
.results .result{
	padding: 0px !important;
}

.results .result .content{
	padding: 0px !important;
}
```
But I don't know if this affects category search or something more.

**Comment by lubber-de** [comment]
Fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2197
