### ISSUE TITLE
Is the RegExp in SemanticUI case sensitive or case insensitive? - Usage Question

### ISSUE THREAD

**Issue by aguyinmontreal** [Semantic-Org/Semantic-UI#5331]
Is the SemanticUI RegExp case sensitive or case insensitive?
And what "flavor" of RegExp is it?

Can't make it work.

**Comment by Banandrew** [comment]
Hi, can you please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to show which part of the framework are you using and how?

**Comment by aguyinmontreal** [comment]
I think the label should rather be "usage question"...

By the way, I'm talking about the regExp for field validations

**Comment by Banandrew** [comment]
@aguyinmontreal [Here’re](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/form.js#L1136) the regular expressions for various field validations. If you’re still not sure what’s causing the problem, I can take a look at the specific example in a fiddle.

**Comment by aguyinmontreal** [comment]
You still did not answer my question! 

Is the regexp case sensitive or not!?

You showed me this:

    htmlID  : /^[a-zA-Z][\w:.-]*$/g,
    email   : /^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i,

The htmlID one is **case sensitive**, while the email one is **not case sensitive**!?

**Comment by Banandrew** [comment]
@aguyinmontreal All of the regular expressions that are used with strings are insensitive. Yes, the sensitivity varies from expression to expression, but not all of the expressions listed are tied directly to a rule—they’re just being used by the validation component internally, or not used at all like `htmlID`.

**Comment by aguyinmontreal** [comment]
ok, if I  want to validate a field with a custom **sensitive** RegExp rule , how do I "declare" that I want it to be sensitive?

**Comment by Banandrew** [comment]
@aguyinmontreal Try using the `regExp[expression]` validation rule and copy paste the expression that you need without the `i` flag. I might be more specific if you tell me what kind of content you’re trying to validate.

**Comment by aguyinmontreal** [comment]
aaah! didn't notice there was a flag there

I'll try that and let you know

It would be hard to explain what I'm trying to do, but the essence of it is that I need to have some specific letters capitalized
