### ISSUE TITLE
[Search] The input should be autocompleted with the first relevant search result as the search goes on

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5336]
Hi,

Semantic ui has a pretty nice feature which is it's select that allows the user to type a name and it instantly looks in all the values of a select and retrieve the best ones. 

I love this feature but I think one thing could be improved so it gets perfect! Please open this -> https://www.deobraemobra.com.br

In the search box at the top type just "arq" (without quotes). You will see semantic ui instanly searches and returns the results. My suggestion is this:

1) in the categories that there are no results it should not display the category name. If you do exactly as I said here (typing "arq") you will see other categorias like OBRA and LOJA have no result and SEMANTIC UI still displays those categories, it's pointless;

2) while the user is typing and semantic UI is filtering the results, it should make the first result the placeholder/mask of the input so the user can have a prediction right in the input while he is typing. I think I can easiily implement this binding a keyup event in the input and grabbing the first item and setting it as placeholder but hopefully someone already implemented this in the library and I am not aware;

I think both items above are not that complicated for those who knows a lot about semantic ui (not my case) OR maybe they are already implemented and I couldnt find how to fix that.

I appreciate your help into this, keep up this good library it's AMAZING.

**Comment by Banandrew** [comment]
I think the first issue comes down to implementing `fullTextSearch: 'exact'` (or rather `searchFullText`, the property names are inconsistent) for the search component: #5275.

**Comment by batata004** [comment]
@Banandrew  thanks man, the problem is not the exact or searchFullText feature, it works fine. It ommits correctly the results that should be ommited BUT it keeps the parent/category even if there is no child. Maybe I was not clear...

**Comment by Banandrew** [comment]
@batata004 Ah, excuse me, you’re right. Then it’s this one that should also include the search component, I’ll update it in a second: #4572.

**Comment by batata004** [comment]
@Banandrew that's exactly what I am looking for! It's sad it has been almost 8 months and this enhancement is still not implemented. It would make this component more intuitive cause hiding uneeded categories keep it clean and makes this component even more powerful!

About the second item I think it's equally important. If I could not be clear about it, could you please open your GMAIL.COM and in the search bar type the beginning of email of one of your most used contacts. You will see that google will suggest some emails you may want BUT ALSO gmail will make a placeholder in the search box with the most relevante result. Dont you think this is great and could be added to this great and amazing semantic ui library?

**Comment by batata004** [comment]
Any idea how I could implement 2?

**Comment by batata004** [comment]
@Banandrew could you please take a look again at https://github.com/Semantic-Org/Semantic-UI/issues/5347 ? There is clearly a bug, you probably didnt test the code right.
