### ISSUE TITLE
Dropdown search reshown after not found or successfull retrieve remoteData

### ISSUE THREAD

**Issue by royhg** [Semantic-Org/Semantic-UI#5337]
Hello, 

Did someone here knew how to reshow dd with search input after not found or after successfull retrieve remoteData without recreate dd or should we recreate the dd?

Additions, do you know how to limiting item showed at dd?

tq.
royhg.

**Comment by Banandrew** [comment]
Hi @royhg, sorry for the delay. I’m a bit confused after reading it, shouldn’t a dropdown already be opening after the data retrieval? I might be more specific if you show me your code, you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to do so. How do you recreate a dropdown?

>Additions, do you know how to limiting item showed at dd?

Do you want to make the menu smaller, or limit the amount of elements that are shown? If you’re working with remote data, I think you should just return less items from the API, and if it’s not possible, you could try utilizing [the API’s](https://semantic-ui.com/behaviors/api.html#/settings) `onResponse()` callback to reduce the amount of items that are returned.

**Comment by royhg** [comment]
Tq, for reply Andrew,
For a quick explanation, 
I just created pointing dd that have search input inside it, and the items was shown below it.
I have successfully had onResponse callback results,
but it seems overridden my search input,
How can I customise my search input still appear in the results onResponse callback?
So each time the DD showed let user can research/refiltered the results..
It seems throttle args is the way not to always send request to server so we can limiting the item results callback?

Sorry for my bad english😓


Royhg

**Comment by Banandrew** [comment]
Not sure what you mean when you say that your search input becomes overriden, can you please fork the fiddle that I linked above just to show what you’re doing? I’m not asking to mimic the API request itself, I think I’ll be able to figure the issue out without it.

**Comment by royhg** [comment]
Hey, Andrew,
I already found a way to always appearing the input search each time show the dd and its just recreating the script on the show function.
but right now Im still struggling to find which dd(index) has been shown/click/appear in the screen/table..

**Comment by royhg** [comment]
Hello,
Do you know how to get the first value of similar dropdown in multiple row?

row1-> dd-1
row2-> dd-2
row3-> dd-3

three of above dd is similar with different value..
How can I get each of their value?

tq. 
royhg

**Comment by Banandrew** [comment]
Hi, sorry for the delay, it depends on what kind of a dropdown you’re using, generally, you can get a value like so:
```JS
let value = $('.dd-1').dropdown('get value')
```
But if it’s a multiple dropdown, you’ll have to pluck the first value from `value` variable afterwards.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
