### ISSUE TITLE
Semantic ui sidebar with angular ui router 

### ISSUE THREAD

**Issue by Fabiman89** [Semantic-Org/Semantic-UI#5339]
i have found a problem working with semantic ui sidebar and angular ui router that i dont know how to solve.
i got the page layout like this: 

```HTML
<body> 
    <aside class="ui inverted labeled icon left inline vertical menu  " >
        <a class="item" ui-sref="home">
            <i class="home icon"></i>
            home
        </a>
    </aside>
    <div class="ui top fixed menu" ui-view="topMenu">
        <a class="item opener">
            <i class="sidebar icon"></i>
            Menu
        </a>
    </div>
    <div  class="pusher" ui-view></div>
</body>
```

but each time the content gets populated to the ui-view, it looses the context size, wich is 0 at initialization. the problem is that if the content from context is bigger than the viewport and need scrolling, it looses the y scroll property, i manage to correc this, but the overflow-y content do not get dimmed and the background inherits pusheable background color (body.pushable { background: #545454!important;);

is there a way to work arround this problem?

**Comment by Banandrew** [comment]
Hi @Fabiman89, I tried reproducing, but didn’t experience anything that would resemble your description. Can you please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) and create a test case reproducing your issue?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
