### ISSUE TITLE
[Form] - Add horizontal form

### ISSUE THREAD

**Issue by rosieks** [Semantic-Org/Semantic-UI#5342]
I'm just looking at switching from bootstrap to semantic-ui, but I cannot find equivalent of [horizontal forms](http://getbootstrap.com/css/#forms-horizontal). I found such [issue](https://github.com/Semantic-Org/Semantic-UI/issues/4480) but solutions there were not enough. I would expect that on each line labels/input are the same width and also that on narrow screen label is above the input.

**Comment by Banandrew** [comment]
Hi @rosieks, it doesn’t exist. There was a thread about it right before `2.0` was released #1583, but it was rejected—you can find an example there. If you’d like to know how to work with the framework’s source, please let me know.
