### ISSUE TITLE
Semantic UI select element and HTML5 required attribute

### ISSUE THREAD

**Issue by seeryj** [Semantic-Org/Semantic-UI#5348]
Hello,

I have Semantic UI select element with configuration like this: 
`<select class="ui search dropdown" id="element_id" name="element_name" required><option value="value_1">option_1</option></select>`

I added a required attribute, because I want to see default pop-up with notification when nothing is chosen. However instead of pop-up, browser (Chrome) gives me an error: "An invalid form control with name='element_name' is not focusable." (pop-up is not showed in other browsers too). As I understood it happens because Semantic UI insert select element inside div container, like this:
![select_element](https://cloud.githubusercontent.com/assets/28525462/25794485/cc468828-33d9-11e7-95c9-4cde2a4e0922.PNG)

If there are any workaround how to use both Semantic UI select element and HTML5 required attribute? Or maybe possible to fix it?

Thank you.

**Comment by Banandrew** [comment]
Hi @seeryj, sorry for the delay, you’ll have to use the form validation component, because SUI dropdowns are JavaScript enhancements over the default ones.
