### ISSUE TITLE
Dropdown bug in Firefox when using empty input in multiselect with scroll

### ISSUE THREAD

**Issue by whitejonty** [Semantic-Org/Semantic-UI#5350]
The bug also can be found in https://semantic-ui.com/modules/dropdown.html

To display the bug, first click on <> to show the code in multi-select of countries and then click on Select Country and hover over items, the focus disappear.

It happens only when the multi-select is empty and using scroll in dropdown with firefox

**Comment by Banandrew** [comment]
Hi, I can’t reproduce, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by vinayakkulkarni** [comment]
@whitejonty : kindly provide a test case, once you do I'll re-open the issue.
