### ISSUE TITLE
[Modal] Multiple modals are underneath each other.

### ISSUE THREAD

**Issue by Kjaal** [Semantic-Org/Semantic-UI#5351]
When using modals with a certain amount of content height, the two modals will be fitted underneath each other.

This is quite annoying when using a modal with a variable height. When changing from some content into another the modal might jump to the bottom of the page?

[Fiddle where two modals are fitted underneath ](http://jsfiddle.net/efp8z6Ln/523/)
[Fiddle where two modals are on top of each other because content height lowered](http://jsfiddle.net/efp8z6Ln/522/)

This is caused by the longer modal getting `display: static;`
When doing this on larger monitors the `display: static;` modal will be placed at the very back of the modals showed.

**Comment by Kjaal** [comment]
@Banandrew is there a temporary fix I can do for this?

**Comment by Banandrew** [comment]
@Kjaal Sorry for the delay, I actually don’t know. I found that we’re already tracking it in #2423, though, so I’m closing the issue as a duplicate. I reposted your test case, try asking there.

**Comment by jlukic** [comment]
Fixed in #2423
