### ISSUE TITLE
[Sidebar] Can not close/hide multiple sidebars on mobile devices

### ISSUE THREAD

**Issue by lvbeck** [Semantic-Org/Semantic-UI#5352]
The issue is similar with https://github.com/Semantic-Org/Semantic-UI/issues/5317
but more specifically under following circumstances:
1. have multiple sidebars in one page.
2. try to manually hide/close a certain sidebar by clicking a button inside the sidebar content:
```
$('.ui.sidebar>.button.close').on('click', function(){
    $(this).closest('.sidebar').sidebar('hide'); // this behavior has no effect
});
```

3. this bug only happens on mobile devices; no problem on desktop.

Tested semanti-ui version on 2.0.9, iPAD/iPhone iOS 10.3.1

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by lvbeck** [comment]
please check this jSFiddle http://jsfiddle.net/lvbeck/hy70hbob/1/embedded/

to reproduce the bug, please follow this:
step 1. click on "Sidebar Menu" button to show sidebar 1 (root menu)
step 2. click on "Products" in the sidebar 1 to show sidebar 2 (products menu) 
step 3. click on "Back" to hide sidebar 2 (go back to root menu)

on desktop, every thing works.
but on Mobile/iOS devices, step 3 fails (no effect)

**Comment by lfire** [comment]
mark
