### ISSUE TITLE
.bower.json not working with grunt

### ISSUE THREAD

**Issue by roelsgaard** [Semantic-Org/Semantic-UI#536]
When using grunt-bower-install no files are included in the index.html file.
This is due to grunt-bower-install not understanding the main section of the .bower.json file in semantic-ui.

I would suggest changing the main section in .bower.js from:

"main": [
    "./build/*"
  ],

to something like:

"main": [
    "./build/packaged/javascript/semantic.js",
    "./build/packaged/css/semantic.css"
],

I have tested that this works, but still need support for fonts, images, etc.

Kind regards
Chris

**Comment by batdevis** [comment]
Is it merged, in which branch?

**Comment by jlukic** [comment]
Current `bower.json` has a main that points to exact files not directories 
https://github.com/Semantic-Org/Semantic-UI/blob/master/bower.json#L12

**Comment by batdevis** [comment]
it points to
```
"main": [
"dist/semantic.css",
"dist/semantic.js"
]
```
so the problem with fonts and images still exists.
In order to work with gulp I changed main section with
```
"main": [
"dist/semantic.css",
"dist/semantic.js",
"dist/themes/default/assets/fonts/*"
"dist/themes/default/assets/images/*"
]
```
