### ISSUE TITLE
Typo in Popup Usage section "Specifying Content In Metadata"

### ISSUE THREAD

**Issue by davidlav** [Semantic-Org/Semantic-UI#5361]
In the info box [here](https://semantic-ui.com/modules/popup.html#specifying-content-in-metadata) the top bullets says "Using HTML `title` attribute" when it should probably say "Using HTML `data-title` attribute" instead, like the `data-content` and `data-html` tags mentioned after it.

**Comment by Banandrew** [comment]
Thank you, I opened a PR; closing as resolved.
