### ISSUE TITLE
Semantic UI bypasses browser form messages

### ISSUE THREAD

**Issue by Pithikos** [Semantic-Org/Semantic-UI#5365]
Hi there. I [posted this issue on stackoverflow](http://stackoverflow.com/questions/43939050/semantic-ui-bypasses-browser-form-messages), looking for a workaround. [Here's a fiddle too.](http://jsfiddle.net/y4uz1m53/2/)

I have a dropdown that works fine in its vanilla version - that is, the user gets a warning if the user forgets to fill it in.

As fast as I style the dropdown with Semantic UI, this functionality disappears. It seams the reason is that Semantic UI hides the original dropdown and uses some styled HTML in its place. With this, the `required` keyword stops having a functionality. Is there a solution to this?

**Comment by Banandrew** [comment]
Hi @Pithikos, you’re correct about the cause of it not working. You could additionally use the [validation](https://semantic-ui.com/behaviors/form.html) component that would be falling back to browser validation for clients with disabled JavaScript.

**Comment by Pithikos** [comment]
@Banandrew  I guess the problem with that solution would be that I end up with code duplication.

I thought about it and currently you need to run `$('.ui.dropdown').dropdown();` to get the the dropdown working. So there is some Javascript involved to get Semantic UI working with the existing HTML. The problem seems to be that whatever generates the new HTML doesn't respect the `required` attribute.

So it seems a bit like a bug from my perspective.

Generated code:
```
<input class="search" autocomplete="off" tabindex="0" data-enpassid="__6">
```

Should be:
```
<input class="search" autocomplete="off" tabindex="0" data-enpassid="__6" required>
```

**Comment by Pithikos** [comment]
Workaround (after calling `$('.ui.dropdown').dropdown();`):

```
$('.ui.dropdown').each(function(){
         $select = $(this).find('select');
         $input = $(this).find('input');
         if ($select.attr('required')) {
             $input.attr('required', 'true');
         }
});
```
