### ISSUE TITLE
Element override files not affecting generated stylesheets.

### ISSUE THREAD

**Issue by merravid** [Semantic-Org/Semantic-UI#5368]
I am trying to alter the look of the ui segment in the default theme by editing the segment.overrides file in src/themes/default/element/ and adding @borderRadius: 0px;

When I build semantic, the resulting segment.css file still shows the default (non-zero) radius.

Am I misunderstanding the use of the .overrides files?

If I change the segment.variables file, the change does go through to the css file.

**Comment by Banandrew** [comment]
Hi @merravid, sorry for the delay; yore’re correct in that `.overrides` are for *rules* overrides/extensions, and `.variables` are for LESS variables used by the framework’s [definition files](https://github.com/Semantic-Org/Semantic-UI/tree/master/src/definitions) or `.overrides`, but you shouldn’t be modifying the default theme—use `installation_folder/src/site` instead, it’s a separate namespace that’s going to override *everything*, both the initial definitions and the default theme.

Please let me know if you have more questions. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Here’s a list of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
