### ISSUE TITLE
[Dropdown] API for adding arbitrary selections (not only from the values available in the dropdown) in multiple selections dropdowns

### ISSUE THREAD

**Issue by DamodarSojka** [Semantic-Org/Semantic-UI#5369]
My use case:
I have a set of options which user is able to pick from, I also allow the user to provide own option, such choice is persisted to the database. When the dropdown is rendered it has to contain the option user has picked, in the case of option from the predefined set of options I am using dropdown('set selected'), in the case of an option which user has provided I am using dropdown('set text'). This solution works great for single choice dropdowns, however it seems to be impossible to accommodate it to the multi pick dropdowns as dropdown('set text') is not creating the UI elements representing the chosen elements inside the dropdown input (I believe they are called chips). Currently there Is no way to programmatically add the chips.

The only approach I can think of that wouldn't involve interaction with chips is to add a user supplied option to the pool of available options whenever I am creating the dropdown that should show such user supplied option. 

This seems like a hack and also on the UX side of things I don't want people to believe that the option that the user has added on his own is an actual option valid in the system. They are only "proposing" something.

**Comment by AaricChen** [comment]
hi,

how about this issues status. what's the next release date?
