### ISSUE TITLE
[Divider] - Wrong position of vertical divider

### ISSUE THREAD

**Issue by croogie** [Semantic-Org/Semantic-UI#5371]
**Steps to Reproduce**
1. Open docs at Divider component
2. Scroll down to Vertical Divider

**Expected**
The Divider should be positioned between each section.

**Result**
Dividers are positioned on the left side of divided sections.

**Testcase**
http://jsfiddle.net/rduvhn8u/155/

**Comment by Banandrew** [comment]
Hi @croogie, thank you, but we’re already tracking it here: #4342.
