### ISSUE TITLE
Drop down css not working with knockout bind option

### ISSUE THREAD

**Issue by MichaelMeyer1** [Semantic-Org/Semantic-UI#5372]
The issue is that when I bind options to the dropdown "ui dropdown" makes it disappear and nothing is in the cell.  If i remove that css then i see the out of the box dropdown.

creating a table will a viewmodel collection and want a dropdown of values for the individual risks

//part of the viewmodel
    var ViewModel = {
        Collection: ko.observableArray(),
        availableRisks: ['L', 'H'],

//the individual risk item in the table, the Collection is bound to the full table

<td>
    <div class="ui dropdown">
          <select data-bind="options: $parent.availableRisks, value: risk"></select> 
</div>
</td>

using 
$('.ui.dropdown')
  .dropdown();
  dosent help

![image](https://cloud.githubusercontent.com/assets/13951445/26089032/e5a0ee06-39b7-11e7-8601-5c59d44cfd4d.png)

without "ui dropdown"
![image](https://cloud.githubusercontent.com/assets/13951445/26089077/325c1f22-39b8-11e7-9458-d9c4c52b6b83.png)

**Comment by MichaelMeyer1** [comment]
![image](https://cloud.githubusercontent.com/assets/13951445/26089032/e5a0ee06-39b7-11e7-8601-5c59d44cfd4d.png)

**Comment by MichaelMeyer1** [comment]
without "ui dropdown"
![image](https://cloud.githubusercontent.com/assets/13951445/26089077/325c1f22-39b8-11e7-9458-d9c4c52b6b83.png)

**Comment by Banandrew** [comment]
Hi @MichaelMeyer1,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by MichaelMeyer1** [comment]
Adding $('.ui.dropdown').dropdown('refresh'); after adding the data to the knockout observable collection made the dropdown work.
