### ISSUE TITLE
[Dropdown] Security Vulnerability with data-text

### ISSUE THREAD

**Issue by daneren2005** [Semantic-Org/Semantic-UI#5376]
When adding the `data-text` option to dropdown item's, when the user clicks on them the contents are executed.  Here is a simple JSFiddle with two dropdowns: http://jsfiddle.net/daneren2005/7x4jqbe7/2/.  The top one uses `data-text` and you will get a popup `XSS` when you select the only option.  The second does not use it and isn't vulnerable.

**Comment by daneren2005** [comment]
This is still an open security vulnerability

**Comment by dreaming-augustin** [comment]
Although there is currently no volunteer to work on any of this, but it would be nice to have a whole section dedicated to security on the Semantic-UI web site, and for each module, a sub-section on the secure use of that particular module.

**Comment by dreaming-augustin** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/6570

**Comment by daneren2005** [comment]
Honestly I would probably hit it myself if it wasn't for all of the open PRs and it seeming to be a waste of time to try to add to this project.

**Comment by dreaming-augustin** [comment]
I know what you mean.   
Meanwhile, if you have the time and feel so inclined,  you can always try submitting a PR to Fomantic-UI, https://github.com/fomantic/Fomantic-UI which is an active fork of this project...

**Comment by daneren2005** [comment]
I will have to take a look at it.  I am still using 2.2 so I would need a decent chunk of time to upgrade to a fork like that to validate all of the changes don't break the crap ton of custom css I use on top of Semantic.  Thanks for the link though.

**Comment by jlukic** [comment]
This is not a security issue, removing html execution is already a setting
```javascript
$('.ui.dropdown.selection').dropdown({preserveHTML: false});
```

http://jsfiddle.net/15pw0Lku/

**Comment by lubber-de** [comment]
We implemented data sanitizing and added a security page to the docs
https://fomantic-ui.com/modules/dropdown.html#/security

**Comment by dreaming-augustin** [comment]
For the record, I repeat what I already said elsewhere: 
https://github.com/Semantic-Org/Semantic-UI/issues/6570#issuecomment-451653492 

> @lubber-de What you did is great! Thank you very much for taking the time to implement this. I am very happy that Fomantic is making such progress and taking security issues seriously. Many thanks to the whole team.
