### ISSUE TITLE
Dropdown open after modal show

### ISSUE THREAD

**Issue by lackneets** [Semantic-Org/Semantic-UI#5378]
First dropdown inside the model opens after the modal is shown

see the pen: https://codepen.io/lackneets/pen/LyBwEK

**Comment by lackneets** [comment]
Sorry I found it caused by [autofocus](https://semantic-ui.com/modules/modal.html#/settings) option.

**Comment by FuriosoJack** [comment]
Realmente pasa por la opcion showOnFocus del dropdown 

https://semantic-ui.com/modules/dropdown.html#/settings

` $('.ui.dropdown').dropdown({
        showOnFocus:false
    });`
