### ISSUE TITLE
[Input] Add connected input fields

### ISSUE THREAD

**Issue by traverse** [Semantic-Org/Semantic-UI#5379]
Hello,

Like a label or action attached to an input I would like inputs attached to other inputs or inputs with a label in between and attached to each other.

Here's a small example of what I mean https://codepen.io/Traverse/pen/JNaYyZ

I would love some feedback because my example was put together in a short amount of time so I'm sure there's a better way to do this.

**Comment by klausklapper** [comment]
This is something I've been missing desperately in Semantic-UI. To me, it feels natural to include this option the same way as it is done for buttons.
