### ISSUE TITLE
semantic+three.js canvas position issue

### ISSUE THREAD

**Issue by alko79** [Semantic-Org/Semantic-UI#5381]
this is my code:

```
<main class="Site-content">
    <div class="ui  grid basic segment">
       <div class="ui menu inverted vertical fixed ">""some vertical menu code""</div>
       <div class="thirteen wide column right floated">
         <canvas class="canv" id="myCanvas" height="500" width="800"  ></canvas>
       </div>
   </div>
...
<script type="text/javascript">
 var camera, scene, renderer;
 var mesh;
 init();
 animate();
 function init() {
   camera = new THREE.PerspectiveCamera( 70, 800 / 500, 1, 20000 );
   camera.position.z = 10000;
   scene = new THREE.Scene();
   var texture = new THREE.TextureLoader().load( '{{ asset('textures/cont.png') }}' );
   var geometry = new THREE.BoxBufferGeometry( 2000, 2000, 2000);
   var material = new THREE.MeshBasicMaterial( { map: texture } );
   mesh = new THREE.Mesh( geometry, material );
   scene.add( mesh );

   var canv = document.getElementById("myCanvas");
   renderer = new THREE.WebGLRenderer({ canvas: canv });
   renderer.setPixelRatio( window.devicePixelRatio );
   renderer.setSize(800, 500 );
   document.body.appendChild( renderer.domElement );

   }

   </script>
```

problem is that the canvas is always on the bottom left of the screen. instead of placing in the right-floated div ...
why document.body.appendChild( renderer.domElement ) is not appending into that div ?

**Comment by Banandrew** [comment]
Hi @alko79,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
