### ISSUE TITLE
Left rail ubuntu issue

### ISSUE THREAD

**Issue by OlegBrazhnichenko** [Semantic-Org/Semantic-UI#5383]
Left rail is under ubuntu menu.

![screenshot from 2017-05-18 15 14 50](https://cloud.githubusercontent.com/assets/11982224/26201666/ccb60256-3bdc-11e7-8ce4-de685a410e5c.png)

**Comment by Banandrew** [comment]
Hi @OlegBrazhnichenko, that’s the intended behavior of the rail component; the “Introduction” section on that page covers everything from the standard rail size to the requirement of breakpoints.
