### ISSUE TITLE
[Dropdown] How to show more items in dropdown?

### ISSUE THREAD

**Issue by IsaacHub** [Semantic-Org/Semantic-UI#5384]
[https://jsfiddle.net/iselwin/0kstzpvw/2/](https://jsfiddle.net/iselwin/0kstzpvw/2/)

The problem here is the list contains more than 10 items but while clicking the dropdown it only shows 3 items, how to make some more items appear adaptive to the viewport or 10 items at once??

This page [https://semantic-ui.com/modules/dropdown.html](https://semantic-ui.com/modules/dropdown.html) is useless, because it shows the HTML code only, should have shown JS also.

**Comment by Banandrew** [comment]
Hi @IsaacHub, the height is responsive and will show this amount of items depending on the screen size:
```LESS
@selectionMobileMaxItems: 3;
@selectionTabletMaxItems: 4;
@selectionComputerMaxItems: 6;
@selectionWidescreenMaxItems: 8;
```
You can tweak those variables in `installation_folder/src/site/modules/dropdown.variables`, just add them there like so:
```LESS
// installation_folder/src/site/modules/dropdown.variables:
@selectionWidescreenMaxItems: 10;
```
Then rebuild the framework with `gulp build`. Please let me know if you have more questions; the following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by outline4** [comment]
Hi, I know this question was initially posted in the wrong place, but I have the exact same problem. 
But my problem is: I am using the standalone files. No gulp, no build tools. Where do I have to change these values in this case? 
Showing just 3 items is very confusing... I upgraded from version 1 and the behavior was better back then.

**Comment by Banandrew** [comment]
Hi @outline4, your only option is to override it with CSS, do something like that somewhere in your project, but after `semantic.css`:
```CSS
.ui.dropdown .menu {
    max-height: value;
    /* You might also want to add `!important` to automatically override all media-queries. */
}
```
If you don’t use build tools, you’ll have to do similar overrides every time you’ll need to change something in SUI, which might become difficult to maintain in the long run.

**Comment by outline4** [comment]
Thank you so much! That fixed it! 

P.S. Don't tell me about the build tools. Luckily it's only this particular project...
