### ISSUE TITLE
Icon Fonts with Data URIs not working

### ISSUE THREAD

**Issue by moosetraveller** [Semantic-Org/Semantic-UI#5385]
We have an issue with the icon fonts `Dropdown` and `Checkbox` when using Internet Explorer 11 and an Endpoint Security solution. All icon fonts which are stated by a Data URI seemed to be blocked. 

Fact is, that the Endpoint Security solution does not allow creation of `*.tmp` files in `*\Users\*\AppData\Local\Temp` and somehow these Base64-encoded Data URI seems to be stored in these files. When deactivating the rule, the icons were shown. However, it's not an option according to the sysops. The rule was introduced in order to have a better protection against Ransomware.

Interestingly, looking at the Semantic UI Dropdown page, the icons are shown. I guess that the CSS file is not cached...?

However, **this is, of course, not a bug but** I hope someone has an idea how to use Semantic UI respectively Data URIs with a strict Endpoint Security solution? 

The only (workaround) solution I might think of is to "override" the font-family of the `.dropdown` class and include the fonts as a file (respectively by an url and not a Data URI) or include another font. **Does anyone knows where I can get both icon fonts (Dropdown and Checkbox) as a file?**

PS. The Icon font `Icon` works fine since it's included as a file.

**Comment by moosetraveller** [comment]
See also: [http://stackoverflow.com/questions/44049818/data-urls-in-css-not-working-with-an-endpoint-security-solution](url)

**Comment by moosetraveller** [comment]
Workaround:

```
.ui.dropdown > .dropdown.icon {
    font-family: 'Icons' !important;
}

.ui.checkbox input:checked ~ .box:after, .ui.checkbox input:checked ~ label:after {
    font-weight: bold;
    content: '\2714' !important;
    font-family: 'Icons' !important;
}
```

**Comment by Banandrew** [comment]
I don’t understand why it was done this way more than 2 years ago, maybe we can take another look at it.

**Comment by moosetraveller** [comment]
Beside discussing the use of Data URIs: 
Why are Data URIs for those specific icon fonts used since both icons (dropdown and checkbox) are also provided by the `Icons` font?

Side note: 
Another difference between the Semantic UI page and our web application is that we are using Angular 4. It's an assumption, but the problem might be that the Endpoint Security solution cannot identify the Base64 string at some point when using Angular. 

From my point of view it's not wrong to use Data URIs and therefore it's in my opinion not a bug.
