### ISSUE TITLE
[Sidebar] [Missing Docs] - Direction is not documented

### ISSUE THREAD

**Issue by italomaia** [Semantic-Org/Semantic-UI#5389]
**Steps to Reproduce**
1. Try to create a sidebar from some direction using docs
2. Try to find the data- settings in https://semantic-ui.com/modules/sidebar.html#/settings
3. You're alone

**Expected**
https://semantic-ui.com/modules/sidebar.html#/settings should have the direction settings documented

**Comment by Banandrew** [comment]
Hi @italomaia, can you please elaborate? I didn’t understand what’s missing.
