### ISSUE TITLE
Problem with Dimmer and Modal on same view

### ISSUE THREAD

**Issue by Barozzi** [Semantic-Org/Semantic-UI#5390]
I encountered an issue having a dimmer are and a modal on the same view caused the dimmer to not display content and freeze the page any time after the modal was displayed. 
I was able to work around this by switching the dimmer to a second modal to get the desired affect.

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by vinayakkulkarni** [comment]
@Barozzi : Can you please provide a test case? Once you do, I'll re-open the issue.
