### ISSUE TITLE
[build] gulp build command not working

### ISSUE THREAD

**Issue by simoncarbajal** [Semantic-Org/Semantic-UI#5391]
`gulp build` can't complete the 'build-assets' phase due to the following error:
```
GulpUglifyError: unable to minify JavaScript
Caused by: DefaultsError: `preserveComments` is not a supported option
semantic/tasks/config/tasks.js:96
          if(error.filename.match(/theme.less/)) {
                           ^
TypeError: Cannot read property 'match' of undefined
```
And is NOT fixed by commenting the following lines:
```
./tasks/config/tasks.js:148:      preserveComments : 'some'
./tasks/config/tasks.js:162:      preserveComments : false
```
Steps to reproduce it:
```
npm install semantic-ui --save
cd semantic/
gulp build
```

**Comment by fabulousduck** [comment]
would also like to see this answered as i am having the same issue. ⌛️

**Comment by fabulousduck** [comment]
i tried to resolve this by downloading the semantic zip from the website.
although this zip does not contain everything and will still error out giving the following
`This relative module was not found:  *./themes/default/assets/images/loader-large.gif in ./~/css-loader?{"minimize":false,"sourceMap":false}!./semantic/dist/semantic.min.css`

**Comment by fabulousduck** [comment]
@simoncarbajal i fixed this by completely removing semantic and reinstalling it. not sure where the cause lies. :man_shrugging:

**Comment by tarkwyn** [comment]
Fix is to change `filename` to `fileName` in line 96 of semantic/tasks/config/tasks.js

e.g. `if(error.fileName.match(/theme.less/)) {`

**Comment by j-f1** [comment]
@tarkwyn Can you make a pull request to fix this?

**Comment by SamPlusPlus** [comment]
I can confirm that @tarkwynl 's change worked for me.

**Comment by neokio** [comment]
The camelCase issue didn't cause any problems, however I was unable to successfully `gulp build` until I commented out the two `preserveComments` tags in /semantic/tasks/config/tasks.js

**Comment by SamPlusPlus** [comment]
@neokio I also received the perserveComments error, but I had to upgrade my version of node to the latest, to get pass that. 

I will not very experienced with gulp/node so take my inputs with a grain of salt.

**Comment by neokio** [comment]
Interesting! Good advice in general, so I updated node from 7.7.1 to the latest (8.1.3), and reinstalled npm (`npm install -g npm`) just to be sure.

The above error still appears, unless I remove both `perserveComments`.

**Comment by neokio** [comment]
The error persists in 2.2.11 ... unable to successfully `gulp build` until I removed both `perserveComments` lines from /semantic/tasks/config/tasks.js.

**Comment by SamPlusPlus** [comment]
@neokio could be unrelated, but when I said I updated to the latest for Node Js I actually went for  LTS, not current. https://nodejs.org/en/ so I went on version 6.11.1

**Comment by neokio** [comment]
I think I found the problem. This issue ... https://github.com/terinjokes/gulp-uglify/issues/265 ... and the latest gulp-uglify release notes reveal that release v3.0.0 of gulp-uglify REMOVED the custom option `preserveComments` :)

In other words, `preserveComments` is now deprecated.

**Comment by vinayakkulkarni** [comment]
Yep, can confirm the issue. Commenting out L148 & L162 solves it. 

Tried with older version of Node / npm & latest version too.
It's not camelCase related or node version related

**Comment by rafaelgilead** [comment]
After all, what will be done in the semantic ui ? To remove the option or comment and wait for uglify downgrade ?

**Comment by jlukic** [comment]
I'll fix the dependencies so that we dont use this version of uglify. Sorry about this guys.

**Comment by boloog** [comment]
I also encountered the same problem, the solution
`require('semantic-ui/dist/semantic.min.js')`
`require('semantic-ui/dist/semantic.min.css')`

**Comment by jpetitte** [comment]
I'm a little late to the party, but I figure another confirmation can't hurt. Commenting out L148 & L162 worked for me as well. Thanks!

**Comment by rafaelgilead** [comment]
Commenting out L148 & L162. It worked for me too.

**Comment by bhargavy** [comment]
Commenting out L148 & L162. It worked for me too.

**Comment by Madankapoor** [comment]
Commenting out only worked , can't find out if issue is in gulp-uglify or semantic ui.

**Comment by jlukic** [comment]
Will get fix in over weekend. Thanks for patience.

**Comment by cur33** [comment]
Commenting worked for me, too. Glad I wasn't the only one with this problem, since I'm new to semantic ui and gulp--and I'm on a time crunch! Thanks guys!

**Comment by sergiomar73** [comment]
Hi, I found that Uglify plugin changed its options and now preserveComments is obsolete:

[https://github.com/gruntjs/grunt-contrib-uglify#deprecated-options-from-2x](https://github.com/gruntjs/grunt-contrib-uglify#deprecated-options-from-2x)

```
Option           | Replacement
preserveComments | output.comments
```

So, just replacing in these 2 lines in **semantic/tasks/config/tasks.js**:

```
./tasks/config/tasks.js:148:      preserveComments : 'some'
./tasks/config/tasks.js:162:      preserveComments : false
```
 with:

```
output: {
    comments: 'some'
}

output: {
    comments: false
}
```
worked for me.

**Comment by kevinmwangi** [comment]
@sergiomar73 Thanks this fixed it

**Comment by basselAhmed** [comment]
@sergiomar73 Thanks man, I can confirm this fixes it.

**Comment by cluxter** [comment]
@sergiomar73 I confirm it too.

**Comment by kutalev** [comment]
@sergiomar73 It worked. Thanks!

**Comment by jlukic** [comment]
A weekend late but pushing this now.

**Comment by erdi** [comment]
What's the timeline for releasing 2.2.12, @jlukic?

**Comment by cluxter** [comment]
It's kind of too bad that we have to wait until v2.2.12 is released to see this bug fixed :/
This is a blocking issue for the one who doesn't patch manually and needs to use `gulp` (sometimes you have to). Wouldn't a v2.2.11.1 be a better solution? Just asking.

**Comment by jlukic** [comment]
Later tonight

**Comment by axper** [comment]
Hmm, still getting this error with v2.2.12:
```
[15:23:13] Plumber found unhandled error:
 GulpUglifyError: unable to minify JavaScript
Caused by: DefaultsError: `comments` is not a supported option
File: /home/axper/project/semantic/dist/components/sticky.js

```

**Comment by zehmigueljr** [comment]
Hi @jlukic , I tried build a test of semantic and the same problem occured. The file tasks.js 
already in the new version, with your last commit. I had to apply the solution that @sergiomar73 showed.
I tried build in 2.2.11 and 2.2.12.

**Comment by jlukic** [comment]
Patch incoming

**Comment by jlukic** [comment]
And out `2.2.13`

**Comment by zehmigueljr** [comment]
Hi, @jlukic 
I have installed de last updates (2.2.13) of semantic and tried build the project.
The fix worked succefully.

Thanks a lot.

**Comment by jlukic** [comment]
Sorry about mistakes with the first fix.

**Comment by cluxter** [comment]
v2.2.13 works on my side. Thanks a lot @jlukic !

**Comment by flornet** [comment]
Hi, I've been having the exact same issue with 2.2.13.
To solve it, I've had to update Node.js & NPM.
It might be obvious... but it wasn't for me :)

**Comment by dickmao** [comment]
Yes, can confirm that default version of nodejs 4.2.6 for ubuntu 16.04 won't work.  Needed to upgrade to 6.x.x.  Thanks.

**Comment by peppelinux** [comment]
Confirmed that it's a problem related to nodejs version. Fixed with:

````
export NODE_VERSION="node-v8.11.1-linux-x64"
cd /opt
# LTS version
wget https://nodejs.org/dist/v8.11.1/$NODE_VERSION.tar.xz
# decompress it
tar xvf $NODE_VERSION.tar.xz
cd $NODE_VERSION

# put it in the executables defaults environment path
export PATH=$PATH:/opt/$NODE_VERSION/bin:$PWD/node_modules/bower/bin
````

then use node.js as usual.
Remember also to uninstall previous node.js installations

**Comment by harshsingh206** [comment]
Plumber found unhandled error:
 GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc ())
 
Any idea on this?
