### ISSUE TITLE
[Flag] - Your Bug Name

### ISSUE THREAD

**Issue by alexanderfanden** [Semantic-Org/Semantic-UI#5393]
**Expected**
The Burma/Myanmar flag is old, it should look like this:
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/255px-Flag_of_Myanmar.svg.png

**Result**
The flag is outdated

**Comment by Banandrew** [comment]
Hi @alexanderfanden, thank you, but we’re already tracking it here: #5145.
