### ISSUE TITLE
[Button] - Load character in button too late

### ISSUE THREAD

**Issue by ky0ncheng** [Semantic-Org/Semantic-UI#5394]
![](http://wx4.sinaimg.cn/mw1024/6d9bd6a5gy1ffu3thq4dwj20920g1q30.jpg)

**Comment by Banandrew** [comment]
Hi @ky0ncheng, can you please elaborate? Is it the documentation website? Is it only on mobile, did you experience it on desktop computers? Were you using a proxy to see the website, maybe it was just a slow connection?
