### ISSUE TITLE
[Website] semantic-ui.com is not accessible from Russia

### ISSUE THREAD

**Issue by archangel-irk** [Semantic-Org/Semantic-UI#5396]
I stay in Moscow and I don't have access to https://semantic-ui.com/ website. Just 404 by timeout.
But http://react.semantic-ui.com/introduction works.

Note: Site works via VPN (Germany).

I like Semantic-UI library and would like to use it in my own projects. But site with docs are not accessible.

**Comment by Banandrew** [comment]
Hi @archangel-irk, I’m also in Moscow, and it’s accessible on wired Beeline. I too had this one website timing out without a single reason to do so, and had to use a proxy server to acess it, so I’m assuming it’s some weird local ISP issue; I don’t think that something can be done on the documentation’s end. Try Google’s DNS, maybe it’ll help.
