### ISSUE TITLE
[install] Autoinstall building Docker image issue

### ISSUE THREAD

**Issue by gthill7** [Semantic-Org/Semantic-UI#5398]
I'm having an issue when trying to build a docker image. It fails during the Semantic UI install even though I have auto install set as 'true'.

<img width="855" alt="screen shot 2017-05-23 at 7 04 44 am" src="https://cloud.githubusercontent.com/assets/17909631/26351572/331a019e-3f86-11e7-9c86-b997636ead92.png">

**Comment by nehvaleem** [comment]
also having this issue

**Comment by crodriguezvega** [comment]
Same here.

**Comment by FrankTheCodeMonkey** [comment]
same issue
