### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by patie** [Semantic-Org/Semantic-UI#540]
What about time-line

something like this
![timeline](https://f.cloud.github.com/assets/760932/1894192/750324ae-7ad7-11e3-8d75-a4704ec33c13.png)
source(http://medleyweb.com/wp-content/uploads/2012/09/Timeline.png)

options vertical,horizontal,only left side bubbles, only right side bubbles, bubbles on both sides

**Comment by fvpDev** [comment]
Is there a way to have a horizontal timeline feed in 2.0?

**Comment by andreweugene** [comment]
Feature still available. Tried making it using cards but I can't use the **point** feature on cards.

**Comment by free2shout** [comment]
Timeline theme in Feed it's ok. But what about displaying the line in the middle of it's container and the content boxes on both sides. Can we do that already?

**Comment by abegehr** [comment]
@jlukic, can we reopen this feature request issue?
Extending the Feed view to support some sort of timeline would be very useful for me.

**Comment by prouast** [comment]
Agreed
