### ISSUE TITLE
[Dropdown] - add result message not displaying

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#5401]
addRresult message for dropdowns that allow additions no longer displays.

I'm not sure with if this was intentionally removed, but the docs appear to suggest that it's still supported.  however, it doesn't appear that this is any option for toggling the message on or off.

**Testcase**
http://jsfiddle.net/55913p4f/1/

**Comment by Banandrew** [comment]
Hi @dmaison, that’s because `hideAdditions` is `true` by default, disable it and the message will start showing. We’re already tracking it here #4052; marking the thread as a duplicate.

**Comment by dmaison** [comment]
ah excellent thank you!
