### ISSUE TITLE
[Sidebar] Unable to use context without nudges to pusher elements?

### ISSUE THREAD

**Issue by saikrishnadeep** [Semantic-Org/Semantic-UI#5403]
If you have a look at this example: http://jsfiddle.net/L4yjsymd/ After I initially click the Menu to get the sidebar and then If I close it, It nudges the `.pusher` element to expand it. It's very noticeable. I was trying to figure out if the sidebar module was in some way changing the pusher's padding or margin properties. Unfortunately, I couldn't find how pusher was being modified. 

Is this an expected behavior? If yes, is there any workaround to fix the nudges? This nudging is much pronounced in this fiddle: http://jsfiddle.net/L4yjsymd/52/

Any help is appreciated :)

**Comment by Banandrew** [comment]
Hi @saikrishnadeep, everything seems to be working as expected, I’m not sure what nudging you’re talking about besides the default pushing animation, if it exists, I don’t see it. A video might help, I usually use [this little open source program](http://www.screentogif.com/) to quickly record the screen and showcase dynamic content, it’s also portable.

[Here’s what I’m seeing](http://i.imgur.com/4IKi4Lu.gifv).

**Comment by saikrishnadeep** [comment]
Hi @Banandrew  Thanks for the suggestion. Here is what I'm seeing: http://i.imgur.com/kmyybgP.gifv If you notice that towards the end of the animation. The right and bottom margin/padding of the pusher element is being adjusted which is causing it to slightly nudge. I hope the gif confirms it. I'm on Chrome Version 58.0.3029.110 (64-bit)

**Comment by Banandrew** [comment]
@saikrishnadeep Thank you, I was able to reproduce it—the content jumps on smaller screens when the second scroll bar appears. You can either force the scroll bars:
```CSS
.ui.attached.segment {
  overflow-y: hidden; /* Or “scroll” as an alternative. */
}
```
Or simply use `transition: 'overlay'`. I don’t think that anything can be done about it besides from that, including the framework level.
