### ISSUE TITLE
form onSuccess and add prompt do not function as expected

### ISSUE THREAD

**Issue by jagooding** [Semantic-Org/Semantic-UI#541]
This is in reference to #538 

``` javascript
{
    inline : true,
    on     : 'blur',
    onSuccess : function(){
        return false;
    }
}
```

Does not prevent the form from being submitted.

Also, I am unable to add inline prompts to a field. I don't get any sort of output on the console, no debugging, no errors, no nothing :|

``` javascript
var field = $('form').form('get field', 'username');
$('form').form('add prompt', field, 'that username is already taken');
```

**Comment by varemenos** [comment]
There is a similar bug with `onFailure`, and it's not possible to prevent the form from submitting because onFailure doesn't provide a jQuery event parameter to use in the callback...

**Comment by dobrych** [comment]
Such an obvious case: prevent submitting of invalid form input and there no direct simple way to do it, `onFailure` doesn't provide the original event to make `event.preventDefault()`
trying a workaround with regular jquery `.on('submit', callback)` approach, it triggers callback, but ignores the `event.preventDefault()` inside it and form still submits, seems like Semantic UI actually submits form programmatically…

So what is the SemanticUI way of managing that case?

**Comment by jlukic** [comment]
Returning false from `onSuccess` will prevent submission (`event.preventDefault()`), as the docs states. If a form fails to validate it will `preventDefault` as well

**Comment by dobrych** [comment]
I've just discovered myself that issue was caused by other js lib, we used mixpanel's track_form feature that seemed to trigger programmatically form again bypassing semantic ui handler.
It was hard to track it down, sorry for false report.
