### ISSUE TITLE
[Dropdown] Search in menu type of dropdown's half is unvisible on mobile mode

### ISSUE THREAD

**Issue by ceremcem** [Semantic-Org/Semantic-UI#5415]
![image](https://cloud.githubusercontent.com/assets/6639874/26513796/2ade26c0-4276-11e7-8a04-028142912211.png)

**Comment by lubber-de** [comment]
Fixed in the upcoming 2.7.5 of Fomantic-UI by https://github.com/fomantic/Fomantic-UI-Docs/pull/122
