### ISSUE TITLE
How to turn off modal transition

### ISSUE THREAD

**Issue by dongwooklee9** [Semantic-Org/Semantic-UI#5419]
Im using modal

$('.ui.long.modal')
.modal('setting', "transition", "fade")
.modal('show')

it's wokring great, but
I want to know how to turn off modal animation.

thanks!

**Comment by Banandrew** [comment]
Hi @dongwooklee9, it’s not supported out of the box. Modals use the transition component, so you could write your own transition styles and use them instead. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by jlebrijo** [comment]
We can remove transition, decreasing duration:

`$('.ui.long.modal')
.modal('setting', "duration", "0")
.modal('show')`
