### ISSUE TITLE
Accordion tab problem

### ISSUE THREAD

**Issue by fridzema** [Semantic-Org/Semantic-UI#5421]
Hello, 
I am dealing with a strange problem.
I want to use a tabular menu inside the accordion. 

Now the problem is that somehow the html gets scrambled inside the accordion.

I have made a fiddle to demonstrate this problem:
[jsfiddle](https://jsfiddle.net/d9epryur/5/)

The problem occurs when you toggle the first tab or open any other tab. 
On first initialization there is nothing wrong en everything works fine.

I hope anyone can help me out with this

**Comment by Banandrew** [comment]
Hi @fridzema, sorry for the delay, set `animateChildren` to `false` on your accordion initialization:
```JS
$('.ui.accordion').accordion({
  animateChildren: false
})
```
It animates the tabs and messes up with their CSS a bit.
