### ISSUE TITLE
[Comment] - Doesn't work inside a modal content

### ISSUE THREAD

**Issue by tienanh2007** [Semantic-Org/Semantic-UI#5422]
**Steps to Reproduce**
just put it inside a modal content

**Expected**
Correct format

**Result**
Incorrect format

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by tienanh2007** [comment]
My bad it was my fault that it didn't work
