### ISSUE TITLE
Patreon support 

### ISSUE THREAD

**Issue by madela** [Semantic-Org/Semantic-UI#5424]
Hello,

I love this project and I think is the best UI framework at the moment, but there is too many unresolved issues on the repository. I think it's too much work for jlukic. What do you think about the idea of supporting jlukic with Patreon so he can have a monthly income so he can dedicate more time to the project?

 jlukic, What do you think about it? Is it ok for you? How much do you need monthly?

**Comment by j-f1** [comment]
@madela You might want to read through #2201 too.

**Comment by Banandrew** [comment]
I think we can close this thread as a duplicate.
