### ISSUE TITLE
How to show an HTML element only in Tablet breakpoint, not in mobile

### ISSUE THREAD

**Issue by softauthor** [Semantic-Org/Semantic-UI#5426]
I tried to show a specific element on in Tablet view using "tablet only" classes. But that element shows in mobile as well. I could do it using @media query but I wonder How to hide it on the mobile using semantic class if any? Thanks

**Comment by Banandrew** [comment]
Hi @softauthor, SUI doesn’t have classes that hide elements at certain breakpoints, the only exception being the grid component, so if you’re trying to hide something other than the grid, it’s unsupported. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
