### ISSUE TITLE
[Docs] Ajax Tabs

### ISSUE THREAD

**Issue by dvnrsn** [Semantic-Org/Semantic-UI#5427]
Sorry I'm new, but just wondering if I can get a little pointer. I'm a little confused by the docs for ajax and tabs.  I'm trying to load new content into some tabs with 

```javascript
$('#tabBar .item').tab({

                    cache: false,
                    apiSettings: {
                        url: 'myURL',
                        responseAsync: function (data, settings) {
                            debugger;
                            //}
                            //mockResponse: function (settings) {
                            //    var response = {
                            //        first: 'AJAX Tab One',
                            //        second: 'AJAX Tab Two',
                            //        third: 'AJAX Tab Three'
                            //    };
                            return settings[data.urlData.tab];
                        }
                    },
                    context: 'parent',
                    auto: true,
                    path: '/'
                });
```

If I use onResponse, I lose the settings, which are nice for knowing which tab to switch.  If I use responseAsync, I don't actually get the URL response.  What I want is to be able to define the URL and have access to the settings object.  What am I misunderstanding?
https://semantic-ui.com/modules/tab.html#retreiving-remote-content

**Comment by devin42r** [comment]
The url falls right inside of apiSettings <a href="https://semantic-ui.com/behaviors/api.html#modifying-response-json">here</a>, but when you actually look at source code, it's outside of apiSettings object...?

**Comment by devin42r** [comment]
I figured it out...my problem was with the line: `context : 'parent'`

Is there documentation on context, auto, and path?  Could really use some fleshing out <a href="https://semantic-ui.com/modules/tab.html#retreiving-remote-content">here</a>

https://jsfiddle.net/devconn/no9fmyzu/15/

**Comment by devin42r** [comment]
Is there a means to trigger ajax for tab on page load without artificially clicking?

**Comment by devin42r** [comment]
Also, I'm struggling to get angular components to render through tab api...? <a href="https://stackoverflow.com/questions/44398781/semantic-ui-ajax-tab-and-angular-components">stackoverflow</a>

**Comment by Banandrew** [comment]
Hi @devin42r, sorry for the delay, there’s `changeTab` method that allows to change tabs programmatically, it should also trigger AJAX. For example:
```JS
$('#tabBar1 .item').tab('change tab', 'fifth')
```
As for Angular, jQuery doesn’t play well with JavaScript frameworks, so it might be an issue with Angular lifecycle—maybe it’d be best to ask around Angular communities.
