### ISSUE TITLE
Popup keeps appear in 'bottom center' even if i set it's position as 'top center'

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5428]
So, what is this about? I set properly `position: 'top center'`, but popup appears in bottom center position without any errors and warnings thrown.

**Comment by vinayakkulkarni** [comment]
Dear @JamesJGoodwin, please post a test-case so that we can investigate further.
You can fork [this jsFiddle](http://jsfiddle.net/efp8z6Ln/).

**Comment by JamesJGoodwin** [comment]
@vinayakkulkarni i don't actually know, how to reproduce the issue. I tried everything to resolve it: changing margins and paddings, deleting elements that could interfere with, etc. And everything with no success.

**Comment by Banandrew** [comment]
Hi @JamesJGoodwin, have I understood it correctly that you can’t reproduce it in a JSFiddle?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
