### ISSUE TITLE
Pop up doesn't work inside blurring Modal

### ISSUE THREAD

**Issue by Vino4** [Semantic-Org/Semantic-UI#5440]
This has been references in https://github.com/Semantic-Org/Semantic-UI-React/issues/1545 and a few others but i still can't find a solution.

https://codepen.io/eGust/pen/zZXomK

Thank you :)

**Comment by Banandrew** [comment]
Hi @Vino4, you have to use pre-existing popups for it to work, because the popup component creates a popup outside of a modal’s dimmer, [here’s an example](http://jsfiddle.net/Banandrew/eh76tLkv/).

**Comment by Vino4** [comment]
Thank you @Banandrew for your switch response!
If i may ask, Is it at all possible to achieve this only using the react component?

**Comment by Banandrew** [comment]
@Vino4 No problem at all. I don’t know, because I don’t work with React—I think it’s best to ask them about it.

**Comment by lubber-de** [comment]
Fixed for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/616
See https://jsfiddle.net/s48j9b5v
