### ISSUE TITLE
[Docs][Question] Is there a page/site where I can sample or view all of the bundled themes online? 

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#5443]
Is there a page/site where I can sample or view all of the bundled themes online? Material, duo, flat, github, gmail, pulsar, round, etc? Thanks.

**Comment by Banandrew** [comment]
Hi @kmd1970, no. You probably know about it already, but I’ll mention it just in case—you can preview themes on some pages, and [the button component](https://semantic-ui.com/elements/button.html) is a good example; there’s a dropdown to the left of the blue “Download” button at the top that allows you to select a theme to preview.

Something more convenient was planned, and probably still is. Do you want the thread to be labeled, or closed?

**Comment by kmd1970** [comment]
Thanks. I knew I saw a sample somewhere, but I couldn't remember where.  😁  Thanks again.
