### ISSUE TITLE
[Dropdown] Add longer item descriptions

### ISSUE THREAD

**Issue by lifehackett** [Semantic-Org/Semantic-UI#5448]
I'm using Semantic-UI-React.  It is following Semantic-UI markup and rendering a Dropdown Item with the description before the text

*From Semantic-UI docs page*
<img width="432" alt="screen shot 2017-06-07 at 9 01 58 am" src="https://user-images.githubusercontent.com/1809761/26885489-0310d85c-4b60-11e7-9241-c88f92bfd943.png">

We would like to show the `description` below the `text` by applying some custom CSS to allow for longer descriptions, but this would require switching the rendering order of the `text` and `description`.  This requires both a code change to Semantic-UI-React and a CSS change to Semantic-UI. When I simply changed the render order in Semantic-UI-React, the UI gets screwed up.

![screen shot 2017-06-07 at 9 06 18 am](https://user-images.githubusercontent.com/1809761/26885711-a10f64b0-4b60-11e7-825c-ff153541285a.png)

Removing this fixes the issue
<img width="330" alt="screen shot 2017-06-07 at 9 07 05 am" src="https://user-images.githubusercontent.com/1809761/26885810-e6513620-4b60-11e7-8118-c3b79f0b22a2.png">

1) Is this a change you would be open to a PR for?
2) If so, what is the best way to coordinate changes across the two projects?

Thank you,
Conor

**Comment by Banandrew** [comment]
Hi @lifehackett, as things currently stand, it will take quite some time to merge it into `next`—I’m sure this is not the case for the React team, but they probably won’t do it until it’s added to the framework. I labeled it as enhancement, and the maintainer will take a look, but when is unknown; unfortunately, he’s the only one who can answer your first question.
