### ISSUE TITLE
delay between two transitions will be ignored

### ISSUE THREAD

**Issue by koup** [Semantic-Org/Semantic-UI#5449]
How can I insert a pause between 2 transitions.

delay(3000) is ignored: 

$('.message').transition('drop').delay(3000).transition('drop');

How can i drop a message, wait 3 sec. and drop the message away?

Thanks

**Comment by Banandrew** [comment]
Hi @koup, you can use `interval` property:
```JS
$('.ui.message')
  .transition({
    animation: 'drop',
    interval: 3000
  })
  .transition('drop')
```

**Comment by koup** [comment]
Hi Banandrew

Unfortunately this does not work. The message disappears immediately.

Thanks

**Comment by Banandrew** [comment]
@koup Sorry about that, add `.transition.hidden` classes to your message to hide it initially, then do it the other way around:
```JS
$('.ui.message')
  .transition('drop')
  .transition({
    animation: 'drop',
    interval: 3000,
  })
```

**Comment by koup** [comment]
Many thanks, now it works 😉

**Comment by sinagolchiin** [comment]
you can use this ->
jQuery('#segment').transition('tada',1500);

teda is our animation and 1500 is time in ms
