### ISSUE TITLE
dropdown auto open inside modal

### ISSUE THREAD

**Issue by jslixiaolin** [Semantic-Org/Semantic-UI#5457]
when i use dropdown in modal,the dropdown was auto open after the modal show.
I hope that the dropdown don't open when the modal show
here is the code
http://jsbin.com/dosiras/edit?html,output

**Comment by Banandrew** [comment]
Hi @jslixiaolin, the modal component has got the `autofocus` property set to `true` by default, here’s what it does:

>When true, the first form input inside the modal will receive focus when shown. Set this to false to prevent this behavior.

```JS
$('.ui.modal')
  .modal({
    autofocus: false
  })
  .modal('show')
```

**Comment by jslixiaolin** [comment]
thank you for replay, i had fix it by following your addvise
