### ISSUE TITLE
Percentage grid structure

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#5459]
Hello,
Do you have a structure like I want?
When I write "four" I want a format that can be "4 * 4 = 16" instead of "100/4 = 25%".
I made a picture to explain it better.

![grid_yapi](https://user-images.githubusercontent.com/13555457/27077098-a609aaf8-5037-11e7-94be-201a23fc2b0c.jpg)

**Comment by oguzhansari** [comment]
I wrote it the way I wanted.
I share with your.

https://drive.google.com/drive/folders/0ByGRCqOwP1AWX0dseFVSMUExWFE?usp=sharing

**Comment by Banandrew** [comment]
Hi @oguzhansari, it actually exists:
```HTML
<div class="ui four column grid">
  <div class="column">
    <div class="ui segment"></div>
  </div>
  <div class="column">
    <div class="ui segment"></div>
  </div>
  <div class="column">
    <div class="ui segment"></div>
  </div>
  <div class="column">
    <div class="ui segment"></div>
  </div>
</div>
```
Same works for `.row` containers.
