### ISSUE TITLE
Add an option to prevent form submit if form validation fails

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#546]
I think a common use case for form validation is to cancel the submit event if the form does not fully validate. I don't see anything in the docs showing this functionality. Perhaps it should be an option on the form?

**Comment by carbontwelve** [comment]
@jlukic I know this is a year old issue at least, but I couldn't find in the documentation any note informing me that returning false from `onSuccess` cancels the form submit trigger; would have saved me fifteen minutes of searching for the answer.
