### ISSUE TITLE
[Radio] should print checked style

### ISSUE THREAD

**Issue by cattermo** [Semantic-Org/Semantic-UI#5460]
Fiddle: http://jsfiddle.net/ahv4gceg/2/

When printing a radio component it always appear unchecked. This is due to browsers removing background graphics on print. 

Can the radio checked style be done in some other way than using background-color? 

A work around that worked for me is to add a border to do the "check" part when printing:
```
.ui.radio.checkbox .box:after,
.ui.radio.checkbox label:after {
  @media print {
    border: 7px solid #212121;
  }
}
```

Would be great if this worked out of the box.

**Comment by Banandrew** [comment]
Hi @cattermo, SUI has a lot of printing issues, and we’re already tracking them in #1099. I’d suggest to repost your comment there.
