### ISSUE TITLE
[Segment] [Header] Top attached header has a negative margin-top

### ISSUE THREAD

**Issue by ocharles** [Semantic-Org/Semantic-UI#5462]
See the following fiddle: https://jsfiddle.net/3rf9jtdu/

I argue that the top alignment of the first table cell's segment (top left segment) should be the same as the header's top alignment (top right). However, the header is the `:first-child` of a table, so it ends up having a negative margin, pulling it out of the padding of the table cell, and thus is out of alignment.

**Comment by ocharles** [comment]
If this is to be closed it should only be because it duplicates #5436

**Comment by hammy2899** [comment]
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/5436

**Comment by lubber-de** [comment]
Fixed in https://github.com/fomantic/Fomantic-UI 2.4.4
