### ISSUE TITLE
Icons have different font sizes using sidebar

### ISSUE THREAD

**Issue by dbrrt** [Semantic-Org/Semantic-UI#5465]
I notice that when I was using different icons, in same areas, they've different size/ratio.
Do you know if that's normal (for instance `user` and `settings`) ?

It happened using sidebar component (left side, not top for instance)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by dbrrt** [comment]
@Banandrew Apparently it doesn't happen there with the last CSS version.
I noticed this issue with React 15 and the official React-Semantic-UI library
http://jsfiddle.net/1r5wvjr5/1/

**Comment by Banandrew** [comment]
@dbrrt Sorry for the delay. React integration is in a [separate repository](https://github.com/Semantic-Org/Semantic-UI-React), it’s being maintained by different people, so I think it’d be best to open a thread there. I’ll close it for now, but please mention this issue in `Semantic-Org/Semantic-UI-React` in case you’ll find that it’s an error in SUI’s CSS, and someone will reopen it.

**Comment by dbrrt** [comment]
@Banandrew The guidelines told me to post it there : 
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI
apparently not a CSS issue, more of an issue on integration side in React library.
