### ISSUE TITLE
modal:allowMultiple，add dimmer

### ISSUE THREAD

**Issue by zhangyuanliang** [Semantic-Org/Semantic-UI#5466]
$('.coupled.modal')
  .modal({
    allowMultiple: true
  });
How to add a dimmer to the second modal, so that the first modal can not operate？
JSFiddle example: https://jsfiddle.net/zhangyuanliang/mpknexne/

**Comment by Banandrew** [comment]
Hi @zhangyuanliang, you can’t. You can use [the dimmer component](https://semantic-ui.com/modules/dimmer.html) on a modal or its child elements, though, or the second modal’s callbacks like `onShow` to disable the first modal’s controls. The following is a standard reply.

**Comment by zhangyuanliang** [comment]
@Banandrew I don't know how to add dimmer on the second modal. Can you help me change the JSFiddle example I wrote? thank you!
JSFiddle example: https://jsfiddle.net/zhangyuanliang/mpknexne/

**Comment by Banandrew** [comment]
@zhangyuanliang Here you go: https://jsfiddle.net/Banandrew/mpknexne/2/ As you can see, it’s not perfect—the dimmer doesn’t fully cover the first modal’s corners, but I think it can be fixed with some additional CSS if you really need it.

**Comment by zhangyuanliang** [comment]
In my project,  six modal in a piece. I can't find a better solution, but still thank you!
