### ISSUE TITLE
[Form validation] Data-validate just takes first field into account

### ISSUE THREAD

**Issue by xDaizu** [Semantic-Org/Semantic-UI#5469]
Check this JsFiddle:

http://jsfiddle.net/4mpb7cfx/183/

if you submit, both "Can't be empty" fields get marked as error. If you correct only the first one, both stop throwing error and it returns true. If you correct only the second one, none of them is unmarked as error.

If you write something in the first field and then submit, it ignores the second "notempty" field.

Checked in **Firefox Developer 54.0b14** and **Chrome 58.0.3029.110**

**Comment by Banandrew** [comment]
Hi @xDaizu, thank you, but we’re already tracking it here: #829. The thread is very old, and I posted your test case there.
