### ISSUE TITLE
Table not fully visible when screen size changes in semantic ui

### ISSUE THREAD

**Issue by wdmeeste1** [Semantic-Org/Semantic-UI#5471]
I have created a table using html and semantic ui (see html code below).

The problem with the following table is when the screen size changes to a smaller format the last columns are not visible anymore (see browser image below: header 9 is not visible anymore). There is also no horizontal scrolling available. Is there a fix for this behavior?

**HTML**

    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
           <meta charset="utf-8" />

        <link href="semantic.min.css" rel="stylesheet" type="text/css" />

        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="semantic.min.js"></script>
        <title></title>
    </head>
    <body>
        <div class='ui container'>
            <table class="ui striped selectable celled table" id="overviewtable">
                <thead>
                    <tr>
                        <th>header 1</th>
                        <th>header 2</th>
                        <th>header 3</th>
                        <th>header 4</th>
                        <th>header 5</th>
                        <th>header 6</th>
                        <th>header 7</th>
                        <th>header 8</th>
                        <th>header 9</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>sdfsdqfqdsf qsfqsf qs dqsfdqfdq</td>
                        <td>qsdfdqsfdqsfdfqsf qs dfsq</td>
                        <td>dqfdqsfdsq</td>
                        <td>dsqfqsdf</td>
                        <td>sqdfsqdf</td>
                        <td>sdfsdfqsf</td>
                        <td>dsfqsdfqsdfqsdf</td>
                        <td>sdqfsqdfsd</td>
                        <td>dsqfqsfdqsfsqfqsfdqsf</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
    </html>

**Browser result**

![image](https://user-images.githubusercontent.com/23402402/27227983-13d82044-52a6-11e7-9443-f32cb1fd2ca5.png)

If you change the screen width further than the table will flip to vertical mode.

PS: same behavior in firefox, chrome and safari.

**Comment by Banandrew** [comment]
Hi @wdmeeste1, no, not out of the box—the behavior is normal, though, and is easily extendable. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by wdmeeste1** [comment]
Stackoverflow question + answer: https://stackoverflow.com/questions/44589659/table-not-fully-visible-when-screen-size-changes-in-semantic-ui
