### ISSUE TITLE
[Sidebar] - Your Bug Name

### ISSUE THREAD

**Issue by dmc12345628** [Semantic-Org/Semantic-UI#5473]
jQuery.Deferred exception: $(...).sidebar is not a function TypeError: $(...).sidebar is not a function
    at HTMLDocument.eval (eval at 235 (http://localhost:8080/0.b981d1fb918631d86b8f.hot-update.js:7:1), <anonymous>:57:31)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined

**Comment by Banandrew** [comment]
Hi @dmc12345628, please check if you included `semantic.min.js`. 

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
