### ISSUE TITLE
semantic ui Modal - which among attached sources clicked? 

### ISSUE THREAD

**Issue by binuidicula** [Semantic-Org/Semantic-UI#5477]
Hi team,

I have a form which is shown using a semantic ui modal. There are more than one button which can bring this modal.  The response of the form submission must be rendered just after the button which initiated the modal. 

How is this feasible?
https://jsfiddle.net/binuidicula/kto1ezb9/ 

regards
Binu K Idicula

**Comment by Banandrew** [comment]
Hi @binuidicula, you could use jQuery’s `.click()` method instead:
```JS
$('.ui.modal')
  .modal(settings)

$('.ui.button')
  .click(function (event) {
    $('.ui.modal')
      .modal('show')
  })
```

**Comment by binuidicula** [comment]
Hi Banandrew,

Thanks for the update. I will use the same. However I think it will be a good abstraction to get event source from the attached buttons in semantic ui itself.
