### ISSUE TITLE
Unable to run npm install sematic-ui@2.2.7 

### ISSUE THREAD

**Issue by neha-s16** [Semantic-Org/Semantic-UI#5479]
I am trying to install semantic-ui version 2.2.7 but it fails with below errors:

npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/home/ar/.nvm/versions/node/v5.12.0/bin/node" "/home/ar/.nvm/versions/node/v5.12.0/bin/npm" "install" "semantic-ui@2.2.7"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! fetch failed with status code 404
npm ERR! 

https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2  is giving 404. Anyone else facing same issue? 

Thanks.

**Comment by Condell** [comment]
I'm having the same issue. I think maybe the user derekslife has deleted his github account, as I get a 404 when even trying to navigate to his user page.

**Comment by vinayakkulkarni** [comment]
Wrench Dependency from derekslife was removed in 2.2.8

See: https://github.com/Semantic-Org/Semantic-UI/commit/6fcbf43bc58a945ce705631c6557dc05f2f44bb9

Plus there's already a comment regarding this on that commit: 
https://github.com/Semantic-Org/Semantic-UI/commit/6fcbf43bc58a945ce705631c6557dc05f2f44bb9#commitcomment-22596505

I urge you to use 2.2.10 instead of 2.2.7

**Comment by Condell** [comment]
Ah, thank you! I was running code that wasn't my own and didn't even notice the dependency version differences >.< .
