### ISSUE TITLE
[Dropdown] Add `.read-only`

### ISSUE THREAD

**Issue by DanAtShenTech** [Semantic-Org/Semantic-UI#5482]
In the same way that `read-only` can be [placed on checkboxes](https://semantic-ui.com/modules/checkbox.html#read-only), I also need to be able to place `read-only` on dropdowns.  We're currently forced to use `disabled` on dropdowns to prevent users from entering data, but this causes the field and its label to be grayed out.

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) implemented `read-only` for dropdown by https://github.com/fomantic/Fomantic-UI/pull/1806
