### ISSUE TITLE
Class name order shouldn’t matter

### ISSUE THREAD

**Issue by rkyoku** [Semantic-Org/Semantic-UI#5484]
Hi,

The result produced by `class="ui segment attached bottom"` and `class="ui bottom attached segment"` differs.

Maybe I'm lacking some basic HTML/CSS knowledge, but I think order should not matter, although I understand it's more "english-readable" to put the classes in the "grammatically correct" order.

Whereas `class="ui bottom attached segment"` gives me the rounded bottom, `class="ui segment attached bottom"` does not (tested on Chrome 58).

Thank you all!

**Comment by Banandrew** [comment]
Hi @RenaudParis, I think that’s because SUI uses the attribute selector—it’s not specific to the segment component—`.ui.segment[class*="bottom attached"]`.

**Comment by Giwayume** [comment]
This is part of the design, hence the name "semantic" ui.

The order allows you to tell the difference when the same word is used multiple times, such as "left aligned" vs "left floated", etc.

**Comment by RenaudParis** [comment]
Thank you for your replies!

I confess this is a bit disturbing, as I am not used to pay attention to class name order :)

I reckon it is not possible anymore to use unique class names like "left-aligned" and "left-floated" (to use the same example)? Also, maybe there are other implications I am not aware of?

Thanks in any case! :)

**Comment by Giwayume** [comment]
That's totally possible and it actually performs better, it's just not the way semantic does it.

**Comment by Banandrew** [comment]
Forgot to link the original thread here: #396.

**Comment by bingcheng1998** [comment]
But for almost all tools, like parcel, the classes will be rearranged, and then it will not work!

eg: class="fluid controls-play tiny ui toggle labeled icon button" will be rearranged to class="button controls-play fluid icon labeled tiny toggle ui" in parcel.

I wonder could this be solved?

**Comment by Giwayume** [comment]
Parcel alphabetically sorts class names just for fun? I can't think of a practical reason to do that besides OCD. Many times the class order written by the developer makes more logical sense in terms of readability than alphabetical order. I can't imagine there's not a way to turn that off.

**Comment by prsyahmi** [comment]
For semantic ui to play with parcel

create .htmlnanorc.js with below content:
```
module.exports = {
	"deduplicateAttributeValues": false,
	"sortAttributesWithLists": false
}
```
