### ISSUE TITLE
Using Dimmer on parent without dimming a certain child element

### ISSUE THREAD

**Issue by exogenesys** [Semantic-Org/Semantic-UI#5487]
I have a search bar in the middle of a page and would like to dim the background (the parent) on focus. Everything was quick and easy. Except, the search bar itself is getting dimmed on focus. (which was expected)

I couldn't find any example illustrating how to do this.

Help me out!

**Comment by Banandrew** [comment]
Hi @exogenesys, the dimmer is at `z-index: 1000`, so adding a higher `z-index` to the search bar should do it, something like that:
```CSS
.search.bar {
  z-index: 1001;
  position: relative;
}
```

**Comment by exogenesys** [comment]
Hi, @Banandrew!

Thanks for answering! I should have mentioned, I'm using Semantic UI for React. And the way they implement a Dimmer involves enclosing the 'dimmable' stuff inside a `<Dimmer.Dimmable />` tags. The stuff you want to not get dimmed, let's us say a button, is also enclosed in the `<Dimmer.Dimmable />` tags. 

The z-index solution doesn't work.

I didn't post it at the Semantic UI React repository because this seems like a CSS issue.

Help me out!
