### ISSUE TITLE
I can not regEx

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#5488]
I have two rules

For Password = Only these will be valid > **A-Za-z** and Turkish character **çıüğöşİĞÜÖŞÇ** and min.  2 length
For Identity No = Valid characters > **0-9** and 11 length (Example: 2136659848)

Can somebody write me these roles please.

Thank you.

**Comment by Banandrew** [comment]
Hi @oguzhansari,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
