### ISSUE TITLE
Modal forms do not validate with "positive" button

### ISSUE THREAD

**Issue by whiteboxcode** [Semantic-Org/Semantic-UI#5491]
When a positive button is added to the form, it does not validate, but a regular submit button does.

I have produced a jsfiddle.  Workaround currently in place is simply to make the submit button "look" like a positive button.
http://jsfiddle.net/7b04neum/

**Comment by Banandrew** [comment]
Hi @whiteboxcode, it does validate, it just also closes the modal. Try returning `false` in modal’s `onApprove()` to see it.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
