### ISSUE TITLE
[Form validation] Integer Prompt Should Show Range Error 

### ISSUE THREAD

**Issue by AhmedAtef07** [Semantic-Org/Semantic-UI#5496]
Default prompt message shows `Please enter an integer value` in case the range rule was violated.

In case the validation rule was for example `integer[0..50]`: Would be better to show the range error instead of the (not so user friendly user).

In case the rule was just `integer`, the same current message be produced.

Suggested message would be: `Value should be within range of (x, y)`, or better `Value should be greater than X and less than Y`

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) added support to show the range values inside the default prompt by
https://github.com/fomantic/Fomantic-UI/pull/1796
See https://jsfiddle.net/lubber/g3nte1m6/14/
![image](https://user-images.githubusercontent.com/18379884/102490441-1e5eaa00-406f-11eb-8fe0-51967e2196d4.png)
