### ISSUE TITLE
different z-index on dimmer and fixed menu

### ISSUE THREAD

**Issue by ForzaSFerrari** [Semantic-Org/Semantic-UI#5497]
If you scroll down and you have a dimmer and a fixed menu on this page. The dimmer shows he's on a different z-index (higher) than the fixed menu.

https://fiddle.jshell.net/s4wgfhb6/

**Comment by tdewolff** [comment]
I encountered this as well, I fixed this with manual CSS line giving `.ui.menu.fixed` a `z-index` over `1000`.
