### ISSUE TITLE
Typo in default theme

### ISSUE THREAD

**Issue by rizedr** [Semantic-Org/Semantic-UI#5498]
Check this line: https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/icon.overrides#L715

**Comment by j-f1** [comment]
What’s wrong with that?

**Comment by Banandrew** [comment]
Hi, there’s definitely nothing wrong with that. Class names can’t start with a digit, and that’s the only way to to allow it—`i.icon.\35 00px:before` basically translates to `i.icon.500px:before`. There’s a reason to change it, though, and we’re already tracking it here: #5468.
