### ISSUE TITLE
[Sidebar] Add the ability to have an always visible sidebar that could be hidden on smaller screens

### ISSUE THREAD

**Issue by stevenspiel** [Semantic-Org/Semantic-UI#5500]
I want the sidebar to be hidden when page loads on mobile and visible when page loads on desktop.

As you can see [here](http://fiddle.jshell.net/r7fws0nn/5/show/light/) (and [code here](http://fiddle.jshell.net/r7fws0nn/5)), when the page loads on desktop, the sidebar is visible and it behaves as expected. However, when the page loads and the window is less than 800px, the sidebar is visible for a moment, and then slides out. 

Here is the gist of it:

HTML
```html
<div class="ui sidebar left overlay visible" id="sidebar"></div>
<div class="pusher"></div>
```

JS
```js
$sidebar = $('#sidebar');
$sidebar.sidebar({transition: 'overlay', mobileTransition: 'overlay'});

if ($(document).width() < 800) {
  $sidebar.sidebar('hide');
} else {
  $sidebar.sidebar('show');
}
```

Also, if I remove the `visible` class from the html `.sidebar` div, then the opposite happens ([example](http://fiddle.jshell.net/r7fws0nn/8/show/light/)). It works fine on mobile, but for desktop, it begins hidden, and then the sidebar immediately pops out.

**Comment by Banandrew** [comment]
Hi @stevenspiel, sorry for the delay. It’s just how it is, and there’s probably no reasonable workaround for that behavior. For instance, the documentation uses 2 sidebars that exist in the DOM at the same time: one is always visible at mobile breakpoints and uses the sidebar component, another is always visible at desktop breakpoints and uses some custom CSS, [something like that](http://jsfiddle.net/Banandrew/9uL6g1hp/).

If you have more questions, I’ll be happy to answer them in this thread. I’m closing it for now, but please let me know if you’d like to reopen it as a feature request.

**Comment by stevenspiel** [comment]
Please do reopen as a feature request. Thank you!
