### ISSUE TITLE
[List] list icon in a list is malformed

### ISSUE THREAD

**Issue by peyman-mohamadpour** [Semantic-Org/Semantic-UI#5502]
look at this:
[List icon malformed](https://ibb.co/mADyvF)

this CSS is wrongly applied:
```
.ui.list .list {
    clear: both;
    margin: 0;
    padding: .75em 0 .25em .5em;
}
```

and this is markup:
```
<div class="ui relaxed list">
    <div class="item">
        <a class="ui label" href="">
            <i class="large unordered list icon"></i>Type of Content to be Design and Developed</a>
    </div>
    <div class="item">
        <a class="ui label" href="">
            <i class="large browser primaryThirdColor icon"></i>Web Content Design and Development</a>
    </div>
</div>
```

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by peyman-mohamadpour** [comment]
[Test case](http://jsfiddle.net/efp8z6Ln/559/)

**Comment by Banandrew** [comment]
@peyman-mohamadpour Thank you, but we’re already tracking it here: #5499.
