### ISSUE TITLE
Form validation rule using function return value as rule type value

### ISSUE THREAD

**Issue by MiikaKan** [Semantic-Org/Semantic-UI#5505]
Hey! I'm trying to set up form validation so, that there is for example a selection field before a text field. If the first option is taken the exactLength has to be 10, and if 2nd then it would have to be 20.

Just a rough idea here:

function check() {
   var selectValue = $('#selection').val();
   if(selectValue == 'option1'){ return 10; }
   else { return 20; }
}

function _setupForm(){
        // Semantic-UI form validation
        $('.ui.form').form({
          fields: {
            textField: {
              identifier: 'textField',
              rules: [
                {
                  type: 'exactLength[]',
                  value: check(),
                  prompt: 'The input has to be {ruleValue} long'
                }
              ]
            }

Is this possible to do with semantic UI?

**Comment by Banandrew** [comment]
Hi @MiikaKan, no. You can obviously pass variables to it like `type: 'exactLength['+ val + ']'`, but once the validation is initialized, it’s final, and you’ll have to reinitialize it with updated values. Don’t forget to `$(form).form('destroy')`the form before initializing it again.

**Comment by MiikaKan** [comment]
Hey @Banandrew so can I just declare a JS varibale like var val = 20; and set it up like that.. I tried it and it is not working, tested with type: 'minLength[" + val + "]' and it shows the field as invalid when submitting
