### ISSUE TITLE
`center aligned` attribute not responsive

### ISSUE THREAD

**Issue by Guillaumejfrt** [Semantic-Org/Semantic-UI#5509]
Hi,

I just begin with semantic. 

I use `center aligned` attribute on a h2 title to make centered in my `ui segment`:
`<div class="ui devise-seg segment">`
        `<h2 class="center aligned btm-mg-25"><%= t(".forgot_your_password") %></h2>`

It works well in computer or tablet view: 
![screen shot 2017-07-05 at 13 15 25](https://user-images.githubusercontent.com/24220655/27862114-08cb7e5c-6184-11e7-964b-f5fe2c4fb6a5.png)

However, it seems not to word on mobile view when I narrow my screen:
![screen shot 2017-07-05 at 13 17 06](https://user-images.githubusercontent.com/24220655/27862164-46d8c830-6184-11e7-80f9-2b374206a433.png)

The text is not centered anymore.

Could someone please help me?

Guillaume

**Comment by Banandrew** [comment]
Hi @Guillaumejfrt, could you please confirm that it’s `<h2 class="ui center aligned header">`, because I’m not seeing it in your code? I’ve just tested it, seems to be working. A test case might also help, you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Guillaumejfrt** [comment]
Hi @Banandrew, I did not have the exact code. I had forgot `ui header` classes. Now it works, thanks a lot.

Is there any beginners tuto (text or video) to begin with semantic-ui?

Thank you so much for yout help.

**Comment by vinayakkulkarni** [comment]
@Guillaumejfrt : Hope the [Kitchen Sink](https://semantic-ui.com/kitchen-sink.html) helps

**Comment by Banandrew** [comment]
@Guillaumejfrt No problem at all. Unfortunately, there isn’t, you’ll just have to go through the documentation.

**Comment by Guillaumejfrt** [comment]
all right! love it :)
