### ISSUE TITLE
Uncaught URIError: URI malformed when trying to send '%' through API

### ISSUE THREAD

**Issue by mxvin** [Semantic-Org/Semantic-UI#5520]
Hello,
I had trouble when I try to send '%' value using semantic API and I got this console message error:

![semanticissue-min](https://user-images.githubusercontent.com/16519644/27984810-5a83027e-6409-11e7-8274-80ff2de588ea.PNG)

https://stackoverflow.com/questions/15326777/uncaught-urierror-uri-malformed-jquery-ui-tabs-on-windows/21078971#21078971 might be references through this issue.
I'm using Chrome 59, Windows 
Thanks
EDIT:
This problem might be a bug on Semantic UI escaping string function. After read documentation, this can be disable by using API settings *encodeParameters=false* . So the further protection comes from server validation, not by client side.

**Comment by Banandrew** [comment]
Hi @mxvin, sorry for the delay, what string produces the error?

**Comment by mxvin** [comment]
That's okay bro 😃 
Here's the fiddle http://jsfiddle.net/cewxfom9/2 
i've test Firefox and Edge and they did the same too,

**Comment by Banandrew** [comment]
@mxvin You’re right, it blows up when the API component tries to decode it [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/api.js#L751). We’ll see how it can be changed.

**Comment by Banandrew** [comment]
@mxvin I’ve been going through my old JSFiddles and found one—apparently I was already talking with someone about the issue, but then completely forgot about it. If you’re interested in a temporary fix, you could use `beforeSend()` callback and `encodeURIComponent()`:
```JS
beforeSend: function (settings) {
  let value = $('input.err').val()

  settings.urlData = {
    value: encodeURIComponent(value)
  }

  return settings
}
```
Or just replace the sign:
```JS
beforeSend: function (settings) {
  let value = $('input.err').val()
  
  let result = value.replace(/[%]/g, function (m) {
    return '%' + m.charCodeAt(0).toString(16)
    // Basically changes "%" to "%25".
  })
  
  settings.urlData = {
    value: result
  }

  return settings
}
```

**Comment by mxvin** [comment]
@Banandrew Whoa, thanks!
I was think beforeSend can make it, but i'm too lazy so i continue to other part of my project 😄
Hope this might help someone out there that facing same problem 💯

**Comment by jjylha** [comment]
up
