### ISSUE TITLE
UI-Dropdown Multi Select Field Layout

### ISSUE THREAD

**Issue by Mojo90** [Semantic-Org/Semantic-UI#5523]
Layout is not as promised as in the [docs](https://semantic-ui.com/modules/dropdown.html#/examples) even if the css etc. is used.

And I find nowhere anything about styles and how to achieve your example, so pls support how to easily have the same look and feel.

More detailed with screenshot: https://github.com/Semantic-Org/UI-Dropdown/issues/13

**Comment by Banandrew** [comment]
Hi @Mojo90, you also need the following components: Reset (or use your own, it’s not critical), Label, Icon, Site (it’s also optional). If you’re planning to use remote content, also the API component.

Please close UI-Dropdown#13, because I don’t have access to that repository. If you have more questions, I’ll be happy to answer them in this thread.

**Comment by Mojo90** [comment]
Thx @Banandrew. I built Semantics with your mentioned components except API and attached the files. But the result is the same: it is not the UI as in your example on the docs. Do I have to adjust something else?

[Archive.zip](https://github.com/Semantic-Org/Semantic-UI/files/1135096/Archive.zip)

**Comment by Banandrew** [comment]
@Mojo90 You also need the transition component. Aside from that, your archive works for me, the icons are missing obviously, but I’m assuming you omitted the font files. Also, don’t forget to include jQuery before SUI’s JavaScript. If you tell me more about your page’s setup, I might be more specific.

**Comment by Mojo90** [comment]
Thx for your Support! I added the transition component, not sure at the moment how to add font files but I think that is not a problem. And jquery (1.11.1) is included before SUI'S JS.
You can see it live here: http://halanke.develapp.me/termine (Dropdown is with `Kategorien auswählen`)
I just use it with
```
$('.ui.dropdown').dropdown({
    allowAdditions: true
  });
```
Script/CSS Files are added before `</body>`.

**Comment by Banandrew** [comment]
@Mojo90 You need to add the `.selection` class to your dropdown. As for font files, load the page, open “Network” tab in developer tools (might be a little different if you don’t use Chrome, in Chrome that’s F12), then select something from the dropdown, and you’ll immediately see three or so errors, hover your mouse cursor on each, and you’ll see the path where you need to copy them relative to your domain’s root. Font files can be found in `themes/default/assets/fonts`.

**Comment by Banandrew** [comment]
@Mojo90 Actually, you need all of the font files, so disregard what I posted earlier about the “Network” tab and just copy all of them into `http://halanke.develapp.me/assets/css/themes/default/assets/fonts/`.

**Comment by Mojo90** [comment]
@Banandrew great, now it works as expected, thx for your great support 😊

**Comment by Mojo90** [comment]
Sorry @Banandrew I have one more thing: just tested it on my mobile (iphone 7 Plus) and there everytime when I click on the dropdown it opens but immediately closes again. Are there any known issues? Thx!

**Comment by Banandrew** [comment]
@Mojo90 No problem at all. I too experience it on your website with the latest version of Chrome for Android, but it doesn’t happen on [the dropdown component’s documentation page](https://semantic-ui.com/modules/dropdown.html). Could you please follow that link on an iPhone and see if it happens there as well?

I’m not sure how to start debugging it, I’d start by updating jQuery to the latest version, but can’t really think of anything else right now.

**Comment by Mojo90** [comment]
@Banandrew indeed it also happens on my device and iOS Simulator on the components doc page - [check this video](https://www.dropbox.com/s/ctzx7fpp4p5lwwa/Dropdown.mov?dl=0). But it does not happen when I open it, rather it is when I try to close the Dropdown by clicking on it. On my real device it happens everywhere that it reopens when I click on the dropdown, as you can see on the iOS Simulator it only happens when clicking on the arrow on the right site but when I click in the middle of the dropdown it closes straight. So not sure but seems like a small issue here with something? Nevertheless I will try to update my jquery version and see if it is than the same behaviour.

**Comment by Banandrew** [comment]
@Mojo90 It probably won’t help with Safari, there’s indeed an issue (#3304), and I have no idea what’s causing it, or how to fix it; somebody with an iPhone will have to deal with it. Upgrading jQuery might help with Android, though, which is still a big chunk of potential users, and I can keep testing it for you. I mean, I’m speculating that there’s an interference on your website, because I don’t experience it on the component’s page, and I also might be wrong.
