### ISSUE TITLE
[popup][enhancement] ontouch displays popup (Windows10 touchscreen)

### ISSUE THREAD

**Issue by JohnRSim** [Semantic-Org/Semantic-UI#5524]
http://jsfiddle.net/efp8z6Ln/562/

```javascript
{
	delay:200,
	on:'hover',
	variation: 'inverted'
}
```
I have a on hover popup - however on my laptop if I tap the element is becomes visible.
I only want the popup to display if I hover over with a mouse.

Is it possible to add this check if tap don't allow the hover?

Thanks

**Comment by Banandrew** [comment]
Hi @JohnRSim, sorry for the delay; it’s not currently possible. The popup component has got `addTouchEvents` property that’s job is to do exactly what you’re asking, but there’s a bug somewhere, and the property can’t be turned off. We’re tracking it here: #3382.

If you have more questions, I’ll be happy to answer them in this thread.

**Comment by lubber-de** [comment]
Fixed. See http://jsfiddle.net/2hm3nmLx/7/show
