### ISSUE TITLE
Setting property on nested accordion causes it to close immediately

### ISSUE THREAD

**Issue by dangitall** [Semantic-Org/Semantic-UI#5527]
When I set the `onOpen` property of a nested accordion dynamically after initialization, it causes the accordion to open and then immediately close. Am I using the module incorrectly?

http://jsfiddle.net/dangit/6dxe0w9s/1/

**Comment by Banandrew** [comment]
Hi @dangitall, I didn’t work with it all that much, but I think that you don’t need to initialize the children—that’s the reason why it closes immediately after being opened, it triggers all events twice. Just set up a callback and figure out if its a child accordion inside of it, something like `$(this).parent()` in `onOpen` might work.

**Comment by dangitall** [comment]
Hi @Banandrew, thanks for the quick response. My impression was that the second call to `.accordion()`  where the first arg is just `'setting'` doesn't do a re-initialization, it just changes a setting; but I'm inferring now that this is not incorrect. Is there a way to change a setting like this after initialization without running the init code again?

**Comment by jlukic** [comment]
You can use the example in docs of a multiple level accordion and `onOpen`

Here's an example
http://jsfiddle.net/wj3g0ryf/
