### ISSUE TITLE
[Dropdown] - Filter Dropdown

### ISSUE THREAD

**Issue by aamirramay296** [Semantic-Org/Semantic-UI#5528]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**
The Dropdown should do this

**Result**
The Dropdown does not do this

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by aamirramay296** [comment]
Search In-Menu

A dropdown can include a search prompt inside its menu

When i use its code actually it dosent work

**Comment by Banandrew** [comment]
Hi @aamirramay296, what doesn’t work exactly? Please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).
