### ISSUE TITLE
Uncheck input name radio (toggle switch)

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5532]
Hi,

After using semantic ui for a while today I encounreted some problem that I cant solve.  have, for example, 3 radio input with the same name and I apply semanti ui on these buttons using the toggle switch (which is very fancy and beautiful btw). If the user clicks in anyone of the input radio button the toggle works beautifully and if the user clicks another input the previous clicked button gets animated to the default appearance (OFF) and the newly clicked button gets animated to receive the ON appereane.

My question is this: if the user needs to uncheck all radios, I mean, the user clicked in one of the radios BUT later he decided that he didnt want to click in any of the radios it's not possible to "uncheck" the input radio, not even using ESC.

Is there someway to do that without having to add any other radio option or complexity?

**Comment by Banandrew** [comment]
Hi @batata004, if I understood you correctly, have you tried setting `uncheckable` to `true`?

**Comment by batata004** [comment]
Sure, using JAVASCRIPT it works perfectly! But the end user will not use javascript in the browser's console to uncheck it. Is there any end user alternative if the user wants to deselect that radio that he clicked?

**Comment by Banandrew** [comment]
@batata004 In that case, no—that’s how `type="radio"` is.

**Comment by batata004** [comment]
So after the user selects an option in the input type=radio it's impossible to him/her deselect it?

**Comment by Banandrew** [comment]
@batata004 Yes.
