### ISSUE TITLE
Dropdown Onchange trigger

### ISSUE THREAD

**Issue by aravindlikes** [Semantic-Org/Semantic-UI#5534]
Add Dropdown on change action trigger after particular wait seconds like in "ui search field"

**Comment by Banandrew** [comment]
Hi @aravindlikes, can you please elaborate?

**Comment by aravindlikes** [comment]
In Multiple selection dropdown, if i selected the one option and closed dropdown menu and immediately i add one more option. in this case it trigger on change action two times. Instead of triggering the on change action twice, if there is an option to trigger action after few seconds. It will reduce the triggering action twice. 

Note: In on change function i'm using an ajax call to fetch the data from database where millions of records are present. Now in the above case it make two ajax call.

**Comment by Banandrew** [comment]
@aravindlikes Is there a reason for you to use `onChange` instead of [the API component](https://semantic-ui.com/behaviors/api.html) with `apiSettings`? It’s the “Remote Content” section [on this page](https://semantic-ui.com/modules/dropdown.html#/examples).

**Comment by aravindlikes** [comment]
I think using api Component instead of on change wont make any difference in functionality. Even there is no waiting timer in api settings.

**Comment by Banandrew** [comment]
@aravindlikes There is. Could you please tell more about what UI pattern you’re tying to achieve? Do you do a request just to get options that a user can choose from? Say, I search for `al`, and it returns `Albatross`, `Alligator` and `Alpaca` options, from which I can select multiple. Or do you need to do a request after a user selected an option? If yes, what for, what do you do after the result is returned?

**Comment by aravindlikes** [comment]
yes, i need to do make ajax call after user selected an option.
Check this [fiddle](https://jsfiddle.net/vc4hLmat/2/)...
In here if i selected or remove one option it update the label immediately. instead of updating it immediately is there any option to update it after few seconds...

**Comment by Banandrew** [comment]
@aravindlikes Alright, sorry for so many questions, just wanted to clarify it as much as possible to be able to help. In that case, no, there’s nothing in the framework that can throttle your requests, and you’ll have to write your own throttler; SUI uses `setTimeout()` [in the API component](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/api.js#L250) to achieve that.

I’m considering it a use case and closing the thread.
