### ISSUE TITLE
[Dropdown] Trigger dropdown menu on click on deeper levels of dropdown menus (instead of hover)

### ISSUE THREAD

**Issue by quantran13** [Semantic-Org/Semantic-UI#5535]
On multi level dropdown lists, the deeper-level dropdown menus are triggered on hover, not on click, even when in the JS initialization, it's specified the triggering event would be `click`. [Here's a link to the JS fiddle](http://jsfiddle.net/kfw0013g/). How do I trigger those deeper-level dropdown menus on `click` instead?

```HTML
<div class="ui dropdown button">
  <span class="text">Choose Category</span>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item">
      <span class="text">Category 1</span>
    </div>
    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text">Category 2</span>
      <div class="menu">
        <div class="item">Item 2A</div>
        <div class="item">Item 2B</div>
      </div>
    </div>
  </div>
</div>
```

Here's the JS initialization:

```
$('.ui.dropdown').dropdown({
    on: 'click',
    action: 'nothing'
});
```

Thanks!

**Comment by Banandrew** [comment]
@qichunren The default setting `on: 'click'` works only for a dropdown’s parent element, a button in this case, and doesn’t work for sub-menus; sub-menus only use `mouseenter`/`mouseleave`. Would you like it to be implemented in the future?

**Comment by quantran13** [comment]
@Banandrew That would be awesome, since hovering is really bad for accessibility. Thanks! (by the way you tagged the wrong person).

**Comment by Banandrew** [comment]
@quantran13 Wanted to let you know that I opened a PR in case you need it right now—it might take a while to be merged. Please note that it doesn’t include some changes to the dropdown component from `master` branch, because our development branch is a few commits behind, so you’ll have to copy and paste it manually.

**Comment by quantran13** [comment]
@Banandrew That's awesome, thanks. I would love to have it right now, but at the same time I don't want to change the library's code manually, I'd rather wait for the merge if it doesn't take too long to be merged. How long do you think it will take?

**Comment by Banandrew** [comment]
@quantran13 I wish I had a better answer, but I don’t know, it’s very much possible that it won’t make it into the next version, which is probably a couple of months away from now. If you don’t want to do it manually, I initially developed it using the `master` branch—which was the current release, `2.2.11`—[here it is](https://jsfiddle.net/7z98sskp/). If it won’t be merged for `2.2.12`, you’ll have to update the fork manually, unfortunately.

But it should work for now, remove the dropdown component from the `components` array in `semantic.json` to stop building it, rebuild the framework, minify the JSFiddle, and add it to your pages after `semantic.min.js`.

**Comment by Banandrew** [comment]
@quantran13 I found an issue with what my PR, either don’t use it at all, or don’t use the `.multiple` variation. I’ll notify you when I push another commit and update all JSFiddles. My apologies, should’ve tested it better.

**Comment by Banandrew** [comment]
@quantran13 I’ve fixed it, all JSFiddles are updated.

**Comment by quantran13** [comment]
@Banandrew Thanks! I'll test it when I have time and I'll let you know how it goes.

**Comment by quantran13** [comment]
@Banandrew Upon testing, I find out that the first time I click the sub-menu, the item is selected, and the dropdown list collapses. After that, click on the sub-menu expands its own dropdown list. So this means that the functionality doesn't work correctly the first time I try to expand the sub-menu/sub-dropdown list, it only works correctly after that.

**Comment by Banandrew** [comment]
@quantran13 I can’t seem to reproduce it with these settings; `action: 'nothing'` works as expected and prevents an item from being selected. If you’ll take [this JSFiddle](https://jsfiddle.net/jmh27f53/) and switch the initialization code at the end with the one that you posted above, do you experience it?

**Comment by quantran13** [comment]
@Banandrew It's working fine now, but I'll have to test it at work tomorrow. I'll let you know the result.

**Comment by quantran13** [comment]
@Banandrew  [Here's an example](https://jsfiddle.net/8o9o7mxa/), I replaced the HTML part and kept your JS part. I'm sure what caused it to break.

**Comment by quantran13** [comment]
@Banandrew Actually, removing the link `ui` class from the second dropdown menu fixed it, [here's the JS Fiddle](https://jsfiddle.net/cum5zpLa/). Any idea why that's the case?

**Comment by Banandrew** [comment]
@quantran13 Sorry for the delay, that’s because `.ui.dropdown` is unnecessary for child dropdowns. So, instead of doing `<div class="ui dropdown link item">` you should be doing `<div class="link item">`.

**Comment by quantran13** [comment]
@Banandrew Oh okay got it. That might be a problem since I'm generating these dropdown menus dynamically, so they all have a template. I'll see what I can do to fix that. Thanks!

**Comment by quantran13** [comment]
@Banandrew It worked beautifully. Thanks so much!
