### ISSUE TITLE
[Form Validation] Error when calling "validate form" with API attached

### ISSUE THREAD

**Issue by dwightbcoder** [Semantic-Org/Semantic-UI#5537]
If a form is manually validated with "validate form" an error is thrown for the call to event.stopImmediatePropagation() if there is an API attached to the form.

The fix is a simple change on form.js:942

`if($module.data('moduleApi') !== undefined) {`

to:

`if(event && $module.data('moduleApi') !== undefined) {`

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by dwightbcoder** [comment]
If you look at the code for form.js you'll see that "event" is used without verifying that it is set, never a good idea unless it should be fatal (not this case).

**Comment by xaeroseven** [comment]
We had this exact issue, applied the fix that @dwightbcoder mentioned and it worked. It would be great to see this merged in as a Pull Request. Thanks!

**Comment by lubber-de** [comment]
Thanks @dwightbcoder . We adopted your fix in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/709

**Comment by pbarney** [comment]
> Thanks @dwightbcoder . We adopted your fix in Fomantic-UI by [fomantic/Fomantic-UI#709](https://github.com/fomantic/Fomantic-UI/pull/709)

With the number of time SUI's maintainers have refused to even acknowledge this problem, I think you just convinced me to final port over to Fomantic. Thanks!
