### ISSUE TITLE
[Search] Item Should Be Selected When Soft Keyboard Is Displayed

### ISSUE THREAD

**Issue by radusuciu** [Semantic-Org/Semantic-UI#5538]
Semantic version: 2.2.11

OS: Android 7.1.2
Browser: Chrome 59.0.3071.125
Model: Nexus 6P

Fiddle: https://jsfiddle.net/radu/9jcj5va8/
Embedded fiddle for use on mobile: https://jsfiddle.net/radu/9jcj5va8/embedded/result

Steps to reproduce:

1. Open embedded fiddle in mobile browser
2. Type in "a" to search box
3. Scroll down to bottom
4. Press "Aruba"

Focus is the blurred, and you are left with "a" in the search box. Everything below Austria exhibits this behavior. Here is a gif of it:

![annoying reproducible](http://imgur.com/o6KpyxV.gif)

To avoid bug, perform steps 1 to 3, then hit back button to close keyboard. Item will now select fine.

I was not able to replicate this behaviour on an iPhone 7 on Safari.

**Comment by Banandrew** [comment]
Hi @radusuciu, can’t reproduce on 7.1.1 and the same version of Chrome. We won’t be able to fix it without owning a device capable of reproducing the issue, so if you have time to look into it, please do.

**Comment by radusuciu** [comment]
Thanks for trying @Banandrew. I'll try and get a few more test cases with other phones.

Just to be sure, you kept the keyboard open and still managed to select one of the lowest values?

**Comment by Banandrew** [comment]
@radusuciu Yes.
