### ISSUE TITLE
Form validation for exact rule is not working in Form example

### ISSUE THREAD

**Issue by phalvinayak** [Semantic-Org/Semantic-UI#5539]
Form validation for exact rule is not working in the [form example](https://semantic-ui.com/behaviors/form.html)

I've entered the exact same text which is required, but unfortunately, it's not working. Please refer the screenshot below.

![image](https://user-images.githubusercontent.com/230028/28194533-88e5d7f6-6862-11e7-9508-9f842c345ff9.png)

**Comment by Banandrew** [comment]
Hi @phalvinayak, there’s already a PR for that that’s waiting to be merged: Semantic-Org/Semantic-UI-Docs#312.
