### ISSUE TITLE
'Form' doc page gets stuck on opera & chrome

### ISSUE THREAD

**Issue by w96k** [Semantic-Org/Semantic-UI#5541]
Page gets stuck on select elements in chrome & opera (in Firefox everything is fine).

You can see this in a quick video:
https://www.youtube.com/watch?v=s9jl-q5w0Uw

Page:
https://semantic-ui.com/collections/form.html

**Comment by Banandrew** [comment]
Let’s track it in one place: Semantic-Org/Semantic-UI-Docs#341.
