### ISSUE TITLE
[Dropdown][Menu] CSS for dropdown menu bug

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI#5542]
It looks like Semantic UI just changed the CSS for dropdown menu which makes the menu open to the left now, instead of default to the right.

Before:
![image](https://user-images.githubusercontent.com/7387035/28216613-4ad8b79e-6880-11e7-8f47-7911a5d756bc.png)

Now (latest CSS):
![image](https://user-images.githubusercontent.com/7387035/28216711-99e83e04-6880-11e7-9c6d-3d7ef8f34614.png)

the new left:0px CSS causes this problem:

.ui.menu .dropdown.item .menu {
    left: 0px;
    min-width: calc(100% - 1px);

**Comment by xmannv** [comment]
Yeah same problem here and waiting for the new change

**Comment by Banandrew** [comment]
Can be reproduced on the documentation.

**Comment by jlukic** [comment]
I'll fix this weekend

**Comment by jlukic** [comment]
Actually this weekend.. fixing now

**Comment by jlukic** [comment]
And a very easy fix..
