### ISSUE TITLE
[Form] Form + Grid results in uneven spacing on left and right.

### ISSUE THREAD

**Issue by JustinTRoss** [Semantic-Org/Semantic-UI#5545]
```
<div id="test">
    <div class="ui grid ui form">
      <div class="row field middle aligned">
        <div class="four wide column">
          <label>Field Name</label>
        </div>
        <div class="twelve wide column">
          <div class="ui fluid input">
            <input type="text" placeholder="placeholder">
          </div>
        </div>
      </div>
    </div>
</div>
```

The resulting form has no space on the left and extra space on the right. This is caused by the existence of max-width: 100% on form, which interacts poorly with the negative margin pattern of grid.

I'm not sure the impetus for adding the max-width on form, but it seems like a reasonable solution to reset max-width to none on .grid.form

Here is a jsfiddle with example: https://jsfiddle.net/81937pkk/

**Comment by JustinTRoss** [comment]
Form + Grid spacing between rows is funky too. It combines padding from top row with margin from field and padding from bottom row.

**Comment by a-birla** [comment]
If you see, .ui.grid has a property which is  margin-left: -1rem; causing the form to cause uneven padding on the left and the right sides.

**Comment by JustinTRoss** [comment]
It also has margin-right: -1rem..

On Jul 14, 2017 4:31 PM, "a-birla" <notifications@github.com> wrote:

If you see, .ui.grid has a property which is margin-left: -1rem; causing
the form to cause uneven padding on the left and the right sides.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Semantic-Org/Semantic-UI/issues/5545#issuecomment-315490700>,
or mute the thread

**Comment by a-birla** [comment]
Yeah but on unchecking the margin-left: -1rem, the form is property aligned

**Comment by JustinTRoss** [comment]
Removing the negative margins actually creates what you can expect from .ui.grid.padded. The negative margin's presence allows for a padding-less grid (rows and columns fill the negative margin).

**Comment by Banandrew** [comment]
Hi @JustinTRoss, I don’t think the classes are supposed to be combined like that, and it can be fixed by reorganizing your HTML a bit:
```HTML
<div id="test">
  <div class="ui form">
    <div class="ui middle aligned grid">
      <div class="four wide column">
        <div class="field">
          <label>Field Name</label>
        </div>
      </div>
      <div class="twelve wide column">
        <div class="field">
          <div class="ui fluid input">
            <input type="text" placeholder="placeholder">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```
There’re more variants that you could use, but that’s the gist of it.

**Comment by JustinTRoss** [comment]
Thanks @Banandrew ! That solved it perfectly.
