### ISSUE TITLE
user icons not working as expected

### ISSUE THREAD

**Issue by JustasPolis** [Semantic-Org/Semantic-UI#5547]
### Steps to reproduce
Using `<i class="user outline"</i> ` and getting blank.  Also user icons with circles are broken too, getting just black circle/white circle. 
https://jsfiddle.net/dmc0m89t/1/   <== reproduce

Thank you!

**Comment by IonutBajescu** [comment]
You're getting blank because "user outline" is not an icon, only "user". 

About the issue with the circles, can you please add it to the jsfiddle?

**Comment by Banandrew** [comment]
Hi @JustasPolis, you can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by calvinclaus** [comment]
Here is a fiddle forked from @Banandrew's reproducing the issue: 
https://jsfiddle.net/calvinclaus/ohnc641z/1/

The classnames were copied from the "User Types" section here: https://semantic-ui.com/elements/icon.html

As you can see the "user outline" does not appear.

**Comment by philrykoff** [comment]
You always have to append " icon" at the end of the class name. "user outline" does not appear as an icon, as it is not defined as one. "user outline icon" works:

https://jsfiddle.net/h7b1744x/
