### ISSUE TITLE
[Form] Disabled Field Should Remove Pointer Events

### ISSUE THREAD

**Issue by seemsindie** [Semantic-Org/Semantic-UI#555]
Is there a way to disable selection dropdown in form? I tried adding disabled class to that div but nothing is happening.

If not how i would go to disable js events happening on that dropdown?

**Comment by kamii1000** [comment]
what if we have to enable the dropdown again?

**Comment by jlukic** [comment]
Using `disabled field` will now remove pointer events on dropdown. 

Another option is just to do this yourself in css `pointer-events: none`

**Comment by kamii1000** [comment]
I've to change the state of dropdown menu dynamically.
I'm using multiple selection dropdown.
```
$('#bachelor')
            .checkbox({
                onChecked: function () {
                    $('#ba_subjects').dropdown({
                        on: 'hover'
                    });
                },
                onUnchecked: function () {
                    $('#ba_subjects').dropdown('destroy');
                }
            })
            ;
```
can you please explain how to do this?

**Comment by jlukic** [comment]
`pointer-events: none` on a class name that is triggered in javascript.

**Comment by kamii1000** [comment]
thanks :)
