### ISSUE TITLE
Doc's theming example project link broken

### ISSUE THREAD

**Issue by envision** [Semantic-Org/Semantic-UI#5554]
Linked in doc page https://semantic-ui.com/usage/theming.html

'Semantic UI includes an **example project** designed to showcase theming. This project includes examples of creating a packaged theme, using component CSS overrides, and managing your themes with theme.config.'

This 'example site' is existing but doesn't work...SSL certificate isn't correctly configured?

http://semantic-org.github.io/example-github/

**Comment by pashute** [comment]
still there today. Link broken. Goes to Semantic UI main github. Not clear what "click the paint icon near the notification" means. Please add the icon in the doc, and also tell where this icon is located. (in the theming app after you opened it)

**Comment by etshy** [comment]
This icon (left one) 
![image](https://user-images.githubusercontent.com/5531204/48768246-f1d1db80-ecb8-11e8-8f25-44a582b98c77.png)
 on this page : https://semantic-org.github.io/example-github/

Next to the notification icon, like said in doc

I didn't worked with themes yet, so can't help you more than that.

**Comment by pashute** [comment]
OK that clarifies it a bit. I'll add the explanation to the file with your icon.  

(I didn't understand at first what the bearded imam stands for ( :-)E   )

![](https://snag.gy/JwyXnu.jpg)

**Comment by pashute** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/pull/414
