### ISSUE TITLE
[Modal] Action should be fired only for instance where it was clicked by user

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [Semantic-Org/Semantic-UI#5559]
Problem is actual for `allowMultiple: true` config. Fiddle: https://jsfiddle.net/donnicky/5vpn7wyk/
In the shown form (Person) click Cancel, then click Yes in confirmation dialog and you'll see that onApprove is called for both dialogs, but it is expected to be called for confirmation dialog only. Generally it the same with any action - it is fired for all active dialogs.

**Comment by nikolaybobrovskiy** [comment]
BTW, now there is a workaround using `selector` modal config if set specific selector per dialog.

**Comment by jlukic** [comment]
Hi, your code should look like this JSFiddle
https://jsfiddle.net/gk7j7a72/

There is a related issue though that you probably ran into where with multiple modals the top modal has to be one of the following:
1) Be initialized last
2) Be included last inside the modals dimmer
3) Manually have a higher z-index set in css

I've made a fix which will automatically make additional modals appear on top in next release.
