### ISSUE TITLE
[Sidebar] should preserve overlay behavior when its transition is set to "overlay"

### ISSUE THREAD

**Issue by ihpar** [Semantic-Org/Semantic-UI#5563]
Sidebar behaves correctly on my computer when its transition is set to overlay as
`$('.ui.sidebar')
    .sidebar('setting', {
      transition: 'overlay'
    })
  ;`

But while on internet explorer of windows mobile, it behaves according to "push" transition, i.e. does not slide over the content but pushes the content.

OS: Win Mobile
Device: Nokia Lumia 520
Browser: Default i.e. shipped with the phone. Sorry couldn't find its version etc anywhere...

Maybe it's irrelevant but the same issue repeats in Chrome's dev tools when device tool bar is active (Ctrl + Shift + M in windows while Dev tools is on)

Test case: [https://semantic-ui.com/](https://semantic-ui.com/) the menu toggle item on top left of the page.

Attached an image showing the sidebar behavior in chrome (1) and mobile (2) mode. I think it should always behave as 1 when transition is set to overlay.

![sidebar](https://user-images.githubusercontent.com/26081641/28388397-460c82e0-6cdb-11e7-8a29-7986ec09f40c.png)

**Comment by Banandrew** [comment]
Hi @ihpar, is it 520 with Windows Phone 8 or 8.1?

**Comment by ihpar** [comment]
Hi @Banandrew, it's Windows Phone 8.1 having a 480x800 resolution.

**Comment by Banandrew** [comment]
@ihpar Sorry for the delay, the sidebar component uses a separate property `mobileTransition` for mobile, it defaults to `uncover`; set it to `overlay`, and it should do it.

**Comment by ihpar** [comment]
@Banandrew Thank you very much. That's awesome, `mobileTransition: 'overlay'` fixed my problem. Best!
