### ISSUE TITLE
Possible to color abritary element?

### ISSUE THREAD

**Issue by swalladge** [Semantic-Org/Semantic-UI#5564]
So if I want a red header I know I can do `<arbitary class="ui red header"></arbitary>`, but I can't seem to get a red element _without_ it being a `header`, `segment`, or other supported classes.

I would expect this should display in red text: `<a class="ui red" href="">click me</a>`, but it doesn't.

Is there a way to simply add a color class to an element, like `red-text`, `blue-background` to arbitarily override the color for something? Should there be?

Thanks.

**Comment by Banandrew** [comment]
Hi @swalladge, there isn’t. Please see #2654 and #1885.

**Comment by lubber-de** [comment]
Implemented. Example here: https://jsfiddle.net/63z148gb/
