### ISSUE TITLE
[Dropdown] 'set selected' when used on a multi dropdown with useLabels:false display the selected value's text

### ISSUE THREAD

**Issue by Rahulzz** [Semantic-Org/Semantic-UI#5567]
I am using 'set selected' on a multi dropdown. When a value is selected using 'set selected' the dropdown doesn't display '1 selected' instead displays the actual text of the value.

When the value is chosen manually:
![image](https://user-images.githubusercontent.com/20224717/28428099-e1038630-6d95-11e7-9839-3879d8964d76.png)

When the value is chosen programmatically:
![image](https://user-images.githubusercontent.com/20224717/28428056-c15972b8-6d95-11e7-96aa-6c2e9af8e06e.png)

**Comment by Banandrew** [comment]
Hi, I can’t seem to reproduce, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by Rahulzz** [comment]
This isn't a bug. I am sorry.

I was calling 'set selected' from the jsp, before the dropdown object was initialized. Changing the order solved everything. 

Thanks for your time.
