### ISSUE TITLE
semantic ui

### ISSUE THREAD

**Issue by Somyajainaditi** [Semantic-Org/Semantic-UI#5569]
my semantic ui  page is not getting responsive . I have  also use media query.what should is do?

**Comment by Banandrew** [comment]
Hi @Somyajainaditi, you should probably use [the grid component](https://semantic-ui.com/collections/grid.html).

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
