### ISSUE TITLE
[Dropdown] Add new feature Read-only (Disabled) dropdown input

### ISSUE THREAD

**Issue by erlangp** [Semantic-Org/Semantic-UI#5572]
[Dropdown] Add new feature Read-only (Disabled) dropdown input

**Comment by erlangp** [comment]
oh sorry.. i just try:
```
$('.ui.selection.dropdown').dropdown();
$('.ui.selection.dropdown').addClass('disabled');
$('.ui.selection.dropdown').addClass('read-only');
```
it's work 👍

**Comment by panzupa** [comment]
disabled class is making everything in dropdown greyish and hard to read. While read-only on other components is just blocking edition. How to make dropdown read-only?

**Comment by Banandrew** [comment]
Hi @panzupa, do you have SUI installed in your project, or do you use it from a CDN?

**Comment by panzupa** [comment]
@Banandrew I have it installed. My workaround solution is to assign disabled class and set style opacity: 100. Works very well I guess :-)

**Comment by Banandrew** [comment]
@panzupa Ah, I just wanted to say that you could override the `.disabled` class via the source, but you already figured it out. 👍

**Comment by erlangp** [comment]
nice tips! thanks @panzupa @Banandrew 👍
