### ISSUE TITLE
[Dropdown] 'set selected' does not recognize dynamically added items via JSON 

### ISSUE THREAD

**Issue by rapgithub** [Semantic-Org/Semantic-UI#5573]
I have used. 

    $(".ui.dropdown.theme").dropdown("refresh");
    $(".ui.dropdown.theme").dropdown("set selected", 'HOT');
 
adding via JSON works fine but the problem it is that set selected is not recognized when dynamically I call to edit a record, and not working...

this is my JSON below using the api
nothing seems to work with dynamically added items via json

$('.ui.dropdown.theme')
    .dropdown({
        saveRemoteData: true,
        apiSettings: {
            method: 'get',
            url: '_request.php?type=getdata'
        },
        fields: { name: "title", value: "code" },
        "success": true,
        onChange: function(value, text, $selectedItem) {
        }
});

any ideas what it is not working with dropdown dynamically created via a JSON file?
thanks for any reply

**Comment by Banandrew** [comment]
Hi @rapgithub, I’m not sure how you’re using `set selected`, could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) to create a test case? You can use `https://api.semantic-ui.com/tags/{query}` as a URL in `apiSettings`—it’s a list of animals.

**Comment by rapgithub** [comment]
I am using set selected in the case when retrieving the data saved from the database and showing it to the user screen again, then every dropdown must be populated from the json and set selected is used to show the thing the users already selected when saving the records..

this is one of the case I am using set selected... but every dropdown that is ajax json created it is not working with set selected unless I click over the dropdown again to set focus and then clicking edit the records can select the items saved and show them...

I think dropdowns created with the api using ajax are not filling the data inside unless you click over them and set focus... 

but if I do not use the api with ajax the dropdown items can be set selected without issue.
if you need JSFiddle i can post later...

**Comment by Banandrew** [comment]
@rapgithub Is there a reason that you can’t populate your dropdowns when a page is loaded initially? I understand the issue, but still like to see a JSFiddle. Alternatively, you could use `set value` and `set text` instead:
```JS
$('.ui.dropdown')
  .dropdown('set value', 'test')
  .dropdown('set text', 'test')
```

**Comment by rapgithub** [comment]
Yes I have tried that and seems to work but it is not the beautiful solution when in the dropdown i need to populate the data from database for  values and names for every field in the form instead of calling simply set selected the value and show the selection.. I know it can be a fix this way but i guess it is not working fine for multiple selection fields with lot of options selected.
 
I will post ln JSFIDDLE this issue.
thanks for your help finding a solution. 👍 but it will be great to find a solution for api remote content and set selected... I think there must be a solution or semantic ui code needs to be updated with this bug...

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by rapgithub** [comment]
the test case will upload soon thanks so busy here...

**Comment by RyanWu39** [comment]
I tried through the flowing codes , cause success! 

$('.ui.dropdown')
  .dropdown('set selected', your.value)
  .dropdown('set text', your.name)

**Comment by coder8keyboard** [comment]
Any fix for this bug? 'set selected' is not firing onChange event for remote API data. Non-remote data works fine.
