### ISSUE TITLE
Semantic-UI + Swiper Slider = Transition: Element is no longer attached to DOM. Unable to animate.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#5574]
This previously worked fine with the Default theme, but now doesn't work.

How can we avoid this from happening?

https://jsfiddle.net/0mtt2phe/2/

**Comment by tmikaeld** [comment]
Changing the default setting doesn't help:

```javascript
$.fn.transition.settings.silent = true;
```
..since Semantic UI will still break the animation for Swiper.

**Comment by tmikaeld** [comment]
Not sure what to do here, since too many other modules depend on Transition module so it can't be removed and setting any debug setting will "transition" the slider.

**Comment by Banandrew** [comment]
Hi @tmikaeld, I don’t have time to look into the conflict, but using non-jQuery version of Swiper seems to be working: `https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js`

**Comment by tmikaeld** [comment]
Ok, I'll ask Swiper to take a look at it then.
