### ISSUE TITLE
Can't add new line in popup content

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5575]
I'm using Angular and I'm adding a dynamic content to popup.
Here is my code: https://plnkr.co/edit/tIYsHZ

As you can see I would like to add some `new line` to the content, but it doesn't work.

Isn't possible to reach that with Semantic-Ui Popup?
Could this be an issue or feature request? Do you know any workaround?

**Comment by Banandrew** [comment]
Hi @smartm0use, it is possible, has nothing to do with SUI, and can easily be researched on the Internet. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by smartm0use** [comment]
I solved using `html` instead of `content` and `<br />` as separator.

https://plnkr.co/edit/isdKPT

Thank you anyway for your response ;)
