### ISSUE TITLE
[Dropdown] Multiple-level dropdown menus auto-expand at start when they have class 'right'

### ISSUE THREAD

**Issue by quantran13** [Semantic-Org/Semantic-UI#5576]
[This is a JSFiddle I created to demonstrate the problem](https://jsfiddle.net/oa1ooj26/) - The menus automatically expand at the beginning (and they don't even have the 'active' class on them). If I remove the 'right' class from either of the menus, it works fine. The problem is that I can't do that for the project I'm working on. Is there way to get around this?

![right-menu](https://user-images.githubusercontent.com/5153039/28536882-02ab165c-7077-11e7-971c-bc91feb6e4f6.png)

Thanks!

**Comment by Banandrew** [comment]
Hello again @quantran13, try adding `.transition.hidden` classes to the first `.right.menu`.

**Comment by quantran13** [comment]
@Banandrew That works, thanks!
