### ISSUE TITLE
[Dropdown] Animation Not working in case of semantic-ui-react

### ISSUE THREAD

**Issue by gsahni** [Semantic-Org/Semantic-UI#5580]
While using <Dropdown placeholder='Select Friend' fluid selection options={friendOptions} />
Animation is not working if we are using react binding for semantic(semantic ui react). While animation is there in normal semantic-ui

**Comment by Banandrew** [comment]
Hi @gsahni, the React integration is in [a separate repository](https://github.com/Semantic-Org/Semantic-UI-React), it will be best to open an issue there.
