### ISSUE TITLE
[Popup] Inverted popup menu - items on hover turns transparent 

### ISSUE THREAD

**Issue by onlyutkarsh** [Semantic-Org/Semantic-UI#5585]
Hello,

I am using popup menu with inverted blue classes. The menu appears fine but the menu items on hover vanish (the color of item is same as background)

Here is the issue script
[http://jsfiddle.net/onlyutkarsh/yc884hrd/5/](http://jsfiddle.net/onlyutkarsh/yc884hrd/5/)

**Comment by jlukic** [comment]
Fixed in `2.2.14`
