### ISSUE TITLE
[Dropdown] - useLabels: false in onVisible resets values

### ISSUE THREAD

**Issue by alexnicolaisen** [Semantic-Org/Semantic-UI#5588]
Hi,

When using onVisible on a dropdown with useLabels: false, the dropdown is reset each time it's opened. 

[Demo](https://jsfiddle.net/09p85y9b/)

The blue and green in the Demo is identical, except "useLabels: false"

Best regards
Alexander N

**Comment by Banandrew** [comment]
Hi @alexnicolaisen, the gist of it is that you shouldn’t be initializing a dropdown every time a popup becomes visible—initialize it only once. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
