### ISSUE TITLE
Popup does not get triggered by own React Components

### ISSUE THREAD

**Issue by HarryGeez** [Semantic-Org/Semantic-UI#5591]
I recently bumped into this problem after I decide to turn some code into their own sub-component.
I'm using `semantic-ui-css@2.2.11` and `semantic-ui-react@0.71.2`

```jsx
<Popup                  
  trigger={<Foo />}
  content='Comments are coming soon!'
  inverted    
  />
```
doesn't show the pop with this
```jsx
class Foo extends Component {
  render() {
    return (
      <a href="sdf">sdafsd</a>
    );
  }
}
```
but displays fine with this
```jsx
<Popup                  
  trigger={<a href="sdf">sdafsd</a>}
  content='Comments are coming soon!'
  inverted    
  />
```

**Comment by Banandrew** [comment]
Hi @HarryGeez, the React integration is in [a separate repository](https://github.com/Semantic-Org/Semantic-UI-React), it will probably be best to open an issue there.
