### ISSUE TITLE
[Dropdown] Multiple Select

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5593]
como faço para não apagar o que selecionei no multiple select, ele apaga o que selecionei do select ai não posso selecionar duas vezes

**Comment by Banandrew** [comment]
Hi, could you please provide a test case with specific steps to reproduce the issue as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by WallaceMielniczki** [comment]
https://jsfiddle.net/WallaceMielniczki/ca0rovs3/16/ preciso selecionar a mesma turma duas vezes no multiple select

**Comment by Banandrew** [comment]
@WallaceMielniczki I think Google Translate’s failing me, can you please elaborate? I didn’t understand the part about selecting the same class twice.

**Comment by WallaceMielniczki** [comment]
sim desculpa, Select the same item from the selection twice

**Comment by Banandrew** [comment]
@WallaceMielniczki It’s not possible out of the box. You’ll either have to use a different UI pattern, or work around it somehow.
