### ISSUE TITLE
[Card] Add `word-wrap: break-word` to various content blocks

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5608]
http://jsfiddle.net/WallaceMielniczki/ca0rovs3/22/ quando adiciono um paragrafo no card ele ultrapassa o tamanho do card.

**Comment by lubber-de** [comment]
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/703
