### ISSUE TITLE
[Menu] Top fixed hidden menu not displaying after passing 'masthead' in mobile devices

### ISSUE THREAD

**Issue by anantajitjg** [Semantic-Org/Semantic-UI#5609]
https://semantic-ui.com/examples/homepage.html

**Tested Browsers:** Firefox, Chrome (Both latest versions)
**Tested Devices:** Desktop PC (with responsive mode), Mobile

In desktop PC, directly going to responsive mode from normal view in browser won't produce this issue. A refresh is needed to produce this issue!

**Screenshots:**

**Before passing _masthead_**
![hidden_menu](https://user-images.githubusercontent.com/22009263/28746074-dff6eca0-74a2-11e7-9c71-3fc1f2e5a4a1.png)
**After passing _masthead_**
Instead of _display_ being _flex_, somehow _undefined_ is returning!
![main_issue](https://user-images.githubusercontent.com/22009263/28746489-01a10f90-74ab-11e7-880e-291926ba9497.png)

**Comment by web-engineer** [comment]
Does exactly the same for me, broken on mobile devices too, debug in remote safari shows same "undefined display style" - this is happening with my theme based on semantic and does the same on their own demo page.

**Comment by web-engineer** [comment]
It seems to be when the page is smaller than "$largestMobileScreen" the fixed position wont apply - you get undefined appear. On a mobile simply flipping from landscape to portrait simulates the sidebar to display as expected.

Feels like it's disabled for small screens by some other helper intentionally...
