### ISSUE TITLE
[Label] pointing label mau posicionado

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5613]
https://jsfiddle.net/WallaceMielniczki/ca0rovs3/30/

**Comment by Banandrew** [comment]
Hi @WallaceMielniczki, it works with `.inline.field` variation, and intentionally so—the framework cannot make assumptions about the width of a label in such scenarios. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by WallaceMielniczki** [comment]
desculpa,  achei que fosse um problema no semantic.
