### ISSUE TITLE
[Sidebar][Docs] When uncover is set on sidebar markup, the uncover class is also added.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#5614]
This causes the z-index to be wrong and the actual sidebar to be behind the dimmer.

https://jsfiddle.net/73d97aju/

**Comment by Banandrew** [comment]
Hello again @tmikaeld, looking through the documentation as well as the source, it seems that you shouldn’t be setting those classes on a sidebar’s markup directly, and the component will always try to add the default `transition` class to a sidebar, which just happens to be `.uncover`.

**Comment by tmikaeld** [comment]
@Banandrew Maybe add a red warning to the start of Sidebar doc not to set classes? Most of the other modules have the opposite function where you set classes for changing behaviour.

**Comment by Banandrew** [comment]
@tmikaeld I agree, either that, or I’ve just thought that maybe we can add a few checks to the component. I’ll dig into it this week to see if it’s be better.

**Comment by tmikaeld** [comment]
If it will add more weight to the framework, I'd rather leave it and just add the warning to the docs.
