### ISSUE TITLE
Table hidden content stops being hidden after table has been resized

### ISSUE THREAD

**Issue by MMiknis** [Semantic-Org/Semantic-UI#5615]
Using the table with any functions that hide fields is causing issues when table gets resized due to window changes. When any of the fields on a table are hidden and table gets resided all the hidden content appears again. 

Below I have attached jsfiddle example with table that has 4 rows of which 2 are hidden but appear once the windows is resized.
https://jsfiddle.net/ca0rovs3/39/

**Comment by Banandrew** [comment]
Hi @MMiknis, that’s because it gets overriden with media-queries that you’ll have to include in your CSS.
