### ISSUE TITLE
[Docs] change language to non-english on front page then in main site back to english and it gets ignored

### ISSUE THREAD

**Issue by ChrisWalshGitHub** [Semantic-Org/Semantic-UI#5616]
**Steps to Reproduce**
change language to chinese on front page
go into the main site and change language to english using the world/globe icon

**Expected**
language should be english

**Result**
It's chinese... changing to a non-english language seems to work, english is ignored

**Comment by jlukic** [comment]
There was a typo in the html preventing english selection

```html
  <div class="item" data-percent="100" data-value="en data-english="English">
    <span class="description">English</span>
    English
  </div>
```

Fixed now
