### ISSUE TITLE
Large monitor breakpoint

### ISSUE THREAD

**Issue by rtarnaud** [Semantic-Org/Semantic-UI#5617]
In src/definitions/collections/grid.less, line 645, it states:
`@media only screen and (min-width: @computerBreakpoint) {`
I think the max-width is missing isn't it? Should be:
`@media only screen and (min-width: @computerBreakpoint) { and (max-width: @largestComputerScreen){`

**Comment by rtarnaud** [comment]
Or rather `@largestSmallMonitor` instead of `@largestComputerScreen`

**Comment by Banandrew** [comment]
Hi @rtarnaud, sorry for the delay, it intentionally targets PCs in general, while `@largeMonitorBreakpoint` and `@widescreenMonitorBreakpoint` target specific computer screen sizes, and will override `@computerBreakpoint`, so setting a `max-width` for it is unnecessary.
