### ISSUE TITLE
[ui] scale of entire ui double in safari vs chrome

### ISSUE THREAD

**Issue by rag666** [Semantic-Org/Semantic-UI#5620]
I created a web page in Semantic UI 2.2.11
```
		<div class="ui grid">
			<div class="row">
				<div class="ui inverted fixed menu navbar grid">
```
... with menu entries ...
then
```
			<div class="ui grid main">
				<div class="row">
					<div class="eight wide left aligned column">

```
... with various text and label components

I am in MacOs Sierra 10.12.6, and get what appears to be double the size in Safari 10.1.2 than in Chrome 59.0...  Please see attached screen shot with 
Chrome on left and safari on right.
<img width="1206" alt="screen shot 2017-08-02 at 10 49 44 am" src="https://user-images.githubusercontent.com/30662962/28882712-ad86dda8-7771-11e7-890c-1e2bf42d1212.png">

**Comment by Banandrew** [comment]
Hi @rag666, can you see the scaling on the documentation website as well?

**Comment by rag666** [comment]
Hello @Banandrew, yes I see the same scaling difference there on the documentation web site.

**Comment by Banandrew** [comment]
@rag666 I’m not certain, we probably need to investigate it further. How do you use SUI, did you include all of the components? Could you please check your `body` tag’s `font-size` in Safari and Chrome?

**Comment by rag666** [comment]
Thank you for your quick replies. 

I put this in my css because everything was even larger before.

html, body {
    font-size: 12px;
}

I tried going smaller, but it gets smaller in both browsers.  Both browsers have the page zoom set at 100%.  Chrome has a setting for font size, which is set to the default of medium; but I did not see an equivalent setting in Safari.

Richard

On August 2, 2017 at 12:58:11 PM, Andrew Golubev (notifications@github.com) wrote:
@rag666 I’m not certain, we probably need to investigate it further. How do you use SUI, did you include all of the components? Could you please check your body tag’s font-size in Safari and Chrome?

**Comment by rag666** [comment]
With your help and suggesting font settings I may have resolved it.  I hit the "cmd -“ key to reduce the font and that did the trick.  I tried clearing the last few days history to make sure it didn’t return, and it did not. Maybe I accidentally hit the “cmd +” a few times without realizing it and it kept the setting for that web page (I did not know it would do that, if that is what happened).

Many thanks
Richard

On August 2, 2017 at 12:58:11 PM, Andrew Golubev (notifications@github.com) wrote:

@rag666 I’m not certain, we probably need to investigate it further. How do you use SUI, did you include all of the components? Could you please check your body tag’s font-size in Safari and Chrome?

**Comment by Banandrew** [comment]
@rag666 Glad it’s resolved. I’ll close the thread, but please let me know if it returns, and we’ll figure something out.

**Comment by rag666** [comment]
I verified this by changing it again and then hitting "cmd 0" to return to default, and it returned to normal.
