### ISSUE TITLE
Tooltip on icon (i) tag with class flag and data-tooltip disapear until hover with the mouse

### ISSUE THREAD

**Issue by khalyomede** [Semantic-Org/Semantic-UI#5622]
## Issue
I detected an issue, here is the JSFiddle to reproduce the problem : [https://jsfiddle.net/j3joxh1e/](https://jsfiddle.net/j3joxh1e/)

This demo is composed of a button and a flag icon (you cannot see the flag, that one part of the issue).

The button has a tooltip, the flag also.

When hovering the button, the tooltip correctly appear.

When hovering just below the button (that is where the flag icon is supposed to be), the flag rotate and appears, and the tooltip appears.

## Remarks
This also apply to any `<i>` tag, not only flags.

## jQuery version
3.1.1

## Semantic version
2.2.11

## Tested on OS
Windows 7 (64 bits)

## Tested on browsers
- Google Chrome version 59.0.3071.115 (Official build) (64 bits)
- Firefox version 54.0.1 (32 bits)
- Internet Explorer version 11.0.9600.18738 (update version : 11.0.44 KB4025252)

## Browsers that are affected by this issue
- Google Chrome version 59.0.3071.115 (Official build) (64 bits)
- Firefox version 54.0.1 (32 bits)
- Internet Explorer version 11.0.9600.18738 (update version : 11.0.44 KB4025252)

## Scripts needed for this demo
- [https://code.jquery.com/jquery-3.1.1.min.js](https://code.jquery.com/jquery-3.1.1.min.js)
- [https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/semantic.min.js](https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/semantic.min.js)

## Stylesheets needed for this demo
- [https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/semantic.min.css](https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/semantic.min.css)
- [https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/themes/default/assets/images/flags.png](https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.11/themes/default/assets/images/flags.png)

**Comment by Banandrew** [comment]
Hi @khalyomede, sorry for the delay; the issue was discussed before: #4213.
