### ISSUE TITLE
[Grid] Inside Table In IE11 Should Render To Correct Width

### ISSUE THREAD

**Issue by cp1880** [Semantic-Org/Semantic-UI#5624]
E.g. https://jsfiddle.net/e1obpc3u/1/

**Expected behavior: ** The lorum ipsum text should wrap at the edge of the screen (and does in most browsers).

**Actual behavior: ** in IE11 the text renders off-screen.

The display:flex CSS rule seems to be to blame, but only when the grid is inside a table element. I was able to boil my problem down to as simple an example as I could (above). In one instance where this was causing me problems, I was able to remove the table, but in general we're using grids inside components that may get used anywhere.

**Comment by Banandrew** [comment]
Hi @cp1880, thanks, we’ll take a look. Setting `table-layout: fixed;` with `width: 100%;` on a `table` element seems to be fixing it, but can be undesirable.
