### ISSUE TITLE
Bug with menu element

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5627]
Hi,

Open this website -> https://www.deobraemobra.com.br

Click in the 3 lines (bar icon) at the right most of the header . Click in the first option BUSCAR POR EMPRESA. Click CANCEL. Now click the 3 lines (bar icon) again and you will see that the option BUSCAR POR EMPRESA is highlighted wrongly, it was not "reseted" as it should. How can we fix this problem?

**Comment by batata004** [comment]
Only I confirmed this bug? Could another person please confirm this?

**Comment by fridaetc** [comment]
Have you tried setting _selectOnBlur_ to _false_?

**Comment by Banandrew** [comment]
Hi @batata004, sorry for the delay, it’s been a busy week. This behavior is normal, the dropdown component has got the `action` property that’s `activate` by default and [is well documented](https://semantic-ui.com/modules/dropdown.html#/settings)—setting it to `hide` should do it, but you might want to see what options are available to you. In the worst case scenario, it also accepts a function.

**Comment by batata004** [comment]
@Banandrew  thanks my friend! I know the default option is to hide and it is working fine! It hide itself with no problem, that's not what I am reporting here. What I am reporting here is that after is hides itself it keeps the selected link selected. After the user click an option it shouldnt mark that item permanently, it should only mark it while the click is being made for usability. Right?

**Comment by batata004** [comment]
ALSO, I cant find selectonblur option inside the dropdown module. Maybe it was removed? See here -> https://semantic-ui.com/modules/dropdown.html#/settings

**Comment by Banandrew** [comment]
@batata004 I took the markup from your website and couldn’t reproduce. Could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) and create a test case?

**Comment by fridaetc** [comment]
Sorry you're right, that prop is for the react component. 
What about: _forceSelection = false_

**Comment by batata004** [comment]
Hi,

I created a small jsfiddle so you can see this bug in action so you dont need to acess https://www.deobraemobra.com.br anymore

https://jsfiddle.net/ca0rovs3/46/

Over your mouse in the 3 bars icon and click in the first option BUSCAR POR EMPRESA. After that click cancel in the promt that appears. If you now click again in the 3 bars icon you will see the first option remains marked forever which is not right.

**Comment by Banandrew** [comment]
@batata004 Like I said, you’re not using the `action` property:
```JS
$('#botao_links_uteis')
  .dropdown({
    on: 'hover',
    action: 'hide'
  })
```

**Comment by batata004** [comment]
@Banandrew again you are most right! Indeed the action has to be used! It worked, thanks my friend, sorry for the lack of understanding about this.
