### ISSUE TITLE
Transition: Element is no longer attached to DOM. Unable to animate.

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5628]
Hello. I'm using Semantic's Transition library along with dimmer and dropdown libs. But since i concat those lib's files in Gulp, Transition became broken and keep throwing me an error: `Transition: Element is no longer attached to DOM. Unable to animate.`

**Comment by JamesJGoodwin** [comment]
Resolved.

**Comment by maxpaj** [comment]
How did you solve it?

**Comment by shakeeb-mts** [comment]
Yes how you solve it?

**Comment by BastardFat** [comment]
Yes how you solve it?

**Comment by hochun836** [comment]
How did you solve it?
