### ISSUE TITLE
Dropdown using onchange="this.form.submit()" not working

### ISSUE THREAD

**Issue by vandolphreyes** [Semantic-Org/Semantic-UI#5629]
I want to submit a form after I change something on the dropdown.

Here's my code.

 ```
  <form action="/url" method="POST">
              <select class="ui dropdown" onchange="this.form.submit()">
                            <option value="">Select Page Number</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
              </select>
  </form>
```
Just how to accomplish this using dropdown and without using it's settings?

**Comment by Banandrew** [comment]
Hi @vandolphreyes,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
