### ISSUE TITLE
officials website is some wrong about chrome

### ISSUE THREAD

**Issue by Nowforpasserby** [Semantic-Org/Semantic-UI#5631]
https://semantic-ui.com/collections/form.html

OS：MAC 10.12.6
chrome：60.0.3112.90

when i come in the url ，that tab is always onload

**Comment by Banandrew** [comment]
Hi @Nowforpasserby, the Chinese version has got some problems that we’re tracking here: #5553, #4829, #5616. I didn’t quite understand the issue that you reported, could you please elaborate, in Chinese maybe?

**Comment by Nowforpasserby** [comment]
就是我的这个环境下，进入这个页面就一直在加载中，一直加载不完，只能强制关

**Comment by zealmurapa** [comment]
same issue here, glad am not alone
