### ISSUE TITLE
Vertical scrolling with dropdown inside

### ISSUE THREAD

**Issue by haotangio** [Semantic-Org/Semantic-UI#5632]
I'm struggling to create a `div` having both `overflow-y: scroll` and a dropdown display inside (see attachment).

The reason is that `semantic-ui` render the dropdown right inside the parent element, not in the root element (e.g: `body`).

I tried several time with the `z-index` but it still didn't work.

May someone give me any suggestion to deal with this issue?

![issue](https://user-images.githubusercontent.com/8952752/28996141-a8afa9e8-7a34-11e7-8ecb-9e1fd964d049.PNG)

**Comment by Banandrew** [comment]
Hi @haotangio, closing as a duplicate of #1340. I don’t think it can be solved with CSS, so you’ll have to wait for an update.
