### ISSUE TITLE
[Dropdown] The component setups a dropdown’s markup incorrectly

### ISSUE THREAD

**Issue by Banandrew** [Semantic-Org/Semantic-UI#5633]
I stumbled upon [this rule](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.less#L836) that’s never applied, because the component [inserts](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L242) a `.sizer` between an `input` and a `.default.text` during the setup.

**Comment by jlukic** [comment]
Fixed in `2.1.12`
