### ISSUE TITLE
Can't use Lists?

### ISSUE THREAD

**Issue by chris985** [Semantic-Org/Semantic-UI#5640]
I understand from the docs that they want us to use <a> within a div for menus and lists, but I would like to use a `<ul><li><a>` as normal.

However, when doing this, all sorts of strange things happen. Try this code:
`			<ul class="ui selection list">
				<li class="item"><a href="#">A</a></li>
				<li class="item"><a href="#">B</a></li>
				<li class="item"><a href="#">C</a></li>
			</ul>
`

Can "list" and "item" be made to work with UL and LI tags? That seems like it is the standards and it seems like a limitation of Semantic UI.

Same with menus.

**Comment by Banandrew** [comment]
Hi @chris985, please see #468, #1497, #3436, #28.

**Comment by chris985** [comment]
Hi @Banandrew I have looked over those posts and they all say the same thing: 

> semantic ui is tag ambivalent and you can use whatever tags you want.

 But if you copy the sample I provided, it just does not work when used with ULs. When you use ULs in the menu or just plain on the page like I provided in the sample.

This issue has not really been resolved yet

**Comment by Banandrew** [comment]
@chris985 I’m assuming you meant the bullets? Jack talks about it in #468.
