### ISSUE TITLE
Hitting Enter on Search

### ISSUE THREAD

**Issue by MarcusEFC** [Semantic-Org/Semantic-UI#5641]
When hitting enter on the Semantic UI search, I am being redirected from http://localhost:3030 to http://localhost:3030/?. Is there a way I can choose where the user is being redirected after they inserted some input in the search bar and hit enter?

**Comment by Banandrew** [comment]
Hi @MarcusEFC, `Enter` uses `preventDefault()` to stop it from happening, and I couldn’t reproduce. 
Could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) and create a test case?

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
