### ISSUE TITLE
[Form Validation] Emptiness validation should prevent whitespaces from approval

### ISSUE THREAD

**Issue by NicoAiko** [Semantic-Org/Semantic-UI#5649]
When validating the form I enter couple of whitespaces.  
I validate my form with `$('.ui.form').form('is valid')` which should end up invalid but it actually goes through anyway. It shows the error too, by the way.  

```javascript
$('.ui.form').form({
  fields: {
    label: {
      identifier: 'label',
      rules: [
        {
          type   : 'empty',
          prompt : 'custom Message A'
        }
      ]
    },
    amount: {
      identifier: 'amount',
      rules: [
        {
          type: 'integer[1..]',
          prompt: 'custom message B'
        }
      ]
    }
  }
});
```

**Comment by Banandrew** [comment]
Hi @NicoAiko, I can’t seem to reproduce: https://jsfiddle.net/8L5ny4yv/ Could you please fork it to create a test case?

**Comment by NicoAiko** [comment]
I can't.  
I don't know really why it passed through.  
The thing is that I use a list to add items to with the form having to be valid.  
When adding items to the list separate to the form though, even whitespaces pass through the form even though errors are being showed.  
I'll investigate this further, so I might update this some time in the future.

**Comment by Banandrew** [comment]
@NicoAiko Alright, I’ll close it for now, but please feel free to post here when you have something, somebody will reopen it.
