### ISSUE TITLE
Chrome Removing "Wide" Classes in Angular 4

### ISSUE THREAD

**Issue by joshrathke** [Semantic-Org/Semantic-UI#5650]
I don't know why, but at some point yesterday google chrome began removing "wide" classes beyond the first instance from my HTML elements. For example:

`<div id="contentContainer" class="three wide mobile twelve wide tablet thirteen wide computer column" [class.content-full-screen]="!sidebarVisibility">`

Becomes this:

`<div id="contentContainer" class="three wide mobile twelve tablet thirteen computer column" [class.content-full-screen]="!sidebarVisibility">`

I looked around and found [this older issue](https://github.com/Semantic-Org/Semantic-UI/issues/1526), but I'm not sure the context is the same. I am building an Angular application with a vanilla build of semantic. Not using any of the angular specific libraries. and it has been happening on multiple computers. Oddly Firefox and Safari seem to work just fine.

I am wondering if anyone knows if Chrome did an update or something like that. Or if anyone knows why all of the sudden the code is being interpreted differently.

**Comment by joshrathke** [comment]
So I did just realize that removing the Class Property binding tags fixes the issue. But I need them to make my application operate correctly. I'll investigate further...

**Comment by Banandrew** [comment]
Hi @joshrathke, thank you for posting, but I’ll close this for now, because it doesn’t seem to have anything to do with SUI itself, and we started limiting GitHub Issues to bug reports and feature requests to keep the board more manageable for maintainers. If you’d like it to be reopened in the future, please post here again.
