### ISSUE TITLE
Really really weird and nasty bug with semantic ui

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5652]
Hi,

I took almost 4 hours to get down to this bug and unfortunatelly it was on semantic fault. To check this bug is very easy as I will show you here.

First of all I am always told to use `<!DOCTYPE html>`  in my html files. And I use it many times. Sometimes I use `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`  which is very old and not very reliable nowadays BUT WITH THIS OLD DOCTYPE the bug does not happen, ONLY with the new DOCTYPE.

Open these 2 links, please:

http://quemfazsite.com.br/temp/teste1.php

http://quemfazsite.com.br/temp/teste2.php

BOTH LINKS have EXACTLY THE same content. EXACTLY. The only difference is that the first link uses the old DOCTYPE and the second link uses the new DOCTYPE.

Ok, where is the bug? In the second link you can see the shadow does not fit well inside the element. See print below with a blue arrow showing the problem:

![aa](https://user-images.githubusercontent.com/8988923/29256665-856512c6-8082-11e7-84d3-2c9ff9dc2a1f.jpg)

Of course, if this bug only happened with the old DOCTYPE I would never take your time opening this bug report. BUT this happens only with the new DOCTYPE. Also I discovered another thing that shows that semantic ui is indeed buggy with this problem:

If I use: `<div style="padding:20px; background:#FFFFFF; height:300px;"></div>` (see that there is no content in the div) the bug happens BUT if I use `<div style="padding:20px; background:#FFFFFF; height:300px;">x</div>` (see that there is content in the div) the bug never happens. You can clearly see this in the second link I posted: the red box in the left has the bug but the box in the right has no bug.

This is a very weird bug cause it works differently depending in the DOCTYPE used AND also works differenty is the DIV has content. AND in the second case, intuitively, the bug should happen only when there is content in the div and never if there is no content inside of it - but in this case the bug demonstrates exatly the opposite.

When I am building some projects I like to make them "pixel perfect" and this bug has been annoying me for months and only today I had time to spare and investigate it and I could never think this could be a semantic ui problem.

I am pretty sure if this bug happens in a simple case as I reported here it may very well happens in other cases that people may be struggling hard to make their design pixel perfect and they may not be aware that semantic ui may be making it a very hard task.

**Comment by Banandrew** [comment]
Hi @batata004, this is not an issue with SUI. Containers with `inline-block` calculate visual height based on inherited `line-height` property, `body`’s in this case, and you can check it on `teste2.php` by increasing the `line-height` property on the `body` tag with developer tools. In your case, elements with `inline-block` should have a `line-height` of zero.

**Comment by batata004** [comment]
@Banandrew wow my friend that was fast!!! I spent hours into this and you solved it in seconds! I didnt know inline-block should have line-height zero. It's strange cause if I need to use line-height (like 20px) inside the element, I will have to set line-height to 0 AND CREATE a "useless element" inside it to hold the line-height:20px, right my friend? Or this can be solved any other way?
