### ISSUE TITLE
[Form Validation] How to clear (reset) error messages?

### ISSUE THREAD

**Issue by erlangp** [Semantic-Org/Semantic-UI#5653]
How to clear (reset) error messages? like `remove prompt` behavior. Thanks

**Comment by Banandrew** [comment]
Hi @erlangp, if I understood you correctly, although undocumented, `remove prompt` is actually a thing, and works the same as `add prompt`, accepting a field’s `identifier` as its first argument:
```JS
// For <input name="empty" type="text">

$('.ui.form')
  .form('remove prompt', 'empty')
```
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by erlangp** [comment]
Thanks that's what i mean :+1:
