### ISSUE TITLE
Input (with a Button) Does Not Correctly Align on Center

### ISSUE THREAD

**Issue by mixerp** [Semantic-Org/Semantic-UI#5655]
<img width="1440" alt="sui-input" src="https://user-images.githubusercontent.com/5273383/29277998-2ec387d4-8133-11e7-9cc1-9c133b576d9c.png">

Semantic UI Input does not center align correctly. Screenshot attached.

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by vinayakkulkarni** [comment]
OP hasn't replied, closing this till @mixerp replies.

PS. Visit [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord](https://discordapp.com/invite/8rr9bsg) for any usage related questions.
