### ISSUE TITLE
Lack of consistency with sizes

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5658]
Hi,

I am migrating several websites to use semantic ui and I am having a really really hard time to make size (big, small, huge...) consistent.

Here is one example. I have 3 elements with class "big" but their actual size if very different.

https://www.quemfazsite.com.br/temp/teste123.php

Check the height of the elements, they are all randomly different.

This problem is more evident in this website https://www.frasesparavida.com.br if you scroll down you will see that a menu will appear and all the 3 itens have completely different heights. The only way I have to fix this is trying to modify line-height of each element to very oddly values but this is very time consuming. If you see at that website https://www.frasesparavida.com.br in the middle there are 3 elements to search (1 input, 1 select and 1 button) and the ONLY WAY I COULD MAKE all 3 itens with same height was trying and error "line-height" with different values!

![image](https://user-images.githubusercontent.com/8988923/29366126-878f7732-826f-11e7-9f60-307053cd0a15.png)

I must be doing something really stupid but if you see the example in the top of this code (teste123.php) I minimized the amount of code so you can see it clearly. I also suggest you to play with line-height in the teste123.php example, if you adjust line-height to very oddly values you can make all 3 elements with same height but that takes forever.

**Comment by batata004** [comment]
One more question: sometimes the class "big" makes an element (button, for exampe) with a certain height, but sometimes, if I use this same button in other places of my code the "big" class size makes the button very small!

I am probably missing something or something is not clear in the docs, would you mind clarifying it to me?

**Comment by Banandrew** [comment]
Hello again @batata004,

* The dropdown component doesn’t offer size variations out of the box, and it picked up the `font-size` property from the search component.
* You set an `input`’s `font-size` directly on an `input`, which is unnecessary, since `.ui.big.input` already sets it.
* Dropdowns work with the input component only if the input component is used as an `.action` container—try utilizing that, it’s thoroughly described on the input’s documentation page.

That’s about it, as for your second question about a button, I can’t comment on it without a test case. Also, if you’re not sure whether it’s a bug or not, or have a quick usage question, please post in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI) first—it’s difficult to maintain the board as it is, and we’d rather not leave issues unanswered, so it quickly clogs the whole workflow.

**Comment by batata004** [comment]
My friend I am really sorry for posting stupid question and keeping posting them. I promise I will avoid it but I think the documentation is terrible, important information is frequently shown in the bottom or not with good highlight. 

I saw the documentation and I have never seen it says that the font-size manages the size of the input. Never. I thought the line-height.

But lets move on. I did xactly what you said, I applied the same font-size to all the components and they all looked with the same size except the button! I applied font-size:16px see:

http://quemfazsite.com.br/temp/teste1233.php

You wanna see the strangest thing? If I try to play with font-size 15, 14 or 17, 18... the size NEVER FITS the size of the other boxes. Please try yourself editing the font-size of the button, it will never match the other elements size!

BUT if you remove the font size and only play with line-height in the button, if you change it you can reach the exact size. See here below, line-height 21px

http://quemfazsite.com.br/temp/teste1244.php

FOr some reason when I play with font-size the incremental size is too big from 16 to 15 or from 16 to 17 so it never fits well. But for some reason with I play with line-height the incremental is pixel size so it's possible to match the desired size that I want.

I am really sorry with my questions but I am having a really hard time with semantic ui. I love it, it's clean, simple, BEAUTIFUL and the community is awesome! BUT the documentation leaves a lot to be said to not advanced programmers and many "small bugs" make this library hard to use. I say "small bugs" things like the ones I reported here already in other threads and you always nicelly replies to me, always! I know they are not bugs but they are things that to not advanced users to know is veeery hard, the docs should be clearer.

Anyway if you could take a look at those 2 examples above I think you could see the "bug" I am saying.

**Comment by Banandrew** [comment]
@batata004 I agree, the documentation could be so much better, but I also think that we can’t be documenting the use of every single CSS property that can easily be inspected with developer tools. SUI is just CSS, a backbone to build your project on, and I think it’s incorrect to treat it as a complete product just
 because it’s got a pretty theme—engineers should be comfortable with the idea that it’s there to be extended, modified, and learned.

>I did xactly what you said
You didn’t, all of the elements should be inside of the `.ui.action.input` container—as per the input component’s documentation. I’d like to talk more about the CSS behind it, but I’m sorry, I have no time to.

**Comment by batata004** [comment]
Great school you are my friend! You taught me so much! I will use .ui.action.input when I get home and I will make sure I come back here to thank you again!

**Comment by batata004** [comment]
@Banandrew WOW!!!!!!!!!!!! YOU ARE RIGHT!!!!! Adding the class worked!!! ;)

BUT NOW that I added the class another bug came up in the same simple example. I created a copy here:

https://www.quemfazsite.com.br/temp/teste123456.php

If you see all elements are marked with "float:right" BUT for some reason semantic UI is removing the float right and setting float:none. I inspected all the 3 elements that have float:right inline and all of them are getting float:none in the F12 of my chrome. Why that? How can I fix that now? I really need to use float:right in the website that I am migrating to semantic ui.

About the documentation I understand what you said, indeed if the documentation should say something about every css property then it would get bigger, bigger than the bible! But still, to beginners like me in semantic ui I am having lots of pain.

I will be very honest: I read most of the documentation and I see no where saying I should use .ui .action .input in the container. Take for example this -> https://semantic-ui.com/elements/button.html

The link above talks specifically about the sizes, there is even a part in the that link that shows all the sizes available (small, big...). It says absolutely nothing about the user having to mandatory use the .ui .action .input class in the parent element.

**Comment by Banandrew** [comment]
@batata004 What are you trying to achieve with `float`, how is it supposed to look?

Here it is, see the “Action” section: https://semantic-ui.com/elements/input.html

**Comment by batata004** [comment]
I need my friend to put all the 3 elements floating to the right, I cant use display:inline-block with align right because of the surrounding elements.

See here -> https://www.deobraemobra.com.br/

You see in the top there are 3 semantic ui inputs (2 select box and one button box). I really need to use float right.

I think that this is clearly a bug, you know why? If you inspect the element you will see the bug. I inspected it to you: See the 2 red arrows in this image:

![image](https://user-images.githubusercontent.com/8988923/29438826-abbc870a-838f-11e7-97ae-78e5014a9f08.png)

Now the "Style" tab in the right. I have never seen something like this, the float:right line should be striken by a line if it was indeed "none".

![image](https://user-images.githubusercontent.com/8988923/29438849-ced517a2-838f-11e7-9a9c-a550c7653051.png)

If you inspect this you will see the problem. I cant imagine why this is happening... and it's said cause this bug ONLY HAPPENS after I add the "ui input action" class you told me. Without these clases the problem does not happen BUT the sizes are buggy.

I took a look at here https://semantic-ui.com/elements/input.html#action and I see no reference ttelling it's mandatory to use .action class in the parent element. Where are you seeing this information?

**Comment by Banandrew** [comment]
@batata004 I think that all those same inline styles that you apply to `.ui.action.input > div` are unnecessary (except for the width, of course), you can apply them to `.ui.action.input` directly. If you don’t want to apply them to a `form`, put them in a container: `form > div`. I tried it, seems to be working fine.

**Comment by batata004** [comment]
@Banandrew ok, those styles are needed in my original code. I removed them. So I realized now 2 bugs, not only one. To make this clearer and not confuse with this thread I assigned a new thread to these 2 bugs ok? -> https://github.com/Semantic-Org/Semantic-UI/issues/5668
