### ISSUE TITLE
[Embed] Add alt attribute to placeholder image

### ISSUE THREAD

**Issue by mdhtr** [Semantic-Org/Semantic-UI#5659]
I'd like to add alt text to video placeholder for accessibility reasons.

I think the alt attribute could be added to embed.js here:
```    
if(image) {
    html += '<img class="placeholder" src="' + image + '">';
}
```
And then the altText could be provided as user option.

**Comment by aydrian** [comment]
Can we please reopen this? I don't believe this is an enhancement but something that is needed for accessibility. An img tag without an alt property will affect Lighthouse scores. We need a fix or a proper work around.

**Comment by mdhtr** [comment]
@aydrian if you want this reopened, I suggest you create a new issue instead and mention this one in it as well. Maybe it will get some more attention this time.
