### ISSUE TITLE
How to change the text color of an <Input /> component knowing that I'm using the Semantic-Ui-React CDN ?

### ISSUE THREAD

**Issue by aziz-boudi4** [Semantic-Org/Semantic-UI#5661]
I'm trying to change the text color of the <Input /> component but with no success .
1- I tried using the prop className.
2- I tried to override the Input css class.

nothing worked so far

**Comment by Banandrew** [comment]
Hi @aziz-boudi4, React implementation is in [a separate repository](https://github.com/Semantic-Org/Semantic-UI-React/issues), and it’d be best to ask there.
