### ISSUE TITLE
lu

### ISSUE THREAD

**Issue by luluyiluchangtong** [Semantic-Org/Semantic-UI#5665]
Why I open the semantic - UI web site is always slow and sometimes unshown.I'm sure it's not broadband

**Comment by vinayakkulkarni** [comment]
Please join our [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) and/or [Discord Server](https://discord.gg/7vqmGxa) for usage related issues.

Closing this as it's not related to SUI itself.
