### ISSUE TITLE
[Dropdown] CSS: Inconsistent style when with scrolling class

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI#5671]
Looking on this [JSFiddle](https://jsfiddle.net/0au4c68n) you'll see that `Dropdown 1` is cool, while `Dropdown 2` does not have the thin line between items and the menu is a bit off on the right side.

I'm using Chrome 60.0.3112.90 on a macOS Sierra 10.12.6

Thanks!

**Comment by Banandrew** [comment]
Hi @AlvMF1, it’s intentional—there’s no point using `.scrolling` in `.selection` dropdowns, because they already have `overflow-y` and `max-height` set. Please let me know if you’d like to know how to modify the amount of options shown in `.selection` dropdowns.

**Comment by AlvMF1** [comment]
I was wondering b/c I use SUI React and the [dropdown](https://react.semantic-ui.com/modules/dropdown) has an `scrolling` prop. Maybe it's for something else @levithomason?

Thanks, anyways!

**Comment by Banandrew** [comment]
@AlvMF1 Take a look at the “Scrolling” section in “Variations” [here](https://semantic-ui.com/modules/dropdown.html). By default, it’s either to limit simple dropdowns that have a lot of options, or “Search In-Menu” pattern that uses two menus, a `.scrolling.menu` in a `.menu`.

**Comment by levithomason** [comment]
Yep, for use with regular dropdowns:

https://react.semantic-ui.com/modules/dropdown#dropdown-example-scrolling

![image](https://user-images.githubusercontent.com/5067638/29496045-4deb2e8c-857f-11e7-9646-667cf4b8c6e2.png)
