### ISSUE TITLE
[Dropdown] Add an ability to show menus in the center from a dropdown parent

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5673]
Hi my friends,

I know I can use pointing class to set the positino of the dropdown menu that appears in the .menu element. But I would like to know if its possible to set it to center?

See this -> https://www.frasesparavida.com.br/

Hover your mouse of LINKS at the top. You will see that the sublink menu appears aligned to top left. 

Now open this -> http://quemfazsite.com.br/temp/aaa/modelo12/

Hover your mouse in the links A EMPRESA or SERVIÓS. You can see that the sublink menu (that shows up) is centered aligned to the PARENT item. Is this possible?

**Comment by Banandrew** [comment]
Hi @batata004, no. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by batata004** [comment]
Sorry, will not happen again.

**Comment by batata004** [comment]
@Banandrew just to help, in the .item element inside the .ui.menu element I used this:

`onmouseover="$(this).children('.menu').css({left:($(this).width() - $(this).children('.menu').width())/2 + 'px'});"`

It worked very nicely, the dropdown menu aligned correctly centered to the parent! The math is simple: take parent width subtract from the dropdown width and divide by 2. Assign that to the "left" property.

I wonder how complicated would be for you guys that have full access to semantic ui code to add this to the main branch. So I could easily add the class "pointing center top" to my .item element and the dropdown would align center. Would that be too hard my friend?

**Comment by batata004** [comment]
My friend @Banandrew I tested a simple code here that worked perfectly! It calculates the menu left position in the onShow event of the dropdown and it works very well. It would be nice to have this enhancement included in the library by default so the user could simply add center class! I think this does not look too complicated to include and makes the menu much much more beautiful!

```
	$("#menu_links").find(".dropdown").dropdown({
												
		on:"hover",
		action:"select",
		onShow:function() {
	
			$(this).find(".menu").css({left:-1*($(this).find(".menu").outerWidth() - $(this).outerWidth())/2 + "px"});
		
		}
		
	}); 
```
