### ISSUE TITLE
Problem with margin-top in the .ui.menu element

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5678]
In the video below I demonstrate this problem. I will not say it's a bug (yet!) but I am pretty sure it's a problem to who is  trying to use the drop down menu of semantic ui. This problem is easily reproduceable and only happens if you use .dropdown({on:"hover"}) . In the link below I provide you the minimum code to generate the problem so you can inspect it easily!

https://quemfazsite.com.br/temp/teste-problema1.php

Here is the short video showing the problem!

https://goo.gl/photos/gSE8YBWzBgj9fpaF8

In the video I present the problem and also the solution at the end which is easy to implement IMHO! No crazy stuff required. ;) The first website where I show you the bug is running localhost the second is running in this link if you want to play with it -> https://www.frasesparavida.com.br

I really hope this helps!

**Comment by Banandrew** [comment]
Hi @batata004, the dropdown component [uses timers to ensure a user’s intent on hover](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3402)—this is by design. You can use the `delay` property to control it, here’re the defaults in ms:
```JS
delay: {
  hide: 300,
  show: 200,
  search: 50,
  touch: 50
}
```
As for everything else, I think that the component works properly, and I’m treating your issues with it as a use case. The initial and the second jiggling transitions probably happen, because a `.menu` is still a dropdown, and it’s up to you as a developer to figure out a way of dealing with it.

**Comment by batata004** [comment]
Great answer my friend, I was not aware of those configurations!

But I think you may not have understood well what is going on: the problem here is not the delay, nothing related to the delay. Despite you provided a very good answer and taught me new thing the problem here is related to the margin-top of the element

Just to make sure the delay is not the problem here I created another test case for you with the delay set to a high value (10 seconds - 10000) so we can disccard it as being the curlprit.

http://quemfazsite.com.br/temp/teste-problema2.php

Do this: open the link above, open your console, hover your mouse over a link that has a dropdown. Wait the dropdown appears (so you can disccard any issue related with the delay, timing...). Now move your mouse down to the dropdown items. Check the message I programmed to appear in the console, you will see that the MOUSELEAVE event will be fired and MOUSEENTER will be fired DESPITE the mouse is still hover the element wrarping the whole thing.

This problem is caused by the MARGIN-TOP in the .menu element. If, instead of being used MARGIN-TOP you use PADDING-TOP (just an example) this problem would never happen! The problem here is that the margin-top causes the .menu element to be distant from the .text element so when the mouse is traveling from .text to .menu it goes to a hole/blank area that causes the mouseleave to be triggered. IF INSTEAD (and you can teste this easily) you use padding-top it will work perfectly! Of course padding-top will not make the element beautiful, in the end if you agree to find a solution to this problem I would suggest using padding-top in a parent element around the .menu element.

The margin-top here is known for causing this problem, the mouseleave problem. If instead you use padding-top this known problem does not happen anymore

I really hope I could make myself being understood, I am not an english native person, I speak only portuguese and very badly I "speak" english so if I was not clear in something please forgive me.

**Comment by Banandrew** [comment]
@batata004 It does happen because of the `margin`. Could you please build your case better, what are you doing with mouse events that makes it a problem?

**Comment by batata004** [comment]
Glad we are at the same page now ;)

My build case is this: I want to add nice hover effect in the .text item. For example, open this site:

https://www.frasesparavida.com.br/

Hover your mouse in LINKS. You see there is a small "bounce" effect in the word LINKS when you pass your mouse over it? That's nice, semantic ui allows me to do that very easily! BUT there is a problem! Move down your mouse to navigate in the sublinks (of the LINK menu). When you move down your mouse, because of the margin-top, the mouseleave is triggered for the whole .ui.item! And right after that the mouseenter is triggered too! That causes a very weird effect.

NOW please press F12 in your Chrome and edit the element to remove the margin. It is by default something like "magin:1em 0 0". Please set it to zero. The problem goes away immediatly!

So my case here is this: IF instead of using margin-top you used anything else (like padding-top) this problem would go away simply! But of course you cant simply change margin-top to padding-top because of the background of the sublink menu, maybe using pseudo element ::before or :;after to have the padding would be a good solution.

Dont you think the proposal that I am doing is relevant? If you dont think I understand and I will have to live with this problem. But if you understand that people may want to add custom effects to their link menu then this problem should first be fixed cause it triggers unnecessary mouseleave/mouseenter event!

**Comment by Banandrew** [comment]
@batata004 I don’t think it can be useful outside of an isolated use case.

**Comment by batata004** [comment]
Thanks my friend @Banandrew ! Anyway, I believe people may try to animate their websites in future and face the same problem as I. You can keep this thread closed but if you have some time in the future I think it would be a quick fix and a great addition to semantic ui to allow users to do fancy things.

I was just studying a little bit about bugs and I came accross this definition in wiki:

"A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways."

Certainly is an unexpected result to have semantic ui firing onmouseleave when it's not supposed to. I am also sure that if a mouse is hover a menu item and it fires the onmouseleave event it's a clear definition of "behave in unintended way". The intended way was NOT to fire onmouseleave event if the user is with his mouse over a link/sublink.

Anyway I dont want to take more of your time, you already gave me a great deal of your time and allowed me to understand a lot better semantic ui! 👍 If any time in the future you have time to have a quick fix into this I would appreciate!
