### ISSUE TITLE
[Accordion] The transition animation has a problem when being used with Vue.js and Chrome

### ISSUE THREAD

**Issue by t123yh** [Semantic-Org/Semantic-UI#5680]
[See this fiddle](https://jsfiddle.net/mbc9vr4y/)

When you click the sections open, the animation is a little 'over-shoot'. This can only be replicated by Chrome. Firefox seems to be of no problem.

![peek 2017-08-22 10-06](https://user-images.githubusercontent.com/8972552/29545554-9cde5c96-8721-11e7-8fde-98b0a5340d42.gif)

**Comment by vinayakkulkarni** [comment]
I tested this on `Chrome 60.0.3112.101 (Official Build) (64-bit)` and it doesn't 'over-shoot' on it.. 

Do you have any plugins / extensions on Chrome?
Did you try it in incognito mode?

**Comment by t123yh** [comment]
@vinayakkulkarni Yeah, I tried this on a Windows Chrome, and it neither over-shoots. It seems to be a platform-specific problem. I'm running Chrome with KDE on Manjaro Linux.

BTW, If I don't use Vue, there's no problem at all.

**Comment by vinayakkulkarni** [comment]
Can you please try [this updated version](https://jsfiddle.net/mbc9vr4y/1/) in Chrome with KDE ?

**Comment by t123yh** [comment]
No, it doesn't help.
