### ISSUE TITLE
[Label][Reveal] ribbon label has lower z-index than fade reveal image

### ISSUE THREAD

**Issue by JGJP** [Semantic-Org/Semantic-UI#5681]
top: ribbon label being hidden behind class="ui fade reveal image"
bottom: same thing with the z-index of the ribbon label set higher

![label-issue](https://user-images.githubusercontent.com/3692190/29549445-545e538c-8743-11e7-9014-277554087a7a.png)

**Comment by vinayakkulkarni** [comment]
Dear @JGJP,

As per our community guidelines, please provide a usecase, you may fork this [jsFiddle](https://jsfiddle.net/ca0rovs3/)

For usage related questions, please visit our forums or [gitter channel](https://gitter.im/Semantic-Org/Semantic-UI)

**Comment by vinayakkulkarni** [comment]
Closing this till OP replies.

Kindly visit [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord](https://discordapp.com/invite/8rr9bsg) for any usage related questions.

**Comment by JGJP** [comment]
Sorry for the late reply, hope this is ok:

https://jsfiddle.net/jgjp/ndns5009/3/

As you can see, the first image is using the semantic-ui as is, and the second image is showing what I expected it to look like. All I've done is added a z-index as an inline style to fix it.

**Comment by jlukic** [comment]
Fix added in next release
