### ISSUE TITLE
Text blurry when using checkbox 

### ISSUE THREAD

**Issue by ven007** [Semantic-Org/Semantic-UI#5686]
All the text get blurry when i use the semantic ui checkbox .
Without semantic UI checkbox (its clear and nice )
![20](https://user-images.githubusercontent.com/10803076/29582746-ba3f9366-8732-11e7-8a86-7b204cab26cb.PNG)
After adding semantic UI checkbox (its blurry )
![a0](https://user-images.githubusercontent.com/10803076/29582745-ba3e62de-8732-11e7-859b-df76b9e31c52.PNG)

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by ven007** [comment]
https://jsfiddle.net/ca0rovs3/

**Comment by Banandrew** [comment]
@ven007 Your JSFiddle is empty, it’s the one I attached. You need to click “Fork”, fill the boxes to create a test case, then click “Update” to save it, the link in the address bar will be changed, and that’s the one that you need to post.

**Comment by ven007** [comment]
https://jsfiddle.net/ca0rovs3/

**Comment by Banandrew** [comment]
@ven007 It’s the same JSFiddle again. What’s the problem, can I help you?

**Comment by ven007** [comment]
Please check this .
https://jsfiddle.net/ca0rovs3/65/

When i add the semantic ui checkbox to the form , the text gets blurry in the chrome .Like the image i have posted . Can you please let me know how i can fix it ?

**Comment by Banandrew** [comment]
@ven007 Which text exactly is blurried?

**Comment by ven007** [comment]
labels text , button text ,icons

**Comment by Banandrew** [comment]
@ven007 It’s going to be happening regardless of the presense of the checkbox, because you’re landing on a half-pixel during the CSS transformation—that’s how the browsers are, and it has nothing to do with SUI. There’re several things you can try to fix it, but please use other resources to do the research.
