### ISSUE TITLE
What kind of book will help me learn Semantic-UI quickly?  (general question)

### ISSUE THREAD

**Issue by aguyinmontreal** [Semantic-Org/Semantic-UI#5687]
I want to help someone on a SemanticUI project. Since, I'm a back-end coder, my knowledge of HTML and CSS is very basic. What book should I read to be able to help him with SemanticUI? 

Should I read a book about Bootstrap3? Is it close enough? Or should I read a general book about Responsive Design?

Thanks!

**Comment by vinayakkulkarni** [comment]
This would get more replies and discussed properly live on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord](https://discordapp.com/invite/8rr9bsg)
