### ISSUE TITLE
Feature Tab responsive

### ISSUE THREAD

**Issue by pierre-H** [Semantic-Org/Semantic-UI#5688]
Hello,

First, I'd like to say THANKS A LOT for Semantic UI : best UI Framework ever !

Is it possible to make responsive tab without pointing or secondary menu : just classic tab ?

Thank you

**Comment by vinayakkulkarni** [comment]
Hi @pierre-H, 

Take a look at [Tabular Menu](https://semantic-ui.com/collections/menu.html#tabular)

Also, if you have questions related to usage, kindly join our [Gitter channel](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord server](https://discord.gg/8rr9bsg)

Closing this issue as it's not related to bug / feature regarding SUI framework itself.
