### ISSUE TITLE
Dropdown set selected issue with Meteor Blaze

### ISSUE THREAD

**Issue by ch-luke** [Semantic-Org/Semantic-UI#5690]
If I do $('.article').dropdown('set selected', 'a') on a standard select it works.

`<select class="article ui search dropdown">
      <option value="">Article</option>
      <option value="a}">A Article</option>
 </select>`

But when I'm using Blaze (e.g. $('.article').dropdown('set selected', -VARIABLE-)) it does not set and the DOM doesn't fully register the generated div.item elements.

`<select class="article ui search dropdown">
      <option value="">Article</option>
      {{#each articles}}
          <option value="{{_id}}">{{title}}</option>
      {{/each}}
 </select>`

Any suggestions ?

**Comment by Banandrew** [comment]
Hi @ch-luke, this repository covers CSS and JS only, and I think it’d be best to ask around Meteor communities first. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
