### ISSUE TITLE
the browser block

### ISSUE THREAD

**Issue by s952787097** [Semantic-Org/Semantic-UI#5692]
The  http://www.semantic-ui.cn   when you click "输入框"  the browser block. (eg:Chome and FireFox )

**Comment by vinayakkulkarni** [comment]
Hi @s952787097,

Can you please tell what's the issue here? It seems you're just informing us something?

For live support ping us on the [gitter channel] (https://gitter.im/Semantic-Org/Semantic-UI)

Waiting for your reply, closing this till then.

**Comment by Banandrew** [comment]
Hi @s952787097, it’s actually a duplicate of #5553, we’re aware of the issue.
