### ISSUE TITLE
I need a sass files!

### ISSUE THREAD

**Issue by manyopensource** [Semantic-Org/Semantic-UI#5693]

**Comment by manyopensource** [comment]
Instead less (less is a old-school: it's very bad)

**Comment by vinayakkulkarni** [comment]
This is a usage related question.

Please visit our [Gitter Channel](https://gitter.im/Semantic-Org/Semantic-UI) for live support.

**Comment by Banandrew** [comment]
Hi @manyopensource, there’s a reason why SUI is a LESS-based framework—SASS doesn’t support variables in include paths preventing theming with SUI—and it has been discussed and explained before [here in SASS’ repository](https://github.com/sass/sass/issues/739#issuecomment-73984809), you might want to read the whole thread.
