### ISSUE TITLE
$(this) not working inside of .api().

### ISSUE THREAD

**Issue by cythgear** [Semantic-Org/Semantic-UI#5695]
Hi.
I have this code:
```
$('.like.icon')
  .api({
    url: '/',
    method: 'POST',
    data: {
      id: $(this).attr('post-id'),
    }
  });
;
```

I have this element in my template:
```
<form method="post">
  <a class="like">
    <i class="like icon" post-id="{{ post.id }}"></i> Like
  </a>
</form>
```

The idea is I have multiple posts with the same element (same class), but with different `post-id`, of course.

When a user click on one of that elements, I need to be able to get the `post-id` attribute from that clicked element, so I need to use `$(this)`, but it's not working.
I've tested on `.click()` event:
```
$('.like.icon').click(function() {
    console.log($(this).attr('post-id'));
});
```
and It's working perfectly, but when I use the `.api()` is returning `undefined`.

Can someone explain me why it's not working? Am I doing something wrong?

**Comment by Banandrew** [comment]
Hi @cythgear, you don’t have to do any of that, you can set up a `url` with parameters instead, which is described in the “Attaching API events” section [on this page](https://semantic-ui.com/behaviors/api.html#/usage). Here’s an example: https://jsfiddle.net/e0nbdpyh/ `data-id` will be automatically sent with the request—you can open the “Network” tab of your browser’s developer tools to see the request.

If you have more questions, I’ll be happy to answer them either in this thread, or in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by cythgear** [comment]
Thanks!
