### ISSUE TITLE
data-content pop-ups do not work in tables

### ISSUE THREAD

**Issue by Mariusmssj** [Semantic-Org/Semantic-UI#5698]
I am having issue using data-content pop-ups in tables as no matter what I do they do just do not work. data-tooltip works fine but I cannot adjust size and width thus I want to use data-content pop-ups but they just down work in tables.

I've got a [jsfiddle environment example setup](https://jsfiddle.net/ca0rovs3/70/) that shows the issue. Am I doing something wrong? (pop-up example code is straight copy from semantic-ui website)

**Comment by Banandrew** [comment]
Hi @Mariusmssj, that’s because `data-tooltip` one uses `:before` and `:after` psuedo classes, which allows it to work without JavaScript. Everything else should be initialized with the `popup()` method.

**Comment by Mariusmssj** [comment]
Thank you :)
