### ISSUE TITLE
A few ideas for implementing custom color palettes

### ISSUE THREAD

**Issue by mwcz** [Semantic-Org/Semantic-UI#57]
Semantic's selectors currently have color values hardcoded, such as `.teal` and `.red`.  I do like the readable nature of those color names, but it does locks the library into only supporting a small handful of static colors.

It also makes it rather difficult for a web designer to convert a Semantic UI-powered site to a new color palette.  Below is a first draft idea on how to add color palette support to Semantic UI.

Two things need to be added to support palettes:
1. Variable color names
2. Variable color values
## Adding support for more color

Colors could be defined in a `palette.less` file with color definitions like these:

```
@P1_NAME: e('white');
@P1_COLOR: #ffffff;

@P2_NAME: e('black');
@P2_COLOR: #000000;

@P3_NAME: e('teal');
@P3_COLOR: #008080;

@P4_NAME: e('red');
@P4_COLOR: #ff0000;
```

_`palette.less` would be modified on a per-site basis to support the desired color palette._

And those colors could be referenced inside selectors across the rest of the library like this:

```
.myclass.@{P1_NAME}.foo { color: @P1_COLOR; }
.myclass.@{P2_NAME}.foo { color: @P2_COLOR; }
.myclass.@{P3_NAME}.foo { color: @P3_COLOR; }
.myclass.@{P4_NAME}.foo { color: @P4_COLOR; }
```

CSS result:

```
.myclass.white.foo {
  color: #ffffff;
}
.myclass.black.foo {
  color: #000000;
}
.myclass.teal.foo {
  color: #008080;
}
.myclass.red.foo {
  color: #ff0000;
}
```

_These selectors would be_  **not**  _modified on a per-site basis._
## Adding support for color permutations

[less](http://lesscss.org) has an awesome array of [color adjustment functions](http://www.lesscss.org/#reference) like `lighten()`, `saturate()`, and more.  Making use of those removes the need to have _dozens_ of unique color codes littering CSS files.  (Note: `contrast()` is perfect for `.inverted`)
## Limitations and Trade-offs
1. Because [less](http://lesscss.org) does not support loops, a limited number of colors can be added.  I lean toward 8 colors being the max.  Very few people would want more than 8 colors on a page, and 8 wouldn't add many SLOC to each selector.
2. Spaces cannot be allowed in color names, but [less](http://lesscss.org) does not provide a way to restrict spaces, or substitute `-` dashes.
3. **The biggie**: custom palettes can not be freely dropped onto an existing Semantic UI site.  With this scheme, adopting a new palette _requires_ markup changes.  That's the price of readability, I suppose.  `class="teal"` versus `class="color1"`.  The former provides excellent readability, while the former allows for better markup-css separation.

If anyone has suggestions, better ideas, ways to overcome the limitations, or any other feedback please contribute!

**Comment by rajeshyogeshwar** [comment]
Is this feature developed? Where can I find more information relating to custom color palettes?

**Comment by jlukic** [comment]
@rajeshyogeshwar http://semantic-ui.com/usage/theming.html#sitewide-defaults
