### ISSUE TITLE
BUG - Ability to enter data in disabled input fields

### ISSUE THREAD

**Issue by AlekseyKasaev** [Semantic-Org/Semantic-UI#5704]
**Steps to Reproduce**
1. Make focus on the previous input field (page https://semantic-ui.com/elements/input.html)
2. Press Tab
3. You are able to write data in the disabled input fields

**Expected**
The disabled input fields should not recive focus

**Comment by Banandrew** [comment]
Hi @AlekseyKasaev, it’s a developer’s responsibility—you can use ` tabindex="-1"` or `disabled=""` on an input to stop it from happening.
