### ISSUE TITLE
Changing background color in inverted menu does not work

### ISSUE THREAD

**Issue by bneumann** [Semantic-Org/Semantic-UI#5708]
Hi,

I was just fiddeling around with the inverted menu when I found that this is not working as expected:

I have a menu and want all items to be of a different color. Here is the fiddle: https://jsfiddle.net/k9ryccjn/2/ 

Although I do it as in the https://semantic-ui.com/collections/menu.html#colored example it does not work.

**Comment by mfaheemakhtar** [comment]
I think there are some problems with the code you are using:

1. You will have to manually add "active" class or write a script to do so.
2. The grey color is overriding the red color.

Check this.
https://jsfiddle.net/k9ryccjn/5/
