### ISSUE TITLE
Bug: semantic ui not displaying icon

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5710]
Hi,

According to documentation semantic ui made a complete port from font awesome 4.7.0. In this version there is an icon named cog, you can see it below:

http://fontawesome.io/icon/cog/

BUT for some reason semantic ui is not displaying this icon. ALL OTHER ICONS from FONT AWESOME that I could test are displaying correctly! Just this icon cog. The icon "cogs" is working fine but the icon "cog" is not. Below is the simplest example showing that this icon is not working. I display 3 icons, 2 are ok an one is not (which is the "cog").

http://quemfazsite.com.br/temp/criar-site123.php

Or I am doing something wrong again? I wouldnt be surprised with so many mistakes I already made here with semantic ui git.

**Comment by vinayakkulkarni** [comment]
can you try `setting icon` instead? it's the same icon afaik.

**Comment by batata004** [comment]
I could try the setting icon, not problem, I was not aware of it. BUT if you say in the documentation you did a complete port (exactly as stated there), it should be complete port. It took to me at least 15 or 20 minutes to realize the icon I wanted was not in the icon set semantic ui said ported from font awesome.

Anyway, I think this solution is again a tweak, just like most of the others solution you good guys posted to me in many other threads I opened. If this is not a complete port it should be said that some icons are missing or that they are already implemented in the semantic ui own's icon set

**Comment by vinayakkulkarni** [comment]
instead of visiting Font-Awesome website, kindly refer to Semantic-UI docs which will provide you with whatever your needs.

You can find All Icons in the [Icon Docs](https://semantic-ui.com/elements/icon.html), no need to visit Font-awesome website imho.

**Comment by batata004** [comment]
Thanks my friend, next time I will not check anymore fontawesome website!

**Comment by vinayakkulkarni** [comment]
I didn't mean to be rude but you could atleast check the official docs
before creating an issue which is totally unrelated to the framework
itself.

**Comment by batata004** [comment]
No no, you were not rude, I even clicked the +1 in your answer! I just think if you dont want stupid beginners like me opening stupid threads you should change the documentation. You should remove:

"Semantic includes a complete port of Font Awesome 4.7.0"

And replace it with:

"Semantic includes icons from Font Awesome 4.7.0 but their names may be different"

**Comment by Djuka** [comment]
This is still the case. In documentation it is specified:
Semantic includes a **complete** port of Font Awesome 5.0.8 designed by the FontAwesome team for its standard icon set.

Some of the icons I wanted to use from Font Awesome set are not available in Semantic UI. Can the docs be updated to specify this? The current definition is misleading and disappointing. I expected that I could use **ANY** icon from Font Awesome collection but that is not the case.

**Comment by hammy2899** [comment]
@Djuka SUI does in fact include a complete port of Font Awesome 5.0.8, keep in mind Font Awesome is currently up to 5.0.13
