### ISSUE TITLE
Disable Tab Key

### ISSUE THREAD

**Issue by Mark324** [Semantic-Org/Semantic-UI#5714]
I try to disable or block the tab key when I display a modal, but when modal is on screen and press the tab key input lost focus, I need that the event be disabled and focus return to input with the problem, I achieved to return the focus, but not block the tab event.

Somebody can help me with this topic.

Thanks.

**Comment by Banandrew** [comment]
Hi @Mark324, if I understood you correctly, it can be disabled using the HTML’s `tabindex="-1"` attribute applied to an input, as well as the modal component’s `autofocus: false` property during the modal’s JavaScript initialization. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
