### ISSUE TITLE
[Dropdown] Dropdown should not open when swiping to scroll on mobile devices.

### ISSUE THREAD

**Issue by merravid** [Semantic-Org/Semantic-UI#5715]
The Semantic-UI dropdown opens when you start a swiping action over the dropdown control when trying to scroll the page on a mobile device. This is undesirable as pages with several dropdowns will make for a bad UX when trying to scroll the page.

The generic select control handles this properly; it distinguishes between swipes and taps.

**Comment by Banandrew** [comment]
Hi @merravid, thanks again, we’re tracking it here: #5180.
