### ISSUE TITLE
Sidebar item can not use popup?

### ISSUE THREAD

**Issue by Dreampie** [Semantic-Org/Semantic-UI#5718]
![image](https://user-images.githubusercontent.com/3667080/29821621-37aad4ea-8c8e-11e7-8b3c-3e9b9a46c1ad.png)

**Comment by Banandrew** [comment]
Hi @Dreampie, that’s because tooltips use `:before` and `:after` pseudo classes, which allows them to work without JavaScript, but a menu’s item already uses pseudo classes, so there’s a conflict, and such use cases should be initialized with the `popup()` method.
