### ISSUE TITLE
[Label] Ribbon should not inherit center alignment from segment

### ISSUE THREAD

**Issue by maxhq** [Semantic-Org/Semantic-UI#5721]
The ribbons should not inherit the alignment from the parent segment.

E.g. the following code centers the ribbon which makes no sense visually:
([view on JSFiddle](https://jsfiddle.net/maxhq/8tmj0np8/))
```html
<div class="ui container">
  <div class="ui raised center aligned segment">
    <a class="ui red ribbon label">I want to be left aligned</a>
    <p>This is strange</p>
  </div>
</div>
```

**Comment by Peteypete** [comment]
This is still an issue for me. Is there a fix?

**Comment by ko2in** [comment]
You should wrap your content in another center aligned container, but not with ribbon together.

Example:
```
<div class="ui container">
  <div class="ui raised segment">
    <a class="ui red ribbon label">Overview</a>
    <div class="ui center aligned container">
      <p>This is it</p>
    </div>
  </div>
</div>
```
View the result on [JSFiddle](https://jsfiddle.net/6grbcLy4/1/).

If you don't prefer to adjust HTML, you can overwrite CSS for ribbon in center aligned container.

Example:
```
.ui.center.aligned .ui.label.ribbon {
  left: calc(-50% + 1em)
}
```
View the result on [JSFiddle](https://jsfiddle.net/nxjtps0o/).
