### ISSUE TITLE
Form Support in Modal Dialog

### ISSUE THREAD

**Issue by oarshad** [Semantic-Org/Semantic-UI#5724]
There should be a support to wrap a dialog's content and action divs in a form so that action buttons can be used as Form Submit or Reset buttons.
```
<div class="ui modal">
  <div class="header">Header</div>
  <form>
  <div class="content">
    <input type="text" />
  </div>
  <div class="actions">
    <button class="ui button" type="submit">Submit</button>
    <button class="ui button" type="reset">Reset</button>
  </div>
  </form>
</div>
```

There is a way around by using jQuery but that is not very intuitive.

**Comment by philrykoff** [comment]
Have you tried <form class="ui modal"> ? This is how I do it but I am not sure whether I have any custom CSS. Semantically, it definetly looks better to me.

**Comment by oarshad** [comment]
Thank you @philrykoff , I just tried it and it did work
