### ISSUE TITLE
No Scrolling for search result

### ISSUE THREAD

**Issue by Wasi-Zafar** [Semantic-Org/Semantic-UI#5726]
i am facing the issue regarding the search result i am using a modal and search inside it when i search the result go out of the the window i could't see it ! (add Scrolling feature in next version) or tell me the solution if any

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by vinayakkulkarni** [comment]
Closing this as it's been a week since OP replied. Will re-open once @Wasi-Zafar replies.

Also, @Wasi-Zafar for Usage related questions, kindly ask in [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) channel or [Discord Server](https://discordapp.com/invite/8rr9bsg)
