### ISSUE TITLE
[Site] horizontal scrollbars are styled oddly, due to style intended only for vertical

### ISSUE THREAD

**Issue by jayphelps** [Semantic-Org/Semantic-UI#5728]
Recently some default styling was added for vertical scrollbars, however it doesn't correctly style horizontal ones. The result is horizontal scrollbars are fatter than vertical ones.

![image](https://user-images.githubusercontent.com/762949/29950883-a9f49fb8-8e73-11e7-809e-6498b9397305.png)

https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/definitions/globals/site.less#L135-L138

Because it removes the webkit-appearance, we need to also set the height for horizontal ones. This can be done either by splitting the styles and using the [horizontal/vertical pseudo classes](https://webkit.org/blog/363/styling-scrollbars/) or just by putting a height in the same selector, since (currently) height placed here will only affect horizontal scrollbars, not vertical.

I would have just PR'd this, but I wanted to first confirm what to call the LESS variable? `@customScrollbarHeight`? Is this ambiguous?

**Comment by Banandrew** [comment]
Hi @jayphelps, sorry for the delay. `@customScrollbarWidth` has already been established, so I don’t think we have any other choice other than `@customScrollbarHeight`—both variables should probably use a similar naming pattern, but changing `@customScrollbarWidth` will break 3 previous versions.

Thank you for the contribution!
