### ISSUE TITLE
[Search] Add "Header"/"Footer" in dropdown results

### ISSUE THREAD

**Issue by Nide83** [Semantic-Org/Semantic-UI#5729]
It's possibile to add an header and/or footer (with buttons) in the dropdown results?

**Comment by Banandrew** [comment]
Hi @Nide83, the search component has got [the templates property](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L1295:L1448) that you can use to override the default templates.
