### ISSUE TITLE
[Dropdown] search class makes "onChange" fire two times

### ISSUE THREAD

**Issue by prudho** [Semantic-Org/Semantic-UI#5730]
Please take a look at this [JSFiddle](https://jsfiddle.net/28Lau7j8/6/).

If you select a value on the dropdown, the `onChange` event is fired, but if you click then elsewhere, the event is fired a second time. If you remove the `search` class, event will be fired only one time.

**Comment by Banandrew** [comment]
Hi @prudho, you can use `forceSelection: false` to disable the behavior.
