### ISSUE TITLE
comments componnet is not right to left

### ISSUE THREAD

**Issue by esma-eel** [Semantic-Org/Semantic-UI#5734]
Hi 
in semantic rtl 
there is everry thing ok in documantation 
but when u copy codes in has some trouble with downloaded and compiled version of rtl semantic 
 Semantic UI - 2.2.12 i downloaded and 
 Semantic UI - 2.2.6 in doc site 

`
/*semantic ui comment fixing*/

.ui.threaded.comments .comment .comments {
    margin: -1.5em 1.25em -1em 0;
    padding: 3em 2.25em 2em 0;
    box-shadow: 1px 0 0 rgba(34, 36, 38, .15)
}
/******/
.ui.comments {
    margin: 1.5em 0;
    max-width: 650px
}

.ui.comments:first-child {
    margin-top: 0
}

.ui.comments:last-child {
    margin-bottom: 0
}

.ui.comments .comment {
    position: relative;
    background: 0 0;
    margin: .5em 0 0;
    padding: .5em 0 0;
    border: none;
    border-top: none;
    line-height: 1.2
}

.ui.comments .comment:first-child {
    margin-top: 0;
    padding-top: 0
}

.ui.comments .comment .comments {
    margin: 0 .5em .5em 0;
    padding: 1em 1em 1em 0
}

.ui.comments .comment .comments:before {
    position: absolute;
    top: 0;
    right: 0
}

.ui.comments .comment .comments .comment {
    border: none;
    border-top: none;
    background: 0 0
}

.ui.comments .comment .avatar {
    display: block;
    width: 2.5em;
    height: auto;
    float: right;
    margin: .2em 0 0
}

.ui.comments .comment .avatar img, .ui.comments .comment img.avatar {
    display: block;
    margin: 0 auto;
    width: 100%;
    height: 100%;
    border-radius: .25rem
}

.ui.comments .comment > .content {
    display: block
}

.ui.comments .comment > .avatar ~ .content {
    margin-right: 3.5em
}

.ui.comments .comment .author {
    font-size: 1em;
    color: rgba(0, 0, 0, .87);
    font-weight: 700
}

.ui.comments .comment a.author {
    cursor: pointer
}

.ui.comments .comment a.author:hover {
    color: #1e70bf
}

.ui.comments .comment .metadata {
    display: inline-block;
    margin-right: .5em;
    color: rgba(0, 0, 0, .4);
    font-size: .875em
}

.ui.comments .comment .metadata > * {
    display: inline-block;
    margin: 0 0 0 .5em
}

.ui.comments .comment .metadata > :last-child {
    margin-left: 0
}

.ui.comments .comment .text {
    margin: .25em 0 .5em;
    font-size: 1em;
    word-wrap: break-word;
    color: rgba(0, 0, 0, .87);
    line-height: 1.3
}

.ui.comments .comment .actions {
    font-size: .875em
}

.ui.comments .comment .actions a {
    cursor: pointer;
    display: inline-block;
    margin: 0 0 0 .75em;
    color: rgba(0, 0, 0, .4)
}

.ui.comments .comment .actions a:last-child {
    margin-left: 0
}

.ui.comments .comment .actions a.active, .ui.comments .comment .actions a:hover {
    color: rgba(0, 0, 0, .8)
}

.ui.comments > .reply.form {
    margin-top: 1em
}

.ui.comments .comment .reply.form {
    width: 100%;
    margin-top: 1em
}

.ui.comments .reply.form textarea {
    font-size: 1em;
    height: 12em
}

.ui.collapsed.comments, .ui.comments .collapsed.comment, .ui.comments .collapsed.comments {
    display: none
}

.ui.threaded.comments .comment .comments {
    margin: -1.5em 1.25em -1em 0;
    padding: 3em 2.25em 2em 0;
    box-shadow: 1px 0 0 rgba(34, 36, 38, .15)
}

.ui.minimal.comments .comment .actions {
    opacity: 0;
    position: absolute;
    top: 0;
    left: 0;
    right: auto;
    -webkit-transition: opacity .2s ease;
    transition: opacity .2s ease;
    -webkit-transition-delay: .1s;
    transition-delay: .1s
}

.ui.minimal.comments .comment > .content:hover > .actions {
    opacity: 1
}

.ui.mini.comments {
    font-size: .78571429rem
}

.ui.tiny.comments {
    font-size: .85714286rem
}

.ui.small.comments {
    font-size: .9em
}

.ui.comments {
    font-size: 1em
}

.ui.large.comments {
    font-size: 1.1em
}

.ui.big.comments {
    font-size: 1.28571429rem
}

.ui.huge.comments {
    font-size: 1.2em
}

.ui.massive.comments {
    font-size: 1.71428571rem
}
`

i coppied these from docs css and then every thing goes like doc examples

**Comment by Banandrew** [comment]
Hi @esma-eel, I can’t seem to reproduce on `2.2.13`, I built an `rtl` version locally, here’s what I’m seeing:

![image](https://user-images.githubusercontent.com/6409354/30009016-9dae7f46-912d-11e7-9153-d85f4ce57cc3.png)

I’m not sure why you’re talking about `2.2.6` on the documentation, it’s `2.2.12` there. How do you use SUI?

**Comment by esma-eel** [comment]
i checked this
view-source:http://semantic.rtlcss.com/dist/semantic.rtl.min.css
2.2.6
i already downloaded semantic from here 
http://semantic.rtlcss.com/introduction/getting-started.html

yes its 2.2.12 
in main docs 
but i checked semantic rtl 
in these adresses

**Comment by Banandrew** [comment]
@esma-eel I know nothing about `MohammadYounes/rtlcss`, but you don’t need any external tools to use the RTL version of SUI—RTL is supported out of the box. Also, `2.2.6` is quite outdated.

Follow the `Getting Started` guide [here](https://semantic-ui.com/introduction/getting-started.html) to install the framework from NPM. During the installation, the installer will ask you whether you need the RTL version of the framework, answer yes, and that’s it. Set up your HTML as RTL afterwards, include the `semantic.rtl.min.css` from the installation folder, and it should work.

We’ve limited GitHub Issues to bug reports and feature requests to keep the board more manageable for maintainers, so I’ll be closing the thread, but please feel free to continue posting here, and I’ll try to help you in any way I can. You can also use our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI) to ask quick questions.
