### ISSUE TITLE
Angular 4 not working with Shape of Semantic Ui

### ISSUE THREAD

**Issue by fjoalland** [Semantic-Org/Semantic-UI#5736]
Hello,

I have a problem with the compatibility with Angular 4 and Semantic ui. I use the module Shape and it works but the design of the transition is different.
I use mdbootstrap too, but even if I remove it it's the same.

Do you know how to make compatible semantic ui with angular 4 ?

Thank you

**Comment by Banandrew** [comment]
Hi @fjoalland,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

Although, I think it’d be best to ask around Angular communities first.
