### ISSUE TITLE
[Table] Performance issues when celled style is used

### ISSUE THREAD

**Issue by proudh0n** [Semantic-Org/Semantic-UI#5747]
I observed that the table component causes some performance issues when using the celled class. This seems to happen with even small collections of items.

My computer specs are i5 6500, 16GB RAM, Intel HD GPU. I'm running Chrome 60.0.3112.113 (64 bit) on Ubuntu 14.04. I've tried on Firefox 55.0.2 (64-bit) on the same machine and I can't see the same issue, on Firefox runs fine

 I have created some fiddles to explain the issue.

[The first one](https://jsfiddle.net/alexviscreanu/sv3cxs34/) is a simple 'ui striped table' with 2500 items, seems to perform fine.

[The second one](https://jsfiddle.net/alexviscreanu/xL41f26c/1/) is a 'ui striped celled table' with only 100 items, it lags when scrolling.

[The third one](https://jsfiddle.net/alexviscreanu/r2hc1f21/2/) is the same 'ui striped celled table' with 2500 items but with the style changed in order to have a basic '1px solid red' border. It seems to work as fine as the first one with the celled class.

**Comment by proudh0n** [comment]
This issue seems to be fixed (at least I don't notice it anymore) on chrome 61.0.3163.79. I don't know in which way the celled class affected the performance but now seems fine.

**Comment by Banandrew** [comment]
@proudh0n Thank you. Let’s close it for now, but feel free to post here again if you’ll encounter it in the future.
