### ISSUE TITLE
[Docs][Rail] Add `font-size: inherit;` to segments in the “Size” section

### ISSUE THREAD

**Issue by AaricChen** [Semantic-Org/Semantic-UI#5748]
In the wiki, the rail size is same. did I missing somthing ?

![image](https://user-images.githubusercontent.com/11514546/30112387-ca79a196-9343-11e7-8c5a-793a32ce0a73.png)

**Comment by Banandrew** [comment]
Hi @AaricChen, sorry about the documentation, it could be better. As stated in the beginning of the page, the rail is always 300px, and different sizes simply change a rail’s `font-size`. Inspect a segment inside of a rail, find the `.ui.segment, .ui.segments .segment` rule, and change its `font-size` to `inherit` to see it.

**Comment by AaricChen** [comment]
thanks for your response.

**Comment by jlukic** [comment]
At some point in the past segments changed to `rem` so they wouldnt apply. Modified examples.
