### ISSUE TITLE
BUG: semanti ui not reseting form field correctly

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5751]
Hi,

The .reset function that you can call to a form is a very usefull one cause you can clear/reset all the state of the form to the initial page load state. It's very handy and has been implemented in browsers since early IE 6.0!

So clearly it's a very usefull thing and I use it a lot when user sends a form to avoid having to refresh the page.

This bug manifests itself not reseting the dropdown menu. It resets all other fields excetp dropdown. Here is a simple case where you can test this bug out:

http://quemfazsite.com.br/temp/teste-criar-site44.php

Select any thing in the dropdown menu, type anything in the input text, select anything in the radio/checkbox buttons... then after that click the RESET button. Everything will reset except the dropdown menu!

It's pretty simple to check this bug, hope the demonstration above helps!

**Comment by Banandrew** [comment]
Hi @batata004. SUI dropdowns are complex HTML groups, that’s why it uses its own methods to restore values (as well as the form validation component’s `reset()` and `clear()` methods). `HTMLFormElement.reset()` doesn’t work with the dropdown component, because it can’t.

**Comment by batata004** [comment]
Did you know that with jquery its possible to attach a reset event to the form? Maybe you could attach reset event to clear the dropdown, it would e nice! I think it's possile and would be a nice addition to the library making it more close to what other UI libraries does (at least jquery ui and bootstrap work very well clearing all form fields!)
