### ISSUE TITLE
[Search] Add autocompletion

### ISSUE THREAD

**Issue by rennokki** [Semantic-Org/Semantic-UI#5752]
I have a local list (the "source" variable in a .search() module, and i have added a list of cities.

The problem is when the user writes in that input, he/she may write the town with a lowercase letter and i need it to be inserted with an uppercase letter, EXACTLY how it is in my list, although i have set `selectFirstResult` to `true`.

This is the piece of code:
`$('#cities-search').search({
        source: cities,
        selectFirstResult: true,
        showNoResults: true
});`
where `cities` is my whole list of cities.

Can't figure it out how to make that work - when user inputs his/her town in other format than the one in the list, it should automatically update the input with the first result it gives.

**Comment by Banandrew** [comment]
Hi @wildramen, I didn’t understand what’s your issue with the component, could you please elaborate?

The search component does select a result in the search field regardless of what a user types in the field—`wildramen` will be `Wildramen` if `cities` stores it like that. `selectFirstResult` simply highlightes the first result without actually selecting it, did you expect `selectFirstResult` to update the search input with the first result?

**Comment by wildramen** [comment]
@Banandrew Indeed. I expected that the field would actually change its value after it was highlighted. Is there any kind of callback for this?

**Comment by Banandrew** [comment]
@wildramen The component doesn’t support any kind of autocompletion, so you’ll have to somehow work around it; maybe you’ll be able to utilize some of the existing callbacks.

**Comment by wildramen** [comment]
@Banandrew Lovely you helped me! Hope it will be a good enhancement in the feature. I'll work it out until the end, i'm glad you have answered me! :D
