### ISSUE TITLE
Pop doesnt work with latest release 2.2.12

### ISSUE THREAD

**Issue by amitpatil321** [Semantic-Org/Semantic-UI#5753]
I found that popup isnt working with v2.2.12 if you initialize popup on button. It works with <p> tag but not on button as shown in demos. I didnt tested it other elements. Below is the demo and my dev environment details.

Demo : https://jsfiddle.net/amitpatil321/cuzL3465/ and https://codepen.io/amitpatil/pen/yoWmyo

OS X Sierra
Chrome 60.0.3112.113

**Comment by Banandrew** [comment]
Hi @amitpatil321, you’re not using it correctly, please refer to the examples in the documentation to correct it.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
