### ISSUE TITLE
Dropdown elements have different font sizes for no reason

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5760]
Hi,

Please check this -> http://quemfazsite.com.br/temp/criar-site-erro.php

I have 2 dropdowns, one using a more "stylish" approach and another using the plain and simple `<select>` element. You can see that the element on the right (that uses the select) has a different font-size and a different line-height. Is there any way to overcome this?

I know I could use the element on the left and replicate it many times as I want instead of using the element in the right! BUT I have a problem: my company is developing an enterprise level system administration and in one single page it has 70 selects! Yeap! Using the approach in the left makes the final outputed HTML really big (at least 3x!), so I really would like to use the `select` approach. Of course, you could tell me to use only the `select` approach BUT in some cases I really need a searcheable dropdown (exactly the one in the left).

As far as I know I am using the `ui action input` parent (as you already taught me before) and I am using the same size `big` in both elements.

**Comment by Banandrew** [comment]
Hi @batata004, try removing `.big` from both dropdowns and adding it to `.ui.action.input` instead. Does it solve the issue?

**Comment by batata004** [comment]
WOW WOW WOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WORKED! http://quemfazsite.com.br/temp/criar-site-erro1.php

I have no idea why this works cause docs says clearly the size must be added to the element itself, not to the parent! My friend, I've figthing this for a long time , sometimes I even have to use line-height to make elements with equal size! Now I think you got it right in the bull's eye! I need to set the size to the parent of the elements!!!

Do you have any link where I can read the need to use .ui.input.action and why shouldnt I set sizes in the element's themselves?

Sorry for bringing this usage question again, but before I come here take your time I always search a lot and try to make it work to avoid spending other's people time

**Comment by Banandrew** [comment]
@batata004 It’s just something you need to remember when working with `.ui.action.input`, it sets the sizes for all of its child elements, so you don’t need to do it for every single child element inside of it. I don’t think the documentation mentions it, but I’m also not sure where we can put it—I’ll go through the docs tomorrow to see where it can be mentioned.

**Comment by batata004** [comment]
Hi my friend, thanks again. Here is the docs:

![image](https://user-images.githubusercontent.com/8988923/30240882-2903c5fe-954f-11e7-87ea-51108a20564d.png)

If has multiple buttons and each one has a size given in its own tag. Sincerally, this is the only place where I can find anything talking only about size.

I will remember what you said, I promise! I will not bring up this kind of problem anymore! But it would be nice to know why I should use `".ui.action.input"`. Will I always have to use that when I have buttons/inputs/selects... side by side and I want them to have the same size? Even if I have only 2 elements, will I have to give a common parent to those 2 elements and assign it `.ui.action.input`?

**Comment by batata004** [comment]
If I am not abusing your patience, I followed your instructions and indeed, if I give the size to the parent element it works perfectly! But for some reason buttons that have icons they are not increasing the size of the icon. Please take a brief example here -> https://www.frasesparavida.com.br/

![image](https://user-images.githubusercontent.com/8988923/30241021-e61be426-9551-11e7-913c-e6dbb79b4a9b.png)

Please see the blue arrow pointing to the search icon. It's very small, why this icon didnt grow up as the font of the other 2 elements grew?

**Comment by Banandrew** [comment]
@batata004 Yes. `.ui.action.input` is just a convenient container that not only sets the sizes, but also fixes borders and margins to allow the components to exist as a single thing. Without it, you’d have to write a custom replacement, which you can do as well.

The button issue is actually a problem, good catch. I won’t be labeling and reopening the issue—I was planning to work on SUI tomorrow anyway, so I’ll just bookmark the thread and open a PR then; the fix should be pretty straightforward.

**Comment by batata004** [comment]
Thanks @Banandrew  you were crystal clear! I will follow your advices and I am pretty sure now I will have a much better relationship with SU library! So far I've been fighting against it to set margins, sizes, font-sizes correctly but you made it very clear: set the size togetter with the container and not in the elements individually!

Have a nice weekend my friend and I hope you are not in the path of the hurricane, if so I wish you best luck!

**Comment by lubber-de** [comment]
Fixed since Fomantic-UI 2.5. Actually  SUI misses font sizes for dropdown, that is the main cause of this issue
See https://jsfiddle.net/bdv5q3r9/
