### ISSUE TITLE
wrong example in text alignment section for card 

### ISSUE THREAD

**Issue by smShakil** [Semantic-Org/Semantic-UI#5761]
There is a wrong example in 'text alignment' section for "card" in the documentation website. I think it's for 'floated content'.

**Comment by vinayakkulkarni** [comment]
Dear @smShakil,

Kindly raise any issues with Documentation in our Docs Repo: [Semantic-UI-Docs](https://github.com/Semantic-Org/Semantic-UI-Docs/issues) with a use-case.

Thanks.

**Comment by Banandrew** [comment]
Hi, no need to open another issue, I’ll open a PR today.
