### ISSUE TITLE
shape inside interval bug if other tab is refresh

### ISSUE THREAD

**Issue by jafarpagerjaya** [Semantic-Org/Semantic-UI#5763]
If other tab are refresh or open other webpage in another tab, a shape effect it will exec fast, but when look at the console its normally exec every 3 sec.

function shape() { 
	$('.ui.shape').shape('flip up');
        console.log(1);
}
setInterval(shape,3000);

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by jafarpagerjaya** [comment]
Ok, this the test case. After run it, please try to refresh another webpage on different tab or open new webpage with different tab, and back to test case it will exec fastly. http://jsfiddle.net/202dxxkw/2/

**Comment by Banandrew** [comment]
@jafarpagerjaya Thank you, this has nothing to do with SUI, please use other resources to understand why it’s happening and how to fix it.
