### ISSUE TITLE
[Dropdown/modal] Dropdown at the end of the modal makes modal scrollable

### ISSUE THREAD

**Issue by indreksiitan** [Semantic-Org/Semantic-UI#5769]
Opening a dropdown at the end of the modal makes the modal scrollable and hides part of the content below the viewport.

Example: https://www.dropbox.com/s/zop674q9l5rfui7/Screenshot%202017-09-10%2019.46.54.png?dl=0

**Comment by Banandrew** [comment]
Hi @indreksiitan, I can’t seem to reproduce, could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) to create a test case?

**Comment by indreksiitan** [comment]
Fiddle here: https://jsfiddle.net/v6096tr0/1/

**Comment by indreksiitan** [comment]
Found that this happens only if the body is "scrolling" - otherwise it's OK.

**Comment by Banandrew** [comment]
@indreksiitan Yes, you’re using `.scrolling.content`, we’re already tracking it here: #1340.
