### ISSUE TITLE
Link inside popup not working

### ISSUE THREAD

**Issue by willemevenwel** [Semantic-Org/Semantic-UI#5771]
Hi,

I have the following html:

<i id="info_file_police_clearance" class="help circle outline icon informationClassDark" data-html="<div>Please remember to <a id='declaration_info'>download the declaration</a>, and get it stamped at your nearest police station.</div>"></i>

Upon hover the popup is showing, but clicking on the a element in the html popup, the click event is not firing which has been bound to that id.

Please assist. How can I have an a element link work within a popup.

Regards,

Willem

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by willemevenwel** [comment]
My appologies, I pasted some code that was removed in the ticket.

https://jsfiddle.net/willemevenwel/vsajc65t/

**Comment by Banandrew** [comment]
@willemevenwel You’re initializing a jQuery object `$("#declaration_info")` on an element that doesn’t exist at the time, so `click()` method does nothing. You could either use the popup’s `onCreate()` callback:
```JS
onCreate: function ($module) {
  $("#declaration_info")
    .click(function () {
      window.location = "https://www.google.com"
    })
},
```
Or [use pre-existing HTML](https://semantic-ui.com/modules/popup.html#/usage) for your popup.
