### ISSUE TITLE
[Button] - Vedio background and sidebar menu issu

### ISSUE THREAD

**Issue by burslane** [Semantic-Org/Semantic-UI#5772]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**

**Result**

**Vedio background no play write after sidebar menu**

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by Banandrew** [comment]
Hi, your test case is empty—you can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by vinayakkulkarni** [comment]
Closing this till @burslane provides a test case.
