### ISSUE TITLE
[Docs] User Types Icons code missing "icon" class

### ISSUE THREAD

**Issue by ThaneshR** [Semantic-Org/Semantic-UI#5776]
In the icon page: https://semantic-ui.com/elements/icon.html

1. Under the **User Types** icon section
2. click **show code**
3. Note the **user circle** code is missing the **icon** class name.
4. Note the **user circle outline** code is missing the **icon** class name.
5. Note the **user outline** code is missing the **icon** class name.

![2017-09-11_164039](https://user-images.githubusercontent.com/7763181/30295706-86eab62a-970f-11e7-894a-252d46040673.png)

**Comment by Banandrew** [comment]
Hi @ThaneshR and thank you, I opened a PR to fix it.
