### ISSUE TITLE
the icon cannot display.

### ISSUE THREAD

**Issue by G-linch** [Semantic-Org/Semantic-UI#5782]
i use the simplest way by using SUI in my website. i just write the url in the link and scripts,everything goes well until i use the <i class="search icon"></i>.it does not work and i found the error:GET http://127.0.0.1:8000/static/css/themes/default/assets/fonts/icons.woff2 net::ERR_ABORTED, my staticfile-dir just like static/css/semantic.min.css, static/js/semantic.min.js.there is no file like the error shows.how can i fix it?

**Comment by Banandrew** [comment]
Hi @G-linch, you can, by putting icon files under that path. Unfortunately, that’s all I can say—it’s very difficult to give advice on issues that are specific to a developer’s local environment.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback, please use one of our other support resources:
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)

**Comment by G-linch** [comment]
thanks for reply,i follow your advice and fix it ,i search in the semantic.min.css and find the icon path which shows ../fonts/xxx.So i put the fonts in the right place, then it works.

**Comment by yanlee26** [comment]
Same here !! Can we fix it by configing the webpack?
