### ISSUE TITLE
[Icon] - Some icons are not found within the font files.

### ISSUE THREAD

**Issue by Leaninsider** [Semantic-Org/Semantic-UI#5783]
**Steps to Reproduce**
Create a "address card icon".

**Expected**
Should show the icon font, as it uses the correct "content-code".

**Result**
The included font does not support this content code.
**Temporary fix:** downloading **font-awesome** instead of using the included font file from semantic

**Comment by Banandrew** [comment]
Hi @Leaninsider, the icon in question seems to be working fine:
https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/themes/default/elements/icon.overrides#L110

Here’s a test case: https://jsfiddle.net/fjjhpckb/
