### ISSUE TITLE
[Card] Add "Primary" and "Secondary" colored cards

### ISSUE THREAD

**Issue by sethmoore** [Semantic-Org/Semantic-UI#5784]
It would be useful to have a colored card variant that has the accent in the primary and secondary brand colors.

**Comment by sethmoore** [comment]
@Banandrew Do you know how I can get this change reviewed and merged?  Or is there a particular cadence that these are looked at.

**Comment by Banandrew** [comment]
@sethmoore Unfortunately, there isn’t, and you’ll just have to wait for the maintainer to review it.

**Comment by lubber-de** [comment]
Available since https://github.com/fomantic/Fomantic-UI/releases/tag/2.4.0
