### ISSUE TITLE
[Grid] Deciding how many columns there will be for each device.

### ISSUE THREAD

**Issue by Newbie012** [Semantic-Org/Semantic-UI#5789]
If I want five columns in a row, then I'll have to mention it in my grid since 5 is not divisible by 16 without residual. So I did something like this:

    <div class="ui five grid"></div>

It works. But! I don't want five columns on every device. In smaller devices, the columns are too crowded. So I was wondering if there's an option to do something like this:

    <div class="ui five computer three tablet one mobile grid">

Or any other idea that can achieve my goal.

**Comment by Banandrew** [comment]
Hi @Newbie012, `.ui.five.grid` pattern doesn’t exist, you should be using `.ui.five.column.grid` instead. It’s CSS, and CSS cannot influence the amount of elements in HTML, only their width. See the `Responsive Grids` section in the grid’s documentation, maybe you’ll be able to use it. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
