### ISSUE TITLE
Focus is not shifting to another ui element after closing the modal.

### ISSUE THREAD

**Issue by PratikMoholkar** [Semantic-Org/Semantic-UI#5790]
I have one semantic button and one semantic input field. On click event on button, I am showing one pop up modal to user. After closing the modal, I need to shift focus to the input field. I use $('#myId').focus() to shift focus to input field. But focus always shifts to the button.
Example:
```
$('#myModalButton').click(function() {
$('#myModal').modal({
});
```
On closing modal I have shifted my focus to another input field i.e '#myId'. But it again shifts to 'myModalButton'.
How to achieve the above scenario?

**Comment by Banandrew** [comment]
Hi @PratikMoholkar,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
