### ISSUE TITLE
[Checkbox] '(in)determinate' does not change the checkbox state

### ISSUE THREAD

**Issue by tomsmalley** [Semantic-Org/Semantic-UI#5793]
This is visible on the example page:
https://semantic-ui.com/modules/checkbox.html#/examples

Click `set determinate` then `indeterminate`, or `set indeterminate` then `determinate`. No callbacks are called and the state remains the same. Callbacks are called when the checkbox is already in the desired state, e.g. `set determinate` then `determinate`.

The documentation indicates that `set determinate` and `determinate` should have the same behaviour (ability to change the state) except the latter will call callbacks:

https://semantic-ui.com/modules/checkbox.html#/usage

> indeterminate - Set as indeterminate checkbox
> determinate - Set as determinate checkbox

> set indeterminate - Set as indeterminate checkbox without callbacks
> set determinate - Set as determinate checkbox without callbacks

**Comment by Yrlish** [comment]
I'm having the same issue with the events. Trying to build a checkbox treeview, but there are no events firing at `onIndeterminate`. Also `.checkbox('indeterminate')` doesn't seem to work while `.checkbox('set indeterminate')` works.
