### ISSUE TITLE
[Modal] The `autofocus` property shouldn’t be focusing disabled inputs or inputs with negative `tabindex`

### ISSUE THREAD

**Issue by JosephCaillet** [Semantic-Org/Semantic-UI#5794]
If the first input (in a modal) has the disabled class, autofocus will still give it focus, which makes it fully editable until it loses focus.
A possible workaround would be to turn off autofocus, but it not a viable solution.

**Comment by lubber-de** [comment]
Prepared for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/704
