### ISSUE TITLE
[popup] width

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5795]
http://jsfiddle.net/WallaceMielniczki/ca0rovs3/80/ clique no nome do menu. Quero que o popup tenha um width fixo de 300px

**Comment by Banandrew** [comment]
Hi @WallaceMielniczki, two options:

* The easiest way is to simply set it with CSS.
* Include a popup’s markup outside of the menu’s, and use the `popup` property to point at the popup. Inspect the second school example on [this page](https://semantic-ui.com/collections/menu.html) for specifics. Here’s its initialization:
```JS
$('.school.example .browse.item')
  .popup({
    popup     : '.admission.popup',
    hoverable : true,
    position  : 'bottom left',
    delay     : {
      show: 300,
      hide: 800
    }
  })
```
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
