### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by Malleta** [Semantic-Org/Semantic-UI#5796]
Greetings,

Just add suffix **icon** on the classes.

![image](https://user-images.githubusercontent.com/23744520/30563067-e18562cc-9cc0-11e7-8206-33e2c6915501.png)

**Comment by Banandrew** [comment]
Hi @Malleta, it’s already been fixed with Semantic-Org/Semantic-UI-Docs#360. Closing as a duplicate of #5776.
