### ISSUE TITLE
[Modal] After showing and hiding a full-screen dimmer, the modal is no longer scrollable

### ISSUE THREAD

**Issue by indreksiitan** [Semantic-Org/Semantic-UI#5797]
After showing and hiding a full-screen dimmer when a long modal is shown, the modal is no longer scrollable.

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by Banandrew** [comment]
@indreksiitan Reminding you about the test case.

**Comment by indreksiitan** [comment]
Yes, I haven't forgotten, just been busy. I'll try to set up a public copy of my framework where it's easier for me to reproduce these issues.
