### ISSUE TITLE
Is it good to include the whole semantic folder in our git repo?

### ISSUE THREAD

**Issue by THPubs** [Semantic-Org/Semantic-UI#5798]
Hi, I'm trying to build an app with Semantic UI. Since I want a customized version, I installed `semantic-ui` package as a dev dependency and created the `semantic` folder inside my project folder. First I modify files under `src/site` directory to customize and build. I output the CSS into the dist folder (Inside semantic) and use it on my site.

Now my question is... is there any file or folder we need to ignore here? Or we should put everything in our repo?

**Comment by Banandrew** [comment]
Hi @THPubs, take a look at [this SO answer](http://stackoverflow.com/questions/32538811/semantic-ui-in-gitignore). Personally, I `gitignore` nothing.
