### ISSUE TITLE
[Dropdown] aligned to the right shifts slightly when 'loading' is enabled.

### ISSUE THREAD

**Issue by vdytsiak** [Semantic-Org/Semantic-UI#5800]
### Steps
Open 
https://codepen.io/anon/pen/OxNQjE or https://jsfiddle.net/n22dmm4L/15/ 
and compare how two dropdowns work

### Expected Result
Both dropdowns(left and right aligned should not shift when adding 'loading')

### Actual Result
The right aligned dropdown shifts slightly on 'loading' added.

### Version
2.2.13

### Testcase
Without React https://jsfiddle.net/n22dmm4L/15/
With React https://codepen.io/anon/pen/OxNQjE

**Comment by Banandrew** [comment]
Hi @vdytsiak, we don’t track issues with the React implementation in this repository; if you think it’s an issue with CSS, could you please create a test case without React? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by vdytsiak** [comment]
Shure, here it is - https://jsfiddle.net/n22dmm4L/15/

**Comment by Banandrew** [comment]
@vdytsiak Thanks, we’ll see if it makes sense to change it in the core. In the meantime, you can override it in `installation_folder/src/site/modules/dropdown.overrides`, these values seem to be working:
```CSS
.ui.loading.dropdown:not(.selection) > i.icon {
  height: 1em !important;
  width: 1em !important;
  margin-left: 0.572em;
}
```
Rebuild the framework after updating `dropdown.overrides`.

**Comment by vdytsiak** [comment]
Thank you for the quick response!

**Comment by lubber-de** [comment]
This is (also) fixed in the community fork Fomantic-UI by
https://github.com/fomantic/Fomantic-UI/pull/1807
