### ISSUE TITLE
Bug when using .scrolling inside menu

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5805]
Hi,

If I have a .menu item and it has too menu `.item`s inside I cant use the scrollbar of the browser to scroll down inside the items. So I read some people saying online that I should give `.scrolling` class to the `.menu` element. So I did that BUT a serious problem happens. You can see it here:

https://www.quemfazsite.com.br/temp/criar-123.php

The element on the left (A EMPRESA) works just fine when you hover your mouse (I didnt apply .scrolling to it) BUT if you do the same to the icon on the right (which has .scrolling to it) you see the menu gets all messed up.

I am doing something wrong?

**Comment by Banandrew** [comment]
Hi @batata004, apply `.scrolling` to `.ui.dropdown`, not a `.menu`. Also, you probably remember, but still—`.pointing` doesn’t work with `.scrolling`.

**Comment by batata004** [comment]
WORKED!!!!!! Sorry! I really didnt find documentation using scrolling class, I didnt know it should only be used in the dropdown element, I thought it should be in the menu element. Anyway, your solutino worked perfectly!!
