### ISSUE TITLE
sticky truncate the document/flashy document when using a sidebar

### ISSUE THREAD

**Issue by MazenDesigns** [Semantic-Org/Semantic-UI#5810]
my top sticky navbar was working perfectly until i introduced a right overlay sidebar. the problem is the sticky module somehow setting the height of the pusher incorrectly in a way which hide a small portion of the page bottom content. the sticky trigger this message " Context has padding, specifying exact height for container ".

in a very short document it create a flashy document when scrolling.

my html structure

```
<div class="ui left small sidebar vertical inverted menu overlay mobile-menu">
            ....
</div>
<div class="pusher" id="sticky-wall">
  <header class="ui sticky">
    ...
  </header>
 ...
</div>
```

js
```
$('.mobile-menu')
	.sidebar()
	.sidebar('setting', 'transition', 'overlay')
	.sidebar('attach events', '.mobile-menu-trigger');

$('.ui.sticky').sticky({
	context: '#sticky-wall',
});
```

i didn't change any css for the pusher and sticky expect the z-index property.

once i remove the sidebar structure it works properly again, any clues ?

**Comment by MazenDesigns** [comment]
by removing the ' overflow: hidden ' from the pusher solved the problem, any thoughts ?

**Comment by Banandrew** [comment]
Hi @MazenDesigns, sorry for the delay. I’ll take a look at it if you create a test case—you can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).
