### ISSUE TITLE
[Button] Prevent .ui.buttons from overflowing its container

### ISSUE THREAD

**Issue by nixxholas** [Semantic-Org/Semantic-UI#5815]
Was wondering if there are any solutions out there to remove the inline behaviour? 

<img width="1342" alt="screen shot 2017-09-28 at 9 53 06 pm" src="https://user-images.githubusercontent.com/4703269/30970425-ab04df1e-a497-11e7-9f8b-fd37f69bbeec.png">

Code:

```
<div class="ui buttons">
    <a asp-action="Drinks"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentSearch="@ViewData["CurrentSearch"]"
       asp-route-pageSize="@Model.PageSize"
       class="ui mini button @prevDisabled">
        Previous
    </a>
    @for (int i = 1; i <= @Model.TotalPages; i++)
    {
        if (i == Model.PageIndex)
        {
            <div class="ui mini button">
                @i
            </div>
        }
        else
        {
            <a asp-action="Drinks"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-page="@i"
               asp-route-currentSearch="@ViewData["CurrentSearch"]"
               asp-route-pageSize="@Model.PageSize"
               class="ui mini button">
                @i
            </a>
        }
    }
    <a asp-action="Drinks"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentSearch="@ViewData["CurrentSearch"]"
       asp-route-pageSize="@Model.PageSize"
       class="ui mini button @nextDisabled">
        Next
    </a>
</div>
```

**Comment by philrykoff** [comment]
From a UX perspective, I think it makes sense to show only the surrounding pages and first and last page, if they are not already shown. I display another button showing an ellipsis "..." in between those. If the user clicks that one, he is prompted for a page number.

SUI also has this problems for Tab buttons. Maybe we could find a generic solution which restricts the width to the available space and scrolls right if the cursor is positioned at the right margin; or traditionally with left and right carets.

**Comment by nixxholas** [comment]
@philrykoff This is an EAD, thus UX doesn't really matter much. Moreover, this implementation of a table view came from Bootstrap directly. These numbered buttons from bootstrap automatically break line in order to fit within the container it is restricted to.
