### ISSUE TITLE
[Dropdown] define default value on multiple dropdown

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5822]
http://jsfiddle.net/WallaceMielniczki/ca0rovs3/87/

**Comment by Banandrew** [comment]
Hi @WallaceMielniczki, sorry for the delay, there’s a couple of options:
* Initialize with `set selected`: `$('.ui.dropdown').dropdown('set selected', 2017)`.
* Initialize with JavaScript only using the `values` property, [here’s an example](http://jsfiddle.net/Banandrew/4vgvv2mb/). Version `2.2.12` is required.

**Comment by WallaceMielniczki** [comment]
Então, eu fiz esse script 
$('.ui.dropdown .item.active.selected, .ui.dropdown .item.active.filtered').each(function(){
            valorSelect = $(this).attr('data-value');
            $(this).parent().closest('.ui.dropdown').dropdown('set selected', valorSelect);
        });

ele funciona com outros selects menos com o multiple

**Comment by WallaceMielniczki** [comment]
??????

**Comment by WallaceMielniczki** [comment]
@Banandrew

**Comment by Banandrew** [comment]
@WallaceMielniczki I’m confused, what was your question?

**Comment by WallaceMielniczki** [comment]
eu quero que ao carregar a pagina o multiple select esteja pré selecionado

**Comment by Banandrew** [comment]
@WallaceMielniczki That I understood and answered. Could you please elaborate?
