### ISSUE TITLE
Remove borders between menu items

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5825]
Is it possible to remove borders between menu lines and just have padding between them? thanks and a question is when are you releasing new updates for semantic ui?

`<div class="ui large top menu attached">
            <a class="toc item custom_fullweight">
              <i class="sidebar icon"></i> Menu
            </a>

  <div class="right menu">
       <a class="item mobile hidden">gfhfhfh</a>
           <a class="item mobile hidden">fhgh</a>
            <div class="ui dropdown top left item mobile hidden" tabindex="0">
      Products<i class="dropdown icon"></i>
      <div class="menu transition hidden" tabindex="-1">
        <a class="item">ghhfg</a>
        <a class="item">ghgh</a>
        <a class="item">ghh</a>
      </div>
    </div>
                <div class="ui dropdown top left item mobile hidden" tabindex="0">
      Support<i class="dropdown icon"></i>
      <div class="menu transition hidden" tabindex="-1">
        <a class="item">gh</a>
		<a class="item">gh</a>
		<a class="item">th</a>
      </div>
    </div>
      <a class="item mobile hidden">Sign In</a>
  </div>
</div>`

**Comment by Banandrew** [comment]
Hi @jackttcoms, sorry for the delay, add a `.borderless` class to your menu. SUI releases aren’t on a schedule, please see [a list of releases](https://github.com/Semantic-Org/Semantic-UI/releases) to get a rough idea on when to expect another one.
