### ISSUE TITLE
Cannot load icon

### ISSUE THREAD

**Issue by ylto** [Semantic-Org/Semantic-UI#5826]
I use ember 2, with semantic UI installed on bower folder. Can't get the icon, any idea?

The error message:
Failed GET http://localhost:4200/assets/themes/default/assets/fonts/icons.woff2 
Failed GET http://localhost:4200/assets/themes/default/assets/fonts/icons.woff 
Failed GET http://localhost:4200/assets/themes/default/assets/fonts/icons.ttf

**Comment by Banandrew** [comment]
Hi @ylto, sorry for the delay, did you put these icon fonts under that path?
