### ISSUE TITLE
[Sidebar] Overflow set to none for "pusher" class when sidebar is closed.

### ISSUE THREAD

**Issue by AustinDavies** [Semantic-Org/Semantic-UI#5827]
I noticed that after I closed the sidebar on my site I was no longer able to scroll vertically anymore. After further investigating I found out that the pusher class was receiving CSS updates with one of those being an update to the overflow property which gets set to none. For an example of my site body structure here you go: 
```
<body>
...
<div class="ui vertical sidebar inverted menu">...</div>
<main class="ui site-container pusher" role="main">
    ... all site content is in this section ...
</main>
...
</body>
```

**Comment by bamsarker** [comment]
I'm having the same issue. Opening the sidebar adds the `pushable` class to the body, which enables the `.pushable>.pusher` styles, including `overflow: hidden;`.

I could removed the "pushable" class from the body, but if Semantic is adding it, it seems like Semantic should be removing it.

@AustinDavies I'm assuming the `pursher` class is a typo in your example above!

**Comment by AustinDavies** [comment]
@bamsarker Yes, the "pursher" class is a typo. I think part of the spec for the sidebar states that you need to have a pusher class in the same section in which your website content resides (most of the time this would just be the <body> as this is the safest/most logical fallback case).
