### ISSUE TITLE
Cannot install semantic-ui

### ISSUE THREAD

**Issue by betimer** [Semantic-Org/Semantic-UI#5828]
Cannot install semantic-ui package:
OS: Win 10
node: 8.6
npm: 5.4.2

C:\Repo\vcm-spa>npm install semantic-ui --save
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find
it in the tree.

> semantic-ui@2.2.10 install C:\Repo\vcm-spa\node_modules\semantic-ui
> gulp install

module.js:529
    throw err;
    ^

Error: Cannot find module 'gulp-header'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Repo\vcm-spa\node_modules\semantic-ui\tasks\collections\internal.js:21:18)
    at Object.<anonymous> (C:\Repo\vcm-spa\node_modules\semantic-ui\tasks\watch.js:51:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.2.10 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Xin\AppData\Roaming\npm-cache\_logs\2017-10-03T00_07_44_782Z-debug.log

**Comment by ylto** [comment]
Delete `node_modules` folder in semantic ui folder then `npm install`

**Comment by betimer** [comment]
@ylto Same result.
I even create a new proj, and do the npm i semantic-ui, got the same result.

Not sure should it be semantic-ui issue or node version issue (8.6.0)

**Comment by ylto** [comment]
Have your run `gulp build` in your `semantic/` folder after npm install?

**Comment by betimer** [comment]
@ylto It's before that stage. It failed when doing `npm install` 

`PS C:\Repo\learn-js\random\del6> npm i semantic-ui --save
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it i
n the tree.

> semantic-ui@2.2.13 install C:\Repo\learn-js\random\del6\node_modules\semantic-ui
> gulp install

module.js:529
    throw err;
    ^

Error: Cannot find module 'gulp-header'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Repo\learn-js\random\del6\node_modules\semantic-ui\tasks\collections\internal.js:21:18)
    at Object.<anonymous> (C:\Repo\learn-js\random\del6\node_modules\semantic-ui\tasks\watch.js:51:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
`

**Comment by ylto** [comment]
Try bower. `bower install semantic-ui`

**Comment by Banandrew** [comment]
Hi @betimer, sorry for the delay, I couldn’t reproduce on NPM `5.4.2`; `gulp-header` is in SUI’s dependencies, and I’m not sure why it’s not installing. Run `npm install gulp-header --save-dev` to see if fixes the issue.

**Comment by betimer** [comment]
@ylto bower seems can work which is weird. As the prod environment is using npm install

**Comment by betimer** [comment]
@Banandrew Thank you. I've tried `npm install gulp-header --save-dev` before install semantic-ui, same error result.

**Comment by betimer** [comment]
@ylto @Banandrew

**Comment by tal-botvinnik** [comment]
Hi guys, I know the issue is closed by I get the same error in Windows 10, when running `npm install semantic-ui`. 
I had another folder with semantic-ui correctly installed the same way. But when it is a new project, it outputs the error. I don't want to copy the node_modules and semantic folder by hand.
You mention that the error is npm cache, would you mind telling me how to clear it?
Thanks

**Comment by Banandrew** [comment]
@tal-botvinnik Hello, that would be `npm cache clean --force`.

**Comment by jeff3dx** [comment]
It's been a year since the last comment and the issue is closed, but this is still a problem with Semantic UI React (0.87.1) on Mac OS and Ubuntu.

**Comment by chinomnsoawazie** [comment]
I have done practically everything on this thread and none works!

**Comment by lubber-de** [comment]
@chinomnsoawazie Try the community fork https://fomantic-ui.com which works with gulp 4 and latest node versions as well
```
npm uninstall semantic-ui
npm install fomantic-ui
```
It still compiles to "semantic.css" and "semantic.js" and is backward compatible so far to semantic.

**Comment by essvega** [comment]
This really fixed the issue!

**Comment by timbog80** [comment]
> @chinomnsoawazie Try the community fork https://fomantic-ui.com which works with gulp 4 and latest node versions as well
> 
> ```
> npm uninstall semantic-ui
> npm install fomantic-ui
> ```
> 
> It still compiles to "semantic.css" and "semantic.js" and is backward compatible so far to semantic.

That doesn't really fix the issue though

**Comment by luisafvaca** [comment]
I had the same issue today, with 0.88.2 semantic-ui version in mac. 
I'm not sure but I resolved it install package using yarn instead of npm.

**Comment by Vic-rider** [comment]
> J'ai eu le même problème aujourd'hui, avec la version 0.88.2 sémantique-ui sous mac.
> Je ne suis pas sûr mais j'ai résolu le package d'installation en utilisant yarn au lieu de npm.

Moi aussi, mais j'ai toujour le même soucis avec semantic

**Comment by Vic-rider** [comment]
i'm just trying with https://fomantic-ui.com/ 

and it work with just one `npm install fomantic-ui --save`

**Comment by iamphoenix310** [comment]
Hi All, Use npm install semantic-ui-css
Works like a charm :)
