### ISSUE TITLE
One click to open dropdown opens dropdown but closes immediately afterwards

### ISSUE THREAD

**Issue by camueller** [Semantic-Org/Semantic-UI#5839]
Using a Javascript initialized dropdown one click top open the dropdown causes the dropdown to open but closes immediately afterwards.

In Chrome 60.0.3112.101 this happens for every click making it almost impossible to select an entry.
**Workaround:** A long-click to open the dropdown causes also the open followed by immediate close but then the mouse button is released the dropdown opens again and remains open.

In Firefox 55.0.2 this happens only sometimes, but sometime the dropdown opens and remains open.

Since I'm using Angular 4 I had to create a plukr instead of a jsfiddle.
I created a very basic example to reproduce the behavior:
https://plnkr.co/1cqcJC1nIRncsPBwAWJp

The HTML can be found in the file src/main.ts but also below:
```
<div class="field">
  <label>Days of week</label>
  <select class="ui fluid dropdown select-dayOfWeek" multiple="" [(ngModel)]="days">
    <option value="1" [selected]="days.indexOf('1') > -1">Monday</option>
    <option value="2" [selected]="days.indexOf('2') > -1">Tuesday</option>
    <option value="3" [selected]="days.indexOf('3') > -1">Wednesday</option>
    <option value="4" [selected]="days.indexOf('4') > -1">Thursday</option>
    <option value="5" [selected]="days.indexOf('5') > -1">Friday</option>
    <option value="6" [selected]="days.indexOf('6') > -1">Saturday</option>
    <option value="7" [selected]="days.indexOf('7') > -1">Sunday</option>
  </select>
</div>
```

**Comment by Banandrew** [comment]
Hi @camueller, could you please try initializing a dropdown on [pre-existing HTML](https://semantic-ui.com/modules/dropdown.html#/usage) instead of initializing it on a `select` element directly?

**Comment by camueller** [comment]
I created a new plunk using pre-existing HTML as shown in the example from [pre-existing HTML](https://semantic-ui.com/modules/dropdown.html#/usage). It shows the same close-after-open behavior:

https://plnkr.co/vneK8mHTUamMXbR3Kuzd

**Comment by Banandrew** [comment]
@camueller I know nothing about Angular, but if you initialize a dropdown with debugging enabled:
```JS
ngAfterViewChecked() {
  $('.ui.dropdown').dropdown({
    verbose: true,
    debug: true,
  });
}
```
`ngAfterViewChecked()` triggers the dropdown initialization over and over, which you probably don’t want to do—please see the console output after you enabled the debugging. This obviously interferes with the dropdown’s behavior, so I’m assuming it has something to do with Angular’s lifecycle, and I think it would be best to ask around Angular communities first.

I’ll close the issue for now, but feel free to post here again if you’ll find that SUI itself has a problem, and someone will reopen it in no time.

**Comment by camueller** [comment]
You are right - this is related to Angular'S life cycle. It works without problems if dropdown initialization is done in AfterViewInit. The updated plunkr https://plnkr.co/1cqcJC1nIRncsPBwAWJp shows this as well.
