### ISSUE TITLE
Dimmer hover issue

### ISSUE THREAD

**Issue by alihalabyah** [Semantic-Org/Semantic-UI#584]
The dimmer hover event will crash after hovering many times.

Check the example here: http://semantic-ui.com/modules/dimmer.html#/examples

**Comment by bj1612** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>dimmer</title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css">
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
</head>
<body>
<div class="container">
<script type="text/javascript">
	$('.event.example .image').dimmer({on: 'hover'});
</script>
	<div class="ui medium image">
	  <div class="ui dimmer">
	    <div class="content">
	      <div class="center">
	        <h2 class="ui inverted header">Title</h2>
	        <div class="ui primary button">Add</div>
	        <div class="ui button">View</div>
	      </div>
	    </div>
	  </div>
	  <img class="ui image" src="img/car-spa.png">
	</div>
	<div class="ui circular image">
	  <div class="ui dimmer">
	    <div class="content">
	      <div class="center">
	        <div class="ui small primary button">Add</div>
	        <div class="ui small button">View</div>
	      </div>
	    </div>
	  </div>
	  <img src="img/car-spa1.png">
</div>
</div>
</body>
</html>

i copy the code from the semantic-ui official website
when i use the code which is available on the semantic-ui use it doesn't work
please help me i want dimmer on hover...
https://semantic-ui.com/modules/dimmer.html#/examples
![screenshot 91](https://user-images.githubusercontent.com/26135202/34327197-3ed49b18-e8e4-11e7-9d59-d13edae08a28.png)
