### ISSUE TITLE
Make text bold with bold div

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5841]
With Semantic is it possible to make it so that instead of writing custom css for text to make it bold you can add the class bold please can you let me know if this is already possible or if you think this is a good idea (probably not the first to think of it) thanks

**Comment by Banandrew** [comment]
Hi @jackttcoms, there’re no classes to allow that out of the box, but you can add your own; in the end, it’s just CSS, and SUI is designed to be extended—please refer to [the theming guide](https://semantic-ui.com/usage/theming.html).
