### ISSUE TITLE
Changing Site Theme is not possible

### ISSUE THREAD

**Issue by ylto** [Semantic-Org/Semantic-UI#5842]
Hi, I use semantic for my vue project. Changing Site theme to something else is not possible, meanwhile changing theme for each element is possible. What's wrong with my setup?

Node: 8.6.0

**Comment by Banandrew** [comment]
Hi @ylto, what are you changing it to?

**Comment by ylto** [comment]
@Banandrew material, amazon, github, etc. all of them didnt work.

**Comment by Banandrew** [comment]
@ylto No. I can’t reproduce, the theme changes are applied correctly. The changes are subtle, are you sure you’re not missing anything? For instance, `material` theme changes the font from `Lato` to `Roboto`:
https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/themes/material/globals/site.variables#L10
Could you please change the `site`’s theme to `material` and check if the font was changed using the developer tools?

**Comment by ylto** [comment]
@Banandrew It changed! But the button still in default theme. Can't it change to material too? The theme is set globally afterall.

![selection_066](https://user-images.githubusercontent.com/1755417/31314834-c3c3f32e-ac34-11e7-97bb-20af3e981c20.png)

**Comment by Banandrew** [comment]
@ylto `site` doesn’t change a theme for all components. When you change a component’s theme, you change a theme only for that component, so changing it for `site` won’t affect the `button` component—only `site`—and `site` is a component like any other that sets global things like typography, colors, and so on.

Also, please keep in mind that a theme might be existing only for a set of components, for example, if you look at [pulsar](https://github.com/Semantic-Org/Semantic-UI/tree/master/src/themes/pulsar/elements) and open `elements` category, you’ll see that `pulsar` has got a theme only for the loader component, so it’s pointless to use `pulsar` for the button component. And that’s how you figure out if a theme has got styles for a component.

Closing the issue as resolved, but please feel free to post here if you have more questions.
