### ISSUE TITLE
set selected option with api call in dropdown

### ISSUE THREAD

**Issue by jaswinderahuja** [Semantic-Org/Semantic-UI#5844]
('.remote.ui.dropdown').dropdown({
apiSettings: {
url: '/api/call'
},
filterRemoteData: true
});

response format : 

{
 "success":true,
  "results":[
                {:value=>"1", :name=>"first value"},
                {:value=>"2", :name=>"second value"}         
       ]
}

$('.remote.ui.dropdown').dropdown('refresh');
$('.remote.ui.dropdown').dropdown('set selected',2);

it is not working... if I am understanding somwthing wrong please help me to understand the same. as I am trying to select the value on when page loaded  and also the list generated is from api for user to change if value given is not correct.

**Comment by Banandrew** [comment]
Hi @jaswinderahuja,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by coder8keyboard** [comment]
It looks like it's a bug. Set selected behavior does not work with API data. Works perfectly on non-api data.
