### ISSUE TITLE
Something is wrong with grid?

### ISSUE THREAD

**Issue by nikola1970** [Semantic-Org/Semantic-UI#5847]
Hello, i just seems to have a weird bug.

I downloaded gird.min.css from your website, added it to my html page but when I make this:

```
<div class="ui grid">
        <div class="column">1</div>
        <div class="column">2</div>
        <div class="column">3</div>
        <div class="column">4</div>
        <div class="column">5</div>
        <div class="column">6</div>
        <div class="column">7</div>
        <div class="column">8</div>
        <div class="column">9</div>
        <div class="column">10</div>
        <div class="column">11</div>
        <div class="column">12</div>
        <div class="column">13</div>
        <div class="column">14</div>
        <div class="column">15</div>
        <div class="column">16</div>
    </div>
```

Those 'columns' do not stack inline, 5 of them went to the second line and I have no idea why (even if I add classes to columns like 'one wide column' and if I add additional call of 'row' then I lose side paddings)? left and right paddings of those columns are taking an extra space and I cannot place them all in one row.

**Comment by Banandrew** [comment]
Hi @nikola1970, what are you seeing, could you please post a screenshot? What are the steps to reproduce the issue aside from creating a 16 column grid?

**Comment by nikola1970** [comment]
Steps to reproduce it are like this: 

Get the grid.css from SemanticUI, make index.html and load grid.css in, and then paste code snippet from my previous post.

here is the screenshot uploaded on imgur:
[https://imgur.com/a/wkfbx](url)

**Comment by Banandrew** [comment]
@nikola1970 Sorry for the delay, you also need the reset component, which is basically the latest version of [Normalize.css](https://github.com/necolas/normalize.css/), although, the component does set some additional styles:
https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/definitions/globals/reset.less#L20-L38

**Comment by nikola1970** [comment]
Thank you @Banandrew !

**Comment by Banandrew** [comment]
Closing as resolved.
