### ISSUE TITLE
[Header][Icon] Link with Icon in Sub Header Causes Icon To Have Extra Right Margin Space

### ISSUE THREAD

**Issue by fatalerrorx** [Semantic-Org/Semantic-UI#5849]
For some reason an icon inside a link in a sub header will have extra space in the right margin. See below example:

https://jsfiddle.net/g8tdvtpe/4/

**Comment by Banandrew** [comment]
Hi @fatalerrorx, not sure about the reasoning behind it, we’ll investigate to make sure we’re not breaking anything else, but you can wrap the text in a `span` as a temporary fix:
```HTML
<a>      
  <i class="user icon"></i>
  <span>User</span>
</a>
```

**Comment by fatalerrorx** [comment]
Thanks!

**Comment by lubber-de** [comment]
Fixed in the community fork https://github.com/fomantic/Fomantic-UI without the need for an extra wrapper
See https://jsfiddle.net/lubber/Ldc9s07y/
