### ISSUE TITLE
More footer options like positioning etc

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5852]
https://www.google.com/chrome/browser/desktop/index.html

For Future Version

The footer on that website has options where you can have bits of the right bits on the left whereas with semantic its a bit more restricted where you can have it centered, left, right but not in different parts at the same time but let me know if I'm wrong and you can do this thanks

**Comment by Banandrew** [comment]
Hi @jackttcoms, you can use the grid to position elements.
