### ISSUE TITLE
[Responsive layout] - conflict on "large monitor only" classes

### ISSUE THREAD

**Issue by Pamzus** [Semantic-Org/Semantic-UI#5853]
When using "large monitor only" classes to display element (let's say segment or button) only on resolution from 1200-1920px, element inherits font-size properties. 

Using default theme you can not have segment visible only on large monitor and keeping default 1rem font-size.

https://jsfiddle.net/zadxdvs3/

`<div class="ui segment large monitor only"></div>`
also gets
`
.ui.large.segment, .ui.large.segments .segment {
    font-size: 1.14285714rem;
}
`

Thanks!

**Comment by Pamzus** [comment]
Found I can change variable when building theme in globals/site.variables
/*-------------------
        Sizes
--------------------*/
/*@largeSize       : (16 / 14);*/
@largeSize       : (14 / 14);

Still think different names should be used, it is unnecessary conflict.

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by Pamzus** [comment]
I've edited post with test fiddle.

**Comment by Banandrew** [comment]
@Pamzus If I didn’t miss anything, visibility classes exist only for the grid component, so I’m assuming you reimplemented them for general use, is that correct?

**Comment by Pamzus** [comment]
So if I understand corectlly visibility classes should be used on row and column?

**Comment by Banandrew** [comment]
@Pamzus Yes, also on a `.grid` itself.

**Comment by Pamzus** [comment]
@Banandrew, thank you for your help and info.

Cheers!
