### ISSUE TITLE
Dropdown open again and again when click for closing while open.

### ISSUE THREAD

**Issue by awaistechverx** [Semantic-Org/Semantic-UI#5855]
I am using Semantic-UI Multiple select dropdown, on web PC/Laptop its working like charm but on mobile its behaving strange, when i click for open it opens fine but when i click again for close, it open again and never close.
Any one have idea how to fix it? you can view this over [here](https://cruiserhandlebars.com/) when you open side menu on mobile device.

**Comment by Banandrew** [comment]
Hi @awaistechverx, this is a known issue: #3304. We might also be tracking it in another thread that I can’t find right now, as it behaves similarly on Chrome for Android.
