### ISSUE TITLE
Name values in form validation

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#5857]
Hi,

I use multiple input of the same name
Do not want to use the value of "name".
We can take a different value base.

For example:
<input **name="address"**>
instead:
<input name="address" **data-name="address"**>

```
var Validate = Form.form({
	inline: true,
	fields: {
		address: {
			identifier: 'address',
			rules: [
				{
				type: 'empty',
				prompt: 'Lütfen adınızı giriniz.'
				}
			]
		}
	}
});
```

instead:
```
var Validate = Form.form({
	inline: true,
	fields: {
		[data-name="address"]: {
			identifier: '[data-name="address"]',
			rules: [
				{
				type: 'empty',
				prompt: 'Lütfen adınızı giriniz.'
				}
			]
		}
	}
});
```

**Comment by Banandrew** [comment]
Hi @oguzhansari, I’m confused, what’s your question?

**Comment by joeyslack** [comment]
@oguzhansari Maybe you don't know, but this feature already exists. You need to use the attribute: `data-validate`. When you specify data-validate you can write your validation like normal, just specify the name you used in the data-validate attribute. See https://semantic-ui.com/behaviors/form.html#/examples#using-server-name-attributes
