### ISSUE TITLE
Multiple columns in the list

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5858]
With the list element i know you can use a grid to achieve this but you can't put a column inside another column so is it possible in the future for you to have multiple lists like you do so segments and have it where there are two columns like the example below thanks

http://jsfiddle.net/karlikdesign/fmroxyLy/

**Comment by Banandrew** [comment]
Hi @jackttcoms, grids can be nested, but I think it’s already possible with something like that: https://jsfiddle.net/Banandrew/wwj8m2cr/ Does that resolve your issue?

**Comment by jackttcoms** [comment]
thanks that worked fine

**Comment by Banandrew** [comment]
Closing as resolved.
