### ISSUE TITLE
[CSS][HTML] <html> tag container is limited to browser viewport size.

### ISSUE THREAD

**Issue by josedarioxyz** [Semantic-Org/Semantic-UI#5860]
The  **semantic.css** file limits a document's < html > tag container size to a user's browser viewport size. This causes page elements to spill outside of the < html > tag container when the total page content is larger than the viewport.

The issue can be observed by editing the following snippet in **semantic.css** from this:

```
/*******************************
             Page
*******************************/

html,
body {
  height: 100%;
}
```

to this:

```
/*******************************
             Page
*******************************/

html,
body {
  height: 100%;

  border-width: 2px;
  border-style: solid;
  border-color: red;
}
```

My suggestion for a fix is that the original snippet be replaced with:

```
/*******************************
             Page
*******************************/

html,
body {
  min-height: 100%;
}
```
Replacing `height: 100%` with `min-height: 100%` ensures the < html > tag container is always at least as big as the viewport without limiting its size in the case of longer, scrollable pages.

**Comment by Banandrew** [comment]
Hi @josedarioxyz, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).
