### ISSUE TITLE
jQuery?

### ISSUE THREAD

**Issue by lordjbs** [Semantic-Org/Semantic-UI#5869]
Semantic cannot find jQuery even when added.
`<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script><script type="text/javascript" src="semantic/dist/semantic.min.js"></script>`
anything i can do?

**Comment by Banandrew** [comment]
Hi @lordjbs, what’s the status of jQuery’s request?

**Comment by lordjbs** [comment]
uhm, I don't get any error, so I don't know what to say..

**Comment by Banandrew** [comment]
@lordjbs I’m assuming it’s `200`, but still, please open developer tools, go to the `Network` tab, reload the page, find the jQuery request and see its status there. Also, please check if `jquery-3.2.1.min.js` is above the `semantic.min.js`.

**Comment by lordjbs** [comment]
Tried browser and stuff, i guess its electron messing around. Thanks :D

**Comment by Banandrew** [comment]
Closing as resolved then.
