### ISSUE TITLE
Unexpected "shadows" in Chrome 61.0.3163.100

### ISSUE THREAD

**Issue by rodrigopires** [Semantic-Org/Semantic-UI#5870]
Since the Chrome's update to version 61, these "shadows" started to show under my tables. (see print below)

The same page works perfectly in other browsers (FF, Edge etc), without these shadows. So it's a Chrome thing.

Anyone know if there's a fix or workaround for it? I'm not sure if it's a Chrome bug or new implementation...

Thank you!

![Chrome Bug print](http://clfilm-aspnetcore.azurewebsites.net/assets/bug-shadow-semantic.png)

**Comment by Banandrew** [comment]
Can also be seen on SUI’s documentation.

**Comment by rodrigopires** [comment]
@Banandrew is this a Semantic-UI bug, or a Chrome bug?

**Comment by Banandrew** [comment]
@rodrigopires I don’t know, we’ll investigate.

**Comment by fridzema** [comment]
I had this problem a long time ago and temporally fixed it at the time with disabling hardware acceleration in chrome.

**Comment by rodrigopires** [comment]
Updated Chrome today to the newest version (62.0.3202.75), and the shadows are no longer being displayed.
