### ISSUE TITLE
Tooltip with Multiple Section

### ISSUE THREAD

**Issue by kieykouch** [Semantic-Org/Semantic-UI#5871]
I need to add tooltip into a selected value from dropdown. 
When a user selects a dropdown, if a user hovers around the selected content, it should display tooltip.
I tried adding (data-content="Add users to your feed" ) into <i> from multiple select dropdown, it doesn't display tooltip at all.

https://jsfiddle.net/ub6y4gto/1/

https://semantic-ui.com/modules/popup.html
https://semantic-ui.com/modules/dropdown.html#multiple-selection

**Comment by Banandrew** [comment]
Hi @kieykouch, sorry for the delay, here’s an example: https://jsfiddle.net/whsufur5/ If you have more questions, I’ll be happy to answer them in this thread.
