### ISSUE TITLE
Adjoining classes. Attribute selectors with *= are slow.

### ISSUE THREAD

**Issue by johnunclesam** [Semantic-Org/Semantic-UI#5875]
In something like this:

`.ui[class*="very basic"].table:not(.sortable):not(.striped) td:first-child, .ui[class*="very basic"].table:not(.sortable):not(.striped) th:first-child`

in many editors I receive this warning:

*Don't use adjoining classes. Attribute selectors with *= are slow!*

Is this true?

How this can impact in my project performances?

**Comment by Banandrew** [comment]
Hi @johnunclesam, they can be, but the difference is negligible. [Somebody did a performance test 3 years ago](https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/), and the difference between more and less efficient CSS selectors was only 35 milliseconds of rendering time on average (for desktop browsers), so you shouldn’t be worrying about it. There’s also a response from one of the WebKit engineers that elaborates on the issue.
