### ISSUE TITLE
[Modal] should disable keyboard input for hidden components

### ISSUE THREAD

**Issue by chdh** [Semantic-Org/Semantic-UI#5876]
#733 is an old Confirmed Bug issue from 2014 for this problem. It has been closed because there was no idea of how to fix it. I have found and tested a [solution](https://github.com/Semantic-Org/Semantic-UI/issues/733#issuecomment-337742305) and documented it with the old issue.

**Comment by Banandrew** [comment]
Hi @chdh, thanks, I reopened and milestoned the issue.
