### ISSUE TITLE
[Segment] Add .equal.width.horizontal.segments

### ISSUE THREAD

**Issue by flashspys** [Semantic-Org/Semantic-UI#5878]
As you can see in [this jsbin](http://jsbin.com/zobiriseyi/edit?html,output) it seems that `ui horizontal segments` does not support `equal width`. I think it should. 
Is there a workaround to support it right now?

**Comment by flashspys** [comment]
Here is a CSS snippet to support `<div class="ui horizontal segments equal width">`
```
.ui.horizontal.segments.equal.width > .ui.segment {
    flex-grow:1;
    width:0;
}
```

**Comment by JPustkuchen** [comment]
Still makes a lot of sense! Thanks for the snippet. Perhaps this could be done in fomantic?

**Comment by lubber-de** [comment]
@JPustkuchen 
I created a PR at the community fork https://fomantic-ui.com to support that 😉 
See https://github.com/fomantic/Fomantic-UI/pull/1969

The only thing left was a `width:100%` as the flex setting is already available for horizontal segments.
