### ISSUE TITLE
Websites built with the framework

### ISSUE THREAD

**Issue by christoffertyrefors** [Semantic-Org/Semantic-UI#588]
I love this framework, and I'm using it for a couple of projects. But, since it's new it's kind of hard to find inspiration from pages other than the official one.

SO, this morning I put together a small app for publishing websites that are built with the framework. The url is http://www.builtwithsemantic.com

It's very simple and alpha, but I do believe that the framework will benefit from this kind of site (wheter it's this one or if someone want's to build something better) to spread the word and "scale up".

Ps.
I'm new to Github, so please correct me if this is the wrong place
ds.

**Comment by saikrishnadeep** [comment]
Just wanted to update that this website is down.
