### ISSUE TITLE
Appending a Dropdown yields `onChange` not to work.

### ISSUE THREAD

**Issue by allidoisace** [Semantic-Org/Semantic-UI#5880]
Selecting an option from 1 dropdown will append a new dropdown menu filled with different choices. Since the page loads once, an event must be made to trigger this new dropdown menu. Any normal `action` or custom action works (ie. `function (text, value)`), however if you try to use `onChange` with or without an action alongside, it cannot even run a `console.log()`. Not sure if this is limitation or maybe something that was not thought of, but I assumed it would work since I am creating a replica of the previous dropdown, but with different values.

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).
