### ISSUE TITLE
Bottom Fixed Menu issue

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5881]
Im trying to place a borderless menu on the bottom of the site but it wont work as soon as i remove the borderless class it works fine.

//Works
```
<div class="ui bottom fixed menu">
  <div class="item">
    <img src="/images/logo.png">
  </div>
  <a class="item">Features</a>
  <a class="item">Testimonials</a>
  <a class="item">Sign-in</a>
</div>
```

//No Work
```
<div class="ui bottom borderless fixed menu">
  <div class="item">
    <img src="/images/logo.png">
  </div>
  <a class="item">Features</a>
  <a class="item">Testimonials</a>
  <a class="item">Sign-in</a>
</div>
```
https://jsfiddle.net/8du65567/

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by jackttcoms** [comment]
https://jsfiddle.net/8du65567/

**Comment by Banandrew** [comment]
@jackttcoms Thank you. That specific rule uses an attribute selector with a specific word order:

https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/definitions/collections/menu.less#L1737-L1745

Change it to `.ui.borderless.bottom.fixed.menu`, and it will work. The issue has been discussed before if you’re interested in it: #396, #5484.
