### ISSUE TITLE
[Dropdown] preserveHTML is useless

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5885]
Hello. According to official documentation HTML inside of `.item` should be preserved after a value selection, but it's actually don't. Documentation says:
>Whether HTML included in dropdown values should be preserved. (Allows icons to show up in selected value)

But my HTML code inside of `.item` never get copied into a `.text` element. `preserveHTML` works only for an icons inside of `.item`, but should work for any HTML code inside of it. 

For example:

```html
<div class="text">
  <img src="/assets/img/flags/ru.svg" alt="RU">
  <span class="currency-rub"></span>
  - Russian ruble
</div>
<i class="dropdown icon"></i>
<div class="menu transition hidden" tabindex="-1">
  <div class="item" data-text=" - Japanese yen"> <!-- data-text attribute can be removed now since we already have label needed inside of each .item -->
    <img src="/assets/img/flags/jp.svg" alt="JPY"> <!-- THIS SHOULD BE INSIDE OF <div class="text"> ABOVE -->
    <span class="currency-jpy"></span> <!-- DONT FORGET ABOUT THIS -->
    - Japanese yen <!-- THIS ONE TOO -->
  </div>
</div>
```

Dropdown will be way more intuitive and easy to use after implementing this functionality. 

Regards,
Andrew.

**Comment by JamesJGoodwin** [comment]
Well, my issue has been successfully resolved with [description](https://semantic-ui.com/modules/dropdown.html#description). 

```html
<div class="item">
  <div class="description">
    <img src="/assets/img/flags/jp.svg" alt="JPY">
    <span class="currency-jpy"></span>
  </div>
  <span class="text">Japanese yen</span>
</div>
```

Since it's resovled I'm closing this topic, but if you still have any comments or suggestions - please feel free to mention me here. Have a nice day!

**Comment by Banandrew** [comment]
Hi @JamesJGoodwin, that doesn’t seem to be the case from what I’ve just tested with SVG. I’ll take a look at it if you create a test case from [this forkable JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by JamesJGoodwin** [comment]
@Banandrew just found the reason for what is happening. You need to remove `data-text` attribute in order to make `preserveHtml` option works.
