### ISSUE TITLE
[Step] - No se respeta el limite de un DIV

### ISSUE THREAD

**Issue by gabri231** [Semantic-Org/Semantic-UI#5886]
**Steps to Reproduce**
Visualmente no funciona correctamente la adaptación de la pantalla. 
Adjunto archivo donde se ve que no se respeta la ubicación dentro de un "DIV".

**Expected**
Debería ser responsive.
**Result**
Traspasa el limite y se visualiza sobre otros elementos

**Testcase**
adjunto img
![semantic](https://user-images.githubusercontent.com/14350442/31865647-874a7f82-b772-11e7-9b01-425cc44af567.PNG)

http://jsfiddle.net/rduvhn8u/1/

**Comment by Banandrew** [comment]
Hi @gabri231, thank you, but we’re already tracking it here: #4880.

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/397 and supposed to be part of Fomantic-UI 2.7.2
