### ISSUE TITLE
Issue with Modal in IE 9

### ISSUE THREAD

**Issue by PurnimaCIC** [Semantic-Org/Semantic-UI#5889]
Hi,

I am getting error 'Modal Undefined' when trying to invoke in IE 9 browser.The same is working in other browsers.Could you please let me know if there is any fix specific to IE 9

**Comment by vinayakkulkarni** [comment]
Dear @PurnimaCIC,

SUI supports IE 11+, take a look here: https://github.com/Semantic-Org/Semantic-UI#browser-support
