### ISSUE TITLE
Add data-* to dropdown select options

### ISSUE THREAD

**Issue by Galeups** [Semantic-Org/Semantic-UI#5895]
Hello.I have problem  of adding data-* to select options.
The task of displaying a block depends on the choice of the select option.
I can not use value ((
I need data-* or class of style, but all attributes clear (

Tnank`s )

**Comment by Banandrew** [comment]
Hi @Galeups, could you please show your markup?

**Comment by Galeups** [comment]
Hi @Banandrew, of course.

html:
```
        <div class="form__field">
          <label class="form__label ">Custom select:</label>
          <select name="select" class="form__select js-select">
            <option value="1">Option 1</option>
            <option value="2">Option 2</option>
            <option value="3">Option 3</option>
            <option value="4">Option 4/option>
          </select>
        </div>
```

JS:
`$('.js-select').dropdown();`

I need ident selected option, to use in styles hidden or visible next block.
Selects In semantic-ui is very good! ))

**Comment by Banandrew** [comment]
@Galeups Заметил, что вы, кажется, говорите по-русски. Я не очень понял, то вы имели в виду, когда сказали, что он «очищается». Удаляется? Если вам нужно, чтобы `data-item` был у каждого `.menu .item`, то можно инициализировать компонент на [уже существующем HTML](https://semantic-ui.com/modules/dropdown.html#/usage), что-то типа этого:
```HTML
<div class="form__field">
  <label class="form__label ">Custom select:</label>
  <div class="ui dropdown form__select js-select">
    <input type="hidden" name="select">
    <i class="dropdown icon"></i>
    <div class="default text">Gender</div>
    <div class="menu">
      <div class="item" data-value="1" data-item="attr-1">Option 1</div>
      <div class="item" data-value="2" data-item="attr-2">Option 2</div>
    </div>
  </div>
</div>
```
Если это отвечает на вопрос, закройте, пожалуйста, тред.

**Comment by Galeups** [comment]
@Banandrew  )) да, по русски привычнее.
Но мне бы хотелось использовать именно select, с присвоением каждому option пользовательских аттрибутов, для дальнейшей их стилизации и отслеживания выбора того или иного option.
Если я в разметке задаю дата аттрибуты, то они удаляются и я получаю разметку без моих data-*

**Comment by Banandrew** [comment]
@Galeups Вместо `input` в качестве хранилища можно использовать и `select`, если это необходимо, но бессмысленно в ключе стилизации, потому что при инициализации на `select`, компонент в любом случае строит аналогичный HTML из этого `select`, а сам `select` скрывает, используя его только в качестве хранилища данных—так что всё равно придётся стилизовать элементы `.menu .item`, а не сам `select`. На всякий случай, если необходимо изначально как-то стилизовать компонент, это лучше всего делать через [исходники LESS](https://semantic-ui.com/usage/theming.html).

**Comment by Galeups** [comment]
@Banandrew, спасибо большое за помощь, понял, что для стилизации целесообразнее использовать html разметку, наверно откажусь от использования select. 
Боялся, что пострадает семантика, но получается, даже при использовании select, на странице строится разметка на div-ах.
Спасибо большое! )
