### ISSUE TITLE
[Sidebar] Stop working after moved to https

### ISSUE THREAD

**Issue by jdotchai** [Semantic-Org/Semantic-UI#5898]
Semantic version: 2.2.6

My sidebar stop working after installed SSL. The sidebar do not hide / animating in when page is ready, it show up and stacked on the "pusher" div. Anyone have this issue and know how to fix it?

js:
`$('.ui.sidebar').sidebar('attach events', '.menu.text .item').sidebar('setting',{debug:true});`

html:
```
<div class="ui sidebar inverted vertical menu">
...
</div>
<div class="pusher">
<div class="ui fluid menu text"><a class="item"><i class="content icon"></i></a></div>
...
</div>
```

<img width="1276" alt="screen shot 2017-10-27 at 8 12 13 am" src="https://user-images.githubusercontent.com/30018451/32082514-a6e04618-baee-11e7-8220-b8958eb68043.png">

**Comment by Banandrew** [comment]
Hi @jdotchai,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
