### ISSUE TITLE
[Popup] Popup on manual shouldn't stay after parent accordion is closed

### ISSUE THREAD

**Issue by savolkov** [Semantic-Org/Semantic-UI#5900]
Hello!

You can see the case here: https://jsfiddle.net/savolkov/twxrg9ax/
When popup is manually shown, it doesn't disappear when the accordion is minimized. Not sure if it is supposed to be so.

**Comment by Banandrew** [comment]
Hi @savolkov, sorry for the delay, it’s supposed to behave like that. `manual` implies that it’s a developer’s responsibility to manipulate the popup.

**Comment by savolkov** [comment]
@Banandrew Thanks for reply!

Could you also please comment on this situation?
https://jsfiddle.net/savolkov/ou575txv/3/
Should popup on manual be higher than modal?

**Comment by Banandrew** [comment]
@savolkov I don’t know. Apparently there was supposed to be a discussion about it 2 years ago, but it lead nowhere: #2269. In any case, if you don’t want this behavior, you can override it in `installation_folder/src/site/modules/popup.variables`: copy `@zIndex: 999;` there and rebuild the framework. The modal uses a `z-index` of `1000`, so setting it to `999` should do it.
