### ISSUE TITLE
Add .ui.hidden to all elements

### ISSUE THREAD

**Issue by buckle2000** [Semantic-Org/Semantic-UI#5905]
Currently,  only dividers can be hidden using `.ui.hidden` class.
What about we can let every element be invisible with `hidden` class?

**Comment by Banandrew** [comment]
Hi @buckle2000, you can use the transition component for that by adding `.transition.hidden` classes to an element. Hidden dividers, on the other hand, serve a different purpose: they still divide content, but without creating a dividing line. It’s a component variation, not a way to hide an element.
