### ISSUE TITLE
[Popup] - Wrong positioning popup

### ISSUE THREAD

**Issue by mamaevaksu** [Semantic-Org/Semantic-UI#5906]
**Steps to Reproduce**
1. Create 
  `<div class='a' style={position: 'relative', top: '100px'}>`
    `<div class='b'>`
  `    bbb`
  `  </div>`
  `</div>`
  `<div class='ui popup'>tooltip</div>`
2. Create popup: $('.b').popup({popup: '.ui.popup', movePopup: false})
3. Hover on div.b

**Expected**
The Popup should show on top left position

**Result**
The Popup bottom position wrong
$offsetParent variable set to div.a, but div.ui.popup is not child of div.a, because movePopup == false,
and bottom of div.ui.popup have to be: 
$offsetParent.height - $target.top + ($(window).height - $offsetParent.outerHeight()) 

Now i solve the problem:
var parent = $(target).popup("get offsetParent");
$(target).popup({
  distanceAway: parent ? $(window).height() - parent.outerHeight() : 0,
  popup: '.ui.popup',
  movePopup: false
});

**Testcase**
http://jsfiddle.net/mamaevaksu/L24524hw/

**Comment by Banandrew** [comment]
Hi @mamaevaksu, your test case is empty.

**Comment by mamaevaksu** [comment]
Done)

**Comment by mamaevaksu** [comment]
+

**Comment by mamaevaksu** [comment]
fixed
