### ISSUE TITLE
Centre logo item inside semantic menu

### ISSUE THREAD

**Issue by Virushaan** [Semantic-Org/Semantic-UI#5914]
Hi, how can I go about centering a item (a company name for example) inside a navbar? I need the company name to be horizonally centered on the page, not just in the middle of the navbar div.

**Comment by Banandrew** [comment]
Hi @Virushaan,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
