### ISSUE TITLE
[Modal] - Add feature to set the parent modal

### ISSUE THREAD

**Issue by erlangp** [Semantic-Org/Semantic-UI#5917]
Please add feature to set the parent modal. So when close the child modal, automatic show parent modal. Thanks 😄

**Comment by Banandrew** [comment]
Hi @erlangp, could you please elaborate and explain your use case? It seems that it’s rather pointless to add something as simple as this to the core; you can already use the [attach events](https://semantic-ui.com/modules/modal.html#attach-events) method as a shorthand.
