### ISSUE TITLE
cant popup the modal

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#5924]
**this is my view**

var Addjob_layout =Marionette.ItemView.extend({
    template: AddJobTemplate,
    render: function () {
      $(".ui .modal").modal("show");
         
});
var addjob_obj = new Addjob_layout();
addjob_obj.render();

**AddJobTemplate.html**

_<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">
    Profile Picture
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="/images/avatar/large/chris.jpg">
    </div>
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="https://www.gravatar.com" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      Nope
    </div>
    <div class="ui positive right labeled icon button">
      Yep, that's me
      <i class="checkmark icon"></i>
    </div>
  </div>
_</div>__

In the above code when i run it is not poping out the standard modal.. can any one tell me the solution.

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.
