### ISSUE TITLE
When I open the pop-up, the google font is reloaded

### ISSUE THREAD

**Issue by QuDDoSS** [Semantic-Org/Semantic-UI#5931]
When I open the pop-up, the google font is reloaded and blinked

http://prntscr.com/h797qw

**Comment by Banandrew** [comment]
Hi @QuDDoSS, I can’t seem to reproduce. You can try self-hosting the font, I posted the instructions [here](https://github.com/Semantic-Org/Semantic-UI/issues/5642#issuecomment-321421683).
