### ISSUE TITLE
Meteor - Font Awesome 4.7

### ISSUE THREAD

**Issue by rereradu** [Semantic-Org/Semantic-UI#5936]
Are Semantic-UI-Meteor-Data and Semantic-UI-Meteor repositories still maintained?
I use Semantic-UI-Meteor in my project and I miss some of the latest icons added in Font Awesome 4.7.

**Comment by Banandrew** [comment]
Hi @rereradu, unfortunately, I can’t answer the question, but we’re already tracking it here: #5675. I was going to mention it to the maintainer before the next release, not sure when it’s going to happen, though.
