### ISSUE TITLE
Sketch files of deleted repo: https://github.com/garystover/Semantic-UI-Kit

### ISSUE THREAD

**Issue by eldjango** [Semantic-Org/Semantic-UI#5940]
Hi folks, I wanted to ask if someone has the files of this repo since its down and the user is also deleted.

It looks like it was the most complete library for sketch, but now I can't find any forks or copies anymore:
https://www.pinterest.de/pin/320529698465231699/

Regards

**Comment by rbtsolis** [comment]
I found this [repo](https://github.com/guacamoly/semantic-ui-kit-for-sketch), its the same user, but in other account

**Comment by eldjango** [comment]
Unfortunately, it's not the same, as it seems to be a really lightweight library compared to that of Pinterest.

**Comment by rbtsolis** [comment]
oh, you are rigth, it isn't the same repo

**Comment by jacky-ttt** [comment]
[https://github.com/intfrr/Semantic-UI-Kit](https://github.com/intfrr/Semantic-UI-Kit) 
This repo should have the same content. Don't know if intfrr and garystover are the same person.

**Comment by eldjango** [comment]
great!!! thanks @jacky-ttt
