### ISSUE TITLE
[Card] Image on the left

### ISSUE THREAD

**Issue by msalafia** [Semantic-Org/Semantic-UI#5946]
I think that will be useful have the possibility to put the image of a Card on the left (or right) side and not only on the top. Something similar was done in Semantic UI Item. Have this possibility for Cards would be nice.
I mean something like this:

![image](https://user-images.githubusercontent.com/11465611/32692485-08e1d116-c719-11e7-8c59-9ffb67fc4cbc.png)

**Comment by lubber-de** [comment]
Available since Fomantic-UI 2.5
See https://fomantic-ui.com/views/card.html#horizontal-cards
![image](https://user-images.githubusercontent.com/18379884/61992402-2e32b400-b05e-11e9-8848-96dc5c3e8b30.png)
