### ISSUE TITLE
ISSUE: Dropdown not displaying issue can anyone see problem

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5948]
Hi im using a dropdown on a navigation and for some reason when you click it the links are not full width but it only happens when a dropdown is on the end?. Am i doing something wrong because its never happened before thanks.

https://jsfiddle.net/fb93gL2j/
https://jsfiddle.net/nrzmkypw/

**Comment by Banandrew** [comment]
Hi @jackttcoms, please see #5741.
