### ISSUE TITLE
modal scroll bug

### ISSUE THREAD

**Issue by acornejo** [Semantic-Org/Semantic-UI#595]
Modals don't work in android, tested in Nexus 5 with latest stock build.

When modals appear initially they display fine, but if modal is too large for the window and you try scrolling, the whole window scrolls, the modal dissapears (and its impossible to get it back).

I think this is related to the issue of modals allowing the background to scroll while open.

**Comment by cometta** [comment]
I faced similar issue as well. @brigand, anyway for you to test on emulator..

**Comment by Enelar** [comment]
https://www.genymotion.com/
