### ISSUE TITLE
How to invoke a region

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#5951]
""driver.js""

var MenuView=Backbone.View.extend({
   
  render:function(){
      this.$el.html("this is menu part");
        return this;
  }
});
var ContentView=Backbone.View.extend({
    
    render:function(){
        this.$el.html("This is content view");
        return this;
    }
});
var AppLaoutView=Marionette.LayoutView.extend({
    template:$("#inputtemplate"),
    render:function(){
        this.$el.html("this is layout view");
    },
    regions:{
        menu:"#menu",
        content:"#content"
    }
});
var applayout=new AppLaoutView({el:"#inputcontent"});
applayout.render();

applayout.getRegion("menu").show(new MenuView());
applayout.getRegion("content").show(new ContentView());
////////////////////////////////////////////////////////////////////////

""input.html""

![image](https://user-images.githubusercontent.com/33145497/32710506-a25ef47c-c85e-11e7-9131-059de53930a9.png)

///////////////////////////////////////////////////////////////////
""Error""
when i try to run this program im getting 

backbone.marionette.min.js:21 Uncaught constructor {name: "Error", message: "An "el" #menu must exist in DOM", stack: "Error: An "el" #menu must exist in DOM↵    at cons… at file:///C:/nodehttp/final/js/driver.js:122:16"}
_ensureElement @ backbone.marionette.min.js:21
show @ backbone.marionette.min.js:21
(anonymous) @ driver.js:122

//////////////////////////////////////////////////////////

Can anyone help me how to solve this error

**Comment by Banandrew** [comment]
Hi @Prasadu112, although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers. I think it will be best to ask around Backbone communities.
