### ISSUE TITLE
Wrong backgroud-color for .ui.horizontal.segments

### ISSUE THREAD

**Issue by Lathanao** [Semantic-Org/Semantic-UI#5952]
Hi,
The css of "ui horizontal segments" (line 16106) get 2 background-color
Look the render example: https://jsfiddle.net/xau9wzo5/
The 'background-color: #FFFFFF;' doesn't seem to be necessary.

.ui.horizontal.segments {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
    background-color: transparent;
    border-radius: 0px;
    padding: 0em;
    background-color: #FFFFFF;
    box-shadow: 0px 1px 2px 0 rgba(34, 36, 38, 0.15);
    margin: 1rem 0em;
    border-radius: 0.28571429rem;
    border: 1px solid rgba(34, 36, 38, 0.15);
}

**Comment by lubber-de** [comment]
Fixed since https://github.com/fomantic/Fomantic-UI 2.6.4

**Comment by Lathanao** [comment]
Hey,

Fomantic looks a great project !
Thx for having pinged me.
