### ISSUE TITLE
Feature: change accordion behavior on active state

### ISSUE THREAD

**Issue by kob-e** [Semantic-Org/Semantic-UI#5953]
Instead of `dispaly: none` and `dispaly: block`
use 
```css
visibility: hidden;
  height: 0;
  opacity: 0;
```
and
```css
 visibility: visible;
  opacity: 1;
```

and then we can add transition effect:
`  transition: visibility 0s, opacity 0.5s linear;`

**Comment by Banandrew** [comment]
Hi @kob-e, why, what’s your use case?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.
