### ISSUE TITLE
Unable to install Semantic-UI as part of npm install (Ignoring local @import of "../n/semantic.rtl.min.css" as resource is missing.)

### ISSUE THREAD

**Issue by hurreedotco** [Semantic-Org/Semantic-UI#5954]
Have been trying to install semantic-ui as part of a larger node install, and we are constantly seeing this fail on both local machines and our build server.

**Local Machine:** 
node --version = v8.9.0
npm --version = 5.5.1
OS : Mac OS 10.13.1

**Build Server:**
node --version = v6.12.0
npm --version = 3.10.10
OS: Mac OS

We have found that running node install a second time on the local machines fixes the problem, but that isn't an option for our production build server as we are using a hosted build agent in VSTS and when it fails a step like this it also fails the build, and running node install a second time isn't possible.

We may be able to shoe-horn in a second npm install, however that still leaves us with a failed build step for every build, and that seems like it's not the right way to go about this.

Are there any steps that we could take to prevent this issue?

Logs and package.json provided.

package.json:

`{
  "name": "mash-able",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.0",
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.3.4",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.1",
    "@nicky-lenaers/ngx-scroll-to": "^0.3.1",
    "@swimlane/ngx-datatable": "^9.3.0",
    "@types/googlemaps": "^3.26.17",
    "angular-froala-wysiwyg": "^1.0.0",
    "angular-io-slimscroll": "^1.2.11",
    "angular-maps": "^0.5.10",
    "angular2-baidu-map": "^3.0.2",
    "angular2-chartjs": "^0.2.0",
    "angular2-datatable": "^0.6.0",
    "angular2-material-datepicker": "^0.5.0",
    "angular2-notifications": "^0.7.4",
    "angular2-wizard": "^0.4.0",
    "bootstrap": "^4.0.0-beta",
    "c3": "^0.4.16",
    "chartist": "^0.11.0",
    "core-js": "^2.4.1",
    "css-animator": "^2.1.1",
    "echarts": "^3.6.2",
    "famfamfam-flags": "^1.0.0",
    "flag-icon-css": "^2.8.0",
    "jquery-knob": "github:aterrien/jQuery-Knob",
    "jquery-sparkline": "^2.4.0",
    "morris.js": "^0.5.0",
    "ng-chartist": "^1.1.1",
    "ng-click-outside": "^2.4.1",
    "ng-knob": "^1.0.1",
    "ng-select": "^1.0.0-beta.6",
    "ng2-currency-mask": "^4.3.1",
    "ng2-file-upload": "^1.2.1",
    "ng2-google-charts": "^3.0.1",
    "ng2-knob": "^1.0.4",
    "ng2-mask": "^1.1.1",
    "ng2-nvd3": "^2.0.0",
    "ng2-toasty": "^4.0.3",
    "ng2-ui-switch": "^1.0.2",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "^1.8.0",
    "ngx-chips": "^1.4.6",
    "ngx-color-picker": "^4.2.0",
    "ngx-echarts": "^1.2.3",
    "ngx-quill-editor": "^2.2.1",
    "peity": "^3.2.1",
    "raphael": "^2.2.7",
    "rxjs": "^5.1.0",
    "screenfull": "^3.3.1",
    "semantic-ui": "^2.2.10",
    "semantic-ui-calendar": "0.0.8",
    "simple-line-icons": "^2.4.1",
    "squeezebox": "^1.1.12",
    "sweetalert2": "^6.6.6",
    "ti-icons": "^0.1.2",
    "zone.js": "^0.8.7"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/chartist": "^0.9.35",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
`

Logs are below:
`[12:32:02] Starting 'package uncompressed rtl css'...
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. (Ignoring local @import of "../n/semantic.rtl.min.css" as resource is missing.)
    at DestroyableTransform.emit (events.js:186:19)
    at DestroyableTransform.onerror (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_readable.js:633:52)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at onwriteError (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/Users/USERNAME/Prototypes/Example-Web/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/USERNAME/Prototypes/Example-Web/node_modules/gulp-clean-css/index.js:38:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.2.13 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USERNAME/.npm/_logs/2017-11-15T12_32_12_849Z-debug.log`

Semantic.json:
`{
  "base": "node_modules",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src\\",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "y\\",
      "uncompressed": "n\\",
      "compressed": "y\\",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "autoInstall": true,
  "rtl": true,
  "components": [
    "reset",
    "site",
    "button",
    "container",
    "divider",
    "flag",
    "header",
    "icon",
    "image",
    "input",
    "label",
    "list",
    "loader",
    "rail",
    "reveal",
    "segment",
    "step",
    "breadcrumb",
    "form",
    "grid",
    "menu",
    "message",
    "table",
    "ad",
    "card",
    "comment",
    "feed",
    "item",
    "statistic",
    "accordion",
    "checkbox",
    "dimmer",
    "dropdown",
    "embed",
    "modal",
    "nag",
    "popup",
    "progress",
    "rating",
    "search",
    "shape",
    "sidebar",
    "sticky",
    "tab",
    "transition",
    "api",
    "form",
    "state",
    "visibility"
  ],
  "version": "2.2.13"
}`

**Comment by Banandrew** [comment]
Hi @hurreedotco, could you please post your `semantic.json`?

**Comment by hurreedotco** [comment]
UPDATED: Added semantic.json to original question
