### ISSUE TITLE
Sticky footer and sidebar

### ISSUE THREAD

**Issue by dasa123** [Semantic-Org/Semantic-UI#5955]
Hi *,
I have setup a sidebar as well as a sticky footer. It's working well except for IE11.

The sidebar requires this structure (source: [Semantic UI Docs](https://semantic-ui.com/modules/sidebar.html#page-structure)):
```
<body>
  <div class="ui sidebar"> ... </div>
  <div class="pusher"> Your site's actual content </div>
</body>
```

The recommended approach for the sticky footer requires this structure (source: [Sticky Footer with Flexbox](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/))
```
<body class="Site">
  <header>…</header>
  <main class="Site-content">…</main>
  <footer>…</footer>
</body>
```
My current solution for all browsers except IE11 is:

```
<body>
  <div class="ui sidebar"> ... </div>
  <div class="pusher Site">
    <header> My default menu </header>
    <main class="Site-content"> The actual content </main>
    <footer> My sticky footer </footer>
  </div>
</body>
```

```
/* source: https://github.com/philipwalton/solved-by-flexbox/blob/master/templates/default.html */
.Site {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

.Site-content {
  flex: 1;
}
```

If I use the complete sticky footer solution ([CSS Code](https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css)), sticky footer stops working in all browsers.

Does somebody know how to get both sticky footer and sidebar working in IE11?

**Comment by dasa123** [comment]
I think I got it working. According to this [post on stackoverflow](https://stackoverflow.com/questions/44700068/flexbox-min-height-and-ie11) another "display: flex" is need.

I changed the code accordingly:

```
<body>
  <div class="ui sidebar"> ... </div>
  <div class="Site-ie-container">
    <div class="pusher Site">
      <header> My default menu </header>
      <main class="Site-content"> The actual content </main>
      <footer> My sticky footer </footer>
    </div>
  </div>
</body>
```

And the CSS:

```
.Site {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

.Site-content {
  flex-grow: 1;
}

/* Only IE11 */
@media all and (-ms-high-contrast:none) {
  *::-ms-backdrop, .Site-ie-container {
    display: flex;
  }
  *::-ms-backdrop, .Site {
    width: 100%;
  }
}
```

**Comment by Banandrew** [comment]
Hi @dasa123, 

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers, and I’ll be closing this thread now that it’s resolved.
