### ISSUE TITLE
Location of LESS and JS (core) files?

### ISSUE THREAD

**Issue by edhenderson** [Semantic-Org/Semantic-UI#5957]
First time user, great library.

Does the location of the LESS and JS (core files) have to be in the source of my project, can they reside in node_modules (as a dependency) so I don't have to commit them to my project?

Of course the overrides etc can be in source/

Sorry for the noob question, thanks so much!

**Comment by Banandrew** [comment]
Hi @edhenderson, [this SO question](https://stackoverflow.com/questions/32538811/semantic-ui-in-gitignore) might help.

**Comment by edhenderson** [comment]
Thanks for the link. I'll take a proper look today. A cursory glance makes it look like this is more of a hack than official recommendation. Is the *Semantic-UI* way to commit the `src` files to repo?

**Comment by Banandrew** [comment]
@edhenderson Yes.

**Comment by edhenderson** [comment]
@Banandrew Thank you for your help Sir.
