### ISSUE TITLE
[Form] Add Fieldset / Legend

### ISSUE THREAD

**Issue by Dayjo** [Semantic-Org/Semantic-UI#596]
I feel like maybe I've missed something here.

I'm doing my first form with semantic-ui and using `<fieldset>` with `<legend>` to group fields together, but they appear to have no styling, plus can't find any documentation or other raised issues on either fieldset or legend tags. 

Is there a reason that there's no support for these tags?

**Comment by mdotobie** [comment]
I'd really like to see Semantic UI implement support for the use of fieldset within forms as an alternative to using divs. I believe fieldset is the more semantic way of grouping form elements.

I did try my hand at modifying the base layout of the fieldset element as per @Dayjo and @Anachron's conversation. Have guys seen any further progress on this path?

**Comment by amingilani** [comment]
For one, increased margins would be nice.
