### ISSUE TITLE
On the new firefox icons not aligned correctly

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5960]
Im using the new Firefox Quantum which can i just say is amazing but with the button when you hover the icon is not directly central as you can see in the images below...

![iconalign](https://user-images.githubusercontent.com/26184209/32974337-1a008ee8-cbf5-11e7-97f4-2042e946f840.PNG)
![iconalign2](https://user-images.githubusercontent.com/26184209/32974338-1a212fc2-cbf5-11e7-965b-41bc0796d5d6.PNG)

**Comment by Banandrew** [comment]
Hi @jackttcoms, I couldn’t reproduce it on Windows. What OS did you use?

**Comment by jackttcoms** [comment]
sorry it appears to be a bit of custom CSS somewhere so i have just overridden it with line-height: 16px; thanks

**Comment by Banandrew** [comment]
Closing as resolved.
