### ISSUE TITLE
Dropdown doesn't work on local machine

### ISSUE THREAD

**Issue by nebrelbug** [Semantic-Org/Semantic-UI#5962]
See Issue #5712--I wasn't sure if I should create a new issue since this was already an issue, but I did.

Same thing exactly; my dropdown works fine on CodePen, just doesn't work when I run the exact same code on my Windows computer or `firebase deploy`. Could someone help? Thanks!

**Comment by Banandrew** [comment]
Hi @nebrelbug, are you absolutely sure you didn’t forget to include jQuery?

**Comment by nebrelbug** [comment]
Yes, I'm absolutely sure. The sidebar works fine. My console doesn't throw any errors; I was wondering whether it might be because I'm including Firebase...

**Comment by nebrelbug** [comment]
I'll add more details tomorrow

**Comment by nebrelbug** [comment]
I don't need to use jQuery UI, right?

**Comment by Banandrew** [comment]
@nebrelbug No, jQuery UI is not needed.

**Comment by nebrelbug** [comment]
Never mind, it seems that it's a problem with my code; it looks like Firebase OnAuthChanged is preventing $(document).ready() from calling? Anyway, sorry for the false alarm. Thanks for all you do! I love Semantic-UI!

**Comment by nebrelbug** [comment]
Never mind; it appears that it's a problem with my code, not with SemanticUI. I guess Firebase OnAuthChanged is preventing $(document).ready() from calling? Anyway, sorry for the false alarm. Thanks for all that you do! I love Semantic-UI!

**Comment by nebrelbug** [comment]
Oops, recommented :)
