### ISSUE TITLE
Icon Text button does not look 100% central

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#5963]
https://semantic-ui.com/ The menu button does not look 100% central 

it might just be me but if you put a ruler on the screen there is a small difference

![btn](https://user-images.githubusercontent.com/26184209/32995405-78650d7a-cd6b-11e7-9489-870ac42bdb5d.PNG)

**Comment by Banandrew** [comment]
Hi @jackttcoms, could you please elaborate, where did you take the first screenshot, and how is the second one supposed to look?

**Comment by jackttcoms** [comment]
IT just looks like it should be a bit further down to be completely central and I took the screenshot on the semantic UI homepage and looked on Edge,Firefox and chrome and they all looked slightly off center
