### ISSUE TITLE
[Checkbox Slider] No "Checked" Class

### ISSUE THREAD

**Issue by zerolfc** [Semantic-Org/Semantic-UI#5966]
When checkbox slider checked - there is no "checked" class appended, unless you uncheck and check it again then it appends "checked" class.

![checkbox](https://user-images.githubusercontent.com/5167436/33044315-643369a2-ce40-11e7-967d-21d3e1ae244d.png)

**Comment by Banandrew** [comment]
Hi @zerolfc, thank you, but we’re already tracking it here: #2506.
