### ISSUE TITLE
[Sticky] Anyone have zIndex issues with Sticky?

### ISSUE THREAD

**Issue by slashwhatever** [Semantic-Org/Semantic-UI#5970]
Example: https://github.com/Semantic-Org/Semantic-UI

Screenshot shows a full width navigation bar that's a Sticky component set to offset=0

Content below is a grid with a series of rows and columns that for some reason scrolls over the top of the sticky component. Seems the only place I can add a zIndex to fix this is inline in the element the sticky component creates.

**Comment by Banandrew** [comment]
Hi @slashwhatever, your test case is a wrong link, I’m assuming you wanted to show something?

**Comment by vinayakkulkarni** [comment]
It's been 2 weeks, yet no test-case.

Will open it once there's a test-case.
