### ISSUE TITLE
Sidebar conflicts with jQuery context-menu plugin

### ISSUE THREAD

**Issue by fperezgaliana** [Semantic-Org/Semantic-UI#5971]
I have a page that uses Semantic UI and jQuery context-menu plugin (https://github.com/mar10/jquery-ui-contextmenu). As soon as I run the sidebar function, the context menu stops working until I reload the page. The jQuery context menus is loaded as this:

```
$("#objPanel").contextmenu({
  menu : [ .... ]
  beforeOpen : function(event, ui) etc...
});
```

I've tried to inspect the DOM for changes on this div but I didn't find any difference before and after calling the sidebar function. In theory, calling this function shouldn't affect the surronding elements, right?

**Comment by Banandrew** [comment]
Hi @fperezgaliana,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
