### ISSUE TITLE
[Header] is mis-named; actually a Heading

### ISSUE THREAD

**Issue by em** [Semantic-Org/Semantic-UI#5972]
There's a very explicit distinction in web standards and practice between a `header`, and a `heading`. You guys seem to have called Heading a Header.

This is a pretty weird issue for me since I'm building a site using a custom semantic theme, and I have to explicitly not import the Semantic Header, and make a custom element called Header that's an actual header.

W3C terminology for reference:

https://www.w3.org/wiki/HTML/Elements/h1,_h2,_h3,_h4,_h5,_and_h6
> These elements represent headings for their sections.

https://www.w3.org/wiki/HTML/Elements/header
> The \<header\> element represents a group of introductory or navigational aids.

It would be nice if there was a real Header in semantic as well BTW.

**Comment by lubber-de** [comment]
We started discussing about this for the official community fork Fomantic-UI
https://github.com/fomantic/Fomantic-UI/discussions/2407
