### ISSUE TITLE
[Comment] Support comments without avatars

### ISSUE THREAD

**Issue by xrajishx** [Semantic-Org/Semantic-UI#5973]
Please find the fiddle [here](https://jsfiddle.net/v89r4y2b/)

The fiddle above is created with the examples in the docs. I have only removed the avatars.

**Comment by Banandrew** [comment]
Hi @xrajishx, this is an unsupported use case, I labeled it as enhancement for possible future implementation.

**Comment by atilkan** [comment]
@Banandrew Why don't you close this issues. I am testing and experimenting this framework. Number of open issues made scared but they are not scary actually.
