### ISSUE TITLE
Stackable Doubling grid and mobile

### ISSUE THREAD

**Issue by haelexuis** [Semantic-Org/Semantic-UI#5976]
Hi, so I want to have columns like this:
when mobile is vertically, there will be only 1 column in grid row
when mobile is horizontally, there will be 2 columns in grid row
by this definition: https://semantic-ui.com/examples/responsive.html it should works in class "ui four column doubling stackable grid container" but it doesn't, even on this site with mobile device, there will be always 1 column in row with "doubling stackable" and with only "doubling" there will be 2 columns in row, but even if mobile is vertically, so what can I do?

**Comment by Banandrew** [comment]
Hi @haelexuis,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
