### ISSUE TITLE
[Search] Unprofessional Hover Effect when Action is Added

### ISSUE THREAD

**Issue by jmorales2718** [Semantic-Org/Semantic-UI#5977]
Hi,

This is a super simple to fix problem...

Found a strange css effect that makes searches with an action look bad.

![image](https://user-images.githubusercontent.com/15984429/33231637-bdb43cfc-d1c6-11e7-878b-d340349aa9e8.png)

This only occurs on hover and can be found on line 221 of semantic-ui-css/components/search.css:

![image](https://user-images.githubusercontent.com/15984429/33231651-12bb172a-d1c7-11e7-81df-5b276f48688c.png)

It is only a problem on hover, but it seems like a strange effect when inside the completely rounded search field.

**Background Info:**

Google Chrome and using SUI React Search Module.

**Recreate:**

Add input prop to Search as follows:

`<Search input={{action: <Button>Button</Button>}}`

**JSFiddle Demo**

[Here's a simple fiddle](https://jsfiddle.net/bc0680p6/2/)

**Comment by lubber-de** [comment]
Fixed since [Fomantic-UI]( https://fomantic-ui.com/) 2.5
