### ISSUE TITLE
[Divider] in grids broken

### ISSUE THREAD

**Issue by em** [Semantic-Org/Semantic-UI#5978]
https://react.semantic-ui.com/elements/divider#divider-example-vertical shows the issue. Everything is absolute positioned off to the farmost left.

**Comment by em** [comment]
BTW: It seems the only way to really get flex-grow 0 and 1 is by using a Divider (well, if it worked). Would be nice if grid columns and rows just had `grow` and `shrink` options. Or `expanding` `contracting`

**Comment by Banandrew** [comment]
Hi @em, thank you, we’re already tracking it here: #4342.
