### ISSUE TITLE
Support for additional Font Awesome fonts?

### ISSUE THREAD

**Issue by kappaknight** [Semantic-Org/Semantic-UI#5979]
I would really like it if Semantic could support the following User Circle font:

http://fontawesome.io/icon/user-circle-o/

The use of circular Profile pics is throughout the entire theme, and this would be a great "default" icon for those that haven't uploaded anything to be their profile pic.

Also, Font Awesome 5.0 is coming out soon. It may be worth checking out what new icons will be available then.

Thanks in advance!

**Comment by Banandrew** [comment]
Hi @kappaknight, it’s supported and documented [here](https://semantic-ui.com/elements/icon.html#user-types):

https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/themes/default/elements/icon.overrides#L203
