### ISSUE TITLE
[Install] Error on ´gulp install´ / ´run setup´

### ISSUE THREAD

**Issue by breytex** [Semantic-Org/Semantic-UI#5980]
Hey!
Just wanted to create my first custom theme for semantic ui.
Freshly checked out the repository and executed npm install.

![screen shot 2017-11-27 at 02 12 21](https://user-images.githubusercontent.com/4541640/33246736-971ed91e-d318-11e7-97dd-0f91e63974c7.png)

Mac OS X 10.12.
Node v8.7.0
npm 5.4.2

Any suggestions?

**Comment by Handiwork** [comment]
I encountered the same problem today...

![tim 20171202155829](https://user-images.githubusercontent.com/8043546/33513242-bbb1d906-d779-11e7-87dd-48a46358d496.png)

**Comment by Handiwork** [comment]
It seems the npm to blame. Package  "prompt-sui" should be  installed correctly by npm@3.10.10.
Please try:`npm un -g npm`
![build succeed](https://user-images.githubusercontent.com/8043546/33547328-b63975dc-d91e-11e7-8ea1-abb030344e71.png)
