### ISSUE TITLE
[Card] - Card size Issue

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [Semantic-Org/Semantic-UI#5981]
**Steps to Reproduce**
1. Define a simple card.
2. The size of cards intent for more than 300px.

**Expected**
The card sould be take size of parent,

**Result**
Card is only taking size of max 290px width.

The issue is having due to CSS defined in core file
.ui.card {
   width: 290px
}

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by jlukic** [comment]
Try a [`fluid card`](https://semantic-ui.com/views/card.html#fluid-card)
