### ISSUE TITLE
Usage question: tabs + ajax

### ISSUE THREAD

**Issue by drnasin** [Semantic-Org/Semantic-UI#5982]
Hi guys, just a quick question regarding tabs as we are not sure it is expected behaviour or a bug. When using ajax content on tabs the only way to get the initial tab to show ajax content (and events to fire) is to explicitly call tab('change tab') after tab initialization? Is this right? Just want to be sure we are not doing it wrong :)

**Comment by vinayakkulkarni** [comment]
Dear @drnasin, Please visit our [gitter channel](https://gitter.im/Semantic-Org/Semantic-UI) or [discord server](https://discord.gg/7vqmGxa) to get answers for usage related questions.
