### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jayphelps** [Semantic-Org/Semantic-UI#5983]
Mostly a question for @jlukic I think. I noticed that the last commits/PRs merged were in early August, so wanting to check if semantic-ui is still maintained. You certainly owe me nothing, just would be helpful to know so I can plan and decide on new apps I'm building.

I've got a couple outstanding PRs as well, but neither is critical so my question is not tied to them #5749 #5832

**Comment by kevinresol** [comment]
Yes: https://github.com/Semantic-Org/Semantic-UI/commits/next

**Comment by jayphelps** [comment]
Woot! Thanks got clarifying!

**Comment by jlukic** [comment]
It's still maintained, my time has been a bit fuzzy recently, but I plan on trying to get a few essential things out over the holidays.

**Comment by kevinresol** [comment]
@jlukic Will you consider setting up Patreon (or other source of funding) so people can financially support the project? https://github.com/Semantic-Org/Semantic-UI/issues/2201
