### ISSUE TITLE
Feature request - to change Modal so it's easier to use with Angular

### ISSUE THREAD

**Issue by alvipeo** [Semantic-Org/Semantic-UI#5984]
I prefer Semantic UI over other interfaces and I use it in Angular 5 applications. But it's a pain to make modal work (using Semantic as it is). So I wonder if I could ask to change modal so it doesn't work with DOM in a more simpler matter... Well, if you had plans to improve Semantic anyway...

**Comment by vinayakkulkarni** [comment]
Dear @alvipeo,

Changing a core component just for a framework doesn't make sense. you might want to take on a semantic-ui-angular project; similar to [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React)?
