### ISSUE TITLE
prevent submit default and field verify's problem.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [Semantic-Org/Semantic-UI#5992]
In default:
```html
<div class="ui fluid large teal submit button">LOGIN</div>
```
This button will verify user's input,such as:
![image](https://user-images.githubusercontent.com/10345361/33546259-88a1166e-d91b-11e7-8ec0-1eb2e21d5534.png)

![image](https://user-images.githubusercontent.com/10345361/33546190-5130d99e-d91b-11e7-9175-02319e018aa7.png)

If 
```JS
$('form').form().submit(function (evt) {
        evt.preventDefault()
});
```
And I use my self function to login. input verify will no effect. How to solve this problem in general?

**Comment by ulises-salinas** [comment]
@MiyamuraMiyako you should use: 

$('form').submit(function (evt) {
        evt.preventDefault()
});

Without .form()

**Comment by MiyamuraMiyako** [comment]
@ulises-salinas Thank you for reply, problem solved.
