### ISSUE TITLE
How do u reset the values in semantic modal

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#5993]
after performing the validation on a modal fields, how to reset the values and reset the color(reset)..

**Comment by Banandrew** [comment]
Hi @Prasadu112,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
