### ISSUE TITLE
how to reset/refresh the modal 

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#5994]
how to reset/refresh the modal before/after closing the modal??

**Comment by ulises-salinas** [comment]
@Prasadu112 do you need to 'restore' the content?  if so, then, show us how it is your modal .

**Comment by vinayakkulkarni** [comment]
Dear @Prasadu112,

Since this is a usage related questions, I suggest you ask it in our [Gitter channel](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord Server](https://discord.gg/7vqmGxa).

Also, kindly fork this [jsFiddle](https://jsfiddle.net/ca0rovs3/) to present your test-case.
