### ISSUE TITLE
Problem with fixed menu and loader

### ISSUE THREAD

**Issue by glagola** [Semantic-Org/Semantic-UI#6]
Hi, I think fixed menu should be above of loader, but only if loader not in modal window.

![screenshot_13 36_14 09 13](https://f.cloud.github.com/assets/1319301/1143151/7bb99fc6-1d21-11e3-8c9c-e6e7c2b4a20f.jpg)

**Comment by scumie** [comment]
This issue seems to had reappear... 

Components like fixed menu, and dropdowns have lower z-index than loader, making them hidden behind the loader.

![2016-01-29_09-51-51](https://cloud.githubusercontent.com/assets/14790771/12701017/09389adc-c7d9-11e5-93f2-a240203076b8.png)
