### ISSUE TITLE
[CDN] Last CDN recipe of the web does not work.

### ISSUE THREAD

**Issue by omarsotillo** [Semantic-Org/Semantic-UI#6008]
Tried downloading and all I found was: Not found

> https://cdn.jsdelivr.net/semantic-ui/2.2.13/semantic.min.css

**Comment by MartinKolarik** [comment]
@omarsotillo is that a link from Semantic's docs?

The correct link is https://cdn.jsdelivr.net/npm/semantic-ui@2.2.13/dist/semantic.min.css
You can find links to all files [on our website](https://www.jsdelivr.com/package/npm/semantic-ui).

**Comment by MartinKolarik** [comment]
Looks like the wrong link is mentioned here: https://semantic-ui.com/introduction/advanced-usage.html#cdn-releases

jsDelivr changed the URL format for new releases in May this year, so links in the docs should be updated (it was also mentioned in #5667). Of course, previous releases are still available using the old links as well so this doesn't affect existing users - you just need to use the new format for new versions.

**Comment by omarsotillo** [comment]
Okay! I will open a pull request and change the new links in the docs repo, is that okay? @MartinKolarik

**Comment by MartinKolarik** [comment]
@omarsotillo yep, that would be great, I think.

**Comment by omarsotillo** [comment]
Super! :bowing_man: Thank you @MartinKolarik! 
Doing it now! :dancer:

**Comment by omarsotillo** [comment]
Opened pull request here : https://github.com/Semantic-Org/Semantic-UI-Docs/pull/368

**Comment by vinayakkulkarni** [comment]
There's already a PR open: https://github.com/Semantic-Org/Semantic-UI-Docs/pull/353

**Comment by MartinKolarik** [comment]
@vinayakkulkarni in that case, why not merge it?

**Comment by omarsotillo** [comment]
It looks the docs are quite abandoned no? :-1: 
@vinayakkulkarni @MartinKolarik
