### ISSUE TITLE
Error with lists CSS not displaying correctly

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#6018]
Im attempting to use the list functionality for each 2 sentence long points but for some reason if it goes over 1 line it break the design so is there a quick fix?

see the example for what i mean

https://jsfiddle.net/8w79jhh6/

**Comment by ashucg** [comment]
@jackttcoms here is your [quick fix](https://jsfiddle.net/8w79jhh6/1/)
