### ISSUE TITLE
how to invoke an click event inside the sidebar

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#6037]
![image](https://user-images.githubusercontent.com/33145497/34104353-1b2133e8-e416-11e7-8df7-dfb3d00d1351.png)

Can anyone help me with this above code, im new to this semantic ui.
i have 3 buttons inside the sidebar, If any of the button is clicked i want to raise a click event.
can anyone please help me with this

**Comment by arobida** [comment]
$("#back").click(function() {

}
$("#updatedetails").click(function() {

}
// Needs a different id
$("#refresh").click(function() {

}
