### ISSUE TITLE
Making sidebar open automatically with URL

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#6040]
I'm trying to build a sidebar launcher where for example you go to https://name.com/index.php?launchsidebar=2 and then it triggers that sidebar to open automatically instead of the user having to click on the button is that possible with javascript/php? thanks

**Comment by ashucg** [comment]
@jackttcoms you can use the following for JS only approach:
`document.addEventListener('ready', function(){
  let hash = location.hash;
  let id = hash.replace('#', '');
  if(id!=null){
    let sidebar = document.getElementById(id);
    if(sidebar.length>0) $(hash).sidebar('toggle');
  }
});`

URL will be: https://example.com/#sidebar
where "#sidebar" is the element ID

If you want to achieve the same results using PHP, you can use:
`document.addEventListener('ready', function(){
  $('<?php echo $sidebar_selector; ?>').sidebar('toggle');
});`

where "$sidebar_selector" contains either the ID or class of the sidebar element, which you can get from $_GET variable.

**Comment by jackttcoms** [comment]
Thankyou for your quick reply and answer i also forgot to mention that currently the way to launch the sidebar content is done dynamically by fetching the content via ID so do you know a method that will allow me to do what twitter do where they load the modal window with that exact tweet in it so for example https://name.com/#sidebar18 and then it loads the sidebar as well as the data-href="modal/getcontent.php?id=18"

thanks very much

`<a class="ui pink button toc viewbidhhandle" data-href="modal/getcontent.php?id=18">View Product</a>`

`  $(".toc").click(function() {
            var dataURL = $(this).attr('data-href');
        $('.modal-body').load(dataURL,function(){
               
      });
       });`

**Comment by ashucg** [comment]
you mean something like [this](https://jsfiddle.net/hkm5maxe/)?

**Comment by jackttcoms** [comment]
yes but instead of a sidebar its now a modal window and the content that i want to automatically load is dynamic so if you want to load product 1 info in modal then link will be https://name.com/?product=1 or https://name.com/#product1 is that possible?

thanks

**Comment by ashucg** [comment]
@jackttcoms yes, you can use the same onShow [callback](https://semantic-ui.com/modules/modal.html#/settings) to load the content in your modal window

**Comment by jackttcoms** [comment]
ok thanks very much but how would i convert this to modal thanks sorry for inconvienience https://jsfiddle.net/hkm5maxe/

**Comment by ashucg** [comment]
@jackttcoms [check this example](https://jsfiddle.net/hkm5maxe/1/)

**Comment by jackttcoms** [comment]
that didnt work :(

I need it to not open always open. What im trying to achieve is where i have a link on another website then you click it and its like https://name.com/modal/#embed[id] and then it opens and loads the content for whatever the ID is but if there is just a link like https://name.com/modal/ then i dont want the modal to open

`
$(".toc").click(function() {
var dataURL = $(this).attr('data-href');
$('.modal-body').load(dataURL,function(){

  });
   });
`

thanks for your help

**Comment by jackttcoms** [comment]
almost where you can load the modal externally so you enter the link 
http://www.website.com/page.php?id=[id]#modal 
and then when you go to the site the modal will be loaded in automatically and no button needs to be clicked to launch it?

thanks

**Comment by ashucg** [comment]
@jackttcoms you need to check conditions using JS for that.
