### ISSUE TITLE
Model + Embed (Website) = Scrollable Content

### ISSUE THREAD

**Issue by LearnPhalcon** [Semantic-Org/Semantic-UI#6049]
Is it possible to have scrollable content inside modal + embed ? I'm unable to have embed scrollable =(( It works, modal and embed loads correctly with wikipedia page but there is no scrollbars and impossible to scroll with arrow keys or up/down keys. Please help, thank you!

Here is what I have;

```javascript
<script>
$(document).ready(function () {
  $('#test').on('click', function(){
    modal = $(this).attr('data-modal');
    $('.modal').modal('show');
  });
  $('.ui.embed').embed();
});
</script>
```

```html
<div id="test" data-modal="wiki"> TEST </div>

<div id="wiki" class="ui modal">
  <div class="header">Wikipedia</div>
  <div class="content">
    <div class="ui embed" data-url="https://en.wikipedia.org/w/index.php?title=CSS_framework&printable=yes">
    </div>
  </div>
</div>
```

**Comment by lubber-de** [comment]
Fixed in the community fork [Fomantic-UI](https://github.com/fomantic/Fomantic-UI)
See your example having scrollbars here https://jsfiddle.net/lubber/t102zdhx/2/
