### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by davidstefando** [Semantic-Org/Semantic-UI#605]
I have an idea. Adding slider element to semantic-ui, the slider elemet can be controlled with navigation or auto-scrolling. Slider element is an effective way to display more content with smaller space.

**Comment by iserdmi** [comment]
This slider was created special for Sematic UI, it looks pretty: https://github.com/tyleryasaka/semantic-ui-range May be you can implement it to Semantic UI?

**Comment by Banandrew** [comment]
@iserdmi Please see #4212.
