### ISSUE TITLE
Some Icon Didn't Work

### ISSUE THREAD

**Issue by yudyananda** [Semantic-Org/Semantic-UI#6057]
Hi folks

I'm working locally and using Semantic UI for my blog design, and recenlty try the icon set. 
It work fine for the icon with 1 attribute like *list icon* *book icon*, the problem appears when i use the icon that have more than 1 attribute like *id card*, it just show a blank square

Any ideas?

**Comment by maateen** [comment]
When I set `@icon     : 'default';` in my **theme.config** and build with gulp, the icon never shows. But When I set `@icon     : 'basic';`, it works like a charm.

Another thing: Icon Set classes aren't matching the icons.

**Comment by yudyananda** [comment]
@maateen 

thanks alot 👍
