### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by TheDancingCode** [Semantic-Org/Semantic-UI#6063]
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by stevelacy** [comment]
Currently `gulp-util` is only used for the `replaceExtention` function, which should be replaced with [replace-ext](https://github.com/gulpjs/replace-ext)

I can send a PR for that change

**Comment by stevelacy** [comment]
Not stale. I will assume that you want a PR for the changes? Sending one
