### ISSUE TITLE
[Dropdown] - Multiple Search Selection should not alter its size in a modal

### ISSUE THREAD

**Issue by Niputi** [Semantic-Org/Semantic-UI#6064]
I have created a [jsfiddle](https://jsfiddle.net/w5yqLopt/1/) which shows the problem with many options in a modal where the dropdown becomes wider and wider the more options are added

Edit
steps
1. have many options in Multiple Search Selection dopdown
2. open the dropdown and keep adding the options

**Comment by Yrlish** [comment]
I too, have a multiple search selection in a modal. I do not experience this issue probably because it's on its own row that spans over the modal's total width.

But in any case, you should try to properly use the `ui grid`, `row`, `column` and the `ui form`, `fields`, `field` classes.
