### ISSUE TITLE
Center aligned fluid buttons

### ISSUE THREAD

**Issue by italomaia** [Semantic-Org/Semantic-UI#6065]
```
<div class="fluid ui vertical basic buttons">
      <button class="fluid ui button">One</button>
      <button class="fluid ui button">Two</button>
      <button class="fluid ui button">Three</button>
</div>
```

Shouldn't the buttons text above be center aligned? Adding "center aligned" also changes nothing.

**Comment by lubber-de** [comment]
Fixed for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/772
See https://jsfiddle.net/0x3jntob/
