### ISSUE TITLE
Update Font Awesome to v5

### ISSUE THREAD

**Issue by michaelimperial** [Semantic-Org/Semantic-UI#6071]
https://fontawesome.com/ has a new expanded/refined icon set for v5

**Comment by hammy2899** [comment]
I have made a port of the new FontAwesome with all the new icons and have setup aliases so there should not be any compatability issues.

You can look at the merge request here https://github.com/Semantic-Org/Semantic-UI/pull/6085

**Comment by mcrawshaw** [comment]
Now released, please close @michaelimperial
