### ISSUE TITLE
"Middle aligned" can not make grid vertically center anymore

### ISSUE THREAD

**Issue by 129emma** [Semantic-Org/Semantic-UI#6077]
I was trying to use `ui middle aligned` grid to make grid vertically center. However, even I totally copy code from the website https://semantic-ui.com/collections/grid.html#vertical-alignment2 . It still not working. Please see the example https://jsfiddle.net/whp895vb/5 . 
I used this last year and it worked very well, I don't know why this attribute doesn't work anymore.

Thank you.

**Comment by Bdthomson** [comment]
I have noticed the same issue.

**Comment by shahyash1993** [comment]
Still the issue is present.
