### ISSUE TITLE
Two Way Data Bind in Dropdown with Vue JS

### ISSUE THREAD

**Issue by jackrsantana** [Semantic-Org/Semantic-UI#6079]
Can anyone please tell me if it is possible to make the Semantic UI dropdown work together with Vue JS?

https://codepen.io/anon/pen/KZQoXe?editors=1010

I would like to define a variable in the v-model property and whenever the variable was changed, change the value selected in the dropdown as well.

**Comment by Patryk27** [comment]
You would have to add an `onchange` event handler manually (`$('.ui.dropdown').on('change', ...)`) and then pass Vue the updated value... but don't go that way, don't mix Vue with jQuery.

Maybe consider using `vue-multiselect` for example?

By the way, there's a Vue-Semantic plugin, if you want to use it - https://semantic-ui-vue.github.io/ - but I recall it doesn't have any dedicated select implemented yet.
