### ISSUE TITLE
Popup message stuck on hover event

### ISSUE THREAD

**Issue by alihalabyah** [Semantic-Org/Semantic-UI#608]
When using the popup functionality on a button connected with a click event the popup sometimes creates a div but it won't remove it when hovering out of the button so when hovering again, another div will show on top of the current one.

**Comment by yuhong-l** [comment]
@jlukic  @alihalabyah  Is this bug fixed? I encountered this one too and didn't find it in PR.

**Comment by etshy** [comment]
Make a jsFiddle to reproduce your problem.
It will help maintainers to find and fix the bug.

**Comment by yuhong-l** [comment]
@etshy  http://jsfiddle.net/k7h5y3gL/
Is it because my 'menuItem' too heavy for this Popup component? Or am I using it in the wrong way.

**Comment by etshy** [comment]
I don't contribute (yet) to this project, I only try to help a bit.
So maybe you have to tag a member or jlukic ?

btw, on your jsFiddle I can't see anything but a "x" on the result frame.

**Comment by hammy2899** [comment]
As @etshy has said your JSFiddle doesn't contain an example. Try saving it and relinking.

**Comment by yuhong-l** [comment]
@hammy2899  hard to repo....
All I could tell you is that 
 <Popup
                ...
                onClose={this.onclose}
                 trigger={<MyButton>}
            />

I specially add a callback function this.onclose for props:   onClose?: (event: React.MouseEvent<HTMLElement>, data: PopupProps) => void

The experiment result is: 
If I hover my mouse on the Popup element, then it pop up 'words' as expected.
After that if I click the Button to trigger something, and slowly(or in normal speed) move my mouse out of the Popup element, the hovering 'words' will disappear as expected.

However, 
If I hover my mouse on the Popup element, then it pop up 'words' as expected.
After that if I move my mouse out of the Popup element **fast enough**, the hovering 'words' will not disappear but keep showing as my mouse is still hovoring on it.

**Comment by etshy** [comment]
You are talking about Component, maybe you would like to ask on the React repo for Semantic-ui : https://github.com/Semantic-Org/Semantic-UI-React ?

This repo is for jQuery usage.

**Comment by yuhong-l** [comment]
sorry~my bad...
