### ISSUE TITLE
Inline drop-down field size issue

### ISSUE THREAD

**Issue by rohan2388** [Semantic-Org/Semantic-UI#6080]
Take a look at the image below.  Looks like a bug to me.
**#1** Can we have dropdown width to match the largest list  item? So we won't have this issue. 
**#2** Or maybe set width of the field itself to match the largest list item?

![input _ semantic ui - google chrome 2018-01-10 01 33 24](https://user-images.githubusercontent.com/20577654/34740875-e26e46f6-f5a6-11e7-81f8-b827926ddf44.png)

**Comment by peterrobertz** [comment]
it works for me; maybe i am missing something; could you please provide a jsfiddle?

**Comment by rohan2388** [comment]
Hi there, sorry I was away last few days. I will be posting jsfiddle tomorrow when I am back to work.
