### ISSUE TITLE
how to pass data from one modal to another modal

### ISSUE THREAD

**Issue by Prasadu112** [Semantic-Org/Semantic-UI#6082]
hello,
Im new to this semantic ui, can anyone help me with this issue please

I have a modal which contain textbox, when the button is clicked the value of the textbox it has to sent to another modal using Multiple Modals

**Comment by NoSoyTsundere** [comment]
If you invoke the modals from the same js file you can store the textbox value in a variable and access it from the other modal.

This should look something like this:
```javascript
var textboxVal; // Will make textboxVal accesible on all subsequent code
function closeModal() {
  textboxVal = document.getElementById('textboxId').value;
  $('.your.modal').modal('hide');
  openOtherModal();
}
function openOtherModal() {
  $('.other.modal').modal('show');
  // textboxVal is accesible with the old textbox value
}
```

**Comment by Prasadu112** [comment]
Thank you so much @NoSoyTsundere I got the solution
