### ISSUE TITLE
[Flag] Burma/Myanmar flag is out of date

### ISSUE THREAD

**Issue by mweiczorek** [Semantic-Org/Semantic-UI#6083]
https://en.wikipedia.org/wiki/Flag_of_Myanmar

The flag was changed back in 2010.

Edit: Libya's is outdated as well.

**Comment by lubber-de** [comment]
For version 2.9 of the community Fork Fomantic-UI, the sprite flags are going to be replaced by the same SVG icons, so every missing country code flag will be supported while the syntax stays backward compatible
https://github.com/fomantic/Fomantic-UI/pull/1190

See your missing (new) flag here https://jsfiddle.net/lubber/nyapwr9L/13/
