### ISSUE TITLE
Is it possible to do an accordion that is opened by a button?

### ISSUE THREAD

**Issue by jackttcoms** [Semantic-Org/Semantic-UI#6087]
Im trying to make it so that when you click a button it expands and shows more content. Is this possible in Semantic UI because i can't figure out or find anything on how to do it

Thanks

**Comment by 1-14x0r** [comment]
try
```
$('.trigger.example .accordion')
  .accordion({
    selector: {
      trigger: '.title .icon'
    }
  })
;
```

you can specify any css selector you want to trigger it. or you could use http://api.jquery.com/trigger/ to trigger the title being clicked on.
