### ISSUE TITLE
dropdown initialization issue:  v2.2.12

### ISSUE THREAD

**Issue by emeunier** [Semantic-Org/Semantic-UI#6088]
Hello, I'm trying to initialize my component with values and the `onChange` event always triggers, even if `fireOnInit` is set to false.

Found while debugging that the module variable `initialLoad` is not set, therefore the `module.is.initialLoad()` function returns undefined instead of false (i assume).

Please help!

**Comment by peterrobertz** [comment]
do you have a jsfiddle for this please?

**Comment by emeunier** [comment]
Hello there,

[http://jsfiddle.net/shdLrafd/6/](url)

Thanks
