### ISSUE TITLE
How to get menus to change active selection. (Documentation)

### ISSUE THREAD

**Issue by jagooding** [Semantic-Org/Semantic-UI#609]
I am trying to figure out how to get menus to change the active selection on a click, like in 
http://semantic-ui.com/collections/menu.html

I've got a fiddle set up here, where as you can see, it doesn't update the active selection upon clicking.
http://jsfiddle.net/xLTuJ/6/

**Comment by gurutvakarshan** [comment]
hi jlukic,
i tried your **Simple activate example** with Tabular menu for my site and its working for me, but its state just show and go like blink.it is not staying activate at all.what to do sir? also how can i learn ui's jquery as you explain in your example.

**Comment by simon3671** [comment]
any luck with this gurutvakarshan? having the same problem.
