### ISSUE TITLE
Multiple sidebars with different 'dimPage' options

### ISSUE THREAD

**Issue by guiguitcho** [Semantic-Org/Semantic-UI#6091]
Hello
The problem appears with two sidebars with different dimPage options (one true, one false) that can be be toggled independently. When the one with the false option is open, there is no dimmer as expected. However if the second one with the dimmer active is toggled while the other is open, there is no dimmer neither, which is not expected. It seems a bug to me. 
Here is the working example [JSFiddle](https://jsfiddle.net/1nt2ab1q/).

**Comment by peterrobertz** [comment]
whats about removing your settings; then it works as expected, right?

https://jsfiddle.net/ubfggfgp/

**Comment by guiguitcho** [comment]
Yes it does but in that case both sidebars have the same dimPage option, which is not why I want.
The problem appears when one wants 2 sidebars with different options. In that case, even by defining different settings in each, they are acting the same way...
