### ISSUE TITLE
Accordion, title link too long: max-width not on the link? With label or text.

### ISSUE THREAD

**Issue by johnunclesam** [Semantic-Org/Semantic-UI#6092]
Asked here also, but not a React problem: https://github.com/Semantic-Org/Semantic-UI-React/issues/2439

### Expected Result

Link just on the label, not all the title line (mouse icon at least).

In the above screen I can click where is yellow painted.

**The problem is not only with label. Also with text only.**

### Actual Result

![image](https://user-images.githubusercontent.com/21275217/34987215-abd0c74a-faba-11e7-8dc7-5c07122d2a61.png)

### Version
0.77.2

### Testcase
https://codesandbox.io/s/p5vl9wp06q

**Comment by peterrobertz** [comment]
i thinks thats the correct behavior. if you want to make the accordion title only as big, as its content - just give the .title this: display: inline-block

**Comment by johnunclesam** [comment]
If I use `display: inline-block` it show me list like this:

- Title - Title - Title - Title - Title - Title - Title - Title

instead of:

- Title
- Title
- Title
- Title
- Title
- Title
- Title

**Comment by johnunclesam** [comment]
Maybe I can use `<br>` before every title? But how? It is a best practice?

**Comment by johnunclesam** [comment]
Reopen, mr. @stale.
