### ISSUE TITLE
Totally missing the point of this, or?

### ISSUE THREAD

**Issue by sabsaxo** [Semantic-Org/Semantic-UI#6094]
OK, so I've installed, and built and yadda yadda. But I seem to be totally missing the point of this project. I was expecting to see and index.html file, that I could open and see all the components rendered in their glory for me to scroll through, modify in code and copy paste into my own projects.

So basically understood this to be a component library (or pattern library)?

**Comment by peterrobertz** [comment]
you can use the documentation for this; why the extra need for an index.html with all components inside?
