### ISSUE TITLE
What paint can icon?

### ISSUE THREAD

**Issue by sabsaxo** [Semantic-Org/Semantic-UI#6095]
Under Theming I see this line:
```
To get started click **the paint can** icon next to the notification button in the top right
```
But there's no paint can icon to be found anywhere (nor notification button in the top right)?

**Comment by peterrobertz** [comment]
http://semantic-org.github.io/example-github/ look top-right, a small outlined greyish paint icon

**Comment by sabsaxo** [comment]
Thanks, but I was reading this in the context of the Getting Started guide, so this sentence is referring to a link earlier in the article.

For better communication it should read »To get started click **the paint can icon** next to the notification button in the top right of the [example project](http://semantic-org.github.io/example-github/)«
