### ISSUE TITLE
semantic modal position centering

### ISSUE THREAD

**Issue by chethan1095** [Semantic-Org/Semantic-UI#6096]
The position of modal is not in center for the first time later from second click it is working fine what may be the problem any solution??

**Comment by peterrobertz** [comment]
how do you call the modal? a piece of code would be nice

**Comment by chethan1095** [comment]
$('#searchclient').modal({
            closable: false,
            onDeny: function () {
                return false;
            },
           
            onApprove: function () {
                return false;
            },
            onDeny: function () {
                return false;
            },
            onHide: function () {
               // Events.trigger("LXE:RELOAD:Request");
            },
            transition:"scale"
        })
            .modal('refresh')
            .modal('show')

**Comment by peterrobertz** [comment]
looks good; the refresh is triggering me; could you provide a minimal jsfiddle?

**Comment by elisaado** [comment]
I've got the same issue. I can't reproduce it in jsfiddle though :/
