### ISSUE TITLE
Move semantic.json into the right place!

### ISSUE THREAD

**Issue by sabsaxo** [Semantic-Org/Semantic-UI#6097]
Put it into the folder you specify here (and here 'semantic/' if the user choose the default):

```
Where should we put Semantic UI inside your project? semantic/
```
So that we don't have to mess around figuring out why it's doing nothing, and then finally have to move it there ourselves manually, thanks. ; )

**Comment by peterrobertz** [comment]
I believe the semantic.json is put into root of your project, because of the ability to update/install your project, if you dont have a semantic folder.
