### ISSUE TITLE
Easily replacing bootstrap with Semantec on an existing project

### ISSUE THREAD

**Issue by vinnytroia** [Semantic-Org/Semantic-UI#6101]
Hi all -
I have a dynamic php project that was developed using bootstrap. I would like to replace it's basic styling with semantec. Is there an easy way to do this? If I just place the bootstrap JS and CSS files with the corresponding semantec ones, would that work? I imagine the css class names will be different, so what are my options. 
In the Semantec examples, I see the Bootstrap migration page, but not really sure what to do with it. 

I don't suppose there is a Semantec CSS file that can just easily be popped-in?

thanks

**Comment by 1-14x0r** [comment]
if only it was that easy. You will have to port all of the components to use the related semantic names, as well as update the css names. there is no migration tool that i know of.
