### ISSUE TITLE
[Modal] - Scrolling fullscreen modal adds a second scrollbar at the page level when resolution is too small

### ISSUE THREAD

**Issue by virulentt** [Semantic-Org/Semantic-UI#6107]
**Steps to Reproduce**
1. Create a fullscreen scrolling modal and open it. (Content has to be huge so the scrollbar appears)
2. Change your window size.
3. Another scrollbar appears at the page level(on the right of the window).

**Expected**
The Modal should resize correctly without adding another scroll bar

**Result**
The Modal seems to have a bad calculation for the margins.

**Testcase**
http://jsfiddle.net/kduju5dv/2/

**Comment by lubber-de** [comment]
Fixed in the latest Version of SUI
See http://jsfiddle.net/7at394z1/

**Comment by joetm** [comment]
Same thing applies when adding an overlong sidebar component.
The two scrollbars overlap each other. They look the same. And they behave in weird ways when using the mouse scroll wheel. Sometimes you'd be scrolling the sidebar, other times the whole page.
