### ISSUE TITLE
Left and right margins are incorrect when Tab has more than 4 tabs

### ISSUE THREAD

**Issue by hegyitaho** [Semantic-Org/Semantic-UI#6112]
Similar to #4167 but for the right and left margins.
http://jsfiddle.net/tpy65sup/1/

**Comment by GuacheSuede** [comment]
#6109

**Comment by lubber-de** [comment]
This has been fixed in the community fork Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/1480
See your adjusted jsfiddle here http://jsfiddle.net/lubber/d8n3hq2p/1/
