### ISSUE TITLE
[Grid] - Buttons overlapping each other inside a column on resize

### ISSUE THREAD

**Issue by abhigyantiwari** [Semantic-Org/Semantic-UI#6115]
**Expected**
There should be space between buttons

**Result**
Buttons start to overlap after browser resize

**Testcase**
Applied stackable, relaxed grid classes. Didn't help.

Here is my code...
```
<div class="ui stackable grid">
		<div class="ui three column row">
			<div class="column"></div>
			<div class="column">
				<h1 style="color: white; font-family: 'Dosis', sans-serif;">You are..</h1>
				<div class="ui relaxed grid">
					<div class="four column row">
						<div class="column"><a href="" class="ui green button">Teacher</a></div>
						<div class="column"><a href="" class="ui green button">Parent</a></div>
						<div class="column"><a href="" class="ui green button">Principal</a></div>
						<div class="column"><a href="" class="ui green button">Student</a></div>
					</div>
				</div>
			</div>
			<div class="column"></div>
		</div>
	</div>
```

Laptop:
![capture2](https://user-images.githubusercontent.com/16822592/35284796-b5eb1d3a-0081-11e8-813b-2fe6003bb08b.PNG)

Tablet:

![capture](https://user-images.githubusercontent.com/16822592/35284803-bcf6e5f0-0081-11e8-9c22-0e3550d2be75.PNG)

**Comment by abhigyantiwari** [comment]
Pls Haaalp!

**Comment by GuacheSuede** [comment]
#6109

**Comment by abhigyantiwari** [comment]
Let's hope it's true that they are working on V3 ad mentioned in ticket you provided! 💯

**Comment by GuacheSuede** [comment]
@abhigyantiwari Doubt so, because they are struggling to find funding
