### ISSUE TITLE
popup.js and possible other modules wrong check of svg support

### ISSUE THREAD

**Issue by Avivonz** [Semantic-Org/Semantic-UI#6118]
#3175 In popup.js line 418, it checks :
`return (typeof SVGGraphicsElement === 'undefined');`

And says it supports it if it returns true, while it will obviously return false, because it does exist.

Fix :
`return (typeof SVGGraphicsElement !== 'undefined');`

**Comment by GuacheSuede** [comment]
#6109

**Comment by lubber-de** [comment]
Fixed since 2.6.4 https://github.com/fomantic/Fomantic-UI/pull/247
