### ISSUE TITLE
Is it possible to Trigger Pop-up in select element using Semantic-UI

### ISSUE THREAD

**Issue by jason-migz** [Semantic-Org/Semantic-UI#6122]
i already tried popup in input and button, it works totally fine but in select it doesnt work. any idea why?
here is the code:
> here is the html code;
` <div class="field">
        <label>Machine No.</label>
        <select class="ui fluid dropdown" id="machine_no" name="machine_no">
         <option selected value="">Select Machine No.</option>
         <option  value="1">1</option>
         <option  value="2">2</option>
         </select>
      </div>`

> here is the js code;
`  $('#machine_no').popup({
     inline     : true,
     hoverable  : true,
     on         : 'hover',
     position   : 'top center',
     delay: {
     show: 100,
     hide: 300
     },
     title: 'testing'})`

**Comment by GammaGames** [comment]
?
https://jsfiddle.net/hw5xfscx/

**Comment by jason-migz** [comment]
thanks but in me it didnt work. but i will figure this out. thank you.

**Comment by jason-migz** [comment]
thank you. but in me it didnt work.

**Comment by jason-migz** [comment]
the solution to this problem is by removing this code:

$('.ui.dropdown').dropdown({
on: 'hover'
});
