### ISSUE TITLE
Custom UI Theme Using semantic-ui-less package

### ISSUE THREAD

**Issue by kerry-money** [Semantic-Org/Semantic-UI#6129]
How do I use a custom theme for semantic ui using the semantic-ui-less package?  In other words, how do I avoid having to copy the whole semantic ui project into my project when theming semantic ui?  If I can use a custom theme in my project and point to the semantic package, I can get updates to the css framework without having to re-download the project.

I was thinking of doing this, but I was running into issues, because internally, the definition/component/element files refer to ../../theme.config, which is a path relative to the files in node_modules.  I saw an article that suggested aliasing ../../theme.config to point to my own theme.config, but this seemed like a hack.

Has anyone else solved this problem?

**Comment by sancarr** [comment]
Hello there,

Here is a detailed breakdown of the process: https://medium.com/webmonkeys/webpack-2-semantic-ui-theming-a216ddf60daf
