### ISSUE TITLE
Modal: Bad position on second show

### ISSUE THREAD

**Issue by mishak87** [Semantic-Org/Semantic-UI#614]
When modal showed for second time it "falls" half bellow screen.

``` js
var self = $('.ui.modal');
self.modal({
  onShow: function () {
    self.modal('refresh'); // does NOT help
    setTimeout(function () {
      self.modal('refresh');
    }, 1000); // does help 1s is probably overkill
  }
});
```

My uneducated guess is position is computed and set only first time when modal is shown and second time default CSS makes it fall.

Modal includes some generated items by KnockoutJS but items are not added between shows.

**Comment by MadisonRong** [comment]
@eserini I got the same error even my version is 1.11.5

**Comment by jlukic** [comment]
@eserini I've removed those lines from #2576. Check against `2.0.3.` when I release today.

**Comment by fuatsengul** [comment]
I was getting same problem at 2.0.7, and @kwolniak's solution fixed my problem for now.

**Comment by jlukic** [comment]
If someone has a test case let me know

**Comment by speciose** [comment]
Yeah, somehow `modal('setting') solve this issue. (Win 10, Firefox 40, Semantic UI 2.0.8)
Problem appears when you start using parameters (settings) for modals:
```
.modal("show") //works great
.modal({allowMultiple: false}).modal("show") //works bad
```
So I've end up with:
```
.modal('setting', {allowMultiple: false}).modal('show')
```

**Comment by jlukic** [comment]
Still having issues reproducing this
http://jsfiddle.net/h3oxngx7/

**Comment by fuatsengul** [comment]
I think the content is the problem. 
I use a dynamically rendered content (meteor-autoform) and it creates DOM contents when the modal has shown. I see very fast transition that the modal loading into screen with no content and after it grows with the content. But it won't fill the screen. It's keeping the start position same as empty state.

**Comment by fuatsengul** [comment]
observeChanges just saved my life :)
Probably it will solve everyone's problem :)

```
$('.myModal')
      .modal( {
        observeChanges: true,
      })
      .modal('show');
```

**Comment by Kyezil** [comment]
Had same issue, only with "basic" modal though.
Also solved with:
`.modal('setting', {}).modal('show')`
instead of
`.modal({}).modal('show')`

**Comment by MrOutput** [comment]
Yes, passing in an object on modal instantiate is not working correctly, please fix asap.

**Comment by MrOutput** [comment]
+1

**Comment by David-Tsui** [comment]
I encountered a problem alike.
I used multiple select dropdown, then click the generated label in the input place to open the modal;
however, every first time the label been clicked, the place of modal is bad.
I wonder that is there someone has some problem?

Test case (It's Chinese, but just click and don't worried that lol.)
http://speechlab.cs.nchu.edu.tw/project2/

**Comment by David-Tsui** [comment]
How about the image loaded in modal?
I can not make the modal locate in correct location if the image contents in modal are generated before modal showing.

**Comment by DavidePastore** [comment]
Thanks @speciose and thanks @Kyezil, your solutions work!

**Comment by adhatama** [comment]
The solution from @speciose and @Kyezil works for me. Thanks!

**Comment by dubsky** [comment]
For me this issue happens when I set detachable:true. 
When I applied the solution mentioned above, the detachable setting was not applied and therefore the positioning problem disappeared.

I looked into the code and the problem is when detachable=true, on the second show the modal content height is evaluated on a hidden element (too soon) and evaluates to 0, which is wrong.

As a workaround I used the following:

        $('#xxx').modal({ detachable:false, observeChanges:true }).modal('show').modal('refresh');

**Comment by Andrew1431** [comment]
None of these fixes are working for me. I have a long form that extends past the page. All works fine, until I have scrolled down and press submit. Upon pressing submit, the modal jumps down and has a huge top margin and is cut off at the bottom of the screen. (Because of a error messages div opening up with a list of all the form invalidation)

trying the `.modal('setting', { ... })` is not working for me. Refresh, etc nothing is working :)

**Comment by bmalum** [comment]
doubled (2nd delayed for 100ms) refresh does recenter the Modal - but does not look nice :/

**Comment by VasilyShelkov** [comment]
so in my case despite doing 
```
$('.ui.modal')
.modal('attach events', '.button', 'show')
.modal('setting', {
	detachable: false,
	observeChanges: true,
	blurring: true,
	transition: 'vertical flip'
});
```

Although after doing some CSS comparisons with the examples in the docs, I found that the only difference and what was causing this is some file that just does not exist and isn't mine in http://localhost:8080/scss/_modal.scss which is applying this css to the modal

```
.modal {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1050;
    display: none;
    overflow: hidden;
    -webkit-overflow-scrolling: touch;
    outline: 0;
}
```

Any ideas why this is ?

**Comment by aborn** [comment]
@dubsky 's solution can fix the similar problem

**Comment by haneefkassam** [comment]
OP's workaround (setting timeout onShow) was the only thing that worked for me (tried all the workarounds posted on this issue).

**Comment by fuatsengul** [comment]
My observation:
Problem happens when modal content creating dynamically and changing the content before second show. So modal calculates its vertical centering offset first and it's getting wrong after content has changed.

So my solution is deleting and re-creating whole element rather than replacing its content.

If your environment is similar of mine, it's solid solution.

BTW: add a little delay between creating element and calling it.

**Comment by hitchcott** [comment]
@fuatsengul bingo. `setting` breaks react unfortunately, but your solution worked.

```
    this.setState({ modal: args });
    setTimeout(() => {
      $modal.modal('show');
    }, 1)
```

**Comment by jiang-ning** [comment]
hey guys, I meet the same problem on "semantic-ui#^2.1.8", I replaced two css defines in my custom css file(because the whole semantic-ui in my .gitignore), and it works fine for me:
`@media only screen and (max-width: 767px) {
  .ui.modal {
    margin: 0 auto;
    left: 0;
  }
}
@media only screen and (min-width: 768px) {
  .ui.modal {
    margin: 0 auto;
    left: 0;
  }
}
`
the 'left:0' is for replace 'left:50%' in class '.ui.modal'

**Comment by raviroyind** [comment]
This is still a bug, modal opens at different position when opened second time.

**Comment by blacksmithblack** [comment]
setTimeout works for me.

Is this problem due to the positioning taking place before the modal has fully loaded?

**Comment by mklnz** [comment]
I'm using Semantic UI with Ember and having the same issue. I've tried all the fixes detailed here and I'm not really having any luck. setTimeout works, but over a slow connection this can be unpredictable.

**Comment by blacksmithblack** [comment]
@mklnz ... I ended up loosing the modal ... I tried the following but it caused more problems further down the line. It goes through any div's inside the modal, calculates their individual height and changes the height of the modal.

`$(modalID).children().each(function (index, object) {
        modalHeight += $('#' + object.id).outerHeight(true);
      });
      $(modalID).animate({height: modalHeight},400);`

If you are having problems over slow connections use the 'onVisible' call back?

**Comment by bartoszkwiedacz** [comment]
I have the same problem.
First fire of modal:
<div class="ui modal image-comment scrolling transition visible active" style="top: 0px; display: block ! important;">
Second fire:
<div class="ui modal image-comment transition visible active" style="margin-top: -143.5px; display: block ! important;">

Also in second time there is no scrolling class on dimmer element.

**Comment by mklnz** [comment]
After digging around I find the problem with my case is Ember inserts and updates the DOM dynamically, and inserts an image inside the modal div. However, this image has not started loading yet, hence the overall height of the modal container is 0.

Semantic then calculates this as 0 and then shows the modal as margin-top of 0 (calculated). Only after the image actually loads the container has a height, in which case the centering is now incorrect.

I suppose I can find some way to "preload" the image perhaps, before showing the modal?

**Comment by raviroyind** [comment]
Entire Semantic-UI framework is fucked up with lots of bugs, the toggle switch does not work after opening & closing modal. I am switching back to bootstrap.

**Comment by neokio** [comment]
Thank you @kwolniak and @fuatsengul ... the combination of your discoveries solved my problem.
For me, the only thing that worked was this:

```javascript
	$('#modal').modal(
		'setting', {
			observeChanges: true,
			// other params here
		}
	);
```

**Comment by chized** [comment]
Mine issue was the modal disappears in two seconds, and the content needs to be read. solved it by using the <button> tag instead of the <a> tag I used, though class remain same as ui button.

**Comment by amitpatil321** [comment]
.modal{
  height: 500px !important;
}

I dont know how but this solution worked for me. I have 3 modal closing and opening after another. and they are in a loop.

**Comment by daneprime8** [comment]
Is there a solid workaround for this yet? I'm getting the same issue. On first open, it's perfectly centered on the screen. On second open, It's position at the top of the screen. I've tried recommendations here but no luck :/

**Comment by skwny** [comment]
Is there a solid workaround for this yet? I'm getting the same issue. On first open, it's perfectly centered on the screen. On second open, It's position at the top of the screen. I've tried recommendations here but no luck :/

**Comment by Practice0** [comment]
My solution was to brute force the css ie
$(“#modal”).modal({
   onDeny: ...
   onApprove: ...
}).modal(“show”);

$(“#modal”).attr(“style”, “top: 10px”);

So I replace the inline styles put in by Semantic UI with my own positioning. In my personal case, it hasn’t broken anything else and seems to be consistently working. I also don’t need it to follow an element but just to show up in full-screen mode in the same position on each open so this works fine for me. Hope this helps!

**Comment by skwny** [comment]
Thanks for that. Unfortunately I went ahead and made a reusable modal :/ Not as good as semantic but what can you do?

**Comment by magiksd** [comment]
Hello, I have this issue too, but only in Firefox. For my project, I have fixed it by scrolling the dimmer to 0 :
```
$('#modal').modal('show');
$('.ui.modals.page.dimmer')[0].scrollTo(0, 0);
```

**Comment by MahmonirB** [comment]
I solved it,
Go to main.js in js folder and change overflow from visible  to hidden  in this code: $('body').delay(350).css({'overflow': 'hidden'});
