### ISSUE TITLE
[Dropdown] [v2.2.14] Multiple Dropdown pre-"selected" Options not visible

### ISSUE THREAD

**Issue by romanzipp** [Semantic-Org/Semantic-UI#6145]
When displaying a `<selection multiple>` with pre-selected Options, these options will not be displayed to the HTML.

**This bug is existing after upgrading to 2.2.14**

**Example - before JS initialized** (T1 will not be shown)
```html
<select multiple class="ui dropdown">
  <option selected>T1</option>
  <option>T2</option>
  <option>T3</option>
</select>
```

## 3/3 options selected
No Option gets displayed (selection active)

![2018-02-07 17_58_18-video 1 - pietsmiet admin opera](https://user-images.githubusercontent.com/11266773/35930251-b7659558-0c31-11e8-95d1-332fd69a39ce.png)

![2018-02-07 18_00_37-video 1 - pietsmiet admin opera](https://user-images.githubusercontent.com/11266773/35930254-b92ddf12-0c31-11e8-9b5d-4673b0e812da.png)

## 2/3 Options selected
Only the not-selected Option gets displayed and is selectable (selection active)

![2018-02-07 18_01_49-video 1 - pietsmiet admin opera](https://user-images.githubusercontent.com/11266773/35930258-bd39a172-0c31-11e8-9419-7bbe356752d2.png)

![2018-02-07 18_01_31-video 1 - pietsmiet admin opera](https://user-images.githubusercontent.com/11266773/35930261-bec8f2a4-0c31-11e8-979c-73ccf3ae77fb.png)

**When selecting T2, the expected behavior is shown until page refresh**

![2018-02-07 18_09_31-video 1 - pietsmiet admin opera](https://user-images.githubusercontent.com/11266773/35930424-256919ee-0c32-11e8-8229-0c14d75f20ff.png)

**Comment by GammaGames** [comment]
#6123

**Comment by camueller** [comment]
I noticed this problem as well. After downgrading to 2.2.12 pre-selected options are displayed properly!

**Comment by qingquanwang** [comment]
:+1:

**Comment by prudho** [comment]
Duplicate #6123
