### ISSUE TITLE
getting unexpected token for import_url in semantic.css file 2.2.14 !

### ISSUE THREAD

**Issue by ct-ferozakbar** [Semantic-Org/Semantic-UI#6151]
Hi,
I have simply cloned this repo and included the files as below (Semantic UI - 2.2.14)
```
<script type="text/javascript" src="Semantic-UI/dist/semantic.min.css"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="Semantic-UI/dist/semantic.min.js"></script>
```
Im getting 'invalid or unexpected token' in semantic.css file for the below line

`@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);
`

### [screenshot url](http://ibb.co/i6eWBH)

im able to open this link in browser (i'm from india)

However if im using the CDN link of this Css file then i'm not getting any issue!
help me to fix this

**Comment by hammy2899** [comment]
This is simply because your trying to load the `semantic.min.css` file using a `<script>` tag not a `<link rel="stylesheet">` tag.

**Comment by ct-ferozakbar** [comment]
how the hell did i missed it (facepalm) ,thanks
