### ISSUE TITLE
[Dropdown] Search dropdowns don't hide dividers

### ISSUE THREAD

**Issue by neokio** [Semantic-Org/Semantic-UI#6173]
Here is a standard `ui search selection dropdown` in Semantic UI v2.3:

![screen-shot-2018-02-20-at-12 55 37 amb](https://user-images.githubusercontent.com/146623/36413083-18591522-15da-11e8-8c92-4c64f78b2419.png)

**Take note of the dividers** (such as the one above "Other".

Now observe what happens after entering `pote` in search:

![screen shot 2018-02-20 at 12 56 43 am](https://user-images.githubusercontent.com/146623/36413210-9d11af7c-15da-11e8-8bae-0e39a18f0b69.png)

See how the two dividers are still there below "Potential Employee"? This gets pretty gnarly with larger lists.

I'd suggest hiding `.ui.search.selection.dropdown > .menu > .divider` via javascript whenever search is triggered, and un-hiding them when it's empty.

**HTML**:
```html
<div class="field">
  <label>Phone Type</label>
  <div class="ui search selection dropdown">
    <input type="hidden" name="type_id">
    <i class="dropdown icon"></i>
    <div class="default text">Phone Type</div>
    <div class="menu">
      <div class="item" data-value="1">Sales Lead</div>
      <div class="item" data-value="2">Distributor</div>
      <div class="item" data-value="3">Potential Distributor</div>
      <div class="item" data-value="4">Postal</div>
      <div class="item" data-value="5">Freight</div>
      <div class="item" data-value="6">Maintenance</div>
      <div class="item" data-value="7">Potential Employee</div>
      <div class="divider"></div>
      <div class="item" data-value="8">Family</div>
      <div class="item" data-value="9">Friend</div>
      <div class="item" data-value="10">Douchebag</div>
      <div class="divider"></div>
      <div class="item" data-value="1000">Other</div>
    </div>
  </div>
</div>
```

**JS**:
```javascript
$('.ui.search.selection.dropdown').dropdown({
  // true, false and 'exact' all have this issue
  fullTextSearch: 'exact'
});
```

**Comment by hammy2899** [comment]
I agree with this, I have created a jsfiddle to to replicate the issue https://jsfiddle.net/52yb48uh/

**Comment by jlukic** [comment]
This use case isnt specifically supported in docs. This would be a feature enhancement.

**Comment by neokio** [comment]
Bump.

**Comment by lubber-de** [comment]
Option `hideDividers` available in https://fomantic-ui.com/modules/dropdown.html#/settings
