### ISSUE TITLE
2.3, mail icon is different and I can't find it in icons list page.

### ISSUE THREAD

**Issue by johnunclesam** [Semantic-Org/Semantic-UI#6174]
2.3, mail icon is different and I can't find it in icons list page.

**Comment by hammy2899** [comment]
Good spot, the icon is now called `envelope`, I am going to add an alias for `mail` to help with compatibility.

**Comment by jlukic** [comment]
Should also have `mail`

**Comment by jlukic** [comment]
Fixed in next
