### ISSUE TITLE
[Icon] Incorrect `user circle outline` icon in v2.3.0

### ISSUE THREAD

**Issue by iROCKBUNNY** [Semantic-Org/Semantic-UI#6176]
<img width="392" alt="qq20180220-195401 2x" src="https://user-images.githubusercontent.com/4929394/36422634-df3e4070-1677-11e8-94d3-07914579589d.png">

**Comment by hammy2899** [comment]
I can confirm `user.circle.outline` displays the incorrect icon.

**Comment by iROCKBUNNY** [comment]
@hammy2899 could you please also help label this bug? This looks quite critical. Thanks a lot!

https://github.com/Semantic-Org/Semantic-UI/issues/6123

Sorry I mentioned this in the wrong issue tracker.

**Comment by jlukic** [comment]
Confirmed this is fixed in next release #6181
