### ISSUE TITLE
At icon medium size conflict

### ISSUE THREAD

**Issue by RomainSanchez** [Semantic-Org/Semantic-UI#6179]
Hi there, when using ``<i class="medium at icon"></i>`` i get a different icon than  @, regardless of the order of classes.This only happens when using "at" icon in medium size

version 2.2.14

**Comment by hammy2899** [comment]
I can confirm `medium.at.icon` is displaying `medium.icon`

**Comment by RomainSanchez** [comment]
Sam eissue with .medium.trash.icon

**Comment by TheHene** [comment]
@RomainSanchez if u want to change the size of an icon u need to use:
![grafik](https://user-images.githubusercontent.com/25691194/36445889-e064ea32-167f-11e8-8554-2f5278f3f7af.png). `medium` is an icon:
![grafik](https://user-images.githubusercontent.com/25691194/36446047-58f73f2c-1680-11e8-8ef5-fa6c5003717f.png)

**Comment by RomainSanchez** [comment]
@TheHene Right.My bad, explicit medium is only for buttons.
