### ISSUE TITLE
"link" icon is displayed instead of the correct icon

### ISSUE THREAD

**Issue by Waals** [Semantic-Org/Semantic-UI#6180]
I just updated Semantic UI, and I noticed that for some icons, when I want a link behaviour on my icon, I instead get the "link" icon.

```html
<!-- Here, "link" icon is displayed instead of "retweet" icon -->
<i class="retweet link icon"></i>
```

I believe this is due to the[ "link" style definition](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/icon.overrides#L408) overriding every previous single-named icon definition.

**Comment by Waals** [comment]
Either the name of the "link" icon or the "link" behaviour (pointer + opacity change on hover) has to change.

**Comment by jlukic** [comment]
There shouldnt be an icon named `link` it should be `linkify`

**Comment by jlukic** [comment]
This is fixed in next.
