### ISSUE TITLE
Unknown prop `aligned` on <div> tag

### ISSUE THREAD

**Issue by ShenAdrada** [Semantic-Org/Semantic-UI#6183]
version 78.2 doesn't seem to recognize 'aligned' prop in the Tab module. do you have any version that don't have this error?

![error aligned](https://user-images.githubusercontent.com/26157352/36461566-2e7cd030-16f9-11e8-952e-82a11bc7dcaa.png)

**Comment by w96k** [comment]
Hey, seems like your problem is using semantic-ui-react, its original semantic-ui repo. 

Report your issue here: https://github.com/Semantic-Org/Semantic-UI-React

**Comment by ShenAdrada** [comment]
@w96k oh. sorry. will close it then. thanks
