### ISSUE TITLE
Circular icons don't display properly in v2.3.0

### ISSUE THREAD

**Issue by avaneev95** [Semantic-Org/Semantic-UI#6184]
There is a problem with icons with circular styles. Some icons are not centered in the circle.
![image](https://user-images.githubusercontent.com/20536879/36468225-947dc6c4-16f3-11e8-86ef-e71ee3941b23.png)
The same problem with .circular.icon.button
![image](https://user-images.githubusercontent.com/20536879/36468196-71810c8a-16f3-11e8-9f54-71055dbdf983.png)

**Comment by avaneev95** [comment]
I think it can be fixed by removing the left and right padding from .circular.icon styles. This seems to be work well both with square and non-square icons since there is text-align: center.

**Comment by w96k** [comment]
@avaneev95 It worked like you said 👍

**Comment by jlukic** [comment]
Fixed in next release
