### ISSUE TITLE
Icon Doc page inconsistencies

### ISSUE THREAD

**Issue by xaeroseven** [Semantic-Org/Semantic-UI#6190]
**_Edit: Looks like a couple of the icon issues have been reported here too: https://github.com/Semantic-Org/Semantic-UI/issues/6175. That being said, there are still a lot of other issues I mention below_**

Love the new addition of Font Awesome 5 to SUI!  Very nice work!  However, I was looking through the categories and noticed several inconsistencies between the Semantic UI Icons doc page and the documentation on Font Awesome's website.

- The `accessible icon` (the modern wheelchair icon) is missing from Accessibility, Health, Users and People, and Vehicles categories (it's in the 'Brands' section only on the SUI doc page, it would be nice to include it in these other categories)
- The youtube icon is missing from the Audio & Video section
- The Chess Rook icon is misspelled in SUI, it has `chess rock`, it should be `chess rook`
- The 'Currency' category icons have several inconsistencies, Bitcoin and others aren't listed here
- SUI has the `user doctor` icon instead of `user md` like in Font Awesome, maybe make an alias so users could use either
- The 'Payments' category icons also have several inconsistencies, amazon and apply pay are missing as well as many others

I also found several other icons that appear to be inaccurate on the docs page.  I've attached images of them.

Thanks so much and let me know if I can help in any way or if you want me to submit a PR for these. Are the main SUI documentation pages something we can submit PR's for?

Best,
-Justin

These are the incorrect icons:
<img width="580" alt="screen shot 2018-02-21 at 12 09 54 pm" src="https://user-images.githubusercontent.com/1595973/36498841-37d6d44e-1705-11e8-9e06-82c400919326.png">
<img width="244" alt="screen shot 2018-02-21 at 12 10 42 pm" src="https://user-images.githubusercontent.com/1595973/36498842-37e35b88-1705-11e8-9ed1-c1eea084eb07.png">
<img width="524" alt="screen shot 2018-02-21 at 12 16 42 pm" src="https://user-images.githubusercontent.com/1595973/36498843-37f0a0f4-1705-11e8-8a7e-bb18b459422f.png">
<img width="174" alt="screen shot 2018-02-21 at 12 16 55 pm" src="https://user-images.githubusercontent.com/1595973/36498844-380207ea-1705-11e8-89b8-31b465a94dc7.png">
<img width="177" alt="screen shot 2018-02-21 at 12 17 09 pm" src="https://user-images.githubusercontent.com/1595973/36498845-38172242-1705-11e8-9f0c-2d5daff54b4a.png">

These are what they should look like based on the FA 5 docs:
<img width="262" alt="screen shot 2018-02-21 at 12 48 06 pm" src="https://user-images.githubusercontent.com/1595973/36499059-c1e26eb4-1705-11e8-93a9-c069ed37fde9.png">
<img width="135" alt="screen shot 2018-02-21 at 12 48 41 pm" src="https://user-images.githubusercontent.com/1595973/36499060-c1f23a92-1705-11e8-82e6-7cb50dae731a.png">
<img width="285" alt="screen shot 2018-02-21 at 12 49 15 pm" src="https://user-images.githubusercontent.com/1595973/36499063-c25bf496-1705-11e8-8c68-8e3444219329.png">
<img width="111" alt="screen shot 2018-02-21 at 12 49 36 pm" src="https://user-images.githubusercontent.com/1595973/36499064-c26c33f6-1705-11e8-8f54-3c3fd638e8c4.png">
<img width="135" alt="screen shot 2018-02-21 at 12 49 40 pm" src="https://user-images.githubusercontent.com/1595973/36499065-c27efafe-1705-11e8-9dc2-f6591228388f.png">

**Comment by hammy2899** [comment]
Thanks for the feedback, the icons which aren't in the categories must have been added after I created the PR because I went through and manually added them (it was time consuming 😆 ).

The icons which are broken I have done a lot of corrections you can take a look [here](https://github.com/Semantic-Org/Semantic-UI/pull/6181). The code icons are broken because the docs has its own code icon which is conflicting with them @jlukic is aware of this.

For all the other suggestions I will look into them and will try and add them to my next patch!

**Comment by xaeroseven** [comment]
😄 No worries, I bet! You did a great job though! Kudos! 

Yeah, it looks like you fixed the arrows alternate horizontal, arrows alternate vertical, and the exchange alternate. It looks like the code, code branch, file code, and file code outline aren't mentioned in that new PR https://github.com/Semantic-Org/Semantic-UI/pull/6181 though. 

Let me know if you have any questions on the others and thanks for the swift reply! You're crushing it @hammy2899 👍

**Comment by jlukic** [comment]
This will be out before Friday with @hammy2899’s work

**Comment by xaeroseven** [comment]
Thanks @jlukic and @hammy2899, we are using Semantic UI in both of our production web apps and have been loving it, keep up the great work!

**Comment by jlukic** [comment]
Changes got delayed, will be out this weekend.

**Comment by jlukic** [comment]
Getting out tonight
