### ISSUE TITLE
[Icon] 'times icon' not showing up

### ISSUE THREAD

**Issue by kaisbe** [Semantic-Org/Semantic-UI#6199]
Hi folks,

first of all, thanks a lot for the amazing project.

I am actually used to show up a times icon within a table cell using the following code:
`
<i class="times icon'"></i>`

However the icon fails to show up although it's not the case whenever I use a different icon class - let's say "check icon" for example ..

Why this is happening?

**Comment by hammy2899** [comment]
What do you mean not showing up, does it show a different icon or does it just not show anything?

**Comment by kaisbe** [comment]
@hammy2899 It shows any different icon from the times icon.

**Comment by hammy2899** [comment]
@kaisbe Can you provide a picture because the `times` icon seems to work for me.

**Comment by kaisbe** [comment]
@hammy2899 As you can see in the following link https://imgur.com/Jv6QBOF, the fourth cell where the class 'times icon' was set, is blank. BTW, I used `<i [ngClass]="iv.v==true? 'check icon': 'times icon'"></i>` for displaying the icons (I use Angular as JS framework).

**Comment by kaisbe** [comment]
@hammy2899 I am using the version 2.2.14.

**Comment by hammy2899** [comment]
Version 2.2.14 does not have a `times` icon I believe it is called `remove`

**Comment by kaisbe** [comment]
@hammy2899  You're right. It shall be 'remove icon', I checked that. But even after upgrading to the latest version, the 'times icon' didn't show up .. What's the version are you using?

**Comment by hammy2899** [comment]
@kaisbe I am using the latest version, 2.3.0

**Comment by kaisbe** [comment]
@hammy2899 Ah ok, it may be a cache problem then. After rebooting my pc, it worked fine, using the latest version. Thanks for your help.
