### ISSUE TITLE
React SUI, Modal inside a Table

### ISSUE THREAD

**Issue by cinjon** [Semantic-Org/Semantic-UI#6200]
Hi, I have a Modal inside a Table like the following. When I click the button to open, two issues arise:

1. It flickers a lot. Looking in the console, this seems to be caused by the scrolling attribute constantly being added and removed. If instead of putting it in the Table I put it outside of the Table, then the issue does not arise. (I actually want to use a Table here though)

2. When I test the above outside of the Table, it's really big. I was aiming for something like the first Modal example on https://react.semantic-ui.com/modules/modal, but instead the modal takes up the whole page and there is a lot of whitespace (because the image and text do not). As mentioned, this is not related to the Table concern.

```
class MyTable extends Component {
  render() {
    var isMe = this.props.isMe;

    return (
      <Table celled striped>
        <Table.Header>
          <Table.Row>
            <Table.HeaderCell textAlign="center">Details</Table.HeaderCell>
          </Table.Row>
        </Table.Header>

        {this.props.data.map((agent, i) => <MyTableRow data={data} defaultOpen={this.props.defaultOpen && i === this.props.data.length - 1} key={i} />)}
      </Table>
    )
  }
}

class MyTableRow extends Component {
  modal() {
    return (
      <Modal defaultOpen={this.props.defaultOpen} trigger={<Button>Click</Button>}>
        <Modal.Header>Detailed Instructions</Modal.Header>
        <Modal.Content image>
          <Image wrapped size='small' src={instructionsImg} />
          <Modal.Description>
            <p>{this.props.data.txt}</p>
          </Modal.Description>
        </Modal.Content>
      </Modal>
    );
  }

  render() {
    var row;
    var isMe = this.props.isMe;
    return (
      <Table.Body>
        <Table.Row>
          <Table.Cell collapsing>{this.modal()}</Table.Cell>
        </Table.Row>
      </Table.Body>
    );
  }
}

```

**Comment by hammy2899** [comment]
This is the repo for SUI not the react version please open this issue on the react repo where they can help you :smile: https://github.com/Semantic-Org/Semantic-UI-React

**Comment by cinjon** [comment]
Ah ok thanks. I thought it was applicable here because it feels like a css issue. Posted there :).
