### ISSUE TITLE
stateContext sets wrong state on api::beforeSend

### ISSUE THREAD

**Issue by MartinWickman** [Semantic-Org/Semantic-UI#6207]
I use `stateContext` to trigger a loader/spinner during an API-call. This works fine, but the problem is the context (this) for `beforeSend` is set to the element matching `stateContext`, *not* the button which initiated the call. This makes it impossible to fetch data from the button (in this case) which is used to populate the request parameters.  According to [the docs](https://semantic-ui.com/behaviors/api.html#/settings), `beforeSend` should have the "initialized element" as context, not the element matching `stateContext`!

The only way around this is to manually add code which enables/disables the spinner using a bunch of callbacks. Unless I'm doing something wrong here, this is clearly a bug.

See the code below for an example.

```
<button class="ui left blue attached button js-assign-all" data-todo="assign">Assign all</button>

$('.js-assign-all')
        .api({
            action: 'assign user',
            method: 'POST',
            stateContext: '.js-project-segment',
            beforeSend: function (settings) {
                settings.data.assign = $(this).data('todo'); // 'this' is NOT the button!
                return settings;
            }
        });
```

**Comment by lubber-de** [comment]
Fixed for Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/498
See https://jsfiddle.net/7oz0bncp/1/
