### ISSUE TITLE
sui site "transition" page: leaf visibility lost when scrolling down

### ISSUE THREAD

**Issue by rnealxp** [Semantic-Org/Semantic-UI#6208]
https://semantic-ui.com/modules/transition.html
Leaf not visible when testing effects after scrolling down on page.

**Comment by jlukic** [comment]
I'll fix this, pretty derpy

**Comment by jlukic** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-Docs/commit/4428ee73d0819c33d4a9545afb4ea19d6ec2e8f5
