### ISSUE TITLE
[Dropdown] Category Search yields duplicate results

### ISSUE THREAD

**Issue by neokio** [Semantic-Org/Semantic-UI#6221]
When searching is set to use multiple fields (such as "category" and "title"), and when the search matches on both category AND title, a category search shows the same line twice.

![screen shot 2018-02-26 at 8 20 13 pm](https://user-images.githubusercontent.com/146623/36708972-ddc0c276-1b32-11e8-9f63-de5355df245c.png)

See [jsfiddle here](https://jsfiddle.net/f3wur1h8/6/).

Any tips on how to omit redundant results?

**Comment by prudho** [comment]
`fullTextSearch` parameter set to `exact` seem to broke something while searching on multiple fields... (summon @hammy2899 and @jlukic).

Just initialize your search component with `fullTextSearch` set to `true` or `false`, according to the desired behavior.

**Comment by jlukic** [comment]
Will address in patch this week.

**Comment by jlukic** [comment]
Fixed in `2.3.1`
