### ISSUE TITLE
Components should use @normal font weight variable

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI#6227]
Variable: [`@normal`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L25) is not used [in all of the components](https://github.com/Semantic-Org/Semantic-UI/search?utf8=%E2%9C%93&q=normal&type=). I think it should be used everywhere instead of `normal`.

**Comment by jlukic** [comment]
Yep forgot to replace in `variable` files

**Comment by jlukic** [comment]
It looks like only the non-default theme were missing variables. Added in next.
