### ISSUE TITLE
Modal is not stack-able is  v2.3

### ISSUE THREAD

**Issue by DxCLL** [Semantic-Org/Semantic-UI#6236]
allowMultiple: true, Comes with different result now.

**Expected**
The Modal2 should stack with Modal1, Modal2 infront of Modal 1

**Result**
Modal 2 is under Modal1
**Testcase**
any suggestion ?  Thanks
http://jsfiddle.net/rduvhn8u/1/

**Comment by hammy2899** [comment]
This has already been reported, please check issues before creating a new one. https://github.com/Semantic-Org/Semantic-UI/issues/6185
