### ISSUE TITLE
[Label] Label with icons other than delete have excessive margins

### ISSUE THREAD

**Issue by ocharles** [Semantic-Org/Semantic-UI#6244]
See https://jsfiddle.net/bxcjqs8r/6/. Note that the down arrow has a right margin. If you use `delete icon` it's fine, but I don't see why delete needs special treatment.

**Comment by hammy2899** [comment]
Icons have margins by default unless you add [`fitted`](https://semantic-ui.com/elements/icon.html#fitted). I'm pretty sure the `delete` icon has an intended use of an action to delete the label similar to the `close` icon on messages https://semantic-ui.com/collections/message.html#dismissable-block

**Comment by ocharles** [comment]
Thanks, I didn't know about `fitted`. I'll keep this open incase devs want to fix it with loose coupling, but I'm otherwise happy to use that.

**Comment by hammy2899** [comment]
I'm going to close this as solved since I don't think it will be "fixed".
