### ISSUE TITLE
[Accordion] - Your Bug Name

### ISSUE THREAD

**Issue by gdsaiful** [Semantic-Org/Semantic-UI#6246]
**Steps to Reproduce**
1. Do something
2. Do something else.
3. Do one last thing.

**Expected**
The Accordion should do this

**Result**
The Accordion does not do this

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by hammy2899** [comment]
@gdsaiful Was this created by mistake?

**Comment by gdsaiful** [comment]
@hammy2899 ops! sorry it was created by mistake -_-
