### ISSUE TITLE
[Sidebar] [Menu] Sticky menu and visible sidebars do not work together

### ISSUE THREAD

**Issue by azmeuk** [Semantic-Org/Semantic-UI#6248]
### Steps
Put a visible sidebar along with a sticky menu, scroll.

### Expected Result
The menu should be sticky :)

### Actual Result
The menu is not sticky, and it shifts a bit to the right.

### Version
2.3

### Testcase
http://jsfiddle.net/azmeuk/bdpz9wch/25/

**Comment by azmeuk** [comment]
Hey stale bot. I would really love you to wait a bit until you close this issue. Cheers

**Comment by jmadkins** [comment]
This is still an issue in the latest version.
