### ISSUE TITLE
Fullscreen Modals since 2.3.0 regression in Safari

### ISSUE THREAD

**Issue by romaninsh** [Semantic-Org/Semantic-UI#6251]
After upgrading to 2.3.0, fullscreen modal widow does not display "close" icon correctly in safari:

From: https://semantic-ui.com/modules/modal.html#/definition

<img width="1243" alt="screen shot 2018-03-07 at 19 08 39" src="https://user-images.githubusercontent.com/453929/37112716-32be54be-223b-11e8-9333-c81aa8cccb76.png">

Cross is still visible, but is positioned badly:

<img width="100" alt="screen shot 2018-03-07 at 19 10 58" src="https://user-images.githubusercontent.com/453929/37112746-49dcd67a-223b-11e8-8a03-c637ad54b0a4.png">

**Comment by romaninsh** [comment]
Same issue in Safari Technology Preview.

**Comment by hammy2899** [comment]
I have checked this on as many Safari versions as I can and have found that this bug goes back to Safari 9.1. There is also another bug where on earlier versions the close icon displays but is not correctly positioned.

It looks like the icon shows then it just disappears
![ezgif-1-35a8f994a3](https://user-images.githubusercontent.com/11588822/37147139-d5da8212-22bd-11e8-9e31-9cab94eb27f7.gif)

Incorrectly placed icon on >9.1 
![image](https://user-images.githubusercontent.com/11588822/37147071-9f1a5aa4-22bd-11e8-835d-eb1d99f0f6a6.png)

**Comment by jlukic** [comment]
Added milestone.
