### ISSUE TITLE
FORM SELECT "multiple" broken after 2.2.13 

### ISSUE THREAD

**Issue by DarthGuybrush** [Semantic-Org/Semantic-UI#6254]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://www.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI
      SO - https://stackoverflow.com/questions/tagged/semantic-ui?sort=votes

✔ Enhancements → Be specific. Assume backwards compatibility is a necessity. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable due to backwards compatibility or CSS limitations.

### Title (Put in field above)
<select multiple="" class="ui dropdown"> existing values not longer selected by default.

### Steps
<select class="ui dropdown" name="GymmyPT_ClubNumber" multiple="">
	<cfloop query="Club_Location_List">
		<cfscript>
			CoachClub=ListFind(ClubLocationList, Club_Number, ",");
		</cfscript>
		<option value="#LCase(Club_Number)#" <cfif Len(CoachClub) NEQ 0>selected</cfif>>#Location#</option>
	</cfloop>
</select>
### Expected Result
Existing values to be "selected".
### Actual Result
Nothing at all is selected.
### Version
2.2.14 and later.

### Testcase
[Fork, update, and replace to show the bug]:
https://jsfiddle.net/ca0rovs3/

**Comment by w96k** [comment]
Hey, can you provide the way to reproduce your bug? Jsfiddle, jsbin.

**Comment by DarthGuybrush** [comment]
Screen grabs of missing “selected” items in build 2.2.14 and 2.3.0. Working in 2.2.13.




Regards

Peter Tilbrook | Web Administrator | Viva Leisure & The Club Group

Head Office: First Floor, Unit 7, 141 Flemington Road, Mitchell ACT 2911
Direct Phone: 02 6163 8008 | Switchboard: 1300 11 LIME | Facsimile: 02 6251 7666 | www.vivaleisure.com.au<http://www.vivaleisure.com.au>

[cid:EC0043-VIVA-LEISURE-New-Signature_1c38227c-349d-46e7-9ca8-95dc8a38e569.jpg]

**Comment by prudho** [comment]
Duplicate #6123
