### ISSUE TITLE
icons and components with 2.3.0

### ISSUE THREAD

**Issue by labby** [Semantic-Org/Semantic-UI#6256]
We noticed  some other/new icons that replaced the older ones using semantic 2.3.0.
But what is more worst is, that obviously icons are more font-weighted than before.
Also some components seem to work different than before (some fields) in css.
Can you confirm this behaviour?
And if yes: is it a bug or a feature ?
In second case we haver to rework our complete backend theme.
For the moment we went back to semantic 2.2.14, but we are not interested in using outdated versions.

**Comment by achimkoellner** [comment]
is this related to the new fontawesome pro icons? some old icons seem no longer to be part of the "free" iconset?

**Comment by labby** [comment]
Yes, seems to be so.
But that can not be the only reason why even "old icons" are now "bold/bolder" and some fields are running out of tables.
If I use rerlease 2.2.14 everything runs well again.

**Comment by hammy2899** [comment]
The icons are now using the new FontAwesome 5 icon set. These icons were redesigned from the ground up hence the difference. I currently have a PR ready to merge which fixes 100% of the bugs which have been reported and some more that I found, the plan is to release this in the next patch.

Can you provide a [JSFiddle](https://jsfiddle.net/ca0rovs3/) showing what you mean by some components work differently now?

**Comment by labby** [comment]
Mhh, i will try with jsfiddle, but I will upload some images (or links) that will show the problem.

**Comment by labby** [comment]
Please find some images attached
![1_230](https://user-images.githubusercontent.com/1763282/37198758-a6c46fa2-237f-11e8-9923-6a3341a1f264.jpg)
![2_230](https://user-images.githubusercontent.com/1763282/37198760-a6e87848-237f-11e8-873a-614b731cba18.jpg)
![1_2214](https://user-images.githubusercontent.com/1763282/37198762-a70b76b8-237f-11e8-8169-409b1a896706.jpg)
![2_2214](https://user-images.githubusercontent.com/1763282/37198763-a733b5ec-237f-11e8-824d-59a963d3dc48.jpg)

**Comment by labby** [comment]
Please see icons (font-weight and font-size) and drop-down field (size).
If I look at the css of elements, nothings semms to have changed there.

**Comment by labby** [comment]
I uploaded reworked images again to make clear what I'm talking about.
Please keep in mind, that this are only examples, there are a lot more differences.
![1_230](https://user-images.githubusercontent.com/1763282/37199017-97939dea-2380-11e8-8bb9-c424903aaf58.jpg)
![2_230](https://user-images.githubusercontent.com/1763282/37199019-97b5fce6-2380-11e8-9b0d-bff3c6d5cc5f.jpg)
![1_2214](https://user-images.githubusercontent.com/1763282/37199020-97da0eb0-2380-11e8-9b1f-72274cf9ff78.jpg)
![2_2214](https://user-images.githubusercontent.com/1763282/37199021-9808778c-2380-11e8-8134-6a9e02659631.jpg)

**Comment by hammy2899** [comment]
Have you tried using the outline icons? The outline icons are a lot "thinner". The table column I will have to look into when I get some time, I will get back to you on this.

**Comment by labby** [comment]
no, I've changed nothing.
I don't want to change the icons to outline because it's a lot of work for us.
I hope someone will find the reason for getting bigger icons now, because most icons itself have not changed as you can see on my images.

**Comment by hammy2899** [comment]
Has the recent update fixed your issues?

**Comment by labby** [comment]
Yes and no :-)
As for the icons only: yes, some icons seem not to be available any more (log out for ecample), but that's no problem, they have to be replaced.

The second one (lower item in my images) is not solved despite using 2.3.1
Will there be a upcoming solution?

**Comment by hammy2899** [comment]
Great to hear the icons are fixed, for the dropdown have you tried adding the `fluid` class to it?

**Comment by labby** [comment]
Sorry, but I have to correct me.
As I opened my test-installation this morning even the icons-item is back again...
I should have reloaded the installation after updating semantic...
As an answer to your question: no, but I can try.
From my point of view there should be a backward compatibilty if making things new.
I know that sometimes this is not possible but then there should be an information.
Now I have to look on every single template in the backend and search for things, we have to change.

If that is standard (which seemed not to be over the last 4 years) we have to think about changing the framework, which will be nearly the same work....
Sorry, but I am deeply disappointed.

**Comment by hammy2899** [comment]
If you want to use the old icons you can change your theme to use the old font files

[icon.overrides](https://github.com/Semantic-Org/Semantic-UI/blob/95ae3bf5fc98e2be09dd0656ccf0994baf0573ca/src/themes/default/elements/icon.overrides)
[icon.variables](https://github.com/Semantic-Org/Semantic-UI/blob/95ae3bf5fc98e2be09dd0656ccf0994baf0573ca/src/themes/default/elements/icon.variables)
[icon fonts](https://github.com/Semantic-Org/Semantic-UI/tree/95ae3bf5fc98e2be09dd0656ccf0994baf0573ca/src/themes/default/assets/fonts)

**Comment by labby** [comment]
From my point of view it's a css thing and not the icons themselves.
As I wrote in one of the above posts I cannot see where the changes come from!
For sure I can override and replace and so on, but up to 2.2.14 we used semantic out of the box with default theme, that was quite nice.
I don't know what happened with 2.3.0 but things got worse not better, which an update is supposed to.
And I am tired of searching for those things.
We are maintaining an open source cms and believe me, that is enough work.

**Comment by hammy2899** [comment]
The "icons changing" is not a CSS problem as I said they have changed because we updated SUI to use the new FontAwesome.

The dropdown not correctly fitting in the table is more likely to be CSS related, try taking a look at this JSFiddle to see how to make inputs fit table columns https://jsfiddle.net/mqy08aq4/

**Comment by labby** [comment]
Don't get me wrong, I appreciate your help.
But if you start to use new FontAwesome it should be clear what this means referring to the icons (and other things).
It is not acceptable that "normal" icons become "bolder" without changing the css.
In this case the framework should grant same behaviour as before.

Thanks for the jsfiddle link, but as long as the icon(bug) is not solved I will not try any further solution referring to other items because icons now let our backend "explode".

As  said: if we have to work on our backend we try to assure, that work is minimized by using framework and not an additional task with every framework update.

**Comment by hammy2899** [comment]
From my knowledge, it is clear that when updating to FA5 that the icons would be different. If you have a problem with the icons report it to the FA team. SUI simply just ports the icons from FA5 we don't change ANYTHING about them.

**Comment by labby** [comment]
Mhh, thanks for the hint.
But as I said, we want to minimize our tasks.
I will once have a deeper look and if this is not successfull we probably will move to another framework.
