### ISSUE TITLE
Fix Meteor.js Build Tools

### ISSUE THREAD

**Issue by devlinpadayachee** [Semantic-Org/Semantic-UI#6259]
It does not seem as though the meteor project is being updated or supported anymore last update was in 2016. Any idea if this will be continuing

**Comment by jlukic** [comment]
The meteor plugin was originally maintained by another user @flemay who can no longer maintain it.

My plan for the next patch is to write new scripts to properly update the data repository for the atmosphere plugin, and keep it up to date with 0-day updates.

I actually use Meteor as my primary development platform, so I'm sympathetic.

**Comment by devlinpadayachee** [comment]
All I’m going to say is that I love you

**Comment by flemay** [comment]
Thank you so much @jlukic. I haven't used meteor for a long time now and I am really not up to date with the latest packaging system. I hope it is simpler than back then! :)

**Comment by jlukic** [comment]
I've just published `2.3.0` with https://github.com/Semantic-Org/Semantic-UI-Meteorize
