### ISSUE TITLE
[Icon] - Can't finde icon?

### ISSUE THREAD

**Issue by TylerLumen** [Semantic-Org/Semantic-UI#6263]
Hey,

i will use the icon from  FontAwesome, but I have a error:

<img width="93" alt="bildschirmfoto 2018-03-11 um 11 45 22" src="https://user-images.githubusercontent.com/13014306/37252491-e97d398e-2521-11e8-860f-2614726ea00a.png">
<img width="1000" alt="bildschirmfoto 2018-03-11 um 11 45 22" src="https://user-images.githubusercontent.com/13014306/37252492-ecab84da-2521-11e8-94a5-56a64dee9132.png">

**Comment by hammy2899** [comment]
This seems to be a problem with `CORS`. Take a look a this MDN page to find out more https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by TylerLumen** [comment]
It was a error into my htaccess. Thanks!
