### ISSUE TITLE
Sample pages do not render correctly on initial load

### ISSUE THREAD

**Issue by jasonpolites** [Semantic-Org/Semantic-UI#6269]
### Steps
Initial visit to https://semantic-ui.com/examples/theming.html fails to correctly render page.  For example:

![screen shot 2018-03-12 at 9 34 51 pm](https://user-images.githubusercontent.com/764528/37322959-fc4f49cc-263d-11e8-9c12-d8b5ee6f893e.png)

Mousing over one of the components typically causes it to pop into view, however a "force reload" of the page (*shift* refresh, or clear cache) will also typically revert to initial broken state.

This was observed on:

Google Chrome: Version 64.0.3282.186 (Official Build) (64-bit)
OSX 10.11.6 (15G1004)

### Expected Result

Page renders correctly first time (without needing to mouse over truncated controls)

### Actual Result

Several controls appear truncated or invisible until mouse over.

### Version
https://semantic-ui.com/examples/theming.html as at date of this issue

**Comment by jasonpolites** [comment]
Hmm now I can't repro in Chrome Version 65.0.3325.146.  Might be a red herring

**Comment by jlukic** [comment]
It's doing some derpy things with iframes to make it easier to maintain. If anyone has a PR to fix this, i'd be game to add, but its not a high priority given other issues.

**Comment by jlukic** [comment]
I've updated the library for loading iframes to latest release.
