### ISSUE TITLE
Dropdown not initialized with hidden values

### ISSUE THREAD

**Issue by bukaOK** [Semantic-Org/Semantic-UI#6271]
https://jsfiddle.net/9nzvjbm3/7/
Dropdown hides values, which placed in hidden field and doesn't add them in text input
semantic-ui 2.3.0

**Comment by kevinah95** [comment]
But that's the purpose of that propertie. I don't see the error.

**Comment by bukaOK** [comment]
@kevinah95 the values in hidden input must be selected

**Comment by jlukic** [comment]
Values in the hidden input should be initialized. I'll check out your example more thoroughly.

**Comment by prudho** [comment]
#6123 ? Debug mode show this message: `Value already selected`.

**Comment by jlukic** [comment]
Fixed in #6123
