### ISSUE TITLE
[modal]Multiple Modals can't center align (version 2.3)

### ISSUE THREAD

**Issue by nbvghost** [Semantic-Org/Semantic-UI#6272]
Multiple Modals can't center align

**Comment by hammy2899** [comment]
This will be related to these issues https://github.com/Semantic-Org/Semantic-UI/issues/6267 https://github.com/Semantic-Org/Semantic-UI/issues/6185

**Comment by jlukic** [comment]
Fixed in #6562, I've introduced a new setting to allow for non-flex positioning to be used in legacy browsers, or when `detachable: false` is used.
