### ISSUE TITLE
[Icons] Circular icons are off-center in Firefox (Linux)

### ISSUE THREAD

**Issue by tobias-kuendig** [Semantic-Org/Semantic-UI#6274]
When using the `circular` class on the new Icons in 2.3 they appear off-center in Firefox 57 on Ubuntu 16.04.

![grafik](https://user-images.githubusercontent.com/8600029/37403923-3d51957e-2788-11e8-8c8a-1dfe84fb305a.png)

**Comment by hammy2899** [comment]
Duplicate https://github.com/Semantic-Org/Semantic-UI/issues/6184
