### ISSUE TITLE
[Dropdown] search selection leads to hard to remove text from input

### ISSUE THREAD

**Issue by pallakartheekreddy** [Semantic-Org/Semantic-UI#6275]
### Steps
1. Type enough characters in a "fluid multiple search special selection dropdown" until "No results found." is displayed.
2. Click outside side of dropdown
3. It's not clearing text entered in search box 

### Expected Result
The text is removed

### Actual Result
Text remains same

### Version
2.2.6

![screen shot 2018-03-15 at 12 01 51 pm](https://user-images.githubusercontent.com/20140324/37447569-b6e7ca00-2848-11e8-8361-ffa31c26c48a.png)

**Comment by prudho** [comment]
I couldn't reproduce this issue at all. Could you please provide a JSFiddle by forking this one : https://jsfiddle.net/ca0rovs3/

**Comment by hammy2899** [comment]
I'm going to close this until a test case is provided.
