### ISSUE TITLE
[Dropdown] onInit selected values should appear in label above the select

### ISSUE THREAD

**Issue by tollr** [Semantic-Org/Semantic-UI#6276]
Hey,

At version 2.2.14, dropdown does no show the preselected values properly as shown in the following jsfiddle : https://jsfiddle.net/ydaamk74/1/

It works until 2.2.12

Good luck and many thanks for your work !

**Comment by hammy2899** [comment]
I can confirm this broke in `2.2.14`, it works on `2.2.13` also.

**Comment by prudho** [comment]
#6123 ?

**Comment by hammy2899** [comment]
@prudho possibly related

**Comment by jlukic** [comment]
Addressed in #6123
