### ISSUE TITLE
Icons acting strange?

### ISSUE THREAD

**Issue by ArsalanBashir** [Semantic-Org/Semantic-UI#6277]
### Icons on V2.3

Link icon does not display anything at all (even on the docs website), star outlined actually displays star.

**Comment by hammy2899** [comment]
Take a look https://github.com/Semantic-Org/Semantic-UI/pull/6226

**Comment by ArsalanBashir** [comment]
Any guesses on when this will be merged? And also, I'm not sure if this is causing the link icon to not appear (the bit about outlined icons breaking makes sense though) 

<img width="395" alt="screen shot 2018-03-15 at 5 26 38 pm" src="https://user-images.githubusercontent.com/2177963/37466298-d60b4f8c-2876-11e8-9d31-7d3528da9d7d.png">

**Comment by hammy2899** [comment]
Lots of the icons had the wrong unicode this is why they break, however the `link` icon is called `linkify` to get around the [`link`](https://semantic-ui.com/elements/icon.html#link) variation.

The PR will possibly get merged sometime this weekend.

**Comment by ArsalanBashir** [comment]
Many thanks @hammy2899
