### ISSUE TITLE
Link icon unexpected result

### ISSUE THREAD

**Issue by tikoflano** [Semantic-Org/Semantic-UI#6278]
### Link icon unexpected result
Since 2.3.0 you can't use link variation for icons.

### Steps
Create a simple play icon formatted as link:

`<i class="play link icon"></i>`

### Expected Result
It should show a PLAY icon formatted as link: pointer cursor and hoverable status

### Actual Result
It shows a LINK icon formatted as link: pointer cursor and hoverable status

### Version
2.3.0

### Testcase
v2.2.14 https://jsfiddle.net/q1kLLhxn/1/
v2.3.0 https://jsfiddle.net/cs9oyq44/1/

**Comment by tikoflano** [comment]
It seems some icons still work, for example it works fine with `<i class="play circle link icon"></i>`

**Comment by hammy2899** [comment]
Take a look at this issue https://github.com/Semantic-Org/Semantic-UI/issues/6277

This should be fixed when this PR is merged https://github.com/Semantic-Org/Semantic-UI/pull/6226
