### ISSUE TITLE
2.3.1 release

### ISSUE THREAD

**Issue by fridzema** [Semantic-Org/Semantic-UI#6283]
Hello, 

I see that there is a new release available '2.3.1'. 
This release is not yet on [npm](https://www.npmjs.com/package/semantic-ui) anybody has an idea about this, maybe someone forgotten to push to npm or something?

**Comment by hammy2899** [comment]
I have also noticed this, I will drop @jlukic a message

**Comment by jlukic** [comment]
It's published now.
