### ISSUE TITLE
sidebar and pushable background

### ISSUE THREAD

**Issue by etshy** [Semantic-Org/Semantic-UI#6284]
HI, I'd like to know why there are things like that
```
body.pushable {
    background: #545454!important;
}
```
inside basic semantic ui ?

Why force a color like that ?
When I add a sidebar to my app, it broke the background bacause of this sort of things (there are 1 or 2 others classes I had to overwrite to prevent that).

I don't think that's a good thing to `important` things like that.

**Comment by hammy2899** [comment]
If you create the sidebar correctly the page background will be the colour of `@pageBackground` which is `#FFFFFF` by default

**Comment by etshy** [comment]
yeah there is a `#FFFFFF` bg color by default (on body selector), that I overwrote by mine but I also had the one in the first post (`body.pushable`), with an !important
I don't think using important in a "CSS Framework" is a good thing, and I just wanted to report that.

**Comment by hammy2899** [comment]
This is best asked on the SUI [Gitter](https://gitter.im/Semantic-Org/Semantic-UI) page.
