### ISSUE TITLE
How I can change size on input?

### ISSUE THREAD

**Issue by gigimon** [Semantic-Org/Semantic-UI#63]
Hello

I want change size for input element when it not include in form because not want focus element left on input.

Thank You! Awesome frameworok

**Comment by Panoplos** [comment]
I also wish to be able to set the width of an input element. Setting the font size affects the height, too, which is not desired. The reasoning behind this is I have a longer placeholder text than the current width allows for.

Would be great to have a variable the ```input.less``` file like ```@width``` that we can override in our site or theme files.

**Comment by ruler88** [comment]
Do you need the input size to be responsive?

If not, you can try using the size option:
```
<input type="text" placeholder="placeholder" size="50">
```

**Comment by jlukic** [comment]
If you just want to specify width on an individual field i recommend oldschool
```html
<input type="text" placeholder="placeholder" size="50">
```

```css
.my.input {
  width: 400px; /* arbitrary amount */
}
```
