### ISSUE TITLE
BUG?? Negative margins on grids

### ISSUE THREAD

**Issue by DaveClissold** [Semantic-Org/Semantic-UI#6300]
Not sure if this is a bug, but I am finding a negative, -1rem margin on the main Grid element.

Surely this is not right? It is bloating my views when using a Grid within in a fluid container on a mobile device, adding around 14px to the width

**Comment by devmohitagarwal** [comment]
The margins are negative values, but the corresponding ".wide.column" classes have equivalent padding to correct that. It's probably done to increase click area of the div..

**Comment by DaveClissold** [comment]
Maybe there is a call for a fluid grid then, as this will not resolve the issue of bloating screen size.

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/ca0rovs3/) to replicate the issue?

**Comment by DaveClissold** [comment]
Closing with my head hung low, feeling a bit silly. I had nested the grid.rows and columns within react components and on one component the grid.column was mistyped, which caused this bloating.
