### ISSUE TITLE
[Component] Icon should execept valid Iconnames

### ISSUE THREAD

**Issue by siluri** [Semantic-Org/Semantic-UI#6309]
### Version
latest

### Testcase
```jsx
<Button inverted icon>
    <Icon name="lightbulb outline" />
</Button>
```
```shell
Warning: Failed prop type: Invalid prop `name` of value `lightbulb outline` supplied to `Icon`.

Instead of `lightbulb outline`, did you mean:
  - lightbulb
  - like outline
  - building outline
...
```

### Solution
i guess, u must add that icon in the [static list](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/SUI.js):
```js
export const ICON_ALIASES = [  ... 'lightbulb', 'lightbulb outline', ... ]
```

**Comment by hammy2899** [comment]
This is a SUI React issue, please create the issue over on the React repo https://github.com/Semantic-Org/Semantic-UI-React
