### ISSUE TITLE
Sidebar is not responsive.

### ISSUE THREAD

**Issue by dalejodc** [Semantic-Org/Semantic-UI#6314]
**Steps to Reproduce**
1. Use some example code of Semantic UI sidebar. 
2. Resize the browser

**Expected**
The Sidebar should hide and show the mobile version?.
Like the web page: https://semantic-ui.com/modules/sidebar.html

**Result**
The Sidebar does not do this when I tried with the examples components.

**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/ca0rovs3/) to replicate the issue?

**Comment by dalejodc** [comment]
Hi, thansk for comment. I'm trying to use a **sidebar**, like that.

_Fig 1._
![1](https://user-images.githubusercontent.com/36966980/38181325-785f4236-35ef-11e8-8eb7-a94bbe8918f8.PNG)

Normally the frameworks, when we resizing the window of the browser the sidebar changes its size. Changing its shape from _Fig 1_ to _Fig 2_ 
On the page Semantic UI, the behavior is perfect, but when we use the sidebar component, it does not behave that way.

_Fig 2._
![imagen](https://user-images.githubusercontent.com/36966980/38181916-04f979a2-35f3-11e8-8b20-0465a43d1f4a.png)

In resumen: I try have a sidebar **_visible_** but when we resize the window of the browser the sidebar should **_hides_** and show a "hamburger icon" menu (_Fig 2_). I come from Materialize and Bootstrap, and that behavior works automatically.

I'm not able to do that using the code of component sidebar of **Semantic UI**.
And I'm very sorry, but I was not abble to do the JSFiddle to explain it.

Thanks a lot for your help!

**Comment by hammy2899** [comment]
You need to manually set this up, this allows flexibility for people to do what they want. Meaning you will need to hide the sidebar and show the hamburger when the screen reaches a certain size.

**Comment by dalejodc** [comment]
I'll try to do it, thanks a lot for your time!
