### ISSUE TITLE
[Accordion] - Does not work in Chrome extensions

### ISSUE THREAD

**Issue by baterflyrity** [Semantic-Org/Semantic-UI#6317]
**Steps to Reproduce**
1. Include Semantic UI into new Chrome extension.
2. Insert accordion template into popup's html.

**Expected**
The Accordion should be interactive.

**Result**
The Accordion does not interactive. It's just like a static html with styles but animation or any click events!

**Test Case**
1. Download [semantic.zip](https://github.com/Semantic-Org/Semantic-UI/files/1866191/semantic.zip).
2. Unzip attached folder.
3. Navigate in [Chrome](chrome://extensions) or [Yandex](browser://extensions) browser to chrome://extensions.
4. Switch on "Developer mode".
5. Click "upload unpacked extension" and choose unzipped folder.
6. Click on new icon in browser toolbar (usually grey rect with S letter).

p.s.
**Additional bug**
Links like &#091;Chrome](chrome://extensions) do not work.

**Comment by hammy2899** [comment]
Could you make a really basic example and upload it as a zip so we can easily test this?

**Comment by baterflyrity** [comment]
@hammy2899 no problem. Watch the offtop.

**Comment by hammy2899** [comment]
The problem is because you didn't initialize the accordion, you need to put `$('.ui.accordion').accordion();` inside a script file.

**Comment by baterflyrity** [comment]
What a surprise!  I really believed I did that( Sorry for useless thread.
