### ISSUE TITLE
Refused to apply style from Semantic UI

### ISSUE THREAD

**Issue by sherlyseptiani** [Semantic-Org/Semantic-UI#6318]
When reloading / go directly to nested routes/ child routes in Vue JS 2 I got this error:

> Refused to apply style from 'http://localhost:8080/civil/semantic/dist/semantic.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
edit:21 GET http://localhost:8080/civil/semantic/dist/semantic.min.js net::ERR_ABORTED
edit:21 GET http://localhost:8080/civil/semantic/dist/semantic.min.js net::ERR_ABORTED
edit:1 Refused to execute script from 'http://localhost:8080/civil/semantic/dist/semantic.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

It works fine on parent route but this error always shows up if we go directly to child route and reloading it. Does anyone know why? How to fix this?

Thanks

**Comment by hammy2899** [comment]
This is not a SUI issue, this seems to be a problem with your web server configuration.
