### ISSUE TITLE
Centering child in a Grid

### ISSUE THREAD

**Issue by giggioz** [Semantic-Org/Semantic-UI#6328]
Hi, i posted this on stackoverflow but i did not get any answer.
Could you help me? Maybe is it a bug?
Thanks.

I'm trying to center a child (horizontally and vertically) in its parent in a Grid layout. 
I don't want to use tricks like

`top: 50%;
left: 50%;
transform: translate(-50%, -50%);`

because this does not use the Grid properties and creates problems for animations.

Can you help me?

https://codesandbox.io/s/qkyv1v8oq6

**Comment by hammy2899** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
