### ISSUE TITLE
Feedback while a table loads its data

### ISSUE THREAD

**Issue by dekhaus** [Semantic-Org/Semantic-UI#6339]
Hi

I have a semantic-ui based table that is 'backed' by an AngularJS scoped array.  I have a set of buttons which act as 'filters' against the aforementioned array.  One of the filter options is 'All'

I've noticed that when switching from one of the non-All filters to the All filter - it takes the table 1-2 seconds to load/re-render its data.  

Is there a way to provide some feedback to the user while this table 'loading/rendering' is occurring ?  I should emphasize that the data is not being 'loaded' in the traditional sense.  Its already available in an array managed by an Angular controller.

Thanks
Dave

**Comment by hammy2899** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
