### ISSUE TITLE
[Progress] Should have an option to omit the min width on the bar

### ISSUE THREAD

**Issue by jacknevitt** [Semantic-Org/Semantic-UI#6341]
### Steps
```
<div class="ui small progress" data-percent="0">
  <div class="bar" style="width: 0%;"></div>
  <div class="label">0/1</div>
</div>
```
### Expected Result
![image](https://user-images.githubusercontent.com/19165624/38945477-830e94c4-432e-11e8-80f6-5554e1268977.png)

### Actual Result
![image](https://user-images.githubusercontent.com/19165624/38945542-a7dfb6fc-432e-11e8-9adf-b8f6007f9f93.png)

### Version
0.78.3

**Comment by jacknevitt** [comment]
As i'm using the progress in a table, there is not much horizontal space so It looks like the 0 is taking up about a fifth of the bar

**Comment by jacknevitt** [comment]
Similarly to https://github.com/Semantic-Org/Semantic-UI/issues/6445 the bar should be at 0
I am not using LESS on my project so cannot use this solution

**Comment by llturro** [comment]
LESS compiles to CSS. The LESS instruction where @barMinWidth is used is

```
@barMinWidth: 2em;
@activeMinWidth: @barMinWidth;

.ui.progress .bar {
  min-width: @barMinWidth;
}

.ui.active.progress .bar {
  min-width: @activeMinWidth;
}
```

Should be possible to emulate the proposed solution in your CSS by adding

```
.ui.progress .bar {
  min-width: 0 !important;
}

.ui.active.progress .bar {
  min-width: 0 !important;
}
```

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/412
Supposed to be included in the upcoming Fomantic-UI 2.7.2 Release

**Comment by dhanushkac** [comment]
When this will be released for Semantic UI react version?

**Comment by hammy2899** [comment]
@dhanushkac Depends, if you need to JS fixes in the linked PR then no but if you need to CSS fixes then yes it will work as long as your using fomantic not semantic.
