### ISSUE TITLE
[Dropdown] Items Should Display As Block For >= 2.2.11 

### ISSUE THREAD

**Issue by pzanitti** [Semantic-Org/Semantic-UI#6359]
2.2.11 contained a big update for dropdowns. https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.2.11

I am suspecting this change is the culprit:
>Dropdown - Dropdowns will automatically detect when they are offscreen to the right and will open leftward instead Thanks @Graveheart #4211

This behavior was working fine and I see no changes in the documentation so I figure this is a regression.

### Steps
1. Make a dropdown on the right of the screen, e.g. in a right menu
2. Have it contain long elements 

### Expected Result
The menu flushes to the left as to have enough space for the items.

### Actual Result
The menu goes inline because it gets set `style="display: flex !important;"` instead of `style="display: block !important;"`.

### Version
\>= 2.2.11

### Testcase
Working perfectly fine in 2.2.10: https://jsfiddle.net/ca0rovs3/480/
Broken in 2.2.11: https://jsfiddle.net/ca0rovs3/481/
Broken in latest (2.3.1): https://jsfiddle.net/ca0rovs3/482/

**Comment by pzanitti** [comment]
I will force `direction` to `downward` for now, it appears to do the trick.

https://jsfiddle.net/ca0rovs3/483/

**Comment by jlukic** [comment]
I've fixed this in `next` with a css solve that makes sure `display: flex` isnt applied to dropdown elements.
