### ISSUE TITLE
Loader is broken in latest Chrome

### ISSUE THREAD

**Issue by jyosh** [Semantic-Org/Semantic-UI#6360]
The loader spinning animation is not displayed properly in the latest chrome browser, Version 66.0.3359.139 (Official Build) (64-bit)

Open this link in latest chrome browser to see the issue
https://semantic-ui.com/elements/loader.html

**Comment by hammy2899** [comment]
I just tested this on `66.0.3359.139 (Official Build) (64-bit)` and its working for me.

**Comment by jyosh** [comment]
It is an issue with a Chrome extension: Loom - Video Recorder

https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb

It interferes with the spinning animation of the loader.

**Comment by daneren2005** [comment]
Thank  you for figuring out what was causing this!  I was having the same issue.
