### ISSUE TITLE
[Form] IE11 - CSS rule is incorrect for input placeholders.

### ISSUE THREAD

**Issue by Ikaer** [Semantic-Org/Semantic-UI#6363]
### Steps
Open the form doc examples (https://semantic-ui.com/collections/form.html#form) on IE11 and Chrome to compare.
IE11 has the wrong css rule for input placeholders (but it is correct for dropdown placeholders)

### Expected Result
Input placeholders should be like in Chrome. 

### Actual Result
If I a take an input from doc input section, the following rule is applied for placeholder:
![image](https://user-images.githubusercontent.com/7936075/39505488-e9fbaf92-4dd2-11e8-8d9d-5c04d0d8a9fa.png)
![image](https://user-images.githubusercontent.com/7936075/39505619-db608e02-4dd3-11e8-88a6-6411610ee28a.png)

IE11 seems to override this rule in a form with an incorrect one.
![image](https://user-images.githubusercontent.com/7936075/39505459-ab02c370-4dd2-11e8-86e5-f8442d34adee.png)
![image](https://user-images.githubusercontent.com/7936075/39505636-fac98cee-4dd3-11e8-8f2e-b78134f3788c.png)

### Version
2.3.1

### Testcase
https://jsfiddle.net/b1uor6xe/1/

**Comment by jlukic** [comment]
Fixed in next release
