### ISSUE TITLE
[Accordion] Nested Accordion doesn't work correctly

### ISSUE THREAD

**Issue by EduardoHidalgo** [Semantic-Org/Semantic-UI#6365]
### Steps
1. Create a "grid container".
2. Inside grid container create "one column row" with accordion (parent).
3. Inside accordion parent create other "grid container".
4. Inside the second grid container create a "three column row", and add one child accordion inside each column div.

### Expected Result
The child accordion should expand and stay open.

### Actual Result
The parent Accordion functions fine, however when attempting to expand the child accordion, it does not open. (it opens very briefly then immediately closes)

### Version
2.3.1

### Testcase
https://codepen.io/anon/pen/gzWyGR

**Comment by EduardoHidalgo** [comment]
Yes, but my implementation works quite different, i did an horizontal accordion using containers and grids. I assume that shouldn't break the accordion inside a container or a grid. Currently in my github website lives the bug:  https://eduardohidalgo.github.io/Profile.html navigate to second section called "Desarrollador" and expand first accordion, like the picture:

all accordions inside are not working properly. 
![image](https://user-images.githubusercontent.com/30780192/39601574-faacae98-4ee7-11e8-9194-59e2ce544aa9.png)

New Test Case in jsfiddle:

https://jsfiddle.net/1peomvgq/

i hope you can see it in jsfiddle.

**Comment by EduardoHidalgo** [comment]
omg,  I didn't figure out. You can consider this issue closed (: Thanks a lot.

**Comment by pierre-vassoilles** [comment]
For the ones who faces this issue next time : `$('...').accordion();` should be called only on the parent element, not on nested accordions. The parent accordion will automatically handle all nested/chrild accordions.

(For french users)
Pour ceux qui seront confrontés à ce problème la prochaine fois : `$('...').accordion();` doit être appelé uniquement sur l'élément parent, et non sur les accordéons imbriqués/enfants. L'accordéon parent gérera automatiquement tous les accordéons imbriqués/enfants.
