### ISSUE TITLE
[Accordion] Nested Accordion doesn't change color properly

### ISSUE THREAD

**Issue by EduardoHidalgo** [Semantic-Org/Semantic-UI#6366]
### Steps
1. Create a "grid container".
2. Inside grid container create "one column row" with accordion (parent).
3. Inside accordion parent create other "grid container".
4. Inside the second grid container create a "three column row", and add one child accordion inside each one.
5. Get css selectors by navigator inspector of parent accordion and modify his attribute "color". (parent and child accordions get his colors by same css selectors in semantic ui css file).

### Expected Result
Accordion Title have two remarkable colors that i want to modify: 

1) Text Color (different to Active status)
2) Text Color with Hover status

If change by css the attibute color it works fine, except for child accordions. Text color without hover swap the color of Text color with Hover.

### Actual Result
Just doesn't work css style.

Alternative way:
Instead of use css, you can modify color with JQuery, where it works correctly.

### Version
2.3.1

### Testcase
(i can't reproduce the case in codepen, css just not working at all.
https://codepen.io/anon/pen/gzWyGR

in my personal website bug appears. I add some screenshots to prove the bug:
https://eduardohidalgo.github.io/Profile.html
Navigate to "Desarrollador" Section, and open first accordion tab.

Parent Accordion have black color, and Child Accordions have the Hover color of parent. 

![image](https://user-images.githubusercontent.com/30780192/39537460-413470ba-4dff-11e8-89fc-cbec6e851f8e.png)

parent styles

![image](https://user-images.githubusercontent.com/30780192/39537626-c8d776c0-4dff-11e8-8457-0a0efc363395.png)

child styles (note that i didn't mark hover, and isn't hovered in webpage)

![image](https://user-images.githubusercontent.com/30780192/39537683-ed3cbcf0-4dff-11e8-9f7f-064e06d2a65e.png)

**Comment by prudho** [comment]
I'm sorry I couldn't reproduce the bug, even on your website.

Could you please provide a reproducible case by forking this: https://jsfiddle.net/ca0rovs3/ ?

**Comment by EduardoHidalgo** [comment]
https://jsfiddle.net/1peomvgq/

is done.

**Comment by hammy2899** [comment]
The proper way to do this would be to make a theme where you can modify the colours https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/accordion.variables 

Currently there is no inbuilt way to change the colour of accordions.

**Comment by EduardoHidalgo** [comment]
That is very helpful. I didn't want to go too deeply into the themes, i thought just can modify styles directly. I learn some new today.

Thanks a lot (:
