### ISSUE TITLE
[Modal] Modal breaks when repeatedly opened and closed

### ISSUE THREAD

**Issue by peterzhu2118** [Semantic-Org/Semantic-UI#6374]
### Steps
Check out [this fiddle](https://jsfiddle.net/7btexc4b/) that opens `modalOne`, then immediately closes `modalOne` and opens `modalTwo`. What is left is a translucent layer on top of the whole page making it impossible to use.

Here is a video of it:
![ezgif-5-10cefeac6f](https://user-images.githubusercontent.com/15860699/39668851-eac5b710-50a7-11e8-8f60-1570a6761b40.gif)

# Expected Output

`modalOne` opens, then `modalOne` closes, then `modalTwo` opens.

### Version
2.3.1

**Comment by hammy2899** [comment]
This isn't a bug, showing and hiding modal's is asynchronous. You should use the callbacks on the modal settings page. https://semantic-ui.com/modules/modal.html#settings

You can also see this working here https://jsfiddle.net/8dwpfbke/

**Comment by peterzhu2118** [comment]
@hammy2899 I see, thanks! Would it be possible to transition from the first modal to the second using JS without using a button like the one shown on [this](https://semantic-ui.com/modules/modal.html#/examples) page?

**Comment by hammy2899** [comment]
You can use the modal behavior https://semantic-ui.com/modules/modal.html#behavior to show/hide etc

**Comment by peterzhu2118** [comment]
@hammy2899, sorry for not clarifying. I want to be able to do something like this, but without the button to transition from modal 1 to modal 2:
![1](https://user-images.githubusercontent.com/15860699/39973562-4d07e838-56ef-11e8-87a9-94555a0ac3c2.JPG)

![2](https://user-images.githubusercontent.com/15860699/39973566-5b6bb1ca-56ef-11e8-98f5-842dff6d6daf.JPG)

Since opening/closing modals are asynchronous, how can I transition to the second modal after the first is closed without setting callbacks (in my case the the second modal is only opened on select cases, not every time the first modal is closed)?

**Comment by peterzhu2118** [comment]
Ah yes that's a good suggestion! Thanks so much!
