### ISSUE TITLE
Doc page: New in 2.3 mistmatch of modal options

### ISSUE THREAD

**Issue by archebyte** [Semantic-Org/Semantic-UI#6377]
This page under New Features > Flexbox Modals and Dimmers
https://semantic-ui.com/introduction/new.html

Shows a mismatch in modal options: centerable vs. centered (see attached screenshot)
<img width="1004" alt="centered-false" src="https://user-images.githubusercontent.com/18292613/39677817-49f61b10-5136-11e8-879c-c54151e25ff8.png">

**Comment by ozzywalsh** [comment]
It should be `centered: false`. That is what is used in the code.

I have created a [pull request](https://github.com/Semantic-Org/Semantic-UI-Docs/pull/393) to fix this in the docs.

It might be better to raise documentation issues on the documentation repo.

**Comment by plebeian-org** [comment]
Ok just wanted to point it out. Sorry I didn't realize there was a repo for docs!  I'll do that in the future.
Cheers!

**Comment by ozzywalsh** [comment]
This can be closed as the [pull request](https://github.com/Semantic-Org/Semantic-UI-Docs/pull/393) to fix it has been merged.
