### ISSUE TITLE
[dropdown] Behavior 'change values' should reset the select options

### ISSUE THREAD

**Issue by qxchen6** [Semantic-Org/Semantic-UI#6378]
### Steps
first，I initialized a dropdown

```
$('.dropdown').dropdown();
```

It works , and initialized with some data , fine .

but ,later ,data changed , so i have to reset the options and refresh the dropdown .

so i try to do this :

```
$('.dropdown').dropdown('change values', { values: [ {value:1, text:'test'} ] });
```
and this:
```
$('.dropdown').dropdown('change values', { values: [ {value:1, text:'test', name:'wtf'} ] });
```
and this:
```
$('.dropdown').dropdown('change values(values)', { values: [ {value:1, text:'test'} ] });
```

and this :

```
$('.dropdown').dropdown('change values(values)', { values: [ {value:1, text:'test', name:'wtf'} ] });
```

all above don't work and throw errors .

the errors seem to mean that the method 'change' 'values' don't exist at all .

![image](https://user-images.githubusercontent.com/25380801/39683497-80aada76-51e8-11e8-9bd1-1e086131d51f.png)

### Expected Result

I want to reset the options after initialized but it doesn't work .

Am i using the wrong syntax ?

### Actual Result

throw error

### Version

I don't know  but i am using the ruby gems and the gem is  :

```
gem 'semantic-ui-sass', '~> 2.2', '>= 2.2.10.1'
```

**Comment by prudho** [comment]
Please try this syntax:

`$('.dropdown').dropdown('change values', [ {value:1, text:'test', name:'wtf'}, {value:2, text:'test2', name:'wtf2'} ]);`

**Comment by qxchen6** [comment]
doesn't work ...  : (

![image](https://user-images.githubusercontent.com/25380801/39691971-de81b75e-5211-11e8-9190-ae31e0f0f0e2.png)

**Comment by prudho** [comment]
This is a weird bug 🤔
The javascript VM doesn't seem to parse correctly the function name and eval it as an array... What's the result if you try this:
`$('.dropdown').dropdown("change values", [ {value:1, text:'test', name:'wtf'}, {value:2, text:'test2', name:'wtf2'} ]);`

**Comment by hammy2899** [comment]
I think you haven't understood the syntax try looking at this [JSFiddle](https://jsfiddle.net/b0pdqcgb/) with a working example.

**Comment by qxchen6** [comment]
I have tried the syntax you suggested . It didn't work . And I copied your code from JSFiddle to my project , it threw errors again .

But , I copied my code to the JSFiddle . It works ...

I think it's a problem of the semantic gem . Is the gem developed by the same organization ?
![image](https://user-images.githubusercontent.com/25380801/39733857-3dc70152-52a7-11e8-82c7-969c84a091fd.png)



The HTML is  

```
<div class="ui input fluid mgt">
    <select name="receivers[]" id="receivers_" class="ui fluid search dropdown" multiple="multiple">
        <option value="1">one</option>
        <option value="2">two</option>
    </select>
</div>
```

**Comment by hammy2899** [comment]
No Semantic-UI-Sass is developed by a third party.

**Comment by qxchen6** [comment]
Thanks for answer ~ 
I solve the problem by use APISettings . 

I'm using the [semantic-ui-sass gem](https://github.com/doabit/semantic-ui-sass)  which using rails pipeline through rails assets not vendor/assets .
I will try to use the gem you provided to check if the problem is still existed in the future .

By the way , the [WebSite of semantic-ui in China](http://www.semantic-ui.cn/)  seems to have some problem . When click some tags such as '输入框' (means 'input') , the page lost response . Can't click anywhere . Can't close . Can't do anything even close the browser . 
I discovered this last year .
However, the [english website](https://semantic-ui.com/) doesn't have the problem .

chrome 66.0.3359.139
OS: macOS 10.13.3
