### ISSUE TITLE
[Dropdown] list should be fully visible when inside a Modal

### ISSUE THREAD

**Issue by kev1n11** [Semantic-Org/Semantic-UI#6416]
### Steps
Put a dropdown inside a modal.
I used React Semantic UI but it seems like a purely css issue.

### Expected Result
The dropdown list to be visible, even if its content floats on top of the modal

### Actual Result
Lower items are clipped and not visible

### Version
semantic-ui-react-0.80.0
semantic-ui-css-2.3.1

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/ca0rovs3/) to replicate the issue?

**Comment by kev1n11** [comment]
False alarm. Turned out somewhere in our code base we set overflow hidden to a parent div :(
