### ISSUE TITLE
[Search] Add setting for error header in search results

### ISSUE THREAD

**Issue by jloewe** [Semantic-Org/Semantic-UI#6442]
### Description
There is no way to localize "[No Results](https://github.com/Semantic-Org/Semantic-UI/blob/33edfc56cd84335dd28fbb210f7ccc9646d78181/src/definitions/modules/search.js#L1380)" in the search results header without adding a template.
![search results header](https://user-images.githubusercontent.com/11992962/41581147-e28b29cc-739d-11e8-88d3-a279c3a25af1.png)

### Solution
Add a setting like `error.header` and use it instead of "[No Results](https://github.com/Semantic-Org/Semantic-UI/blob/33edfc56cd84335dd28fbb210f7ccc9646d78181/src/definitions/modules/search.js#L1380)".

### Version
semantic-ui-search - 2.3.1

**Comment by jloewe907** [comment]
Duplicate of #5791

**Comment by lubber-de** [comment]
Implemented since https://github.com/fomantic/Fomantic-UI 2.4.2
