### ISSUE TITLE
Is there the slider component?

### ISSUE THREAD

**Issue by biapar** [Semantic-Org/Semantic-UI#6448]
Is there the slider component similar this https://jqueryui.com/slider/?

**Comment by dutrieux** [comment]
No but you can check this : https://github.com/Semantic-Org/Semantic-UI/issues/1336

**Comment by biapar** [comment]
Hi, but it’s for image slider. I need a number slider or values

**Comment by hammy2899** [comment]
Try looking at this issue https://github.com/Semantic-Org/Semantic-UI/issues/1336
