### ISSUE TITLE
keyboardShortcuts on modal not reacting to "enter" key pressed

### ISSUE THREAD

**Issue by KingOsman** [Semantic-Org/Semantic-UI#6450]
Trying to submit form when i press enter inside modal, even though keyboardShortcuts is set to true for modal, only escape key works (exits modal). However, when I'm in one of the textfields and submit "enter" key, no action is being taken.

Demo:

http://jsfiddle.net/pgfm6yt0/10/

Test: Enter 'enter' key 
Expected result: Modal's onApprove function is triggered
Actual result: No action is taken

Final thoughts: If this is not supported, then how can one go around supporting this on their side? i.e. how can I make the modal react to enter key press?

Thanks

**Comment by hammy2899** [comment]
This isn't anything todo with the modal, it seems to be because you don't have an submit input in your form. http://jsfiddle.net/vpfyn06g/

Also take a look here https://stackoverflow.com/a/26433820/7325243

**Comment by KingOsman** [comment]
That doesn't answer my question; I need the onApprove method to be triggered when the key that is pressed down is enter inside that modal.

Can this be done or not, and if not then what is keyboardShortcuts for?

**Comment by hammy2899** [comment]
You will need to write some custom JavaScript since SUI doesn't have support for that.

**Comment by hammy2899** [comment]
You can't access the settings of a component therefore you can't call the onApprove method set in the settings.

My advice would be to move the function out of the options and just call it inside your enter click event.

**Comment by KingOsman** [comment]
Sounds good, thanks for the help. Closing this issue.
