### ISSUE TITLE
[FLAG] Wrong flag for Reunion Island

### ISSUE THREAD

**Issue by lapwil** [Semantic-Org/Semantic-UI#6453]
## Bug Report
The Reunion Island Flag is wrong, I need it for the French regions display

### Steps
When trying to display the Reunion Island's flag the French one is displayed, but Guyana, Martinique, Guadeloupe have their own.

### Expected Result
The result that you expected.
![image](https://user-images.githubusercontent.com/10071994/41912216-561ea3f8-794f-11e8-8ad8-34136f230811.png)

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/10071994/41912228-60da5102-794f-11e8-9c7c-123df5913695.png)

### Version
0.81.2

**Comment by ColinFrick** [comment]
Seems to be a proposal and not an official flag
https://en.wikipedia.org/wiki/Flag_of_R%C3%A9union
https://en.wikipedia.org/wiki/R%C3%A9union
