### ISSUE TITLE
[Search] - set value - can't call

### ISSUE THREAD

**Issue by MrMarci666** [Semantic-Org/Semantic-UI#6454]
Hey guys, I wanted to reset the Semantic UI search field, after the onSelect event called.

When I call the behavior, but it does nothing!

$('.ui.search').search('set value', '');
Other ways, it works, when I call this function from another source.
I don't really understand why, maybe there is a bug.

Thank you!

TEST IT HERE:
[https://jsfiddle.net/9jcj5va8/46/](https://jsfiddle.net/9jcj5va8/46/)

**Comment by hammy2899** [comment]
This will be due to this line https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L237

**Comment by MrMarci666** [comment]
Yes! Is it legal to repair that myself? Or I should wait for the official solution?

**Comment by hammy2899** [comment]
@MrMarci666 you are free to open a pull request to suggest a fix, please read the [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) before submitting.

**Comment by lubber-de** [comment]
Fixed in https://github.com/fomantic/Fomantic-UI 2.5.0

**Comment by MrMarci666** [comment]
This seems to be fixed.
