### ISSUE TITLE
[Accordion] Content children display rules are overridden 

### ISSUE THREAD

**Issue by GammaGames** [Semantic-Org/Semantic-UI#6459]
### Steps
1. Give child of accordion content css for display: none
2. Child is shown when accordion item is open and closed

### Expected Result
Item CSS shouldn't be overridden 

### Actual Result
Item CSS is overridden

### Version
2.3.2

### Testcase
[Open and close the top item](https://jsfiddle.net/5g9qtmyc/)

**Comment by ColinFrick** [comment]
You could deactivate the animateChildren option:
```javascript
$(".ui.accordion").accordion({animateChildren: false});
```

Or wrap the content in a div:
```html
<div class="active content">
  <div>
    <p class="hidden">A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.</p>
    <a class="hidden ui right floated blue labeled icon button">
      <i class="circle icon"></i>
      Hidden?
    </a>
  </div>
</div>
```

**Comment by GammaGames** [comment]
The animateChildren option was exactly what I was looking for, somehow I missed it! Thank you!
