### ISSUE TITLE
Missing icons in 2.3.1 & 2.3.2

### ISSUE THREAD

**Issue by al35mm** [Semantic-Org/Semantic-UI#6468]
I am developing a web application for which I am using Semantic-UI which I have used in many other apps during the past several years. I am using it via CDNJS - latest version 2.3.2 and I have discovered some missing icons e.g. gem, gem outline and futbol - none of these show up/render at all. These are the only ones I have noticed missing so far, but obviously, I have not checked them all. Unfortunately, I really need those gem icons in this project. There are also missing in 2.3.1. Is this a known issue?

**Comment by al35mm** [comment]
@ColinFrick Thanks for your reply. That's really strange. Yes, it works in your fiddle. What do you mean by "problem loading the font"? All the icons I have used in the app so far work fine. Gem is the first one I have used that doesn't work - it should show up just the same as the others. What could the problem be?

**Comment by ColinFrick** [comment]
@al35mm You're right, if most icons are showing and only a few not the font seems to be loaded correctly.
Maybe some of your custom styling interfering with these icons? Could you inspect the element in your app and compare it to the applied styles in the jsfiddle?

**Comment by al35mm** [comment]
OK, so it works when used as standard on a white background, but it's not working in an inverted header on a black column. I've tried to reproduce it in a fiddle and no problems there [https://jsfiddle.net/wa492jys/6/](url). 

Not sure where to start looking for the fix. My css shouldn't be a problem. The odd thing is that it only seems to affect the gem icon and the futbol icon so far. I don't have any styles named gem or futbol that could be overriding them.

**Comment by hammy2899** [comment]
@al35mm Do you have any custom CSS modifying `.icon` or `<i>` elements?

**Comment by al35mm** [comment]
@hammy2899 No. I have just looked through my css and nothing for .icon or <i> in any way. But if there was that would affect all icons, not just one or two. I need to do some more testing after I've grabbed some sleep. I tried a gem icon in another area on the site and it displayed just fine.  The issue might just be associated with this one part of the app.

**Comment by al35mm** [comment]
OK, cracked it. My fault... the gem icon was not displayed in the app's backend section. This uses a different main template to the front end and the Semantic-UI version had not been updated in the backend and so those icons were not available. Stupidly simple really. Thanks for your help.
