### ISSUE TITLE
[Theme] In the end, I made an inverted theme myself

### ISSUE THREAD

**Issue by Atulin** [Semantic-Org/Semantic-UI#6479]
Since it seems that an official inverted theme isn't a priority, I made a super quick, super easy and super dirty edit to the ``semantic.css`` and ``semantic.min.css`` that results in a completely inverted theme. Finding a way to invert all the colors took the longest, but in the end it turns out there's a website that does just that in a few seconds.
~~Yes, *all* the colors are inverted. That includes green -> purple, blue -> orange, etc. I'm hoping to change those back sometime soon.~~

~~Here's the gist, hope it'll prove useful to someone 👌~~
~~https://gist.github.com/Atulin/bdcf51f9c5d62f5bf045b7a0cb73eaa0~~

**EDIT:**
The dark theme should look much better now. Colors are as they should be and all. I had to write a cute lil' app that grabs all RGB and RGBA colour values, changes them into HSB, flips the Brightness, and writes them back as RGB and RGBA [[source code](https://github.com/Atulin/CSSWizard)].
It was well worth it, though. Here's the brand new version. Still has some quirks, but they can be ironed out.

- [Full code](https://gist.github.com/Atulin/cb2d52c8165af4d74614be92fe9ec9b0)
- [Minified](https://gist.github.com/Atulin/cff1013e281e2724951ce2700a36284d)

**Comment by hammy2899** [comment]
This is great and I am sure a lot of people will appreciate this. However, I am going to close this since it isn't an issue or enhancement request.

**Comment by hubertguillemain** [comment]
Maybe it would make sense to add this to http://semantic-ui-forest.com/ ?
