### ISSUE TITLE
[Label] basic "color" should display only it's borders colored.

### ISSUE THREAD

**Issue by joalcava** [Semantic-Org/Semantic-UI#6501]
### Steps
`<div class="ui basic red label">Hola!</div>`

### Expected Result
The label should display with its borders colored red, the font should also be red and the inner background should be white.

### Actual Result
The label is being shown as a flat red rectangle.
### Version
2.3.3

### Testcase
[https://jsfiddle.net/oa7uqLky/](https://jsfiddle.net/oa7uqLky/)

**Comment by ColinFrick** [comment]
Duplicate of #6439
