### ISSUE TITLE
Load SEMANTIC UI ASYNC

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#6502]
Hi,

I am creating a landing page and I reallly need it to open fast but I also really need to use semantic ui cause my entire code depends heavily on semantic ui.

So my question is this: always before loading semantic ui I have to load jquery. I usually load jquery syncronously and then load semantic ui asyincronously. Is there a way I can load jquery AND semnatic ui asyncronously and avoid having problems (in case semantic ui loads faster than jquery)?

**Comment by Atulin** [comment]
You could use the ``.ready()`` function of jQuery. In this case, though, Semantic would start loading only **after** jQuery is loaded.

**Comment by willstott101** [comment]
Could you use [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer)? Loads scripts asynchronously with the html page but execute in the order they appear in the document. That page also has ideas for loading scripts via createElement but keeping them in-order. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async

**Comment by batata004** [comment]
Thanks, indeed defer is a great way to do that! But I ended up using loadJS library which gave me great control over how semantic ui should be loaded!
