### ISSUE TITLE
[Dimmer] Locked scroll page when I use page dimmer

### ISSUE THREAD

**Issue by rccorrea** [Semantic-Org/Semantic-UI#6509]
After I use page dimmer, scroll page stop to working in touchscreens (usually mobile phones).

### Steps
1. Add references:
```
<link rel="stylesheet" type="text/css" href="semantic/semantic.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="semantic/semantic.min.js"></script>
```

2. After start body tag (inside it), add page dimmer:
```
    <div id="dimmerPage" class="ui page dimmer">
        <div class="content">
            Hello
        </div>

        <div class="ui button" onclick="hideDimmer();">
            Close
        </div>
    </div>

    <p>
        <div class="ui button" onclick="showDimmer();">1</div>
    </p>
```

3. Insert function to show and hide page dimmer:
```
    <script>
        function showDimmer() {
            $('#dimmerPage').dimmer('show');
        }

        function hideDimmer() {
            $('#dimmerPage').dimmer('hide');
        }
    </script>
```

### Expected Result
Touchscreen allow to scroll normally (before dimmer, it works).

### Actual Result
Scroll page using touch stop working.
In Chrome > F12 > Ctrl + Shift + M > Elements > Event Listeners: I see a new event, called 'preventScroll', I think that this event, when hide dimmer, needed to be removed.

### Version
2.3.3

### Testcase
https://jsfiddle.net/p3kd6abf/9/

**Comment by lubber-de** [comment]
Fixed in https://github.com/fomantic/Fomantic-UI 2.7.0
