### ISSUE TITLE
[Icon] - Icon does not display.

### ISSUE THREAD

**Issue by midas0925** [Semantic-Org/Semantic-UI#6519]
import React, { Component } from 'react';
import { Icon } from 'semantic-ui-react';

...
<Icon size='large' bordered name='home' />
...

but it doesn't display at all. How can we solve this problem?

**Comment by hammy2899** [comment]
This is a SUI React issue, please create the issue over on the React repo https://github.com/Semantic-Org/Semantic-UI-React
