### ISSUE TITLE
Dropdown in menu inside sidebar

### ISSUE THREAD

**Issue by JCKodel** [Semantic-Org/Semantic-UI#652]
http://jsfiddle.net/7h2t8/

The dropdown menu should appear outside sidebar (now it adds a scrollbar to the sidebar)

**Comment by PrimeByDesign** [comment]
@MohammadYounes - Your example doesn't work.

**Comment by MohammadYounes** [comment]
@PrimeByDesign it's just broken links, updated here http://jsfiddle.net/uT822/27/

**Comment by PrimeByDesign** [comment]
@MohammadYounes That's perfect! Thank you!!
