### ISSUE TITLE
[Sticky] - left side menu bug

### ISSUE THREAD

**Issue by dyens** [Semantic-Org/Semantic-UI#6528]
**Steps to Reproduce**
1. Open some url. For example https://semantic-ui.com/introduction/new.html
2. Open left side menu
3. Click on modules/sticky

**Expected**
As on other site pages i expect that the left side menu will not disappear.

**Result**
 Left side menu was disappeared ;-)

**Comment by hammy2899** [comment]
This is the same on the Container page, this is intended.
