### ISSUE TITLE
[Card] .ui.cards has negative top and bottom margin

### ISSUE THREAD

**Issue by teohhanhui** [Semantic-Org/Semantic-UI#6530]
### Steps
1. Use `.ui.cards`

### Expected Result
It respects the top and bottom margins.

### Actual Result
It sticks too close to what comes before and after. It's especially bad for mobile.

### Version
2.3.1

### Testcase
https://jsfiddle.net/snuvcL9k/1/

**Comment by hammy2899** [comment]
This is intended if you want spacing between your elements that is up to you or you could use a hidden divider https://semantic-ui.com/elements/divider.html#hidden

**Comment by teohhanhui** [comment]
It's not about *adding* spacing. The `.ui.cards` eats up margins because it uses negative margins. This is about being a good citizen.

**Comment by teohhanhui** [comment]
How to be a good UI component: Don't take what's not yours, unless you know it's safe to do so, e.g. a component that's meant to be used together.
