### ISSUE TITLE
[Button] Hover status remains if mouse up is triggered outside of the button in Chrome

### ISSUE THREAD

**Issue by robespmun** [Semantic-Org/Semantic-UI#6551]
### Steps

Click (mouse down) on a button, then drag the mouse outside of it and release the mouse (mouse up).

### Expected Result

The button should return to normal state after triggering the mouse up event.

### Actual Result

The button remains in hover state.

### Version
2.2.12
2.3

### Testcase

You can reproduce it with any button show here https://semantic-ui.com/elements/button.html

As far as I know, the issue only reproduces in Chrome. I am testing in Chrome 68.0.3440.106. I haven't been able to reproduce it in Firefox (I'm running 61.0.2) or IE11 (using 11.0.9600.18860).

**Comment by jlukic** [comment]
This is the browser behavior of `<button>` it will remain focused after clicking.
