### ISSUE TITLE
[Dropdown] - onChange handler's $choice argument always empty

### ISSUE THREAD

**Issue by feeva** [Semantic-Org/Semantic-UI#6555]
**Steps to Reproduce**
1. Initialize a dropdown with onChange handler
2. Do some action(ie. click) to trigger the dropdown selection
3. onChnage handler is called but $choice argument is empty

**Expected**
$choice argument contains jQuery element

**Result**
$choice is undefined

**Testcase**
http://jsfiddle.net/y7npxb3d/

**One more thing to comment**
Dropdown's `action` setting has the function signagure `text, value, element` while `onChange` has `value, text, $choice`. What about making those two have the same form?

**Comment by hammy2899** [comment]
This seems to be the issue when the `action` is set to `hide`

**Comment by jlukic** [comment]
Fixed in next
