### ISSUE TITLE
[icon] Legacy icon "disk outline icon" does not exists in font

### ISSUE THREAD

**Issue by albb0920** [Semantic-Org/Semantic-UI#6556]
### Steps
`<i class="disk outline icon"></i>`

### Expected Result
should display icon as it was in 2.2.x

### Actual Result
![demo](https://i.imgur.com/tqe8vXn.png)
it's shown as tofu

### Version
2.3.3

### Testcase
http://jsfiddle.net/a9zvdw6j/15/

**Comment by hammy2899** [comment]
@albb0920 There is no `disk` icon in semantic, if you are looking for a hard drive you can use `hdd` or `hdd outline`

**Comment by albb0920** [comment]
https://react.semantic-ui.com/elements/icon/
There's disk at least in 2.2, but indeed the outline version isn't in the document.
I'll use outline hdd instead, thanks!

**Comment by jlukic** [comment]
I've fixed the alias for `disk outline icon`
