### ISSUE TITLE
Bug with select not being able to use tiny/mini

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#6561]
Semantic ui docs has an example of dropdown menu that makes use of <select> element. It works fine BUT it does not respect defined sizes. I tried MINI, TINY and it does not work.

Example -> [http://jsfiddle.net/4mpb7cfx/2149/](http://jsfiddle.net/4mpb7cfx/2149/)

So how does one make the select element smaller to fit well side by side with other elements that are using "tiny" size?

Even creating a parent element |form class="ui form tiny"|  it also does not work.

**Comment by ColinFrick** [comment]
Semantic UI dropdowns don't have size modifiers at the moment.
