### ISSUE TITLE
Dropdown on iOS's focus cursor should remain situated in the focused input, but is moving out of the focused input.

### ISSUE THREAD

**Issue by the-simian** [Semantic-Org/Semantic-UI#6575]
### Steps
1. use the dropdown as normally you would do in iOs
2. Its broken.

### Expected Result
1. the cursor does not 'fly out' of the input vertically

### Actual Result
2. the cursor really does 'fly out' of the input vertically
![image](https://user-images.githubusercontent.com/954596/45454337-20c04580-b6a9-11e8-9aa7-231f6402c9ce.png)
### Version
2.3.1

### Testing
The semantic ui dropdown is confirmed as working as expected on the following

- the IOS simulator inside of Xcode (all versions of ios in the simulator)
- an Ipad running safari
- All browsers I tested (even IE)
- Android (Tested on an edge 6 plus as well as a Note 9, actual hardware not simulator)

it DOES NOT CORRECTLY work on

- Iphone 7and  Iphone 7 plus

**Comment by the-simian** [comment]
```
        $('.your-dropdown').dropdown({
          showOnFocus: true,
          selectOnKeydown: false,
          forceSelection: false,
          onChange: changeHandlerHere //whatever you do to change stuff here.
          delay: { hide: 300, show: 200, search: 50, touch: 250 }
        })
```

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/ca0rovs3/) to replicate the issue?

**Comment by the-simian** [comment]
@hammy2899 do you have a jsfiddle template you use with the latest libraries already imported? I am just using the code above. I don't have a lot of time to set up a repro today because I unfortunately spent a lot of my time budget diagnosing this across all the hardware devices I listed upthread

**Comment by hammy2899** [comment]
@the-simian Yes fork this fiddle, it has the latest version of semantic ready to use https://jsfiddle.net/ca0rovs3/

**Comment by the-simian** [comment]
I've set up this like I've observed the issue, but I still need to test on iOS
https://jsfiddle.net/e3fytkj0/11/

**Comment by the-simian** [comment]
I wanted to pop back in, I've been researchign this for some time. Its possible this is a more fundamental issue in iOS, and not necessarily the fault of this library: https://bugs.webkit.org/show_bug.cgi?id=138201

that said, I need to close the issue
