### ISSUE TITLE
Update with npm in custom directories

### ISSUE THREAD

**Issue by etshy** [Semantic-Org/Semantic-UI#6593]
I have a problem updating semantic-ui with npm

I installed semanticui 2.3.1 somes months ago and I have this semantic.json

```
{
  "base": "assets\\semantic\\",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "autoInstall": false,
  "rtl": false,
  "version": "2.4.0"
}
```

As you see I installed the sources in `assets\semantic\` (Symfony project)
When I did an `npm update`, the version prop was updated in the file, as you can see, but the sources in `assets\semantic\` are still in 2.3.1. as you can see in the the following file

Start of the `dist\semantic.js`

```
/*
 * # Semantic UI - 2.3.1
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
/*!
 * # Semantic UI 2.3.1 - Site
 * http://github.com/semantic-org/semantic-ui/
 *
 *
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
```

I have the updated files in the `node_modules\semantic-ui` forder though.

If a gulp taks is needed, maybe the doc should be updated ?

**Comment by hammy2899** [comment]
You will need to run `gulp build` to build the new update.

**Comment by etshy** [comment]
Oh yeah thanks, seems It worked great.

Maybe adding this to the docs (I dunno if it's possible to add a automated script at the end of the `npm update` to do it automatically ?)

**Comment by etshy** [comment]
You mean at the end of the `npm update` ? Yeah that could make that clearer.
