### ISSUE TITLE
[Dropdown] `clearable` is not workin with `on: 'hover'` option

### ISSUE THREAD

**Issue by mthoretton** [Semantic-Org/Semantic-UI#6594]
### Steps

`$('.ui.dropdown').dropdown({transition: 'drop', on: 'hover', clearable: true,});`

### Expected Result

I'd expect I can click the `x` to clear the selection.

### Actual Result

The `x` cannot be clicked.

### Version
2.4.0

### Testcase
https://jsfiddle.net/aeou6q5m/

**Comment by mthoretton** [comment]
Also, even if I didn't manage to reproduce in the jsfiddle, the dropdown items are blurry when I open it (only with `clearable`)
![screen shot 2018-09-21 at 15 08 19](https://user-images.githubusercontent.com/6221533/45883048-3ff95a00-bdb0-11e8-878a-783a928d8e08.png)
=> when I move the pointer over it gets back to normal
![screen shot 2018-09-21 at 15 08 33](https://user-images.githubusercontent.com/6221533/45883049-3ff95a00-bdb0-11e8-99da-a379ac46970b.png)

. They become normal when I move the pointer over the list.

**Comment by jlukic** [comment]
Although from a UX perspective I don't think its a great idea to use `hover` with a clickable clear icon, it is still a bug. I'll fix.

**Comment by mthoretton** [comment]
Thanks for looking at it! And yes, even if it's fixed I'll probably keep "non-hover" dropdowns with `clickable`

**Comment by jlukic** [comment]
This was fixed in `2.4.1`

**Comment by lubber-de** [comment]
Also fixed in https://github.com/fomantic/Fomantic-UI 2.6.3
