### ISSUE TITLE
Hamburger icon

### ISSUE THREAD

**Issue by SamirMokiem** [Semantic-Org/Semantic-UI#6598]
## Feature Request

Make the 'side bar' icon easy to find in the http://react.semantic-ui.com/elements/icon/search.

### Problem description
I was searching for the hamburger icon. i searched `hamburger`, `lines` and `triple`. but with that i couldn't find it. Then i searched on the non react version site and found the icon on the home page. With developer tools, i found out it was called 'sidebar'. I am used to calling it a hamburger menu from a android developer view.

### Proposed solution
Make it possible to find it with `hamburger`, `lines` or `triple`

**Comment by ColinFrick** [comment]
It's actually the `bars` icon from fa: https://fontawesome.com/icons/bars

**Comment by hammy2899** [comment]
We should add `hamburger` as an alias.

**Comment by SamirMokiem** [comment]
> It's actually the `bars` icon from fa: https://fontawesome.com/icons/bars

If you search on `hamburger` you also find it
https://fontawesome.com/icons?d=gallery&q=hamburger

**Comment by hammy2899** [comment]
@SamirMokiem FontAwesome use keywords to search https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml#L926. SUI does not do that is searches purely from the icon name.

**Comment by lubber-de** [comment]
https://github.com/fomantic/Fomantic-UI 2.7.2 includes the hamburger alias
