### ISSUE TITLE
Adobe XD UI Kit

### ISSUE THREAD

**Issue by johnpauljrabanal** [Semantic-Org/Semantic-UI#6610]
Hello guys,

Good day!

Just want to know if semantic-UI has a toolkit for **Adobe XD?**
Thank you in  advance.

**Comment by laszlogulasz** [comment]
You can use this Semantic UI Sketch Styleguide: https://github.com/stoneddesigner/semantic-ui-sketch

**Comment by johnpauljrabanal** [comment]
@zyzniewski thanks bro! that was great!

**Comment by olefredrik** [comment]
Just finished up a complete UI Kit for Adobe XD based on the components in Semantic https://medium.com/@olefredrik/designing-a-complete-ui-kit-for-adobe-xd-based-on-semantic-ui-f214fae8ec37?sk=bba62a6599216224d87496f9a6e1688d
