### ISSUE TITLE
Inline fields - Label text with spaces breaks

### ISSUE THREAD

**Issue by pavangayakwad** [Semantic-Org/Semantic-UI#6613]
Please check the screen shot. Label with space in between words wraps. Looks like a bug.

![image](https://user-images.githubusercontent.com/1834890/46574426-d8065e80-c9c0-11e8-8a4f-35a0c38863de.png)

**Comment by CrispyBacon1999** [comment]
I was able to achieve this by wrapping the inline fields div in an eight wide column. I think it just doesn't like having sizing on the specific field, as it works fine if you place it surrounding the entire element. https://jsfiddle.net/2vyt7wru/8/

**Comment by CrispyBacon1999** [comment]
It's not really something that semantic can do as it doesn't work with their current grid system and field system. The inline fields will style themselves to fit the container properly, but then when you add grid sizing to it, that styling will change. All the `inline fields` box does is make display the fields inside with flexbox, but then by adding column sizing inside that flexbox, it modifies how the elements render. By wrapping the entire `inline fields` with the column, it does the flexbox positioning outside the fields and allows the field to figure out how big it wants the components to be.
