### ISSUE TITLE
Dropdown menu items's description issue

### ISSUE THREAD

**Issue by t-edward** [Semantic-Org/Semantic-UI#6615]
Given we have:
```
<div class="ui dropdown button">
    <i class="filter icon"></i>
    <div class="menu">
        <div class="item" data-value="all">
            <span class="description">10</span>
            <span class="text">All Pages</span>
        </div>
        <!-- More items -->
    </div>
</div>
```

The menu is not showing correctly just because the button text is too short (an icon).
It's like the menu's width depends on the button's width.

Here is a screenshot from Semantic UI's website.
I have changed the label to "1"
![screen shot 2018-10-07 at 3 35 58 pm](https://user-images.githubusercontent.com/5211235/46581554-70dfbd00-ca47-11e8-8b15-ad55d143ee30.png)

**Comment by tcmal** [comment]
From your screenshot: "Using a description may require setting a minimum width on menu to prevent content overlap."
