### ISSUE TITLE
[Input] invalid pseudoclass should work same as error class

### ISSUE THREAD

**Issue by palindrom615** [Semantic-Org/Semantic-UI#6618]
### Title
[Input] invalid pseudoclass should work same as error class

As an web developer using react, it is big sadness that both using browser built-in validation feature like `type` or `pattern` attribute of `input` element and semantic ui library is bit complex.

It would be great if both error class and `input` element having `:invalid` pseudo class results same. for example,
```jsx
<Input error={emailValidationFunction(value)} />
```
and
```jsx
<Input type="email" />
```

Actually I already worked on it on my work. I hope using standard html attribute in semantic ui considered more positively.

**Comment by lubber-de** [comment]
The community fork Fomantic-UI prepared that by https://github.com/fomantic/Fomantic-UI/pull/2085
The additional placeholder selectors are not necessaryy, because such fields only get invalid by the browsers, if at least something has been entered (thus no placeholder seen anymore)
