### ISSUE TITLE
[Dropdown] Getting no text or value from Multiple Selection dropdown.

### ISSUE THREAD

**Issue by MangeSwe** [Semantic-Org/Semantic-UI#6620]
### Steps
Creating multiple selections dropdown with data from API

### Expected Result
When using .dropdown('get text' or 'get value') get content in a array.

### Current result
Nothing. 

### Code
[jsfiddle](https://jsfiddle.net/k3ubhp84/)

**Comment by jlukic** [comment]
In all these cases you are referencing the original `<select>` element and not the transformed dropdowns.

**Comment by MangeSwe** [comment]
I have also tried this that should be the correct way if I have understood correctly (opt 1).

```
<select id="drp1" class="ui fluid multiple selection dropdown opt1" multiple="">
</select>
```
```
var tmp = $('.ui.dropdown.opt1').dropdown('get value');
var tmp2 = $('.ui.dropdown.opt1').dropdown('get text');
```

[JSFiddle](https://jsfiddle.net/k3ubhp84/2)
