### ISSUE TITLE
Style name conflict: "list"

### ISSUE THREAD

**Issue by nusco** [Semantic-Org/Semantic-UI#6649]
Using the "list" icon in a "ui list" messes it up.
Demo of the issue: https://codepen.io/nusco/pen/bmyOOE

**Comment by jd17ortiz** [comment]
+1

**Comment by exoego** [comment]
I think this issue is a duplication of https://github.com/Semantic-Org/Semantic-UI/issues/2427

**Comment by nusco** [comment]
> I think this issue is a duplication of #2427

Confirmed, it's the same issue. The original issue is labeled Stale. What's the policy in these cases? Un-stale the original and close this one?

**Comment by hammy2899** [comment]
As this is a duplicate I will close this issue but thanks for the pen.

**Comment by lubber-de** [comment]
This is fixed in https://github.com/fomantic/Fomantic-UI
See http://jsfiddle.net/qbwp0jsa/
