### ISSUE TITLE
Using semantic.min.js and semantic-ui-react.min.js on the same page

### ISSUE THREAD

**Issue by aktywnitu** [Semantic-Org/Semantic-UI#6662]
How to use semantic.min.js and semantic-ui-react.min.js on the same page?
For example I have problem with Dropdown component (react) (inline style for menu "display:block!important" is added by first library, but is not removed).
Have sombody some nice solution?

**Comment by hammy2899** [comment]
This is a SUI React issue, please create the issue over on the React repo https://github.com/Semantic-Org/Semantic-UI-React
