### ISSUE TITLE
[From Validation] should be initializing on all elements with a specified identifier to have the same ruleset be applied to multiple fields

### ISSUE THREAD

**Issue by msj121** [Semantic-Org/Semantic-UI#667]
Is there a way to validate multiple form elements with the same name/id/class?

With php you submit multiple elements with name="value[]" and it is turned into an array on post.

But it might be valuable to allow one to validate all inputs with class "notEmpty" and then to make a rule with an identifier: "notEmpty" and try to add "." before just as much as "#" is added.

This is extremely useful when dynamically adding fields to a form especially when the fields allow for multiple of the same information like contacts, as you can see:

http://jsfiddle.net/wq4wL/

Using name for multiple fields won't work since they are all highlighted with errors even if one has a value and one not. Please advise the best solution.....

**Comment by burka** [comment]
@jlukic @Anachron 
The data-validate does not work for multiple inputs as suggested in you answer, or am I doing wrong?
See: http://jsfiddle.net/n8uqe74c/
Thanks!

**Comment by avalanche1** [comment]
@burka Totally agree!
Seems like right now we cannot have same rule applied to multiple fields.
Think this should be reopened.

**Comment by roelvan** [comment]
should be reopened indeed

**Comment by jhaesus** [comment]
+1

**Comment by shivekundefined** [comment]
Well don't know but above examples not working. It is not validating dynamically added fields individually. See this fiddle -> [http://jsfiddle.net/shivek/mf0kcL9q/2/](url) 

But I found a hack and done this.. [https://jsfiddle.net/d1x99xwg/12/](url)

Not sure whether there is another better way then this or not but it worked for me. Any suggestions or any other working solutions are welcome and appreciated.

**Comment by Emielangelaan** [comment]
Agreed that all fields with the same name should be initialized for validation. We have a dynamic form where more date fields can be added when needed. When added, the fields are required and should be validated. We just replicate the part of the validation object a couple of times now and give each field an incrementing ID. Very ugly, but it works.

**Comment by picitelli** [comment]
Any update on this? Being able to validate on fields with the same name would be very helpful.

**Comment by Johanbo123** [comment]
+1

**Comment by kodamirmo** [comment]
+1

**Comment by kabapy** [comment]
+1

**Comment by kabapy** [comment]
here is my code, i use 2 data attribute:
1- data-validate: the data validate name used as identifier by the validator
2- data-validate-group : to search for the validation group and rename all group members data-validate attribute

then i create the validator object and init the validation on the form on the submit event
` validationObj = {
            error: function (errors) {
                var
                    html = '<ul class="list">'
                    ;
                $.each(errors, function (index, value) {
                    html += '<li>' + value + '</li>';
                });
                html += '</ul>';
                return $(html);
            },
            fields: {
                vendorName: 'empty',
                amount: 'empty',
                invoice: 'empty',
                invoiceDate: 'empty',
                invoiceReference: 'empty',
                paymentDue: 'empty',

                terms: 'checked'
            }
        }

// re-index all complex validation ids in data-validate
        var complexItems = [];
        $("[data-validate-group='complex-allocation']").each(function (index, item) {
            var $item = $(item);
            $item.attr("data-validate", "complex-allocation-" + index);
            complexItems.push("complex-allocation-" + index)
        });

if (advancedAllocationFlag) {
            // advanced complex allocation validation
            for (i = 0; i < complexItems.length; i++) {
                validationObj.fields[complexItems[i]] = 'empty';
            }
        } else {
            for (i = 0; i < simple_allocation_validation.length; i++) {
                validationObj.fields[simple_allocation_validation[i]] = 'empty';
            }
        }

        // add validation
        $('#mainForm').form(validationObj);
`
