### ISSUE TITLE
Search dropdown with allowAdditions submits form on enter key

### ISSUE THREAD

**Issue by dfsmirnov** [Semantic-Org/Semantic-UI#6672]
The form should ignore Enter key presses from the dropdown's search input wheh allowAdditions=true too .

Reproducible jsfiddle, type on keybord new value, then push Enter to finish typing, form will submit:
http://jsfiddle.net/bojf4m1c/

 Semantic UI - 2.4.2

**Comment by lubber-de** [comment]
Fixed since 2.7.0 https://github.com/fomantic/Fomantic-UI/pull/320

**Comment by ivangomes** [comment]
Please close this.
