### ISSUE TITLE
Drop down list item half displayed

### ISSUE THREAD

**Issue by mind0n** [Semantic-Org/Semantic-UI#6696]
### Drop down list item half displayed
![image](https://user-images.githubusercontent.com/1991295/49327785-9b11af00-f5a0-11e8-8773-d072bb46f60f.png)

### Steps
1. Go to https://semantic-ui.com/introduction/new.html with latest Chrome browser
2. Scroll down to Clearable Dropdowns section
3. Click the dropdown
### Expected Result
Menu item South Korea should be displayed correctly

### Actual Result
Only half of South Korea menu displays

### Version
2.4

### Testcase
https://semantic-ui.com/introduction/new.html

**Comment by V1shvesh** [comment]
I am a first contributor and I'd like to work upon this issue. Can I be assigned to it?

**Comment by samrae7** [comment]
<img width="898" alt="Screenshot 2019-10-19 at 10 08 03" src="https://user-images.githubusercontent.com/4126146/67141131-6827e680-f258-11e9-9cb5-31daf647d620.png">
Looks like this is fixed/no longer an issue
