### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by Jncocontrol** [Semantic-Org/Semantic-UI#6698]
/topic

Am i doing something wrong? I typed the code in correctly and still not working

**Comment by lubber-de** [comment]
Please create a jsfiddle to reproduce the issue you encounter.

**Comment by Jncocontrol** [comment]
https://jsfiddle.net/d5gfec91/

**Comment by lubber-de** [comment]
You forgot to include the library 😉
https://jsfiddle.net/d5gfec91/3/
