### ISSUE TITLE
which themes are included in jsDeliver cdn?

### ISSUE THREAD

**Issue by landall** [Semantic-Org/Semantic-UI#6704]
Is there only the precompiled default theme?
I cannot find the .min.css of the other themes. T_T

**Comment by xiaohanyu** [comment]
Hi, @landall 

The official semantic-ui's repo do not have precompiled themes.

However, good news is, I have built some precompiled themes:

https://github.com/semantic-ui-forest/forest-themes

But I still need some time to publish these prebuilt themes to npm, and update.

Just give me some time.

**Comment by landall** [comment]
> Hi, @landall
> 
> The official semantic-ui's repo do not have precompiled themes.
> 
> However, good news is, I have built some precompiled themes:
> 
> https://github.com/semantic-ui-forest/forest-themes
> 
> But I still need some time to publish these prebuilt themes to npm, and update.
> 
> Just give me some time.

Thanks for your great work!
I'm using Sina Cloud so there is no ssh access to compile anything.

**Comment by xiaohanyu** [comment]
@landall 

There're some prebuilt themes here: https://github.com/semantic-ui-forest/forest-themes/tree/master/dist

The bootstrap-v3 and semantic-ui theme should be OK, while the bootstrap-v4 is still under construction. Give me some time.
