### ISSUE TITLE
[Icon] 'linkedin alt' should be 'linkedin alternate'

### ISSUE THREAD

**Issue by hauke-d** [Semantic-Org/Semantic-UI#6707]
### Steps
In the icon docs search for linkedin. 

The correct style is defined for `linkedin alt`, but everywhere else it is `linkedin alternate`. 

### Expected Result
`linkedin alternate` should be a black "in" without a square around it
![image](https://user-images.githubusercontent.com/15606289/49864532-f8102f00-fe02-11e8-90e9-15dc4339072a.png)

### Actual Result
`linkedin alternate` is the same as `linkedin`
![image](https://user-images.githubusercontent.com/15606289/49864493-e3339b80-fe02-11e8-8fa6-298f8de2ff0e.png)

### Version
2.4.X

**Comment by lubber-de** [comment]
https://fomantic-ui.com/elements/icon.html has the latest FontAwesome 5.7 integrated where the icon names differ but the icons are now correctly assigned
![image](https://user-images.githubusercontent.com/18379884/53014677-6e579000-3449-11e9-83a0-a0273c7b0940.png)
