### ISSUE TITLE
Semantic UI fonts are not looking good( Pixel Broken ) in IE, some one help me to fix this

### ISSUE THREAD

**Issue by hajanajubudeen88** [Semantic-Org/Semantic-UI#6708]
hi,
Semantic UI fonts are not looking good( Pixel Broken ) in IE, some one help me to fix this

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/ca0rovs3/) to replicate the issue?

Also please give more of a description of what you mean by pixel broken.

**Comment by hajanajubudeen88** [comment]
Hi Hammy,
Thank You for your reply
Here i attached the two different screen shots that i faced the font shrunk problem in IE and Google Chrome

1. The first image is **Google Chrome** screenshot, the start button is looking awesome. same way i'm looking the same design in **IE** that is also looking good but, its looking a little bit **shrunk**

![chrome](https://user-images.githubusercontent.com/32840808/49921793-b8197c80-fed4-11e8-8aa0-73a704de1b4f.PNG)

2. IE Screenshot
![ie_screenshot](https://user-images.githubusercontent.com/32840808/49921795-b94aa980-fed4-11e8-8797-894c2bea10f5.PNG)

**Comment by hammy2899** [comment]
I just tried this and can't seem to reproduce on IE11
![image](https://user-images.githubusercontent.com/11588822/49926518-a378bc80-feb3-11e8-8f6c-cc40e54bc7d7.png)

What version of IE are you using?

JSFiddle: https://jsfiddle.net/hpezs8qy/

**Comment by hajanajubudeen88** [comment]
I'm using IE11 only, it is showing like what i send you previously, anyways thank you for your great support
