### ISSUE TITLE
[View][Advertisement] online demo page is broken 

### ISSUE THREAD

**Issue by DimalChandrasiri** [Semantic-Org/Semantic-UI#6711]
### Steps
The online documentation and demo page for **Views** -> **Advertisement** shows a 404.

### Expected Result
Should show the relevant page.

### Actual Result
![image](https://user-images.githubusercontent.com/11191791/49929343-4a774b80-fee8-11e8-92e8-973cb7fef602.png)

### Version
0.84.0

**Comment by hammy2899** [comment]
This is a SUI React issue, please create the issue over on the React repo https://github.com/Semantic-Org/Semantic-UI-React
