### ISSUE TITLE
List Item Icon Rotates Around Wrong Point when using Loading Spinner

### ISSUE THREAD

**Issue by HieronymusLex** [Semantic-Org/Semantic-UI#6717]
## Bug Report

From: https://github.com/Semantic-Org/Semantic-UI-React/issues/3342

### Steps
When using a Loading Icon as the floated icon for a List.Icon, the entire icon rotates around a fixed point rather outside the icon bounds, rather than rotating about it's own center. Sorry if that's not very clear but it should be obvious by looking at the codesandbox (link below).

I've tried it with both Icon and List.Icon components

### Expected Result
Icon animation looks natural and rotation origin point is icon's center

### Actual Result
Icon animation rotates around wrong point

### Version
0.84.0

### Testcase
https://codesandbox.io/s/98709pjw24

**Comment by lubber-de** [comment]
This is a Semantic-UI React issue. It works fine with plain SUI
http://jsfiddle.net/tonpv46c/

```html
<i class="huge spinner loading icon"></i>
```

**Comment by lubber-de** [comment]
Sorry, it can confirm, this happens when the loading icon is inside a List item..., so it's not a SUI React issue

**Comment by lubber-de** [comment]
It is fixed. See here:
http://jsfiddle.net/pn75L2tj/

**Comment by HieronymusLex** [comment]
@lubber-de thanks! will this fix be incorporated into the lib or is the provided CSS workaround the way forward?

**Comment by lubber-de** [comment]
@HieronymusLex It is included in the next release of [Fomantic UI 2.7.2](https://github.com/fomantic/Fomantic-UI/milestone/14?closed=1)
If you still use SUI 2.4 you'll stick to the CSS workaround
