### ISSUE TITLE
An extra space below panel

### ISSUE THREAD

**Issue by ssi-anik** [Semantic-Org/Semantic-UI#6720]
![sematic-panel](https://user-images.githubusercontent.com/2676602/50721459-2f17ee80-10ea-11e9-8e2d-4a1a9e1a08a6.png)
Hey, I am not a CSS or designing guy. I don't even know the exact term what to use in this case. I found this issue in the following page in one of your examples.
https://semantic-ui.com/examples/bootstrap.html

Browser: Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
OS: Ubuntu 18.04

**Comment by ColinFrick** [comment]
@ssi-anik This is a stacked segment:
> A segment can be formatted to show it contains multiple pages
https://semantic-ui.com/elements/segment.html#stacked
