### ISSUE TITLE
styles should not depend on order of class

### ISSUE THREAD

**Issue by yskkin** [Semantic-Org/Semantic-UI#6730]
### Steps
https://jsfiddle.net/y8L6h5c9/

### Expected Result
Both button should float right.

### Actual Result
If `right floated` is not appeared in class exactly same order,
float is not working.

Toggling class in devtool breaks button's float state

### Version
2.4.2

### Testcase
Please see Steps.

**Comment by hammy2899** [comment]
read the following https://github.com/Semantic-Org/Semantic-UI/pull/6731#issuecomment-454052462
