### ISSUE TITLE
[sidebar] Sidebar with overlay class should close and reopen

### ISSUE THREAD

**Issue by jase-languasco** [Semantic-Org/Semantic-UI#6744]
### Steps
1. Add a close button to the sidebar and an open button in the pusher div
2. the sidebar should have the following classes: ui left inverted vertical menu sidebar visible overlay (note: the overlay class is what seems to cause the issue)
3. close the sidebar
4. attempt to reopen it

### Expected Result
ability to toggle overlay sidebar. 

### Actual Result
Close is a little clunky and the sidebar won't reopen. It seems the sidebars z-index is not appropriately reverted after the sidebar is closed

### Version
2.4.1

### Testcase
https://jsfiddle.net/odmhbpce/2/

**Comment by hammy2899** [comment]
@jase-languasco You need to specify the overlay transition in the sidebar settings not as a class, SUI will add the class for you when the sidebar is open. https://jsfiddle.net/g035bcf2/
