### ISSUE TITLE
[Docs] Please remove China Mirror Site

### ISSUE THREAD

**Issue by rmlzy** [Semantic-Org/Semantic-UI#6759]
[The China Mirror Site](http://www.semantic-ui.cn/) belongs to a game company now.

![image](https://user-images.githubusercontent.com/33822612/53392175-914aec80-39d3-11e9-89b5-fe10c8cea8eb.png)

![image](https://user-images.githubusercontent.com/33822612/53392193-a0319f00-39d3-11e9-9d2a-6adfc1c4109e.png)

**Comment by GammaGames** [comment]
I wonder if that was a thing @jlukic normally takes care of, where did he go this time?

**Comment by ctudoudou** [comment]
I also found this problem when I jumped to the Chinese image. I suggested removing this site. Thanks.

**Comment by clarmso** [comment]
According to the Wayback Machine, the domain name has expired. The site was successfully crawled the last time in August 2018.
https://web.archive.org/web/20181101000000*/http://www.semantic-ui.cn

**Comment by rmlzy** [comment]
I'm going to close it because it's repeated.
