### ISSUE TITLE
NPM won't install

### ISSUE THREAD

**Issue by martykan** [Semantic-Org/Semantic-UI#6773]
### Steps

1. Create a new directory, init npm
2. Run `npm install semantic-ui`

### Expected Result

It installs as it should.

### Actual Result

```
# npm install semantic-ui
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> semantic-ui@2.4.2 install /test/node_modules/semantic-ui
> gulp install

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module 'gulp-print'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/test/node_modules/semantic-ui/tasks/watch.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Version
2.4.2

**Comment by martykan** [comment]
A temporary solution currently is to include the gulp-print dependency manually. This works for me.

**Comment by AlighaThor** [comment]
Reporting the same issue.

**Comment by AlighaThor** [comment]
> A temporary solution currently is to include the gulp-print dependency manually. This works for me.

Hi @martykan. Did you install manually gulp-print so?

**Comment by martykan** [comment]
With `npm install gulp-print@5.0.0` it works, 5.0.1 seems to be broken

**Comment by AlighaThor** [comment]
@martykan It worked. Weird, but it worked. Thanks!

**Comment by martykan** [comment]
It's been promptly fixed in gulp-print 5.0.2

**Comment by timbog80** [comment]
Unfortunately, this is still an issue in 2020

```npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> semantic-ui@2.4.2 install /Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui
> gulp install

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm WARN moleculo@1.0.0 No description
npm WARN moleculo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timbogdanov/.npm/_logs/2020-01-25T01_58_49_691Z-debug.log
➜  moleculo```

**Comment by Pledix** [comment]
> Unfortunately, this is still an issue in 2020
> 
> ```
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> 
> > semantic-ui@2.4.2 install /Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui
> > gulp install
> 
> fs.js:35
> } = primordials;
>     ^
> 
> ReferenceError: primordials is not defined
>     at fs.js:35:5
>     at req_ (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:143:24)
>     at Object.req [as require] (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:55:10)
>     at Object.<anonymous> (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
>     at Module._compile (internal/modules/cjs/loader.js:1151:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1040:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
> npm WARN moleculo@1.0.0 No description
> npm WARN moleculo@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! semantic-ui@2.4.2 install: `gulp install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the semantic-ui@2.4.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/timbogdanov/.npm/_logs/2020-01-25T01_58_49_691Z-debug.log
> ➜  moleculo```
> ```

I have same issue! What I need to do?

**Comment by rafaelgrube** [comment]
> > Unfortunately, this is still an issue in 2020
> > ```
> > npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> > 
> > > semantic-ui@2.4.2 install /Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui
> > > gulp install
> > 
> > fs.js:35
> > } = primordials;
> >     ^
> > 
> > ReferenceError: primordials is not defined
> >     at fs.js:35:5
> >     at req_ (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:143:24)
> >     at Object.req [as require] (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:55:10)
> >     at Object.<anonymous> (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
> >     at Module._compile (internal/modules/cjs/loader.js:1151:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
> >     at Module.load (internal/modules/cjs/loader.js:1000:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
> >     at Module.require (internal/modules/cjs/loader.js:1040:19)
> >     at require (internal/modules/cjs/helpers.js:72:18)
> > npm WARN moleculo@1.0.0 No description
> > npm WARN moleculo@1.0.0 No repository field.
> > 
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! semantic-ui@2.4.2 install: `gulp install`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the semantic-ui@2.4.2 install script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /Users/timbogdanov/.npm/_logs/2020-01-25T01_58_49_691Z-debug.log
> > ➜  moleculo```
> > ```
> 
> I have same issue! What I need to do?

Me too!

**Comment by lubber-de** [comment]
Try the actively maintained community fork https://github.com/fomantic/Fomantic-UI which is backward compatible to semanic but uses gulp 4 and updated dependencies (and a lot more features .... :wink:

**Comment by codesofmine** [comment]
> > > Unfortunately, this is still an issue in 2020
> > > ```
> > > npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > > npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > > npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> > > 
> > > > semantic-ui@2.4.2 install /Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui
> > > > gulp install
> > > 
> > > fs.js:35
> > > } = primordials;
> > >     ^
> > > 
> > > ReferenceError: primordials is not defined
> > >     at fs.js:35:5
> > >     at req_ (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:143:24)
> > >     at Object.req [as require] (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:55:10)
> > >     at Object.<anonymous> (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
> > >     at Module._compile (internal/modules/cjs/loader.js:1151:30)
> > >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
> > >     at Module.load (internal/modules/cjs/loader.js:1000:32)
> > >     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
> > >     at Module.require (internal/modules/cjs/loader.js:1040:19)
> > >     at require (internal/modules/cjs/helpers.js:72:18)
> > > npm WARN moleculo@1.0.0 No description
> > > npm WARN moleculo@1.0.0 No repository field.
> > > 
> > > npm ERR! code ELIFECYCLE
> > > npm ERR! errno 1
> > > npm ERR! semantic-ui@2.4.2 install: `gulp install`
> > > npm ERR! Exit status 1
> > > npm ERR!
> > > npm ERR! Failed at the semantic-ui@2.4.2 install script.
> > > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > > 
> > > npm ERR! A complete log of this run can be found in:
> > > npm ERR!     /Users/timbogdanov/.npm/_logs/2020-01-25T01_58_49_691Z-debug.log
> > > ➜  moleculo```
> > > ```
> > 
> > 
> > I have same issue! What I need to do?
> 
> Me too!

Me Too

**Comment by skendall74** [comment]
Closed? I am having the same problem.  In 2020.

**Comment by huayong1678** [comment]
> > > > Unfortunately, this is still an issue in 2020
> > > > ```
> > > > npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > > > npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> > > > npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> > > > 
> > > > > semantic-ui@2.4.2 install /Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui
> > > > > gulp install
> > > > 
> > > > fs.js:35
> > > > } = primordials;
> > > >     ^
> > > > 
> > > > ReferenceError: primordials is not defined
> > > >     at fs.js:35:5
> > > >     at req_ (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:143:24)
> > > >     at Object.req [as require] (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/natives/index.js:55:10)
> > > >     at Object.<anonymous> (/Users/timbogdanov/Desktop/sites/moleculo/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
> > > >     at Module._compile (internal/modules/cjs/loader.js:1151:30)
> > > >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
> > > >     at Module.load (internal/modules/cjs/loader.js:1000:32)
> > > >     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
> > > >     at Module.require (internal/modules/cjs/loader.js:1040:19)
> > > >     at require (internal/modules/cjs/helpers.js:72:18)
> > > > npm WARN moleculo@1.0.0 No description
> > > > npm WARN moleculo@1.0.0 No repository field.
> > > > 
> > > > npm ERR! code ELIFECYCLE
> > > > npm ERR! errno 1
> > > > npm ERR! semantic-ui@2.4.2 install: `gulp install`
> > > > npm ERR! Exit status 1
> > > > npm ERR!
> > > > npm ERR! Failed at the semantic-ui@2.4.2 install script.
> > > > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > > > 
> > > > npm ERR! A complete log of this run can be found in:
> > > > npm ERR!     /Users/timbogdanov/.npm/_logs/2020-01-25T01_58_49_691Z-debug.log
> > > > ➜  moleculo```
> > > > ```
> > > 
> > > 
> > > I have same issue! What I need to do?
> > 
> > 
> > Me too!
> 
> Me Too

Me Too. In 2020

**Comment by ggcaponetto** [comment]
welcome 2020

**Comment by gordiash** [comment]
same here

**Comment by ggcaponetto** [comment]
I moved to fomantic UI without any problem

**Comment by iamphoenix310** [comment]
Same issue I am facing in 2021
