### ISSUE TITLE
[Dropdown] allowAdditions set to true, message "addResult" not appearing when typing in new value

### ISSUE THREAD

**Issue by stimularity** [Semantic-Org/Semantic-UI#6785]
### Steps
The error is visible in the live docs:
https://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions

* Setup semantic dropdown with allowAdditions: true
* Type in new tag
* Dropdown displaying 'Add <b>{term}</b>' does not appear

### Expected Result
Addition item menu should appear, displaying "text to add {term}."

### Actual Result
No menu appears.

### Version
2.4.1

**Comment by lubber-de** [comment]
Use `hideAdditions:false;`

**Comment by stimularity** [comment]
That was the issue. Thank you.
