### ISSUE TITLE
semantic-ui mirror is a advertising site

### ISSUE THREAD

**Issue by HelloGit100** [Semantic-Org/Semantic-UI#6801]
When I click to switch to Simplified Chinese, 

想访问镜像站点吗?
Semantic 有了一个位于中国的镜像站点 semantic-ui.cn, 中国大陆地区的人应该访问起来会更快.

semantic-ui.cn is a advertising site，please remove it.

**Comment by hammy2899** [comment]
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6736
