### ISSUE TITLE
[TextInput] - How to get the value of TextInput before it was changed?

### ISSUE THREAD

**Issue by zbeedatm** [Semantic-Org/Semantic-UI#6856]
### Steps
- set a defaultValue for TextInput
- get that value from anywhere before changing or typing any new charachter in it

I have the following:

>  <TextInput
                            id="txtDupProjectName"
                            labelText=""
                            placeholder="Name"
                            required
                            defaultValue={this.projectName + "_Copy"}
                            // invalid={this.dupProjectName === ''}
                            // invalidText="Mandatory"
                            onChange={ e => this.handleDupProjectNameChange(e) }
                        />

If I dont type any charachter inside the textInput (handleDupProjectNameChange isn't called), but need to save my change with default value inside it:

I tried to get the value by plain javascript but didn't work:

> document.getElementsByName('txtDupProjectName')[0].value

**Comment by noxsiio** [comment]
your input has no name. either you give the input a name or do it with it:

`document.getElementsById('txtDupProjectName')[0].value`

**Comment by zbeedatm** [comment]
Yes I realized my mistake and closed it. Thanks anyway
