### ISSUE TITLE
Link For Semantic-UI Theming Example shows a weird Logged in State of @jlukic user

### ISSUE THREAD

**Issue by shaurya-xyz** [Semantic-Org/Semantic-UI#6877]
Link For Semantic-UI shows a weird Logged in State of unknown user

### Description
1) Follow the the theming guide from [docs](https://semantic-ui.com/usage/theming.html)
2) Click on [example Project link](https://semantic-org.github.io/example-github/)

### Expected Result
Should show users logged in account or sign in option

### Actual Result

Shows logged in using @jlukic account

![Screenshot 2019-09-24 at 2 55 09 PM](https://user-images.githubusercontent.com/9611106/65499953-1d76b100-dedc-11e9-9de4-0c15217bf341.png)

### Version
N/A

### Testcase
N/A

**Comment by hammy2899** [comment]
@shaurya-xyz This page is not GitHub, its just a static example page showing you what can be made using Semantic. Also @jlukic is the author of Semantic hence why it shows his user in the example.

**Comment by shaurya-xyz** [comment]
@hammy2899 thanks for pointing out, "example in doc pointing seemed as if it is pointing to code example."
