### ISSUE TITLE
Unclear radio button group usage

### ISSUE THREAD

**Issue by aidv** [Semantic-Org/Semantic-UI#6905]
### Changing radio button name breaks the group
Use the format: [Component] Component Should Do X
i.e. [Checkbox] onChange Should Fire When Update Triggered via DOM

### Steps

Running the following code works
`<div class="ui form">
                            <div class="grouped fields">
                                <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="example2" checked="checked">
                                    <label>Once a week</label>
                                </div>
                                </div>
                                <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="example2">
                                    <label>2-3 times a week</label>
                                </div>
                                </div>
                            </div>
                        </div>`

Changing the value `name=` to anything other than `example2` breaks the group and the other radio buttons in the same group won't uncheck.

Reason to that is that the value `name=` MUST BE THE SAME across all radio buttons in the same group.

**Comment by VanquishedWombat** [comment]
What you observe is standard HTML 4+ (so back to the 90's) behaviour. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox and scroll to the 'Handling multiple checkboxes' section to see an explanation. You have raised this as an issue - IMHO it could be reasonable to consider withdrawing it as it is an issue of knowledge, not of SUI.
