### ISSUE TITLE
[Dropdown] How to show loading mark for dropdown list?

### ISSUE THREAD

**Issue by leadstar116** [Semantic-Org/Semantic-UI#6911]
### Expected Result
First of all, I am so excited to use Semantic UI.
I have one problem with multiple dropdown.
I am using dropdown for selecting cities from USA.
Totally, it has around 28,000 items and it makes lazy loading for selecting and searching for city name.
Is there any way to show loading mark when Dropdown loads all items and search so let customers know it's still working?
Currently, it shows result in 5~8 seconds which is really not good for customers.
### Version
2.4.1

**Comment by GammaGames** [comment]
Have you tried putting an icon in it? It looks like the [icon will turn into a loader](https://fomantic-ui.com/modules/search.html#using-different-response-fields)

![Screen record from 2019-12-23 08 12 33](https://user-images.githubusercontent.com/7832163/71365368-ffacfc80-255b-11ea-94fe-482d4dff1359.gif)

**Comment by leadstar116** [comment]
@GammaGames Thanks for your comment.
How can I add that icon to dropdown?

**Comment by GammaGames** [comment]
The example I linked to has a example for search:

```html
<div class="ui search">
  <div class="ui left icon input">
    <input class="prompt" type="text" placeholder="Search GitHub">
    <i class="github icon"></i>
  </div>
</div>
```

I realized you said you are using a dropdown, not search. The remote content example for search functionality with remote content, why not have an empty dropdown and then filter the list of towns with the entered string?

**Comment by leadstar116** [comment]
@GammaGames 
I am using remote content dropdown but have some minor issue.
List doesn't update even I type nothing existing.
Attached file.
FYI, here's the link to screenshot. https://screencast.com/t/MCgW9ObzI2CT
Thanks.

**Comment by leadstar116** [comment]
`                    <div class="form-group col-md-12">
                        <label class="text-muted">Location (optional) </label><br/>
                        <div class="ui location fluid search semantic selection dropdown">
                            <input type="hidden" name="campaign_location">
                            <div class="default text">Your current city/state</div>
                            <i class="dropdown icon"></i>
                        </div>
                    </div>`

**Comment by leadstar116** [comment]
Hi, @GammaGames 
Any idea for this?

**Comment by lubber-de** [comment]
@leadstar116 See the following example (uses the community fork https://github.com/fomantic/Fomantic-UI 2.8.3, but should work with SUI 2.4 as well)
https://jsfiddle.net/aoqs729v/
![loading_dropdown](https://user-images.githubusercontent.com/18379884/71521188-f1deda80-28bf-11ea-8d04-21009e1b86d1.gif)

**Comment by GammaGames** [comment]
Aha, there he is! I was going to suggest leadstar go post the issue on the fomantic repo because it is actively maintained and has very helpful (and faster to respond) users :)

**Comment by leadstar116** [comment]
Thank you, guys!
Sorry for the late response but this helped me...

**Comment by GreG2MarS13** [comment]
to force loader on remote (multiple) search dropdown if not visible :

css: 
```
.ddloader {
        color:transparent!important;
        cursor:default!important;
    }

    #yourDropdown.loading .ddloader {
        color: blue !important;
    }
```
Jquery : 
`$('#yourDropdown input:first-child ').after('<i class="dropdown icon ddloader"></i>');`
