### ISSUE TITLE
Cannot install semantic-ui on windows

### ISSUE THREAD

**Issue by Dylekter** [Semantic-Org/Semantic-UI#6914]
How to fix it?

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users...

**Comment by Yomi-daniel1** [comment]
I am experiencing the same error. 
Pls how did you resolve it?

**Comment by lubber-de** [comment]
You may try the active community fork [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) which supports Gulp 4
```
npm install fomantic-ui
npx gulp build
```
https://fomantic-ui.com/introduction/getting-started.html
