### ISSUE TITLE
When " npm install semantic-ui --save "

### ISSUE THREAD

**Issue by Darshan197** [Semantic-Org/Semantic-UI#6915]
> semantic-ui@2.4.2 install C:\xampp\htdocs\node_modules\semantic-ui
> gulp install

fs.js:33
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:33:5
    at req_ (C:\xampp\htdocs\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\xampp\htdocs\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\xampp\htdocs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm WARN rollback Rolling back is-data-descriptor@1.0.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdocs\node_modules\define-property\node_modules'
npm WARN rollback Rolling back glob@5.0.15 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdocs\node_modules\rework-import\node_modules'
npm WARN rollback Rolling back glob@3.1.21 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdocs\node_modules\globule\node_modules'
npm WARN rollback Rolling back minimatch@0.2.14 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdocs\node_modules\globule\node_modules'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\package.json'
npm WARN htdocs No description
npm WARN htdocs No repository field.
npm WARN htdocs No README data
npm WARN htdocs No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DC\AppData\Roaming\npm-cache\_logs\2020-01-07T11_55_57_874Z-debug.log

**Comment by Darshan197** [comment]
I have install the gulp globally

**Comment by lubber-de** [comment]
Does it work when using the community fork https://github.com/fomantic/Fomantic-UI instead? That works with gulp 4 and latest dependencies

**Comment by Darshan197** [comment]
It is some what working but when Run " npx gulp build " it stuck after some time.

**Comment by Darshan197** [comment]
Thanks Now It Is Working.
