### ISSUE TITLE
How To Integrate Semantic-UI IN Vue JS ??

### ISSUE THREAD

**Issue by Darshan197** [Semantic-Org/Semantic-UI#6916]
Any Body Have Idea That How To Integrate Semantic-UI IN Vue JS ?
In my main.js i import it like this

**import './assets/scss/app.scss'
require('fomantic-ui')**

And My app.scss is like this
**@import '~fomantic-ui/dist/semantic.min.css';**

**Styling Is Working But Js doesn't** 
Any Body Please Help With This....

**Comment by truesteps** [comment]
Just use semantic-vue, trust me on thisone, you will burn yourself trying to make semantic work with VUE, i've been struggling for 2 years and I'm at a point where i'm thinking of rewriting it all to vuetify :D Much better framework for VUE

**Comment by Darshan197** [comment]
Sorry But My Problem Is Solved.
Successfully Integrated Semantic UI With VUE.

Thanks

**Comment by vinayakkulkarni** [comment]
If you're OK with jQuery in your bundle, you can easily integrate Semantic-UI with Vue.js codebase.

gulp takes care of everything.

**Comment by Darshan197** [comment]
It Can Be Done Without gulp Also.
No need to build semantic-ui
Just Use It Like Any Other Dependency
