### ISSUE TITLE
mobile view problem 

### ISSUE THREAD

**Issue by hamzehparsi** [Semantic-Org/Semantic-UI#6965]
hi
In mobile mode, the scrollbar has a horizon axis !!! ???

![Untitled](https://user-images.githubusercontent.com/13706093/77403798-6990a880-6dce-11ea-824b-ecc5989c3c53.png)

**Comment by felixmosh** [comment]
Related to this code, https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/globals/site.less#L132-L170.

**Comment by hamzehparsi** [comment]
thanks
