### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by kathusha** [Semantic-Org/Semantic-UI#6970]
![screen shot 2018-11-09 at 11 09 15](https://user-images.githubusercontent.com/9863988/48253455-f15f5800-e40f-11e8-9d53-5931740c54cf.png)

To follow up on this, wrapping with span would still require a lot of customization to have it functional.

I have yet to try overriding `pointer-events`

EDIT: I tried `pointer-events`. It requires me to annotate the rule with `important!` (because the original one does). And now it appears on hover, but doesn't disappear on mouse leave...

I would really appreciate an example where none of the above unexpected behaviors applies.

_Originally posted by @quanganhtran in https://github.com/Semantic-Org/Semantic-UI/issues/4296#issuecomment-437298277_

**Comment by kathusha** [comment]
I am facing the same issue.  Can anyone help me on this

**Comment by dandv** [comment]
@kathusha: can you please edit the title of your issue?
