### ISSUE TITLE
while installing semantic-ui

### ISSUE THREAD

**Issue by gokuljs** [Semantic-Org/Semantic-UI#6971]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://www.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI
      SO - https://stackoverflow.com/questions/tagged/semantic-ui?sort=votes

✔ Enhancements → Be specific. Assume backwards compatibility is a necessity. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable due to backwards compatibility or CSS limitations.

### Title (Put in field above)
Use the format: [Component] Component Should Do X
i.e. [Checkbox] onChange Should Fire When Update Triggered via DOM

### Steps
installing semantic-ui using npm
npm install semantic-ui
### Expected Result
package should be installed 
### Actual Result

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jsgok\AppData\Roaming\npm-cache\_logs\2020-04-17T21_44_33_375Z-debug.log
![Screenshot (59)](https://user-images.githubusercontent.com/51263906/79616847-a88ef100-8123-11ea-96c2-0dbbad6a469b.png)

### Version
x.y.z

### Testcase
[Fork, update, and replace to show the bug]:
https://jsfiddle.net/ca0rovs3/

**Comment by HJFallen** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/6934 I found this, it seems to be the same issue. Hope this helps.

**Comment by gokuljs** [comment]
i think installation dosen't work i found out this https://fomantic-ui.com/ they have migrated to fomantic-ui

**Comment by gokuljs** [comment]
even this uses semantic-ui

**Comment by HJFallen** [comment]
Its a community release that is updated so that the install still works. I had the same issue and used fomantic UI and it worked. Its the exact same thing, just updated to work with all of the dependencies.

**Comment by tully4school** [comment]
> i think installation dosen't work i found out this https://fomantic-ui.com/ they have migrated to fomantic-ui

THANK YOU!!!
