### ISSUE TITLE
Set Selected Value For Multiple Select with Other Initialization Paramaters

### ISSUE THREAD

**Issue by cupcakedream** [Semantic-Org/Semantic-UI#6978]
Hey All - 

I'm trying to set selected values for a multiple select dropdown but I can't seem to figure out how to do this during initialization. I know I can do it after initialize but I want to avoid firing an onchange event at all costs. I've looked everywhere can't seem to figure out how to do this. Is it not supported?

```
    jQuery('.outcome select').dropdown({
        selected : [1,2,3,4,5],
        onChange : function( x,y,z ) {
            jQuery.ajax({ url : 'ajax.php', method : 'post',
                data : { action : 'outcome', id : y }
            });
        }
    });
```

**Comment by iamareebjamal** [comment]
Semantic-UI has been deprecated for years now, please use fomantic UI

**Comment by lubber-de** [comment]
@iamareebjamal He already posted the same issue at Fomantic-UI and it is already answered, solved and even fixed with an additional PR there 😉 
https://github.com/fomantic/Fomantic-UI/issues/1470
https://github.com/fomantic/Fomantic-UI/pull/1471

**Comment by iamareebjamal** [comment]
Great 👍😊

**Comment by cupcakedream** [comment]
Yup it's all set, thanks all!
