### ISSUE TITLE
[Menu] - Dropdown menu display error using vertical class

### ISSUE THREAD

**Issue by AchievedOwner** [Semantic-Org/Semantic-UI#6997]
## Code as below
```
<div class="ui compact menu vertical">
    <div class="ui simple dropdown item">
        Dropdown
        <i class="dropdown icon"></i>
        <div class="menu">
            <div class="item">Choice 1</div>
            <div class="item">Choice 2</div>
            <div class="item">Choice 3</div>
        </div>
    </div>
</div>
```
## Result 
![image](https://user-images.githubusercontent.com/52902266/88018478-6201c600-cb5a-11ea-94a0-86fba5d7e4f0.png)

and I also cannot click the dropdown items

**Comment by lubber-de** [comment]
This was already fixed in the active community fork [Fomantic-UI](https://fomantic-ui.com)
See your fixed example here https://jsfiddle.net/lubber/qhzv6kag/
