### ISSUE TITLE
[Dropdown] - No inverted class

### ISSUE THREAD

**Issue by NorteX-dev** [Semantic-Org/Semantic-UI#6998]
**Steps to Reproduce**
1. Add a dropdown element of Semantic UI
2. Try to invert it / the expandable menu with the `inverted` class

**Expected & Result**
The Dropdown should turn "dark-mode" (inverted) but does not. As far as I know, every element should have an inverted mode. I need it as I'm making my page all dark-mode.

**Testcase**
The dropdown works fine, just no class, so the testcase is not required.

**Comment by lubber-de** [comment]
The active community fork Fomantic-UI already provided an inverted variant for dropdown since 2 years
See https://fomantic-ui.com/modules/dropdown.html#inverted

**Comment by NorteX-dev** [comment]
Oh, ok. Didn't even know semantic UI was not maintained anymore.
