### ISSUE TITLE
何时会支持 vue 

### ISSUE THREAD

**Issue by littlefrogfromthenorth** [Semantic-Org/Semantic-UI#7010]
✔ Enhancements

何时会支持 vue

**Comment by sasharevzin** [comment]
I assume the guy is asking when we are planning to support Vue.
@littlefrogsite Here the link you can use: https://semantic-ui-vue.github.io/#/

**Comment by littlefrogsite** [comment]
Yes.
Thanks

**Comment by carkod** [comment]
@jlukic this needs to be closed
