### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by pipozzz** [Semantic-Org/Semantic-UI#7027]

**Comment by prudho** [comment]
Oh boy here we go again...

Please take a look at these issues before: #6109, #6418, #6945, #4886, #4059, #3894, #3637...

Captain as abandonned the ship, leaving the boat adrift... Luckily some people decided to fork the project in the repo [Fomantic UI](https://github.com/fomantic/Fomantic-UI/), which is basically the same framework with a ton on bugfixes, news features, and oh, an active development.

**Comment by pipozzz** [comment]
thanks for the info 👍

**Comment by codler** [comment]
@layershifter can you pin this issue to let others know that this project is dead?

**Comment by layershifter** [comment]
@codler I am not a maintainer of this repro and simply does not have permissions 🤔 

I am working only on [Semantic UI React](https://github.com/Semantic-Org/Semantic-UI-React) and it's alive, we recently released `2.0.0`. Folks from [Fomantic UI](https://github.com/fomantic/fomantic-ui) are doing good job with maintaining a fork of Semantic UI.

**Comment by kierenj** [comment]
Has there been no official announcement/word at all?
