### ISSUE TITLE
[Form Validation] "Is Valid" Method Needed

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#703]
You should be able to call $('#myForm').form('is valid') and have it return a boolean value.

A use case is preventing a modal from closing onApprove by returning if the form is valid.

**Comment by gabro** [comment]
It's been a year, any updates on this?
Or is there another way to synchronously know whether a form is valid?

**Comment by jackbarham** [comment]
Is there anyway to listen if the form is valid or not - If the form is valid/invalid I would like to toggle the disabled class in the submit button so the user cannot close the modal unless all fields are valid?

**Comment by DruidKuma** [comment]
Still need solution to check if form is valid from my code...

**Comment by jlukic** [comment]
Lost this thread somewhere in the ages. Will revisit some additional, obvious, missing form behaviors after `2.0` launch.

**Comment by jlukic** [comment]
@DruidKuma 

I've added `is valid` method as a stopgap. Returns `true/false` if form validates.

i.e. 
```javascript
if ( $('form').form('is valid') ) {
  // do something
}
```

**Comment by DruidKuma** [comment]
https://github.com/jlukic

Very impressed with such a quick solution. Thank you very much.

**Comment by jlukic** [comment]
The biggest problem with this project is just keeping on top of open issues. Feel free to ping any other threads that need attention.

**Comment by erlando** [comment]
It would be great if there was a way to silently ask a form if it validates *without* all errors popping up. 

Use case: Toggle enabled state on submit on the fly.

Right now a call to form('is valid') gets really messy on an empty form. This is not desirable.

On a sidenote: It would be great if the validation state was reflected on the form the same way it is relected on individual fields via the error-class.

**Comment by avalanche1** [comment]
@erlando +1

**Comment by jlukic** [comment]
So I'm going to set `is valid` to no longer update UI by default. This was a mistake that got codified, and I'm pretty sure no one is expecting `is valid` to behave that way.  See #703 for other changes to these functinos in `2.2.8`

**Comment by jlukic** [comment]
Added in `2.2.8` as described above.
