### ISSUE TITLE
[Card] card isn't getting in dark mode,even when applied `inverted` Class

### ISSUE THREAD

**Issue by i-priyanshu** [Semantic-Org/Semantic-UI#7056]
### Steps
 I applied the `inverted` class, to my card element ,but it is not changing its colour to dark 
### Expected Result
 Card Should have have a dark background.
### Actual Result
  Card is Still having the light default colour.

**Comment by lubber-de** [comment]
`inverted card` is only supported when using the community fork https://github.com/fomantic/Fomantic-UI

https://fomantic-ui.com/views/card.html#inverted

**Comment by i-priyanshu** [comment]
> `inverted card` is only supported when using the community fork https://github.com/fomantic/Fomantic-UI
> 
> https://fomantic-ui.com/views/card.html#inverted

Oh, I see, thanks for clearance.
