### ISSUE TITLE
[Enhancement] Update discord icon

### ISSUE THREAD

**Issue by PadowYT2** [Semantic-Org/Semantic-UI#7066]
The discord logo right now is old, it was changed ~6 months ago, would you mind to update?

**Comment by GammaGames** [comment]
Looks like it was only updated in FA 5.15.4, I wonder if [fomantic/Fomantic-UI](https://github.com/fomantic/Fomantic-UI) would be willing to add this to 2.9.0.

**Comment by lubber-de** [comment]
Fomantic-UI just updated FA to 5.15.4 in the nightly beta by https://github.com/fomantic/Fomantic-UI/pull/2227
