### ISSUE TITLE
[Popup] Setting to hide on scroll

### ISSUE THREAD

**Issue by ElRaph** [Semantic-Org/Semantic-UI#707]
Hi,
maybe i have a little improvement.
I used popups and tried to close them on a page scroll event, cause they are positioned on body and when i scroll, they are still on this position, while they point on wrong data.

When i create them inline, the positioning works, but the page needs nearly 10sec to render all items.
Therefore i thought it would be nice, if u can close them on a scroll event.

Thx for all work on Semantic-Ui! :)
Raph

**Comment by jlukic** [comment]
Added last novemeber
