### ISSUE TITLE
logging jQuery is not defined in source  `semantic.min.js`  (cdnjs)🤔

### ISSUE THREAD

**Issue by ullaskunder3** [Semantic-Org/Semantic-UI#7070]
I was working on react application and just for testing I thought of using semantic.min.js from `cdn`

```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Why ?  It's logging jQuery is not defined in source  `semantic.min.js` 🤔

![image](https://user-images.githubusercontent.com/66258652/145456908-d0122317-5350-4eee-a7b4-452fe4df8321.png)

**Comment by PadowYT2** [comment]
Because, it cannot work **without** jQuery
