### ISSUE TITLE
[Header] Correct terminology is Heading, not Header

### ISSUE THREAD

**Issue by eablokker** [Semantic-Org/Semantic-UI#7077]
Header is the wrong terminology for the header component. These are called "headings" not "headers".

Here is a reference explaining the difference:
https://ell.stackexchange.com/questions/191301/are-header-and-heading-interchangable-in-the-context-of-information-at-the

There are many more examples if you google heading vs header.

**Header**  
The upper portion of a page (or other) layout.  
Information (such as a page number) printed or placed at the top of each page of a document (as opposed to footer).

**Heading**  
The title or topic of a document, article, chapter, or of a section thereof.  
Something that forms or serves as a head especially : an inscription, headline, or title standing at the top or beginning (as of a letter or chapter).

Unfortunately even the CSS class names for headings are called "header". Pretty common mistake as the two words sound the same. But it is quite incorrect to call them headers.

[#597](https://github.com/Semantic-Org/Semantic-UI/issues/5972) <-- Issue opened more than 4 years ago!!! Can't believe this has been ignored for this long!

**Comment by eablokker** [comment]
Nevermind, this repo is dead.

**Comment by lubber-de** [comment]
We started discussing about this for the official community fork Fomantic-UI
https://github.com/fomantic/Fomantic-UI/discussions/2407
