### ISSUE TITLE
Semantic UI is impossible to install through NPM.

### ISSUE THREAD

**Issue by s1nistr4** [Semantic-Org/Semantic-UI#7088]
Semantic UI is impossible to install through NPM. I've tried:
`
npm init -y;
sudo npm install -g gulp;
npm install semantic-ui;
`
The problem isn't necessarily an issue with semantic-ui, the reason for this error is that Gulp is shipping broken on later versions of Node, the package hasn't been updated in 3 years and overall you probably switch to something else or just not use it entirely.

**Comment by lubber-de** [comment]
Try the official and actively maintained community fork https://github.com/fomantic/Fomantic-UI which uses gulp 4

**Comment by jlukic** [comment]
This should be resolved with `2.5.0`
