### ISSUE TITLE
Dark mode for comment component

### ISSUE THREAD

**Issue by jim-king-2000** [Semantic-Org/Semantic-UI#7127]
When I render [`comment`](https://semantic-ui.com/views/comment.html) component on dark background, all the text is invisible since the color of the text is the same as the one of the background. Is there any dark mode for `comment` component?

**Comment by GammaGames** [comment]
The community fork added an inverted variation back in 2018: https://fomantic-ui.com/views/comment.html#inverted

![image](https://github.com/Semantic-Org/Semantic-UI/assets/7832163/713c4ce9-2d35-47b8-8a90-c3a2a8ef33c6)
