### ISSUE TITLE
Korean cannot be changed on the main screen

### ISSUE THREAD

**Issue by ggnu11** [Semantic-Org/Semantic-UI#7151]
Changing your language to Korean doesn't apply to the screen. Other languages work well, but only Korean doesn't

chrome

https://github.com/user-attachments/assets/d6722d8c-1002-4589-b4c2-a337d1bdf896

**Comment by jlukic** [comment]
Sorry this took a while to fix. It was a typo the language is `ko` not `kr` 

Fix should be live now
![{39FAF5C3-AC53-421A-82F7-ACFA17CE7D49}](https://github.com/user-attachments/assets/209f3b8b-1231-4301-9629-e1152890ff5c)
