### ISSUE TITLE
[Checkbox] - Disable checkbox activation on link click

### ISSUE THREAD

**Issue by philrykoff** [Semantic-Org/Semantic-UI#717]
Hello all,

when initiating a checkbox via JavaScript, it may be inadvertently checked when clicking on a link which is contained within the table as this click is being recognized as a click on the label.

The JavaScript need not to act on clicks of child elements of the label, otherwise the following situation may occur:
- User visits a site where he needs to accept terms and conditions
- Actual terms and conditions are being linked from within the label of the checkbox to accept said terms and conditions
- User want's to read said terms and conditions and by clicking on the link contained in the label, checks the checkbox although he not willfully accepted t&c

Workaround: don't use JavaScript version of the checkbox module. _ackbar_ It's a trap! _ackbar_

Please keep legal implications in mind when setting a severity ;-)

Thanks & KR

**Comment by Atulin** [comment]
Any chance of unstaleing this issue?
