### ISSUE TITLE
How to verify name[]

### ISSUE THREAD

**Issue by litaonet** [Semantic-Org/Semantic-UI#728]
```
  <input type="text" name="expand_value[]"  /> 
  <input type="text" name="expand_value[]"  /> 
  <input type="text" name="expand_value[]"  /> 
  <input type="text" name="expand_value[]"  /> 
```

this JQuery append to html
How to verify

**Comment by geemang2000** [comment]
My 2 cents is the validation objects should NOT be 1 to 1 matched with fields. In my app I build a table and the cells are text inputs. I really don't want to have to build new validator objects in for every column. Its seems it'd be really handy to reference a validator using its name in the .form({ reusable: { ...
