### ISSUE TITLE
Not clear how to implement server-side Form validation

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#734]
http://semantic-ui.com/modules/form.html provides behavior for client-side validation, but it's not clear how I am supposed to trigger a server-side validation when the form is submitted, and display an error message if a problem occurs.

I invoked `$("#myForm").form("add errors", ["something went wrong"])` and this added the error to the list of errors, but the error list remains hidden.
1. What callback should I use for triggering the server-side validation (keep in mind it will execute asynchronously)?
2. How do I hide/show the error list?

Please elaborate on this common use-case in the documentation.

**Comment by specimen151** [comment]
Any progress on this?
