### ISSUE TITLE
[Form Validation] Initialize with one settings object, instead of two parameters

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#736]
Form initialization expects the following syntax:

`form(rules, settings)`

It isn't obvious, but if you run: `form(rules).form(settings)` instead, the second call nukes the rules set by the first call.

The documentation should be more explicit about form initialization (to prevent this misunderstanding) or unify rules and settings to avoid this problem altogether.

Perhaps:

```
var myRules = [];
var mySettings = {};

form({
rules: myRules
settings: mySettings
});
```

**Comment by kmd1970** [comment]
Just add Parsley.js as the official form validation for Semantic UI :+1:
