### ISSUE TITLE
Can you resize a textarea?

### ISSUE THREAD

**Issue by dragonfire1119** [Semantic-Org/Semantic-UI#737]
I put rows on there and it doesn't change the size of the textarea? Is there something I'm missing?

**Comment by avalanche1** [comment]
I think @dragonfire1119 meant the initial size of textarea on page load.
Currently there is no way to manually set it's size. It is an issue.

**Comment by avalanche1** [comment]
@dragonfire1119 You can override initial ```textarea``` size with manual CSS
```stylus
textarea
	height: 600px !important
	width: 500px !important

**Comment by jlukic** [comment]
I would always recommend using height over cols.
