### ISSUE TITLE
[Form Validation] Behavior to Set Field as Invalid 

### ISSUE THREAD

**Issue by phillip-haydon** [Semantic-Org/Semantic-UI#752]
Possibly lacking docs on how to do this, but need the ability to mark a single field as invalid.

I.e

``` javascript
$('.ui.form').form('set fieldname', { valid: false, message: 'username is taken' });
```

This is so validation outside of the form behaviour can be done. 

Woops... Just realised I raised this like 5 months ago already... #224

**Comment by oniisaki** [comment]
Found a workaround that could be used until there is an official fix. Utilizes JQuery and semantic UI CSS classes.
```javascript
$(window).load(function (){
	var form = $(".ui.form");
	var fieldname = "username"
	form.addClass("error");
	form.find(":input[name='"+fieldname+"']").closest( ".field" ).addClass("error");
	form.form("add errors", [ 'Unexpected error with server-side validation' ]);
});
```

**Comment by avalanche1** [comment]
@oniisaki , a pity it doesnt work wit inline validation :frowning:
