### ISSUE TITLE
[Menu] Left Vertical Pointing Menu

### ISSUE THREAD

**Issue by cloud-walker** [Semantic-Org/Semantic-UI#775]
Default vertical pointing menus are actually pointing to the right, I think it would be great to have the left counterpart!

Like this:

``` html
<div class="ui vertical left pointing menu"></div>
<div class="ui vertical right pointing menu"></div>
```

with default to right:

``` html
<div class="ui vertical pointing menu"></div>
```

cheers!

**Comment by uyab** [comment]
Really waiting for this :+1:

**Comment by jlukic** [comment]
Right tabular menus are available in `2.1` which should be coming shortly. Do not have `right pointing menu` yet however

**Comment by siddo420** [comment]
Could this also be done for any div tag (and not just a menu)? 

For example: http://semantic-ui.com/collections/message.html divs

**Comment by richardtallent** [comment]
I have a need for this and it doesn't appear to be working in 2.2.6. Vertical menus always point right. They also don't show the pointer if set to fluid, which is kind of a bummer when trying to create a vertical pointing menu in a grid column.

**Comment by richardtallent** [comment]
This fixed it as an override in my CSS, but I'm sure it would need some tweaking to go back into a pull request for the LESS.

```
 .ui.vertical.left.pointing.menu .item:after {
    right: auto;
    left: 0;
    -webkit-transform: translateX(-50%) translateY(-50%) rotate(45deg);
    transform: translateX(-50%) translateY(-50%) rotate(45deg);
    margin: 0 0 0 -.5px;
    border: none;
    border-bottom: 1px solid #D4D4D5;
    border-left: 1px solid #D4D4D5;
}
```
