### ISSUE TITLE
Modal: Bad position on second show #2

### ISSUE THREAD

**Issue by FrostBy** [Semantic-Org/Semantic-UI#776]
Bug #614 is still reproduced.
Windows 8
FF 28.0
jQuery 2.0.2
demo: https://docs.google.com/file/d/0B19STWBC891DWEJXd2ZWeGxFY0E
but when the document or window size is changed, margin of the modal is fixed

**Comment by niceguy61** [comment]
this is same for me.
Windows 10, FF 55.0.2883.87 m
jQuery 2.0.2
