### ISSUE TITLE
form Checkbox value is always 'on'

### ISSUE THREAD

**Issue by saidelimam** [Semantic-Org/Semantic-UI#778]
I'm trying to access a checkbox value to send over a form pos request like this:

var rememberme = $('.ui.Login.form').form('get field', 'lg_rememberme').val();

But the value I get is always 'on' whatever the checkbox state is!
Is there a special way to get its checked value ?

**Comment by danielk1260** [comment]
@Anachron i see your fiddle and i like the code, i have a question about.
it's possible interact with this code for adding a spot to progress bar when click on checkbox?

**Comment by Anachron** [comment]
Sure that's possible. I wont make your homework though. :)

**Comment by danielk1260** [comment]
i need a some codes anachron, you interested for cash? paypal ready

**Comment by ricardovf** [comment]
I fixed this using:

```
jQuery.fn.api.settings.beforeSend = function(settings) {
    jQuery(this).find('.ui.checkbox input[type=checkbox]').each(function() {
        settings.data[jQuery(this).prop('name')] = jQuery(this).prop('checked');
    });

    return settings;
};
```
