### ISSUE TITLE
Accordion in menu allow multiple sections to be open at the same time

### ISSUE THREAD

**Issue by 29x10** [Semantic-Org/Semantic-UI#791]
How to allow only one section to be open at the same time?

**Comment by adamcollingburn** [comment]
Hi, was this ever fixed?

**Comment by tfrere** [comment]
Apparently not, i still have the same issue

**Comment by sam016** [comment]
I am also facing the same issue. `Exclusive` is not working for accordion menu.

**Comment by douglasg14b** [comment]
Same issue here, exclusive doesn't seem to be working as expected :|

**Comment by Banandrew** [comment]
`exclusive` is `true` by default, and I couldn’t reproduce the bug in a JSFiddle. Can someone please fork [this fiddle](http://jsfiddle.net/efp8z6Ln) and see if you can create a test case?

**Comment by esdot** [comment]
Looks like this is working now: [demo](https://jsfiddle.net/nb6LL8gc/)
