### ISSUE TITLE
support button element within "ui action" components

### ISSUE THREAD

**Issue by jhudson8** [Semantic-Org/Semantic-UI#793]
Below is not rendered correctly (notice the ```button``` element)
```
<div class="ui action input">
  <input name="text" type="text">
  <button class="ui button">Search</button>
</div>
```
Compared with the following which is rendered correctly (using the ```div``` element)
```
<div class="ui action input">
  <input name="text" type="text">
  <div class="ui button">Search</div>
</div>
```

**Comment by jlukic** [comment]
Looks like this one finally lands. `<button>` actually supports flex-box quite well.

**Comment by Enelar** [comment]
Cool stuff. I will check it with input.action, and few other things, and report.

**Comment by Enelar** [comment]
Let me rise that question once more. Why `button` is not synonym to `.button`?
At least, for example why `.ui > button` not?

**Comment by Enelar** [comment]
I checked every documented input.action case. Everything fine.
Firefox, Chrome.

**Comment by jlukic** [comment]
I'm glad to know. Thanks for double checking
