### ISSUE TITLE
Double Confirm

### ISSUE THREAD

**Issue by codename-** [Semantic-Org/Semantic-UI#818]
Maybe semantic-ui could provide similar behaviour to buttons like this plugin: https://github.com/stefanocudini/bootstrap-confirm-button

This could be very useful UX module for use with administration panels or applications with functionality similar to "iOS App Store' installation of apps, allowing for confirmation without 'dummy modals' system.

**Comment by jlukic** [comment]
I don't think this will be roadmapped. The solve is very particular.
