### ISSUE TITLE
[Modal] Attempt to focus on the first visible input when a modal is shown

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#824]
Forms are commonly shown within modals. Having the modal plugin search for the first visible input and focusing on it if it is found would be very convenient. To prevent breaking usability, it should store the current document.activeElement just before the modal is shown and restore focus to it when the modal closes.

**Comment by varemenos** [comment]
There should be a way to disable this feature, not everyone wants their form to be submitted accidentally

**Comment by jlukic** [comment]
Sure

**Comment by ShimShamSam** [comment]
@varemenos In my PR for this feature, I added a setting called "autofocus" that you could set to false in order to disable it. I'm not sure if it transitioned into the newer releases, since I don't see it in the docs anymore.

**Comment by abernix** [comment]
:+1:

**Comment by abernix** [comment]
Actually, @varemenos, this already works perfectly with autofocus: false.  However, it is not in the docs currently.

**Comment by varemenos** [comment]
> However, it is not in the docs currently

If it's not in the docs, it's not accessible...

I sound like an asshole but please understand my reasoning.

**Comment by abernix** [comment]
Perfectly reasonable.  Just letting you know what I found.  I ran into the same problem but checked the code and found it when I saw @ShimShamSam's reply.

Regardless, I already submitted a pull-request fix for the docs, Semantic-Org/Semantic-UI-Docs#34 - should be fixed soon.

**Comment by abernix** [comment]
Pull request was accepted and is now live.  This is now in the docs.

**Comment by varemenos** [comment]
:+1: Thanks @abernix
