### ISSUE TITLE
[Segment] Add Corner Floated Icons

### ISSUE THREAD

**Issue by markibanez** [Semantic-Org/Semantic-UI#831]
I manually added a close/delete button to the segment. Could be useful to add this.
![close or delete button on segment element](https://cloud.githubusercontent.com/assets/7534847/2929253/3498ddd4-d787-11e3-81b2-c0148f97cbd5.png)

**Comment by jlukic** [comment]
Corner labels work in segments. I think this is the closest we'll offer
