### ISSUE TITLE
modal close automatically after pressing action buttons

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#834]
I am using Angular js with semantic ui modal, but when I add an ng-click event to it, the alert trigger automatically, but the modal close soon.

anyway to solve it? Thanks!

**Comment by will123195** [comment]
That didn't work for me but this did:

```js
$('.modal').modal({
  onApprove: function () {
    return false
  }
})
```

**Comment by MrOutput** [comment]
you can edit what actions do to the modal in the settings object.

**Comment by LiesbethW** [comment]
This problem still occurs for me. @MrOutput could you elaborate what you mean with the settings object?
