### ISSUE TITLE
How to unbind form validation dynamically？

### ISSUE THREAD

**Issue by chinalu** [Semantic-Org/Semantic-UI#837]
I bind validation as  $('.f1').form(some_rules, {}), then I want to change validate rules.
How to unbind old rules and use new rules?

**Comment by Maxvien** [comment]
@jlukic Thanks you so much! My problem too :smiley:

**Comment by davidzd** [comment]
this is for 'destroy' the rules but how to bind new rules after that?

**Comment by Banandrew** [comment]
@davidzd Initialize it again.
