### ISSUE TITLE
Incorrect Menu Display on Page Refresh (Chrome only)

### ISSUE THREAD

**Issue by inpariswithyou** [Semantic-Org/Semantic-UI#839]
I've created a simple page with an inverted menu bar across the top (class="ui inverted menu"). Within that, I have a right-aligned secondary menu (class="right menu"). 

Everything looks fine, except when the page loads for the very first time OR upon an F5 refresh, when the right-aligned secondary menu is placed directly beneath the intended location, still right-aligned but below the plane of the menu.

If I click the home link, or any other link on the page, the right-aligned menu fixes itself and looks perfect... but upon another F5 refresh or initial load, the same wrong placement happens.

The code on the pages, both the correct and incorrect one, appears to be the same.

The problem appears ONLY in Chrome (34.0.1847.131 m); Firefox and IE work fine. Here are two pictures:

Right Way:
![sosoright](https://cloud.githubusercontent.com/assets/7589407/2981162/01b7e92c-dc01-11e3-91d6-4e0d1d6ee9ad.jpg)

Not Right Way:
![wrong](https://cloud.githubusercontent.com/assets/7589407/2981161/01b7dc3e-dc01-11e3-8bd7-7b7637d440c7.jpg)

**Comment by mutil** [comment]
I can confirm this bug with chromium 39. In my case, it is happening only after login in a meteor app. Unfortunately, for this reason, I cannot reproduce it in a jsfiddle.
Pretty nasty bug I must say, and the workaround mentioned above, doesn't work for me.

**Comment by ssolida** [comment]
Same bug in my case (Chrome 40.0), but @iBotPeaches 's solution fixes the issue !

**Comment by ssolida** [comment]
problem occurs whenever there is a floating item in the right menu ... if I remove the "floating" class, the problem is resolved
![capture d ecran 2015-02-06 a 11 07 19](https://cloud.githubusercontent.com/assets/3765515/6077563/8f5353ae-adf0-11e4-970e-3ff3d3636a84.png)

**Comment by jlukic** [comment]
If there's some new evidence I'll re-open

**Comment by clagace** [comment]
@iBotPeaches' hack did save my day, even if this is 2017. Thanks a lot !
