### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#845]
Please add the ability to use semantic-ui with a private instance of JQuery as discussed at http://requirejs.org/docs/jquery.html#noconflictmap

**Comment by hipertracker** [comment]
@jlukic you can use [jspm](http://jspm.io/) (IMHO, better than AMD/UMD) with my fork of [react-semantify](https://github.com/hipertracker/react-semantify). It works in the browser out of box without any gulp/grunt/broccoli procesing.

**Comment by tanrax** [comment]
Don't UMD support?
