### ISSUE TITLE
Multi Select

### ISSUE THREAD

**Issue by lstrzelecki** [Semantic-Org/Semantic-UI#847]
It would be nice to have something which is called 'select2'. Please check this out: http://t0m.github.io/select2-bootstrap-css/3.4.1.html

Especially: Select2 multi select

**Comment by geemang2000** [comment]
I'm curious if this is still alive? I'm all in on SUI. I need a multiselect for my UI.  

I like http://brianreavis.github.io/selectize.js/ . I might use this for now. The challenge with non-SUI components is the normal styles and the validation / error styling do not matchup well.

**Comment by jlukic** [comment]
I would recommend using Selectize for now. It will still be a while.

**Comment by geemang2000** [comment]
Thanks @jlukic  If this helps anyone I'm using https://github.com/machineboy2045/angular-selectize

**Comment by RyanThompson** [comment]
Hi @jlukic - what is your timeline guesstimate here? I am using this UI on a very large open source project and love it. But the multi-select feature is really killing me. If your delivery guesstimate is waaaay off.. would you consider sharing plans / outlines / requirements, if you have any, with me? I would be happy to contribute the feature.

The project is https://github.com/pyrocms/pyrocms which is powered with https://github.com/anomalylabs/streams-platform

The plugin, preferably, would power one of our core field types which was powered by select2 but.. kinda like to keep it all in the family when possible: https://github.com/anomalylabs/multiple-field_type

**Comment by jlukic** [comment]
I'm kind of in crunch mode right now, im personally out of money and trying to figure out a way to make the project sustainable. I really do want to address multi-select but fighting the clock. 

I'll see if i can rummage out a day to add..

**Comment by RyanThompson** [comment]
I'd start by making your donate button more pronounced. It was a little hard for me to find ;-)

Let me know if I can help. PS I didn't see anything other than the donations as far as monetization? None of my business but just curious!

Cheers

**Comment by geemang2000** [comment]
This is an incredible body of work. We should help out getting more publicity. I'm donating today.

**Comment by jlukic** [comment]
Thanks for donating, this is actually the largest donation i've ever received (!) :dancer: . 

I'm working on adding multiselect as we speak. I think it will work nicely with `ui label` 

I haven't really had time to step away from code to think about money too much. Its a bad habit which I've been trying to step out of, but there always seem to be other coding demands which make it difficult to dedicate time exclusively to things unrelated to making the project better.

**Comment by RyanThompson** [comment]
You're very welcome - A drop in the worthy pool for a product like this I am sure. But seriously put your donate button in the header lol!

Sounds great regarding the multi-select! Very excited. Ya, I think that's another developer stereotype too for developers who are also running a business lol. I know I've been there in the past. Do you have any ideas on how you could monetize better that you haven't acted on perhaps?

Regarding publicity, theming has always been a little week for PyroCMS. Mostly because it has been historically built by developers and not designers. But that has changed with our 3.0 release and I plan on making the packaged public theme with Semantic UI as well (PS do you have any templates?). The admin theme is already Semantic UI. I think designers will love using the default public theme right out of the box which should be nice exposure and enticement. Our docs will predominately condone Semantic UI too.

I think having a rockin framework for the public / admin themes and not some custom crap whoever made a long time ago will really encourage designers to check out our theming approach and nudge them your way.

Cheers

**Comment by RyanThompson** [comment]
And yes, `ui label` sounds like an amazing plan. Really you can combine the search select and labels and viola. Im sure it's not that easy ^_^

**Comment by jlukic** [comment]
Thanks again to both of you, and I'll let you know on progress. Beginning asap. 

I'm going to lump multiselect in with the `2.0` release which I'm hoping to use to drive up attention again in the project.

**Comment by geemang2000** [comment]
Awesome! I'm using Sematic for the admin interface of the product we're launching (http://www.icsynergy.com/spgateway/)  Once we launched I'll blog about Semantic-UI too.

**Comment by jlukic** [comment]
![progres](https://dl.dropboxusercontent.com/u/2657007/multiselect.gif)

**Comment by RyanThompson** [comment]
Oh SNAP! Sexeh! Well done sir.

**Comment by geemang2000** [comment]
Awesome!!! Will this allow creating arbitrary entries?

**Comment by jlukic** [comment]
Will support tokenizing and option for adding new choices.

**Comment by geemang2000** [comment]
I'll be first inline to help test this. Nice work! This alone will bring a lot of visibility to your project. Bad *ss multi-select and dropdown don't exist. I've wasted more time than I want to admit on select2, selectize etc.

**Comment by hyperborea** [comment]
This is amazing! I assume it will work along with form validation?

**Comment by jlukic** [comment]
Yes

**Comment by jgod** [comment]
Very slick

**Comment by nickretallack** [comment]
This looks beautiful.  When can I start using it?

**Comment by jlukic** [comment]
I'm staging about 3 weeks of changes into a `2.0` release which will be coming soon.

**Comment by georges** [comment]
This is fantastic.

**Comment by kvetoslavnovak** [comment]
Really great. Thank you very much.

**Comment by anush0247** [comment]
Yes, Its really great.

**Comment by mrmylanman** [comment]
This feature will definitely be appreciated on this end. Glad to see it looks like it's nearing completion.

I made a modest donation to show my appreciation.

**Comment by fntsrlike** [comment]
Awesome!

**Comment by david50407** [comment]
So cool!

**Comment by marcoT89** [comment]
Thanks a lot man! Thats really a awesome feature!!! I can`t whait for this
multiselect element!! Just perfect! Don`t stop!

Em qua, 8 de abr de 2015 às 14:28, David Kuo <notifications@github.com>
escreveu:

**Comment by jlukic** [comment]
Will be releasing beta docs this week for people who want to adopt early

**Comment by kamaroly** [comment]
@jlukic how do you computer those animated form inputs?

**Comment by jlukic** [comment]
Examples of multiselect are now up in beta docs. They are about 90% of the way, still need a few polish adjustments.
http://beta.semantic-ui.com/modules/dropdown.html#multiple-selection

@kamaroly All animations use semantic's transition module. 
http://semantic-ui.com/modules/transition.html

**Comment by mrmylanman** [comment]
I am extremely excited about this. The components look awesome!

**Comment by anush0247** [comment]
I got a problem in a situation

I am having a skills form with some c,java, pythons skills list. first user selected c, java. 
later he wants to update the list to c,python when he is trying that i can't remove the java from the list
selected=selected is not removing for that java option in select list

Inintially multi select comes with selected=selected for the options that are previosly selected in html code but i can't figure it out when we apply .dropdown() to that select its looks like empty selection 

how do i fix this. 

Thank you
apart from this all are working fine

**Comment by jlukic** [comment]
@anush0247 please open a new thread if you want to post a bug, and include a test case. This is not the place to post on that. 

There's a link in readme for JSfiddle with `next` branch.

**Comment by anush0247** [comment]
ok i will report it in a new branch

**Comment by mindbits** [comment]
fantastic work! 

will there also be a version that supports remote calls for large datasets?

**Comment by jlukic** [comment]
We try to stay ambivalent about backend since most frameworks we work with are opinionated on the matter. That being said, any normal way which you grab data works, just initialize dropdown after :)

If you're looking for querying against a remote data set the `search` component was defined with that in mind.

**Comment by avalanche1** [comment]
Hey mate, why don't you monetize like those guy- at least for starters:
http://robomongo.org/backlog

**Comment by mindbits** [comment]
That is actually an awesome idea. 

The search component is not useful for my case and I would donate a nice amount to have some core select2 functionality in the multiselect component including but not limited to remote calls.

**Comment by jlukic** [comment]
I've added more examples of multiselect in beta documentation. I have 1-2 hours more polish then closing up on dev.
http://beta.semantic-ui.com/modules/dropdown.html#/examples

**Comment by avalanche1** [comment]
well, what can I say?
**Outstanding job!**

**Comment by parhelium** [comment]
@jlukic you are doing fantastic job !
Thanks, for your hard work !

I really need to have multiselect in semantic-ui, becuase form validation doesn't work nice with selectize...
How can I boost development of this feature, donation ?
What is your bitcoin address ?

**Comment by khadijesheikhan** [comment]
@jlukic Thanks for your works.
I am a beginner and I do not know how to use the multiple selection,
I downloaded UI Framework from http://beta.semantic-ui.com/modules/dropdown.html#/examples but I still get the same look (not multiple selection).

Could you explain the steps? I might have missed something.

**Comment by jlukic** [comment]
@parhelium This will be part of june 1st `2.0` release. 

Thanks for offering to pitch in. You can find the [donation link](https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=sl35C8_YUwjR7pOucKvGVojWCvtmb044iG_iWHiyqtRD4Sf4wOGjBqlE9VW&dispatch=5885d80a13c0db1f8e263663d3faee8d99e4111b56ef0eae45e68b8988f5b2dd) in the footer of semantic-ui.com

**Comment by amitos80** [comment]
Hi!
got to say i love the simplicity of semantic, makes css work so much easier, thanks!
Is the 2.0 beta available for download?

**Comment by jlukic** [comment]
All set for release next week

**Comment by jlukic** [comment]
Made this gif of keyboard shortcuts with multiselect
![](https://dl.dropboxusercontent.com/u/2657007/multi-shortcuts.gif)

**Comment by avalanche1** [comment]
It would be nice to have a reference of these shortcuts in the docs, I guess

**Comment by rui-infotrack** [comment]
Just wondering about this multiselect: can we have something like this that when there is no result matched, the user can still press enter and add that as a new tag?

**Comment by jlukic** [comment]
@rui-infotrack Thats already available as `allowAdditions` setting

**Comment by geemang2000** [comment]
In the Dropdown examples Mulit-select works as advertised. http://semantic-ui.com/modules/dropdown.html#/examples

However, with a single select the Enter key does not add the element. It'd be great if the single had the same behavior .

**Comment by jlukic** [comment]
It does, check docs.

**Comment by rui-infotrack** [comment]
@jlukic sorry, my bad... should've found it myself. Thank you : )

**Comment by adrianitech** [comment]
Isn't there a possibility to remove the dropdown and have a simple tags input just like in this example: http://formvalidation.io/examples/bootstrap-tagsinput/?

**Comment by dhvsandeep** [comment]
Is it possible to have multiple check boxes instead of options, a select all and unselect all options along? 

On clicking the check box updates the name in select box with name or this many items selected !

**Comment by avalanche1** [comment]
@dhvsandeep this is a tottaly new enchancement for dropdown. Open a separate issue and I'll tag it as enhancement proposal
