### ISSUE TITLE
Column grid issue on Safari

### ISSUE THREAD

**Issue by Woodahs** [Semantic-Org/Semantic-UI#849]
Columns are behaving unproperly on Safari 5.1.7 (on Windows) - i.e. on three column row the third column does not fit in a row and shows below
http://jsfiddle.net/pMDsH/119/
http://imagizer.imageshack.us/a/img834/4239/g9d8u.jpg

**Comment by seizethedave** [comment]
While the proposed solutions did not work for me, finding the `ui grid` containing the affected columns and setting it to `display: block` seems to have fixed it.
