### ISSUE TITLE
[UI] Spinbox Input

### ISSUE THREAD

**Issue by kevinwarren** [Semantic-Org/Semantic-UI#859]
Below is code that would work to get a number spinner working within Semantic UI. Spinner buttons can be given the usual colour classes too. CSS for smaller & bigger input tags would need to be added. Please add to Semantic. :-)

Code based on: http://exacttarget.github.io/fuelux/#spinner

Please see jsfiddle: http://jsfiddle.net/2c9qE/

Ps. I have no idea why but some padding in css is being ignored in jsfiddle making the spinner too wide.

**Comment by geemang2000** [comment]
:+1:

**Comment by jlukic** [comment]
From #1703 
> Spinbox:

> Similar to masked input in that it can only contain numbers and have 2 buttons for increment / decrement. Definable min and max values of course; ability to define a step value (could increment a time value by 15 minutes).

> My favorite thing about most spinbox's ive seen is that it allows you to use your mouse wheel to scroll the value. Not a necessity but it's a pretty neat usability feature.

> Examples
http://getfuelux.com/javascript.html#spinbox
http://jqueryui.com/spinner/#time

**Comment by larsbo** [comment]
:+1: 

I updated @kevinwarren's fiddle to make it work with the current semantic ui version and made the markup a bit more semantic. The new version is here:
http://jsfiddle.net/cqkr7z1h/
