### ISSUE TITLE
onSuccess() fires twice

### ISSUE THREAD

**Issue by iBotPeaches** [Semantic-Org/Semantic-UI#870]
I was trying to track down a problem and realized my requests were going through twice. 

I made a JSFiddle which shows this behavior: http://jsfiddle.net/iBotPeaches/NHxA2/4/

EDIT: I guess adding AJAX into the mix was not needed, onSuccess fires twice regardless: (non-ajax) http://jsfiddle.net/iBotPeaches/Hu32u/2/

0.17 - Semantic
29.0.1547 - Chrome

**Comment by douglasg14b** [comment]
the submit event is also fired twice, which makes for some awkward behavior.

**Comment by ideadx** [comment]
This thing is shit, spend 3hr looking for issue.

**Comment by benjiao** [comment]
> the submit event is also fired twice, which makes for some awkward behavior

I was experiencing this as well. It fires exactly once after replacing the `form` tags with `div` while leaving the class. (eg. `<div id="register-form-0" class="ui form">`).

It seems like Semantic fails to block the form's submit event?

**Comment by benjiao** [comment]
Hello, 

Still experiencing this in version 2.2.6. The form still submits twice. 

Replacing `form` tags with `div` while leaving the classes (`<div id="register-form-0" class="ui form">`) makes the form submit exactly once. Could there be a problem in blocking the original form submit event?

**Comment by qingdi** [comment]
still wrong

**Comment by haiquan** [comment]
Please use $('.ui.form') in the console to check how many elements it can find. If more than one, you should add your custom form class for each form, such as
```HTML
<div class="ui form from-do-xxx">
```

Then use the added custom form class, not the ".ui.form", to write your code.

```Javascript
$(".from-do-xxx").form({
   xxx: yyy
})
```
