### ISSUE TITLE
Popup : Object doesn't support property or method 'easeOutQuint' 

### ISSUE THREAD

**Issue by flessard** [Semantic-Org/Semantic-UI#871]
I go this error under IE9 whit popup ?
This is bug or not ? 
Any have idea to fix this error ? 
Thanks !

**Comment by smeijer** [comment]
At some point in history, this bug has returned. Perhaps want to add the missing animation again?

[The animation defined](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/popup.js#L1135) doesn't match [the animation provided](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/popup.js#L1218)

```js
// Adds easing
$.extend( $.easing, {
  easeOutQuint: function (x, t, b, c, d) {
    return c*((t=t/d-1)*t*t*t*t + 1) + b;
  }
});
```
