### ISSUE TITLE
Clarify meaning of "secondary menu"

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#875]
http://semantic-ui.com/collections/menu.html defines a secondary menu as: `A secondary menu allows for a section of content on a page to be activated`.

I don't understand this explanation. If the menu is supposed to "activate" a section of content on a page, why does nothing happen when I click on the various menu items in the demo?

Please clarify what it means for a menu to "activate" a section of page and how to link the two together. It seems the current demo code is incomplete.

**Comment by gdw2** [comment]
I'd vote to reopen this issue.  I was confused when I read:

```
A secondary menu allows for a section of content on a page to be activated
```

as it implies that this behavior is unique to secondary menus.  I think no description would be better than a confusing one.

**Comment by jlukic** [comment]
The wording is pretty poor. I'll revise

**Comment by jlukic** [comment]
"A menu can adjust its appearance to de-emphasize its contents"

**Comment by jlukic** [comment]
Current revision

**Comment by gdw2** [comment]
Much better IMO.  Thanks.
