### ISSUE TITLE
Tabs : Multiple Data Content

### ISSUE THREAD

**Issue by surtic86** [Semantic-Org/Semantic-UI#884]
Hello,

Is there a Method in Semantic UI to associate more then one Data Container on a Tab?

In Bootstrap you can do this in a easy way but in Semantic this don't work.
~~~~~
data-target="#attacker_research1, #attacker_fleet1"
~~~~~

Here is a Sample Code where i need to have one Menu who can select two Items per Tab.
http://jsfiddle.net/WinstonF/d93af/1/

Thanks for your Help.

**Comment by jlukic** [comment]
Closing, this can be done programatically using `$.tab('change tab', 'foo');`
