### ISSUE TITLE
Support "disabled" property on buttons in line with web standards

### ISSUE THREAD

**Issue by jwarnes** [Semantic-Org/Semantic-UI#898]
Buttons should automatically apply the disabled styling when the disabled property is present, eg 

```
<button class="ui button" disabled>Disabled!</button>
```

This is important because the disabled property is frequently used to control user interactions. Dynamically altering that property with a data-binding library like knockout or angular becomes a hassle because you have to explicitly change the class as well as toggling the property. 

Other UI frameworks such as Foundation and Bootstrap support this by default.

**Comment by SummerWish** [comment]
not fixed

**Comment by jlukic** [comment]
Thanks for the heads-up, was unaware.
