### ISSUE TITLE
[Icon] Allow overlayed icons

### ISSUE THREAD

**Issue by vinz243** [Semantic-Org/Semantic-UI#904]
Hi,
It would be great if it was possible to mix icon using overlays. For example, on an icon we could add a small `+` icon on the top right corner to show an addition.

**Comment by amooz** [comment]
+1, this would really extend how much usage we can get out of these icons.  Some suggestions:
- we should be able to specify the overlay position, such as: "top left overlay icon" or "bottom right overlay icon"
- we should be able to specify independent colours for the overlays such as "red overlay icon" or "secondary overlay icon"

**Comment by tbracken** [comment]
+1 For colorful corner icons, and ability to specify corner location (top right, top left, etc..)
