### ISSUE TITLE
[Form Validation] Add Validation Delay

### ISSUE THREAD

**Issue by cipiripper** [Semantic-Org/Semantic-UI#906]
I am using modal dialog to collect some user-data, and if I make it validate on "blur", and the user focuses the first input field, and wants to cancel without entering any value, he is unable to do so because when mouse down is triggered on "Cancel" HTML element, that triggers "onblur" for the focused field, which displays the inline error, expanding the dialog, and moving the Cancel button away from the mouse cursor. So when user releases the mouse button, "click" doesn't happen on "Cancel" element, and form dialog stays on.

Fiddle: http://jsfiddle.net/cipiripper/6e7P8/

So, it would be great if you could ignore "onblur" vaildation if focused element is used to "Cancel" the dialog, or only do the "onblur" validation if next element being focused is also an input field that will be validated...

**Comment by avalanche1** [comment]
+1
`delay` setting seems to be there, but doesnt seem to work for me. Anyway, it'd be nice to be able to specify delay time.

**Comment by arvi** [comment]
I'm encountering the same thing when I combine this with a modal that has cancel button. Even if action buttons are not within form element, the blur validate field event is being triggered because of the automatic autofocus on the first input element.

Can't seem to figure out how to solve this.
