### ISSUE TITLE
Add UI Sticky Component

### ISSUE THREAD

**Issue by luxlogica** [Semantic-Org/Semantic-UI#930]
It would be wonderful to have an 'affix' behaviour that could be attached to arbitrary elements, like menus and navigation bars, as well as footers, or images. 

To clarify: 'affix' refers to making a movable element stay within the boundaries of the viewport. You may want to 'affix' an element so that if the user scrolls down the page, it sticks to the top of the screen, and doesn't scroll out of view. You may also do the opposite: affix an element - like a 'sticky footer' - to the bottom of the screen. 

The Semantic website itself uses 'affixed' elements extensively: the black menubar at the top of the screen that doesn't move, the immovable tab that opens the left sidebar, and the cat image in the 'transition' page on the docs, that stays within the viewport when you scroll down.

**Comment by jlukic** [comment]
Docs were added previously
