### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by vinz243** [Semantic-Org/Semantic-UI#932]
Is there a plan to support google's material design ? It would make an interesting feature, wouldn't it?

**Comment by CedricDumont** [comment]
Did someone has a work in progress in this area ? regards

**Comment by brigand** [comment]
Two other material design implementations (in React): 
 - http://material-ui.com/#/components/buttons
 - http://sanderspies.github.io/react-material/

JS is used mostly to toggle class names which start animations, and to position things like the ripple on buttons (click on different places on a rectangular button).

**Comment by jlukic** [comment]
The groundwork is in place with theming. It's a bit difficult to visualize all of it together in the current docs (which only support showing themes of the current element). But there's Material themes already for button, modal, and site.

**Comment by dandv** [comment]
Where is the best place to track the progress on the Material Design theme for *all* Semantic elements, collections, views and modules?

**Comment by mikkhait** [comment]
Does it exist yet?

**Comment by jlukic** [comment]
There is no progress on this. If someone wants to contribute a complete Material theme, it would be an easy PR, but keep in mind the bar for design detail for the project is set at a certain level.

**Comment by ChrisOHu** [comment]
Hi guys can also check this one : http://www.material-ui.com/v0.15.0-alpha.2/

**Comment by CloudMunk** [comment]
So where does this stand now, I'm looking at using some Material Degisn UI with semantic in a react project I'm currenty on.
