### ISSUE TITLE
[Table] Create a non responsive variation, or make disable responsiveness by default

### ISSUE THREAD

**Issue by pkaminski** [Semantic-Org/Semantic-UI#947]
Forcing tables to stack on mobile makes it impossible to implement more advanced application-specific width-shrinking techniques while keeping the (very nice) semantic-ui styling.  It would be best if the default `.ui.table` was not responsive and required an extra `.stackable` variant to enable the stacking behavior.  If that's not possible due to backwards compatibility, then a new `.unstackable` variant would be fine too -- I implemented this as a workaround in my project, but it's a pain due to all the `!important` overrides that the media rule brings in.

**Comment by mg98** [comment]
Is there already a better way?
