### ISSUE TITLE
[Form Validation] Add Errors not Working Correctly

### ISSUE THREAD

**Issue by lazlo-bonin** [Semantic-Org/Semantic-UI#959]
According to the [docs on form validation](http://semantic-ui.com/modules/form.html), I can add errors manually:

> add errors(errors) |  Adds errors to form, given an array errors

(I want to use this feature because I submit my form via AJAX, do server-side validation, then want to display the results.)

I tried the following code:

```
$('#my-form').form("add errors", [ 'error' ]);
$('#my-form').form("validate form");
```

I get this contradictory output from the console when calling the above methods, and the form validates as successful when it obviously shouldn't.

![enter image description here](http://i.stack.imgur.com/UFmww.png)

Unless I'm doing something wrong?

As a side note, as the documentation is far from clear, in the array of errors, (how) can I link an error to a field name?

**Comment by orlaqp** [comment]
Hi there! Any progress on this issue?

**Comment by avalanche1** [comment]
I've dug up this api from source to manually show inline errors:
`$('.form').form('add').prompt('fieldname' (from name attribute),'error text')`

**Comment by eyalw** [comment]
@avalanche1 it seems that using your line of code only colors the field with red but does not show the 'error text' in errors list.

However, using
```
$(this.refs.form).form('add errors', {
        email: 'error text',
      });
```

does show the error in the list, but does not color the field

**Comment by specimen151** [comment]
+1

**Comment by timothycoutlakis** [comment]
+1 This is very urgent.  There is no proper documentation on this.  I need to integrate these forms with Angular.

**Comment by avalanche1** [comment]
@eyalw , yep, I only use inline error prompts.

**Comment by bersujamu** [comment]
+1 , this is important feature.
Agree with @timothycoutlakis , this is very urgent.

**Comment by MaxKostenko** [comment]
@avalanche1 
In this way looks better
```javascript
$(this).form('add prompt', 'fieldname', 'error text');
$(this).form('remove prompt', 'fieldname');
```

**Comment by neokio** [comment]
None of the above works for me. But this does:

```javascript
	$('.form').form('add prompt', 'email');
	$('.form .error.message').html('Please enter a valid email address').show();
```

**Comment by power721** [comment]
$('#form').form('add errors', {password: 'Invalid Credentials', email: 'Invalid email'})
$('#form').form('add prompt', 'email')
$('#form').form('add prompt', 'password')

**Comment by neokio** [comment]
a) Unstalification
b) This disfunction is so quirky and commonplace that it should be a BUG, not an enhancement.
