### ISSUE TITLE
[Form] Add Equal Sized Field Variation

### ISSUE THREAD

**Issue by dsignr** [Semantic-Org/Semantic-UI#979]
Hi, I'm using the inline form styling as [described in the docs](http://semantic-ui.com/collections/form.html) and I am able to make something like this:
![screen shot 2014-07-31 at 17 18 37](https://cloud.githubusercontent.com/assets/5097028/3763832/c921f5d2-18a8-11e4-8aa0-d4564634003c.png)

What I'd really like to do is something like this:
![screen shot 2014-07-31 at 17 20 19](https://cloud.githubusercontent.com/assets/5097028/3763839/df94afee-18a8-11e4-9b87-56281c89359e.png)

I tried using 'wide', etc. Still no luck. Any thoughts, or do I have to manually assign a width for the labels as of now? (That's not going to be very DRY, though)

Thanks!

**Comment by dsignr** [comment]
Hey Jack! Any progress in this front? I bumped into this issue again :D

**Comment by kalebdf** [comment]
+1 on solving this without too much more markup

**Comment by jlukic** [comment]
I dont know of anyway to solve this, even with `flexbox` without using `display: table-cell`

**Comment by salarmehr** [comment]
Any news regarding this issue?

**Comment by dsignr** [comment]
@salarmehr I'd recommend for now, you may need to manually set a width for those labels, because I realized if you ignore the elements involved (label, input) this is actually a grid design problem which is why the framework doesn't have straightforward solutions rather than using a grid itself.

**Comment by palashkaria** [comment]
@salarmehr I think using inline-flex and flex-basis should solve this. You'll have to provide a min-width to the label

**Comment by jlukic** [comment]
Can you jsfiddle what you mean @palashkaria 

I haven't seen any reasonable way to do this with `flex` outside of manually specifying a value in `px`, which is content dependent.

**Comment by palashkaria** [comment]
@jlukic You are right about setting a value in px, but I'd prefer this over using grids as it requires no changes to the form markup. 

[Here's](http://jsfiddle.net/palashkaria/Lzwzkmb7/) the fiddle

**Comment by dsignr** [comment]
@palashkaria well, that's pretty neat..atleast, much better than my grid implementation! 👍

**Comment by jlukic** [comment]
That pixel width is based on the text size of the labels, there's no way to set that on a framework level.

**Comment by palashkaria** [comment]
@jlukic 
Again, I agree, but this will just help people [like me] who end up here looking for a site level solution.

At the framework/theme level, I also don't see any way other than table-cells

**Comment by Severec** [comment]
### 

> `_**

1. 

**_`
