### ISSUE TITLE
[Dropdown] Add "Include HTML" option, or modify action to include 'set html'

### ISSUE THREAD

**Issue by DragosMocrii** [Semantic-Org/Semantic-UI#986]
I am using the dropdown to select an image among several options. Images show nice in the dropdown (when the menu is expanded), however when I select one option, the image is not set as the current value. I believe you are using the .text() method to set it, would it be possible to allow using images as menu options?

Thank you

**Comment by ejosvp** [comment]
Hello, there is a way to use preserveHTML with a dropdown generated by a select tag?

I see https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L1562
```js
              return ($choice.data(metadata.text) !== undefined)
                ? $choice.data(metadata.text)
                : (preserveHTML)
                  ? $.trim($choice.html())
                  : $.trim($choice.text())
              ;
```

but, `.html()` of an `<option>` only returns the text without the html tags.
