### ISSUE TITLE
[Module] Should have "exists" method to check whether element is initialized 

### ISSUE THREAD

**Issue by KabluBR** [Semantic-Org/Semantic-UI#988]
The behavior "exists" that is on the module popup should exist in all modules to prevent double triggering. 
I am having some problems in some situations by firing twice some dropdowns and checkboxes.

**Comment by jlukic** [comment]
```javascript
if(methodInvoked) {
  if(instance === undefined) {
    module.initialize();
  }
  module.invoke(query);
}
```

One issue with this is that all components require init before calling a method. `invoke` requires an instance to reflect over.

**Comment by jlukic** [comment]
Dropdown in `2.0` will automatically now return `ui dropdown` for chaining when called on a `select`

In addition any future calls on the original select will operate automatically on the rendered dropdown. This should solve any issues with init on `<select>`
